### ISSUE TITLE
DataProvider with pagination and filters

### ISSUE THREAD

**Issue by ufik** [api-platform/core#1012]
Hello,

I had to specify some where conditions for my ednpoint, so I created my own DataProvider, it works well, but I lost pagination and filtering, is there a way how to just adjust query and leave rest on api platform core?

**Comment by soyuka** [comment]
You have to inject and use our extensions:
- [DataProvider](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L62)
- [Extensions](https://github.com/api-platform/core/tree/master/src/Bridge/Doctrine/Orm/Extension)
- [Injection](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPass.php)

**Comment by ufik** [comment]
Any little example? I don't follow what you mean by use our extensions (only think I can think of is to partialy copy DataProvider - part with

```
foreach ($this->collectionExtensions as $extension) {
            $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName);
```

), but not sure if this is the right way.

**Comment by soyuka** [comment]
Yes, for the filters we use a [`FilterExtension`](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/FilterExtension.php). You'll need at least this one if you want our built-in filters.

**Comment by ufik** [comment]
Any idea how to inject this ```array $collectionExtensions = []``` ?

**Comment by soyuka** [comment]
With a CompilerPass? [see here](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPass.php)

**Comment by Simperfit** [comment]
@ufik is it good for you ?

**Comment by ufik** [comment]
Yeap, thanks.

**Comment by botjaeger** [comment]
> With a CompilerPass? [see here](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/DoctrineQueryExtensionPass.php)

link's broken
