### ISSUE TITLE
Provide an example of custom search filter

### ISSUE THREAD

**Issue by robertosanval** [api-platform/core#1015]
Hello,

I need to do a custom search in an Entity based in a param value, how I could implement that?

The documentation about this point it's very poor https://api-platform.com/docs/core/filters#creating-custom-filters

Thanks

**Comment by Tim59** [comment]
Hello @robertosanval ,

Maybe this can help you : https://github.com/Tim59/api-platform/commit/7ece6dd3fc6e2cc1108e0779bcf16dd882a51999

**Comment by robertosanval** [comment]
Thanks @Tim59 I really appreciate your help!

**Comment by soyuka** [comment]
@Tim59 do you think you can help us improve the docs on this matter? We recently updated it through https://github.com/api-platform/docs/pull/178 but it may not be enough?
Thanks!
