### ISSUE TITLE
[Question] about 409 HTTP status code

### ISSUE THREAD

**Issue by jordscream** [api-platform/core#1016]
Hello,

In my team, we discussed about the HTTP status code 409 ( conflict )

Most of developpers suggest to use it when we have duplicate entry in DBMS

See Amazon: http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/APIError.html
See Stripe: https://stripe.com/docs/api#errors
And others...

Now, in our API platform project, we put a UniqueEntity in our Entity and API platform returns naturally a 400 bad request caused by checking constraint in Entity.

What about dissociate Unique Constraint errors to the others errors to send a 409 HTTP status code when we catch the unique constraint ?

WDYT ? @dunglas @teohhanhui @soyuka

**Comment by dunglas** [comment]
Create a custom validation constraint throwing an exception that you will map to 409?

**Comment by jordscream** [comment]
@dunglas , create a new Exception Class in api platform to catch Unique Constraint with 409 status code will make any sense ?

**Comment by dunglas** [comment]
Yes (IMO).

**Comment by jordscream** [comment]
@dunglas ok will propose soon a PR for this ^^
thanks :-)

**Comment by dunglas** [comment]
After double thinking about it, I'm not sure anymore :) Let's see the PR but not guarantee, it's maybe to specific.

**Comment by magarzon** [comment]
I don't like HTTP 409 error in UniqueConstraint validation violation. According to the specification, 409 error code is:

**Comment by Simperfit** [comment]
This could be contributed in a specific bundle anyway :).

Can we close this ?

**Comment by jordscream** [comment]
@Simperfit Yes
