### ISSUE TITLE
[Question] How to instantiate entity correctly?

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#1019]
If I really need to be sure, that there is no possibility to create some entity with mandatory constructor data - what will be the right way to instantiate it, using api-platform? I have tried to set property via events, and it doesn't work.
```
    public function __construct(JobStatus $status)
    {
        $this->addStatus($status);
    }
```

<img width="1112" alt="2017-03-29 22 44 20" src="https://cloud.githubusercontent.com/assets/3224226/24473256/4a202416-14d1-11e7-92ff-c4bfe5dc362b.png">

**Comment by mitalcoi** [comment]
Update:
I think, this solution is good for me: https://symfony.com/doc/current/components/serializer.html#using-callbacks-to-serialize-properties-with-object-instances

But I don't know how can I get access to serializer behaviour in API-platform

**Comment by Simperfit** [comment]
You may want to use listener to hook before api-platform and to add that status from the JobStatus.

**Comment by mitalcoi** [comment]
@Simperfit can you please provide an example?

**Comment by sroze** [comment]
That's a very weird thing, that I'd consider as a bug. If you have a constructor on your entity... a lot of things go wrong 🤔
