### ISSUE TITLE
Filters logging

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#102]
It would be great to have some tools to ease the development and debug of filters, for starter:
- list all filters
- get which filters are enabled for a given resource
- for a given URI, which filters are applied, output of the DQL query if using Doctrine?
- logs in the profiler with detailed view of which filter is being used, applied and what it has done

I guess it won't be a priority but I still find it worth being mentioned.

**Comment by alanpoulain** [comment]
Has been done in https://github.com/api-platform/core/pull/1865
