### ISSUE TITLE
Q: How to autoretrieve custom relations with custom object?

### ISSUE THREAD

**Issue by insekticid** [api-platform/core#1029]
```
/**
 * Class Project
 * @ApiResource(attributes={"normalization_context"={"groups"={"project"}}})
 */
class Project
{
    /**
     * @ApiProperty(identifier=true)
     * @var int
     */
    protected $id = null;

    /**
     * @Groups({"project"})
     * @var string
     */
    protected $name = null;

    /**
     * @Groups({"project"})
     * @ApiProperty(iri="/project/{id}/detail")
     * @ApiProperty(attributes={"shortname"="project_details"})
     * @var ProjectDetail
     */
    public $detail;
```

```
/**
 *
 * Class ProjectDetails
 * @ApiResource
 */
class ProjectDetail
{
    /**
     * @Groups({"project"})
     * @var double
     */
    protected $GPSLat = null;

    /**
     * @Groups({"project"})
     * @var double
     */
    public $GPSLon = null;

    /**
     * @ApiProperty(identifier=true)
     * @Groups({"project"})
     * @var int
     */
    protected $id = null;
```

How to autoretrieve this:
```
{
  "@context": "/contexts/Project",
  "@id": "/project/48",
  "@type": "Project",
  "Id": 48,
  "Name": "name",
  "detail": {
     GPSLat: '1213',
     GPSLon: '3321'
  }
}
```

**Comment by dunglas** [comment]
It should work if you have the appropriates getters and setters. What output do you get?

**Comment by insekticid** [comment]
detail = null

**Comment by dunglas** [comment]
It looks an hydratration problem. Are you using Doctrine? If yes, can you provide the mapping?

**Comment by insekticid** [comment]
Without doctrine. Like I sad in topic name

**Comment by dunglas** [comment]
Can you post your data provider? If you don't use Doctrine, you must take care of hydrating relations by yourself (or ensure that your ORM or whatever properly do it).

**Comment by insekticid** [comment]
How I can take care of mapping? No documentation exists

**Comment by dunglas** [comment]
Of which mapping? Your custom data provider must return the object, and all its relations must be populated (at least all those needed by the serializer).
Here, the serializer call `$obj->detail`, it is `null`, so it displays `null`. Set `$obj->detail` to something else in your data provider and it should be all good.

**Comment by insekticid** [comment]
I made custom data provider, that gets data from SOAP service.

What I want is:
Create new Entity Class with "return SomeClass" annotation and API Platform will automatically gets this data from my DataProvider becaouse of this annotation.

Now I created EmbeddedRelationNormalizer+ new EmbeddedRelation class.

`
    public function normalize($object, $format = null, array $context = array())
    {
        return [
            'test'=> $this->getItemDataProvider()->getItem($object->getUri(), $object->getIdentity(), 'get')
        ];
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof EmbeddedRelation;
    }
`

It will be good, If API Platform can handle this automatically by annotation only

**Comment by dunglas** [comment]
Ok, it's not how API Platform is designed.

Your data provider should return the whole object graph already populated. If you want some sort of lazy loading (as Doctrine do), you should use proxies (I recommend https://github.com/Ocramius/ProxyManager) to play the request to the SOAP server only when needed.
It will be easier to it this way than using custom normalizers.

**Comment by insekticid** [comment]
Thanks for ProxyManager hint. I will look into it

**Comment by Simperfit** [comment]
@insekticid it is ok fo you ?
