### ISSUE TITLE
Filters names conversion

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#103]
As existing filters are based on properties, when using a name converter, it feels odd to have properties and filters named differently.
That's why I'd like to use the name converter for filters too.

The straightforward solution is to inject the name converter, if configured, in each filters (I think we won't inject it in the AbstractFilter, as custom filters might no be based on a property, therefore, might not need conversion). 
Injecting the converter is what we are already doing in [ItemNormalizer](https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php#L71) for instance.

But, another solution came to my mind: 
- Create a new `convertedName` (or any better name) property in [`AttributeMetadata`](https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/AttributeMetadata.php)
- Inject the name converter in the [`AttributeLoader`](https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Loader/AttributeLoader.php) and populate the new property with the converted name using the converter.
- Inject the `ClassMetadataFactory` in AbstractFilter and provide a `getMappingMetadata` method.
- Use those metadata in each filter in order to retrieve the converted name whenever it is needed (documentation and query parameters from request).

The drawback is that we need to maintain both `mappingMetadata` from `ClassMetadataFactory` and doctrine metadata in the current filters. In [such cases](https://github.com/dunglas/DunglasApiBundle/blob/master/Doctrine/Orm/Filter/SearchFilter.php#L122-L131), we need to loop over the `mappingMetadata` to find the matching doctrine property and the proper convertedName.

The benefits are that we won't need to inject the name converter anymore, as the `api.mapping.class_metadata_factory` is used instead. 
For what it is worth, the conversion is also done only once. Custom filters are free to use metadata or not.

Do you see anything wrong with this approach ? Do you have any suggestion ?

**Comment by dunglas** [comment]
I'll think a bit more about that but it looks like a good design.

**Comment by ogizanagi** [comment]
Here what it'll look like using the mentioned strategy for filters: https://github.com/dunglas/DunglasApiBundle/compare/dunglas:master...ogizanagi:filters_names_conversion (see [first commit](https://github.com/dunglas/DunglasApiBundle/commit/aa6905ab5847bf1496513507cb405a4f6ff07f0c))

Second one is about introducing a ClassMetadataRegistry which allows to access and perform search from different metadata "provider" in one point. But I'm not convinced myself, as the interest is pretty limited for now (The same could be achieved by keep injecting both metadata factory in filters, as in the first commit, and add a method to ClassMetadata). Is there any common operations across different metadata providers that will justify it ?

**Comment by Simperfit** [comment]
What is the point on this ? Should it be on 2.1 ?

**Comment by soyuka** [comment]
A discussion is available here: https://github.com/api-platform/core/pull/2377

**Comment by soyuka** [comment]
Duplicate from https://github.com/api-platform/core/issues/2090
