### ISSUE TITLE
Proposition: using annotation for filters

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1033]
Thank you again for your great work !

It would be easier to add a filter in the entity with annotations instead of adding a service.
For example : 
```php
<?php

// src/AppBundle/Entity/Offer.php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;          // for example

/**
 * @ApiResource()
 */
class Offer
{
    /**
     * @ApiFilter('type="search_filter", precision="exact")
     */
    private $id;

    /**
     * @ApiFilter('type="date_filter")
     */
    private $date;

    ...
}

```

The goal here is to simplify the use of filters with Api-Platform, and I think it's important because the great success of Api-Platform is it's simplicity.

**Comment by soyuka** [comment]
I think this is a good idea. We should wait for @api-platform/core-team approval first, but would you ike to work on a PR for this feature?

**Comment by dunglas** [comment]
I like the idea, may I suggest an alternative syntax?

```php
<?php

// src/AppBundle/Entity/Offer.php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;          // for example
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;

/**
 * @ApiResource
 */
class Offer
{
    /**
     * @ApiFilter(SearchFilter::class, strategy="exact")
     */
    private $id;

    /**
     * @ApiFilter(DateFilter::class)
     */
    private $date;

    ...
}
```

I would also allow to add the `@ApiFilter` on the class to enable the filter for all properties.

**Comment by vincentchalamon** [comment]
I would love to see this feature! But we should also think about filters applied to multiple fields (i.e. `search_filter`)

**Comment by dunglas** [comment]
We'll need a bridge with the Symfony DI component:

1. collect all annotations for the same filter in a given class
2. create a service extending the `abstract` one with all properties of this class configured

**Comment by soyuka** [comment]
```
     * @ApiFilter(SearchFilter::class, strategy="exact")
```

This is really neat, it'll help using custom filters too :).

> I would also allow to add the @ApiFilter on the class to enable the filter for all properties.

This might work well on simple filters, or if you  want the same behavior for every properties. I doubt that this would be useful in real case scenarios. 

For example with the `search_filter`:

```php

/**
 * @ApiFilter(SearchFilter::class, strategy="exact")
 */
class Dummy {
  /**
   * @ApiFilter(SearchFilter::class, strategy="partial")
   */
   private $foo;
}
```

This would mean that properties filters override the resource ones? 

What about multiple filters on one property? Would there be multiple annotations? (or `@ApiFilters()`).

Last but not least, on the class if say we put a `date_filter`:

```php

/**
 * @ApiFilter(DateFilter::class, strategy=DateFilter::EXCLUDE_NULL)
 */
class Dummy {
}
```

This should only apply to Dates properties on the given class.

**Comment by sroze** [comment]
I'd love such feature! Happy to prototype it :)

**Comment by dunglas** [comment]
> What about multiple filters on one property? Would there be multiple annotations?

Yes, exactly like for `@Assert` annotations.

**Comment by jordscream** [comment]
cool feature , I can propose something also ^^

**Comment by soyuka** [comment]
Is someone working on this yet?

**Comment by Simperfit** [comment]
Could be on 2.1.0 maybe @soyuka.

I don't think someone has been working on it, if someone want begin it, that could be neat ! @sroze @jordscream

**Comment by soyuka** [comment]
I'll have time this week end for this. Though it may be better to wait for #1099.
