### ISSUE TITLE
Improve doctrine extensions and pagination

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1035]
To avoid all the DQL work on every request we can (and should) actually cache the DQL/SQL (not sure if we can use the QueryCacheImpl but would be better).

Todo:

- [x] improve Should Eager code duplication
- [ ] ~~cache resulting dql or sql~~ 
- [ ] review the pagination helper (#955) because it helps with DX and fixes some edge cases

**Comment by dunglas** [comment]
The generated DQL vary depending the applied filters isn't it? We cannot predict it reliably. And Doctrine already cache the result of the DQL to SQL transformation (if configured properly).

**Comment by soyuka** [comment]
Indeed we can't predict the filters. I'll see how I'll handle the `should eager` part but I'll probably have some optimizations to do there. 
Anyway this is more of a reminder that I need to do this stuff \o/.
