### ISSUE TITLE
Eager Loading Extension does not use dynamic serialization context

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#1039]
I use a custom context builder to enable a resource expansion type feature. However, when looking at the context that the eager loading extension uses, it does not use the dynamic serialization groups I have defined.

Looks like the getSerializerGroups() method in EagerLoadingExtension gets them groups directly from the resource metadata object instead of the context builder.

**Comment by dunglas** [comment]
ping @soyuka

**Comment by soyuka** [comment]
I think that's because the `SerializerContextBuilder` relies on `Request` that I didn't injected it to the extensions. 

Which one of our contexts does handle the so called dynamic serialization group?

**Comment by dunglas** [comment]
We may inject the `request_stack` service and use the `SerializerContextBuilder` only if a request is available?

**Comment by soyuka** [comment]
So it's [this class](https://github.com/api-platform/core/blob/master/src/Serializer/SerializerContextBuilder.php) that handles dynamic serialization?

Yeah 👍  we have to do that because our eager loading will only fetch what needs to be serialized, and those groups are missing.
