### ISSUE TITLE
Introduce a @Depth annotation

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#104]
When serializing trees with groups such as the following, it is convenient to be able to configure the Serialization depth:

```php
class TreeEntry
{
    /**
      * @var TreeEntry
      * @Groups{"a"}
      */
    public $parent;
}
```

A new `@Depth(n)` where N is the maximum depth level to normalize can be useful for such use case. When `n` is reached, the normalizer will output the IRI of the resource instead of embedding it. Proposal:

```php
class TreeEntry
{
    /**
      * @var TreeEntry
      * @Groups{"a"}
      * @Depth(2)
      */
    public $parent;
}
```

**Comment by dunglas** [comment]
Alternative:
* Introduce the Depth annotation directly in the Symfony Serializer component
* Add a handler system similar to the circular reference handler
* Register a custom handler outputting an IRI in the bundle

**Comment by SoboLAN** [comment]
If the depth of the objects is higher than the specified value in `@Depth` annotation, then how will the output look like ?

Also, the next step the Serializer will do after normalizing is encoding. In that case, wouldn't the encoding step fail ?

**Comment by dunglas** [comment]
- In Symfony, it will work like for circular reference: allow to register a `\Callable` as handler, the default callable throw an exception
- The bundle will register a custom handler outputting the IRI of the relation
- Because of the previous, it will the encoding will be OK in the bundle

**Comment by MLKiiwy** [comment]
Really good idea, maybe add also this option in normalization / denormalization context ?

**Comment by felicitus** [comment]
+1 from me. @Depth is pretty much essential for serializing trees.

**Comment by theofidry** [comment]
@dunglas any update regarding this feature?

**Comment by sroze** [comment]
Done in symfony/symfony#17113
