### ISSUE TITLE
Error for custom data provider with entity without ORM

### ISSUE THREAD

**Issue by kate-kate** [api-platform/core#1044]
Hello. I've made custom ItemDataProvider according to [https://api-platform.com/docs/core/data-providers](url). Unfortunately, there is no example for using not ORM entity in docs. So I made the shortest variant, but it always throws an error like 'Parameter  "id" for route "api_campaign_types_get_item" must match "[^/\\.]++" ("" given) to generate a corresponding URL.' when I'm trying to send request like /api/campaign_types/1

Here is the code of my test entity class:
```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * Class CampaignType
 * @ApiResource
 */
class CampaignType
{
    private $id;
    private $type = 'test';

    public function __construct($id)
    {
        $this->id = $id;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getType() {
        return $this->type;
    }
}
```

ItemDataProvider works just like your variant in docs. So, what is the problem?
Also I think, that example class without ORM should be in docs.

**Comment by soyuka** [comment]
You need `@ApiProperty(identifier=true)` on the `id` property :).

**Comment by kate-kate** [comment]
@soyuka Thanks a lot!!!

P.S. But still believe it should be mentioned more explicitly in this part of docs (finally i found it in serialization, maybe it would be more searchable with little separate "Custom entity" section)

**Comment by soyuka** [comment]
@kate-kate may you help us improving the docs on this? https://github.com/api-platform/docs Thanks!
