### ISSUE TITLE
Not supported Method in Symfony 2.8.*

### ISSUE THREAD

**Issue by fedotovaleksandr** [api-platform/core#1045]
Request haven't a method getMimeTypes in  Symfony 2.8.*
/api-platform/core/src/EventListener/AddFormatListener.php

`   61:         $mimeTypes = Request::getMimeTypes($routeFormat);`

Not supported ! 
Please use for Symfony 2.8.* :
`$mimeTypes = [$request->getMimeType($routeFormat)];`

**Comment by magarzon** [comment]
API Platform requires Symfony v3.2, doesn't support 2.8

**Comment by fedotovaleksandr** [comment]
- Improve compatibility with Symfony 2.8

Version 2.0.3

**Comment by fedotovaleksandr** [comment]
https://github.com/api-platform/core/releases/tag/v2.0.3

**Comment by magarzon** [comment]
The "Improve compatibility with Symfony 2.8" that version did was only to use PHP constants instead of JsonResponse constant.
Anyway, I don't know the reason to support 2.8 in the core, and not in the API Platform framework

**Comment by fedotovaleksandr** [comment]
@magarzon  maybe i create PR and You look it up? Simply, all other functions of Api-platform work perfect in 2.8. 2.8 is LTS support version

**Comment by Simperfit** [comment]
@fedotovaleksandr If you could create a PR and we will look that.

**Comment by Simperfit** [comment]
We could be fixing this since we need this methods.

I think you should use version 3.1 of HttpFoundation in order to make this work.

**Comment by aggrosoft** [comment]
I just installed the new beta and it does not work with 2.8 because of a few things in the ApiPlatformExtension and some service definitions. As far as I can see from the composer file the beta still supports symfony 2.8 - is this still valid or do we have to stick with 2.0 when running 2.8 ? Pull requests welcome for 2.8 maintenance?

**Comment by teohhanhui** [comment]
You need a newer version for many of the Symfony components. At that point, staying with 2.8 starts to look like a losing proposal. :smile:

**Comment by aggrosoft** [comment]
Well but 2.8 is the only LTS Version currently, shouldn't it be possible to use a LTS Version with api-platform? 3.4 LTS won't be out until next year and our plans were to use 2.8 until the next LTS comes out.

**Comment by teohhanhui** [comment]
You can stick to API Platform 2.0 :)

**Comment by aggrosoft** [comment]
Ok alright, then my proposal would be to change the composer.json for 2.1 then to exclude symfony 2.8 support.

**Comment by aggrosoft** [comment]
Ok will do, thanks for clearing that out ;)
