### ISSUE TITLE
[Question] Integrate with fos_js_routing? 

### ISSUE THREAD

**Issue by fedotovaleksandr** [api-platform/core#1048]
Hi guys! 
I want integrate with fos_js_routing bundle , for this i must add 'expose' option to route ,for example in traditional way ` @Route("/api/x/x", name="x_x_x", options={"expose"=true}) `
But I use yaml config for configuration api-platform
'My\Entity':
    collectionOperations:
            get:
                method: 'GET'
                options: {expose: true}

How to add 'options' for route,in yaml config?
Thanks!

**Comment by soyuka** [comment]
Operations are only for api-platform related routes. You should use the default routing configuration for this (either `@Route` with annotations or `routing.yml`).

**Comment by teohhanhui** [comment]
I wouldn't recommend using FosJsRoutingBundle... It belongs in the bygone era where the backend and frontend were coupled.
