### ISSUE TITLE
ApiResource annotation of "string|null" throws exception in Doctrine's DocParser

### ISSUE THREAD

**Issue by aldenw** [api-platform/core#1050]
In the api-platform project when setting the "description" property annotation for ApiResources, Doctrine's DocParser class does not recognize the "null|string" syntax and throw an exception.  The ApiResource class currently is 
```php
final class ApiResource
{
    /**
     * @var string
     */
    public $shortName;

    /**
     * @var string|null
     */
    public $description;
```
The \Doctrine\Common\Annotations\DocParser class throws an exception on line 813, after not recognizing the "string|null" notation.   I worked around by removing the "|null".

**Comment by soyuka** [comment]
```
/**
 * @var string
 */ 
public $description = null;
```

**Comment by jon1328** [comment]
Same here. Setting a default value of _null_ as suggested by @soyuka does not change anything.

To reproduce simply set up a new api-platform installation (I did it through composer) and set "description" in AppBundle\Entity\Foo:
```
/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource(description="this is a foo")
 * @ORM\Entity
 */
class Foo
{
```

We're ending up with:
> FileLoaderLoadException in FileLoader.php line 118: [Type Error] Attribute "description" of @ApiResource declared on class AppBundle\Entity\Foo expects a(n) string|null, but got string in .

Which occurs in [Doctrine/Common/Annotations/DocParser.php line 813](https://github.com/doctrine/annotations/blob/v1.4.0/lib/Doctrine/Common/Annotations/DocParser.php#L813)

Where:
```
$type = {array} [3]
 type = "string|null"
 value = "string|null"
 required = false

$values = {array} [1]
 description = "this is a foo"
```

So it looks like Doctrine does not like multiple types in @ var tags.
