### ISSUE TITLE
Metadata factory chain is hard to predict

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1066]
Following use case:
```php
class MyEntity
{

    /**
     * @API\ApiProperty(writable=false)
     * @ORM\Id
     * @ORM\Column(name="id", type="guid")
     * ID gets generated and set in an entity listener
     * GeneratedValue=NONE is implicit and implies isNaturalIdentifier=true in doctrine metadata
     *
     * @var string
     */
    private $id;
}
```

In this case writable=false is completely ignored. That is because the metadata factory from the doctrine bridge sets the "isWritable" always as long as "isIdentifier" wasnt set.

What does work is `@API\ApiProperty(identifier=true, writable=false)`.

Anyway, I would expect that any metadata set in the annotations (or other "first class" metadata sources of api-platform) to take precedence over metadata extracted from thrid party sources.

edit: sad thing is, that any behavioral change to the metadata precedence would cause BC breaks

**Comment by soyuka** [comment]
User-configured metadata should take precedence over other configurations.

WDYT? I'd consider this as a bug.

**Comment by dunglas** [comment]
It's definitely a bug.
