### ISSUE TITLE
[Question] Add exsisting route to Api-platform

### ISSUE THREAD

**Issue by fedotovaleksandr** [api-platform/core#1067]
Hi guys! I have existing route 
(
for example api_ping that return only 200 status 
` @Route("/ping", name="api_ping") `
) . 

How i can add this route to api-platform's docs ?

**Comment by meyerbaptiste** [comment]
You can follow these links:

- https://github.com/api-platform/docs/issues/143#issuecomment-260221717
- https://github.com/api-platform/core/issues/887
- https://github.com/api-platform/api-platform/issues/185
- https://github.com/api-platform/core/pull/886

**Comment by fedotovaleksandr** [comment]
@meyerbaptiste  thanks! But in all Issues, work with Entity and _api_resource_class ,   can i add route to docs without resourse_class?

**Comment by meyerbaptiste** [comment]
I use my joker: ping @Simperfit aka Swagger killer

**Comment by soyuka** [comment]
@fedotovaleksandr I don't see anything in [the code](https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php#L113) the would prevent you from adding a custom operation to the docs. But, I think that any `Operation` needs to be associated to an `@ApiResource` to be detected as one.

**Comment by meyerbaptiste** [comment]
Or you can decorate the `api_platform.swagger.normalizer.documentation` service.

**Comment by backbone87** [comment]
maybe an @ApiOperation would be something useful? this would allow to work operation centric

**Comment by fedotovaleksandr** [comment]
@backbone87 Hi my friend,thanks for reply! I can't find this annotation in ApiPlatform\Core\Annotation\*
it's swagger annotation?

**Comment by soyuka** [comment]
There are no such annotation yet @fedotovaleksandr

**Comment by fedotovaleksandr** [comment]
@soyuka Thanks .

**Comment by raziel057** [comment]
I'm also very interested by this kind of annotation, which could be used to document routes that are not directly related to an entity. Sometimes you need a ping route or aggregation and it would be great to see it in Swagger view.
