### ISSUE TITLE
Any ideas on how we could speed up ResourceClassResolver?

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1068]
[This class](https://github.com/api-platform/core/blob/master/src/Api/ResourceClassResolver.php) gets called a lot. I already speed up things by ~20% by avoiding the `resourceNameCollectionFactory->create()` call (quick & dirty):

```
    public function isResourceClass(string $type): bool
    {
        if (isset($this->arrayCache[$type])) {
            return $this->arrayCache[$type];
        }

        foreach ($this->resourceNameCollectionFactory->create() as $resourceClass) {
            $this->arrayCache[$resourceClass] = true;
            if ($type === $resourceClass) {
                return true;
            }
        }

        $this->arrayCache[$type] = false;
        return false;
    }
```

Though, `getResourceClass` is still slow \o/. I'm not sure that we can find any `key` to cache our `$value` though. 
I think that by removing `try/catch` we could improve it a bit, but this would break a lot of things (returning `null` instead of throwing an `InvalidArgumentException`). WDYT?

Any ideas appreciated!

**Comment by backbone87** [comment]
if the slow part is the custom iterator, than maybe using ResourceMetadataFactoryInterface directly (with a special instance that is configured to "fail fast", if cache didnt hit) could help.

Or extending the ResourceNameCollectionInterface to have a "contains" method.

**Comment by soyuka** [comment]
I think the slow part is [getResourceClass](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Api/ResourceClassResolver.php). Or, it's not that slow but it gets called a lot:  [Blackfire](https://blackfire.io/profiles/f121df89-b193-4268-9ff6-a554420742b2/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main())

**Comment by soyuka** [comment]
Closing this because I'm not sure we can do anything about that. #212

**Comment by bastnic** [comment]
I'm allowing myself to reopen it because `ResourceClassResolver::getResourceClass` is responsible of no less than 13% in prod mode, because foreach entity, it will go through ALL possible resource, without any break in the loop (seems logic) nor any cache. And so, `is_a` is called 63630 times.

Just adding a local cache clear everything:

```php
        if (isset($this->localMostSpecificResourceClassCache[$targetClass])) {
            return $this->localMostSpecificResourceClassCache[$targetClass];
        }

        foreach ($this->resourceNameCollectionFactory->create() as $resourceClassName) {
            if (!is_a($targetClass, $resourceClassName, true)) {
                continue;
            }

            if (null === $mostSpecificResourceClass || is_subclass_of($resourceClassName, $mostSpecificResourceClass)) {
                $mostSpecificResourceClass = $resourceClassName;
            }
        }

        if (null === $mostSpecificResourceClass) {
            throw new \LogicException('Unexpected execution flow.');
        }

        $this->localMostSpecificResourceClassCache[$targetClass] = $mostSpecificResourceClass;
```

Before : 

![image](https://user-images.githubusercontent.com/84887/71133557-2b964e00-21fb-11ea-96e6-d06d50327fee.png)

Diff :

![image](https://user-images.githubusercontent.com/84887/71133590-3ea91e00-21fb-11ea-88da-979a4429f5c5.png)
