### ISSUE TITLE
Hypermedia controls at docs.jsonld 

### ISSUE THREAD

**Issue by cr3a7ure** [api-platform/core#1079]
Parsing the docs.jsonld, which is the Hydra description for the API, there are no links/IRIs that can be resolved in order for an automated client to perform the described operations.

The IRIs used are either local or schema.org based if we use SchemaGenerator.
So there is no information for the client as to where he should GET/POST.

One idea to address this is to change the IRIs of classes to something dereferenceable inside the API,   `/thing` for example and specify `@type: schema:Thing` in order to describe the class.
`/thing` would be similar to `contexts/Thing`.

Another idea is the use of `hydra:Link` and `hydra:TemplatedLink` for collections and instances of a class as an `rdf:Property`. Hydra do specify that both `Link` and `TemplatedLink` have a subClassof `hydra:Resource, rdf:Property`. I'll try to implement it and see where it leads.

I was reading this example [Restbucks_with_Hydra](https://www.w3.org/community/hydra/wiki/Restbucks_with_Hydra), while trying to implement a graph based automated client.

What is your views on this?

**Comment by dunglas** [comment]
Hi @cr3a7ure, I've the same kind of questions. In my opinion, the best idea is to ask the Hydra mailing list: http://www.hydra-cg.com/

**Comment by cr3a7ure** [comment]
Well, it's a good thing that others share my concerns :)
I will try to resolve those things (hydra:search, etc) and I hope I'll comeback with a solution-interpretation.

Thanks Dunglas for your dedication!

**Comment by cr3a7ure** [comment]
I've searched through the Hydra mailing list the past days and have to make some points we should consider. Hydra does not explicitly specify the structure of the document from what I've seen. There is a proposed way from some members, but the closest thing to validation is Hydra Console.

With this in mind, I propose some changes in the api-platform that might address some recurring problems. Some points are just keeping in pace with the spec.
About the others, I will try to implement some of these either way, but opinions are more than welcome in order to be accepted as a pull request in a later time.

1. Replace `hydra:CreateResourceOperation` to `hydra:Operation` .
Since every named operation has changed to the generic `hydra:Operation`.

2. Replace `hydra:PagedCollection` to `hydra:PartialCollectionView` .
`hydra:PagedCollection` is no longer used has changed to `hydra:PartialCollectionView`. I'll refer to it as `hydra:PagedCollection` for the rest of this post. 

3. Allow someone if he wants to express the search patterns inside the `docs.jsonld`.
Search applies to Collections not on Classes. We can search/filter when we `GET` more than one instances. So we could expand `"range": "hydra:PagedCollection"`.

4. There is a problem, with RDF graphs as far as the Collections described in the `docs.jsonld`. When a client requests how to retrieve Collections, there is no @type to link between a Class and a Collection. Although, when returning the Collection, instances/members are `@id:/tests/123, @type:testClass`, specifying their `@type`. Along with the search proposal I would also add a `member:{ @type:/testClass }`.

5. About the above stated question according to IRIs. The `hydra:supportedOperation` we use in Class, applies to the Classes instances and not the Class itself, so my assumptions are wrong. If we want to assign an operation to a given IRI/URL we should use the `hydra:operation` term which refers to the `@id` containing it as property.

6. I believe that we should be able to select whether the schema.org should go as the `@id` of a Class, while keeping the usage of schemaGenerator. This way we can assign a local IRI, rather the absolute schema.org/ClassName. IMHO `@type:[hydra:Class, schema:ClassName]` would be a solution.

Original: 
```
"@id": "#Entrypoint",
      "@type": "hydra:Class",
      "hydra:title": "The API entrypoint",
      "hydra:supportedProperty": [
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "#Entrypoint/thing",
            "@type": "hydra:Link",
            "domain": "#Entrypoint",
            "rdfs:label": "The collection of Thing resources",
            "range": "hydra:PagedCollection",
            "hydra:supportedOperation": [
              {
                "@type": "hydra:Operation",
                "hydra:method": "GET",
                "hydra:title": "Retrieves the collection of Thing resources.",
                "rdfs:label": "Retrieves the collection of Thing resources.",
                "returns": "hydra:PagedCollection"
              }
            ]
          },
          "hydra:title": "The collection of Thing resources",
          "hydra:readable": true,
          "hydra:writable": false
        },
```
Proposed
```
"@id": "#Entrypoint",
      "@type": "hydra:Class",
      "hydra:title": "The API entrypoint",
      "hydra:supportedProperty": [
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "#Entrypoint/thing",
            "@type": "hydra:Link",
            "domain": "#Entrypoint",
            "rdfs:label": "The collection of Thing resources",
            "range": {
              "@id":"#Entrypoint/thing/collection",
             "@type: "hydra:PagedCollection",
   *3*     "hydra:search": {}, // Expand everything here, or use an IRI?
   *4*    "hydra:member":{  "@type": "/testClass" }
            },
            "hydra:supportedOperation": [
              {
                "@type": "hydra:Operation",
                "hydra:method": "GET",
                "hydra:title": "Retrieves the collection of Thing resources.",
                "rdfs:label": "Retrieves the collection of Thing resources.",
                "returns": "#Entrypoint/thing/collection"
              }
            ]
          },
          "hydra:title": "The collection of Thing resources",
          "hydra:readable": true,
          "hydra:writable": false
        },
```

**Comment by Simperfit** [comment]
What could we do here @cr3a7ure do you want to submit a PR ?

**Comment by cr3a7ure** [comment]
I'm working on it. I have to finish a whole system of services based on such changes.
You can have a look here https://github.com/cr3a7ure/core/tree/apires
It's a mess and I need to clean things up and test before submitting a PR.
Well, you can close/hide it for now.
