### ISSUE TITLE
Add a filter to pass dynamic serialization groups in the URL

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#1082]
`http://example.com/books?groups=group1,group2` should add the passed groups to the list of applied groups. The groups configured tru annotations should be preserved or not depending of a configuration flag.

The filter should **not** be Doctrine dependent. It must implement the `FilterInterface` (to appear in the documentation) and decorate the `SerializerContextBuilder` to apply groups.

**Comment by antograssiot** [comment]
I love this feature, we implemented something close to that in our app but we also have a `Group`   entity si wé décider to go with `normalization_groups` as parameter name.

**Comment by teohhanhui** [comment]
I don't like this. This reeks of implementation details being leaked.

**Comment by meyerbaptiste** [comment]
Can be closed.
