### ISSUE TITLE
relation update question

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#1085]
Hi, guys!
I faced with some problems while updating of embedded entities. I'm not sure if it is bug or expected behaviour, but when I send PUT-request with embedded resource also to be updated, it creates new embedded resource instead of updating it. For example, I send PUT req to ```/foos/1```:
```
{
    "parentFieldToUpdate": "parentValueToUpdate",
     "bar": {
          "@id": "/bars/1",
          "fieldToUpdate": "valueToUpdate"
      }
}
```
In response I get:
```
{
    ...
    "parentFieldToUpdate": "parentValueToUpdate",
    "bar":{
         "@id":"/bars/2",
         "fieldToUpdate": "valueToUpdate"
    }
}
```
and also ```/bars/1``` still not updated.

Probably this is expected behaviour, but does it means that we can't modify complex embedded entities per one request?

**Comment by soyuka** [comment]
#321 #990

**Comment by mitalcoi** [comment]
Oh, thx! I missed to add "ld+json" to headers)
