### ISSUE TITLE
@Assert/Valid seem not working for embedded object

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#1086]
I have a property with embedded object (type Address), and in Address country, locality and street are required. It is annotated with @Assert\Valid(). And it is not a relation, just embedded property (but it is saved to another’s model collection). And I can create not valid Address as well. BTW I also have a related Address type property and it is validating well

**Comment by dunglas** [comment]
If it's a bug, it is related to the Symfony Validator. API Platform doesn't do anything specific about embedded objects regarding validation, it just delegates to the Symfony Validator. You should report this problem on the Symfony bug tracker.

**Comment by mitalcoi** [comment]
@dunglas, I'm agree.
But it is strange that there are no any issues about that problem at symfony github...
