### ISSUE TITLE
Serializing Collections without ApiResource leads to memory usage exceeded error

### ISSUE THREAD

**Issue by aggrosoft** [api-platform/core#1119]
I don't know if this is more a symfony/serializer related bug, but when you are using the ApiResource annotation without using any Groups and you have any kind of related entity which is not flagged as ApiResource as well it will just run into a hard to debug "Memory usage exceeded ..." PHP Error.

I just found this out the hard way while integrating the bundle into a few of our entities as a draft, maybe raising some kind of exception or just skipping those objects might be better.

I'm using just the api-platform/core and symfony 2.8 as we are still migrating, maybe it relates to that as well. Symfony Serializer is 3.1.

**Comment by soyuka** [comment]
Can you disable eager loading and try again?

**Comment by aggrosoft** [comment]
Sorry I missed to mention that, I tried disabling eager loading in the config using eager_loading => enabled: false and also eager_loading => force_eager: false but this does not change anything. I also tried it on the entity level but this does not change anything at all.

**Comment by soyuka** [comment]
It changes how the queries are computed. If it doesn't leads to a memory leak that's for the better.

Anyway, the maxDepth should be reached before any memory overhead if that were the case. Let us know how this goes, I don't have any more leads I could give you to debug this :|.

**Comment by aggrosoft** [comment]
I already fixed it by just adding the ApiResource annotation for the related entities. I will just do that and exclude the stuff I don't need using Groups. Maybe this is worth a note in the docs or something so nobody else has to look that up again.
