### ISSUE TITLE
No work with symfony 2.8 in prod mode

### ISSUE THREAD

**Issue by izquierdogalan** [api-platform/core#1121]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: The parent definition "cache.system" defined for definition "api_platform.cache.route_name_resolver" does not exist. in /Users/jonathan/Sites/dapda/projects/salesmaker/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php on line 100

**Comment by teohhanhui** [comment]
This is expected. The `symfony/cache` component required is v3.1 and above.

**Comment by aggrosoft** [comment]
@izquierdogalan you can just install it by using composer:

`composer require symfony/cache`

This will also work for symfony 2.8

**Comment by hugohenrique** [comment]
I have this problem: ``#1 /app/vendor/api-platform/core/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php(59): Symfony\Component\PropertyInfo\PropertyInfoExtractor->getShortDescription('Domain\\Offer\\Of...', 'id', Array)``

**Comment by hugohenrique** [comment]
And too: 
``
Uncaught Exception: Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in . (which is being imported from "/app/app/config/routing.yml"). Make sure there is a loader supporting the "api_platform" type. {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Objects returned by Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in . (which is being imported from \"/app/app/config/routing.yml\"). Make sure there is a loader supporting the \"api_platform\" type. at /app/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:213, Exception(code: 0): Objects returned by Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator::getIterator()```

**Comment by teohhanhui** [comment]
Yes, please check that your Symfony components meet our version requirements.

You may refer to: https://github.com/api-platform/core/blob/ec403298dce13e2bb2208955351b5003a9a9c20e/composer.json#L44-L54

**Comment by teohhanhui** [comment]
@api-platform/core-team We really need a separate `composer.json` for the bundle (how do we enforce it?), because some components are actually required when one wishes to use the bundle :smile:

**Comment by hugohenrique** [comment]
@teohhanhui I'm using the v3.3.0-RC1

**Comment by teohhanhui** [comment]
It's a separate issue then. I see that you've opened api-platform/core#1127

**Comment by Simperfit** [comment]
@izizquierdogalan do you still have an issue ?

**Comment by izquierdogalan** [comment]
Sorry for the delay I solved it by installing the following packages in symfony 2.8:

"symfony/property-info": "3.1",
 "symfony/serializer": "3.1",
"symfony/cache": "^3.2",
"api-platform/core": "2.0.8",
"lexik/jwt-authentication-bundle": "^2.4",
"nelmio/cors-bundle": "^1.5",
"symfony/http-foundation": "3.2.8"

And creating the following services:

services:
    serializer.mapping.cache.apcu:
        class: Doctrine\Common\Cache\ApcuCache

    api_platform.cache.route_name_resolver:
        class: Doctrine\Common\Cache\ApcuCache
        public: false
    api_platform.cache.metadata.resource:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.cache.metadata.property:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.route_name_resolver.cached:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.metadata.resource.name_collection_factory.cached:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.metadata.resource.metadata_factory.cached:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.metadata.property.name_collection_factory.cached:
          class: Doctrine\Common\Cache\ApcuCache
          public: false
    api_platform.metadata.property.metadata_factory.cached:
          class: Doctrine\Common\Cache\ApcuCache
          public: false

With this I have running my api in sf 2.8!!

**Comment by teohhanhui** [comment]
The last part of your fix is wrong. You need to add (at least):

```json
    "symfony/framework-bundle": "^3.1",
```
