### ISSUE TITLE
Swagger documentation throws an error if a PATCH action is defined

### ISSUE THREAD

**Issue by magarzon** [api-platform/core#1122]
Swagger documentation throws an error Method PATCH is not supported if there is PATCH action defined.

The issue is added in this commit: https://github.com/api-platform/core/commit/0333f7c764602c2bf07e8e32363a8f5a36d5ac1f

IMHO PATCH should be allowed even if there is nothing to show in the documentation (like it was until this commit), specially if there are requests to add support to JSON PATCH

**Comment by dunglas** [comment]
Definitely a bug. @soyuka this change should be reverted https://github.com/api-platform/core/commit/0333f7c764602c2bf07e8e32363a8f5a36d5ac1f#diff-32d63273c86a7e4c14c3fa6bb4131194R173 WDYT?

**Comment by Simperfit** [comment]
I agree that this change should be reverted.

**Comment by soyuka** [comment]
I think I asked about this when I added the `RuntimeException` :p. Reverted.
