### ISSUE TITLE
loader_paths only available in "dev-master" version

### ISSUE THREAD

**Issue by hugohenrique** [api-platform/core#1126]
You could launch a new minor version with a feature [loader_paths](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L102-L115)

**Comment by hugohenrique** [comment]
ping @dunglas

**Comment by soyuka** [comment]
If we want to do this we need to backport the feature in 2.0 (not sure we will do this). In the meantime you can use dev-master.

**Comment by hugohenrique** [comment]
I'm already using ``dev-master``

**Comment by hugohenrique** [comment]
But with Symfony v3.3.0-RC1 you have a problem #1127
