### ISSUE TITLE
[Question] Self-referencing nullable

### ISSUE THREAD

**Issue by angelov-todor** [api-platform/core#1142]
I have an entity defined like this:

    <?php
    declare(strict_types=1);
    
    namespace AppBundle\Entity;
    
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\ORM\Mapping as ORM;
    use Symfony\Component\Serializer\Annotation\Groups;
    
    /**
     * Metadata
     *
     * @ORM\Table(name="metadata")
     * @ORM\Entity
     */
    class Metadata
    {
        const TYPE_NUMBER = 'number';
        const TYPE_TEXT = 'text';

        /**
         * @var integer
         *
         * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned"=true})
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="IDENTITY")
         * @Groups({"get_image", "create_image_metadata"})
         */
        protected $id;
    
        /**
         * @var string
         *
         * @ORM\Column(name="name", type="string", length=50, nullable=false)
         * @Groups({"get_image", "create_image_metadata"})
         */
        protected $name;
    
        /**
         * @var string
         *
         * @ORM\Column(name="type", type="string", columnDefinition="ENUM('number', 'text')", nullable=false)
         * @Groups({"get_image", "create_image_metadata"})
         */
        protected $type = self::TYPE_TEXT;
    
        /**
         * @var null|Metadata
         * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Metadata", inversedBy="children")
         * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
         */
        protected $parent;
    
        /**
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\Metadata", mappedBy="parent")
         */
        protected $children;
    }

which is self-referencing.

When I post to the endpoint:

    {name: "test", type: "text", parent: null}

It returns me an error:

    @context:"/contexts/Error"
    @type:"hydra:Error"
    hydra:description:"Expected IRI or nested document for attribute "parent", "NULL" given."
    hydra:title:"An error occurred"

In resouces.yaml I have only `AppBundle\Entity\Metadata: ~`.
The column definition is: `ALTER TABLE metadata ADD parent_id INT UNSIGNED DEFAULT NULL;`

How to define that `parent` is nullable?

**Comment by angelov-todor** [comment]
Somehow removing the `children` relation I was able to post.

**Comment by teohhanhui** [comment]
Did you figure this out? It would be good to share how you solved it.

**Comment by todor-programista** [comment]
It was some weird caching issue. But the app behaved realy strange and I removed cache couple of times.
