### ISSUE TITLE
Swagger example value without groups in annotation

### ISSUE THREAD

**Issue by grachevko** [api-platform/core#1147]
I wrote custom `SerializerContextBuilder` whith add many "default" groups. Like class name in snake_case, {class name}-read/write, etc. 
And then remove normalization/denormalization context from attribute of `ApiResource` annotation.

Groups work fine, but documentation produce "Example value" for POST/PUT with full attributes include readonly.

**Comment by Simperfit** [comment]
Do you still have an issue ?
