### ISSUE TITLE
Register services for autoconfiguration (Symfony 3.3 autowiring)

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#1151]
Using Symfony 3.3 autowiring, it's possible to add tags on services by directories. But if some services in the same directory should have different tags, it's not possible to autowire it properly.

Like EventSubscriberInterface, API Platform should register its services for autoconfiguration. For example with data providers:
```php
$container->registerForAutoconfiguration(ItemDataProviderInterface::class)
            ->addTag('api_platform.item_data_provider');
$container->registerForAutoconfiguration(CollectionDataProviderInterface::class)
            ->addTag('api_platform.collection_data_provider');
```
In your opinion, which interfaces should be autoconfigured?:
- ItemDataProviderInterface: api_platform.item_data_provider
- CollectionDataProviderInterface: api_platform.collection_data_provider
- FilterInterface: api_platform.filter

**Comment by dunglas** [comment]
Excellent idea! Can you open a PR?

**Comment by vincentchalamon** [comment]
@dunglas PR in progress. I just need to know if the interface list is enough or need to be completed

**Comment by dunglas** [comment]
I would also suggest to add:

* `QueryItemExtensionInterface` => `api_platform.doctrine.orm.query_extension.item`
* `QueryCollectionExtensionInterface` => * `api_platform.doctrine.orm.query_extension.collection`

**Comment by dunglas** [comment]
And do you think you'll be able to create a [MVCE](https://stackoverflow.com/help/mcve) without including the secret elements?

**Comment by soyuka** [comment]
thanks @vincentchalamon !
