### ISSUE TITLE
Deprecation in the form of new arguments not handled properly

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#1153]
Bug introduced in #984:

> TypeError: Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter::getClassMetadata() must be of the type string, null given

We must ensure that things work properly even when the new arguments are not provided.

**Comment by soyuka** [comment]
Can you give more stack trace? Not sure where this comes from.

**Comment by teohhanhui** [comment]
https://github.com/api-platform/core/blob/099279098fe8c60a0bc213e3320c9c73649cbd87/src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php#L243

`$resourceClass` could be `null`.
