### ISSUE TITLE
Custom operations and _format content negotiation

### ISSUE THREAD

**Issue by wcoppens** [api-platform/core#1155]
Just wondering, what way could we support the `_format` on custom operations and keep both route types working just as with default CRUD resources?

So a custom route which would work in both cases:
```
GET /api/book/custom
GET /api/book/custom.json
```

Thanks in advance.

**Comment by soyuka** [comment]
By adding the format parameter to your custom operation path?

**Comment by wcoppens** [comment]
True, however in case we do the following:

```
/**
     * @Route(
     *     name="api_books_custom",
     *     path="/api/books/custom.{_format}",
     *     defaults={
     *          "_api_resource_class"=User::class,
     *          "_api_collection_operation_name"="register"
     *     }
     * )
     * @Method("GET")
     */
    public function __invoke($data)
```

The following route will return 404:
```
GET /api/books/custom
```

**Comment by dunglas** [comment]
Add a default value (null for instance) for `_format`.

**Comment by wcoppens** [comment]
@dunglas That did the trick, important note i did try this first (before creating this issue):

```PHP
/**
 * @Route(
 *     name="api_books_custom",
 *     path="/api/books/custom.{_format}",
 *     defaults={
 *          "_format",
 *          "_api_resource_class"=Book::class,
 *          "_api_collection_operation_name"="custom"
 *     }
 * )
 * @Method("GET")
 */
public function __invoke($data)
```

That does not work, the default should definitly be:
`"_format"=null`
