### ISSUE TITLE
[Question] Required Filter and limit filter by user

### ISSUE THREAD

**Issue by klb-rodriguez** [api-platform/core#1163]
Hello.

I recently started to use the Framework, I had been serching in the official documentation and forums a way to defined a required filter each time a client consume the api, or a way of return nothing if any filter is defined in the request, also a way to restrict depending of user (role) wich filter can use.

thanks in advantage.

**Comment by Simperfit** [comment]
There are no built-in mechanism to do that, but you could do it in a listener or in a doctrine extension, this is on my todo list.

**Comment by backbone87** [comment]
i would need the possibility to declare certain filters as required too. do you have any news on this or can you give me a hint to the entrypoint for a custom listener/extension? I am not sure if this should be done within the kernel pipeline or within doctrine extensions. Also i would like that the required filter is reflected in the Swagger spec.

**Comment by wcoppens** [comment]
@Simperfit What kind of exception would be the best to raise inside a event listener or extension to reflect the requirement back to the client?

**Comment by ismail1432** [comment]
https://github.com/api-platform/core/pull/1692 related ?

**Comment by soyuka** [comment]
looks like it thanks @ismail1432
