### ISSUE TITLE
Change Swagger word in favor of OpenAPI

### ISSUE THREAD

**Issue by ismailbaskin** [api-platform/core#1164]

**Comment by Simperfit** [comment]
@ismailbaskin Do you want to make a PR about this ?

**Comment by ismailbaskin** [comment]
@Simperfit Should I change all swagger words (except swagger UI) to Open API?

**Comment by meyerbaptiste** [comment]
LGTM... WDYT @api-platform/core-team?

**Comment by dunglas** [comment]
Not in class names, it would be a BC break 😓.
In UIs it's ok. In docs, I think we should use something like `OpenAPI (previously known as Swagger)` because I'm pretty sure that most people still type "Swagger" in various search engines.

**Comment by ismailbaskin** [comment]
What about `api:swagger:export` command, it will break BC too. So this issue will be closed until new major version, isn't it? @dunglas

**Comment by soyuka** [comment]
We can create a new command but keep this one to avoid breaking IMO.

**Comment by antograssiot** [comment]
Wouldn't it work to just use  `setAliases()` @soyuka ?
http://api.symfony.com/3.1/Symfony/Component/Console/Command/Command.html#method_setAliases

**Comment by soyuka** [comment]
Yes @antograssiot obviously :p

**Comment by Simperfit** [comment]
@ismailbaskin do you want to do it ?

**Comment by mysiar** [comment]
@Simperfit which branch to start on and to which branch this PR should be made ?

**Comment by Simperfit** [comment]
@mysiar master IMHO, since 2.2 does not accept new feature and 2.1/2.0 are bug/security fix only.

**Comment by dunglas** [comment]
Fixed in https://github.com/api-platform/core/pull/2302
