### ISSUE TITLE
Dependency on Symfony 3.3 not specified ?

### ISSUE THREAD

**Issue by tseho** [api-platform/core#1170]
When trying **v2.1.0-beta.1**, there is a missing dependency on symfony/dependency-injection:^3.3 when using the ApiPlatformBundle. It's only specified inside require-dev.

When installing it on symfony/symfony:3.2.9, the package will be installed but the DependencyInjection will produce an error on runtime like this:

`Unable to parse file "/app/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/../Resources/config/filter.xml".`

I had to upgrade to symfony:3.3 and it worked.

Should the requirement be explicit ?

**Comment by meyerbaptiste** [comment]
No, because as you can see it, `symfony/dependency-injection` is used as a bridge inside the core, so it isn't required.

**Comment by tseho** [comment]
@meyerbaptiste Thanks for the response. 

I understand the core/bridge difference, is adding a composer conflict to symfony/dependency-injection:<3.3 an option ?

This, in theory, should not affect standalone projects using core, only full symfony applications using the bundle.

**Comment by meyerbaptiste** [comment]
To sum up the problem, see this comment: https://github.com/api-platform/core/issues/1121#issuecomment-302354562

But yes, `conflict` could be an idea, this should work.

**Comment by dunglas** [comment]
👍 for a `conflict` section.

**Comment by Simperfit** [comment]
@tseho could you submit a PR ?

**Comment by tseho** [comment]
@Simperfit sure.

Do we need to add other conflicts or `symfony/dependency-injection:<3.3` will be enough ?

**Comment by meyerbaptiste** [comment]
IMO, all the others dev dependencies except tests dependencies.

**Comment by Simperfit** [comment]
Like @meyerbaptiste said, we don't want it to be symfony/symfony btw, but only the dev dependencies.

Thanks about that @tseho

**Comment by Nek-** [comment]
This issue can be close @tseho
