### ISSUE TITLE
Add "Api Platform" section in the profiler

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1176]
Hello,

Thanks again for your great work !
I just discovered that EasyAdminBundle adds a section in the debug profiler.

It would be nice to have an Api Platform in the profiler like EasyAdminBundle.
There would be for example the entity, the normalization context, filters used, data provider ...

It's just a little proposition that could help when debugging.

Thank you again !

**Comment by Simperfit** [comment]
Hello @pierre-H,

I guess why not !

It could be nice to have something like that :).

**Comment by soyuka** [comment]
Would be really nice, I already thought about that, mainly for groups debugging. Though, maybe symfony would accept a PR that adds serialization debbugging to the profiler?
