### ISSUE TITLE
Swagger ui 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1177]
We have an issue on the new swagger ui with `identifier` fields. 

First, it's always forced to `integer` and always has the `id` name (even though the id name can be different).

![swager-ui-bug](https://user-images.githubusercontent.com/1321971/27125645-3e01be50-50f5-11e7-9efd-2cf41f73d85e.png)

On the screenshot for example, the resource has a composite identifier. In the old swagger I could send a string `foo=a;bar=b` and it worked. Because there is a client-side validation on `integer` it's not possible anymore :|. 

Same goes for resources that are not identified by an `integer`, field is still client-validating and doesn't send the request.

I'm not sure where it could be fixed (but if it could be fixed by Friday it'd be lovely :p).

ping @ginifizz @Simperfit

**Comment by soyuka** [comment]
Oh and another thing. Every time we want to test we have to:
1. click on try it out
2. then only we can fill the fields

I think that fields should be visible the moment we open a "request" so that we can directly click on `Execute` without having to do 2 manipulations.

**Comment by dunglas** [comment]
For the other thing, I agree but it should be reported to the Swagger team... It's the default behavior of the new version.

**Comment by backbone87** [comment]
big problem when one is using UUIDs as PKs

**Comment by Simperfit** [comment]
@backbone87 could you please create  a new issue describing the problem ?

**Comment by backbone87** [comment]
i dont see why? its exactly the problem @soyuka described in the opening post. you cant use anything but integer IDs with the current sandbox UI. i was just replying to stress that this is a hugh DX problems for ppl using UUIDs.

**Comment by dunglas** [comment]
It's a bug in Swagger UI isn't it? If it's the case it should be fixed upstream.

**Comment by backbone87** [comment]
idk, i just searched for an open issue, because i experienced the problem described in the OP. afaik swagger ui is configured via a swagger/open api config? then maybe the generated config isnt correct?

**Comment by backbone87** [comment]
Ok i have looked into the swagger api spec generated by api platform and this is what i get for a string ID field (UUID).

```json
                    "parameters": [
                        {
                            "name": "id",
                            "in": "path",
                            "required": true,
                            "type": "integer"
                        }
                    ],
```

so this is not an upstream problem

**Comment by dunglas** [comment]
Thanks for investigating and finding the underlying problem. We'll fix that!

**Comment by backbone87** [comment]
Here are the relevant code sections:
https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php#L234
https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php#L308
https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php#L351

in each case the identifier is just forced to a integer with name "id" without taking the resource metadata into consideration

**Comment by backbone87** [comment]
a hint for a workaround until this is fixed:
specify the correct parameter config via swagger_context resource operation param:
```
 *          "get"={
 *              "method"="GET",
 *              "path"="/x/{id}",
 *              "normalization_context"={"groups"={"x_item_output"}},
 *              "swagger_context"={
 *                  "parameters":{
 *                      {
 *                          "name": "id",
 *                          "in": "path",
 *                          "required": true,
 *                          "type": "string",
 *                      },
 *                  },
 *              },
 *          },
```

**Comment by dunglas** [comment]
Can you try this fix https://github.com/api-platform/core/pull/1197 guys?

**Comment by backbone87** [comment]
can be closed

**Comment by edwardselby** [comment]
specifying "swagger_context" helped me.

The docs (https://api-platform.com/docs/core/operations/#creating-custom-operations-and-controllers) shows basics of how to define a custom operation but doesn't really cover swagger documentation (at least i couldn't find anything).

This changes the documentation, as per recommended docs. notice nested "swagger_context":
```
 * @ApiResource(
 *     itemOperations={
 *          "GET",
 *          "special"={
 *              "route_name"="widget_register_by_uuid",
 *              "swagger_context"={
 *                  "parameters"={
 *                      {
 *                          "name" = "uuid",
 *                          "in" = "path",
 *                          "required" = "true",
 *                          "type" = "string"
 *                      }
 *                  }
 *              }
 *          }
 *     },
```

**Comment by Simperfit** [comment]
Could you please open a documentation PR to improve this ?
Le mer. 7 mars 2018 à 18:14, edwardselby <notifications@github.com> a
écrit :
