### ISSUE TITLE
Float rounding on Json

### ISSUE THREAD

**Issue by Tim59** [api-platform/core#1179]
Hello, 

I have a bug with the output of float field in my app : 

My object Foo has a field horizontal_position defined as :
~~~~
* @ORM\Column(type="float", precision=10, scale=2)
~~~~
If i make a post with 
~~~~
{
  "horizontal_position": 0.3
}
~~~~
The output is : 
~~~~
{
  "horizontal_position": 0.29999999999999999
}
~~~~

Additionals infos :
- there is no problem in csv just on json 
- on the function getAttributeValue() the return is good (0.3)
- I'm on psql but it seem to be store good as 0.3

**Comment by soyuka** [comment]
You may want to use `decimal` instead of `float`. I think that the above is a correct behavior and a known issue.

**Comment by Tim59** [comment]
Thank you @soyuka

**Comment by aggrosoft** [comment]
@Tim59 one more addition, if your are going to use decimal be sure that api-platform will return a string instead of a number type in the json response - this is due to how the serializer and doctrine handles this type.
