### ISSUE TITLE
Doctrine filters

### ISSUE THREAD

**Issue by djoos** [api-platform/core#1185]
Hi there,

when implementing a Doctrine filter (eg. [UserAware](http://blog.michaelperrin.fr/2014/12/05/doctrine-filters/)), the results get filtered correctly (hydra:member), however the [paginator's query](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/Paginator.php#L51) doesn't seem to pick up the filter, so the hydra:totalItems and hydra:view are incorrect...

```
    "hydra:member": [],
    "hydra:totalItems": 61,
    "hydra:view": {
        "@id": "/foos?page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/foos?page=1",
        "hydra:last": "/foos?page=6",
        "hydra:next": "/foos?page=2"
    }
```

I'll dig deeper into the issue, but any heads up is appreciated - thanks in advance!

Kind regards,
David

**Comment by soyuka** [comment]
My first though was that [extension priorities](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml) are wrong, but it looks fine (filters are applied before the pagination). To look further you'd need to inspect what's going on [here](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L64). 

Lmk how this turns out. We may want to start with a behat test too see if bug there is.

**Comment by djoos** [comment]
A quick update - after picking this up just now again...

I spotted in the [PartialConnectionViewNormalizer](https://github.com/api-platform/core/blob/b88d975fa152d295ffeed332dab81dd8376722d1/src/Hydra/Serializer/PartialCollectionViewNormalizer.php#L48) that $data looked like:

```
Array
(
    [@context] => /contexts/Project
    [@id] => /projects
    [@type] => hydra:Collection
    [hydra:member] => Array
        (
        )

    [hydra:totalItems] => 61
)
```

So, hydra:member is correct while hydra:totalItems is incorrect.

Digging deeper, I spotted in the [CollectionNormalizer](https://github.com/api-platform/core/blob/b88d975fa152d295ffeed332dab81dd8376722d1/src/Hydra/Serializer/CollectionNormalizer.php#L86) that the `$object->getTotalItems()` differs from `count($object)`: 61 (incorrect) vs. 0 (correct)

The paginator object used to instantiate the [Paginator](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/Paginator.php#L48) carries the issue with it already, as the $paginator->getQuery() doesn't respect the Doctrine filter, so the count($paginator) returns an incorrect (as in: unfiltered) count, causing the issues further downwards.

Not sure yet where the src/Bridge/Doctrine/Orm/Paginator-object gets instantiated, but that'll be my next step.

TBC!

**Comment by djoos** [comment]
The instantiation of the [Paginator](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/Paginator.php) happens in the [PaginationExtension](https://github.com/api-platform/core/blob/a3cf0fb6d128f4126144848dc7c76fa2abb65f67/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php).

The [CollectionDataProvider](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L64) lists the following extensions:
```
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\EagerLoadingExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterEagerLoadingExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\OrderExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\PaginationExtension
```
...so, including the PaginationExtension, which [kicks in](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L68) and whose [getResult-method](https://github.com/api-platform/core/blob/a3cf0fb6d128f4126144848dc7c76fa2abb65f67/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L111-L117) is oblivious to the Doctrine filter.
That brings me back to the [CollectionDataProvider](https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L62) where the query builder is instantiated...

TBC!

**Comment by djoos** [comment]
Some further inspection shows that the DoctrineFilter is executed for pagination purposes *before* my Configurator is called (which sets the annotation reader as well as the field + value to filter upon), hooked up on `kernel.request`. Obviously the filter returns rather than adding the filter query as required data is not set - when I, instead of letting the Configurator do this upon kernel.request, hard-code values in the filter, the pagination is fixed and everything is ok.

So, why is the Doctrine filter called for pagination purposes *before* kernel.request? kernel.request which is [documented](http://api.symfony.com/3.3/Symfony/Component/HttpKernel/KernelEvents.html) as:
"The REQUEST event occurs at the very beginning of request dispatching. This event allows you to create a response for a request before any other code in the framework is executed." #puzzled

**Comment by djoos** [comment]
Aha!

API Platform's [ReadListener](https://github.com/api-platform/core/blob/a409851c3bfaa6b5e36f84a53422d7f0a9ab0fa0/src/EventListener/ReadListener.php) kicks off the ChainCollectionDataProvider > CollectionDataProvider -> PaginationExtension -> Paginator upon kernel.request, [with priority 4](https://github.com/api-platform/core/blob/e3c17c885377d73bb94bd6a728b039080b7d31f7/src/Bridge/Symfony/Bundle/Resources/config/api.xml#L113-L119).

The DoctrineFilter's configurator is also tagged with kernel.request, but without using any priority parameter. So, when using DoctrineFilters you need to make sure to have it kick in prior to the API Platform's ReadListener: I've upped the priority of my filter's "configurator" to > 4 and... voila: the pagination is correct now!

```
    "hydra:member": [],
    "hydra:totalItems": 0,
```
+ "hydra:view" is omitted, as expected.

Hope this helps someone in the future when dealing with DoctrineFilters!

**Comment by Simperfit** [comment]
Thanks for this @djoos do you mind creating a PR on the docs about this ?

**Comment by djoos** [comment]
Sure, no problem!

**Comment by Soullivaneuh** [comment]
Should not this priority be automatically set if not specified?

It would be error-less than a line on the doc, in my opinion.

**Comment by shahzaibm10c** [comment]
Is there a way to completely remove hydra:totalItems from the response? When doing raw query and return result as array of apiResource.
