### ISSUE TITLE
Order filter not working 

### ISSUE THREAD

**Issue by vivekkhurana** [api-platform/core#1186]
I have an entity and created two filters on it, like this

```
delivery.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id:'exact',subscriberId: 'exact' }]
        tags:      [ { name: 'api_platform.filter', id: 'delivery.search' } ]
    delivery.order_filter:
        parent:    'api_platform.doctrine.orm.order_filter'
        arguments: [ { createdAt: { default_direction: 'DESC' } } ]
        tags:      [ { name: 'api_platform.filter', id: 'delivery.order' } ]
```
Then added the filters to the entity like this

```
/**
 * Delivery
 * @ApiResource(attributes={"filters"={"delivery.search","delivery.order"}})
 * @ORM\Entity
 */
class Delivery
{

```

Now if I open the we console I can see the filters for id, subscriberId and order[createdAt] . When I try out the API from swagger console the API works properly. But accessing the API from curl or browser the "order" filter is ignored.

When I try to access the API this is the result that I see in the swagger console

Request URL
http://192.168.0.106/wd-api/web/app.php/deliveries?subscriberId=1

where as the url requested is

http://192.168.0.106/wd-api/web/app.php/deliveries?order[createdAt]=desc&subscriberId=1

So it makes me wonder where the order filter has gone missing?

**Comment by Simperfit** [comment]
I don't quite understand, using the Swagger UI it works ok, but when using the browser it does not ?

**Comment by vivekkhurana** [comment]
Yes, when accessed via browser or curl or any other mode of API call the order filter is ignored but when accessed through swagger UI, the order filter works. 
By accessing through swagger UI I mean filling the value in the parameter text box  and clicking "Try it out" button.

**Comment by soyuka** [comment]
Can you go to "network" in the browser console panel. Then execute the request. Right click on the network line with your request and "copy url" or "copy as curl" and paste that instead.

Some terminal are having issues (different according to shell) with non-escaped special characters (like `[`). If it works in swagger there's no reason that it doesn't elsewhere ^^.
You can also check the symfony profiler to see if parameters are correctly computed.

**Comment by Simperfit** [comment]
Is this ok for you @vivekkhurana ?

**Comment by vivekkhurana** [comment]
Yes wrapping order[createdAt] with encodeURIComponent and then passing the arguments solves the problem. Maybe this can be documented somewhere?

**Comment by Simperfit** [comment]
@vivekkhurana Yeah, why not, maybe we could open a doc PR, could you do it ?
