### ISSUE TITLE
When composite identifier is missing should return 404 instead of 400

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1191]
See https://github.com/api-platform/core/pull/1182/files#r123189130

**Comment by soyuka** [comment]
IMO not a big deal, feel free to reopen ping @teohhanhui @Simperfit

**Comment by teohhanhui** [comment]
IMO returning the wrong HTTP status code *is* a big deal.

**Comment by soyuka** [comment]
Though both are valid:

> One could argue that the url is malformed (hence 400).

**Comment by Simperfit** [comment]
What is the point here @teohhanhui ? I think both are right but 400 feels _righter_

**Comment by teohhanhui** [comment]
If you're talking about the query string, I'd agree that 400 is correct. But here we're talking about a resource that cannot be found, i.e. a resource with this IRI does not exist. It's very obvious that 404 is the only correct status code.
