### ISSUE TITLE
Required property not being respected on deserialization

### ISSUE THREAD

**Issue by themizzi** [api-platform/core#1193]
I have an entity that looks as follows:

```php
class Job
{
    /**
     * @Assert\NotBlank()
     * @var array
     */
    private $data;

    /**
     * @return array
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param array $data
     */
    public function setData(array $data)
    {
        $this->data = $data;
    }
}
```

This is not a doctrine entity and it is routed to a custom action (not important but this is routing this data to amazon sqs, hence the custom action). It gets to the action fine, except it gets there even if I don't specify a "data" element in the POST body.

The ValidatorPropertyMetadataFactory correctly sets the required attribute on the PropertyMetadata class to true due to the NotBlank annotation, but this is never checked on deserialization.

The Symfony AbstractObjectNormalizer doesn't deal with "required" attributes, it only validates attributes that exist in the normalized data. While I don't agree with that behavior, it seems that it is expected behavior since there is no concept of "required" attributes, and therefore likely Symfony core isn't going to change.

Unless I'm missing something, it seems the ItemNormalizer might be a good spot for this.

**Comment by Perf** [comment]
It seems I have similar issue. Validation is not performed on a custom operation.
From User entity ApiResource annotation:
```php
 *     collectionOperations={
 *         "confirmation"={
 *             "method"="POST",
 *             "path"="/users/confirmation",
 *             "controller"=App\Controller\User\Confirmation::class,
 *             "denormalization_context"={"groups"={"Confirmation"}},
 *             "validation_groups"={"vgConfirmation"},
 *             "access_control"="is_anonymous()",
 *             "swagger_context"={"summary"="Confirms user account creation"},
 *         },
```
Field from User entity:
```php
    /**
     * @var string
     * @ORM\Column(type="string", length=64, nullable=true, unique=true)
     * @Assert\NotBlank(groups={"vgConfirmation"})
     * @IsHash(groups={"vgConfirmation"})
     * @Serializer\Groups({"Confirmation"})
     */
    protected $confirmationToken;
```
From Custom Action for /users/confirmation:
```php
    public function __invoke(User $data)
    {
        dump($data);die;

        $user = $this->repository->findOneByConfirmationToken($data->confirmationToken);
        $user->enable();
        $user->resetConfirmation();

        $this->em->flush();

        $this->dispatch(UserEvent::CONFIRMED, new UserEvent($user));
    }
```

So, it doesn't matter what I POST to /users/conformation, I'm always ending on `dump($data);die;`, but before that - User object that was created from request and populated with data from request should be validated. So if I omit `confirmationToken` field in JSON body it should throw an validation Exception, or if it's blank or not passed `IsHash()` custom validator... 
It seems validation is not performed.

**Comment by trsteel88** [comment]
I think it's a flaw that Actions don't automatically validate. My preference is to use actions over subscribers. Subscribers feel hacking. It means you need to depend on specific values being in the request rather than just setting the controller to execute.

I dug into how API Platform validate data and created an ActionValidator:

```php
<?php

namespace App\Api\Validation;

use ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException;
use ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface;
use ApiPlatform\Core\Util\RequestAttributesExtractor;
use Psr\Container\ContainerInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Validator\Validator\ValidatorInterface;

final class ActionValidator
{
    private $validator;

    private $requestStack;

    private $resourceMetadataFactory;

    private $container;

    public function __construct(
        ValidatorInterface $validator,
        RequestStack $requestStack,
        ResourceMetadataFactoryInterface $resourceMetadataFactory,
        ContainerInterface $container
    ) {
        $this->validator = $validator;
        $this->requestStack = $requestStack;
        $this->resourceMetadataFactory = $resourceMetadataFactory;
        $this->container = $container;
    }

    public function validate($data)
    {
        $request = $this->requestStack->getMasterRequest();

        if (
            $request->isMethodSafe(false)
            || $request->isMethod('DELETE')
            || !($attributes = RequestAttributesExtractor::extractAttributes($request))
            || !$attributes['receive']
        ) {
            return;
        }

        $resourceMetadata = $this->resourceMetadataFactory->create($attributes['resource_class']);

        $validationGroups = $resourceMetadata->getOperationAttribute($attributes, 'validation_groups');

        if (!$validationGroups) {
            // Fallback to the resource
            $validationGroups = $resourceMetadata->getAttributes()['validation_groups'] ?? null;
        }

        if (
            $this->container &&
            \is_string($validationGroups) &&
            $this->container->has($validationGroups) &&
            ($service = $this->container->get($validationGroups)) &&
            \is_callable($service)
        ) {
            $validationGroups = $service($data);
        } elseif (\is_callable($validationGroups)) {
            $validationGroups = $validationGroups($data);
        }

        $violations = $this->validator->validate($data, null, (array) $validationGroups);

        if (0 !== \count($violations)) {
            throw new ValidationException($violations);
        }
    }
}
```

Then in each of my Actions I just include the ActionValidator and call the validate method:

```php
<?php

namespace App\Api\Action\User;

...

class ForgotPasswordRequestAction
{
    private $validator;

    private $mailer;

    public function __construct(
        ActionValidator $validator,
        Mailer $mailer
    ) {
        $this->validator = $validator;
        $this->mailer = $mailer;
    }

    public function __invoke(UserForgotPasswordRequest $data)
    {
        $this->validator->validate($data);

        ...send email to user
    }
}
```

The only downside is that RequestAttributesExtractor is marked as @internal. Would be great if this helper was built into the API Platform at the very least.

The above ActionValidator will use all the relevant validation_groups configured on the relevant API endpoint.

**Comment by trsteel88** [comment]
@dunglas do you think it would be worth adding an ActionValidator service to the core and documenting it?

Is there a reason Actions don't validate by default?

**Comment by dunglas** [comment]
It looks like a bug to me. If the Symfony validator component is installed, this listener should always be executed, regardless if it's a built-in or a custom action: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Validator/EventListener/ValidateListener.php

**Comment by dunglas** [comment]
Regarding `required` attributes. It's just a hint for documentation generators. Doing the validation is not the responsibility of the serializer, but of the validator component (that should be triggered, as explained in my previous comment, as long as a validation constraint is set).

**Comment by trsteel88** [comment]
@dunglas The ValidateListener fires onKernelView. It should fire onRequest otherwise it will execute after the logic and the object is returned from the Action.

I'm not sure what the consequences would be if we changed this listener.

**Comment by dunglas** [comment]
It's intended. The validation is done just before the write listener. If you won't to shortcut this, you need to trigger the validator manually in your action (it deserves a doc entry).

**Comment by trsteel88** [comment]
Yeah I thought so. So what I'm thinking is we should have a helper to validate. The service I created above ensures it validates with the correct validation groups. Without it, you would be specifying the group's even though it's in the config already. 

Would it be worth having a validate config on Actions when defining the controller? This way you don't need to manually configure a validator service for each custom action.

**Comment by soyuka** [comment]
Closing, for custom actions maybe that you could add your own listener that does the validation?
