### ISSUE TITLE
[QUESTION] How to save nested relation?

### ISSUE THREAD

**Issue by VeeeneX** [api-platform/core#1195]
For example I have Brand:

```
{
  "id": 0,
  "name": "string",
  "website": "string",
  "keywords": [
    {
      "language": "string",
      "keyword": "string"
    }
  ],
  "translations": [
    {
      "id": 0,
      "language": "string",
      "website": "string",
      "name": "string",
      "description": "string"
    }
  ]
}
```
As you can see I have relations keywords and translations and if I try to save translations with this array:
```
{"translations":{"1":{"language":"en","description":"asf"}},"name":"Asfasf","website":null}
```
I got an error `Nested documents for attribute \u0022translations\u0022 are not allowed. Use IRIs instead.`

**Comment by sroze** [comment]
You will have to create the relation before, and use its URI.

**Comment by VeeeneX** [comment]
@sroze And can be done this in feature by one call?

**Comment by Tim59** [comment]
@VeeeneX for me you need to have the same denormalization groups one the  entities and a relation with cascade persit

**Comment by dunglas** [comment]
@Tim59 indeed, this is a supported use case.

**Comment by VeeeneX** [comment]
Thanks

**Comment by sushrest** [comment]
@sroze How do I use the IRI?
