### ISSUE TITLE
Change /api/docs to api/crud-docs

### ISSUE THREAD

**Issue by lvillarino** [api-platform/core#1196]
Hi:

I want to know how I can change the documentation endpoint from /api/docs to api/crud-docs 

Thanks

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/routing/api.xml

**Comment by Simperfit** [comment]
I think is ok for you @lvillarino, feel free to ping me if still have an issue.

**Comment by lvillarino** [comment]
Solution

Add to the routing.yml this configuration

```
api_doc:
    path:   /dl/docs.{_format}
    defaults: { _api_respond: '1', _controller: 'api_platform.action.documentation', _format: '' }
```
