### ISSUE TITLE
[Question] Context reset randomly on list

### ISSUE THREAD

**Issue by Tim59** [api-platform/core#1200]
Hi, 

I recently discover a bug in my app, when I'm on listing (about 4000 objects) some elements are not serialized with the good groups (it seem the context was reset randomly). I have create a filter for adding infos in a custom context builder. 

When I make a debug I can see the contextBuilder is good initialize but when i'm on normalize my extra infos doesn't exists.

More infos : 
- I have override the ApiNormaliser and the ContextBuilder
- there is no problem in item view
- About 4 contents are on issues on a list of 50

**Comment by Simperfit** [comment]
Could you maybe post more info ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test in order to see.

**Comment by Tim59** [comment]
@Simperfit I try to make that tomorrow, 

For exemple I add $context['fields'] = ['title'] in the ContextBuilder
And in the normaliser $context['fields'] does not exist

**Comment by Tim59** [comment]
@Simperfit after testing, an other code was on conflict with the context initialization. my fault sorry.
