### ISSUE TITLE
Swagger UI Sandbox does not display validation errors

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1204]
If a validation error occurs, when POSTing a resource via Swagger UI, the response is not displayed.
It works with NelmioApiDoc.

**Comment by backbone87** [comment]
Also doesnt work with PUT

**Comment by dunglas** [comment]
Yes it also works with Swagger UI 2. It's a regression in Swagger UI.

**Comment by dunglas** [comment]
It seems to have been fixed: https://github.com/swagger-api/swagger-ui/pull/3076

**Comment by dunglas** [comment]
Can you try if https://github.com/api-platform/core/pull/1205 fixes the problem @backbone87?

**Comment by backbone87** [comment]
@dunglas it does show the error response now, but sadly its not formatted

iirc the best practice was to send pretty printed JSON anyway in APIs? maybe we can change this on the server side?

**Comment by dunglas** [comment]
Pretty printed JSON take more space. IMO it's the responsibility of the client to beautify the JSON. It should be easy to patch Swagger UI.

**Comment by backbone87** [comment]
i am just repeating what a google search for "REST best practices" returns:
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pretty-print-gzip

and i think that this are very sane arguments and statements. it shouldnt be too hard to make it configurable, no?

**Comment by dunglas** [comment]
It's already configurable using the DI component: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Encoder/JsonEncode.php#L26

**Comment by backbone87** [comment]
Didnt know that. Nvm then
