### ISSUE TITLE
Cache key "p@id" contains reserved characters {}()/\\@:

### ISSUE THREAD

**Issue by marcw** [api-platform/core#1213]
When sending a PUT request with this payload to an endpoint managed by api platform, I get the error mentionned in the title. 

<details>
<summary>JSON</summary>
<code><pre>
{
"@id":"/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f",
"@type":"File",
"name":"FlambyTrack2",
"extension":"mp3",
"description":"Foobar",
"createdAt":"2017-05-12T08:47:54+00:00",
"updatedAt":"2017-05-12T08:47:54+00:00",
"owner": {
    "id":"b2559645-3b3a-4693-950a-22341566f96e",
    "createdAt":"2017-05-12T08:47:54+00:00",
    "updatedAt":"2017-06-29T12:46:41+00:00",
    "originId":"b2559645-3b3a-4693-950a-22341566f96e"
},
"id":"/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
}
```

stacktrace: 

```
{
  "@context": "/app_dev.php/api/app_dev.php/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Cache key \"p@id\" contains reserved characters {}()/\\@:",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php",
      "line": 162,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\Cache",
      "short_class": "CacheItem",
      "class": "Symfony\\Component\\Cache\\CacheItem",
      "type": "::",
      "function": "validateKey",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/ArrayTrait.php",
      "line": 45,
      "args": [
        [
          "string",
          "p@id"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Cache\\Adapter",
      "short_class": "ArrayAdapter",
      "class": "Symfony\\Component\\Cache\\Adapter\\ArrayAdapter",
      "type": "->",
      "function": "hasItem",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php",
      "line": 55,
      "args": [
        [
          "string",
          "p@id"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Cache\\Adapter",
      "short_class": "ArrayAdapter",
      "class": "Symfony\\Component\\Cache\\Adapter\\ArrayAdapter",
      "type": "->",
      "function": "getItem",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php",
      "line": 890,
      "args": [
        [
          "string",
          "p@id"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\PropertyAccess",
      "short_class": "PropertyAccessor",
      "class": "Symfony\\Component\\PropertyAccess\\PropertyAccessor",
      "type": "->",
      "function": "getPropertyPath",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php",
      "line": 188,
      "args": [
        [
          "string",
          "@id"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\PropertyAccess",
      "short_class": "PropertyAccessor",
      "class": "Symfony\\Component\\PropertyAccess\\PropertyAccessor",
      "type": "->",
      "function": "setValue",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php",
      "line": 110,
      "args": [
        [
          "object",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "@id"
        ],
        [
          "string",
          "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "ObjectNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer",
      "type": "->",
      "function": "setAttributeValue",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 202,
      "args": [
        [
          "object",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "@id"
        ],
        [
          "string",
          "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "operation_type": [
              "string",
              "item"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ],
            "request_uri": [
              "string",
              "/app_dev.php/api/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "cache_key": [
              "string",
              "92cd7300f8ade49ec6f2cb8a000d8de7"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "AbstractObjectNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php",
      "line": 292,
      "args": [
        [
          "array",
          {
            "@id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "@type": [
              "string",
              "File"
            ],
            "name": [
              "string",
              "FlambyTrack2"
            ],
            "extension": [
              "string",
              "mp3"
            ],
            "description": [
              "string",
              "Foobar"
            ],
            "createdAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "updatedAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "owner": [
              "array",
              {
                "id": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ],
                "createdAt": [
                  "string",
                  "2017-05-12T08:47:54+00:00"
                ],
                "updatedAt": [
                  "string",
                  "2017-06-29T12:46:41+00:00"
                ],
                "originId": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ]
              }
            ],
            "id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ]
          }
        ],
        [
          "string",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "operation_type": [
              "string",
              "item"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ],
            "request_uri": [
              "string",
              "/app_dev.php/api/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "cache_key": [
              "string",
              "92cd7300f8ade49ec6f2cb8a000d8de7"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "denormalizeObject",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php",
      "line": 174,
      "args": [
        [
          "array",
          {
            "@id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "@type": [
              "string",
              "File"
            ],
            "name": [
              "string",
              "FlambyTrack2"
            ],
            "extension": [
              "string",
              "mp3"
            ],
            "description": [
              "string",
              "Foobar"
            ],
            "createdAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "updatedAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "owner": [
              "array",
              {
                "id": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ],
                "createdAt": [
                  "string",
                  "2017-05-12T08:47:54+00:00"
                ],
                "updatedAt": [
                  "string",
                  "2017-06-29T12:46:41+00:00"
                ],
                "originId": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ]
              }
            ],
            "id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ]
          }
        ],
        [
          "string",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "operation_type": [
              "string",
              "item"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ],
            "request_uri": [
              "string",
              "/app_dev.php/api/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "object_to_populate": [
              "object",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "denormalize",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php",
      "line": 132,
      "args": [
        [
          "array",
          {
            "@id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "@type": [
              "string",
              "File"
            ],
            "name": [
              "string",
              "FlambyTrack2"
            ],
            "extension": [
              "string",
              "mp3"
            ],
            "description": [
              "string",
              "Foobar"
            ],
            "createdAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "updatedAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "owner": [
              "array",
              {
                "id": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ],
                "createdAt": [
                  "string",
                  "2017-05-12T08:47:54+00:00"
                ],
                "updatedAt": [
                  "string",
                  "2017-06-29T12:46:41+00:00"
                ],
                "originId": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ]
              }
            ],
            "id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ]
          }
        ],
        [
          "string",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "operation_type": [
              "string",
              "item"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ],
            "request_uri": [
              "string",
              "/app_dev.php/api/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "object_to_populate": [
              "object",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "deserialize",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/api-platform/core/src/EventListener/DeserializeListener.php",
      "line": 69,
      "args": [
        [
          "array",
          {
            "@id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "@type": [
              "string",
              "File"
            ],
            "name": [
              "string",
              "FlambyTrack2"
            ],
            "extension": [
              "string",
              "mp3"
            ],
            "description": [
              "string",
              "Foobar"
            ],
            "createdAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "updatedAt": [
              "string",
              "2017-05-12T08:47:54+00:00"
            ],
            "owner": [
              "array",
              {
                "id": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ],
                "createdAt": [
                  "string",
                  "2017-05-12T08:47:54+00:00"
                ],
                "updatedAt": [
                  "string",
                  "2017-06-29T12:46:41+00:00"
                ],
                "originId": [
                  "string",
                  "b2559645-3b3a-4693-950a-22341566f96e"
                ]
              }
            ],
            "id": [
              "string",
              "/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ]
          }
        ],
        [
          "string",
          "Acme\\Bundle\\FileBundle\\Entity\\File"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "item_operation_name": [
              "string",
              "put"
            ],
            "operation_type": [
              "string",
              "item"
            ],
            "api_allow_update": [
              "boolean",
              true
            ],
            "resource_class": [
              "string",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ],
            "request_uri": [
              "string",
              "/app_dev.php/api/app_dev.php/api/files/0b7eb8a8-5ddd-4eb6-8e1a-399c2a3e336f"
            ],
            "object_to_populate": [
              "object",
              "Acme\\Bundle\\FileBundle\\Entity\\File"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "DeserializeListener",
      "class": "ApiPlatform\\Core\\EventListener\\DeserializeListener",
      "type": "->",
      "function": "onKernelRequest",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php",
      "line": 106,
      "args": [
        [
          "array",
          [
            [
              "object",
              "ApiPlatform\\Core\\EventListener\\DeserializeListener"
            ],
            [
              "string",
              "onKernelRequest"
            ]
          ]
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php",
      "line": 212,
      "args": [
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "doDispatch",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php",
      "line": 44,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php",
      "line": 146,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
      "line": 129,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
      "line": 68,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/Users/marc/work/websites/www.example.com.dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
      "line": 171,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/Users/marc/work/websites/www.example.com.dev/web/app_dev.php",
      "line": 29,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    }
  ]
}
</pre></code></details>

**Comment by dunglas** [comment]
Looks like a Symfony bug. Can you try if https://github.com/symfony/symfony/pull/23156 fix the problem (you can try `symfony/symfony:^3.3@dev`.

**Comment by marcw** [comment]
The issue was caused by the absence of `denormalization_context` configuration in my resource.
