### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by cocciagialla** [api-platform/core#1215]
Hi, 
I have a resource "Match" in relations with 2 Team objects:
```
/**
 * @ApiResource()
 *
 * @ORM\Table(name="match")
 */
class Match {

    /**
     * @var Team
     *
     * @ORM\ManyToOne(targetEntity="Team")
     */
    private $homeTeam;


    /**
     * @var Team
     *
     * @ORM\ManyToOne(targetEntity="Team")
     */
    private $awayTeam;
```

In the Swagger documentation, in the 'Example Value' section of the POST operation, it results in something like this:
```
{
  "homeTeam": "string",
  "awayTeam": "string",
  ...
```

In the 'Model' section:
```
homeTeam:	string *
awayTeam:	string *
```

Why it can't resolve automatically the resource Team and instead set the type to `string`?
How can I get a more detailed documentation?

I tried with both v1.x and the new beta v2 but the problem persist.

Thanks

**Comment by Simperfit** [comment]
Hey @cocciagialla,

Thanks for using API-Platform !

You need to pass an IRI, in order to have the [embedded](https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-relations) items directly in the docs and in the response.

**Comment by cocciagialla** [comment]
@Simperfit thanks for the quick reply and thanks for all the works on Api-Platform. 
Can you please explain what do you exactly mean with "pass an IRI"?

**Comment by soyuka** [comment]
An [IRI](https://www.w3.org/TR/json-ld/#iris) is an Internationalized Resource Identifier. In our context it looks like this: `/api/my_resources/1` for the item `MyResource` having an identifier of `1`.

**Comment by soyuka** [comment]
I think we said all there is to be said, please ping if you have issues.
