### ISSUE TITLE
disallow extra field when denormalization

### ISSUE THREAD

**Issue by IndraGunawan** [api-platform/core#1217]
i think it would be great if api-platform has built in validation to allow/disallow extra fields when user POST / PUT data

so if user submit data that the property does not exist or the property does not include in denormalization context group, it will be throw validation error like Symfony form type http://symfony.com/doc/current/reference/forms/types/form.html#allow-extra-fields

**Comment by backbone87** [comment]
The symfony serializer has an Option to check extra props. though not for missing Attributes, which makes the current PUT more like a PATCH

**Comment by IndraGunawan** [comment]
you're right, but `allow_extra_attributes` context key was introduced in Symfony 3.3. https://symfony.com/doc/current/components/serializer.html#deserializing-an-object and current api-platform not support extra resource attribute key

**Comment by backbone87** [comment]
i also needed required attributes. i solved the problem by using a flag within my model that is initialied to false per default and then set to true, if the setter is called. you can then use a `Callback` validator and a custom method to produce validation errors, if the setter is not called.

its not a beauty but it works.

**Comment by dkarlovi** [comment]
This is more a feature request than a question, basically 
> Support `allow_extra_attributes=false` in API Platform

Is it not?

**Comment by meyerbaptiste** [comment]
`allow_extra_attributes` is supported, I just did the test.

**Comment by dkarlovi** [comment]
@meyerbaptiste Great, can you paste a short sample?

**Comment by dkarlovi** [comment]
`allow_extra_attributes` does indeed work, although the error message could use some work (I guess that should be fixed in Symfony).

But, how to enable it? I just it from a `SerializerContextBuilderInterface`, but it would be cool to be able to enable it from config and override resource metadata.

**Comment by dunglas** [comment]
I agree. Having a global config flag to populate à base normalization and denormalization context would be a nice DX improvement.

Would you mind opening a PR?

**Comment by dkarlovi** [comment]
> Would you mind opening a PR?

I knew somebody would say that. :) But yes, I'll do it. :+1:

**Comment by soyuka** [comment]
> I agree. Having a global config flag to populate à base normalization and denormalization context would be a nice DX improvement.

Coming soon with symfony default context configuration (I hope)

**Comment by maks-rafalko** [comment]
Disallowing extra fields for the whole project:

```php
<?php

declare(strict_types=1);

namespace App\Serializer;

use ApiPlatform\Core\Serializer\SerializerContextBuilderInterface;
use Symfony\Component\HttpFoundation\Request;

final class DisallowExtraAttributesContextBuilder implements SerializerContextBuilderInterface
{
    private SerializerContextBuilderInterface $decorated;

    public function __construct(SerializerContextBuilderInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null): array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);

        if (!$normalization && \in_array($request->getMethod(), ['PUT', 'PATCH', 'POST'], true)) {
            $context['allow_extra_attributes'] = false;
        }

        return $context;
    }
}
```

and service definition:

```yaml
# app/config/services.yaml

services:
    # ...
    App\Serializer\DisallowExtraAttributesContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\DisallowExtraAttributesContextBuilder.inner' ]
        autoconfigure: false
```

**Comment by dunglas** [comment]
For the record, this option can now be enabled globally: https://github.com/api-platform/core/pull/3151

**Comment by cnizzardini** [comment]
> #3151

How exactly?

**Comment by guilliamxavier** [comment]
> How exactly?

In your `config/packages/api_platform.yaml`:

```yaml
api_platform:
    defaults:
        denormalization_context:
            allow_extra_attributes: false
```

**Comment by cnizzardini** [comment]
> > How exactly?
> 
> In your `config/packages/api_platform.yaml`:
> 
> ```yaml
> api_platform:
>     defaults:
>         denormalization_context:
>             allow_extra_attributes: false
> ```

So others are aware, this only works in 2.6 or higher. It throws an exception when you try in 2.5.10. The PR was never tagged with a milestone so it's hard to tell...

**Comment by acirulis** [comment]
Is it really working as global defaults? I am using 2.6.8 version and if I configure allow_extra_attributes at Resource level, it works. However configuration defaults does not work. I also couldn't find in source code, where denormalization_context block would be parsed (e.g. in AnnotationResourceMetadataFactory)
