### ISSUE TITLE
documentation for jsonld_embed_context is wrong

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1218]
According to https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-the-context you can set jsonld_embed_context to true within the attributes of a resource or operation, but that has no effect. in reality you need to set the option within a normalization_context.

**Comment by teohhanhui** [comment]
Good catch! You can help us fix this by opening a Pull Request at https://github.com/api-platform/docs

**Comment by dunglas** [comment]
Closed by 2efdb6fe550934daa87e3481fce7f6efb2503ee2.
