### ISSUE TITLE
[JSON-LD] correctly add context of embedded nodes

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1223]
this is a follow up to the problem described in https://github.com/api-platform/core/issues/1222#issuecomment-312745686

The jsonld context is not correctly populated when embedded nodes. Either specify the context per embedded node ( see https://json-ld.org/spec/latest/json-ld/#advanced-context-usage ) or somehow pass up context entries to the root node.

**Comment by jkabat** [comment]
Is there any info how to solve this issue? At the moment (and with the lack of knowledge as I'm still quite new to api-platform) I'm tempted to replace @context @vocab to "http://schema.org/"...

But I would rather use a better way to get rid of json-ld validation issues for embedded nodes.

**Comment by soyuka** [comment]
This has changed recently, lmk if there's still an issue.
