### ISSUE TITLE
Swagger documentation for custom parameters in URLs

### ISSUE THREAD

**Issue by blesenechal** [api-platform/core#1230]
Hi, 

I have some routes that contain custom parameters, for example:
```
@Route(path="/users/{user_id}/reviews") 
@Method("POST")
```

The generated Swagger documentation only contains the “body” parameter, not the “path” parameters.
So my API can't be tested using Swagger.

In `ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer::updatePostOperation`, `$pathOperation['parameters']` is only generated with the “body” parameters, the “path” parameters are not used :
```
$pathOperation['parameters'] ?? $pathOperation['parameters'] = [[
    'name' => lcfirst($resourceShortName),
    'in' => 'body',
    'description' => sprintf('The new %s resource', $resourceShortName),
    'schema' => ['$ref' => sprintf('#/definitions/%s', $this->getDefinition($definitions, $resourceMetadata, $resourceClass, $this->getSerializerContext($operationType, true, $resourceMetadata, $operationName)))],
]];
```

I could workaround this by manually adding  a “swagger_context” to my operation:
```
"swagger_context" = {
    "parameters" = {
        {
            "name" = "user_id",
            "in" = "path",
            "required" = "true",
            "type" = "string"
        }
    }
}
```
But if a parameter is set “swagger_context” it overrides the “body” for the POST operation and I would also need to define also all the POST parameters in the “swagger_context” :-(

Would it be possible to :
- Add the path parameters in DocumentationNormalizer using the placeholders in the route ? to have something like :
```
$pathOperation['parameters'] ?? $pathOperation['parameters'] = [
    /** BEGIN for all placeholders in the route path */
    [
        'name' => '<parameter name in the path>',
        'in' => 'path',
        'required' => 'true',
        'type' => 'string'
    ],
    /** END for all placeholders in the route path */
    [
        'name' => lcfirst($resourceShortName),
        'in' => 'body',
        'description' => sprintf('The new %s resource', $resourceShortName),
        'schema' => ['$ref' => sprintf('#/definitions/%s', $this->getDefinition($definitions, $resourceMetadata, $resourceClass, $this->getSerializerContext($operationType, true, $resourceMetadata, $operationName) ))],
    ]
];
```
-	or merge the “swagger_context” instead of replacing ?

________________________

Note : This could also be done for item operations (GET/PUT/DELETE) : there is an hardcoded “id” parameter, it could also be auto-generated from the route path

Actual code of parameters for item operations :
```
$pathOperation['parameters'] ?? $pathOperation['parameters'] = [[
    'name' => 'id',
    'in' => 'path',
    'type' => 'string',
    'required' => true,
]];
```

**Comment by backbone87** [comment]
thats not the end of the story, you must also make the data providers aware of different parameter keys, but yes, using the route params to generate the swagger docs is one part of it.

**Comment by hackintos** [comment]
Have to tried to make it PUT instead of POST?

**Comment by Simperfit** [comment]
@blesenechal do you want to provide a Pull request fixing this behaviour ?

**Comment by blesenechal** [comment]
@Simperfit I'd like, but I won't have the time.

**Comment by teohhanhui** [comment]
I think we should provide a way to add extra parameters while keeping the defaults?

**Comment by soyuka** [comment]
You can use `queryParameters` in the swagger context IIRC.

**Comment by Dah-kenangnon** [comment]
Hello.
I have a problem with the documentation generated from api platforme with Redoc.

I noticed that there are several redoc parameters (which allow such a good customization) that Api platform does not support.
For example provide an introduction to the API, make submenus and many others.

Please, I would like to have a doc like this one:

https://rebilly.github.io/RebillyAPI/

If it exists a chance to add parameters that will use Redoc, thank you for helping me
