### ISSUE TITLE
AbstractItemNormalizer and Inheritance

### ISSUE THREAD

**Issue by Plasmagun86** [api-platform/core#1243]
Hi ! 

I have an abstract class 'Notification' and 2 child classes 'Email' with fromEmail, subject fields and 'PostalMail' with postal address. 

When I call "/notifications", i retrieve item that can be 'Email' or 'PostalMail' but fields are incoherent. Every items have the same fields but not compatible with their own class, sometimes I have Email with null address but without fromEmail or subject. Sometimes PostalMail have null fromEmail and subject but without address.

I localized the trouble in AbstractItemNormalizer in getAllowedAttributes function. If this function retrieve attributes from current object and not from resource_class in context, the results I expected is return.

Am i right ? or is there a better solution ?

**Comment by soyuka** [comment]
https://github.com/api-platform/api-platform/issues/277 
https://github.com/api-platform/api-platform/issues/266

It's a known issue and we're still not sure if we want to fix this because it's bad practice.
