### ISSUE TITLE
Bug with AbstractItemNormalizer and Subresources

### ISSUE THREAD

**Issue by benjaminjonard** [api-platform/core#1244]
Hello, I found a bug when using subresources. 

I have collections that hold items. A collection can have a parent collection and children collections.
When I call `/collections/4/items` I have this result :

```json
{
    "@context": "/app_dev.php/contexts/Item",
    "@id": "/app_dev.php/collections/4/items",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/app_dev.php/items/16",
            "@type": "Item",
            "id": 16,
            "name": "Item #1",
            "collection": {
                "@id": "/app_dev.php/collections/4",
                "@type": "Collection",
                "name": "Child 2nd gen",
                "parent": {
                    "@id": "/app_dev.php/collections/3",
                    "@type": "Collection",
                    "name": "Child 1st gen",
                    "parent": {
                        "@id": "/app_dev.php/collections/1",
                        "@type": "Collection",
                        "name": "Parent",
                        "parent": "/app_dev.php/collections/4"
                    }
                }
            },
            "template": null,
            "user": "/app_dev.php/users/1",
            "data": [],
            "tags": [],
            "createdAt": "2017-07-10T21:52:21+00:00",
            "updatedAt": null
        }
    ],
    "hydra:totalItems": 1
}
```

The collection with the name "Parent" has no parent, this property should be null (it works well when calling the item directly `/items/16`).

I found the code responsible for this in `ApiPlatform\Core\Serializer\AbstractItemNormalizer` 

```php
/*
 * On a subresource, we know the value of the identifiers.
 * If attributeValue is null, meaning that it hasn't been returned by the DataProvider, get the item Iri
 */
if (null === $attributeValue && isset($context['operation_type']) && $context['operation_type'] === OperationType::SUBRESOURCE && isset($context['subresource_resources'][$className])) {
    return $this->iriConverter->getItemIriFromResourceClass($className, $context['subresource_resources'][$className]);
}            
```

This `if` statement should be `false` in these conditions. I tried to find a fix but I couldn't find one. 
If you need help and can give me a few leads, I can look at it again.

Thanks :)

**Comment by soyuka** [comment]
Interesting case, I think that this is due to the fact that the `resourceClass` of `parent` is the same as the one you're requesting.

It'd be lovely if you could:
1. Add a failing behat test on this repository with your use case (you can do a PR with this)
2. Provide a fix if you think you can manage! We can discuss it better with a failing test case though :).

Thanks for the report!

**Comment by benjaminjonard** [comment]
Ok I'll have a look in the next few days :)

**Comment by soyuka** [comment]
Any updates?

**Comment by Simperfit** [comment]
Closing as this seems to get no feedback. Feel free to re-open if you have more information.
