### ISSUE TITLE
Add recommendation for custom filters 

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#126]
More like guidelines for custom filters:
* keep in mind the queryBuilder parameters conflict
* never use `setParameters` instead of `setParameter` as it will wipe out all previous parameters

I do not know if it has really its place here though.

**Comment by dunglas** [comment]
1. the bundle should already be safe but the doc can be enhanced to explain how to deal with that
2. `setParameters` is never used in the bundle so no problem here :-)

**Comment by theofidry** [comment]
Update on the issue regarding the `QueryBuilder` conflicts: it happens quite often when you have a few entities and custom filters for each, especially when dealing with relations for the join aliases. In our cases, we had to declare a `DoctrineHelper` class to secure the parameters. Given this use case may occur quite often, would it be worthwhile to add this kind of helper to the bundle?
