### ISSUE TITLE
How to add annotation @ORM\HasLifecycleCallbacks in entity from schema.yml file?

### ISSUE THREAD

**Issue by banandam** [api-platform/core#1269]
We are generating entity file from schema.yml using Schema Generator. 

Instead of add manually `* @ORM\HasLifecycleCallbacks` in entity file is there any option to mention it in schema.yml file?

Reference Link: https://stackoverflow.com/questions/17321893/automatic-values-for-updated-at-created-at-in-doctrine

**Comment by meyerbaptiste** [comment]
No, you can't, but you can create your own generator: https://api-platform.com/docs/schema-generator/configuration#disabling-generators-and-creating-custom-ones.
