### ISSUE TITLE
Subresource visited tracking is broken

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#1272]
Basically the same as #1139. Previously fixed in #1144 and #1162.

> Category
> - children
> - parent

Self-referencing resources results in infinite recursion leading to OOM.

> Product
> - brands
> - isRelatedTo
> - isSimilarTo

It tries to traverse deeper on the same path more than once, e.g.

> [LogicException]
> Route pattern "/products/{id}/is_related_to/{isRelatedTo}/is_related_to/{isRelatedTo}/brands.{_format}"
> cannot reference variable name "isRelatedTo" more than once.

The expected behaviour is:
```
Product -[isRelatedTo]-> Product -[isRelatedTo] -> Product
                                 /  cut here  /
```

**Comment by soyuka** [comment]
Isn't this unit tested?

**Comment by teohhanhui** [comment]
The tests must be wrong then...

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/master/tests/Bridge/Symfony/Routing/ApiLoaderTest.php#L232-L251

**Comment by soyuka** [comment]
Do you have a full stack trace for me?

**Comment by teohhanhui** [comment]
Not for the first case because it's OOM.

For the second case:

https://gist.github.com/teohhanhui/e4fe81e6d3dd55a0094140c789cc74eb

**Comment by teohhanhui** [comment]
Which wasn't helpful. We need Behat tests for this.

**Comment by teohhanhui** [comment]
I see that `$visiting` is only a local variable, so I don't know how that can possible work for visited tracking.

**Comment by soyuka** [comment]
Okay managed to reproduce ;).

**Comment by teohhanhui** [comment]
Yeah, you're missing the crucial part which is the `$visited` array which must be passed on. :laughing:

**Comment by plamenh** [comment]
Hey there, I am not sure, if this relates to my case, but I believe I have an issue with this:

`php.CRITICAL: Uncaught Exception: Route pattern "/platform/api/aliases/{id}/units/{units}/properties/{properties}/building/units/{units}/building.{_format}" cannot reference variable name "units" more than once.`

In Unit.php I have:

```
/**
     * Many Units have Many Properties.
     *
     * @ORM\ManyToMany(targetEntity="Property", mappedBy="units", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Expose
     * @MaxDepth(2)
     * @SkipWhenEmpty
     * @ApiSubresource
     */
    private $properties;
```

In Property.php:

```
/**
     * One Property has Many Units.
     *
     * @ORM\ManyToMany(targetEntity="Unit", inversedBy="properties")
     * @Expose
     * @MaxDepth(3)
     * Max depth of 3 needed to settle collections from property
     * @SkipWhenEmpty
     */
    private $units;
```

I know this is a ManyToMany and this might be an issue, but anyone knows of any solution? Thanks.
