### ISSUE TITLE
Router parameters requirements (Enhancement)

### ISSUE THREAD

**Issue by marcw** [api-platform/core#1273]
Currently, the ApiLoader route creation doesn't bring parameters requirement when creating a route (see https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L181-L194).

It means that when adding a custom operation, the ApiLoader's created route takes precedence over the custom operation. It is easily fixable by switching orders in the router, but I guess it would be also nice to have automatic route parameters requirements. 

Example:
```
Route 1: /myresources/{id}
Route 2: /myresources/my-custom-operation
```

When accessing `/myresources/my-custom-operation`, the router will match `/myresources/{id}`. as the {id} format is not defined as a requirements.

Is it a good idea to define requirements by default? I have the feeling that we could check the Doctrine metadata of the id field and create a requirement for numeric id or guid. Can you think of any drawbacks of defining such defaults?

**Comment by Simperfit** [comment]
@api-platform/core-team ?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/commit/9352351f04f2fe27c818d5cb025273cb4e3a7174#diff-c38359c69731b3bdcea477d3e35c1f97 ?
