### ISSUE TITLE
"No resource class found" if related entity is not explicitly in the file

### ISSUE THREAD

**Issue by RyderOne** [api-platform/core#1284]
Hello guys,
firstly thanks for your amazing work.

I would like to report something that is not specified in the documentation and that could save much time to anyone experiencing the same issue in the future.

I have 3 entities : Ground, HeadOffice and Address. A ground has an embeded (doctrine's annotation Embeded) relation with address, and headOffice has an embedded relation with address too.

I wanted to use api platform for ground and headoffice endpoints.
Everything works fine for ground, I get objects like this : 

```javascript
{
    "entitled": "STADE JEAN SPAETY 1",
    "address": {
      "street": "ROUTE D ENSISHEIM HR 2/3",
      "postalCode": "68190",
      "city": "UNGERSHEIM",
      "country": "France"
    }
}
```

But for headOffice I got this error :
No resource class found for object of type "AppBundle\Entity\Address".

After some debugging hours, I found out that the problem occured in ``src/Serializer/AbstractItemNormalizer.php`` in the method ``getAttributeValue``, where it tries to get propertyMetadata from attribute : in the headOffice case it fails (type in property metadata returned is null)

After comparing all annotations and methods in Ground.php and in HeadOffice.php, I found out that the only difference was in the property setter for address : in ground class, the setter was type hinted "Address" but not in headOffice class

Ground : 
```php

    /**
     * Set address.
     *
     * @param Address $address
     *
     * @return Ground
     */
    public function setAddress(Address $address)
    {
        $this->address = $address;

        return $this;
    }
```
HeadOffice : 
```php

    /**
     * Set address.
     *
     * @param Address $address
     *
     * @return HeadOffice
     */
    public function setAddress($address) // <-- Note the missing type hint
    {
        $this->address = $address;

        return $this;
    }
```

After adding the type hint in headOffice, the error disappeared and I successfully managed to get my head offices.

Conclusion : If you don't explicitly specify the type hint in your class, the metadata factory fails to guess your property type. I thought it could guess it from namespace (they are all in AppBundle\Entity namespace after all) or from annotation on address property but apparently not.

Is it an issue ? Is it possible to add a warning on doc, especially here : https://api-platform.com/docs/core/serialization-groups-and-relations#normalization ? Is it possible to modify something to guess this part ?

Thanks for your answers. I'm not a specialist in serializer and I would be happy if you can explain to me (and others) if this is a good idea or not !

**Comment by dunglas** [comment]
Thanks for your feedback! Would you mind opening a docs PR?

**Comment by RyderOne** [comment]
I'm sorry to bother you with that but can you explain a little bit to me why it does not work with entities in the  same namespace ? Is it intended or is it something we can improve ?

**Comment by soyuka** [comment]
Entities in the same namespace? I think that we do it all the time in our [test fixtures](https://github.com/api-platform/core/blob/master/tests/Fixtures/TestBundle/Entity/DummyProduct.php#L46).

**Comment by RyderOne** [comment]
My bad, I use v2.0.9, does  ``@ApiSubresource`` has something to do with it ? Is it new in 2.1 ?
Because as you said @soyuka, the test fixture is a perfect example of what should not work on my case.
I'll try to run theses tests locally to see what's going on.

Thank you

**Comment by soyuka** [comment]
`@ApiSubresource` is a new feature in 2.1 (not related).

**Comment by soyuka** [comment]
About the referenced test file I was talking about the fact that we don't declare namespace for classes that are in the same scope (this is your issue right?).

**Comment by RyderOne** [comment]
Yes it is. In my case the 3 files / classes are in the same namespace ``AppBundle\Entity``, as well as DummyProduct and DummyAggregateOffer are in the same namespace ``ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity``

**Comment by soyuka** [comment]
And the issue comes out from the getter/setter or from an annotation?

**Comment by RyderOne** [comment]
This is the property declaration in both Ground.php and HeadOffice.php
```
    use Symfony\Component\Serializer\Annotation as Serializer;
    .
    .
    .
    .
    /**
     * @ORM\Embedded(class="Address", columnPrefix="address_")
     * @Serializer\Groups({"apiRead"})
     */
    protected $address;
```

I use @Groups annotation as mentioned in https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-relations

There was no indication on what was the root cause of the problem, I just figured out after comparing Ground and HeadOffice that "Address" type hint was missing in the setter from HeadOffice and fortunately, adding it resolved the issue.

I had a similar case previously with another entities and a custom getter. In this previous case, I just found another way to do things to not have the problem. After finding this type hint thing, I tried again with the other entities by adding a custom setter along side the custom getter, and adding the right type hint in it, and it worked too.

**Comment by soyuka** [comment]
Shouldn't it be:

```diff
-@ORM\Embedded(class="Address", columnPrefix="address_")
+@ORM\Embedded(class="Address::class", columnPrefix="address_")
```

**Comment by RyderOne** [comment]
I didn't know you could do this but ``class="Address"`` seems good from Doctrine's doc : http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html

With ``::class`` I get this error : ``Unknown Entity namespace alias 'AppBundle\\Entity\\Address'.``

**Comment by soyuka** [comment]
Oh okay my bad!

**Comment by meyerbaptiste** [comment]
And with `class=Address::class` instead of `class="Address::class"`? 😛

**Comment by RyderOne** [comment]
In case you want to see the whole class : 
```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation as Serializer;

/**
 * Ground.
 *
 * @ORM\Table
 * @ORM\Entity(repositoryClass="AppBundle\Repository\GroundRepository")
 * @ApiResource(collectionOperations={"get"={"method"="GET"}}, itemOperations={"get"={"method"="GET"}}, attributes={
 *     "normalization_context"={"groups"={"apiRead"}}
 * })
 */
class Ground implements MapAddressInterface
{
    use TimestampableEntity;
    use Traits\MetaImportTrait;
    use Traits\SoftDeletableTrait;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Serializer\Groups({"apiRead"})
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     */
    protected $uuid;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Groups({"apiRead"})
     */
    protected $entitled;

    /**
     * @ORM\Embedded(class="Address", columnPrefix="address_")
     * @Serializer\Groups({"apiRead"})
     */
    protected $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Groups({"apiRead"})
     */
    protected $surface;

    /**
     * @ORM\ManyToOne(targetEntity="Club", inversedBy="grounds")
     */
    protected $club;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Match", mappedBy="ground")
     */
    protected $matches;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->matches = new ArrayCollection();
    }
    
    /**
     * Convenient method for api only
     * @Serializer\Groups({"apiRead"})
     */
    public function getClubId()
    {
        return $this->getClub() ? $this->getClub()->getId(): null;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->entitled;
    }

    public function toJsonArray()
    {
        return [
            'id' => $this->getId(),
            'surface' => $this->getSurface(),
            'entitled' => $this->getEntitled(),
            'uuid' => $this->getUuid(),
        ];
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set uuid.
     *
     * @param string $uuid
     *
     * @return Ground
     */
    public function setUuid($uuid)
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Get uuid.
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Set entitled.
     *
     * @param string $entitled
     *
     * @return Ground
     */
    public function setEntitled($entitled)
    {
        $this->entitled = $entitled;

        return $this;
    }

    /**
     * Get entitled.
     *
     * @return string
     */
    public function getEntitled()
    {
        return $this->entitled;
    }

    /**
     * Set address.
     *
     * @param Address $address
     *
     * @return Event
     */
    public function setAddress(Address $address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address.
     *
     * @return Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set surface.
     *
     * @param string $surface
     *
     * @return Ground
     */
    public function setSurface($surface)
    {
        $this->surface = $surface;

        return $this;
    }

    /**
     * Get surface.
     *
     * @return string
     */
    public function getSurface()
    {
        return $this->surface;
    }

    /**
     * Set club.
     *
     * @param Club $club
     *
     * @return Ground
     */
    public function setClub(Club $club = null)
    {
        $this->club = $club;

        return $this;
    }

    /**
     * Get club.
     *
     * @return Club
     */
    public function getClub()
    {
        return $this->club;
    }

    /**
     * Add match.
     *
     * @param Match $match
     *
     * @return Ground
     */
    public function addMatch(Match $match)
    {
        $this->matches[] = $match;

        return $this;
    }

    /**
     * Remove match.
     *
     * @param Match $match
     */
    public function removeMatch(Match $match)
    {
        $this->matches->removeElement($match);
    }

    /**
     * Get matches.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMatches()
    {
        return $this->matches;
    }

    /**
     * Sets the value of id.
     *
     * @param mixed $id the id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Sets the value of matches.
     *
     * @param mixed $matches the matches
     *
     * @return self
     */
    public function setMatches($matches)
    {
        $this->matches = $matches;

        return $this;
    }
}
```
I ommit nothing as it mays be important. The interface is in the same namespace.

**Comment by RyderOne** [comment]
@meyerbaptiste It works but in the same way as class="Address" : if I remove the type hint in the setter it fails too with the initial error "No resource class found .."

**Comment by soyuka** [comment]
Another solution is to not use getters and setters :smile_cat: 

```php
mespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation as Serializer;

/**
 * Ground.
 *
 * @ORM\Table
 * @ORM\Entity(repositoryClass="AppBundle\Repository\GroundRepository")
 * @ApiResource(collectionOperations={"get"={"method"="GET"}}, itemOperations={"get"={"method"="GET"}}, attributes={
 *     "normalization_context"={"groups"={"apiRead"}}
 * })
 */
class Ground implements MapAddressInterface
{
    use TimestampableEntity;
    use Traits\MetaImportTrait;
    use Traits\SoftDeletableTrait;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Serializer\Groups({"apiRead"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     */
    public $uuid;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Groups({"apiRead"})
     */
    public $entitled;

    /**
     * @ORM\Embedded(class="Address", columnPrefix="address_")
     * @Serializer\Groups({"apiRead"})
     */
    public $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Serializer\Groups({"apiRead"})
     */
    public $surface;

    /**
     * @ORM\ManyToOne(targetEntity="Club", inversedBy="grounds")
     */
    public $club;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Match", mappedBy="ground")
     */
    public $matches;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->matches = new ArrayCollection();
    }
    
    /**
     * Convenient method for api only
     * @Serializer\Groups({"apiRead"})
     */
    public function getClubId()
    {
        return $this->getClub() ? $this->getClub()->getId(): null;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->entitled;
    }

    public function toJsonArray()
    {
        return [
            'id' => $this->getId(),
            'surface' => $this->getSurface(),
            'entitled' => $this->getEntitled(),
            'uuid' => $this->getUuid(),
        ];
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add match.
     *
     * @param Match $match
     *
     * @return Ground
     */
    public function addMatch(Match $match)
    {
        $this->matches[] = $match;

        return $this;
    }

    /**
     * Remove match.
     *
     * @param Match $match
     */
    public function removeMatch(Match $match)
    {
        $this->matches->removeElement($match);
    }
}
```

Careful you have a `setId` but it's a `GeneratedValue` and therefore should not be writable.

**Comment by cesarluis13915** [comment]
I had the same issue and I want to share with you what happened. After reading from #667 , #201 and #184 , y realized that my mistake was that the setter and getter methods for my `@ORM\OneToMany` attribute were misspelled. Mi attribute name is `camposDinamicos` , while setter method was `setCamposDinamicosValoress`. Notice the two "s" at the end.

After changing it to `setCamposDinamicosValores`, the error went away. 

I think that **Api-Platform** should force developers to define the correct methods instead of trying to guess.

Anyway, thanks for your amazing work. Sorry for my bad english.
