### ISSUE TITLE
Don't use the api normalizer for tasks different than api

### ISSUE THREAD

**Issue by sebdec** [api-platform/core#1287]
I think It doesn't make sense to use the api platform normalizer for common tasks other than api:
$this->get('serializer')->normalize($object, $format, $context) 

Is there a way to use the default symfony serializers (without all the api platform normalization behaviour) ?

**Comment by dunglas** [comment]
For now it's not possible. But this is being discussed here (I also find it's a good idea, but it comes with drawbacks): https://github.com/api-platform/core/pull/1184#issuecomment-311166174

I close this issue a a duplicate. Feel free to join the existing conversation. All feedbacks will really help to make a decision.
