### ISSUE TITLE
Eager loading a relation without serializing it

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#1290]
Hey there,

I'd like to eager load an association *without* having it embedded, as I serialize a computed value from the association. Example:

```php
/**
 * @ApiResource(attributes={
 *     "normalization_context" = {"groups" = {"foo"}},
 * })
 */
class Foo
{
    /**
     * @var Collection|Amount[]
     *
     * @ORM\OneToMany(
     *     targetEntity="Amount",
     *     mappedBy="foo"
     * )
     */
    protected $amounts;

    /**
     * @return Money
     * @Groups({"foo"})
     */
    public function getTotalAmount()
    {
        $total = new Money(0, new Currency('USD'));

        foreach ($this->amounts as $amount) {
            $total = $total->add($amount->getAmount());
        }

        return $total;
    }
}
```
Clearly i want `amounts` eager loaded via a left join.
Is there a way to achieve this?

I realise that I could do this in an Collection/Item Extension:
```php
final class FooLoadedExtension implements QueryCollectionExtensionInterface, QueryItemExtensionInterface
{
    private function addWhere(QueryBuilder $queryBuilder, string $resourceClass): void
    {
        if (Foo::class === $resourceClass) {
            $rootAlias = $queryBuilder->getRootAliases()[0];
            $queryBuilder->addSelect('amounts');
            $queryBuilder->leftJoin(sprintf('%s.amounts', $rootAlias), 'amounts');
        }
    }
}
```

But this is dangerous, as I could easily end up with a double left join if:
- started filtering on nested amounts or
- i later decided to embed the `$amounts` but forgot to remove my Extension left join, or

So really i don't find the extension an acceptable solution.

Thanks!

**Comment by soyuka** [comment]
There's already a `EagerLoadingExtension` (enabled by default) that may already take care of this no?

**Comment by bendavies** [comment]
For me, The eager loading extension only left joins if I annotate the  association with the correct normalisation group.

**Comment by bendavies** [comment]
Without the serialization group, It `continues` here:
https://github.com/api-platform/core/blob/4fffea6519c63c066f3be08d9c72703d1c55ad6c/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php#L159
because `isReadable` is false.

**Comment by soyuka** [comment]
Yes, you don't want your field to be readable?

To avoid joining more than once (on filters for example) we're using [this](https://github.com/api-platform/core/blob/4fffea6519c63c066f3be08d9c72703d1c55ad6c/src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php#L355) internally. Therefore, your extension should be safe as long as it runs before our `FilterExtension`.

**Comment by bendavies** [comment]
> Yes, you don't want your field to be readable?
I'm not sure what you mean sorry. I just want the collection eager loaded (left joined), but not serialized.

I don't think i can rely on `getExistingJoin` on the Filter extension because there is no guarantee that my joined alias will be the same.

**Comment by soyuka** [comment]
> I'd still like to do this without an Extension if possible?

Hmm, not really because the `EagerLoadingExtension` is tied to the serialization context. Assumption was "What's the point of joining something you don't want to serialize". Though, your code is a good use case where this assumption isn't true. 

I need to come up with something that could force `EagerLoading` to join some property that isn't serializable. 

For now, I'd suggest to override the `EagerLoadingExtension` and add a dirty fix:

```diff
diff --git a/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php b/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
index 174211cf..0ac40dc3 100644
--- a/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
+++ b/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php
@@ -156,7 +156,7 @@ final class EagerLoadingExtension implements QueryCollectionExtensionInterface,
                 continue;
             }

-            if (false === $propertyMetadata->isReadableLink() || false === $propertyMetadata->isReadable()) {
+            if ($association !== 'foo' && $resourceClass !== 'Foo' && (false === $propertyMetadata->isReadableLink() || false === $propertyMetadata->isReadable())) {
                 continue;
             }
```

**Comment by bendavies** [comment]
thanks @soyuka . looking forward to seeing what you come up with!
