### ISSUE TITLE
[Question] Persisting a OneToMany-relation

### ISSUE THREAD

**Issue by bartwesselink** [api-platform/core#1298]
Hi!

I'm performing a PUT-request to update a resource, that contains a OneToMany-relationship. But everytime I update this resource, it creates new entities, meaning that it contains creates new IDs. How can I prevent this? I tried referencing the old id with `@id`, but that did not work sadly.

I'm performing this request:

```
{
  "content": "tasfsadf",
  "attachment": "",
  "attachments": [
    {
      "@id": "/api/update-attachments/41",
      "@type": "UpdateAttachment",
      "title": "",
      "fileName": "recognize-logo.png",
      "filePath": "598044e795aa3234924898.png"
    }
  ],
  "publicationDate": "2017-08-01T11:07:56+02:00",
  "id": "9"
}
```

Thanks in advance!

**Comment by soyuka** [comment]
What's your doctrine mapping on the entity? You may want to read [Transitive persistence / Cascade Operations](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#transitive-persistence-cascade-operations).

**Comment by bartwesselink** [comment]
Thanks for your answer, but I do have such a mapping:
```
    /**
     * @var UpdateAttachment[]|Collection
     *
     * @ORM\OneToMany(targetEntity="UpdateAttachment", mappedBy="update", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Groups("update")
     */
    private $attachments;
```
Or do I need a different cascade operation?

**Comment by soyuka** [comment]
I can't try this out right now but I know that sending something like this should work:

```
PUT /my_entity/1

{
    "association": [ "/my_association/1", "/my_association/2", {"title": "bar"} ]
}
```

If you have the correct deserialization groups it'll create a third association.

**Comment by bartwesselink** [comment]
Yep! Works, thanks. But this means there is no way to update an association (not a problem, I can send separate requests)?

**Comment by soyuka** [comment]
It may work, json should be the following:

```
PUT /my_entity/1

{
    "association": [ {"@id": "/my_association/1", "title": "foo"}, "/my_association/2", {"title": "bar"} ]
}
```

You may need a `merge` option in doctrine and denormalizaiton groups need to be correct. Still I'm not sure and I prefer to update my association alone because this will lead to many queries.

**Comment by bartwesselink** [comment]
Mm, that's true.. I'll consider this, thanks for your answer!
