### ISSUE TITLE
Performance regression in 2.1 beta 2

### ISSUE THREAD

**Issue by raziel057** [api-platform/core#1303]
I just tried to upgrade to 2.1 beta 2 where I didn't found any bugs but a regression in execution time when returning a lot of results. Memory also increases a lot. 

As you can see when I get 9200 results (id, name):

In 2.0.10 it takes about 600ms

![api-platform-2 0 1](https://user-images.githubusercontent.com/652505/28912531-ec9533e6-7834-11e7-8b49-31da165fcc81.png)

With 2.1.0 beta 2: 7s

![api-platform-2 1 0-beta-2](https://user-images.githubusercontent.com/652505/28912551-fdfbe2d8-7834-11e7-9061-e054244abcd5.png)

I tried to downgrade, upgrade multiple times and I always have the same results. The regression seems to be linked to the serialisation part. Could you please check?

**Comment by Simperfit** [comment]
Is it in dev / prod ?

is it at first run ?

**Comment by raziel057** [comment]
I have the same penalty in DEV and PROD env. Not only at first run, it's always the case.

**Comment by Simperfit** [comment]
@raziel057 Could you please try with current master ? Some cache improvement have been done in master.

**Comment by meyerbaptiste** [comment]
Did you try to run Blackfire on your project to localize the problem? It could help us to have a shared profile.

**Comment by raziel057** [comment]
@Simperfit I just tried to upgrade to dev-master:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating api-platform/core (v2.0.10 => dev-master 4fffea6):  Checking out 4fffea6519

But I have the same (bad perf) results.

@meyerbaptiste I will create a Blackfire profile this afternoon.

**Comment by soyuka** [comment]
Can you also check the `Cache` section?

**Comment by raziel057** [comment]
Each time I upgrade / downgrade I clean the cache and restart my server. Each time I have a perf issue in 2.1.0 and not in 2.0.10

**Comment by raziel057** [comment]
Please find here the Blackfire profile:
https://blackfire.io/profiles/compare/5a87c426-1908-485d-aed4-7ae05d5f7c99/graph

2.0.10 (env DEV):

```
$ blackfire curl 'http://avtax-api-platform.local/api/places/special/thin?pagination=false' -H 'Host: avtax-api-platform.local' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.7,fr;q=0.3' --compressed -H 'Referer: http://avtax-api-platform.local/api' -H 'Cookie: PHPSESSID=2hurci6ksscnlmfnobib83i5gm' -H 'Connection: keep-alive'
Profiling: [########################################] 10/10
Blackfire cURL completed
Graph URL https://blackfire.io/profiles/4554c77e-e8ac-41cc-8e40-9b317bc05213/graph
No tests! Create some now https://blackfire.io/docs/cookbooks/tests
No recommendations
```

Label | Value
--------------|---------------
Wall Time  |  2.01s
I/O Wait     |  n/a
CPU Time  |     n/a
Memory     | 65.2MB
Network     |   n/a     n/a     n/a
SQL           | n/a     n/a

2.1.0-dev (env DEV):

```
$ blackfire curl 'http://avtax-api-platform.local/api/places/special/thin?pagination=false' -H 'Host: avtax-api-platform.local' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.7,fr;q=0.3' --compressed -H 'Referer: http://avtax-api-platform.local/api' -H 'Cookie: PHPSESSID=2hurci6ksscnlmfnobib83i5gm' -H 'Connection: keep-alive'
Profiling: [########################################] 10/10
Blackfire cURL completed
Graph URL https://blackfire.io/profiles/e234cd98-142f-4e95-8827-e1f7f64517a8/graph
No tests! Create some now https://blackfire.io/docs/cookbooks/tests
No recommendations
```

Label | Value
--------------|---------------
Wall Time  |  8.99s
I/O Wait     |  n/a
CPU Time  |     n/a
Memory     | 74.1MB
Network     |   n/a     n/a     n/a
SQL           | n/a     n/a

**Comment by soyuka** [comment]
Looks like 2.1.0-dev is not using cache or I don't get it. 

May you share both blackfire independently, diff doesn't say much :|.

Also, in the symfony profiler, could you compare data from the `Cache` menu?

**Comment by raziel057** [comment]
Yes for sure:
2.0.10 : https://blackfire.io/profiles/4554c77e-e8ac-41cc-8e40-9b317bc05213/graph
2.1.0-dev : https://blackfire.io/profiles/e234cd98-142f-4e95-8827-e1f7f64517a8/graph

**Comment by Simperfit** [comment]
@soyuka is right IMO, It looks like the getCacheKey is triggering the cache to build instead of using it.

**Comment by raziel057** [comment]
From 2.1.0-dev

![symfony profiler](https://user-images.githubusercontent.com/652505/28924468-2974bba6-7862-11e7-9dfb-c7898b0c41cd.png)

**Comment by raziel057** [comment]
From 2.0.10

![cache-2 0 10](https://user-images.githubusercontent.com/652505/28924708-e9d01a9e-7862-11e7-84c8-114b28aace9c.png)

**Comment by bendavies** [comment]
that's a lot of calls to `md5` and `serialize`

**Comment by soyuka** [comment]
@bendavies indeed, apparently all coming from [`AbstractObjectNormalizer->getCacheKey`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L61). What's weird is that the context should be keeping this key in-memory no?

**Comment by soyuka** [comment]
I'm using APCU cache.

So, this is out of my hands because I'm using a custom normalizer. For example I retrieve a collection of 262 elements, each having 6+ relations (one of the relation is a toMany having a relation toOne). This took 1.4 sec [blackfire](https://blackfire.io/profiles/edb8f8bc-bd8e-4a2b-a801-589270663182/graph).

![perf](https://user-images.githubusercontent.com/1321971/28928066-8ecf822e-786c-11e7-90dc-84cdaf9cb64a.png)

I'm on master with symfony `3.3.6` but still using custom normalizers.

---------- 

Okay because I like performances I removed my custom normalizers to do the test. So here is the same route:

![perf2](https://user-images.githubusercontent.com/1321971/28928602-e7d91bf4-786d-11e7-9fe3-0e3e1b13d7fe.png)

[blackfire](https://blackfire.io/profiles/ee95e641-00a0-4ad4-86b9-37d895596132/graph)

Not seeing any of those `md5/serialize` calls like you :|.

-----------

For those who care, here is a [blackfire diff between default normalizer and normalizer dumper](https://blackfire.io/profiles/compare/ee95e641-00a0-4ad4-86b9-37d895596132...edb8f8bc-bd8e-4a2b-a801-589270663182/graph). Dumpers are from https://github.com/symfony/symfony/pull/22051 which I tweaked a bit and implemented my own `PropertyAccessor` on top of it.

**Comment by soyuka** [comment]
Reproduced!

https://github.com/soyuka/api-platform-perf

**Comment by Simperfit** [comment]
@soyuka it's strange if you reproduce it on 2.0 since this is on 2.1 beta did you change the vendor

**Comment by soyuka** [comment]
![beta](https://user-images.githubusercontent.com/1321971/28930221-9380935c-7872-11e7-81b2-3f216c5796bd.png)
![2 0](https://user-images.githubusercontent.com/1321971/28930231-972dd0e6-7872-11e7-9c00-990722ecd7a0.png)

I just changed the `api-platform/core` to `2.0` + `composer update` + `rm -r cache/*`

Look at the readme.

**Comment by soyuka** [comment]
Okay so, the commit named "Builtin cache invalidation system aka make API Platform fast as hell" is actually decreasing performances by over 80% :|.

I simply used my repository from above and took over every commit we did (on a comparison [2.0...master](https://github.com/api-platform/core/compare/2.0...master)) and tried randomly until I hit the one that is responsible for this issue. Everytime I changed the commit I launched the following script:

```
composer update
rm -r var/cache/*
bin/console server:stop
bin/console server:start
echo "no cache"
curl -w "Time total: %{time_total}" -o /dev/null -s "http://localhost:8001/foos.jsonld?pagination=false"
echo "cache"
curl -w "Time total: %{time_total}" -o /dev/null -s "http://localhost:8001/foos.jsonld?pagination=false"
```

After a couple of tries:

Commit https://github.com/api-platform/core/commit/2139c802abd52a81af7f6f16132eea55ad081e14 is the breakpoint:
```
"api-platform/core": "dev-master#2139c802abd52a81af7f6f16132eea55ad081e14",
Time total: 7.711412% 
```

The commit ~1 https://github.com/api-platform/core/commit/5dc1b08ba7483f03b0148e9bfe33014acc4266e3 : 

```
"api-platform/core": "dev-master#5dc1b08ba7483f03b0148e9bfe33014acc4266e3",
Time total: 1.659163% 
```

**Comment by bendavies** [comment]
Good work!

**Comment by soyuka** [comment]
I found out the lines:

1. https://github.com/api-platform/core/commit/2139c802abd52a81af7f6f16132eea55ad081e14#diff-3e45e8e6ce08f8a7cbbbda1601d5ff29R90 (6s on the above)
2. https://github.com/api-platform/core/commit/2139c802abd52a81af7f6f16132eea55ad081e14#diff-459c81ea781f42965c562949a62620c3R71 (less perf decrease but 0.4s on the above)

I'm investigating further.

**Comment by raziel057** [comment]
Thanks for your investigations. It's great to see that you take care of performance. cI think it's a very important part in a API platform.

**Comment by soyuka** [comment]
Whew, so bottom story the performance leak was caused by [getCacheKey](https://github.com/symfony/serializer/blob/master/Normalizer/AbstractObjectNormalizer.php#L364).
Indeed, [the responsible commit](https://github.com/api-platform/core/commit/2139c802abd52a81af7f6f16132eea55ad081e14) was adding every IRI to `$context['resources']`. 
Therefore, the serializer cache key, which is based on `serialize($context)` was:

- taking more and more time to be computed (hence all those `md5`/`serialize` calls)
- never the same, so actually never used and always re-computed (hence all those `md5`/`serialize` calls)

Thanks @meyerbaptiste @Simperfit for the talks around that :).

**Comment by meyerbaptiste** [comment]
Did the #1307 solve your issue @raziel057?

**Comment by raziel057** [comment]
I think but I would not be able to test before the 1 of September. I'm in holidays. Thanks for the fix.

**Comment by raziel057** [comment]
@soyuka @meyerbaptiste Thanks for the fix. I just checked and it works like a charm. I don't have perf regressions anymore.

**Comment by Simperfit** [comment]
That's a good feedback, thanks !
