### ISSUE TITLE
Event subcriber not working for PUT/POST action

### ISSUE THREAD

**Issue by Kleinast** [api-platform/core#1306]
Hi,

I am on api-platform/core v2.0.9 with symfony v3.3.5.

I tried to set custom voter on all action (get collection, get item, put and post). I created a subcriber

``` yaml
AppBundle\EventListener\UserSubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

```

The subcriber look like that

``` php
final class UserSubscriber implements EventSubscriberInterface
{
    private $permissionService;
    private $authorizationChecker;

    /**
     * UserSubscriber constructor.
     */
    public function __construct(PermissionService $permissionService, AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->permissionService = $permissionService;
        $this->authorizationChecker = $authorizationChecker;
        dump("héé");
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::VIEW => [
                ['setPermissions', EventPriorities::PRE_WRITE],
            ],
            KernelEvents::REQUEST => [
                ['checkAccess', EventPriorities::PRE_READ],
            ],
        ];
    }
}
```

It seem, when I test get collection or get item, it dump well my 'hé' message, so It's right implemented, but when I try to put or post an item, it never show me the 'héé' message.
It is really wird no ? 
It seem dependency injection implement it only when I try to post or put a ressource.
Is it a bug ? Or did I misunderstand something ?

Thanks

**Comment by meyerbaptiste** [comment]
It should work. Maybe you have another subscriber with an `Event::stopPropagation()` call...

**Comment by Mgibs** [comment]
I don't think it's a issue, Event don't have output.
Instead of dump, in this context you should use the logger component  to see if the event is trigger:
[https://symfony.com/doc/current/components/console/logger.html]()

**Comment by Simperfit** [comment]
@Kleinast did @Mgibs's awnser fit the needs?
