### ISSUE TITLE
[Question] Event system, adding a response header from POST_WRITE

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1308]
I've subscribed to `KernelEvents::VIEW => [['create', EventPriorities::POST_WRITE]]` as I need to run a service on my entity to add a header (I'm figuring out the URL for upload to Azure Blob Storage, to be exact). It needs to be done post-write as I require the entity's ID, but before serialize (as I need the actual entity to do this).

Problem is, if I subscribe to `POST_WRITE`, there's no `Response` yet. If I subscribe to `PRE_RESPOND`, the entity is already serialized. I can replace the whole thing obviously, but maybe I'm missing a better way?

Is there a way to (slightly) customize the response without duplicating the whole thing?

**Comment by dkarlovi** [comment]
FWIW, I've added the URL to request attributes and then set it to Response from `KernelEvents::RESPONSE => [['append', EventPriorities::POST_RESPOND]]`. That's quite hacky and nasty, but it does work.

**Comment by Simperfit** [comment]
We could add a new priority if you need it, depends on how we could use it.

Btw, [`EventPriorities::KEY`](https://github.com/api-platform/core/blob/master/src/EventListener/EventPriorities.php) is just a shortcut to KenervelEvents priorities.

**Comment by dkarlovi** [comment]
The norm seems to be to transfer the value via `Request::attributes` from one listener and use it from the other. I don't like that, but that's how it works. :)

Closing.
