### ISSUE TITLE
Missing endpoint on api:swagger:export 

### ISSUE THREAD

**Issue by lvillarino** [api-platform/core#1318]
I have a symfony app that use api-platform to expose data from a table and I have a controller that return a json.

When I run the command "php bin/console api:swagger:export > web/swagger.json" the result don't inside the configuration for my custom endpoint

I have set enable_nelmio_api_doc=true
and my custom endpoint is

```
/**
 *
 * Expose Global Swagger Documentation
 *
 * ### Response ###
 *
 *  Json string
 *
 * @ApiDoc(
 *  views = { "default" },
 *  section="Swagger",
 *     statusCodes={
 *         200="Returned Json",
 *         400={
 *           "Swagger Documentation hasn't been generated.",
 *         }
 *     }
 * )
 *
 * @Route(“/hello.json”)
 * @Method("GET")
 */
public function helloJuliaAction(Request $request)
{
		$responseData = array(
			'status' => Response::HTTP_OK,
			‘msg’ => “Hello Julia“,
		);
		return $this->createApiResponse($responseData, Response::HTTP_INTERNAL_SERVER_ERROR);
}

```

**Comment by Simperfit** [comment]
The swagger command works with the swagger generated by api-platform, not by nelmio-api-doc, I think nelmio has things on their own.
