### ISSUE TITLE
Error while trying to generate swagger.json

### ISSUE THREAD

**Issue by lvillarino** [api-platform/core#1319]
Hello,

I am trying to dump a swagger file using api:swagger:dump command and I get this error:

```
[Symfony\Component\Debug\Exception\ContextErrorException]
Notice: Undefined index: actualType
```

The dumped json only contains "/others" path for each resource.
Did you ever have this issue ?

I found this https://github.com/api-platform/core/issues/310

below are the bundles that I'm using

```
"require": {
        "php": ">=5.5.9",
        "ext-redis": "*",
        "api-platform/core": "^2.0",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "jms/serializer-bundle": "^2.0",
        "nelmio/api-doc-bundle": "^2.13",
        "oro/doctrine-extensions": "^1.2",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0",
        "switch-saf/service-basics-bundle": "^1.0.2",
        "symfony/dotenv": "^3.3",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0||^2.0"
    },
```

api_platform config

```
    # Enable the Nelmio Api doc integration.
    enable_nelmio_api_doc: true

    # Enable the Swagger documentation and export.
    enable_swagger: false

    # Enable Swagger ui.
    enable_swagger_ui: true

```

Thanks

**Comment by Simperfit** [comment]
Could please retry with `-vvv` to have the stack trace, and post it here ?

**Comment by lvillarino** [comment]
`php bin/console api:swagger:dump -vvv
{"swaggerVersion":"1.2","apis":[{"path":"\/others","description":"Lead"},{"path":"\/others","description":"description"},{"path":"\/others","description":"description"},{"path":"\/others","description":"description"},{"path":"\/others","description":"description"}],"apiVersion":"0.1","info":{"title":"Symfony2","description":"My awesome Symfony2 app!","TermsOfServiceUrl":null,"contact":null,"license":null,"licenseUrl":null},"authorizations":[]}

API declaration for "others" resource: 

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: actualType                        
                                                             

Exception trace:
 () at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Swagger/ModelRegistry.php:100
 Nelmio\ApiDocBundle\Swagger\ModelRegistry->register() at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/SwaggerFormatter.php:540
 Nelmio\ApiDocBundle\Formatter\SwaggerFormatter->registerModel() at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/SwaggerFormatter.php:313
 Nelmio\ApiDocBundle\Formatter\SwaggerFormatter->produceApiDeclaration() at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/SwaggerFormatter.php:89
 Nelmio\ApiDocBundle\Formatter\SwaggerFormatter->format() at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Command/SwaggerDumpCommand.php:164
 Nelmio\ApiDocBundle\Command\SwaggerDumpCommand->getApiDeclaration() at /var/www/html/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Command/SwaggerDumpCommand.php:102
 Nelmio\ApiDocBundle\Command\SwaggerDumpCommand->execute() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:892
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:40

api:swagger:dump [-r|--resource [RESOURCE]] [-l|--list-only] [-p|--pretty] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<destination>]`

**Comment by dunglas** [comment]
Could you try again with the latest version please?

**Comment by lvillarino** [comment]
I try again with the version **"api-platform/core": "^2.1",**  and I'm getting the same error

```
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: actualType     
```

Thanks

**Comment by Simperfit** [comment]
This does not occur anymore.
