### ISSUE TITLE
Can't use `maximum_items_per_page`

### ISSUE THREAD

**Issue by vdesdoigts** [api-platform/core#1325]
Hello,

I wonder how to use the parameter `maximum_items_per_page`.  
I need it in the following case:  
I have a user who has messages, but I only want to display the top 20.
`api/users/1` return the user's informations, with all messages (170 for example) 
```
{
    @context: "/app_dev.php/api/contexts/User",
    @id: "/app_dev.php/api/users/13",
    @type: "User",
    firstName: "Vincent",
    lastName: "Desdoigts",
    messages: [
        ...
    ]
}
```

I see a `$maximumItemPerPage` in the `PaginationExtension` but I don't understand how to use it.  

Can you help me?
Thank you

**Comment by soyuka** [comment]
Hi, this doesn't work on relations. If you're using the unstable version you may use subresources with a pagination (`/users/1/messages`). If not, you will have to use a custom action.

**Comment by vdesdoigts** [comment]
@soyuka Thanks, I am using `dev-master`, I tried with `@ApiSubresource` on relations.  
But I get `No route found for "GET /api/user/1/messages"`.  
Am I missing something?

```
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="user")
     * @Groups({"user"})
     * @ApiSubresource
     */
    private $messages;
```

**Comment by vdesdoigts** [comment]
There is probably an error in my code, I tried with the entities of the example, it works!
