### ISSUE TITLE
Is there any plan for supporting Webhooks?

### ISSUE THREAD

**Issue by ismailbaskin** [api-platform/core#1327]

**Comment by meyerbaptiste** [comment]
Can you tell us more about your idea?

**Comment by dunglas** [comment]
It's on my todo list. In the mean time, it's very easy to implement userland using API Platform events.

**Comment by dkarlovi** [comment]
@dunglas can you give a short outline of the functionality?

**Comment by Simperfit** [comment]
ping @dunglas

**Comment by Simperfit** [comment]
@ismailbaskin Could you please add more detail on what you want ?
