### ISSUE TITLE
SQLSTATE[HY000] [2002] php_network_getaddresses

### ISSUE THREAD

**Issue by danieljsc** [api-platform/core#1337]
Hi,

I've been trying to install/deploy api-platform on my centos 7 server.

These are my actual parameters:
```
parameters:
    database_host:     localhost
    database_port:     3306
    database_name:     api_platform
    database_user:     api_platform
    database_password: Teste_API_PLATFORM_12
```
When changing parameters.yml to 'localhost' || '127.0.0.1' database I get an error on the logs:

Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: **"An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): **SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, **PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): **PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at** /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"}

PHP-PDO installed: **php-pdo-7.1.8-1.el7.remi.x86_64**

So it looks like PDO constructor is failing to resolve localhost?
Is this any PHP 7.* known bug? Could anyone help?

___________________________________________________________
Did a simple test to pdo connection on the server:

```
<?php


$servername = "localhost";
$username = "api_platform";
$password = "Teste_API_PLATFORM_12";
$database = "api_platform";

try {
    $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully";
    }
catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
```

On the browser i got "Connected successfully"

**Comment by danieljsc** [comment]
Ok...

Did a simple test to pdo connection on the server:

```
<?php


$servername = "localhost";
$username = "api_platform";
$password = "Teste_API_PLATFORM_12";
$database = "api_platform";

try {
    $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully";
    }
catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
```

On the browser i got "Connected successfully"

**Comment by soyuka** [comment]
> So it looks like PDO constructor is failing to resolve localhost?
Indeed.

Is this any PHP 7.* known bug? Could anyone help?

Not really as I managed to use mysql successfully with api platform a couple of times :|.

**Comment by Simperfit** [comment]
Could you try using docker ? maybe there is something that does not work with centos ?

**Comment by dunglas** [comment]
Closing because no feedback. Feel free to reopen if you can provide more information.

**Comment by AlexandrTarasov** [comment]
most likely your var like $servername and  so on doesn't perceive how it's have to. Try to use ".$servername."

**Comment by daniaaalarshad** [comment]
> Hi,
> 
> I've been trying to install/deploy api-platform on my centos 7 server.
> 
> These are my actual parameters:
> 
> ```
> parameters:
>     database_host:     localhost
>     database_port:     3306
>     database_name:     api_platform
>     database_user:     api_platform
>     database_password: Teste_API_PLATFORM_12
> ```
> 
> When changing parameters.yml to 'localhost' || '127.0.0.1' database I get an error on the logs:
> 
> Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: **"An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\DBAL\Exception\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\DBAL\Driver\PDOException(code: 2002): **SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, **PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known** at /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): **PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at** /var/www/html/test-api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"}
> 
> PHP-PDO installed: **php-pdo-7.1.8-1.el7.remi.x86_64**
> 
> So it looks like PDO constructor is failing to resolve localhost?
> Is this any PHP 7.* known bug? Could anyone help?
> 
> Did a simple test to pdo connection on the server:
> 
> ```
> <?php
> 
> 
> $servername = "localhost";
> $username = "api_platform";
> $password = "Teste_API_PLATFORM_12";
> $database = "api_platform";
> 
> try {
>     $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password);
>     // set the PDO error mode to exception
>     $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
>     echo "Connected successfully";
>     }
> catch(PDOException $e)
>     {
>     echo "Connection failed: " . $e->getMessage();
>     }
> ```
> 
> On the browser i got "Connected successfully"

Your question actually solved my problem. lol THANKS :dancing_men:
