### ISSUE TITLE
PUT & nested properties with validation : always null

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1338]
Hello,

Thanks for Api Platform : a great tool !!!

I am trying to update an object with sub-objects : 

```php

/**
 * @ApiResource(
 *     collectionOperations={"get": {"method": "GET"} },
 *     itemOperations={
 *         "get": {
 *             "method": "GET"
 *         },
 *         "put": {
 *             "method": "PUT",
 *             "denormalization_context"={"groups"={"book_edit"}}
 *         }
 *     }
 * )
 */
class Book {
    /**
     * @var Author
     * @Groups({"book_edit"})
     * @Assert\NotNull
     */
    private $author;
}

/**
 * @ApiResource
 */
class Author {
    /**
     * @var string
     * @Groups({"book_edit"})
     */
    private $name;

    /**
     * @var sting
     *
     * @Assert\NotBlank
     */
    private $aProperty;
}
```

And like the doc [says](https://api-platform.com/docs/core/serialization-groups-and-relations#denormalization), I added in the json the **@id** key in order to point to the author but all author properties are null so it doesn't retrieve the real object and it causes validation error.

I discovered few things : 
- if I remove the validation, it tries do to an INSERT on the database instead of UPDATE (for author)
- with Xdebug, I find that it uses `src\Serializer\ItemNormalizer::denormalize` and this function uses the **id** property, not **@id**. So I tried with **id** and I have the same result.

Could you please help me ?

Thank you

**Comment by soyuka** [comment]
Are you using doctrine? Could we have the mapping?

Do you have getters and setters for those relations?

**Comment by pierre-H** [comment]
@soyuka  yes I use Doctrine.

This is the original mapping : 

```php
/**
 * @ORM\Entity()
 * @ApiResource(
 *     collectionOperations={"get": {"method": "GET", "normalization_context"={"groups"={"sejour_list"} } } },
 *     itemOperations={
 *         "get": {
 *             "method": "GET",
 *             "normalization_context"={"groups"= {"fiche_patient_general", "fiche_patient", "rens-ss", "dossier-medical" } }
 *         },
 *         "put": {
 *              "method": "PUT",
 *              "denormalization_context"={"groups"={"sejour_edit"}},
 *         },
 *         "info_sejour": {
 *             "method": "GET",
 *             "normalization_context"={"groups"={"sejour_info"}}
 *         } 
 *    }
 * )
 */
class Sejour {
    /**
     * @var Patient
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Patient", inversedBy="sejours", cascade={"persist"})
     * @ORM\JoinColumn(name="patient", referencedColumnName="id")
     *
     * @Groups({"sejour_list", "sejour_edit"})
     *
     * @Assert\NotNull()
     * @Assert\Valid()
     */
    private $patient;


    // GETTER and SETTER for patient
}

/**
 * @ORM\Entity()
 * @ApiResource(
 *     collectionOperations={"get": {"method": "GET"} },
 *     itemOperations={
 *         "get": {
 *             "method": "GET"
 *         },
 *         "put": {
 *             "method": "PUT",
 *             "denormalization_context"={"groups"={"sejour_edit"}}
 *         }
 *     }
 * )
 */
class Patient {
    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Sejour", mappedBy="patient", cascade={"persist"})
     * @ORM\OrderBy({"numSejour": "ASC"})
     */
    private $sejours;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=64, nullable=false)
     *
     * @Assert\NotBlank
     * @Assert\Length(max="64")
     *
     * @Groups({ "sejour_edit"})
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=false)
     *
     * @Assert\NotBlank
     * @Assert\Length(max="64")
     * @Groups({ "sejour_edit"})
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=10, nullable=false)
     *
     * @Assert\NotBlank
     * @Assert\Length(max="10")
     */
    private $code;

    // GETTERs and SETTERs for name, firstname, code and sejour (with add and remove for the last one)
}
```

**Comment by soyuka** [comment]
Looks fine, assuming your sending `{"author": { "@id": "/authors/1" } }` on `/books` it should create a book having `1` as author.

**Comment by pierre-H** [comment]
Well, it doesn't work : AP creates a new author with ID 1 and all other author properties as null.

I saw with XDebug that the AbstractObjectNormalizer is used when there is **@id** and with **id** it's more complex : the `IriConverter::getItemFromIri()`function is used by `ItemNormalizer::updateObjectToPopulate()` then the `ChainItemDataProvider` is used with `$context['fetch_data'] = false` then the ItemDataProvider stops at the line `return $manager->getReference($resourceClass, $identifiers);`
The getReference function return an object with all properties as null.

Looks like the problem comes from `$context['fetch_data'] = false`

**Comment by soyuka** [comment]
This is because the author doesn't exist yet? If you want to create both (as you have `cascade persist`), you should be able to do:

```
POST {"author": {"name": "foo"}}
```

**Comment by pierre-H** [comment]
@soyuka no : the author exists already

**Comment by soyuka** [comment]
> Looks like the problem comes from `$context['fetch_data'] = false`

This is intended, if the author already exists we don't need to fetch it.

The test [located here](https://github.com/api-platform/core/blob/master/features/main/relation.feature#L48) is doing the same thing (`third_level` exists). What I don't get is that you're talking about `PUT` though the `Book` (or `Sejour`) can not exist without an `Author` (or `Patient`).

Maybe related to https://github.com/api-platform/api-platform/issues/375.

**Comment by pierre-H** [comment]
Me I want to edit a book and its author. The book and the author already exist.
AP find the book but not the author (AP wants to insert a new author instead of editing the good one).

I don't think that is related to https://github.com/api-platform/api-platform/issues/375

**Comment by soyuka** [comment]
`PUT /books/1 {"author": "/author/2"}` works, I just edited the behat test case from above to add this case.

Maybe it's a group issue?

**Comment by pierre-H** [comment]
Maybe but I don't see what exactly

**Comment by pierre-H** [comment]
In this line there is **id** and not **@id** : https://github.com/api-platform/core/blob/12871f38fdadf79e696526ac492be4ccfd82001c/src/Serializer/ItemNormalizer.php#L33 is it first normal ?

If there is **id**, it's this line which returns the object with all properties as null : 
https://github.com/api-platform/core/blob/12871f38fdadf79e696526ac492be4ccfd82001c/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L74

The problem is that it should normally continue so it can gets the real object

**Comment by pierre-H** [comment]
> > Looks like the problem comes from $context['fetch_data'] = false

> This is intended, if the  author already exists we don't need to fetch it.

Yes @soyuka  but if that's the case, the validation cannot works properly

**Comment by soyuka** [comment]
I don't see where you need `@id` or `id` in your case. Also, check out the `JsonLd` normalizer which is using `@id`.

**Comment by pierre-H** [comment]
Oh thank you @soyuka !
I found the solution : in my http header, there was `application/json` and not `application/ld+json` : that's a so stupid mistake !
That's was AP used the simple ItemNormalizer and not the JsonLd ItemNormalizer.*

But, there is still a question for who wants to use json and not jsonld : 
why for json `fetch_data` is false : 
https://github.com/api-platform/core/blob/12871f38fdadf79e696526ac492be4ccfd82001c/src/Serializer/ItemNormalizer.php#L47
and for jsonld `fetch_data` is true : 
https://github.com/api-platform/core/blob/12871f38fdadf79e696526ac492be4ccfd82001c/src/JsonLd/Serializer/ItemNormalizer.php#L105

**Comment by soyuka** [comment]
Hmm, it's probably wrong in the `ItemNormalizer`, may you patch it? Thanks!

**Comment by pierre-H** [comment]
@soyuka done https://github.com/api-platform/core/pull/1340
