### ISSUE TITLE
Custom controller doc is hard to understand

### ISSUE THREAD

**Issue by awildeep** [api-platform/core#135]
I am attempting to build a custom controller for an endpoint (I used http://dunglas.fr/2015/06/introducing-dunglass-api-platform-beta-the-next-generation-php-framework/ as a primer to get started).

I would like to have a controller for my "people" endpoint so I can eventually add in security restrictions.  For example only authenticated users with the role "ROLE_PEOPLE_LIST" can see the people listing.  Or say if a user has the "ROLE_PEOPLE_LIST_IN_MY_ORGANIZATION" will list people in that users organization via a filter.

Of course, I may be thinking about this incorrectly, and maybe I do not want a controller.  However I can not seem to get a custom controller working and I have tried more variations on what is in the doc than I would care to admit.

Is there a best practice for restricting access to an endpoint?  Or partially restricting access to a pre-filtered list?

**Comment by dunglas** [comment]
Hi @awildeep,

Generally speaking, creating a custom controller should be done in last resort. For use cases you describe, I think there is cleaner ways:

**Blocking the whole list to a given role**

Using the Symfony security component is the recommended way: http://symfony.com/doc/current/book/security.html#denying-access-roles-and-other-authorization

**Partial list filtering**

Using a custom `DataProvider` doing the appropriate database query according to the current user role is considered a best practice: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/data-providers.md

We will add cookbook for such common use cases, it's a work on progress.

However, creating custom controller should work. Have you registered a custom operation for your custom controller? Can you upload your test in a GitHub repo so I can reproduce the problem or help you to fix the configuration?

**Comment by awildeep** [comment]
@dunglas 

So you are using the Symfony firewall to restrict access.   That makes sense. 

I'll have to look into the ```DataProvider```.   I am guessing you have no examples that check Roles yet.

As for the controller, I did not have a custom operation registered.   The doc for custom controllers makes it seem like my custom controller would override the prebuilt one from the start.  I'll take another stab at getting a controller working and see if I can update the doc in a pull request.

Thanks for the response.

**Comment by dunglas** [comment]
Enhancing the doc will be of course greatly appreciated! Thanks for proposing.

The custom controller doesn't automatically override the default one:
- if you don't map it with a custom operation, you must expose it with the routing system (e.g. annotations) manually.
- to override the controller for a built-in action you must register a custom operation (internally the bundle registers default operations thanks to a compiler pass if no custom operation is set).

You're right: the doc must explicit that.

**Comment by Simperfit** [comment]
Is the doc updated about this ? It is still relevant ?

**Comment by dunglas** [comment]
It's easier in v2 and the doc has been updated.
