### ISSUE TITLE
Deserialization errors cause a server error response insteadof client error

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1352]
When deserializing for example an invalid phone number into a PhoneNumber value object (from https://github.com/misd-service-development/phone-number-bundle), the `PhoneNumberNormalizer` throws an `UnexpectedValueException` and the API response with error 500 insteadof 400.

Also the response should contain a `ConstraintViolationList` like all other errors

**Comment by dunglas** [comment]
It's a normal behavior, it's your responsibility to catch library errors. The `exception_to_status` config option also allows to map an exception with a status code (https://github.com/api-platform/docs/blob/master/core/configuration.md).

**Comment by backbone87** [comment]
> it's your responsibility to catch library errors

What you mean by that? Validation errors are "caught" too and the exception thrown is https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Exception/UnexpectedValueException.php . I think one would expect these deserialization errors by bad client input to be handled with a correct error response automatically.

also yes i can map the error to a status code via config, but one gets no description why the error happened.

**Comment by dunglas** [comment]
There is a special handler for the validator (you can register custom handlers too).

**Comment by dunglas** [comment]
Did you tried to add the constraints provided by the bundle (just a hint, I never used it)?

**Comment by backbone87** [comment]
there are constraints, but that is not the problem, because the constraint will never be appied. the deserialization happens before the validator can be executed. but what was provided can not be deserialized into a syntatically valid value object

**Comment by dunglas** [comment]
Ok got it. There is nothing we can do for such cases. It's not possible to distinguish deserialization errors like this one from real errors that must throw a 500.

You need to use the config option or add your own exception handler (like the one we created for validation errors).

**Comment by backbone87** [comment]
well all deserialization errors should be of type https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Exception/UnexpectedValueException.php

so adding a handler to the core would be nice, since its a common problem when working with value objects

**Comment by meyerbaptiste** [comment]
By default `Symfony\Component\Serializer\Exception\UnexpectedValueException` throws a 400 because this exception extends the `Symfony\Component\Serializer\Exception\ExceptionInterface`, see: https://github.com/api-platform/core/blob/5111c739f047d196ed5b2c74e04467380ca3816c/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L193-L197

Do you override the default `exception_to_status` config?

**Comment by backbone87** [comment]
yes, i do, thanks for the tipp, but shouldnt the default values be merged? i started this project from api-platform/api-platform, maybe its a good idea to include these default values explicitly into the config too

**Comment by backbone87** [comment]
anyway this doesnt solve the problem with inconsistent error responses. especially errors caused by client users not client implementors.
A client implementor may produce invalid JSON which is clearly 400er and should be noticed on devtime.
A client user may enter a FOOBAR phonenumber and produces a 400er too, but since the error happens at serializer lvl, he gets the same response as for invalid JSON.

Within the serializer component its pretty clear how to distinguish these different errors:
If the error occurs within the encoder -> client implementors fault
If the error occurs within the normalizer -> either implementors or users fault

hm, the only idea i can come up with is a `null` or `invalid` object in the value objects value space. which gets deserialized jsut fine and gets checked during validation.

ofc a reason could be made that client implementors provide sufficient checks for client users, so there are no invalid (not deserializable) values submitted.
