### ISSUE TITLE
Validation : support of errors levels

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1357]
Hello,

Thanks again for Api-Platform !

I'd like to use [different error levels](https://symfony.com/doc/current/validation/severity.html).
What I'd like is to have in the response (with all constraints message) the severity value. Is there a way to achieve this ?

Thank you !

**Comment by dunglas** [comment]
I wasn't even aware of this feature. After double checking, there is nothing regarding severity directly in the Validator component, it's a custom usage of the `payload` object.

Exposing `payload` objects client-side can be implemented easily has we already do for `violations:

* For Hydra: https://github.com/api-platform/core/blob/master/src/Hydra/Serializer/ConstraintViolationListNormalizer.php#L64
Anf for RFC7807: https://github.com/api-platform/core/blob/master/src/Problem/Serializer/ConstraintViolationListNormalizer.php#L54

It is as easy as adding `'payload' => $violation->getConstraint()->getPayload()` after `violations`. However, maybe the payload defined by the user may contain sensitive data (@webmozart, do you have a hint about that?), if it's the case, we should provide a configuration option to prevent payload serialization. We should also not add a `payload` key if no payload is provided.

Would you mind opening a PR?

**Comment by norkunas** [comment]
I would suggest to also serialize violation constraint error code

**Comment by pierre-H** [comment]
An option where we can configure which payload fields to serialize could be better : 
```yml
api_platform:
    payload_validation_keys:
    - severity
    - other_field
```
This way, we can have sensitive and public data in the playload.

**Comment by pierre-H** [comment]
@dunglas I created a [PR](https://github.com/api-platform/core/pull/1364) but I don't know why test don't pass ...
