### ISSUE TITLE
Extending DocumentationNormalizer

### ISSUE THREAD

**Issue by ismailbaskin** [api-platform/core#1370]
**Problem :** I see there is no option for extending document normalizer. But, I need to add some custom operation or use [vendor spesific extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#vendorExtensions) . When I check [the code](https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php#L49-L67) ctor parameters is increasing in every feature, and there is 767 lines of code. 😓

**Suggestion :**
Using DocumentSerializerInterface classes and merge results.
```php
interface DocumentSerializerInterface
{
    public function result(Documentation $documentation): array;
}
```

**Comment by dunglas** [comment]
Doesn't [this docs entry](https://api-platform.com/docs/core/swagger#override-swagger-documentation) address your need?

**Comment by dunglas** [comment]
Closing as no feedback.
