### ISSUE TITLE
One to One bidirectional Subresource

### ISSUE THREAD

**Issue by devrck** [api-platform/core#1371]
Hello,

Maybe it's a stupid question but consider the following situation:
* Entity A that has a attribute Entity B
* Entity B that has a reference back to Entity A

You can have this type of behavior like in doctrine a One-to-One bidirectional.

My problem is that it generates urls like: A/{id}/B/A and I expect to see something like A/{id}/B

**Comment by soyuka** [comment]
Question OneToOne Answer:

https://github.com/api-platform/core/blob/eb47c5791cc84156a849a9c2f99279a57b6e28fc/tests/Fixtures/TestBundle/Entity/Question.php#L39-L41

Resolves in `/questions/1/answer`

https://github.com/api-platform/core/blob/eb47c5791cc84156a849a9c2f99279a57b6e28fc/features/main/subresource.feature#L9

**Comment by devrck** [comment]
@soyuka ok, but if I don't use Doctrine :smile: ?

**Comment by devrck** [comment]
As a note I want the following to happen:
Entity A:
* A/{id}/B

Entity B:
* B/{id}/A

**Comment by soyuka** [comment]
> @soyuka ok, but if I don't use Doctrine 😄 ?

Then the `isCollection` flag is important - see [SubresourceMetadata](https://github.com/api-platform/core/blob/master/src/Metadata/Property/SubresourceMetadata.php#L45).

> Entity A:
>
>   A/{id}/B

Means `@ApiSubresource` on relation `B` in the `A` entity.

> Entity B:
>
>   B/{id}/A

Means `@ApiSubresource` on relation `A` in the `B` entity. Still, you'll have `B => A => B` because there is a subresource on the `B` relation on `A` (works on reverse too).

**Comment by devrck** [comment]
Ok how do i set the `isCollection`?
Also I consider generating routes like B/{id}/A/B to be wrong.

**Comment by soyuka** [comment]
Not wrong, but yeah we still need to give a way to configure the generated path in-depth.

About the collection, the [property `Type` just needs to be a collection](https://github.com/api-platform/core/blob/eb47c5791cc84156a849a9c2f99279a57b6e28fc/src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php#L84) (type it as array for example)

**Comment by devrck** [comment]
@soyuka ok I understand can you please tell me how to hide some operations?

**Comment by soyuka** [comment]
Hide? You want them "not to be defined". We need to improve the `@ApiSubresource` annotation (with `depth` or (need ideas?)). For now it's not really possible :).

You could however declare a custom `CollectionOperation`  that will use the `SubresourceDataProvider` instead of the default!

**Comment by soyuka** [comment]
Allow to redefine subresources as we're redefining collection operations.

For example:

```
 @ApiResource(subresourceOperations={"some_subresource_key"={"method"="GET"}}})
```

NB: need to check if we can rewrite collectionOperations.

**Comment by devrck** [comment]
@soyuka the solution you've suggested could no work because on the [`ApiResource`](https://github.com/api-platform/core/blob/master/src/Annotation/ApiResource.php#L24) there is no `subresourceOperations`, to redefine what a subresource does you have to define them in `itemOperations` or `collectionOperations` but apparently you can not assign an empty collection to force them to dissapear.

E.g:

```php
/**
 * Class A
 *
 * @ApiResource(
 * collectionOperations={
 *     "get"={"method"="GET"}
 * },
 * itemOperations={
 *      "get"={"method"="GET"},
 *      "api_A_B_get_subresource"={}
 * }
 * )
 */
class A 
{
   protected $B;
}
```

**Comment by devrck** [comment]
The only way i see it is to redefine `api_platform.subresource_operation_factory`

**Comment by soyuka** [comment]
We definitely need to improve that part, feel free to send a PR if you're able to patch it!

**Comment by devrck** [comment]
For now I overwrote the service mentioned above to stop the auto-generation. Will try to find better solution if I can think of one.
