### ISSUE TITLE
[Path Resolver] Path resolver is not work

### ISSUE THREAD

**Issue by ad3n** [api-platform/core#1372]
I upgraded to 2.1.0 but path resolver is not work. Documentation: `https://api-platform.com/docs/core/operation-path-naming#create-a-custom-operation-path-resolver`

I read the code directly and i saw that is deprecated, and i try to use segment name buat also not work.

How to customize the path in version 2.1.0?

**Comment by mmplanet** [comment]
Can this get a higher priority? It has the potential to totally break existing apps.

**Comment by ad3n** [comment]
cc @dunglas for confirmation

**Comment by meyerbaptiste** [comment]
It's a bug, see #1381.

**Comment by ad3n** [comment]
@meyerbaptiste :+1: great... I think we need release this patch soon...

**Comment by meyerbaptiste** [comment]
@ad3n 2.1.1 should be released very very soon 😉
