### ISSUE TITLE
Changing the Serialization Context Dynamically

### ISSUE THREAD

**Issue by raziel057** [api-platform/core#1375]
I tried to implement a change of context of serialization like explained here:
https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically

But I have an issue because the method ``createFromRequest`` is called with the exact same parameters for each entity linked to my root entity.

For example if I have:
```php
...

/**
 * @ApiResource(attributes={
 *     "denormalization_context"={"groups"={"write"}}
 * },
 * @ORM\Table
 * @ORM\Entity
 */
class User
{
    /**
     * @Groups({"write"})
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Group")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(nullable=false)
     * })
     */
    private $group;

    ...
}
```

The method ``createFromRequest`` is called one time for User and one other for Group, but ``$request->attributes->get('data')`` is always an iinstance of ``User``.

I analysed and this method is called in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php ``getSerializerContext``. Each time this method is called ``$resourceClass`` is equals to ``AppBundle\Entity\User``.

It comes from 
```php
$serializerContext = $this->getSerializerContext($context['resource_class'] ?? $resourceClass, $contextType, $options);
```

Here ``$resourceClass`` is  ``AppBundle\Entity\User`` and next  ``AppBundle\Entity\Group``. Is it normal to give always the root context here (``AppBundle\Entity\User``) ? If yes would it be possible to expose the current processed ``$ressourceClass`` to be able to change the serialization context only for the root or a child entity?

**Comment by dunglas** [comment]
@soyuka could you take a look, IIRC, we changed something related to this recently.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/commit/5d6094044b0de136a32ce7be669b75c7b6f4dd07#diff-3e45e8e6ce08f8a7cbbbda1601d5ff29 maybe

**Comment by soyuka** [comment]
Maybe related: https://github.com/api-platform/docs/issues/298

**Comment by soyuka** [comment]
@raziel057 Could you try to manually revert [this commit](https://github.com/api-platform/core/commit/5d6094044b0de136a32ce7be669b75c7b6f4dd07#diff-3e45e8e6ce08f8a7cbbbda1601d5ff29) ? Would be really helpful!

**Comment by raziel057** [comment]
@soyuka I tried to revert this commit but it doesn't change anything. For the current use case (user lined to group) I always have 2 calls to createFromRequest with ``AppBundle\Entity\User`` as subject.

**Comment by raziel057** [comment]
It's not really a big issue but just don't know if it's normal to have ``AppBundle\Entity\User`` as subject each time we pass in createFromRequest.

**Comment by dunglas** [comment]
What I don't understand is why this method is called twice. It should be called only 1 time per request (and `data` should contain the top level entity).

**Comment by dunglas** [comment]
Are you working on a `POST` or `PUT` request? In this case it's normal that this method is called two times: 1 time for deserialization, another time for serialization.

**Comment by raziel057** [comment]
@dunglas I work on PUT request but the method is called 2 times for serialization (from my simple sample). I tried to add more ManyToOne relation and the method is called one time for the root entity and 1 time for each relation.

It may be normal to allow to change the serialization/deserialization group for each relation independently? But in this case it would be useful to have the current child entity.

**Comment by soyuka** [comment]
@dunglas might be called because of the EagerLoading. The relation is calling the `DataProvider` through the `Normalizer`. Each time, the `EagerLoadingExtension` tries to get back the context. Maybe that the context should not be recomputed there but I think it had something to do with relations.

**Comment by dunglas** [comment]
Ok, wasn't aware of this behavior. It indeed looks weird that it's not called with the good subject.

**Comment by Simperfit** [comment]
What's the state of this ?

**Comment by soyuka** [comment]
Closing, feel free to ping if you want me to reopen.
