### ISSUE TITLE
How Overwrite the GET action to access a composite primary key

### ISSUE THREAD

**Issue by lvillarino** [api-platform/core#1376]
Hi,

I want to know how I can overwrite the GET action to accept a composite primary key.
My current GET action is /entity/{id} and I want to be /entity/{r1}/{r2}/{r3}

My table don't have an unique primary key ID at this time

```
CREATE TABLE `table_name` (
  `r1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `r2` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `r3` enum('A','B','C') NOT NULL DEFAULT 'A',
  `r4` varchar(255) DEFAULT NULL,
  `r5` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`r1`,`r2`,`r3`),
  KEY `table_name_001` (`r2`),
  KEY `table_name_002` (`r5`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

and I can't modify the table

Thanks

**Comment by soyuka** [comment]
Composite are accessible like this: `/entity/r1=1;r2=1;r3=1`

**Comment by backbone87** [comment]
is there any way to change this?
i would love to create api resources for URLs like `/parent/{parent_id}/child/{child_id}`

**Comment by soyuka** [comment]
Could you be more precise @backbone87 ?

**Comment by backbone87** [comment]
Well it applies to basically all 1:n relations with privately owned to-many entities and other things like an attributed n:n.

Example:
- article (id)
- tagdefinition (id)
- tag (article_id, tagdefinition_id, position, created_date)

here tag has a composite foreign primary key.

When i design an API for this (by hand) i would like the following:
- /articles (includes taglist)
- /articles/{id} (includes taglist)
- /tagdefinitions
- /tagdefinitions/{id} 
- /articles/{id}/tags (primarily to insert new tags)
- /articles/{id}/tags/{tagdefinition_id} (primarily to address and delete tags)

**Comment by soyuka** [comment]
Interesting!

The two last routes will not be hard to implement with subresources, I'll try to dig into it! Indeed, if there's already one of the composite key in the endpoint we don't need it twice.

```
POST /articles/{id}/tags 
PUT/DELETE /articles/{id}/tags/{tagdefinition_id}
```

Work needed:
- support `POST`, `PUT`, `DELETE` on subresources (hopefully uses the same WriteListener as usual resources) - works on the last resource part (here tags)
- support composite keys interpretation to allow smarter endpoints

**Comment by Simperfit** [comment]
Thanks @soyuka!

**Comment by jhfyang** [comment]
> Work needed:
> 
> * support `POST`, `PUT`, `DELETE` on subresources (hopefully uses the same WriteListener as usual resources) - works on the last resource part (here tags)
> * support composite keys interpretation to allow smarter endpoints

Has this been done ? Is there any documentation for it ? 

When I call debug:router I do not find any routes for such patterns :

GET /articles/{id}/tags/{tagdefinition_id}
