### ISSUE TITLE
Url array request

### ISSUE THREAD

**Issue by Kasu0708** [api-platform/core#1378]
api-platform/core doesn't recognise the request url of the frontend (react js).

GET http://192.168.6.86:8000/districts/1,/districts/2 404 (Not Found)

But it works if I change manually to 

GET http://192.168.6.86:8000/districts/1,2

**Comment by dunglas** [comment]
It's weird that the 2nd URL give the expected result. There is nothing to filter collections like that currently in core.

Do you have checked https://github.com/api-platform/docs/blob/master/admin/handling-relations-to-collections.md?

**Comment by Simperfit** [comment]
@Kasu0708 If you still need something, feel free to re-open this!
