### ISSUE TITLE
JSON-LD Normalizer cant denormalize IRIs to objects

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1380]
Example call: `$serializer->denormalize('/my-objects/1', MyObject::class, 'jsonld');`
This call just throws some errors (at least when called from within a serialization process).

This problem occured to me, when having an object graph with non ApiResource objects in between. Because for these "normal" objects the default symfony object normalizer is called, it tries to denormalize the object with the above line. When the JSON-LD normalizer denormalizes an IRI, it does not call another subdenormalization, but insteadof does the IRI > object conversion on "his side".

**Comment by Simperfit** [comment]
Could you please provide a reproducer ?

**Comment by soyuka** [comment]
Closing, feel free to ping if you want me to reopen.
