### ISSUE TITLE
Rework & Extract JsonLd serialization into own component

### ISSUE THREAD

**Issue by backbone87** [api-platform/core#1385]
There are several problems with the current JsonLd serialization:
- Relies on ApiResource metadata
- Does not work well with non ApiResources like Embeddables or "normal" entities
- Does not reuse existing json-ld libraries
- Does not provide an easy way to switch between the different json-ld forms: expanded, compact, flattened

From my point of view there are 3 things such a component needs:
- Metadata for things to be serialized, of which type they are and what properties they contain
- A normalizer that translates between PHP-things and expanded json-ld format
- An encoder that takes the expanded json-ld format and reuses existing json-ld tools to produce one of the 3 json-ld document forms (pretty much a noop for expanded form)

I would like to hear some feedback for this first plan and maybe wishes/hints what should be improved compared to the current implementation.

**Comment by backbone87** [comment]
a first question: which json-ld library you guys prefer and/or have experience with already?
- https://github.com/digitalbazaar/php-json-ld
- https://github.com/lanthaler/JsonLD

**Comment by soyuka** [comment]
I don't really use any.

**Comment by dunglas** [comment]
And they have the same number of stars ^^

For our JavaScript libs we use the DigitalBazaar lib (https://github.com/api-platform/api-doc-parser/blob/master/package.json#L34), maybe should be use it in PHP too for consistency?

**Comment by backbone87** [comment]
I have started working on a JSON-LD serializer https://github.com/hofff/json-ld

I am currently working on the normalization process. Feedback is very welcome. (I am also at Symfony Live Berlin, if anyone wants to have a heads-up talk)

**Comment by backbone87** [comment]
Normalization is pretty feature complete for now.
Added a lot of functional tests, PRs for behavioral and/or unit tests are very welcome.

Moving on to metadata inheritance. Since i am not sure about desireable behavior regarding this, i would appreciate feedback very much.

**Comment by soyuka** [comment]
@backbone87 don't hesitate to ping me on PR's on your repository ;).
