### ISSUE TITLE
Getting parent of null

### ISSUE THREAD

**Issue by mcanepa** [api-platform/core#1386]
I'm having an issue when using doctrine's [single table inheritante](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance) and `@ApiResource`.

At first, I thought it was a doctrine issue but I now I think it's related to API Platform, specifically with ApiResource.

I posted an issue [here](https://github.com/doctrine/doctrine2/issues/6656)

Maybe I'm not using the annotations correctly so you guys will decide if this is an actual issue or I'm just using this wrong.

My problem was that when getting a collection for the first level under root level I got this message:

> The discriminator column "type" is missing for "AppBundle\Entity\MyEntity" using the DQL alias "parent_a2".

Code to reproduce:
`MyEntity.php`
```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity
 * @ORM\Table(name="my_entity",indexes={@ORM\Index(name="idx_type_my_entity", columns={"type"})})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "root"            = "Root",
 *     "level_1"         = "Level1",
 *     "level_2"         = "Level2",
 *     "level_3"         = "Level3"
 * })
 *
 * @ApiResource(
 *      attributes={
 *      	"force_eager"=false,
 *          "denormalization_context"={"groups"={"g_write"}},
 *          "normalization_context"={"groups"={"g_read"}}
 *      }
 * )
 */
abstract class MyEntity
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 * @Groups({"g_read"})
	 */
	protected $id;

    /**
	 * @ORM\OneToOne(targetEntity="MyEntity")
	 * @Groups({"g_write", "g_read"})
	 */
	protected $parent;

	/**
	 * @ORM\Column(type="string")
	 * @Assert\Type(type="string")
	 * @Assert\NotBlank()
	 * @Groups({"g_write", "g_read"})
	 */
	protected $name;

	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	public function getId()
	{
		return $this->id;
	}

	public function setParent(MyEntity $parent = null)
	{
		$this->parent = $parent;

		return $this;
	}

	public function getParent()
	{
		return $this->parent;
	}

	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	public function getName()
	{
		return $this->name;
	}
}

```
`Root.php`

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ApiResource(
 *      attributes={
 *          "denormalization_context"={"groups"={"g_write"}},
 *          "normalization_context"={"groups"={"g_read"}}
 *      }
 * )
 */
class Root extends MyEntity {}
```

`Level1.php`

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ApiResource(
 *      attributes={
 *          "denormalization_context"={"groups"={"g_write"}},
 *          "normalization_context"={"groups"={"g_read"}}
 *      }
 * )
 */
class Level1 extends MyEntity {}
```

`Level2.php`

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ApiResource(
 *      attributes={
 *          "denormalization_context"={"groups"={"g_write"}},
 *          "normalization_context"={"groups"={"g_read"}}
 *      }
 * )
 */
class Level2 extends MyEntity {}
```

And so on...

You must end with a table like this one
```
+----+-----------+-------+---------+
| id | parent_id | name  |  type   |
+----+-----------+-------+---------+
|  1 | null      | val_1 | root    |
|  2 | 1         | val_2 | level_1 |
|  3 | 1         | val_3 | level_1 |
|  4 | 1         | val_4 | level_1 |
|  5 | 3         | val_5 | level_2 |
+----+-----------+-------+---------+
```

Now, if you do a GET of level 2 for example, you will get what it's expected, but if you do a GET for level 1, then the error occurs.

For what I've seen in the log for a level 1 resource, it will fetch it's parent (root) and it's parent's parentt (null), hence the error.

What I did to solve it it's to remove this line from Level1.php

`"normalization_context"={"groups"={"g_read"}}`

so the final code would be

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ApiResource(
 *      attributes={
 *          "denormalization_context"={"groups"={"g_write"}}
 *      }
 * )
 */
class Level1 extends MyEntity {}
```

or even

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ApiResource()
 */
class Level1 extends MyEntity {}
```

I'm using ApiResource wrong? Maybe I don't need to redefine context if it's already defined in the base class?

Is it actually an issue?

**Comment by soyuka** [comment]
I'm using simple inheritance without issues but I'm never requesting the `Root` entity (hence the `Abstract`).

May you give us the `Routes` you're calling which are leading to issues? Thanks.

**Comment by mcanepa** [comment]
The hierarchy is: `Root > Level 1 > Level 2 > Level 3 > Level N`

An the issue appear in a simple `GET` for a collection for `Level 1`.

`http://localhost/demo/issue_doctrine/web/app_dev.php/level1s`

or

`curl -X GET "http://localhost/demo/issue_doctrine/web/app_dev.php/level1s" -H  "accept: application/ld+json"`

Use this SQL to generate a table like the one I've posted:
`
INSERT INTO `my_entity` VALUES (1,NULL,'val_1','root'),(2,1,'val_2','level_1'),(3,1,'val_3','level_1'),(4,1,'val_4','level_1'),(5,3,'val_5','level_2');`

**Comment by benjaminrau** [comment]
@mcanepa Thanks for documentation of the issue, it helped me to think that my issue is the same. Also for me the issue occures on root level where relation is null. Did you solve it?

**Comment by soyuka** [comment]
Closing, feel free to ping if you want me to reopen.
