### ISSUE TITLE
question: cURL error 6: Could not resolve host: varnish

### ISSUE THREAD

**Issue by schmanat** [api-platform/core#1389]
I followed the steps descriped in the "Get started" sections of the doc.
I create an Entity and it works, but if i want to POST or PUT an entry I get the following error:

`Uncaught PHP Exception GuzzleHttp\Exception\ConnectException: "cURL error 6: Could not resolve host: 
varnish (see http://curl.haxx.se/libcurl/c/libcurl-errors.html`

In `the app/config/parameter.yml` exists the following configuration

varnish_url:
  - http://varnish

I don't use varnish, is there a possibility to deactivate the varnish entry. The strange thing is, if I create the project (via composer) the Foo Entity exists this Entity works without any errors.

**Comment by dunglas** [comment]
Yes, just remove these lines: https://github.com/api-platform/api-platform/blob/master/app/config/config.yml#L85-L92

**Comment by schmanat** [comment]
great, thanks for your quick support.
