### ISSUE TITLE
@ORM\Embeddable and @ORM\Embedded dosen't seems to work anymore 

### ISSUE THREAD

**Issue by FlorianGirardEIG** [api-platform/core#1392]
Hello all,

I do have 2 Entity who one include the other one with the @ORM\embeddable functionality . 
Since the version 2.1 of the api platform, it doesn't seems to work.

### I have the main Entity 
```php
/**
 * @ApiResource(
 *  attributes={
 *          "jsonld_embed_context"=true,
 *          "normalization_context"={"groups"={"g1"}},
 *          "denormalization_context"={"groups"={"g1"}}
 *  })
 * @ORM\Entity
 */
class Foo
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\Column(type="integer", name="content_type")
     */
    private $id;

    /**
     * @var string Something else
     *
     * @ORM\Column
     * @Groups({"g1"})
     */
    private $bar = '';

    /**
     * @var Suub Other Structured Infos
     * @ORM\Embedded(class = "Suub", columnPrefix = "Suub_")
     * @Groups({"g1"})
     */
    private $suub;

    public function __construct()
    {
      $this->suub = new Suub();
    }

    public function setSuub(Suub $suub)
    {
        $this->suub = $suub;
    }

    public function getSuub() : Suub
    {
        return $this->suub;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getBar() : string
    {
        return $this->bar;
    }

    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```
### The Embeddable entity
```php
namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups as Groups;
/**
 * @ORM\Embeddable
 * @ApiResource()
 */
class Suub
{
    /**
     * @var string Something else
     * @ORM\Column
     * @Groups({"g1"})
     */
    private $bar = '';

    public function getBar() : string
    {
        return $this->bar;
    }

    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```
It looks like it's all correct:
```json
[
  {
    "bar": "string",
    "suub": {
      "bar": "string"
    }
  }
]
```
But since 2.1 I get this error:

`` Unable to generate an IRI for the item of type \"AppBundle\\Entity\\Suub\" ``

I'm doing this because I need to have a certain Json structure and not having N tables with 1..1 relations. If you have any other idea I'm all ears.

**Comment by backbone87** [comment]
the @ApiResource shouldnt be on the embeddable and you need to define the jsonld context yourself on the parent entity for the embeddable (if you want to use jsonld)

**Comment by FlorianGirardEIG** [comment]
Hello,

You're right @apiresource should not be on the embeddable (I was playing around).
But the second option solved the issue for me. I didn't want to use jsonld but I haven't exclude it from error_formats in config.yml

So I've changed to "jsonld_embed_context"=false, and updated my config.yml

```php
//app/config/config.yml
framework:
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
```
Thanks you a lot!!! 

Have a nice weekend!

**Comment by backbone87** [comment]
np, please close this issue too

**Comment by etomilin** [comment]
This thread is a bit confusing. What is the proper way to use Doctrine Embeddables with Api Platform 2.1?
I've tried it both ways:
1. without declaring Embeddable class as an ApiResource
2. with declaring Embeddable class as an ApiResource with no actions

In first scenario Swagger documentation was not generating correctly (Embeddable was represented as a string in Models/Examples).
In second scenario Swagger documentation worked correctly, but requests were failing because of "Unable to generate an IRI for the item of type..." errors.

**Comment by backbone87** [comment]
the first approach is the correct one. but the swagger documentation generator doesnt has the feature to generate detailed schemas for embeddables (PRs welcome), but you can define the swagger documentation for the embeddable per hand (in the @ApiProperty in the @Entity where you use the @Embedded)
