### ISSUE TITLE
[Documentation] Create Documentation for Custom Action/Controller

### ISSUE THREAD

**Issue by ad3n** [api-platform/core#1393]
When we create an action that not covered by Api Platform (`https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers`) we need to create documentation depending on filter(s) and or parameter(s).

I try to use `ApiDoc` (cause we use NelmioApiDoc) but we have an error (action/method not registered). 

How to add more documentation for custom action?

Thanks

**Comment by Simperfit** [comment]
You could follow this link in order to document [custom action with swagger](
https://github.com/api-platform/core/issues/1067).

For the part with nelmio, could you please provide a way to reproduce ?

**Comment by raziel057** [comment]
Hi,

Currently @ApiResource annotation is checked in path:

    $dirname.'/Entity'
    $dirname.'/Resources/config/api_resources'.$extension

When you wants to add custom routes not directly linked to any entity, you can create a custom Action but the route is not visible in Swagger documentation. It would be great to allow the addition of @ApiResource to be able to document the route at the Action / Controller level.

So maybe it could be interesting to also fetch the following folders:

    $dirname.'/Action'
    $dirname.'/Controller'

**Comment by vlefort** [comment]
Hi,

Some news about this ?

I have the same case with custom route witch is not present in doc.

Regards,

**Comment by timotheemoulin** [comment]
Hi,
any news about it? That would be great if we could document our custom endpoints.
Cheers

**Comment by dunglas** [comment]
Use https://api-platform.com/docs/core/swagger/#overriding-the-swagger-documentation

**Comment by auipga** [comment]
https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification
(The anchor changed)
