### ISSUE TITLE
Error at the installation : non-existent service api_platform.http_cache.purger

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1394]
Hello,

When I try to install a new version of AP 2.1.1, I've got this error : 

> [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
>   The service "api_platform.doctrine.listener.http_cache.purge" has a dependency on a non-existent service "api_platform.http_cache.purger".

In `src\Bridge\Symfony\Bundle\Resources\config` I've got only `api_platform.http_cache.purger.varnish_client` and `api_platform.http_cache.purger.varnish`.

Note : I don't want to use varnish so in parameters, I have `varnish_urls: []`

Thanks for your work !

**Comment by dunglas** [comment]
Can you try to just delete those lines https://github.com/api-platform/api-platform/blob/master/app/config/config.yml#L86-L88 ?

**Comment by pierre-H** [comment]
@dunglas thank you : now there is no error
