### ISSUE TITLE
Custom collection route - HTTP status code

### ISSUE THREAD

**Issue by GonZOO82** [api-platform/core#1398]
Hi, I create the new custom collection route with POST method.
My problem is that the answer is always 201 (created), but I don't create new item, I checking the user password with email password parameters.

```
{
   "email": "aaa@bbb.cc",
   "password": "myPassword"
}
```

How to change the response code in custom route?

**Comment by meyerbaptiste** [comment]
You have to return your own `Response` instance in your controller instead of an array or something else.

**Comment by Taluu** [comment]
Bumping this ticket (should I open a new one ?), as `POST` does not always mean 201. See https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5

Could open a PR if interested ?

**Comment by teohhanhui** [comment]
@Taluu RFC 2616 is obsolete: https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead

**Comment by teohhanhui** [comment]
But yes, you're right. `POST` does not always return `201` as the successful status code. That said, this issue is about custom operations, so I don't think it's a problem for us.

**Comment by Taluu** [comment]
Not only for custom operations actually, could be useful for classic operations. Such as adding a `status_code` or something like that on the operation's config ?

**Comment by matlar83** [comment]
> Hmm... Indeed we should support overriding the HTTP status code.

I agree with you: should be possible in custom operations to override success HTTP status code

**Comment by soyuka** [comment]
We now have a `status=202` option.

**Comment by gustawdaniel** [comment]
Example of usage, when sending `manifest` not save it in database 

> src/Entity/Manifest.php

```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(
 *     collectionOperations={
 *          "post"={
 *               "path"="/manifest",
 *               "status"=200,
 *          }
 *      },
 *     itemOperations={"get"={"method"="GET"}}
 * )
 */
class Manifest
{
    /**
     * @ApiProperty(identifier=true)
     * @Assert\EqualTo("uploadAnnouncement")
     */
    private $type;

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;
        return $this;
    }
}
```
