### ISSUE TITLE
[Meta][Low priority] Using JSON Schema $ref in Behat tests

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1399]
With `justinrainbow/json-schema` 5.2.4+ (which is default in current `behatch/contexts` master), [you can use JSON Schema's `$ref`](https://github.com/dkarlovi/json-schema-behat-external-ref/blob/master/features/my.feature#L57-L65) to import external schema fragments, which should make current feature files much more readable.

Something to think about in the long run.

**Comment by dunglas** [comment]
Would be great!

**Comment by meyerbaptiste** [comment]
I wait for a stable version of `behatch/contexts` with this change for months...

**Comment by dkarlovi** [comment]
As you're a "rising star" project owners, might want to try and get them to tag something usable soonish. I'm already using master on my API Platform app and it works without any changes (at least for my scope).

**Comment by Simperfit** [comment]
We are using $ref now, this can be closed.
