### ISSUE TITLE
Why no cache on API doc Hydra generation ?

### ISSUE THREAD

**Issue by fmata** [api-platform/core#1404]
Hi,

In order to speed up our app which uses api-platform intensively, we try to cache everything and we use HTTP cache with Varnish.

But one question : why the API doc Hydra is not cached ? In our app it takes each times ~1s to generate in jsonld.

Could you accept a PR which adds a cache for API doc Hydra and an invalidation when the metadata are updated ?

**Comment by dunglas** [comment]
Yes it's a miss, the Hydra endpoint should respect values set in the `cache` config section.

**Comment by fmata** [comment]
This endpoint does not depend on a resource but on all definitions/mappings information.

Do you have an insight where I can plug the invalidation ?

Maybe in a cache warmer, WDYT ?

**Comment by sroze** [comment]
I'd completely agree this should be cached. As you mentioned the invalidation is here a tricky point... should a cache warmer talk to Varnish? Not sure about this one 🤔 

Maybe just following the `cache` configuration is enough, and invalidation of this documentation is down to the user.

**Comment by fmata** [comment]
@dunglas @sroze see PR #1437
