### ISSUE TITLE
Extending JSON-LD context in doc

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1408]
Hello,

I'd like to extend the JSON-LD context like described [here](https://www.api-platform.com/docs/core/extending-jsonld-context) but for the documentation (http://my-api/docs.jsonld). I find my properties in the context of the entity but not in the documentation.

I need that for the client-generator : I want to create a generator with more validation rules (generated from for example [PropertyValueSpecification](http://schema.org/PropertyValueSpecification), with the `valuePattern` property) and the only way I see is to extend JSON-LD context in the doc .

Thank you again for your work

**Comment by pierre-H** [comment]
See PR

**Comment by Simperfit** [comment]
The issue will be closed if we merge the PR or find an another to deal with that.
