### ISSUE TITLE
CollectionDataProviderInterface does not play well with generators

### ISSUE THREAD

**Issue by greg0ire** [api-platform/core#1422]
I tried implementing it with generators, and it worked just fine... until... I implemented a second.

The problem is here:

https://github.com/api-platform/core/blob/020dbf21246bc7acbd8c417e0ab64bddafcadf3b/src/DataProvider/ChainCollectionDataProvider.php#L38-L48

Here is what my implementation looks like:

```php
    public function getCollection(string $resourceClass, string $operationName = null)
    {
        if ($resourceClass !== Person::class) {
            throw new ResourceClassNotSupportedException();
        }

       yield $aPerson;
```

The ChainCollectionDataProvider will loop over my providers, and will immediatly return the generator returned by the first data provider because no code is executed until the generator is used inside a foreach, which happens later in the code, outside the try / catch block.

The solution would be to introduce a `supports` method in the interface.

**Comment by meyerbaptiste** [comment]
Fixed by #1429.
