### ISSUE TITLE
How to avoid updating a field, but keep creating it. (filter field in PUT / POST operation)

### ISSUE THREAD

**Issue by MLKiiwy** [api-platform/core#143]
It's a real question and maybe the "Hydra vocab" is the reason that block this feature.

My problem is simple : 
I want create a resource with two fields, but one of this two field cannot be updatable. (authorize two field on POST but one field on PUT operation).

Actually Normalization/Denormalization is shared between operation because the vocabulary is shared between operations and a property is only : read or write (not read, write-in-creation, write-in-update)

So, how to deal with this problem ? 
Maybe ask this question on Hydra ML ?

**Comment by dunglas** [comment]
Here is a thread speaking about that: https://lists.w3.org/Archives/Public/public-hydra/2015Jun/0018.html
You can still do what you want with a custom normalizer or a custom controller.
