### ISSUE TITLE
Invalid Doctrine Query on Nested Subresources

### ISSUE THREAD

**Issue by mab05k** [api-platform/core#1442]
I have a hierarchy of resources with OneToMany relationships between all: Large => Medium => Small => Tiny and I apply "subresource" annotations to all of them. This configuration creates all combinations of routes:

```
"Collection Operations"
/api/larges
/api/larges/{id}/mediums
/api/large/{id}/mediums/{mediums}/smalls
/api/large/{id}/mediums/{mediums}/smalls/{smalls}/tinies
/api/mediums
/api/mediums/{id}/smalls
/api/mediums/{id}/smalls/{smalls}/tinies
/api/smalls
/api/smalls/{id}/tinies
```

These extended route hierarchies return 500 errors.  The problem occurs when API Platform recursively creates the subqueries for these relationships. 

For example: /api/large/{id}/mediums/{mediums}/smalls/{smalls}/tinies creates the following query:

```mysql
SELECT o 
FROM AppBundle\\Entity\\Tiny o 
WHERE 
	o.smalls 
IN (
	SELECT smalls_a1 
	FROM AppBundle\\Entity\\Small smalls_a1 
	WHERE small_a1.id = :id_p1 AND smalls_a1.medium 
	IN(
		SELECT mediums_a2 
		FROM AppBundle\\Entity\\Medium mediums_a2 
		WHERE mediums_a2.id = :id_p2
         ) 

	AND mediums_a2.large 
	IN(
		SELECT id_a3 
		FROM AppBundle\\Entity\\Large id_a3 
		WHERE id_a3.id = :id_p3
        )
);
```

The query SHOULD look like this:
```mysql
SELECT o 
FROM AppBundle\\Entity\\Tiny o 
WHERE 
	o.smalls 
IN (
	SELECT smalls_a1 
	FROM AppBundle\\Entity\\Small smalls_a1 
	WHERE small_a1.id = :id_p1 AND smalls_a1.medium 
	IN(
		SELECT mediums_a2 
		FROM AppBundle\\Entity\\Medium mediums_a2 
		WHERE mediums_a2.id = :id_p2 AND mediums_a2.large 
        	IN(
	        	SELECT id_a3 
	        	FROM AppBundle\\Entity\\Large id_a3 
	        	WHERE id_a3.id = :id_p3
                )
         ) 
);
```

The issue here is the "AND mediums_a2.large" portion of the query is not nested properly and is out of scope because it was defined within the previous "IN" statement, and throws a Doctrine out of scope exception. This error occurs in the SubresourceDataProvider (src/Bridge/Doctrine/ORM/SubresourceDataProvider.php:146). The function that should recursively create these nested queries is limited to going 2x subresources deep. This function needs to be enhanced to support additional nested subresources.

This issue brings up another question:
```
This seems unnecessary:
/api/large/{id}/mediums/{mediums}/smalls/{smalls}/tinies

These should be sufficient:
/api/smalls/{id}/tinies
```
Should API Platform be generating all the additional routes? Or should it be able to support the deep nesting of relationship subresources?

**Comment by soyuka** [comment]
Sorry for the long response time!

```
/api/smalls/{id}/tinies
```

This should be possible by adding a `Subresource` on the `tiny` property of the `Small` resource.

About the above query, I think that you're right and there is a bug as the query is not recursive. Please don't hesitate to send a patch about this! I'll try to work on this ASAP but this may be in a couple of weeks...

 > Should API Platform be generating all the additional routes? Or should it be able to support the deep nesting of relationship subresources?

We already have some requests about this and subresources need to be improved in order to:
  - allow to generate only subresources we need (https://github.com/api-platform/core/issues/1371#issuecomment-332904383)
  - https://github.com/api-platform/core/issues/1376#issuecomment-330137535 improve DX with composite identifiers

**Comment by alanpoulain** [comment]
I'm working on this.

**Comment by meyerbaptiste** [comment]
Fixed by https://github.com/api-platform/core/pull/1608.
