### ISSUE TITLE
Extensions against RESTful conventions + cacheing issues?

### ISSUE THREAD

**Issue by sverraest** [api-platform/core#1448]
Looking at the documentation for extensions is being used to filter a list or items based on the token . Isn't this against the convention of not manipulating RESTful resources / lists by meta data? 

For example, using the extension to filter by current user
`GET /api/offers`
would yield different results based on the token which makes it impossible to cache.

Is there a build-in way to do this as follows:
`GET /api/offers?user_id=:id`
Where you can pick up the user_id and verify it against an ACL.
An additional requirement would be making this user_id filter required in most cases.

Another solution would be creating a custom route `/api/users/:user_id/offers` I guess and apply the :user_id against an ACL in a listener there?

**Comment by dunglas** [comment]
If the `Vary` header is set accordingly (`Vary: Authorization` for instance), it's perfectly valid regarding the HTTP spec. We should update the docs to make it bold.

> Is there a build-in way to do this as follows:
> GET /api/offers?user_id=:id
> Where you can pick up the user_id and verify it against an ACL.
> An additional requirement would be making this user_id filter required in most cases.

Yes, (I alway use this strategy myself, I also find it more RESTish):

* Add the search filter on the `user` property: https://api-platform.com/docs/core/filters#search-filter
* Add an event listener that throw if a filter is not applied: https://api-platform.com/docs/core/events (it can also be implemented as an extension)

It would be nice to add a doc entry about that.

> Another solution would be creating a custom route /api/users/:user_id/offers I guess and apply the :user_id against an ACL in a listener there?

You can probably do it with subresources + the security system:

* https://api-platform.com/docs/core/operations
* https://api-platform.com/docs/core/security

But I never tried by myself.

**Comment by sverraest** [comment]
Thanks @dunglas for the quick reply as always.
I'll play around with it and afterwards will try to do a PR against the documentation.

**Comment by Simperfit** [comment]
This seems resolved, please if you can create a Documentation PR, that will be awesome!
