### ISSUE TITLE
Filters not doing optimal query

### ISSUE THREAD

**Issue by julienpillias** [api-platform/core#1457]
Hi team.
Having a strange behaviour with a filter => Filter is not doing the right query.

In my case I have 3 entities : User, Project, and ticket

Project has multiple tickets
Project has 2 user (one "customer", and one "EA team") <= this may be the pb for API Platform

All files on gist : https://gist.github.com/julienpillias/2d0d05a127a5018c5714b476196078b1

requesting this :
```
/tickets?project.EAteamUser.id=89
```

And having a strange SQL :
```sql
SELECT DISTINCT t0_.id AS id_0, t0_.id AS id_1
FROM ticket t0_
INNER JOIN project p1_ ON t0_.project_id = p1_.id
INNER JOIN user u2_ ON p1_.eateam_user_id = u2_.id
LEFT JOIN project p3_ ON t0_.project_id = p3_.id
WHERE t0_.id IN (
SELECT t4_.id FROM ticket t4_
INNER JOIN project p5_ ON t4_.project_id = p5_.id
INNER JOIN user u6_ ON p5_.eateam_user_id = u6_.id
WHERE u6_.id = '89')
AND p3_.customer_id = 89
ORDER BY t0_.id ASC LIMIT 30 OFFSET 0;
```

I was waiting something like this :
```sql
SELECT DISTINCT t0_.id AS id_0, t0_.id AS id_1
FROM ticket t0_
INNER JOIN project p1_ ON t0_.project_id = p1_.id
WHERE p1_.eateam_user_id = 89
ORDER BY t0_.id ASC LIMIT 30 OFFSET 0;
```

So 2 pb here :
 - to much joins (their are some issues about this)
 - having a WHERE on customer_id instead of eateam_user_id !
Is that an API pltform bug, or did i do something bad ?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/944 may be related

**Comment by meyerbaptiste** [comment]
It would be nice to have a small project to reproduce this query for easy debugging!

**Comment by sroze** [comment]
Giving it a go

**Comment by julienpillias** [comment]
OK, I'll try to do this in 3-4 hours.

Just need a repo with minimum configuration, or do you want something specific ?

**Comment by sroze** [comment]
An application that we can run, and reproduce the problem with would be ideal.

**Comment by sroze** [comment]
In [this repository](https://github.com/sroze/api-platform-issue-1457) I can reproduce the inner query but can't reproduce the issue with the extra `AND p3_.customer_id = 89`...

**Comment by julienpillias** [comment]
I'm working on a new minimalist repo to reproduce bug. Hope it will be ready in 1 - 2 hours

**Comment by julienpillias** [comment]
Ok, so just seen that I was not up to date :/
composer update : 
...
Updating api-platform/core (v2.1.1 => v2.1.2)
...

Now, i have the excepted result (no more extra AND p3_.customer_id = 89... ) , but SQL seems not so good (using sub query) : 
```sql
SELECT 
   count(DISTINCT t0_.id) AS sclr_0 
FROM ticket t0_ 
INNER JOIN project p1_ 
    ON t0_.project_id = p1_.id 
WHERE t0_.id IN ( 
    SELECT t2_.id FROM ticket t2_ 
     INNER JOIN project p3_ 
          ON t2_.project_id = p3_.id 
     WHERE p3_.eateam_user_id = '87'
);
```

**Comment by sroze** [comment]
You're right, this could be optimised, but at least it's not a bug (anymore?). PR is welcome 👍

**Comment by soyuka** [comment]
Queries can always be optimised according to the use case. We're using a variant of EagerLoading that benefits from our ResourceMetadata and it's Serialization systems but it's really hard to have clean and optimized queries for every use case. IMHO if you want a perfect query there are no better way then doing a custom DataProvider :).

**Comment by backbone87** [comment]
This is a static subquery that only operates on PKs and FKs and both should be indexed. So the cost of this subquery is minimal and removing it probably only gains a few dozen mircoseconds. Not all subqueries are "evil" and using static subqueries makes dynamic sql scenarios like this much more clean.

The kind of subqueries you want to look out for from a performance standpoint are [dependant subqueries](https://www.google.de/search?q=dependant+subquery), which *can* be problematic

**Comment by julienpillias** [comment]
For this speciefic project should not be a problem. But for an other project, we have bigggg tables with about a million rows... (with a great hardware)  
Will check this later :)

**Comment by soyuka** [comment]
@julienpillias any news?

**Comment by julienpillias** [comment]
Hi,

As soyuka says, it's not a bug (Subqueries are to prevent a bug that took out the filtered relation instead of just filtering by the relation). So i did not dig in.
Maybe on the next project (will start next year) :-)

Still using apiPlatform, and all is fine, excpet maybe swagger wich is very long to open, and sometime crash chrome... But this may be a swagger pb, not ApiPlatform

**Comment by soyuka** [comment]
> Still using apiPlatform, and all is fine, excpet maybe swagger wich is very long to open, and sometime crash chrome... But this may be a swagger pb, not ApiPlatform

Haha :laughing: I feel you men, I can NOT open the swagger UI on my computer (I have only 534 routes)!

**Comment by jderusse** [comment]
I've the same issue with a "many to one" relation.
in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L65 we check only if the query have a `join` relation. Will we probably should check if we have a `join to many` relation. Like we do in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L337

**Comment by stephanvierkant** [comment]
Same issue here. A (pseudo-code) `FROM Foo WHERE Foo.id IN (SELECT id FROM Foo ..)` isn't optimal.

@soyuka Why did you close this issue? I think this is still an issue.

**Comment by teohhanhui** [comment]
@stephanvierkant Can you open a new issue to explain the problem in full? This issue is too old, too much has changed since then.
