### ISSUE TITLE
[ASK] How to manage virtual property

### ISSUE THREAD

**Issue by ad3n** [api-platform/core#1459]
How to manage virtual property that not managed by Doctrine and not registered in metadata.

I got ```No resource class found``` error when using virtual property containing object.

Thanks

**Comment by soyuka** [comment]
Declaring them manually as a resource property through the metadata should suffice.

**Comment by ad3n** [comment]
hhhmmm i don't want to make it persistence. I just need to setting up on post load... It is possible to do it?

**Comment by soyuka** [comment]
Can you give an example? I'm not sure to follow.

```php

class Entity
{
  /**
   * To me this is a virtual property and will get serialized.
   * @ApiProperty 
   */
  public $foo;
}
```

**Comment by ad3n** [comment]
Ah thank you... I don't know about that annotation... Thank you so much

**Comment by tezvi** [comment]
Sorry for resurrecting an old thread, are api-platform filters available for properties decorated by ApiProperty annotation, like in previous example?

**Comment by soyuka** [comment]
Not really because most of the filters are tied to doctrine (PropertyFilter and GroupFilter should work). Use a custom filter, it'll work :).

**Comment by tezvi** [comment]
ok thx :)
