### ISSUE TITLE
How to deal with large request url in filters?

### ISSUE THREAD

**Issue by ivaaaan** [api-platform/core#1463]
I have a simple entiy `User`:

```php
/**
 * User
 *
 * @ORM\Entity()
 * @UniqueEntity(fields="username", message="Username is already exist.")
 *
 * @ApiResource(
 *     collectionOperations={
 *         "get"={"method"="GET", "filters"={UsersFilters::class}},
 *         "post"={"method"="POST"},
 *     },
 *     itemOperations={
 *         "get"={"method"="GET"},
 *         "put"={"method"="PUT"},
 *     },
 *     attributes={
 *         "normalization_context"={"groups"={"user", "subscriptions"}},
 *         "denormalization_context"={"groups"={"user"}},
 *     }
 * )
 */
class User
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Username should not be blank.")
     *
     * @Groups({"user", "subscription"})
     */
    private $username;
}
```

And it's works fine with: `GET /api/v1/users?username[0]=123&username[1]=1234124`. But when we have 150+ usernames in url obviously I will get error like "Request URL too large". Solution is also obviously: I need to change filter action from `GET` to `POST` and pass parameters to `POST` body. So how I can simple override default `GET` filter?

**Comment by ivaaaan** [comment]
I'm trying this:
```
 * @ApiResource(
 *     collectionOperations={
 *         "get"={"method"="POST", "filters"={UsersFilters::class}}
 *     },
....
```

And in my `UsersFilter`:
```
    protected function extractProperties(Request $request/*, string $resourceClass*/): array
    {
        return json_decode($request->getContent(), true);
    }
```

But its still trying to create user on POST, not filter.

**Comment by jdeniau** [comment]
You may have a little architecture problem here, it seems weird to filter 150 users.

You may address it by creating a custom filter. 

If you really want to stick to the post request, you can eventually create a new route. That's not really REST friendly but it will work fine. 

 Another way is to have a custom route matcher like searching in the request objet the content of your body like explained [here] (http://symfony.com/doc/3.4/routing/conditions.html)
Another way is to send a body to your "GET" request but I don't know if it is supported by symfony

**Comment by Simperfit** [comment]
Closing as we got no feedback from OP.
