### ISSUE TITLE
Add support for bundleless entities

### ISSUE THREAD

**Issue by codedmonkey** [api-platform/core#1484]
Shouldn't need any comment, Symfony 4 is based on the concept of bundleless applications, yet my entities can only be discovered through a bundle according to the documentation. Please support this, it would be much appreciated.

**Comment by meyerbaptiste** [comment]
This is already supported, see #1271. For example: https://github.com/symfony/recipes/blob/master/api-platform/core/2.1/config/packages/api_platform.yaml

**Comment by codedmonkey** [comment]
Thank you so much, was looking for an hour, didn't figure it would be so easy.
