### ISSUE TITLE
Error GET on ManyToOne relation, field "is already defined"

### ISSUE THREAD

**Issue by guilhemVB** [api-platform/core#1490]
Hi,

I've a ManyToOne relation between entity Stage and entity Voyage (a Voyage have many Stage), and when I send a GET request to a specific Stage, I've the following error :

`"hydra:description": "[Semantical Error] line 0, col 86 near 'voyage WHERE': Error: 'voyage' is already defined.",`
Te complet error trace : [error field is already defined.txt](https://github.com/api-platform/core/files/1466508/error.field.is.already.defined.txt)

I use Api platform v2.1.1. The two entities : Stage : https://github.com/guilhemVB/api-lms/blob/master/src/AppBundle/Entity/Stage.php#L44 and Voyage : https://github.com/guilhemVB/api-lms/blob/master/src/AppBundle/Entity/Voyage.php#L99

$voyage attribute is not supposed to appear on serialize Stage object, because $voyage is not in normalization_context group.

Am I doing something wrong ? Do you have any idea ?

Maybe related to https://github.com/api-platform/core/issues/1017

Thanks
Guilhem

**Comment by soyuka** [comment]
They are some unreleased patches that could apply there. Could you try to use the [2.1 branch ?](https://github.com/api-platform/core/tree/2.1)

**Comment by guilhemVB** [comment]
I tried, but same error.

**Comment by guilhemVB** [comment]
I found the problem : I had a Custom extensions loaded twice. That's why I hadsame where clause twice.
