### ISSUE TITLE
Support filtering on json columns

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#1496]

**Comment by soyuka** [comment]
Meaning? Shouldn't that be a `JsonFilter`?

**Comment by norkunas** [comment]
In apip there is no way to serialize different entities props using single table inheritance so to avoid it I am using json column so I need to have a way to filter those entities based on data in json column :)

**Comment by soyuka** [comment]
You'd have to build your own filter IMO. "SearchJsonFilter" or something like this. OIthers may also be interested?

**Comment by norkunas** [comment]
Yes, I know, but would be nice to have this in core :)

**Comment by Simperfit** [comment]
Do we want this in core @api-platform/core-team ?

**Comment by sroze** [comment]
I'd say so.

**Comment by alanpoulain** [comment]
See: https://github.com/api-platform/core/issues/2274
