### ISSUE TITLE
Metadata YamlExtractor incompatible with Symfony4

### ISSUE THREAD

**Issue by cristi-contiu** [api-platform/core#1497]
Hello everyone.

I ran into an issue using the [YAML format mapping](https://api-platform.com/docs/core/getting-started#mapping-the-entities) on a Symfony4 project: The [Metadata YamlExtractor](https://github.com/api-platform/core/blob/master/src/Metadata/Extractor/YamlExtractor.php#L35) uses the `Yaml::PARSE_KEYS_AS_STRINGS` constant, which, according to the Symfony upgrade guides was [deprecated in Symfony 3.4](https://github.com/symfony/symfony/blob/master/UPGRADE-3.4.md#yaml) and [removed in Symfony 4](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#yaml).

Annotation mappings work just fine.

From the upgrade guides, it looks like it's enough to remove the use of this constant and keep only the `Yaml::PARSE_CONSTANT` but I am not sure how this will play out regarding compatibility with older versions of symfony/yaml.

Thank you

**Comment by dunglas** [comment]
Fixed in #1497.
