### ISSUE TITLE
I18n support (translations, etc)

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1506]
What would be a good way to go forward with internationalization of my resources, asssuming I'm using [Atlantic18/DoctrineExtensions](https://github.com/Atlantic18/DoctrineExtensions) (via [stof/StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle))?

This was discussed in #127 where @MLKiiwy linked to [his fork](https://github.com/MLKiiwy/DunglasApiBundle/tree/tdd-i18n-support). Does this still look relevant to you (with newer versions/features released), was the direction he was going OK from API Platform's POV?

What would be solid next steps here?

**Comment by binhle410** [comment]
If you want i18n with Doctrine, I suggest using KNP DoctrineBehaviors. It has better support for the translation to be put in a separate row and table.

**Comment by tahirm** [comment]
any update on this?
Im also looking for recommended setup for i18n with api-platform.

**Comment by pvgnd** [comment]
+1

**Comment by zolex** [comment]
+1

**Comment by beyer-johannes** [comment]
+1

**Comment by teohhanhui** [comment]
I don't see how this is specific to API Platform. But it'd be good to have a doc entry for i18n...

**Comment by alanpoulain** [comment]
Closed in favor of: https://github.com/api-platform/docs/issues/600
