### ISSUE TITLE
[question] Best practice way to filter something belonging to current user

### ISSUE THREAD

**Issue by andrewtch** [api-platform/core#1511]
Hello,

as I understand the subj can me implemented with custom `DataProvider`, `Filters` or `Events`, and I can integrate numerous `Auth` bundles, but what is the best-practice way to do this in a Symfony app?

To explain it more, for example, I have `User` that have multiple `Orders`. `User` is identified by `Bearer token`.

The expected result is, that when I access `GET /orders` with no bearer token, I should get `403`; when I have a valid token, I should get a list of orders belonging to authenticated user. It should not be possible for a `User` to get all `Orders` at all.

How should this be done properly? 

Thanks!

**Comment by norkunas** [comment]
Hey, you're looking for this https://api-platform.com/docs/core/extensions :)

**Comment by andrewtch** [comment]
Thanks!

**Comment by blump** [comment]
I come back to this question. What annoys me with this extension method to return a different collection per user is the management of the cache that can be heavy behind and make that orders never returns the same thing.

For example, if we create a route / orders / {userId} / user, it is better for the cache and also to respect a little more REST. By cons it's more boring to implement.

Which solution do you prefer? I'm wondering
