### ISSUE TITLE
[Serializer] Streamlined context management

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1526]
Currently, serializer context is [quite simple by default](https://github.com/api-platform/core/blob/master/src/Serializer/ContextTrait.php#L31-L37) which prevents from doing certain things:

1. setting app-wide settings (for example, `allow_extra_attributes=false` as in #1217)
2. setting resource-wide settings
3. setting request-specific settings (for example, setting per-user / OAuth client `timezone` for DateTime (de)normalization)

IMO it would make sense to provide a way to build a context, maybe with a new service tag? WDYT?

**Comment by soyuka** [comment]
What about overriding SerializerContextBuilder?

**Comment by dkarlovi** [comment]
It gets complex as you want to add resource-specific contexts.

It does make it somewhat possible, but it's not great. @dunglas agreed: https://github.com/api-platform/core/issues/1217#issuecomment-341690511

**Comment by dunglas** [comment]
This has been fixed (at least partially) by https://github.com/api-platform/core/pull/3151
