### ISSUE TITLE
GraphQL with relay js compability

### ISSUE THREAD

**Issue by bitcoinporn** [api-platform/core#1531]
I checked latest commit regarding GraphQL...it very nice.

Will be more better if we can support relay js, here is relay specs: https://facebook.github.io/relay/docs/graphql-relay-specification.html

can't wait this feature.
Can we extends mutation or query for individual Entity?

**Comment by dunglas** [comment]
Hi,

Implementing the relay spec is on our todo list (it's already done for pagination). PRs are welcome (just let us know if you start working on something by opening an issue to not duplicate the work)!

**Comment by bitcoinporn** [comment]
Nice knowing it on todo list.

I'm not really understand well api-platform core yet....tried to play on it. 
Trying to implements filters from "filters"={...} , but no luck yet. Still trying to understand how core work

**Comment by Simperfit** [comment]
I think we are implementing the realy spec, @bitcoinporn could you please check again ?

**Comment by matigda** [comment]
Hey, I can't really get field "hasPreviousPage" in my graphql API. And that causes issues when using Relay on the frontend part. Is there any flag I have to set up or should it work out of the box?
