### ISSUE TITLE
SQL could be improved for OnToMany relation

### ISSUE THREAD

**Issue by raziel057** [api-platform/core#1553]
I have an entity with ``OnToMany`` relation:

```php
/**
 * TimeSlot
 *
 * @ApiResource
 * @ORM\Entity
 */
class TimeSlot
{
   ...

    /**
     * @var \Doctrine\Common\Collections\Collection of Period
     *
     * Bidirectional - One-To-Many (INVERSE SIDE)
     *
     * @ORM\OneToMany(targetEntity="Period", mappedBy="timeSlot", indexBy="number")
     */
    private $periods;
```

When I call the api ``GET /api/time_slots`` to retrieve the list of timeslots, I got the following json, which is correct:
```json
[
  {
    "id": 1,
    "periods": [
      "/app_dev.php/api/periods/1"
    ]
  },
  {
    "id": 2,
    "periods": [
      "/app_dev.php/api/periods/2"
    ]
    ...
  }
]
```

But the SQL generated is:
SELECT t0_.id AS id_0, ... FROM time_slot t0_ WHERE t0_.id IN (?) ORDER BY t0_.id ASC;
SELECT t0.id AS id_1, ... FROM period t0 WHERE t0.time_slot_id = 1;
SELECT t0.id AS id_1, ... FROM period t0 WHERE t0.time_slot_id = 2;
...

So as you can see, we create one request by item of the collection rather than joining from the main request. Is it normal?

**Comment by backbone87** [comment]
You can use EAGER loading of the association. If you dont want to eagerly load per default, then there is also an extension for the doctrine provider.

**Comment by raziel057** [comment]
yes in fact I would like to load only for some serialization groups (not by adding a ``fetch="EAGER"`` at ORM mapping level). Could you provide more info on the extension for Doctrine Provider?

**Comment by backbone87** [comment]
https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Util/EagerLoadingTrait.php

**Comment by soyuka** [comment]
We have our own EagerLoadingExtension

Be sure to declare serialization groups on the relation so that the query can do the correct optimizations.

**Comment by raziel057** [comment]
Ok thanks!
