### ISSUE TITLE
Autowiring Doctrine ORM Extension lead to deprecated

### ISSUE THREAD

**Issue by raziel057** [api-platform/core#1556]
I created a specific action that use a FilterExtension as you can see on the code bellow:

```php
final class TicketAmountAction
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager, FilterExtension $filterExtension)
    {
        $this->entityManager = $entityManager;
        $this->filterExtension = $filterExtension;
    }

    /**
     * @Route("/services/tickets/amount", name="api_ticket_amount")
     * @Method({"GET"})
     */
    public function __invoke(string $status)
    {
        $qb = $this->entityManager->createQueryBuilder()
            ->select('sum(o.price)')
            ->from(Ticket::class, 'o');

        $this->filterExtension->applyToCollection($qb, new QueryNameGenerator(), Ticket::class);

        $amount = (int) $qb->getQuery()->getSingleScalarResult();

        return new JsonResponse($amount);
    }
}
```

But Symfony throw a deprecation exception:

``
Autowiring services based on the  types they implement is deprecated since Symfony 3.3 and won't be  supported in version 4.0. You should rename (or alias) the "api_platform.doctrine.orm.query_extension.filter" service to "ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension" instead.
``

As a workarround, I can declare the following service in my app:
```yaml
services:
    ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension:
        alias: api_platform.doctrine.orm.query_extension.filter
```

Would it be possible to modify the configuration of those ORM extension services to make them "Autowireable" without deprecation.

**Comment by soyuka** [comment]
Yes it's something we need to fix. I had the same issue with the metadata services. 

Since symfony 3.4 autowiring is less magic (for the better) and you indeed need to alias interfaces to the named service :). 

I'll patch this in my later train!

**Comment by raziel057** [comment]
@soyuka Thank you. Those Extensions are a great feature. Very useful and so easy to reuse in custom routes! Great work.
