### ISSUE TITLE
The authorize button in the swagger-ui does not get valid feedback

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#1564]
cf this GIF http://g.recordit.co/cP0gcv9T73.gif

When one click on authorize nothing in the UI happens.

I guess it's related to https://github.com/api-platform/core/issues/779

**Comment by majermi4** [comment]
I also reported the same 5 days ago to api-platform/api-platform - https://github.com/api-platform/api-platform/issues/486

**Comment by rogamoore** [comment]
Try this solution: https://github.com/api-platform/api-platform/issues/486#issuecomment-359242911
If it works, we should update the docs.
