### ISSUE TITLE
[RFC] Create annotations for operations, swagger context, etc

### ISSUE THREAD

**Issue by Koc** [api-platform/core#1565]
For now we adding item operations as plain array inside `ApiResource.itemOperations`. Would be better replace plain arrays with another annotation - `Operation`. Like Doctrine's `JoinColumn` annotation. Providing it allows us using annotation autocomplete and get information about all available operation options.

Same for swagger context, param, etc

**Comment by soyuka** [comment]
We will not add these annotations because it adds new classes to maintain and the few the better
