### ISSUE TITLE
ManyToOne and nullable=false produce required:false in hydra response

### ISSUE THREAD

**Issue by hariszukanovic** [api-platform/core#1567]
I expected that setting nullable=false on a ManyToOne would mark that property in hydra docs.jsonld response as required: true
Instead, I am getting required:false

Is there a correct way to mark a ManyToOne required in hydra response? 
Maybe a bug?

Entity relation:
```php
    /**
     * @ORM\ManyToOne(targetEntity="Node", inversedBy="services")
     * @ORM\JoinColumn(name="node_id", referencedColumnName="id", nullable=false, onDelete="RESTRICT")
     * @Groups({"service_list"})
     */
    private $node;
```
Hydra (part) of docs.jsonld response for the property:
```json
{
"@type": "hydra:SupportedProperty",
"hydra:property": {
"@id": "#SupervisorService/node",
"@type": "hydra:Link",
"rdfs:label": "node",
"domain": "#SupervisorService",
"owl:maxCardinality": 1,
"range": "#Node"
},
"hydra:title": "node",
**"hydra:required": false,**
"hydra:readable": true,
"hydra:writable": true
}
```
DB foreign key looks correct:
```
+---------------------------+----------------------------------+------+-----+---------+----------------+
| Field                     | Type                             | Null | Key | Default | Extra          |
+---------------------------+----------------------------------+------+-----+---------+----------------+
| node_id                   | int(11)                          | NO   | MUL | NULL    |                |
```

**Comment by hariszukanovic** [comment]
It is sometimes difficult to understand which annotations affect which behaviors.
I found that adding
* @Assert\NotNull()
produces
"hydra:required": true

If you feel that nullable=false on the ManyToOne should not make the property required in the same way as adding the validator @Assert\NotNull() then please close the ticket.

**Comment by soyuka** [comment]
IMO it's a non-existant feature, it can be fixed here:

https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php#L58

(Look for the property in the metadata and call `withRequired(!$metadata->nullable)`.

**Comment by Simperfit** [comment]
As said in the PR, this will be closed as won't fix.
