### ISSUE TITLE
Doctrine 2.6 not supported 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1578]
Reference build: https://travis-ci.org/api-platform/core/builds/319078313

Only diff between composer installations:

```diff
58c58
<   - Installing doctrine/orm (v2.6.0): Downloading (100%)
---
>   - Installing doctrine/orm (v2.5.14): Downloading (100%)
```

For now I'll enforce the `api-platform/core` version to `<2.6`

**Comment by lcobucci** [comment]
@soyuka what's happening is that RelatedToDummyFriend uses an association as identifier and the associated entity uses a post generated id (auto generated):

https://github.com/api-platform/core/blob/0ed9a024c2d2914fd571dd446dfe7e4dbf5465f6/tests/Fixtures/TestBundle/Entity/RelatedToDummyFriend.php#L40-L47

We are discussing internally how we are going to handle that, as @guilhermeblanco mentioned in https://github.com/doctrine/doctrine2/pull/6701#issuecomment-352644779. 

I hope this gives you a better idea of what's happening and let me know how can we help you on this.

**Comment by soyuka** [comment]
Thanks @lcobucci !
