### ISSUE TITLE
A ressource cannot be transversable or apiplatform throws an error

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#1584]
If my resource implement `ArrayAccess`, then I can't use it with ApiPlatform because the class cannot be resolved anymore.

Here is the related problematic code:

https://github.com/api-platform/core/blob/0ed9a024c2d2914fd571dd446dfe7e4dbf5465f6/src/Api/ResourceClassResolver.php#L42-L51

A solution is to add my custom normalizer but in that case I can't benefit of the jsonld `ItemNormalizer`.

**Comment by soyuka** [comment]
This code part is kinda sensitive but I think we would accept a patch for this.

**Comment by soyuka** [comment]
My feeling? If I were you I would patch this (also add the fix the Dictionary) - on master - and do a pull request or launch the test suite to check if something break haha.

**Comment by Nek-** [comment]
I meant, what is your feeling about the BC break.

**Comment by soyuka** [comment]
Why is there an `sprintf` with no arguments in the first place :laughing: .

I'm not sure to understand what change you're going to apply in this class and therefore can't comment. Please propose a patch and we'll discuss it there :stuck_out_tongue: .

**Comment by Nek-** [comment]
@soyuka do you think it should be fixed on master only or for both master and 2.1?

**Comment by Simperfit** [comment]
IMO it should be fixed on master.

**Comment by Nek-** [comment]
It is!

**Comment by teohhanhui** [comment]
@Nek- Is this still a problem?

**Comment by Nek-** [comment]
@teohhanhui I meant "it is... fixed on master" 😄
