### ISSUE TITLE
Create Entity From a database

### ISSUE THREAD

**Issue by GreyBlade** [api-platform/core#1594]
So I have a database already running, my question is, because i cant find on how to do it.
How do I create my entity in api platfrom from the tables information I have in the database?

**Comment by dunglas** [comment]
As API Platform uses Doctrine by default, you can do it easily using `bin/console doctrine:mapping:import`: http://symfony.com/doc/current/doctrine/reverse_engineering.html

**Comment by GreyBlade** [comment]
```
docker-compose exec app bin/console doctrine:mapping:import http://symfony.com/doc/current/doctrine/reverse_engineering.html

```

trying to use this command to import the reverse engineering i get this error


```
Bundle "http://symfony.com/doc/current/doctrine/reverse_engineering.html" d  
  oes not exist or it is not enabled. Maybe you forgot to add it in the regis  
  terBundles() method of your AppKernel.php file? 
```

**Comment by dunglas** [comment]
You should read http://symfony.com/doc/current/doctrine/reverse_engineering.html...

**Comment by wbelhomsi** [comment]
For anyone still lost please read: [https://github.com/api-platform/api-platform/issues/539#issuecomment-428072509](url) it might help you
