### ISSUE TITLE
"Improve" error messages by adding custom data

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#1598]
Hi,

It's maybe more a Symfony relevant question but it can be addressed by api-platform too so I post it here first:

Is there a way to add some informations in Validation exceptions, because a string message is sometimes a little too short, it could be usefull to add some contextual informations, and treat here after.

A classic error is something like that: `Article 128 not found`, but you can only treat it by parsing the string.

It could be very interesting to have something like that:
```json
{
  "message": "Article 128 not found",
  "data": {
    "type": "Article",
    "id": 128,
    "code": "entity_not_found"
  }
}
```

**Comment by lyrixx** [comment]
You can use the HTTP Status code to understand what is failing.

**Comment by jdeniau** [comment]
Well status code is limited. In this simple example it will do the job but in a more complex example, it is not sufficient.

Imagine a validation error or a 404 thrown by an entity not found in a filter for example. It's really hard to investigate what's going on on the client part.

**Comment by gagaXD** [comment]
Hey,

It can be an useful enhancement when serializing custom exception.

For example : I have an exception

```php
class SubscriptionException extends HttpException
{
    private $customData = 'this is my custom data';
....
  /**
     * @return string
     */
    public function getCustomData(): string
    {
        return $this->customData;
    }

    /**
     * @param string $dede
     */
    public function setCustomData(string $customData): void
    {
        $this->customData = $customData;
    }
```
I could be nice to have an output like this when this error is thrown :
```json
{
   "@context":"\/api\/contexts\/Error",
   "@type":"hydra:Error",
   "hydra:title":"An error occurred",
   "hydra:description":"my message!",
   "CustomData: "this is my custom Data"
   ....
}
```

**Comment by soyuka** [comment]
With validation errors (see the ValidationExceptionListener) we should have everything we need. If you want a custom behavior please see how we did there to handle custom data in the response.
