### ISSUE TITLE
GraphQL -> Item Resolver relies on routing IriConverter

### ISSUE THREAD

**Issue by dkozickis** [api-platform/core#1600]
Hi!

ItemResolver for GraphQL currently relies on default implementation of `IriConverterInterface` (`IriConverter`) to get the item on request. Because of that, I cannot request item by normal ID, I have to prepend it with REST endpoint path.

To illustrate.

If I request with normal ID (UUID):

```graphql
{
  aircraftIcaoType(id: "a2e132c8-8376-432f-a418-7e2a6e2b2a0a") {
    code,
    id
  }
}
```

I get following error

```json
{
  "errors": [
    {
      "debugMessage": "No route matches \"a2e132c8-8376-432f-a418-7e2a6e2b2a0a\".",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "aircraftIcaoType"
      ]
    }
  ],
  "data": {
    "aircraftIcaoType": null
  }
}
```

If I adjust request to 

```graphql
{
  aircraftIcaoType(id: "/api/aircraft_icao_types/a2e132c8-8376-432f-a418-7e2a6e2b2a0a") {
    code,
    id
  }
}
```

I get the item

```json
{
  "data": {
    "aircraftIcaoType": {
      "code": "A320",
      "id": "/api/aircraft_icao_types/a2e132c8-8376-432f-a418-7e2a6e2b2a0a"
    }
  }
}
```

Is it a bug or an expected behavior for GrapQL implementation on Api Platform?

**Comment by c410-f3r** [comment]
Things have changed since #1569.
I guess it is possible to return the original id with `_id`.

**Comment by dkozickis** [comment]
So its intended then, thank you @c410-f3r .
Will close this one and wait for @dunglas blog post :) 👍

**Comment by kiler129** [comment]
Can anyone locate any blog post about this? It doesn't seem to be a way to get original ID.

`ResourceFieldResolver` has a description of `A field resolver that resolves IDs to IRIs and allow to access to the raw ID using the "#id" field.` but you cannot get `#something` field :D
