### ISSUE TITLE
Custom attributes with entities, serialization and validation

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1611]
I'm working on a "extended attribute" system which should allow my API's clients (apps) to extend the original entity without making a mess for other clients.

For example, let's say I have a `Recipe` entity:

```php
class Recipe {
    private $name;
    private $preparation;
    private $ingredients;
}
```

and that works great in 99% of the time, but certain client want to define additional client-specific (app) or client+user-specific (user using the app) data to it, for example, a user attaches a private note, "Double the butter". This cannot be integrated into the entity itself as various clients might have quite elaborate additional attributes and I don't want to mess up my DB schema with all their attributes combined.

I have the persistence fully functional (I'm using Doctrine ODM integrated with ODM, it persists and loads everything correctly), now I'm looking into how to integrate this properly into API Platform.

So, if I have something like this:

```json
{
    "name": "Coq au vin",
    "preparation": "...",
    "ingredients": "...",
    "_extended": {
        # this is context-specific, determined by the current user and OAuth client
        "note": "Double the vin"
    }
}
```

what would be a good way to do this (seeing API Platform overrides parts of Symfony's serialization / validation process)? I'd like this to behave a natively as possible, not be out of place in any way.

I'm currently looking into modifying serialization metadata and having a custom denormalizer, both of which seem tricky as the attributes are, as I said, request-specific.

TIA.

**Comment by dunglas** [comment]
It should be possible to just extend the base entity and tell API Platform to just load the extended one (not the parent one).

**Comment by dkarlovi** [comment]
But seeing the extended attributes are client-specific (not just the content, their actual **existence**, some client might have `note`, other might not have it at all) and there might be several hundred clients, I'd need to have a specific extended class for each client and each entity.

**Comment by soyuka** [comment]
There's no perfect solution for this, you'll always have some drawbacks. 

You can also have a "OneToOne" relation to a "Recipe-Extended" table for example.

**Comment by dkarlovi** [comment]
@soyuka that doesn't seem correct. As I said, I already have persistence functional (via Doctrine ODM and a custom behaviour).

It works like this:

```php
class Recipe
{
    // as noted before

    /** @var ExtendedAttributeBag */
    private $extendedAttributeBags = [];  // ArrayCollection of scoped ODM documents (client-specific or client+user specific)
}

/**
 * @ODM\Document
 */
class ExtendedAttributeBag
{
    private $client;
    private $user = null;
    private $attributes = []; // ArrayCollection of embedded ODM documents
}
```

So, when you load a `Recipe`, you actually get its extended attributes attached (if any, of course) depending on the client/user making the request. It works with fetch, create, update, etc when I use the entities directly.

My question here is how and where to convince the serializer (and later, validator) not to dismiss these properties. You might have a point on the "relation" part, I should try to treat this as a single (API Platform) embedded resource (relation), just need to figure out how to define it exactly. :+1:

**Comment by soyuka** [comment]
I'm not fond of document databases because they're giving too much liberties which may lead to performance issues later and will try to make an abstraction of that 😄.

For the serialization part, I have a case where I need to dynamically add groups to some properties. I have a `MetadataLoader` that I inject in the `serializer.mapping.chain_loader`. 
You'd need a way to identify this classes that have "extended attributes" (for example an empty interface). 
I assume that this would be the same for the validation part, as all you need is to make sure that the metadata is correct according to the extended fields.

Let me know if you want a peak at the code responsible for this (if obviously it answers some problematic)!

**Comment by dkarlovi** [comment]
The extendable classes already have a non-empty interface as the custom Doctrine behavior depends on it.

> Let me know if you want a peak at the code responsible for this

If you could do that, that would be of amazing help.

**Comment by soyuka** [comment]
https://gist.github.com/soyuka/9db650f10ab46c4b971ad96b6086d380

I'm really not sure that this is the best way, it works for me. You could also add the same to the metadata factories (upper in the call stack [see here](http://api.symfony.com/3.1/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactory.html)). To me this data is more "loaded" once, hence the `loader` override.

**Comment by dkarlovi** [comment]
@soyuka thank you very much for this. <3

It looks very similar to the direction I'm currently going (only you're doing it in a compiler pass, while I need it per-request so I'm doing it in an event handler). This leads me to believe I'm on the right track with my current approach, only _something_ is misaligned _somewhere_ for me so will continue in the same direction and try to get it working. If I do, I'll outline the solution in this issue.

Thank you very much once more, this makes me owe you two beers already. By the time I'm done with the project, you might have a whole case of it. :laughing:

**Comment by dkarlovi** [comment]
FWIW, I did get this working by
1) introducing a `Manager`-type root object which holds all the extended attributes
2) introducing a custom (de)serializer for that `Manager` object (so, not messing with serializer metadata)
3) introducing a event subscriber which forces validation of all `Extendable` entities' `extendedAttributes` (which is an instance of the `Manager`) properties with `Assert\Callback`
4) implementing the said callback on the manager which validates itself after being constructed by the deserializer

It all works quite well for now.
