### ISSUE TITLE
[Performance] Avoid using Exception

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#1613]
Hello.

I notice there are many many part of the code that are using exception to control the flow of code execution.
I'm not here to debate if exceptions should be used to control the flow (even if I have my personal POV ;) ).

But generating an exception has a high cost for the CPU. So basically it's slower.

I made a small [benchmarck](https://github.com/lyrixx/php-bench) and I let you see results:

```

+----------------+---------+---------+---------+---------+---------+--------+-------+
| subject        | best    | mean    | mode    | worst   | stdev   | rstdev | diff  |
+----------------+---------+---------+---------+---------+---------+--------+-------+
| benchException | 1.766μs | 1.855μs | 1.860μs | 1.937μs | 0.056μs | 3.02%  | 3.35x |
| benchSupport   | 0.534μs | 0.554μs | 0.549μs | 0.580μs | 0.015μs | 2.79%  | 1.00x |
+----------------+---------+---------+---------+---------+---------+--------+-------+
```

So I think we could speed up this project by changing the design. We Could introduce new interfaces with a `support` function. The BC layer should be quite easy.

WDYT?

**Comment by dunglas** [comment]
I'm definitely 👍 to do this (we already started to introduce new interfaces for Data Providers for instance).

The v2 has been started with PHP 7 (= support for return types, but not for nullable ones, it was encouraging to throw exception instead of not using the typehint).

**Comment by lyrixx** [comment]
The issue with returning null is you don't know if the collection is empty, or if the data provider do not support the "type".

**Comment by dunglas** [comment]
@lyrixx yes, I mean returning null + adding a `supportMethod`, just like @greg0ire has done here: https://github.com/api-platform/core/blob/master/src/DataProvider/RestrictedDataProviderInterface.php

**Comment by lyrixx** [comment]
Ah nice ;) I missed this one ;)

**Comment by soyuka** [comment]
We should start listing what class may be improved in that way. AFAIR we're still doing this in metadata factories, but as they're cached I'm not sure it's worth the change?

**Comment by lyrixx** [comment]
Indeed for the metadata it is not Q big deal. 
I'm thinking about the data provider and maybe some other (I'm on my phone atm)

**Comment by greg0ire** [comment]
Performance is not the only issue with exceptions: I changed the data providers so that collection data providers could be implemented as generators.

**Comment by soyuka** [comment]
We removed most of these calls, closing feel free to ping or open a new issue if the problem is still present.
