### ISSUE TITLE
Migrating $container->get("api_platform.iri_converter") to current API platform

### ISSUE THREAD

**Issue by Drachenkaetzchen** [api-platform/core#1615]
Hi,

in my functional tests, in the legacy dunglas API Platform, I often used the wonderful `IriConverter` to convert `IRIs` into items or vice versa. For example:

```php
        $iriConverter = $this->getContainer()->get('api_platform.iri_converter');

        $iri = $iriConverter->getIriFromItem($user);

        $client->request('GET', $iri);
```

However, now this doesn't work anymore since the service is private. Is there an equivalent to this in `api-platform 2.1`?

**Comment by dunglas** [comment]
Hi @Drachenkaetzchen,

You need to make this service private for test only, I suggest to use an alias for that to make it explicit that this service should not be public outside of the test environment.

Here is an example with the Property Accessor:

https://github.com/api-platform/core/blob/master/tests/Fixtures/app/config/config_test.yml#L213-L215

**Comment by Drachenkaetzchen** [comment]
Yes, that works for me. Thank you!
