### ISSUE TITLE
(de)normalization_context is not used for subresourceOperations

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#1616]
According to the example in the doc, the following snippet do not work:

```php

/**
 * @ORM\Entity()
 * @ApiResource(
 *      subresourceOperations={
 *          "answer_get_subresource"= {
 *              "method"="GET",
 *              "path"="/questions/{id}/all-answers",
 *              "normalization_context"={"groups"={"answer_read"}},
 *          },
 *      },
 * )
 */
class Question
```

Reprocuder: https://github.com/lyrixx/test/tree/api-platform-subresource-path

**Comment by soyuka** [comment]
Mhh, I think that it's taking the "normalization_context" of the required resource class, not the class where the actual subresource is declared. I'll comment in the PR.

When I implemented subresources at first, there was no `SubresourceOperation` (it was a CollectionOperation).

**Comment by lyrixx** [comment]
> Mhh, I think that it's taking the "normalization_context" of the required resource class, not the class where the actual subresource is declared. I'll comment in the PR.

Yes, I noticed that. But there are no way to that in a clean way. If I add a new collectionOperationType, It adds a new route :/ IMHO, this way is much more easier and intuitive.

**Comment by abysKri** [comment]
Hi,
The route (/questions/{id}/all-answers) appear in the answer swagger ui too. How to hide it ?
Thanks

**Comment by lyrixx** [comment]
I opened a pr for that too :-D

**Comment by Nek-** [comment]
This is not exacly the same issue but is very close. I tried to use `allow_extra_attributes` context option and this doesn't work. Only the documentation example works for the context options (which is "groups").

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ApiResource(
 *     attributes={"denormalization_context"={"allow_extra_attributes"=false}}
 *     collectionOperations={
 *          "get",
 *          "post"={"denormalization_context"={"groups"={"post"}}}
 *     },
 *     itemOperations={
 *          "get",
 *          "put"={"denormalization_context"={"groups"={"put"}, "allow_extra_attributes"=false}}
 *     }
 * )
 */
class Article {}
```

The fun part is the group I specified on "PUT" is ok, but the "allow_extra_attributes" context key is ignored.

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/core/issues/2706
