### ISSUE TITLE
Collection not denormalized in case typehint is ArrayCollection

### ISSUE THREAD

**Issue by benjaminrau** [api-platform/core#1622]
This is a question which came to my attention after recent update to Symfony 3.4 and Doctrine ORM 2.5.

I have a collection as property on my resource class like this which is populated by an array of IRIs to InquiredArticle entity on POST request:
```
/**
     * @var ArrayCollection
     *
     * @Groups({
     *     "api_purchaserpass_post_item_current_user_organization_type_purchaser",
     *     "api_purchaserpass_post_item_current_user_organization_type_retailer"
     * })
     */
    private $inquiredArticles;
```

After upgrade it is no longer denormalized because within \ApiPlatform\Core\Serializer\AbstractItemNormalizer::setAttributeValue
denormalization is tried to be done with
**\ApiPlatform\Core\Serializer\AbstractItemNormalizer::denormalizeRelation**
instead of
**\ApiPlatform\Core\Serializer\AbstractItemNormalizer::denormalizeCollection**
because $type->isCollection returns false.

If i change the typehint to
`@var InquiredArticle[]|ArrayCollection`
the attribute is detected as collection and denormalized by the proper method (denormalizeCollection) again.

Any ideas?

Cheers Ben

PS: Happy new year everybody and ApiPlatform team, thank you so much for... erm ApiPlatform. We love to use it! We would love to get some details (benjamin.rau@gotoemma.de) about how to donate - i was searching the website for information but didnt find any.

**Comment by soyuka** [comment]
> If i change the typehint to
@var InquiredArticle[]|ArrayCollection
the attribute is detected as collection and denormalized by the proper method (denormalizeCollection) again.

This is correct indeed and the correct type should be `InquiredArticle[]` which solves the issue.

**Comment by lexaboss** [comment]
Thanks a lot !!!!
