### ISSUE TITLE
How to serialize ALL exceptions ?

### ISSUE THREAD

**Issue by fabmlk** [api-platform/core#1630]
If my application is 100% API, then I guess I want to serialize 100% of the raised (uncaught) exceptions into the appropriate JSON format, what would be the guidelines to do so ?

**Comment by jewome62** [comment]
The work is made here : https://github.com/api-platform/core/blob/master/src/EventListener/ExceptionListener.php
You can override it with EventListener with best priority

**Comment by baudev** [comment]
If you want to serialise it into jsonld, you may need (if it's a symfony controller for example) to set the `format` attribute of the request to `jsonld`:
```php
$request->attributes->set('_format', 'jsonld');
```
