### ISSUE TITLE
Property filter 

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/core#1632]
Hi,

Great bundle, thanks !

Quick question regarding the 'Property filter' feature.

Is it possible to have something like `'/books?properties[]=title,author' `
instead of `'/books?properties[]=title&properties[]=author'` ?

It would be more readable and easy to use I think.

Thanks in advance for your answer,
Julien

**Comment by soyuka** [comment]
Nope but you could override the class and build your own [properties filter](https://github.com/api-platform/core/blob/35edfb6ae999cf77e04caf81d9c33cbda9aa3890/src/Serializer/Filter/PropertyFilter.php).

**Comment by pesseyjulien** [comment]
true that, thanks !
