### ISSUE TITLE
Problem with datetime_immutable and DateFilter.

### ISSUE THREAD

**Issue by temp** [api-platform/core#1638]
I'm getting 2 errors if I use a Doctrine DateFilter on a datetime_immutable field.
The first error is in the query itself, since the DateFilter creates an instance of DateTime, and not DateTimeImmutable. The second error is thrown inside the DataCollector, due to the same reasons.
I guess the addWhere() protected method in DateFilter should check wether or not the field is of $type "*_immutable", and create a DateTimeImmutable instead of a DateTime.

**Comment by sroze** [comment]
Fixed by #1652.

**Comment by temp** [comment]
Any chance to get this released as 2.1.5 soon?
