### ISSUE TITLE
getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by gdharris1970** [api-platform/core#1639]
When I run the following command, I get error messages:

bin/console doctrine:database:create

Here are the errors:

[Doctrine\DBAL\Exception\ConnectionException]
  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

[PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

[PDOException]
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by soyuka** [comment]
Your database configuration must be wrong.

**Comment by gdharris1970** [comment]
Thanks for the quick reply! Where do I look for the database configuration? I'm really new to this stuff. Thanks in advance!

**Comment by gdharris1970** [comment]
As @soyuka stated above, I think my DB configuration is incorrect. I'm not sure where that information is stored. Can someone point me in the right direction? Thanks!

**Comment by dunglas** [comment]
Check in `app/config/parameters.yml`.

**Comment by gdharris1970** [comment]
That did it! Thank you so much!
