### ISSUE TITLE
Inheritance ?

### ISSUE THREAD

**Issue by pvgnd** [api-platform/core#164]
What is the best way to handle inheritance with the API Bundle ?

For example, I need AdministativeArea list with Country and City. Inheritance is configured on AdministrativeArea Entity as a SINGLE_TABLE inheritance.
I created resource for AdministrativeArea, but when I call "http://localhost/api/administrative_areas", the result is : 
No resource found for object of type "AppBundle\\Entity\\City"

I think I need to map City entity to AdministrativeArea resource but I don't know how to do that.

**Comment by felicitus** [comment]
It seems that you are missing a resource entry for the City entity:

https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/getting-started.md#registering-the-services
