### ISSUE TITLE
`createSchema` / `dropSchema` vs `recreateSchema`

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#1642]
Today behat `FeatureContext.php` file declare two tags:
  * `@BeforeScenario @createSchema`
  * `@AfterScenario @dropSchema`

I propose to replace them by one unified tag `@BeforeScenario @recreateSchema`.

The problem I saw with that is the following:
Using `@createSchema` without using `@dropSchema` on the previous test will result in an error like `Error while creating database, table XXX already exists`.
So when you need to have a clean database, you need to not only add `@createSchema` on your test scenario, but add `@dropSchema` on the previous test.
A weirder case could occur if you do not "clear" every file, and you launch your files in a random order like [fastest](https://github.com/liuggio/fastest) does. You might sometime have issues, but not everytime :)

The `@recreateSchema` would just a drop and recreate the schema.

I do not see a case where it is useful to use only one of those two tags, but I do not have all the vision on api-platform as you guys, so it's opened for discussion :)

**Comment by dunglas** [comment]
In most features files, we put `@createSchema` on the first scenario, and `@dropSchema` on the last, to reuse the same database during all the test and speed up the builds.

**Comment by jdeniau** [comment]
Then the only change that will be made is to remove `@dropSchema` and replace `@createSchema` by `@recreateSchema`.

The only difference is that on the first file it will try to delete an empty table (no really perf change), and it will "leave" the database untouched after the last run (but on travis, it will be dropped by travis, and on local machine it will be dropped by the first file of the next run)

**Comment by soyuka** [comment]
I launch:

```
rm -rf tests/Fixtures/app/cache/test && ./vendor/bin/behat --stop-on-failure
```
