### ISSUE TITLE
Float is not deserialized correctly

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#1647]
I have a `float` property on my ApiResource. When I send a valid value in JSON, API Platform seems to don't recognize it correctly and throw an error.

Entity:
```php
class Product
{
    /**
     * @var null|float
     * @ORM\Column(type="decimal", precision=8, scale=5, nullable=false, name="feature_volume")
     * @Groups({"product_read", "product_write", "cart_read"})
     */
    private $volume;

    public function getVolume(): ?float
    {
        return $this->volume;
    }

    public function setVolume(?float $volume): void
    {
        $this->volume = $volume;
    }
}
```

Request:
```json
{
    "volume": 538.47839,
}
```

Response: `The type of the "price" attribute must be "string", "double" given.`
Status code: 400
Last call: `vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php on line 227`

@api-platform/core-team Do you have an idea why API Platform doesn't recognize my float value? I need to force it to string now…

**Comment by dunglas** [comment]
The decimal Doctrine type is mapped to a string, it’s documented here: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html (because it can be too long to be stored on a PHP’s float).
If you want a PHP’s float, use the float Doctrine type.
