### ISSUE TITLE
Naming conventions for resource endpoint

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#165]
For an entity `User`, the endpoint will be `users`, but there is two issues:
* the plural name of an entity is not configurable, ex the plural of `Medium` should be `Media` and not `Mediums` (well technically speaking both are valid but the meaning differs so it depends of the context)
* composed name like `ContentCluster` have either `content_cluster` or `contentcluster` as an endpoint, on may prefer another one like `content-cluster`. I'm saying either because I have both cases although I'm not really sure where it comes from but it's not the point.

Could it be possible to make this configurable? For the composed name maybe a global naming strategy would do although a configuration on a resource basis may be useful too.

**Comment by dunglas** [comment]
Technically it is already configurable using custom operations and custom routes. That being said, it's not developer friendly and any work on that is welcome!

**Comment by Simperfit** [comment]
ping @theofidry this can be closed no ?

**Comment by theofidry** [comment]
Yep, via #547 :)
