### ISSUE TITLE
No such file or directory...

### ISSUE THREAD

**Issue by gdharris1970** [api-platform/core#1651]
I'm working my way through the tutorial called "Creating your First API with API Platform, in 5 Minutes." When I run this command:

docker-compose exec app bin/console doctrine:schema:update --force

I get these errors:

[Doctrine\DBAL\Exception\ConnectionException]
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[HY000] [2002] No such file or directory

[PDOException]
SQLSTATE[HY000] [2002] No such file or directory

The entities appeared to have generated correctly when I ran:

docker-compose exec app bin/console doctrine:generate:entities AppBundle

**Comment by gdharris1970** [comment]
I ran the command in verbose mode, but it didn't give me anything useful. :-(

I really want to get the is working. I think that once I understand it, the time for developing my API will be greatly reduced and more secure!

**Comment by gdharris1970** [comment]
Well, I tried changing "localhost" to "127.0.0.1" in the config files. This was a suggestion given on several forums that I found, but it didn't work. I'm not surprised because the error I'm getting appears to be a SQL driver error, so I'm not sure what changing those values would do. I tried changing the MYSQL config in the docker-compose.yml to reflect the correct values, but that didn't work either. I'm completely stumped! Please help!

**Comment by gdharris1970** [comment]
It looks like the command is trying to create a database schema. The api_platform database does exist. I verified that. It only has one table, which is "foo". That table only contains one row. Does the command that is failing try to create database tables? If so, where is the schema file located?

**Comment by gdharris1970** [comment]
By the way, I can access MySQL from the command line just fine, so that definitely works, but it feels like the schema updater does not know how to find MySQL. I'm totally not sure though because the error message is so cryptic. Is there anyway to test this theory?

**Comment by gdharris1970** [comment]
I'm getting an exception in the following file on line 43:

vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php

The line of code looks like the following:

parent::__construct($dsn, $user, $password, $options);

This line of code is in the class construct function. I printed out the four parameters to a test file, and they all look correct.

**Comment by gdharris1970** [comment]
What in the world! I'm trying to modify PDOConnection.php to drop some variables out to a flat file, and the file is not being created. The error says that it's happening at line 43 in that file, so I put a few debugging lines of code above line 43. Everything runs normally (except for the same old errors), but my test file is never being created. I have triple checked my code, and it's correct. Is something cached somewhere that I'm not aware of?

**Comment by lethak** [comment]
are you using docker on windows ?

**Comment by Simperfit** [comment]
@gdharris1970 if you still have an issue please feel free to ping me or to re-open this issue.

**Comment by MVincentM** [comment]
@Simperfit hi, i have the exact same issue and I don't find any solution. I use a Mac and symfony 4
