### ISSUE TITLE
Swagger does not reference correct schema when using embedded resource

### ISSUE THREAD

**Issue by Toflar** [api-platform/core#1657]
Sorry guys, I tried to provide a PR directly but the `DocumentationNormalizer` is a bit too complex at the moment. I don't quite see how all these names go together so here's the issue. If you can guide me I can help with a PR.

```php
/**
 * @ApiResource(
 *     attributes={
 *         "normalization_context"={"groups"={"Quickcheck_GET"}},
 *         "denormalization_context"={"groups"={"Quickcheck_POST"}
 *    }
 * })
 */
class Quickcheck
{
    /**
     * @var QuickcheckAnswer[]
     *
     * @ORM\OneToMany(targetEntity="QuickcheckAnswer", mappedBy="quickcheck", cascade={"all"})
     * @ApiSubresource
     * @Groups({"Quickcheck_GET", "Quickcheck_POST"})
     */
    private $quickcheckAnswers;
}
```

```php
/**
 * @ApiResource(
 *     attributes={
 *         "normalization_context"={"groups"={"QuickcheckAnswer_GET"}},
 *         "denormalization_context"={"groups"={"QuickcheckAnswer_POST", "Quickcheck_POST"}}
 *    }
 * )
 */
class QuickcheckAnswer {}
```

So I can `POST` to `/quickcheck` like so just fine:

```json
    {
      "quickcheckAnswers":[
        {
          "key":"foo",
          "value":"whatever"
        },
        {
          "key":"foo2",
          "value":"whatever2"
        }
      ]
    }
    """
```

it all gets deserialized and updated correctly, awesome! But swagger shows me this:

![bildschirmfoto 2018-01-17 um 17 59 47](https://user-images.githubusercontent.com/481937/35055785-47336e40-fbb0-11e7-9748-b24c36bbdeb6.png)
![bildschirmfoto 2018-01-17 um 17 59 57](https://user-images.githubusercontent.com/481937/35055786-475b5fcc-fbb0-11e7-88f7-4782397bc0e4.png)
![bildschirmfoto 2018-01-17 um 18 00 01](https://user-images.githubusercontent.com/481937/35055788-490200c4-fbb0-11e7-8625-09bf74e77fdf.png)

I'd expect it to embed the schema instead.
I don't quite understand why there's a model for each combination of all groups because `@Groups({"Quickcheck_GET", "Quickcheck_POST"})` means **either** `Quickcheck_GET` or `Quickcheck_POST`, imho.

Thanks for the help!

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/core/issues/2706
