### ISSUE TITLE
Handle entities that are not REST resources

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#166]
In some cases we can have a relationship between two entities, for the sake of the example let's say `User` and `Dummy`. The relationship is a unidirectional one to one owned by `User`. In this case, there is not much interest to expose `Dummy`, so we might end up willing to expose the whole entity `Dummy` when accessing to a `User` resource and manage this entity via `User`. However this causes two problems:

* This won't work because an error will be thrown stating that `Dummy` is not a resource
* It won't be possible to update `Dummy` via `User`

It may be simpler to keep the current behavior because I'm not sure this case is very RESTful like but I think it would at least deserve a mention in the doc as when dealing with relationships, all related entities must be declared as resources too. Maybe a note after [the service declaration](Resources/doc/getting-started.md#registering-the-services).

**Comment by dunglas** [comment]
I agree that this is not RESTful.

A possible workaround (not tested):
* Create a `Resource` for `Dummy`
* Register no operation at all on that resource

It will be possible to use that entity class as `Resource` but it will not be exposed trough the routing system.

**Comment by theofidry** [comment]
Well, thinking this over I'm not sure it's a good idea: it means sometime you can update a resource via another entity and it may be quite dangerous. Unless in this case, since `Dummy` is not exposed, it is not considered as a resource and it's attributes are in fact a part of `User`, and in this case it makes sense and more RESTful like.

**Comment by teohhanhui** [comment]
I wonder if the REST mantra goes "everything is a resource..." (oft-repeated but how true is it?)

Does it really make sense to expose, for example [GeoCoordinates](https://schema.org/GeoCoordinates)? Or in my case, a TourDuration that only specifies the number of days and nights and nothing else?

**Comment by teohhanhui** [comment]
There are 2 hurdles in supporting non-resource objects:

- [ ] Dunglas\ApiBundle\Mapping\Loader\LoaderChain::checkClassMetaData throws when object has no identifier
- [ ] Dunglas\ApiBundle\Api\ResourceResolverTrait::guessResource throws when a resource is not found for the class

**Comment by teohhanhui** [comment]
`Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer::supportsNormalization` is falsely claiming that it can handle these non-resource objects IMO.

@dunglas What would your suggestion be to fix this?

**Comment by theofidry** [comment]
Any update regarding this? I agree it's definitely not very restful and we're better of using several resources. Still, as we may use value objects for our entities, and more specifically `@Embeddable` for Doctrine 2.5, it would be non sense to declare those value objects as resources as a resource has an identity, which a value object does not have. @teohhanhui has given some valid examples but without a doubt there is more.

**Comment by teohhanhui** [comment]
See discussion on api-platform/schema-generator#33 for a practical solution / workaround...

**Comment by teohhanhui** [comment]
Hmm... On second thought, we might be able to just leave everything we don't know how to normalize/denormalize to the other registered normalizers/denormalizers, just as it should be. If we assume that a Doctrine Embeddable is a value object, it should be handled normally by the `ObjectNormalizer` for example...

**Comment by theofidry** [comment]
>Doctrine Embeddable is a plain value object it should be handled normally by the ObjectNormalizer

:+1:

**Comment by teohhanhui** [comment]
Which makes this not a feature, but a potentially BC-breaking bug.

**Comment by dunglas** [comment]
> Hmm... On second thought, we might be able to just leave everything we don't know how to normalize/denormalize to the other registered normalizers/denormalizers, just as it should be. Since a Doctrine Embeddable is a plain value object, it should be handled normally by the ObjectNormalizer for example...

@teohhanhui 100% agree (and I've a similar problem on one of my project), this is an error of design. Any patch welcome.
