### ISSUE TITLE
Order by embedded field in ApiResource annotation

### ISSUE THREAD

**Issue by Awkan** [api-platform/core#1670]
# Problem reproduction
I use an ordering on an embedded field in my entity. I want to order by embed.name field for example, then I put `embed.name` in my ApiResource->attributes->order annotation.
```php
/**
 * @ORM\Embeddable
 */
class EmbeddableDummy
{
    /*
     * @ORM\Column()
     */
    private $name;
    // ...
}

/**
 * @ApiResource(
 *     attributes={
 *         "order"={"embed.name": "DESC"}
 *     }
 * )
 */
class EmbeddedDummy
{
    /**
     * @ORM\Embedded(class="EmbeddableDummy")
     */
    public $embed;
}
```
This works well since v2.1.3 but the bug appeared with the next release. A message like this appear with a 500 : 
```
[Semantical Error] line 0, col 119 near 'embed_a1 ORDER': Error: Class AppBundle\\Entity\\EmbeddedDummy has no association named embed
```
After some research I found the "culprit": https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/OrderExtension.php#L62.

# Problem
The problem is that in case of embedded entities, a join is made.

# Resolution
Avoid join when an embedded field is used in ordering.    
Refering to the above link, we have to keep if clause (`$field = "{$rootAlias}.{$field}";`) for embedded fields and not `joinOnce` in the where clause.

If you're ok, I can make a fix

**Comment by soyuka** [comment]
Seems like a valid use case :+1: on the patch!

**Comment by Awkan** [comment]
Thanks. Then PR is in progress, I'll submit it soon (maybe today)

**Comment by Simperfit** [comment]
The PR has been merged, thanks @Awkan!
