### ISSUE TITLE
How to get routes associated with an entity ?

### ISSUE THREAD

**Issue by emilien-puget** [api-platform/core#1679]
Hello,

Is there a way to get all the routes associated with an entity ?

I wanted to add informations about the routes available to an user when logged in, among other things.

Thank you

**Comment by soyuka** [comment]
You may want to take a look at the [DocumentationNormalizer](https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php) and how the internal metadata things are working. You'd need to use the `ResourceMetadataFactoryInterface` to get `Collection` and `Item` operations (those are "routes") and then do what you want with them :) .

**Comment by emilien-puget** [comment]
I found this file and modified a bit to add a method to retrieve the information ; are you interested in a PR or is it an unwanted change ?

**Comment by soyuka** [comment]
I think that this isn't really a wanted change as it seems specific to your needs. If there's more demand we will be glad to take your patch into consideration.

**Comment by emilien-puget** [comment]
All right, i made a gist here https://gist.github.com/emilien-puget/0bf3bcef66e2a64c31219520385a00ab, thank you for your assistance.
