### ISSUE TITLE
api_filters.yml - Symfony 4 Location?

### ISSUE THREAD

**Issue by sigmatec** [api-platform/core#1681]
I'm trying to implement filters into my app but cannot figure out where the api_filters.yml file goes in Symfony 4. No matter what directory I put it in, it gets overlooked.

I tried following the [Docs](https://api-platform.com/docs/core/filters#doctrine-orm-filters) but no luck so far.

I am new to Symfony and Api Platform so apologies if it's me being an idiot, but do they docs need updating?

**Comment by norkunas** [comment]
Hey @sigmatec,

You can put them in `config/api_filters.yaml` and then import in your services.yaml file:
```
import:
    - { resource: api_filters.yaml }
```

**Comment by lexa-uw** [comment]
Hello @sigmatec,

Just add your `api_filters.yml` to `config/packages/api_filters.yml`

**Comment by norkunas** [comment]
@lexa-uw but it's not a package configuration, only services definitions for filters :)

**Comment by lexa-uw** [comment]
@norkunas 
Yes. You are right.
Would be better to place config in `config/services/api_filters.yml` and import it in services config:
```
import:
    - { resource: services/api_filters.yml }
```
[How to Import Configuration Files/Resources](https://symfony.com/doc/current/service_container/import.html)

**Comment by sigmatec** [comment]
@norkunas  @lexa-uw 

Thank you very much to you both.  I went with your second suggestion @lexa-uw as the structure makes sense.
