### ISSUE TITLE
On-demand pagination for toMany relations

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#1686]
There has been some demand on this particular feature.

Example:

```
Resource {
  name
  ChildResource[]
}

GET /api/resource

{
  name: 'foo',
  childResources: [1,2,3 ... 30 ] // paginated
}
```

I'm really not sure how / if we can pull this out but I'm opening this issue to keep track of ideas suggestions.

About the configuration we could use `@ApiProperty(attributes={"paginate": true})` with maybe some more parameters to control that pagination? 

We may also flag this as a "wontfix" and propose an alternative solution.

**Comment by teohhanhui** [comment]
From #1083, it seems we need to allow greater control, at least the following should be supported:

- IRI to subresource collection
- IRI to subresource collection, but include total item count
- paginated subresource collection, with IRI to subresources
- paginated subresource collection, with embedded subresources

**Comment by soyuka** [comment]
superseeded by https://github.com/api-platform/core/issues/2706
