### ISSUE TITLE
[Swagger] add --yaml to SwaggerCommand

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1688]
It would be cool if you'd be able to say `api:swagger:export --yaml` to get valid YAML out (instead of JSON). This way, if you're storing it to a file for human consumption, you get YAML which is easier to diff etc.

Should be simple enough.

**Comment by dunglas** [comment]
👍 Would be great. (would be great to also support OpenAPI v3 :D)

**Comment by dkarlovi** [comment]
Yeah, if you're on board with this, I'll add it tomorrow.

**Comment by dkarlovi** [comment]
There, hope it's OK, I targeted master since it's a new feature.
