### ISSUE TITLE
Doctrine binary type : "attribute must be resource, string given"

### ISSUE THREAD

**Issue by alex-ception** [api-platform/core#1691]
Hi,

I have an entity having the following field :
```
class MyClass
{
    /*
     *
     * @ORM\Column(name="my_field", type="binary", length=7)
     * @Assert\NotBlank
     */
    private $myField;

    /**
     * @param string $myField
     */
    public function setMyField(string $weekDays): void
    {
        $this->myField = $myField;
    }
}
```
I am trying to do a PUT on this class. I used the generated swagger documentation, to get my payload, which is the following :
```
{
  "weekDays": "string",
}
```
But when I tried to do the PUT request, the API respond the following :
The type of the "myField" attribute must be "resource", "string" given.

It seems to be legit since doctrine store the data in a varbinary, and retrieve it as a resource. But I obviously can't pass a stream resource in my payload.

Does anyone have an idea to solve my problem ?
Thanks.
PS : I pay :beers: to the one helping me to solve this ;)

**Comment by dunglas** [comment]
You'll need to use a normalizer decorator to convert the string to a resource back and forth before passing it to Doctrine: https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-add-extra-data

**Comment by Simperfit** [comment]
I'm closing here since we got no feedback, if you still have an issue please feel free to ping me.
