### ISSUE TITLE
GraphQL and Custom Operations 

### ISSUE THREAD

**Issue by nicodmf** [api-platform/core#1700]
Is there a way to add custom mutation or query in graphql, like with the rest API ?

**Comment by dunglas** [comment]
Yes but it's not documented yet :(
https://github.com/api-platform/core/blob/master/src/GraphQl/Type/SchemaBuilder.php#L84

**Comment by AntoineBourin** [comment]
Is there some news about custom operations with GraphQL in Api platform ? :)

**Comment by alanpoulain** [comment]
@AntoineBourin please see the PR above your message.

**Comment by AntoineBourin** [comment]
Thanks! :+1:
