### ISSUE TITLE
Profiler bundle

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#1701]
For debugging purpose while migration from v1 to v2, I created a small profiler bundle for api-platform:
https://github.com/mapado/api-platform-profiler-bundle/

It is quite simple for now but tell us if a ressource is found, what routes are defined for this resource and the filters linked. (basically, it replace a big `dump` of the context):

![example](https://camo.githubusercontent.com/c6926b2f717f7787e6f1691d7644d5a81a15754b/68747470733a2f2f73637265656e73686f747363646e2e66697265666f7875736572636f6e74656e742e636f6d2f696d616765732f30323137613934642d623661342d343361312d393231372d6433336464323631323639302e706e67)

I think it can be interesting to merge this in the Symfony Bridge.

If you are OK with this, I will open a PR with it

**Comment by dunglas** [comment]
Nice! It definitely can be in core.

**Comment by jdeniau** [comment]
Ok, I will make a PR of it then

**Comment by sroze** [comment]
Very good idea! 👍 to have it inside.

**Comment by soyuka** [comment]
Would be awesome to also have so serialization debugging tool but I guess this has more to do with symfony itself \o/

**Comment by jdeniau** [comment]
@soyuka well it can, but as api-platform do use the serializer, it can be implement in here too.

For a first version, I will only merge the actual profiler though because displaying data related to serializer may be a huge amount of work !

**Comment by soyuka** [comment]
> I will only merge the actual profiler though because displaying data related to serializer may be a huge amount of work !

It's definitely out of scope yes
