### ISSUE TITLE
[Meta] add a build Makefile to ease contributions

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1703]
_**Edit:** to avoid confusion which was pointed out to me in Slack: bulk of the suggestion is transferring all the build requirements to a Docker image and run all the jobs using it, Makefile is just a friendly wrapper around that._

I've started adding a `Makefile` to all projects I work on which tries to ease contributions (first of all, mine, of course :laughing: ): [example 1](https://github.com/rollerworks/search/blob/master/Makefile), [example 2](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Makefile).

Idea is to have a single command you're able to run before you commit and increase your chances of the build passing before you actually push, by which avoiding CI build to fail 20min later because of CS violation.

First target (which is run if no targets given) should:

1. fix CS
2. run tests
3. run PHPStan
4. prepare for commit in other ways

Now you commit and push and are almost certain your CI will pass.

Later, a good approach is to switch your CI build to also use `Makefile` targets too ([example 1](https://github.com/rollerworks/search/blob/master/.travis.yml), [example 2](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/.travis.yml)) which simplifies the CI config file, but also allows the user to have a fully functional build locally, without actually waiting for CI.

**Comment by soyuka** [comment]
Our Contributing guide should be enough
