### ISSUE TITLE
[Swagger] invalid defaults for paths and definitions in Swagger doc

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1704]
From #1695:

> It seems like this is the output:
>
>```yaml
>swagger: '2.0'
>basePath: /
>info:
>    title: 'My Dummy API'
>    version: 0.0.0
>    description: 'This is a test API.'
>paths: null
>definitions: null
>```
>
> while this is supposed to be the output:
> 
>```yaml
>swagger: '2.0'
>basePath: /
>info:
>    title: 'My Dummy API'
>    version: 0.0.0
>    description: 'This is a test API.'
>paths: {}
>definitions: {}
>```
>
> I've added `--no-schema` to the validator just to make it pass, should default these values to an empty object in another PR.

Also removing `--no-schema` from Travis.

**Comment by Taminoful** [comment]
I'd like to give this one a shot as part of #Hacktoberfest, if it's still relevant to the core. 😃

**Comment by soyuka** [comment]
Thanks for your investigation @Taminoful ! I'm closing this then :)
