### ISSUE TITLE
Custom operation in hal/json

### ISSUE THREAD

**Issue by MadisD** [api-platform/core#1706]
Hi
I have created a custom operation **/api/cities/{id}/custom** which is basically a custom sub-resouce.
Is there a way to show that operation exists in the list of "_links" in  **/api/city/{id}** resource like other sub-resources? 

Like so
``` json
    "_links": {
        "self": {
            "href": "/api/cities/13255"
        },
        "parish": {
            "href": "/api/parishes/450"
        },
        "custom": {
            "href": "/api/cities/13255/custom"
        }
    }
```
Or is this kind of thinking wrong?

**Comment by Simperfit** [comment]
I think you need to look at the HAL spec, but that's something we are not going to implement in the core directly IMO. 

You can achieve by using a custom doc normalizer that decorates the hal one.
