### ISSUE TITLE
problem with nelmio doc bundle

### ISSUE THREAD

**Issue by magdoss** [api-platform/core#1709]
Type error: Too few arguments to function ApiPlatform\Core\Documentation\Action\DocumentationAction::__invoke(), 0 passed in C:\Users\majdi\Desktop\api-platform-2.1.6\var\cache\dev\ContainerKovpa9k\getNelmioApiDoc_Describers_ApiPlatformService.php on line 8 and exactly 1 expected

j'ai installé nelmio avec la configuration suivante 
//config.yml

api_platform:
    enable_nelmio_api_doc: true
nelmio_api_doc:
    areas:
        path_patterns: 
            - ^/api(?!/doc$)

//routing.yml

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

comment je peut résoudre ce problème !

**Comment by dunglas** [comment]
See https://github.com/api-platform/core/pull/1705
