### ISSUE TITLE
Token Pagination

### ISSUE THREAD

**Issue by davidbarratt** [api-platform/core#1713]
Is there a way to implement token pagination instead of page number pagination?

**Comment by Simperfit** [comment]
@davidbarratt could you please explain what you want ?

**Comment by davidbarratt** [comment]
Explanation:
http://blog.vermorel.com/journal/2015/5/8/nearly-all-web-apis-get-paging-wrong.html

Examples:
*  https://developers.facebook.com/docs/graph-api/using-graph-api#paging
*  https://developer.twitter.com/en/docs/ads/general/guides/pagination
*  https://www.mediawiki.org/wiki/API:Query#Continuing_queries
* https://docs.connect.squareup.com/articles/catalog-overview?q=pagination#pagination

I _think_ the best way to do this with a relational database would be to use a `WHERE id > continue` kind of query. This would work with auto increment ids or something like [ulid](https://github.com/ulid/javascript). But it could really work with any field that has a unique key and is in the order you want.

**Comment by meyerbaptiste** [comment]
It's on our todolist to add this in the core but  personally I haven't thought about the implementation yet.

**Comment by alanpoulain** [comment]
PR for cursor-based pagination: https://github.com/api-platform/core/pull/1915

**Comment by norkunas** [comment]
This could be closed, right? PR is already merged
