### ISSUE TITLE
Add special assert applyed only before normalize

### ISSUE THREAD

**Issue by Kleinast** [api-platform/core#1735]
Hi,

I have problem on my project which seem recurent like https://github.com/api-platform/core/issues/1157 or https://github.com/api-platform/core/issues/1691.
I had same problem with entity relations.
As validation happen after serializer, some Normalizer can fail and throw error.

Would it be a good idea to implement the possibility to assert with validation constraint some elements before serialisation ?

For exemple
```
    /*
     * @Assert\NotBlank()
     * @Assert\DateTime()
     * @Assert\Type('string', group='before_serialize')
     * @Assert\Regex('(\d{4})-(\d{2})-(\d{2})', group='before_serialize')
     */
    private $date;
```
With this, an invalid string date will throw a contraintList exception.
What do you think about this idea, is it relevant to process like this ?

Thanks for your advice.

**Comment by athos7933** [comment]
I think it's a very good idea !

**Comment by soyuka** [comment]
You can use the new `disable_type_enforcement` in symfony's normalizer's context.

**Comment by Kleinast** [comment]
Thanks @soyuka
