### ISSUE TITLE
Subresource collection filters not added by DocumentationNormalizer

### ISSUE THREAD

**Issue by YaoOcelotl** [api-platform/core#1736]
Hi.

The DocumentationNormalizer is using the wrong resource class for obtaining subresource collection filters.
In [DocumentationNormalizer.php#L157](https://github.com/api-platform/core/blob/v2.2.2/src/Swagger/Serializer/DocumentationNormalizer.php#L157) uses the parent resource class

`if ($parameters = $this->getFiltersParameters($resourceClass, $operationName, $subResourceMetadata, $definitions, $serializerContext)) {`

it should use the subresource class

`if ($parameters = $this->getFiltersParameters($subresourceOperation['resource_class'], $operationName, $subResourceMetadata, $definitions, $serializerContext)) {`

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/core/issues/2706
