### ISSUE TITLE
2.2 broken serialization context building

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#1737]
Before 2.2 in `api-platform/core/src/EventListener/ReadListener.php` there was no serialization context building, so the `data` attribute was available in `api-platform/core/src/EventListener/SerializeListener.php` and then I was able to apply groups based on object data, but now the context is already built..

**Comment by antograssiot** [comment]
Then if in your context builder returns context if data attribute is null, it should works like before I think

**Comment by norkunas** [comment]
But this is a BC BREAK and then docs example should be updated

**Comment by norkunas** [comment]
Good, so know I need to refactor all my context builders :disappointed:
