### ISSUE TITLE
Entity with array property breaks GraphQL query

### ISSUE THREAD

**Issue by alex88** [api-platform/core#1739]
It's the first time I use GraphQL and I'm pretty new to api-platform so I might be wrong.
I've just updated a project to 2.2.2, added the graphql library and with an entity with this property:

```
/**
 * @var array
 * @ORM\Column(name="home_team_periods_score", type="simple_array", nullable=true)
 * @Groups({"match_read", "sport_matches"})
 */
private $homeTeamPeriodsScore;
```

this because in https://github.com/api-platform/core/blob/v2.2.2/src/GraphQl/Type/SchemaBuilder.php#L320-L371 when a property is an iterable/array like in this case the variable `$resourceClass` stays as null and when it gets into
```
if ($this->isCollection($type)) {
  return $this->paginationEnabled && !$input ? $this->getResourcePaginatedCollectionType($resourceClass, $graphqlType) : GraphQLType::listOf($graphqlType);
}
```
`getResourcePaginatedCollectionType` is called with `null` for `$resourceClass` and that throws an error. Changing the condition to `if ($this->isCollection($type) && !is_null($resourceClass))` fixed it locally but I'm not sure it's the right way to do it

**Comment by alanpoulain** [comment]
It's weird because the condition `$this->isCollection($type)` shouldn't be true in case of a simple array (not a relation).
I will investigate the issue this week-end maybe.

**Comment by alex88** [comment]
Thanks @alanpoulain
