### ISSUE TITLE
Doctrine fixtures bundle Integrations

### ISSUE THREAD

**Issue by cduran433** [api-platform/core#1748]
Hello,

I want to add some fixtures to my project. This is the class configuration:
```

 *
 * @ORM\Entity
 * @ApiResource(
 *              attributes={
 *                  "normalization_context"={"groups"={"read"}},
 *                  "denormalization_context"={"groups"={"write"}}
 *              },
 *              collectionOperations={"post"},
 *              itemOperations={"get","put"}
 *     )
 */
class Foo
{
}
```

When I execute the fixtures load command (php bin/console doctrine:fixtures:load), I face this error:

`No collection route associated with the type "App\Entity\Foo
`
If I add the get method as a collection operators, it works well but I prefer not to do that to keep as clean as possible the API. Is it possible to be done?

**Comment by dunglas** [comment]
The `GET` method for both items and collection is mandatory (as stated in the docs). At least the route must exist (because the IRI must be dereferencable), but it can return an empty response.

**Comment by cduran433** [comment]
Thank you!
