### ISSUE TITLE
[GraphQL Mutation] will treat `@ORM\Embedded` as `String` type

### ISSUE THREAD

**Issue by leesiongchan** [api-platform/core#1750]

**Comment by leesiongchan** [comment]
Or `graphql` doesn't support `nested mutation` yet?

**Comment by leesiongchan** [comment]
ping @alanpoulain

**Comment by alanpoulain** [comment]
Yes, API Platform doesn't support nested mutations (yet?). You need to give an IRI for an embedded entity. I will document it later. See also this PR: https://github.com/api-platform/core/pull/1702

**Comment by leesiongchan** [comment]
> But for an embedded entity I'm not sure about which behaviour we want.

Do you mean whether to treat it as flat or object? In the meantime, what is the temporary solution to deal with embedded type?

**Comment by alanpoulain** [comment]
Yes. I think it would be better to treat it like a json_array (iterable type, see this PR https://github.com/api-platform/core/pull/1661). In the meantime have you tried to give it as a JSON encoded string?

**Comment by leesiongchan** [comment]
> Yes. I think it would be better to treat it like a json_array (iterable type, see this PR #1661).

Yes, indeed.

>  In the meantime have you tried to give it as a JSON encoded string?

Tested, it still throwing errors :(

**Comment by alanpoulain** [comment]
What are the errors?

**Comment by leesiongchan** [comment]
![error](https://image.ibb.co/c3BcTS/Screenshot_from_2018_03_07_18_09_03.png)

**Comment by alanpoulain** [comment]
I think you are done for, sorry :( You have to wait for a fix.

**Comment by eradionov** [comment]
Seems like not only mutations do not work
query operations do not work as well

**Comment by eradionov** [comment]
Embedded resource does not work for queries as well for graphql
Is it supported in api-platform?
