### ISSUE TITLE
Remove  ResourceController

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#176]
Controllers can (and probably should) be removed. It is not necessary and using only events would be a better design and provide better extensions point in this case.

**Comment by dunglas** [comment]
Try using something list [Action-Domain-Responder](https://github.com/pmjones/adr) or a command bus instead.

**Comment by sroze** [comment]
I don't think that event or command bus is relevant in that case, but ADR far more :)

**Comment by dunglas** [comment]
A command bus like in Laravel for "custom code" can be appropriate too. Maybe a conjonction of both.

**Comment by dunglas** [comment]
Done.
