### ISSUE TITLE
Cache key collision when multiple subresource paths end in same entity

### ISSUE THREAD

**Issue by jmatsumura** [api-platform/core#1769]
Using:

- API-platform 2.1.4
- Symfony 3.4.1

If you have three entities:

1. `Book`
2. `Store`
3. `Library`

With the following relationships:
- `Library` has a one-to-many relationship to `Book`
- `Store` has a one-to-many relationship to `Book`

If both `Library` and `Store` have `@ApiSubresource` annotations for `Book` then the first path (either `/store/#/books` or `/library/#/books`) hit will be set in Symfony's cache pool (using `Book` to perform the lookup) and that cache key will be assigned to the entire resource path. 

So an initial request to `/store/1/books` will lock the cache to any requests that end in `books` to be expecting something like `/store/#/books` so that if you try call `/library/1/books` it fails due to expecting a valid `Store` IRI in the request.

**Comment by themizzi** [comment]
This can be repaired using the same code from 2.2 at the top of CachedRouteNameResolver::getRouteName()

```php
$context = \func_num_args() > 2 ? func_get_arg(2) : [];
$cacheKey = self::CACHE_KEY_PREFIX.md5(serialize([$resourceClass, $operationType, $context['subresource_resources'] ?? null]));
```

We would like to be able to stay on the 2.1 line as it will require us to upgrade a number of custom filters we have. (I work with @jmatsumura). I will open a pull request for this.

**Comment by soyuka** [comment]
Backported. @dunglas should tag a new 2.1 by the end of the week in the mean time you can use the vcs thing! Thanks for the report!
