### ISSUE TITLE
[RFC] Use xkey to purge cache

### ISSUE THREAD

**Issue by jderusse** [api-platform/core#1776]
Reading the PR https://github.com/FriendsOfSymfony/FOSHttpCache/pull/409/files on FOSHttpCache, Their is a more efficient way to purge cache. 

Documentation http://book.varnish-software.com/4.0/chapters/Cache_Invalidation.html#hashtwo-xkey-varnish-software-implementation-of-surrogate-keys

**Comment by dunglas** [comment]
Very interesting. 👍 to support this feature.
It will probably also impact the design of #1689 (ping @Toflar).
We also need to check how we can make the interface/code compatible with both this and CloudFlare's cache tags.

I think we can deprecate the current system for this new one.

**Comment by Toflar** [comment]
Yeah, I've seen that. So - again - another reason to just ask the purger to add the tags in whatever format it wants to. We can extend that and allow the purger not only to format the iris but also modify the response the way it likes. So in code that would look like this:

```php
class VarnishPurger implements NewPurgerInterface
{
    public function purge(array $iris)
    {
        // same/similar logic as now
    }

    public function tagResponse(Response $response, array $iris)
    {
        $response->headers->set('xkey', implode(',' $iris));
    }
}
```

```php
final class AddTagsListener
{
    private $iriConverter;
    private $purger;

    public function __construct(IriConverterInterface $iriConverter, NewPurgerInterface $purger)
    {
        $this->iriConverter = $iriConverter;
        $this->purger = $purger;
    }

    public function onKernelResponse(FilterResponseEvent $event)
    {
        // same/similar logic as now to get $resources/$iris

        $this->purger->tagResponse($event->getResponse(), $resources);
    }
}
```

It just allows to basically do anything. You can add one header, 5 headers, you can have a `ChainedPurger`, I can have my `Psr6CachePurger` and name/format the tags myself etc. Full flexibility and all we have to do is deprecate the current `PurgerInterface` for a new one. Or just leave it in place and provide an `AdvancedPurgerInterface`.

**Comment by Toflar** [comment]
Any feedback on that? 😄

**Comment by teohhanhui** [comment]
Relevant?

https://www.youtube.com/watch?v=1Uzn31cQUQ8

https://cdn2.hubspot.net/hub/209523/file-366502730-pdf/Cache_Invalidation_Strategies_A_Varnish_Webinar.pdf

**Comment by dunglas** [comment]
@Toflar can we make something independent from the Response class? (I plan to add PSR-7 support at some point)?

**Comment by Toflar** [comment]
I don't think this is relevant here because we have Symfony controllers that expect Symfony responses. But when I revamp the concept I'll keep it in mind and see what I can do :)
