### ISSUE TITLE
Custom Operation Paginator

### ISSUE THREAD

**Issue by lori-neogen** [api-platform/core#1793]
Hi,
I used this example to create paging info for routes.
#1548 

I does work, but only for normal routes. I cant make it work for custom operations.
In the Event Subscriber at  KernelEvents::RESPONSE $event->getRequest()->attributes->get('data')) i have instance of the entity and not Paginator, even if i return Paginator from the custom route.

All the values are corect on the Json response, except there is no paging info.
For standard routes the data is paginator at the  KernelEvents::RESPONSE event.

How can i insert paging info in Response Header on Custom routes ?
Also i would like to apply filters to custom routes ... which will affect the paging info.

Any ideas ? Any examples ?

**Comment by gorghoa** [comment]
Hi @lori-neogen,

Did you properly configured your custom operation in the `collectionOperations` (not in the `itemOperations`)?

**Comment by lori-neogen** [comment]
Yes.
Finally i gived up on that.
I managed to get the needed data other way, not with controller/action.
If i create a custom collection operation like this : 

vendor_special"={
              "path"="vendors/{id}/transactions",
              "normalization_context"={"groups"={"vendor_transactions"}},
              "method"="GET"
          }
then it works.
I was using route_name instead of path and i had a controller that returned Paginator.
And used the example with @UserAware() annotation from documentation to filter data based on logged in user.

Thanks.

**Comment by Simperfit** [comment]
This seems to be resolved, feel free to ping me if you still have an issue.
