### ISSUE TITLE
Unable to use PaginationExtension's limit/offset with custom Elasticsearch extension

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#1802]
I'm trying to [replace the lookup part of the process with one based on Elasticsearch](https://github.com/rollerworks/search/blob/master/lib/ApiPlatform/Elasticsearch/Extension/SearchExtension.php#L89-L97).

It works like this:
1. transform the input params into an ES query
2. ES determines exactly which documents match and returns **exact set and order** of entity IDs
3. set those entity IDs directly on the query builder and fetch exactly those entities

So, for this to work, Elasticsearch needs to know the limit/offset, which is provided by the pagination extension.

Sadly, the extension does too much currently as it applies the limit/offset and the immediately fetches the result from QueryBuilder. This means I cannot reuse the functionality and this seems impossible to implement without copy/pasting the relevant code from pagination to my extension.

1. Pagination, Elasticsearch - Elasticsearch never triggered
2. Elasticsearch, Pagination - no limit/offset information

**Comment by ro0NL** [comment]
@meyerbaptiste i still havent come to play with elasticsearch, but this is solved after #1999  isnt it?

**Comment by soyuka** [comment]
Yes @ro0NL thanks!
