### ISSUE TITLE
Bug or feature? Weird resource identificator in GraphQL

### ISSUE THREAD

**Issue by insekticid** [api-platform/core#1806]
I am playing with graphQL and only way how to query some resource is via fqn id in GraphQL query. But i thing, it should be changed and simplified

Look at this query
```
{
  greeting(id: "greetings/1") {
    name
  }
}
```

![image](https://user-images.githubusercontent.com/177340/38166644-7ba6d530-3527-11e8-9a76-2770536241ca.png)

Better sollution is via this standard query. Is this bug or feature?
```
{
  greeting(id: "1") {
    name
  }
}
```

![image](https://user-images.githubusercontent.com/177340/38166650-9d9225dc-3527-11e8-8379-da6c807c49f9.png)

You can watch this GraphQL tutorial https://youtu.be/UBGzsb2UkeY?t=1424

**Comment by dunglas** [comment]
Your proposal isn't valid according to the Relay spec: https://facebook.github.io/relay/docs/en/graphql-server-specification.html#object-identification
Using an IRI allows the API Platform's GraphQL endpoint to be compatible with the REST subsystem, it's a big win when using both together. See the end of https://dunglas.fr/2018/03/symfonylive-paris-slides-rest-vs-graphql-illustrated-examples-with-the-api-platform-framework/ for instance.

Closing.

**Comment by kiler129** [comment]
@dunglas I understand the reasoning, but maybe REST compatibility should be an option (enabled by default)? When you only utilize GraphQL it's kind of strange to handle such ids.
Also, I don't see where making ids plain conflicts with the Realy specification you linked?

**Comment by tigitz** [comment]
I tend to agree that if you chose to only use GraphQL from API Platform, other ways of exposing data in the framework shouldn't "leak" into the one you've chosen.

I get this is for applications wanting to manage both GraphQL and REST but my feeling is that they're the minority compared to "REST only" or "GraphQL only". You might have data that indicates the contrary though.

@dunglas As a "GraphQL only" project developer myself I'm wondering if a mechanism to opt-in or opt-out of this seems reasonable to you ? The default would be opt-in.

**Comment by milosa** [comment]
What bothers me is that this results in URLS looking like:
`localhost/todolist/%2Fapi%2Ftodo_lists%2F123` 
instead of just
`localhost/todolist/123`


Also, a graphql query like this:
`query {  TodoLists(id: "/api/todo_lists/123") { name }}` 

seems a bit verbose to me.
I'm using a TodoList query, yet I also have to use an id specifying the type.

**Comment by dunglas** [comment]
@milosa making class non-final make them very hard to maintain, we prefer to provide the appropriate extension points using composition. You can already change this behavior (for instance to use a UUID, or to base64 encode the IRI, that would be easier to implement and better IMHO) by decorating the `api_platform.iri_converter` service.
