### ISSUE TITLE
Array of non-resource objects on property

### ISSUE THREAD

**Issue by smarijic** [api-platform/core#1807]
Hi,
In my project I have a resource that I want to expose which is not an entity, it's more of a command that tell system to perform an operation. Class looks like this

```
<?php
/**
*@ApiResource()
*/
class A {
  /**
  * B[]
  */
  private $b;
}
```

$b should be array of objects and from some reason in the docs when I check that resource it shows it as a string.

I was looking at this test (https://github.com/api-platform/core/blob/master/tests/Fixtures/TestBundle/Entity/ContainNonResource.php) as an example so I figured it would be possible to do such things.

Any ideas? I am just starting out with API Platform so excuse me if it's trivial question.

**Comment by soyuka** [comment]
This is now supported in 2.4!
