### ISSUE TITLE
Change default priority on autoconfiguration Doctrine DataProvider extensions

### ISSUE THREAD

**Issue by Taluu** [api-platform/core#1815]
Currently, on symfony's dependency injection, the services which implements the doctrine data provider extensions are autoconfigured with tags with a priority = 0 (no priority set).

The thing is, the Pagination extension, which implements the result interface (and thus stops the data provider iteration on its extensions) doesn't leave the other extensions the chance to do something, because it has a priority set to 8.

So my whole point would be to set a default priority to 9, or lower more the pagination's priority so it is executed after the default set. So that no configuration is needed when creating a new extension.

**Comment by soyuka** [comment]
Current:

| Class | Collection Priority | Item Priority |
| ------- | ----------------- | ----------------------- |
| `EagerLoadingExtension`  | 64 | 64 |
| `FilterExtension`  | 32 | ∅ | 
| `FilterEagerLoadingExtension` | 31 | ∅ |
|  `OrderExtension` | 16 | ∅ |
|  `PaginationExtension` | 8 | ∅ |

Proposal : 

| Class | Collection Priority | Item Priority |
| ------- | ----------------- | ----------------------- |
| `EagerLoadingExtension`  | -1 | -1 |
| `FilterExtension`  | -8 | ∅ | 
| `FilterEagerLoadingExtension` | -16 | ∅ |
|  `OrderExtension` | -32 | ∅ |
|  `PaginationExtension` | -64 | ∅ |

Like this we don't add a compiler pass that alters your code. WDYT, would this work?

**Comment by Taluu** [comment]
As long as the `0` is executed by default, anything goes. :}

**Comment by soyuka** [comment]
That's done and is active in 2.4 :)
