### ISSUE TITLE
No specific message if I give a wrong Uuid

### ISSUE THREAD

**Issue by mhlsf** [api-platform/core#1816]
Imagine I create a relation between two people that is a contract.

And I give two uuid corresponding to each person but with one uuid that doesn't correspond to an actual person. Then it try to insert a null value into my database because denormalizeRelation() in the AbstractItemNormalizer return a null if no match are found. 

How can I trow a specific message if the uuid have no correspondance in my database instead of trying to insert the null value (Like "This uuid doesn't correspond to any known person") ?

**Comment by Simperfit** [comment]
Could you please give us the entity you are using ?

It seems that you are lacking some kind of validation.

**Comment by mhlsf** [comment]
What entity do you mean ?

**Comment by Simperfit** [comment]
The one you are using.

I think before it cames to the denormalizeRelation, it should be checked earlier if it's a valid uuid or not ?

You can do this using event listener, to check that the uuid is not a valid value. By the way, you are not using IRIs in this case but plain identifier ?

**Comment by mhlsf** [comment]
I found the solution to my issue, I just had to put an "@Assert\NotNull" that secure giving wrong uuid.

My bad.

**Comment by Simperfit** [comment]
Glad that you found a solution, no problem!
