### ISSUE TITLE
Milestone for the next release?

### ISSUE THREAD

**Issue by Zarthus** [api-platform/core#1818]
Hello, I have a question regarding the next release status as no milestone exists for the next version ( https://github.com/api-platform/core/milestones )

Recently we migrated our software from 1.x to 2.2, and our testsuite duration has increased significantly.

The fix for this is already in place, and visible here: https://github.com/api-platform/core/pull/1725 
This feature is a difference of our test suite running for roughly 4 hours rather than 10 minutes.

Naturally we're not really super keen on using a development branch from composer and would much rather work on a stable branch (and forking the project to add this fix on top is also not super desirable).

For me the question is whether there is a known ETA for the next release version, or whether we're better off running a temporary fork.

Thank you.

**Comment by soyuka** [comment]
Should we backport this to 2.2 @dunglas ?

**Comment by Simperfit** [comment]
I agree this should be backported.
