### ISSUE TITLE
access_control on custom operations 

### ISSUE THREAD

**Issue by ljbergmann** [api-platform/core#1822]
I've created a custom operation for one of my entities and would like to secure it like the other item and collection operations. I've added the "access_control" annotation to the "special "annotation at the entity but i it does not work.

Am i correct, that i have to mange the access control at my custom operation ?
If that is the case it would be very helpful to include this in the documentation. 

P.S My current workarround is to use the IsGranted Annotation from the FrameworkExtraBundle.

**Comment by soyuka** [comment]
> Am i correct, that i have to mange the access control at my custom operation ?

Yes, you have to do this by your own. Adding the security annotation is the way to go.
Because custom operations are nothing more then pure symfony, I'd recommend to check the symfony documentation on the subject: https://symfony.com/doc/current/security.html

Closing this, feel free to ping me.
