### ISSUE TITLE
NameConverter specific for Resource

### ISSUE THREAD

**Issue by ewgRa** [api-platform/core#1823]
For now there is ability to set name converter one for all.

We have a case (mostly about field aliases), when we need specify NameConverter specific to resource.

I check exists information, there is couple of abandoned PR in Serializer, and perhaps API-Platform, but there is no good solution for that. For now we can customize it through Normalizer, Denormalizer, but it require a lot of customization on all levels of configurations and so on.

I can redefine normalizer and give it my custom name_converter for specific resource. It works, but there is problems with SwaggerUI documentation and so on, since it is don't know anything about name converters specific for entities.

Is I miss something and there is good solution for that?

How I see possible solutions?
1.
```
resource_name_converters: 
  - FooClass: foo_service
```
(good performance, backward compatible)

2. everywhere, where api_platform.name.converter is used, introduce new name_converter, that will have function like "normalize($resourceClass, $propertyName)"
(probably broke backward compatibility)

3. tag: api_platform.name_converter with "isSupport" stuff and so on. (worse performance)

I can prepare PR, but before would be nice to be sure that it will not go to trash.

**Comment by soyuka** [comment]
The best for this use case is to simply decorate our metadata factories to change what you need (it can be property/resource wise). 
I'm closing this but feel free to ping me.
