### ISSUE TITLE
Decouple the JSON-LD / Hydra presentation layer from that bundle

### ISSUE THREAD

**Issue by sroze** [api-platform/core#183]
It may be interesting the decouple this JSON-LD / Hydra presentation layer from the bundle itself to be able to use it outside of a Symfony context.

This layer might be extremely useful in other stacks.

**Comment by dunglas** [comment]
Yes it's something I've in my head but there is some dependencies hard to remove:
- the Router Component (hypermedia...)
- the Serializer Component

Anyway, you can already install the bundle in any context and use only classes you need. I'm in the process of reducing the number of dependencies in `composer.json` (#177).

**Comment by dunglas** [comment]
Done (and we also now have HAL and Swagger components)
