### ISSUE TITLE
Can't use a plain id identifier for a relation denormalization

### ISSUE THREAD

**Issue by Taluu** [api-platform/core#1840]
#1762 reverted #1547 to solve a bug, but we were kind of relying on that to be able to fetch / set an entity from its id without using iris or a nested `id` object.

```json
{
    "id": "d1890e8f-fd21-5283-9087-0df87279077d",
    "mainMedia": "d1890e8f-fd21-5283-9087-0df87279077d"
}
```

Used to work up to 2.2.3, but since #1762 (and thus 2.2.4...), it doesn't anymore and triggers an error. I know this is not standard (and kinda relying on a bug...), but it's how the front currently works (I opened a ticket on their side to solve their mess). But still, supporting that would be useful imo.

I have an `IriConverter` decorator, so I could intercept this, but the fact is that in the iri converter, I have no "context" such as the main entity, the property, or its type so I could tinker and make an iri from that before passing it to the decorated service.

**Comment by Taluu** [comment]
It seems that this block : https://github.com/api-platform/core/blob/2.2/src/Serializer/AbstractItemNormalizer.php#L294-L302 doesn't take into account the allowPlainIddentifiers. Unless I read the feature wrong, this doesn't allow to use plain identifier to identify a resource.

**Comment by Taluu** [comment]
So, I kinda got further on that point. It seems that my property is a writable link, So this passes into the normal serializer and never reaches the part when the `allowPlainIdentifier` is executed.

I have 2 objects : A `Product` and `Media`, and they are linked through a `mainMedia` property (which as its setter `setMainMedia`) on the `Product`.

So the request is a PUT on the product, with the body of the first message. And I end up with the `Invalid IRI ?` error.

**Comment by bendavies** [comment]
can this be closed?

**Comment by Taluu** [comment]
Thought this was already closed. Closing then. :}
