### ISSUE TITLE
Slow API requests in dev env when upgrading from 2.1.3 to ^2.1.4

### ISSUE THREAD

**Issue by jonday-simitive** [api-platform/core#1842]
After upgrading to V2.1.4 requests to Api Platform routes in our application became noticeably slower in dev env when recompiling YAML and Annotations. 

I have traced this so far to YamlFileLoader::parseImport ... it appears to be changes to SubresourceOperationFactory::computeSubresourceOperation between 2.1.3 and 2.1.4 which have caused the issue.   

Blackfire Profile 2.1.3:
https://blackfire.io/profiles/4138e961-2f87-4e92-9bab-b91578afdeb2/graph

Blackfire Profile: 2.1.4:
https://blackfire.io/profiles/7d19e9d1-caeb-450c-8d0e-f09d938034d8/graph

**Comment by Simperfit** [comment]
As said this affects devs only (in prod it should not cause any issue since it will be compiled only one time).

@soyuka any idea ? could we improve anyway ?

**Comment by soyuka** [comment]
It's cached https://github.com/api-platform/core/blob/35edfb6ae999cf77e04caf81d9c33cbda9aa3890/src/Operation/Factory/CachedSubresourceOperationFactory.php 

Maybe if someone wants to dig in the subresource operation algorithm but it's tricky.

**Comment by Simperfit** [comment]
Closing as wontfix since it occurs only on dev-mode, you can use https://github.com/api-platform/core/pull/1725 to improve the perf I think.
