### ISSUE TITLE
ApiSubresource not being resolved when using custom data provider

### ISSUE THREAD

**Issue by Ronnie-J** [api-platform/core#1845]
Hi. (question really)

I am trying to add a `ApiSubresource` to my main class in order to establish relation. I would also like for the `ApiSubresource` to be fetched along with the main entity.

So I have an Identity class that has an IdentityItemDataProvider class. This works as expected. (I dont use Doctrine)

I then add 

```
    /**
     * @var PostalAddress|null physical address of the item
     *
     * @ApiSubresource()
     * @Groups({"get", "address"})
     */
    private $postalAddress;
```

As established from the documentation but nothing magically happens to this. I thought it would automatically establish relation. When I explicit (in the `IdentityItemDataProvider`) set the `PostalAddress`object it does show as expected in the output. 

```
{
    "data": {
        "id": "/app_dev.php/identities/123",
        "type": "Identity",
        "attributes": {
            "email": "foo@bar.com",
            "email_verified": true,
            "name": " ",
            "given_name": "",
            "family_name": "",
            "middle_name": null
        },
        "relationships": {
            "postal_address": {
                "data": {
                    "type": "PostalAddress",
                    "id": "/app_dev.php/identities/123/postaladdress"
                }
            }
        }
    }
}
```

But I was under the impression that using a `ApiSubresource` was the same as automatically resolve the `ApiSubresource` in the main Identity entity where it is linked? If this is possible what am I missing?

I have an `PostalAddressItemDataProvider` as well and I can access the data by going to `/identities/{id}/postaladdress`.

**Comment by soyuka** [comment]
I hope you found a solution, if not please came back to us, thanks!

**Comment by Ronnie-J** [comment]
I didn't. I had to discard this approach and haven't revisited it but it's fine that it's being closed as much has changed within a year.
