### ISSUE TITLE
Non-RESTful endpoint ?

### ISSUE THREAD

**Issue by jcerri** [api-platform/core#1849]
Is there a way to handle non-RESTful custom endpoint into api-platform ?
I have to setup a custom endpoint which needs to return multiple resource classes.

**Comment by soyuka** [comment]
Just use a symfony route + controller ?

**Comment by jcerri** [comment]
Thanks, will try that.

**Comment by vesol** [comment]
how we can combine api-platform swagger with these symfony route + controller definitions?

**Comment by dunglas** [comment]
@vesol https://api-platform.com/docs/core/swagger/#overriding-the-swagger-documentation

**Comment by dunglas** [comment]
You can also use https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html

**Comment by vesol** [comment]
@dunglas there is a chance to combine api-platform swagger and nelmio api doc swagger into one documentation endpoint?

**Comment by dunglas** [comment]
Yes, when configured properly, Nelmio will import the API Platform description automatically.
