### ISSUE TITLE
serialize and deserialize from abstract

### ISSUE THREAD

**Issue by komik966** [api-platform/core#1851]
It would be useful to have support for this: http://symfony.com/blog/new-in-symfony-4-1-serialize-and-deserialize-from-abstract-classes

**Comment by sroze** [comment]
How would you like to use it, within ApiPlatform? Because I believe you can already 🤔

**Comment by komik966** [comment]
I was thinking about single endpoint per all classes inheriting from one abstract class. Abstract class is ApiResource, inheriting classes not.
Everything seems to work fine, except properties which are members of inheriting classes.
Here is example: https://github.com/komik966/core/commit/3e8efff9b21b547219a96f3ceba397166f30e341
In example above properties `BitBucketCodeRepository::integratedWithHipChat`, `GitHubCodeRepository::stargazer` after deserialization are always null. This problem exists only when I add annotation `@ApiResource` to abstract class `CodeRepository`

Maybe my configuration is wrong - I'll investigate it once again.
