### ISSUE TITLE
Pagination: Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#1860]
I've accidentally called endpoint with page parameter as js object which was casted to [object Object] and surprisingly i've got 500 instead of 400? or just ignoring the page.

Pagination doesn't check if the received page value is numeric before dealing with calculations.

**Comment by Simperfit** [comment]
Thanks for giving us this feedback!

@norkunas do you want to provide the pull request fixing it ?

**Comment by Simperfit** [comment]
Thanks anyway!
