### ISSUE TITLE
Identifier with (de)normalization contexts

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#187]
When using (de)normalization contexts by using serialization groups with Doctrine ORM, groups should not have any impact on the `@ORM\Id` property. If the identifier must be settable, a setter should be provided for it, regardless of the context.

Now this behaviour works fine as of now. But when dealing with embedded relation, not anymore. If I have the entities `User` and `Books` with serialization groups to display some of `Books` properties when retrieving a `User` resource, the `LoaderChain::checkClassMetaData()` will fail if I forget the proper serialization group on `Books` identifier property.

**Comment by dunglas** [comment]
Can you try with https://github.com/dunglas/DunglasApiBundle/pull/180

It changes the identifier system in deep.

**Comment by theofidry** [comment]
No idea of the current test but is definitely worth some tests...

**Comment by dunglas** [comment]
Fixed and tested.
