### ISSUE TITLE
Unable to use `swagger_context` in subresource

### ISSUE THREAD

**Issue by jeffreymb** [api-platform/core#1873]
I have a subresource definition on a DTO class as follows:
```
 *     subresourceOperations={
 *          "chapters_get_subresource"={
 *              "path"="bibles/{version}/books/{book}/chapters",
 *              "swagger_context"={
 *                  "parameters"={
 *                      {"name"="version", "in"="path", "type"="string", "required"=true},
 *                      {"name"="book", "in"="path", "type"="string", "required"=true},
 *                  },
 *              },
 *          },
 *     },
```

The `swagger_context` has no effect in the swagger UI. Am I doing something wrong or is this a bug?

**Comment by jeffreymb** [comment]
Perhaps you are correct that this should be a custom collection operation instead of a subresource, but the bug remains that it isn't currently possible to set a custom swagger context in a subresource.

**Comment by soyuka** [comment]
Indeed `swagger_context` is missing [here](https://github.com/api-platform/core/blob/e0dfbcd787948a9018962541b275198050bb74bd/src/Swagger/Serializer/DocumentationNormalizer.php#L130). Although I'm not sure that we should support this because you shouldn't need it and do a custom operation instead :).

**Comment by soyuka** [comment]
merging with https://github.com/api-platform/core/issues/2706

**Comment by brunonic** [comment]
In my case, I need to change my subresource operation tags in swagger, it's not possible now and this is not cool.
