### ISSUE TITLE
Relations are eagerly loaded even when set to false on OneToOne EXTRA_LAZY properties

### ISSUE THREAD

**Issue by jayesbe** [api-platform/core#1889]
/**
     * @var \AppBundle\Entity\Referral $reference
     * 
     * @ApiProperty(attributes={"fetchEager": false})
     * @ORM\OneToOne(targetEntity="\AppBundle\Entity\Referral", mappedBy="referred", fetch="EXTRA_LAZY", cascade={"remove"})
     */
    private $reference;

This relation is still eagerly loaded and should not be. Only happens on OneToOne from what I can see.

**Comment by bendavies** [comment]
does https://github.com/api-platform/core/pull/1897 resolve this?

**Comment by soyuka** [comment]
Closing as no answer and indeed this should be fixed. Feel free to ping me if that's not the case.
