### ISSUE TITLE
DataProvider Overhead?

### ISSUE THREAD

**Issue by jayesbe** [api-platform/core#1898]
I have numerous tables that have an ID but also a combination (Client ID, Client External ID) as a unique index.

I would like to expose data based on client id naturally. If I create a data provider for each entity that has this combination, I could have almost as many data providers as I have entities.  

If we assume, say, 50 data providers that have been defined all with priority 5. Will the platform iterate through each provider until a matching provider is found? ie, O(n) in the worst case to determine the provider required ?  Or does the platform determine which provider(s) prior to will be required?

If the former, is there anyway to reduce this overhead to a O(1) considering these data providers would be scanned on each request? Maybe, adding a "provider" to an operation..

    /**
     *
     * @ApiResource(attributes={
     *       "normalization_context"={"groups"={"API_READ"}},
     *       "denormalization_context"={"groups"={"API_WRITE"}}
     *     },
     *     collectionOperations={},
     *     itemOperations={
     *       "getBySpecialId"={
     *         "provider"=CustomerAccountItemDataProvider::class, <---- something like this, rather than defining a kernel event listener
     *         "method"="GET",
     *         "path"="/customer-account/{id}",
     *         "controller"=CustomerAccountAction::class,
     *         "force_eager"=true
     *       }
     *     }
     * )
     */

**Comment by jayesbe** [comment]
Just noticed the RestrictedDataProviderInterface

However, still wondering about the above..

**Comment by soyuka** [comment]
If you have 50 things to do that look alike I think you could make this work with only one data provider or maybe a query extension.

About the above, we can declare a `Controller` per operation but the data provider works through the RestrictedDataProviderInterface indeed. See https://github.com/api-platform/core/blob/master/src/DataProvider/ChainItemDataProvider.php#L43 

@bendavies we could also add a localCache there now that I think of it :p.

**Comment by antograssiot** [comment]
Closing this, I agree with @soyuka
