### ISSUE TITLE
Injecting required data in to the constructor during denormlization?

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#1903]
Most of my entities are tied to a particular Account entity, which is set based on the authentication details of the user accessing the API.

As my entities are required to set this property priority to being written to the database, I need to find a way to set this property through the serializer when an object is created through the API. 

For example:

```php
class User {
    /**
     * @ORM\Id
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Account")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    public function __construct(Account $account)
    {
        $this->account = $account;
    }
}
```

Since this account property is based on the authenticated user, I do not want this property to be writeable by the user, but I still need to inject it in to the serializer somehow so that it is set when a new User entity is created.

I thought about using Doctrine prePersist event, but certain validators require the account property to be set to function properly (for example... User must have a unique email address per Account), so this won't work for me.

What is the best way to go about doing this?

**Comment by bwegrzyn** [comment]
Allowing to override the context for GraphQL calls as I mentioned in #1904 would solve this.

I am able to do this for REST calls, but not for GraphQL calls.

**Comment by soyuka** [comment]
Closing this in favor of #1904
