### ISSUE TITLE
Unable to specify custom serializer context for GraphQL calls

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#1904]
The context for GraphQL calls is [hard coded](https://github.com/api-platform/core/blob/d4cfd02c1209ab315e57e7171e6b1cedf5d61762/src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php#L92) instead of using a ContextBuilder service and is impossible to override.

It would be nice to be able to override it so we could set things such as `default_constructor_arguments` introduced in symfony/symfony#25493.

Currently, for REST calls we can decorate the `api_platform.serializer.context_builder` service to add custom context properties, but this is not possible for GraphQL calls.

**Comment by Simperfit** [comment]
Do you want to work on this ? I think we can introduce a contextbuilder service.

**Comment by alanpoulain** [comment]
Done in master: https://api-platform.com/docs/master/core/graphql/#changing-the-serialization-context-dynamically
