### ISSUE TITLE
The total number of joined relations has exceeded the specified maximum

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#1910]
I have two entities, one representing a `Todo`

```
// Todo entity
/**
 * @ORM\Table(name="coo_app_todos")
 * @ORM\Entity()
 * @ApiResource(
 *     attributes={
 *        "normalization_context"={"groups"={"todo"}}
 *     },
 *     itemOperations={
 *          "get",
 *          "put"={"normalization_context"={"groups"={"put"}}}
 *     }
 * )
 */
class Todo
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups({"todoList", "todo"})
     */
    private $id;

    /**
     * @var TodoList
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\TodoList", inversedBy="todos")
     * @ORM\JoinColumn(name="toto_list", referencedColumnName="id")
     * @Groups({"todo", "put"})
     */
    private $todoList;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Groups({"todoList", "todo", "put"})
     */
    private $name;

    ...

}
```

and one representing a `TodoList`:

```
// TodoList
/**
 * @ORM\Table(name="coo_app_todo_lists")
 * @ORM\Entity()
 *
 * This makes possible to return also the todos associated to the fetched TodoList.
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"todoList"}}
 * })
 */
class TodoList
{

    ...

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Todo", mappedBy="todoList")
     * @ORM\OrderBy({"opened" = "DESC"})
     * @ApiSubresource()
     * @Groups("todoList")
     */
    private $todos;

    ...

}
```

A `Todo` is obviously associated to a `TodoList` and I need that when I fetch a Todo, I get also some details of the `TodoList`.

But this configuration doesn't permit me to create new `Todo`s as I receive this error:

> The total number of joined relations has exceeded the specified maximum. Raise the limit if necessary, or use the \"max_depth\" option of the Symfony serializer.

I'm trying with a payload like this:

```json
{
    "todoList": "/api/todo_lists/1",
    "name": "Vediamo che succede"
}
```

Nothing complex: just the name of the `Todo` and the `TodoList` in which it is.

I've tried to add  `"put"={"normalization_context"={"groups"={"put"}}}` to the `itemOperations` but this didn't solved my problem.

Any ideas of how I can solve this problem?

I need that the `TodoList` is embedded in the response I receive for a single `Todo` and, obviously, I want to be able to also create new `Todo`s.

Thank you!

PS

The api documentation is telling me that the payload should be something like this:

```jason
{
  "todoList": {
    "account": "string",
    "name": "string",
    "createdAt": "2018-04-30T14:24:44.463Z",
    "updatedAt": "2018-04-30T14:24:44.463Z"
  },
  "name": "string",
  "description": "string",
  "opened": true,
  "createdAt": "2018-04-30T14:24:44.463Z",
  "updatedAt": "2018-04-30T14:24:44.463Z"
}
```

So I think that there is something wrong with the configuration of the embedding...

**Comment by soyuka** [comment]
There's a relation joining recursivity.
Two solutions:
1. Disable eager loading ( https://api-platform.com/docs/core/performance#eager-loading ) https://github.com/api-platform/core/issues/876#issuecomment-266053664 
2. Use `@MaxDepth` with `enable_max_depth: true`

```php
@ApiResource(attributes={"normalization_context": {"groups"={"todolist"}, "enable_max_depth"=true}})
```

**Comment by Aerendir** [comment]
@soyuka , thank you for your fast reply!

Can you provide me with an example, please?

I've tried to use `enable_max_depth` and the annotation `@MaxDepth` as shown in the Symfony's Serializer doc, but the problem isn't solved, so maybe I'm continuing to configure it wrong...

**Comment by br750** [comment]
work for me 👍 
`@ApiResource(attributes={
 *     "force_eager"=false,
 *     "normalization_context"={"groups"={"readCO"},"enable_max_depth"=true},
 *     "denormalization_context"={"groups"={"writeCO"},"enable_max_depth"=true}
 *     
 *     
 * })`

**Comment by br750** [comment]
work without "force_eager"=false TOO
