### ISSUE TITLE
Configure route identifiers for subresources

### ISSUE THREAD

**Issue by lucascourot** [api-platform/core#1918]
Hi,

is it possible to customize the route identifier names in ApiPlatform when using subresources?

Example:
I want my route 
`/api/customers/{id}/entity_types/{entityTypes}/layouts` 
to become 
`/api/customers/{customerId}/entity_types/{entityTypeId}/layouts` 
so that I can easily implement a custom SubresourceDataProviderInterface.

I quickly tried to figure out where the magic was done and found out this method
https://github.com/api-platform/core/blob/d9d0e04402703e202db7ddd476fd591819e5ca12/src/Operation/Factory/SubresourceOperationFactory.php#L114
For me it looks like it's not configurable but I wanted to ask to be sure.

Thanks.

**Comment by soyuka** [comment]
Oh you just want to customize parameters names. I looked into this and it's not supported (yet?). Indeed, they're generated in the SubresourceOperationFactory (and the names have a special meaning to find associations later in the SubresourceOperationDataProvider). I doubt that this would be an interesting feature though.

About your data provider you should be able to create one without changing those identifiers names, they will be:

```php
<?php

[
  'id' => 1, // customerId, or the root of the subresource
  'entityTypes' => 2 // entity type id
]
```

One thing that may work is to override the whole path of the subresource operation (see custom operation in the docs) and add your own data provider.

**Comment by soyuka** [comment]
> parameter names conflict with each other.

They don't conflict, I mean for 1 route there are no parameters with the same name :).

> First generated route
/api/customers/{id}/entity_types/{entityTypes}/layouts
Here the entity type id is named entityTypes
> 
> Second generated route
/api/entity_types/{id}/layouts
Here the entity type id is named just id sob

Yes, the `subresource_context` is there to help you make a correlation between entity and id.

You should be able to override the subresource operation path:

```
@ApiResource({subresourceOperations={"find_name_here": {"path": "/my/new/path"}})
```

**Comment by lucascourot** [comment]
Thanks, `subresourceOperations` did the job. But now, my Swagger is completely lost.

The route is now correct (`
/api/customers/{customerId}/entity_types/{entityTypeId}/layouts`) but the parameters are still called `id` and `entityTypes`. The "try it out" feature doesn't work either.

**Comment by soyuka** [comment]
check: https://github.com/gries/api-platform/pull/1/files  and https://github.com/api-platform/api-platform/issues/644

**Comment by lucascourot** [comment]
yes but your links don't mention the possibility to rewrite the parameter names of the default routes (getItem, getSubresource, etc.).
I rewrote all of the them but I now get errors `Unable to generate an IRI for the item of type ...` because it internally tries to generate routes by passing values for params named "id" etc.

**Comment by soyuka** [comment]
I guess there is some more work to be done here then :). What would be a potential solution for your issue?

**Comment by soyuka** [comment]
related to https://github.com/api-platform/api-platform/issues/1022 merged in https://github.com/api-platform/core/issues/2706
