### ISSUE TITLE
Cannot return HTML in custom operation

### ISSUE THREAD

**Issue by Toflar** [api-platform/core#1920]
The `SwaggerUiListener` checks if the request accepts `HTML` and if either `_api_resource_class` or `_api_respond` is set. For a custom operation you always have an `_api_resource_class` which means you can never return HTML responses as the listener will just override the controller.

**Comment by Toflar** [comment]
No it just checks for `->has('api_respond')` which doesn't care if it's true or false :)

**Comment by soyuka** [comment]
`api_respond` is now checked as a boolean.

**Comment by kayneth** [comment]
Hello. 
The initial request from @Toflar was to be able to return an html response from a custom operation.
But the condition would always be falsy when doing some custom operation with html format.

Shouldn't it be :
```php
if (
 'html' !== $request->getRequestFormat('') ||
 !$request->attributes->has('_api_resource_class') ||
 !$request->attributes->getBoolean('_api_respond', false)
) {
   return;
}
```
instead of : 
```php
if (
 'html' !== $request->getRequestFormat('') ||
 !($request->attributes->has('_api_resource_class') || $request->attributes->getBoolean('_api_respond', false))
) {
   return;
}
```

Thank you :smile:
