### ISSUE TITLE
Feature suggestion: support property level normalization/denormalization context

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#1922]
Usage: being able to specify date formats on date times.

```
/**
 * @ApiProperty(
 *  attributes={
 *      "normalization_context": {
 *          "datetime_format": "Y-m-d"
 *      }
 *  }
 * )
 */
```

Secondary, could we default the date time format if the doctrine type was `date` as opposed to `datetime`?

**Comment by soyuka** [comment]
Steps that should make this work:

1. create a new Normalizer that is
  - metadata-aware
  - supports datetime class
2. parse metadata 
3. instantiate a DateTimeNormalizer with the format given as constructor argument

Currently I use the following workaround:

- my own Date classes (extends DateTime) with `__toString()` methods to get proper format
- my own DateTimeNormalizer (extends Syfmony's DateTimeNormalizer) to add to the supported types my own classes

**Comment by raresserban** [comment]
No updates on this?

**Comment by teohhanhui** [comment]
@raresserban It'd require property-level context support in Symfony Serializer first. Please open a feature request with Symfony if you're keen to see this happen.

**Comment by llupa** [comment]
I know this has been open for a while, but if it is ever done so that it can be configured on API property level. I have the "opposite" issue in my project 😅 

````php
/**
* @var DateTime
*
* @ORM\Column(name="from_time", type="time")
*/
private $from;

/**
* @var DateTime
*
* @ORM\Column(name="to_time", type="time")
*/
private $to;
````

Could we also default the date time format if the doctrine type was `time` as opposed to `datetime`?

PS. I'd like to help but IDK where to start?

**Comment by alanpoulain** [comment]
Related PR in Symfony: https://github.com/symfony/symfony/pull/39399.

**Comment by alanpoulain** [comment]
Related docs PR: https://github.com/api-platform/docs/pull/1379.
