### ISSUE TITLE
Hydra Normalization on custom action

### ISSUE THREAD

**Issue by timotheemoulin** [api-platform/core#1935]
Hi,
I have a custom action that gather entities and return them as a JSON output.
How can I add all the **hydra** data to my output?
Here is the shortened class.

```php
class PointOfSaleController extends Controller
{
    /**
     * @Route(
     *     name="action_pos_transactions",
     *     path="/pointofsales/{id}/transactions"
     * )
     * @Method("GET")
     * @param Request $request
     * @return JsonResponse
     */
    public function transactionsAction(Request $request): JsonResponse
    {
        /** @var EntityManager $em */
        $em = $this->container->get('doctrine.orm.entity_manager');

        /** @var TransactionRepository $transactionRepository */
        $transactionRepository  = $em->getRepository(Transaction::class);

        $transactions = $transactionRepository->getByPos($request->get('id'));

        $classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader()));
        $normalizer = new ObjectNormalizer($classMetadataFactory);
        $serializer = new Serializer(array($normalizer));

        $data = $serializer->normalize($transactions, 'json', ['groups' => ['read_transaction']]);

        // @todo add hydra wrapper

        return new JsonResponse($data, Response::HTTP_OK);
    }
```

Can I use the same normalizer that is used by the automatically generated controllers? If yes, how, I can't find it in the docs.

Thanks
tim

**Comment by jenaye** [comment]
Hi @timotheemoulin ,

I think you shouldn't create a new response even with a custom action
in my opinion you should just return your content as shown in the example in the documentation here : 
https://api-platform.com/docs/core/operations/#recommended-method

and it will return the JSON with all hydra keys
just try to return u're $transactions

best regards
Mike,

**Comment by timotheemoulin** [comment]
Hi @jenaye ,
just returning the `$transaction` doesn't work because I need to return a `Response` object and not a collection. Simply returning it as stated in the doc seems to only work on subresources.

So what if I just want to return a simple object or collection that is not related to an entity.

Regards,
Timothée

**Comment by teohhanhui** [comment]
The normalizers in API Platform are mostly only useful for working with classes which have `ResourceMetadata` (i.e. with `@ApiResource` annotation). The same is true for the documentation normalizers.

Otherwise you're on your own.

**Comment by timotheemoulin** [comment]
Ok, so you would suggest to use a custom normalizer to wrap my response data?

**Comment by teohhanhui** [comment]
I actually don't understand why you would return something that is not an `@ApiResource` but still should have Hydra docs?

**Comment by timotheemoulin** [comment]
Well a `Transaction` is an `@ApiResource`

```php
/**
 * An transaction is composed of one to many products.
 *
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"read_transaction"}},
 *     "denormalization_context"={"groups"={"write_transaction"}}
 * })
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TransactionRepository")
 * @AppBundleConstraints\TransactionInOut
 */
class Transaction
{
```

but if I return `$transactions` which is an array returned by `\Doctrine\ORM\EntityRepository::findBy` I get the error `The controller must return a response (Array(0 => Object(AppBundle\Entity\Transaction), 1 => Object(AppBundle\Entity\Transaction)) given).`

```php
/**
 * @Route(
 *     name="action_pos_transactions",
 *     path="/pointofsales/{id}/transactions"
 * )
 * @Method("GET")
 * @param Request $request
 * @return array
 */
public function transactionsAction(Request $request): array
{
    /** @var EntityManager $em */
    $em = $this->container->get('doctrine.orm.entity_manager');

    /** @var TransactionRepository $transactionRepository */
    $transactionRepository  = $em->getRepository(Transaction::class);

    $transactions = $transactionRepository->getByPos($request->get('id'));

    return $transactions;
}
```

**Comment by timotheemoulin** [comment]
Hi, I finally managed to output a correct response with that : 

```php
class PointOfSaleController extends Controller
{
    /**
     * @Route(
     *     name="action_pos_transactions",
     *     path="/pointofsales/{id}/transactions",
     *     methods={"GET"},
     *     defaults={
     *         "_api_resource_class"=PointOfSale::class,
     *         "_api_item_operation_name"="special"
     *     }
     * )
     */
    public function __invoke(Request $request, PointOfSale $data)
    {
        return $data->transactionsTo;
    }
}
```

This outputs all the transactions linked to my PointOfSale with all the correct wrapper.
