### ISSUE TITLE
Cannot POST id to create new resources

### ISSUE THREAD

**Issue by Toflar** [api-platform/core#1937]
Currently, it's not possible to create new resources while providing a custom `id` attribute because APIP will prevent from doing so saying `Update is not allowed for this operation.`.

This is caused by checking `$context['api_allow_update']` in the serializer which is set in the `SerializerContextBuilder`. Basically updating is allowed if the request was a `PUT` or `PATCH` request.

This is check nonsense for two reasons:

* First of all, it's hardcoded on `id` so if my identifier is named `uuid` this check has no effect.
* It's perfectly valid to send a POST request with an identifier, in case the resource **did not exist yet**

So I'd like to remove that check completely.

The next step would be the question if we want to validate this and imho there's only one solution to this: The serializer is the only one knowing whether an identifier was (or multiple were) provided or not. Right now it's hardcoded to `id` but instead we should use the `IdentifiersExtractor` to ask for all of them. Then we need to ask the `ItemDataProvider` if an item for these `$identifiers` already exists and **only if so, we need to throw the exception**. That would mean the serializers need both an instance of `IdentifiersExtractorInterface` and `ItemDataProviderInterface`. Also, it's actually the same for all the serializers. But I'm not really sure, the list of constructor arguments goes on and on and on for the serializers. This is usually not a good sign and maybe means we need to refactor something else first? Wdyt?

**Comment by dunglas** [comment]
I agree, this check isn't the good way to fix this problem. However it has been introduced to fix a real issue, I think we should dive into the history of it, and find a better fix :)

**Comment by dunglas** [comment]
> This is usually not a good sign and maybe means we need to refactor something else first? Wdyt?

Indeed, but it should be done on the Symfony Serializer side first.

**Comment by Toflar** [comment]
The better fix was already proposed 😄 And I could implement it on the `AbstractItemSerializer`. It just means I have to inject two new services which is a BC break.

**Comment by dunglas** [comment]
As long as they are optional (they can trigger a deprecation notice to make them mandatory in 3.0), it's not a BC break. But maybe we'll we find something more elegant when coding/refactoring. Don't hesitate to open the PR to discuss this.

**Comment by Toflar** [comment]
I've created a PR to outline my ideas https://github.com/api-platform/core/pull/1939

**Comment by soyuka** [comment]
See reasoning in https://github.com/api-platform/core/pull/2022#issuecomment-399402142. You can always decorate the ItemNormalizer to implement your own logic.
