### ISSUE TITLE
[JSON-API] Normal filters + sorting filters doesn't work

### ISSUE THREAD

**Issue by cluis13915** [api-platform/core#1940]
I have seen this few weeks ago but I have not had time to create the issue.

If I use `filter` and `sort` query parameters at the same time, one overwrites the other. I don't remember who overwrites whom.

As quick solution for me, I changed from the listener ApiPlatform\Core\JsonApi\EventListener\TransformFilteringParametersListener the way `_api_filters` is set.

`$request->attributes->set('_api_filters', $filters);`

to

`$request->attributes->set('_api_filters', array_merge(`
 `   $request->attributes->get('_api_filters', []),`
 `   $filters`
`));`

I'm using **v2.2.1** version. Thanks for your work. Sorry for my bad english.

**Comment by antograssiot** [comment]
Can you try to update to the latest 2.2.x version
I was unable to reproduce a failing test, and tried the following:

```
Scenario: Get filtered collection ordered - Issue #1940
    When I send a "GET" request to "/dummies?sort=-id&filter[dummyDate][after]=2015-04-28"
    Then the response status code should be 200
    And the JSON should be valid according to the JSON API schema
    And the JSON should be deep equal to:
    """
    {
       "links": {
           "self": "\/dummies?sort=-id&filter%5BdummyDate%5D%5Bafter%5D=2015-04-28"
       },
       "meta": {
           "totalItems": 2,
           "itemsPerPage": 3,
           "currentPage": 1
       },
       "data": [
           {
               "id": "\/dummies\/29",
               "type": "Dummy",
               "attributes": {
                   "description": "Smart dummy.",
                   "dummy": null,
                   "dummyBoolean": null,
                   "dummyDate": "2015-04-29T00:00:00+00:00",
                   "dummyFloat": null,
                   "dummyPrice": null,
                   "jsonData": [],
                   "arrayData": [],
                   "name_converted": null,
                   "_id": 29,
                   "name": "Dummy #29",
                   "alias": "Alias #1",
                   "foo": null
               }
           },
           {
               "id": "\/dummies\/28",
               "type": "Dummy",
               "attributes": {
                   "description": "Not so smart dummy.",
                   "dummy": null,
                   "dummyBoolean": null,
                   "dummyDate": "2015-04-28T00:00:00+00:00",
                   "dummyFloat": null,
                   "dummyPrice": null,
                   "jsonData": [],
                   "arrayData": [],
                   "name_converted": null,
                   "_id": 28,
                   "name": "Dummy #28",
                   "alias": "Alias #2",
                   "foo": null
               }
           }
       ]
   }
    """
```

And the order of sort parameter and filtering doesn't seems to impact the result either...

**Comment by antograssiot** [comment]
@MyDigitalLife `itemsPerPage` is not parsed here in your case.

You should be using it like this test is showing https://github.com/api-platform/core/blob/1d5f020eb55705ed1d58f0c5269631b439dfd08d/features/jsonapi/pagination.feature#L28

and that is handled in `ApiPlatform\Core\JsonApi\EventListener\TransformPaginationParametersListener` and filled into `_api_filters`

**Comment by MyDigitalLife** [comment]
@antograssiot That did fix my problem. I do find it a bit strange that this is not documented (as far as i can see) and is not the way that is shown in the documentation. Looking at this https://api-platform.com/docs/core/pagination/#globally-3 you see there is a example that uses just ?itemsPerPage=15 as a example. Documentation might need to be updated.

**Comment by soyuka** [comment]
Can you help us improve the documentation? Thanks!

**Comment by juffin-halli** [comment]
I found that `TransformFilteringParametersListener` could overwrite _api_filters attribute (it does not consder already existing value in this property). So if this listener would be used last - all the values except filtering params will be lost. And this listener is really used last: it has same priority and last order in `vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml`.

**Comment by soyuka** [comment]
Would you be able to send a fix?
