### ISSUE TITLE
IriConverter error with SubResource after migrate 2.2.6

### ISSUE THREAD

**Issue by thomasglachant** [api-platform/core#1951]
I just upgrade from `2.2.5` to `2.2.6` and when I use : 
```
$entity = $iriConverter->getItemFromIri('/entities/1');
```

I have this error : 
```
PHPUnit\Framework\Error\Notice: Undefined index: subresource_context

/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:108
/project/vendor/api-platform/core/src/DataProvider/OperationDataProviderTrait.php:107
/project/vendor/api-platform/core/src/Bridge/Symfony/Routing/IriConverter.php:81
```

I don't use the subresource in my project so I checked the IriConverter and OperationDataProviderTrait and I think we use `$attributes['subresource_context']` but this index is not set when no subresource used.

**Comment by dunglas** [comment]
> It's werid, can you dump $attributes in https://github.com/api-platform/core/blob/2.2/src/DataProvider/OperationDataProviderTrait.php#97 ? item_operation_name should be defined but there may be a bug here.

We cannot rely on this (the normalize can be used "by hand", without any context). And it should work.

**Comment by soyuka** [comment]
Yes, `$attributes` comes from https://github.com/api-platform/core/blob/2.2/src/Bridge/Symfony/Routing/IriConverter.php#L71 (router)

**Comment by thomasglachant** [comment]
I agree with @dunglas , I use this in a symfony command so I don't have a full context with `item_operation_name`.

**Comment by soyuka** [comment]
I'm not talking about the context, the call to `router->match` doesn't return `item_operation_name`?

**Comment by thomasglachant** [comment]
@soyuka I just check and `$attributes` value is an empty array in this case.

**Comment by soyuka** [comment]
And `$parameters`? 

https://github.com/api-platform/core/blob/2.2/src/Bridge/Symfony/Routing/IriConverter.php#L71

There should be at least a `resource_class` ^^".
