### ISSUE TITLE
Why is swagger property type determined as `string` for non-resource objects?

### ISSUE THREAD

**Issue by olivermack** [api-platform/core#1955]
Hi,

I just came across a smaller thing that I don't find a proper reason about so I'm looking for a "PR's are welcome" or an explanation :)

The `\ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer::getType()` has the following parts: 

https://github.com/api-platform/core/blob/14432bd01c9ba98221097b287a41e4aee67d658a/src/Swagger/Serializer/DocumentationNormalizer.php#L582-L601

As I can see we're already in an `if (Type::BUILTIN_TYPE_OBJECT === $type)` condition and are setting the type `string` if the method did not get a `$className` (L583) or the given `$className` is not a ResourceClass (L591) - why is that? Why not directly return `object` in those cases?

Background: I have a couple of properties that with annotations like `@ApiProperty(iri="https://schema.org/PostalAddress")` where the referenced Object is a custom POPO/DTO which is not a resource class per se - I've added a custom doctrine datatype that treats those kinds as `JsonSerializable` objects and stores a string. All the serialization and deserialization is working fine but the swagger spec does not comply to this concept anymore.

Would it be _wrong_ to change the respective lines to return `['type' => 'object']`?

Best

**Comment by dunglas** [comment]
I may be wrong, but IIRC the `object` type doesn't exist in the Swagger specification. An object must be defined by a proper JSON Schema. What we may do in this case, is adding a JSON schema allowing any object, and reference this JSON schema in the Swagger docs.

What would be even better (for DTOs, embedded object like this one etc) is to generate a valid JSON Schema using https://github.com/dunglas/php-to-json-schema (or something similar).

PR's are welcome :D

**Comment by olivermack** [comment]
Yeah, that sounds sane, indeed ;)... Actually I thought that there is some sort of `object` primitive but you're right, I don't see it in the specs.

I'll make my mind up about your suggestions today to see what might fit in my situation. Thanks for your suggestion though! If I find something sustainable I'll drop it here and maybe even submit a PR. 

Other than that I guess this issue can be closed as you already gave a valid answer :)
