### ISSUE TITLE
Swagger documentation: Could not resolve reference

### ISSUE THREAD

**Issue by seb2411** [api-platform/core#1969]
When the resource short-name contain a slash the Swagger documentation fail to link the ref and fire error saying "Could not resolve reference ...".

It can be fix by converting every slash by something else (like a -) when generating the definition key in the function getDefinition.

I think this bug was fixed in last version of Swagger UI.

**Comment by dunglas** [comment]
It looks like a bug in Swagger UI to me. But we may `urlencode()` the short name to prevent this bug. Would you mind opening a PR?

**Comment by dunglas** [comment]
Maybe can we just execute https://github.com/api-platform/core/blob/master/update-js.sh to update Swagger UI :D

**Comment by dunglas** [comment]
> Do you want me to push the last version of Swagger UI as a PR ?

Yes please.

> Replacing the slash by a dash or underscore in the reference key is doing the job but it's little bit "magic".

Can you try with a call to `urlencode` (it will be cleaner)? If it works, a PR would be very welcome too.

**Comment by seb2411** [comment]
The Swagger UI PR is done. I fixed the update script too.

**Comment by seb2411** [comment]
For the urlencode() is working but I have the %2 appearing in the model section of the resources instead of the `/`. In the models at the bottom of the page everything is ok. I will try to find some alternative solution tomorrow.

**Comment by dunglas** [comment]
The best solution would be to fix Swagger UI directly :D

**Comment by hkosova** [comment]
The characters `/` and `~` in node names must be encoded as `~1` and `~0` when used in a `$ref`, and other special characters must be percent-encoded.

```
definitions:
  Foo/Bar«Baz» :

=>

$ref: '#/definitions/Foo~1Bar%C2%ABBaz%C2%BB'
```

From the [JSON Pointer Specification](https://tools.ietf.org/html/rfc6901) (emphasis mine):

> 3. Syntax
> ...
> Because the characters '\~' (%x7E) and '/' (%x2F) have special meanings in JSON Pointer, **'~' needs to be encoded as '~0' and '/' needs to be encoded as '~1' when these characters appear in a reference token.**

> 6. URI Fragment Identifier Representation
> A JSON Pointer can be represented in a URI fragment identifier by encoding it into octets using UTF-8 [RFC3629], **while percent-encoding those characters not allowed by the fragment rule in [RFC3986].**

By the way, in OpenAPI 3.0 characters other than `a-zA-Z0-9 _ . -` are [no longer allowed](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#componentsObject) in model names.

**Comment by dunglas** [comment]
Thanks for pointing this @hkosova!

**Comment by Simperfit** [comment]
Do we have something to do here ?

**Comment by stchr** [comment]
@dunglas Please have a look at my try #3669. Would adjust this as needed. Feedback is welcome!
