### ISSUE TITLE
Bad Behaviour ? Leaking generic comments from the entity

### ISSUE THREAD

**Issue by seb2411** [api-platform/core#1978]
Hello,

A behaviour of the current API-Platform is too get generic code comments from the property and entity and expose them as Description (if no description is given). I don't think it's a good behaviour by default. The comment can be related to the code or for internal use only.

What do you think ?

**Comment by dunglas** [comment]
It's intended, `@ApiResource` are by definition the **public** data model. See https://github.com/api-platform/core/issues/1747#issuecomment-391308202

**Comment by dunglas** [comment]
By the way, this behavior can be disabled by removing the `api_platform.metadata.resource.metadata_factory.php_doc` service. It would be nice to add an entry in the documentation mentioning this point. Would you mind opening a doc PR?
