### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#198]
Add doc with guidelines for performance improvements.

**Comment by rolebi** [comment]
Axe of improvements:
- Custom `PropertyAccess` with lightweight logic
- Custom `Serializer` to ignore normalization of scalar values

**Comment by dunglas** [comment]
IMO specialized property accessor such as a GetSetMethodPropertyAccessor can be contributed upstream to Symfony.
They can help to improve performance in a lot of other contexts when the project is under control (e.g. always have accessor methods). cc @webmozart
