### ISSUE TITLE
Allow WritableLink, Disallow Writable

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#1989]
Hey there,

I have the following scenario.
Resources:
Invoice hasMany LineItems.
For simplicatiion, LineItems only have an amount.

Imagine an Invoice already exists, with 2 LineItems.

I want to allow creating a new invoice:
i want allow this, creating a new `Invoice` with `LineItems`, `POST /invoices`:
```php
{
  "name": "Invoice 2",
  "lines": [{
    "amount": 100
  }]
}
```
but disallow creating an invoice with **existing** Line Items, `POST /invoices`:
```
{
  "name": "New Foo",
  "lines": [{
    "id": "/line-items/1"
  }]
}
```
This must **not** be allowed, as reassigning a Line Item from 1 invoices to another does not make sense.

In terms of api platform nomenclature, I think this would be `Allow writableLink but Disallow writable`. I don't think this is currently possible, so what would be the best way to enforce this usecase?

Thanks,
Ben

**Comment by soyuka** [comment]
> In terms of api platform nomenclature, I think this would be Allow writableLink but Disallow writable. I don't think this is currently possible, so what would be the best way to enforce this usecase?

Didn't we already talked about that? To me you have a few solutions currently:
- implement a validation listener that does the check
- implement a denormalizer that fails with your own rule (you can add your own metadata in the `attributes` array for properties or resources)
- implement your own data persister with that behavior

**Comment by bendavies** [comment]
Thanks @soyuka ! a custom validator seems the easiest way for now!

**Comment by soyuka** [comment]
Closing this I guess the suggestion stands :D
