### ISSUE TITLE
SerializerPropertyMetadataFactory overwrites readableLink and writableLink metadata

### ISSUE THREAD

**Issue by oxan** [api-platform/core#1994]
The `SerializerPropertyMetadataFactory` overwrites the `readableLink` and `writableLink` property metadata with its own computed value. This is unfortunate, as it makes setting them to `false` using an annotation or XML/YAML configuration impossible. Manually setting these properties to `false` is useful in situations like #1001 (entity using serialization groups references itself, and wants to serialize self-reference as an IRI instead of embedded document).

Also related to #1980.

**Comment by soyuka** [comment]
:+1: let's keep discussing this in #1980 but user-defined metadata should totally override the rest.
