### ISSUE TITLE
ID not writable when creating resource

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#2018]
Hey,

It's a pretty common use case to allow an API consumer to write a PK of a resource on creation. This allows, amongst other things, asynchronous api endpoints which the consumer can then poll, as they know the ID of their resource.

This code currently prevents this:
https://github.com/api-platform/core/blob/c0de241ab907e3ddaa857962804869963821f446/src/Serializer/ItemNormalizer.php#L35-L38

Does anyone know the intention of this code?
I'm pretty sure it can be safely adapted for the above use case, but just want some feedback before hand.

Thanks

**Comment by bendavies** [comment]
No, that's not the case. Have a look at that if statement again

when posting to create a resource:
1. `$data['id']` is what is posted.
2. `$context[self::OBJECT_TO_POPULATE]` is not set
3. `$context['api_allow_update']` is false

so the exception is thrown.

**Comment by soyuka** [comment]
Definitely, if you try with a property named `foo` as PK it'll work though :laughing:

**Comment by bendavies** [comment]
found some related discussions:
https://github.com/api-platform/core/issues/1741
https://github.com/api-platform/api-platform/issues/343

**Comment by bendavies** [comment]
https://github.com/api-platform/core/pull/1939

**Comment by soyuka** [comment]
See reasoning in https://github.com/api-platform/core/pull/2022#issuecomment-399402142. You can always decorate the ItemNormalizer to implement your own logic.
