### ISSUE TITLE
Custom payload for custom operation

### ISSUE THREAD

**Issue by csarrazi** [api-platform/core#202]
Currently, when adding a custom operation, one cannot specify another class for the custom operation. Indeed, NelmioApiDoc takes the original resource as its source of documentation, which may be wrong, as we may want to use a custom value object, or no payload at all.

This is also linked to issue #186.

We should allow for operations on resources using external objects (by specifying a class for the operation).

Use cases include

* workflow management operations
* operations which require a custom payload which executes complex business logic

We definitely want these to be auto-documented.

**Comment by csarrazi** [comment]
Also, we should be able to expose resources which do not have an ID. This would be the case for value objects, which may be used for some custom operations.

**Comment by pvgnd** [comment]
>  we should be able to expose resources which do not have an ID

+1

**Comment by dunglas** [comment]
Fixed in v2.

**Comment by hikeorders** [comment]
How to use Custom payload for custom Mutation ? Could any one please give me an example ?
