### ISSUE TITLE
Enable partial option result in unexpected behavior. 

### ISSUE THREAD

**Issue by hassanjuniedi** [api-platform/core#2020]
Hey , I'm using events subscriber to update the response , when in enabled the [Pagination partial](https://api-platform.com/docs/core/pagination#partial-pagination) option, 
the controller result of GetResponseForControllerResultEvent was a `class@anonymous/home/www/PaginationExtension.php0x3f43t993r43r5.`

This is my subscriber class:
```
public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => ['updateLogo', EventPriorities::POST_WRITE],
            KernelEvents::VIEW => ['generateLogoCachedImages', EventPriorities::POST_WRITE ],
        ];
    }
public function generateLogoCachedImages(GetResponseForControllerResultEvent $event) {
        $result = $event->getControllerResult();
        $method = $event->getRequest()->getMethod();
        $class = get_class($result);
        $class= !$class;
        $resource = $event->getRequest()->attributes->get('_api_resource_class');

        if ($result instanceof Paginator) {
            $resource = $event->getRequest()->attributes->get('_api_resource_class');
            if ($resource !== Category::class) return;

            foreach ($result->getIterator() as $item) {
                if ($item instanceof Category) {
                    $this->setLogoCachedImages($item);
                }
            }
            return;
        }

        if (!$result instanceof Category || Request::METHOD_GET !== $method) {
            return;
        }
        $this->setLogoCachedImages($result);
    }
```
The $result variable holds the value of class@anonymous instead on instance of Paginator: 
![img](https://i.imgur.com/da1VffD.jpg)

when i disable the pagination partial the controller result return to be the Paginator instance.
![img](https://i.imgur.com/EXacODZ.jpg)

any idea how to keep partial option enabled and remain the controller result to be instance of Paginator ?

**Comment by soyuka** [comment]
> any idea how to keep partial option enabled and remain the controller result to be instance of Paginator ?

 Short answer I don't think you can. The partial paginator isn't an instance of Doctrine\...\Paginator.

You should be able to use https://github.com/api-platform/core/blob/d18ec0da1ac52f92ca755ca275cd0853d0972878/src/DataProvider/PaginatorInterface.php though.

**Comment by hassanjuniedi** [comment]
@soyuka thanks, but how i can use PaginatorInterface in my case ?

**Comment by soyuka** [comment]
I'm not sure of what you're trying to achieve. I just see `$result instanceof Paginator` in the screenshots, I guess you could use `$result instanceof PaginatorInterface`?

**Comment by hassanjuniedi** [comment]
I traced the execution of this method and found that if partial pagination is enabled then the return value is anonymous class that extend AbstractPaginator.

[PaginationExtension](https://github.com/api-platform/core/blob/d18ec0da1ac52f92ca755ca275cd0853d0972878/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php)
```
// src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php@getResults

if ($this->isPartialPaginationEnabled($this->requestStack->getCurrentRequest(), $resourceMetadata, $operationName)) {
         return new class($doctrineOrmPaginator) extends AbstractPaginator {
    };
}
```
now i can check if the type of controller result is instance of AbstractPaginator:

```
if ($result instanceof AbstractPaginator) {
     // do something
}
```
