### ISSUE TITLE
Throw Exception on Invalid Order Filter Query

### ISSUE THREAD

**Issue by mab05k** [api-platform/core#2030]
When using the Order Filters, the syntax is `order[field]=<asc|desc>`. 

Right now, if a user submits this query with something invalid, like `order[field]=true`, the filter is not applied and the User has no idea why his response is not ordered as expected.

Can we issue a 400 Response when a value other than `asc`, `desc`, or `''` are sent in the query?

**Comment by teohhanhui** [comment]
Probably will be fixed by https://github.com/api-platform/core/pull/1723?

**Comment by mab05k** [comment]
Looks good to me, I'll close this issue. Thanks @teohhanhui !

**Comment by jdeniau** [comment]
@teohhanhui  I did not look particularly at the order filter descriptions, but #1723 should put the background to order filter validation yes
