### ISSUE TITLE
Too many normalize iterations

### ISSUE THREAD

**Issue by SergeyMilegov** [api-platform/core#2031]
Just imagine.
I have 50 custom normalizers.
I have api action which returns me 1000 translations (key => value).
The Api Platform try to normalize every value.
So we have 50000 useless iterations. What for?
Make ability to disable normalization for scalar attributes please.

**Comment by soyuka** [comment]
Can't you create your own CollectionNormalizer that override ours? Then you apply the patch from https://github.com/api-platform/core/pull/2029 and you're good to go? :)

**Comment by SergeyMilegov** [comment]
How does it help another people?

**Comment by ymarillet** [comment]
The problem is potentially `I have api action which returns me 1000 translations (key => value).`, can't you filter at this level ?

**Comment by teohhanhui** [comment]
The 1000 translations are not attributes on the object, right? If the key-value pairs are in a PHP `array`, it should just be 1 call. Or ideally in a [Map](https://secure.php.net/manual/en/class.ds-map.php), and we should make sure that it's well supported...

**Comment by SergeyMilegov** [comment]
>If the key-value pairs are in a PHP array, it should just be 1 call.
Yes it is array with (key-value). And api platform tries to normalize every value.

**Comment by teohhanhui** [comment]
Okay, that sounds bad.
