### ISSUE TITLE
Router->getRouteCollection() to slow in debug mode.

### ISSUE THREAD

**Issue by SergeyMilegov** [api-platform/core#2032]
The ApiPlatform for every request make router->getRouteCollection(). It is to slow for dev env with enabled debug (6 sec in my case).

**Comment by soyuka** [comment]
Do you know which class is responsible? We could introduce a local cache but we will need to iterate through it at least once.

**Comment by SergeyMilegov** [comment]
ApiPlatform\Core\Bridge\Symfony\Routing\Router

**Comment by annagreenang** [comment]
I completely agree with you soyuka

**Comment by teohhanhui** [comment]
If there is a way for us to not use `getRouteCollection` at all, it'd be great. If that's not possible, we should add a cache warmer to avoid calling `getRouteCollection` repeatedly.

**Comment by teohhanhui** [comment]
So, the problem is that we don't have a mapping from resource class and operation type back to its route name. I believe this mapping can fully be generated at container compilation time, and this mapping would then be injected into the above `RouteNameResolver` class.

**Comment by teohhanhui** [comment]
> May be better to build route name using RouteNameGenerator and then check its existence.

There is a fundamental problem with that: we do not control the route names. They could be entirely customized. Only the auto-generated route names are predictable.

**Comment by Siregacvek** [comment]
@teohhanhui 
> So, the problem is that we don't have a mapping from resource class and operation type back to its route name

Exactly.

> I believe this mapping can fully be generated at container compilation time, and this mapping would then be injected into the above RouteNameResolver class.

Yes, this would be a best solution I think.

**Comment by Siregacvek** [comment]
> There is a fundamental problem with that: we do not control the route names. They could be entirely customized. Only the auto-generated route names are predictable.

May be I'm wrong, but above code works only with auto-generated routes, because it's relying on some default predefined values:
`             $currentResourceClass = $route->getDefault('_api_resource_class'); `
`             $operation = $route->getDefault(sprintf('_api_%s_operation_name', $operationType)); `

**Comment by teohhanhui** [comment]
> but the code above works only with auto-generated routes, because it's relying on some default predefined values

No, those are the route defaults you'd need to set. What we're looking for here are the standard collection or item routes, not custom operations.
