### ISSUE TITLE
The Deserialization does not detect a phpdoc typed resource properly in prod.

### ISSUE THREAD

**Issue by GregoireHebert** [api-platform/core#2034]
When using a `DTO`, such as:

```php
/**
 * @ApiResource(
 *     collectionOperations={
 *         "post": {
 *             "path": "/my/route",
 *         },
 *     },
 *     itemOperations={},
 * )
 */
final class Foo
{
    /**
     * @var Dummy a resource.
     */
    public $dummy;
    public $customInt;
    public $customArray;
}
```

And sending a post with some custom data and a $dummy field filled with an IRI

```json
{
   "customInt":555,
   "customArray":[],
   "dummy":"/api/dummies/1"
}
```

Once the content is deserialized here:
here: https://github.com/api-platform/core/blob/master/src/EventListener/DeserializeListener.php#L94

In dev, the dummy field is now a `Dummy` instance.
In prod, the dummy field is a `string` with the IRI.

This inconsistency comes from the presence of two dependencies in dev:
```json
"phpdocumentor/reflection-docblock": "^3.0 || ^4.0",
"phpdocumentor/type-resolver": "^0.2.1 || ^0.3 || 0.4",
```

Two workarounds: 
Adding a Setter with the `Dummy` TypeHint in my project.
works but does not fix every problems especially when dealings with collections of resources.
or
adding theses two dependencies in prod.

WDYT ?

**Comment by teohhanhui** [comment]
You're supposed to add these dependencies yourself if you want to use https://github.com/api-platform/core/blob/v2.2.8/src/Metadata/Resource/Factory/PhpDocResourceMetadataFactory.php and https://github.com/symfony/symfony/blob/v4.1.0/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php

**Comment by teohhanhui** [comment]
In fact, it's already listed in "suggests": https://github.com/api-platform/core/blob/v2.2.8/composer.json#L75

**Comment by GregoireHebert** [comment]
ok, silly me, I forgot to check my own dev dependencies dependencies. thanks @teohhanhui.
