### ISSUE TITLE
Cannot pass an IRI in JSON for a constructor parameter

### ISSUE THREAD

**Issue by guillaume-perreal** [api-platform/core#2036]
When an object constructor accepts an object that is actually a relation, api-platform/core 2.2.6 fails to denormalize it from an IRI.

e.g. Given this following class, where any Item must be associated to a Project:
```php
/**
 * @ORM\Entity
 * @API\ApiResource
 */
class Item {
  /**
   * @var UuidInterface
   * @ORM\Id
   * @ORM\Column(type="uuid")
   * @Assert\Uuid(strict=true)
   */
  private $id;

  /**
   * @var Project
   * @ORM\ManyToOne(targetEntity=Project::class)
   * @ORM\JoinColumn(nullable=false)
   */
  private $project;

  /* ... More fields ... */

  public constructor(Project $project) {
    $this->id = Uuid::uuid4();
    $this->project = $project;
  }

  /* ... Getters and unicorns ... */
}
```

The serializer has no issue serializing it. However, it fails to deserialize from the following JSON:

```json
{  "project": "/projects/e00fc841-b090-47da-b67b-9d5b3a73e7ba" }
```

If I understood the code correctly, the normalizer fails to identify the "project" parameter of the constructor as the "project" association. It waits for a full project and does not even try to fetch an existing project from the database. With a full project, it complains about not being allowed to update (?!).

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/pull/1749

It should be in `2.3`
