### ISSUE TITLE
Regression: Unable to have resource without an ID since v2.2.6

### ISSUE THREAD

**Issue by jeffreymb** [api-platform/core#2038]
In version 2.2.5, I had a resource that didn't have an id. There were several other required parameters, that could be considered a composite primary key. I am loading the actual data with a Item Data Provider.

This was working great for me until I recently upgraded to 2.2.8. By manually going back one version at a time and then stepping through the code with xDebug, I was able to figure out what was going on. The changes in the `ApiPlatform\Core\EventListener\ReadListener` which happened it 6d40a8c27d3779809dae69bd09d1380f5948edf3 are where the functionality changed.

Was this a purposeful design change or a regression? Is there a suggested workaround?

**Comment by soyuka** [comment]
I'm not sure how this change makes your code break if you have your own data provider ?

**Comment by jeffreymb** [comment]
Before this commit, line 87 would get the value from the Data Provider. After this commit, the new line 86 (`extractIdentifiers`) throws an exception with the `'id'` parameter is not in the url.

**Comment by jeffreymb** [comment]
Right on. Sorry for not being clearer originally. 😬

**Comment by soyuka** [comment]
To me we fixed a bug, `id` should never be `null` in the item data provider... Anyway, because of the BC promise I'm going to put back the old behavior asap! Thanks for the report!

**Comment by dunglas** [comment]
Was it allowed by the PHPDoc?

**Comment by soyuka** [comment]
```
     * @param array|int|string $id
```

Not from first sight no.

**Comment by teohhanhui** [comment]
We should not revert the bug fix.

**Comment by soyuka** [comment]
@jeffreymb I'm sorry but you've hit a `wontfix`... Would it be possible for you to explain your use case where you have:
- an ItemDataProvider
- no `id` in your url (no `{id}` param)

I'll try to help you to find another solution to the problem! Thanks, I hope that you understand why we can't revert the bug fix :p.

**Comment by jeffreymb** [comment]
I can understand about the `wontfix`. My situation is an api endpoint to access data from a hierarchy like Volume -> Chapter -> Paragraph. Volume and chapter are required parameters to pass to the endpoint. There are a few other optional parameters also, but no obvious primary key other than the composite of all three (volume/chapter/paragraph) options. I suppose I could fudge it and pick one of volume/chapter and call it the id, but surely there is a better solution.

**Comment by soyuka** [comment]
On what class is your `ApiResource` for the latter?

My first guess would be a custom Controller (ie: don't go through the ReadListener, set `_api_receive` to `false` in the operation attributes, handle the data thing yourself).

**Comment by jeffreymb** [comment]
I have a single `Reference` class that has the `ApiResource`.

The idea of a custom controller had crossed my mind, I'll check into that further.
