### ISSUE TITLE
GraphQl Schema generates wrong Type for Relations

### ISSUE THREAD

**Issue by andreaspenz** [api-platform/core#2058]
Hello,

i have got a customer entity with a one-to-many-relation to an email-entity. Through the rest-api i am able to create the a new customer and the emails with a single request. Swagger already displays the correct arguments:

![screenshot from 2018-06-29 11-46-18](https://user-images.githubusercontent.com/1625605/42086189-a7101cf2-7b92-11e8-8949-9fa270001d0c.jpg)

But when i go to Graphiql it tells me that it expects an array of strings as an argument for the emails:

![screenshot from 2018-06-29 11-51-11](https://user-images.githubusercontent.com/1625605/42086363-1e883878-7b93-11e8-9074-8a634ddfafb8.png)

The source of the problem is in the SchemaBuilder when the types are converted (https://github.com/api-platform/core/blob/master/src/GraphQl/Type/SchemaBuilder.php#L354). Because the input is true (createCustomerInput mutation) and the depth is 7 it always returns a GraphQl-StringType. I dont think that this is the right behaviour because the 7 isn´t the depth, its just the 7nth field. 

When i do not increse the depth (https://github.com/api-platform/core/blob/master/src/GraphQl/Type/SchemaBuilder.php#L377) and just pass it to the function as it is the following mutation works and saves the customer including the emails. 

Request:
```graphql
mutation {
  createCustomer(
    input: {
      clientMutationId: "12", 
      firstName: "asdf", 
      lastName: "asdf", 
      emails: [
        {
          clientMutationId:"1", 
          email: "a@a.at", 
          primary: false
        }
      ]
    }
  ) {
    id
    emails {
      edges {
        node {
          id
          email
        }
      }
    }
  }
}
```
Result:

```graphql
{
  "data": {
    "createCustomer": {
      "id": "/customers/5fe8afae-bc4a-4ba7-8418-01c4d1a00c78",
      "emails": {
        "edges": null
      }
    }
  }
}
```

But as you can see the Result does not contain the emails. If i send another request and try to get the customer directly the emails are present again.

Request:
```graphql
{
  customer(id: "/customers/dcbfc05c-a72a-47d8-9111-fc5869831650") {
    firstName
    emails {
      edges {
        node {
          email
        }
      }
    }
  }
}
```

Response
```graphql
{
  "data": {
    "customer": {
      "firstName": "asdf",
      "emails": {
        "edges": [
          {
            "node": {
              "email": "a@a.at"
            }
          }
        ]
      }
    }
  }
}
```

Am i missing some config or is this a bug?

**Comment by alanpoulain** [comment]
This behavior is wanted. See #1964.
But `depth` should not be 7 and we should probably investigate this.

**Comment by leyriel** [comment]
Hello, do you have a news for this ? :)

**Comment by alanpoulain** [comment]
The `depth` issue has been fixed. See https://github.com/api-platform/core/pull/2612#issuecomment-475242513.
