### ISSUE TITLE
Deprecation notices with SensioFrameworkExtraBundle 5.2

### ISSUE THREAD

**Issue by nielsvandermolen** [api-platform/core#2062]
Changelog:
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md

> Also replace the annotations Sensio\Bundle\FrameworkExtraBundle\Configuration\Route and Sensio\Bundle\FrameworkExtraBundle\Configuration\Method with Symfony\Component\Routing\Annotation\Route

Seems it needs to be changed in:
- ` core/tests/Fixtures/TestBundle/Controller/CustomActionController.php`
- `core/tests/Fixtures/TestBundle/Controller/DummyValidationController.php`

to avoid deprecation notices during testing

**Comment by sroze** [comment]
Good catch. Do you want to send a PR for it? :)

**Comment by nielsvandermolen** [comment]
I rather not at the moment. I am not sure if it is just changing the class name or that it could be more complex and that it might break something (e.g. the tests).

**Comment by soyuka** [comment]
Our version constraint is `^4.0` so we shouldn't reach `5.0` in the core, especially that these are only present in our tests. As it's not used anywhere else there really is no rush here.

**Comment by teohhanhui** [comment]
I think we should test with 5.x, as that's the latest stable.

**Comment by jenaye** [comment]
Done in #2108 @nielsvandermolen Thanks for reporting
