### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by Nesslax** [api-platform/core#2079]
Generation of an Entity that log all actions executed in API 
Verb --- Entity --- User   --- Parameters 
Post ---  Book --- Admin --- Name="test"
Get   --- Book --- Admin  --- Null

**Comment by er1z** [comment]
Why not use Doctrine Audit?

**Comment by Nightbr** [comment]
Hey,
I don't think this feature should be in the core. But it could be a great feature as a separate bundle!

**Comment by dunglas** [comment]
From my experience, such audit logs are better handled at the RDMS level wit extensions such as https://www.pgaudit.org/.
At the Doctrine level, https://github.com/simplethings/EntityAuditBundle is very useful.
It can also easily be done at the Nginx level with a custom log format.

A bundle to do it can be interesting, but anyway it's out of scope for core. Closing.
