### ISSUE TITLE
Help - how to how to specify a many to many relation as listOf instead of Iterable

### ISSUE THREAD

**Issue by lexandre75** [api-platform/core#2091]
Hello,

I have a custom data provider using mongo (https://packagist.org/packages/sol/api-platform-mongo-bridge work in progress).

I have defined two documents, category and product. A category has many products a product have one category.

In my document, I have a "ReferenceMany" (near a "manyToMany" relation for Mongo). In GraphQL the products attribute for the category connection appears as an iterable instead of a productConnection.

How could I specify the connection ?

**Comment by alanpoulain** [comment]
Closing because too old. Feel free to reopen if it doesn't work with the latest version.
