### ISSUE TITLE
Generate Hydra member's @id programmatically?

### ISSUE THREAD

**Issue by djoos** [api-platform/core#2092]
Hi there,

what would be the cleanest way to generate a resource's "@id" value programmatically?
FYI: We would like to be able to return an "@id" for an entity in a custom action...

Thanks in advance!

**Comment by er1z** [comment]
First thing I came across is to create custom DataProvider, then mark field as identity.

**Comment by djoos** [comment]
Hi @er1z,

thanks! It's annotated as @ORM\Id (we're using Doctrine).

It feels like there must be a more elegant way to only generate the @id than having to retrieve the whole item via a data provider?

**Comment by soyuka** [comment]
```
@ApiProperty(identifier=true)
```

Might help you.

**Comment by djoos** [comment]
Hi @soyuka,

thanks - that helps making sure the ID gets generated when returning a normal response of the entity. However, I'm specifically after how I can, eg. in a custom controller (building the specific JSON response myself), generate the value normally returned in @id programmatically.

ie. `$id = IDGenerator::generateIDForEntity($entity); //would return /entity/123`

Currently I have the following, but there must be a better way to generate @id values having an entity object that is an @ApiResource:
```
$reflect = new ReflectionClass($entity);

$id = sprintf(
    '/%ss/%s',
    strtolower($reflect->getShortName()),
    $entity->getId()
);
```

Thanks!

**Comment by soyuka** [comment]
You are using doctrine on this entity if I read correctly, please take a look at https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#identifier-generation-strategies you can use your own Custom generator or whatever.

If you want to do this without doctrine (ie on a DTO) you'll need `@ApiProperty(identifier=true)` to flag the property as identifier. The generation would be done in a data persister or the custom controller depending on what is being used.

**Comment by djoos** [comment]
Hi guys,

all of a sudden the penny dropped: I reread my first post and saw "generation" there - I didn't mean the generation of the actual value of the id (ie. auto-increment, guid, etc.), but generation as in "a way to get from API platform the @id value for a given existing entity". In other words: I've got an existing entity in the database with an id (let's say "123"), but how am I able to get the entity's @id / IRI ('/entity/123')?

I currently do this via...
```
$reflect = new ReflectionClass($entity);

$id = sprintf(
    '/%ss/%s',
    strtolower($reflect->getShortName()),
    $entity->getId()
);
```
...but surely there must be a helper or something available to be able to get that @id value easier given an existing entity.

Thanks in advance!
David

**Comment by teohhanhui** [comment]
@djoos Check the IriConverter :)

**Comment by djoos** [comment]
@teohhanhui - perfect, thanks!

The solution is as simple as injecting the "api_platform.iri_converter" service and then use the IriConverter's getIriFromItem method, ie. `$iriConverter->getIriFromItem($entity)`, which returns the expected '/entity/123'.

Thanks for your help!
