### ISSUE TITLE
Undefined index: subresource_context

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2094]
I POST to a sub entity, document -> articles then i get the fallowing error:

File: vendor/api-platform/core/src/DataProvider/OperationDataProviderTrait.php
Line: 104
Undefined index: subresource_context

```
$attributes =
resource_class = "Entity\DocumentArticle"
collection_operation_name = "get"
receive = true
```

**Comment by soyuka** [comment]
It's weird you should not take this path within a collection operation.

In the ReadListener we return early on a collection operation here:
https://github.com/api-platform/core/blob/master/src/EventListener/ReadListener.php#L80

**Comment by do-web** [comment]
I have found the Problem. This error accours if i post a new sub entity with an empty id like this:

POST /documents

```

{
 id: "1",
 articles: [
  {
   id: "",
   title: "test",
  amount: 1,
    price: "2.99"
   }
 ]
}
```

**Comment by soyuka** [comment]
Would you mind giving me the entities? If the article there is a new one can you try without any `id`?

**Comment by do-web** [comment]
Without an id it is working.
