### ISSUE TITLE
[BUG] Entity decimal property not returning a string

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2100]
I have the following field:

```
    /**
     * @ORM\Column(name="price", type="decimal", nullable=false, precision=12, scale=4)
     * @var float
     */
    public $price;
```

If price is **0** the serializer returns an **INT** not a **STRING** as expected. 
**If the type is decimal is should always returns a string.**

So if i try to PATCH back the "wrong" response with the int 0 i get the error: 
"The type of the "price" attribute must be "string", "integer" given."

**Comment by teohhanhui** [comment]
Shouldn't it be `@var string` instead of `@var float`?
