### ISSUE TITLE
[BUG] Plain Ids not working with JSON

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2101]
I have enabled allow_plain_identifiers and set the header "Accept: application/json"

The PATCH ist working fine with this:

```
{
"id": 1,
"articles": [
  "article": "20"
]
}
```

But then the response is in IRI format
```
{
"id": 1,
"articles": [
  "article": "/articles/20"
]
}
```

Expected result should be:

```
{
"id": 1,
"articles": [
  "article": "20"
]
}
```

**Comment by dunglas** [comment]
Looks like a bug too. For information, I would like to change how we handle plain identifiers and deprecate the current way: https://github.com/api-platform/core/pull/2022#issuecomment-398851861

**Comment by numediaweb** [comment]
are there any plans on when this will be fixed?

**Comment by do-web** [comment]
Iam using the current version and the bug still exists.
