### ISSUE TITLE
[BUG] Updating a property with orphanRemoval removes all entities

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2102]
```
    /**
     * @ORM\OneToMany(targetEntity="App\Article", mappedBy="document", cascade={"all"}, orphanRemoval=true, fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"sorting" = "ASC"})
     * @Groups({"document"})
     */
    public $articles;
```

**PATCH**
```
{
"id": 1,
    "articles": [
       {
         "id": "10",
         "name": "test"
       },
       {
         "id": "11",
         "name": "test2"
       },
       {
         "name": "test3"
       }
    ]
}
```

Result is:

```
{
"id": 1,
    "articles": [
       {
         "id": "12",
         "name": "test3"
       }
    ]
}
```

Expected result should be:

```
{
"id": 1,
    "articles": [
       {
         "id": "10",
         "name": "test"
       },
       {
         "id": "11",
         "name": "test2"
       },
       {
         "id": "12",
         "name": "test3"
       }
    ]
}
```

If i PATCH / PUT a sub entity the entities are not updated, they are removed.
My current workaround is to delete the id before i PATCH the document.

**Comment by dunglas** [comment]
What do you mean by `PATCH`? We don't support patch out of the box (except for the JSONAPI, as defined in the spec, and it has a special behavior).

**Comment by do-web** [comment]
I'am using PATCH with plain application/json. But this bug also appears with PUT.

**Comment by dunglas** [comment]
Can you try if it also occurs when using JSON-LD instead of raw jSON?

**Comment by iwan-wijaya** [comment]
@dunglas This also occurs when using JSON-LD, I just tried it.

**Comment by michael-obat** [comment]
Hello.

We dealings with the same issue.
Is there a correction planned ?

Thanks.

**Comment by WilliamPeralta** [comment]
+1
