### ISSUE TITLE
OrderFilter on nested entity seems KO

### ISSUE THREAD

**Issue by BatsaxIV** [api-platform/core#2109]
Hi guys,

An entity _User_ has a relation with another entity _Conversation_.
If I use the **OrderBy** filter on _conversation.createdAt_ the User without a _Conversation_ will be excluded from the results.

```php 
@ApiFilter(OrderFilter::class, properties={"conversation.createdAt": "ASC" }})
```
Searching through github I've found : 

- [This first issue](https://github.com/api-platform/core/issues/363) with [the associated fix](https://github.com/api-platform/core/pull/367/files)

- The ability to use null comparison with [this PR](https://github.com/api-platform/core/pull/838) 

So I transform my filter to : 
```php 
@ApiFilter(OrderFilter::class, properties={"conversation.createdAt": { "nulls_comparison": OrderFilter::NULLS_SMALLEST, "default_direction": "ASC" }})
```

Full of trust :+1: , I press Send button on postman and... still excluded :disappointed: 

Digging a bit I see that the [OrderFilter](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/OrderFilter.php#L149) call a specific method for join relation : 
```php 
list($alias, $field) = $this->addJoinsForNestedProperty($property, $alias, $queryBuilder, $queryNameGenerator, $resourceClass);
```

Then on the [AbstractFilter](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php#L325) : 
```php 
$alias = QueryBuilderHelper::addJoinOnce($queryBuilder, $queryNameGenerator, $parentAlias, $association);
```

And finally in the [QueryBuilderHelper](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Util/QueryBuilderHelper.php#L44) : 
```php 
if (Join::LEFT_JOIN === $joinType || QueryChecker::hasLeftJoin($queryBuilder)) {
    $queryBuilder->leftJoin($query, $associationAlias, $conditionType, $condition);
} else {
    $queryBuilder->innerJoin($query, $associationAlias, $conditionType, $condition);
}
```
There is no **$joinType** send and the **QueryCheck::hasLeftJoin** returns false, so an _innerJoin_ is made instead of a _leftJoin_.  
If I forced a _leftJoin_, the results are ok.

Am I missing something or is there a problem?

Thanks,
Jérémy.

**Comment by teohhanhui** [comment]
`nulls_comparison` is for ordering `NULL` values. It does not affect joins.

That said, we might be able to do something similar for a non-existent relation...

**Comment by teohhanhui** [comment]
But anyway, yes, I think this should be considered a bug.

**Comment by teohhanhui** [comment]
Summoning @soyuka :crystal_ball:

**Comment by soyuka** [comment]
@BatsaxIV could you send me both entities? Thanks!

**Comment by BatsaxIV** [comment]
Hi @soyuka,

Here are the entities :

[2109.tar.gz](https://github.com/api-platform/core/files/2261569/2109.tar.gz)

**Comment by BatsaxIV** [comment]
Thanks @soyuka !
