### ISSUE TITLE
Custom operation - custom request body in swagger

### ISSUE THREAD

**Issue by wesol05** [api-platform/core#2110]
As I know there is no way to add subresoure post for now, so I need to add custom operation and emulate it. I found such example in one of the previous topics: https://github.com/gries/api-platform/pull/1/files#diff-03658d5f5162523638fa095aac8fb995

My question is - how to set up object instead of scalar value in request body? Object should be generated from another resource.

Thanks in advance

**Comment by soyuka** [comment]
> My question is - how to set up object instead of scalar value in request body? Object should be generated from another resource.

Not sure I got that but I guess you could override the `_api_resource_class` to trick api platform in thinking that you'll post this class and not the origin one.

**Comment by vesol** [comment]
unfortunately it doesn't work. I have tried it already

**Comment by soyuka** [comment]
use openapifactory
