### ISSUE TITLE
How to limit access to model property based on is_granted

### ISSUE THREAD

**Issue by Soullivaneuh** [api-platform/core#2118]
On your [documentation](https://api-platform.com/docs/core/security), I found we can limit method access based on `is_granted` calls.

But how to limit property access from both doc and API? For example with this entity:

```php
namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Table
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ValidTldRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("nameCanonical")
 * @ApiResource
 */
class ValidTld
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64)
     * @ORM\Id
     * @Assert\NotBlank
     */
    private $name = '';

    /**
     * Domain name, Puny coded.
     *
     * @see http://php.net/manual/en/function.idn-to-ascii.php
     *
     * @var string
     *
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\Length(max="255")
     */
    private $nameCanonical;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $favorite = false;

    // getters/setters
}
```

I would like `favorite` to to be shown only with `ROLE_ADMIN` (or more complex voter calls).

To compare, we was able to do that on FOSRest thanks to the `groups` option.

Is that maybe a not existent feature?

Thanks

**Comment by dunglas** [comment]
See https://github.com/api-platform/api-platform/issues/773#issuecomment-406598278

**Comment by Soullivaneuh** [comment]
Thank you @dunglas. I'll try, but it looks to feet my needs. :+1: 

I looked at the doc first but I didn't found that. Maybe a special link on the security section for that might help a bit? :-)

**Comment by Soullivaneuh** [comment]
Just another question: Will this method have any influence on the swagger/doc generation?

**Comment by teohhanhui** [comment]
What do you want to happen in the docs? Different fields in the docs based on authorization role?

I don't think that's a good idea or necessary.

**Comment by soyuka** [comment]
Closing as duplicate from https://github.com/api-platform/api-platform/issues/773#issuecomment-406598278

**Comment by Soullivaneuh** [comment]
> I don't think that's a good idea or necessary (security by obscurity).

The API is used by both admin and customer. Is not about obscurity, but we won't pollute the user documentation with ton of fields they don't need.
