### ISSUE TITLE
Let's talk about performances

### ISSUE THREAD

**Issue by dupuchba** [api-platform/core#212]
Hi everyone,

I was playing with the bundle and I did a backfire.io profiling which was very interesting. 
I just did a GET /poeple/3 API call with php 5.5.18 (no cache).

Note that Nelmio doc generation takes almost 30% of CPU time but I wasn't asking for it (we load it everytime).

I was curious **to see your point of view about that**.

Thank's everyone.

link here => https://blackfire.io/profiles/74457ce7-817a-4266-ad11-87c498d18762/graph

**Comment by dunglas** [comment]
He heavy operation is the PHPDoc parsing but this not especially related to NelmioApiDoc. It occurs for populating metadata :

- property type guessing (using the property info library)
- textual description for the Hydra documentation (so used by NelmioApiDoc of installed)

This an expensive operation but in production you should use the cache (see the performance chapter in the doc).

**Comment by dupuchba** [comment]
@dunglas I know (and I warned ^^) that caching metadata is a must have but I am still curious about nelmio optimization. 

- Do we really need it on each request ?

**Comment by dunglas** [comment]
Have you enabled the Nelmio cache? Can you make another profile to show the difference when Nelmio is not installed?

**Comment by dupuchba** [comment]
@dunglas I'll do it next week, like you I really need holidays ^_^

**Comment by rolebi** [comment]
related to #198

**Comment by rolebi** [comment]
related to #198 ?

**Comment by theofidry** [comment]
@rolebi not really, #198 is really more on guidelines and doc. This case is an optimization of the bundle.

**Comment by Simperfit** [comment]
What is the state of this issue ?

**Comment by theofidry** [comment]
@Simperfit we need a good benchmark showing we can handle 2000 req/s just fine :P

**Comment by teohhanhui** [comment]
Usually, serialization takes up the bulk of the time. If we have generated normalizers (symfony/symfony#17516), that'll be a huge win. Or perhaps it may be possible to introduce some cache layer to prevent re-generating the serialized string each time?

**Comment by theofidry** [comment]
@teohhanhui make custom serializers and a property accessor for the benchmark :P

**Comment by soyuka** [comment]
> Usually, serialization takes up the bulk of the time.

+1, for example (development mode): 

![screenshot-localhost-2016-11-09-14-25-43](https://cloud.githubusercontent.com/assets/1321971/20139854/74e0c532-a688-11e6-85a7-f89f72c94861.png)

**Comment by soyuka** [comment]
Theoretically, if we know we have the same pattern per resourceClass, we should be able to cache some undergoing in the serializer no?
Also, if we have a collection, we know that it's items are deserializing the same way, might be room for improvement on this side.

**Comment by dunglas** [comment]
Yes, but we can do this directly in the Symfony component (a resource class is just a class after all). It will benefit for all usages of the Serializer.

**Comment by dunglas** [comment]
Btw, profiles in dev mode are biased because caches of the Serializer component are not enabled.

**Comment by soyuka** [comment]
More data 
> simple query, no relations, ~8k items, apcu cache enabled

https://blackfire.io/profiles/325404d0-c782-4f05-88ed-4676b6c3368b/graph

![serializer3](https://cloud.githubusercontent.com/assets/1321971/24004191/f030f9aa-0a65-11e7-815c-26b692724071.png)

**Comment by soyuka** [comment]
We need to cache `getIriFromItem` because it calls `getIdentifiersFromItem` which is heavy in metadata parsing.

**Comment by Simperfit** [comment]
Since the PR has been merged I think this can be closed we improved alot the performance, if you have any idea on how to improve it more, PR are welcome ! :)
