### ISSUE TITLE
[Feature?] Add decoded body to request attributes

### ISSUE THREAD

**Issue by Taluu** [api-platform/core#2130]
In some of my actions (and some of my services), I may have a need to access the request's content, especially to make a `json_decode` call (or a serializer::decode).

I think it would be better so that the deserializer listener could add a step so that it stores the decoded request in its attributes, rather than having just the deserialized data (in case of some additionnal fields, .. and so on).

WDYT ?

**Comment by ragboyjr** [comment]
I wonder if this is related to #2168

**Comment by Taluu** [comment]
Not really IMO. It could be used for that though. The idea is to have an array containing the decoded request in the request's attributes :

```
{
   "foo": "bar"
}
```

```
dump($request->attributes->get('_body'));
```

would output

```
[
    "foo" => "bar"
]
```

**Comment by ragboyjr** [comment]
@Taluu wouldn't this be easy to add your own event listener to json decode the body? It seems like this could exist outside of API Platform fairly easily.

**Comment by borNfreee** [comment]
> @Taluu wouldn't this be easy to add your own event listener to json decode the body? It seems like this could exist outside of API Platform fairly easily.

my 2 cents: It would, but if it can be out of the box, it is much better for DX.

**Comment by dunglas** [comment]
Doing this will increase the memory usage. So why not, but it should be optin.
Honestly, this use case looks a bit advanced to me, a doc entry would probably be enough.

**Comment by borNfreee** [comment]
> Doing this will increase the memory usage.

I doubt it will be much more than a couple of kB. 

In my project, we had situations where we manually stored decoded body in one listener (`POST_VALIDATE`) to use it later in another listener (`POST_WRITE`) just to not duplicate decoding logic.

I'm not saying we did it right, lol, but this is an example that it can be useful.

Personally, I would vote for adding this to the core since memory usage is not a problem IMO, but I would love to see at least a doc entry for this 👍

**Comment by dunglas** [comment]
> I doubt it will be much more than a couple of kB.

It directly depends of the payload’s size. Large payload will lead to large memory increase. But why not as long as it’s an optin feature.

**Comment by Taluu** [comment]
The memory argument is not a real one IMO. We could in the decoding listener (or before ?) store the decoded body in the attributes, and then use the serializer to work from that instead of the request's body.

Unless you're thinking about the fact of storing a decoded payload that could be indeed huge ?

**Comment by soyuka** [comment]
I agree with @dunglas it's useful for advanced uses only. Also this is easy enough to be implemented by the developers if they need it right?
