### ISSUE TITLE
GraphQL: can't filter nested objects

### ISSUE THREAD

**Issue by Siregacvek** [api-platform/core#2149]
Hello.

I try to filter nested entities. Example:
I have the following schema: `Entity 1<-* SubEntity 1<-* SubSubEntity`. Each entity has string property `Name`.

When I add the following filter to `Entity`:
```
/**
 * @ApiResource()
 ...
 */
class Entity
{
    /**
     * @ApiFilter(SearchFilter::class, properties={"name": "ipartial"})
     */
    private $subEntities;
}

```
this query works fine:
```
{
  entities {
    subEntities (name: "Name") {
    ...
    }
  }
}

```
I get all the `entities` with filtered `subEntities`.

But when I add new filter:
```
...
    /**
     * @ApiFilter(SearchFilter::class, properties={"name": "ipartial"})
     * @ApiFilter(SearchFilter::class, properties={"subSubEntities": "exact"})
     */
    private $subEntities;
```
or
```
...
    /**
     * @ApiFilter(SearchFilter::class, properties={"name": "ipartial"})
     * @ApiFilter(SearchFilter::class, properties={"subSubEntities.name": "ipartial"})
     */
    private $subEntities;
```

The Schema builder even doesn't see this second filter. I suspect that the reason is that the new filter is not of scalar type, but an object. 

Am I doing something wrong or it's a bug?

**Comment by Siregacvek** [comment]
@alanpoulain I explored the code and what I found.
My first filter `* @ApiFilter(SearchFilter::class, properties={"name": "ipartial"})` works only because `Entity` and `SubEntity` have the same field `Name`.
I believe the issue is here:
https://github.com/api-platform/core/blob/797cea682956871c0a848275bbaeabf1339ad615/src/GraphQl/Type/SchemaBuilder.php#L229

Your code trying to find the search property in a root class `Entity`, but my filter is given over a property `SubEntity`, and I think it must search in `SubEntity`'s properties. That's why schema builder doesn't work with the second filter `* @ApiFilter(SearchFilter::class, properties={"subSubEntities.name": "ipartial"})` - root class `Entity` doesn't have `subSubEntity` property and this filter just ignoring.

**Comment by Siregacvek** [comment]
@alanpoulain regarding behat test - sorry I don't know how to launch test from your environment, but I believe that if here 
https://github.com/api-platform/core/blob/797cea682956871c0a848275bbaeabf1339ad615/features/graphql/filters.feature#L87-L108

you will filter by a unique relatedDummy's field like this:
```
...
relatedDummies(fieldPresentedOnlyInRelatedDummy: "value") {
...
```
you will be able to reproduce the issue.

**Comment by Siregacvek** [comment]
[failed-test.diff.txt](https://github.com/api-platform/core/files/2271758/failed-test.diff.txt)
@alanpoulain here you can find a patch with new behat test. I hope this will be helpful

**Comment by Siregacvek** [comment]
[success-test.patch.txt](https://github.com/api-platform/core/files/2271783/success-test.patch.txt)
It's a next patch where I copied the field from `RelatedDummy` to `Dummy` entity. When you apply it, the test above will become successful.

**Comment by alanpoulain** [comment]
I'll have a look in a few days.

**Comment by alanpoulain** [comment]
I don't understand your diff. If you want to filter the `relatedDummies` by their `uqname`, you have to do it like this:
```graphql
    {
      dummies(relatedDummies_uqname: "UQRelatedDummy13") {
        edges {
          node {
            id
            relatedDummies {
              edges {
                node {
                  id
                  name
                }
              }
            }
          }
        }
      }
    }
```
It's explained here: https://api-platform.com/docs/core/graphql#filtering-on-nested-properties
Sure it's not very intuitive but it works. But maybe I've not understood your issue?

**Comment by Siregacvek** [comment]
@alanpoulain I think you query must return only `Dummies` which have `RelatedDummy` with `uqname` = `UQRelatedDummy13` . At least this is how I understand documentation:

> The above allows you to find offers by their respective product's color like for the REST Api. You can then filter using the following syntax:
> ```
> {
>   offers(product_color: "red") {
>     edges {
>       node {
>         id
>         product {
>           name
>           color
>         }
>       }
>     }
>   }
> }
> ```

I want the other behavior - I want to get **all** `Dummies`, each Dummy has to contain `RelatedDummies` list filtered by condition.

**Comment by Siregacvek** [comment]
@alanpoulain even in your test
```
  Scenario: Retrieve a collection filtered using the related search filter
    Given there are 1 dummy objects having each 2 relatedDummies
    And there are 1 dummy objects having each 3 relatedDummies
    When I send the following GraphQL request:
    """
    {
      dummies(relatedDummies_name: "RelatedDummy31") {
        edges {
          node {
            id
          }
        }
      }
    }
    """
    And the response status code should be 200
    And the JSON node "data.dummies.edges" should have 1 element
```
originally you have two Dummy objects, but your request should retrieve only one Dummy.

But per my expectations the following request:
```
    {
      dummies {
        edges {
          node {
            id
            relatedDummies(uqname: "UQRelatedDummy13") {
              edges {
                node {
                  id
                  name
                }
              }
            }
          }
        }
      }
    }
```
should retrieve all Dummies with filtered related dummies. Something like this:
```
{
  "data": {
    "Dummies": [ 
       {
       "id": "firstDummy"
       "relatedDummies": [] 
       },
       {
       "id": "secondDummy"
       "relatedDummies": [
            {
            "id": "relatedDummy13"
            "uqname": "UQRelatedDummy13"
            }
       }
       ]
```

**Comment by Siregacvek** [comment]
@alanpoulain , please, can you respond on above.

**Comment by alanpoulain** [comment]
@Siregacvek I've done the fix in a PR.
With this, if a search filter has been configured in the nested entity, you can use it to filter the nested collection.
You can test it if you want to make sure it solves your issue.

**Comment by Siregacvek** [comment]
@alanpoulain great thanks. I'll look at it asap.

**Comment by jamesisaac** [comment]
Hi @alanpoulain 

Could you please give an example of what a simple configuration for nested entity filtering using `@ApiFilter` should look like?  I've dug through the codebase in your PR #2177, but I really can't see how you've managed to indicate that `relatedDummies` should be filterable on `name`.

I've tried a few things and none of them work:

**1. Add `@ApiFilter` to my nested entity class**

Works at the root level of a GraphQL query, but not when that entity appears as a nested OneToMany (doesn't appear in the GraphQL schema).

**2. Add `@ApiFilter` to the parent class's nested property with `"properties"={"name"}`**

Doesn't appear in the GraphQL schema.

**3. Add `@ApiFilter` to the parent class's nested property with `"properties"={"nestedEntity.name"}`**

Finally appears in the GraphQL schema, however introduces multiple problems: (a) it's appearing on *every* OneToMany collection of the parent entity, not just the one it was annotation on, (b) it's named `nestedEntity_name`, not just `name` like in your Behat test, (c) it doesn't actually work to filter anything when used at the nested level, only at the root level.


I've set up a minimal repro of these attempts here: https://github.com/jamesisaac/api-platform-nested-filter/commit/95c3b91a744eb30f8eb7bbc4f96e60d2a6e973b2

**Comment by jamesisaac** [comment]
Apologies... I was just using a version of API Platform which didn't include the fix :/.  This actually works really nicely (with technique 1 of the 3 above), thanks!

**Comment by alanpoulain** [comment]
Nice to hear that :smile: I didn't have time to investigate this issue, thanks for retrying yourself!
I think this issue can be closed then.

**Comment by Siregacvek** [comment]
Yes, thanks @alanpoulain . I already use your commit in my development, it works fine.
