### ISSUE TITLE
Type not getting @inheritdoc data

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#215]
If I have the following entity:

```php
class Dummy
{
    /**
     * @var string
     */
    $fullname;
}
```

At [Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer#L241](JsonLd/Serializer/ItemNormalizer.php#L241), the `$type` variable will have a type `"string"`.

However, if I do:

```php
class ExtendedDummy extends Dummy
{
    /**
     * {@inheritdoc}
     */
    $fullname;
}
```

`$type` variable will have a type `null` and throw an error since the next line call `isCollection()` on `null`. Is it the expected behaviour? I'm not against saying that we have to redeclare the `@var` when we use the `@inheritdoc`, but at least the exception thrown should be more helpful.

**Comment by dunglas** [comment]
This is perfectly correct. The PHPDoc "standard" (the current one, we're still waiting for the PSR version) doesn't allow to use inheritdoc like that.
The fact is that even using it like we do everywhere for methods is not supported by the standard, it's a SAMI/Symfony "proprietary" extension.

The PHPDoc parser we use keep in scope with the standard. If you want to inherit the doc from the parent, just remove totally the docblock of the child.

**Comment by theofidry** [comment]
Ok then maybe a more friendly error will do like `"@var notation is missing for ExtendedDummy::fullname"` would do the work

**Comment by dunglas** [comment]
Something like "cannot guess the type, add an @var annotation"? Because there are several way to guess the type: PHPDoc but also the typehint of the mutator method and Doctrine metadata.

**Comment by theofidry** [comment]
Yup

**Comment by theofidry** [comment]
Do you have any idea if the issue is still relevant @dunglas? Can't really test at the moment and if I remember right it changed a lot since then.

**Comment by dunglas** [comment]
Not relevant anymore here has the component has been moved to Symfony.
