### ISSUE TITLE
Is it possible to automatically create custom routes for all resources with a give interface?

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/core#2152]
Hi there,

I have a set of resources that have an interface to indicate that they support draft versions.  I'd like to add a `/{resource}/:id/draft` endpoint to each one.  I can do this manually, but wanted to know whether it's possible to automatically add routes for resources with a given interface?

Any pointers welcome, even just let me know where to look in the code, and I'll go from there.

Thanks.

**Comment by soyuka** [comment]
Hi! 

Take a look at how I implemented this in https://github.com/api-platform/core/pull/2040/files

Basically I've added:
- a MetadataFactory (https://github.com/api-platform/core/pull/2040/files#diff-cbb762db80115b8cd945e1b7afca2549R26) that adds a new operation with a special `_path_suffix` attribute
- an OperationPathResolver (https://github.com/api-platform/core/pull/2040/files#diff-77c2bdd4ba15c5b78fe842e846bfa3e0) to add this suffix when it matches my criterias

**Comment by toby-griffiths** [comment]
@soyuka Thanks for that.  That's really helpful.
