### ISSUE TITLE
Question: How to get parent and nested entities filtered by nested entity column

### ISSUE THREAD

**Issue by kolinko-ant** [api-platform/core#2154]
Hello guys! I am dealing right now with api platform and what I've seen so far is really make me happy. Thanks for such great product! 

Now my question. Imagine I have 2 entities - `faqCategory` (has 1-to-many to faq) and `faq` (many-to-1 to category). Faq entity has string column `isTop`. What I want is to get all categories with faq items filtered by faq.isTop = 1.

In code It looks like this (simplified):
FaqCategory
```
/**
 *
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "path"="/faq/categories"
 *          }
 *     },
 *     itemOperations={
 *          "get"={
 *              "path"="/faq/categories/{id}"
 *          }
 *     },
 *     normalizationContext={"groups"={"faq_category_collection"}},
 * )
 * @ApiFilter(SearchFilter::class, properties={"faqItems.istop": "exact"})
 * @ORM\Table(name="faq_categories")
 * @ORM\Entity
 */
class FaqCategory
{
...
/**
     * @var
     * @ORM\OneToMany(targetEntity="Faq", mappedBy="faqCategory")
     * @Groups({"faq_category_collection"})
     */
    public $faqItems;

    /**
     * FaqCategory constructor.
     */
    public function __construct()
    {
        $this->faqItems = new ArrayCollection();
    }
}
```
Faq
```
/**
 *
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "path"="/faq"
 *          }
 *     },
 *     itemOperations={
 *          "get"={
 *              "path"="/faq/{id}"
 *          }
 *     },
 *     normalizationContext={"groups"={"faq_collection"}},
 * )
 * @ORM\Table(name="faq")
 * @ORM\Entity
 */
class Faq
{
 /**
     * @var string
     *
     * @ORM\Column(name="istop", type="string", length=0, nullable=false)
     * @Groups({"faq_category_collection"})
     */
    private $istop = '0';

/**
     * @var
     *
     * @ORM\ManyToOne(targetEntity="FaqCategory", inversedBy="faqItems")
     * @ORM\JoinColumn(name="catg_id", referencedColumnName="id")
     */
    private $faqCategory;
}
```
So, by requesting url `/api/service/faq/categories?faqItems.isTop=1` I want to get categories (which have only top faq items) including faq items which is only `isTop`, for example:
```
[
  {
    "id": 20,
    "content": "Booking",
    "faqItems": [
      {
        "id": 43,
        "catgId": 20,
        "istop": true
      },
     {
        "id": 44,
        "catgId": 20,
        "istop": true
      }
      ]
}]
,
```
But in fact I have faq items which have `isTop=0` as well.

Final sql query looks like this:
```
SELECT DISTINCT *
FROM faq_categories c0_ 
LEFT JOIN faq c1_ ON c0_.id = c1_.catg_id 
WHERE c0_.id IN (
	SELECT c2_.id FROM faq_categories c2_ LEFT JOIN faq c3_ ON c2_.id = c3_.catg_id WHERE c3_.istop = '1'
	) 
	ORDER BY c0_.id ASC LIMIT 30;
```
So, subquery returns all categories which have top faq items and then just get all categories with resulted ids. That's why in response I have correct categories, but inside category I have all the faq items (top and not top). But I want to have only top items inside category. 

Is that possible to do with native filters system or I have to create custom filter and build custom query to get needed results?

**Comment by kolinko-ant** [comment]
Any information about this?  Will be really appreciated for any help.

**Comment by kolinko-ant** [comment]
@soyuka Thanks for the answer.

> if isTop is a boolean you should use a BooleanFilter.

Yes, I know that. But in particular case this is string. 

> You need to handle this behavior by using a custom query though.

To achieve this I need to create custom filter, right?

**Comment by soyuka** [comment]
> To achieve this I need to create custom filter, right?

To make things easier I'd do a DataProvider with my own query and inject `RequestStack` to get the parameter if needed.

**Comment by kolinko-ant** [comment]
Ok, will try it. Thanks a lot!

**Comment by teohhanhui** [comment]
Duplicate of #944

**Comment by teohhanhui** [comment]
Related: #944

**Comment by teohhanhui** [comment]
Duplicate of #2253
