### ISSUE TITLE
DateFilter before and after is the same date with a datetime field in doctrine

### ISSUE THREAD

**Issue by axelvnk** [api-platform/core#2166]
When applying a date range to an endpoint to get data for just one whole day, for example ?someDateField[before]=2018-08-21&someDateField[after]=2018-08-21

The query results in this : 
>=2018-08-21 00:00:00 AND <=2018-08-21 00:00:00

Which will only show results that have exactly the datetime 2018-08-21 00:00:00

When what you really want is : 
>=2018-08-21 00:00:00 AND <=2018-08-21 23:59:59

Can't we check if the before and after dates are the same and by default change the time of the latter to 23:59:59 (or bump 1 day)

Ofcourse you can pass the time as well, but it seems desirable that when asking for one day, you get one day..

**Comment by ragboyjr** [comment]
I think you can specify this with strictly_before/strictly_after.

I think you just need to do: `someDateField[strictly_before]=2018-08-22&someDateField[after]=2018-08-21`

**Comment by ragboyjr** [comment]
@axelvnk
