### ISSUE TITLE
Allow Constructors with Relationships

### ISSUE THREAD

**Issue by ragboyjr** [api-platform/core#2169]
Currently, Resource constructors will fail if they contain a relationship entity.

```php
class Book
{
    private $id;
    private $author;
    private $title;

    public function __construct(Author $author, string $title) {
        $this->author = $author;
        $this->title = $title;
    }

    public function getId(): ?int { return $this->id; }
    public function getAuthor(): Author { return $this->author; }
    public function getTitle(): string { return $this->title; }
}
```

This is because the ItemNormalizer in API Platform only denormalizes a relationship entity on the `setAttributeValue` method call. However, the `instantiateObject` method call in the normalizer is done before the relationship value has been denormalized.

I think this could be trivial to implement if we override the instantiateObject, check if any of the properties are relationships, and if so, we denormalize them ahead of time so that whether a value is set via setAttributeValue or instantiateObject, it will be denormalized properly.

Thoughts?

**Comment by ragboyjr** [comment]
This is the same issue as #2123

**Comment by bendavies** [comment]
I think there are extensive tests for this here from @komik966
https://github.com/api-platform/core/pull/1991

I think it's very unfortunate that https://github.com/api-platform/core/pull/1749 was merged without these tests.

**Comment by ragboyjr** [comment]
I think we can close this now that @komik966's changes have been merged.

Thanks!
