### ISSUE TITLE
cannot set protected manytoone

### ISSUE THREAD

**Issue by emillosanti** [api-platform/core#217]
based on the product/offer example here:

https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/getting-started.md#mapping-the-entities

posting an Offer with "post": "/posts/1" works

however, when changing Offer class' $post to protected and generating doctrine's getter/setters,
post is not set and the field is left null.

**Comment by theofidry** [comment]
Can you show your getter/setters and detail what actions you do (the body of your post action) with which version you using?

Passing `public` properties from public to `protected` or `private` is definitely not an issue as long as they have accessors. The bundle uses the `PropertyAccessor` to do this work. So it must be something else.

**Comment by emillosanti** [comment]
Offer class (working version):

```
/**
 * @ORM\Entity
 */
class Offer
{
    //...

    /**
     * @ORM\ManyToOne(targetEntity="Product")
     */
    protected $product;

    /**
     * Set product
     *
     * @param \AppBundle\Entity\Product $product
     * @return Offer
     */
    public function setProduct(\AppBundle\Entity\Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get product
     *
     * @return \AppBundle\Entity\Product 
     */
    public function getProduct()
    {
        return $this->product;
    }
}
```

POST:
```
{
  "product": "/api/products/1",
  "description": "test description",
  "price": 1.25
}
```
RESPONSE:
```
{
  "@context": "/api/contexts/Offer",
  "@id": "/api/offers/2",
  "@type": "Offer",
  "description": "test description",
  "price": 1.25,
  "product": null
}
```

When the class is revised by setting product to public:
note: this works with or without the setters.
```
    public $product;
```


POST:
```

{
  "product": "/api/products/1",
  "description": "test description public",
  "price": 1.25
}
```

RESPONSE:
```
{
  "@context": "/api/contexts/Offer",
  "@id": "/api/offers/3",
  "@type": "Offer",
  "description": "test description public",
  "price": 1.25,
  "product": "/api/products/1"
}
```


package versions:
dunglas/api-bundle                   dev-master 420cab9

with
symfony/symfony                      v2.7.3
doctrine/orm                         v2.4.7

**Comment by pvgnd** [comment]
I think your docblock is incomplete.
Could you try to set the @var

```
/**
  * @var \AppBundle\Entity\Product
  * 
  * @ORM\ManyToOne(targetEntity="Product")
  */
protected $product;
```

Moreover, I think you should use the "itemOffered" property name (with @IRI("http://schema.org/itemOffered") annotation) instead of "product" as described in http://schema.org/Offer

**Comment by emillosanti** [comment]
found the issue, in the ReflectionLoader's populateFromSetter method.

```
        if (
            null !== $denormalizationGroups ||
            1 !== $numberOfRequiredParameters ||
            !preg_match('/^(set|add|remove)(.+)$/i', $methodName, $matches)
        ) {
            return;
        }
```

since my setter method is declared : 
```
public function setProduct(\AppBundle\Entity\Product $product = null)
```
$numberOfRequiredParameters is equal to 0.

I would suggest using numberOfParameters (via ReflectionFunctionAbstract::getNumberOfParameters), but I'm certainly not familiar with its implications.

**Comment by theofidry** [comment]
Indeed I'm encountering the same issue on my project.

**Comment by dunglas** [comment]
We found an edge case. A mutator with no required parameter looks weird to me but I fully understand this workaround to both have the typehint and Allow null value.

A smart fix would be to allow only "optional" parameters if they have a typehint and a default value being `null`. What do you think?

**Comment by ogizanagi** [comment]
:+1:

**Comment by theofidry** [comment]
Is it the only edge case? I mean we can put different default values, `null` is the mots usual one but for an array for instance we often use `[]` too.

**Comment by dunglas** [comment]
@theofidry the solution proposed by @emillosanti looks good to me:

In https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Loader/ReflectionLoader.php#L141 allow setters with 0 or 1 required parameters (instead of only those with one currently).

**Comment by theofidry** [comment]
Ok I'll try it this weekend see if it works out for me. See [my comment](https://github.com/dunglas/DunglasApiBundle/pull/226#issuecomment-140072451) for all the cases. Do we have a test suite to test it out?

**Comment by dunglas** [comment]
Not relevant anymore (the loader system has been entirely rewrote).
