### ISSUE TITLE
Hide password from user interface, but build form to allow entry of a new password

### ISSUE THREAD

**Issue by christhomas** [api-platform/core#2186]
Hi, 

I can use the serializer to remove a password from a user when its being sent to api-platforms admin panel. But then the create form is missing the password field allowing me to set a password on new entities.

Is there a way to solve this problem using the annotations? or some configuration?

**Comment by dunglas** [comment]
Hi,

You mean, you want to hide it from the admin UI, but still expose it in the API? In this case, you can just remove the fields you don't want in the admin: https://github.com/api-platform/admin/pull/87

It deserves a proper documentation entry.

**Comment by christhomas** [comment]
I think there is perhaps a security issue here. The problem is that when you read the user from the database, the entity has a field for password. But that password should never be passed to a third party for any reason. That entity should retain it privately and can test the password is matching the one given, but never give the raw encrypted password out.

So the solution posted here is merely to ignore the field that was sent by the API. Then there is still the problem of passing the password across the network to a third party to ignore. Wouldn't that mean I could read into your javascript app and pull out peoples passwords?

With other fields, it could make sense to alter the form based on selection variables like this, but passwords are different since they are sensitive and they should be held to an even higher standard.

**Comment by dunglas** [comment]
Ok I got what you want to do.

You must never expose the encrypted password. What I do in my apps is:

* create a `plainPassword` property that is not mapped with a database's column (memory only)
* create a `password` property mapped with a database column, it contains the encrypted password (the encryption is done server side, by hashing the `plainPassword` field, you can use event listeners for that)
* use normalization/denormalization groups to **never** expose `password` publicly
* use normalization/denormalization groups to expose `plainPassword` **only** for the `POST` operation
* optionally, you can also use dynamic serialization groups to also expose `plainPassword` for the `PUT` operation **if** the current user is allowed to do it

Btw, I plan to release a "UserBundle" at some point, it will help for such use cases.

**Comment by christhomas** [comment]
Ah ok, this sounds a good idea, you have a shadow field for the form but you only read the database field into another field which isn't exposed. Nice, thanks!
