### ISSUE TITLE
Nelmio API Doc support is broken

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#219]
------------------

This is a meta-issue to gather Nelmio related issues.

------------------

Based on `dev-master`, NelmioApiDoc is broken due to multiple issues:
- [ ] Since #180, **ClassMetadataFactoryInterface**, **ClassMetadataFactory**, **AttributeMetadataFactoryInterface**, and **AttributeMetadataFactory** moved from the `Dunglas\ApiBundle\Mapping` namespace to the `Dunglas\ApiBundle\Mapping\Factory` namespace, and some signatures has changed.  
:small_red_triangle: Both Nelmio [`DunglasApiParser`](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/DunglasApiParser.php#L50) and [`DunglasApiProvider`](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/AnnotationsProvider/DunglasApiProvider.php#L47) typehint the old **ClassMetadataFactoryInterface** location.  
:small_red_triangle: `ClassMetadataFactoryInterface::getAttributes()` became `ClassMetadataFactoryInterface::getAttributesMetadata()`,  
`ClassMetadataFactoryInterface::getTypes()` became `ClassMetadataFactoryInterface::getType()`, ...  
Related: https://github.com/nelmio/NelmioApiDocBundle/pull/685

- [x] Switching from the `ResourceController` to the `ADR` pattern implementation with **Actions** as callables classes controllers services:  
:small_red_triangle: Nelmio [`ApiDocExtractor::getReflectionMethod($controller)`](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php#L205-L233) properly handle controllers as services, but not callable classes with the `__invoke()` method.
This is clearly a Nelmio issue, but could be avoid by defining a proper method to use instead of `__invoke`.  
:white_check_mark: **Merged PR**: https://github.com/nelmio/NelmioApiDocBundle/pull/695

Although, there are other issues with the current behaviors:
- [ ] We cannot make custom operations with a custom payload (it will work, but the nelmio sandbox would be wrong): https://github.com/dunglas/DunglasApiBundle/issues/202

https://github.com/nelmio/NelmioApiDocBundle/pull/686 fixes most of those issues, but directly in the Nelmio repository. 
But the 2.9.* version should remain compatible with latest beta IMO.

As explained in https://github.com/dunglas/DunglasApiBundle/issues/156#issuecomment-128405547, I think the `DunglasApiProvider` & `DunglasApiParser` should belong to the `api-bundle` in order to spot breaking changes as soon as they are made.

What do you think ?

**Comment by dunglas** [comment]
About the `invoke()` method support, it must definitely be added to NelmioApiDoc because this is a feature supported by Symfony and used by projects not depending of ApiBundle.

**Comment by teohhanhui** [comment]
+1

**Comment by teohhanhui** [comment]
Fixed by #410
