### ISSUE TITLE
Support short UUID in Ramsey bridge

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#2191]
We could add rudimentary support in the Ramsey UUID normalizer for the short UUID variant: https://packagist.org/packages/pascaldevink/shortuuid

**Comment by soyuka** [comment]
It's really easy to add this in one's own project no? Not sure we need to add this to core.

**Comment by ParmentierChristophe** [comment]
we can't implement this, because this test not working :

```
    public function testFailDenormalizeUuid()
    {
        $this->expectException(\ApiPlatform\Core\Exception\InvalidIdentifierException::class);

        $uuid = 'notanuuid';
        $normalizer = new ShortUuidNormalizer();
        $this->assertTrue($normalizer->supportsDenormalization($uuid, ShortUuid::class));
        $normalizer->denormalize($uuid, ShortUuid::class);
   
    }
```

**Comment by soyuka** [comment]
see https://github.com/pascaldevink/shortuuid/issues/29

**Comment by thib92** [comment]
Would love to take that one. Any idea how this should be configured? I'm guessing it should be an opt-in configuration option?

**Comment by soyuka** [comment]
We can't implement this yet because an invalid uuid doesn't throw on the upstream library. see related links, mb you can try to patch there first

**Comment by thib92** [comment]
Oh good to know, I'll see what I can do. Thanks @soyuka
