### ISSUE TITLE
Swagger Documentation ignore @ApiProperty(writableLink=true)

### ISSUE THREAD

**Issue by ehdez82** [api-platform/core#2192]
Greetings, in the POST operation for the Equipment entity the Swagger documentation does not correctly display the type for the field "equipmentType".

Expected result:
{
  "serialNumber": "string",
  "equipmentType": "string",
  "customer": "string"
}

Current result:
{
  "serialNumber": "string",
  "equipmentType": {},
  "customer": "string"
}

These are my entities:
Equipment.php
```
/**
 * @ApiResource(
 *      collectionOperations={
 *          "get"={"method"="GET","normalization_context"={"groups"={"equipment:read:all"}}},
 *          "post"={"method"="POST","route_name"="equipment_post"}
 *      },
 *      itemOperations={
 *          "get"={"method"="GET"}
 *      },
 *      attributes={
 *          "normalization_context"={"groups"={"equipment:read"}},
 *          "denormalization_context"={"groups"={"equipment:write"}}
 *      }
 * )
 * 
 * @ORM\Table(name="equipment")
 * @ORM\Entity
 */
class Equipment {

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups({"equipment:read:all"})
     */
    private $id;


    /**
     * @ORM\Column(name="serial_number", type="string", length=50, nullable=false)
     * @Groups({"equipment:read","equipment:read:all","equipment:write"})
     * @Assert\NotBlank()
     */
    private $serialNumber;


    /**
     * @ORM\ManyToOne(targetEntity="EquipmentType")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="equipment_type_id", referencedColumnName="id")
     * })
     * @ApiProperty(writableLink=true)
     * @Groups({"equipment:read","equipment:read:all","equipment:write"})
     * @Assert\NotBlank()
     */
    private $equipmentType;

    /**
     * @ORM\ManyToOne(targetEntity="Customer")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="customer_id", referencedColumnName="id")
     * })
     * @Groups({"equipment:write"})
     * @Assert\NotBlank()
     */
    private $customer;

    /* ... */
}
```

EquipmentType.php
```
/**
 * @ApiResource(
 *      collectionOperations={
 *          "get"={"method"="GET","normalization_context"={"groups"={"equipmenttype:read:all"}}}
 *      },
 *      itemOperations={
 *          "get"={"method"="GET"}
 *      },
 *      attributes={
 *          "normalization_context"={"groups"={"equipmenttype:read"}}
 *      }
 * )
 * 
 * @ORM\Table(name="equipment_type")
 * @ORM\Entity
 */
class EquipmentType
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups({"equipmenttype:read:all","equipment:read"})
     */
    private $id;


    /**
     * @ORM\Column(name="code", type="string", length=5, nullable=false)
     * @Groups({"equipmenttype:read","equipmenttype:read:all","equipment:read","equipment:read:all"})
     */
    private $code;

    /**
     * @ORM\Column(name="name", type="string", length=50, nullable=false)
     * @Groups({"equipmenttype:read","equipmenttype:read:all","equipment:read","equipment:read:all"})
     */
    private $name;

    /* ... */

}
```

Customer.php
```
/**
 * @ApiResource(
 *      collectionOperations={
 *          "get"={"method"="GET","normalization_context"={"groups"={"customer:read:all"}}},
 *          "post"={"method"="POST"}
 *      },
 *      itemOperations={
 *          "get"={"method"="GET"},
 *          "put"={"method"="PUT"}
 *      },
 *      attributes={
 *          "normalization_context"={"groups"={"customer:read"}},
 *          "denormalization_context"={"groups"={"customer:write"}}
 *      }
 * )
 * 
 * @ORM\Table(name="customer")
 * @ORM\Entity
 */
class Customer {

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups({"customer:read:all"})
     */
    private $id;


    /**
     * @ORM\Column(name="name", type="string", length=256, nullable=false)
     * @Groups({"customer:read","customer:read:all","customer:write"})
     */
    private $name;

    /**
     * @ORM\Column(name="code", type="string", length=5, nullable=false)
     * @Groups({"customer:read","customer:read:all","customer:write"})
     */
    private $code;

    /* ... */

}
```

I have tried putting the annotation @ApiProperty (writableLink = true) to the field "equipmentType" without any results. Perhaps the writableLink=true functionality is not clear to me, I did not find a clear explanation in the ApiPlatform documentation.

Why does the documentation interpret the "equipmentType" and "customer" fields differently when both have the same type of relationship (ManyToOne)?
Thanks in advance.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/1980
https://github.com/api-platform/core/pull/1997

**Comment by ehdez82** [comment]
I have reviewed these issues and is fixed the preference for user metadata, which is correct.

However, I have consulted the DocumentationNormalizer class and the writableLink value is not consulted, only the readableLink value.

Specifically the function getType in [DocumentationNormalizer.php#L515](https://github.com/api-platform/core/blob/6c15002da5c2ca0e79d1fd20213051ff217b007f/src/Swagger/Serializer/DocumentationNormalizer.php#L515)

What would happen on a scenario with readableLink=true and writableLink=true? I think I should give writableLink preference if it is a POST or PUT operation.

Sorry for any misinterpretation of the core code. I'm still a novice with the framework.

I take this opportunity to leave my congratulations. I consider that the APIPlataform framework is very powerful and robust. You have done a great job.
Thanks

**Comment by soyuka** [comment]
Yes I think that you're right about the DocumentationNormalizer, would you like to propose a patch?

**Comment by ehdez82** [comment]
Yes, please, I would like to propose a patch. How I should proceed?

**Comment by soyuka** [comment]
> Yes, please, I would like to propose a patch. How I should proceed?

1. Fork the project (top right on github)
2. Change the code and push on your fork
3. Open a pull request on github

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
