### ISSUE TITLE
[GraphQL] Requesting _id without id leads to "cannot return null for non-nullable field"

### ISSUE THREAD

**Issue by jamesisaac** [api-platform/core#2194]
Perhaps related to #2132 and #2060

This query:

```graphql
{
  person(id: "/people/1") {
    _id
    name
  }
}
```

(Where `$id` on the model is a private field with just a getter, like in the example project) produces this error:

```json
{
  "errors": [
    {
      "debugMessage": "Cannot return null for non-nullable field Person._id.",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "person",
        "_id"
      ]
    }
  ],
  "data": {
    "person": null
  }
}
```

Can be fixed by including `id` in the query:

```graphql
{
  person(id: "/people/1") {
    id
    _id
    name
  }
}
```

```json
{
  "data": {
    "person": {
      "id": "/people/1",
      "_id": 1,
      "name": "Alice"
    }
  }
}
```

Maybe this is not a priority until the refactoring of #2022 has been carried out.

**Comment by dunglas** [comment]
@jamesisaac can you try the patch I proposed in #2195 to confirm it fixes this issue?

**Comment by jamesisaac** [comment]
@alanpoulain Is this something that just changed?  I thought `_id` was the recommended way to get our model's internal `$id` property (as `id`is reserved in GraphQL for the IRI).

@dunglas Thanks!  I've left my comment on the PR.

**Comment by dunglas** [comment]
@jamesisaac you’re right, your usage is legit.
