### ISSUE TITLE
Relationship set as null creates a new empty object

### ISSUE THREAD

**Issue by iwan-wijaya** [api-platform/core#2197]
### The problem
Whenever I set a relationship value as null on a `nullable=false` field the serializer will instantiate a new object and doctrine will throw an error. (`ORMInvalidArgumentException`)
### Expected behavior
Serializer should keep null values or throw `ApiPlatform\Core\Exception\InvalidArgumentException`?.

### Steps to reproduce
I have a "Product" entity that has a relatonship like this: 

```php
    /**
     * @var ProductCategory|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\ProductCategory")
     * @ORM\JoinColumn(name="product_category_id", nullable=false) <- nullable is false here
     *
     * @Assert\NotBlank()
     *
     * @Groups("product:product_category")
     */
    private $productCategory;

    public function getProductCategory(): ?ProductCategory
    {
        return $this->productCategory;
    }

    public function setProductCategory(?ProductCategory $productCategory): Product
    {
        $this->productCategory = $productCategory;

        return $this;
    }
```
Create a new entity by POST
```json
{
    "name": "Nice product",
    "price": "100",
    "discount": "0",
    "stock": 0,
    "productCategory": null // <- relationship value set as null
}
```

Will throw this error:

> A new entity was found through the relationship 'App\Entity\Product#productCategory' that was not configured to cascade persist operations for entity: App\Entity\ProductCategory@000000000f29717c000000002e829821. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\ProductCategory#__toString()' to get a clue.

Apparently if I set productCategory value to null and nullable is false, then the serializer will instantiate  a new empty productCategory object

```
Product {#490 ▼
  -id: null
  -name: "Nice product"
  -price: "100"
  -discount: "0"
  -stock: 0
  -productCategory: ProductCategory {#776 ▼  <- Should be null
    -id: null
    -name: null
    -createdAt: null
    -updatedAt: null
  }
  -createdAt: null
  -updatedAt: null
}
```

After tracing the issue I found out that  my object is instantiated from here and I'm not sure why: https://github.com/symfony/serializer/blob/master/Normalizer/AbstractNormalizer.php#L398

Here is my complete entity code
https://gist.github.com/iwan-wijaya/d289215ef619214f999fbbcacf093bf0
https://gist.github.com/iwan-wijaya/c609375f85cf0d9531113d11b900f637

**Comment by antograssiot** [comment]
In your product entity you should remove `product_category` from denormalization groups and you'll get the correct exception.

**Comment by iwan-wijaya** [comment]
@antograssiot By doing so, I will only be able to submit IRIs as product category, what if I want to embed product category data?

**Comment by jordanaubert** [comment]
This issue seems to be solved, I get this error when I set `null` to productCategory value : 
```
Expected IRI or document for resource \"App\\Entity\\ProductCategory\", \"NULL\" given."
```

WDYT @soyuka ?

**Comment by soyuka** [comment]
:+1: you can always send a behat test case as a proof :)
