### ISSUE TITLE
Add a test for SwaggerCommand with --yaml 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#2198]
see https://github.com/api-platform/core/pull/2121

**Comment by dkarlovi** [comment]
The test should be with both JSON any YAML, the root cause is unrelated to serialization format.

**Comment by antograssiot** [comment]
This was partially done in https://github.com/api-platform/core/pull/2256.
I didn't saw this issue before, do you have something more specific to test in mind @soyuka  ?

**Comment by soyuka** [comment]
Nope thanks @antograssiot !
