### ISSUE TITLE
Allow writable IDs

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#2201]
https://github.com/api-platform/core/pull/2022#issuecomment-398851861

**Comment by clemherreman** [comment]
Hello everyone,
Are there any news on this? I noticed #2022, and I wanted to know if there is any ETA on this. Like @borNfreee [#2022 (comment)](https://github.com/api-platform/core/pull/2022#issuecomment-418085756) I'm willing to help on that, but I guess I'd need some guidance on how :)

My use case is that I have an application, consuming my API, that needs to work offline, and still create new resources instances locally, while offline. A good solution would be to have my resources uses UUID as identifiers, and allow to specify the identifiers in `POST` calls. This way the application and the API can create new instances independently.

**Comment by bendavies** [comment]
@dunglas wanted to work on this but didn't have time IIRC, like many of us, so I'm sure help would be appreciated if you want to start!

**Comment by soyuka** [comment]
I do think that this is now working, let me know if you have no solution.
