### ISSUE TITLE
Allow json (and ld+json) body for operations with _api_receive=false

### ISSUE THREAD

**Issue by mgiraud** [api-platform/core#2202]
Hi !

Maybe I miss something, but why this kind of request relies on multipart/form-data exclusively as written here : https://api-platform.com/docs/core/file-upload/#making-a-request-to-the-code-classlanguage-textmedia_objectscode-endpoint

I was trying to write some custom operations like "register" or "reset password" actions and do not want to depend on my User Entity for deserialization. I guess there is an other clean way to do this, can you help me out ?

thank you in advance

**Comment by Jibbarth** [comment]
I think you should add the `_api_respond=true` parameters to your route.

**Comment by mgiraud** [comment]
It doesn't work better
