### ISSUE TITLE
GraphQl: redundant fetch of entities

### ISSUE THREAD

**Issue by Siregacvek** [api-platform/core#2204]
Good morning!
In the latest version 2.3.2 I found the following issue.

**Given** I have collection of entities `Entity`.
**Given** I have [extension](https://api-platform.com/docs/core/extensions/) `EntityFilter` to filter `Entities` per user permissions. So some users can see all entities, some users - partial sub-collections, some - don't see them at all.
**Given** I sent graphql request as a user:
```
{
   entities {
      id
      name
   }
}
```
**Then** in profiler I have to see one db-query like
```
Select * from entity where <some my business logic conditions to limit access>
```
**But** I see 2 db-queries:
```
Select * from entity
Select * from entity where <some my business logic conditions to limit access>
```
Obviously I don't need the first query and it's useless for my case.

I see that recently you added this [commit](https://github.com/api-platform/core/commit/cce3781f78e985110c6a5b0c379f35cb23d8d935#diff-0e280fa016b79eacb061c504a6348752) and it's a reason of this weird behavior. I've read the article of Ocramius, but anyway this commit is not clear to me.

**Comment by Siregacvek** [comment]
I found a place in article related to this commit, but as I understand (and see this every day in my queries) partial hydration already works (out-of-the-box for Doctrine). So this commit looks weird for me. Please explain if I'm not right.

**Comment by alanpoulain** [comment]
Hello. It will be reverted soon. See https://github.com/api-platform/core/pull/2205.

**Comment by Siregacvek** [comment]
@alanpoulain great, thanks!

**Comment by alanpoulain** [comment]
Should be OK now.
