### ISSUE TITLE
Altering response cache headers for an operation / resource

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#2207]
I've created a custom operation for a resource to fetch one randomly. The cache response means that varnish would save the response to the cache.

Looking at the `AddHeaderListener` class, this has a priority of `-1`.

The `EventPriorities` constants do not provide a priority less than this, so for now I have to add a response listener and hard code the priority.

Is it worth simply adding a constant to `EventPriorities`, something like `POST_HEADERS`, just in case the priority of the listener is changed in future? Looking at the listener, it only reads the settings from the config so cannot be set on the fly for a single entity/collection if required. Otherwise, is there another recommended method I may be missing?

Thanks!

**Comment by silverbackdan** [comment]
In the interest of keeping this up to date, had a chat with @dunglas and 2 options:
1 - the cache header listener should not override manually configured headers
2 - add the ability to adjust cache headers in annotations

I'll reference this issue in a PR when I have a moment.

**Comment by teohhanhui** [comment]
Fixed in #2288
