### ISSUE TITLE
IRI system applied to collections

### ISSUE THREAD

**Issue by ymarillet** [api-platform/core#2211]
Hey there,

Just sharing a thought that could lead to an enhancement.

Quick example from the Demo app:

https://demo.api-platform.com/books.jsonld
Well, currently, it's retuning error 500, but as per the contract, we should get something like:

```json
[
  {
    "isbn": "string",
    "title": "string",
    "description": "string",
    "author": "string",
    "publicationDate": "2018-09-20T13:01:18.885Z",
    "reviews": [
      {
        "body": "blahblah"
      },
      {
        "body": "blehbleh"
      },
      {
        "body": "foobar"
      }
    ]
  }
]
```

Let's say there will be so many reviews attached to a single book that finally we don't want to embed them in the response, we would have, for example:

```json
[
  {
    "isbn": "string",
    "title": "string",
    "description": "string",
    "author": "string",
    "publicationDate": "2018-09-20T13:01:18.885Z",
    "reviews": [
        "/reviews/1",
        "/reviews/4",
        "/reviews/11"
    ]
  }
]
```

It would be the default behaviour btw, if you'd not specify normalization groups on the resource.
Bloating point: the orm still needs to fetch the reviews from the database to transform them into IRIs, and if there are 1000 reviews, it would output 1000 IRIs. 

In that case you would tell me to not expose the "reviews" attribute, but we'd lose an important part of the autodiscovery process ...

Maybe we could instead have an IRI-like system on collections ?:

```json
[
  {
    "isbn": "string",
    "title": "string",
    "description": "string",
    "author": "string",
    "publicationDate": "2018-09-20T13:01:18.885Z",
    "reviews": "/reviews?book.id=1"
  }
]
```

What do you guys think ?

**Comment by soyuka** [comment]
Would be feasible without much code. Especially with subresources. It's kinda the reverse of what's working today.
For example:

```
{"reviews": "/books/1/reviews", ...}
```

I'm :+1:

**Comment by jvancoillie** [comment]
What about this enhancement?
In the [documentation](https://api-platform.com/docs/core/subresources/#subresources), subresources can be nested the -to-many relationship but I can't get this behavior set up.
I must have missed something.

**Comment by dunglas** [comment]
I like the idea! But we must be sure to implement this in the most standard and future-proof way possible (especially for the format of the query parameter).

**Comment by soyuka** [comment]
3.2 now supports this
