### ISSUE TITLE
SubResource fields of only be one type

### ISSUE THREAD

**Issue by ragboyjr** [api-platform/core#2220]
Currently, depending on your serialization context, a sub-resource will either be a string representing it's id, or it will be an object representing the entity.

This polymorphic treatment of sub-resource fields makes writing frontend code that has to deal with entities and sub fields which can be different types difficult and more cumbersome since you'll always need to check to see if a field is a string vs object. This is further exacerbating considering that most clients are using javascript and being able to differentiate types in javascript isn't the nicest DX.

I propose that instead of conditionally serializing an sub resource as a string or object, we just a different property for the id of the sub resource and the actual entity.

So example:

```php
class Book {
  public $id;
  public $name;
  public $author;
}

class Author {
  public $id;
  public $name;
}
```

The serialization of the book class would look like one of the following currently (depending on the serialization context):

```json
{
  "id": 1,
  "name": "book",
  "author": "/authors/1"
}
```

OR:

```json
{
  "id": 1,
  "name": "book",
  "author": {
    "id": 1,
    "name": "author"
  }
}
```

I propose, that the id of the sub entity would always go into a field `{entityName}Id`, and the entity field will either exist or not depending on if it's included in the serialization context:

```json
{
  "id": 1,
  "name": "book",
  "authorId": "/authors/1"
}
```

OR:

```json
{
  "id": 1,
  "name": "book",
  "author": {
    "id": 1,
    "name": "author"
  },
  "authorId": "/authors/1"
}
```

In the new version, you can always reliably access the Id of a sub resource, and it's much easier to see if a sub resource is included or not via just checking if it's undefined:

```js
if (book.author) {
  // you now know book.author is an object
}
```

**Comment by ragboyjr** [comment]
Further more, if you were to use a strictly typed frontend in Swift or iOS, with this new enhancement, the client's data model would be able to look like:

```swift
class Book {
  var id: Int
  var name: String
  var author: Author?
  var authorId: String
}
```

**Comment by soyuka** [comment]
this should work now :)
