### ISSUE TITLE
`allow_extra_attributes=false` does not work for `{"entity": {"id": XXX}}` notation

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/core#2229]
It's possible to `POST` request with relation by either:

* sending an IRI:

```json
{
    "id": 1,
    "relatedEntity": "/api/related_entities/2"
}
```

* sending an object with the ID:

```json
{
    "id": 1,
    "relatedEntity": {
        "id": "2"
    }
}
```

Note - both request are valid and works in the same way - new `Entity` is created, and existing `RelatedEntity` relation is saved with the `Entity`.

However, when I add `allow_extra_attributes=false` flag to the `$context`, the latter example stops working and fails with the following error:

```
Extra attributes are not allowed ("id" are unknown)
```

This error is triggered when `relatedEntity` object is being denormalized.

The root cause of it is this code:

https://github.com/api-platform/core/blob/4dacd1ac2f1776fcedb19c8b085a590f5177ff86/src/Serializer/AbstractItemNormalizer.php#L241-L249

and in particular this line returns `false`: `isset($context['api_denormalize']) && ($propertyMetadata->isWritable() || !\is_object($classOrObject) && $propertyMetadata->isInitializable()) `

Why? Because `id` is not writable by default (it's private and has only getter), it is not initializable.

When you replaces such request with IRI - it works fine.

So I think it's a bug.

**Comment by soyuka** [comment]
plain identifiers have been deprecated, there's a normalizer in the documentation if needed
