### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by mikelerch** [api-platform/core#2240]

**Comment by mikelerch** [comment]
@dunglas Could you please delete this issue? It bothers me that it's showing up on my timeline :D

**Comment by mikelerch** [comment]
ping @antograssiot @mauchede @meyerbaptiste @mysiar @theofidry @teohhanhui @soyuka @Simperfit

**Comment by theofidry** [comment]
Hi, sorry but besides not having the permission, I don't think it's a bit deal. However getting spammed for it is certainly far more unpleasant. Please avoid this in the future
