### ISSUE TITLE
Allow to set the sunset HTTP header

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#2245]
API Platform could provide a developer-friendly way to set [the Sunset HTTP header](https://tools.ietf.org/html/draft-wilde-sunset-header-06) on deprecated endpoints to indicate when this endpoint will not be available anymore. The syntax like could be like the following:

```php
/**
 * @ApiResource(
 *   deprecationReason="This endpoint is replaced by Bar", <- already supported
 *   sunset="2019/01/01" <- any string supported by DateTime
 * )
 */
class Foo
{
}
```

**Comment by norkunas** [comment]
#2185 similar

**Comment by norkunas** [comment]
Would this support the url change without replacing the resource?

**Comment by soyuka** [comment]
> Would this support the url change without replacing the resource?

Like setting the Location header + 301 status?

**Comment by norkunas** [comment]
If it makes sense in api.

**Comment by blanky0230** [comment]
I'd like to give this a go If you don't mind ? ;)

**Comment by soyuka** [comment]
> If it makes sense in api. But my primary reason is that it should generate routes for deprecated and new route and understand the IRI's from the old and new

To transform an IRI to a Resource we use the RouteCollection, not sure how we could introduce some kind of change there to transform a route to another if it has been deprecated.
