### ISSUE TITLE
Allow other operation than GET for sub resources

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2251]
As described in the [documentation](https://api-platform.com/docs/core/operations#subresources):

> Since ApiPlatform 2.1, you can declare subresources (only for `GET` operation at the moment).

At the moment mean it will change, right? :stuck_out_tongue_winking_eye:

So, here is something planned about it? Do you think it's something easy to do?

Regards

**Comment by soyuka** [comment]
Wouldn't be that hard but definitely requires work.

```
POST /dummy/1/relatedDummy
```

Would expect a `RelatedDummy` and will have to set the reverse relation on `dummy/1` to this new one. I think that it should work without much additions if Doctrine can persist the owner from the opposite side?

Anyway, for now I'd advise you to build a custom operation with a `DataPersister` handling your specific use case.

**Comment by Soullivaneuh** [comment]
> Anyway, for now I'd advise you to build a custom operation with a `DataPersister` handling your specific use case.

Would you please like to elaborate? With a sample or a link? Thanks.

**Comment by soyuka** [comment]
Something like:

```php
<?php
/**
 * @ApiResource(
 *     itemOperation={
 *          "answer_post"= {
 *              "method"="POST",
 *              "path"="/question/{id}/answer
 *          }
 *      }
 * )
 */
```

Then https://api-platform.com/docs/core/data-persisters/#creating-a-custom-data-persister (you can use the Request (see `$request->attributes->get('_api_item_operation_name')` in the `support` to check that you call this operation only when the operation name is `answer_post`)

**Comment by torreytsui** [comment]
Hello @soyuka, @Soullivaneuh, is there any update?

I'm checking and see if I can help implementing this. It will be a great feature for the project I'm working on as we have many real use cases for it. Let me know 😃

**Comment by soyuka** [comment]
closing will be supported in 3.0
