### ISSUE TITLE
[Proposal] Make Pagination extension more engine-agnostic

### ISSUE THREAD

**Issue by er1z** [api-platform/core#2255]
When we use pure ORM pagination, it's easy because a proper extension is bundled. But if we want to rely on own DataProvider we have to write this from scratch. I mean the logic for reading a model's metadata, checking is everything associated within pagination is configured.

Right now it's tightly coupled to Doctrine's logic whereas it could be useful for another sources.

What do you think?

**Comment by soyuka** [comment]
I use something like this to wrap my DTOs and keep the pagination based metadata:

```php
<?php

declare(strict_types=1);

namespace App\Api\Collection;

use ApiPlatform\Core\DataProvider\PartialPaginatorInterface;

/**
 * This objects represents a partial collection
 * you should return it when using a paginated object, usually built out of DTOs.
 */
class PartialCollection implements \IteratorAggregate, PartialPaginatorInterface
{
    private $page;
    private $itemsPerPage;
    private $results;

    public function __construct(array $results, float $page = 1, float $itemsPerPage = 25)
    {
        $this->itemsPerPage = $itemsPerPage;
        $this->page = $page;
        $this->results = $results;
    }

    /**
     * {@inheritdoc}
     */
    public function getCurrentPage(): float
    {
        return $this->page;
    }

    /**
     * {@inheritdoc}
     */
    public function getItemsPerPage(): float
    {
        return $this->itemsPerPage;
    }

    /**
     * {@inheritdoc}
     */
    public function getIterator(): \Traversable
    {
        return new \ArrayIterator($this->results);
    }

    /**
     * {@inheritdoc}
     */
    public function count(): int
    {
        return iterator_count($this->getIterator());
    }
}
```

**Comment by er1z** [comment]
Ok, but I mean something more specific: right now it's completely up to you how metadata and parameters are being read. Look at ``\ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\PaginationExtension`` — there is much of logic that would be useful in any data source provider, for example to know what page you request and even if the particular DTO class has enabled pagination and so on.

I just ask to decouple this logic from Doctrine bridge. Or may I do something wrong — if so, let's try to find out and improve docs because DTO's chapter is a bit confusing and — IMO — insufficient for doing tasks like mine one.

**Comment by soyuka** [comment]
I'd definitely be up for it but it's not that easy to decouple. There was an attempt in https://github.com/api-platform/core/pull/955 (can't find my attempt but I also worked on this without managing to have something clean).

We could start by providing a metadata helper that gives you all the pagination settings (itemsPerPage, currentPage etc.) for a given resource + operation to ease the query configuration?

> insufficient for doing tasks like mine

What is it? May I have more details on what you're trying to accomplish?

**Comment by meyerbaptiste** [comment]
> We could start by providing a metadata helper that gives you all the pagination settings

Something like that? https://github.com/api-platform/core/pull/1999/files#diff-4f871107a843108c8faaa5bd1ec8d7e8

**Comment by er1z** [comment]
@soyuka — right now Doctrine's Pagination extension gets known what page request is it; has class enabled pagination at all and so on.

Obviously, I can implement this logic myself but it will be mostly copied of ``PaginationExtension``. And this code would be shared across my projects.

To sum up: I want the API Platform to provide me a possibility to create ``DataProvider`` with some information about what page is being requested without re-implementing existing logic. Currently, I see non-Doctrine logic as second-class citizen because trivial task requires copying and modifying code that is already present.

Why don't create something like PaginationExtensionAbstract and inherit (or compose, does not matter right now) shared logic to own adapters?

Moreover, it's mentioned how to inject extensions to own providers: https://api-platform.com/docs/core/data-providers#injecting-extensions-pagination-filter-eagerloading-etc but if you try to make them working when you get data from anything else than Doctrine, you definitely fail.

**Comment by soyuka** [comment]
> > We could start by providing a metadata helper that gives you all the pagination settings
> 
> Something like that? https://github.com/api-platform/core/pull/1999/files#diff-4f871107a843108c8faaa5bd1ec8d7e8

This is nice we def. should add it. Would this be a step forward to fixing your issue @er1z ?

> Moreover, it's mentioned how to inject extensions to own providers: https://api-platform.com/docs/core/data-providers#injecting-extensions-pagination-filter-eagerloading-etc but if you try to make them working when you get data from anything else than Doctrine, you definitely fail.

Yes extensions are def. tight to doctrine for now.

**Comment by er1z** [comment]
@soyuka — Looking briefly at: https://github.com/api-platform/core/pull/1999/files#diff-4f871107a843108c8faaa5bd1ec8d7e8 the answer is I WANT THIS. 👏

**Comment by soyuka** [comment]
@meyerbaptiste would you mind extracting this part and proposing it as a new feature? tyvm

**Comment by er1z** [comment]
Any news on this issue?

**Comment by meyerbaptiste** [comment]
I'm finishing the Elasticsearch support so I think this feature will come with it.

**Comment by er1z** [comment]
Cool, when it could be released? I'm asking because I don't know if I should implement such a functionality in my app or just wait? Do you need any help?

**Comment by z31fbras** [comment]
Hi @meyerbaptiste , do you have any news on this?
If I understand correctly, this would be a great help for users who want to paginate results of a data provider, isn't it?

**Comment by er1z** [comment]
Do you need any help, @meyerbaptiste?

**Comment by meyerbaptiste** [comment]
Good news: #1999 which includes the new pagination helper is ready for review.

**Comment by er1z** [comment]
As the #1999 has been merged, consider this issue as fixed. Thanks!
