### ISSUE TITLE
How to send empty response on POST request

### ISSUE THREAD

**Issue by dwolfhub** [api-platform/core#2261]
Ideally an anonymous user could send a post request but not send GET requests to view others submissions. I also don't want them to see the ID that was generated, so I'd like to block the response from POST and also block the GET requests.

I've tried setting permissions, _api_respond = false, not defining the itemOperation for GET, and using normalizationContext. 

Unsure how to make this possible without doing it completely custom.

Some Code:
```
/**
 * @ApiResource(
 *     collectionOperations={"post"},
 *     itemOperations={"get"}
 * )
 * @ORM\Entity(repositoryClass="App\Repository\InvitationRequestRepository")
 */
```

**Comment by dwolfhub** [comment]
Looks like the way to solve this is by using event subscribers.

**Comment by temp** [comment]
Same problem here. Documentation states that _api_respond=false disabled the SerializeListener, but this does not seem to be the case. Maybe the documentation should be changed? Or could this be a bug?

**Comment by trrtr** [comment]
For others landing here looking for an answer: setting `output: false` for an operation does the trick.
https://api-platform.com/docs/symfony/messenger/#using-messenger-with-an-input-object
