### ISSUE TITLE
Custom GET operation [question][help]

### ISSUE THREAD

**Issue by Telous** [api-platform/core#2263]
How is the correct way to create a custom GET operation using an **another** field instead **id**?

I have a this entity:

```
class Client
{
     private $id;
     private $name; (string)
     private $clientCode; (string)
     ...
}
```

I try to create an **additional** GET operation using **$clientCode** instead a **$id**.
example:
    my.api/api/clients/code/{clientCode}

I tried using [custom operation](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers), but only return a **Not Found** Exception :cry:
Is it possible to create this operation, without affecting the others?

**Comment by er1z** [comment]
Show how have you created a custom operation? Have you also created correct event listener on this operation?

**Comment by Telous** [comment]
> Have you tried annotating with `@ApiProperty(identifier=true)` or the equivalent configuration in Yaml or XML?

I try to use this, but the **id** identifier stop working for the others operations.
i need to use both of them (clientCode  and id)

**Comment by silverbackdan** [comment]
Ah I see, you'll have to add some customisation. I think you'll need to add a custom data provider:
https://api-platform.com/docs/core/data-providers/#custom-item-data-provider

I'd probably decorate the default ORM data provider https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php

If you do this where you do not overwrite the original provider as shown here:
https://symfony.com/doc/current/service_container/service_decoration.html

Make sure when you make sure your new data provider is set to only support your `Client` entity to prevent unwanted side-effects. 

I think that'll get you where you're hoping to be. 🤞

**Comment by silverbackdan** [comment]
After a quick skim, it may be that it can support multiple identifiers... Maybe add the annotation to both the id and the clientCode properties. Just adding it to one may disabled the auto-detection of the id field from the doctrine annotations.

**Comment by silverbackdan** [comment]
Sorry for lots of comments at once - I think the multiple identifiers in the provider is actually referring to composite ids in the database. You probably will have to go down the route of making your own data provider.

**Comment by er1z** [comment]
Why do you use DataProvider and Controller at once?

**Comment by silverbackdan** [comment]
As @er1z mentioned - it looks like your controller is simply getting the entity and nothing more so is not needed. But I thought I'd try and help by providing a few references for you to explore and perhaps help you.

If you create a custom controller, it will be passed the object already fetched from a data provider. It works using event listeners as you can see here:
https://api-platform.com/docs/core/events/

When you take a look at custom controllers here: https://api-platform.com/docs/core/operations/#creating-custom-operations-and-controllers you'll see that the entity is passed to the controller/action.
