### ISSUE TITLE
Custom identifiers, no identifier and identifier loaders

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#227]
## Custom identifiers, in a non-Doctrine context.

Since #125, we have potential extension points for loading and defining what represents the identifier in a class.
Something that would have been great, is having a simple property annotation allowing to define which property is the identifier in the class.

Regarding:
> The possibility to add an annotation to set our custom idenfier manually without doctrine was removed from this PR and moved in another future PR. Because it imply other changes ... in DataProvider fro example (cant use Doctrine getReference ... DataProvider is really doctrine linked)

I'm not sure I understand the issue, because custom identifiers are not only something needed in the Doctrine context. 

## Custom (identifier) loaders

On a second hand, currently, we cannot easily add our own loader in the `LoaderChain`, except using a compiler pass. Is it a sufficient workflow or should we expose more convenient ways to extend this part ?

## ValueObject & no identifier
Last but not the least: as stated in https://github.com/dunglas/DunglasApiBundle/issues/202#issuecomment-129460564:
> Also, we should be able to expose resources which do not have an ID. This would be the case for value objects, which may be used for some custom operations.

It's currently impossible, as we get the following exception:
> The class "AppBundle\ValueObject\Foo" has no identifier. 

A real identifier property  does not make any sense for such objects (meant to be used to submit custom payloads with the POST http verb for instance). 
But if we really need to have an identifier in ClassMetadata, what about using the same annotation as mentioned above, but on the class, with a `value` property (default: classname) ?

**Comment by dunglas** [comment]
How a resource can have an IRI if it has no identifier (value object)?

**Comment by ogizanagi** [comment]
The point is, to me, that such resources won't need an IRI (but should still appear in the `/apidoc`), as it only represents custom payloads for operations.

But I'm clearly not an expert of the Json-ld and Hydra vocab, and fail to understand the specifications on many points. My real aim behind this issue is to gather feedbacks and suggestions on how to proceed (and what changes in the bundle would be needed) in order to expose:
- Custom operations with a given payload, fully documented in the Nelmio api doc and in the `/apidoc`/`contexts` using jsonld & hydra vocab:
    - Custom Api Operations might be perfect, except the generated documentation is wrong (#202), as we cannot specify the resource acting as payload.
    - Exposing directly value object as resources isn't a solution either, as it actually fails because of the missing identifier, and no GET operations (https://github.com/dunglas/DunglasApiBundle/pull/205#issuecomment-131016319).
- Non-Doctrine resources with a custom identifier (add an identifier loader / generic `@Api\Identifier` annotation).
- Non-resources objects with no identifiers in general (there are already some issues about it: #166, #181).

**Comment by teohhanhui** [comment]
I don't think it's necessary for a resource to have an IRI if it's only embedded in another resource, e.g. [QuantitativeValue](https://schema.org/QuantitativeValue)

**Comment by dunglas** [comment]
V2 is now able to deal with non-resource objects.
