### ISSUE TITLE
POST operation should return a body according to swagger, but they don't

### ISSUE THREAD

**Issue by Soullivaneuh** [api-platform/core#2276]
On a simple POST resource, without modification regarding the body response, I have this generated doc:

![image](https://user-images.githubusercontent.com/1698357/47443939-ae697780-d7b5-11e8-8a39-2ca56ef35e89.png)

So I should have the created object on the response. But when I try, I got nothing:

![image](https://user-images.githubusercontent.com/1698357/47443976-bc1efd00-d7b5-11e8-9d70-08495d9766a9.png)

I don't know what should be the default behavior, but one of the two sides is wrong.

**Comment by Soullivaneuh** [comment]
The called controller is `api_platform.action.post_collection`, alias of `ApiPlatform\Core\Action\PlaceholderAction`.

**Comment by silverbackdan** [comment]
OK so it probably is the event listeners creating the output (which is how API Platform is designed).

Can you replicate this on a new installation of API platform that you can share the repo for? You don't have any listeners that may override the output do you?

**Comment by Soullivaneuh** [comment]
ATM I'm still working on the API platform integration. I'll do it when I will go back to this issue. :+1:

**Comment by Soullivaneuh** [comment]
It seems to be a serialization issue: https://github.com/api-platform/core/blob/b6898f3958b74e95c4550e91a87105cdfa5874a8/src/EventListener/SerializeListener.php#L72

`$controllerResult` contains my data, but the serializer returns nothing.

Still investigating.

**Comment by Soullivaneuh** [comment]
Ok so the serialization group is wrong. But I don't think it's a direct api-platform issue as the serialization group building is on my own side. Closing.
