### ISSUE TITLE
PUT custom item operation should not have a body as default on documentation

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2296]
If I create a custom PUT item operation:

```
 *         "validate" = {
 *             "method" = "PUT",
 *             "path" = "/ssl_certificates/{id}/validate",
 *             "controller" = SslCertificateValidate::class
 *         }
```

The documentation will add the model description as body parameter, same as classic PUT operation.

If the operation is custom, I don't see why this body should be automatically added.

Am I right?

**Comment by dunglas** [comment]
It will change with #2235, but currently it's expected that even a custom controller will return the an instance of the resource class. If it's not the case, you have to update the Swagger doc "by yourself".
Maybe does it deserve more documentation.
