### ISSUE TITLE
openApi 3.0.0 DocumentationNormalizer 

### ISSUE THREAD

**Issue by piotrbrzezina** [api-platform/core#2297]
Hi...

I wonder if you consider change from swagger 2.0 to openApi 3.0.0

openapi 3.0.0 gives as a bunch of additional field type and more flexibility. In my case I  care about the functionality of oneOf (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/)

What do you think about that ?

**Comment by dunglas** [comment]
It would be awesome. A PR would be very appreciated.
However we should support both formats,l (not only 3.0) because a lot of tools still don’t support 3.0.

**Comment by dunglas** [comment]
Support for OpenAPI v3 is now in master: https://github.com/api-platform/core/pull/2302
