### ISSUE TITLE
Importing resource config from another bundle

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#2299]
I'm creating a bundle with a whole load of other resources, but I want these to be optional.

Right now API Platform parses mapping paths as simple file paths. If I raise a PR to parse these in a similar way to how Symfony routes can be imported (e.g. @AcmeBundle/Resources/config/api-platform/all.xml) would you be willing to merge it?

Thought I'd ask before rushing into it.

Thanks.

**Comment by silverbackdan** [comment]
Thanks - I will hopefully get a PR in later this evening.

**Comment by RSalo** [comment]
There is no need for PR. I had the same problem because my resource placed in the wrong place. Just place your resource in bundle path "$dirname/Resources/config/api_resources.yaml". https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L294
This issue may be closed.

**Comment by silverbackdan** [comment]
Hi @RSalo - this is more for a re-usable bundle that you'd include in your own project. For example in the bundle I may want to give lots of optional resources, that way someone using the bundle could reference just the configs that they want to, or easily omit some of the resource metadata to define it (override defaults). Currently it'll just automatically map in all the resources defined in every bundle... I think unless things have changed since I raised this. (Sorry this issue is embarrassingly old, I must find time to review).

**Comment by necobm** [comment]
Hi every one, I have a similar issue/need. I have an Abstract Resource A, and children resources B, C, D, and I have the Resources specifications defined into separated YAMLs. So, I need to reuse the "attributes" and "properties" specification part of resource A YAML, into resources B, C, D, that way, if in the future I add or change fields or properties into resource A, I have only change the resource configuration in one place: resource A YAML file.

What about that PR that @silverbackdan commented earlier.

Regards.

**Comment by soyuka** [comment]
definitely
