### ISSUE TITLE
Creating custom mutations GraphQL

### ISSUE THREAD

**Issue by Giant-Jelly** [api-platform/core#2309]
Im trying to create a custom authentication mutation with GraphQL but cant find any explanation saying how to do that?

Can someone point me in the right direction? Im happy to update the documentation with an example etc afterward.

**Comment by alanpoulain** [comment]
Sorry, it's not possible nowadays. The GraphQL part of API Platform needs to be modified in order to allow it.

**Comment by Giant-Jelly** [comment]
Oh I see, any plans on making this possible? I think its pretty likely that this is needed in most projects as it doesnt take long before the complexity grows past the standard functionality

**Comment by leyriel** [comment]
Hello, i have a same probleme. Can i do a relationship mutation (like one to many) in graphQL request ?

**Comment by serviware** [comment]
i create custom mutations with [data persisters](https://api-platform.com/docs/core/data-persisters/)

**Comment by alanpoulain** [comment]
Custom mutations can be done in master: https://api-platform.com/docs/master/core/graphql/#custom-mutations
