### ISSUE TITLE
Filter custom name

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2310]
According to the documentation, I can set a custom name for an order filter, but not a classic search filter.

It would be great to be able to do this.

Example:

```php
/**
 * @var Os|null
 *
 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Os", inversedBy="servers")
 * @ORM\JoinColumn(referencedColumnName="id", nullable=true)
 * @Groups({"get", "post:admin", "put:admin"})
 * @ApiFilter(SearchFilter::class, strategy="exact",
 *     properties={
 *         "os.name"
 *     })
 */
private $os;
```

This will give me the `os.name` filter. It is working, but not very user friendly nor useful for the API end user.

I would like to name this filter simply `os`.

It is not currently possible if I am right.

**Comment by Soullivaneuh** [comment]
Any feedback about the idea?

**Comment by soullivaneuh** [comment]
Am I the only one of this planet to have this need? :upside_down_face:

**Comment by julienfalque** [comment]
You're not 😊, I made a similar proposal recently: #3606. I didn't know about yours, maybe we can close mine as duplicate.

**Comment by soyuka** [comment]
Let's follow this at https://github.com/api-platform/core/issues/3606
