### ISSUE TITLE
Swagger put a required id parameter on a route without any parameter

### ISSUE THREAD

**Issue by Soullivaneuh** [api-platform/core#2312]
With this special "current" operation:

```php
 * @ApiResource(
 *     collectionOperations={
 *         "get"
 *     },
 *     itemOperations={
 *         "get",
 *         "current" = {
 *             "method" = "get",
 *             "path" = "/user",
 *             "controller" = UserCurrent::class,
 *             "defaults" = {
 *                 "_api_receive" = false
 *             },
 *             "swagger_context" = {
 *                 "summary" = "Retrieves the currently authenticated user."
 *             }
 *         }
 *     }
 * )
```

I have to provide an id parameter.

![image](https://user-images.githubusercontent.com/1698357/48006132-70edde00-e115-11e8-80a9-e08c5d4ca97f.png)

And this one is never used on "trying mode".

**Comment by antograssiot** [comment]
@Soullivaneuh adding `"parameters"={}` to your `swagger_context` attribute should do the trick

**Comment by Soullivaneuh** [comment]
@antograssiot I did an another workaround with the swagger decorator.

Yours could work, but it will remove any parameter, any if we had legitimate ones.

**Comment by antograssiot** [comment]
You can define any legitimate parameter using this attribute too.
Whatever is in this attribute will be used, and is [documented here](https://api-platform.com/docs/core/swagger#changing-operations-in-the-swagger-documentation)
Closing as solved anyway, thanks for your feedback
