### ISSUE TITLE
Quick Clarification on DataProviders for subresources

### ISSUE THREAD

**Issue by theshaunwalker** [api-platform/core#2321]
Not necessarily bug but a case of either missing documentation or unexpected behaviour. 
Apologies if I'm missing something but I cant find anything in documentation or existing issues that match my thinking.

Would appreciate anyone with subresources experience to shed some light on this.

My scenario:
I use API Entities as plain DTOs, I dont use doctrine at the API Platform layer, my intention is to have a custom data provider/persister mapped to every action and have API Platform essentially only responsible for the HTTP layer and serializing/deserializing request/responses.

**Assumption:**
DataProviders/DataPersisters are used as a native method to provide custom methods of providing/persisting data for Entities.
My assumption would be that this would be a standard pattern for how to provide/persist entities wether they are top level resources or subresources.

**Reality:**
From what I've seen in my findings, DataProviders (not looked at Persistance side of things yet) are not used at all for subresources.
And the only way to map a custom method of providing an Entity that is a subresource, is a Controller action.

ie. GET /user/123/messages triggers neither the User nor Message data provider.

**Question:**
I want to have a custom Provider/Persister for subresources, is the only way to achieve this via a controller action? (ignoring kernel events)

Many thanks for any help I dont like creating github issues for simple queries but I've just hit a brick wall with trying to debug if custom DataProviders are even part of the equation with subresources.

**Comment by theshaunwalker** [comment]
Closing as the clarification is essentially:

Resources, wether they are root `/users` or subresources `/company/1/users` are sent to the same data provider. So its the data provider's responsibility as far as I can tell, to identify its a subresource call, and manage the query accordingly.

**Comment by hizagi** [comment]
I LOVE YOU, can't this be added to the official documentation?
