### ISSUE TITLE
Add configuration to define two identifier but with OR condition

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2324]
For example, add the possibility to add identifiers to `$id` and `$name` properties, but not consider them as composite identifier.

In that case, APIP will look at the `$id` first, then `$name`.

Related to #2323 debate.

**Comment by soyuka** [comment]
#2126 maybe?

**Comment by Soullivaneuh** [comment]
@soyuka Not sure. Here is a concrete case:

```php
class Server
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups("gets")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64, unique=true)
     * @Groups({"gets", "post:admin"})
     * @ApiFilter(SearchFilter::class, strategy="partial")
     */
    private $name = '';
}
```

I would like APIP to search on `$id` first, then on `$name` but not both combined.

`/api/servers/1` should work.
`/api/servers/ns42442` should work too.

If your PR is resolving this need, so yeah it can close this issue. :+1:

**Comment by soyuka** [comment]
I figured out better and I have to be :-1: because this is not good practice, an identifier should be unique. In this case I'd only use the `$name`.

**Comment by Soullivaneuh** [comment]
> because this is not good practice

Maybe. But customer need does not always fit the best practice. Both are needed here.

I can understand if you won't make it native, I will be okay with my custom data provider then. :+1:

**Comment by norkunas** [comment]
This is a common case when you generate slugs for resources..

But I've solved this with another solution without need to create data provider:

```
<?php

declare(strict_types=1);

namespace App\EventSubscriber\Company;

use ApiPlatform\Core\EventListener\EventPriorities;
use App\Entity\Company;
use App\Repository\CompanyRepository;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class ResolveIdFromSlug implements EventSubscriberInterface
{
    private $repository;

    public function __construct(CompanyRepository $companyRepository)
    {
        $this->companyRepository = $companyRepository;
    }

    public function resolve(GetResponseEvent $event): void
    {
        $request = $event->getRequest();

        if (!\in_array($request->attributes->get('_route'), ['api_companies_get_item', 'api_companies_put_item', 'api_companies_delete_item'], true)) {
            return;
        }

        $identifier = $request->attributes->get('id');

        if (\ctype_digit($identifier)) {
            return;
        }

        $company = $this->companyRepository->findOneBySlug($identifier);

        if (null !== $company) {
            $request->attributes->set('id', $company->getId());
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => ['resolve', EventPriorities::PRE_READ],
        ];
    }
}
```

**Comment by soyuka** [comment]
You could also avoid the slug query here by using the identifier denormalizer + https://github.com/api-platform/core/pull/2323#issuecomment-438282483

**Comment by norkunas** [comment]
> You could also avoid the slug query here by using the identifier denormalizer + [#2323 (comment)](https://github.com/api-platform/core/pull/2323#issuecomment-438282483)

Thanks, will check it.

**Comment by teohhanhui** [comment]
Also -1 here for the same reasons.
