### ISSUE TITLE
Property alias

### ISSUE THREAD

**Issue by Soullivaneuh** [api-platform/core#2332]
Like this:

```php
/**
 * @ApiProperty(alias="foo")
 */
private $status;
```

Then the property will be used as `foo` on the API.

WDYT?

**Comment by dunglas** [comment]
Not necessary anymore, it has been fixed in Symfony directly: https://github.com/symfony/symfony/pull/28505

**Comment by Soullivaneuh** [comment]
Looks awesome! Will test it immediately.

**Comment by Soullivaneuh** [comment]
@dunglas Are the modifications done in framework-bundle mandatory? https://github.com/symfony/symfony/commit/d1d1ceb38e171132b6d13e19cd5576bd0dc85cd8#diff-0e793081ceb720201745c982a568903fR1366

I would like to update only the serializer, but the framework force me to update nearly the whole symfony dependencies. :-|

**Comment by dunglas** [comment]
I think they are

**Comment by Soullivaneuh** [comment]
@dunglas I finally success my upgrade and tried:

```php
namespace App\Entity;

use AppBundle\Enum\Status;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

trait StatusTrait
{
    /**
     * @var int
     *
     * @ORM\Column(type="smallint")
     *
     * @SerializedName("toto")
     * @Groups("gets")
     */
    private $status = Status::CREATE;

    final public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    final public function getStatus(): int
    {
        return $this->status;
    }
}
```

But I still have `status` on the json response. Did I miss something?

**Comment by Soullivaneuh** [comment]
So I tries this on `AttributeMetadata`:

```php
/**
 * {@inheritdoc}
 */
public function setSerializedName(string $serializedName = null)
{
    dump($serializedName, $this);
    $this->serializedName = $serializedName;
}

/**
 * {@inheritdoc}
 */
public function getSerializedName(): ?string
{
    dump($this->serializedName, $this);
    return $this->serializedName;
}
```

And the getter is never called.

So I suppose this is why I don't have any converted name. But I don't know why it is not called.

**Comment by Soullivaneuh** [comment]
`MetadataAwareNameConverter::normalize` is never used, this is why. Why it's never used? Answer in next episode. \o/

**Comment by Soullivaneuh** [comment]
Ok I found why and I think some modification have to be done on api-platform.

The issue is the name converted set on framework bundle is not passed directly on the normalizer but on the metadata aware name converter: https://github.com/symfony/symfony/pull/28505/files#diff-0e793081ceb720201745c982a568903fL1366

But, in api-platform, you still copy the "old" method for your normalizers: https://github.com/api-platform/core/blob/d67848110778af711c5f54226fe1234ec5668230/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L77-L79

IMHO, the `name_converter` option should be deprecated (or is it used for something else?) and the `serializer.name_converter.metadata_aware` should be passed if exists.

The current workaround of this issue is quite simple, just add this line on the `api_platform` configuration:

```yaml
api_platform:
    name_converter: serializer.name_converter.metadata_aware
```

**Comment by Soullivaneuh** [comment]
Another issue: The documentation generator ignore the annotation.

**Comment by bendavies** [comment]
nice debugging.

**Comment by Soullivaneuh** [comment]
Thanks @bendavies ! :+1: 

I divided this problem onto two issues:

-  https://github.com/api-platform/core/issues/2342
- https://github.com/api-platform/core/issues/2343
