### ISSUE TITLE
Handle id and uuid with api platform

### ISSUE THREAD

**Issue by rockyweng** [api-platform/core#2338]
Just wondering if I am able to use API platform to handle the following table structure. 
```
student
--------------
- id - auto increment - primary key
- uuid - string 
- name
- department_id
```

```
department
--------------
- id - auto increment - primary key
- uuid - string 
- name
```

I would like to use api platform to achieve the following with ApiSubresource:

GET /api/student/{uuid} 

Response
```
{
  "uuid": "a1590004-f74b-4a10-93f0-27f17c370058",
  "name": "student1",
  "department": "/api/department/a2122004-f74b-4a10-93f0-27f17c370058"
}
```

Thanks.

**Comment by bendavies** [comment]
I do something similar. 
Try annotating your ID with `@ApiProperty(identifier=false)` and the uuid with `@ApiProperty(identifier=true)`

**Comment by rockyweng** [comment]
Thanks @bendavies . Your approach is working.
