### ISSUE TITLE
How to inject custom graphql type

### ISSUE THREAD

**Issue by epourail** [api-platform/core#2340]
I am using a data type object to handle the translations of a property (this DTO is used within an @ApiResource entity)
The REST endpoint is used to set/write the translations (as an array of lang/value)
The graphql endpoint is used to request the translated property, according the `Accept-Language` http header, which will be returned as a string. 

Here my DTO : 
```
/**
 * Class I18n
 * @package App\DataTypeObject
 *
 * @ApiResource(
 *     shortName="I18n",
 *     attributes={
 *         "denormalization_context":{"groups":{"0":"WRITE_I18N"}},
 *         "normalization_context":{"groups":{"0":"READ_I18N"}}
 *     },
 *     itemOperations={"get"},
 *     collectionOperations={}
 * )
 *
 * @ORM\Entity()
 */
class I18n implements DTOInterface
{
    private $fr;

    private $en;

    /**
       getters and setters
    */
}
```

My issue is to avoid to declare 2 properties (one to handle the translations via my `I18n` class and the other one to return a `string` translated), 

The solution found is to handle the DTO as a string (on the graphql endpoint) : 
  - via a custom graphql type :

```
/**
 * Class I18nType
 */
final class I18nType extends StringType
{
    /**
     * I18nType constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->name = 'I18n';
        $this->description =
            'The `String` scalar type represents textual data, represented as UTF-8
character sequences. The `I18n` type represents the translated text of a multilanguage field.';
    }
}
```
  - inject this type at the schema creation (in the schema builder). I need to use reflection  in a decorated `SchemaBuilder`

```
class SchemaBuilder implements SchemaBuilderInterface
{
    /**
     * @var SchemaBuilderInterface $decorated
     */
    private $decorated;

    /**
     * SchemaBuilder constructor.
     * @param SchemaBuilderInterface $decorated
     * @throws \ReflectionException
     */
    public function __construct(SchemaBuilderInterface $decorated)
    {
        $this->decorated = $decorated;

        $reflection = new \ReflectionProperty(
            \get_class($this->decorated),
            'graphqlTypes'
        );
        $reflection->setAccessible(true);

        $graphqlTypes = $reflection->getValue($this->decorated);
        $graphqlTypes['I18n'] = new I18nType();
        $reflection->setValue($this->decorated, $graphqlTypes);
    }

    /**
     * @inheritdoc
     */
    public function getSchema(): Schema
    {
        return $this->decorated->getSchema();
    }
}
```
  - in my graphql normalizer, I return a string when a i18n-class property is defined.

Is there a another/better solution ?
It will be a nice feature, to allow to define a custom graphql type to update the behavior of a DTO on the graphql endpoint.

**Comment by alanpoulain** [comment]
It could be interesting to have a method in the `SchemaBuilderInterface` to add a new type, but the `convertType` method will also need to know when and how to convert your property. Not sure if it can be done easily.

**Comment by epourail** [comment]
Note : in my `I18nType` class, I tried to override the `parseValue` and `parseLiteral` methods to try to handle the type behavior but there were never called.

**Comment by alanpoulain** [comment]
Documentation about using custom types can be found here: https://api-platform.com/docs/master/core/graphql/#custom-types
