### ISSUE TITLE
[Bug] If annotations are disabled, AnnotationFilterPass shouldn't be invoked

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#2345]
If you set `framework.annotations: false`, AnnotationFilterPass shouldn't be run at all since this produces an error:

https://github.com/api-platform/core/blob/28eb702af9a63cf09153c974d969d9f17d7a2fcc/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php#L45

**Comment by soyuka** [comment]
We'll remove/deprecate annotations from 3.0 but this should be fixed lol.
