### ISSUE TITLE
BC Break: IdentifierConverter adds nested 'id' property

### ISSUE THREAD

**Issue by Matth--** [api-platform/core#2349]
I have a SubresourceDataprovider that uses the identifier to perform a query.
The result in v2.2.9 on the `array $identifiers` was

```php
[
    ['id'] = 25
]
```

When upgrading to 2.3.* the `ApiPlatform\Core\Identifier\IdentifierConverter` class (called in `ApiPlatform\Core\DataProvider\OperationDataProviderTrait` converts every id to an extra nested array so the `array $identifiers` argument on the getSubresource method in my SubresourceDataprovider has been changed to:

```php
[
    ['id'] = [
        ['id'] = 25
    ]
]
```

**Comment by soyuka** [comment]
This should be added to the changelog I think.

**Comment by Matth--** [comment]
Could be done (changed my dataprovider for now) but I think it is weird to nest the id further down as we know that there is only one id passed to a `SubresourceDataprovider`.

**Comment by soyuka** [comment]
This comes from the subresource implementation and the work on normalizing identifiers between data providers. By the way there can me more then one identifier for a subresource. Glad you fixed it and sorry about that!
