### ISSUE TITLE
Search filter: configure at query level rather than definition level

### ISSUE THREAD

**Issue by ymarillet** [api-platform/core#2351]
Hey there,

Sharing a thought again. The current implementation of the SearchFilter forces to define one but only one specific search strategy for a property among exact, partial, start, end, word_start (and their insensitive variant).

Problem is we cannot have 2 or more of these strategies available for query. Thus it would be, imho, faily easy to achieve that with the same behaviour as the DateFilter.

The implementation could still define a strategy which could be the default strategy to apply.

Example with a SearchFilter configured on a prop named "city" with strategy "exact":
?city=amsterdam
?city[exact]=amsterdam //same effect as previous line
?city[start]=new
?city[end]=york
?city[partial]=ris
etc.

**Comment by soyuka** [comment]
There is definitely work to be done to improve how filters work. My advice here is to build your own filter, you could try to re-use some of our code to build queries.

**Comment by ymarillet** [comment]
What's the plan concerning the filters system ? Is it worth working (I mean contributing) on this enhancement as-is on the current system ?

**Comment by soyuka** [comment]
I'm not sure that what you have in mind is easy to implement on top of the current search filter especially if you want to avoid breaking things.

**Comment by soyuka** [comment]
closing in favor of #2400
