### ISSUE TITLE
Missing route returns Symfony Twig HTML exception template

### ISSUE THREAD

**Issue by theshaunwalker** [api-platform/core#2352]
Hi,

Trying a route/method not setup as a route in symfony returns the standard Twig HTML exception page.

I would expect an API format response, JSON or whatever API Platform is configured to.

I couldnt find any existing issues or reference to it in the documentation.

Is this standard behaviour in dev mode?  Does switching to production mode enable my expected behaviour? Or am I just missing some configuration?

Many Thanks.

**Comment by ersin-demirtas** [comment]
Hi @theshaunwalker, 

There is good documentation on https://api-platform.com/docs/core/errors/#errors-handling, I think you need to check if you are passing the right headers to get JSON response. 

The example below should return JSON respose with header accept : application/ld+json
`curl -X GET "https://api.aqkwa.co.uk.test/api/v1/auditable_events" -H "accept: application/ld+json"`


Addtional info for configuring error formats:
https://api-platform.com/docs/core/configuration/
