### ISSUE TITLE
Graphql: issue with complex virtual properties 

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#2356]
Hello!
I have the following problem: say my entity has method `getObjectValue()`, which returns virtual object-value (it's not reflected in DB and even it's not a property of entity) with several nested levels something like this:
```
[
        {
          "actualValues": {
            ...
            "product": {
              "id": 458
            }
          },
          "minimalValues": null,
          "violation": {...},
          "violated": false
        }
]
```
I noticed that here you initialize context attributes: https://github.com/api-platform/core/blob/822c78c946db1fc037eaf6e11a2b2faaa023b72b/src/GraphQl/Resolver/ItemResolver.php#L63 
So after this my serialization context becomes equal to `["attributes": ["objectValue"] ]` ("objectValue" attribute taken from method name) and because of this my nested object will be serialized to empty array without of any internal content (because internal fields are not in attributes list).
If I remove this logic, my context remains empty and my object-value returns fine.

Am I doing smthg wrong or it's a bug?

**Comment by Siregacvek** [comment]
By the way this is a problem when I use [json-odm](https://github.com/dunglas/doctrine-json-odm) package together with api-platform - by default the object, saved to json field, wouldnt be returned properly in api-platform.

So I used [this approach](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis) to extend `context['attributes']` and this solved my problem.
