### ISSUE TITLE
[Question] VichUploader file URL

### ISSUE THREAD

**Issue by kl3sk** [api-platform/core#2362]
Hello,

I implement VichUpload as the [Doc says](https://api-platform.com/docs/core/file-upload/) and it work as expected.

Now I want to retrieve my resources with their downloadable URL. How can I achieve that ?

Nota:
I use the `vich_uploader.namer_directory_current_date_time` service.

thanks for you help

**Comment by soyuka** [comment]
Isn't [this](https://api-platform.com/docs/core/file-upload/#linking-a-mediaobject-resource-to-another-resource) what you look for? Please try to ask your question on the symfony slack (api platform channel).

**Comment by kl3sk** [comment]
Hello,

thank you for your answer but this is not. This returns the `iri`, what I want(ed) is the web path.

In fact this is not the good solution for me, because in this case all `mediaObject` have a public direct access.
Instead I've made a controller that serve them and coul'd be catch by Symfony firewall.

**Comment by teohhanhui** [comment]
Indeed, the documentation does not do that correctly. In the example, it returns the plain path as the `contentUrl`, which is of course quite useless. Usually, what you'd want is the URL, as you've mentioned.

Perhaps you could do that in a [normalizer](https://api-platform.com/docs/core/content-negotiation/#writing-a-custom-normalizer), by using [StorageInterface::resolveUri](https://github.com/dustin10/VichUploaderBundle/blob/7a115e5f2e4697f434b1eb4f564ca4c74191b0ba/Storage/StorageInterface.php#L44-L53). And help us improve the docs for file upload.
