### ISSUE TITLE
Support inclusion of resources from a path according to JSON:API spec

### ISSUE THREAD

**Issue by dematerializer** [api-platform/core#2365]
Although [Inclusion of Related Resources](https://jsonapi.org/format/#fetching-includes) was partly implemented in #1949 as requested by #1934, unfortunately support for inclusion of resources from a path was not implemented. Would it be possible for this to be supported as well?

The following already works as expected (comments are included in the response):

```
GET /articles/1?include=comments HTTP/1.1
Accept: application/vnd.api+json
```

This doesn't work (neither comments nor authors are included in the response as they should be according to the spec):

```
GET /articles/1?include=comments.author HTTP/1.1
Accept: application/vnd.api+json
```

**Comment by thomasdom** [comment]
The implementation of this enhancement would add a huge performance improvement for apps with a server using API Platform with JSON:API

**Comment by tonymrakovcic** [comment]
Any ideas on this?
This would be a great improvement

**Comment by simonihmig** [comment]
We (specifically @andreasschacht) have been working on this recently, and got it working in our app (with some overridden services). We just need to find the time to properly integrate the changes (mainly tests!) upstream here. I hope we can file a PR next week, or the week after!?
