### ISSUE TITLE
Using ApiBundle with symfony (standalone)

### ISSUE THREAD

**Issue by kazeichev** [api-platform/core#2369]
Hi! I have sn existing Symfony 3 project and I want to inject only API Component from your platform to my project. I have some problems with installation. Well, I've done:
1. `composer require api-platform/api-pack`
2. In my User entity, I add following `/** ...  @ApiResource ... */`
3. After it, I try to access api endpoint: `https://myurl.com/api` and I have a 404 error. 
What's wrong? 
Sorry for so stupid question $(

**Comment by soyuka** [comment]
Did you start the server? Please check the symfony official slack, someone will definitely be able to help you there. I'm closing this because this issue tracker should be used for bug not support, thanks for your consideration.
