### ISSUE TITLE
PropertyFilter not exposed as collection

### ISSUE THREAD

**Issue by idsplus-carlos** [api-platform/core#2370]
When applying PropertyFilter to an Entity, properties is exposed as a simple string, whereas it should be a string collection. As of now implementation is broken, ie, you can't ask for more than one property if one were to adhere to the documentation.

It's now detailed in the documentation as:
`{"name":"properties[]","in":"query","required":false,"type":"string"}`

Should be:
`{"name":"properties[]","in":"query","required":false,"type":"array","items":{"type":"string"},"collectionFormat":"multi"}`

**Comment by antograssiot** [comment]
PR has been merged

**Comment by idsplus-carlos** [comment]
Hi @antograssiot , sadly it's still happening with 2.3.6.
It seems when or after merging the PR, a swagger description was added to the field. However, that description also includes the name of the property, but it's incorrectly typed. Right now reads as follows:
`'name' => $this->parameterName,`
should be:
`'name' => $this->parameterName.'[]',`

Current implementation causes swagger to send the property as "properties" instead of "properties[]" thus preventing PHP from processing it correctly.

Should i open a new bug or we're good reopening the current one?
