### ISSUE TITLE
Perstister strange behavior with an error "Unable to generate an IRI for the item of type"

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2373]
If i add this Persister i get an error patching a Document with DocumentArticles.

The error:
Unable to generate an IRI for the item of type "App\Entity\Client\DocumentArticle"

If i remove the Persister all works fine.

Here is my Persister:

```
final class TestPersister implements DataPersisterInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function supports($data): bool
    {
        return true;
    }

    public function persist($data)
    {
        return $data;
    }

    public function remove($data)
    {

    }
}
```

**Comment by soyuka** [comment]
It is because you didn't create an identifier while persisting. For example:

```
$data->id = 0;
```

**Comment by do-web** [comment]
mh ok after i make this:

`
    public function persist($data)
    {
        $this->em->persist($data);
        $this->em->flush();

        return $data;
    }
`

it worked
