### ISSUE TITLE
Can't enable Pagination with CollectionDataProvider

### ISSUE THREAD

**Issue by guilhemVB** [api-platform/core#2390]
Hello,

I use an external API to find and expose Data in my API. I use a CollectionDataProvider to do that (as explained here : https://api-platform.com/docs/core/data-providers/#data-providers). The external API provide a pagination system and the number of items, so its perfect but I don't know how to enable the pagination. Could you please help me ? :)

This is my CollectionDataProvider : 
```
final class InvoiceCollectionDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface
{
    /** @var LoggerInterface */
    private $logger;

    /** @var GuzzleService */
    private $guzzleService;

    public function __construct(GuzzleService $guzzleService, LoggerInterface $logger)
    {
        $this->guzzleService = $guzzleService;
        $this->logger = $logger;
    }

    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return Invoice::class === $resourceClass;
    }

    public function getCollection(string $resourceClass, string $operationName = null): \Generator
    {
        try {
            $list = $this->guzzleService->listInvoices();
            $totalNumberOfItems = $this->guzzleService->getTotalNumbeOfItems();
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
            $list = [];
            $totalNumberOfItems = 0;
        }
        foreach ($list as $item) {
            yield $item;
        }
    }
}
```

As explained in the documentation, I tried to inject $collectionExtensions in the Provider, but I don't know how to use it :/
```
    App\DataProvider\InvoiceCollectionDataProvider:
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
```

Thanks alot,

Guilhem

**Comment by norkunas** [comment]
Integrated collection extensions are for Doctrine, you should do the pagination yourself, by reading the provided page by user from the request query and passing it to the external api

**Comment by guilhemVB** [comment]
Thank you for your answer. That's I understood, I have to build the pagination by mayself, but I don't understand how to do that :/

**Comment by norkunas** [comment]
I'd suggest you to open PaginationExtension and just try to copy some parts of it's functionality, like reading itemsPerPage attribute from the request and then just pass that attribute value to your 3rd party api :)
