### ISSUE TITLE
metadata_factory.cached depends on Doctrine

### ISSUE THREAD

**Issue by benr77** [api-platform/core#2394]
I'm trying to set up ApiPlatform without Doctrine, loading all data from ElasticSearch via custom Data Providers.

However, when trying to clear the Symfony cache I'm getting the following error:

`The service "api_platform.metadata.property.metadata_factory.cached" has a dependency on a non-existent service "doctrine". `

This is obviously because I've removed Doctrine from the project, but how can I stop this error?

**Comment by soyuka** [comment]
It's weird we don't have [any dependencies to doctrine](https://github.com/api-platform/core/search?q=path%3Asrc%2FBridge%2FSymfony%2FBundle%2FResources%2Fconfig%2Fmetadata+doctrine&unscoped_q=path%3Asrc%2FBridge%2FSymfony%2FBundle%2FResources%2Fconfig%2Fmetadata+doctrine) there :|.

**Comment by benr77** [comment]
If I disable the bundle, the cache clears just fine. Re-enabling the bundle and again I get this message when I clear the cache.

I then removed `composer remove api-platform/api-pack` followed by `composer remove api-platform/core` and the error is now gone. The pack does include Doctrine so figure that was the problem.

**Comment by soyuka** [comment]
Yeah indeed, then the configuration finds out the class exists and tries to load doctrine. Nice that you found out a solution.
