### ISSUE TITLE
@id IRI and @type do not show up in response

### ISSUE THREAD

**Issue by mcbuckets** [api-platform/core#2397]
I have two entities exposed by `@ApiResource` annotation. However, one of them has `@id` and `@type` in GET collection response the other one doesn't. Configuration seems identical.

```
{
  "@context": "/api/contexts/Keywords",
  "@id": "/api/keywords",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "id": "0006e6e0-d6cb-43d6-ac0e-ec6f486aa3c3",
      "keyword": "keyword",
      "created": "2018-11-29T21:21:28+00:00",
      "modified": "2018-11-29T21:21:28+00:00"
    },
      ...
   ]
}
```
This is what i get on calling `/api/keywords` with GET request. Why is there no IRI?

The configuration is as follows:

```
/**
 * Keywords
 *
 * @ApiResource(
 *     itemOperations={
 *          "get",
 *          "get_combine_keywords"={
 *              "method"="GET",
 *              "path"="/keywords/{id}/combine",
 *              "controller"=KeywordsCombine::class
 *          }
 *      },
 *     collectionOperations={
 *          "get"={
 *              "method"="GET",
 *              "attributes"={
 *                  "normalization_context"={"groups"={"keywords","flatten"}}
 *              }
 *          }
 *      }
 * )
 * @ApiFilter(GroupFilter::class, arguments={"parameterName": "groups", "overrideDefaultGroups": false})
 * @ORM\Table(name="keywords")
 * @ORM\Entity
 */ 
```

**Comment by hictao** [comment]
I have the same problem did you find the source of the problem ?

**Comment by mcbuckets** [comment]
@hictao try putting the `id` in normalization group

**Comment by hictao** [comment]
Thank you for your response I found another cause of my problem

**Comment by mcbuckets** [comment]
@hictao feel free to share your solution. Maybe it helps somene

**Comment by hictao** [comment]
@mcbuckets my problem was related to my custom serializer, it was decorating 
`api_platform.serializer.normalizer.item`
instead of
`api_platform.jsonld.normalizer.item`

**Comment by antograssiot** [comment]
looks resolved.
feel free to reopen it if not.
