### ISSUE TITLE
Search on date values

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#241]
Let's say I have the following values for a date property:
* first value: `2015-04-28T02:23:50+00:00`
* second value: `2015-04-28T02:23:50+00:10`

Since I know the exact values, will would use the search filter with the exact string `2015-04-28T02:23:50+00:00`. But this will not work since the PHP value retrieved in the filter will be `2015-04-28T02:23:50 00:00` and not `2015-04-28T02:23:50+00:00`, so it is currently impossible to get only one of the two value...

**Comment by teohhanhui** [comment]
Using the search filter for matching dates is just such a bad idea (it should not be done, even if it's possible).

**Comment by dunglas** [comment]
I agree with @teohhanhui. A dedicated filter for date is a better way.

**Comment by teohhanhui** [comment]
Why not add more operators to the date filter?

- equal
- less than or equal
- greater than or equal

(Not so sure if this makes sense because time is supposed to be non-discrete...)

Alternatively, just use `before` and `after` with values of 1 second difference.

**Comment by theofidry** [comment]
There was a little error, for the input `2015-04-28T02:23:50+00:00` the PHP value received is `2015-04-28T02:23:50 00:00` (without the `+`) and the value stored and tested against is `2015-04-28 02:23:50`. So I have to use `preg_replace('/(\d{4}(-\d{2}){2})T(\d{2}(:\d{2}){2}) \d{2}:\d{2}/', '$1 $3', $value)`.

I'm raising the issue because we're having a search filter and it don't work with an exact match for dates. The solution is easy (it's just a `preg_replace`) but we can choose not to bother with it and say it's the responsibility of the developer to handle date cases. But if it's the chosen stance, we have to specify it in the doc..

**Comment by dunglas** [comment]
We now have a date filter: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/DateFilter.php
