### ISSUE TITLE
JSON-LD: don't fail when the resource class has no identifiers

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#2416]
When a resource class has properties mapped as identifier, our JSON-LD normalizer should use a [blank node identifier](https://w3c.github.io/json-ld-syntax/#dfn-blank-node-identifier) as value for the `@id` property instead of failing.

**Comment by soyuka** [comment]
Can you pin point to a code location where this is an issue? Thanks!

**Comment by dunglas** [comment]
I'm not sure of the location, but try to create an entity with no identifier, and it fails during the serialization.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/2495 adds blank identifiers (need to add a test)
