### ISSUE TITLE
SerializerContextBuilder not working

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2421]
I have created a the fallowing:

```
final class AdminContextBuilder implements SerializerContextBuilderInterface
{
    private $decorated;
    private $authorizationChecker;

    public function __construct(SerializerContextBuilderInterface $decorated, AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->decorated = $decorated;
        $this->authorizationChecker = $authorizationChecker;
    }

    public function createFromRequest(Request $request, bool $normalization, ?array $extractedAttributes = null): array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);

        if ($this->authorizationChecker->isGranted('ROLE_SYSADMIN')) {
            $context['groups'][] = 'sysadmin';

            if ($normalization) {
                $context['groups'][] = 'sysadmin_read';
            } else {
                $context['groups'][] = 'sysadmin_write';
            }
        }

        return $context;
    }
}
```

And added the fallowing to the property:
```
    /**
     * @ORM\Column(name="status", type="integer", length=1, nullable=true)
     * @Groups({"sysadmin"})
     */
    public $status;
```

The user has not the ROLE_SYSADMIN but can PATCH the item.

I also tried to set here:

```
 *   itemOperations={
 *     "patch"={
 *       "denormalization_context"={"groups"={"sysadmin","sysadmin_write"}, "swagger_definition_name": "CreationWrite"},
 *       "normalization_context"={"groups"={"sysadmin","sysadmin_read"}, "swagger_definition_name": "Read"},
 *      },
 *   }, 
```

But all users can patch the item!

**Comment by antograssiot** [comment]
Keep your `$status` property annotation as is, and declare another denormalization group on the entity like the following:
```
 *   itemOperations={
 *      "get", "put", "patch"={"denormalization_context"={"groups"={"yourdefaultgroupname:write"}},
 *   }, 
```

As long as there are no default denormalization groups on the entity/operation attribute, local properties groups are not checked.
https://github.com/api-platform/core/blob/a3f616702aad5492fb661b53aed3bb3621fe7b59/src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php#L82-L84


Indeed if you're using `"denormalization_context"={"groups"={"sysadmin","sysadmin_write"}..` like in your last example, then every one will be granted as those groups became the default and your `AdminContextBuilder ` is useless. Also if only admin can use the PATCH operation, you could also use the `access_control` attribute but it might not fit you scenario

**Comment by do-web** [comment]
Ok, i have done this:

`
 *   itemOperations={
 *     "patch"
 *   }, 
`

And now it should work? It already worked for other operation like GET, but PATCH not working.
Indeed that was a good hint to use access_control but i also want to figer out why PATCH is not working.

**Comment by antograssiot** [comment]
if you don't have denormalization_context that's not enough, you need at least one group to be defined in either the operation or the entity attribute
