### ISSUE TITLE
Can't disable swagger for a single entity 

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2422]
I cant disable specific entity to shown in the swagger docs.

I want a entity not to shown in swagger.

**Comment by soyuka** [comment]
Decorate the documentation normalizer.

**Comment by do-web** [comment]
Have you an example or a link to the Documentation where i can find this information?

**Comment by antograssiot** [comment]
https://api-platform.com/docs/core/swagger/#overriding-the-swagger-documentation
