### ISSUE TITLE
[QUESTION] Partial data in operation when PATCHing entity

### ISSUE THREAD

**Issue by TrogWarZ** [api-platform/core#2430]
Hello! I'm using ApiPlatform 1.1.0 with Symfony 4.2.1 (flex 1.1.8) and with help of JWT auth bundle 2.6.1.

I have custom operation for updating current user. For example, i want to update fullname of user with this request:

```bash
http -v PATCH 'example.com/api/me.jsonld' <<< '{"fullname":"John Doe"}'
```

Custom operation code:

```php
<?php

namespace App\Controller;

use App\Entity\User;
use Http\Discovery\Exception\NotFoundException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

final class UpdateCurrentUser
{
    public function __invoke(Request $request, TokenStorageInterface $storage, User $data): User
    {
        $token = $storage->getToken();
        if (!$token) throw new NotFoundException('Invalid token');

        /** @var User $user */
        $user = $token->getUser();
        if (!$token) throw new NotFoundException('Invalid user');

        // ... ??? ...

        return $data;
    }
}
```

User entity constructor is empty. Look at line 21 of operation – at this point, `$data` variable contains ALL properties filled `null` except `email`. 

But, what if user can nullify this property? How can get only sent properties that user sent? And, maybe, automatically assign those properties into user entity?

**Comment by antograssiot** [comment]
> How can get only sent properties that user sent ?

you could always inject/use the Request object, that's a normal symfony action

**Comment by TrogWarZ** [comment]
> > How can get only sent properties that user sent ?
> 
> you could always inject/use the Request object, that's a normal symfony action

And then iterate by myself via sent data from user? ApiPlatform don't have code to simplify this routine?

**Comment by antograssiot** [comment]
> what if user can nullify this property?
That is also supported already by standard `PUT` operation. Partial update and nullable values
