### ISSUE TITLE
multipart/form-data (Upload File)

### ISSUE THREAD

**Issue by raphydev** [api-platform/core#2431]
Hi, and thanks for this great works, it's been a long time since I use api-platform.
I read in the doc, that the format "multipart/form-data" for the file upload is not taken.
Also in the doc, he made an integration with Vich, but using a symfony form builder.
Can you give us an idea or an example of image upload with the format: multipart / form-data with api-platform?
Thank you in advance !

PS: i'm using React-redux for my front app

**Comment by z31fbras** [comment]
You can totally upload an image to API-Platform using the example in the documentation without using a symfony form on your front-end. I've used this exact example on the back-end and a colleague of mine used it with an Angular 7 front-end.

If you want to test the upload feature in the Swagger documentation, you can use these annotations on the MediaObject entity: it will display an upload field.

`
 * @ApiResource(iri="http://schema.org/MediaObject", collectionOperations={
 *     "get",
 *     "post"={
 *         "method"="POST",
 *         "path"="/media_objects",
 *         "controller"=CreateMediaObjectAction::class,
 *         "defaults"={"_api_receive"=false},
 *         "denormalization_context"={"groups"={"media_object_post"}},
 *         "validation_groups"={"media_object_post"},
 *         "swagger_context" = {
 *            "consumes" = {
 *                "multipart/form-data",
 *             },
 *             "parameters" = {
 *                 {
 *                      "name" = "file",
 *                      "in" = "formData",
 *                      "required" = "true",
 *                      "type" = "file",
 *                      "description" = "The file to upload"
 *                 }
 *             },
 *         }
 *     },
 * })`

**Comment by raphydev** [comment]
@z31fbras .. nice thanks

**Comment by mrkonovalov** [comment]
How to make method PUT for file?

**Comment by 9heun9** [comment]
> How to make method PUT for file?

Struggling with this as well. 

My problem is that it I'm not able to get the 'file' parameter in my custom operation.

I mapped a custom operation as follows: 

```
/**
 * @ORM\Entity
 * @ApiResource(
 * 
 *     ...
 * 
 *     itemOperations={
 *         "get",
 *         "put"={
 *             "controller"=EditMediaObject::class,
 *             "deserialize"=false,
 *             "validation_groups"={"Default", "media_object_create"},
 *             "swagger_context"={
 *                 "consumes"={
 *                     "multipart/form-data",
 *                 },
 *                 "parameters"={
 *                     {
 *                         "in"="formData",
 *                         "name"="file",
 *                         "type"="file",
 *                         "description"="The file to upload",
 *                     },
 *                 },
 *             },
 *         },
 *         "delete"
 *     },
 * )
 * @Vich\Uploadable
 */
```
The operation itself looks like this: 

```
<?php
// api/src/Controller/EditMediaObject.php

namespace App\Controller;

use App\Entity\MediaObject;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

final class EditMediaObject
{
    /**
    * @var RequestStack
    */
    private $requestStack;


    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }
    public function __invoke(MediaObject $data): MediaObject
    {
        $request = $this->requestStack->getCurrentRequest();
        $uploadedFile = $request->attributes->get('file');
        if (!$uploadedFile) {
            throw new BadRequestHttpException ('"file" is required');
        }
        $data->file = $uploadedFile;

        return $data;
    }
}
```
It populates $data correctly (the MediaObject property which I would like to replace), but file is not accessible from $requestStack 

What am I missing? 

(sorry for bumping this thread)

**Comment by teohhanhui** [comment]
Why inject the `RequestStack`? Just add `Request $request` argument in the `__invoke` method.

**Comment by 9heun9** [comment]
Thank you, this is really helpful

**Comment by dvalverdeGF** [comment]
> },

Hi!
This worked for me before, but after an upgrade, I'm getting this error:

```
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "The content-type \"multipart/form-data; boundary=----WebKitFormBoundaryss4XqvUy3Dknawjh\" is not supported. Supported MIME types are \"application/ld+json\", \"application/json\", \"text/html\".",
```

**Comment by teohhanhui** [comment]
@dvalverdeGF It looks like your comment has something missing...

**Comment by dvalverdeGF** [comment]
Sorry, was a mistake.
However, today I've found a solution:

I've added this elements to api-platform config file:

```
api_platform:
        multipart:
            mime_types: ['multipart/form-data']
```
and this attribute to my swagger description:

`"deserialize"=false`

it works again.

**Comment by tomsihap** [comment]
> Sorry, was a mistake.
> However, today I've found a solution:
> 
> I've added this elements to api-platform config file:
> 
> ```
> api_platform:
>         multipart:
>             mime_types: ['multipart/form-data']
> ```
> 
> and this attribute to my swagger description:
> 
> `"deserialize"=false`
> 
> it works again.

@dvalverdeGF my `api_platform.yaml` file  doesn't recognise the `multipart` attribute.

**Comment by ilove3q** [comment]
> > Sorry, was a mistake.
> > However, today I've found a solution:
> > I've added this elements to api-platform config file:
> > ```
> > api_platform:
> >         multipart:
> >             mime_types: ['multipart/form-data']
> > ```
> > 
> > 
> > and this attribute to my swagger description:
> > `"deserialize"=false`
> > it works again.
> 
> @dvalverdeGF my `api_platform.yaml` file doesn't recognise the `multipart` attribute.

use it:

>  patch_formats:
>         multipart: ['multipart/form-data']

**Comment by llaurenz** [comment]
I added `mime_types: ['multipart/form-data']` to my config file, but now I am getting the error message: `Deserialization for the format multipart is not supported`, where can I specify the "deserialize"=false option?

**Comment by khaledBou** [comment]
Hello,
I'm using the same example provided by api platform to upload file and i tried with postman to make a multi upload and i tried to dump the request : 
`public function __invoke(Request $request): MediaObject
    {
        $uploadedFile = $request->files->get('file');
        dd($uploadedFile);
        if (!$uploadedFile) {
            throw new BadRequestHttpException('"file" is required');
        }

        $mediaObject = new MediaObject();
        $mediaObject->file = $uploadedFile;

        return $mediaObject;
    }
`
![dump](https://user-images.githubusercontent.com/39246997/83414190-5bd64f80-a41d-11ea-965f-c11d6ba8ae13.jpg)

How can i make a multi upload ?

**Comment by Renrhaf** [comment]
@khaledBou Just use different keys for your files in Postman (file1; file2; etc)
And use the code `$request->files->all()` to get them all.

**Comment by khaledBou** [comment]
i used files all like this  : 
`$uploadedFile = $request->files->all();
        
        if (!$uploadedFile) {
            throw new BadRequestHttpException('"file" is required');
        }

        $mediaObject = new MediaObject();
        $mediaObject->file = $uploadedFile;

        return $mediaObject;`

and i got this error :  
Return value of Vich\\UploaderBundle\\Mapping\\PropertyMapping::getFile() must be an instance of Symfony\\Component\\HttpFoundation\\File\\File or null, array returned

**Comment by marryj** [comment]
I want o upload multiple files too, but couldn`t achive it. Does anybody know how to implement it.

**Comment by Lanicet** [comment]
@khaledBou did you find any solution for this problem?

**Comment by Lanicet** [comment]
Hi everyone, I finally found a solution by using DataPersiter without using vichBundle anytime. I didn´t use the ResolveMediaObjectContentUrlSubscriber Class from the documentation below my code I hope this can help you. 
```
//Entity/MediaObject.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Controller\CreateMediaObjectAction;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ApiResource(
 *     iri="http://schema.org/MediaObject",
 *     normalizationContext={
 *         "groups"={"media_object_read"}
 *     },
 *     collectionOperations={
 *         "post"={
 *             "controller"=CreateMediaObjectAction::class,
 *             "deserialize"=false,
 *
 *             "validation_groups"={"Default", "media_object_create"},
 *             "openapi_context"={
 *                 "requestBody"={
 *                     "content"={
 *                         "multipart/form-data"={
 *                             "schema"={
 *                                 "type"="object",
 *                                 "properties"={
 *                                     "file"={
 *                                         "type"="string",
 *                                         "format"="binary"
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         "get"
 *     },
 *     itemOperations={
 *         "get"
 *     }
 * )
 */
class MediaObject
{
    /**
     * @var int|null
     *
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @ORM\Id
     * @Groups({"media_object_read", "article_read", "user_read", "category_read"})
     */
    protected $id;

    /**
     * @var string|null
     *
     * @ApiProperty(iri="http://schema.org/contentUrl")
     * @Groups({"media_object_read", "article_read", "user_read", "category_read"})
     */
    public $contentUrl;

    /**
     * @var File|null
     * @Assert\NotNull(groups={"media_object_create"})

     * @Groups({"media_object_read", "article_read", "user_read", "category_read"})
     */
    public $file = [];

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     * @Groups({"media_object_read", "article_read", "user_read", "category_read"})
     */
    private $filePath;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="images", cascade={"persist"})
     * @Groups({"media_object_read"})
     */
    private $article;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getFilePath()
    {
        return $this->filePath;
    }

    public function setFilePath($filePath)
    {
        $this->filePath = $filePath;

        return $this;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }
}



//DataPersister/DataPersister.php
<?php

namespace App\DataPersister;

use ApiPlatform\Core\DataPersister\ContextAwareDataPersisterInterface;
use App\Entity\MediaObject;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class MediaObjectDataPersister extends AbstractController implements ContextAwareDataPersisterInterface, ResumableDataPersisterInterface
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function supports($data, array $context = []): bool
    {
        return $data instanceof MediaObject;
    }

    public function persist($data, array $context = [])
    {
        foreach ($data->getFile() as $key => $image) {
            $data->setFilePath($image);
            $MediaObject = new MediaObject();
            $MediaObject->setFilePath($image);
            $MediaObject->setArticle($data->getArticle());

            $this->entityManager->persist($data);

            if ($key > 0) {
                $this->entityManager->persist($MediaObject);
            }
        }
        $this->entityManager->flush();
    }

    public function remove($data, array $context = [])
    {
        $this->entityManager->remove($data);
        $this->entityManager->flush();
    }
}
```


//Controller/CreateMediaObjectAction.php
<?php

namespace App\Controller;

use App\Entity\MediaObject;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

final class CreateMediaObjectAction extends AbstractController
{
    public function __invoke(Request $request, ArticleRepository $repo)
    {
        $uploadedFile = $request->files->all();

        if (!$uploadedFile) {
            throw new BadRequestHttpException('"file" is required');
        }
        $id = $repo->find($request->request->get('article'));
        $mediaObject = new MediaObject();
        $filesname = [];
        foreach ($uploadedFile['file'] as $image) {
            $fichier = md5(uniqid()).'.'.$image->guessExtension();
            $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

            $filesname[] = $fichier;
        }
        $mediaObject->SetArticle($id);
        $mediaObject->file = $filesname;

        return $mediaObject;
    }
}

**Comment by sardarnaqib** [comment]
@khaledBou if you are using Postman you should add square brackets to the field name in Postman for example files[] then you will get all files
and if you are using FormData Api you should do something like this
`let formData = new FormData();
        
        files.forEach(file => {
            formData.append('files[]', file);
        })`

**Comment by sardarnaqib** [comment]
@khaledBou if you are using Postman you should add square brackets to the field name in Postman for example files[] then you will get all files
and if you are using FormData Api you should do something like this

```
let formData = new FormData();
        
files.forEach(file => {
    formData.append('files[]', file);
})
```

**Comment by sardarnaqib** [comment]
> Hello,
> I'm using the same example provided by api platform to upload file and i tried with postman to make a multi upload and i tried to dump the request :
> 
> ```
> public function __invoke(Request $request): MediaObject
>     {
>         $uploadedFile = $request->files->get('file');
>         dd($uploadedFile);
>         if (!$uploadedFile) {
>             throw new BadRequestHttpException('"file" is required');
>         }
> 
>         $mediaObject = new MediaObject();
>         $mediaObject->file = $uploadedFile;
> 
>         return $mediaObject;
>     }
> ```
> 
> ![dump](https://user-images.githubusercontent.com/39246997/83414190-5bd64f80-a41d-11ea-965f-c11d6ba8ae13.jpg)
> 
> I always got one file , How can i make a multi upload ?

@khaledBou if you are using Postman you should add square brackets to the field name in Postman for example files[] then you will get all files
and if you are using FormData Api you should do something like this

```
let formData = new FormData();
        
files.forEach(file => {
    formData.append('files[]', file);
})
```
