### ISSUE TITLE
Convert Entity's Id to a HashId in runtime without persisting

### ISSUE THREAD

**Issue by BharathVibhav** [api-platform/core#2449]
Hi,

I'm working my way through API Platform.
I'm currently trying to implement this
https://github.com/ivanakimov/hashids.php

by following the steps in 
https://github.com/api-platform/api-platform/issues/724#issuecomment-398812438

how ever, I'm unable to pass the entity as a whole in my serializer. I can only get the individual properties to be passed through. 

**My Entity:**

    class MyEntity
    {
    /**
     * @var int
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="message", type="text", length=0, nullable=true)
     */
    private $message;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * @param string|null $message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }
    }

**services.yaml:**

`'App\Serializer\CommonIdentifierNormalizer':
        tags: [ name: serializer.normalizer ]`

**CommonIdentifierNormalizer:**

    namespace App\Serializer;

    use Hashids\Hashids;
    use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
    use Symfony\Component\Serializer\Serializer;
    use Symfony\Component\Serializer\Encoder\JsonEncoder;
    use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
    use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
    use Doctrine\Common\Annotations\AnnotationReader;
    use Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader;

    class CommonIdentifierNormalizer implements NormalizerInterface
    {
     private $normalizer;
    
    public function __construct(ObjectNormalizer $objectNormalizer)
    {
        $this->normalizer = $objectNormalizer;
    }

    public function normalize($object, $format = null, array $context = array())
    {
        $hashId = new Hashids('', 7);
        $data = $hashId->encodeHex($object->getId());

        $object->setId($data);

        return $this->normalizer->normalize($object);
    }

    public function supportsNormalization($data, $format = null)
    {
        return is_object($data);
    }
    }

However even the supportsNormalization method fails since only individual properties are being passed.
I would like to make it a global solution, where in all the properties marked as identifiers are normalized and my request accepts hashid's instead of the primary key.
Can you help me with this?

**Comment by soyuka** [comment]
IdentifierNormalizers will only work on single identifiers you should be able to do that though. If not just use a custom data provider.
