### ISSUE TITLE
How to add own access_control callback funktion

### ISSUE THREAD

**Issue by do-web** [api-platform/core#2456]
Something like this custom_callback:

```
/**
 * Secured resource.
 *
 * @ApiResource(
 *     attributes={"access_control"="custom_callback()"},
 *     collectionOperations={
 *         "get",
 *         "post"={"access_control"="custom_callback()"}
 *     },
 *     itemOperations={
 *         "get"={"access_control"="custom_callback()"}
 *     }
 * )
 * @ORM\Entity
 */
```

**Comment by lukasluecke** [comment]
You could use `is_granted('CUSTOM_PERMISSION')` and then register a Voter with your custom logic.

**Comment by do-web** [comment]
i have done that. :) It was just a question if a custom callback can be registred.

**Comment by lukasluecke** [comment]
Since it‘s just an expression I guess you could try this: https://symfony.com/doc/current/components/expression_language/extending.html
