### ISSUE TITLE
Description YAML parsing

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/core#2458]
So, I wanted to make some doc improvement to my API and discovered the following.

In my apiplatfrom packadge config I have te following

```
    # The description of the API.
    description: |
        Een API om een huwelijks regestratie te benaderen 
        #test 1  
        text  
        #test 2  
        text  
```

But when rendering the swagger yaml file I end up with 

```
info:
    title: 'Huwelijks (HRC) API'
    version: '0.0.1 Alpha'
    description: "Een API om een huwelijks regestratie te benaderen \n#test \ntext  \n#test 2  \ntext  \n"
```

Wish basically prevents me from writing  a proper api explanation as part of my swagger file 

I’m I overlooking something?

**Comment by antograssiot** [comment]
closing as the PR has been merged
