### ISSUE TITLE
Deserialization of doctrine Collection

### ISSUE THREAD

**Issue by LucasTheCure** [api-platform/core#2467]
How to force denormalization process to use Doctrine Collection object instead of simple php array.
Normalization works and create array from Collection but reverse operation behaves differently.
This breaks consistency because getter returns Collection but setter needs array to work.

```php
// this do not work, the denormalization process create array instead of doctrine Collection
// and generate exception during setting value
class HomeEntity {
    public function getItems(): Collection { return $this->items; }
    public function setItems(Collection $items): void
    {
        $this->items = $items;
    }
}

// this works! denormalization process create array, everything works just fine
class HomeEntity {
    public function getItems(): Collection { return $this->items; }
    public function setItems(array $items): void
    {
        $this->items = new ArrayCollection($items);
    }
}
```

**Comment by ragboyjr** [comment]
@LucasTheCure I think I'd recommend not exposing the collection class on you entities/resources.

So, changing `getItems(): array { return $this->items->toArray(); }`. This prevents you from leaking implementation details from HomeEntity and also ensures that items is immutable.
