### ISSUE TITLE
outputClass swagger name

### ISSUE THREAD

**Issue by er1z** [api-platform/core#2468]
Currently:

`src/Swagger/Serializer/DocumentationNormalizer.php:553`
```
        if (null !== $publicClass) {
            $keyPrefix .= ':'.md5($publicClass);
        }
```

How about allowing to specify generated struct name? Think it should be introduced before releasing 2.4 because it leads to produce weirdly-named classes when — for example — `swagger-codegen` is being used.

**Comment by soyuka** [comment]
We definitely need to add a class to generate this name :+1:

**Comment by er1z** [comment]
If you point me, what do you need from architecture aspect, may be it will be possible for me to create a PR with this.

**Comment by ragboyjr** [comment]
@er1z Would something like this work: https://github.com/api-platform/core/pull/2487

**Comment by er1z** [comment]
@ragboyjr yup, it should work but your solution disallows to put name on generated structure. We need to create (that's proposal) an adequate key under `swagger_context` configuration structure and use your code as a fallback. I'll look into in a couple of days because I need this. :)

**Comment by er1z** [comment]
Any updates?

Currently `vendor/api-platform/core/src/Swagger/Serializer/DocumentationNormalizer.php:305` forces `$serializerContext` to be null so I cannot specify the whole name. Also, `buildDefinitionName` is private so decorating this will take a massive amount of code.

**Comment by soyuka** [comment]
Wasn't this fixed by https://github.com/api-platform/core/pull/3231 ?

**Comment by soyuka** [comment]
configure `operationId` or it takes `operationName` in 3.2
