### ISSUE TITLE
DataProviders are chained when item is not found.

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#247]
Due to the current implementation of [`DataProviderChain::getItem()`](https://github.com/dunglas/DunglasApiBundle/blob/master/Model/DataProviderChain.php#L42), when a data provider claims to support a given resource but cannot find the item and returns `null`, next (supporting) data providers are called until the last one.
Then, if the last one returns `null`, a 404 page will be created.

I'd expect that when the first DataProvider supporting the Resource returns `null`, a 404 response is generated without trying other providers.

The same happens for `getCollection` when returning an empty array (Hopefully, not when returning an empty Paginator).

Is that the expected behavior ?
If it is, can we imagine an (empty?) interface that data providers could implement just to stop the "propagation" ? Any suggestion about the name of such an interface ?
As my expectations are more describing a `DelegatingDataProvider` than a `DataProviderChain`, should we provide both in the bundle, and allow to simply choose the desired behavior in the config ?

**Comment by dunglas** [comment]
The behavior you suggest looks good to me (returning  a 404 when the `null` occurs), however it would be a BC break.

The interface introduces too complexity IMO. Maybe can we change that behavior in v2.

**Comment by dunglas** [comment]
Fixed in v2.
