### ISSUE TITLE
2.4.0 beta : Fail to generate the graphql schema

### ISSUE THREAD

**Issue by epourail** [api-platform/core#2471]
The schema builder failed due to a call to a missing method in the `webonyx/graphql-php` bundle

```
In SchemaBuilder.php line 211:
                                                                                                           
  Attempted to call an undefined method named "getStandardTypes" of class "GraphQL\Type\Definition\Type".  
```

**Comment by alanpoulain** [comment]
Are you using the latest `webonyx/graphql-php` version (0.13)?
https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/Type.php#L184

**Comment by epourail** [comment]
yes

**Comment by epourail** [comment]
> Are you using the latest `webonyx/graphql-php` version (0.13)?
> https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/Type.php#L184

**Comment by epourail** [comment]
@alanpoulain  Let me check, it seems I have a conflict installing the last version of webonyx/graphql-php package

**Comment by epourail** [comment]
> @alanpoulain Let me check, it seems I have a conflict installing the last version of webonyx/graphql-php package

I confirm The issue was due to a conflict with my `composer.lock`
Sorry.
