### ISSUE TITLE
Little performance issue on pagination

### ISSUE THREAD

**Issue by iCodr8** [api-platform/core#2473]
To get the total value for the pagination a query like this is used:

200ms
```
SELECT count(DISTINCT e0_.id) AS sclr_0 FROM xxxxxx e0_ WHERE e0_.archived = ? AND e0_.team_id = ?
```

When the distinct is removed on this query, it will be much faster. An I think the distinct is not really used on this request.

80ms
```
SELECT count(e0_.id) AS sclr_0 FROM xxxxxx e0_ WHERE e0_.archived = ? AND e0_.team_id = ?
```

What do you think?

**Comment by soyuka** [comment]
Would using the partial pagination configuration option work for you? It drastically improves the performances. The `DISTINCT` thing comes from Doctrine and the way they do the pagination, we don't really have a way to change it IIRC.

**Comment by soyuka** [comment]
I'd suggest to use https://github.com/soyuka/esql or native queries :).
