### ISSUE TITLE
OpenAPI/Swagger Object Definition on GET, id link on POST

### ISSUE THREAD

**Issue by ghry5** [api-platform/core#2478]
I have a Property entity which has a collection of possible Units as follows below.
I want the Units to be embedded in GET /properties(/{id}) and to be links (iri / id) in POST /properties.
This is because the possibleUnits should always be listed together with a property and a properties possible Units should be changeable among a preexisting Unit "pool".
```
/**
 * @ApiResource(
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}},
 *     )
 *     
 */
class Property {
     /**
     * The possible units for this property
     * @var \Doctrine\Common\Collections\Collection
     * @Groups({"read", "write"})
     */
    private $possibleUnits;
}
...
class Unit {
   /**
   * @Groups({"read"})
   private name;
}
```
As no property of Unit has the "write" group i would expect the Swagger documentation for the POST /properties call to be as follows
```
{
  possibleUnits: [ "string" ]
}
```
But is instead: 
```
{
  possibleUnits: [ {} ]
}
```
I noticed that if i remove the NormalizationContext (the READ context) the POST model gets changed to what i wanted. But the GET call is then also of type ["string"] instead of the embedded entity.
This seems to be since in the [DocumentationNormalizer's getType](https://github.com/api-platform/core/blob/master/src/Swagger/Serializer/DocumentationNormalizer.php) Method always seems to take into account the $readableLink and not the $writeableLink(is this even used anywhere?) even for the POST calls.

**Comment by ragboyjr** [comment]
Thanks for the report, I'd check on this issue again after 2.4 is fully released since they are making heavy changes in the Documentation Normalizer.

I'd imagine you could just set the swagger context manually on those endpoints as a work around to get the docs right.
