### ISSUE TITLE
Content Negotiation (custom format) vs Custom Operation?

### ISSUE THREAD

**Issue by Souhail-5** [api-platform/core#2504]
Hello,

I want your advices.

I have a resource named Report exposed by this route `/api/reports/{id}`.
By default, this route returns a `.jsonld` response containing the id, name, type, and data of a Report.

Now, I want to configure this route `/api/reports/{id}.html` to expose an HTML rendering of a Report ; and this route `/api/reports/{id}.pdf` to expose a PDF rendering of a Report.

For these routes, should I use [Content Negotiation](https://api-platform.com/docs/core/content-negotiation/) (with an Encoder) or [Custom Operation](https://api-platform.com/docs/core/operations/)? **Why?**

For now I opted for Content Negotiation. So I configured 2 new formats (html + pdf) and created 2 new Encoder (HtmlReportEncoder + PdfReportEncoder).

Thanks in advance.

**Comment by soyuka** [comment]
Definitely content negociation yes, you're changing the format of the response, the operation is the same I don't see why you should have a custom operation. A custom operation would be preferable if you had to return something else then a report or maybe a richer one compared to the default operation (different serialization groups).

**Comment by mrtnzagustin** [comment]
@Souhail-5 can you show me your code for "So I configured 2 new formats (html + pdf) and created 2 new Encoder (HtmlReportEncoder + PdfReportEncoder)." ??
