### ISSUE TITLE
DateTimeZone Is Not Accessible In GraphQL

### ISSUE THREAD

**Issue by kiler129** [api-platform/core#2509]
## Background
`SchemaBuilder` contains special magic handling of `DateTime` & `DateTimeImmutable` to force rest of the system into thinking that `DateTimeInterface` objects are just strings: 

https://github.com/api-platform/core/blob/27f331ca4a36041929e32122e948101c7043498c/src/GraphQl/Type/SchemaBuilder.php#L343-L347

This handling does not change since the [original PR for GraphQL](https://github.com/api-platform/core/pull/1358) by @alanpoulain. My guess is it was done because [Symfony Serializer provides `\DateTimeInterface` normalization OOB](https://github.com/symfony/serializer/blob/master/Normalizer/DateTimeNormalizer.php).

## Problem
Special handling is not provided for `\DateTimeZone`. It lands as an object which is processed later on and arrives in here:

https://github.com/api-platform/core/blob/2bb6f950b4fe3568e5c87d3bbe56fbf87f1901da/src/GraphQl/Type/SchemaBuilder.php#L459-L465

This code unfortunately refuses to map **any** of the `DateTimeZone` fields, since `$propertyMetadata->getType()` returns `null` and field is dropped as a result :(

## Workaround
~~So far I don't see any.~~ Providing custom `PropertyTypeExtractorInterface` implementation which handles `DateTimeZone` & registering `DateTimeZone` as an API resource is actually a workable solution.

## Solution?
Is my understanding correct here? Can `\DateTimeZone` be handled any other way?

**Comment by soyuka** [comment]
fixed I guess
