### ISSUE TITLE
[Question] How to retreive current user in a custom controller?

### ISSUE THREAD

**Issue by myerffoeg** [api-platform/core#2511]
Hi,

I am struggling creating a custom controller to retreive current user by now I have done this :

```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * @Route("/authentication")
 */
class AuthenticationController extends AbstractController
{
    /**
     * @Route("/me")
     * @Method("GET")
     * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
     */
    public function meAction()
    {
        // $this->getUser();
    }
}
```

But the `@Security` does not find my logged user (I am using JWTToken) it returns me that I must be logged to use this action.

How can I manage to return my current user using this way ?

**Comment by soyuka** [comment]
Inject the TokenStorageInterface see https://github.com/api-platform/core/issues/477 also

**Comment by myerffoeg** [comment]
Sorry but could you provide me an example?

**Comment by soyuka** [comment]
there are multiple examples on the issue I gave above, maybe you have an issue with your firewall you should check what the symfony debug page is giving you.

**Comment by myerffoeg** [comment]
You was right I was on the wrong firewall my bad thank you.
