### ISSUE TITLE
[RFC] Expose Enum Swagger Context In GraphQL

### ISSUE THREAD

**Issue by kiler129** [api-platform/core#2512]
Currently some of my fields are documented in a way similar to this:

```php
    /**
     * @var string|null Gender, see GenderType for possible values
     *
     * @ORMEnumAssert\Enum(entity="Vendor\App\DBAL\Types\GenderType")
     * @ORM\Column(type="gender", nullable=true, name="gender")
     * @ApiProperty(
     *     attributes={
     *         "swagger_context"={
     *             "enum"={
     *                 GenderType::GENDER_MALE,
     *                 GenderType::GENDER_FEMALE
     *             }
     *         }
     *     }
     * )
     */
    private $gender;
```

This works great for REST (maybe except that you have to manually define it all the time :P). It will be nice to expose this to GraphQL too. WDYT?

**Comment by dunglas** [comment]
We need enum support in PHP!
In the meantime, a cleaner solution would be to support an external enum lib, such as https://github.com/myclabs/php-enum that is already is supported by our schema generator.

**Comment by kiler129** [comment]
I will definitelly take a look. We use very simple enum library (`fresh/doctrine-enum-bundle`) which simply stores values as strings and we document them in `swagger_context`.

**Comment by lukasluecke** [comment]
Are there any updates on this? Maybe a similarly manual solution for now to define possible values, and something a bit more automatic later on?

@killer129 did you implement something for this in your project?

If not, I might be able to work on a basic PR soon.

**Comment by lukasluecke** [comment]
Are there any updates on this? Maybe a similarly manual solution for now to define possible values, and something a bit more automatic later on?

@kiler129 did you implement something for this in your project?

If not, I might be able to work on a basic PR soon.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/2254
