### ISSUE TITLE
The resource path matches an action path, not the entity one

### ISSUE THREAD

**Issue by partageit** [api-platform/core#2515]
Hello, I encounter a strange behaviour with resource paths.

It is my first experience with api-platform/core 2.3. It worked well with api-platform/core 2.1.

I create an entity:

```php
// src/Entity/Answer.php

/**
 * @ORM\Entity
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"answer"}},
 *     "denormalization_context"={"groups"={"answer"}}
 * })
 */
class Answer {
  // ...
}
```

When I `GET /answers`:

```json
{
    "@context": "/contexts/Answer",
    "@id": "/answers",
    "@type": "hydra:Collection",
    "hydra:member": [...]
}
```

The `@id` is correct.

I add an action:

```php
// src/Action/AnswerAction.php

class AnswerAction {
    /**
     * @Route(
     *     name="answer_import",
     *     path="/answers/-/import",
     *     methods={"GET"},
     *     defaults={
     *         "_api_resource_class"=Answer::class,
     *         "_api_collection_operation_name"="answer_import"
     *     }
     * )
     */
    public function import($data) {
      // ...
    }
}
```

The same `GET /answers`:

```json
{
    "@context": "/contexts/Answer",
    "@id": "/answers/-/import",
    "@type": "hydra:Collection",
    "hydra:member": [...]
}
```

The `@id` is the action's one, i.e. `/answers/-/import`.

Moreover, `GET /`:

```json
{
    "@context": "/contexts/Entrypoint",
    "@id": "/",
    "@type": "Entrypoint",
    "answer": "/answers/-/import",
    "...": "/..."
}
```

I think I missed something about resource URIs...

**Comment by partageit** [comment]
I have some news!

This class is used when building the entrypoint: `ApiPlatform\Core\Bridge\Symfony\Routing\RouteNameResolver`.

The methods `RouteNameResolver::getRouteName()` lists routes and returns the first matching one.

With my class with route `/answers` and my action with route `/answers/-/import`, both match the route condition, but `/answers/-/import` is the first one in the list.  
As a consequence, it is returned, and the entrypoint considers this route as the one to present.

The list returned by `$this->router->getRouteCollection()->all()`:

```
- answer_import
- ...
- api_entrypoint
- api_doc
- api_jsonld_context
- api_questions_get_collection
- api_questions_post_collection
- api_answer_get_collection
- api_answer_post_collection
- api_*_collection
```

'Native' operations are after custom ones.

I tried this simple (dumb?) solution, adding `array_reverse()`, and it works :

```php
foreach (array_reverse($this->router->getRouteCollection()->all(), true) as $routeName => $route) {
  // ...
}
```

Do you know a better solution?

**Comment by soyuka** [comment]
You can change the route name so that it comes before :sweat_smile: . We have other issues on that subject (routes order) and I don't know any good solution to the problem :/.

**Comment by partageit** [comment]
:stuck_out_tongue: 

Thank you for your answer :)

My sample was not so good.  
Even when changing the action name, native operations are after custom ones:

```
- answer_import
- ...
- zzz_answer_import
- api_entrypoint
- api_doc
- api_jsonld_context
- api_questions_get_collection
- ...
```

I have noticed that the content of `docs.jsonld` was not correct, but the content of the documentation (the pretty one, with the spider) does not have the problem, routes are correct.  
Maybe the same algo should be used on both documentations?

**Comment by soyuka** [comment]
Closing as  there's no good solution for this.
