### ISSUE TITLE
[Bug] Property Type Assumes Child Types Are Equal To Superclass Types

### ISSUE THREAD

**Issue by kiler129** [api-platform/core#2517]
## How to reproduce
Let's start with two simple entities:

```php
/**
 * @ApiResource()
 */
class NullableSuperclass
{
    /**
     * @var string|null Superclass field
     */
    public $field;
}
```

```php
/**
 * @ApiResource()
 */
class NonNullableChild extends NullableSuperclass
{
    /**
     * @var string Child field
     */
    public $field;
}
```

Now attempting to call `\ApiPlatform\Core\Metadata\Property\Factory\PropertyMetadataFactoryInterface::create()` on both of them.

## Buggy behavior
The calls to property metadata info produce very interesting result: both of them have `type->nullable` set to `false`:
![image](https://user-images.githubusercontent.com/1227834/52663129-8bc9ae80-2ecb-11e9-8413-75b317888b20.png)

*Screenshot is from a living system (top one is the child, bottom one is the superclass) for the but this is reproducable on fresh symfony skeleton + `api` insttall too*

## Impact
This causes a lot of problem down the road (e.g. wrong GraphQL schema, crashes while trying to get the superclass object). I tracked the problem down to the property metadata returning wrong results. Symfony PropertyInfo actually doesn't have this problem, so there's some problem with logic/caching in API Platform implementation ;)

**Comment by soyuka** [comment]
Not sure to follow, you expected the first one to be nullable but the second one not? Maybe that https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php is where something is wrong?

**Comment by kiler129** [comment]
@soyuka Yes, I know it sounds scary but the use case is actually simple: `PersonName` which has all fields nullable (as in life ;)) and `PersonNameStrict` which mandates `first` & `last` fields to be non-nullable.

I will try to poke with the code in that metadata factory when I have a minute.

**Comment by soyuka** [comment]
closing in favor of https://github.com/api-platform/core/issues/4091
