### ISSUE TITLE
504 Gateway Timeout by using FilterEagerLoadingExtension

### ISSUE THREAD

**Issue by AlexLiebing** [api-platform/core#2520]
We are doing a search request of article positionen with api platform and sometime getting gateway timeout because of to long query calculation of oracle db.

http request like this
.. api/positionen?limit=1000&status[in][]=open&status[in][]=lttp&properties[]=id&properties[]=amount&properties[]=openAmount&properties[]=position&properties[]=positionsextension&properties[]=pending&properties[]=text&properties[]=status&properties[article][]=id&properties[extendedData][] ...

and it results in this query:
<pre>
SELECT *
FROM Positionen o 
LEFT JOIN o.offer offer_a1 
LEFT JOIN o.article article_a2 
LEFT JOIN articleSt articleSt_a3 
LEFT JOIN o.positionV positionV_a4 
LEFT JOIN o.amount amount_a5 
LEFT JOIN o.specialData specialData_a6 
WHERE o IN(
SELECT o_a7 
FROM Positionen o_a7 
LEFT JOIN o_a7.offer auftrag_a8 
LEFT JOIN o_a7.article article _a9 
LEFT JOIN article_a9.articleSt articleS_a10 
LEFT JOIN o_a7.positionV positionV_a11 
LEFT JOIN o_a7amount  amount_a12 
LEFT JOIN o_a7.specialData specialData_a13 
WHERE o_a7.status IN(:o_status) AND o_a7.id IN(:o_id));
</pre>

So here we seen in the subselect in where condition the same sql like in the outer sql. So the question is, Why do we need the subselect at all? Without the subselect it would be run in time.

So in every case we have the double amount of joins in the query which is unnecessary in our case.

When I looked in the code there are one line in Line: 76 in FilterEagerLoadingExtension. If I comment it out I would get the same result.

<pre>
$in = $this->getQueryBuilderWithNewAliases($queryBuilder, $queryNameGenerator, $originAlias, $replacementAlias);
$queryBuilderClone->andWhere($queryBuilderClone->expr()->in($originAlias, $in->getDQL()));
</pre>
For what I need this? In our case we only need here the $in query without $queryBuilderClone.

Or when we need it. Is there any way to optimize this code for building better query?

**Comment by soyuka** [comment]
You can maybe disable eager loading for this request?

**Comment by AlexLiebing** [comment]
For this request, yes. But the url builds dynamicly, so in some case needs some join table ...

**Comment by soyuka** [comment]
You can also do your own DataProvider that doesn't uses the FilterEagerLoadingExtension but uses EagerLoadingExtension
