### ISSUE TITLE
Document "allow_plain_identifiers"

### ISSUE THREAD

**Issue by kiler129** [api-platform/core#2521]
It seems like `allow_plain_identifiers` option is there, but there's no docs for it. Additionally enabling it doesn't give me `_id` in GraphQL (which I'm not sure is an effect of not being implemented or me misunderstanding the option ;)).

rel. #1833

**Comment by soyuka** [comment]
`allow_plain_identifiers` is used to allow that kind of body:

```
POST /dummies {"relation": "1"}
```

instead of the recommended:

```
POST /dummies {"relation": "/relations/1"}
```

It's not really recommended to use it and it's still a controversal subject see https://github.com/api-platform/core/pull/2022#issuecomment-398851861

**Comment by yeisonking0214** [comment]
There is a way, to do the same but with when i do GET request to the entity?

**Comment by soyuka** [comment]
We want to remove this notion, closing this.
