### ISSUE TITLE
[Bug] @ApiSubresource maxDepth ignored for self-referencing subresources.

### ISSUE THREAD

**Issue by ghry5** [api-platform/core#2533]
I have the following class:
```
class Person {
  //@ApiSubresource(maxDepth=1)
  private $address;
  //@ApiSubresource(maxDepth=1)
  private $boss;
  //@ApiSubresource(maxDepth=1)
  private $subordinates;
}
```
`$boss` and `$subordinates` are references to the same Person entity (bidirectional oneToMany) and `$address` references an Address entity. Due to setting maxDepth=1 on all three i would expect the following three subresources:

- /people/{id}/address
- /people/{id}/boss
- /people/{id}/subordinates

The actual subresources are:

- /people/{id}/address
- /people/{id}/boss
- /people/{id}/boss/address
- /people/{id}/boss/subordinates
- /people/{id}/boss/subordinates/address
- /people/{id}/subordinates
- /people/{id}/subordinates/{subordinates}/address
- /people/{id}/subordinates/{subordinates}/boss
- /people/{id}/subordinates/{subordinates}/boss/address

The culprit seems to be the following in `SubresourceOperationFactory`
```
            // Handle maxDepth
            if ($rootResourceClass === $resourceClass) {
                $maxDepth = $subresource->getMaxDepth();
                // reset depth when we return to rootResourceClass
                $depth = 0;
            }
            if (null !== $maxDepth && $depth >= $maxDepth) {
                break;
            }
            ...

            $this->computeSubresourceOperations($subresourceClass, $tree, $rootResourceClass, $operation, $visited + [$visiting => true], ++$depth, $maxDepth);
```

Since `$rootResourceClass` equals `$resourceClass` (as $boss and $subordinates refer to the same entity) the 'current' $depth will get reset every time.

I propose the following solution:
```
      if (null === $rootResourceClass) {
            $rootResourceClass = $resourceClass;
            // initialize depth to 0 on root level
            $depth=0;
        }
        ...

            // Handle maxDepth
            // get the minimum maxDepth from the rootMaxDepth and the maxDepth of the current to be visited Subresource
            $currentMaxDepth = array_diff([$maxDepth, $subresource->getMaxDepth],[null]));
            $currentMaxDepth = empty($currentMaxDepth) ? null : min($currentMaxDepth);

            if (null !== $currentMaxDepth && $depth >= $currentMaxDepth) {
                break;
            }
            ...

            // to be at the correct depth in every recursion change ++$depth to $depth + 1 and pass on the $currentMaxDepth
            $this->computeSubresourceOperations($subresourceClass, $tree, $rootResourceClass, $operation, $visited + [$visiting => true], $depth + 1, $currentMaxDepth);
```

**Comment by soyuka** [comment]
LGTM, would you mind opening a pull request with this?
