### ISSUE TITLE
[Question] Options value in operation definition

### ISSUE THREAD

**Issue by matlar83** [api-platform/core#2546]
In the docs examples of operations configuration (https://api-platform.com/docs/core/operations/#configuring-operations) I see there is a "options" parameter:

`/**
 * ...
 * @ApiResource(itemOperations={
 *     "get"={"method"="GET", "path"="/grimoire/{id}", "requirements"={"id"="\d+"}, "defaults"={"color"="brown"}, "options"={"my_option"="my_option_value"}, "schemes"={"https"}, "host"="{subdomain}.api-platform.com"},
 *     "put"={"method"="PUT", "path"="/grimoire/{id}/update", "hydra_context"={"foo"="bar"}},
 * })
 */
class Book
{
    //...
}`

How can I get in my code the values of these options?

Thank you
Matteo

**Comment by antograssiot** [comment]
Those options are automatically passed to the [Symfony Route](https://github.com/symfony/routing/blob/5a75bcbc6c14759b56f8f73f5c1cd4abfb44cde0/Route.php#L53) as 4th parameter.
The same goes for `requirements`, `path`, `defaults` etc...

**Comment by matlar83** [comment]
Ok, thank you.
So, if I want to set a value I can get anywhere it is better to set it in
the "defaults" property.

This way I can get my values as request attributes.

Thank you
Matteo

Il giorno gio 21 feb 2019 alle ore 09:17 Anto <notifications@github.com> ha
scritto:

**Comment by antograssiot** [comment]
Exactly
