### ISSUE TITLE
dev-master: Unable to render this definition

### ISSUE THREAD

**Issue by Rebolon** [api-platform/core#2559]
Hi,

i started a project on api-platform 2.3 but in the documentation i saw interesting thing about DataTransformer and DTO. Because it's only available on 2.4 beta1 (or master) i moved into master to test it.
When i run `/api` i expect to see the swagger (OpenAPI) page like on 2.3, but this time i got this message:

```
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match  openapi: 3.0.n (for example, openapi: 3.0.0).
```

In work with Php Built-in server on a PHP 7.1.18. I use Symfony 4.2.* components.
Is there something to change in packages/api_platform.yaml ? 

Thanks for helps !

**Comment by soyuka** [comment]
You must have done something wrong, I usually start with:

```
composer create-project symfony/skeleton my-app
composer require api migrations
composer require server maker --dev
# edit composer.json and add:
#        "api-platform/core": "2.4.x-dev",
composer update
bin/console make:entity
bin/console make:migration
bin/console doctrine:migrations:execute
```

There you'll be on our 2.4 branch, it has the I/O feature and will be tagged soon as `2.4-beta.2`.

**Comment by Rebolon** [comment]
Ok, i've tried your protocol and it works.
But in fact in my projects it doesn't.
The content of the script node "swagger-data" doesn't content the required spec.swagger version

```
{"url":"/api/docs?format=json","spec":{"mimeTypes":["application/ld+json","application/json","text/html"],"version":"0.0.0","description":"","title":"","resourceNameCollection":["Entity\\Civilite","Entity\\Prescripteur\\Address","Entity\\Prescripteur"]},"oauth":{"enabled":false,"clientId":"","clientSecret":"","type":"oauth2","flow":"application","tokenUrl":"/oauth/v2/token","authorizationUrl":"/oauth/v2/auth","scopes":[]}}
```

I have reduced the api_platform.yaml file to its minimal content. And i'm still investigating with minimal Entities to see what's wrong.

**Comment by ghettovoice** [comment]
I have the same issue. Right after the upgrade from api-platform/core@d2b1b96 commit, swagger main page is broken, i.e. script node "swagger-data" doesn't has correct swagger configuration.  

I spent a lot of time trying to find meaningful changes from next commits that could beak swagger, but
without luck.

**Comment by Rebolon** [comment]
It seems that one of my services ID in services.yaml is the problem
I wanted to inject a Serializer so I redefined it with public:true.
It was ok on 2.3 but a fail on 2.4

You may list your services

**Comment by ghettovoice** [comment]
@Rebolon thanks for the tip :+1:

I have a item normalizer decorator that causes the problem. Looks like I need to recheck its implementation with latest version of the api-platform.

This my decorator definition:

```yml
    app.serializer.normalizer.item:
        class: App\Serializer\ItemNormalizer
        decorates: api_platform.serializer.normalizer.item
        arguments:
            - '@app.serializer.normalizer.item.inner'
            - '@api_platform.iri_converter'
            - '@api_platform.identifiers_extractor'
            - '@api_platform.name_converter'
        tags:
            - serializer.normalizer
```

And the decorator

```php
final class ItemNormalizer implements NormalizerInterface, DenormalizerInterface, SerializerAwareInterface
{
    /**
     * @var NormalizerInterface|DenormalizerInterface
     */
    private $decorated;
    /**
     * @var IriConverterInterface
     */
    private $iriConverter;
    /**
     * @var IdentifiersExtractorInterface
     */
    private $identifiersExtractor;
    /**
     * @var NameConverterInterface
     */
    private $nameConverter;
    /**
     * @var SerializerInterface
     */
    private $serializer;

    public function __construct(
        NormalizerInterface $decorated,
        IriConverterInterface $iriConverter,
        IdentifiersExtractorInterface $identifiersExtractor,
        NameConverterInterface $nameConverter
    ) {
        if (!$decorated instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException(\sprintf(
                'The decorated normalizer must be an instance of %s.',
                DenormalizerInterface::class
            ));
        }

        $this->decorated = $decorated;
        $this->iriConverter = $iriConverter;
        $this->identifiersExtractor = $identifiersExtractor;
        $this->nameConverter = $nameConverter;
    }

    public function setSerializer(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;

        if ($this->decorated instanceof SerializerAwareInterface) {
            $this->decorated->setSerializer($serializer);
        }
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return $this->decorated->supportsNormalization($data, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        return $this->decorated->normalize($object, $format, $context);
    }

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $this->decorated->supportsDenormalization($data, $type, $format);
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        // denormalizing of the IRI string into resource object (for example as constructor argument)
        if (is_string($data) && !isset($context[AbstractObjectNormalizer::OBJECT_TO_POPULATE])) {
            if ($item = $this->denormalizeFromIri($data, $context)) {
                return $item;
            }
        }
        // append identifiers to the $data from object to populate
        // this is only needed when deserializing $class is differ from
        // the class of of the object to populate
        if (is_array($data) && isset($context[AbstractNormalizer::OBJECT_TO_POPULATE])) {
            $data = $this->appendIdentifiers($data, $context);
        }

        return $this->decorated->denormalize($data, $class, $format, $context);
    }

    private function denormalizeFromIri(string $data, array $context)
    {
        try {
            return $this->iriConverter->getItemFromIri($data, $context + ['fetch_data' => true]);
        } catch (InvalidArgumentException $e) {
            return null;
        }
    }

    /**
     * @param array $data
     * @param array $context
     *
     * @return array
     *
     * @throws ExceptionInterface
     */
    private function appendIdentifiers(array $data, array $context): array
    {
        if (!$this->serializer instanceof NormalizerInterface) {
            throw new \LogicException(\sprintf(
                'The injected serializer must be an instance of %s.',
                NormalizerInterface::class
            ));
        }

        $identifiers = $this->identifiersExtractor->getIdentifiersFromItem($context[AbstractNormalizer::OBJECT_TO_POPULATE]);
        foreach ($identifiers as $name => $value) {
            $name = $this->nameConverter->normalize($name);
            if (!is_scalar($value)) {
                $value = $this->serializer->normalize($value);
            }
            if (!isset($data[$name])) {
                $data[$name] = $value;
            }
        }

        return $data;
    }
}

```

**Comment by ghettovoice** [comment]
My mistake was definition of `serializer.normalizer` tag on the decorator service.
According to [v2.4.0-beta.2](https://github.com/api-platform/core/releases/tag/v2.4.0-beta.2) release notes priorities of normalizers were updated and my decorator definition don't work now.

Actually the correct decorator definition should be without tag redefine

```yml
   app.serializer.normalizer.item:
        class: App\Serializer\ItemNormalizer
        decorates: api_platform.serializer.normalizer.item
        arguments:
            - '@app.serializer.normalizer.item.inner'
            - '@api_platform.iri_converter'
            - '@api_platform.identifiers_extractor'
            - '@api_platform.name_converter'
```
Now all works as expected.

**Comment by UrGuardian4ngel** [comment]
Ran into this exact same problem earlier today!

No code changes, no decorations, no custom normalizers.
It just stopped working mysteriously.

Did a `git bisect`. Noticed it started failing since commit d7885e7f4d8e08217baf2ceb95cbde3775291e2c with following message:

```
Unable to render this definition

The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```

When I checkout **one commit before** (bb30d60787e50b94f89ff10c3b38116eda7a9054), it's working again.

Any ideas? Does this need a new ticket? ...?
Will try to debug (or reproduce) this myself later on, if there are no other known solutions yet.

**Comment by Rebolon** [comment]
@UrGuardian4ngel you don't overload any native services in your services.yaml ?

**Comment by UrGuardian4ngel** [comment]
Overloading? Not in the sense of "decorating" or "overwriting", at least... 🤔

Well, it turned out that we had strapped in Symfony's `Reflection`-based `PropertyNormalizer` in that project, as we are using non-anemic data models (without getters / setters).

It's default priority of `0` broke the API documentation home page (`/api`) in `v2.4.0-beta.2` with above-mentioned error.
Adding a negative priority of `-1000` (or to be exact: `-890`, to 'complete' API Platform's sequence) made things work again for us... 👌

--- 
P.S.: Have to admit, it's a little bit counter-intuïtive with the release notes:

> If you have custom normalizer we recommend to use **positive** priorities.

😉

**Comment by erop** [comment]
I have the same issue while overriding "dunglas_doctrine_json_odm.serializer" service in `services.yaml` as written [here](https://packagist.org/packages/dunglas/doctrine-json-odm) in clause **How can I add additional normalizers?** Nothing differs in `services.yaml` from service definition as in `@DoctrineJsonOdm/src/Bundle/Resources/config/services.xml`  Strange but wiping out the snippet from `services.yaml` immediately restores Swagger UI to its normal state.

**Comment by erop** [comment]
The problem was in missed in `services.yaml` `autoconfigure: false`. It was an essential in my case.

**Comment by eerison** [comment]
I'm facing the same issue :/ 

<img width="1296" alt="Screenshot 2022-02-05 at 18 05 13" src="https://user-images.githubusercontent.com/6358755/152659025-36a73152-6f85-427a-88b2-b321bb64559a.png">


```
name     : api-platform/core
descrip. : Build a fully-featured hypermedia or GraphQL API in minutes!
keywords : Hydra, JSON-LD, api, graphql, hal, jsonapi, openapi, rest, swagger
versions : * 2.7.x-dev, * dev-main
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://api-platform.com
source   : [git] https://github.com/api-platform/core.git 119b05b631aae94a922838c6c3ba2f64618210a5
dist     : [zip] https://api.github.com/repos/api-platform/core/zipball/119b05b631aae94a922838c6c3ba2f64618210a5 119b05b631aae94a922838c6c3ba2f64618210a5
path     : /app/vendor/api-platform/core
names    : api-platform/core
```

```
PHP 8.1.0 (cli) (built: Dec  2 2021 12:28:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```
