### ISSUE TITLE
[GraphQL] `clientMutationId` should not be required

### ISSUE THREAD

**Issue by lukasluecke** [api-platform/core#2570]
Right now the generated GraphQL schema requires a `clientMutationId` for every mutation. This is based on the original Relay (Classic) specification, but depending on your client (Relay Modern, Apollo, ..) might not be required, or even useless (and therefore leads to clutter in client code).

I propose adding a configuration option that allows to specify, wether you want this to be generated at all, and wether it should be required.

**Comment by alanpoulain** [comment]
Have you an example of it causing an issue in a tool?

**Comment by lukasluecke** [comment]
As a reference, the [current Relay specification](https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs) contains the following:
> In particular, all mutations must expose exactly one argument, named input. This argument’s type must be a NON_NULL wrapper around an INPUT_OBJECT. That input object type **may** contain an argument named clientMutationId. **If provided**, that argument must be a String. That argument **may** be non‐null.

**Comment by alanpoulain** [comment]
Maybe it should just be nullable then?

**Comment by lukasluecke** [comment]
@alanpoulain It doesn't cause any issues with tools per se, it gets handled just like any other argument.

The issue is that it might not provide any value, yet you are required to provide that argument in every mutation you write.

**Comment by alanpoulain** [comment]
I think we can consider it a bug and make a PR for 2.4. Do you want to do it?

**Comment by lukasluecke** [comment]
I'll make the PR 👍

**Comment by alanpoulain** [comment]
Fixed in 2.4.
