### ISSUE TITLE
PurgeHttpCacheListener load old content on preUpdate

### ISSUE THREAD

**Issue by jewome62** [api-platform/core#2572]
Version : api-platform/core - dev-master 7e9655a
Into composer.json : "api-platform/core": "2.4.x-dev"

I have a relation OneToOne

```php

class Author {
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Media\AuthorAvatar", inversedBy="author", cascade={ "remove"})
     */
    protected $avatar;
}
```

```php
class AuthorAvatar
{
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User\Author", mappedBy="avatar", cascade={"persist"})
     */
    protected $author;

    public function setAuthor(Author $author): self
    {
        $author->setAvatar($this);
        $this->author = $author;
        return $this;
    }
```
Controller with ParamConverter for map Author
```php
 public function __invoke(Request $request, AuthorAvatar $data, Author $author): AuthorAvatar
    {
        $uploadedFile = $request->files->get('file');

        if (!$uploadedFile) {
            throw new BadRequestHttpException('"file" is required');
        }

        $data->setFile($uploadedFile);
        $data->setAuthor($author);

        return $data;
    }
```

Into a custom controller (but with event api-platform enable), i create a new `AuthorAvatar` and set `Author`  with existing Author `$newAvatar->setAuthor($existingAuthor)` (`Author` has a old `AuthorAvatar`)

In this context, PurgeHttpCacheListener on preUpdate of Author will load old `AuthorAvatar` to get Iri.
And refresh `Author` with old value.

If i disable purge varnish, i have not this problem.

**Comment by teohhanhui** [comment]
Sorry, I've spent a long time trying to understand this, but it's unclear to me. Could you provide a project t

**Comment by bendavies** [comment]
hard to tell from the issue, but probably **something** to do synchronizing bidirectional collections when updating one side of the relation: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#synchronizing-bidirectional-collections

this is pretty hard to do for a bi directional onetoone

suspect userland code is not doing this correctly.

**Comment by jewome62** [comment]
@teohhanhui I can't share you this private project. But i can see on Friday morning ?

@bendavies I verify this with @vincentchalamon . And all are good before pre-Update event into lifecycle into doctrine. After PurgeHttpCacheListener the entity are corrupted with old data

**Comment by bendavies** [comment]
a reproducer would be needed 👍
