### ISSUE TITLE
[Question] What are the Pros and Cons of having a "ChainIriConverter" just like ChainDataPersister/Provider?

### ISSUE THREAD

**Issue by llupa** [api-platform/core#2577]
Recently in my team we are developing a resource that exists only as a subresource. While I know that insert operations are not supported for subs. We noticed that with a minimal set up for a custom operation most of the _stuff_ worked automatically. 

Except for the `WriteListener` in which case failed because could not generate IRI for item. (Data was persisted correctly). 

We were wondering if there is anything against having a `supports` method in the `IriConverterInterface` (and the other implementations) so that we could define a custom IriConverter per resource / subresource / operation ? 

Is there anything that makes this technically very hard / impossible? There was no time for it?

**Comment by soyuka** [comment]
You can already decorate the IriConverter, use your own if needed and call ours if not. Would that work?

**Comment by llupa** [comment]
We are trying to see if we can assign a dedicated WriteListener to this resource and we are looking into the custom iri converter too. If we find something that looks useful we might propose it as an example for the docs (or even just here).

**Comment by llupa** [comment]
@soyuka I am not sure if this is the right place for this kind of topic. But I would really appreciate it to have also some _insider_ view on this. 

So we have Model `Movie` that relates as a one to many with `Review`. Now the business logic is that you cannot create a review first. A review has to be created under a movie. This part is straight forward to understand. 

So there is a `movie.yaml` somewhere specifying the setup for the endpoints and a subresource for `reviews`. We also setup a `review.yaml` where we overwrote the operations so that the Action class calls a Handler/Validator to make sure the relationship is maintained correctly and more (unrelated to the question). 

For now we decided to have the path set to: `/movies/{pid}/reviews/{id}` for PUT / GET (item) and DELETE. As a side note, having `{id}` in this case makes the framework load the correct item and we have some validator `for parent-id`. 

The only "issue" is the IriConverter, as far as I could tell it is _global_. We tried to add a decorator and did a simple `instanceof` for the cases that concerned us and it works. The IRIs are generated correctly and they are read correctly. But this seems counterproductive since we know many of our models exist only under others which would make us go for a Factory-Strategy solution in our Decorator. 

We are also thinking of making a fork and try out with a ChainIriConverter solution so subresources can be responsible for their own IRIs. 

I see both solutions as valid, not sure if I am missing something? The chain looks much more preferable and now we are back to the initial question. Is there something that will backfire painfully? If it proves successful we would also like to contribute, but at the same time, we don't want to work on something that doesn't fit.

**Comment by soyuka** [comment]
Both solution look fine, I'm not really sure that we want write support for subresources in api platform (subresources are already causing issues because people misuse/overuse them sometimes :p). 
We may discuss it if you have a proposal, indeed the work you did looks good! WDYT @api-platform/core-team ?
 
> Is there something that will backfire painfully?

You mean because you decorated the IriConverter? No, unless we break things by inadvertence you should be just fine.

**Comment by soyuka** [comment]
identifiers have evolved a lot since then see Architectural decision records.
