### ISSUE TITLE
FilterEagerLoadingExtension returns wrong resultset when using composite keys

### ISSUE THREAD

**Issue by idsplus-carlos** [api-platform/core#2580]
FilterEagerLoadingExtension returns excess results when using composite keys.

This is due to 2 problems with the following code [(FilterEagerLoadingExtension in master):](https://github.com/api-platform/core/blob/d86f95613f7c080e8bb3112c938610d7714192b8/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L79)

```
// Because Doctrine doesn't support WHERE ( foo, bar ) IN () (https://github.com/doctrine/doctrine2/issues/5238), we are building as many subqueries as they are identifiers
foreach ($classMetadata->getIdentifier() as $identifier) {
	if (!$classMetadata->hasAssociation($identifier)) {
		continue;
	}
	$replacementAlias = $queryNameGenerator->generateJoinAlias($originAlias);
	$in = $this->getQueryBuilderWithNewAliases($queryBuilder, $queryNameGenerator, $originAlias, $replacementAlias);
	$in->select("IDENTITY($replacementAlias.$identifier)");
	$queryBuilderClone->andWhere($queryBuilderClone->expr()->in("$originAlias.$identifier", $in->getDQL()));
	$changedWhereClause = true;
}
```

1. There's a loop generating a new JOIN for each ID in the composite key, in the form of `foo IN (JOIN1) AND bar IN (JOIN2) AND baz IN...`. However, this produces incorrect results since it assumes that ANDing the IDs from the multiple joins is the same as `WHERE ( foo, bar ) IN ()`, which is not.
  As a counterexample, let's say we have the following set:
  `(foo, bar, prop1): (1, 1, 'a'), (1, 2, 'b'), (1, 3, 'b'), (2, 2, 'a'), (2, 3, 'b')`
  Filtering on property `prop1 = 'b'` results in the following composite ids `(foo, bar): (1, 2), (1, 3), (2, 3)`
  With multiple joins, this would be expressed as `foo IN (1, 2) AND bar IN (2, 3)`, which would match the correct results, but also `(2, 2)` that shouldn't be on the set.
  We have a patch working right now that replaces the JOINS with an EXISTS that works as expected when filtering, but sadly it doesn't eager-load as expected.
2. When multiple composite keys exists, metadata only returns hasAssociation($identifier) as true for the first identifier of the composite key. This results in having only a JOIN even when there's a composite identifier. I'm not sure this happened in our case because wrong mappings, but there didn't seem to be a problem with them before.

**Comment by soyuka** [comment]
Composite keys aren't battle-tested here. It would be awesome if you could patch this!
