### ISSUE TITLE
Not possible to declare operation filters via annotations

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#2587]
It's not possible to declare operation filters via annotations

For example:

```
 * @ApiResource(
 *   collectionOperations={"get",
 *     "search"={"filters"={
 *         @ApiFilter(MatchFilter::class, properties={"description", "title", "keywords"}),
 *         @ApiFilter(OrderFilter::class, properties={"created"="desc"}, arguments={"orderParameterName"="order"})
 *     }}
 *   }
 * )
```

If you want to work on this I started here: https://github.com/soyuka/core/tree/fix-filter-per-operation

**Comment by Taluu** [comment]
In the docs, it is said it supports the syntax `"filters"={FilterName::class}`, but doesn't look like it is implemented ?

Anyway, I'd rather use your syntax (with the nested `@ApiFilter` annotation) if it's still a go. :}

**Comment by jamesisaac** [comment]
> "filters"={FilterName::class}

This syntax mentioned in the docs does seem to be implemented, however, how are you able to select properties with this syntax?  @soyuka any chance you could show how the example you wrote can be implemented in that syntax please (if it's possible)?  The following didn't work (complains that `filter` must be a string):

```
 * @ApiResource(
 *   collectionOperations={"get",
 *     "search"={"filters"={
 *         MatchFilter::class={"properties"={"description", "title", "keywords"}},
 *         OrderFilter::class={"properties"={"created"="desc"}, "arguments"={"orderParameterName"="order"}},
 *     }}
 *   }
 * )
```

**Comment by soyuka** [comment]
#2400
