### ISSUE TITLE
[v2.4.0-beta] RangeFilter MongoDB fails

### ISSUE THREAD

**Issue by sylev** [api-platform/core#2595]
I do not fail to run the mongodDB rangeFilter.
1st problem:
It seems to me that there is an inversion of the parameters gte and lte in this line
File: ApiPlatform \ Core \ Bridge \ Doctrine \ MongoDbOdm \ Filter \ RangeFilter

Line 81: $ aggregationBuilder-> match () -> field ($ matchField) -> gte ($ rangeValue [0]) -> lte ($ rangeValue [1]);

2nd problem:
Values ​​are not treated as numeric values ​​in the following file:
ApiPlatform \ Core \ Bridge \ Doctrine \ Common \ Filter \ RangeFilterTrait
Here is how I treated this problem but it may not be the right solution:
/ **
* Normalize the value.
* /
private function normalizeValue (string $ value, string $ operator)
{
   if (! is_numeric ($ value)) {
       $ this-> getLogger () -> notice ('Invalid filter ignored', [
           'exception' => new InvalidArgumentException (sprintf ('Invalid value for' [% s] ', expected number', $ operator)),
       ]);

       return null;
   }

   return $ this-> get_numeric ($ value);
}

/ **
* Get the numerical value
* @param $ value
* @return int | float | null
* /
private function get_numeric ($ value) {
   if (is_numeric ($ value)) {
       return $ value + 0;
   }
   return null;
}

**Comment by antograssiot** [comment]
Indeed the first problem seems a bug to me, would you mind sending a PR ?

**Comment by sylev** [comment]
If you want. What do you think about the second problem?

**Comment by alanpoulain** [comment]
@sylev You're right about the second issue. The Behat tests are not written correctly, that's why I didn't detect it before. I'm fixing it, thank you for reporting it.

**Comment by alanpoulain** [comment]
Will be solved in 2.4.
