### ISSUE TITLE
Filter on sub nested property

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/core#2602]
Supposing we have an entity like this
```yaml
offer
    products
        categories
            id
            enabled
```
Can I filter with something like `/offer?boolean[product][category.enabled]=true` ?

**Comment by jewome62** [comment]
Issues on github are for bugs and feature asking.

For help in future, see : https://api-platform.com/support/

For your answer : https://api-platform.com/docs/core/filters/#filtering-on-nested-properties

**Comment by vasilvestre** [comment]
I got problem reading documentation due to anchor problem. For those wondering, it's simpler.
/offer?products.categories.enabled=true is what I want.
(Current state is that generated DQL do not work but it may be because of outdated apip version)

**Comment by vasilvestre** [comment]
https://github.com/api-platform/core/issues/2645
