### ISSUE TITLE
DataTransformer does not work for related entity

### ISSUE THREAD

**Issue by trsteel88** [api-platform/core#2610]
I have the following models:

ProjectShot:
    file: ProjectShotFile

ProjectShotFile:
    name: string

I've created a DataTransformer and set an input attribute on the ProjectShotFile. However, when saving "ProjectShot", the transformer doesn't fire because $context['input']['class'] is null.

From the DTO documentation it has a check for "null !== ($context['input']['class'] ?? null)".

If I put the input on ProjectShot it would work. But I want to do the transformer directory on ProjectShotFile (which is coming from an Abstract class that I want to repeat this transformer on).

Wondering if there is actually a way to ALWAYS do a data transformation for a specific entity (and I don't actually have to specify and input/output parameter)?

**Comment by teohhanhui** [comment]
@trsteel88 Which version are you on? Could you try the `2.4` branch?

**Comment by soyuka** [comment]
I'm not sure that you need any input here. An input class is a different representation of a resource that you'll have to transform. Here it looks like you just have a relation that is not a resource which is fine on 2.4.

Can you detail what you want to do?

**Comment by soyuka** [comment]
Closing, feel free to come back to us if needed.
