### ISSUE TITLE
api:swagger:export in https://editor.swagger.io/

### ISSUE THREAD

**Issue by coudenysj** [api-platform/core#2616]
When I paste the output of `bin/console api:swagger:export -y -o swagger.yml` in https://editor.swagger.io/, I get a lot of warnings.

Does this have something to do with versions, or with the combination of Hydra?

**Comment by dunglas** [comment]
Can you provide your swagger definition please? It will help a lot to debug.

**Comment by coudenysj** [comment]
Hi @dunglas, if I investigate a bit further (and test the swagger.yml from the demo project), I get a lot of these errors:

```
Semantic error at paths./books.get.responses.200.schema.items.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
Jump to line 30
```

Line: `$ref: '#/definitions/Book-book:read'

The rest from the issues are probably my own fault.

**Comment by hosseinsalemi** [comment]
Same problem. How to solve this?
