### ISSUE TITLE
The need for cache warmers

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#2618]
Hello,

Currently, Api Platform does not ship with any cache warmers.
This typically makes the first request to each route slow as a cache is primed on demand. (hitting one api route does not prime all routes, so the effect is compounded).

I've just been hit by a stampede in production because of this, causing a small outage, so not ideal.

The following classes are candidates for being warmed:

- [CachedDocumentMetadataFactory](https://github.com/api-platform/core/blob/master/src/Bridge/Elasticsearch/Metadata/Document/Factory/CachedDocumentMetadataFactory.php)
- [CachedPropertyMetadataFactory](https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php) *
- [CachedPropertyNameCollectionFactory](https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/CachedPropertyNameCollectionFactory.php) *
- [CachedResourceMetadataFactory](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/Factory/CachedResourceMetadataFactory.php)
- [CachedResourceNameCollectionFactory](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/Factory/CachedResourceNameCollectionFactory.php)
- [CachedRouteNameResolver](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/CachedRouteNameResolver.php)
- [CachedSubresourceOperationFactory](https://github.com/api-platform/core/blob/master/src/Operation/Factory/CachedSubresourceOperationFactory.php) *

However, this is not so easy.
The starred (*) factories take an array of `$options`, which are currently not known in the CLI context, and are provided from the router/current request, and will vary per route.

**Comment by teohhanhui** [comment]
Generally speaking, most of the slowness is due to reading from PHPDoc. So, I think it makes sense if we could have a specialized cache for PHPDoc.

**Comment by bendavies** [comment]
That assessment looks correct.
Here is a profile of 1st vs 2nd request (with a warmed production cache)
https://blackfire.io/profiles/compare/2517aaf4-8564-4137-b15c-dec2025568e3...4243edce-efdd-4198-be41-7d77f5a80636/graph

It's a bit hard to look at because of all the decoration, but the majority of the time is spent at `phpDocumentor\Reflection\Types\ContextFactory::createForNamespace`

**Comment by soyuka** [comment]
relevant discussion: https://github.com/api-platform/core/issues/2593

**Comment by bastnic** [comment]
Yep @soyuka, same problems. 

In dev mode, `phpDocumentor\Reflection\Types\ContextFactory` is called too much time because all the stack is made to be cacheable in single switch mode. The same file is read again again and again. Just adding a static cache per default reduce every call in dev mode and the first call in prod mode.

**Comment by kiler129** [comment]
I will just leave it here:

![image](https://user-images.githubusercontent.com/1227834/54617894-1a33d180-4a30-11e9-92ba-fabfb9e5a45a.png)
![image](https://user-images.githubusercontent.com/1227834/54617943-2d46a180-4a30-11e9-81e8-a6bf82d854a3.png)


Warmers are really needed ;)

**Comment by soyuka** [comment]
So, this is the first call? Then it's cached? Thanks!

**Comment by bastnic** [comment]
never cached without `api_platform.metadata_cache` set to true. Cf #2593, in my case it's 1600 calls for only 78 files. Just adding a simple static cache in the class show the enormous performance gain.

**Comment by teohhanhui** [comment]
IMO we should use cache in dev. I plan to take a look very soon.

**Comment by teohhanhui** [comment]
Hmm... Symfony PropertyInfo's `PhpDocExtractor` already has a local cache for `DocBlock`s: https://github.com/symfony/symfony/blob/v4.2.4/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php#L36-L39

**Comment by bastnic** [comment]
FYI, https://github.com/symfony/symfony/pull/32188 got merged, so phpdocextractor is no more an issue since Symfony 4.4

**Comment by dkarlovi** [comment]
Note: having cache warmers is also a requirement for running in read-only environments, which is the direction Symfony is trying to move toward.

**Comment by tdashton** [comment]
Is there any update on this request / issue? We are running into the same circumstances here and would love to be able to warm up our apiPlatform caches before deploying to our read-only environment.

**Comment by naxo8628** [comment]
+1 Here!

**Comment by soyuka** [comment]
IMO `cache:clear` does the job just fine no? I'll close this for now feel free to ping if needed.
