### ISSUE TITLE
Doctrine\Common\Util\Inflector is deprecated 

### ISSUE THREAD

**Issue by red-smeg** [api-platform/core#2626]
can Doctrine\Common\Util\Inflector be removed from 

Bridge/Symfony/Routing/RouteNameGenerator.php
GraphQI/Type/SchemaBuilder.php
Operation/DashPathSegmentNameGenerator.php
Operation/UnderscrorePathSegmentNameGenerator.php

**Comment by soyuka** [comment]
Hi,

we're using the Doctrine\Common\Inflector\Inflector namespace ?

**Comment by teohhanhui** [comment]
@red-smeg Are you looking at an old version? 2.2? It's not supported anymore.

**Comment by raziel057** [comment]
I also have lot of deprecations as it's still used as you can see on "master":

- [UnderscorePathSegmentNameGenerator.php](https://github.com/api-platform/core/blob/master/src/Operation/UnderscorePathSegmentNameGenerator.php)
- [DashPathSegmentNameGenerator.php](https://github.com/api-platform/core/blob/master/src/Operation/DashPathSegmentNameGenerator.php)

Deprecation: https://github.com/doctrine/inflector/commit/fc14fdd061c210afcb50d76f2ff9db795a807e26

**Comment by dunglas** [comment]
I suggest to switch to the Symfony String component instead.

**Comment by derrabus** [comment]
> I suggest to switch to the Symfony String component instead.

But that would mean dropping php 7.1 support, wouldn't it?
