### ISSUE TITLE
ItemNormalizer::updateObjectToPopulate should use getItemIriFromResourceClass instead of getIriFromResourceClass

### ISSUE THREAD

**Issue by Inari-Whitebear** [api-platform/core#2632]
Maybe I'm wrong with this, but
https://github.com/api-platform/core/blob/master/src/Serializer/ItemNormalizer.php#L98
seems to fetch the collection route and stick an identifier on. Shouldn't it instead use `getItemIriFromResourceClass` ( https://github.com/api-platform/core/blob/master/src/Api/IriConverterInterface.php#L59 ) to fetch the route for the item directly with the identifier?

**Comment by dunglas** [comment]
Indeed (this code is probably older than the introduction of `getItemIriFromResourceClass`). Would you mind opening a pull request?

**Comment by soyuka** [comment]
let's follow this in #3609
