### ISSUE TITLE
subResource controller not work

### ISSUE THREAD

**Issue by lichnow** [api-platform/core#2634]
I set the SubResource Controller,but it not work,has any error of the code?
```
 * @ApiResource(
 *     collectionOperations={
 *         "api_categories_articles_get_subresource"={
 *             "method"="GET",
 *             "normalization_context"={"groups"={"list"}},
 *             "controller"=Blog\GetArticle::class
 *         },
 *         "get"={
 *             "normalization_context"={"groups"={"list"}}
 *         },
 *         "post"={
 *             "access_control"="is_granted('blog.article.create',object)",
 *         }
 *     },
 *     itemOperations={
 *         "get",
 *         "put"={
 *             "access_control"="is_granted('article.edit',object)",
 *         },
 *         "delete"={
 *             "access_control"="is_granted('article.remove',object)",
 *         },
 *     }
 * )
```
and controller
```
class GetArticles
{
    public function __invoke(Request $request, ArticleRepository $articleRepo,Category $data): Paginator
    {
        $page = (int) $request->query->get('page', 1);
        return $articleRepo->getPaginated($page,$articleRepo->getFromTreeCategory($data));
    }
}
```

**Comment by lichnow** [comment]
@er1z run the api point after set the controller,nothing happened,no any error.if I set a controller which not exits,it also no error and no behavior. And I set it to `subresourceOperations`, It still has no reaction.
But I change `api_categories_articles_get_subresource` to be `articles_get_subresource`,and set it to `subresourceOperations`,like this
```
 * @ApiResource(
 *    subresourceOperations={
 *        "articles_get_subresource"={
 *            "method"="GET",
 *            "controller"=GetArticles::class
 *        }
 *    }
 *)
```
api platform give me an error,
```
Catchable Fatal Error: Object of class ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Paginator could not be converted to string
```
![image](https://user-images.githubusercontent.com/1695900/54744298-90d3f900-4c01-11e9-80a6-858c7747ea99.png)

I do the category to be nested tree.and the category id `2` is the child of id `1`,some articles is belongs to category id `2`,but I want to get these articles when fetch category id `1` also.when I custom a controller and route to test the repository method is work fine.but I want to fetch these articles use `subresource api` ,not custom a api point.

so ,"custom controller for subresource not work" this is a bug or unimplemented features?or I must custom a data provider to do it?

**Comment by er1z** [comment]
Think that specifying path manually will simplify things a lot. But separating a problem into a publicily available repository will simplify finding out what's going on.

**Comment by lichnow** [comment]
@er1z so, how to custom a controller for subresource ?

**Comment by lichnow** [comment]
@er1z I solve it,set `api_receive` to be `false`
