### ISSUE TITLE
Swagger documentation incorrect for patch json:api format

### ISSUE THREAD

**Issue by MyDigitalLife** [api-platform/core#2635]
It looks like there are some problems with the generated swagger documentation. It looks like the configuration is not correct for the json:api format. I'm using the following version of the api-platform packages:
* api-platform/api-pack: v1.2.0
* api-platform/core: v2.3.6

I also tested this with v2.4 beta of the core but no changes. 

In the json:api standard its defined that a patch must look like this:
```
PATCH /articles/1 HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "To TDD or Not"
    }
  }
}
```
https://jsonapi.org/format/#crud-updating

My generated documentation has the following example for the body of a patch function:
```
{
  "id": 0,
  "name": "string",
}
```

Its not the same as defined in the standard and is also doesn't work when performing a request. When inputing the the correct format defined in the standard it does work correctly. The problem just to be purely a documentation generation issue and not a functional issue with the api call itself.

In my api_platform config I have only json:api as format:
```
api_platform:
    formats:
        jsonapi:  ['application/vnd.api+json']
    error_formats:
        jsonapi:  ['application/vnd.api+json']
```

Am I forgetting a config somewhere to auto generate the correct swagger documentation? Otherwise is probably a bug or a missing configuration in je Api platform core.

**Comment by peter-gemvision** [comment]
Looking a bit more into this and I can see that #2415 and #2585 already specify that this is a issue and we might be able to fix this with OpenApi v3. I'll close this as this issue is redundant with these issues already existing.

**Comment by MyDigitalLife** [comment]
Looking a bit more into this and I can see that #2415 and #2585 already specify that this is a issue and we might be able to fix this with OpenApi v3. I'll close this as this issue is redundant with these issues already existing.
