### ISSUE TITLE
symfony/orm-pack and api-platform

### ISSUE THREAD

**Issue by wow-apps** [api-platform/core#2636]
API-Platform didn't work with Doctrine if it was installed via Flex.

How to reproduce:

```
symfony new my_project
composer require symfony/orm-pack
composer require api
```

And we got an exception in `CheckExceptionOnInvalidReferenceBehaviorPass.php line 86`:

> The service "api_platform.metadata.property.metadata_factory.cached" has a dependency on a non-existent service "doctrine".

But if we change the order of setup (require api before orm), everything works:

```
symfony new my_project
composer require api
composer require symfony/orm-pack
```

**Comment by Shyroby** [comment]
Same Error. How to solve it?

**Comment by Navds** [comment]
I see that this issue has been closed, how did it get resolved ?
