### ISSUE TITLE
Update uses prefixed id instead of originId

### ISSUE THREAD

**Issue by DenisVorobyov** [api-platform/core#2661]
When initiating update from admin component, PUT request looks like:
{
@context: "/api/contexts/Company"
@id: "/api/companies/49481a25-d948-401b-9fee-12f4d07f0ed3"
@type: "Company"
created_at: "2019-03-25T14:14:49+03:00"
enabled: true
id: "/api/companies/49481a25-d948-401b-9fee-12f4d07f0ed3"
name: "Company name"
originId: "49481a25-d948-401b-9fee-12f4d07f0ed3"
}

And getting error back pointing that server is trying to set id="/api/companies/49481a25-d948-401b-9fee-12f4d07f0ed3"

**Comment by soyuka** [comment]
Your `id` should be read only so that this doesn't happen.

**Comment by DenisVorobyov** [comment]
Thank you. Already got it.

**Comment by teohhanhui** [comment]
But I'm curious why the `id` property is serialized like that? It looks wrong to me?
