### ISSUE TITLE
[RFC] Drop support for PHP 7.1

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#2663]
Proposed version target: 2.5

Active support for PHP 7.1 has already ended on 2018-12-01, and security support will end on 2019-12-01
(see https://www.php.net/supported-versions.php)

Notable new features in PHP 7.2, that may be relevant for API Platform:

https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.object-type
https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.abstract-method-overriding
https://www.php.net/manual/en/function.spl-object-id.php
https://www.php.net/manual/en/reserved.constants.php#constant.php-float-epsilon

**Comment by dunglas** [comment]
+1 but on API Platform 3.0, that will be released after Synfony 5.0.

**Comment by teohhanhui** [comment]
> A new Symfony major version (e.g. 3.0, 4.0) comes out every two years.

https://symfony.com/doc/current/contributing/community/releases.html

That means after 2019-11-xx? I think that's too long to wait.

**Comment by dunglas** [comment]
> That means after 2019-11-xx?

Exactly, because Symfony will not drop 7.1 support before this date, and there are no rushes.

**Comment by teohhanhui** [comment]
It's bad for the maintenance of our code, because we'll always be 2 years behind in terms of the language features that we can utilize, unless Symfony again decides to make the jump earlier, like they did with Symfony 4.1 (more than half a year before PHP 7.0 EOL).

**Comment by soyuka** [comment]
Hehe 3.0 is supporting > 8 only so I can close this
