### ISSUE TITLE
FilterEagerLoadingExtension dependency problem

### ISSUE THREAD

**Issue by strider2038** [api-platform/core#2666]
We have decorated class ResourceClassResolver in our project. After update to v2.4 we have issues with dependency injection of ResourceClassResolver in FilterEagerLoadingExtension

https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L35

I think it is good to use ResourceClassResolverInterface in FilterEagerLoadingExtension instead of conrete final class ResourceClassResolver.

**Comment by antograssiot** [comment]
Indeed my bad, would you ming opening a PR ? 
I can fix it tonight if not...

**Comment by antograssiot** [comment]
Closing as there is an open PR to fix it
