### ISSUE TITLE
MetadataAwareNameConverter is not used unless serializer.name_converter is set in SF.

### ISSUE THREAD

**Issue by ogirardkaliop** [api-platform/core#2677]
Hey guys,

Not sure if this is the right place but the added code in `MetadataAwareNameConverterPass` ( https://github.com/api-platform/core/pull/2562 ) seems wrong to me.

Let me explain:

```
if (1 >= \count($definition->getArguments()) || null === $definition->getArgument(1)) {
       return;
 }
```
This checks for the presence of a second argument and that it's not null. The second argument of `MetadataAwareNameConverter` is the `$fallbackConverter` but the thing is, this `$fallbackConverter` is only set if you define `serializer.name_converter` in `framework.yaml`.

What this mean is, API Platform will not auto-use the `MetadataAwareNameConverter` if you don't define `serializer.name_converter`.
I was expecting it to use it regardless and lost a lot of time finding out why.

Also, I wanted to use both the `MetadataAwareNameConverter` and snake_case but if I follow the docs and set `name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'` in `api_platform.yaml` then I lose the `@SerializedName` behavior.

I think that ApiPlatform should **always** use `MetadataAwareNameConverter` (if available, of course) and use the value of `api_platform.name_converter` to set $fallbackConverter (or set it as the main NameConverter if `MetadataAwareNameConverter` is not available).

This behavior is kinda redundant with the default symfony one with `serializer.name_converter` BUT it allows API-Platform to stay free of a dependency with Symfony (which is what you guys wanted, as per https://github.com/api-platform/core/pull/2523#discussion_r257995961 ).

Cheers.

**Comment by teohhanhui** [comment]
It was reported in https://github.com/api-platform/api-platform/issues/1075
