### ISSUE TITLE
Serializers are no longer applying additional fields

### ISSUE THREAD

**Issue by trsteel88** [api-platform/core#2681]
Serializers no longer appear to be adding additional fields in the latest Symfony version (4.2.5)

Is this an issue with the bundle or Symfony?

While trying to debug the issue, I noticed that the supportsNormalization method no longer receives the object

```php
public function supportsNormalization($data, $format = null)
    {
        dump($data);
        return $data instanceof MyEntity;
    }
```

It only seems to get the attributes on the entity, not the entity itself.

**Comment by teohhanhui** [comment]
@trsteel88 Could you check if https://github.com/api-platform/core/pull/2679 fixes your issue?

Anyway, if we're going to figure this out, you'd need to provide more information. :smile:

**Comment by soyuka** [comment]
Please come back to us if there's still an issue, #2679 should fix this!

**Comment by trsteel88** [comment]
Serializers still don't appear to be working. I've setup a basic repo here: https://github.com/trsteel88/API-Platform-Serializer-Issue

Commands to get up and running

```
- composer install
- bin/console doctrine:database:create
- bin/console doctrine:schema:update --force
- bin/console doctrine:fixtures:load -y
```

Then make a request for /api/projects

The data looks like this:

![Screen Shot 2019-04-11 at 9 41 48 am](https://user-images.githubusercontent.com/869933/55920959-1580c880-5c3e-11e9-993f-6395449dd5a2.png)

This serializer is meant to fire and add additional data to the result: https://github.com/trsteel88/API-Platform-Serializer-Issue/blob/master/src/Api/Serializer/ProjectSerializer.php

**Comment by teohhanhui** [comment]
@trsteel88 You should try with the latest `2.4` branch:

```console
$ composer require 'api-platform/core@2.4.x-dev'
```

**Comment by trsteel88** [comment]
That line doesn't actually work:

```
[InvalidArgumentException]                                                   
Could not find a matching version of package api-platform/core@2.4.x-dev. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  
```

Running the following allows an install. But it doesn't fix the problem. The serializer still isn't firing

```composer require api-platform/core ~2.4@dev```

I pushed that composer update on the repo: https://github.com/trsteel88/API-Platform-Serializer-Issue

**Comment by teohhanhui** [comment]
Sorry for the wrong syntax. It's supposed to be `:` before the version constraint.

**Comment by teohhanhui** [comment]
@trsteel88 If you could help us add a failing Behat test to our test suite, that'd be much appreciated.
