### ISSUE TITLE
[RFC] Dealing with plain PHP Api Resource

### ISSUE THREAD

**Issue by joelwurtz** [api-platform/core#2683]
We got an app where we would expose a referential for our users through our API (using APIP)

We have something like this:

```php
/**
 * @ApiResource
 */
abstract class FooReferential {
    abstract public function getId(): string;
    abstract public function getName(): string; 

   ...
}

final class FooReferentialItem1 extends FooReferential {
    ...
}

final class FooReferentialItem2 extends FooReferential {
    ...
}
```

Then we got a DataProvider where we inject all of this class and which allows to APIP to correctly get a collection.

Getting a collection works nicely, however other use cases does not work:

 * Getting a single item seems to work weirdly: adding an `@id` / `@context` on some properties
 * When having another Resource that use one of those item, class resolver get the final class (the item) and not the parent class which is the correct resource class. So this fails to correctly convert the item to an iri item.
 * Same as before when trying to post an entity with a reference to a referential item

I'm wondering if this is an use case that is supported or that you want to support: we want to expose a referential through an API where the data are in plain PHP (no Doctrine / Mongodb / ...)

IF that the case will do some PRS to try to support this is an better way in the future.

**Comment by soyuka** [comment]
>When having another Resource that use one of those item, class resolver get the final class (the item) and not the parent class which is the correct resource class. So this fails to correctly convert the item to an iri item.

You expect the resource class to be `FooReferential` not the implementation itself? This should indeed work, if not it's a bug. May also be related to https://github.com/api-platform/core/issues/2609

**Comment by joelwurtz** [comment]
> You expect the resource class to be FooReferential not the implementation itself?

Yes, Actually IriConverter resource class resolver do a `get_class` without checking is this class is a resource (i'm on 2.3 FYI, don't know if this change something)

**Comment by Nek-** [comment]
@joelwurtz fixing this one will probably solve your problems or at least a part of them: https://github.com/api-platform/core/issues/2609 (currently working on).

**Comment by teohhanhui** [comment]
Can you verify that #2797 fixes the problem? :smile:
