### ISSUE TITLE
Nested collection in graphql mutation

### ISSUE THREAD

**Issue by matlow** [api-platform/core#2720]
Hello
I try to create an entity with linked items with graphql.
Does api-platform support posting an entity and nested collection in a single graphql mutation query ?
I can't find example in `api-platform/core/features/graphql/mutation.feature`
Do i have to make a custom query ?
thx

**Comment by matlow** [comment]
I got my responses here : https://github.com/api-platform/core/pull/1886 and https://github.com/api-platform/core/issues/1964

**Comment by alanpoulain** [comment]
Closing this issue then.
