### ISSUE TITLE
SearchFilter not working with GraphQL ?

### ISSUE THREAD

**Issue by Isengo1989** [api-platform/core#2724]
I am using the SearchFilter Class on kw

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Annotation\ApiFilter;

/**
 * @ApiResource
 * @ORM\Entity
 */
class Availability
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var int
     * @ApiFilter(SearchFilter::class, strategy="exact")
     * @ORM\Column(name="kw", type="integer", nullable=false)
     */
    public $kw;
```

It works fine on REST but not on GraphQL, because it is returning the full list

![Auswahl_427](https://user-images.githubusercontent.com/8600299/55911205-69f55b00-5be0-11e9-9597-bb2e53dcb5d5.jpg)

**Comment by lukasluecke** [comment]
SearchFilter works fine for me on (on a `string` column). Maybe try using `NumericFilter`, since you are using an `integer` column?

**Comment by alanpoulain** [comment]
It should work with integers though.

**Comment by davidgerth** [comment]
SearchFilter does not work for integer columns here. If I use NumericFilter, it works.

**Comment by alexfauquette** [comment]
I had the same issue. The first filter work with REST and GraphQL. The second one works only with REST
```
@ApiFilter(NumericFilter::class, properties={"eleve.id": "exact" })

@ApiFilter(SearchFilter::class, properties={"eleve.id": "exact" })
```

**Comment by alanpoulain** [comment]
Solved by https://github.com/api-platform/core/pull/4295.
