### ISSUE TITLE
Cannot validate values of type "NULL" automatically

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#2731]
When calling a collection post operation and if forgot to include a body then the api should handle this gracefully and return a 400 error instead of 500.

Currently it tries to validate "null" because controller result is null and symfony validator obviously doesn't like it.

Response from api:
```
{  
   "@context":"\/contexts\/Error",
   "@type":"hydra:Error",
   "hydra:title":"An error occurred",
   "hydra:description":"Cannot validate values of type \u0022NULL\u0022 automatically. Please provide a constraint."
}

```

**Comment by soyuka** [comment]
Duplicate: https://github.com/api-platform/core/issues/1282

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/pull/2757

**Comment by jsawicki-internetcompany** [comment]
I had the same problem, and solved it by disabling the validation with `validate=false` in the custom operation in entity. 

```
"my_custom_operation"={
 *              "input"=MyCustomInput::class,
 *              "method"="POST",
 *              "path"="/an_entity/something",
 *              "controller"=MyCustomAction::class,
 *              "validate"=false,
 *              "normalization_context"={
 *                  "groups"={
 *                      "groupA:read",
 *                  }
 *              },
 *              "denormalization_context"={
 *                  "groups"={
 *                      "groupB:update",
 *                  }
 *              },
 *              "validation_groups"={
 *                  "Default",
 *                  "groupB:update",
 *              }
 *          },
```

**Comment by ismaellastlevel** [comment]
I had the same problem, because if forgot to return the data after managing it from controller. So I just had to put a return.
from:
`public function postComment($data){
        $this->commentHandler->handleAdding($data);
    }`
to:
`public function postComment($data){
        return $this->commentHandler->handleAdding($data);
    }`
