### ISSUE TITLE
Custom GraphQL mutations without ID not possible

### ISSUE THREAD

**Issue by lukasluecke** [api-platform/core#2736]
SchemaBuilder contains the following code in `getResourceObjectTypeFields`: 
```
$idField = ['type' => GraphQLType::nonNull(GraphQLType::id())];

[...]

if (!$input || 'create' !== $mutationName) {
    $fields['id'] = $idField;
}
```

This makes it impossible to create custom mutations without an ID field (i.e. custom create mutations).

Even when using a custom denormalization context for the mutation, the ID field remains.

**Comment by lukasluecke** [comment]
@alanpoulain Any suggestions / ideas?

**Comment by alanpoulain** [comment]
You mean an ID field in the input type? Yes maybe it should be changed to an allow list instead of a block list.

**Comment by lukasluecke** [comment]
Yes, I want a mutation that does not have an ID field in the input type.

You mean changing `'create' !== $mutationName` to (something equivalent to) `in_array($mutationName, ['update','delete'])`? That would certainly solve my issue.

**Comment by alanpoulain** [comment]
Yes I mean that :slightly_smiling_face:
