### ISSUE TITLE
Ability to modify the vary header

### ISSUE THREAD

**Issue by smatyas** [api-platform/core#2742]
In my use-case I have to implement an authenticated and cached API. Most of the endpoints' results should be cached per user, so the default setting like this works fine:

```yaml
vary: ['Content-Type', 'Authorization', 'Accept-Language']
```

But there are some endpoints that serve common, shared resources, so they shouldn't vary by `Authorization`.

The question is: is there any simple way to modify the `vary` header per operation currently? I know I can implement a listener to modify the response in these cases, but I was looking for something like the [Setting Custom HTTP Cache Headers](https://api-platform.com/docs/core/performance/#setting-custom-http-cache-headers) feature, but for the `vary` header.

If there is no such feature yet, I could help implementing something like what was done in #2288 if you find it useful.

**Comment by teohhanhui** [comment]
Sounds good to me. It should be noted that the `Vary` header can be set multiple times, and that's perfectly valid.

**Comment by soyuka** [comment]
It's not supported yet. Might be a good enhancement indeed.

**Comment by teohhanhui** [comment]
Added in #2758
