### ISSUE TITLE
ReDoc links seem to be wrong

### ISSUE THREAD

**Issue by jon-ht** [api-platform/core#2747]
Hi,

If you navigate through the [documentation with ReDoc UI](https://demo.api-platform.com/?ui=re_doc), API links for resources aren't matching any valid routes.

In the exemple below, the URI shouldn't be `https://demo.api-platform.com/books?ui=re_doc` instead of `https://demo.api-platform.com/?ui=re_doc/books` ?

```diff
- https://demo.api-platform.com/?ui=re_doc/books
+ https://demo.api-platform.com/books?ui=re_doc
```

![image](https://user-images.githubusercontent.com/17051512/56414103-e3004c80-6289-11e9-9cd6-63a4c2655d6e.png)

Or even show the API link without `?ui=re_doc` part ?

**Comment by antograssiot** [comment]
I've opened a [PR on ReDoc](https://github.com/Rebilly/ReDoc/pull/895) as we don't have a way to work around that on our side I think. 
Thanks for reporting anyway @jon-ht

**Comment by antograssiot** [comment]
Closing as it was fixed and released upstream https://github.com/Rebilly/ReDoc/releases/tag/v2.0.0-rc.5
