### ISSUE TITLE
How to make custom action controller.

### ISSUE THREAD

**Issue by Nykilor** [api-platform/core#2756]
Hi ! 
At the start sorry if this a duplicate of any sort, but I read trough other issues but still can't work this out.

I recently started learning how to use the API PLATFORM. I'm strugling to get the know-how to make a custom action controller. In my specific situation I have 3 Entities: 

- `Domain` 
- `LdapUser` 
- `PhoneNumbers` 

The action that i want to accomplish is fetching data from Active Directory by using the access information stored in `Domain` entity and the credentials passed by `$_POST` and then creating the `LdapUser` and `PhoneNumbers` entity with the information it recieves.
I've tried adding this controller to the `Domain` by the `itemOperations` const and made new fields in `Domain` `$login` and `$password` that are not mapped by the ORM by using `@Groups` but this was not to elegant and some fields randomly went `readOnly`. By adding those 2 fields to the entity they get automaticly set. What I would like to archive is a action controller that is not directly connected to the `Domain` entity and is mapped inside the `/api` docs and uses the goodies that API PLATFORM provides. Thanks for any help in this topic.

THE CONTROLLER  

        class LdapGetDataController extends AbstractController {
          /**
           * @Route(
           *     name="LdapGetData",
           *     path="/api/domain/LdapGetData/{id}",
           *     methods={"POST"},
           *     defaults={
           *      "_controller"="\App\Controller\LdapGetDataController::fetch",
           *      "_api_item_operation_name"="LdapGetData",
           *      "_api_resource_class"=Domain::class,
           *      "_api_receive"=true
           *     }
           * )
           */
            public function fetch(Domain $data, ActiveDirectoryFetch $class, Request $request) {
              $response = $class->fetchData($data);

              return $this->json($response);
            }

        }

THE ITEM OPERATION ADDNOTATIONS IN THE DOMAIN ENTITY  

     *  itemOperations={
     *      "get"={"method"="GET"},
     *      "put"={"method"="PUT"},
     *      "delete"={"method"="DELETE"},
     *      "LdapGetData"={
     *        "normalization_context"={"groups"={"ldap"}},
     *        "method"="POST",
     *        "route_name"="LdapGetData",
     *        "swagger_context" = {
     *          "parameters" = {
     *            {
     *              "name" = "id",
     *              "in" = "path",
     *              "required" = "true",
     *              "type" = "integer",
     *              "description" = "Domain ID with whom should the data be fetched"
     *            },
     *            {
     *              "name" = "credentials",
     *              "in" = "body",
     *              "required" = "true",
     *              "schema" = {
     *                 "type" = "object",
     *                 "properties" = {
     *                  "login" = {
     *                    "type" = "string"
     *                  },
     *                  "password" = {
     *                    "type" = "string"
     *                   }
     *                }
     *              }
     *            }
     *          },
     *          "responses" = {
     *            "200" = {
     *              "description" = "The count of changes will be in response."
     *            }
     *          }
     *        }
     *      }
     *   }

**Comment by soyuka** [comment]
Would using an `input` class help for this use case (ie a different representation of your data)?

**Comment by Nykilor** [comment]
By using the `DTO` that's in the docs? But it will be still related to the `ApiResource` of `Domain` and the `Input` will affect the deserialization of all endpoints. I've also tryed to make a new Entity `LdapFetch` with the `$login $password $domain` properties but it requires that the Entity has an ID and I don't need it to perform this task, and the `Input`. The docs for DTO are not too friendly in the examples f.i. on the `Input` there's in the code `new Book()` but the script only imports `BookInput()` class. I'm really trying to figure things out but I'm quite confused by all this. I googled for some tutorials but they only show the basics.

		<?php
		// src/DataTransformer/BookInputDataTransformer.php

		namespace App\DataTransformer;

		use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
		use App\Dto\BookInput;

		final class BookInputDataTransformer implements DataTransformerInterface
		{
			/**
			 * {@inheritdoc}
			 */
			public function transform($data, string $to, array $context = [])
			{
				$book = new Book();
				$book->isbn = $data->isbn;
				return $book;
			}

			/**
			 * {@inheritdoc}
			 */
			public function supportsTransformation($data, string $to, array $context = []): bool
			{
				// in the case of an input, the value given here is an array (the JSON decoded).
				// if it's a book we transformed the data already
				if ($data instanceof Book) {
				  return false;
				}

				return Book::class === $to && null !== ($context['input']['class'] ?? null);
			}
		}

**Comment by soyuka** [comment]
> The docs for DTO are not too friendly in the examples f.i. on the Input there's in the code new Book() but the script only imports BookInput() class

This is definitely a mistake, and yes docs should be improved ^^. 

You can use a different `input` per operation, this way it'll impact the serialization only for this endpoint.

The data transformer will be where you'd  handle the creation of the `LdapUser` based on the `Domain` (I think I got it right?). Then, just return the entity in the `transform` function, it'll be persisted by doctrine afterwards)

**Comment by Nykilor** [comment]
Time went by and I did work things out today :) 
My Code if anyone stumbles across similar issue.
 
Domain Entity:

		<?php

		namespace App\Entity;

		use ApiPlatform\Core\Annotation\ApiResource;
		use App\Dto\LdapFetchInput;
		use App\Controller\LdapFetchController;

		use Doctrine\ORM\Mapping as ORM;

		/**
		 * @ApiResource(
		 *   itemOperations={
		 *      "get"={"method"="GET"},
		 *      "put"={"method"="PUT"},
		 *      "delete"={"method"="DELETE"},
		 *      "LdapGetData"={
		 *        "path"="/domain/ldap_fetch/{id}",
		 *        "controller"=LdapFetchController::class,
		 *        "input"=LdapFetchInput::class,
		 *        "output"=false,
		 *        "method"="POST",
		 *        "swagger_context" = {
		 *          "parameters" = {
		 *            {
		 *              "name" = "id",
		 *              "in" = "path",
		 *              "required" = "true",
		 *              "type" = "integer",
		 *              "description" = "ID of Domain which will be used to fetch the data by."
		 *            },
		 *            {
		 *              "name" = "credentials",
		 *              "in" = "body",
		 *              "required" = "true",
		 *              "schema" = {
		 *                 "type" = "object",
		 *                 "properties" = {
		 *                  "login" = {
		 *                    "type" = "string"
		 *                  },
		 *                  "password" = {
		 *                    "type" = "string"
		 *                   }
		 *                }
		 *              }
		 *            }
		 *          },
		 *          "responses" = {
		 *            "200" = {
		 *              "description" = "The count of changes will be in response."
		 *            }
		 *          }
		 *        }
		 *      }
		 *   }
		 * )
		 * @ORM\Entity(repositoryClass="App\Repository\DomainRepository")
		 */
		final class Domain
		{
			... all the methods and properties 
		}


Controller code: 

		<?php

		namespace App\Controller;
		use App\Dto\LdapFetchInput;

		use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
		use App\Service\ActiveDirectoryFetch;

		class LdapFetchController extends AbstractController {

			private $ad;

			public function __construct(ActiveDirectoryFetch $ad) {
			  $this->ad = $ad;
			}

			public function __invoke(LdapFetchInput $data) {
			  $response = $this->ad->fetchData($data);
			  return $this->json($response);
			}

		}

Input DTO class: 

		<?php

		namespace App\Dto;

		final class LdapFetchInput {
		  /**
		 * @var \App\Entity\Domain
		 */
		  public $domain;
		  public $password;
		  public $login;
		}

Data transformer ( registered in services.yaml like in tutorial ): 

		<?php
		// src/DataTransformer/BookInputDataTransformer.php

		namespace App\DataTransformer;

		use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
		use ApiPlatform\Core\Serializer\AbstractItemNormalizer;
		use App\Entity\Domain;

		final class LdapFetchInputDataTransformer implements DataTransformerInterface
		{
			/**
			 * {@inheritdoc}
			 */
			public function transform($data, string $to, array $context = [])
			{
				$entity = $data;
				$entity->domain = $context[AbstractItemNormalizer::OBJECT_TO_POPULATE];

				return $entity;
			}

			/**
			 * {@inheritdoc}
			 */
			public function supportsTransformation($data, string $to, array $context = []): bool
			{
				if ($data instanceof Domain) {
				  return false;
				}

				return Domain::class === $to && null !== ($context['input']['class'] ?? null);
			}
		}

It works and the `LdapFetchInput` class in the magic method __invoke of the `LdapFetchController` is filled with data the `$domain` variable has the Domain Entity (got to do that by hand in the Data Transformer) in it, and the `$login` and `$password` are getting automatically filled byt the `$data` passed in the `JSON body`.

Reference: 
 * https://api-platform.com/docs/core/dto/#using-data-transfer-objects-dtos (I still think those docs are confusing in some places) 
 * https://api-platform.com/docs/core/operations/#recommended-method 
 * Whole code available in the project I'm working on if anyone want's to check: https://github.com/Nykilor/telefony-srv

**Comment by DanielCambray** [comment]
What is strange, is that finally your dataTransformer doesn't transform anything. It transforms a LdapFetchInput object  into another LdapFetchInput object with some additional info. I understand that it works, by is it good pratices ?

**Comment by soyuka** [comment]
Data transformers must be use for edge cases only, there's often something easier to do using dataprovider / datapersister.
