### ISSUE TITLE
Wrong alias replacement in FilterEagerLoadingExtension

### ISSUE THREAD

**Issue by juffin-halli** [api-platform/core#2763]
Method `ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterEagerLoadingExtension::getQueryBuilderWithNewAliases` uses simple `str_replace($aliases, $replacements, (string) $wherePart)`. So if i have embedded object in my entity being serialized it`s alias could be replaced. 
For exampe: entity have embedded object in property "seo" and field expression would be "o.seo.slug". Using standard alias "o" the code produces "o_a2.seo_a2.slug" expression.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/2221

**Comment by teohhanhui** [comment]
@soyuka I think it's a different issue. And this is much worse.

**Comment by teohhanhui** [comment]
We should not use `str_replace` at all when dealing with a query.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/2793
