### ISSUE TITLE
Normalization / denormalization context using expressions

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#2764]
We should ~track https://github.com/symfony/symfony/issues/31004 and~ implement an easy way to provide `normalization_context` / `denormalization_context` using expression language ~through route `defaults`~, e.g.:

```php
/**
 * @ApiResource(
 *     denormalizationContext={
 *         "default_constructor_arguments"={
 *             "@=resource_class"={
 *                 "token"="@=request.attributes.get('token')",
 *             },
 *         },
 *     },
 * )
 */
```

This should remove the need to write a `SerializerContextBuilder` decorator in many cases.

**Comment by soyuka** [comment]
we don't want to introduce that kind of complexity inside serialization
