### ISSUE TITLE
Demo is returning error 500

### ISSUE THREAD

**Issue by gnumoksha** [api-platform/core#2767]
https://demo.api-platform.com/

![Screenshot from 2019-04-27 14-18-19](https://user-images.githubusercontent.com/696797/56852933-a078e880-68f7-11e9-83d0-612977f166b1.png)

**Comment by soyuka** [comment]
Thanks, this has been fixed recently and we're trying to find a proper fix (closing as dup from https://github.com/api-platform/demo/issues/108)
