### ISSUE TITLE
[JSONAPI] No resource class found for object of type Dto\*Output

### ISSUE THREAD

**Issue by NicoBoos** [api-platform/core#2777]
Hi,

I'm using DTOs in order to provide a different representation on my class for the output. 
Getting data works perfectly fine with JSON, HAL or JSON-LD, but when I want to retrieve a JSON:API response I get the following error:
`No resource class found for object of type \"App\\Dto\\ColumnOutput\".`

Here are the classes I'm using:

My entity: 

```
namespace App\Entity\Column;

use App\Dto\ColumnOutput;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Table(...)
 * @ORM\Entity(...)
 * @ApiResource(
 *     output=ColumnOutput::class
 * )
 */
class Column
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }
}
```

The output DTO:

```
namespace App\Dto;

final class ColumnOutput
{
    public $id;
}
```

And finally the data transformer:

```
namespace App\DataTransformer;

use App\Dto\ColumnOutput;
use App\Entity\Column;

final class ColumnOutputDataTransformer implements DataTransformerInterface
{
    /**
     * @param Column $data
     * @param string $to
     * @param array $context
     *
     * @return ColumnOutput|object
     */
    public function transform($data, string $to, array $context = [])
    {
        $output = new ColumnOutput();
        $output->id = $data->getId();
        return $output;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsTransformation($data, string $to, array $context = []): bool
    {
        return ColumnOutput::class === $to && $data instanceof Column;
    }
}
```

The data transformer is declared in `services.yaml`.

Am I missing something?

PS: My problem seems to be linked to [Using DTO : No resource class found for object of type "App\Dto\***Output". #972](https://github.com/api-platform/api-platform/issues/972) but I'm not sure.

**Comment by soyuka** [comment]
What version of Api Platform do you use?

**Comment by NicoBoos** [comment]
I'm using the api-platform/core v2.4.2.

**Comment by NicoBoos** [comment]
That's completely my fault ... While debugging I edited the API Platform core by error.

All is perfectly working! Sorry for the inconvenience.

**Comment by Spomky** [comment]
Hi @NicoBoos,

I have the same error for some Input/Output classes that are similar to the one you described here above.
I cannot figure out what configuration option could induce that error.

How did you solved that?

**Comment by NicoBoos** [comment]
@Spomky, I changed the code in the Api Platform bundle to try something and I haven't reverted it ...

Removing the modification done in the Api Platform code was enough to fix my issue.
