### ISSUE TITLE
[DTO] [Enhancement] Ensure DataTransformer::transform actually returns an object

### ISSUE THREAD

**Issue by bpolaszek** [api-platform/core#2790]
Hey there!

When switching to an input DTO and then doing a PUT request, I got that weird exception:

```json
{
    "@context": "/api/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Cannot validate values of type \"NULL\" automatically. Please provide a constraint.",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "vendor/symfony/validator/Validator/RecursiveContextualValidator.php",
            "line": 166,
            "args": []
        }
    ]
}
```

It took me something like 2 hours figuring out I just forgot a `return` statement at the end of my `DataTransformerInterface::transform` implementation :sweat_smile::gun:

I know we can't type-hint an `object` return-type on PHP 7.1 (and setting a return type would cause a BC break), but would it make sense to ensure that an object is actually returned at the end of the DTO transformation process?

Thank you!
Heedless Ben

**Comment by soyuka** [comment]
> I know we can't type-hint an object return-type on PHP 7.1 (and setting a return type would cause a BC break), but would it make sense to ensure that an object is actually returned at the end of the DTO transformation process?

I wish we had a generic type and we don't. We used doc blocks to comment the return type, I think that phpstorm would've notified you but I'm not sure. There are no magic solutions for this though :|.

**Comment by bpolaszek** [comment]
@soyuka We have `object` since PHP 7.2 but ApiP is >=7.1, so I was thinking about adding a simple check like:

```php
foreach ($transformers as $transformer) {
    if ($transformer->supportsTransformation($object, $to, $context)) {
        $object = $transformer->transform($object, $to, $context);
        if (!\is_object($object)) {
            throw new \RuntimeException("Play Sad Trombone 🎺");
        }
    }
}
```

**Comment by soyuka** [comment]
Could you provide a PR with that? I see no harm in adding it indeed.

**Comment by bpolaszek** [comment]
PR on its way :-) Should we consider it covered by the absence of regressions or should it be unit-tested as well?

**Comment by soyuka** [comment]
Unit tests never harm :).
