### ISSUE TITLE
Wrong join condition alias replacement in FilterEagerLoadingExtension

### ISSUE THREAD

**Issue by tezvi** [api-platform/core#2792]
This has been already reported and mentioned here #2763, #2221 and #1310. However it seems there is still a problem that results in bad DB performance on my side (using Oracle 12).

The FilterEagerLoadingExtension extension replaces all existing join aliases with new ones, but it does not replace old aliases in complex / custom WITH JOIN conditions.

Given an example with the following SQL query:

```
SELECT a1.*
FROM b AS b1
JOIN c AS c1 ON b1.id = c1.b_id AND c1.foo IN (1,2,3)
```
would result in something like this:
```
SELECT a1.*
FROM b AS b1
JOIN c AS c1 ON b1.id = c1.b_id AND c1.foo IN (1,2,3)
WHERE a1.id IN (
  SELECT a2.id
  FROM b AS b2
  JOIN c AS c2 ON b2.id = c2.b_id AND c1.foo IN (1,2,3)
)
```

The IN clause subquery still refers to old alias "**c1**". This does not impact query results but it impacts query performance. When the real-life query defines multiple JOINS this drastically reduces query performance from 50 ms to 100 seconds in my case.

https://github.com/api-platform/core/blob/796f613b438b135249339f5f20bccbabe987736d/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L150-L155
Notice that old alias **$joinPart->getAlias()** is added to **$aliases** array after the search/replace has been made so it will become available only for further joins, not the current one. Also the new alias should be somehow replaced in **$condition** variable before invoking **QueryBuilderHelper::addJoinOnce()**

**Comment by teohhanhui** [comment]
@tezvi #2763 has not been resolved. It's still an open issue. I don't see any PRs for it yet either.

**Comment by teohhanhui** [comment]
But your issue seems to be https://github.com/api-platform/core/pull/2221 :smile:

It's not related to #2763

**Comment by tezvi** [comment]
Yeah it refers to the same code chunk, but you're right. #2221 is what basically gives me problems 😀

**Comment by tezvi** [comment]
I could try to provide PR but would have to change QueryBuilderHelper::addJoinOnce() call and generate newAlias before adding join.
Do you think this would be a good approach?
It probably won't cover more complex WITH join conditions.
