### ISSUE TITLE
How to disable REST completely?

### ISSUE THREAD

**Issue by danaki** [api-platform/core#2796]
In my project I use GraphQL only and need no to configure REST operations. How do I disable REST and leave GraphQL support only?

**Comment by teohhanhui** [comment]
That makes me sad. :cry:

But on a more serious note, it's not currently possible, because GraphQL uses the generic `application/json` MIME type.

**Comment by dunglas** [comment]
You can register only the GraphQL route, instead of all API Platform routes. Replace the content of `config/routes/api_platform.yml` by:

```
api_platform_graphql:
    resource: '@ApiPlatformBundle/Resources/config/routing/graphql.xml'
```

It should do the trick.

**Comment by dunglas** [comment]
Ideally, we should add a flag to disable REST, and not register the kernel listeners in this case. In the meantime the previous solution should be good enough.

**Comment by lukasluecke** [comment]
@dunglas Your suggestion with the routing modifications sadly doesn't work.

The main issue is that GraphQL still uses the routes for IRI generation, not sure if that can easily be solved by still registering the routes, but not attaching the listeners?

**Comment by teohhanhui** [comment]
@lukasluecke You could try manually overriding some of the built-in event listeners with the same service IDs. But we need to identify which listeners are used by GraphQL, and which are not.

**Comment by teohhanhui** [comment]
Hmm... Actually I think an easier way would be to just do:

```php
<?php
// api/src/Entity/Book.php

use ApiPlatform\Core\Annotation\ApiResource;
use App\Controller\PublishBookAction;

/**
 * @ApiResource(
 *     graphql={
 *         ...
 *     },
 *     collectionOperations={
 *     },
 *     itemOperations={
 *     },
 * )
 */
class Book
{
```

**Comment by lukasluecke** [comment]
Related to #2954 (since this should be the only thing that's currently still required from the REST operations, if you want GraphQL to work)

**Comment by lukasluecke** [comment]
@dunglas Was this not already resolved? (#3079 and api-platform/docs#886)
Maybe we should close #2954 to prevent confusion.

**Comment by dunglas** [comment]
Good catch! To entirely fix this one we should a config option to easily disable everything that can be disabled from the REST subsystem.

**Comment by lukasluecke** [comment]
@dunglas I'll try to get something in for #2946 soonish, which should also make it possible to globally define these operation settings (and then have a doc entry with the exact settings to use) - do you think that would be enough?

**Comment by dunglas** [comment]
Could also be related to https://github.com/api-platform/core/issues/3099 right?

**Comment by lukasluecke** [comment]
@dunglas Ah yes, must've missed that one. I'll create a PR for it this / next week, if no one beats me to it 🙂

**Comment by oleg-brizy** [comment]
> @dunglas Was this not already resolved? (#3079 and [api-platform/docs#886](https://github.com/api-platform/docs/pull/886))
> Maybe we should close #2954 to prevent confusion.

Thanks

I added to all my (graphql) entities

```php
use ApiPlatform\Core\Action\NotFoundAction;

/**
 * @ApiResource(
 *  graphql={...},
 *  collectionOperations={},
 *  itemOperations={ "get"={ "controller"=NotFoundAction::class, "read"=false, "output"=false } }
 * )
 */
```

And it did the trick. Even when I have access to an object the REST `GET /item/{id}` throws 404.

----

I am migrating to graphql-only API and I completely don't need REST. I disable it to get rid of maintaining it (testing, permissions checking).

**Comment by soyuka** [comment]
Indeed the safe way to diable item operations is to do:

```
/**
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *             "method"="GET",
 *             "controller"=NotFoundAction::class,
 *             "read"=false,
 *             "output"=false,
 *         },
 *     },
 * )
 */
```

As documented [at the end of this section](https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations)

**Comment by filip-polic** [comment]
This is my little "hack" for disabling anything other than GraphQL endpoints. Not sure if it's the 100% right way to do so but here is the snippet.

```
<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\KernelEvents;

class KernelRequestSubscriber implements EventSubscriberInterface
{
  public static function getSubscribedEvents()
  {
    return [
      KernelEvents::REQUEST => ['onKernelRequest', 255],
    ];
  }

  public function onKernelRequest(RequestEvent $event)
  {
    if (!$event->isMasterRequest()) {
      return;
    }

    $request = $event->getRequest();
    $path = $request->getPathInfo();
    $allowedPaths = ["/graphql"];

    if ('dev' === $_ENV['APP_ENV']) {
      $allowedPaths = array_merge($allowedPaths, ["/graphql_playground"]);
    }


    if (!in_array($path, $allowedPaths)) {
      throw new NotFoundHttpException("Page not found");
    }
  }
}

```

**Comment by plamenh** [comment]
It's all fine and dandy, guys, but the routes are still generated. Is there a way to disable route generation as well? 20K urls(in our case) are a bit excessive for us.

**Comment by soyuka** [comment]
There's no way to disable that, you could eventually  override the ApiLoader file...

**Comment by plamenh** [comment]
> There's no way to disable that, you could eventually override the ApiLoader file...

Any idea how to leave only the graphql route exposed? When editing ApiLoader I am able to either disable all routes or none.

**Comment by dunglas** [comment]
You can register the GraphQL route "manually" (in config/route.yaml for instance).
IMHO we should provide a configuration option to disable REST entirely. Another approach could be to use the new `defaults` option (available in `master`) to disable every operations except `GET` ones.

**Comment by plamenh** [comment]
A quick update - overriding the ApiLoader file does the job perfectly. I got rid of about 40K completely useless REST urls. Just don't forget to revisit ApiLoader whenever you do 'composer upgrade'.

**Comment by oleg-brizy** [comment]
@plamenh Have you tried [this solution](https://github.com/api-platform/core/issues/2796#issuecomment-606729715)?

In my project `bin/console debug:router` shows only those few GET routes, only one for each entity.

**Comment by plamenh** [comment]
@oleg-brizy I tried that one, but it does not work for me. I need the routes gone, I don't need the routes to point to a 404 page returned by a controller. My cache warm-up with 40K routes was painfully slow and timing out, you can imagine what this means in dev environments (waiting 30+ seconds for timeout on each and every small change in the codebase).

**Comment by kelvin2200** [comment]
> > There's no way to disable that, you could eventually override the ApiLoader file...
> 
> Any idea how to leave only the graphql route exposed? When editing ApiLoader I am able to either disable all routes or none.

Can we have an example on HOW TO override the ApiLoader file?

**Comment by plamenh** [comment]
> > > There's no way to disable that, you could eventually override the ApiLoader file...
> > 
> > 
> > Any idea how to leave only the graphql route exposed? When editing ApiLoader I am able to either disable all routes or none.
> 
> Can we have an example on HOW TO override the ApiLoader file?

I would be interested in that too. We are currently overriding code in place.

**Comment by plamenh** [comment]
This keeps interrupting our deployment flow. I don't think it's ok for this issue to be closed.

**Comment by plamenh** [comment]
2.7.0 update:

You need to comment line 104 here - vendor/api-platform/core/src/Symfony/Routing/ApiLoader.php

**Comment by bdiouih** [comment]
This seems still needed in api-platform/core version 3.2.6 (probably 3.3 also).
You should add these attributes to your entities, in order to disable the REST API,
but keeping only one GET operation (with 404 error):

```
#[ApiResource(
    operations: [
        new Get(
            controller: NotFoundAction::class,
            output: false,
            read: false
        )
    ],
    ...
```

**Comment by brunobg** [comment]
If you get here, see https://github.com/api-platform/core/issues/7915 for a modern fix.
