### ISSUE TITLE
[Question][Doc]How it works and access restrictions

### ISSUE THREAD

**Issue by ShuyqcK** [api-platform/core#2807]
Hello, 
I'm starting a project in api-platform as component and i have a  question.
(feel free to delete the issue if it's not interesting or misplaced)

I ask myself _"how to restrict access using custom voters ?"_ and not found anything in the doc, so I asked our friend Google which told me to look at the issue : [#521](https://github.com/api-platform/core/issues/521) but there are two "contradictory" answers : 
- [commented 2016](https://github.com/api-platform/core/issues/521#issuecomment-216374018) 
- [commented 2018](https://github.com/api-platform/core/issues/521#issuecomment-443215325)

After looking  at the code, I think the first (comment 2016) is right. And if i have well understood how it works, we can assume this schema :
![Untitled Diagram](https://user-images.githubusercontent.com/6217771/57920125-9a44af00-789a-11e9-9302-f61789da7a8e.png)

Question : 
If I am right, is it possible to insert a schema like this one in the doc to help people understand how it works.

**Comment by soyuka** [comment]
Have you checked our access control feature https://api-platform.com/docs/core/security/ ? 
Indeed you can use voters inside custom listeners. You can also take a look at api-platform's code to see how we implemented the access control feature (see DenyAccessListener).

**Comment by ShuyqcK** [comment]
Hi @soyuka ,

I checked the doc before posting this issue and I found only this part which refers to my question :
> It is also possible to use the event system for more advanced logic or even custom actions if you really need to.

The rest of the doc is really oriented on  _access control directives_ and even if it is possible to call a custom voter with expressions, no example is given(only roles are called).

My goal by posting this issue was to point out that the answer  is not clear in the documentation, and that the first issue referenced by google contains contradictory answers which can be confusing for newcomers.

**Comment by soyuka** [comment]
Thanks for your feedback @ShuyqcK ! Do you have documentation improvements in mind? I'd love that we improve our doc on this subject !

**Comment by ShuyqcK** [comment]
@teohhanhui , @soyuka 
It may be a bit late but, in my opinion, your documentation is complete but it is such a maze, maybe a small map could help newcomers like me.

![API-PLATFORM](https://user-images.githubusercontent.com/6217771/61466235-d7e8b580-a979-11e9-8e81-e71719449655.jpg)

**Comment by teohhanhui** [comment]
As I've mentioned on Slack, we should definitely have a diagram that gives a good overview of how the different pieces fit together, but I think it should not be centered around the Symfony kernel events. :smile:

**Comment by plamenh** [comment]
So, anyone can supply an example?
