### ISSUE TITLE
[GraphQL] OrderFilter does not consider the order of the properties to filter on

### ISSUE THREAD

**Issue by epourail** [api-platform/core#2808]
When a resource is defined with an `OrderFilter` on multiple properties, the GRAPHQL endpoint does not keep the sorting of the properties (to filter on).

In the following example
```
/**
 * @ApiResource()
 */
class Dummy
{
   /** @var string */
   private $firstname;

   /** @var string */
   private $laststname;

   // ...
}
```
and the api-p filter service defintion :
```
dummy.order_filter:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
       properties: 
          firstname: ~
          lastname: ~
```
Calling the REST endpoint `/dummies?order[lastname]=ASC&order[firstname]=ASC` returns the  expected results ; the `OrderFilter` is called and the `$context[filters][order]` argument is populated with the properties to filter on in the expected order (1st the `lastname` and 2nde the `firstname`)
```
context => [ 
  filters => [
    order => [
      lastname => ASC,
      firstname => ASC
    ]
  ]
]
```
So the SQL query is build keeping the properties sorting : 
`SELECT * FROM dummies ORDER BY lastname ASC, firstname ASC`

The issue is on the GRAPHQL endpoint that keeps the default order (defined in the service definition). 
Calling the syntax `dummies(order: {"lastname": "ASC", "firstname": "ASC"}) { ... }`, the SQL query is build keeping the default order :
`SELECT * FROM dummies ORDER BY firstname ASC, lastname ASC`
In this case, the `OrderFilter` is called and the `$context[filters][order]` argument is : 
```
context => [ 
  filters => [
    order => [
      firstname => ASC
      lastname => ASC,
    ]
  ]
]
```

**Comment by epourail** [comment]
@soyuka Did you qualify this bug ? Can you telle me if it is an "easy to pick" ?

**Comment by soyuka** [comment]
Hi @epourail don't hesitate to try and fix this but it looks like it's not an easy pick from first hand.

**Comment by ArnoudThibaut** [comment]
@epourail @soyuka The problem is not on api-platform side, it occure during the parsing of the query. So it's a webonyx/graphql-php bug.
The fix is ready for me but I wanted to wait the end of my holiday before making a pull request.

**Comment by epourail** [comment]
@ArnoudThibaut @soyuka Did you status on this issue considering the webonyx response ?

**Comment by soyuka** [comment]
Looks like we won't be able to change this, any thoughts @ArnoudThibaut ?

**Comment by epourail** [comment]
Any status of this issue ?

For information, I share my workaround to handle such case.
Decorating the `api_platform.doctrine.orm.query_extension.filter` service.
```php
private function sortContextOrderProperties(array $context): array
    {
        if (!array_key_exists('filters', $context)
            || 'api_graphql_entrypoint' !== $this->request->attributes->get('_route')
            || !array_key_exists('order', $context['filters'])
            || count($context['filters']['order']) < 2
        ) {
            return $context;
        }

        preg_match(
            '#order:\s*{[\s]*([^0-9^}]*)\s*}#',
            $this->request->getContent(),
            $matches
        );

        $orderSorting = [];
        foreach ($context['filters']['order'] as $property => $order) {
            $pos = strpos($matches[1], $property);
            $orderSorting[$pos][$property] = $context['filters']['order'][$property];
        }

        ksort($orderSorting);
        $context['filters']['order'] = array_merge_recursive(...$orderSorting);

        return $context;
    }
```

**Comment by ArnoudThibaut** [comment]
Sorry for not answering sooner.
As vladar told me on my PR the arguments order is not kept with InputObjectType and the solution is to use a List instead.

@epourail It could be nice if you can review my PR and try my fix on your project and told me ifeverything is fine with the OrderFilter, the others built-in filter but especialy with your custom filters if you have some.

**Comment by epourail** [comment]
@ArnoudThibaut I quickly test your branch and it fixes the issue.  For now, I didn't see any regressions with my custom filters.
