### ISSUE TITLE
cannot persist API resource via POST request anymore

### ISSUE THREAD

**Issue by guizmo51** [api-platform/core#2809]
Hello, I read other issue in order to avoid duplicate issue but I don't find similar problem.
Using api-platform/core 2.3 and SF 4.2 I cannot persist API resource using POST anymore. 
I submitted data using JSON format, I received a "201 created status" with the JSON I submitted. (before when it worked I received  JSON ld response).  By debugging there's no SQL Request. I checked all events and by investigating Symfony Serializer is called but api_platform.serializer.normalizer.item is never called anymore. 

WriteListener is called and $this->dataPersister->supports($controllerResult) returns FALSE.
$controllerResult ['controllerResult'] contains an array of the submitted data (only one resource is submitted). 
I think it's a problem with denormalization... it receives an array but returns an array again instead of an object. 
I wouldn't be able to tell if a composer update break my API and when.
Do you need other things ? Thanks in advance for your reading and your help

I'm currently running fresh API-Platform (demo) and check what's wrong with my project.

**Comment by teohhanhui** [comment]
What you've described is really weird. Are you able to reproduce the problem with a clean project?

**Comment by guizmo51** [comment]
Well, after hours and hours of tests and research I found the issue. I have a service for "dunglas json odm", it injected several normalizers and ItemNormalizer was not called.  end :) (thanks for your help!)

**Comment by teohhanhui** [comment]
Did you try updating to the latest versions of both packages? If they don't work together, we should fix them.
