### ISSUE TITLE
Replacements for api.pre_update and api.pre_create events

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#281]
Hi,

in my application, I need to replace data prior writing entities to the database. Previously, I used the `api.pre_update` and `api.pre_create` events to do so.

Are there any replacement events in `master` I can use?

Verbose use case:
- Users upload images to the application. They are created as `TemporaryUploadedFile` entities and passed back to the frontend
- The frontend attaches those `TemporaryUploadedFile` entities to the objects which are about to be created/updated
- The frontend sends the new object including the `TemporaryUploadedFile` entity to the server
- The server used to listen to all create and update events and replacing the `TemporaryUploadedFile` entities with the correct file entities

The design goal here is to don't create "floating" file entities, which would have to be removed afterwards if the user decides not to save the entity.

Thanks
Felicitus

**Comment by ogizanagi** [comment]
Can't you register two listener, before and after the `ManagerViewListener` in order to do so ?

**Comment by dupuchba** [comment]
I don't really understand your use case, but still, if you use Doctrine, you can still implement event listeners  => http://doctrine-orm.readthedocs.org/en/latest/reference/events.html#implementing-event-listeners

**Comment by felicitus** [comment]
@ogizanagi In fact, one listener was enough. I will post my solution later.

@dupuchba The issue is that I can't submit the file data itself. So the user uploads a file and receives a reference to the uploaded file. Directly creating an attachment to the entity is bad practice, because the user should be able to cancel editing any time.

Example: I have a `Product` which may have images. The user retrieves the product with no images. The user adds an attachment by uploading it to the server and receives a ´TemporaryUploadedFile`. Now when the user clicks "save", the frontend transmits the changes `Product` having the `TemporaryUploadedFile` in the `images` collection. However, the `Product` entity has a relation which only allows `ProductImages` in the collection, causing Doctrine to throw an error. Thus my listener replaces any `TemporaryUploadedFile` with actual instances of the type `ProductImage`.

**Comment by felicitus** [comment]
My solution can be found here:

[TemporaryFileEventListener.php](https://github.com/partkeepr/PartKeepr/blob/sf2migration/src/PartKeepr/UploadedFileBundle/EventListener/TemporaryFileEventListener.php)
[config.yml](https://github.com/partkeepr/PartKeepr/blob/sf2migration/app/config/config.yml#L166)

@dunglas A flowchart of program execution could be helpful for the documentation, especially with the event system. A few hours, I was unaware of that DunglasApiBundle currently hooks in via the event system, and users can actually modify the serializer results prior doctrine takes over. What do you think?

**Comment by dunglas** [comment]
@felicitus I agree and I'll do it but I prefer to wait the end of development cycle of the v2 because big change will still occur.

**Comment by dunglas** [comment]
The event system has been entirely rethought and is now documented: https://github.com/api-platform/docs/blob/master/core/events.md
