### ISSUE TITLE
Get fails when Entity name is an SQL reserved word

### ISSUE THREAD

**Issue by JDruery** [api-platform/core#2820]
For example, an Entity named Group will generate the following error: "An exception occurred while executing 'SELECT g0_.id AS id_0, g0_.name AS name_1 FROM group g0_ ORDER BY g0_.id ASC LIMIT 30':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group g0_ ORDER BY g0_.id ASC LIMIT 30' at line 1"

In the select statement, the table name "group" has no backticks. Here is the entity used to generate the above error:

```
<?php
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 *
 * @ApiResource
 * @ORM\Entity
 */
class Group
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string $name Name of the Group
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name = '';

    public function getId(): int
    {
        return $this->id;
    }
}
```

**Comment by antograssiot** [comment]
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words might solve your issue

**Comment by teohhanhui** [comment]
You could try using a custom naming strategy: https://github.com/api-platform/demo/blob/6333f50106581c7559dd69f5cf0373c56be3ce49/api/src/Doctrine/ORM/Mapping/ResourceNamingStrategy.php

I feel like we should ship it in api-platform/api-platform

WDYT @dunglas?

**Comment by vasilvestre** [comment]
I think I solved it using annotation, and Entity(name="`name`") something like this

**Comment by JDruery** [comment]
Thanks everyone for your suggestions. I decided to go with a custom naming strategy, since I also wanted to add a prefix to all tables. It worked well, and solved the problem of using SQL reserved words for entities. BTW, really enjoying working with the amazing api-platform!

**Comment by antograssiot** [comment]
Thanks for your feedback, closing then
