### ISSUE TITLE
Deprecated code since Symfony 4.3.

### ISSUE THREAD

**Issue by anthony-launay** [api-platform/core#2835]
`2x: Method "ApiPlatform\Core\JsonLd\Serializer\ItemNormalizer::createChildContext()" will have a third "?string $format" argument in version 5.0; not defining it is deprecated since Symfony 4.3.`

`1x: The "Symfony\Component\HttpKernel\EventListener\ExceptionListener" class is considered final since Symfony 4.3. It may change without further notice as of its next major version. You should not extend it from "ApiPlatform\Core\EventListener\ExceptionListener".`

`1x: The "ApiPlatform\Core\EventListener\ExceptionListener::onKernelException()" method will require a new "string $eventName" argument in the next major version of its parent class "Symfony\Component\HttpKernel\EventListener\ExceptionListener", not defining it is deprecated.`

`1x: The "ApiPlatform\Core\EventListener\ExceptionListener::onKernelException()" method will require a new "EventDispatcherInterface $eventDispatcher" argument in the next major version of its parent class "Symfony\Component\HttpKernel\EventListener\ExceptionListener", not defining it is deprecated.`

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/core/pull/2784

**Comment by anthony-launay** [comment]
Thank's @alanpoulain
