### ISSUE TITLE
Change DataPersisterInterface add context parameters to methods.

### ISSUE THREAD

**Issue by nicolae-stelian** [api-platform/core#2837]
In ApiPlatform\Core\DataPersisterChainDataPersister for example persisters methods (supports, persist, remove) are call with context param: $persister->supports($data, $context) . Sometimes is util to have in a custom persister the context.
To get context I do not  implement DataPersisterInterface in persister because force the signature of methods with only one param and I need the context (some useful information are here).

**Comment by soyuka** [comment]
Hi use the ContextAwareDataPersisterInterface

**Comment by nicolae-stelian** [comment]
Thank'you.
