### ISSUE TITLE
Resource "App\Dto\InvoiceInput" not found. when using nested resources

### ISSUE THREAD

**Issue by Spomky** [api-platform/core#2839]
Hi,

This issue is very similar to #2777, but I am not sure to clearly understand how to fix that.
I created several Input/Output classes that work fine except one

```php
<?php

declare(strict_types=1);

namespace App\Dto;

use App\Entity\Contract;

final class InvoiceInput
{
    /**
     * @var Contract
     */
    public $contract;

    /**
     * @var string
     */
    public $reference;

    /**
     * @var \DateTimeInterface
     */
    public $date;

    /**
     * @var float
     */
    public $amount = 0.0;
}
```

The `input` attribute is correctly set for the `App\Entity\Invoice` class and the data transformer declared as a service.

```php
<?php

declare(strict_types=1);

use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
use ApiPlatform\Core\Serializer\AbstractItemNormalizer;
use App\Dto\InvoiceInput;
use App\Entity\Invoice;

final class InvoiceInputDataTransformer implements DataTransformerInterface
{
    /**
     * @param object $data
     */
    public function transform($data, string $to, array $context = []): Invoice
    {
        if (!$data instanceof InvoiceInput) {
            throw new \InvalidArgumentException('Invalid object');
        }
        $invoice = $context[AbstractItemNormalizer::OBJECT_TO_POPULATE] ?? new Invoice();
        $invoice->contract = $data->contract;
        $invoice->date = $data->date;
        $invoice->reference = $data->reference;
        $invoice->amount = $data->amount;

        return $invoice;
    }

    /**
     * @param object $data
     */
    public function supportsTransformation($data, string $to, array $context = []): bool
    {
        if ($data instanceof Invoice) {
            return false;
        }

        return Invoice::class === $to && null !== ($context['input']['class'] ?? null);
    }
}
```

Request body looks like:

```json
{
  "reference":"Invoice #001",
  "amount":1010.1,
  "contract":"/contracts/aea63074-088b-4d8a-8ba2-56dca08ff323",
  "date":"2019-06-02"
}
```

I tried to debug and found that:

* The method `InvoiceInputDataTransformer::supportsTransformation` is called and returns `true` as expected
* The method `InvoiceInputDataTransformer::transform` is never called
* The method `AbstractItemNormalizer::denormalize` is called as well as `parent::denormalize($data, $inputClass, $format, ['resource_class' => $inputClass] + $context),` at line 180
* The line 356 of `Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer` throws an exception when calling `this->setAttributeValue(…);` with attribute `contract` (an IRI)

From what I understand, the `Contract` object is not correctly instantiated. [The documentation](https://api-platform.com/docs/core/dto/#using-objects-as-relations-inside-resources) mentions that:

> Because API Platform can (de)normalize anything in the supported formats […], you can use any object you want inside resources

I also tried to pass an object for the `contract` attribute like `"contract":{"@id":"/contracts/aea63074-088b-4d8a-8ba2-56dca08ff323"},` but the error message is:

> Nested documents for attribute "contract" are not allowed. Use IRIs instead.

What am I doing wrong?
How to get the attribute `contract` being populated with a `App\Entity\Contract` object?

**Comment by soyuka** [comment]
Might be that you need groups? Everything looks correct from here.

**Comment by teohhanhui** [comment]
@Spomky I haven't looked into your issue, but could you try with the latest `2.4` branch (`2.4.x-dev` in `composer.json`) and see if you have the same problem?
