### ISSUE TITLE
What about validation constraints ?

### ISSUE THREAD

**Issue by lucascherifi** [api-platform/core#284]
Hello,

I am delighted using this nice project :) Thank you.

As part of one of my projects, I am trying to make a form that is automatically built based on "/apidoc". 

This is handy but I noticed that there was nothing about validation constraints (eg Assert \ Range (min =0 , max = 4) ).

I figure it would be practical to get them here : hydra:supportedClass / hydra:supportedProperty / hydra:constraints (not mentioned in W3C Draft http://www.w3.org/ns/hydra/spec/latest/core/)

I would like to propose that to hydra members but I would like to talk about it with you before.

Regards,

Lucas.

**Comment by dunglas** [comment]
IMO it should be discussed on the Hydra list first but I think it's a too specific use case to be included in the spec.

The current behavior looks fine to me: it's not present in the API doc but if the validation fail when data are submitted, a 400 error with a `hydra:Error` with an explicit message will be sent to the client.
If you want to describe it in the API doc, you can create a custom vocabulary (not in the Hydra namespace) with more constraints.

**Comment by lucascherifi** [comment]
Thank you Kévin for this answer.

We are currently working on SOA architecture and I think API centric model is a very good thing. This reduce front office and back office as "user interfaces", as API consumers.

In each back office, there is a lot of forms and a well-designed form should, at least, indicate to the user what (and how) are the constraints for each field.

As Hydra APIs are meaning as auto discoverable, this use case could be quite general. This kind of feature should be great for this bundle (eg. a "dunglas:" namespace in apidoc) as we are able to parse these constraints (Assert annotation).

**Comment by theofidry** [comment]
The thing is that the doc displayed for properties, e.g. the types of the properties, are different from the constraints doc which is specific to POST/PUT endpoints, for which there is no doc available aside from an external tool like NelmioApiDoc. So it's better to keep it in the API doc rather than in the responses unless there's an Hydra standard for that.

**Comment by lucascherifi** [comment]
Hi Theo, thanks for this feedback.

In order to get a correct maintainability for our platforms years after years, I think it's necessary to get these contraints in apidoc endpoint in order to avoid small API changes to become a heavy work because of modifying our consumers (back office in our case) : Example : changing the width of a range of integer values.

the  /apidoc endpoint is made to describe the API as much as possible and for every verbs, as the writable and readable fields as present (BTW I think it should be "readonly" and "writeonly" as http://www.w3.org/ns/hydra/spec/latest/core/#issue-6). IMO this endpoint is the best place to add this kind of information. It's not a part of the current draft of Hydra group. We could propose it before, but as HTML5 is born from consumers decisions (web browser in this case), I think we could implement that feature, then propose it to be a part of the standard (Hydra).

**Comment by dunglas** [comment]
The doc is now a standard Symfony normalizer and can be decorated to add custom properties like this one.
