### ISSUE TITLE
How I can grant access for many roles using annotation?

### ISSUE THREAD

**Issue by victor-felix** [api-platform/core#2846]
I can grant access for many roles, but the forms below not work.

Example:

/**
 * @ApiResource(
 *     attributes={
 *          "access_control"="is_granted('ROLE_STUDENT')",
 *          "access_control"="is_granted('ROLE_TEACHER')"
 *     }
 * )
...

/**
 * @ApiResource(
 *     attributes={
 *          "access_control"="is_granted('ROLE_STUDENT, ROLE_TEACHER')"
 *     }
 * )
...

/**
 * @ApiResource(
 *     attributes={
 *          "access_control"="is_granted('ROLE_STUDENT', 'ROLE_TEACHER')"
 *     }
 * )
...

**Comment by lukasluecke** [comment]
You can use [logical operators in expression language](https://symfony.com/doc/current/components/expression_language/syntax.html#logical-operators), so the following should work:

```
@ApiResource(
    attributes={
        "access_control"="is_granted('ROLE_STUDENT') or is_granted('ROLE_TEACHER')"
    }
)
```

**Comment by victor-felix** [comment]
@lukasluecke its work!! Thank u bro!!
