### ISSUE TITLE
Passing a specific hydrator in Doctrine ORM Pagination Extension is not supported

### ISSUE THREAD

**Issue by tigitz** [api-platform/core#2847]
I've got a use case where I just need to add some extra fields to a doctrine entity with values coming from its relationship.

I've decided to try one approach by using an Extension that adds a `leftjoin` to the querybuilder and build my entity with a specific hydrator.

Something like:

```php
<?php

namespace App\Doctrine\Hydrator;

use App\Entity\Subscriber;
use Doctrine\ORM\Internal\Hydration\ObjectHydrator;

class SubscriberHydrator extends ObjectHydrator
{
    protected function hydrateRowData(array $data, array &$result)
    {
        $hydratedResult = [];
        parent::hydrateRowData($data, $hydratedResult);

        $subscriber = $hydratedResult[0][0];

        $keys = array_keys($hydratedResult);
        $key = end($keys);

        /** @var Subscriber $subscriber */
        $subscriber->setRow($hydratedResult[$key]['row']);
        $subscriber->setPlaceName($hydratedResult[$key]['placeName']);
        $subscriber->setGrandstand($hydratedResult[$key]['grandstand']);
        $subscriber->setSection($hydratedResult[$key]['section']);

        $result[] = $subscriber;
    }
}
```

As it results to a simple doctrine entity to the eyes of api-platform, I'm supposed to benefit from the whole ecosystem out of the box including the Pagination Extension.

The last piece would be to add an extension that implements the `getResult` method from`QueryResultItemExtensionInterface, QueryResultCollectionExtensionInterface` and pass the hydrator mode to the query.

Unfortunately the Query object is not exposed in the Pagination Extension:
https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L147

So I have to override the whole method instead of passing some config value to set the hydration mode. Which is not ideal.

I wonder what's your thought about it ? Does the use case seems reasonable enough to cosnider a way to pass the hydration mode ?

**Comment by soyuka** [comment]
Indeed, you'd have to re-use the Pagination extension code inside your own. When you alter the Query you don't have it's modifications inside the QueryBuilder, therefore there are no other solution available except to use this altered Query object directly :|.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/2493 might be of interest here

**Comment by tigitz** [comment]
> #2493 might be of interest here

Definitely! thank you. I looked for similar issues but not "possibly related PR" before posting :sweat_smile:

I'll close this as it seems to fix my issue. :+1:
