### ISSUE TITLE
validation_groups always null

### ISSUE THREAD

**Issue by sfmok** [api-platform/core#2850]
Hi,

In the next line `$attributes` never has `validaion_groups`

https://github.com/api-platform/core/blob/efe39ceab94f448cc3ae5dc68cc6b8066e1dc9cd/src/Validator/EventListener/ValidateListener.php#L58

So, the next line for retrieve `validations_groups` is not needed because it does not exist in $attributes.

https://github.com/api-platform/core/blob/efe39ceab94f448cc3ae5dc68cc6b8066e1dc9cd/src/Validator/EventListener/ValidateListener.php#L67

I guess we have an issue there. What in case we need to change the validation_groups directly from the request.

**Comment by soyuka** [comment]
Not enough data about what's wrong and/or a reproducer. Please open a new issue if the problem is still there
