### ISSUE TITLE
Regression where operation returns resource class different from input resource class

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#2855]
Introduced here:
https://github.com/api-platform/core/pull/2822

Example operation:
```php
/**
 * @ApiResource(
 *     itemOperations={
 *         "get": {
 *             "method": "GET",
 *             "path": "/payments/{id}",
 *         },
 *         "void": {
 *             "method": "POST",
 *             "path": "/payments/{id}/void",
 *             "controller": PaymentVoid::class,
 *             "deserialize": false
 *         }
 *     }
 * )
 */
class Payment { ... 
```

`PaymentVoid` controller returns a `Void`, which is also a resource.
This worked on `2.4.3`.

Now errors:
```
{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Object of type \u0022Void\u0022 does not match \u0022Payment\u0022 resource class."}
```

**Comment by teohhanhui** [comment]
Do you have a stack trace?

**Comment by bendavies** [comment]
@teohhanhui i'll DM you

**Comment by bastnic** [comment]
FYI I have the same error but in a slightly different context. 

parent have multiple childs (relation OneToMany), child have have one parent (relation ManyToOne).

each serializaion group (parent:list / child:list) relate each other exect the relation field that the child.parent is not in serialization group parent:list to avoid recursion.

a call to /parents/ give all the parent with there relative multiple childs.

but a call to /childs/ crash `"Object of type \"...\Parent" does not match \"Child\" resource class."`. 

stacktrace : 
- src/Api/ResourceClassResolver.php L63
- src/Serializer/AbstractItemNormalizer.php L127 arguments : (object : proxy parent 1, string : class child, boolean true)
