### ISSUE TITLE
symfony/messenger v4.3 wraps any exception into HandlerFailedException

### ISSUE THREAD

**Issue by karser** [api-platform/core#2856]
Hi folks!

Before symfony/messenger v4.3, the exceptions were transparent - you got what you threw. So that you could specify them in the exception_to_status map and receive meaningful statuses.
As of v4.3, symfony/messenger [started wrapping any exception into HandlerFailedException](https://github.com/symfony/messenger/blob/master/CHANGELOG.md), so api-platform always returns 500.
Here is a similar issue described in SO https://stackoverflow.com/questions/55558350/custom-exception-from-messenger-handler

So the idea is to recover previous exception and match to exception_to_status map.
```
if ($exception instanceof HandlerFailedException) {
    $exception = $exception->getPrevious();
}
```
What do you think of this approach? Does it make sense or I'm missing something?

**Comment by dunglas** [comment]
It looks a bit hacky to me... but I don't have another solution in mind. Do you have some thoughts about that @sroze?

**Comment by karser** [comment]
I see, v2.4.4 doesn't support it yet, it has `"conflict": {"symfony/messenger": ">=4.3"}`. So I must have tested v2.4.3 + messenger v4.3.
