### ISSUE TITLE
Invalid swagger JSON in 2.4

### ISSUE THREAD

**Issue by coudenysj** [api-platform/core#2857]
Since upgrading from 2.3.6 to 2.4.4 I get errors in my PATCH documentation.

    Validation failed. /paths/api/assets/{id}/patch has duplicate parameters
    Validation failed. Found multiple body parameters named "asset" on line 1

I document the asset body parameter in the PATCH swagger_context, but because of the `no break` [here](https://github.com/api-platform/core/blob/076e0085dc9710df8882a37ca1cecf4fc31f8c23/src/Swagger/Serializer/DocumentationNormalizer.php#L304), the PUT parameters are appended too.

What was the reason for this no break? https://github.com/api-platform/core/commit/20590a03c194014b0cc598a88fbc65b859e22098#r33912998

**Comment by soyuka** [comment]
Because the PATCH and the PUT have similar outputs in swagger. Could you give a try in patching this?
