### ISSUE TITLE
Mercure and relative IRI as topic

### ISSUE THREAD

**Issue by partageit** [api-platform/core#2872]
Hello,

My API is available from many FQDN. For example:

- `https://host1/api/books`
- `https://host2/api/books`

When this request is sent: `PUT https://host1/api/books/2`, the mercure publisher sends a notification to the topic `https://host1/api/books/2`.

Clients connected to the other address do not receive notifications, as the subscription does not match.

Is it a way to push notifications to `/api/books/2`, i.e. the path without scheme/hostname? Or is it a best practice?

In `PublishMercureUpdatesListener::publishUpdate()`, I noticed that the topic is built with:

```php
$iri = $this->iriConverter->getIriFromItem($entity, UrlGeneratorInterface::ABS_URL);
```

Maybe the second parameter of `getIriFromItem()` can be configurable?

With some advices, I can help for implementation.

**Comment by soyuka** [comment]
It should be part of https://github.com/api-platform/core/pull/2708, maybe we can continue this one?

**Comment by karser** [comment]
I think there are 2 options
1. The api domain is set in api-platform configuration
2. Ability to use relative paths

Here is how I do that now:
```
/**
 * @ApiResource(mercure=true)
 */
class Book {
    private $users = [];

    public function getMercureTargets(): array
    {
        $domain = getenv('API_DOMAIN');

        $targets = array_map(function(User $user) use ($domain) {
            return "https://{$domain}/users/{$user->getId()}";
        }, $this->users);

        return $targets;
    }
}
```

Domain may vary, e.g: domain.tld, stage.domain.tld, test.domain.tld, so it's passed as an environment variable. For me it's a bit weird accessing environment variable 1. from entity 2. using `getenv`.

**Comment by soyuka** [comment]
You can configure the `url_generation_strategy` now.
