### ISSUE TITLE
What about mongo ObjectId?

### ISSUE THREAD

**Issue by markitosgv** [api-platform/core#2877]
Im reading this in documentation:

> Identifier fields always need to be integers with an increment strategy. API Platform does not support the native ObjectId.

I've Mongo ObjectIDs as documents primary key, and GET, DELETE and PUT resources by mongo id it seems ok.

But I can't create a new resource with another Document relation. Is it possible to do that?

For example:

```
POST to a new BlogPost resource:
{
  "author": "5af58fc7eeb3a7076559e3d2",
  "title": "test"
}
```

This call returns:

> Invalid IRI \"5af58fc7eeb3a7076559e3d2\"

**Comment by alanpoulain** [comment]
This is not supported in API Platform right now because it would mean changing a lot of things to make it work in all cases.

**Comment by markitosgv** [comment]
I see... well I think to real support MongoDB we need to support ObjectID, because is standard way for identifiers in Mongo.

**Comment by markitosgv** [comment]
Sorry, my fault before. If I send "author" as "/api/v2/authors/5af58fc7eeb3a7076559e3d2" it works!

**Comment by soyuka** [comment]
nice it looked weird to me if it wouldn't work.

**Comment by kralos** [comment]
@soyuka Is this closed because `ObjectId` is supported? If so should the restriction be removed from the docs? if not, why isn't it supported? I'm struggling to find the reason for this comment in the docs.

**Comment by kralos** [comment]
> This is not supported in API Platform right now because it would mean changing a lot of things to make it work in all cases.

@alanpoulain can you elaborate?

**Comment by alanpoulain** [comment]
I don't remember well, but I think there are some cases where having `ObjectId` could cause issue because it requires specific handling.
Maybe it works for simple cases though.

**Comment by soyuka** [comment]
IMO this should work as UUID work, if not please provide a reproduction of some kind. I'll update the docs.
