### ISSUE TITLE
No routes for class with the same name but different namespace

### ISSUE THREAD

**Issue by nightio** [api-platform/core#2881]
Assume we have two classes configured for ApiPlatform:
```
namespace App\Customer;

/**
 * @ApiResource()
 */
class Program
```

```
namespace App\Management;

/**
 * @ApiResource(routePrefix="/management")
 */
class Program
```

the route for second one is not generated because `ApiPlatform\Core\Bridge\Symfony\Routing\RouteNameGenerator` uses only shortClassName so there will be only one route e.g. `api_programs_get_item                                GET      ANY      ANY    /programs/{id}.{_format}`

**Comment by soyuka** [comment]
Decorate the ShortNameResourceMetadataFactory and add a prefix (for example the last part of the namespace): `customer_program`, `management_program`.

**Comment by nightio** [comment]
@soyuka thanks for your response.
I have tried your idea, but a short name is also used to generate routing path so I'm getting something like this:
`/customer_program/{id}` and `/management/management_program/{id}`
Instead of this it should get I would like to have
`/program/{id}` and `/management/program/{id}`

Anyway it should throw an Exception in current situation. Now there is no info that route has not been generated.

**Comment by antograssiot** [comment]
You can also specify a different `shortname` attribute and define the `path` you want in each operation. It will avoid to decorate the ShortNameResourceMetadataFactory and will give you what you want

**Comment by soyuka** [comment]
Indeed, @antograssiot solution is even easier (thanks! :p) ! I thought he wanted to prefix every resource, but if it's only for a couple just use configuration!
