### ISSUE TITLE
Type Error using Messenger and DELETE

### ISSUE THREAD

**Issue by Spomky** [api-platform/core#2888]
I have the following error when deleting a resource:

> TypeError : Argument 2 passed to Symfony\Component\Messenger\Envelope::__construct() must be of the type array, object given, called in /vendor/api-platform/core/src/Bridge/Symfony/Messenger/DataPersister.php on line 91

Works fine if line 91 of [DataPersister.php](https://github.com/api-platform/core/blob/v2.4.5/src/Bridge/Symfony/Messenger/DataPersister.php#L91) is replaced with `$this->messageBus->dispatch(new Envelope($data, [new RemoveStamp()]));`

**Comment by soyuka** [comment]
Mhh isn't this related to a new messenger version? What version of api platform/symfony are you using?

**Comment by Spomky** [comment]
Api Platform Core 2.4.3 and SF 4.3.2

**Comment by soyuka** [comment]
We fixed it on master but I'm not sure that this should happen on 2.4 : https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Messenger/DataPersister.php#L91

**Comment by Spomky** [comment]
OK great!.
You are right the master branch is correct. But it looks like the [2.4 one](https://github.com/api-platform/core/blob/2.4/src/Bridge/Symfony/Messenger/DataPersister.php#L91) and the version tagged 2.4.x aren't (e.g. [v2.4.5](https://github.com/api-platform/core/blob/v2.4.5/src/Bridge/Symfony/Messenger/DataPersister.php#L91))
