### ISSUE TITLE
Fix remaining Symfony deprecations

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#2896]
I figured out that many Symfony deprecations aren't fixed yet. They are just hidden by our default PHPUnit Bridge configuration.

To display these deprecations, you can run `SYMFONY_DEPRECATIONS_HELPER=max[total]=0 vendor/bin/phpunit`.

Pull Requests welcome!

**Comment by zairigimad** [comment]
Hello @dunglas , I think the deprecations are part of FosUserBundle.

**Comment by teohhanhui** [comment]
> SYMFONY_DEPRECATIONS_HELPER=max[total]=0

we already use that in one of our Travis jobs, right?
