### ISSUE TITLE
OrderExtension cannot order by columns in nested relations

### ISSUE THREAD

**Issue by tezvi** [api-platform/core#2904]
Hi everyone!

I've noticed that OrderExtension which deals with default resource ordering does not support ordering by columns from joined tables. It works for join relation on resource entity (first level only), but it does not follow "deeper" relations.

Example:
Product
 - id (PK)
 - userId (FK)

User
 - id (PK)
 - firstname
 - lastname
 - groupId (FK)

Group
 - id (PK)
 - groupName

If I want to configure default ordering for Product resource like "user.group.groupName", the OrderExtension will join only users to products and fail with error that group.groupName does not exists on User entity (Doctrine error).

The solution would be to add multiple joins here
https://github.com/api-platform/core/blob/ee7ef885f8653015fe7f6eeb913aae0d8fb34386/src/Bridge/Doctrine/Orm/Extension/OrderExtension.php#L68-L69

I could provide a PR if you guys think this should be implemented.

**Comment by soyuka** [comment]
This would add some complexity and I'd suggest to use your own OrderFilter, queries will be cleaner.
