### ISSUE TITLE
[Mercure integration] ability to specify topics for resource collection

### ISSUE THREAD

**Issue by karser** [api-platform/core#2913]
Hello everyone. I have a question related to Mercure integration in api-platform. How to subscribe on a resource collection topic without specifying an id?

I inspected [PublishMercureUpdatesListener](https://github.com/api-platform/core/blob/v2.4.5/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php), it seems the topic is an IRI, meaning it always contains ID.

```
$iri = $this->iriConverter->getIriFromItem($entity, UrlGeneratorInterface::ABS_URL);
$update = new Update($iri, $data, $targets);
```

So that `$em->persist(new Notification()); $em->flush();` would publish an update with IRI like `https://example.com/notifications/1`

So the only way to subscribe to updates is to know their IRIs. How to deal with the newly created objects? [PublishMercureUpdatesListener::publishUpdate](https://github.com/api-platform/core/blob/v2.4.5/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php#L162) knows their IDs because it is executed on `postFlush`, but how to subscribe to a newly created object on the frontend without knowing its ID?

Looks like it'd be more useful if we add collection IRI to the topic. So the EventSource client would have more options to subscribe:
```
$update = new Update([
  'https://example.com/notifications/1',
  'https://example.com/notifications', //collection IRI (without ID)
  'https://example.com/users/<id>/notifications', //collection subresource IRI
], $data, $targets);
```

Or even more interesting, why can't the object specify its topics as well as targets using expression language?
`@ApiResource("mercure"={"targets"="object.getTargets", "topics"="object.getTopics"})`

Another approach: the entity implements the corresponding interface
```
@ApiResource("mercure"=true)
class MyEntity implements TargetsAwareInterface, TopicsAwareInterface  {
    public function getMercureTargets(string $apiHost): array {
        return [$apiHost.'/users/'.$this->user->getId()];
    }
    public function getMercureTopics(string $apiHost): array {
        return [
            $apiHost.'/my_entities/'.$this->id,
            $apiHost.'/my_entities',
        ];
    }
}
```

**Comment by dunglas** [comment]
Hi @karser 

> So the only way to subscribe to updates is to know their IRIs. How to deal with the newly created objects? PublishMercureUpdatesListener::publishUpdate knows their IDs because it is executed on postFlush, but how to subscribe to a newly created object on the frontend without knowing its ID?

You can use URI Templates for that. Subscribing to `https://example.com/notifications/{id}` will do the trick.

Adding support targets in expression language could be nice!

**Comment by karser** [comment]
>Subscribing to https://example.com/notifications/{id} will do the trick.

Argh, I didn't know about this feature, sorry.

>Adding support targets in expression language could be nice!

It's already possible to add `targets` through expression language. Did you mean `topics`?

Also, what do you think about `TargetsAwareInterface, TopicsAwareInterface` when `"mercure"=true` ?

**Comment by karser** [comment]
`https://example.com/notifications/{id}` works like a charm, thank you! In this case my proposal doesn't make much sense, closing this issue along with PR.
