### ISSUE TITLE
UniqueEntity works on IRI but not on Objects

### ISSUE THREAD

**Issue by numediaweb** [api-platform/core#2937]
I have an entity configured like this:
```php
...
 * @ORM\Table(
 *  uniqueConstraints={
 *      @ORM\UniqueConstraint(name="unique_unsubscribes", columns={"subscriber_id", "service_id"}),
 *  })
 *
 * @UniqueEntity(
 *     fields={"subscriber", "service"},
 *     message="This unsubscribe request already exists."
 * )
 */
class Unsubscribe
{
    ...

    /**
     * @ORM\ManyToOne(targetEntity="ApiBundle\Entity\Subscriber", inversedBy="unsubscribe", cascade={"persist"})
     */
    private $subscriber;

    /**
     * @ORM\ManyToOne(targetEntity="ApiBundle\Entity\Service", inversedBy="unsubscribes")
     */
    private $service;
```
When I post some duplicate data like this:
```js
{
    "subscriber": "/api/subscribers/3",
    "service": "/api/services/1",
}
```
I get a nice HTTP bad request `400` error as expected: `This unsubscribe request already exists.`
But when I post it like this:
```php
{
    "subscriber": {
        "contact": "test@example.com",
        "type": 1
    },
    "service": "/api/services/1"
}
```
The `UniqueEntity` doesn't catch it but instead I get a DB error from `uniqueConstraints` instead.
Of course I can [convert PHP exceptions to HTTP errors](https://api-platform.com/docs/core/errors/) but this will slow down the response as I have to run an extra query in the database to check for duplicate :(

Do you guys know of any other solution?

Thanks!

**Comment by teohhanhui** [comment]
Your `subscriber` is missing the `@id`. (Assuming you're using JSON-LD.)

**Comment by numediaweb** [comment]
@teohhanhui I am passing a new subscriber entity that will be created: so I don't have and don't need the `subscriber` id :)

**Comment by teohhanhui** [comment]
In that case, what is the bug? If it's a new `Subscriber`, the `UniqueEntity` constraint cannot do its job based on what you've declared.

**Comment by numediaweb** [comment]
I was thinking that when I pass a new object instead of it's URI, it will create it and then assign the relation and validate etc.. but this actually doesn't work because it cannot bind an entity that doesn't have an ID, therefore it won't even detect if it is duplicate!
The solution sofar is to use an event listener and create the entity and associate it for validation..
