### ISSUE TITLE
Disable built-in data persisters

### ISSUE THREAD

**Issue by bradconor** [api-platform/core#2952]
Hello,

I was wondering how can I disable doctrine ORM's data persister for an operation ?

Thanks

**Comment by soyuka** [comment]
Sure, what verison of api platform are you using? You need to disable the WriteListener see https://api-platform.com/docs/core/events/#built-in-event-listeners

**Comment by bradconor** [comment]
Well, the 2.4 version, so if I want to disable it, I put it like this : 
```
@ApiResource(routePrefix="/api",
 *     itemOperations={
 *          "put"={
 *              "write"=false
 *          }
 *     },
```
Or how do I proceed ?

**Comment by soyuka** [comment]
```
@ApiResource(routePrefix="/api",
 *     itemOperations={
 *          "put"={
 *                "attributes"={"write"=false}
 *          }
 *     },
```

**Comment by bradconor** [comment]
Thanks it works !
