### ISSUE TITLE
Route with an id containing a slash return a 404

### ISSUE THREAD

**Issue by dardinier** [api-platform/core#2953]
Hi,

I have an entity called `Worker` with ids that may contains `/`. This entity does not use any ORM. It is just an ApiResource.

My operation to get a worker is `/api/workers/{id}`.

When I require a resource with an id containing a 'slash', it seems that the string is being url encoded which should prevent to mess up the routing.

But in reality, it looks like it's being interpreted by something so it is creating a new unknown route.

##### Case 1 :

 - My id is `hello`. It does not contain any `/`.

- I get a normal behaviour :

Request :

![1](https://user-images.githubusercontent.com/24563898/61941764-68d21900-af98-11e9-8379-8334575f8bc9.png)

Response :

![3](https://user-images.githubusercontent.com/24563898/61941815-7edfd980-af98-11e9-92d0-38325e7f0cc4.png)

##### Case 2 :

 - My id is `hello/world`. It contain a `/`.

- I get the unexpected behaviour :

Request :

![2](https://user-images.githubusercontent.com/24563898/61941896-a8990080-af98-11e9-92eb-c94872c72950.png)

Response :

![4](https://user-images.githubusercontent.com/24563898/61941906-aafb5a80-af98-11e9-8292-2ece17de149d.png)

This result to a 404 :

![5](https://user-images.githubusercontent.com/24563898/61941937-bb133a00-af98-11e9-93cb-5191799b89df.png)

So it looks like even if the id is url encoded, the API detect a route.

Is this expected ?

**Comment by soyuka** [comment]
Yes the router will have issues with `/` if you don't specify that they should be matched in the parameter. See: https://symfony.com/doc/current/routing/slash_in_parameter.html#configure-the-route. 

I think that you'll need a custom operation because we don't forward the route requirements (not 100% sure though, maybe that you can pass them through the route defaults?).

**Comment by dardinier** [comment]
Yes, that was it !

I added the requirement for the id in my operation declaration :

```yaml
# config/api_platform/resources/worker.yaml
App\Entity\Worker:
    itemOperations:
        get:
            requirements:
                id: '.+'
```

Now requesting a worker with an id containing a slash works.

Thank you.
