### ISSUE TITLE
Add a warning for name collisions 

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#296]
Follow up of #195

**Comment by teohhanhui** [comment]
We should document the methods to be used to avoid collision in both the join alias and bound parameter name, when #242 is merged.

On that note, I should probably send a companion PR to [api-platform/doc](https://github.com/api-platform/doc). Somehow missed out on updating docs (weird...)

**Comment by Simperfit** [comment]
I think this is outdated ? @theofidry
