### ISSUE TITLE
RangeFilter throws 500 when trying to search with float by integer field

### ISSUE THREAD

**Issue by karser** [api-platform/core#2963]
Hello, I encountered an issue where RangeFilter is searching with a float value by integer field.
I'm getting an error: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "9.5"

It turns out that you can't bind float to where clause in Postgres https://stackoverflow.com/questions/57314159/php-pdo-cant-bind-a-float-parameter-to-search-by-integer-field

But still, shouldn't RangeFilter cast the search value to the field type to avoid this error? In this case,  `float` to `integer`?

**Comment by karser** [comment]
Here is what can be done in RangeFilter:

Solution 1: cast left side to float (Postgres-specific):
```
$stmt = $con->prepare('SELECT t.* FROM my_table t WHERE CAST(t.integer_field AS FLOAT) > ?');
$stmt->execute([9.5]);
```

Solution 2: bypass pdo parameters bindings (more generic though):
```
$v = '9.5'; //user input
$v = filter_var($v, FILTER_VALIDATE_FLOAT);
if ($v === false) {
    throw new InvalidArgumentException("Property {$property}: '{$v}' is not valid number");
}
$stmt = $con->prepare('SELECT t.* FROM my_table t WHERE t.integer_field > '.$v);
$stmt->execute();
```

Solution 3: truncate / round the search value and cast its type to `int` if the field type is integer.

What do you think?

**Comment by soyuka** [comment]
I'd do number 3 :p. Number 1 is fine though.

**Comment by soyuka** [comment]
closing as we now have query string validation right?
