### ISSUE TITLE
[GraphQL] Disabling pagination per resource

### ISSUE THREAD

**Issue by lukasluecke** [api-platform/core#2965]
[Disabling pagination for a specific resource](https://api-platform.com/docs/core/pagination/#for-a-specific-resource) is not handled by GraphQL, only the global setting is respected.

**Comment by alanpoulain** [comment]
If it's the case, it's a bug since the code to handle it is already here:
https://github.com/api-platform/core/blob/cfa8f34d0d5779e0d7e4805ae0d1062afd699aab/src/GraphQl/Type/FieldsBuilder.php#L235

**Comment by lukasluecke** [comment]
@alanpoulain Sorry, seems there was an issue locally with caching - disabling the pagination indeed removes the arguments and disables the pagination, but this seems to not be supported by the CollectionResolverFactory.

**Comment by lukasluecke** [comment]
@alanpoulain The problem is that the `paginationEnabled` flag is set globally, so disabling the pagination per resource doesn't work.

**Comment by alanpoulain** [comment]
Yes disabling the pagination per resource is not implemented (yet).

**Comment by lukasluecke** [comment]
Pretty sure that's still a bug 😉 I will create a PR soon - should I add the flag per resource only, or also allow it per operation?

**Comment by alanpoulain** [comment]
It depends of the POV :slightly_smiling_face:
Thanks for taking it. You should do it like in REST: per operation and fallback on resource (it's a boolean flag).

**Comment by alanpoulain** [comment]
Related issue: https://github.com/api-platform/api-platform/issues/1181

**Comment by lukasluecke** [comment]
From the documentation the "enabled" flag seems to be only global or per resource, only the other settings have documented per operation usages. Is this just a documentation error?

**Comment by alanpoulain** [comment]
If you look at the code directly, it seems to be doable per operation too. So I think it's a mistake in the documentation.

**Comment by alanpoulain** [comment]
Will be in 2.5.
