### ISSUE TITLE
Question: additional parameter in custom operation

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#2968]
Hello everyone.

Just a question - is there a recommended way to pass additional info to custom operation controller? Example:
`GET: api/products/{id}/export/{type}`
Method is not so important to me, if this can be done with `POST`, please advise.

Thanks.

**Comment by CvekCoding** [comment]
Now I get this parameter from `Request`. Is this the best way or not?

**Comment by ismail1432** [comment]
From my POV you can pass information in body for custom operation. Get them from Request is the easiest way and the best way for me but I’m not an API Standard expert so it’s just my 2 cents

**Comment by soyuka** [comment]
Indeed, use a custom operation and you should have everything you need in the Request object.
