### ISSUE TITLE
[GraphQL] Incorrect (parent) filters in nested collections

### ISSUE THREAD

**Issue by lukasluecke** [api-platform/core#2969]
The arguments (filters) for nested collections are based on the parent resource configuration, not on the collection's resource configuration.

**Comment by lukasluecke** [comment]
I will create a PR with the fix soon 🙂

**Comment by luca-simonetti** [comment]
I thought that was the expected behaviour. I see the light at the end of the tunnel now!
Do you have an ETA for this to be merged in master? Can I help somehow to make things quicker?

**Comment by alanpoulain** [comment]
Fixed in master and 2.4.
@luca-simonetti either wait for a release or use the dev version.
