### ISSUE TITLE
Multiple filter values behaviour not matching jsonapi recommandation

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/core#2980]
https://github.com/api-platform/core/blob/92f655c84e9d03f38ee2986906fba11ce529bc2f/src/JsonApi/EventListener/TransformFilteringParametersListener.php#L20

**Comment by soyuka** [comment]
Superseeded by https://github.com/api-platform/core/issues/2981

**Comment by vasilvestre** [comment]
Sorry idk what happened ^^'
