### ISSUE TITLE
Multiple filter values behaviour not matching jsonapi recommandation

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/core#2981]
From link in phpdoc :

> Mutiple filter values can be combined in a comma-separated list. For example:

`GET /comments?filter[post]=1,2 HTTP/1.1`

https://github.com/api-platform/core/blob/92f655c84e9d03f38ee2986906fba11ce529bc2f/src/JsonApi/EventListener/TransformFilteringParametersListener.php#L20

I've already tried this and it didn't work. I am doing something wrong or APIP do not follow these recommandation ?

**Comment by soyuka** [comment]
I'm not sure that we do follow these recommandation, especially that filters are tight to the DBMS not to the format. You can easily decorate the search filter to implement this behavior though!

**Comment by vasilvestre** [comment]
> I'm not sure that we do follow these recommandation, especially that filters are tight to the DBMS not to the format. You can easily decorate the search filter to implement this behavior though!

I think someone told me to use event listener to convert filters to that format. Do you think it's worth mentionning it in documentation ?

**Comment by soyuka** [comment]
You have an event listener that changes the query parameters in the Request object? This'd work indeed, I'd try to handle the format directly in the filter if possible instead.

**Comment by vasilvestre** [comment]
> You have an event listener that changes the query parameters in the Request object? This'd work indeed, I'd try to handle the format directly in the filter if possible instead.

In which filter ?
