### ISSUE TITLE
Compatibility symfony/messenger

### ISSUE THREAD

**Issue by pimjansen** [api-platform/core#2985]
Hey,

I was wondering what is going on with the messenger integration. I noticed that the latest version 2.4.5 is not compatible with symfony/messenger: >=4.3. 
However when i try to install the 4.2 version i will get notified that it is not compatible with all other relations there are available and require symfony 4.3.* packages.

Are you going to skip this version or why isnt it compatible?

**Comment by soyuka** [comment]
Hi! Indeed, answers are available in this issue: https://github.com/api-platform/core/issues/2912
