### ISSUE TITLE
[GraphQL] [Question] Different access control for item and collections query

### ISSUE THREAD

**Issue by mahmoodbz** [api-platform/core#2988]
I want to have different access control for item and collection query. bat operation for both are the same here:
https://api-platform.com/docs/master/core/graphql/#security-access_control

Thank you.

**Comment by alanpoulain** [comment]
You can use `collection_query`. I will add it to the documentation (you can do it if you want).

**Comment by mahmoodbz** [comment]
@alanpoulain 
Thanks for your response, I tried it but I think its mandatory  to define my own resolver in this case, right?
because of here: 
https://github.com/api-platform/core/blob/master/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php#L76

I tried to use it without custom resolver and I get error:
`Warning: Illegal offset type in isset or empty`
And It means container can't find resolver.

**Comment by alanpoulain** [comment]
My bad, you're right `collection_query` is only used for the custom resolvers.
The `query` operation is used for both item and collection and it is an issue indeed.
Maybe we should introduce a `collection_query` as a top-level operation.

**Comment by mahmoodbz** [comment]
I think so, I'll try to prepare pull request for this issue and make item and collection query as top level operation.

**Comment by alanpoulain** [comment]
It would be great (and it would help :slightly_smiling_face:) if you could contribute it!

**Comment by alanpoulain** [comment]
Done in 2.5.
