### ISSUE TITLE
[GraphQL] Allow multipart/form-data content type in graphql entry point

### ISSUE THREAD

**Issue by mahmoodbz** [api-platform/core#2991]
I want to implement file upload in graphql with custom mutations but I get `GraphQL query is not valid` error. I think in the [entry point parser](https://github.com/api-platform/core/blob/master/src/GraphQl/Action/EntrypointAction.php#L84) we need to allow multipart/form-data content type so user can write file upload mutation.
Something like this:
https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by teohhanhui** [comment]
I don't do GraphQL, but this is so freaking weird! :laughing:

**Comment by alanpoulain** [comment]
Done in 2.5.

**Comment by oleg-brizy** [comment]
> Done in 2.5.

How to fix the missing serializer for `multipart: ['multipart/form-data']`?

This is the second day I am trying to make upload work and still have no idea how to finish it and if it's even possible. I tried to find the solution with multipart serializer in comments and all I found is "Api Platform is not responsible for implementing this serializer" and "Symfony framework will not add this serializer, it should be done in PHP core".

Can you please clarify what's the deal with that serializer and add explicit info in docs about it?

Now I have a feeling that docs are outdated (and there is a big story going on in comments that I am not aware of).
