### ISSUE TITLE
Missing source maps in swagger ui assets

### ISSUE THREAD

**Issue by georgevanvliet** [api-platform/core#3008]
When I start a clean symfony project and add the api pack, upon loading the swagger documentation, I receive console errors that the following files (source maps) could not be found:

* http://localhost/bundles/apiplatform/swagger-ui/swagger-ui.css.map
* http://localhost/bundles/apiplatform/swagger-ui/swagger-ui-bundle.js.map
* http://localhost/bundles/apiplatform/swagger-ui/swagger-ui-standalone-preset.js.map

I would expect these mapping files to be present inside `api-platform/core/src/Bridge/Symfony/Bundle/Resources/public/swagger-ui/swagger-ui.css`

The generated assets contain a `sourceMappingUrl` directive at the bottom, but the files they point to are not included in the distribution.

Is it possible to either not generate the sourceMappingUrl at the bottom, or include the source map files in the distribution?
Or is there another option I am missing?

**Comment by teohhanhui** [comment]
PR welcome! I think we just need to copy them in https://github.com/api-platform/core/blob/master/update-js.sh
