### ISSUE TITLE
Context never passed to data persister remove in WriteListener

### ISSUE THREAD

**Issue by kurzyx** [api-platform/core#3010]
When implementing `ContextAwareDataPersisterInterface` I expect context to be passed to the remove method like it would to the persist method. This however never happens as seen in the WriteListener.

https://github.com/api-platform/core/blob/7ac5857a45be6806c76c39d1e53a99c7fcc883bc/src/EventListener/WriteListener.php#L109

Is this a bug, or was this done on purpose, if so why?

**Comment by soyuka** [comment]
This is a bug we may have missed this code path :)

**Comment by teohhanhui** [comment]
Please help us by sending a Pull Request on the `2.4` branch. :smile:
