### ISSUE TITLE
cannot perform GraphQL sub-selections on non-resource collections

### ISSUE THREAD

**Issue by ehough** [api-platform/core#3016]
This issue is related to #2740 and #2687, but it's different enough that I felt it deserves a separate issue.

I'm having trouble performing sub-selection queries on non-doctrine, non-resource collections. Here's an example. Say I have a very simple resource class:

```php
/**
 * @ApiResource
 */
class Book
{
    /**
     * @ApiProperty(identifier=true)
     *
     * @var string
     */
    public $id;

    /**
     * @var Chapter[]
     */
    public $chapters;
}
```
with `Chapter` is a simple POPO:

```php
class Chapter
{
    /**
     * @var int
     */
    public $startingPage;

    /**
     * @var string
     */
    public $name;
}
```
For testing purposes I have custom data provider that serves dummy instances of books, each with several chapters. I also have a `Normalizer` that handles normalizing `Chapter`s. This works well initially:

![basic query](https://i.imgur.com/iX9zq1y.png)

But say I want to fetch only the chapter names, I run into the following error:

`Field \"chapters\" of type \"Iterable!\" must not have a sub selection.`

![sub-selection errors](https://i.imgur.com/V1tKxUd.png)

This is a contrived example, of course, but you can imagine some of the properties on the nested object being bandwidth-heavy or expensive to compute.

I saw that there has been quite a bit of refactoring of the GraphQL code in `master`, but unfortunately I'm experiencing this issue with both the `2.4` branch as well as `master`. I also tried to go through the GraphQL code but I'll admit that it's a bit over my head.

Any guidance would be appreciated. Thanks!

**Comment by alanpoulain** [comment]
Today the schema is built only with the resources. That's why there is this issue.
I plan to do it relatively soon since it's a very asked feature.

**Comment by hoangnd25** [comment]
Creating a custom type (from ObjectType) then using TypeConverter to replace the default type with the custom type seems to work for me.

**Comment by alanpoulain** [comment]
Yes it can be a solution.

**Comment by ehough** [comment]
> Creating a custom type (from ObjectType) then using TypeConverter to replace the default type with the custom type seems to work for me.

@hoangnd25 any chance you could share a little pseudo-code showing your custom type and TypeConverter? Would really appreciate any tips you could offer.

**Comment by hoangnd25** [comment]
You could create custom type like this


```php
<?php

use GraphQL\Type\Definition\Type;

class ChapterType extends ObjectType
{
    public function __construct()
    {
        parent::__construct([
            'name' => 'Chapter',
            'fields' => [
                'startingPage' => [
                    'type' => Type::int(),
                ],
                'name' => [
                    'type' => Type::string()
                ],
            ],
            'resolveField' => [$this, 'resolve']
        ]);
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo)
    {
         if ($resolveInfo->fieldName === 'startingPage') {
                return $root['startingPage'];
         }
    }
}
```

Then use TypeConverter to replace it

```php
<?php

final class TypeConverter implements TypeConverterInterface
{

    public function convertType(Type $type, bool $input, ?string $queryName, ?string $mutationName, string $resourceClass, string $rootResource, ?string $property, int $depth)
    {
        if (Type::BUILTIN_TYPE_OBJECT === $type->getBuiltinType()
            && is_a($type->getClassName(), Chapter::class, true)
        ) {
            return 'Chapter';

            // or use the type container
            // return $this->typeContainer->get(ChapterType::class)
        }

        return $this->defaultTypeConverter->convertType($type, $input, $queryName, $mutationName, $resourceClass, $rootResource, $property, $depth);
    }
}
```

You would need to extend ObjectType or equivalent, `ApiPlatform\Core\GraphQl\Type\Definition\TypeInterface` only works for scalar types

You might need to create a normalizer for `Chapter` as well.

This is just a hack imo.

**Comment by alanpoulain** [comment]
Should be solved with https://github.com/api-platform/core/pull/3327.

**Comment by wcoppens** [comment]
@alanpoulain perhaps you or someone else can share a correct way on configuring the annotations on the model classes? Or is there some example for this case?

Setting the child property to `@var ChildClass[]` still results in `Iterable` for me, turning it into `Collection<ChildClass>` does result in a correct Introspection result however query results are empty in this case while the returned object from the dataprovider definitely isn't.

Thanks!

**Comment by oleg-brizy** [comment]
I had this issue with a regular object type.

```php
<?php

declare(strict_types=1);

namespace App\Type\Definition;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use ApiPlatform\Core\GraphQl\Type\Definition\TypeInterface;

final class SeoPropsType extends ObjectType implements TypeInterface
{
    public function __construct(array $config = [])
    {
        $config['fields'] = [
            'title' => Type::string(),
            'description' => Type::string(),
        ];

        parent::__construct($config);
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function serialize($value)
    {
        return $value;
    }

    public function parseValue($value)
    {
        return $value;
    }

    public function parseLiteral($valueNode, ?array $variables = null)
    {
        return $valueNode;
    }
}
```

because [`TypeInterface extends LeafType`](https://github.com/api-platform/core/blob/e7dad315e01a015c83901698811285b558a2072e/src/GraphQl/Type/Definition/TypeInterface.php#L23) and [it causes the error](https://github.com/webonyx/graphql-php/blob/0dd030e0074cd4774620608408ad9bfae95b902f/src/Validator/Rules/ScalarLeafs.php#L25-L28).

**The solution** was to not implement `TypeInterface` and register the type manually
_(because [only `TypeInterface` implementations are registered automatically](https://github.com/api-platform/core/blob/e7dad315e01a015c83901698811285b558a2072e/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L462-L463))_

```php
final class SeoPropsType extends ObjectType { ... }
```

```yaml
services:
    App\Type\Definition\SeoPropsType:
      tags: [ 'api_platform.graphql.type' ]
```

----

Isn't `TypeInterface extends LeafType` a bug?
Because this is a conflict `MyType extends ObjectType implements TypeInterface🡒LeafType` - **Object is not a Leaf**

**Comment by alanpoulain** [comment]
@oleg-brizy fixed in https://github.com/api-platform/core/pull/3621.

**Comment by oleg-brizy** [comment]
@alanpoulain Thanks. But I can't use it because it's not merged and I can't merge it in my fork because I get conflicts.

**Comment by KorvinSzanto** [comment]
> Setting the child property to `@var ChildClass[]` still results in `Iterable` for me, turning it into `Collection<ChildClass>` does result in a correct Introspection result however query results are empty in this case while the returned object from the dataprovider definitely isn't.

Did you ever get to the bottom of why the query results are empty for the contained items? I'm having to use simple arrays for my subresources because otherwise they aren't selectable. No error just an empty result.
