### ISSUE TITLE
Heads up: PHP 7.4 breaking changes

### ISSUE THREAD

**Issue by Devristo** [api-platform/core#3017]
Note: this issue is just a heads up. I know PHP 7.4 might be out of your scope for now. But there are some 'breaking changes' to watch out for.

For example due to https://github.com/php/php-src/pull/4386 the following line will throw an error when $parentOperation is null: 

https://github.com/api-platform/core/blob/345612c913e1aca6da4f4aa1cd885421ca6385ff/src/Operation/Factory/SubresourceOperationFactory.php#L78

Possibly running the tests on PHP 7.4 would uncover more issues.

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/pull/3036

**Comment by Devristo** [comment]
Perfect ! :tada:

**Comment by Devristo** [comment]
As the
