### ISSUE TITLE
Swagger generates operation id's with small first letter.

### ISSUE THREAD

**Issue by Nykilor** [api-platform/core#3022]
I have a problem, when I tried to write functional tests for my app I got an following error 

		PHPUnit 7.5.15 by Sebastian Bergmann and contributors.

		Testing Project Test Suite
		2019-08-27T14:16:24+02:00 [critical] Uncaught PHP Exception ApiPlatform\Core\Exception\RuntimeException: "The operation "GETQuizCollection" cannot be found in the Swagger specification." at D:\xampp\htdocs\quizz\quizz-api\vendor\api-platform\core\src\Bridge\Symfony\Bundle\Action\SwaggerUiAction.php line 180
		E                                                                   1 / 1 (100%)

		Time: 4.33 seconds, Memory: 44.00 MB

		There was 1 error:

		1) App\Tests\QuizResourceApiTest::testRetriveQuizzesList
		Undefined property: Symfony\Component\DomCrawler\Crawler::$headers

		D:\xampp\htdocs\quizz\quizz-api\tests\QuizResourceApiTest.php:19

		ERRORS!
		Tests: 1, Assertions: 0, Errors: 1.

So I was wondering why do I get this if that route should be available, so I ran the command api:openapi:export, and to my surprise it appears that all the operationId start with a small letter.

		{
			"swagger": "2.0",
			"basePath": "\/",
			"info": {
				"title": "",
				"version": "0.0.0"
			},
			"paths": {
				"\/api\/answers": {
					"post": {
						"tags": [
							"Answer"
						],
						"operationId": "pOSTAnswerCollection",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Creates a Answer resource.",
						"responses": {
							"201": {
								"description": "Answer resource created",
								"schema": {
									"$ref": "#\/definitions\/Answer"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "answer",
								"in": "body",
								"description": "The new Answer resource",
								"schema": {
									"$ref": "#\/definitions\/Answer"
								}
							}
						]
					}
				},
				"\/api\/answers\/{id}": {
					"put": {
						"tags": [
							"Answer"
						],
						"operationId": "pUTAnswerItem",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Replaces the Answer resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							},
							{
								"name": "answer",
								"in": "body",
								"description": "The updated Answer resource",
								"schema": {
									"$ref": "#\/definitions\/Answer"
								}
							}
						],
						"responses": {
							"200": {
								"description": "Answer resource updated",
								"schema": {
									"$ref": "#\/definitions\/Answer"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"delete": {
						"tags": [
							"Answer"
						],
						"operationId": "dELETEAnswerItem",
						"summary": "Removes the Answer resource.",
						"responses": {
							"204": {
								"description": "Answer resource deleted"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						]
					},
					"get": {
						"tags": [
							"Answer"
						],
						"operationId": "gETAnswerItem",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves a Answer resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						],
						"responses": {
							"200": {
								"description": "Answer resource response",
								"schema": {
									"$ref": "#\/definitions\/Answer"
								}
							},
							"404": {
								"description": "Resource not found"
							}
						}
					}
				},
				"\/api\/media_objects": {
					"post": {
						"consumes": [
							"multipart\/form-data"
						],
						"parameters": [
							{
								"in": "formData",
								"name": "file",
								"type": "file",
								"description": "The file to upload"
							}
						],
						"tags": [
							"MediaObject"
						],
						"operationId": "postMediaObjectCollection",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Creates a MediaObject resource.",
						"responses": {
							"201": {
								"description": "MediaObject resource created",
								"schema": {
									"$ref": "#\/definitions\/MediaObject-media_object_read"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"get": {
						"tags": [
							"MediaObject"
						],
						"operationId": "getMediaObjectCollection",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves the collection of MediaObject resources.",
						"responses": {
							"200": {
								"description": "MediaObject collection response",
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#\/definitions\/MediaObject-media_object_read"
									}
								}
							}
						},
						"parameters": [
							{
								"name": "page",
								"in": "query",
								"required": false,
								"description": "The collection page number",
								"type": "integer"
							}
						]
					}
				},
				"\/api\/media_objects\/{id}": {
					"get": {
						"tags": [
							"MediaObject"
						],
						"operationId": "getMediaObjectItem",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves a MediaObject resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						],
						"responses": {
							"200": {
								"description": "MediaObject resource response",
								"schema": {
									"$ref": "#\/definitions\/MediaObject-media_object_read"
								}
							},
							"404": {
								"description": "Resource not found"
							}
						}
					}
				},
				"\/api\/questions": {
					"post": {
						"tags": [
							"Question"
						],
						"operationId": "pOSTQuestionCollection",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Creates a Question resource.",
						"responses": {
							"201": {
								"description": "Question resource created",
								"schema": {
									"$ref": "#\/definitions\/Question"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "question",
								"in": "body",
								"description": "The new Question resource",
								"schema": {
									"$ref": "#\/definitions\/Question"
								}
							}
						]
					}
				},
				"\/api\/questions\/{id}": {
					"put": {
						"tags": [
							"Question"
						],
						"operationId": "pUTQuestionItem",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Replaces the Question resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							},
							{
								"name": "question",
								"in": "body",
								"description": "The updated Question resource",
								"schema": {
									"$ref": "#\/definitions\/Question"
								}
							}
						],
						"responses": {
							"200": {
								"description": "Question resource updated",
								"schema": {
									"$ref": "#\/definitions\/Question"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"delete": {
						"tags": [
							"Question"
						],
						"operationId": "dELETEQuestionItem",
						"summary": "Removes the Question resource.",
						"responses": {
							"204": {
								"description": "Question resource deleted"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						]
					},
					"get": {
						"tags": [
							"Question"
						],
						"operationId": "gETQuestionItem",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves a Question resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						],
						"responses": {
							"200": {
								"description": "Question resource response",
								"schema": {
									"$ref": "#\/definitions\/Question"
								}
							},
							"404": {
								"description": "Resource not found"
							}
						}
					}
				},
				"\/api\/quizzes": {
					"get": {
						"tags": [
							"Quiz"
						],
						"operationId": "gETQuizCollection",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves the collection of Quiz resources.",
						"responses": {
							"200": {
								"description": "Quiz collection response",
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#\/definitions\/Quiz-quizzes_read_all"
									}
								}
							}
						},
						"parameters": [
							{
								"name": "page",
								"in": "query",
								"required": false,
								"description": "The collection page number",
								"type": "integer"
							}
						]
					},
					"post": {
						"tags": [
							"Quiz"
						],
						"operationId": "post_quizzQuizCollection",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Creates a Quiz resource.",
						"responses": {
							"201": {
								"description": "Quiz resource created",
								"schema": {
									"$ref": "#\/definitions\/Quiz-post_quizz"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "quiz",
								"in": "body",
								"description": "The new Quiz resource",
								"schema": {
									"$ref": "#\/definitions\/Quiz-quizzes_save_user_single"
								}
							}
						]
					}
				},
				"\/api\/quizzes\/{id}": {
					"put": {
						"tags": [
							"Quiz"
						],
						"operationId": "pUTQuizItem",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Replaces the Quiz resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							},
							{
								"name": "quiz",
								"in": "body",
								"description": "The updated Quiz resource",
								"schema": {
									"$ref": "#\/definitions\/Quiz"
								}
							}
						],
						"responses": {
							"200": {
								"description": "Quiz resource updated",
								"schema": {
									"$ref": "#\/definitions\/Quiz"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"delete": {
						"tags": [
							"Quiz"
						],
						"operationId": "dELETEQuizItem",
						"summary": "Removes the Quiz resource.",
						"responses": {
							"204": {
								"description": "Quiz resource deleted"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						]
					},
					"get": {
						"tags": [
							"Quiz"
						],
						"operationId": "gETQuizItem",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves a Quiz resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						],
						"responses": {
							"200": {
								"description": "Quiz resource response",
								"schema": {
									"$ref": "#\/definitions\/Quiz-quizzes_read_single"
								}
							},
							"404": {
								"description": "Resource not found"
							}
						}
					}
				},
				"\/api\/quizzes\/{id}\/questions": {
					"get": {
						"tags": [
							"Question",
							"Quiz"
						],
						"operationId": "api_quizzes_questions_get_subresource",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves the collection of Question resources.",
						"responses": {
							"200": {
								"description": "Question collection response",
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#\/definitions\/Question"
									}
								}
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						]
					}
				},
				"\/api\/reports": {
					"get": {
						"tags": [
							"Report"
						],
						"operationId": "gETReportCollection",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves the collection of Report resources.",
						"responses": {
							"200": {
								"description": "Report collection response",
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#\/definitions\/Report-report_read"
									}
								}
							}
						},
						"parameters": [
							{
								"name": "page",
								"in": "query",
								"required": false,
								"description": "The collection page number",
								"type": "integer"
							}
						]
					},
					"post": {
						"tags": [
							"Report"
						],
						"operationId": "pOSTReportCollection",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Creates a Report resource.",
						"responses": {
							"201": {
								"description": "Report resource created",
								"schema": {
									"$ref": "#\/definitions\/Report-report_read"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "report",
								"in": "body",
								"description": "The new Report resource",
								"schema": {
									"$ref": "#\/definitions\/Report-report_save"
								}
							}
						]
					}
				},
				"\/api\/reports\/{id}": {
					"get": {
						"tags": [
							"Report"
						],
						"operationId": "gETReportItem",
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Retrieves a Report resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						],
						"responses": {
							"200": {
								"description": "Report resource response",
								"schema": {
									"$ref": "#\/definitions\/Report-report_read"
								}
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"put": {
						"tags": [
							"Report"
						],
						"operationId": "pUTReportItem",
						"consumes": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"produces": [
							"application\/ld+json",
							"application\/json",
							"text\/html"
						],
						"summary": "Replaces the Report resource.",
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							},
							{
								"name": "report",
								"in": "body",
								"description": "The updated Report resource",
								"schema": {
									"$ref": "#\/definitions\/Report-report_put"
								}
							}
						],
						"responses": {
							"200": {
								"description": "Report resource updated",
								"schema": {
									"$ref": "#\/definitions\/Report-report_read"
								}
							},
							"400": {
								"description": "Invalid input"
							},
							"404": {
								"description": "Resource not found"
							}
						}
					},
					"delete": {
						"tags": [
							"Report"
						],
						"operationId": "dELETEReportItem",
						"summary": "Removes the Report resource.",
						"responses": {
							"204": {
								"description": "Report resource deleted"
							},
							"404": {
								"description": "Resource not found"
							}
						},
						"parameters": [
							{
								"name": "id",
								"in": "path",
								"required": true,
								"type": "string"
							}
						]
					}
				}
			},
			"securityDefinitions": {
				"apiKey": {
					"type": "apiKey",
					"in": "header",
					"description": "Value for the Authorization header",
					"name": "Authorization"
				}
			},
			"security": [
				{
					"apiKey": []
				}
			],
			"definitions": {
				"Answer": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"question": {
							"type": "string"
						},
						"text": {
							"type": "string"
						},
						"photo": {
							"type": "string"
						},
						"isAnswer": {
							"type": "boolean"
						}
					}
				},
				"MediaObject": {
					"type": "object",
					"description": "",
					"externalDocs": {
						"url": "http:\/\/schema.org\/MediaObject"
					},
					"properties": {
						"contentUrl": {
							"type": "string"
						},
						"file": {
							"type": "string"
						},
						"filePath": {
							"type": "string"
						},
						"user": {
							"type": "string"
						}
					}
				},
				"MediaObject-media_object_read": {
					"type": "object",
					"description": "",
					"externalDocs": {
						"url": "http:\/\/schema.org\/MediaObject"
					},
					"properties": {
						"contentUrl": {
							"type": "string"
						}
					}
				},
				"Question": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"quiz": {
							"type": "string"
						},
						"text": {
							"type": "string"
						},
						"photo": {
							"type": "string"
						},
						"chart": {
							"type": "array",
							"items": {
								"type": "string"
							}
						},
						"answers": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"Quiz": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"user": {
							"type": "string"
						},
						"title": {
							"type": "string"
						},
						"tags": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"type": {
							"type": "integer"
						},
						"photo": {
							"type": "string"
						},
						"creationDate": {
							"readOnly": true,
							"type": "string"
						},
						"updateDate": {
							"type": "string"
						},
						"isPublic": {
							"type": "boolean"
						},
						"disabled": {
							"type": "boolean"
						},
						"disablingReason": {
							"type": "string"
						},
						"questions": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"Quiz-post_quizz": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"user": {
							"type": "string"
						},
						"title": {
							"type": "string"
						},
						"tags": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"type": {
							"type": "integer"
						},
						"photo": {
							"type": "string"
						}
					}
				},
				"Quiz-quizzes_read_all": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"user": {
							"type": "string"
						},
						"title": {
							"type": "string"
						},
						"tags": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"type": {
							"type": "integer"
						},
						"photo": {
							"type": "string"
						}
					}
				},
				"Quiz-quizzes_read_single": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"user": {
							"type": "string"
						},
						"title": {
							"type": "string"
						},
						"tags": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"type": {
							"type": "integer"
						},
						"photo": {
							"type": "string"
						},
						"questions": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"Quiz-quizzes_save_user_single": {
					"type": "object",
					"description": "",
					"properties": {
						"title": {
							"type": "string"
						},
						"tags": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"type": {
							"type": "integer"
						},
						"photo": {
							"type": "string"
						}
					}
				},
				"Report-report_put": {
					"type": "object",
					"description": "",
					"properties": {
						"resolved": {
							"type": "boolean"
						},
						"resolvedBy": {
							"type": "string"
						},
						"resolveResponse": {
							"type": "string"
						}
					}
				},
				"Report-report_read": {
					"type": "object",
					"description": "",
					"properties": {
						"id": {
							"readOnly": true,
							"type": "integer"
						},
						"quiz": {
							"type": "string"
						},
						"user": {
							"type": "string"
						},
						"reason": {
							"type": "string"
						},
						"description": {
							"type": "string"
						},
						"resolved": {
							"type": "boolean"
						},
						"resolvedBy": {
							"type": "string"
						},
						"resolveResponse": {
							"type": "string"
						},
						"creationDate": {
							"readOnly": true,
							"type": "string",
							"format": "date-time"
						}
					}
				},
				"Report-report_save": {
					"type": "object",
					"description": "",
					"properties": {
						"quiz": {
							"type": "string"
						},
						"user": {
							"type": "string"
						},
						"reason": {
							"type": "string"
						},
						"description": {
							"type": "string"
						}
					}
				}
			}
		}

I already tried to update composer packages but it didn't help resolve the issue. (I use the latest 2.4.6 api platform)
I also tried to set up the project again but it didn't help either for some reason all the names start with a small letter. 

Anyone has an idea how to resolve this issue ?

The project: 
https://github.com/Nykilor/quizz-api

**Comment by WhiteRabbitDE** [comment]
I think that is caused by line 224 in the DocumentationNormalizer

` $pathOperation['operationId'] ?? $pathOperation['operationId'] = lcfirst($operationName).ucfirst($resourceShortName).ucfirst($operationType);
`

**Comment by WhiteRabbitDE** [comment]
Wouldn't it be good to use "lower" instead of "lcfirst" for the operationName so it would be consistent?

**Comment by Nykilor** [comment]
It worked. Thank you, I was to exhausted to notice such a thing I guess 🥇
