### ISSUE TITLE
ApiTestCase is incompatible with LiipTestFixturesBundle

### ISSUE THREAD

**Issue by daFish** [api-platform/core#3023]
Hello there,

I was testing the new `ApiTestCase`-class and unfortunately it is incompatible with https://github.com/liip/LiipTestFixturesBundle.

The reason is that `ApiTestCase` is extending `KernelTestCase`. The database tool from mentioned bundle expects an object of type `WebTestCase`:

https://github.com/liip/LiipTestFixturesBundle/blob/master/src/Services/DatabaseToolCollection.php#L46

I see two ways to make them compatible:
- let `ApiTestCase` extend from `WebTestCase`
- type hint `KernelTestCase` instead of `WebTestCase` in LiipTestFixturesBundle

As LiipTestFixturesBundle states it is used in functional tests, I'm that would be the correct place to change it.

**Comment by teohhanhui** [comment]
There's nothing for us to do here. The bundle should be changed, or you could use https://github.com/hautelook/AliceBundle

**Comment by daFish** [comment]
Thanks for the information. In the meantime the bundle itself has been updated to address this issue: https://github.com/liip/LiipTestFixturesBundle/pull/29
