### ISSUE TITLE
[GraphQL] Custom errors for graphql endpoint

### ISSUE THREAD

**Issue by mahmoodbazdar** [api-platform/core#3024]
In GraphQL php library that Api platform is using it user can define custom error format. 
Here is documentation for custom errors in  php GraphQL library:
https://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting

I think we should add this feature so developers can create their own error formats based on exceptions.

Example 1:  We don't have status codes for errors and I think its helps if we return a status property in error object so frontend developer can decide how to show it .

Example 2: Validation errors format isn't good now. All of error massages concat in one string and frontend developer needs to do some process on error string  on every error messages.

**Comment by alanpoulain** [comment]
Having a way to customize the errors would be indeed a nice improvement.

**Comment by mahmoodbazdar** [comment]
I'll try to create pull request for it.

**Comment by lukasluecke** [comment]
This is actually a pretty important issue, since right now errors get completely swallowed in production environments, and there's no way to handle them (at least I didn't find one).

**Comment by lecajer** [comment]
Hi, why this ? "We don't have status codes for errors" shouldn't api platform return http status code different from 2xx when there is an error ?
