### ISSUE TITLE
Operation ids when dumping swagger json

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#3025]
Hi everyone,

in issue #3022 i noticed that the Operation id is generated with lcfirst. When you use uppercase in the annotations you end Up with Something like gETResourceCollection. 

Imho it would be better to replace lcfirst with lower. Example in the mentioned issue #3022.

Wdyt ?

**Comment by soyuka** [comment]
I'd recommend to use camelCase and not a mix of uppercase/lowercase. Anyway, you could always override the [DocumentationNormalizer](https://github.com/api-platform/core/blob/1c19bf56d45debbfa83fcf80d051e0a2fd540f36/src/Swagger/Serializer/DocumentationNormalizer.php#L254) and use your own naming conventions there? 

I see no harm in modifying this though, feel free to open a pull request !

**Comment by soyuka** [comment]
Mhh after a second look I think that there's a confusion here between a method and an operation name. The operation name has absolutely no reason to be written in Uppercase and we definitely should not change that. The error in #3022 comes from a configuration error/confusion and is expected to happen imo.
