### ISSUE TITLE
maximumItemsPerPage attribute isn't consistent with other pagination attributes

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3050]
The  `maximumItemsPerPage` attribute is not consistent with all other pagination related attributes. They all start with the `pagination` prefix. Except this one. We should deprecate the current one, and introduce a consistent new one.

**Comment by soyuka** [comment]
bug fix on 2.4

**Comment by bpolaszek** [comment]
It looks like `DocumentationNormalizer` does not reflect `minimum` / `maximum` [pagination attributes](https://swagger.io/docs/specification/2-0/describing-parameters/#default-parameters-values) for Swagger v2 (seek for _Default parameter values_), this is why that part is currently untested.
Should I add support in the same PR or in a separate one?

**Comment by alanpoulain** [comment]
It would be better in a separate one.
