### ISSUE TITLE
[GraphQL] Use same Type for Item and Collection item if possible

### ISSUE THREAD

**Issue by lukasluecke** [api-platform/core#3059]
If there are no differences in the serialization for Item and Collection items of a resource, we should use the same type - otherwise things get unnecessarily complicated (e.g. Fragments would have to be duplicated).

Currently it also breaks several "smart" caching systems that rely on the `__typename`.

This would be similar to how we handle the Type used for Mutations (GraphQl/Type/TypeBuilder.php:104) 

Related to #3015.

**Comment by lukasluecke** [comment]
@alanpoulain

**Comment by lukasluecke** [comment]
@alanpoulain @mahmoodbazdar Since you were involved in this change, what do you think?

**Comment by mahmoodbazdar** [comment]
@lukasluecke Allowing user to have different serialization group for items and collections was one of the reasons for this change. 
One solution may be to add `query` back to operations and it apply to both items and collections and if users defined `item_query` and `collection_query` we override query settings.

**Comment by jamesisaac** [comment]
Regarding the serialization side, is the main use-case different permission levels meaning different fields visible for different users?

Is so, the recommended approach I have seen suggested by the Facebook team, is keeping the type the same, but having some of the fields come back as null if the user isn't authorised to see them ([link](https://github.com/graphql/graphql-js/issues/113#issuecomment-129569874)).  (Maybe this feature could somehow be provided by API Platform??)

Perhaps there are some situations where a different type would be preferred, but I think in the majority of cases keeping it simple with a single type per entity might be more desirable?

**Comment by lukasluecke** [comment]
@mahmoodbazdar Did you check the way we handle the Mutation Type? My suggestion is to only use the different type, if there are actually differences in the serialization configuration.

**Comment by lukasluecke** [comment]
@jamesisaac That also sounds interesting - but then we would have to modify the Type to make all possibly inaccessible fields nullable. I think this might be best suited for a separate discussion / issue 🙂

**Comment by mahmoodbazdar** [comment]
@lukasluecke You are right.I think we should have done that. I think its a small change. we should update it here:
https://github.com/api-platform/core/blob/0354379e3f016909c60e5d89d90a4bccb42cbfbb/src/GraphQl/Type/TypeBuilder.php#L64-L72
and check if serialization groups are different.
I can create pull request for that(Or you can do that yourself if you need it quickly)

**Comment by lukasluecke** [comment]
@mahmoodbazdar Yes, that's what I was thinking as well 🙂 If you could create the PR that would be great 🙌

**Comment by mahmoodbazdar** [comment]
@lukasluecke OK, I'll create PR this weekend🙂

**Comment by lukasluecke** [comment]
Just noticed another (bigger) issue with the current implementation - it also breaks several "smart" caching systems that rely on the `__typename` (e.g. in Apollo, Urql).

If I have a list of resources, the items have the `Collection` type - If I now update a single resource with a mutation, the result I get has the `Item` type, which means that the cache doesn't know they relate to the same resource.

I think this should be reason enough to also add a big warning about this in the Docs - you could probably solve this by overriding the cache key generation logic (I don't use Apollo anymore, but it would probably be `dataIdFromObject´).

**Comment by jamesisaac** [comment]
@lukasluecke Actually after reading this comment: https://github.com/api-platform/core/issues/3040#issuecomment-527447898 I think the technique I described would already be possible, if the auth-related serialization groups are added with the Context Builder.

I'm just thinking the technique allowed with #3015  (and also now recommended in the docs) is maybe an anti-pattern... is there really a strong use-case where you'd want different types for the same entity on collection vs item?  The example given in https://github.com/api-platform/docs/pull/863 (admin vs user view) is probably better solved with the Context Builder making fields null for non-admin?

Like you've just commented above, it breaks the assumptions most GraphQL libraries make -- one of the major points of GraphQL is that you can yourself choose exactly which data you want in different queries (say a detailed "item" view vs a smaller "collection" view), that's not something that needs to be enforced at schema level.

**Comment by lukasluecke** [comment]
@jamesisaac I don't have a strong opinion about the general use-case at the moment - I just want this to be opt-in instead of breaking "everything" without a reason 😅

I think splitting the operations makes sense, because this way you can control if they are registered at all (e.g. you might not even want to provide access to some resources as a collection, only individual items?).

Following the solution we chose for the mutations (as indicated in the issue description) would allow people that have this need of separate serialization settings to fulfill it (with the caveats noted in my last comment), but not affect everyone else. Even the use case for different types returned from mutations might be an "anti-pattern", but it's certainly one that might / did arise.

**Comment by lukasluecke** [comment]
@dunglas Please make sure this is resolved before the 2.5 release, otherwise we will break a lot of frontend stuff unnecessarily 😕

@mahmoodbazdar Do you know when you'll get to that PR yet? Otherwise I'll try to fit it in this week 🙂
