### ISSUE TITLE
References to Resources in an External API

### ISSUE THREAD

**Issue by mab05k** [api-platform/core#3074]
I have 2 API services. 

API 1 Resource with a reference to a resource in API 2
```json
{
  "id": 1,
  "api2Resource": "https://example.com/api/api_2_resource/1"
}
```

I want to be able to store the Id of the external resource `1` in my Database, but present it as an IRI (with or without the hostname and protocol) in the API interface.

Is this something this project is willing to support?

**Comment by soyuka** [comment]
I think that this is a use case for subresources. But yes it is supported as IRIs are linked to the Router, if the route is present it should work as expected.

**Comment by mab05k** [comment]
That doesn't sound quite right for what I'm looking for. The "API 2" (think 3rd party API) resource is in a completely different Service/Application, and "API 1" would not be exposing that route, or have it defined in its router.

**Comment by soyuka** [comment]
mhh you can take a look at adding a custom normalizer for this or maybe the IriConverter

**Comment by mab05k** [comment]
The pull request I submitted adds ability for the Absolute URL. I'm also taking a look at putting something together for you to review that could support the external resources like I suggested.

Although, maybe this is something I should just implement in my own application instead of attempting to add the feature into the project? @soyuka

**Comment by soyuka** [comment]
> Although, maybe this is something I should just implement in my own application instead of attempting to add the feature into the project? @soyuka

How would you add this? I'm not sure that we could easily find a generative way of doing so :|. I'd try for my application first and check if something can come out from it but definitely not sure on how it could work for everyone.

**Comment by mab05k** [comment]
I was able to get it working to generate this. (Note: `/external_dummies` is at `http://example.com/external_dummies`)
```
  Scenario: External Resources should support hostnames and routes separate from the API
    Given there are 1 externalResource objects
    And I add "Accept" header equal to "application/ld+json"
    And I add "Content-Type" header equal to "application/json"
    And I send a "GET" request to "/external_dummies"
    And the JSON should be equal to:
    """
    {
      "@context": "\/contexts\/ExternalDummy",
      "@id": "\/external_dummies",
      "@type": "hydra:Collection",
      "hydra:member": [
        {
          "@id": "\/external_dummies\/1",
          "@type": "ExternalDummy",
          "externalResource": "https:\/\/external-api.com\/external_resources\/1",
          "id": 1
        }
      ],
      "hydra:totalItems": 1
    }
    """
```
This was done by adding a new annotation and some custom Doctrine Types. There are some definite downsides, because it exposes a route for this resource that doesn't actually exist in the API.

I'm going to keep refining it and will push up a PR as a proposal later.
