### ISSUE TITLE
Hardcoded parent constructor parameters on AbstractItemNormalizer

### ISSUE THREAD

**Issue by DethCount** [api-platform/core#3087]
https://github.com/api-platform/core/blob/81d276c33c871ee45605222d474181a503cdf1bd/src/Serializer/AbstractItemNormalizer.php#L75

**Comment by dunglas** [comment]
Hi, I don't understand the issue. Can you elaborate?

**Comment by DethCount** [comment]
You basically block users to use the full potential of this class.
I needed this parameter : PropertyTypeExtractorInterface $propertyTypeExtractor = null

**Comment by dunglas** [comment]
It’s on purpose. API Platform normaliser cannot work without the API Platform metadata system. You must not use a custom property type extractor here. However the API Platform metadata system can use you custom PropertyInfo implementations (and so it will be used by our normalizers).

**Comment by Toflar** [comment]
@dunglas I think I have the same issue here. Maybe missing something but when working with https://github.com/dunglas/doctrine-json-odm, the existing data that's in the database is correctly read in the `ReadListener` but then the `DeserializeListener` basically drops all the data as the serializer will create a new nested object.
What's the correct approach here then?

**Comment by lucasgranberg** [comment]
> It’s on purpose. API Platform’s normalizers cannot work without the API Platform metadata system. You must not use a custom property type extractor here. However the API Platform metadata system can use you custom PropertyInfo implementations (and so it will be used by our normalizers).

I don't see how having access to PropertyInfo and ClassDiscriminatorResolver would get in the way of api-platform's custom normalizers. In my case I need these services in the normalizers becouse otherwise single table inheritance with discriminatorMapping won't work.
