### ISSUE TITLE
Order of the entrypoints list

### ISSUE THREAD

**Issue by mRoca** [api-platform/core#3091]
Calling the main entrypoint of the api-platform stack returns the list of declared resources. For example:
```json
=> GET https://api/

# Accept: application/json
{
    "resourceNameCollection": [
        "App\\Entity\\User",
        "App\\Entity\\Advert"
    ]
}

# Accept: application/ld+json
{
    "@context": "/contexts/Entrypoint",
    "@id": "/",
    "@type": "Entrypoint",
    "user": "/users",
    "advert": "/adverts"
}
```

## The problem

The entrypoints order is not always the same and depends of your system. This can be a problem if you want to test your API. For example:

```diff
--- Expected
+++ Actual
@@ @@
     "@id": "/",
     "@type": "Entrypoint",
-    "user": "/users",
-    "advert": "/adverts"
+    "advert": "/adverts",
+    "user": "/users"
 }
```

## The reason

The [EntrypointAction::__invoke()](https://github.com/api-platform/core/blob/master/src/Action/EntrypointAction.php#L35) method returns the list of declared resources by calling the [AnnotationResourceNameCollectionFactory::create](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php#L26) method, which will call the [ReflectionClassRecursiveIterator::getReflectionClassesFromDirectories](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php#L55) one. In this method, the [get_declared_classes()](https://github.com/api-platform/core/blob/master/src/Util/ReflectionClassRecursiveIterator.php#L54) function is called in order to get all classes from the resources directories.

The result of this method is not always the same, as it depends of your system and your autoloading files.

## The solutions

- Do nothing
- Add a `sort($declared);` after the [$declared = array_merge(get_declared_classes(), get_declared_interfaces());](https://github.com/api-platform/core/blob/master/src/Util/ReflectionClassRecursiveIterator.php#L54) in `ReflectionClassRecursiveIterator`
- Add a `ksort($classes);`  in the [AnnotationResourceNameCollectionFactory::create method](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php#L61)
- Add a `sort($classes);` in the [ResourceNameCollection constructor](https://github.com/api-platform/core/blob/master/src/Metadata/Resource/ResourceNameCollection.php#L30)
- Add a `ResourceNameCollection` or a `Entrypoint` custom serializer to order the result

What do you think about that ? Should we always sort the endpoints list ? Or only sort the `ReflectionClassRecursiveIterator` result ?

**Comment by dunglas** [comment]
Good catch! I'm favor of sorting alphabetically. We should definitively prevent the order to be platform dependent. "Add a sort($classes); in the ResourceNameCollection constructor" looks like the best solution to me.

**Comment by mRoca** [comment]
Ok, I'll create a PR

**Comment by mRoca** [comment]
Done, but I've had to update the `src/Hydra/Serializer/EntrypointNormalizer.php` file as it's the only place where the Resources are listed by their short name and not their class name (my bad).
