### ISSUE TITLE
Error while trying to generate swagger.json

### ISSUE THREAD

**Issue by nassuf** [api-platform/core#310]
Hello,

I am trying to dump a swagger file using api:swagger:dump command and I get this error:

[Symfony\Component\Debug\Exception\ContextErrorException]  
Notice: Undefined index: actualType

The dumped json only contains "/others" path for each resource.
Did you ever have this issue ?

**Comment by dunglas** [comment]
With NelmioApiDoc? I never tried to do that personally but I'm sure it should be fixed in NelmioApiDoc directly.

**Comment by nassuf** [comment]
Yes, this is a command from NelmioApiDoc.
The swagger generated only contains "/others" path for each resource.
Is there a configuration to set for Nelmio to detect Dunglas routes then generate a right swagger ?

**Comment by dunglas** [comment]
No I think nobody tried this before and a patch should be done in NelmioApiDoc to make the Swagger support able to deal with this bundle.

**Comment by Simperfit** [comment]
we added a command in v2.0 , I think this can be closed.
