### ISSUE TITLE
GraphQl: interface feature implementation

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#3116]
Q | A
-- | --
Bug fix? | no
New feature? | yes
BC breaks? | probably
Deprecations? | no
Tests pass? | no
Fixed tickets |  
License | MIT
Doc PR |  

I started the work on implementation of interfaces. The feature is in draft version now and works this way:
1. I've added 2 properties in `ApiResource`: bool `interface` (false by default) and array `implements`.
2. If some resource's `interface` property is `true`, then I create new type as an instance of `InterfaceType` and add postfix `Interface`. E.g. `DocumentInterface`.
3. If some resource has property `implements` which is array of FQN resources, then I validate them and add here https://github.com/api-platform/core/blob/9799193466b0059fd82254798e9a06f32d8ef2f4/src/GraphQl/Type/TypeBuilder.php#L124

This works fine except one thing. See here: https://github.com/api-platform/core/blob/9799193466b0059fd82254798e9a06f32d8ef2f4/src/Metadata/Property/Factory/InheritedPropertyNameCollectionFactory.php#L54-L58

What happens here: any parent resource receives all the properties of his **descendants**. May be this is good until we have interfaces, but this is definitely wrong when we start using Interfaces. `InterfaceType` must contain only his own (and his ancestor's) properties but not his descendants.

See example:
```
/**
 * @ApiResource(interface=true)
 */
class Parent
{
 public parentProperty;
}

/**
 * @ApiResource(implements={"Parent"})
 */
class Child extends Parent
{
 public childProperty;
}
```

`InheritedPropertyNameCollectionFactory` makes `Parent` to have `childProperty`. Which is wrong if we want to use interfaces and query common and specific fields this way:
```
{
  parents {
    parentProperty
    ... on Child {
      childProperty
    }
  }
}
```
To solve the issue I can develop work around (e.g. implement `PropertyNameCollectionFactoryInterface` and use it for resources with new feature, but for all other resources leave the current PropertyFactory to not create BC).

But may be I'm wrong and you can advise me the better way how to implement `interface` feature to avoid the problem explained above?

**Comment by alanpoulain** [comment]
I wonder if it's a good idea to use a property of `ApiResource`. Why not using a PHP interface? They are already managed by API Platform. And you would not have the problem you describe.

**Comment by CvekCoding** [comment]
@alanpoulain it's a draft version, just to play with feature. Yes, I can recognize interface and their descendants automatically based on php, but this doesnt not help me in a described problem. The current `InheritedPropertyNameCollectionFactory` written in a way when interface type (in graphql schema) will have all the properties of all its descendants. Webonyx doesnt allow this and throws an error.

See example:
```
/**
 * @ApiResource()
 */
interface Parent
{
 public getParentProperty();
}

/**
 * @ApiResource()
 */
class FirstChild implements Parent
{
 public firstChildProperty;
}

/**
 * @ApiResource()
 */
class SecondChild implements Parent
{
 public secondChildProperty;
}
```
In this example `InheritedPropertyNameCollectionFactory` will automatically fill `ParentInterface` type with all available properties:  `parentProperty`, `firstChildProperlty`, `secondChildProperty`. Which is obviously wrong. When `Webonyx` validates the resulted schema it throws an error, that `FirstChild` has to have property `secondChildProperty` and `SecondChild` has to have `firstChildProperty`, because they implement interface with all these properties.

The reason of this issue is in the following code:
```
if (is_subclass_of($knownResourceClass, $resourceClass)) { 
     foreach ($this->create($knownResourceClass) as $propertyName) { 
        $propertyNames[$propertyName] = $propertyName; 
     } 
} 
```
There must be condition with the reversed order of parameters: `is_subclass_of($resourceClass, $knownResourceClass)`.

**Comment by alanpoulain** [comment]
It's strange because the tests don't tell this:
https://github.com/api-platform/core/blob/9799193466b0059fd82254798e9a06f32d8ef2f4/features/main/table_inheritance.feature#L448-L523
@teohhanhui maybe you have an idea why?

**Comment by CvekCoding** [comment]
@alanpoulain thanks for the link. I'll check it and let you know.

**Comment by CvekCoding** [comment]
@alanpoulain it's because `tests/Fixtures/TestBundle/Model/ResourceInterfaceImplementation.php` is not an `ApiResource`. When you add `ApiResource` annotation to it you can see that `ResourceInterface` receives additional property `bar`, but should not have it. It will be inherited from `ResourceInterfaceImplementation`.

**Comment by CvekCoding** [comment]
And we must to annotate child classes with `ApiResource`, because otherwise they will not appear in `Schema`.

**Comment by lukasluecke** [comment]
@CvekCoding Awesome, I was just about to start working on this as I need it for proper handling of my entities (Doctrine Inheritance). Could you possibly open (draft) PR with your current implementation?

I just quickly skimmed your proposal and so far I agree with your suggestions - I‘ll try it out in my project as soon as I can and report back.

**Comment by CvekCoding** [comment]
@lukasluecke it works in my project already, but I hardcoded a fix in `InheritedPropertyNameCollectionFactory` and `InheritedPropertyMetadataCollectionFactory` for now. It's not a solution for common use, but first I want to clarify the current issue.
I hope that solution will be ready in a few days.

**Comment by CvekCoding** [comment]
@lukasluecke if this is urgent for you then I'll try to open PR tomorrow.

**Comment by lukasluecke** [comment]
No worries, it's fine 🙂 I just think that having the proposed code available would make for an easier discussion as well - e.g. I think changing the behaviour of the current implementation might be the right thing, instead of adding new classes just for this (depending on what exactly is affected).

**Comment by CvekCoding** [comment]
Changing behavior of current implementation - it's a significant BC. I've added another `PropertyFactory` which handles only classes with new interface feature so we can avoid BCs.
But may be Im working in a wrong direction. Waiting for @alanpoulain opinion.

**Comment by teohhanhui** [comment]
@CvekCoding Have you investigated what's going on with the `InheritedPropertyNameCollectionFactory` and `InheritedPropertyMetadataCollectionFactory`? Should they even exist at all? :laughing:

**Comment by lukasluecke** [comment]
@teohhanhui That's what I was trying to say as well 😅 I couldn't imagine a realistic use case where you would expect the current behaviour - so maybe we could just get rid of it 😄

**Comment by lukasluecke** [comment]
@alanpoulain Even for Doctrine inheritance, the only case where you might want this behaviour is for the `SINGLE_TABLE` strategy, but for `JOINED` it probably won't work (or is at least pretty confusing). And for GraphQL especially, all child fields would have to be nullable on the parent I believe.

**Comment by CvekCoding** [comment]
@teohhanhui yes, I did. This class allows to work with polymorphism in a case when we dont have interfaces.
You can declare some field to be of type `Parent` relation, and this relation receives all the fields of all `Parent` descendants (this is what `InheritedPropertyNameCollectionFactory` is for). This will allow you to query this object with any possible fields. This is not good from OOP point of view, but this is working and solves some problems with queriing of polymorphic objects.

**Comment by CvekCoding** [comment]
> I think we should fix the underlying bugs before you try to build a new feature on top. 

@alanpoulain really I do not see the other way for now. Many projects (even mine) relying on this behavior. As I wrote before, this is very significant breaking change if you remove or change this behavior. My opinion is that we have to work around this issue for now with new Factory and deprecate the current behavior. Everyone who relying on current behavior of Inherited factory will be required to rewrite queries using interface or unions (will be great to add them too later).
But may be I dont see something and @soyuka can advise solution.

**Comment by lukasluecke** [comment]
@CvekCoding Any chance you could push your implementation as a Draft PR? I think this would allow for a much faster discussion of the possible issues 🙂

**Comment by CvekCoding** [comment]
@lukasluecke yes, of course. I'll try to merge the most recent changes in my 2.5 branch tomorrow and push it to create PR.
My project works on 2.4 branch still and all interface related changes are there at this moment.

**Comment by lukasluecke** [comment]
Sounds good, if you need any help with rebasing onto 2.5 or anything just let me know!

**Comment by CvekCoding** [comment]
@lukasluecke so what I have at this moment.
I have my own fork of APIP with some fixes and few improvements.
As I wrote above, my project is on 2.4 still and interface feature is developed and provenly works on this version. You can see it here https://github.com/CvekCoding/core/tree/2.4-interface

Also I moved my interface improvements to 2.5 branch here https://github.com/CvekCoding/core/tree/2.5-fixes . See these commits in 2.5 (I think this branch is interesting for you more):
https://github.com/CvekCoding/core/commit/1c2be617e3b291824ef0fa5fa7964ff222ef7dc9
https://github.com/CvekCoding/core/commit/21db095462973f6b7f1929f586f7dbfa733a0e63
https://github.com/CvekCoding/core/commit/1606bccfc79e4b569a02558eaa4c795444ed7203

But I cant promise that it works ok because I dont use 2.5 for now. 
I can create PR today to the official report so we can discuss the feature there to make it acceptable for APIP. Definitely I did some things in a hurry and they need to be reworked. This is enough for me, but not suitable for APIP.

**Comment by lukasluecke** [comment]
@CvekCoding Are you still interested in working on this? I think it would be really great to have this, as it is quite an important feature in GraphQL 🙂

**Comment by CvekCoding** [comment]
@lukasluecke yes, sure. I want to complete one thing Im working on now and then I can create PR for this feature. I hope I will be able to do this on this weekend (optimistic) or next week.

**Comment by lukasluecke** [comment]
@CvekCoding Awesome, looking forward to the PR! 🚀 No pressure though 🙂

**Comment by kacperjurak** [comment]
@CvekCoding thanks for doing this. This is something what i need in my project and I keep my fingers crossed to make it happen :)

**Comment by lukasluecke** [comment]
@CvekCoding Is there anything I can do to help you move forward with this? From what I can see in your branch you already got the basics down, so I would like to avoid doing the same work again 🙂

**Comment by CvekCoding** [comment]
@lukasluecke in my project I already use interfaces for a quite long time (may be 2-3 months) and it works perfect to me.
But I'm still on APIP@2.4. More of this - I use my own fork with some other fixes and improvements. So the most biggest challenge for me is to migrate my `interface`-related improvements to vanilla APIP@2.5. So I think you cant help me with this. But as I promised, I'll do this on current week. Im near of completing my current bunch of tasks and then I'll dedicate some time on our task.

**Comment by CvekCoding** [comment]
I realize that it's important improvement and my code can be start point to develop this feature for production.
BTW @lukasluecke do you have any plans on developing graphql-subscriptions in Graphql. I know that Dunglas recommended use `Mercure` for this. From my point of view `subscriptions` is a biggest graphql-feature missed in php-world.

**Comment by lukasluecke** [comment]
@CvekCoding Alright, I currently need this functionality for a project, so I'm trying to get your version running right now 🙂 If you have time for a clean-up and proper PR that would be awesome, otherwise I'll just hack something together for now (it's only a prototype 😉)

Thanks for your work already! 🙏

**Comment by lukasluecke** [comment]
@CvekCoding Yeah subscriptions are another thing that would be awesome to have - I have done some preliminary work on them, but nothing runnable. I am not convinced that Mercure **can** be used for them, due to the way the topics work - you would have to generate a "magic" topic per subscription, redirect the original subscription request to that, and then listen for changes on all resources contained in the subscription query, serialize them to GraphQL output and send them there 🤔

I didn't have time to follow up on this yet sadly 🙈  (Probably best to comment in #3124 if you have any ideas)

**Comment by alanpoulain** [comment]
I've almost finished the GraphQL subscriptions implementation :slightly_smiling_face: Coming soon.
Indeed a "magic" topic is generated per subscription in my implementation.

**Comment by lukasluecke** [comment]
@alanpoulain Awesome, thank you! Really looking forward to this "christmas present"! 🎁🙌

**Comment by lukasluecke** [comment]
@CvekCoding I got a basic implementation of interfaces running now (on 2.5 / master) 👍
There were a few things that didn't work originally (related to `Item`/`Collection`-Types)

I have a general question though - should the Interface-Classes only be registered as Interface-Types, or also provide a "base"-Implementation? Unless they are `abstract`, I think it would make sense to also register them as normal types, and also to register their mutations (e.g. a shared `delete` function might make sense?)

**Comment by CvekCoding** [comment]
@alanpoulain as far as I know Apollo and Relay cant work with SSE (Event Sources), but only with web sockets. But when I read about `Mercure` I was under impression that `Mercure` works only with SSE, but not web-sockets. Am I right or this is not a trouble for your implementation?

**Comment by lukasluecke** [comment]
@CvekCoding See my comment in #3124 - there was at one time an implementation of a SSE-Transport, maybe this will could reused?

**Comment by CvekCoding** [comment]
@lukasluecke 
> I got a basic implementation of interfaces running now

Do you mean my implementation?

> should the Interface-Classes only be registered as Interface-Types, or also provide a "base"-Implementation

To answer your question I have to refresh in mind my implementation - so it's hard to answer right now. But at a glance I think it's better to split concerns - interface type must be abstract so it must not be a simple graphql-type. More of this - may be it's possible to map php-interfaces automatically to final graphql-classes.
Example:
```
/**
* @ApiResource()
*/
interface IA {}

/**
* @ApiResource()
*/
interface IB {}

/**
* @ApiResource()
*/
final class A implements IA {}

/**
* @ApiResource()
*/
final class B implements IB {}

/**
* @ApiResource()
*/
final class AB implements IA, IB {}
```
And in schema we will see automatic mapping between types:
- type A implements IA
- type B - implements IB
- and type AB - both IA and IB

I thought about this when I developed interfaces, but something stopped me - dont remember what :)

**Comment by alanpoulain** [comment]
@CvekCoding yes Mercure is based on SSE and to make it work with Apollo you need a compatible transport.
@dunglas is promoting HTTP/2 and SSE over WebSocket (HTTP/1 only), that's why Mercure will be the first implementation. But we can think about how to make it work with WebSocket too afterwards.

**Comment by CvekCoding** [comment]
@lukasluecke PR commit is ready. I'll post it tomorrow am when I'll complete explanation message to attach to PR.
