### ISSUE TITLE
PHP version requirement in `composer.json`

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/core#3122]
`composer.json` says `>=7.1` and being on this PHP version I get:

```
Problem 1
    - doctrine/mongodb-odm 2.0.0-RC2 requires php ^7.2 -> your PHP version (7.1.22) does not satisfy that requirement.
    - doctrine/mongodb-odm 2.0.0-RC1 requires php ^7.2 -> your PHP version (7.1.22) does not satisfy that requirement.
    - Installation request for doctrine/mongodb-odm ^2.0@rc -> satisfiable by doctrine/mongodb-odm[2.0.0-RC1, 2.0.0-RC2].
```

Thought this is a require-dev package, should PHP version be increased to `^7.2`?

**Comment by alanpoulain** [comment]
I don't think so because MongoDB is optional. Having PHP >= 7.2 is only when you use it.

**Comment by maks-rafalko** [comment]
What is "optional MongoDB" could you please define it? It's required (it is placed under `require-dev`) package and `composer install` fails with the error message above.

What I want to say is when I on PHP 7.1 then I **can't** use `api-platform-core`.

Probably, instead of [removing](https://github.com/api-platform/core/blob/e468d98d260e0cf49d63d088fd5678ecab1b8912/.github/workflows/ci.yml#L45) MongoDB package on 7.1 we need to *install* for `>7.2`?

**Comment by alanpoulain** [comment]
The packages in `require-dev` are there when you want to *contribute* to API Platform. They are not used when you want to *use* API Platform.
So yes, if you want to contribute to API Platform, you need to have PHP >= 7.2 (or to ignore the platform requirements in Composer).

**Comment by maks-rafalko** [comment]
This is strange :) But if you guys happy with it, it's ok.

Closing.. Thanks for the feedback.
