### ISSUE TITLE
Add Mercure support for GraphQL subscriptions

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3124]
Currently, API Platform supports Mercure for REST (https://api-platform.com/docs/core/mercure/), but not for GraphQL.
It could be done as described here: https://github.com/dunglas/mercure#how-to-use-mercure-with-graphql

**Comment by lukasluecke** [comment]
I would love to tackle this, but from what I remember the last time I tried to get this working, it wasn't as easy as described there (I think we discussed this already a few months back in Slack). Do you have any concrete pointers on what needs to be done?

https://github.com/CodeCommission/subscriptions-transport-sse was one thing I found back then, that might be useful - but it's not updated and not sure if it even still works.

**Comment by lukasluecke** [comment]
A good first step might be to allow choosing the serialization format and normalization context that the `PublishMercureUpdatesListener` uses per operation.
