### ISSUE TITLE
Swagger-UI - Oauth2 implicit flow does not work

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#3131]
Hi everyone !

As the title says, the implicit workflow does not work in the Swagger-UI. The reason is that the oauth2-redirect.html is missing and the parameter "oauth2RedirectUrl" is initialized with the default value but should point to the oauth2-redirect.html (absolute url) once it is added to the public folder.

We could generate the URL in the SwaggerUiAction by included the assetPackage but that does not seem to be wanted as stated in #1960 .

So any hints on a more elegant solution?

**Comment by teohhanhui** [comment]
I thought you were going to re-submit that PR?

**Comment by teohhanhui** [comment]
What I understand from #1960 is that your approach in #3019 is the correct one.

**Comment by WhiteRabbitDE** [comment]
@teohhanhui  sorry for the confusion. Yes this is a follow up to #3019. But that PR was a bit messy and we agreed that the url to the redirect html should be included in the swagger data array. 
My ideas are the assetPackage or a seperate route with controller and a Templates that includes the html file. In the approach in 3019 i would have to merge the Data in twig which isnt the way to go i guess.

**Comment by teohhanhui** [comment]
Sorry if I didn't make that clear. What I meant is that it should be part of the JS object, not part of the template parameters passed from the controller. :smile:

**Comment by WhiteRabbitDE** [comment]
I totally misunderstood you then and would have just updated the PR :-) I will put up a new one tomorrow, targeting 2.5.

Fun fact: Merging the data in twig was my first solution i dismissed ;-)

**Comment by WhiteRabbitDE** [comment]
New PR is set up so I think we don't need this issue anymore.  Thanks @teohhanhui 😃
