### ISSUE TITLE
[Cache] Create CloudFlarePurger

### ISSUE THREAD

**Issue by eerison** [api-platform/core#3141]
Hi,

Are there any PR to create purger to cloud flare? 

If not I think we can use this Issue for create this purger!

**Comment by dunglas** [comment]
Nobody worked on that yet. Unfortunately, to test this a paid Cloudflare account is required. I'm not sure that it fits in core because it will be a pain to maintain (needs a paid account).

**Comment by eerison** [comment]
You can use it to all plans 

https://api.cloudflare.com/#zone-purge-files-by-url

**Comment by teohhanhui** [comment]
@eerison You're looking at the wrong section, it should be:

https://api.cloudflare.com/#zone-purge-files-by-cache-tags-or-host

**Comment by eerison** [comment]
@teohhanhui But if do I use this `https://github.com/api-platform/core/blob/master/src/HttpCache/VarnishPurger.php` , It going to remove only one cache, or it use tags to remove the caches?  

Because what I was thinking is when I do a update from a resource purge the cache related to that resource.

**Comment by teohhanhui** [comment]
> is it going to use tags to remove the caches?
>
> when I do a update from a resource it gonna purge the cache related to that resource.

Yes, you'd need to support that in your VCL, e.g.: https://github.com/api-platform/api-platform/blob/c7be6494525e3b4c1bdc7cee0d6687c302cee7bc/api/docker/varnish/conf/default.vcl#L36-L49

**Comment by eerison** [comment]
Ok, I gonna resolve this issue thanks :)
