### ISSUE TITLE
assertJsonContains - Declaration of ArraySubset should be compatible with PHPUnit Constraint

### ISSUE THREAD

**Issue by SpiGAndromeda** [api-platform/core#3153]
The following error occurs if I use assertJsonContains inside an ApiTestCase:

`Declaration of ApiPlatform\Core\Bridge\Symfony\Bundle\Test\Constraint\ArraySubset::evaluate($other, string $description = '', bool $returnResult = false) should be compatible with PHPUnit\Framework\Constraint\Constraint::evaluate($other, $description = '', $returnResult = false)`

API core version is 2.5.

The test class:
```php
<?php

declare(strict_types=1);

namespace Tests\Spez\User\Application\Action;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\Client;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;
use InvalidArgumentException;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager;
use Spez\User\Domain\Model\User;
use Spez\User\Infrastructure\Persistence\UserRepository;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\DecodingExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;

/**
 * Class TestGetUsers
 * @package Spez\Tests\Spez\User\Application\Action
 */
final class TestUsers extends ApiTestCase
{
    use RefreshDatabaseTrait;

    /** @var Client */
    private $client;

    /** @var string */
    private $token;

    public function setUp(
    ): void
    {
        /** client creation ... **/
    }

    /**
     * @throws ClientExceptionInterface
     * @throws DecodingExceptionInterface
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function testGetUsers(
    ): void
    {
        $this->client->request('GET',
            '/api/users');

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('content-type',
            'application/ld+json; charset=utf-8');
        $this->assertJsonContains([
            '@context' => '/api/contexts/User',
            '@id' => '/api/users',
            '@type' => 'hydra:Collection',
            'hydra:totalItems' => 10,
            'hydra:view' => [
                '@id' => '/api/users?page=1',
                '@type' => 'hydra:PartialCollectionView',
                'hydra:first' => '/api/users?page=1',
                'hydra:last' => '/api/users?page=1',
                'hydra:next' => '/api/users?page=1',
            ],
        ]);
        $this->assertMatchesResourceCollectionJsonSchema(User::class);
    }
}
```

I don't think that this is an usage error because the example is straight from the documentation. ([Documentation](https://api-platform.com/docs/distribution/testing/))

Best regards,
spigandromeda

**Comment by teohhanhui** [comment]
What is the version of PHPUnit? We only support 8.x

**Comment by SpiGAndromeda** [comment]
@teohhanhui Sorry I propably missed that in the documentation. I relied on symfony phpunit bridge wich seems to ship with phpunit 7.4 (even with modified SYMFONY_PHPUNIT_VERSION).

If it's not in the documentation. Shoud it be added? And why does the composer.json says:
`"phpunit/phpunit": "^7.5.2 || ^8.0",` in require-dev?

**Comment by teohhanhui** [comment]
Personally I'd not recommend using `simple-phpunit` (the `phpunit` wrapper shipped in `symfony/phpunit-bridge`).

We allow PHPUnit 7.5 in our test suite only for compatibility with PHP 7.1. Some tests that are not compatible are skipped in that build.

**Comment by SpiGAndromeda** [comment]
What about updating the documentation? I can't find any hint on the phpunit version.

**Comment by dunglas** [comment]
We only support PHPUnit 8. It's the version included with API Platform, and you can use it with the bridge: https://github.com/api-platform/api-platform/blob/master/api/Dockerfile#L62-L63
Setting `SYMFONY_PHPUNIT_VERSION` to `8.3` works.

**Comment by SpiGAndromeda** [comment]
What about the people don't using API platform with Docker?

**Comment by soyuka** [comment]
update phpunit :)

**Comment by faso-dev** [comment]
> What about the people don't using API platform with Docker?

Exactly, i've the same problem

**Comment by teohhanhui** [comment]
> Exactly, i've the same problem

> update phpunit :)

**Comment by mrtnzagustin** [comment]
Hello. I have problems with assertMatchesResourceCollectionJsonSchema and assertMatchesResourceItemJsonSchema. I have installed symfony 4.4.1 and api-platform core 2.5.4. The test always assert OK no matters which class is passed to the arguments. Example geting collection or item of CLASS A and calling those methods with CLASS B or CLASS C as argument. Always pass the tests. I think maybe is a problem with php unit version?

When i run (as docs recommends https://api-platform.com/docs/distribution/testing/) composer require --dev test-pack http-client justinrainbow/json-schema, symfony phpunit bridge installs php unit 7.5.
Which are the steps to add testing utilities with the last version of phpunit? i am running a custom dockerfile with php fpm and other tools.
And, if i already did "composer require --dev test-pack http-client justinrainbow/json-schema" which are the steps to update phpunit to 8.x, force symfony not to use simple-phpunit and dont broke the compatibility? I run mi tests with "php bin/phpunit".


ANOTHER POSIBILITY: assertMatchesResourceCollectionJsonSchema and assertMatchesResourceItemJsonSchema test the json schema matches entries like '@context' => '/api/contexts/MyClassA' and "@type": "MyClassA", or just generic things like '@type' => 'hydra:Collection'? maybe i missunderstood those methods.

**Comment by teohhanhui** [comment]
If you're using the Symfony PHPUnit Bridge, you can set `SYMFONY_PHPUNIT_VERSION`.

**Comment by mrtnzagustin** [comment]
Thanks @teohhanhui , but using the last version of phpunit didn't solve the problem with assertMatchesResourceCollectionJsonSchema and assertMatchesResourceItemJsonSchema.
EXAMPLE:
```php
public function testGetCollection(): void
{
	// Obtiene el token con login
	$token = $this->login();

	// Solicita laa collection
	$response = static::createClient()->request('GET', "http://localhost/api/endpoint_class_a", [
		'headers' => [
			'Authorization' => "Bearer $token",
		],
	]);

	// Controla que la rta sea exitosa
	$this->assertResponseIsSuccessful();

	// Controla que el content type sea JSON-LD (the default)
	$this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

	// Controla que el json devuelto coincida con el esquema de la clase asociada
	$this->assertMatchesResourceCollectionJsonSchema(ClassB::class);
}
```

Assert 'assertMatchesResourceCollectionJsonSchema' works and shuldn't.

**Comment by teohhanhui** [comment]
@mrtnzagustin Sorry, I don't get what you mean. Can you explain the problem in more detail?

**Comment by mrtnzagustin** [comment]
Problem solved. I missunderstood what "compare json schema" means. I read about it and all that checks is key values types, not specific content like  '@context' must  be equals to '/api/contexts/MyClassA'. Just  '@context' must be a type of "string". Thanks a lot!!

**Comment by faso-dev** [comment]
> > Exactly, i've the same problem
> 
> > update phpunit :)

Okay, i'll check it. Thank you

**Comment by theofidry** [comment]
With PHPUnit9 out what's the update policy regarding the PHPUnit compatibility?

**Comment by dunglas** [comment]
Even the latest patch release? I thought I fixed that 😖.

We must enforce compatibility with all stable PHPUnit versions, including v9. PR welcome!
