### ISSUE TITLE
skip_null_values option always added if PATCH is available request type

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#3159]
Is it necessary to always add the `skip_null_values` option to the normalizer even if the current request method is not `PATCH`? The current implementation will skip null values even for the get requests if the patch option is available for the resource. Also it doesn't seem to matter what format type is being requested... At least if I just want the mime type `application/json` this is still applied if `application/merge-patch+json` is available.

I'm not sure if you were intending to have any backwards compatibility breaking changing in version 2.4.0, but I'm not very familiar with the patch method options. I was using this method in a very abnormal implementation where I have a Symfony form I serialize and then can post individual fields using the PATCH method to validate those individually as a user completes the form.

I can see that the patch format type `application/merge-patch+json` triggers this behaviour and I'm not using that so removed it anyway for now and it doesn't affect me anymore. I just thought it was worth a mention to discuss. Sorry if it's a quick issue and you just end up closing this!

**Comment by dunglas** [comment]
It's intended indeed. It's not a BC break because you need to explicitly enable JSON Merge Patch support to change this behavior (it's not enabled by default, so you can safely upgrade).

It's mandatory to have this behavior, by the RFC:

> Null values in the merge patch are given special meaning to indicate the removal of existing values in the target.
> ...
> This design means that merge patch documents are suitable for describing modifications to JSON documents that primarily use objects for their structure and do not make use of explicit null values
