### ISSUE TITLE
Parent model list child(ren) field(s) on parent resource calls

### ISSUE THREAD

**Issue by dFayet** [api-platform/core#3176]
**API Platform version(s) affected**: 2.4.7

**Description**  
Given the following Model structure:
```
/**
 * @ApiResource()
 */
class Human
{
    /**
     * @var string
     * @ApiProperty(identifier=true)
     */
    public $id;

    /**
     * @var int
     */
    public $age;
}
```
and
```
/**
 * @ApiResource()
 */
class Person extends Human
{
    /**
     * @var string
     */
    public $name;
}
```

I except to have the property `name` on the Resource `Person` and not in the `Human` one
But I get the `name` property also on `/humans` calls.

**How to reproduce**  
Create one resource inheriting from an other.
Call an endpoint on the parent one and see the child's field being there.

**Possible Solution**   
The problem seems to come from https://github.com/api-platform/core/blob/c4f0ef14709ff85fecb36075501e78e247ea2993/src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php#L47-L51

When I'm doing the call `GET /humans` I see that `$resourceClass` is `Human` and have `$knownResourceClass` being `Person`, so `is_subclass_of` return true, and it adds the child property to the parent.
Doing `if (is_subclass_of($resourceClass, $knownResourceClass))` instead resolves the problem.

But before doing a PR I wanted to know if this behavior is correct, because ... ? 
Otherwise I would be happy to do the PR.

**Comment by teohhanhui** [comment]
Can you tell us if you did `POST /persons` or `POST /humans` at first?

**Comment by dFayet** [comment]
As of today I can not reproduce my issue :/

I close this issue and the related PR.
 
I have not seen any mention of the polymorphic behaviour in the doc, and the inheritance seems to not be covered at all (beside the doctrine's one). Is it intended? (if no, I will be more than happy to help on the redaction)
