### ISSUE TITLE
subresourceOperations and security does not work as expected

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#3177]
**Description**  
https://api-platform.com/docs/core/subresources/#access-control-of-subresources

In the documentation, `has_role('ROLE_AUTHENTICATED')` is used and there are no example about using the object.
It's because the `object` var is not the question (according to the doc), it's an array of answers.
So it's really not convenient to use it.

As we will use it in a subresource, it should be qustions IHMO (the resource) and not the answers (the sub resource**s**).

---

We can hack the system but this is so wrong:
```
"security"="object == [] or is_granted('ROLE_VIEW', object[0].getQuestion())"
```

**Comment by julienfalque** [comment]
I'm facing the same issue: if one is not allowed to access the parent resource, they should not be able to see its subresource either. There should be a way to deny access based on the parent resource but this does not seem possible at the moment. As @lyrixx said, a hacky workaround is possible but is totally wrong.
