### ISSUE TITLE
[security_post_denormalize] Validator should be called before Voter

### ISSUE THREAD

**Issue by OlivierFromLille** [api-platform/core#3186]
**Description**  
With the use of security_post_denormalize, we have all data needed in the Voter. But in this Voter, if we check a mandatory property which must not be blank, we'll have a fatal if it is not defined in the body.

**Example**  
Let's use the following example:
```
namespace App\Security;

use App\Entity\Post;
use App\Entity\User;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\Voter\Voter;

class PostVoter extends Voter
{
    // these strings are just invented: you can use anything
    const VIEW = 'view';
    const EDIT = 'edit';
    const CREATE = 'create';

    protected function supports($attribute, $subject)
    {
        // if the attribute isn't one we support, return false
        if (!in_array($attribute, [self::VIEW, self::EDIT, self::CREATE])) {
            return false;
        }

        // only vote on Post objects inside this voter
        if (!$subject instanceof Post) {
            return false;
        }

        return true;
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        $user = $token->getUser();

        if (!$user instanceof User) {
            // the user must be logged in; if not, deny access
            return false;
        }

        // you know $subject is a Post object, thanks to supports
        /** @var Post $post */
        $post = $subject;

        switch ($attribute) {
            case self::VIEW:
                return $this->canView($post, $user);
            case self::EDIT:
                return $this->canEdit($post, $user);
            case self::CREATE:
                return $this->canCreate($post, $user);
        }

        throw new \LogicException('This code should not be reached!');
    }

    private function canView(Post $post, User $user)
    {
        // if they can edit, they can view
        if ($this->canEdit($post, $user)) {
            return true;
        }

        // the Post object could have, for example, a method isPrivate()
        // that checks a boolean $private property
        return !$post->isPrivate();
    }

    private function canEdit(Post $post, User $user)
    {
        // this assumes that the data object has a getOwner() method
        // to get the entity of the user who owns this data object
        return $user === $post->getOwner();
    }

    private function canCreate(Post $post, User $user)
    {
        if ($post->isPrivate() && !in_array(Role::ROLE_POST_PRIVATE, $post->getOwner()->getRoles())) {
            return false;
        }

        return true;
    }
}

```
In the function canCreate(), we check the result of $post->isPrivate(), so we have to set in the POST query the value for the property "private".
So the body given in the POST should be something like that:
```
{
    ...,
    "private": false,
    ...
}
```

If the property "private" is mandatory, we have to create a Constraint like this:
```
App\Entity\Post:
    properties:
        private:
            - Type: bool
            - NotBlank: ~
```

The problem is, if we send the body without the property "private", the Voter is called before the Validator. So we'll have a fatal resulting in "hydra:description": "Return value of App\\Entity\\Post::isPrivate() must be a boolean, null returned"

For the moment, I must call the validate() function in the Voter before checking the condition to grant access or not. Furthermore, the validate() function is called a second time if the Voter grants access.

Thanks

Olivier

**Comment by soyuka** [comment]
related to https://github.com/api-platform/core/issues/1646 somehow? I remember seeing some discussion about this but can't put my hand on it anymore.

**Comment by OlivierFromLille** [comment]
No it is not. Nevermind, I'll fix your work

**Comment by emancypage** [comment]
Hi, I am also expirence this kind of problem that I assume that the $subject in voteOnAttribute() is validated. But it isn't when I use security_post_denormalize for POST method.

Is it possible that annotated Validations would be called before we use any type of Voters? In my case it is security_post_denormalize ?
