### ISSUE TITLE
Extract IRIFilter from SearchFilter?

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#319]
Filtering by IRI or ID can be made more explicit.

This will make things clearer and also has the potential to fix a use case in #70 (i.e. `null` means no value for a to-one relation).

**Comment by teohhanhui** [comment]
Further thought: Perhaps it can be made into a relation filter, where we can also query whether a related resource is contained / not contained in the collection (through a to-many relation).

**Comment by dunglas** [comment]
Looks fair enough.

**Comment by theofidry** [comment]
Are you talking about [`SearchFilter::getFilterValueFromUrl()`](https://github.com/dunglas/DunglasApiBundle/blob/e1344ec2e4cd04f42b03a065acfd2f4c7f69cb06/Doctrine/Orm/Filter/SearchFilter.php)?

**Comment by teohhanhui** [comment]
@theofidry No. I'm talking about "filtering on relations".

**Comment by Simperfit** [comment]
@teohhanhui We can filter on relations with all of the filters, it is still an issue ?

**Comment by teohhanhui** [comment]
@Simperfit This issue is about separating the relation filter from the
string matching filter, because they're unrelated.

**Comment by Simperfit** [comment]
I forgot about this. I think this should be done, and I think we will do it. But it means alot of deprecation.

**Comment by soyuka** [comment]
#2400
