### ISSUE TITLE
AbstractItemNormalizer does not map basic non-string types correctly in XML and CSV

### ISSUE THREAD

**Issue by warslett** [api-platform/core#3192]
**API Platform version(s) affected**: Observed in 1.2.0

**Description**  
When using XML or CSV encoder types, values are always decoded as strings. This results in errors at denormalisation "The type of the \"myFieldName\" attribute must be \"bool\", \"string\" given." Same issue for float and integer values.

**How to reproduce**  
1. Create a resource with a boolean value
2. Enable XML encoder
3. Post XML to resource endpoint setting boolean value
4. Observe error

**Possible Solution**  
I have fixed the issue locally by adding some logic to AbstractItemNormalizer::createAttributeValue to infer valid values depending on type:
```
        if (is_string($value) && 'string' !== $type->getBuiltinType()) {

            if (ctype_digit($value)) {
                if ('float' === $type->getBuiltinType()) {
                    $value = floatval($value);
                }
                if ('int' === $type->getBuiltinType()) {
                    $value = intval($value);
                }
            }

            if ('bool' === $type->getBuiltinType()) {
                if (in_array($value, ['true', 'True', 'T', 't', "1"], true)) {
                    $value = true;
                }
                if (in_array($value, ['false', 'False', 'F', 'f', "0"], true)) {
                    $value = false;
                }
            }
        }
```

**Additional Context**  
This issue is also present in the Serializer project even though it uses a different implementation: https://github.com/symfony/symfony/issues/33849

**Comment by soyuka** [comment]
We do need to fix this upstream (in symfony) and then see what we can do about it in api platform as mentioned by @teohhanhui in https://github.com/api-platform/core/pull/3191#issuecomment-544474697.

**Comment by warslett** [comment]
@soyuka @teohhanhui yes I understand. Just for visibility of where it's are up to... There is a pull request open in Symfony Serializer to fix this issue in AbstractObjectNormalizer which has been quiet for 2 weeks. https://github.com/symfony/symfony/pull/33850

However as I've previously explained, the fix in the Symfony Serializer component will not fix the problem in the API Platform because the fix depends on a dependency which is not injected when used with API Platform. Therefor I have asked the contributor to break his fix out into a protected method so that we can call it in ObjectItemNormalizer so that we can solve the problem with less duplication. If the PR in Symfony Serializer doesn't move in the next few days I will pick it up.

I think this is what you call inheritance hell :laughing:. It looks to me like there is a case in the long term for decoupling AbstractItemNormalizer from AbstractObjectNormalizer as it's own independent implementation of NormalizerInterface and dealing with duplication by composition over inheritance.

**Comment by soyuka** [comment]
If you have time to improve the PR in question you could always open a new one there reusing the commits of the original author, I'm sure he won't see any issue in that.

**Comment by teohhanhui** [comment]
I'd recommend some patience when contributing to open source projects. It's unreasonable to expect something to move forward quickly, especially for a large project like Symfony. :smile:

**Comment by warslett** [comment]
no problem @teohhanhui just dumping all my thoughts while it's fresh in the mind. I'll have forgotten about it in 2 weeks. :smile:

**Comment by lyrixx** [comment]
Since the [upstream PR](https://github.com/symfony/symfony/pull/33850) has been merged, I think we can close this issue, isn't?

**Comment by warslett** [comment]
@lyrixx I'll double check this evening but I think when I first opened this issue the fix in the PR in symfony serializer was not going to fix the problem in ApiPlatform because the fix depends on a dependency which is not injected when used with API Platform. However that was a while ago now so I'll take another look it might have all changed

**Comment by alanpoulain** [comment]
Solved in https://github.com/api-platform/core/pull/4145.
