### ISSUE TITLE
Concurrent requests don't get executed properly / return wrong responses

### ISSUE THREAD

**Issue by Tomaszal** [api-platform/core#3205]
**API Platform version(s) affected**: 2.5.0

**Description:**
When the server receives 2 or more concurrent requests, sometimes it returns the same response to several requests.

**How to reproduce:**
I have setup an [example repository here](https://github.com/Tomaszal/api-platform-concurrent-bug).

**Additional context:**
As you can see in the repository, I am trying to get 3 separate entities using curl:
```
curl https://127.0.0.1:8000/api/entity1s & curl https://127.0.0.1:8000/api/entity2s & curl https://127.0.0.1:8000/api/entity3s
```
Most of the time it works just fine and I receive something like this (expected behaviour):
```
{"@context":"\/api\/contexts\/Entity3","@id":"\/api\/entity3s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
{"@context":"\/api\/contexts\/Entity1","@id":"\/api\/entity1s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
{"@context":"\/api\/contexts\/Entity2","@id":"\/api\/entity2s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
```
However, sometimes I receive a duplicate of some entity instead of the entity I requested (here 2 Entity2s and no Entity1s):
```
{"@context":"\/api\/contexts\/Entity3","@id":"\/api\/entity3s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
{"@context":"\/api\/contexts\/Entity2","@id":"\/api\/entity2s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
{"@context":"\/api\/contexts\/Entity2","@id":"\/api\/entity2s","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
```

**Comment by teohhanhui** [comment]
This does not seem to be related to API Platform.

**Comment by Tomaszal** [comment]
@teohhanhui seems you are right. I've tested the same setup except I replaced Symfony CLI server with Nginx and this behaviour did not occur.
