### ISSUE TITLE
Mercure: Publish updates to collections (addition/removals)

### ISSUE THREAD

**Issue by Richard87** [api-platform/core#3206]
**API Platform version(s) affected**: 2.5.0

**Description**  
API-Platform doesnt publish updates when a collection is updated/changed

**How to reproduce**  
Add or remove a entity that belons in a collection

**Possible Solution**  
Add these lines to `PublishMercureUpdateListener`:
```php
/** @var PersistentCollection $collection */
foreach ($uow->getScheduledCollectionDeletions() as $collection) {
    $this->storeEntityToPublish($collection->getOwner(), 'updatedEntities');
}

/** @var PersistentCollection $collection */
foreach ($uow->getScheduledCollectionUpdates() as $collection) {
    $this->storeEntityToPublish($collection->getOwner(), 'updatedEntities');
}
``` 

**Additional Context**  
If a new Collection (owner) is created, this will publish duplicate events, the "item created", and "item updated" (for collections)

Original issue: https://github.com/symfony/mercure/issues/13

My use case is a React app, with a Group component, that uses the list if items, and passes on the item id to the child... I a new Child is added to a group, it's not beeing pushed to the client since the Group is not updated even if its collection is updated....

**Comment by lukasluecke** [comment]
I think it makes sense to add this - the issue with duplicate events shouldn't matter, since the subscriber can just choose to ignore certain topics / events in these cases.

**Comment by Richard87** [comment]
It's not a big issue, but it would be nice to avoid it...

Instead of having 3 different change-lists, there should be 2, 'regular-changes', and deleted changes...
Process the deleted changes first, and if there is a update in 'regular-changes', remove the entity from that list, then process the remaining changes (I feel it should make the code cleaner too, but I'll think about it...)

**Comment by Richard87** [comment]
A new problem have come up... Mercure is spammed with updates because a collection is updated. But that collection is not in use in front-end, and is not serialized by API-Platform...

Which solution would be best?

1. Filter the collection updates based on context and groups on the property?
2. Create a new `@mercure` annotation for the collection property, to signal API-Platform to push updates on it
3. Add a `groups` property on the existing `@mercure` annotation to specify which serialization fields should be watched for changes.

I prefer 2, a new `@mercure` annotation for the collection that should be watched, but a `groups` property could also work nicely, and be easy to start using...

**Comment by Richard87** [comment]
After thinking about it, and noticing Mercure already uses the class `normalization_context`, I think using that to check the changes is optimal.

I have the changed fields from doctrine's UnitOfWork, but I have a hard time accessing `Normalizer::getAllowedAttributes` so I can easily check if the properties changed are in the current group...

Does anybody have an idea? 
(in testing I'm just deserializing the document to get the list of interesting properties, and checking it towards the list of changed properties, ignoring the update if it's not interresting)

**Comment by stephanvierkant** [comment]
@soyuka Why did you close this issue?

**Comment by soyuka** [comment]
Because 2.7 is now EOL and this is quite old without any resolutions. Also, there's no reproducer and by the looks of it  I don't know if it's a bug or a feature request. Last but not least, you can always implement your own Mercure publisher to do what you want in your code. If there are concern with this please open a new issue or propose a patch!

**Comment by stephanvierkant** [comment]
Thanks for explaining!
