### ISSUE TITLE
Relation may not be updated

### ISSUE THREAD

**Issue by jderusse** [api-platform/core#321]
Due to a bug in doctrine (see https://github.com/doctrine/doctrine2/pull/1546)

In some conditions (see bellow) entities may not be correctly updated:
- Having a relation `ManyToOne`
- using `fetch="EAGER"` on the relation
- using a constraint like `@UniqueEntity`
- make a PUT request on the entity without changing the unique property, but changing the relation

expect result: relation changed
actual result: relation unchanged

TL;DR
Given The deserializer inject proxies in the relations.
When re-hydrating the same object (made by `UniqueEntity` when searching an entity with the same code)
Then the proxy is replaced by the data retrieved from the query (due to the EAGER relation)

Why opening an issue here:
- to follow the issue
- in case the issue is not fixed on doctrine (or not in previous branches)

Possible fixes:
- Unserialize twice (right after the validation)
- force iris to fetch data in https://github.com/dunglas/DunglasApiBundle/blob/1.0/JsonLd/Serializer/ItemNormalizer.php#L343

**Comment by soyuka** [comment]
I think that you have to use serialization groups on the relation so that it gets updated. 

See: 
https://github.com/dunglas/DunglasApiBundle/issues/153 https://github.com/dunglas/DunglasApiBundle/issues/232

**Comment by jderusse** [comment]
It look likes, it's not related: when I dump the object right after the deserialization, it's well formatted.

**Comment by dunglas** [comment]
A Doctrine fix will definitely be the better solution.

If we need to fix it in API Platform directly we need to find a way to done it without creating a dependency to Doctrine.

**Comment by Simperfit** [comment]
Are we going to fix this in api-platform ?

**Comment by kate-kate** [comment]
@soyuka @dunglas @Simperfit 
Hello guys. IIUC this issue means, that related entity still can not be updated with the parent. This bug seems critical to me, so what you think can be done to fix it? Is it a Doctrine Proxy problem? May I try to help?

**Comment by soyuka** [comment]
@kate-kate we could try to add a failing test case but if this is indeed due to the doctrine issue we need a fix there :/. We now do fetch the data in the `itemNormalizer` as initially suggested by @jderusse

**Comment by soyuka** [comment]
Closing as it should be fixed in doctrine,
