### ISSUE TITLE
Better naming for outputs with DTOs

### ISSUE THREAD

**Issue by MLDMoritz** [api-platform/core#3211]
**Description**  
When using a DTO as an output, the name generated for that Model is not readable, it's a hash. The name should be more readable, eg. filename.

**Example**  

With `"output"=RequestPasswordResetRequestResult::class`

Current version generates names like this: `RequestPasswordResetRequest:7f546cb601bbd9e0eb1a7cfa305ea7fb`

output should be
`RequestPasswordResetRequest:RequestPasswordResetRequestResult`
or
`RequestPasswordResetRequestResult`

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/pull/2487
