### ISSUE TITLE
DTO's for delete request

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#3212]
**Description**  

Would be nice to have out of the box support in apip for this. In case I'm working with user data related operations, I want to force user to enter their password for confirming the operation and the 
dto could be reused for many operations where only the user password is asked and validated.
Or at least to have a way configure/expose/allow the operation request body.

My current solution is to deserialize into dto the request body on PRE_WRITE, but then I need to update swagger manually.

**Example**  

```
final class UserPasswordConfirmInput
{
    public $password;
}

/**
 * @ApiResource(
 *     itemOperations={
 *         "delete"={
 *             "method"="DELETE",
 *             "input"=UserPasswordConfirmInput::class
 *         }
 *     }
 * )
 */
class UserEmail
{
  // ...
}
```

**Comment by teohhanhui** [comment]
> 
>    A payload within a DELETE request message has no defined semantics;
>    sending a payload body on a DELETE request might cause some existing
>    implementations to reject the request.
>
> https://tools.ietf.org/html/rfc7231#section-4.3.5

Really not sure this is a good idea at all....

**Comment by norkunas** [comment]
But it doesn't say that the payload must be empty :)

**Comment by teohhanhui** [comment]
> But it doesn't say that the payload must be empty

Indeed it doesn't, but since it's undefined semantics I don't think this should be supported for the general case.

**Comment by teohhanhui** [comment]
> I want to force user to enter their password for confirming the operation

This is a UI level concern. What should happen at the REST API level is that you need to re-authenticate the user, if I understand correctly. So nothing needs to change in your `DELETE` operation.

**Comment by norkunas** [comment]
UI won't help in that case if JWT is compromised.

**Comment by teohhanhui** [comment]
Hence the need to require re-authentication. In any case, the authentication layer should not leak into your DELETE operation. Taking the user's password is clearly a breach of this separation.

**Comment by norkunas** [comment]
Reauthentication for what? If you have JWT you already can authenticate yourself and no way to invalidate it

**Comment by teohhanhui** [comment]
Yes, indeed, with JWT this doesn't seem easy to achieve, but the fact is that this remains a concern of the authentication layer. Hope this helps.
