### ISSUE TITLE
ApiPlatform name_converter setting sets serializer behaviour globally and breaks Symfony Messenger

### ISSUE THREAD

**Issue by mrmaad** [api-platform/core#3213]
**API Platform version(s) affected**: 2.5.0

**Description**  
Setting name_converter in `api_platform.yaml` file to `serializer.name_converter.camel_case_to_snake_case` breaks Symfony Messenger default consuming method. Further investigations shows that AbstractNormalizer tries to create BusNameStamp by looking for `busName` field, but this is already converted to `bus_name`. That results in an error:

> In AbstractNormalizer.php line 504:
>                                                                                                                                                                         
>   Cannot create an instance of Symfony\Component\Messenger\Stamp\BusNameStamp from serialized data because its constructor requires parameter "busName" to be present. 

Checking the message headers in Rabbit shows correct, camelCase named fields.

**How to reproduce**  
Set the name converter to the setting shown above, dispatch some message to any bus (in that case it was Rabbit), and try to consume it.

**Comment by soyuka** [comment]
Isn't this an issue related to how you declare messenger? Could you dump your configuration?
