### ISSUE TITLE
Partial openapi overrides impossible

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#3238]
**API Platform version(s) affected**: 2.5

Running `bin/console api:openapi:export -y` i see the generated data for e.g. `requestBody` of our custom endpoint:

```
/path
  operation:
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Entity:7c91f5079b2df8cb68fe8eddd7adf087-Group'
        description: 'The updated Entity resource'
```

i want to modify the description, so i did:

```
Entity:
    itemOperations:
        operation:
            openapi_context:
                requestBody:
                    description: CUSTOM
```

re-running the export i see:

```
/path
  operation:
      requestBody:
        description: CUSTOM
```

we lose the content info, leaving the GUI mysteriously broken :( i cannot duplicate the existing config.

**Comment by ro0NL** [comment]
same for custom responses when using:

```yaml
Entity:
    itemOperations:
        delete:
            openapi_context:
                responses:
                    409:
                        description: boo
```

it overrides the current 204/404 responses

**Comment by ro0NL** [comment]
same for parameters :(

**Comment by felipyamorim** [comment]
@soyuka Is this expected behavior? I'm wanting to modify just the description of a custom operation and the same thing happened here.

@ro0NL How did you get around this issue?
