### ISSUE TITLE
Custom exception not working anymore

### ISSUE THREAD

**Issue by bz4r** [api-platform/core#3239]
**API Platform version(s) affected**: 2.x

**Description**  
If i throw a custom api platform exception
throw new CustomException('Custom');
it should return 400.
But it returns a symfony error 500.

```
api_platform:
    exception_to_status:
        App\Exception\CustomException: 400
```

```
    /**
     * @Route(name="api_article_pdf", path="/article/{id}/pdf", methods="GET")
     * @param $id
     * @return \Symfony\Component\HttpFoundation\JsonResponse|StreamedResponse|null
     * @throws CustomException
     */
    public function test($id)
    {
...
        throw new CustomException('test');
...
        return $response;
    }
```

**How to reproduce**  
https://api-platform.com/docs/core/errors/

**Comment by teohhanhui** [comment]
Please use the #api-platform channel on Symfony Slack for support questions. Thanks!

**Comment by jkabat** [comment]
@bz4r was it resolved somehow? Im getting this issue as well.

**Comment by teohhanhui** [comment]
@jkabat

> Please use the #api-platform channel on Symfony Slack for support questions. Thanks!

**Comment by teohhanhui** [comment]
@jkabat Following up on your messages on Slack...

Can you confirm that this only happens with Symfony 4.4+?

**Comment by mehdibo** [comment]
I have the same issue, I mistakenly opened it in the other repository:
https://github.com/api-platform/api-platform/issues/1864

**Comment by mehdibo** [comment]
After some digging, I found that api-platform only handles the exception if it's a route managed by the framework, in my case I was throwing the exception from a custom controller.

@bz4r are you doing the same?

**Comment by guilliamxavier** [comment]
> After some digging, I found that api-platform only handles the exception if it's a route managed by the framework, in my case I was throwing the exception from a custom controller.

Indeed: https://github.com/api-platform/core/blob/1ba77218dfe61ca9e6cff1bbb3e9a4a6658d4538/src/EventListener/ExceptionListener.php#L43-L49

So, try adding either a `$request->attributes->set('_api_respond', true);` at the beginning of your method (after injecting the Request), or a `defaults={"_api_respond": true}` in your `@Route` annotation (or `defaults: ['api_respond' => true]` in your `#[Route]` attribute)

**Comment by vincentchalamon** [comment]
Closing as [an issue](https://github.com/api-platform/docs/issues/1330) have been opened on the api-platform/core project, and [a PR](https://github.com/api-platform/docs/pull/1344) is in progress.
