### ISSUE TITLE
Float value contain additional decimal places

### ISSUE THREAD

**Issue by hasidiluk** [api-platform/core#3249]
**API Platform version(s) affected**: 1.2

**Description**  
When I return a `float` value for `get` request its return value with additional decimal values.
Here is my set method. 
```
    /**
     * @param float|null $discountedBasePrice
     *
     * @return Price
     */
    public function setDiscountedBasePrice(?float $discountedBasePrice): Price
    {
        $this->discountedBasePrice = 23234.10;

        return $this;
    }
```
But in the response its return as follow.How should I resolve this. I need to get value as ` 23234.10`

```
{
    "@context": "/wcapi/contexts/Departure",
    "@id": "/wcapi/departures",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/wcapi/departures/2023897",
            "@type": "Departure",
            "id": 2023897,
            "prices": {
                "single": {
                    "USD": [
                        {
                            "basePrice": 7220,
                            "totalPrice": 7350,
                            "discountedBasePrice": 23234.099999999999,
                        }
                    ],
```

**Comment by soyuka** [comment]
what is the doctrine type used?

**Comment by hasidiluk** [comment]
> what is the doctrine type used?

I'm not using `doctrine` here, I used `Drupal Bootstrap` as service for database calls inside my project. Because I build a API for drupal project.

**Comment by soyuka** [comment]
Mhh okay because with doctrine for example, the `numeric` type is using a `string` in JSON because of rounding that may cause issues. Maybe that you should use a string to store the number? @teohhanhui do you have an idea to fix this behavior?
