### ISSUE TITLE
All functions in Hydra DocumentationNormalizer are private, can not decorate easily

### ISSUE THREAD

**Issue by gomcodoctor** [api-platform/core#3264]
I want to decorate Hydra DocumentationNormalizer to create user permission based documentation, so tried to decorate it, but all functions are private, so I will need to copy all functions to my decorator class, can we make these functions public and prevent copying of functions

**Comment by soyuka** [comment]
Why do you need access to these private methods? Feel free to open a pull request to fix https://github.com/api-platform/core/issues/2719, I think it'd require to change the DocumentationNormalizer directly. Maybe we can externalize some of the methods but I'm not sure it's necessary. Anyway, let's keep the discussion in #2719 ?

**Comment by teohhanhui** [comment]
The methods are private by design. Being private it means we're free to change them, and not be bound by BC promises for these.
