### ISSUE TITLE
FilterEagerLoadingExtension should check if a toMany join exists

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#3267]
From: https://github.com/api-platform/core/issues/1457#issuecomment-549863843

I've the same issue with a "many to one" relation.
in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php#L65 we check only if the query have a join relation. Will we probably should check if we have a join to many relation. Like we do in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L337

**Comment by xepozz** [comment]
@soyuka can we just remove this condition?
SQL-query is very hard and too long with it.

**Comment by wuchen90** [comment]
If I understood the purpose of `FilterEagerLoadingExtension`, the following kind of code can resolve the not optimal query issue (https://github.com/api-platform/core/issues/1457):

```
// FilterEagerLoadingExtension.php

    public function applyToCollection(...)
    {
// ...
        $originAlias = $queryBuilder->getRootAliases()[0];
        $apply = false;

        foreach ($wherePart->getParts() as $part) {
            if (0 !== \strpos($part, $originAlias . '.')) {
                $apply = true;
                break;
            }
        }

        if (!$apply) {
            return;
        }
// ...
```

We need subqueries only if the filters apply to sub resources no?

**Comment by soyuka** [comment]
> We need subqueries only if the filters apply to sub resources no?
Yes

**Comment by yoannpeyrard** [comment]
Hello everyone.

> > We need subqueries only if the filters apply to sub resources no?
> > Yes

If I well understand the purpose of this nested query (as described in #944), this behaviour is needed and relevant only if there is a filter on toMany relations. 

But it is not needed if there is only filters on toOne relations : there is no risk of data loss when serializing the resource and its relations. Thus, this nested query become a performance issue for large data sets.

So, it is possible to detect if a filter on a toMany relation is involved in the query an therefore using the nested query only for this case ?

**Comment by soyuka** [comment]
let me close that we'll see if it's really needed
