### ISSUE TITLE
Allow status code in _api_respond

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#3269]
We have a POST endpoint that needs to vary between 201 and 202. Currenty i set a custom request attribute + event subscriber just for this, as i want to keep returning api resources from my controller.

What about leveraging the core `_api_respond` for this? So i could do `$request->attributes->set('_api_respond', 202)` and be done :)

**Comment by dunglas** [comment]
Good idea! 👍 on my side

**Comment by teohhanhui** [comment]
I'd suggest using a new attribute name, e.g. `_api_response_status_code`
