### ISSUE TITLE
Nested filtering uses subquery instead of using join 

### ISSUE THREAD

**Issue by stephanvierkant** [api-platform/core#3271]
**API Platform version(s) affected**: 1.2.1 (with Symfony 4.3)

**Description**  
I'm trying to use nested filtering on some entities. Because it was very slow, I started to dig into the actual queries and I discovered that sometimes it uses a subquery instead of using the existing joins. My business logic is way more complex, but let's assume we've got a Forum -> Topic -> Message relationship. This is what `api/messages.json?topic.forum.code=support&page=1` uses:

```
SELECT c0_.id, (...)
FROM Message c0_
         INNER JOIN Topic c1_ ON c0_.topic_id = c1_.id
         INNER JOIN Forum o2_ ON c1_.forum_id = o2_.id
WHERE c0_.id IN (SELECT c10_.id
                 FROM Message c10_
                          INNER JOIN Topic c11_ ON c10_.topic_id = c11_.id
                          INNER JOIN Forum o12_ ON c11_.forum_id = o12_.id
                 WHERE  o12_.code = ?)
ORDER BY c0_.id ASC
LIMIT 10
```

(as you can see I removed some joins and renamed my business logic to more generic table names for the sake of simplicity)

The expected result is
```
SELECT c0_.id, (...)
FROM Message c0_
         INNER JOIN Topic c1_ ON c0_.topic_id = c1_.id
         INNER JOIN Forum o2_ ON c1_.forum_id = o2_.id
WHERE o2_.code = ?
ORDER BY c0_.id ASC
LIMIT 10
```

I don't understand why this subquery is created. On some other entities nested filtering works fine, but on these entities it creates this subquery. I can't figure out the difference between those cases.

Any idea why this subquery is created?

**Comment by teohhanhui** [comment]
It's how Doctrine Paginator works: https://www.doctrine-project.org/projects/doctrine-orm/en/current/tutorials/pagination.html

And it does so for a good reason.

**Comment by stephanvierkant** [comment]
I've tried nested filtering on some other entities and it's not using subquery for those entities. Any idea what 'complex fetch-join scenarios' are?

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/blob/v2.5.2/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L317
