### ISSUE TITLE
API Platform 2.4 is not compatible with Symfony 3.4 LTS without flex

### ISSUE THREAD

**Issue by benjaminrau** [api-platform/core#3296]
**API Platform version(s) affected**: 2.4

**Description**  
Api Platform 2.4 is not compatible with symfony/symfony 3.4 LTS (without flex). api-platform/core 2.4 requires symfony/web-link in ^4.1 and  symfony/serializer in ^4.2.6 while symfony/symfony 3.4 replaces symfony/web-link and symfony/serializer at "self.version".

This results in the replace doesnt match with web-link and serializer and tries to install symfony/symfony together with both symfony/web-link and symfony/serializer while they conflict with each other.

**How to reproduce**  

1. composer require symfony/symfony ^3.4
2. composer require api-platform/core ^2.4

**Possible Solution**  

- Require symfony/web-link as ^3.4 instead of ^4.1.
- Require symfony/serializer as ^3.4 instead of ^4.2.6.

I am not very knowledged with composer but it feels it should be required like ^3.4 || ^4.
I didnt manage to do so. Got errors about invalid version string.

**Additional Context**  
```
Problem 1
    - Conclusion: remove symfony/symfony v3.4.36
    - Conclusion: don't install symfony/symfony v3.4.36
    - api-platform/core v2.4.0 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1].
```

```
Problem 1
    - Conclusion: remove symfony/symfony v3.4.36
    - Conclusion: don't install symfony/symfony v3.4.36
    - api-platform/core v2.4.0 requires symfony/serializer ^4.2.6 -> satisfiable by symfony/serializer[v4.2.10, v4.2.11, v4.2.12, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1].
```

Also described here: https://github.com/api-platform/api-platform/issues/885
Put i here because its an api-platform/core issue, not one of api-platform/api-platform.

**Comment by benjaminrau** [comment]
**At first: Thanks to @teohhanhui and others for their help on this issue in Slack! I really appreciate it! I was completed lost.**

What i personally didnt understand before is that symfony/symfony is/was just a collection of symfony packages (all at the same version). According to teohhanhui meanwhile its no longer recommended to require these packages indirectly by symfony/symfony but rather direct (via projects root composer.json) - if not using flex. Furthermore its possible to require these packages in different versions.

So indeed all of this was stated by teohhanhui before - but i didnt understand.

Taken this literally using api-platform/core 2.4 together with Symfony 3.4 means to REMOVE symfony/symfony and to ADD all these packages below on composer.json as below:
```
        "ext-xml": "*",
        "doctrine/common": "~2.4",
        "fig/link-util": "^1.0",
        "twig/twig": "^1.41|^2.10",
        "psr/cache": "~1.0",
        "psr/container": "^1.0",
        "psr/link": "^1.0",
        "psr/log": "~1.0",
        "psr/simple-cache": "^1.0",
        "symfony/polyfill-apcu": "~1.1",
        "symfony/polyfill-ctype": "~1.8",
        "symfony/polyfill-intl-icu": "~1.0",
        "symfony/polyfill-mbstring": "~1.0",
        "symfony/polyfill-php56": "~1.0",
        "symfony/polyfill-php70": "~1.6",
        "symfony/asset": "~3.4.0",
        "symfony/browser-kit": "~3.4.0",
        "symfony/cache": "~3.4.0",
        "symfony/class-loader": "~3.4.0",
        "symfony/config": "~3.4.0",
        "symfony/console": "~3.4.0",
        "symfony/css-selector": "~3.4.0",
        "symfony/dependency-injection": "~3.4.0",
        "symfony/debug": "~3.4.0",
        "symfony/debug-bundle": "~3.4.0",
        "symfony/doctrine-bridge": "~3.4.0",
        "symfony/dom-crawler": "~3.4.0",
        "symfony/dotenv": "~3.4.0",
        "symfony/event-dispatcher": "~3.4.0",
        "symfony/expression-language": "~3.4.0",
        "symfony/filesystem": "~3.4.0",
        "symfony/finder": "~3.4.0",
        "symfony/form": "~3.4.0",
        "symfony/framework-bundle": "~3.4.0",
        "symfony/http-foundation": "~3.4.0",
        "symfony/http-kernel": "~3.4.0",
        "symfony/inflector": "~3.4.0",
        "symfony/intl": "~3.4.0",
        "symfony/ldap": "~3.4.0",
        "symfony/lock": "~3.4.0",
        "symfony/monolog-bridge": "~3.4.0",
        "symfony/monolog-bundle": "^3.4.0",
        "symfony/options-resolver": "~3.4.0",
        "symfony/process": "~3.4.0",
        "symfony/property-access": "~3.4.0",
        "symfony/proxy-manager-bridge": "~3.4.0",
        "symfony/routing": "~3.4.0",
        "symfony/security": "~3.4.0",
        "symfony/security-core": "~3.4.0",
        "symfony/security-csrf": "~3.4.0",
        "symfony/security-guard": "~3.4.0",
        "symfony/security-http": "~3.4.0",
        "symfony/security-bundle": "~3.4.0",
        "symfony/serializer": "^4.2.6",
        "symfony/stopwatch": "~3.4.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/templating": "~3.4.0",
        "symfony/translation": "~3.4.0",
        "symfony/twig-bridge": "~3.4.0",
        "symfony/twig-bundle": "~3.4.0",
        "symfony/validator": "~3.4.0",
        "symfony/var-dumper": "~3.4.0",
        "symfony/web-link": "^4.1",
        "symfony/web-profiler-bundle": "~3.4.0",
        "symfony/web-server-bundle": "~3.4.0",
        "symfony/workflow": "~3.4.0",
        "symfony/yaml": "~3.4.0",
```

Please notice that symfony/serializer and symfony/web-link are required with different version than 3.4 - which is the important part that caused conflicts when requiring them indirectly via symfony/symfony which would require them as "self.version".

This may be helpful for others as lost as i was.

**Comment by Muspi** [comment]
Hi, I have same problem, trying to install apiplatform-core 2.5 on my 3.4 symfony distribution.
I tried your solution to remove symfony/symfony in my composer an put packages list instead.

But did-you made other modifications to make it work?
As an example, my post install scripts does not longer exists:
` "scripts": {
        "symfony-scripts": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },`

Any idea?
