### ISSUE TITLE
OpenAPI Component Schema name are not valid

### ISSUE THREAD

**Issue by kayneth** [api-platform/core#3313]
**API Platform version(s) affected**: 2.*

**Description**  
Based on official OpenApi schema: https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json#L196
[Jane](https://github.com/janephp/janephp) only generate Models & Normalizers based on this specification.

This specification have a regex for each components schame as `^[a-zA-Z0-9\\.\\-_]+$`.

Every name generated with `ApiPlatform\Core\JsonSchema\SchemaFactory::buildDefinitionName` are not compatible with the specification if we use Input/Output or when there is the format added.

The explanation was originally posted in https://github.com/janephp/janephp/issues/209#issuecomment-567040243_

**How to reproduce**  

Take a simple resource configuration:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources xmlns="https://api-platform.com/schema/metadata"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://api-platform.com/schema/metadata
           https://api-platform.com/schema/metadata/metadata-2.0.xsd">
    <resource class="App\Book\Entity\Book" iri="http://schema.org/Book">
        <attribute name="input">App\Book\Api\BookInput</attribute>
        <attribute name="output">App\Book\Api\BookOutput</attribute>
        <attribute name="normalization_context">
            <attribute name="swagger_definition_name">book-write</attribute>
        </attribute>
    </resource>
</resources>
```

Where each class may have whatever you want for properties, etc.

**Possible Solution**  
To follow specification, we may replace `:` by any valid character `._-`.
But does it break anything on API-Platform side?

**Comment by soyuka** [comment]
Once https://github.com/api-platform/core/pull/3309 gets merged we should try to fix this. I don't think it'd break anything but one's have to try :).

**Comment by kayneth** [comment]
Ok, thank you for your quick answer. 😄 
I especially wanted to know if you had any counter-indications to make such a change because it hadn't already been done.

**Comment by teohhanhui** [comment]
> I especially wanted to know if you had any counter-indications to make such a change because it hadn't already been done.

I think it's just an oversight on our part.
