### ISSUE TITLE
[performance] Add local cache on ResourceClassResolver::getResourceClass()

### ISSUE THREAD

**Issue by bastnic** [api-platform/core#3316]
**API Platform version(s) affected**: 4.5.* 

**Description**  
Follow up of this closed ticket: https://github.com/api-platform/core/issues/1068, I find a way to optimize a lot `ResourceClassResolver::getResourceClass()`.

**How to reproduce**  
Just go to a normal apip route. My case is violent because I've a lot of api resources and the response returns a lot of entities.

But there is room for improvment!

**Possible Solution**  
`ResourceClassResolver::getResourceClass()` is responsible of no less than 13% in prod mode, because foreach entity, it will go through ALL possible resource, without any break in the loop (seems logic) nor any cache. And so, `is_a` is called 63630 times.

Just adding a local cache clear everything:

```php
        if (isset($this->localMostSpecificResourceClassCache[$targetClass])) {
            return $this->localMostSpecificResourceClassCache[$targetClass];
        }

        foreach ($this->resourceNameCollectionFactory->create() as $resourceClassName) {
            if (!is_a($targetClass, $resourceClassName, true)) {
                continue;
            }

            if (null === $mostSpecificResourceClass || is_subclass_of($resourceClassName, $mostSpecificResourceClass)) {
                $mostSpecificResourceClass = $resourceClassName;
            }
        }

        if (null === $mostSpecificResourceClass) {
            throw new \LogicException('Unexpected execution flow.');
        }

        $this->localMostSpecificResourceClassCache[$targetClass] = $mostSpecificResourceClass;
```

Before : 

![image](https://user-images.githubusercontent.com/84887/71133557-2b964e00-21fb-11ea-96e6-d06d50327fee.png)

Diff :

![image](https://user-images.githubusercontent.com/84887/71133590-3ea91e00-21fb-11ea-88da-979a4429f5c5.png)

**Comment by bastnic** [comment]
If someones asks for the apcu_fetch, I created an issue for that: https://github.com/symfony/symfony/issues/35041

**Comment by dunglas** [comment]
LGTM!
