### ISSUE TITLE
EventPriorities::POST_RESPOND seems useless

### ISSUE THREAD

**Issue by alexsegura** [api-platform/core#3323]
Hi,

I was willing to add some custom response header, so I thought the most logical priority was `POST_RESPOND`.

At first, I used `KernelEvents::VIEW` (as indicated in the docs) as the hooking point, but it didn't work, my event subscriber was not called. 

```php
public static function getSubscribedEvents()
{
    return [
        KernelEvents::VIEW => [
            ['addMyCustomHeader', EventPriorities::POST_RESPOND],
        ],
    ];
}
```

It is because `RespondListener` calls `setResponse`, and stops propagation (see #879).

What works is this:

```php
public static function getSubscribedEvents()
{
    return [
        KernelEvents::RESPONSE => [
            ['addMyCustomHeader', EventPriorities::POST_RESPOND],
        ],
    ];
}
```

But it's actually the same as:

```php
public static function getSubscribedEvents()
{
    return [
        KernelEvents::RESPONSE => 'addMyCustomHeader',
    ];
}
```

Because `POST_RESPOND` value is `0`, which is the default.

---

From what I understand, the only use case where `POST_RESPOND` can be reached, is when a `Response` was set before, or when `respond` attribute is `false` (but then, why would one use `POST_RESPOND`?)

https://github.com/api-platform/core/blob/a12ac48a10aeb4f0888346ae462a5f7072a677e2/src/EventListener/RespondListener.php#L55-L57

I confess I don't really understand what this statement is used for? 
Is it to skip handling controller responses from "normal" controllers?

---

I was about to make a PR on the docs, but it seems to me there is no real point in keeping `POST_RESPOND`: if people want to modify the response, they just hook on `KernelEvents::RESPONSE`, period. 

Past `KernelEvents::VIEW`, API Platform doesn't do much, except to add cache headers & Hydra links.

**Comment by teohhanhui** [comment]
The `EventPriorities` constants are there for convenience / avoiding the need to hard-code the priority value in most cases. The fact that `POST_RESPOND` is `0` (the same as the default) is a coincidence / implementation detail.
