### ISSUE TITLE
[performance] cost of AbstractItemNormalizer::getAllowedAttributes()

### ISSUE THREAD

**Issue by bastnic** [api-platform/core#3325]
**API Platform version(s) affected**: 2.5.3

**Description**  
In prod environment, `AbstractItemNormalizer::getAllowedAttributes()` represents almost 8% of the total requests. Just for grabing list of properties that can be accessible. It seems way too much for what it doses. 

![image](https://user-images.githubusercontent.com/84887/71327669-8685b900-250b-11ea-8ebf-0e788799b56a.png)

The current implementation seems to be:

```
function getAllowedAttributes($classOrObject, array $context, ...) {
    grab serialization properties of this object classes (or class directrly) // this is cached, but still calld 193 times for like 10 differents entity type

	foreach properties
		grab metadata for this property  // this is cached, but still called 2170 times
	
		exclude incorrect serialization properties (property does not exists / not readable / writable)
	
	return curated list of properties
}
```

There is cache at each sublevel of this function, but it's not enough. Just the `serialize()` calls for each of the 193 + 2170 calls represents multiples ms.

Ok the context is given as parameter everywhere, so it must impacts something.

I'm trying to understand the impact of:
- caching the whole getAllowedAttributes by resource class
- can I warm so it's never done by the user

And further questioning:
- the exclusion list seems to be errors in the serialization properties, maybe warm for them (for me it was only forgotten removed properties, and it troubles me that preventing it cost 7% of the total). Maybe signal that errors in dev mode so it can be cleaned. The DI fails if there is properties that does not exists, we can add that type of check at runtime in dev? Or just a log that list errors

**Comment by bastnic** [comment]
And a new note in favor of adding an error (maybe more on symfony side btw), I just discover some fields "isDefaultStuff", where the methods are `setIsDefaultStuff(bool $stuff): void` and `isDefaultStuff(): bool`. I always thought they worked. But nope because this stack remove it (even if they works!)

**Comment by teohhanhui** [comment]
> I just discover some fields "isDefaultStuff", where the methods are setIsDefaultStuff(bool $stuff): void and isDefaultStuff(): bool. I always thought they worked. But nope because this stack remove it (even if they works!)

If that's a bug, can you open a new issue / PR (targeting `2.5`) for that? :smile:

**Comment by bastnic** [comment]
> If that's a bug, can you open a new issue / PR (targeting `2.5`) for that? smile

I'm only on the performance side for now. Have not checked yet if APIP or Symfony. Will do. 

And not sure if it's a bug or not ;). We just don't like calling isser `getIsDefaultStuf()`

**Comment by teohhanhui** [comment]
I'm referring to this part:

> even if they work

So, if it's something that works with Symfony, but is removed by API Platform, I guess that's a bug.

**Comment by bastnic** [comment]
Yeah I figured, but I'm not sure it works on Symfony.

**Comment by bastnic** [comment]
Feature request added in Symfony for the allowedAttributes part.

**Comment by bastnic** [comment]
Pull request in Symfony: https://github.com/symfony/symfony/pull/35183.
