### ISSUE TITLE
[performance] Serialization yaml files are parsed on each requests

### ISSUE THREAD

**Issue by bastnic** [api-platform/core#3326]
**API Platform version(s) affected**: 2.5.3

**Description**  
Not sure why yet but in dev, I see that all serialization yaml files are parsed at each request. No other yaml file are loaded.

![image](https://user-images.githubusercontent.com/84887/71366753-4245f780-25a3-11ea-8fd6-dad497642257.png)

No problem in production because `ClassMetadataFactory` is decorated by `CacheClassMetadataFactory`.

Stacktrace:

```
#0 /var/www/project/apps/api/vendor/symfony/serializer/Mapping/Loader/YamlFileLoader.php(141): Symfony\Component\Yaml\Parser->parseFile('/var/www/projec...', 256)
#1 /var/www/project/apps/api/vendor/symfony/serializer/Mapping/Loader/YamlFileLoader.php(43): Symfony\Component\Serializer\Mapping\Loader\YamlFileLoader->getClassesFromYaml()
#2 /var/www/project/apps/api/vendor/symfony/serializer/Mapping/Loader/LoaderChain.php(58): Symfony\Component\Serializer\Mapping\Loader\YamlFileLoader->loadClassMetadata(Object(Symfony\Component\Serializer\Mapping\ClassMetadata))
#3 /var/www/project/apps/api/vendor/symfony/serializer/Mapping/Factory/ClassMetadataFactory.php(50): Symfony\Component\Serializer\Mapping\Loader\LoaderChain->loadClassMetadata(Object(Symfony\Component\Serializer\Mapping\ClassMetadata))
#4 /var/www/project/apps/api/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(166): Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory->getMetadataFor('Lib\\Core\\Entity...')
#5 /var/www/project/apps/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php(151): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(Object(Lib\Core\Entity\Site), 'json', Array)
```

**How to reproduce**  
yaml serialization files, and a bsic apip route in dev env.

**Possible Solution**  
none yet, still searching.

Not sure yet if it's an APIP or Symfony bug.

**Comment by teohhanhui** [comment]
We don't load the Serializer YAML files directly, so it must be Symfony...

**Comment by bastnic** [comment]
Confirmed that this is a Symfony bug ("feature request") by reproducing it in a project without apip. Good news as it will fix a bigger number of project, but heavier to fix / release.

**Comment by bastnic** [comment]
Follow up in here: https://github.com/symfony/symfony/issues/35096
