### ISSUE TITLE
[Elasticsearch] Unable to get aggregation results

### ISSUE THREAD

**Issue by Cocray** [api-platform/core#3334]
**API Platform version(s) affected**: 2.5.3

**Description**  
Hello APIP team.

It seems impossible to retrieve "aggregation" results returned by ES because only "hits" are managed in the code. It should be great having access to this huge part provided by ES.

Thanks

**Comment by signor-pedro** [comment]
Hi, is there any update on this? Do all the people using elasticsearch in API Platform just not use aggregations? 🤔

**Comment by pimjansen** [comment]
> Hi, is there any update on this? Do all the people using elasticsearch in API Platform just not use aggregations? 🤔 

Create your own provider. Aggregations are really impacted by the way you structures your ES data
