### ISSUE TITLE
PATCH Method does not have default supported format ?

### ISSUE THREAD

**Issue by KaporalK** [api-platform/core#3335]
**API Platform version(s) affected**: 2.5.0^

**Description**  
When updating my project to api-platform 2.5.0, my custom route using PATCH HTTP method broke, with the following error message `The content-type "application/json" is not supported. Supported MIME types are "\".`

I fixed the route with the following annotation:
 ```
 *              "input_formats"={"json"={"application/ld+json", "application/json" }},
 *              "output_formats"={"json"={"application/ld+json", "application/json"}}
```

My route definition 
```
 *          "test"={
 *              "method"="PATCH",
 *              "path"="/users/{id}/name",
 *              "controller"=PatchNameController::class ,
 *              "input_formats"={"json"={"application/ld+json", "application/json" }},
 *              "output_formats"={"json"={"application/ld+json", "application/json"}}
 *          },
```

And i'm using the recommended method to register custom controller

**Comment by soyuka** [comment]
Indeed, please configure this globally following these instructions: https://api-platform.com/docs/core/content-negotiation/#configuring-patch-formats

**Comment by KaporalK** [comment]
Oh ok thanks

Woudn't it be nice to have a "What's new" on your doc to see what have you updated on the documentation for the X.x version ?

It's becoming harder to follow your update without re-reading every line of your doc or making a (kinda useless) git issue

A page with every new doc for the version X.x could prevent that :)

**Comment by soyuka** [comment]
It's supposed to be in the [changelog](https://github.com/api-platform/core/blob/master/CHANGELOG.md) if it isn't we missed it! 

NB to contributors: To close this issue we need to mention this in the changelog
