### ISSUE TITLE
Access Control: security attribute object not populated on POST for is_granted

### ISSUE THREAD

**Issue by timgregg** [api-platform/core#3336]
**API Platform version(s) affected**: 2.5.3

**Description**  

Using the "access_control" attribute for POST requests. In the below example "object" is set as the current entity and is available to security voters as the subject.

` collectionOperations={
    "post"={"method"="POST", "access_control"="is_granted('ACCOUNT_ADMIN', object)"}
}`

Using the "security" attribute the "object" and "subject" on security voters are null.

`collectionOperations={
    "post"={"method"="POST", "security"="is_granted('ACCOUNT_ADMIN', object)"}
}`

**Comment by desmax** [comment]
Can confirm, also had some bug with when moving to `security` field, had to revert back to `access_control `.

**Comment by desmax** [comment]
@timgregg apparently you have to use `security_post_denormalize` instead. See https://api-platform.com/docs/core/security/#executing-access-control-rules-after-denormalization

I would say deprecation message for using access_control should also mention `security_post_denormalize`, not only `security`.

**Comment by winzza** [comment]
Hmmm... strange... When i use similar entry:
```
 *     collectionOperations={
 *        // ..
 *         "post" = {
 *             "security" = "is_granted('CHECK_ACCESS', object)",
 *             // ...
 *         }
 *     }
```
I geting `ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator` object.

Anyway, how said @desmax, use `security_post_denormalize` option.

**Comment by jmontoyaa** [comment]
I have the same issue but using GET. The subject in the Voter is `ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator.
This is also reported here: 

https://stackoverflow.com/questions/59051663/using-symfony-voters-on-collectionoperations-get

No matter if I use `security_post_denormalize` or `security` the subject return is a Paginator.

**Comment by jmontoyaa** [comment]
Maybe I have to do a loop in the voter for the paginator?

```
protected function voteOnAttribute(string $attribute, $subject, TokenInterface $token): bool
{
      /** @var Paginator $resource */
        foreach ($subject as $item) {
            /** @var MyEntity $item */
            echo get_class($item);
            // Filter $item?
        }
}
```

**Comment by jmontoyaa** [comment]
Ok, I see my problem. I have to use extensions to filter the GET

https://api-platform.com/docs/core/extensions/
