### ISSUE TITLE
Favor ItemSerializer composition over inheritance

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#3339]
Each ItemNormalizer, per format, extends from `AbstractItemNormalizer`. Resulting in many services like `api_platform.jsonld.normalizer.item` etc.

We cannot decorate a single item normalizer to mutate the root item data, in a generic fashion.

**Comment by ro0NL** [comment]
Currently i create a custom  normalizer, doing more or less:

```php
public function supportsNormalization($data, $format = null, array $context = [])
{
    return !isset($context[self::class]) && isset($context['resource_class']) && is_object($data) && $data instanceof $context['resource_class'];
}
```

but it feels a bit clumsy vs. decorating the API platform item normalizer :/

**Comment by soyuka** [comment]
We're aware of this :) please help us continue https://github.com/api-platform/core/pull/2579 !

**Comment by ro0NL** [comment]
I see :) cool. Closing in favor of #2355, my bad.
