### ISSUE TITLE
Item normalize relation return id instead of iri on json

### ISSUE THREAD

**Issue by cacahouwete** [api-platform/core#3340]
**Description**  
When  `accept: application/json` why we can't have simple id ? Iri should be used only on application/ld+json ?

In AbstractItemNormalizer::normalizeRelation we could return identifier(s) instead of iri on `'json' === $format` ?

**Example**  
JSON (now)
```json
[
  {
    "id": "Pair-1",
    "driver": "/api/drivers/Driver-1",
    "vehicle": "/api/vehicles/Vehicle-1"
  },
 ...
]
```
JSON (proposition)
```json
[
  {
    "id": "Pair-1",
    "driver": "Driver-1",
    "vehicle": "Vehicle-1"
  },
 ...
]
```
JSONLD
```json
{
  "@context": "/api/contexts/Pair",
  "@id": "/api/pairs",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/pairs/Pair-1",
      "@type": "Pair",
      "id": "Pair-1",
      "driver": "/api/drivers/Driver-1",
      "vehicle": "/api/vehicles/Vehicle-1"
    },
    ...
  ],
  ...
}
```

**Comment by mariuseliassen** [comment]
In your entity you can just add a helper function to return the id

```
/**
 * @var int|string|whatever-your-id-is
 * @Groups({"your-output-group"})
*/
public function getRelationId() {
     return $this->getRelationField()->getId();
}
```

And then remove the relation itself from normalization context group

**Comment by soyuka** [comment]
Do you have `allow_plain_identifiers` to `true` see https://api-platform.com/docs/core/configuration/

**Comment by cacahouwete** [comment]
Ok ^^, thx

**Comment by soyuka** [comment]
it can't work with JSON-LD, use `application/json` for that or use a normalizer like we documented here: https://api-platform.com/docs/core/serialization/#plain-identifiers
