### ISSUE TITLE
ResourceClassResolver Exclude Traversable

### ISSUE THREAD

**Issue by stood** [api-platform/core#3341]
Hi,

I use api-platform with pomm and I upgrade package : https://github.com/pomm-project/pomm-api-platform/pull/9.

I'm writing a persister but I have a problem. In fact, the function ```getResourceClass``` of ```ResourceClassResolver``` exclude values ```\Traversable```. 

Why?

The pomm object implements this interface.

**Comment by soyuka** [comment]
Good question, probably to exclude ArrayCollection-like objects maybe that we can add an exception for this? In the meantime, just override the ResourceClassResolver in your application and allow the pomm object.
