### ISSUE TITLE
Cursor based pagination throws Warning: Illegal string offset 'direction'

### ISSUE THREAD

**Issue by KableCH** [api-platform/core#3348]
**API Platform version(s) affected**: 2.5.4

**Description**  
Following the docs on how to implement [cursor based pagination](https://api-platform.com/docs/core/pagination/#cursor-based-pagination) throws
`Warning: Illegal string offset 'direction'`

**How to reproduce**  Add the following annotations to an entity:
`
/**
 * @ApiResource(attributes={
 *   "pagination_partial"=true,
 *   "pagination_via_cursor"={"field"="id", "direction"="DESC"}
 * )
 * @ApiFilter(RangeFilter::class, properties={"id"})
 * @ApiFilter(OrderFilter::class, properties={"id"="DESC"})
 */
`

**Possible Solution**  
I think this bug comes from [PartialCollectionViewNormalizer](https://github.com/api-platform/core/blob/e8effc74ec97261545bfca145f837607e1898134/src/Hydra/Serializer/PartialCollectionViewNormalizer.php#L150) (line 155, 160 & 161). Instead of `$field['direction']` and `$field['field']` it should be `$fields['...']`

**Comment by soyuka** [comment]
Hi @KableCH, can you help us improve the cursor-based pagination ? It's experimental for now and we appreciate some new eyes on it!

**Comment by KableCH** [comment]
Hey @soyuka, sure I'd love to help with the code

**Comment by MarcioNido** [comment]
I think the problem is that the "pagination_via_cursor" is expecting an array, so the annotation should be:
`"pagination_via_cursor"={"fields"={"field"="id", "direction"="DESC"}}`
That worked for me.
