### ISSUE TITLE
Fix TypeFactory getClassType

### ISSUE THREAD

**Issue by Raulnet** [api-platform/core#3361]
**API Platform version(s) affected**: x.y.z

**Description**  
in class 'ApiPlatform\Core\JsonSchema\TypeFactory'
the method getClassType could return an error if the argument '$classname' is not a resource and if the argument '$readablelink' is null;

**Comment by teohhanhui** [comment]
Can you give an example?

**Comment by teohhanhui** [comment]
ping @Raulnet

> could return an error

Could you provide more details please?
