### ISSUE TITLE
How to show in the openapi docs when a field it's a relationship, and requires an IRI?

### ISSUE THREAD

**Issue by ghost** [api-platform/core#3363]
The OpenApi docs that are generated for an entity/resource that includes relationships with other entities simply specify `string`for those fields:

![image](https://user-images.githubusercontent.com/60233442/73008980-ebd11080-3e0f-11ea-90c2-4120c1aec973.png)

But the information is misleading, because in this case both `role` and `admin` are actually relationships to other classes and an IRI should be sent. Something like:

```
{
  "role": "/api/roles/1",
  "admin": "/api/admins/245"
}
```

This docs are consumed by other developers to know how to interact with the API, and are usually frustrated because it's not obvious when a field is a relationship (and requires an IRI) and when a regular string should be used.

Is there a way to configure so this is included in the documentation, preferably automatically?

**Comment by yivi** [comment]
This would be a nice thing to have. Not sure how should it present itself, but I have got similar questions from users of our API.
