### ISSUE TITLE
Dynamic Validation Groups not work

### ISSUE THREAD

**Issue by winzza** [api-platform/core#3364]
**API Platform version(s) affected**: 2.5.3

**Description**  
I tried to do everything according to the documentation.
https://api-platform.com/docs/core/validation/#dynamic-validation-groups
`"Alternatively, you can use a service to retrieve the groups to use:"`

I want to make groups based on user roles.For this I need autowiring
`__construct(Security $security)`

**How to reproduce**  
use example from documentation

**Comment by antograssiot** [comment]
Did you declare your service as public ?
> Just note that this service must be public

**Comment by norkunas** [comment]
There is a PR to improve this #3346 :)

**Comment by winzza** [comment]
I apologize for my carelessness.
@antograssiot thank you so mach. After I made this service public.
```
// config/services.yaml

services:
    ...

    'App\Validator\MyServiceGroupsGenerator':
        public: true
```
It's work. Maybe it's worth adding to the documentation? Because for all services, by default, public is set to false...

@norkunas thank for you job. Nice solution.

**Comment by antograssiot** [comment]
that's already in the doc, my quote is from the documentation actually but we might need to improve its visibility
