### ISSUE TITLE
Custom filter should not be loaded before authorization

### ISSUE THREAD

**Issue by winzza** [api-platform/core#3369]
**API Platform version(s) affected**: 2.5.3
**Symfony**: 5

**Description**  
I need my custom filter. To create dynamic filters `required = true`.
My custom filter class:
```
// src/Filter
<?php

declare(strict_types=1);

namespace App\Filter;

use Symfony\Component\Security\Core\Security;
//.. many use;

final class MyCustomFilter extends AbstractContextAwareFilter
{
    /**
     * @var Security
     */
    private $security;

    public function __construct(
        Security $security,
        // other dependency params
    ) {
        parent::__construct($managerRegistry, $requestStack, $logger, $properties, $nameConverter);
        $this->security = $security;

        var_dump($this->security->getUser()); // <-- output null
    }

    public function getDescription(string $resourceClass): array
    {
        var_dump($this->security->getUser()); // <-- output null

        if (!$this->properties) {
            return [];
        }

        $description = [];
        foreach ($this->properties as $property => $strategy) {
            $description["search_${property}"] = [
                'property' => $property,
                'type'     => 'string',
                'required' => $this->security->isGranted('ROLE_USER') ? true : false, // <-- not work
                'swagger'  => [
                    'description' => '//...',
                    'name'        => '//...',
                    'type'        => '//...',
                ],
            ];
        }

        return $description;
    }

    /**
     * Passes a property through the filter.
     *
     * @param mixed $value
     */
    protected function filterProperty(
        string $property,
        $value,
        QueryBuilder $queryBuilder,
        QueryNameGeneratorInterface $queryNameGenerator,
        string $resourceClass,
        string $operationName = null
    ): void {
        // TODO: Implement filterProperty() method.
    }
}

```
In the `getDescription` method i want set the `required` in `true` or `false`. But I do not get the user object because the `getDescription` method worked before authenticating user.
And if I set `var_dump($this->security->getUser()); exit;` in `__construct` or 'getDescription', and press `ctrl+R` in my brouser, instead load my page and display swagger documentation, i get NULL

**How to reproduce**  
Create class from description and add in `@ApiFilter`:
```
 * @ApiFilter(MyCustomFilter::class)
```

**Comment by ksom** [comment]
Same issue in my case. I have to modify the filter description based on user, but the filter is loaded before authorization and I can't perform an isGranted and get my token user.

Anyone have a workaround ?

**Comment by soyuka** [comment]
The way I see it is that your field is not required and you should instead use some kind of validation to sanitize the input. Filters here is not the way to go.

**Comment by winzza** [comment]
I would like the user to get an error if there are not enough filtering arguments and this user is not an administrator. For the simple user, this filter should be required. The admin may not set the filter, it is not necessary for him.

**Comment by ksom** [comment]
In one of my case, for example, it is because I use Elasticsearch aggregations and I have to specify all values possible for the filter (buckets from aggregation). And to do my Elasticsearch query, I had to have my user available because I don't perform the same query based on user.

**Comment by mvanduijker** [comment]
You also get the validation messages when unauthenticated. So you expose a bit of the working of your api to unauthenticated users.
