### ISSUE TITLE
[Proposal] Allow array in messenger attribute

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#3371]
**Description**

Using `messenger=true` attribute on a Doctrine entity disable the persist/remove of the object to respect the CQRS, it must be done asynchronously. In some projects, it's required to save the object synchronously before sending the object.

This cannot be done in an EventSubscriber according to [Extending API Platform](https://api-platform.com/docs/core/extending/) section, and must be done in a custom data persister. This behavior could be automatized in API Platform using a new value in the `messenger` attribute.

Current values are:
* `messenger=true`: dispatching a Resource through the Message Bus
* `messenger=input`: using Messenger with an Input Object

Additional values could be:
* `messenger="persist"`: saving an object and dispatching a Resource through the Message Bus
* `messenger=["persist", "input"]`: saving an Input Object and using Messenger with it

**Example**

```php
<?php

// api/src/Entity/Content.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ApiResource(messenger="persist")
 */
class Content
{
    // ...
}
```

```php
<?php

// api/src/Entity/Content.php

namespace App\Entity;

use App\Dto\ContentRequest;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ApiResource(
 *     collectionOperations={
 *         "post"={"status"=202}
 *     },
 *     itemOperations={},
 *     messenger=["persist", "input"],
 *     input=ContentRequest::class,
 *     output=false
 * )
 */
class Content
{
    // ...
}
```

**Proposal**

In order to handle this new feature, the MessengerDataPersister should be updated to support the additional values: `save` or an array. If the attribute value matches `save` or contains it, then the ChainDataPersister must be called again with a context option to prevent an infinite loop. Otherwise, the MessengerDataPersister works as expected, following the CQRS pattern.
<br><br><br><br><br><br>
Sorry for the long description. Here is an API potato:

![image](https://user-images.githubusercontent.com/407859/73856019-2639a500-4835-11ea-8308-2d9622dc56af.png)

**Comment by alanpoulain** [comment]
Wouldn't it be better for the value to be `persist` then?

**Comment by vincentchalamon** [comment]
Could be better indeed as it's the method name in the DataPersisterInterface. But what about `remove`?

**Comment by dunglas** [comment]
"persist" looks good to me
