### ISSUE TITLE
[GraphQL][Type Definition] Extends no existant ScalarType class

### ISSUE THREAD

**Issue by mpiot** [api-platform/core#3378]
**API Platform version(s) affected**: 2.5.4

**Description**  
When using API Platform on Symfony, and using the command `lint:container`, I've 2 errors:

>  Invalid service "api_platform.graphql.iterable_type": class "ApiPlatform\Core\GraphQl\Type\Definition\ScalarType"
  not found while loading "ApiPlatform\Core\GraphQl\Type\Definition\IterableType".

> Invalid service "api_platform.graphql.upload_type": class "GraphQL\Type\Definition\ScalarType" not found while loa
  ding "ApiPlatform\Core\GraphQl\Type\Definition\UploadType".

Indeed, in these files, `GraphQL\Type\Definition\ScalarType` is extended but do not exists:
 - https://github.com/api-platform/core/blob/master/src/GraphQl/Type/Definition/IterableType.php#L34
 - https://github.com/api-platform/core/blob/master/src/GraphQl/Type/Definition/UploadType.php#L26

**Comment by mpiot** [comment]
Someone hav ean idea ? Because it brokes the PHP preloading too.

**Comment by alanpoulain** [comment]
I don't have these issues on the `2.5` branch.
I don't see any issue with extending `GraphQL\Type\Definition\ScalarType`.
This class comes with the vendor https://github.com/webonyx/graphql-php:
https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/ScalarType.php

**Comment by mpiot** [comment]
In fact I've try to install the `webonyx/graphql-php` then it works well with:
 - symfony console lint:container
 - PHP 7.4 preloading

But I'm not sure that  is expected because this package is not installed by default but is needed.

**Comment by alanpoulain** [comment]
Sorry, even without the vendor, I don't have the issue.
Are you sure you have not enabled GraphQL like this?
```yml
api_platform:
    graphql:
        enabled: true
```
Have you cleared your cache *twice*?

**Comment by mpiot** [comment]
@alanpoulain You're totally right, I've forget a piece of config in api_platform config:

```
api_platform:
    graphql:
        collection:
            pagination:
                enabled: false
```

I remember to rmeove the enabled, apparently keep a part of config.

Thanks a lot :)
