### ISSUE TITLE
Multiple IRI feature ? 

### ISSUE THREAD

**Issue by MLKiiwy** [api-platform/core#338]
In the application I develop, for legacy reason we have two identifier for the same resource, the classic IRI : **/myResource/1** and also it's legacy identifier : **/myResource/legacy/199** 

I already made custom operation to handle the "legacy endpoint" and it works perfectly.
The feature I want to set up it to send legacy IRI in POST/PUT request to simplify some workflow.
For my point of view : 
```json
{
   "@id": "/contact/1",
   "@type": "Contact",
  "relatedResource": "/myResource/1"
} 
```

is the same as : 
```json
{
   "@id": "/contact/1",
   "@type": "Contact",
  "relatedResource": "/myResource/legacy/199"
} 
```

But actually it doesn't work ... the https://github.com/dunglas/DunglasApiBundle/blob/1.0/Api/IriConverter.php#L88 identify my new endpoint but try to 
```php
$this->dataProvider->getItem($resource, $parameters['id'], $fetchData)
```

I think it's a wrong way nothing valid that $parameters['id'] exist ...
Maybe a prefered way is to simulate the GET operation, what do you think ?

**Comment by dunglas** [comment]
the existence of `$parameters['id']` is checked here: https://github.com/dunglas/DunglasApiBundle/blob/1.0/Api/IriConverter.php#L82

What about decorating the `ItemNormalier` to automatically "rewrite" old URLs to new URLs internally?
