### ISSUE TITLE
Update entity on POST_DESERIALIZE, before security_post_denormalize

### ISSUE THREAD

**Issue by pmontoya** [api-platform/core#3380]
**Description**  
I tried to update an entity after deserialization and before `DenyAccessListener::onSecurityPostDenormalize` method call.
As this event listener has a priority of 1, it's execute before my own listener.
Do you think it could be a good idea to change priority to 0?

If yes, I would create a new pull request updating 
`<tag name="kernel.event_listener" event="kernel.request" method="onSecurityPostDenormalize" priority="1" />`
to
`<tag name="kernel.event_listener" event="kernel.request" method="onSecurityPostDenormalize" priority="0" />`
in [src/Bridge/Symfony/Bundle/Resources/config/security.yml](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/security.xml) file.

**Comment by soyuka** [comment]
You can do a compiler pass to change this on your side, I'm afraid we don't like to change priorities as it may break lots of current implementations.

**Comment by pmontoya** [comment]
Ok thanks.
