### ISSUE TITLE
JSON Schemas generated by API Platform should include additionalProperties: false

### ISSUE THREAD

**Issue by quentinus95** [api-platform/core#3382]
**API Platform version(s) affected**: 2.5.1

**Description**  
Today, JSON Schemas generated by API-Platform do not include `additionalProperties: false`. This reduces type saftey when using a code generator.

**How to reproduce**  
Create an ApiResource in a new project, check the generated Swagger documentation. The JSON Schema generated for the ApiResource does not include `additionalProperties: false`.

**Possible Solution**  
Simply add `additionalProperties: false` when generating the schema.

**Comment by teohhanhui** [comment]
Feel free to open a PR targeting `master`. :smile:

**Comment by quentinus95** [comment]
@teohhanhui here you go: https://github.com/api-platform/core/pull/3388

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/3804

**Comment by soyuka** [comment]
Will be out in the next release
