### ISSUE TITLE
How to getClassMetadata() for transient resources (such as DTOs)?

### ISSUE THREAD

**Issue by shehi** [api-platform/core#3387]
This piece of code here:
https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Common/PropertyHelperTrait.php#L168

relies on ```getManagerForClass()``` method from Doctrine Persistence lib, which is here:
https://github.com/doctrine/persistence/blob/1.3.6/lib/Doctrine/Persistence/AbstractManagerRegistry.php#L183

As you can see, when a resource class is transient, we get no manager for it, naturally. And as a result, ```Call to a member function getClassMetadata() on null``` occurs, since we got ```null``` from ```getManagerForClass()``` method. 

Is this a bug? Or how do we handle transient resources like DTOs? I started to get this error the moment I introduced ```ApiFilter()``` annotations to my DTOs.

**Comment by teohhanhui** [comment]
You should not use `@ApiFilter` annotation on your "DTO" (input / output) class. Put the annotation in your resource class.

**Comment by teohhanhui** [comment]
Kindly use the #api-platform channel on Symfony Slack for support questions like these.
