### ISSUE TITLE
Data Transformers for the DTO break the schema

### ISSUE THREAD

**Issue by EmilCataranciuc** [api-platform/core#3392]
**API Platform version(s) affected**: 1.2

**Description**  
When using the input and output attributes on an ApiResource the schema gets broken (the RequestBody for the POST action in the Swagger interface shows {}) and the fields of the object passed to DataTransformerInterface::transform are null. At the same time the fields of the object passed to DataTransformerInterface::supportsTransformation contain the proper values.

**How to reproduce**  
I am not using the Api Platform distribution. It's a regular Symfony install with composer req api-platform/api-pack and admin-pack. I have the following on my resource entity:
@ApiResource( input=ScheduleInput::class, output=ScheduleOutput::class, normalizationContext={"groups"={"schedule"}}, denormalizationContext={"groups"={"schedule"}},)

**Comment by EmilCataranciuc** [comment]
Code investigation revealed no reason for the behavior. Currently I suspect I am doing something wrong but I am not sure what.

**Comment by EmilCataranciuc** [comment]
Debugging revealed that this is no bug. When using serialization groups the annotations should also be added to the data transformers.

**Comment by teohhanhui** [comment]
> When using serialization groups the annotations should also be added to the data transformers.

Hmm... What do you mean?

**Comment by EmilCataranciuc** [comment]
When using serialization group annotations (@Group) the fields in the data transformers (for example BookInput::isbn) which are to be serialized should also have their serialization group annotation added.

Or we could simply add the change to the "Using Data Transfer Objects (DTOs)" chapter:
```
<?php
// api/src/Entity/Book.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(normalizationContext={"groups"={"book"}})
 */
class Book
{
    /**
     * @Groups({"book"})
     */
    public $name;

    /**
     * @Groups({"book"})
     */
    public $isbn;

    // ...
}
```

```
<?php
// src/Dto/BookInput.php

namespace App\Dto;

final class BookInput {
  /**
   * @Groups({"book"})
   */
  public $isbn;
}
```

```
<?php
// src/DataTransformer/BookInputDataTransformer.php

namespace App\DataTransformer;

use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
use App\Entity\Book;

final class BookInputDataTransformer implements DataTransformerInterface
{
    /**
     * {@inheritdoc}
     */
    public function transform($data, string $to, array $context = [])
    {
        $book = new Book();
        $book->isbn = $data->isbn;
        return $book;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsTransformation($data, string $to, array $context = []): bool
    {
        // in the case of an input, the value given here is an array (the JSON decoded).
        // if it's a book we transformed the data already
        if ($data instanceof Book) {
          return false;
        }

        return Book::class === $to && null !== ($context['input']['class'] ?? null);
    }
}
```

**Comment by teohhanhui** [comment]
Uhh, that makes sense, yes. PR welcome on https://github.com/api-platform/docs

**Comment by EmilCataranciuc** [comment]
Created the PR. Thank you.
