### ISSUE TITLE
Pagination : Incorrect next page

### ISSUE THREAD

**Issue by quser374** [api-platform/core#3393]
Hi

I have this pagination on my endpoint /products : 
`"hydra:view": {
        "@id": "/products?page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/products?page=1",
        "hydra:last": "/products?page=10",
        "hydra:next": "/products?page=2"
    },`

But if I manually go to page 12 which doesnt exists, I would have this pagination : 
`    "hydra:view": {
        "@id": "/products?page=12",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/products?page=1",
        "hydra:last": "/products?page=10",
        "hydra:previous": "/products?page=11",
        "hydra:next": "/products?page=13"
    },`

Is it normal ? Why does it say that there is a next page ?

Thanks in advance for your time.

**Comment by soyuka** [comment]
You're using partial pagination right? Help us fix this in https://github.com/api-platform/core/blob/master/src/Hydra/Serializer/PartialCollectionViewNormalizer.php#L117 please !

**Comment by WhiteRabbitDE** [comment]
What is the expected result ? To not render an non existing next page link? Could be enough to put the existing checks together and add something like $currentPage < $lastPage for next link.

What about previous page if e.g. 3 pages exist and i call page 5. Should it render page 3 or 4 ?
