### ISSUE TITLE
How to properly check permission on filter?

### ISSUE THREAD

**Issue by oleg-brizy** [api-platform/core#3398]
I have a required arg/filter for collection query which is an ID. I want to check if user has access to that ID before retrieving the collection from database.

I can throw an "AccessDenied" exception in resolver or data provider but maybe there is a cleaner way to do this, like a dedicated stage/layer where permissions checks should be done (not in data retrieval layer).

```php
<?php

/**
 * @ApiResource(
 *  graphql={
 *     ""={
 *         "collection_query"=MyCollectionResolver::class,
 *         "args"={
 *             "project"={"type"="ID!"}
 *         }
 *     }
 *  }
 * )
 * @ApiFilter(SearchFilter::class, properties={"project": "exact"})
 *
 * @ORM\Entity(...)
 */
class MyEntity
{
    /**
     * @ORM\ManyToOne(targetEntity="Project")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $project;
}
```

_Note: I use empty query name `""={...}` to override default collection query and to make it without prefix (like shown in docs)._

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/3369#issuecomment-587490206 mayber related. 

This should be done either pre-data retrieval either after, depends on how you see this. Anyway, a filter is here to filter when you retrieved the data, the way I understand your issue it should end up being something like:

```
SELECT data WHERE user has the right to fetch it
```

**Comment by oleg-brizy** [comment]
I saw that issue. From docs I understood that validation is more for mutations input, not for query parameters.

From annotation I don't see how it should be possible. Maybe something like this:

```
"args"={"project"={"type"="ID!", "security"="is_granted(project)"}}
```

but it looks like too much trouble for the devs of this platform.

----

I will try to debug the flow. I need to hook into the stage before resolver/dataProvider, right after the args have been parsed. Maybe decorate default denormalizer ([docs about extending](https://api-platform.com/docs/core/extending/#extending-api-platform)), not sure (the platform is still new to me and I am trying to figure things out).

**Comment by oleg-brizy** [comment]
Most examples related to custom logic permission check as result silently hide the data ([empty/filtered list](https://api-platform.com/docs/core/extensions/#example), [no value for attribute](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis)). I need to throw error that user has no permission to use such value in filter.

**Comment by oleg-brizy** [comment]
So far the most convenient place to do the permission check on filter is under [this](https://github.com/api-platform/core/blob/dee4c0980cdb4060191d738db08ab73fc6efde1e/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L97) (and [this](https://github.com/api-platform/core/blob/dee4c0980cdb4060191d738db08ab73fc6efde1e/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L143)) line.
My current plan is to copy/extend `SearchFilter` and add permission checks under those lines. I will throw `GraphQL\Error\Error` which is caught and on client I get 
`{"errors": [{"message": "Message from exception"}]}`

**Comment by teohhanhui** [comment]
I'd recommend doing authorization on the resources actually being accessed, i.e. don't care **how** they're being accessed, but only **what** is being accessed.

**Comment by oleg-brizy** [comment]
@teohhanhui My resource is shared and I give permissions on a category (in this example - project), when you access the resource (list) you must specify the category and I check if you have access to that category before retrieving the resource list from db.

I don't see how to implement your recommendation. Maybe you can provide some hints.

So far the solution is custom filter is acceptable for me.

**Comment by teohhanhui** [comment]
Assuming each of the resource item has a reference to the category, you could loop through the collection and call the voter on each item.

**Comment by oleg-brizy** [comment]
I don't like this approach because it's inefficient. I'll better check once on category filter arg before getting the collection from db.

**Comment by teohhanhui** [comment]
Mixing authorization logic into filtering logic is breaking the boundaries between the different layers of the system.

**Comment by desmax** [comment]
@oleg-brizy I usually create subresource route and check if i have access to holder object(category in your case). maybe this could  give you some ideas.

**Comment by oleg-brizy** [comment]
@desmax what do you mean by "subresource"? I'm doing this filtering in GraphQL only (I will disable REST for my project).

**Comment by desmax** [comment]
@oleg-brizy sorry, didn't notice graphql

but what I meant is this
```
*     subresourceOperations={
 *          "api_accounts_projects_get_subresource"={
 *              "method"="GET",
 *              "route_name" = "api_accounts_projects_get_subresource",
 *              "security_post_denormalize"="is_granted('list', [_api_resource_class, id, _api_subresource_operation_name])"
 *          },
 *     }
```
in voter I check if user has access to list projects of that particular account

**Comment by oleg-brizy** [comment]
@desmax Thanks. I will add this in todo for later investigation. Now I almost finished the custom filter.
