### ISSUE TITLE
Resources should allow fuller descriptions in the generated documentation

### ISSUE THREAD

**Issue by inferont** [api-platform/core#3399]
**Description**  
Currently, adding a description for an API will update the generated documentation with whatever is provided. This should be supported for resources as well. This field is currently supported in the Open API export. It should also show in the web view.

**Example**  
Adding a description field for a resource should cause the following text to appear.
![image](https://user-images.githubusercontent.com/12887855/74775111-a19a4e00-525a-11ea-913d-d5505851a84e.png)

**Comment by soyuka** [comment]
can be overriden
