### ISSUE TITLE
How to automatically filter embeding relations data?

### ISSUE THREAD

**Issue by winzza** [api-platform/core#3400]
**API Platform version(s) affected**: 2.5.4

**Description**
I'm very sorry to write here... I have a question, but stackoverflow didn't help me. Maybe someone will help me here https://stackoverflow.com/questions/60283532/how-to-automatically-filter-embeding-relations-data

Sorry again, for asking a question here.

**Comment by soyuka** [comment]
I've tried to answer there. Let's try to keep github for bug tracking.
