### ISSUE TITLE
Class Fig\Link\Link Not found

### ISSUE THREAD

**Issue by rhuot** [api-platform/core#3408]
**API Platform version(s) affected**: 2.4.6

**Description**  
Class Fig\Link\Link not found.

**How to reproduce**  
Symfony/web-link v4.4 remove dependance package web-link
https://github.com/symfony/web-link/compare/4.3...4.4

**Possible Solution**  
Add package "fig/link-util"

**Comment by soyuka** [comment]
ApiPlatform 2.5 has this.

**Comment by teohhanhui** [comment]
> **Possible Solution**
> Add package "fig/link-util"

Yes, that's the workaround if you want to stay on API Platform 2.4 (not recommended, as it's no longer maintained).

**Comment by soyuka** [comment]
> it's no longer maintained
2.4 still gets security fixes though :p
