### ISSUE TITLE
Open API version not recognized in Swagger documentation normalizer

### ISSUE THREAD

**Issue by stefankleff** [api-platform/core#3409]
**API Platform version(s) affected**: 2.5.4

**Description**  
The DocumentationNormalizer (ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer) should normalize the documentation according to the config value api_platform.swagger.versions.
In fact it will use always version 2. The reason for that is that in the container configuration (https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/swagger.xml#L34) the argument for the defaultContext is missing. Therefore the config value api_platform.swagger.versions gets injected as the constructor argument for $defaultContext and for the argument $swaggerVersions the constructor default value "[2, 3]" is used. 

**How to reproduce**  
Set api_platform.swagger.versions to [3]

**Possible Solution**  
Add an additional line for the argument for the defaultContext to the container definition

**Additional Context**

**Comment by soyuka** [comment]
see also https://github.com/api-platform/core/pull/3338

**Comment by soyuka** [comment]
fixed in https://github.com/api-platform/core/pull/3443
