### ISSUE TITLE
Broken getCollection in a custom collection data provider 

### ISSUE THREAD

**Issue by EmilCataranciuc** [api-platform/core#3415]
**API Platform version(s) affected**: 2.1.0

**Description**  
When getCollection returns an empty array, as per the documentation: https://api-platform.com/docs/core/data-providers/#custom-collection-data-provider Hydra returns the following error:
Given action "RA/CRUD_GET_LIST_SUCCESS", reducer "total" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

**How to reproduce**  
Create a custom collection data provider and return an empty array() for no results.

**Comment by EmilCataranciuc** [comment]
Seems to be related to the paginator but I am not 100% sure.

**Comment by EmilCataranciuc** [comment]
The problem seems to be related to the documentation and most likely isn't a bug.

**Comment by teohhanhui** [comment]
Can you share how you've resolved the issue? Is there a mistake in the docs? If so, feel free to send a PR to https://github.com/api-platform/docs

**Comment by ssengedonazil** [comment]
So how can we fix such then .  2days trying this

**Comment by ssengedonazil** [comment]
Thats what am streessed  with

**Comment by TheFuriousSnail** [comment]
@ssengedonazil I don't remember the context of this. But looking at my last comment I remember making some changes to the documentation. Generally API Documentation is quite good. If you follow it you should solve most of your issues.
