### ISSUE TITLE
decimal number float problem

### ISSUE THREAD

**Issue by gokselozgur** [api-platform/core#3426]
Hello everyone, 

I have a problem about price variable. I used these configurations, which are copied from api-platform documentation, for price variable.

    /**
     * @ODM\Field(type="float")
     * @Assert\NotBlank
     * @Assert\Range(min=0, minMessage="The price must be superior to 0.")
     * @Assert\Type(type="float")
     * @Groups({"product"})
     */
    public $price;

However, it cannot post the values like 10.00 but it posts 10.01
Anyone know how can I solve this?

**Comment by teohhanhui** [comment]
As for MongoDB, there's the `Decimal128` type, but unfortunately it's not supported by Doctrine MongoDB ODM yet: https://github.com/doctrine/mongodb-odm/issues/1835
