### ISSUE TITLE
The default configuration is lost if any attribute is set

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3428]
**Description**  

There is something annoying with the new default config mechanism introduced in `master`: if you set any attribute, even just one, the default config for all other attributes is lot. IMO it's not the expected behavior. Defaults should always be applied if not overrode at the resource or operation level. To do so, the metadata factory applying the default should be the last one in the decoration chain, and set values that have not been set explicitly.

**Comment by soyuka** [comment]
I can't reproduce see https://github.com/soyuka/core/pull/new/fix-default-behavior and run `vendor/bin/behat --stop-on-failure features/http_cache/headers.feature:15`.

Attributes in the resource annotation do get the defaults (in `config_common`, top left):

![20200424_11h06m56s_grim](https://user-images.githubusercontent.com/1321971/80196006-07b99d80-861d-11ea-8d5f-d734ad0307b6.png)

The final resource attributes are on the right, IMO it's the correct behavior (unless we want a recursive merge on the `vary` config?, I doubt that).
