### ISSUE TITLE
[SwaggerUI] Unable to overwrite context with elao enum types

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#3432]
**API Platform version(s) affected**: 2.5.4

**Description**  

I'm using elao/enum in my project. When generating the SwaggerUI, the Enums are generated as Definitions for Read and Write operation. Unforunatly those definition is empty ( Links to #/definitions/MediaEnum-read ) . 
I wanted to overwrite the swagger_context to help the user to understand what values they have to input.
e.g.
`* @ApiProperty( attributes={"openapi_context"={
     *     "type"="string",
     *     "enum"={"video/mp4", "video/mpeg"},
     *     "example"="video/mpeg"}})
     *`
The field type is mediaEnum in this example which is an instance of Elao\Enum\Bridge\Doctrine\DBAL\Types\AbstractEnumType.

The problem is that the overwritten openapi_context is not used for this field. It works for simple fields like the "description" field which is just  type="string"

I know there are some Issues/PRs open and merged regarding the swagger ui. Does one of them solve this problem ? If not, im more than willing to work on a solution if anyone could point me into the right direction.

**Comment by teohhanhui** [comment]
See #3007.

**Comment by teohhanhui** [comment]
Hmm... This would require decorating the `TypeFactory`, so that we know `Elao\Enum\EnumInterface` classes are enums, not objects. Not sure if it'd require further changes...

**Comment by WhiteRabbitDE** [comment]
Decorating the TypeFactory did the Trick! Thanks @teohhanhui !

Shall i make a PR and add that directly into the TypeFactory or is that to specific to add ElaoEnum Implementation?

**Comment by soyuka** [comment]
It's a bit too specific, an entry in the documentation would help though!

**Comment by teohhanhui** [comment]
I think this kind of integration should be provided out of the box, like how we have support for `ramsey/uuid` (custom normalizer).

It should be a decorator, I think.

**Comment by WhiteRabbitDE** [comment]
> It should be a decorator, I think.

Ramsey is supported directly in the TypeFactory. Why do you prefer to add elao as decorator ? We wouls have to add it as dependency to check the class too or do you want to not register the decorator by default?

**Comment by teohhanhui** [comment]
We can change that to be in another decorator too. It's not practical to inline everything as such an approach is not scaleable.
