### ISSUE TITLE
Add missing parameter $defaultContext for Swagger docs normalizer

### ISSUE THREAD

**Issue by rendler-denis** [api-platform/core#3434]
**API Platform version(s) affected**: 2.5

**Description**  
The service definition for ```api_platform.swagger.normalizer.documentation``` was missing a value for the ```$defaultContext``` parameter. Since the ```$defaultContext``` and ```$swaggerVersions``` are both arrays the issue did not appear to be easily visible.

**How to reproduce**  
Build the container and take a look at the definition for ```api_platform.swagger.normalizer.documentation```

**Possible Solution**  
I've created a [PR to fix this for branch 2.5](https://github.com/api-platform/core/pull/3433)

**Comment by soyuka** [comment]
Why do I have a feeling of deja vu ? https://github.com/api-platform/core/pull/3338

**Comment by rendler-denis** [comment]
:laughing:  at least my fix doesn't break any tests. I did look for a similar issue, but since I am already pressured by time and I had a quick fix I thought let's do this. you can close it if you consider not needing it.

**Comment by soyuka** [comment]
thnaks @rendler-denis

**Comment by teohhanhui** [comment]
Hmm... We need to improve our behavioural tests then. Something like this should have been caught...

**Comment by teohhanhui** [comment]
This class suffers from too many arguments anyway. :laughing: :sweat:
