### ISSUE TITLE
Wrong link on github

### ISSUE THREAD

**Issue by yapro** [api-platform/core#3444]
I try to add a question and see:

![image](https://user-images.githubusercontent.com/263248/76619662-74c91600-653c-11ea-8eef-9b5ffc9e1a88.png)

Than I clik on link https://api-platform.com/support/ and see:

![image](https://user-images.githubusercontent.com/263248/76619748-a641e180-653c-11ea-84c2-c34cc3a32e6a.png)

**Comment by soyuka** [comment]
We forgot to change it by https://api-platform.com/community

**Comment by norkunas** [comment]
Redirects helps in this case :)

**Comment by toofff** [comment]
Done ;)
