### ISSUE TITLE
SearchFilter not work for related fields

### ISSUE THREAD

**Issue by yapro** [api-platform/core#3446]
**API Platform version(s) affected**: v2.5.4

**Description**  
I need to get all sites for one group, but SearchFilter for the SiteGroupAssociation doesn't see fields: group, site.

![image](https://user-images.githubusercontent.com/263248/76620916-4f89d700-653f-11ea-9e7e-b6d968cb2564.png)

**How to reproduce**  

https://github.com/yapro/api-platform-test/commit/2c5188632d2f5fe3a8e0d32eb5565fb4358e72db

**Comment by soyuka** [comment]
Does this work without SwaggerUI?

**Comment by yapro** [comment]
I am using Entity relations incorrectly, here is a right example https://github.com/api-platform/demo/blob/master/api/src/Entity/Book.php#L117

**Comment by teohhanhui** [comment]
In order to filter on relations, you have to specify them explicitly in the `properties` of the `SearchFilter`. Not passing a whitelist of allowed properties is **not** recommended anyway.
