### ISSUE TITLE
Pomm support

### ISSUE THREAD

**Issue by sanpii** [api-platform/core#345]
- [X] PB  - Add sf/PropertyInfo type extractor
- [x] PB  - Add sf/PropertyInfo list extractor
- [x] API - DataProvider + EventListener
- [x] PB  - Add sf/Serializer normalizer for complexe type (Point, Circle, etc.)

**Comment by sanpii** [comment]
For pomm, I pushed a new `api-platform` branch in the [symfony bridge](https://github.com/pomm-project/pomm-symfony-bridge/tree/api-platform) and in the [bundle](https://github.com/pomm-project/pomm-bundle/tree/api-platform).

Today, I created the extractor for sf/PropertyInfo component and test the serialization with a simple entity. We probably have enough to start work in the api bundle.

**Comment by sroze** [comment]
Great, thank you @sanpii. I'll have a look to create the data provider asap.

**Comment by sanpii** [comment]
Complex type serialization seems working fine: https://github.com/pomm-project/pomm-bundle/blob/api-platform/tests/tests/Features/serializer.feature

**Comment by dunglas** [comment]
Great! I take care of the migration to of master to the Symfony PropertyInfo Component.

**Comment by dunglas** [comment]
Would be nice to have Pomm support in 2.1!

**Comment by Simperfit** [comment]
@sanpii @dunglas Can we do something on our end to do this ? 
Do you want some help for doing this ?

**Comment by sanpii** [comment]
@Simperfit for the pomm bundle, all stuff is ready to merge and planned for the next minor version.

I probably will merge tomorrow.

**Comment by sanpii** [comment]
Merged.

**Comment by sanpii** [comment]
Some good news: the new version of pomm bundle, with the PropertyInfo list extractor, is on the road (first RC today).
 
I implemented the write event listener, but I don’t understand how can I get the data. Currently I use `$request->getContent()`: https://github.com/sanpii/api-platform-core/blob/pomm/src/Bridge/Pomm/WriteListener.php#L39

Some test about what the pomm bridge can do: https://github.com/sanpii/api-platform-pomm-test/blob/master/tests/Features/pomm.feature

**Comment by dunglas** [comment]
Great to hear!

About the event listener, I don't get why you need those lines: https://github.com/sanpii/api-platform-core/blob/pomm/src/Bridge/Pomm/WriteListener.php#L39-L40

At this point, the Symfony Serializer (in `DeserializeListener`) will already have updated the entity (https://github.com/api-platform/core/blob/master/src/EventListener/DeserializeListener.php#L66-L68).

**Comment by sanpii** [comment]
> I don't get why you need those lines

Because the entity is empty. It’s probably a problem with the desezializer.

**Comment by dunglas** [comment]
Indeed, looks like it fail to use the Pomm to PropertyInfo Bridge.

**Comment by sanpii** [comment]
Ok, that works fine with a denormalizer for the pomm entities.

But in exchange, I lose the hydra metadata: https://github.com/sanpii/api-platform-pomm-test/blob/master/tests/Features/pomm.feature#L130-L134

**Comment by sanpii** [comment]
Well, the deserializer is now in the pomm bundle master.

I also extract my core modifications in a new bundle: https://github.com/sanpii/pomm-api-platform

**Comment by sanpii** [comment]
Great! I switched to `application/json` format for the tests and all work as I expect 😃 

My work is almost done, I’ll see with @chanmix51 to migrate this repository to pomm-project organisation, but now I waiting for feedbacks.

**Comment by soyuka** [comment]
What's the status on this?

**Comment by alanpoulain** [comment]
I think we can consider it done in the bundle (https://github.com/pomm-project/pomm-api-platform). Thank you @sanpii!
However, it needs to be documented and referenced. I've created the issue in the docs: https://github.com/api-platform/docs/issues/932
