### ISSUE TITLE
Exported OAS specification does not load into API Gateway

### ISSUE THREAD

**Issue by frak** [api-platform/core#3462]
**API Platform version(s) affected**: 2.5.4

**Description**  
When exporting the API defintiion as OAS, the resultant file will not import into AWS API Gateway stating "Unable to build importer with provided input. Unable to determine OAS version"

**How to reproduce**  
Run the command: `$ symfony console api:openapi:export -y --spec-version=3 --api-gateway -o apigw.yaml`
Now try to [create an API Gateway](https://eu-west-1.console.aws.amazon.com/apigateway/main/import?region=eu-west-1) with the resultant YAML and you will see the error in the AWS console.
(I have also tried JSON and manually changing the version of the output to 3 as that seems to stay as version 2 no matter what version you select.)

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/2821
