### ISSUE TITLE
hydra:writable should be hydra:writeable (misspelled)

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#3464]
**API Platform version(s) affected**: any

**Description**  
There has never been `hydra:writable` in the Hydra spec.

**How to reproduce**  
N/A

**Possible Solution**  
Rename `hydra:writable` to `hydra:writeable`. We have to make the corresponding changes in https://github.com/api-platform/api-doc-parser too.

**Additional Context**  
N/A

**Comment by adrientiburce** [comment]
I opened a PR on this repo and on api-doc-parser, I'm not sure if something else needs to be changed.

**Comment by adrientiburce** [comment]
@teohhanhui  It can be closed, I don't know why Github doesn't close automatically this issue.
