### ISSUE TITLE
[GraphQl] Error in response when value is null

### ISSUE THREAD

**Issue by alexia-soares** [api-platform/core#3465]
**API Platform version(s) affected**: 2.5.4

**Description**  
When a selected field is empty in database, the reponse of a GraphQl request contains the following error, but the result is still correct. The GraphQl query is correct and when I fill this data in DB, error disappears.

query : 
```
{
  item(id: "cc429bad-960a-4b1d-94bc-7188f8f7a8c0") {
    id
    name
    emails
  }
}
```

error : 
```
{
  "errors": [
    {
      "message": "Resource class cannot be determined.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "item",
        "emails"
      ]
    }
  ],
  "data": {
    "item": {
      "id": "cc429bad-960a-4b1d-94bc-7188f8f7a8c0",
      "name": "Item name",
      "emails": null
    }
  }
}
``` 
This error appears after apiplatform/core upgrade from 2.4.5 to 2.5.4.

**Comment by alexia-soares** [comment]
More informations : 
This error occures only on Doctrine JSON type column, when data is null instead of empty array, 
it seems like a regression.

**Comment by MarcDiaz** [comment]
Up.

I have exactly the same problem.

**Comment by Syourt** [comment]
Same issue here.
