### ISSUE TITLE
Configuration version

### ISSUE THREAD

**Issue by baudev** [api-platform/core#3467]
Currently, the `version` of the API (the one shown into the swagger documentation) must be set into the `config/packages/api_platform.yaml` file.

https://github.com/api-platform/core/blob/3b8dc7daa8ecb89d444a8fca220acea341ee4861/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L158

However, I see no reason why this version could not simply be selected from the version specified in the project's `composer.json`.
In fact, when someone manages a project using API Platform and version it, he versions the `composer.json.` The current system requires to modify at each version change the `composer.json` and also the `api_platform.yaml` file.

What do you think about this?

I tag the creator of the configuration file @dunglas

**Comment by adrientiburce** [comment]
I think it could be different if you have a Symfony project using API Platform,
* let's say you are doing some changes in you project perhaps you'd like to increment your project's `composer.json`
* and vice-versa if you make a small fix on you API, there is no reason to edit the `composer.json`

**Comment by baudev** [comment]
@adrientiburce 
I don't really see any concrete cases where your two points apply.

Let's imagine that `composer.json` and the API version are at version `2.1.0`. You make a bug fix on the API (hotfix). 
If you updated only the API version, then your API would be at version `2.1.1`. And your `composer.json` would stay at `2.1.0`? I find that doesn't really make sense (unless you consider that the API or` composer.json` version is not useful, so in that case why not merge them?).

**Comment by adrientiburce** [comment]
@baudev 
I personally don't use the version in my `composer.json` but let's say we use it, we have a php project at version 2.0.
If we want to add an API only now, then it would be useful to have its own version and begin with 1.0.

**Comment by baudev** [comment]
@adrientiburce 
In this case it is recommended, and much cleaner, to start the API in a separate folder and start a new composer project (`compose init`). Indeed, this is intended by the principle of modularity in computing.
