### ISSUE TITLE
FilterEagerLoadingExtension duplicates joins added by EagerLoadingExtension

### ISSUE THREAD

**Issue by julienfalque** [api-platform/core#3487]
**API Platform version(s) affected**: 2.5.4

**Description**  
On a collection operation with filtering, `FilterEagerLoadingExtension` transforms the query into a wrapped subquery: `... WHERE o.id IN( <original query> )`. When doing so, it duplicates joins from the original query and keeps them on the wrapping query in the result.

Though some of those joins might have been added by `EagerLoadingExtension`. Duplicating them is not necessary as they don't change the result (the retrieved resources will be the same). They should appear in the wrapping query, but not in the wrapped one. With many extra joins, this can lead to performance penalty. In my case I'm not sure yet whether the performance penalty was a database issue (e.g. missing index) but preventing joins duplication fixed it.

**How to reproduce**  
Use a filter on a collection operation of a resource that has many eager loaded relations.

**Possible Solution**  
To prevent the duplication, I changed the `priority` attribute of the `api_platform.doctrine.orm.query_extension.collection` tag of `EagerLoadingExtension`: I set it to `-18` instead of `-8` so it runs *after* `FilterEagerLoadingExtension`. This did not break any test on the project but I don't know all the implications of such change. Should the tag be updated in `api-platform/core`? If so, maybe `FilterEagerLoadingExtension` could be merged into `EagerLoadingExtension`?

**Comment by soyuka** [comment]
Maybe related: https://github.com/api-platform/core/issues/2908

IIRC the order is important because FilterEagerLoadingExtension should be run after filter which runs after eagerloadingextension or something like that :p. We covered the use case with a behat test so if you try running them it should fail somewhere. The solution proposed in the related issue may be a cleaner one?

**Comment by julienfalque** [comment]
As far as I understand, #2908 is a slighly different issue: it is about not adding eager loading joins when those joins already exist in the query. In my case, there was no joins in the original query.

I'll have a look at the Behat test you mentionned.

**Comment by julienfalque** [comment]
So I tried running Behat tests with the change described above and all tests pass on both `2.5` and `master` branches. Shall we give my proposal a try?

**Comment by soyuka** [comment]
Why not indeed!

**Comment by julienfalque** [comment]
#3525 has been merged.
