### ISSUE TITLE
XML path configuration for subresources?

### ISSUE THREAD

**Issue by yivi** [api-platform/core#3490]
We are trying to change the path serialization group for several subresources in our project, but no settings do not appear to make any difference.

For the entity `LeadsReceived`, with a many-to-may relationship with `Specialty` we have the property `specialties` declared as a subresource:

```xml
<resources xmlns="https://api-platform.com/schema/metadata">
    <resource class="App\Domain\Entity\LeadReceived">
   <!-- rest of the config -->
        <property name="specialties">
            <subresource resourceClass="App\Domain\Entity\Specialty" collection="true" maxDepth="1" />
        </property> 
</resource>
```
This works. And it's great.

Problem is, we'd like to change the  generated path for the subresource. I've executed `debug:router` and I've seen that the appropriate route is `api_lead_receiveds_specialties_get_subresource`. By following the [docs](https://api-platform.com/docs/core/subresources/) I've added the following to the configuration file:

```xml
<resources xmlns="https://api-platform.com/schema/metadata">
    <resource class="App\Domain\Entity\LeadReceived">
        <!-- rest of the config -->
         <subresourceOperations>
            <subresourceOperation name="api_lead_receiveds_specialties_get_subresource">
                <attribute name="path">/leads_received/{id}/all_specialties</attribute>
            </subresourceOperation>
        </subresourceOperations>
</resource>
```

But the path is unchanged. I execute `debug:router api_lead_receiveds_specialties_get_subresource` and I get exactly the same route as before.

I get the route `/api/lead_receiveds/{id}/specialties`, which is the default generated one, instead of `/api/leads_received/{id}/all_specialties`, which is what I expect from the above configuration..

Am I doing something wrong? Is this a bug? Not supported for XML configuration? Does it need to be configured on the owning side of the relationship (`LeadsReceived`, in this case), or in the other side?

In the docs there are subresource annotations both on `Question` and `Answer`, which makes it slightly confusing.

**Comment by yivi** [comment]
[Here](https://api-platform.com/docs/core/subresources/#using-custom-paths), for example, we see the `subresourceOperations` part of the annotation being used on both sides of the relationship (Question and Answer).

This makes it look as if, when using XML configuration, I can define de `subresourceOperations` in either resource configuration. In my case, I tried setting the configuration above both in `LeadReceived.xml` and `Specialty.xml`, where the resource configuration for each class is kept.

But the results are the same (the subresource URL path does not change).

I'm not sure if something is missing in the docs or if it is me misreading them. Would love to offer a PR to the docs to help a bit, but not sure _what_ should the docs say in this case.

**Comment by yivi** [comment]
I'm trying to debug this myself, but can't find exactly where the problem is yet. 

I see that the routes are loaded on `ApiPlatform\Core\Bridge\Symfony\Routing\ApiLoader::load()`, but that only the regular subresource (defined as "properties) routes are added to the route collection. 

`$resourceMetadata` has the appropriate values (specifically `$resourceMetadata['subresourceOperations']`, loaded earlier on `ApiPlatform\Core\Metadata\ExtractorXmlExtractor::extractPath()`), but these do not seem to be used for route generation, so they wouldn't affect the resulting path.

It's more likely this is me doing something wrong and not a bug, but it does seem that the documentation does not match the results here (but the docs not always reflect all the different configuration options &mdash;XML, YML or annotations&mdash;, so it may be me misreading them) .

If there is an actual problem, would love to help finding it, but might need a prod in the right direction so I can look at the right place in the source code.

**Comment by soyuka** [comment]
Hi sorry for the late answer, please see https://github.com/api-platform/core/issues/3458 which should be a first answer. We worked on improving this in https://github.com/api-platform/core/pull/3466, still few things to be improved there if you want to check if that may be a fix for you, thanks !

**Comment by yivi** [comment]
No apologies necessary. Thanks for replying at all, much obliged.

 I'll investigate those two links

**Comment by yivi** [comment]
It works! **Thank you** so much! I grew some grey hair with this.

No sense making a docs PR, since there is already a PR pending to fix the more immediate problem.

**Comment by soyuka** [comment]
Nice, please if you can help with testing the Pull request or giving some opinion about how we could improve the DX onthis particular issue don't hesitate!
