### ISSUE TITLE
[GraphQL] Custom mutation resolver - 'Undefined index: input' error

### ISSUE THREAD

**Issue by kacperjurak** [api-platform/core#3492]
**API Platform version(s) affected**: api-platform/core (dev-master dd497cf)

**Description**  
We have a custom mutation resolver with custom input types, like in docs (https://api-platform.com/docs/core/graphql/#custom-mutations). After runnning a custom mutation, all the logic is properly executed, and data are saved in the database, but the response has an error - `Notice: Undefined index: input` instead of data of inserted item.

Everything works well in 2.5.4. Changing api-platform/core to dev-master in composer.json (switching to dev version) causes problems. We are trying to use dev version, because of page pagination (which will be included in API Platform 2.6). 

**How to reproduce**  
Create custom mutation, e.g. createCompany, and put some logic inside.

Then run a mutation, for example in Playground:

`mutation {
  createCompany(input: {company: {name: "company name", notes: "notes"}}, companyMainContactPerson: {email: "mail@example.com", roles: []}) {
    company {
      id
      name
      notes
      mainContactPerson {
        id
      }
    }
  }
}`

and we have an error: 
`Notice: Undefined index: input`

![image](https://user-images.githubusercontent.com/8933136/79343685-00b0d200-7f2f-11ea-89fc-cd4713c9034a.png)

**Comment by keresztesiattila** [comment]
I can confirm it happens on the latest 2.6.4 release also.

**Comment by andreiborca** [comment]
Hi @kacperjurak . Have you fund a way to avoid the issue? A workaround maybe? Thanks in advance.

**Comment by kacperjurak** [comment]
> 
> 
> Hi @kacperjurak . Have you fund a way to avoid the issue? A workaround maybe? Thanks in advance.

Unfortunately not.

**Comment by kacperjurak** [comment]
There are more details about this problem in #4183
