### ISSUE TITLE
Wrong use of link rel for mercure

### ISSUE THREAD

**Issue by GregoireHebert** [api-platform/core#3499]
**API Platform version(s) affected**: ^2.0

At the moment the link header added is as follows: `<https://demo.mercure.rocks/hub>; rel="mercure"`
But only relations in the IANA registry should be used.
`<https://demo.mercure.rocks/hub>; rel="hub"`

https://www.iana.org/assignments/link-relations/link-relations.xhtml

In the meantime you could also fill in a request.

Relation types are registered on the advice of a Designated Expert
(appointed by the IESG or their delegate), with a Specification
Required (using terminology from RFC5226).

Registration requests consist of the completed registration template
below, typically published in an RFC or Open Standard.  However, to allow for the allocation of values prior to publication, the Designated Expert may
approve registration once they are satisfied that a specification
will be published.

Note that relation types can be registered by third parties, if the
Designated Expert determines that an unregistered relation type is
widely deployed and not likely to be registered in a timely manner.

The registration template is:

* Relation Name:
* Description:
* Reference:
* Notes: [optional]
* Application Data: [optional]

Registration requests should be sent to the link-relations@ietf.org
mailing list, marked clearly in the subject line (e.g., "NEW RELATION - mercure" to register a "mercure" relation type).

Within at most 14 days of the request, the Designated Expert(s) will
either approve or deny the registration request, communicating this
decision to the review list and IANA.  Denials should include an
explanation and, if applicable, suggestions as to how to make the
request successful.

Decisions (or lack thereof) made by the Designated Expert can be
first appealed to Application Area Directors (contactable using
app-ads@tools.ietf.org email address or directly by looking up their
email addresses on http://www.iesg.org/ website) and, if the
appellant is not satisfied with the response, to the full IESG (using
the iesg@iesg.org mailing list).

But I have the feeling that hub is appropriate.

**Comment by dunglas** [comment]
The rel=mercure is being submitted by IANA, and is in the spec. This mustn't change.
