### ISSUE TITLE
FQDN context

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#350]
Hi,

I noticed that `@context` does not include the FQDN, example:

```
@context: "/api/contexts/Distributor"
```

The example on [json-ld.org](http://json-ld.org/) does include the FQDN.
 
Is there a built-in configuration to change that behavior, or do I need to implement it myself?

**Comment by felicitus** [comment]
It seems that https://github.com/dunglas/DunglasApiBundle/blob/1.0/JsonLd/ContextBuilder.php does use `RouterInterface::ABSOLUTE_URL` for `getBaseContext`, but not for `getContextUri`. I think this should be made configurable.

**Comment by dunglas** [comment]
See my comment in #351
