### ISSUE TITLE
No item route associated when itemOperations is set but empty

### ISSUE THREAD

**Issue by symfonyaml** [api-platform/core#3501]
**API Platform version(s) affected**: 2.5.4

## Description
When the `itemOperations` is empty, and `collectionOperations` is set, there is an error when fetching the collection like `[GET] /api/books`

```php
No item route associated with the type "App\Entity\Book"
error in RouteNameResolver.php line 62
```

## How to reproduce
Create an entity with the api mapping
```yaml
App\Entity\Book:
    itemOperations: {} # <---- this creates the bug
    collectionOperations: { get: ~ }
```

##  Possible Solution
in  [RouteNameResolver.php line 50](https://github.com/api-platform/core/blob/5f7eaf3df1e580a41ea7274c2de868f74fc14353/src/Bridge/Symfony/Routing/RouteNameResolver.php#L50), the value returned in the sprintf for `$operationType` should be _collection_, but its _item_ instead.

Then the route default value  `_api_item_operation_name` does not exists so no route is not found.
When I replace by `_api_collection_operation_name` it works.

##  Occurences
 - [In this comment](https://github.com/api-platform/api-platform/issues/492#issuecomment-549944885)
 - Looks like [this ticket](https://github.com/api-platform/core/issues/2823) is a duplicate. It uses `itemOperations: []` too

**Comment by soyuka** [comment]
Indeed the safe way to diable item operations is to do:

```
/**
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *             "method"="GET",
 *             "controller"=NotFoundAction::class,
 *             "read"=false,
 *             "output"=false,
 *         },
 *     },
 * )
 */
```

As documented [at the end of this section](https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations).

**Comment by symfonyaml** [comment]
@soyuka thanks for your answer.
Unfortunately your solution still list the get item endpoint in the the swagger doc.
I am really confused why it would not be possible to just have a list endpoint for an entity.

**Comment by versh23** [comment]
you can remove it by swagger decorator https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification

**Comment by akerouanton** [comment]
You can also manually set the IRI used by the normalization context, such that it won't try to generate one:

```yaml
App\Entity\Book:
    itemOperations: {}
    collectionOperations: { get: { normalization_context: { iri: "" } } }
```
