### ISSUE TITLE
SearchFilter on ElaoEnum values broken in 2.5.5

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#3512]
**API Platform version(s) affected**: 2.5.5

**Description**  
When using a search filter in 2.5.5 on a field that is a enum (elao) an error occurs 
`"Error : Call to a member function getValue() on string"`

The change that is causing this error is #3331.

**How to reproduce**  
Set up a field with an enum type e.g.

```
    /**
     * @var MediaEnum
     *
     * @ORM\Column(name="MIME_TYPE", type="mediaEnum", length=255)
     */
    private $mimeType;
```
and try to filter on that field 
`$this->request('GET', 'attachments?mimeType=image/jpeg')`

**Possible Solution**  

**Additional Context**  
`Error : Call to a member function getValue() on string
 apiplatform-projekt\vendor\elao\enum\src\Bridge\Doctrine\DBAL\Types\AbstractEnumType.php:55
 apiplatform-projekt\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1588
 apiplatform-projekt\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:1621
 apiplatform-projekt\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:914
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\Query\Exec\SingleSelectExecutor.php:50
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\Query.php:337
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php:992
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php:947
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\AbstractQuery.php:750
 apiplatform-projekt\vendor\doctrine\orm\lib\Doctrine\ORM\Tools\Pagination\Paginator.php:177
 apiplatform-projekt\vendor\api-platform\core\src\Bridge\Doctrine\Orm\AbstractPaginator.php:69
 apiplatform-projekt\vendor\api-platform\core\src\Hydra\Serializer\CollectionNormalizer.php:86
 apiplatform-projekt\vendor\api-platform\core\src\Hydra\Serializer\PartialCollectionViewNormalizer.php:55
 apiplatform-projekt\vendor\api-platform\core\src\Hydra\Serializer\CollectionFiltersNormalizer.php:73
 apiplatform-projekt\vendor\symfony\serializer\Serializer.php:146
 apiplatform-projekt\vendor\symfony\serializer\Serializer.php:119
 apiplatform-projekt\vendor\api-platform\core\src\EventListener\SerializeListener.php:95
 apiplatform-projekt\vendor\symfony\event-dispatcher\Debug\WrappedListener.php:126
 apiplatform-projekt\vendor\symfony\event-dispatcher\EventDispatcher.php:264
 apiplatform-projekt\vendor\symfony\event-dispatcher\EventDispatcher.php:239
 apiplatform-projekt\vendor\symfony\event-dispatcher\EventDispatcher.php:73
 apiplatform-projekt\vendor\symfony\event-dispatcher\Debug\TraceableEventDispatcher.php:168
 apiplatform-projekt\vendor\symfony\http-kernel\HttpKernel.php:163
 apiplatform-projekt\vendor\symfony\http-kernel\HttpKernel.php:80
 apiplatform-projekt\vendor\symfony\http-kernel\Kernel.php:201
 apiplatform-projekt\vendor\symfony\http-kernel\Client.php:65
 apiplatform-projekt\vendor\symfony\framework-bundle\Client.php:131
 apiplatform-projekt\vendor\symfony\browser-kit\AbstractBrowser.php:390
 apiplatform-projekt\vendor\api-platform\core\src\Bridge\Symfony\Bundle\Test\Client.php:124
 apiplatform-projekt\tests\Appointment\AttachmentApiTest.php:50`

**Comment by maciej-laskowski** [comment]
I have experienced the same issue.

**Comment by kacperjurak** [comment]
Same for me. Needed revert to 2.5.4.

**Comment by guilliamxavier** [comment]
Does 2.5.6 fix the issue?

**Comment by maciej-laskowski** [comment]
@guilliamxavier Yes, upgrading to 2.5.6 fixed the issue. Thanks!
