### ISSUE TITLE
Breaking change in 2.5.5

### ISSUE THREAD

**Issue by rmikalkenas** [api-platform/core#3513]
**API Platform version(s) affected**: 2.5.5

**Description**  
A new argument was added to ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter::addWhereByStrategy which is not introduced to changelog.

Does the api platform follows semantic versioning? Because patch and minor releases should not contain breaking changes

**Comment by soyuka** [comment]
Oh indeed, this is my fault, I thought we added this argument as last with a default value to minimize the impact... I wish we had an interface so that I'd have seed this earlier.

**Comment by dunglas** [comment]
@rmikalkenas we do follow semver, but bugs happen ;) We're on it!

**Comment by devel-pa** [comment]
Hi,

I understand that the parameter is placed wrong and delivers a beautiful BC.
But also this revert breaks my entire app filtering by subresource binary uuid.
There is any chance to have this implemented back any time soon?

Thanks,

Paul

**Comment by soyuka** [comment]
this has been reverted in 2.5.6

**Comment by devel-pa** [comment]
;(
a BC with a BC.
For whom will need you can bring back the functionality by using the `2.5.5` SearchFilter in your src and use that instead the `2.5.6` one.
