### ISSUE TITLE
customize graphql schema

### ISSUE THREAD

**Issue by MartkCz** [api-platform/core#3523]
I want to add low-level mutation e.g. create share links. Now it's not possible because Schema returned by SchemaBuilder is immutable.

Idea:
```php
interface SchemaBuilderInterface
{
    public function getSchema(): GraphQlSchemaBuilderInterface;
}
```

```php
interface GraphQlSchemaBuilderInterface
{
    public function addQuery(string $name, array $configuration): static;

    public function addQueries(array $fields): static;

    // Same for Mutations, Subscriptions
  
    public function setTypeLoader(callable $typeLoader): static;

    public function build(): Schema;

    // More methods in future if needed
}
```

I could prepare PR

**Comment by alanpoulain** [comment]
Why not using a custom query?

**Comment by MartkCz** [comment]
Because it's tied to an entity (https://github.com/api-platform/core/blob/master/src/GraphQl/Type/FieldsBuilder.php#L114 - resourceClass cannot be null). Mutation *share* does not have entity, returns only array of string.

I didn't find other solution

**Comment by alanpoulain** [comment]
Why not creating a specific *resource* for this need (not tied to Doctrine), and a custom mutation for it?

**Comment by MartkCz** [comment]
I'll try, thank you

**Comment by MartkCz** [comment]
It works. Thanks again
