### ISSUE TITLE
IdentifierDenormalizers loop is not stopped as soon as Identifier was converted

### ISSUE THREAD

**Issue by oleg-andreyev** [api-platform/core#3538]
**API Platform version(s) affected**: v2.5.5

**Description**  
- I'm using UUID as my primary keys
- I'm using `me` keyword in URLs to avoid exposing UUID
- Using IdentifierDenormalizers to convert `me` to UUID (user is taken from TokenStorage)
- When `me` was converted to UUID (Object) IdentifierDenormalizers loop is not stopped

**Possible Solution**  
- If `$identifierDenormalizer` is supported and it was able to convert `$identifier` into something loop should stop.

**Additional Context**  
![image](https://user-images.githubusercontent.com/1244112/80616198-47332000-8a49-11ea-8bb7-6fb75a735fca.png)
![image](https://user-images.githubusercontent.com/1244112/80616280-6631b200-8a49-11ea-8e34-8dc115906202.png)
![image](https://user-images.githubusercontent.com/1244112/80616338-76e22800-8a49-11ea-9e04-87784dc6eed1.png)

**Comment by WhiteRabbitDE** [comment]
Are you using ramsey/uuid version >= 4 ? I think i had the same issue, @soyuka made a fix for this which  will be released with 2.5.6. 

The fix --> #3511

**Comment by oleg-andreyev** [comment]
@WhiteRabbitDE yes, it looks like `\is_string($data)` in `supportsDenormalization` will help.
Despite said above do we really need to continue iterate over `IdentifierDenormalizers` as soon as identified was converted? Based on the code of `IdentifierConverter` there is an assumption that identifier could be converted more than once

**Comment by soyuka** [comment]
this has been fixed :)

**Comment by guilliamxavier** [comment]
Maybe the real fix was #3578
