### ISSUE TITLE
[GraphQl] OneToMany without Doctrine

### ISSUE THREAD

**Issue by MartkCz** [api-platform/core#3542]
**API Platform version(s) affected**: current dev-master

```php
/**
 * @ApiResource()
 */
final class Timeline
{

	/**
	 * @var PostUnion[]|PaginatorInterface
	 */
	public iterable $posts;

}
```

```php
/**
 * @ApiResource()
 */
final class PostUnion
{

	public string $type;

	public ?string $subject;

	public string $content;

}
```

I'm getting IterableConnection instead of PostUnionConnection.

The goal is:

```php
$timeline = new Timeline();
$timeline->posts = new ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator($postPaginator);

return $timeline;
```

Any suggestion or it's bug?

**Comment by mxmp210** [comment]
Use PostUnion[] | Collection as variable type.

You will also need to hydrate collectionand return it with ArrayPaginator instance from your data provider in order to work with GraphQL as simple arrays are not supported with graphql for pagination purposes.

**Comment by alanpoulain** [comment]
Fixed by https://github.com/api-platform/core/pull/3591.
