### ISSUE TITLE
ODM: issue with embedded subresources

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#3549]
As far as I see the current subresource data provider doesnt cover the case with collection of embedded items. The issue is here:
https://github.com/api-platform/core/blob/cfc05d1ce5e9e45898cb95ab71abf47e2d579da3/src/Bridge/Doctrine/MongoDbOdm/SubresourceDataProvider.php#L150-L161 

I propose the following fix:
```
        if ($classMetadata->hasAssociation($previousAssociationProperty)) {
            foreach ($normalizedIdentifiers as $key => $value) {
                $aggregation->match()->field($key)->equals($value);
            }

            if ($classMetadata->hasReference($previousAssociationProperty)) {
                $aggregation->lookup($previousAssociationProperty)->alias($previousAssociationProperty);
            } else { // hasEmbed
                $aggregation
                    ->unwind("$$previousAssociationProperty")
                    ->replaceRoot("$$previousAssociationProperty");

                return $aggregation;
            }
        }
        elseif ($classMetadata->isIdentifier($previousAssociationProperty)) {
            foreach ($normalizedIdentifiers as $key => $value) {
                $aggregation->match()->field($key)->equals($value);
            }

            return $aggregation;
        }
```
Here I've added `else` branch for embedded case.

**Comment by alanpoulain** [comment]
I'm not sure to understand your change, but if the tests are green and if you can provide one or more working Behat tests, I think it will be OK.

**Comment by CvekCoding** [comment]
@alanpoulain Mongo allows store relations of 2 types: embedded (store them in the same collection, the best for value object) and related documents (store them in the other collection, very similar to related tables). For APIP both are subresources. But to select them we have to use 2 different approaches:
* related documents are very simlar to usual RDBMS - we use `lookup` aggregation which is like `left join`
* to select embedded documents we have to use `unwind` and `replaceRoot` aggregations.

The second option is not supported now in APIP. At the same time  from my point of view the second option is most important for Mongo because otherwise there is no pros against usual RDBMS.

Regarding tests - sorry, but I' overwhelmed with work and cant deploy this feature with tests. All I can is just highlight problem and share my code with you.
