### ISSUE TITLE
custom identifiers not working

### ISSUE THREAD

**Issue by jav974** [api-platform/core#3554]
**API Platform version(s) affected**: 2.5.4

**Description**  
According to https://api-platform.com/docs/core/identifiers/ , we should be able to customize the identifier name and type, but i'm not able to do so.

**How to reproduce**  
`
```
/**
 * Class Taxon
 * @package ApiBundle\Entity
 * @ApiResource(
 *     attributes={
 *          "pagination_enabled"=false,
 *          "write"=false
 *     },
 *     collectionOperations={},
 *     itemOperations={
 *          "get"
 *     },
 *     graphql={
 *          "item_query"
 *     }
 * )
 */
class Taxon
{
    /**
     * @ApiProperty(identifier=true)
     * @var string
     */
    public $slug;

    /**
     * @ApiProperty(identifier=false)
     * @var int
     */
    public $id;
}
```
`

**Additional Context**  
This is what i get after a full cache clear and the above entity defined as is (i was expecting to see a slug instead of id in the url, same happens with graphql query)
![result](https://user-images.githubusercontent.com/2507131/81558006-38276880-938d-11ea-9d2b-f4b8b1cd0be9.png)

**Comment by jav974** [comment]
So i tried to follow this one after : https://api-platform.com/docs/core/operations/

```
/**
 * Class Taxon
 * @package ApiBundle\Entity
 * @ApiResource(
 *     attributes={
 *          "pagination_enabled"=false,
 *          "write"=false
 *     },
 *     collectionOperations={},
 *     itemOperations={
 *          "get"={
 *              "path"="/taxon/{slug}",
 *              "requirements"={"slug"="\S+"},
 *          }
 *     },
 *     graphql={
 *          "item_query"
 *     }
 * )
 */
class Taxon
{
    /**
     * @ApiProperty(identifier=true)
     * @var string
     */
    public $slug;

    /**
     * @ApiProperty(identifier=false)
     * @var int
     */
    public $id;
}
```

Now i get this :
![result2](https://user-images.githubusercontent.com/2507131/81559699-2e533480-9390-11ea-86d5-cfd46861a376.png)

and if i put something in the id field then submit, the slug part of url isn't replaced by the random id i put (the only editable field), not that i was expecting something else..

Is there something i'm doing wrong or is the doc somehow outdated or the spec is not compliant ? Thank you for your time.

**Comment by darthf1** [comment]
Same issue. Had this working previously. Don't know if this is a bug or something has changed in the config/setup.

**Comment by darthf1** [comment]
I think something broke in `v2.5.5`. 

My properties:
```php
    /**
     * @ApiProperty(identifier=false)
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private int $id;

    /**
     * @ApiProperty(identifier=true)
     * @ORM\Column(type="guid", unique=true)
     */
    private string $uuid;
```

`ID` is an `int`, my identifier `uuid` is a `string`.

When calling an operation, I get:
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "61608d27-2bf4-48a6-b137-39150cabbc9a"
```
Looking at the log, the WHERE statement in the SQL query is wrong. Its looking for the uuid in the ID column.

Rolling back to 2.5.4 fixes this issue for me.

**Comment by darthf1** [comment]
Issue is still there in `v2.5.6`.

Looks like it came from here: https://github.com/api-platform/core/compare/v2.5.4...v2.5.5#diff-fae38206cf0ed8fc1782a35395052166R221

**Comment by soyuka** [comment]
works on 2.6 alpha please test
