### ISSUE TITLE
Serializing null values depends on existance of patch itemOperation

### ISSUE THREAD

**Issue by SiebelsTim** [api-platform/core#3557]
**API Platform version(s) affected**: 2.5.0

**Description**  
The [SerializerContextBuilder](https://github.com/api-platform/core/blob/b47cceacb594f635f41831b2d53aa033d24fd86c/src/Serializer/SerializerContextBuilder.php#L105) determines to set `'skip_null_values'` to true based on the existance of `patch` in `itemOperations`. As a result, the `get` operation serializes null values when there is no `patch` listed, and are omitted when there is `patch` listed.
I don't think behaviour of the get operation should be affected by configuration of the patch operation.

**How to reproduce**  
Have an ApiResource with `get` and `patch`.
```
 * @ApiResource(
 *     itemOperations={"get", "patch"},
 *    )
```
Null values should be omitted.

Have an ApiResource with no `patch`.
```
 * @ApiResource(
 *     itemOperations={"get"},
 *    )
```
Null values should be visible.

**Possible Solution**  
Only set `skip_null_values` if we are using the patch route:
https://github.com/api-platform/core/blob/b47cceacb594f635f41831b2d53aa033d24fd86c/src/Serializer/SerializerContextBuilder.php#L105

**Additional Context**  
The SerializerContextBuilder does not overwrite existing settings. And I don't know why it does set them in the first place. There might be something deeper going on I don't see.

**Comment by dunglas** [comment]
This is mandatory for compliance with the JSON Merge Patch RFC on one hand, and backward compatibility on the other hand. skip_null_values will default to true in API Platform 3. In the meantime there are no better solution IMHO.

**Comment by SiebelsTim** [comment]
I understand that this is needed for backwards compat. I dont understand why the patch action should change the get action. JSON merge patch defines a data format and does not connect different REST routes as far as I know.
