### ISSUE TITLE
[RFC] PHP based configuration

### ISSUE THREAD

**Issue by Grafikart** [api-platform/core#3558]
**Description**  
I like using ApiPlatform but I find the configuration painfull to set up (lack of autocompletion, no reusability, no automation, break easily without usefull warning...). 
Being able to configure API platform using simple PHP class would solve these problems.

**Example**  

```php
function __invoke(ApiConfigurator $configurator) {
   // itemOperations
   $operations = array_map(function ($method) {
            return (new ItemOperation(Comment::class, $method))
                ->setNormalizationContext(['read:comment'], 'ReadComment')
                ->setSecurity($method === 'GET' ? CommentVoter::READ : CommentVoter::EDIT, 'object');
        ;
    }, ['GET','DELETE','PUT']);
    $operations[] = new ItemOperation(Comment::class, 'patch');

    // collection operation
    $operations[] = new CollectionOperation(Comment::class, 'get')
    $configurator->addOperations($operations);
}
```

This approach solve many problems I have with the configuration right now : 

- It's self documenting. It's easier to discover features reading the source code
- It's easier to automate some features using functions or custom classes.
- It's easier to detect problems when the configuration API changes using static analysis.

**Comment by alanpoulain** [comment]
Somehow related: https://github.com/symfony/symfony/pull/36778

**Comment by dunglas** [comment]
+1 on my side to have a PHP configuration. The metadata subsystem already allows to plug any source of configuration, so it should not be too hard. I agree with @alanpoulain, it must be consistent with what Symfony provides.

@Grafikart are you using PHPStorm? Is yes, the PHP Annotations plugin will enable auto completion for almost everything. As we provide XSDs, autocompletion should also work with XML config file (but TBH I’ve not tested).

**Comment by Grafikart** [comment]
@dunglas I'm using PHPStorm and it offers autocompletion for top level property but doesn't work for parameters for operations for instance. Also I couldn't figure out how to use constant for the security is_granted. 

```php
/**
*  itemOperations={
*.     "get"={???},
*      "post"={"normalization_context"=???}   
* }
**/
```

It's easy to mix up normalizationContext and normalization_context and with annotation you have no feedback for this kind of typo :(

**Comment by fabpot** [comment]
Closing as the referenced PR is about doing that in Symfony core. For API platform, you should probably move the discussion to their repo instead.

**Comment by weaverryan** [comment]
I would love this feature also. API Platform metadata is too powerful (and thus, complex) to fit nicely into annotations (and I normally LOVE annotations). I also just replied to a user on SymfonyCasts that loves API Platform, but dislikes the annotations.

Getting this BEST "syntax" of a config system is the problem. If someone has some time to work on it, I would be very happy with an "first try" imperfect system. Once we have that, I have no doubt that the community will start iterating on it to improve it. But we need that first version! 

Cheers!

**Comment by soyuka** [comment]
Its easier in 3.0 closing this for now
