### ISSUE TITLE
Subresource class name as a parameter

### ISSUE THREAD

**Issue by lchrusciel** [api-platform/core#3559]
**API Platform version(s) affected**: v2.5.4 (and probably all below)

Hello, Folks 👋 Thanks a lot for all the work you've put into this library.

**Description**  
In Sylius all entities have to be expressed in config files as Symfony parameters, in order to allow for easy overriding of classes. For regular `ApiResource` everything works fine thanks to AbstractExtractor and it's resolve method:
https://github.com/api-platform/core/blob/cfc05d1ce5e9e45898cb95ab71abf47e2d579da3/src/Metadata/Extractor/AbstractExtractor.php#L76-L126
We need the same functionality for ApiSubResource, where you have to declare `resourceClass` (at least in XML mappings), however, the class there is taken as it is: 
https://github.com/api-platform/core/blob/cfc05d1ce5e9e45898cb95ab71abf47e2d579da3/src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php#L144

**How to reproduce**  

Defining FQCN as a parameter and using it in XML (or YAML) configuration in the `resourceClass` option.

**Possible Solution**  

Resolving parameters from all configuration nodes.

**Additional Context**  
We've decorated ExtractorFactory:

https://github.com/Sylius/Sylius/blob/66dd2d0bb0b359acfce5fc22de9ba177db1c99ae/src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php#L31-L46

and register it only for our case(XML, but could be easily done for YAML as well) and duplicated parameter resolving logic there. Putting resolving logic itself to separate service may be a good decision as well. Ref. https://github.com/Sylius/Sylius/pull/11474

I would say, that using parameters as FQCN is not typical, however it may be useful to allow for parameters to be used in all XML/YAML mappings and it's arguments.

**Comment by alanpoulain** [comment]
Hello @lchrusciel. I think we have a recent PR to resolve this: https://github.com/api-platform/core/pull/3556. Could you take a look at it to see if it resolves your issue?

**Comment by lchrusciel** [comment]
Hello @alanpoulain,

I wish, I would spot this line earlier! That's exactly what would solve our issue. My bad, that I checked only issues to see if someone already noticed it.

**Comment by esserj** [comment]
Hi @lchrusciel I made the pull request for exactly that reason :D was building an api for the 1.8 version

in the meantime i've created a decorator to solve the issue:
decorating `api_platform.metadata.extractor.yaml` and `api_platform.metadata.extractor.xml`

```php
<?php

declare(strict_types=1);

namespace Inventis\SyliusWishlistPlugin\ApiPlatform\Extractor;

use ApiPlatform\Core\Metadata\Extractor\ExtractorInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use function is_numeric;
use function preg_match;
use function preg_replace_callback;
use function sprintf;
use function str_replace;

/**
 * https://github.com/api-platform/core/pull/3556
 *
 * this class can be removed when support has been added to api_platform
 */
final class SubResourceClassResolverExtractorDecorator implements ExtractorInterface
{
    /**
     * @var ExtractorInterface
     */
    private $extractor;
    /**
     * @var ContainerInterface
     */
    private $container;
    /**
     * @var array
     */
    private $collectedParameters = [];

    public function __construct(ExtractorInterface $extractor, ContainerInterface $container)
    {
        $this->extractor = $extractor;
        $this->container = $container;
    }

    /**
     * @inheritDoc
     */
    public function getResources(): array
    {
        $resources = $this->extractor->getResources();
        foreach ($resources as &$resource) {
            if ($resource['properties'] === null) {
                continue;
            }
            foreach ($resource['properties'] as &$propertyValues) {
                if (isset($propertyValues['subresource']['resourceClass'])) {
                    $propertyValues['subresource']['resourceClass'] = $this->resolve($propertyValues['subresource']['resourceClass']);
                }
            }
            unset($propertyValues); //unset ref
        }
        unset($resource); //unset ref

        return $resources;
    }

    private function resolve(string $value): string
    {
        $escapedValue = preg_replace_callback('/%%|%([^%\s]++)%/', function ($match) use ($value) {
            $parameter = $match[1];

            // skip %%
            if (!isset($parameter)) {
                return '%%';
            }

            if (preg_match('/^env\(\w+\)$/', $parameter)) {
                throw new \RuntimeException(sprintf('Using "%%%s%%" is not allowed in routing configuration.', $parameter));
            }

            if (\array_key_exists($parameter, $this->collectedParameters)) {
                return $this->collectedParameters[$parameter];
            }

            $resolved = $this->container->getParameter($parameter);

            if (\is_string($resolved) || is_numeric($resolved)) {
                $this->collectedParameters[$parameter] = $resolved;

                return (string) $resolved;
            }

            throw new\ RuntimeException(sprintf('The container parameter "%s", used in the resource configuration value "%s", must be a string or numeric, but it is of type %s.', $parameter, $value, \gettype($resolved)));
        }, $value);

        return str_replace('%%', '%', $escapedValue);
    }
}
```

**Comment by alanpoulain** [comment]
Fixed in master.
