### ISSUE TITLE
Possible optimization for relations?

### ISSUE THREAD

**Issue by wysow** [api-platform/core#358]
Hello,

Considering this extract on `/apidoc` url:

```
{
  @type: "hydra:SupportedProperty",
  hydra:property: {
    @id: "https://schema.org/isPartOf",
    @type: "rdf:Property",
    rdfs:label: "isPartOf",
    domain: "http://schema.org/SoftwareApplication",
    range: "#SoftwareApplication"
},
  hydra:title: "isPartOf",
  hydra:required: false,
  hydra:readable: true,
  hydra:writable: true,
  hydra:description: "Indicates a CreativeWork that this CreativeWork is (in some sense) part of."
}
```

A `SoftwareApplication` is `PartOf` 0 to many others `SoftwareApplication` so should the `@type` be something about some kind of collection or something similar? Or do I miss something here...?

**Comment by dunglas** [comment]
I'm not really sure of what you want to mean but `@type` of classes in the Hydra API doc are mostly part of the Hydra or RDF namespaces because these classes describe the structure of the API and not the returned data itself.

**Comment by wysow** [comment]
@dunglas this is more a discussion and maybe not really a "bug", I'm learning a lot about json-ld and hydra these days... My concern is using https://github.com/api-platform/admin auto discovery feature for relations, they are typed like `rdf:Property` and should maybe use another type... As I said maybe I'm saying _bullshit_...

**Comment by teohhanhui** [comment]
@wysow Refer to the Hydra spec: http://www.hydra-cg.com/spec/latest/core/#hydra:supportedProperty

**Comment by wysow** [comment]
@teohhanhui Not sure to get you on this one, there si also http://www.hydra-cg.com/spec/latest/core/#hydra:Collection so my question is : sounds like `Collection` is better to describe many-to-many relations no? But maybe I'm not understanding something here...

**Comment by teohhanhui** [comment]
@wysow You're confusing two very different things. `supportedProperty` is used on the `Class` (the type), whereas `Collection` is only relevant when returning resources (the data).

**Comment by wysow** [comment]
@teohhanhui but when I'm returning an entity data, isn't it a resource?

**Comment by teohhanhui** [comment]
@wysow Where does it show up in any of the resources? `/apidoc` is the API documentation, and also where you can find all the `Class`es defined.

**Comment by wysow** [comment]
@teohhanhui OK so what you mean is that there is no way to describe a many to many relation in the hydra format when using "auto discovery" feature?

**Comment by dunglas** [comment]
It can be done at runtime but not sure that it's possible at the configuration time.

@lanthaler, did you know a way to represent differentiate n-n and 1-n relations with Hydra?

**Comment by lanthaler** [comment]
I'm not familiar with the "auto discovery" feature being discussed here but

    "@id": "https://schema.org/isPartOf",
    "@type": "rdf:Property",

is definitely correct. The IRI `https://schema.org/isPartOf` defines a property. What you actually want to discuss is it's `range`. It defines the type the values of `isPartOf`. Having it's range set to `#SoftwareApplication` means that `isPartOf` directly points to resources of type `#SoftwareApplication`, not to collections that in turn point to `#SoftwareApplication` resources. Both are valid options.

@wysow if you are learning about JSON-LD and Hydra, I'd suggest (and invite) you to [join the Hydra W3C Community Group](http://www.hydra-cg.com/#community). We have a very friendly mailing list there where people are more than happy with answering such questions.

**Comment by wysow** [comment]
@lanthaler Thanks a lot for all this useful information, @dunglas with that in mind it sounds like it will be difficult to handle auto-discovery on relations right?
