### ISSUE TITLE
Problem with pagination in custom actions

### ISSUE THREAD

**Issue by ivanmunozruiz** [api-platform/core#3583]
I have a custom action my action don't use any subresource, I make a query with joins to get the paginator, if I have only one page all is fine but when there are more than one page I get this error

```
"hydra:description": "Notice: Undefined index: subresource_operation_name",
"file": PartialCollectionViewNormalizer.php",
"line": 85
```
If I change this line
`$isPaginatedWithCursor = $paginated && null !== $metadata && null !== $cursorPaginationAttribute = $metadata->getCollectionOperationAttribute($context['collection_operation_name'] ?? $context['subresource_operation_name'], 'pagination_via_cursor', null, true);`

for this
`
$isPaginatedWithCursor = $paginated && null !== $metadata && null !== $cursorPaginationAttribute = $metadata->getCollectionOperationAttribute($context['collection_operation_name'] ?? $context['subresource_operation_name'] ?? '', 'pagination_via_cursor', null, true);`

it works fine, I don't know if could be a bug or my problem

my custom action is an itemOperations

**Comment by lucasgranberg** [comment]
I have the same problem when creating a custom itemOperation. In stead of modifying the source I got it working by adding a empty subresource_operation_name:

``` yaml
        normalization_context:
          groups: ['read']
          subresource_operation_name: ''
```

**Comment by DennisdeBest** [comment]
Thanks @lucasgranberg This worked for me :+1:
