### ISSUE TITLE
Transation of schema

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#3592]
It was necessary to me to translate some schema fields, particularly `description` field.
If this is interesting for APIP it's quite easy - add `Translator` service to the builders (e.g. `TypeBuilder`) and use it here https://github.com/api-platform/core/blob/9ccf57835b3a4f0c54cbde1ef43af193bf689b34/src/GraphQl/Type/TypeBuilder.php#L101

Do you want me to create PR for this?

**Comment by alanpoulain** [comment]
Why not. It should work without it though.
