### ISSUE TITLE
Entity CLASS_CONSTRAINT validation called after flush (GraphQL)

### ISSUE THREAD

**Issue by danaki** [api-platform/core#3593]
**API Platform version(s) affected**: 2.5.4

My Batch entity defined as:
```
/**
 * @ORM\Entity(repositoryClass="App\Repository\BatchRepository")
 * @ORM\Table()
 * @ApiResource(
 *     attributes={"order"={"id": "DESC"}},
 *     graphql={
 *         "collection_query"={"normalization_context"={"groups"={"batch:query"}}},
 *         "item_query"={"normalization_context"={"groups"={"batch:query"}}},
 *         "create"={
 *             "mutation"=App\GraphQL\CreateBatchMutationResolver::class,
 *             "normalization_context"={"groups"={"batch:query"}},
 *             "denormalization_context"={"groups"={"batch:mutation"}}
 *         },
 *         "start"={
 *             "mutation"=App\GraphQL\BatchTransitionMutationResolver::class,
 *             "denormalization_context"={"groups"={"batch:transition"}}
 *         },
 *         "finish"={
 *             "mutation"=App\GraphQL\BatchTransitionMutationResolver::class,
 *             "denormalization_context"={"groups"={"batch:transition"}}
 *         },
 *         "pause"={
 *             "mutation"=App\GraphQL\BatchTransitionMutationResolver::class,
 *             "denormalization_context"={"groups"={"batch:transition"}}
 *         }
 *     }
 * )
 * @BatchTeamMembersAvailable
 */
class Batch
{
...
}
```

BatchTransitionMutationResolver:
```
class BatchTransitionMutationResolver implements MutationResolverInterface
{
    private $registry;
    private $batchRepository;

    public function __construct(Registry $registry, BatchRepository $batchRepository)
    {
        $this->registry = $registry;
        $this->batchRepository = $batchRepository;
    }

    public function __invoke($batch, array $context)
    {
        $transition = preg_replace('/Batch$/', '', $context['info']->fieldName);
        $workflow = $this->registry
            ->get($batch)
        ;

        $workflow->apply($batch, $transition);

        return $batch;
    }
}
```

The problem is that when mutation is called and workflow transition applied and commited, only then BatchTeamMembersAvailable class constraint is called and produces error (if applicable). This can be seen from logs:

```
Jun  3 02:10:26 |INFO | SERVER POST (200) /api/graphql host="127.0.0.1:8004" scheme="https"
Jun  3 03:10:25 |INFO | WORKFL Leaving "started" for subject of class "App\Entity\Batch" in workflow "batch_state".
Jun  3 03:10:25 |INFO | WORKFL Transition "finish" for subject of class "App\Entity\Batch" in workflow "batch_state".
Jun  3 03:10:25 |INFO | WORKFL Entering "finished" for subject of class "App\Entity\Batch" in workflow "batch_state".
Jun  3 03:10:25 |DEBUG| DOCTRI "START TRANSACTION"
Jun  3 03:10:25 |DEBUG| DOCTRI INSERT INTO batch_reservations (quantity, created, batch_id, created_by, team_id) VALUES (?, ?, ?, ?, ?) 1=-5 2="2020-06-02T23:10:25+00:00" 3=7 4=4 5=3
Jun  3 03:10:25 |DEBUG| DOCTRI SELECT SUM(b0_.quantity) AS sclr_0 FROM batch_reservations b0_ INNER JOIN batches b1_ ON b0_.batch_id = b1_.id WHERE b1_.production_plan_id = ? 0=7
Jun  3 03:10:25 |DEBUG| DOCTRI SELECT t0.id AS id_1, t0.priority AS priority_2, t0.item AS item_3, t0.planned_quantity AS planned_quantity_4, t0.produced_quantity AS produced_quantity_5, t0.remaining_quantity AS remaining_quantity_6, t0.reserved_quantity AS reserved_quantity_7, t0.offset_quantity AS offset_quantity_8, t0.quantity_in_pack AS quantity_in_pack_9, t0.notes AS notes_10, t0.order_code AS order_code_11, t0.week_number AS week_number_12, t0.color AS color_13, t0.grade AS grade_14, t0.ippc AS ippc_15, t0.logotype AS logotype_16, t0.shiftplan_id AS shiftplan_id_17 FROM production_plans t0 WHERE t0.id = ?
Jun  3 03:10:25 |DEBUG| DOCTRI INSERT INTO batch_logs (state_from, state_to, created, batch_id, created_by, team_id) VALUES (?, ?, ?, ?, ?, ?) 1="started" 2="finished" 3="2020-06-02T23:10:25+00:00" 4=7 5=4 6=3
Jun  3 03:10:25 |DEBUG| DOCTRI UPDATE production_plans SET reserved_quantity = ? WHERE id = ? 0=-35 1=7
Jun  3 03:10:25 |DEBUG| DOCTRI UPDATE batches SET state = ? WHERE id = ? 0="finished"
Jun  3 03:10:26 |DEBUG| DOCTRI "COMMIT"
Jun  3 03:10:26 |DEBUG| DOCTRI SELECT SUM(b0_.quantity) AS sclr_0 FROM batch_reservations b0_ INNER JOIN batches b1_ ON b0_.batch_id = b1_.id WHERE b1_.production_plan_id = ? 0=7
```

The last line starting with "SELECT" comes from the actual `BatchTeamMembersAvailable` validator while `COMMIT` is already happened and the state of the entity becomes inconsistent.

**Comment by joelisayas** [comment]
qsdqsd

Hey ,
i got a similar problem with a custom mutation 

    /**
     * @ORM\Entity(repositoryClass="App\Repository\SaleItemRepository")
     * @ORM\Table(name="fwc_sale_item")
     * @ORM\HasLifecycleCallbacks()
     * @ApiResource(
     *     attributes={"security"="is_granted('ROLE_USER')"},
     *     collectionOperations={
     *         "get",
     *         "post"={"security"="is_granted('ROLE_ADMIN')"}
     *     },
     *     itemOperations={
     *         "get"={"security"="is_granted('ROLE_ADMIN')"},
     *         "put"={"security"="is_granted('ROLE_ADMIN')"},
     *     },
     *     normalizationContext={"groups"={
     *          "sale_item:read",
     *          "timestampable:read"
     *     }, "swagger_definition_name"="Read"},
     *     denormalizationContext={"groups"={
     *          "sale_item:write"
     *     }, "swagger_definition_name"="Write"},
     *     graphql={
     *         "item_query"={"access_control"="is_granted('ROLE_USER')"},
     *         "collection_query"={"access_control"="is_granted('ROLE_USER')"},
     *         "delete"={"access_control"="is_granted('ROLE_ADMIN')"},
     *         "create"={"access_control"="is_granted('ROLE_ADMIN')"},
     *         "mutation"={
     *              "mutation"=SaleItemMutationResolver::class,
     *              "args"={
     *                  "id"={"type"="ID!", "description"="Id"},
     *                  "price"={"type"="Int!", "description"="Price"},
     *                  "oldQuantity"={"type"="Int!", "description"="Old Quantity"},
     *                  "newQuantity"={"type"="Int!", "description"="New Quantity"},
     *                  "stockId"={"type"="Int!", "description"="Stock Id"}
     *              },
     *              "write"=false,
     *              "deserialize"=false,
     *         },
     *     }
     * )
     */
	 class SaleItem{
	 ...



Using the Assert\Valid on this relation

    ...
    /**
         * @ORM\OneToOne(targetEntity=Stock::class, inversedBy="saleItem")
         * @ORM\JoinColumn(name="stock_id", referencedColumnName="id", nullable=true)
         * @Groups({"sale_item:write", "sale_item:read"})
         * @Assert\Valid
         */
        private $stock;
    ...
	
The Error exception is thrown after the flush (flush is made in the custom resolver)
