### ISSUE TITLE
Setting deprecated services properly

### ISSUE THREAD

**Issue by NicoHaase** [api-platform/core#3595]
**API Platform version(s) affected**: `api-platform/core` v2.5.6

**Description**  
Symfony 5.1 has been released last week, and it's deprecation handling has changed a bit. According to https://github.com/symfony/symfony/commit/f10413cf34c1cd5eb915a0f8814ac016b1567833, you need to use not only the `deprecated` tag in src/Bridge/Symfony/Bundle/Resources/config/api.xml, but also provide the package name and the version number in which the deprecation has been introduced.

**How to reproduce**  
Start a new project based on Symfony 5.1 and API Platform

**Possible Solution**  
Change each occurence of a `deprecated` tag to something like

```
<deprecated package="api-platform/core" version="2.5">The "%service_id%" service is deprecated since API Platform 2.5.</deprecated>
```

**Comment by alanpoulain** [comment]
Hello.
There is already a PR to fix this deprecation: https://github.com/api-platform/core/pull/3589.
