### ISSUE TITLE
OpenAPI specification invalid

### ISSUE THREAD

**Issue by tomasvanrijsse** [api-platform/core#3597]
**API Platform version(s) affected**: 2.5.4

**Description**  
I'm trying to export OpenApi spec v3.0 and use it with ApiSprout to mock my api.
The file generated by `console api:openapi:export` contains `:` in the component names which isn't valid according to OpenApi Spec 3

**How to reproduce**  
To export I'm using this command `docker-compose exec php bin/console api:openapi:export --spec-version=3 --output=swagger_docs.json`
To verify the results I've used `npx speccy lint swagger_docs.json`

The output says
```
Specification schema is invalid.
#/components/schemas/AddressOutput:jsonld
component name invalid
```
It seems like the :jsonld part is invalid because `:` isn't allowed as component name charachter in the OpenApi v3 spec.

**Comment by Swahjak** [comment]
Duplicate of https://github.com/api-platform/api-platform/issues/1493

**Comment by tomasvanrijsse** [comment]
Yes, seems like the exact same problem.
