### ISSUE TITLE
JSON-merge PATCH - 'skip_null_values' affects output representation on success

### ISSUE THREAD

**Issue by jesparic** [api-platform/core#3600]
**API Platform version(s) affected**: 1.2.2

**Description**  
When performing a JSON merge PATCH request, the file `src/Serializer/SerializerContextBuilder.php` (line 105) sets the serializer context to `skip_null_values`. I understand from https://github.com/api-platform/core/issues/3159 that this is done to support JSON-merge 'delete' functionality as defined by the specification. However, I'm assuming this option is intended to target serialization 'on the way in', whereas it also seems to affect the output response so that the success response includes only properties of the patched entity that are not null. This seems like undesirable behaviour to me, I would have expected the full resource representation in the success response (same as doing a GET)

**How to reproduce**  
Send a patch to a resource/entity (single property) while the entity also contains an exposed API property that has a null value. The null property will not be shown in the success response

**Possible Solution**  
Perhaps there is some way to reduce the scope of the 'skip_null_values' option so it only affects serialization on the input?

**Comment by dunglas** [comment]
This intended. It’s the only way to have proper and consistent support for JSON Merge patch. And it’s why this feature is not enabled by default (except in the recipe). This has already been discussed a lot and IMHO this is the best we can do for now. In API Platform 3, PATCH and this behavior will be the default, but for now we must ensure BC with API Platform versions released before the support of JSON Merge Patch.

**Comment by jesparic** [comment]
Thanks for getting back so quickly and thanks for the response. Sorry I missed the other discussions and for misconception here.. 

I see that I can easily decorate `ApiPlatform\Core\Serializer\SerializerContextBuilder` and use `$normalization === false` check to override the setting for de-normalization to get desired behaviour

The reason I am looking to go with the simpler JSON merge PATCH (even though it seems to be discouraged) is that SWAGGER UI has baked in support for making the requests. Whereas for the more robust (and slightly more complex) JSON PATCH, swagger won't auto-fill a request in the same way. I think it is also slightly less intuitive for the developer - What is your opinion on usage of JSON merge PATCH? Am I being naive in moving forward with it - am I setting myself up for problems further down the line?

PS, thanks for all your hard work on this amazing package!

**Comment by Tjeerd** [comment]
I just want to add that I ran into this issue today as well. After adding support for PATCH operations to certain entities my consumers were suddenly complaining about the changed behaviour of the GET operations (not returning null values anymore).

I do understand that this is intended, and conforms to the spec, as it should do. A remark in the documentation (with the keyword 'skip_null_values') might help though, as it took me quite a while to figure out this 'side-effect' of adding PATCH operations.

**Comment by dunglas** [comment]
You’re right it should be added to the docs (PE welcome). By the way it should also be possible to prevent this behavior (which makes the API non-conform to the JSON Merge Patch RFC) by explicitly setting ˋskip_null_values` to false in the resource configuration (normalization context).

**Comment by emancypage** [comment]
Hi, I have a 2.5.6 version of the core API Platform.
I have tried to set ˋskip_null_values` in resource configuration to false and its not working if PATCH is in resource.
Is it now correct behavior? That even if I set ˋskip_null_values`=false the PATCH response will not contain NULL values?

**Comment by soyuka** [comment]
refer to https://symfony.com/doc/current/components/serializer.html#skipping-null-values which can be set using a SerializerContextBuilder IIUC. Doc PR welcome.
