### ISSUE TITLE
PATCHing a subresource returns a "No route matches %s" error

### ISSUE THREAD

**Issue by leup** [api-platform/core#3609]
**API Platform version(s) affected**: v2.5.6 (and before)

**Description**  
When sending a PATCH request for a resource containing a subresource, the request fails with a "No route matches %s" error.
This is because the subresource is not found.

The culprit seems to be in the ItemNormalizer::updateObjectToPopulate.

https://github.com/api-platform/core/blob/master/src/Serializer/ItemNormalizer.php#L76

```php
$context[self::OBJECT_TO_POPULATE] = $this->iriConverter->getItemFromIri((string) $data['id'], $context + ['fetch_data' => true]);
```

It should be `data['@id']` instead of `$data['id']` when calling `getItemFromIri`

**How to reproduce**  

Given a `Resource` entity with a `subresource` field of type `Subresource` entity on a OneToOne relationship.

```php
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 */
class Resource
{
    /**
     * @ORM\OneToOne(targetEntity=Subresource::class, cascade={"persist", "remove"})
     */
     private $resource;

    public function getSubresource(): ?Subresource
    {
        return $this->subresource;
    }

    public function setSubresource(?Subresource $subresource): self
    {
        $this->subresource = $subresource;
        return $this;
    }
}
```

```php
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 */
class Subresource
{
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
     private $someField;

    public function getSomeField(): ?string
    {
        return $this->someField;
    }

    public function setSomeField(?string $someField): self
    {
        $this->someField = $someField;
        return $this;
    }
}
```

Trying to send a PATCH request which will update the subresource (given that you already have created the resource + subresource first :D)

```json
{
  "@id": "/api/resource/1",
  "subresource": {
     "@id": "/api/subresource/1",
     "someField": "someValue"
  }
}
```

**Possible Solution**  

It should be `data['@id']` instead of `$data['id']` when calling `getItemFromIri`.
Tried it in local and the error goes away.

I am not confident of any side effect this "fix" could have as I am not a expert of the internals of Api Platform.

edit: typo

**Comment by ntomka** [comment]
I have the same error. If I understands correctly in line https://github.com/api-platform/core/blob/master/src/Serializer/ItemNormalizer.php#L76 there should be `$data['@id']` instead of `$data['id']`, because `getItemFromIri()` accepts a proper IRI format, instead it gets a numeric ID.

#2632 seems somewhat related.

@dunglas If you are agreed with us on this issue I can open a PR for both (I see that #2632 still has no open PR).

**Comment by dunglas** [comment]
It looks good to me! PR welcome :)
@soyuka could you also take look? You know this part better than me!

**Comment by ntomka** [comment]
I've just tried the fix @Inari-Whitebear mentioned in #2632 and it also fixes this issue so it seem that the catch block not working properly too. But I guess we need both modifications to properly fix `ItemNormalizer::updateObjectToPopulate()` method.

**Comment by soyuka** [comment]
Write support in subresources should be added after reworking subresources with #3689 (needs ADR + #2706)

**Comment by vincentchalamon** [comment]
Subresources have been deprecated in 2.7 and removed in 3.0
