### ISSUE TITLE
Can the doctrine orm be kept out of v2.0

### ISSUE THREAD

**Issue by mvrhov** [api-platform/core#361]
I'm looking at the dependency graph of the upcoming 2.0.
And it seems that the ORM is now a required dependency. 
In the next project I'm trying to avoid an ORM, because:

* you soon find out that it hinders your development as you start to write most queries either in pure SQL and smashing your head by mapping dependencies by hand.
* you usually never ever change the db, so the DQL has no point

**Comment by dunglas** [comment]
It was a required dependency but it is not the case anymore in 1.1 (released soon) and 2.0.
In the meantime you can use 1.1@dev.

**Comment by mvrhov** [comment]
Oh. I was looking at trying to use 2.0 as it's a fresh project and a long-term one.

**Comment by dunglas** [comment]
Be careful, 2.0 is pretty stable now **but** it will still there are still sole major BC breaks to come.

**Comment by teohhanhui** [comment]
Actually, `doctrine/orm` is found under `require` section of composer.json in `master` branch...

**Comment by dunglas** [comment]
@teohhanhui good catch, should be changed.

**Comment by dunglas** [comment]
Fixed.
