### ISSUE TITLE
Multiline property description

### ISSUE THREAD

**Issue by AlexeyKosov** [api-platform/core#3612]
**API Platform version(s) affected**: 2.5.6

**Description**  
When I add a long multiline comment on a property of a resource, only the part of the text until a period goes to the property's description. So it turns out I can't use more than one sentence in a description.
Moreover, line breaks won't turn into <br> in Swagger so everything goes in one line.

**How to reproduce**  
Write a complex multi-line comment for a property of a resource and check it on Swagger.

**Comment by ecourtial** [comment]
I still see the issue on my side.
