### ISSUE TITLE
Attribute paginationType is camelCase and not documented

### ISSUE THREAD

**Issue by oleg-brizy** [api-platform/core#3613]
**API Platform version(s) affected**: 2.6.5

**Description**  

1. Getter is here

    https://github.com/api-platform/core/blob/dabbcb6cea02e09d941d25c21b6f421dc157b21a/src/DataProvider/Pagination.php#L218

2. Here is checked if it's `'cursor'`, else (any value) treated as `(page: Int)` pagination

    https://github.com/api-platform/core/blob/dabbcb6cea02e09d941d25c21b6f421dc157b21a/src/GraphQl/Type/FieldsBuilder.php#L328-L330

3. Not documented https://api-platform.com/docs/core/pagination/

**How to reproduce**  

```
/**
 * @ApiResource(
 *  graphql={
 *      "collection_query"
 *  },
 *  attributes={
 *     "paginationType"="any_value"
 *  }
 * )
```

**Possible Solution**  

Rename to `pagination_type` (snake_case, as all attributes), allow only two values `cursor` & `offset` (or whatever name you'll decide) and document.

**Comment by alanpoulain** [comment]
It is: https://api-platform.com/docs/master/core/graphql/#using-the-page-based-pagination.
You're right about the camel case. Could you provide a PR?

**Comment by oleg-brizy** [comment]
At the moment I don't have time to investigate the rename implications, if there are tests to fix/add.
