### ISSUE TITLE
Type error in AbstractrFilter

### ISSUE THREAD

**Issue by Kharalampidi** [api-platform/core#3631]
**API Platform version(s) affected**: 2.5.6

**Description**  
explode() expects parameter 2 to be string, int given
https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php#L151

**How to reproduce**  
You can see this error on this page - https://demo.api-platform.com/books?page=1&itemsPerPage=15&order[]=asc
Just send in query order[]=asc param and an error occurs when you use OrderFilter::class in this case.

**Comment by soyuka** [comment]
You should specify the property you want to filter on `order[name]=asc`. I'll improve the exception thrown.
