### ISSUE TITLE
Illegal string offset in AbstractItemNormalizer

### ISSUE THREAD

**Issue by abeal-hottomali** [api-platform/core#3633]
**API Platform version(s) affected**: 2.5.6
**Description**  
In `\ApiPlatform\Core\EventListener\SerializeListener::onKernelView`...

I see the lines (starting at 85):
```php
     $resources = new ResourceList();
     $context['resources'] = &$resources;
     // ... unrelated ...
     $resourcesToPush = new ResourceList();
     $context['resources_to_push'] = &$resourcesToPush;
```

Is there a reason those are assigned by reference?  I ask, because I'm running into a strange error.  I haven't yet been able to come up with a decent test case for you, but I can say that over the course of a request, the type of `$context['resources']` in this file is "object", but somewhere over the course of the request, by the time it reaches `\ApiPlatform\Core\Serializer\AbstractItemNormalizer::normalize`, specifically the lines 

```php
        if (isset($context['resources'])) {
            $context['resources'][$iri] = $iri;
        }
```

the type has changed to "string", with a value of "object(ApiPlatform\Core\Serializer\ResourceList)".

When I change this to no longer be assigned by reference, the problem appears to go away, and my test that was failing now passes.

I see from the repo that the lines in `\ApiPlatform\Core\EventListener\SerializeListener::onKernelView` haven't changed *that* recently, so perhaps my *fix* is really just obscuring an error elsewhere.  I found it unusual to assign an object by reference, though, so I wanted to check and make sure.

**Comment by abeal-hottomali** [comment]
An update on this:
I do see that `$context[AbstractObjectNormalizer::EXCLUDE_FROM_CACHE_KEY][] = 'resources';` in `\ApiPlatform\Core\EventListener\SerializeListener` **was** changed recently, in e20f9997b2b3c88fd1932c6d8600a4f4a394c6b2.  I've so far been unable to determine where exactly in code `'resources'` and `'resources_to_push'` are rehydrated from serialized cache, although they're cleared in `\ApiPlatform\Core\Serializer\CacheKeyTrait::getCacheKey`.

**Comment by abeal-hottomali** [comment]
I think I found at least what is triggering the problem, if not the source. 
 It has to do with a call to `\ApiPlatform\Core\Metadata\Resource\Factory\PhpDocResourceMetadataFactory::create`, which invokes `$this->docBlockFactory->create`.  It is this call that is somehow causing the problem:
    - `\phpDocumentor\Reflection\DocBlockFactory::parseTagBlock` -> `$this->tagFactory->create`.

It happens when the entity file contains `@see` statements.  I removed the following from my entity file:
```php
 *
 * @see CustomerOrderVoter
 *   Includes access control logic for this entity.
 * @see api/config/serializer/CustomerOrder.yaml
 *   Defines serialization groups.
 * @see api/config/api_platform/resources/CustomerOrder.yaml
 *   Defines Api-platform exposure.
```
And the problem went away.

**Comment by christiankohlsdorfer** [comment]
I had the same issue. After some research i was able to reproduce your problem. 

I was able to get rid of it locking `"phpdocumentor/reflection-docblock"` to `"4.*"` in composer.json and it was solved. It seems this somehow interacts with first time caching and the api-platform $context['resources'] causing these problems.

**Comment by dunglas** [comment]
This is probably related to a change in the Symfony Serializer. I'm on vacation until the end of August, but if nobody fix this before I'll take a look when I'll be back.

**Comment by soyuka** [comment]
maybe related issues: https://github.com/api-platform/core/issues/3565 https://github.com/api-platform/core/issues/3344

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
