### ISSUE TITLE
[Rest] NumericFilter and RangeFilter on the same property triggers an error

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#3634]
**API Platform version(s) affected**: 2.*

**Description**  

Creating both `NumericFilter` and `RangeFilter` on the same key triggers the following notice : 
```
At least one value is required, multiple values should be in "schemaVersion[]=firstvalue&schemaVersion[]=secondvalue" format
```

This issue is similar to #3483  but for REST and the error is not as blocking.

**Possible Solution**  

I would go for the same possible solution as @epourail : implementing `[eq]` and `[neq]` for the range filter, this way, the `NumericFilter` could be only used for "simple" search, and the `RangeFilter` superseed the `NumericFilter` for complex searches.

I can open a PR on that if you want to, and it may fix #3483 too.

**Comment by soyuka** [comment]
We'd end up having a complex numeric filter. There was a discussion about filters somewhere (can't find it) and IMO for advanced use case developers should create their own.
