### ISSUE TITLE
Negative Date Filter

### ISSUE THREAD

**Issue by timgregg** [api-platform/core#3637]
**Description**  
I have a requirement for an API to provide a collection of meters that haven't had a reading in the last 24 hours.

I was wondering if this is something that has already been solved or if anyone has ideas on the syntax etc

Is this something that could be an addition to the date filter or better off as a custom filter?

**Example**  

could we have something like:

`property[not_after]=value`
`property[not_before]=value`

**Comment by lucasgranberg** [comment]
have you tried the range filter?
`property[lt]=value`
`property[gt]=value`
https://api-platform.com/docs/core/filters/#range-filter

**Comment by timgregg** [comment]
Thanks, I am not sure that is going to work as a "Meter" has many "Readings" so If I had something like

`reading.date[lt]=20200101000000`

That would get me meters that had a reading before that date but wouldn't exclude meters that have a reading after that date. 

What I am looking for is to find meters that don't have a reading after a certain date (not greater than) but they may or may not have a reading before.

**Comment by soyuka** [comment]
For complex needs please create your own filter.

**Comment by timgregg** [comment]
> For complex needs please create your own filter.

Thanks, I can create my own filter. But was wondering 

1. Is something that others would want to see as part of the date filter?
2. What are peoples opinion on using the following the syntax

```
property[not_after]=value
property[not_before]=value
```
