### ISSUE TITLE
graphql_playground error !

### ISSUE THREAD

**Issue by OussamaELAMRANI** [api-platform/core#3638]
**API Platform version(s) affected**: 
```composer.json 
"api-platform/api-pack": "^1.1",
"webonyx/graphql-php": "^14.0"
```

**Description**  

When I want to run the GraphQL playground I get the error below:

"type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Attempted to load class \"Debug\" from namespace \"GraphQL\\Error\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Component\\ErrorHandler\\Debug\" or \"Doctrine\\Common\\Util\\Debug\"?",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/api/vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php",
      "line": 49,
      "args": []
    },

**Possible Solution**  

At line 14 in the Class __vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php__
```php

use GraphQL\Error\Debug;

# Replaced by
use GraphQL\Error\DebugFlag;

```

**Additional Context**  

![image](https://user-images.githubusercontent.com/16527183/87099026-a6c75c00-c240-11ea-8e27-177bc898defb.png)

**Comment by alanpoulain** [comment]
Fixed by https://github.com/api-platform/core/pull/3621.
You need to either:
- wait for a new version to be released
- use the dev version of the `2.5` branch
- downgrade webonyx/graphql-php to a previous version (`0.13`)
