### ISSUE TITLE
violations array is missing with GraphQL Response Error

### ISSUE THREAD

**Issue by sachingk** [api-platform/core#3639]
**API Platform version(s) affected**: 2.1

**Description**  
Say an API request is sent and it results in few validation errors. 

When JSON based API Request is being sent, we get validation message along with violations  array. 

![image](https://user-images.githubusercontent.com/1048263/87394332-454f1680-c5cd-11ea-8963-6dfdc9d15b61.png)

However when GraphQL Request is being sent, we get validation message but violations  array is absent 

![image](https://user-images.githubusercontent.com/1048263/87394419-64e63f00-c5cd-11ea-899d-5c98cd20f23e.png)

If any one have solved this issue , then please help me with it.

**Comment by alanpoulain** [comment]
Please use the `master` version of API Platform, the feature is already implemented (https://api-platform.com/docs/master/core/graphql/#exception-and-error-formatting).
