### ISSUE TITLE
RFC: SearchFilter - decouple single/multiple values from association cardinality

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#365]
Given a `Tour` entity with a single-valued (to-one) association named `type` (`TourType`):

Currently we can do:
`/tours?type=/tour_types/1`
but should this be supported as well?
`/tours?type[]=/tour_types/1&type[]=/tour_types/2`

Conversely, given that the `Tour` entity also has a multi-valued (to-many) association named `themes` (`TourTheme`):

Currently we can do:
`/tours?themes[]=/tour_themes/1&themes[]=/tour_themes/2`
but should this be supported as well?
`/tours?themes=/tour_themes/1`

**Comment by teohhanhui** [comment]
It should be mentioned that part of #188 was (unintentionally) introduced into `1.x` by #337

**Comment by bwegrzyn** [comment]
How about supporting multiple values on a property of an association?

I have a use case where Users have one role, but roles are classified as different types. I'd want to be able to get all users with roles that are type 1 and 2 without having to issue 2 separate requests.

`/users?role.type[]=admin&role.type[]=staff`

**Comment by sroze** [comment]
This kind of use cases starts to be too complicated (at least dedicated)
IMO. I would recommend you to create a dedicated API endpoint for that.

**Comment by bwegrzyn** [comment]
I see your point, but the bundle already supports filtering on a single property like that, so it makes sense to support multiple properties like that for feature completion.

Creating a dedicated endpoint for every case where we might need filtering like this is a lot of extra work, not to mention making it as flexible as every other end point provided by the bundle. It's a work around for now for sure.

I'm hoping that eventually the bundle supports these kind of filtering options.

**Comment by teohhanhui** [comment]
@bwegrzyn I don't think custom endpoints is the answer. That's the heavyweight solution in a RESTful API design - because they'd necessarily need to be modelled as resource subcollections (or you'd be shooting yourself in the foot and defeating the purpose of using this bundle, or that of having a web API-powered app in the first place).

**Comment by teohhanhui** [comment]
Personally, I've come to accept that many small requests is not a bad thing. But of course I can't speak on the specifics of your use case.

**Comment by bwegrzyn** [comment]
@teohhanhui I don't think custom endpoints are the answer either, but it's the only solution right now apart from doing several requests. 

What if I need to get users for several role types? Do I make another custom endpoint, or do I have a request for each type. What if I want to paginate users from these several roles? You can't paginate data from several requests likes this without some weird solution.

I'm not opposed to making several requests for different datasets, but this is several requests for a single filtered dataset. Why make the extra requests for something that should be (IMO, at least) handled by the bundle?

**Comment by dunglas** [comment]
I'm not against adding such feature to the existing filter.
Btw, you can still add this feature with a custom filter, there is no need for a custom endpoint here.

**Comment by bwegrzyn** [comment]
Thanks for the tip @dunglas. I haven't had a chance to play with custom filters yet, but I'll give it a try.

I'd still like to see this kind of feature added to the bundle.
