### ISSUE TITLE
SearchFilter by IRI of association when association use difference API identifier field will cause ORM exception

### ISSUE THREAD

**Issue by vuongxuongminh** [api-platform/core#3658]
**API Platform version(s) affected**: 2.5.6

**Description**  
Following document https://api-platform.com/docs/core/identifiers/#changing-identifier-in-a-doctrine-entity I changed identifier of my Doctrine entity class to difference field. It's association field need to apply search filter in another entity class  with exact strategy. When search with IRI value will cause ORM exception `missing identifier field`.

The problem come from [SearchFilterTrait.php#L123](https://github.com/api-platform/core/blob/v2.5.6/src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php#L123) because `fetch_data` set to false and my api resource class use difference identifier when item data provider get reference [ItemDataProvider.php#L83](https://github.com/api-platform/core/blob/v2.5.6/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L83) the identifier field of Doctrine is missing.
 
**How to reproduce**  

Create 2 entities Category and Item and change identifier of Category to `code` field. Add `SearchFilter` with `category` field to Item. Example:

```php
/**
 * @ApiResource()
 * @ORM\Entity()
 */
class Category
{
    /**
     * @ORM\Id()
     * @ApiProperty(identifier=false)
     */
    public $id;

    /**
     * @var string
     * @ApiProperty(identifier=true)
     */
    public $code;
}

/**
 * @ApiResource()
 * @ApiFilter(SearchFilter::class, properties={"category"="exact"})
 * @ORM\Entity()
 */
class Item
{
    /**
     * @ORM\Id()
     */
    public $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     */
    public $category;
}
```

**Possible Solution**  

At line [ItemDataProvider.php#L82](https://github.com/api-platform/core/blob/v2.5.6/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L82) add condition check Doctrine identifier field exist before call `getReference` if not we need to fetch data.

**Comment by soyuka** [comment]
SearchFilter is known to be broken with custom identifiers. Please use a custom filter and avoid using `     * @ApiProperty(identifier=false)` on the field marked as an identifier `     * @ORM\Id()` these won't work together.
