### ISSUE TITLE
HttpException message missing for 5XX errors

### ISSUE THREAD

**Issue by lazka** [api-platform/core#3659]
**API Platform version(s) affected**: v2.5.6

**Description**  

I'm trying to return a 502 HTTP error with an error message.

**How to reproduce**  

```php
<?php
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

...
throw new HttpException(Response::HTTP_BAD_GATEWAY, "My Message");
...
```

I get back this:

```json
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Bad Gateway"
}
```

I'd have expected `My Message` to be in the response.

**Comment by soyuka** [comment]
This must have to do with how exceptions are serialized see ExceptionAction. I guess you could change this? Not sure that we wanted to add the message to the response.

**Comment by lazka** [comment]
The code in api-platform removing the error message is here: https://github.com/api-platform/core/blob/22ce6399180f9408f19b0b3c857317d2ddd7ea9d/src/Problem/Serializer/ErrorNormalizerTrait.php#L32

I've worked this around now by adding a HTTPException subclass and a custom serializer which adds back the message for this exception type only (to prevent internals leaking in case something depends on the current behavior somehow):

https://gist.github.com/lazka/b20ebfe6bd5045d34a14bac9bf249808

For some context: I'm calling lots external services which can fail, so I want to relay which background service failed somehow to the client, even in production, so it's easier to debug. If someone has a better idea, feedback welcome :)
