### ISSUE TITLE
DateFilter not working for custom date Type.

### ISSUE THREAD

**Issue by grummbeer** [api-platform/core#3660]
**API Platform version(s) affected**: latest

**Description**  

DateFilter fails on custom date Type.

**How to reproduce**  

Create a custom DBType that deals with date but name is not one of defined in [DOCTRINE_DATE_TYPES](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/DateFilter.php#L33)

 Copy of https://github.com/doctrine/dbal/blob/2.10.x/lib/Doctrine/DBAL/Types/DateTimeType.php
```php
class DateTimeMicroType extends Type
{
    private const FORMAT = 'Y-m-d H:i:s.u';
    private const NAME = 'datetime_micro';

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return 'DATETIME(6)';
    }
```
The Filter fails: `http://host/api/resource.json?time[after]=2020-07-30T10:00:00.500000`

Is there a way to get this working without a custom Operation?

**possible solution**

Just a shot in the dark.

What about checking the converted value/process instead matching a fixed Type in https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Common/Filter/DateFilterTrait.php#L62

currently checks the Type
```php
protected function isDateField(string $property, string $resourceClass): bool 
{
    return isset(self::DOCTRINE_DATE_TYPES[(string) $this->getDoctrineFieldType($property, $resourceClass)]);
}
```
checking the convert process

```php
protected function isDateField(string $property, string $resourceClass): bool
{
    try{
        $this->getManagerRegistry()->getConnection()->convertToPHPValue(new \DateTime(), $this->getDoctrineFieldType($property, $resourceClass));
        return true;
    } catch (\Exception $e) {
        // could not converted, no date possible? really?
        return false;
    }
}
```
I am unsure what problems could appear with this approach, or how or what problems in generally are there. So just an Idea.

With this changes the DateFilter is working as expected, just one note about the returned value

``` 
GET http://host/api/resource.json?time[after]=2020-07-30T10:00:00.500000

{
   "time": "2020-07-30T10:00:00+02:00"
}
```
mircroseconds missing in outputformat.  Is the outputformat configurable to `DateTimeInterface::RFC3339_EXTENDED = "Y-m-d\TH:i:s.vP"`?

And also the docs missing a clearifing note at https://api-platform.com/docs/core/filters/#date-filter

> The value can take any date format supported by the \DateTime constructor.

… and type is one of … https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/DateFilter.php#L33 

- date
- date_immutable
- time
- time_immutable
- datetime
- datetime_immutable
- datetimetz
- datetimetz_immutable
 
Thanks and have a nice day.

**Comment by soyuka** [comment]
I'd suggest to write your own filter or extend ours. 

The output format is linked to how symfony normalizes dates you should be able to change it (see https://symfony.com/blog/new-in-symfony-3-1-datetime-normalizer). 

About the documentation feel free to open a PR on api-platform/docs.
