### ISSUE TITLE
Authentication lost, because of PUT request on user resource [PHP 7.4, Symfony 5.1]

### ISSUE THREAD

**Issue by RomanZberg** [api-platform/core#3661]
**API Platform version(s) affected**: 2.5.6

**Description**  
Whenever I make a PUT Request to update the username of the current logged in user to a username of a existing user I get a response with a 400 status code, caused by a validation error.

Nothing is wrong with that, because I have added a UniqueEntity annotation to the userentity, which causes this error.

Wrong is, that when I submit the same PUT request again, I get a 401 status code.
The first PUT request must have logged me out in some way. I get a 401 status code, because only fully authenticated users can use this route.

Instead of being logged out I should again get a 400 error.
**Note**: This only happens if the entity implements Symfony's Userinterface.

Im using API Platform with PHP 7.4 and Symfony 5.1

**How to reproduce**  

**My project:** [api-php.zip](https://github.com/api-platform/api-platform/files/4981329/api-php.zip)

1. Download my project
2. Install dependencys
    ```$ composer install```
3. Edit .env to adjust the database credentials
4. Create database
    ```$ php bin/console doctrine:database.create```
5. Execute Migrations
    ```$ php bin/console doctrine:migrations:migrate```
5. Load Fixtures
    ```$ php bin/console doctrine:fixtures:load```
6. Through the Swagger UI, use the login route to authenticate using the following credentials:
    **username:** user1
    **password:** 123456
    Remember the id returned from the login response (property user)
7. Submit a PUT request on the user resource with the userid from the login as request parameter and the following body:
   ```{"username": "user2"}```
8. A request with the status code 400 is retured. Submit the same request again.
9. A 401 status code is returned and you have been logged out

**Comment by soyuka** [comment]
what is your authentication strategy ? as Api Platform doesn't have any authentication system I guess that it has to do with your code.
