### ISSUE TITLE
Mercure Publish fails if expression returns bool false

### ISSUE THREAD

**Issue by dennobaby** [api-platform/core#3681]
**API Platform version(s) affected**: 2.5

**Description**  
Mercure Publish fails if an expression is used which could return false:
`The value of the "mercure" attribute of the "MyClass" resource class must be a boolean, an array of options or an expression 
returning this array, "boolean" given.'`

**How to reproduce**  
```
/**
  * @ApiResource(
  *    mercure="object.mercure()"
  * )
  */
class MyClass
{
[...]
    private function mercure(){
        return false;
    }
}
```

**Possible Solution**  
Maybe just move the if-clause in https://github.com/api-platform/core/blob/38d69e6fdeaa6d6d32d43b7467454acb17d11315/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php#L157 after the expression-evaluation in https://github.com/api-platform/core/blob/38d69e6fdeaa6d6d32d43b7467454acb17d11315/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php#L161

**Comment by stephanvierkant** [comment]
I'm having the same problem. I'll try to create a PR.
