### ISSUE TITLE
ItemNormalizer duplicate collection identifiers

### ISSUE THREAD

**Issue by Korbeil** [api-platform/core#3682]
**API Platform version(s) affected**: 2.5.4

**Description**  
We have some requests on our API that could be same as following:
```bash
curl -XPUT -H 'Accept: */*' -H 'Content-Type: application/json' -d '{"bars": ["80250f45-23af-4c33-a08f-68c0ca9ff163", "00efc472-e71d-4745-849d-08c9b0008bd3", "916ca812-c71d-4dad-8e16-793d29c90954", "916ca812-c71d-4dad-8e16-793d29c90954"]}' 'http://api/foo/b1af0fd0-fdaa-43bb-b315-d8b3e43f7435'
```

Here we have a "foo" entity where we want to update the "bars" property which is a collection or "bar".
To do so, we give a list of UUIDs to reference the "bar" we want in this collection.
Here the issue is that I have 2 UUIDs that are the same and this produce API Platform to try to create the duplicate in database (which already exists so it doesn't work and crash with a 500 status code).

**How to reproduce**  
As shown before, you need an entity with a collection of another entity and make a PUT request using references to update this collection. Exactly like the curl request I used before.

**Possible Solution**  
I tried to make a decorator over `api_platform.serializer.normalizer.item` to avoid duplicates in collection of id references. But I think this should fit in API Platform core code (and not in mine). What you think about it ?

**Additional Context**  
N/A

**Comment by alanpoulain** [comment]
It seems an edge case to me, but if the code to fix it is simple, I'm personally OK with it.

**Comment by soyuka** [comment]
Wasn't this fixed? If not please provide a reproduction behat test case.
