### ISSUE TITLE
Using Symfony\Bridge\Doctrine\ManagerRegistry instead of Doctrine\Common\Persistence\ManagerRegistry

### ISSUE THREAD

**Issue by MimaTomis** [api-platform/core#3683]
**API Platform version(s) affected**: 2.5.6

**Description**  

When I try to make a request to the server, an error occurs:
```stacktrace
Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given
```

The problem is that starting with version 2.9 of the **doctrine/common** library, the following code has been removed:
https://github.com/doctrine/common/tree/2.8/lib/Doctrine/Common/Persistence

https://github.com/api-platform/core/blob/38d69e6fdeaa6d6d32d43b7467454acb17d11315/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml#L113-L118

**How to reproduce**  

Add the following dependencies to composer.json:

```json
{
  "require": {
    "doctrine/orm": "^2.7"
  }
}
```

**Possible Solution**  

Use the following class from [Symfony\Bridge\Doctrine\ManagerRegistry](https://github.com/symfony/doctrine-bridge/blob/master/ManagerRegistry.php) as argument type instead of `Doctrine\Common\Persistence\ManagerRegistry`

**Comment by alanpoulain** [comment]
A release to fix it in the Doctrine bundle has been made 3 hours ago: https://github.com/doctrine/DoctrineBundle/releases/tag/2.1.2.

**Comment by MimaTomis** [comment]
> A release to fix it in the Doctrine bundle has been made 3 hours ago: https://github.com/doctrine/DoctrineBundle/releases/tag/2.1.2.

The problem is not with the configuration. From the error in the issue description, you can see that the correct service comes to the constructor. 
```
Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given
```

The problem is that the type hints in the code refer to a class that doesn't exist.

**Comment by alanpoulain** [comment]
Please see the fix in the Doctrine bundle, the typehint is OK: https://github.com/doctrine/DoctrineBundle/pull/1202/files.

**Comment by MimaTomis** [comment]
I see. 

This `<service id="Doctrine\Common\Persistence\ManagerRegistry" alias="doctrine" public="false" />` is alias to `Doctrine\Bundle\DoctrineBundle\Registry`. This does not solve the problem with the missing class referenced by the code.

i updated the library version and and cleared the cache.
doctrine/doctrine-bundle: 2.1.2

The error is still present.

**Comment by alanpoulain** [comment]
Seems this interface needs to be implemented instead: https://github.com/doctrine/persistence/blob/2.0.x/lib/Doctrine/Persistence/ManagerRegistry.php
It will need to be changed in API Platform and a new release.
@dunglas could you take a look at it?

**Comment by weaverryan** [comment]
This is happening all over our part of the Internet. Here is the fix in SensioFrameworkExtraBundle: https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/691 and the fix for MakerBundle https://github.com/symfony/maker-bundle/pull/667

As I understand it, DoctrineBundle 2.1.1 now allows doctrine/common 3.0, which no longer comes with the old, legacy class alias support for `Doctrine\Common\Persistence\ManagerRegistry`. So it's not that a service changed or an alias become unavailable, the change is on a deeper, PHP level: DoctrineBundle now *allows* a version of other dependencies that no longer come with the legacy class aliases. My understand may be incomplete, this stuff makes my head spin a bit :p.

**Comment by weaverryan** [comment]
See #3684

**Comment by BenPilliez** [comment]
So how can we install API platform please?

**Comment by treeleaf** [comment]
@BenPilliez I was able to install it by adding, in the project composer.json:
"conflict": {
  ...
  "doctrine/common": ">=3.0",
   "doctrine/persistence": "<1.3"
}

Like suggested in ticket #3684 
I had to remove composer.lock and do composer install again

**Comment by BenPilliez** [comment]
OK thanks you 😊. I will test this tomorrow

**Comment by nicolas-canfrere** [comment]
thanks @treeleaf !

**Comment by BenPilliez** [comment]
Thank's a lot @treeleaf :D

**Comment by MimaTomis** [comment]
Thanks everybody!
For me, the most acceptable way is:

1. Adding to composer.json
    ```json
    "conflict": {
        "doctrine/common": ">=3.0",
        "doctrine/persistence": "<1.3"
    }
    ```
2. Execute 
    ```bash
    composer remove doctrine/*
    ```
3. Execute 
    ```bash
    composer require "doctrine/orm:^2.7"
    ```

**Comment by afolabiolayinka** [comment]
Replace Doctrine\Common\Persistence\ManagerRegistry with Doctrine\Persistence\ManagerRegistry

**Comment by gotgot1995** [comment]
Hi there :wave:

I'm having the same error (only two years later) but with a more recent version `2.7.5` of api-platform.

Here is my `composer.json` file:
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/core": "^2.7",
        "doctrine/annotations": "^1.13",
        "doctrine/doctrine-bundle": "^2.7",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.13",
        "nelmio/cors-bundle": "^2.2",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.15",
        "sensio/framework-extra-bundle": "^6.2",
        "symfony/asset": "5.4.*",
        "symfony/console": "5.4.*",
        "symfony/dotenv": "5.4.*",
        "symfony/expression-language": "5.4.*",
        "symfony/flex": "^1.17|^2",
        "symfony/framework-bundle": "5.4.*",
        "symfony/property-access": "5.4.*",
        "symfony/property-info": "5.4.*",
        "symfony/proxy-manager-bridge": "5.4.*",
        "symfony/runtime": "5.4.*",
        "symfony/security-bundle": "5.4.*",
        "symfony/serializer": "5.4.*",
        "symfony/twig-bundle": "5.4.*",
        "symfony/validator": "5.4.*",
        "symfony/yaml": "5.4.*"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.4.*"
        }
    },
    "require-dev": {
        "symfony/maker-bundle": "^1.43"
    }
}
```

And here is the error I'm getting when typing `bin/console make:entity --api-resource`:
```
[critical] Error thrown while running command "make:entity --api-resource". Message: "[Creation Error] An error occurred while instantiating the annotation @ApiResource declared on class App\Entity\TestProject: "Argument 1 passed to ApiPlatform\Metadata\ApiResource::__construct() must be of the type string or null, array given, called in ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 1474"."
```

Any help would be most appreciated. :pray:

**Comment by carlosmay1975** [comment]
> Hi there 👋
> 
> I'm having the same error (only two years later) but with a more recent version `2.7.5` of api-platform.
> 
> Here is my `composer.json` file:
> 
> ```
> {
>     "type": "project",
>     "license": "proprietary",
>     "minimum-stability": "stable",
>     "prefer-stable": true,
>     "require": {
>         "php": ">=7.2.5",
>         "ext-ctype": "*",
>         "ext-iconv": "*",
>         "api-platform/core": "^2.7",
>         "doctrine/annotations": "^1.13",
>         "doctrine/doctrine-bundle": "^2.7",
>         "doctrine/doctrine-migrations-bundle": "^3.2",
>         "doctrine/orm": "^2.13",
>         "nelmio/cors-bundle": "^2.2",
>         "phpdocumentor/reflection-docblock": "^5.3",
>         "phpstan/phpdoc-parser": "^1.15",
>         "sensio/framework-extra-bundle": "^6.2",
>         "symfony/asset": "5.4.*",
>         "symfony/console": "5.4.*",
>         "symfony/dotenv": "5.4.*",
>         "symfony/expression-language": "5.4.*",
>         "symfony/flex": "^1.17|^2",
>         "symfony/framework-bundle": "5.4.*",
>         "symfony/property-access": "5.4.*",
>         "symfony/property-info": "5.4.*",
>         "symfony/proxy-manager-bridge": "5.4.*",
>         "symfony/runtime": "5.4.*",
>         "symfony/security-bundle": "5.4.*",
>         "symfony/serializer": "5.4.*",
>         "symfony/twig-bundle": "5.4.*",
>         "symfony/validator": "5.4.*",
>         "symfony/yaml": "5.4.*"
>     },
>     "config": {
>         "allow-plugins": {
>             "composer/package-versions-deprecated": true,
>             "symfony/flex": true,
>             "symfony/runtime": true
>         },
>         "optimize-autoloader": true,
>         "preferred-install": {
>             "*": "dist"
>         },
>         "sort-packages": true
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "src/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "App\\Tests\\": "tests/"
>         }
>     },
>     "replace": {
>         "symfony/polyfill-ctype": "*",
>         "symfony/polyfill-iconv": "*",
>         "symfony/polyfill-php72": "*"
>     },
>     "scripts": {
>         "auto-scripts": {
>             "cache:clear": "symfony-cmd",
>             "assets:install %PUBLIC_DIR%": "symfony-cmd"
>         },
>         "post-install-cmd": [
>             "@auto-scripts"
>         ],
>         "post-update-cmd": [
>             "@auto-scripts"
>         ]
>     },
>     "conflict": {
>         "symfony/symfony": "*"
>     },
>     "extra": {
>         "symfony": {
>             "allow-contrib": false,
>             "require": "5.4.*"
>         }
>     },
>     "require-dev": {
>         "symfony/maker-bundle": "^1.43"
>     }
> }
> ```
> 
> And here is the error I'm getting when typing `bin/console make:entity --api-resource`:
> 
> ```
> [critical] Error thrown while running command "make:entity --api-resource". Message: "[Creation Error] An error occurred while instantiating the annotation @ApiResource declared on class App\Entity\TestProject: "Argument 1 passed to ApiPlatform\Metadata\ApiResource::__construct() must be of the type string or null, array given, called in ./vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 1474"."
> ```
> 
> Any help would be most appreciated. 🙏

Hello, were you able to solve this issue?
