### ISSUE TITLE
DTO validation before transformation

### ISSUE THREAD

**Issue by root-aza** [api-platform/core#3710]
Hi. How to do the validation dto before transformation?  Only the entity is in the post of the event denormalization.

**Comment by norkunas** [comment]
Hello,

You can inject the `ApiPlatform\Core\Validator\ValidatorInterface` to your data transformer and then call validator before transformation.

**Comment by root-aza** [comment]
@norkunas **After deserialization dto.**  Your solution doesn't fit.  Decision: https://gist.github.com/root-aza/bab970470418dc2bc563b80ee301cc6e

**Comment by norkunas** [comment]
I dont understand. You transform the DTO to entity,so the dto is already deserialized..
