### ISSUE TITLE
Symfony Uid support for Json schema

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#3714]
**Description**  

Since Symfony 5.1 the Uid component was introduced and when relying only on it instead of ramsey/uuid,
wrong schema is generated, because it detects it as an object instead of string:uuid.
There is a pull request to symfony for Uid normalizer https://github.com/symfony/symfony/pull/36406/files,
but there are two missing pieces:
 - symfony/uid identifier normalizer;
 - json schema to support uuid/ulid;

I can open separate PR's for both of these, but we should decide if the second point is a bugfix or a new feature?

**Example**  
none

**Comment by soyuka** [comment]
You can add both to a single PR as these need symfony 5.1 anyway, thanks @norkunas !

**Comment by norkunas** [comment]
Which base branch to choose? :slightly_smiling_face:
