### ISSUE TITLE
hydra:view is not showing when using Custom Collection Data Provider

### ISSUE THREAD

**Issue by benborla** [api-platform/core#3721]
**API Platform version(s) affected**: 
- api-platform/core v2.5.7
- api-platform/api-pack v1.3.0

**Description**  
I need help with this issue, currently, I'm working on adding a custom collection data provider for my User entity, this entity works fine if I don't use UserCollectionDataProvider, I can see the *hydra:view* property, but when I use this UserCollectionDataProvider it's not visible please refer to response below:

Has **UserCollectionDataProvider**:

```json
{
    "@context": "/api/contexts/User",
    "@id": "/api/users",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/api/users/1",
            "@type": "User",
            "id": 1,
            "email": "benborla@icloud.com",
            "roles": [
                "ROLE_USER"
            ],
           ...
        },
    ],
    "hydra:totalItems": 20,
    "hydra:search": {
        "@type": "hydra:IriTemplate",
        "hydra:template": "/api/users{?createdAt[before],createdAt[strictly_before],createdAt[after],createdAt[strictly_after],updatedAt[before],updatedAt[strictly_before],updatedAt[after],updatedAt[strictly_after],id,id[],email,firstName,middleName,lastName,accountType,accountType[]}",
        "hydra:variableRepresentation": "BasicRepresentation",
        "hydra:mapping": [
            {
                "@type": "IriTemplateMapping",
                "variable": "createdAt[before]",
                "property": "createdAt",
                "required": false
            },
           ...
        ]
    }
}
```

**No UserCollectionDataProvider**
```json
    "hydra:view": {
        "@id": "/api/users?page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/api/users?page=1",
        "hydra:last": "/api/users?page=6",
        "hydra:next": "/api/users?page=2"
    },
```

**How to reproduce**  
Here's my UserCollectionDataProvider code
```php
<?php
// src/DataProvider/UserCollectionDataProvider

declare(strict_types=1);

namespace App\DataProvider;

use App\Entity\User;
use App\Repository\UserRepository;
use App\DataProvider\AbstractRoleCollectionCheckpoint;
use Doctrine\Common\Persistence\ManagerRegistry;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGenerator;

class UserCollectionDataProvider
{
    private $repository;
    private $collectionExtensions;

    public function __construct(
        UserRepository $repository,
        ManagerRegistry $managerRegistry,
        iterable $collectionExtensions
    ) {
        $this->repository = $repository;
        $this->managerRegistry = $managerRegistry;
        $this->collectionExtensions = $collectionExtensions;
    }

    public function supports(
        string $resourceClass,
        string $operationName = null,
        array $context = []
    ): bool {
        return User::class === $resourceClass;
    }

    public function getCollection(
        string $resourceClass,
        string $operationName = null,
        array $context = []
    ) {
        if (!$this->supports($resourceClass, $operationName, $context)) {
          return;
        }

        $manager = $this->managerRegistry->getManagerForClass($resourceClass);
        $repository = $manager->getRepository($resourceClass);
        $queryBuilder = $repository->createQueryBuilder('e');
        $queryNameGenerator = new QueryNameGenerator();

        foreach ($this->collectionExtensions as $extension) {
            $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);

            if ($extension instanceof QueryResultCollectionExtensionInterface && $extension->supportsResult($resourceClass, $operationName, $context)) {
                return $extension->getResult($queryBuilder, $resourceClass, $operationName, $context);
            }
        }

        return $queryBuilder->getQuery()->getResult();
    }
}
```

My configuration:
```yaml
# config/services.yaml
services:
    App\DataProvider\UserCollectionDataProvider:
      tags: [ { name: 'api_platform.collection_data_provider', priority: 1 } ]
      # Autoconfiguration must be disabled to set a custom priority
      autoconfigure: false
      arguments:
          $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
```

Thank you.

**Comment by rugolinifr** [comment]
Use **XDebug** and make sure that the `PaginationExtension` extension is added to your query builder within the `foreach` loop. If it's not, i guess this is because of the content of the `$context` array.

**Comment by benborla** [comment]
I did check this one and PaginationExtension is loaded. 

@rugolinifr to answer your question why I created a UserCollectionDataProvider, I will use this for role checking for GET collection request. I just removed the unnecessary code that shouldn't be in the question. On the example above, I did remove the code for role checking to isolate the issue but seems it's not the reason why. 

Before posting here, I did all I can to debug the issue and was able to reproduce the bug.

**Comment by rugolinifr** [comment]
Well, I don't know then.

And what is exactly your "role checking" purpose ? It sounds like a  _security_ concern and it is suppose to be handled at the [extension level](/#extensions) for collection operations, as mentioned [here](https://api-platform.com/docs/core/security/#filtering-collection-according-to-the-current-user-permissions).

**Comment by benborla** [comment]
I'm checking if the user has the role to access the collection of a certain entity, for this one, I'm checking if the user has access to retrieve a collection of users.

I am following that documentation, but it says here:
[API Platform: Security](https://api-platform.com/docs/core/security/)
```
*Note 2: You can't use Voters on the collection GET method, use Collection Filters instead.
in the documentation:
```
and if you found that is said here:
[API Platform: Security](https://api-platform.com/docs/core/security/#filtering-collection-according-to-the-current-user-permissions)
```
Filtering collections according to the role or permissions of the current user must be done directly at the data provider level. For instance, when using the built-in adapters for Doctrine ORM, MongoDB and ElasticSearch, removing entries from a collection should be done using extensions. Extensions allow to customize the generated DQL/Mongo/Elastic/... query used to retrieve the collection (e.g. add WHERE clauses depending of the currently connected user) instead of using access control expressions. As extensions are services, you can inject the Symfony Security class into them to access to current user's roles and permissions.

If you use custom data providers, you'll have to implement the filtering logic according to the persistence layer you rely on.
```

that's why I created the `UserCollectionDataProvider`, I won't be putting the logic of how I check the role of a user on that class, since it's not related to the issue I'm encountering and I was able to reproduce the bug with just that code I provided above.

**Comment by rugolinifr** [comment]
I think you didn't understand both the documentation, and me. the documentation you just linked says:

> when using [...]  Doctrine [...] should be done using extensions.

According to your [first post](https://github.com/api-platform/core/issues/3721#issue-700580952), you are using Doctrine.

According to your [previous posts](https://github.com/api-platform/core/issues/3721#issuecomment-692018394), you have created a new Data Provider with the **only** purpose to check  user permission. I guess that if the user does not have permission, he can't see some records within the collection, right ?

Once again, I tell you that this job should be done within a Doctrine extension. So basically you *don't* need to create a custom Data Provider, what you need to do is to create a custom Extension, not a custom Data Provider. Your extension will be called by the Doctrine Data Provider if it is needed. A Doctrine Extension update the Doctrine Query Language and acts at database level: its efficient because it removes unwanted records directly from the database, not inside your running PHP API code.

Anyway do what you want. About the pagination issue itself, I don't know.

**Comment by dunglas** [comment]
Your custom data provider doesn't return an instance of `PaginatorInterface` (https://github.com/api-platform/core/blob/master/src/DataProvider/PaginatorInterface.php). It's why this isn't considered as a paged collection. If you return an object implementing this interface, the normalizer will automatically add the appropriate metadata to the JSON document.

**Comment by benborla** [comment]
Alright @dunglas thank you!

**Comment by benborla** [comment]
It's working, thank you again.
