### ISSUE TITLE
Swagger version 3 is hidding "exemple values" 

### ISSUE THREAD

**Issue by Aikoze** [api-platform/core#3722]
**API Platform version(s) affected:**

    api-platform/core v2.5.7
    api-platform/api-pack v1.3.0

**Description**  
Swagger version 3 is hidding "exemple values" with ManyToOne relations on POST and PUT operations

With the exact same code i have my "showing exemple values" back when i downgrade to Swagger version 2, that's only happening with  ManyToOne relations on POST and PUT.

**_Swagger version 3 :_** 
![image](https://user-images.githubusercontent.com/23453566/93106436-8e484780-f6b0-11ea-8262-fcd829676238.png)

**_Swagger version 2:_**
![image](https://user-images.githubusercontent.com/23453566/93106759-fdbe3700-f6b0-11ea-9596-7a4a243dcb0c.png)

Maybe @soyuka could help :)
Thanks for your amazing works with Api platform !

**Comment by dunglas** [comment]
This looks related to https://github.com/swagger-api/swagger-ui/issues/6402.
IMHO it should be fixed in Swagger UI directly.

**Comment by soyuka** [comment]
should be fixed by now
