### ISSUE TITLE
expand/collapce tags/operations, filter by tags and other swagger ui config options support

### ISSUE THREAD

**Issue by dvc** [api-platform/core#3730]
**Description**  
With really large api best choise to collapse all and|or activate search filter (may be with some default filter).

Full documentation can be found here: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

But current configuration doesn't supports sourch tuning.

**Example**  

``` /api?docExpansion=none&filter=Org ```

![image](https://user-images.githubusercontent.com/588564/93462742-d60ce000-f8f7-11ea-8f89-437b3632c339.png)

**Comment by WhiteRabbitDE** [comment]
I think you could enable that in your project by using a decorator. Anyway i think that could bei a nice feature to add in the config.

Do you plan to work on a PR @dvc ?

**Comment by dvc** [comment]
Hello, @WhiteRabbitDE !

Sorry, this is my first PR. Can you help me with it? Some review, how to write correct tests, where to update docs...

**Comment by dvc** [comment]
@WhiteRabbitDE , i've create a PR with code and docs update. 

Test almost fixed, except code style in other files. Do i have to fix CS issues?

I don't understand how to _"Also don't forget to add a comment when you update a PR with a ping to the maintainers, so he/she will get a notification"_?

And when i shuld squash commits?

**Comment by WhiteRabbitDE** [comment]
Hey @dvc ,

i am not a project member and not sure im the right person to answer your questions. Maybe @dunglas or @soyuka can help answering your questions?
