### ISSUE TITLE
If i can't write a test my changes won't be accepted?

### ISSUE THREAD

**Issue by tebaly** [api-platform/core#3732]
Hey. I am using the platform in my project and added the functions I need. I cannot write tests. Therefore, I cannot leave a request. How can I suggest my changes in the code?

**Comment by dunglas** [comment]
You can always open the PR. We'll help you to write the test if necessary!

**Comment by tebaly** [comment]
Add router loaders #3733
* The code that I wrote a long time ago and now use it myself
* I could get confused, maybe this is not the whole code
