### ISSUE TITLE
Output data transformation logic skipped if data is not a resource class

### ISSUE THREAD

**Issue by skalpa** [api-platform/core#3734]
**API Platform version(s) affected**: 2.5.7

**Description**  
When using `output: SomeClass`, the API Platform normalizer should check whether the output class (and not the current content of `data`) is a resource class. However it is not the case now, and the data transformation logic may be skipped in some scenarios (in my case a CQRS application):

* Use the messenger integration
* Have the message handlers return an object that is **not** a resource (i.e. a `SomeId` instance which is an identifier value object)
* Configure API platform with `output: SomeReadModel` (which **is** a resource class)
* Add a data transformer to transform the identifier value object to `SomeReadModel`

Expected behaviour: the data transformer is invoked so it can transform `SomeId` to `SomeReadModel`
Current behaviour: the data transformer is not invoked, because `SomeId` is not a resource class

**How to reproduce**  

```yaml
App\MyEntity:
  collectionOperations:
    post:
      messenger: input
      input: App\MyCommand
      output: App\MyReadModel
App\MyReadModel:
  itemOperations:
    get: ~
```

* Configure the `App\MyCommand` message handler so it returns an instance of `App\MyEntityId` (or anything that is not an instance of `MyEntity` or `MyReadModel`.
* Add a data transformer to transform the message handler output to `MyReadModel`

**Possible Solution**  
Fix the `ApiPlatform\Core\Serializer\AbstractItemNormalizer::supportsNormalization()` logic so it takes the output class into account:

```php
    public function supportsNormalization($data, $format = null, array $context = [])
    {
        if (!\is_object($data)) {
            return false;
        }
        $objectClass = $this->getObjectClass($data);
        $outputClass = $this->getOutputClass($objectClass, $context);

        return $this->resourceClassResolver->isResourceClass($objectClass)
            || (null !== $outputClass && $this->resourceClassResolver->isResourceClass($outputClass));
    }
```

Note: you'll also have to change classes that extend `AbstractItemNormalizer` so they pass the `$context` argument to it.

In my opinion the `$objectClass` should be completely ignored when the `$outputClass` is set, but this may introduce a BC break so the proposed fix is probably safer.

Also, theorically this may introduce BC breaks as some data transformers that were just skipped before might now be called after the fix, forcing users to fix their `supportsTransformation()` logic. However this is extremely unlikely as everybody who would be affected by the BC break would also have been affected by the issue described here.

**Comment by soyuka** [comment]
It's hard to handle all cases, we don't want to use data transformation logic on non-resource oir there will be too much confusion.
