### ISSUE TITLE
[Discussion] Best practice for comparing changes in a DataPersister?

### ISSUE THREAD

**Issue by jamesisaac** [api-platform/core#3751]
As the [docs say](https://api-platform.com/docs/core/extending/#extending-api-platform), the recommended way to add _"custom business logic and computations to trigger before or after persistence (ex: mail, call to an external API...)"_ is now to use DataPersisters, rather than the old method of EventSubscribers.

These seem to work well as a replacement in general, although one shortcoming I'm noticing is there doesn't seem to be a way to compare the current version of the resource (about to be persisted) with how it was originally before denormalization.  With an EventListener, I could have just stored the original property value in `KernelEvents::REQUEST`, and compared it in `KernelEvents::VIEW`.

Simple use-case example: when `User.approved` turns from `false` to `true` after a `PUT` request, sending out a "Your account has been approved" email.

There's Doctrine UnitOfWork's `getOriginalEntityData`, which could be used as follows:

```php
public function persist($data, array $context = [])
{
    if ($data instanceof User) {
        $original = $this->em->getUnitOfWork()->getOriginalEntityData($data);
        if (!($original['approved'] ?? null) && $data->approved) {
            // send email
        }
    }
}
```

However this feels a bit questionable to rely on, as it's not officially recommended anywhere, coupled to Doctrine, can't be statically analysed, etc.

Wondering if API Platform could provide a mechanism for this itself?  In an ideal world, something like:

```php
public function persist($data, array $context = [])
{
    $original = $context['original_resource'];
    if ($data instanceof User && $original instanceof User) {
        if (!$original->approved && $data->approved) {
            // send email
        }
    }
}
```

**Comment by rugolinifr** [comment]
> [...] I'm noticing is there doesn't seem to be a way to compare the current version of the resource (about to be persisted) with how it was originally before denormalization. With an EventListener, I could have just stored the original property value in KernelEvents::REQUEST, and compared it in KernelEvents::VIEW.

The "original resource" [is cloned then stored](https://github.com/api-platform/core/blob/176cdf9cedd187de8ef172d1fbdaf669ccabd431/src/EventListener/ReadListener.php#L120)  within the current `Request` object under the `previous_data` key. 

With a custom data persister (or any service), you have access to the current request by type-hinting the `RequestStack` object:

```php
public function __construct(RequestStack $requestStack)
{
    $this->response = $requestStack->getCurrentRequest();
}
```

Then fetch the resource when you need it:
```php
$originalResource = $this->request->get('previous_data');
```

With an event subscriber, the request is already available through a dedicated method:
```php
public function payload(ViewEvent $event): void  //Or any event extending KernelEvent
{
    $request = $event->getRequest();
}
```

Also, since the original resource is cloned, don't forget to implement your own `__clone()` method ([there is some concerns using Doctrine](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/cookbook/implementing-wakeup-or-clone.html)), especially to keep distinct `Collection` properties between the original and the processed resource.

**Comment by jamesisaac** [comment]
Nice!  Exactly what I was looking for, thanks.

I think I'll submit a PR proposing that's added to the DataPersister docs.  From what I can see `previous_data` isn't documented anywhere.

**Comment by dunglas** [comment]
It would be cleaner to pass this in the context of the data provider instead of relying on the `RequestStack` service (to preserve the compatibility with GraphQL).

PR welcome for this too!

**Comment by jamesisaac** [comment]
Ah right, I didn't catch that `previous_data` wasn't being set for GraphQL too.  Yeah, in that case, a unified approach to access it for both systems would be great.  I imagine this is a pretty common use-case.

**Comment by rugolinifr** [comment]
I did not know about that, I confess i've never used it so I'm not aware of its lifecycle.
