### ISSUE TITLE
Mongodb: search terms are not escaped before use in rexexp

### ISSUE THREAD

**Issue by rimas-kudelis** [api-platform/core#3754]
**API Platform version(s) affected**: master

**Description**  
Searched strings are not properly escaped before being used in Mongodb regular expressions. 

**How to reproduce**  
I have an entry containing a string with parentheses (let's say it's `foo(bar)`)in Mongodb, and it appears that I have to escape that string in my HTTP query if I want to find that entry:

`http://my.host/my/entities?myField=foo(bar)` yields no results, but
`http://my.host/my/entities?myField=foo\(bar\)` yields all the results expected by performing the first query.

**Possible Solution**  
[SearchFilter::addEqualityMatchStrategy()](https://github.com/api-platform/core/blob/176cdf9cedd187de8ef172d1fbdaf669ccabd431/src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php#L165) should escape strings before concatenating them to form a regular expression.

**Comment by alanpoulain** [comment]
Sure, would you want to make a PR?
