### ISSUE TITLE
Assert\Type is not working

### ISSUE THREAD

**Issue by ghost** [api-platform/core#3761]
**API Platform version(s) affected**: 2.5.7

**Description**  
I have added an annotation "Assert\Type(type="bool")" on a boolean property of an entity. When I try to test if validation is working and pass string as value, I get the following error "The type of the \"isPublic\" attribute must be \"bool\", \"string\" given." This error comes from Doctrine, not from the Validation component.

**How to reproduce**  
1. Add the following property to an entity:
`/**`
`* @ORM\Column(type="boolean")`
`* @Assert\Type(type="bool")`
`*/`
`private $isPublic = true;`
2. Send request to create or update the entity: 
`{`
`"isPublic": "test"`
`}`

**Comment by dunglas** [comment]
Can you copy the stack trace please? This error should come from the serializer (and it's intended), not from Doctrine.

**Comment by xPolo360** [comment]
This is indeed from the symfony serializer.
You must deactivate type checking.

The easiest method for me is to decorate the API platform ContextBuilder 
[see doc](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically)

exemple:
```php
<?php

declare(strict_types=1);

namespace App\Api\Serializer\ContextBuilder;

use ApiPlatform\Core\Exception\RuntimeException;
use ApiPlatform\Core\Serializer\SerializerContextBuilderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

final class DisableTypeEnforcementContextBuilder implements SerializerContextBuilderInterface
{
    /**
     * @var SerializerContextBuilderInterface
     */
    private $contextBuilder;

    public function __construct(SerializerContextBuilderInterface $contextBuilder)
    {
        $this->contextBuilder = $contextBuilder;
    }

    /**
     * @throws RuntimeException
     */
    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null): array
    {
        $context = $this->contextBuilder->createFromRequest($request, $normalization, $extractedAttributes);

        if (!isset($context[AbstractObjectNormalizer::DISABLE_TYPE_ENFORCEMENT])) {
            $context[AbstractObjectNormalizer::DISABLE_TYPE_ENFORCEMENT] = true;
        }

        return $context;
    }
}
```

**Comment by soyuka** [comment]
Thanks @xPolo360 would you be able to add this to the documentation?

**Comment by dunglas** [comment]
It's not a good idea to disable the type checking. If the types of the JSON document a invalid, you shouldn't not even finish the deserialization.

**Comment by xPolo360** [comment]
@soyuka Why not if I find time to ...

@dunglas yes and no, in this case it is necessary to add annotations @Assert\type in entity to check types.

Personally I prefer this solution because the return message from the API is more explicit.

Example with foo entity:
```php
/**
 * @ApiResource
 */
class Foo
{
    /**
     * @var string
     * @Assert\Type('string')
    public $name;
}
```
I send POST /api/foo with data:
```json
{
  "name": 1
}
```
case 1 type enforment enable.
responce:
```json
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "The type of the \"name\" attribute must be \"string\", \"integer\" given."
}
```
case 2 type enforment disable.
````json
{
  "@context": "/contexts/ConstraintViolationList",
  "@type": "ConstraintViolationList",
  "hydra:title": "An error occurred",
  "hydra:description": "name: This value should be of type string.",
  "violations": [
    {
      "propertyPath": "name",
      "message": "This value should be of type string."
    }
  ]
}
```

**Comment by maquejp** [comment]
I have the same result (issue).

`@Assert\Type(type="string", message="The value of capital should be of type {{ type }}")`

```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "The type of the \"capital\" attribute must be \"string\", \"integer\" given.",
```

`@Assert\NotBlank(message="The capital cannot be blank")`

We can expect the same behaviour as

```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "capital: The capital cannot be blank",
  "violations": [
    {
      "propertyPath": "capital",
      "message": "The capital cannot be blank"
    }
  ]
}
```

**Comment by kconde2** [comment]
I'm facing same issue. Any updates ?

**Comment by emr-dev** [comment]
Similar problem

**Comment by emr-dev** [comment]
A sterilizer error message is returned instead of a validator component error

Entity
```
    #[Assert\Type(type: 'bool', message: 'some message')]
    private ?bool $sex = null;
```
Request 
```
{
  "sex": "test"
}
```
Response 
```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "The type of the \"sex\" attribute must be \"bool\", \"string\" given.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/vendor/symfony/serializer/Exception/NotNormalizableValueException.php",
      "line": 31,
      "args": []
    }
``` 

I expected an response
```
{
  "title": "An error occurred",
  "detail": "sex: some message'",
  "violations": [
    {
      "propertyPath": "sex",
      "message": "some message'"
    }
  ]
}
```

Is there another way without deactivating Serializer type checking?

**Comment by mantaszv** [comment]
I am facing the same issue, Why it is closed?
Am I alone facing closed and not fixed api-platform issues mutiple times, or I am unlucky?
Started to use API-platform recently and facing so many issues with it.

**Comment by soyuka** [comment]
answer is at https://github.com/api-platform/core/issues/6392
