### ISSUE TITLE
openApi doc v3 don't use global configuration of api-platform.

### ISSUE THREAD

**Issue by xPolo360** [api-platform/core#3763]
**API Platform version(s) affected**: 2.5.7

**Description**  
When generating the openApi v2 doc the DocumentationNormalizer does not take into account the pagination values configured in /config/packages/api_platform.yaml

**How to reproduce**  
On file /config/packages/api_platform.yaml
```yaml
api_platform:
    collection:
        pagination:
            items_per_page: 25
```
In uri /docs the default value of perpage is 30 instead of 25
```json
{
    "name": "perpage",
    "in": "query",
    "required": false,
    "description": "The number of items per page",
    "schema": {
        "type": "integer",
        "default": 30,
        "minimum": 0
    }
}
```
**Possible Solution**  
On DocumentationNormalizer.php in function addPaginationParameters get the global configuration of api-platform
in line 377 remplace default value 30 by global value:
```php
$itemPerPageParameter['schema'] = [
    'type' => 'integer',
    'default' => $resourceMetadata->getTypedOperationAttribute($operationType, $operationName, 'pagination_items_per_page', <GLOBAL VALUE OF ITEMS PER PAGE>, true),
    'minimum' => 0,
];
```

**Comment by soyuka** [comment]
This should work now also we recommend to use `defaults`.
