### ISSUE TITLE
IRI converter, getIriFromResourceClass without a GET collection

### ISSUE THREAD

**Issue by GHuygen** [api-platform/core#3765]
First of all i would like to take the opportunity to thank al the people how work hard to make this platform possible!
The more I work with it the more possibilities i see!
THANK YOU!!

**API Platform version(s) affected**: 2.5.6

**Description**  
If you have a entity where the GET collection is disabled.
But still use the POST collection!
You would expect that the getIriFromResourceClass from the IriConverter still gives you the collection IRI.
But it throws the following error:
```` ApiPlatform\Core\Exception\InvalidArgumentException : No collection route associated with the type "App\Entity\...".````

**How to reproduce**  
When you disable the GET collection and try to get the IRI from the IriConverter with functon "getIriFromResourceClass"

**Possible Solution**  
I traced it back to RouteNameResolver.
On line 53, only a GET is allowed.
````
if ($resourceClass === $currentResourceClass && null !== $operation && (empty($methods) || \in_array('GET', $methods, true))) {
    if (OperationType::SUBRESOURCE === $operationType && false === $this->isSameSubresource($context, $route->getDefault('_api_subresource_context'))) {
    continue;
    }

    return $routeName;
}
````
If we allow the POST method here I think it would solve the issue.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/4881
