### ISSUE TITLE
[Bug] When using Doctrine Extension in OrderBy

### ISSUE THREAD

**Issue by dzasa** [api-platform/core#3767]
**API Platform version(s) affected**: 2.5.7

**Description**  
When using Doctrine Extension, in this example FIELD, error is thrown:
`The alias \"FIELD(o\" does not exist in the QueryBuilder.` 

Problem is here:
https://github.com/api-platform/core/blob/1c7c26d0e8f505e493fa31397255d2de2c5dce13/src/Bridge/Doctrine/Orm/Util/QueryChecker.php#L106-L113

OrderByAliases would look like this:
`array:2 [
  0 => "FIELD(o"
  1 => "o"
]`

Where `FIELD(o` should not be presented.

**How to reproduce**  
`$queryBuilder->orderBy('FIELD(o.id,1,2,3)');`

**Possible Solution**  
https://github.com/dzasa/core/commit/89e67c5000f7c5dff881a13f0e659acd36488cf0

**Additional Context**

**Comment by mislavjakopovic** [comment]
Bump, can we please fix this? Confirmed that the issue occurs when we try to add the FIELD and that the fix from @dzasa solves it.

**Comment by MKHSKY** [comment]
This is still relevant when adding a filter to order stuff like this 
```php
 $alias = $queryBuilder->getRootAliases()[0];
        $priorityOrder = $queryNameGenerator->generateParameterName('priorityOrder');
        $queryBuilder
            ->addOrderBy(sprintf('FIELD(%s.priority, :%s)', $alias, $priorityOrder), $direction)
            ->setParameter($priorityOrder, TicketPriority::ALL);
```

**Comment by SherinBloemendaal** [comment]
I've bumped into the same issue when using a `CASE WHEN ...`. It seems it is not fixed yet?
