### ISSUE TITLE
PATCH with plain JSON on OneToMany, got wrong response.

### ISSUE THREAD

**Issue by do-web** [api-platform/core#3778]
**API Platform version(s) affected**: Latest

**Description**  
I create a plain JSON PATCH request:

/api/advertisements/80cdf3f4-b1ea-4679-9f8f-89fab0acb446

```
{
   id: "80cdf3f4-b1ea-4679-9f8f-89fab0acb446"
   images: [{id: "f43408f8-ff08-47ab-9be2-b6d6e545ff28",…}]
}
```

Images is a OneToMany relation. 
The response of images is an object now:

```
{
  id: "80cdf3f4-b1ea-4679-9f8f-89fab0acb446"
  images: {1: {id: "2fdedb4b-85aa-445c-adf4-9934e08cab72",…}}
}
```

Expected result should be an array:

```
{
  id: "80cdf3f4-b1ea-4679-9f8f-89fab0acb446"
  images: [{id: "f43408f8-ff08-47ab-9be2-b6d6e545ff28",…}]
}
```

**Comment by norkunas** [comment]
See https://api-platform.com/docs/core/serialization/#collection-relation
