### ISSUE TITLE
Possible Varnish Weird Behavior

### ISSUE THREAD

**Issue by aalinia** [api-platform/core#3780]
**API Platform version(s) affected**: 2.5.6

**Description**  
I've deployed an api-platform app with docker-compose and everything seems good when containers start ...
but I think varnish works unproperly. when I reload the docs page sometimes it has an error,
sometimes it loads partially,
and sometimes it loads completely ....

**Additional Context**  
Screenshots 

![photo_2020-10-22_12-36-53](https://user-images.githubusercontent.com/1521117/97028440-008e3080-1569-11eb-953c-2050d9bdda26.jpg)

![photo_2020-10-22_12-36-57](https://user-images.githubusercontent.com/1521117/97028450-04ba4e00-1569-11eb-99cd-922d16135e0f.jpg)

![photo_2020-10-22_12-37-00](https://user-images.githubusercontent.com/1521117/97028451-05eb7b00-1569-11eb-9e9d-2a31a7075a30.jpg)

**Comment by chalasr** [comment]
'Looks related to https://github.com/api-platform/api-platform/issues/1367
