### ISSUE TITLE
RangeFilter value coerce

### ISSUE THREAD

**Issue by guitoon** [api-platform/core#3796]
Before all thank you for this amazing project.
To respect [your general design considerations](https://api-platform.com/docs/core/design/) we've based our API on Dto instead of doctrine entities.
To do it we had to create our own filter, mainly based on yours.

**Description**  
In ApiPlatform\Core\Bridge\Doctrine\Common\Filter\RangeFilterTrait there are 2 functions to normalize values. They convert string values into int with `$value + 0;`
Why use this functionality instead of "intval" which is designed for this purpose?

**Example**  
Before
```
 private function normalizeValue(string $value, string $operator)
    {
        if (!is_numeric($value)) {
            $this->getLogger()->notice('Invalid filter ignored', [
                'exception' => new InvalidArgumentException(sprintf('Invalid value for "[%s]", expected number', $operator)),
            ]);

            return null;
        }

        return $value + 0; // coerce $value to the right type.
    }
```
After
```
 private function normalizeValue(string $value, string $operator)
    {
        if (!is_numeric($value)) {
            $this->getLogger()->notice('Invalid filter ignored', [
                'exception' => new InvalidArgumentException(sprintf('Invalid value for "[%s]", expected number', $operator)),
            ]);

            return null;
        }

        return  inval($value); // coerce $value to the right type.
    }
```
I can make a PR if it's pertinent

**Comment by antograssiot** [comment]
Likely because intval would not work with floats, so the example given in the doc would not work `/offers?price[between]=12.99..15.99`

```php
var_dump("15.02" + 0);
// will give float(15.02)

var_dump(intval("15.02"));
// int(15) obviously
```

**Comment by guitoon** [comment]
Indeed, thank you for this point.
