### ISSUE TITLE
PHP 7.4 typed relations are not working on deserialisation

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#3815]
**API Platform version(s) affected**: 2.5.7

**Description**  

When I use a typed property for a relation I have this error:

```
```

**How to reproduce**  

```
use App\Entity\Hosting;
use Symfony\Component\Serializer\Annotation\Groups;

class CDNInput
{
    /**
     * @Groups({"post"})
     */
    public string $subdomainName;

    /**
     * @Groups({"post"})
     */
    public Hosting $hosting;
}
```

**Possible Solution**  

**Additional Context**  

Note: Adding the `@var` combined with the typed property is the current workaround to make it working properly.

**Comment by alanpoulain** [comment]
Please see https://github.com/api-platform/core/issues/3800.

**Comment by dunglas** [comment]
This should be handled automatically by Symfony PropertyInfo.
Can you copy the error (it doesn't appear), and the output of `composer show` please?

**Comment by WhiteRabbitDE** [comment]
I am using this successfully in one of my projects so i can confirm it should work.
 
 ```
 /**
     * @var ArrayCollection|PriceCondition[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Price\PriceCondition", mappedBy="priceAlteration", orphanRemoval=true, cascade={"persist"})
     */
    private Collection $priceConditionList;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Price\Price", orphanRemoval=true, cascade={"persist"})
     * @ORM\JoinColumn(name="PRICE_ID", referencedColumnName="ID", nullable=false)
     */
    private Price $price;
```

Im using 
`symfony/property-info                v5.1.8    Symfony Property Info Component`
