### ISSUE TITLE
ManyToOne missing parent entity in construct

### ISSUE THREAD

**Issue by phoefnagel** [api-platform/core#3819]
Hi, I am quite new to Api Platform and currently struggling with the following issue.

For example:

Resource **A** has a OneToMany relation with resource **B** and resource **B** has a ManyToOne relation with resource **A**. What I am trying to achieve is that when creating resource **A** (POST request) it can optionally contain one or more **B** resources. When one or more **B** resources are present they should be persisted together with resource **A**.

**Code resource A (parent):**
```php
/**
* @Groups({"parent:read", "parent:write"})
* @ORM\OneToMany(targetEntity="App\Entity\Child", mappedBy="parent", cascade={"persist"})
*/
private Collection $childs;

public function __construct(array $childs)
{
       $this->id = Uuid::getVersion4();
       $this->childs = new ArrayCollection($childs);
}
```

**Code resource B (child):**
```php
/**
* @ORM\ManyToOne(targetEntity="App\Entity\Parent", inversedBy="childs")
* @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=false)
*/
private Parent $parent;

/**
* @Groups({"parent:read", "parent:write"})
* @ORM\Column(name="var1", type="string", nullable=false)
*/
private string $var1;

/**
* @Groups({"parent:read", "parent:write"})
* @ORM\Column(name="var2", type="string", nullable=false)
*/
private string $var2;

public function __construct(Parent $parent, string $var1, string $var2)
{
       $this->id = Uuid::getVersion4();
       $this->parent = $parent;
       $this->var1 = $var1;
       $this->var2 = $var2;
}
```

The problem is that the first parameter ($parent) of resource B is not provided during the deserialization which results in an exception.

What is the best way to fix this instead of iterating in the parent construct and call a setter to provide the parent entity?

EDIT:
The second and third parameter ($var1 and $var2) are provided as first and second parameter.

**Comment by jamesisaac** [comment]
Have a look at the Doctrine docs on managing associations: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/working-with-associations.html#association-management-methods
