### ISSUE TITLE
PHP 8 incompatibility

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#3839]
api-platform/core v2.5.7 requires willdurand/negotiation ^2.0.3, but this version is incompatible with upcoming php ^8. 
https://github.com/willdurand/Negotiation/commit/113acb8e977d145ad09d50fd53f48c9e25025379

Meanwhile, willdurand/negotiation:dev-master already have that issue fixed, but still not tagged with release version.
What is your idea to fix that issue and make api-platform fully compatible with php 8?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/2.5/composer.json#L27 

This has been addressed in https://github.com/api-platform/core/commit/8e58a986970dc3abe1fa994f6849631ad77e09a1
