### ISSUE TITLE
jsonld.SyntaxError: Invalid JSON-LD syntax; @context term values must be strings or objects

### ISSUE THREAD

**Issue by ollietb** [api-platform/core#3844]
**API Platform version(s) affected**: dev-master

**Description**  
Upgrading from 176cdf9 to dev-master causes an error in React Admin `jsonld.SyntaxError: Invalid JSON-LD syntax; @context term values must be strings or objects`

**How to reproduce**  

For me the call to /api/docs.jsonld changes between versions
176cdf9:
```
{
   "@context":{
      "@vocab":"https:\/\/localhost:8443\/api\/docs.jsonld#",
      "hydra":"http:\/\/www.w3.org\/ns\/hydra\/core#",
      "rdf":"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#",
      "rdfs":"http:\/\/www.w3.org\/2000\/01\/rdf-schema#",
      "xmls":"http:\/\/www.w3.org\/2001\/XMLSchema#",
      "owl":"http:\/\/www.w3.org\/2002\/07\/owl#",
      "schema":"http:\/\/schema.org\/",
      "domain":{
         "@id":"rdfs:domain",
         "@type":"@id"
      },
      "range":{
         "@id":"rdfs:range",
         "@type":"@id"
      },
      "subClassOf":{
         "@id":"rdfs:subClassOf",
         "@type":"@id"
      },
      "expects":{
         "@id":"hydra:expects",
         "@type":"@id"
      },
      "returns":{
         "@id":"hydra:returns",
         "@type":"@id"
      }
   },
   "@id":"\/api\/docs.jsonld",
   "@type":"hydra:ApiDocumentation",
   "hydra:title":"Homewerk.co API",
   "hydra:entrypoint":"\/api",
```
compared to dev-master:
```
{
   "@context":{
      "@vocab":"https:\/\/localhost:8443\/api\/docs.jsonld#",
      "hydra":"http:\/\/www.w3.org\/ns\/hydra\/core#",
      "openapi":"OpenApi\/openapi",
      "info":"OpenApi\/info",
      "servers":"OpenApi\/servers",
      "paths":"OpenApi\/paths",
      "components":"OpenApi\/components",
      "security":"OpenApi\/security",
      "tags":"OpenApi\/tags",
      "externalDocs":"OpenApi\/externalDocs",
      "extensionProperties":"OpenApi\/extensionProperties"
   },
   "@type":"OpenApi",
   "@id":"_:17018",
   "openapi":"3.0.3",
```

**Possible Solution**  

I imagine it has to do with the OpenAPI changes in master recently

**Comment by soyuka** [comment]
I don't have this, using master `/docs.jsonld` outputs:

![20201122_10h47m52s_grim](https://user-images.githubusercontent.com/1321971/99900629-0d5d8b80-2cb1-11eb-8be4-58f55ecf6750.png)

**Comment by ollietb** [comment]
Do you know what would cause the type to change from `"@type":"hydra:ApiDocumentation"` to `"@type":"OpenApi",`?

**Comment by soyuka** [comment]
Not really and this is what surprises me, are you overriding some documentation related services? You may contact me on symfony-devs.slack.com

**Comment by ollietb** [comment]
I'm adding a swagger decorator to handle the JWT token, as mentioned in the docs, but I don't think that's causing it.
```
    App\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: ['@App\Swagger\SwaggerDecorator.inner']
        autoconfigure: false
```

**Comment by soyuka** [comment]
Not really, there is a new normalizer called `api_platform.openapi.normalizer` but this one should still work. Anyway this is more related to Hydra then it is to OpenAPI.

**Comment by dunglas** [comment]
I can confirm the issue. Here is a reproducer with a Vanilla installation: https://github.com/api-platform/api-platform/pull/1693
