### ISSUE TITLE
Create maker commands to generate data providers and data persisters

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3849]
**Description**  

It could be nice to add two commands to MakerBundle (or to ApiPlatformBundle): `make:data-provider` and `make:data-persister`.

This would help users bringing their own persistence layer.

**Comment by GregoireHebert** [comment]
Good idea, it could even be extended to `DataTransformer`, `ItemQueryExtension`, `CollectionQueryExtension` and custom filter extending `AbstractContextAwareFilter `.

**Comment by chalasr** [comment]
>  (or to ApiPlatformBundle)

As discussed, extending maker-bundle in api-platform makes much more sense than the opposite to me.

**Comment by dunglas** [comment]
We shouldn't encourage using `DataTransformer` (data transformers are very often misused). +1 for the other classes.

**Comment by mysiar** [comment]
it might be easier to create it in MakerBundle, @dunglas what do you think ?

**Comment by LebzoDev** [comment]
Instead of creating a persister file and customing it, it would be better to have one command to generate it
