### ISSUE TITLE
Enable OPCache Preloading on SF 4.4

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/core#3852]
Hi,

Trying to enable opcache preloading : https://symfony.com/blog/new-in-symfony-4-4-preloading-symfony-applications-in-php-7-4

I have setup the option on my php config but I'm getting the following error :

`Argument 1 passed to ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyNameCollectionFactory::create() must be of the type string, null given, called in /app/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php on line 330`

Code where it's triggered :

```

        $groups = ['read_user', 'me_user'];
        if($user->hasProfile('worker')) $groups[] = 'worker';
        $serializedEntity = $this->container->get('serializer')->serialize($user, 'json', ['groups' => $groups]);
        return new Response($serializedEntity, 200, ['Content-Type' => 'application/json']);
```

Any idea what i'm doing wrong ?

Thanks in advance,
Julien

**Comment by soyuka** [comment]
Maybe that it needs the same as https://github.com/api-platform/core/pull/3827 ?

**Comment by crls-brtlm** [comment]
I've also found this problem... Same error.
Did you have any advance with it?

**Comment by pesseyjulien** [comment]
nop :/

**Comment by crls-brtlm** [comment]
Maybe, this is an issue that can be solved with the tags container.preload and container.no_preload for the affected classes which can define which classes should be preloaded by PHP as stated here https://symfony.com/doc/current/performance.html.

Unfortunately, I'm using SF 4.4 and these tags were introduced on SF 5.1

**Comment by pesseyjulien** [comment]
Upgraded to SF 5.2 and no error anymore !
