### ISSUE TITLE
[2.5.8] assertMatchesResourceItemJsonSchema with DateTime Format "U"

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#3878]
**API Platform version(s) affected**: 2.5.8

**Description**  
Not 100% sure its a bug but I have an embeddable with an attribute ``` private ?DateTimeInterface $startDateTime; ```
and Im decorating the SerializerContextBuilder to use datetime_format="U". After the changes in assertMatchesResourceItemJsonSchema my tests are now failing because the response contains an timestamp.

``` 
timeRange.startDateTime: Invalid date-time "1606994586", expected format YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss+hh:mm
``` 

The Endpoint itself still works and returns the object as 
```
'timeRange' => Array &1 (
        '@type' => 'TimeRange'
        '@id' => '_:11331'
        'startDateTime' => '1606994586'
    )
```

**Comment by alanpoulain** [comment]
Since it's a custom format, you probably need to decorate the `TypeFactory` in `JsonSchema` too.

**Comment by WhiteRabbitDE** [comment]
DateTime is already "string" in the TypeFactory
```
 if (is_a($className, \DateTimeInterface::class, true)) {
            return [
                'type' => 'string',
                'format' => 'date-time',
            ];
        }
```
Or is it the format that matters ?

**Comment by alanpoulain** [comment]
I think it's the format.

**Comment by WhiteRabbitDE** [comment]
You are right. The format was causing my problem. After decorating the TypeFactory the tests pass and my swagger ui does fit my data better anyways this way :-)

Thanks @alanpoulain !
