### ISSUE TITLE
assertMatchesResourceCollectionJsonSchema and assertMatchesResourceItemJsonSchema breaks after adding ALLOW_EXTRA_ATTRIBUTES to false

### ISSUE THREAD

**Issue by pmontoya** [api-platform/core#3881]
**API Platform version(s) affected**: 2.5.8

**Description**  
[This commit](https://github.com/api-platform/core/commit/7595ac7c17eecd5be320026583c040c44c9ed851#diff-b0c03d04114819985843f011d3de75f6516e4c0c26ed9b9357c077338426eb6e) add the serialization context parameter but it breaks serialization groups schema.

I think this due to https://github.com/api-platform/core/blob/ab474b69c4e05318659f91e3cc55625b8c302735/src/JsonSchema/SchemaFactory.php#L283 : as `$serializerContext` is not null, `$this->getSerializerContext($resourceMetadata, $type, $operationType, $operationName)` is not call so serialization groups aren't set in serialization context and assert is false.

**How to reproduce**  
Create an Entity with some properties not serialized and launch test on schema with one of `assertMatchesResourceCollectionJsonSchema` or `assertMatchesResourceItemJsonSchema` : the result will be false

**Comment by alanpoulain** [comment]
The arrays should probably be merged. Could you make a PR?

**Comment by pmontoya** [comment]
Ok, I'm in

**Comment by alanpoulain** [comment]
Related: https://github.com/api-platform/core/issues/3896

**Comment by soyuka** [comment]
closing in favor of #3896
