### ISSUE TITLE
[OpenAPI] v2.6.0-alpha Subresources - paths are missing prefix in OpenAPI

### ISSUE THREAD

**Issue by VeryStrongFingers** [api-platform/core#3906]
**API Platform version(s) affected**: v2.6.0alpha

**Description**  
Generated documentation is not producing route paths including the configured route prefix.

`php bin/console debug:router` is generating correct paths, and is functioning as expected, so this problem appears isolated to the OpenAPI generation.

**How to reproduce**  
1. config/routes/api_platform.yaml
```
api_platform:
  resource: .
  type: api_platform
  prefix: /example
```

2. Create a resource, and subresource

3. Visit your local documentation. Subresources will not be prefixed with `/example`

**Possible Solution**  
The culprit looks to be within https://github.com/api-platform/core/blob/76ca5351337f9a817de6cfdb6f1b395f4dbd94ad/src/OpenApi/Factory/OpenApiFactory.php#L282

the `path` key appears to be present when the operation type is a subcollection, but not item/collection which is why this issue is limited.

 If the operationPathResolver was used, the route would contain the prefix.

**Comment by GrmpfNarf** [comment]
The issue does not only appear in subressources it also appears when you have set the ``path`` attribute for an operation in the @ApiResource annotation.

Quickfix via https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification
```php
public function normalize($object, $format = null, array $context = [])
{
   $prefix= 'api'; //TODO: set your prefix here without leading /
    $paths = array_keys($docs['paths']);

   foreach ($paths as $path) {
       if (preg_match('/^(?!(\/'.$prefix.'.*)).*/', $path)) {
           $newPath = '/'.$prefix.$path;
           $docs['paths'][$newPath] = $docs['paths'][$path];
           unset($docs['paths'][$path]);
       }
   }
   return $docs;
}
```
I think the issue appears by not using an ``operationPathResolver`` when the ``path`` attribute is set manually in ``ApiPlatform\Core\OpenApi\Factory\OpenApiFactory`` in line 282

```php
private function getPath(string $resourceShortName, string $operationName, array $operation, string $operationType): string
{
    $path = $operation['path'] ?? $this->operationPathResolver->resolveOperationPath($resourceShortName, $operation, $operationType, $operationName);
    ...
}
```
