### ISSUE TITLE
BC break in 2.5.8

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#3918]
Reproducer: https://github.com/theofidry/bug-9283

```
composer install
docker-compose up -d
bin/console doctrine:migration:migrate --env test
vendor/bin/phpunit
```

We have been using API-Platform with VOs as entity identifiers. Although the doc generated by API-Platform looks wrong (assumes it's an object):

<img width="439" alt="Screen Shot 2020-12-19 at 14 36 48" src="https://user-images.githubusercontent.com/5175937/102690734-b1324c80-4207-11eb-8a0b-36421d842520.png">

It is in practice working fine.

However when it comes to the testing utilities, the `::assertMatchesResource{Item,Collection}JsonSchema()` assertions now fail with a message along the lines of:

```
hydra:member[0].id: Integer value found, but an object is required
```

**Comment by alanpoulain** [comment]
Yes because it was not working at all before.
See https://github.com/api-platform/core/pull/3803.

**Comment by theofidry** [comment]
I suspected that, but how to fix it?

**Comment by alanpoulain** [comment]
It means that, like you say, the generated documentation is wrong and needs to be fixed.

**Comment by theofidry** [comment]
I’ll see if that’s enough and how hard/easy it is to do. But IMO that
remains quite a bit task to do (and not documented) for not a minor but a
patch release

**Comment by alanpoulain** [comment]
Personally, I think that this assertion not working at all was a big issue to be fixed as soon as possible. It was very misleading because developers trusted it to verify the schema even if the schema was wrong.

**Comment by theofidry** [comment]
Whilst I agree it's a big issue, I don't think upgrading to a patch or minor version should break and/or require hours of work to upgrade. That you have deprecations and that you may need some work to address them or you have a new way to do things sure.

Anyway what is done is done, but maybe it would be best to have a faster release cycle for patch releases at least. https://github.com/api-platform/core/compare/v2.5.7...v2.5.8 is 61 commits: finding what cause an issue to an external person may be quite hard and providing a reproducer is not always 5min either. I'm lucky to have both you and greg being quite responsive, but I think it may be quite off putting to more than one person (and very realistically more than one person would have just not upgraded and be left with a bad impression)

**Comment by soyuka** [comment]
If you want OpenAPI to use an `int` just specify:

```
diff --git a/src/Entity/Greeting.php b/src/Entity/Greeting.php
index 84ea60b..ffeeb54 100644
--- a/src/Entity/Greeting.php
+++ b/src/Entity/Greeting.php
@@ -18,6 +18,7 @@ class Greeting
      * @ORM\Id
      * @ORM\GeneratedValue
      * @ORM\Column(type="greeting_id")
+     * @var int
      */
     public GreetingId $id;
```

The schema is correct imo as you're using an Object (GreetingId) as the type of the identifier.

**Comment by theofidry** [comment]
I don't think having contradictory doc types is the solution (and most SA will yell at you for good reasons) – unless there was a special ApiPlatform type. I'll either try to change the types for each model or update manually the doc.
