### ISSUE TITLE
[Graphql] SerializeStage

### ISSUE THREAD

**Issue by joelisayas** [api-platform/core#3925]
Hi,

my goal is to add an extra attribute 'totalExtraCount' at the collection operation.
if i understood the best practice would be to decorate the Serialize stage. Do you have an example like the WriteStage in the doc ?

**Comment by alanpoulain** [comment]
Hello. If you do it in the serialize stage, it will not be available in the GraphQL schema.
Maybe it would be better to create a "virtual" property instead.

**Comment by joelisayas** [comment]
ok thks
