### ISSUE TITLE
Call to member function GetType() on null

### ISSUE THREAD

**Issue by dylanjacob** [api-platform/core#393]
When denormalizing data, the "Call to member function GetType() on null" error is thrown.  

Log info:
```
[Mon Jan 25 09:44:47.181971 2016] [:error] [pid 33018] [client <ip redacted>:59881] PHP Notice:  Undefined offset: 0 in /var/www/PartKeepr/vendor/dunglas/api-bundle/JsonLd/Serializer/ItemNormalizer.php on line 241, referer: https://<hostname redacted>/
[Mon Jan 25 09:44:47.182221 2016] [:error] [pid 33018] [client <ip redacted>:59881] PHP Fatal error:  Call to a member function getType() on null in /var/www/PartKeepr/vendor/dunglas/api-bundle/JsonLd/Serializer/ItemNormalizer.php on line 241, referer: https://<hostname redacted>/
```

Looks like `$type = $attributesMetadata[$attributeName]->getType();` is getting `$attributeName == null` and so getType is acting on a null value.

**Comment by dunglas** [comment]
First of all, thanks for taking the time to report this issue.

This issue looks weird to me. Can you paste an example of JSON document allowing to reproduce this error? Or better can you update your PR to add a test?

**Comment by dunglas** [comment]
You submit a document like `{"": "foo"}` right?

**Comment by dylanjacob** [comment]
The issue related to the JSON document is something like this:
```
{
   ...
   project: {
   0: "/"
   },
   ...
}
```

The 0 as a key is being passed as the array element id in `$attributesMetadata[$attributeName]` and there is no element so getType() is throwing the exception.

**Comment by dunglas** [comment]
This is not a valid JSON document. According to the spec, keys must be strings.
Try your document on http://jsonlint.com/ it will throw an error.

Btw, `json_decode` fails to decode such document:

```php
var_dump(json_decode('{0: "foo"}'));
# NULL
```

**Comment by teohhanhui** [comment]
@dunglas I suppose @dylanjacob meant `"0"` instead of `0`

**Comment by teohhanhui** [comment]
This is from partkeepr/PartKeepr#579 and seems to be related to #285

(The JSON should be from an earlier API response...)

**Comment by dylanjacob** [comment]
partkeepr/PartKeepr#579 has been fixed, closing...
