### ISSUE TITLE
Error after disabling docs : Unable to generate a URL for the named route \"api_doc\" as such route does not exist.

### ISSUE THREAD

**Issue by GS-Wacan** [api-platform/core#3937]
This is my second project with Api Platform, the API is close to be ready for release.
I switched the .env to prod, and disabled the docs, since I do not need or want to share it publicly.

```yaml
# config/packages/api_platform.yaml
api_platform:
    enable_docs: false
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
```

This makes some resources unnaccessible with GET methods, as I get the 500 error : 
`Unable to generate a URL for the named route \"api_doc\" as such route does not exist.`

This only seems to happen using json-ld format, for a few resources, with the get collection operation.
Everything works fine with an Accept json header or .json at the end, and the get item operation, but I need the json-ld format for the bundled pagination that's very handy.

I've tried to remove unnecessary annotations, filters, groups, update my packages and symfony, but I still have the same issue.

Here's one of the non-working resources, it's very simple and it doesn't use a DataProvider : 

```php
<?php
// src/Entity/Score.php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ScoreRepository;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

/**
 * @ApiResource(
 *      attributes={
 *          "order"={"delta": "ASC"},
 *          "pagination_client_items_per_page"=true,
 *          "maximum_items_per_page"=50
 *      },
 *      collectionOperations={
 *         "get"={
 *             "normalization_context"={"groups"={"score:read"}}
 *          }
 *      },
 *      itemOperations={
 *          "get"={
 *             "normalization_context"={"groups"={"score:read"}},
 *              "security"="is_granted('ROLE_USER')"
 *          },
 *         "delete"={"security"="is_granted('ROLE_ADMIN')"}
 *      })
 * @ApiFilter(SearchFilter::class, properties={"user": "exact", "user.address.country": "exact"})
 * @ORM\Entity(repositoryClass=ScoreRepository::class)
 */
class Score
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"enter:score", "score:read"})
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="scores")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"enter:score", "score:read"})
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Challenge::class, inversedBy="scores")
     * @ORM\JoinColumn(nullable=true)
     * @Groups({"enter:score", "score:read"})
     * @ApiFilter(SearchFilter::class, strategy="exact")
     */
    private $challenge;

    /**
     * @ORM\ManyToOne(targetEntity=Course::class)
     * @ORM\JoinColumn(nullable=true)
     * @Groups({"enter:score", "score:read"})
     * @ApiFilter(SearchFilter::class, strategy="exact")
     */
    private $course;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"enter:score", "score:read"})
     */
    private $type;

    /**
     * @ORM\Column(type="float")
     * @Groups({"enter:score", "score:read"})
     */
    private $delta;

    /**
     * @ORM\ManyToOne(targetEntity=Copilot::class)
     * @Groups({"enter:score", "score:read"})
     */
    private $copilot;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getChallenge(): ?Challenge
    {
        return $this->challenge;
    }

    public function setChallenge(?Challenge $challenge): self
    {
        $this->challenge = $challenge;

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): self
    {
        $this->course = $course;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDelta(): ?float
    {
        return $this->delta;
    }

    public function setDelta(float $delta): self
    {
        $this->delta = $delta;

        return $this;
    }

    public function getCopilot(): ?Copilot
    {
        return $this->copilot;
    }

    public function setCopilot(?Copilot $copilot): self
    {
        $this->copilot = $copilot;

        return $this;
    }
}
```

Does any one encountered the same issue ? And how may I fix it ? A little help would be much appreciated as almost everything is working

**Comment by alexislefebvre** [comment]
A possible workaround: keep the doc but add a rule to block the access:

```
security:
    # ...

    access_control:
        - { path: '^/api$', roles: ROLE_SUPER_ADMIN }
```

**Comment by lukey78** [comment]
This is very annoying. There're 4 locations in the code with code like `$this->urlGenerator->generate('api_doc', ...)` - without checking if the feature is actually enabled.

For me it fails in `ContextBuilder.php` in the method `getBaseContext`.

Any idea how to fix this?

**Comment by alexislefebvre** [comment]
It looks like the value of `enable_docs` is never checked: https://github.com/api-platform/core/search?q=enable_docs

Another workaround may be to define `api_doc` to replace the original route with a blank page.

**Comment by alexislefebvre** [comment]
See also https://github.com/api-platform/api-platform/issues/1504

**Comment by GS-Wacan** [comment]
> See also [api-platform/api-platform#1504](https://github.com/api-platform/api-platform/issues/1504)

Thank you I didn't find similar issues, but this looks like the best option ! I'll try it a bit later

**Comment by soyuka** [comment]
This is expected as without docs you can not use jsonld. Use `json` and you'll be able to disable docs.

**Comment by ahmed-bhs** [comment]
It's confusing that the enable_docs, enable the `api_doc` route but it does not enable the doc !

**Comment by Mazzzoni** [comment]
In case people are still getting the error, want jsonld and they want to hide their documentation in production, here's how I "hide" documentation pages using event subscriber and regex, works quite fine for me, let me know if there's a better approach to this scenario.

```php
<?php declare(strict_types=1);

namespace YourNamespace\EventSubscriber;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * Used to empty documentation pages in prod environment
 */
final class ApiDocumentationSubscriber implements EventSubscriberInterface
{
    private const PROTECTED_PATHS = [
        '^/api$',
        '^/api/docs',
    ];

    public function __construct(
        private readonly ParameterBagInterface $parameterBag,
    )
    {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => ['onKernelRequest', 249],
        ];
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        if ($this->parameterBag->get('app.env') !== 'prod') {
            return;
        }

        $path = $event->getRequest()->getPathInfo();
        $path = rtrim($path, '/');

        foreach (self::PROTECTED_PATHS as $protectedPath) {
            // Build regex php style
            $protectedPath = str_replace('/', '\/', $protectedPath);
            $protectedPath = '/' . $protectedPath . '/';

            preg_match($protectedPath, $path, $match);

            if ($match) {
                throw new NotFoundHttpException();
            }
        }
    }
}
```

Make sure to provide the correct namespace for your use case + have a "app.env" parameter available.

**Comment by ikarolaborda** [comment]
But what about the people who still want to show their documentation? for me, after updating symfony version to 6.2 and PHP to 8.1, i needed to switch the apiResource annotations for attributes, and i got that same problem, but i need the documentation

**Comment by alebedev80** [comment]
Why issue is closed? I can't use build-in OpenAPI doc generator because it's not support multi-language. So, i'm using hand-made specs which hosted on stand-alone domain. How to use JSON-LD without docs? I think framework is some approaches + libraries and recomendation how to use them. User decides by themself what and how to use.

**Comment by alebedev80** [comment]
Solution if need to change 'api_doc' link to any url:

```
api_doc:
  path: 'https://www.google.com'
  schemes: [ 'https' ]
  host: 'www.google.com'
```

**Comment by soyuka** [comment]
>  What if we want jsonld AND not show our documentation ? 

JSON-LD is hypermedia so docs.jsonld should be available no?

About OpenAPI it's different but there should be a flag to disable it. Please open a new issue if the issue persists.

**Comment by awsms** [comment]
> > What if we want jsonld AND not show our documentation ?
> 
> JSON-LD is hypermedia so docs.jsonld should be available no?

If I explicitely disable `enable_docs` in my config, I'm expecting it to be disabled, regardless of standards or conventions.
