### ISSUE TITLE
[GraphQL] Resolve item of sub-class

### ISSUE THREAD

**Issue by TamasSzigeti** [api-platform/core#3951]
**Description**  

I wanted to implement GraphQL interfaces to support querying doctrine discriminated unions, which I have, by decorating the TypeBuilder. But there is a [strict check here](https://github.com/api-platform/core/pull/2655/files#diff-caa33cd51f1f4faab6f5c013c0c5249742fb1d23a2d4aa8db1444e5724da64d1R124) that stops it from working. Everything works just fine when I take that out. Before submitting a PR, I wanted to ask if there is any specific reason this check should not be changed to `is_subclass_of`.

Also, any plans to support this use case? I'd gladly contribute, if I could get some assistance.

Thank you!

**Comment by alanpoulain** [comment]
Hello.
There is a first version for an interface support here: https://github.com/api-platform/core/pull/3306.
I need to take some time to check it properly.
