### ISSUE TITLE
php attribute to configure collection operation item

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#3952]
**API Platform version(s) affected**: dev-master

**Description**  
Not clear, how to use php attribute to configure collection operation item

#[ApiResource(
    collectionOperations: ['"post"={"status"=202}'],
    itemOperations: []
)]

If you add this to documentation it will be very helpfull

**Comment by dunglas** [comment]
Yes updating our docs is on the todo list! Help for this would be very welcome!

**Comment by mitalcoi** [comment]
I will help with pleasure if you advice me how do to it. The way described in my example didn't work for me :(

**Comment by WhiteRabbitDE** [comment]
Does this PR help you? I think this ist what you are looking for.
https://github.com/api-platform/docs/pull/1245/files
