### ISSUE TITLE
Problem in routing in 2.6-beta

### ISSUE THREAD

**Issue by roukmoute** [api-platform/core#3958]
**API Platform version(s) affected**: 2.6.x-dev

**Description**  
Prefix in api_platform configuration is no longer taken into account.

**How to reproduce**  
In 2.5.9, if I write this path:
```php
/**
 * @ApiResource(
 *     itemOperations={},
 *     collectionOperations={
 *          "get"={
 *             "path"="/rapports",
 *         }
 *     }
 * )
 */
```
and this configuration:
```yml
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```
I've got:
![image](https://user-images.githubusercontent.com/2140469/104593188-9967b000-566f-11eb-986d-c99577b00252.png)

Everything is normal.

If I update to `"api-platform/core": "^2.6.x-dev"` (dev-master c37641b), I've got:
![image](https://user-images.githubusercontent.com/2140469/104593846-9a4d1180-5670-11eb-88e8-bda29790e4c7.png)

And this is not only visual, here it is the cURL it gave me:
```sh
curl -X GET "http://localhost:8000/rapports?page=1" -H  "accept: application/json"
```

**Comment by soyuka** [comment]
is fixed at https://github.com/api-platform/core/pull/3956

**Comment by soyuka** [comment]
is fixed at https://github.com/api-platform/core/pull/3956
