### ISSUE TITLE
symfony profiler + subresource breakage on 2.6.0

### ISSUE THREAD

**Issue by yivi** [api-platform/core#3976]
**API Platform version(s) affected**: 2.6.0

**Description**  
With the profiler enabled, queries to subresources break, and the profiler information is not saved (a profiler token is generated, but the data is lost.

**How to reproduce**  
Minimal repo demonstrating the issue here:
https://github.com/yivi/api-platform-bug-subresource-profiler

```
composer create-project symfony/skeleton project
cd project
composer req api
composer req profiler
```

Created two basic `Book` and `Author` entities, with `Book` -> ManyToOne -> `Author`, and `Author::books` marked as subresource:

```
    /**
     * @ORM\OneToMany(targetEntity=Book::class, mappedBy="author")
     * @ApiSubresource
     */
    private $books;
```

Trying:

```
curl -X GET "http://localhost:9898/api/authors/1/books?page=1" -H  "accept: application/ld+json"
```

I get:
[error.log](https://github.com/api-platform/core/files/5860920/error.log)

**Possible Solution**  
Sadly I have no clue. I'll try to dig more tomorrow.

**Additional Context**  
Found out about this mostly because I saw that the profiler data was being disappearing from some requests, which seemed very strange. Going back to 2.5.9 everything works as it should.

**Comment by yivi** [comment]
Seems to be fixed on 2.6.1

**Comment by yivi** [comment]
My mistake, I had set the requirements to 2.5.9 to double check the behavior didn't occur in pre 2.6

Retested on 2.6.1, the issue remains:

![CleanShot 2021-01-31 at 15 06 32](https://user-images.githubusercontent.com/1815039/106386578-ef5d8700-63d5-11eb-9c39-e0ee8db5597a.png)

**Comment by raresserban** [comment]
I think I also have the same issue after updating. But I get the error:
`request.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at F:\Coding\PHP\Sites\caut.mesteri\vendor\symfony\http-kernel\Profiler\FileProfilerStorage.php line 175 {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at F:\\Coding\\PHP\\Sites\\caut.mesteri\\vendor\\symfony\\http-kernel\\Profiler\\FileProfilerStorage.php:175)"} []` from the Profiler.

**Comment by yivi** [comment]
@raresserban  Yes, that error is included in the trace attached above.

On `Symfony\Component\HttpKernel\Profiler\FileProfilerStorage::175` an attempt is made to serialize `ApiPlatform\Core\Bridge\Symfony\Bundle\DataCollector\RequestDataCollector`, which ends up triggering that error.

The changes for `RequestDataCollector` are minimal for this release, so I guess the problem is triggered by a change of behavior up the chain. Only today had some time to dig a bit more, but couldn't find anything definitive yet.

Hoping for someone smarter than me coming along to figure it out. :)

**Comment by soyuka** [comment]
Indeed this is a really weird issue and kinda hard to debug!

**Comment by soyuka** [comment]
Can you try my fix at https://github.com/api-platform/core/pull/4023/files?

**Comment by burned42** [comment]
@soyuka for me that seems to do the trick and my tests are all green with your fix! :rocket:

**Comment by yivi** [comment]
Indeed @soyuka, that does  the trick. 🥇

**Comment by soyuka** [comment]
Don't close this yet I want to dig deeper to find the commit introducing this particular issue.

**Comment by vincentchalamon** [comment]
@soyuka Is this bug still relevant, or did your fix solved it?
