### ISSUE TITLE
Add OrSearchFilter - filter on multiple conditions using OR

### ISSUE THREAD

**Issue by WybrenKoelmans** [api-platform/core#398]
https://gist.github.com/WybrenKoelmans/81179b07ae0a10de30ba

I unfortunately do not have the time right now to make a proper PR, but using the gist above it should be straight forward what I intend. 

The most important lines are 
https://gist.github.com/WybrenKoelmans/81179b07ae0a10de30ba#file-orsearchfilter-php-L153

and the switch changes around
https://gist.github.com/WybrenKoelmans/81179b07ae0a10de30ba#file-orsearchfilter-php-L171

``` yaml
  resource.object.search_filter:
      parent: 'myapi.doctrine.orm.or_search_filter'
      arguments:
        - 'entity.user.name_first': 'partial'
          'entity.user.name_last':  'partial'
          'entity.user.telephone':  'partial'
```

Should give me something like 

``` sql
AND (entity.user.name_first LIKE '%testing%' OR
         entity.user.name_last LIKE '%testing%' OR
         entity.user.telephone LIKE '%testing%')
```

**Comment by theofidry** [comment]
IMO if we add support for the `or` operator we should add support for operators `or`, `and`, `gt(e)`, `lt(e)` and such.

@dunglas if we take this path it would be worth taking some work from [LoopBackApiBundle](https://github.com/theofidry/LoopBackApiBundle). But this will require some work to be fair. Would you want to do it for v2 or v1 too?

**Comment by dunglas** [comment]
@theofidry ok for me to include LoopBackApiBundle in core. Will you target the v1.1 or the v2?

**Comment by WybrenKoelmans** [comment]
Excellent news, this looks promising. Thank you both.

**Comment by theofidry** [comment]
@dunglas not sure I'll look more deeply this weekend. Basically I have two solutions:

1. Finish the support of search on multi-values for the filters and then just merge it to DunglasApiBundle as a brand new filter
2. Change the existing filter to ship with the new features

The 2. is very unlikely without any BC. I need to check it a bit more to be able to tell the easiest path. But it requires a bit of work to finish it, and much more time to ease the integration and check the performance impact.

**Comment by dunglas** [comment]
BC means 2.0 (IMO it would be better to have it in 2.0 as 1.1 is very stable now).

**Comment by theofidry** [comment]
Yep, 1. possibly means merge-able in v1, 2. guaranteed to go be in v2.

I'm gonna take a proper look at that this weekend (too busy this week~)

**Comment by soyuka** [comment]
@theofidry IMO having a case insensitive filter (#384) would concern the same topic, filters. The #384 proposal might not be adequate in the way it's configurated (`ipartial` instead of `partial` + a boolean). Let me know if I can help.

**Comment by theofidry** [comment]
Good reminder, will look into that as well :)

**Comment by Simperfit** [comment]
@theofidry what is missing on this ?

**Comment by mcanepa** [comment]
I'm in the need for this feature in my API; I have to search for a given value in several fields at the same time, so an OR filter will be very much welcome.

Is there any progress on this? some estimated release date?

**Comment by teohhanhui** [comment]
@mcanepa:
> I have to search for a given value in several fields at the same time

Best use a full-text search implementation then. If you're using PostgreSQL, the built-in [Full Text Search](https://www.postgresql.org/docs/current/static/textsearch.html) is a good option.

There are certainly use cases for an `OrFilter`, I just don't think what you've described is one of them.

**Comment by soyuka** [comment]
I agree about the Full Text Search, I've myself implemented a Filter with Oracle Text. 

Anyway, you should try to build your own filter. There is a nice example [here](https://github.com/api-platform/api-platform/pull/237#issuecomment-281947585). You can also check the documentation about filters [here](https://api-platform.com/docs/core/filters#creating-custom-filters) and [here](https://api-platform.com/docs/core/filters#creating-custom-doctrine-orm-filters).

**Comment by Simperfit** [comment]
Are we going to implement it on core @api-platform/core-team

**Comment by soyuka** [comment]
IMO it's not really worth the work (because this is never only a matter of AND or OR). We should advise to build custom filters if someone needs this.

**Comment by Simperfit** [comment]
i'm  -1 on this too, we could help people building their custom one, but that will not be in core :)

**Comment by hbroer** [comment]
Ty for helping on this. Now i know how to use this simple basic functionality with 6 Lines of Configuration. Not.  Now I am building a own filter. That regex example helps very well. Not. ^^ just saying ^^

**Comment by hbroer** [comment]
````PHP
<?php

namespace AppBundle\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\ORM\QueryBuilder;

use Doctrine\Common\Annotations\AnnotationReader;

final class SearchFilter extends AbstractFilter
{
    protected function filterProperty(string $property, $value, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        if ($property === 'search') {
            $this->logger->info('Search for: ' . $value);
        } else {
            return;
        }

        $reader = new AnnotationReader();
        $annotation = $reader->getClassAnnotation(new \ReflectionClass(new $resourceClass), 'AppBundle\\Filter\\SearchAnnotation');

        if (!$annotation) {
            throw new \HttpInvalidParamException('No Search implemented.');
        }

        $parameterName = $queryNameGenerator->generateParameterName($property);
        $search = [];

        foreach ($annotation->fields as $field)
        {
            $search[] = "o.{$field} LIKE :{$parameterName}";
        }

        $queryBuilder->andWhere(implode(' OR ', $search));
        $queryBuilder->setParameter($parameterName, '%' . $value . '%');
    }

    /**
     * @param string $resourceClass
     * @return array
     */
    public function getDescription(string $resourceClass): array
    {
        $description['search'] = [
            'property' => 'search',
            'type' => 'string',
            'required' => false,
            'swagger' => ['description' => 'Searchfilter'],
        ];

        return $description;
    }
}
````

````PHP
<?php

namespace AppBundle\Filter;

use Doctrine\Common\Annotations\Annotation;
use Doctrine\Common\Annotations\Annotation\Target;
use Doctrine\Common\Annotations\AnnotationException;

/**
 * @Annotation
 * @Target("CLASS")
 */
final class SearchAnnotation
{
    public $fields = [];

    /**
     * Constructor.
     *
     * @param array $data Key-value for properties to be defined in this class.
     * @throws AnnotationException
     */
    public function __construct(array $data)
    {
        if (!isset($data['value']) || !is_array($data['value'])) {
            throw new AnnotationException('Options must be a array of strings.');
        }

        foreach ($data['value'] as $key => $value) {
            if (is_string($value)) {
                $this->fields[] = $value;
            } else {
                throw new AnnotationException('Options must be a array of strings.');
            }
        }
    }
}
````
services.yml
````YML
    'AppBundle\Filter\SearchFilter':
        class: 'AppBundle\Filter\SearchFilter'
        autowire: true
        tags: [ { name: 'api_platform.filter', id: 'search' } ]
````
src/AppBundle/Entity/Product.php
````PHP
<?php

namespace AppBundle\Entity;
[...]
use AppBundle\Filter\SearchAnnotation as Searchable;

/**
 * [...]
 * @Searchable({"name", "description", "whatever"})
 */
class Product { [...] }
````

**Comment by benjaminrau** [comment]
Great work @hbroer, that helped me a lot. I changed few things for my usecase:
- annotation now supported properties on relations
- description in swagger documentation contains info which properties are searched
- search is now case-insensitive

src/AppBundle/Filter/SearchFilter.php
```
<?php

namespace AppBundle\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\ORM\QueryBuilder;

use Doctrine\Common\Annotations\AnnotationReader;

final class SearchFilter extends AbstractFilter
{
    protected function filterProperty(string $property, $value, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        if ($property === 'search') {
            $this->logger->info('Search for: ' . $value);
        } else {
            return;
        }

        $reader = new AnnotationReader();
        $annotation = $reader->getClassAnnotation(new \ReflectionClass(new $resourceClass), \AppBundle\Filter\SearchAnnotation::class);

        if (!$annotation) {
            throw new \HttpInvalidParamException('No Search implemented.');
        }

        $parameterName = $queryNameGenerator->generateParameterName($property);
        $search = [];
        $mappedJoins = [];

        foreach ($annotation->fields as $field)
        {
            $joins = explode(".", $field);
            for ($lastAlias = 'o', $i = 0, $num = count($joins); $i < $num; $i++) {
                $currentAlias = $joins[$i];
                if ($i === $num - 1) {
                    $search[] = "LOWER({$lastAlias}.{$currentAlias}) LIKE LOWER(:{$parameterName})";
                } else {
                    $join = "{$lastAlias}.{$currentAlias}";
                    if (false === array_search($join, $mappedJoins)) {
                        $queryBuilder->leftJoin($join, $currentAlias);
                        $mappedJoins[] = $join;
                    }
                }

                $lastAlias = $currentAlias;
            }
        }

        $queryBuilder->andWhere(implode(' OR ', $search));
        $queryBuilder->setParameter($parameterName, '%' . $value . '%');
    }

    /**
     * @param string $resourceClass
     * @return array
     */
    public function getDescription(string $resourceClass): array
    {
        $reader = new AnnotationReader();
        $annotation = $reader->getClassAnnotation(new \ReflectionClass(new $resourceClass), \AppBundle\Filter\SearchAnnotation::class);

        $description['search'] = [
            'property' => 'search',
            'type' => 'string',
            'required' => false,
            'swagger' => ['description' => 'FullTextFilter on ' . implode(', ', $annotation->fields)],
        ];

        return $description;
    }
}
```

**Comment by iCodr8** [comment]
Thank you so much @hbroer. This is exactly what I was looking for. At first I didn't got it working, because the filter definition in the `@ApiResource` annotation was missing.

So I have added this and it works:

```php
/**
 * @ApiResource(
 *     attributes={
 *         "filters"={"search"}
 *     }
 * )
 * @Searchable({"name", "description", "whatever"})
 */
class Product { [...] }
```

And I optimized the search. So you can enter `ones evi` when you are searching `Kevin Jones`
 over multiple fields.

```php
final class SearchFilter extends AbstractFilter
{
    // ... other code

    protected function filterProperty(string $property, $value, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        if ($property === 'search') {
            $this->logger->info('Search for: ' . $value);
        } else {
            return;
        }

        $reader = new AnnotationReader();
        $annotation = $reader->getClassAnnotation(new \ReflectionClass(new $resourceClass), 'AppBundle\\Filter\\SearchAnnotation');

        if (!$annotation) {
            throw new \HttpInvalidParamException('No Search implemented.');
        }

        $parameterName = $queryNameGenerator->generateParameterName($property);
        $searchItems = explode(' ', str_replace('-', ' ', $value));

        if (is_array($searchItems)) {
            $andx = $queryBuilder->expr()->andx();

            foreach ($searchItems as $index => $searchItem) {
                $orx = $queryBuilder->expr()->orx();

                foreach ($annotation->fields as $field) {
                    $orx->add($queryBuilder->expr()->like('o.' . $field, ':' . $parameterName . '_' . $index));
                }

                if ($orx->count()) {
                    $queryBuilder->setParameter($parameterName . '_' . $index, '%' . $searchItem . '%');
                    $andx->add($orx);
                }
            }

            if ($andx->count()) {
                $queryBuilder->andWhere($andx);
            }
        }
    }

    // ... other code
}
```

**Comment by apfz** [comment]
I am doing the above but the filter is never reached. Could anyone have a look at my detailed question regarding this at: https://stackoverflow.com/questions/49372971/custom-filter-api-platform-not-working

**Comment by zakjakub** [comment]
I have same problem as @apfz - filter appears in documentation, but it's never applied. filterProperty() is never reached.

**Comment by apfz** [comment]
unfortunately I did not find a solution for it, so I had to switch to another API framework :(. glad I did though, [filtering is now a breeze](https://loopback.io/doc/en/lb3/Where-filter.html).

**Comment by teohhanhui** [comment]
@zakjakub @apfz Please open another issue for your question. :smile:

**Comment by renta** [comment]
Thanks @hbroer @benjaminrau for your code. I've done a custom OR filter without annotation https://gist.github.com/renta/b6ece3fec7896440fe52a9ec0e76571a

**Comment by soyuka** [comment]
looks good! Be careful with [`LOWER` and performances](https://api-platform.com/docs/core/performance#search-filter) though  :)

**Comment by dardinier** [comment]
Hi @benjaminrau and @iCodr8, I liked both of your ways to do it.

But I need to combine those two features :

- Search on properties :

> annotation now supported properties on relations
From @benjaminrau 

- Search on multiples fields :

> And I optimized the search. So you can enter `ones evi` when you are searching `Kevin Jones`
over multiple fields.
From @iCodr8 

You both chose different ways to do it and today, I am not able to merge it.

How would you imagine it ?

**Comment by teohhanhui** [comment]
@dardinier Use full text search: https://www.postgresql.org/docs/10/textsearch.html

**Comment by vipulw2011** [comment]
> ```
> <?php
> 
> namespace AppBundle\Filter;
> 
> use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter;
> use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
> use Doctrine\ORM\QueryBuilder;
> 
> use Doctrine\Common\Annotations\AnnotationReader;
> 
> final class SearchFilter extends AbstractFilter
> {
>     protected function filterProperty(string $property, $value, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
>     {
>         if ($property === 'search') {
>             $this->logger->info('Search for: ' . $value);
>         } else {
>             return;
>         }
> 
>         $reader = new AnnotationReader();
>         $annotation = $reader->getClassAnnotation(new \ReflectionClass(new $resourceClass), 'AppBundle\\Filter\\SearchAnnotation');
> 
>         if (!$annotation) {
>             throw new \HttpInvalidParamException('No Search implemented.');
>         }
> 
>         $parameterName = $queryNameGenerator->generateParameterName($property);
>         $search = [];
> 
>         foreach ($annotation->fields as $field)
>         {
>             $search[] = "o.{$field} LIKE :{$parameterName}";
>         }
> 
>         $queryBuilder->andWhere(implode(' OR ', $search));
>         $queryBuilder->setParameter($parameterName, '%' . $value . '%');
>     }
> 
>     /**
>      * @param string $resourceClass
>      * @return array
>      */
>     public function getDescription(string $resourceClass): array
>     {
>         $description['search'] = [
>             'property' => 'search',
>             'type' => 'string',
>             'required' => false,
>             'swagger' => ['description' => 'Searchfilter'],
>         ];
> 
>         return $description;
>     }
> }
> ```
> 
> ```
> <?php
> 
> namespace AppBundle\Filter;
> 
> use Doctrine\Common\Annotations\Annotation;
> use Doctrine\Common\Annotations\Annotation\Target;
> use Doctrine\Common\Annotations\AnnotationException;
> 
> /**
>  * @Annotation
>  * @Target("CLASS")
>  */
> final class SearchAnnotation
> {
>     public $fields = [];
> 
>     /**
>      * Constructor.
>      *
>      * @param array $data Key-value for properties to be defined in this class.
>      * @throws AnnotationException
>      */
>     public function __construct(array $data)
>     {
>         if (!isset($data['value']) || !is_array($data['value'])) {
>             throw new AnnotationException('Options must be a array of strings.');
>         }
> 
>         foreach ($data['value'] as $key => $value) {
>             if (is_string($value)) {
>                 $this->fields[] = $value;
>             } else {
>                 throw new AnnotationException('Options must be a array of strings.');
>             }
>         }
>     }
> }
> ```
> 
> services.yml
> 
> ```yaml
>     'AppBundle\Filter\SearchFilter':
>         class: 'AppBundle\Filter\SearchFilter'
>         autowire: true
>         tags: [ { name: 'api_platform.filter', id: 'search' } ]
> ```
> 
> src/AppBundle/Entity/Product.php
> 
> ```
> <?php
> 
> namespace AppBundle\Entity;
> [...]
> use AppBundle\Filter\SearchAnnotation as Searchable;
> 
> /**
>  * [...]
>  * @Searchable({"name", "description", "whatever"})
>  */
> class Product { [...] }
> ```

@hbroer I am beginner to api platform and I want to achieve search in multiple properties i.e OR Filter. Can you please help me configuring it. 
@benjaminrau @iCodr8 If you can also, Please.
Thanks in advance

**Comment by teohhanhui** [comment]
@vipulw2011 Please use the proper channels for support questions. Thanks!

You can ask on the #api-platform channel of Symfony Slack.

**Comment by kacperjurak** [comment]
Using of `ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter` is deprecated.

Please use `ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractContextAwareFilter` instead.

**Comment by masseelch** [comment]
@dardinier I think i wrote a filter you could use: https://gist.github.com/masseelch/47931f3a745409f8f44c69efa9ecb05c

@hbroer, @benjaminrau

**Comment by khaledBou** [comment]
I tried to add the custom search filter to an abstract class but it doesn't   work , i can't instantiate an abstract class, is any solution to prevent the new $resourceClass ?  or maybe a custom search filter for an abstract class ?
