### ISSUE TITLE
openapi_context parameters do not appear

### ISSUE THREAD

**Issue by allphat** [api-platform/core#3989]
**API Platform version(s) affected**: 2.6.0

**Description**  
since v2.6.0 my parameters do not appear in the interface

**How to reproduce**  
If i declare an apiResource in my entity like that:
@ApiResource(
 *     normalizationContext={"groups"={"get"}},
 *     collectionOperations={
 *         "senders"={
 *             "method"="GET",
 *             "path"="/senders/{type}/{media}",
 *             "controller"=GetSenders::class,
 *             "pagination_enabled"=false,
 *             "openapi_context"={
 *                 "summary"="Get senders by type and media",
 *                 "parameters"={
 *                     {
 *                          "description"="Type of sender",
 *                          "name"="type",
 *                          "in"="path",
 *                          "type"="string",
 *                          "required"=true,
 *                          "default"="BOTH"
 *                     },
 *                     {
 *                         "description"="Type of medium",
 *                         "name"="media",
 *                         "in"="path",
 *                         "type"="string",
 *                         "required"=true,
 *                         "default"="EMAIL"
 *                     }
 *                 }
 *             }
 *         }
 *     },
 *     itemOperations={"get"}
 
the 2 parameters appear if I use v2.5.9 but disappear in 2.6.x

Is there something i have to change to make it work?

**Comment by brianvanderwerf1982** [comment]
Confirmed, after upgrade of v2.5.9 to v2.6.x my yaml config of openapi_context stopped working.  
All openapi_context parameters/filters (other then id) disappeared. Other things like requestBody still works.
Didnt see a relation to anything in the changelog that can relate.

**Comment by Cbruyere** [comment]
Regarding the OpenApiFactory : 
```
            $pathItem = $pathItem->{'with'.ucfirst($method)}(new Model\Operation(
                $operationId,
                $operation['openapi_context']['tags'] ?? (OperationType::SUBRESOURCE === $operationType ? $operation['shortNames'] : [$resourceShortName]),
                $responses,
                $operation['openapi_context']['summary'] ?? $this->getPathDescription($resourceShortName, $method, $operationType),
                $operation['openapi_context']['description'] ?? $this->getPathDescription($resourceShortName, $method, $operationType),
                isset($operation['openapi_context']['externalDocs']) ? new ExternalDocumentation($operation['openapi_context']['externalDocs']['description'] ?? null, $operation['openapi_context']['externalDocs']['url']) : null,
                $parameters,
                $requestBody,
                isset($operation['openapi_context']['callbacks']) ? new \ArrayObject($operation['openapi_context']['callbacks']) : null,
                $operation['openapi_context']['deprecated'] ?? (bool) $resourceMetadata->getTypedOperationAttribute($operationType, $operationName, 'deprecation_reason', false, true),
                $operation['openapi_context']['security'] ?? null,
                $operation['openapi_context']['servers'] ?? null
```
that's normally in line with the OpenApi spec's 3.0 ? in fact no more "parameters" key in openapi_context

**Comment by soyuka** [comment]
Thank you for reporting this issue. As this wasn't tested on our earlier Swagger component I forgot to add it. See #4001 for the patch.

**Comment by Cbruyere** [comment]
great, could you fix also the extensionProperties ? thanks for the job.

**Comment by soyuka** [comment]
I think that it's working:

```
$docs = $docs->withExtensionProperty('value', 'Custom x-value value');
dump($docs);
```
