### ISSUE TITLE
Can't get computed fields

### ISSUE THREAD

**Issue by Isos9** [api-platform/core#3991]
**API Platform version(s) affected**: 2.6

**Description**  
The group on collectionOperations is not working for computed fields

**How to reproduce**  

![image (24)](https://user-images.githubusercontent.com/16087932/106110414-f886f380-614a-11eb-9f3f-5ccd1ef53095.png)
![image (25)](https://user-images.githubusercontent.com/16087932/106110402-f45ad600-614a-11eb-8213-8920f3fd0b52.png)

**Additional Context**  
I also tried with another group name only for collection operations, and I get normal fields but not computed.

**Comment by soyuka** [comment]
did you remove the cache? We need more information to reproduce this.
