### ISSUE TITLE
Sorting of the resources in the (OpenApi) docs page

### ISSUE THREAD

**Issue by stiffroy** [api-platform/core#3996]
**API Platform version(s) affected**: 2.6.1

**Description**  
For the OpenApi docs, the resources are no more sorted as before.

**How to reproduce**  
Just download and run the application, create a few api resources and then navigate to the (OpenApi) docs page.

**Possible Solution**  
I have created a pull request at [#3995](https://github.com/api-platform/core/pull/3995) but for some reason the PhpStan check fails. The failure message comes from some ElasticSearch component which does not relate with my commits.

**Additional Context**  
If anyone wants to look into the PhpStan failure message, please feel free.

**Comment by soyuka** [comment]
thanks for the report @stiffroy !
