### ISSUE TITLE
Symfony name converter breaking the OpenApi docs

### ISSUE THREAD

**Issue by stiffroy** [api-platform/core#3997]
**API Platform version(s) affected**: 2.6.1

**Description**  

If we use a Symfony name converter, the docs page is broken. The `Authorize` button on the top left which has been introduced in the version 2.6 is not shown. Also the `Request Body` section (between `Parameters` and `Responses`) under the endpoints are completely missing. So, you cannot also try out any endpoints as this section is completely missing

**How to reproduce**  

Configure Api Platform to use the Symfony's camel-to-snake case converter as documented [here](https://api-platform.com/docs/core/serialization/#name-conversion)
Activate the service:
```
# api/config/services.yaml
services:
    'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter': ~
```
and then use it:
```
# api/config/packages/api_platform.yaml
api_platform:
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
```
Now go and try some of your endpoints from the OpenApi (Swagger) docs. The `Request Body` section will no more show up. And the endpoints cannot be tested anymore.

**Possible Solution**  

Not yet looked into it but my assumption is, something is breaking when this name converter is run. Didn't try yet with custom name convertor.

**Additional Context**  

When trying with some API testing clients like [Postman](https://www.postman.com/), both the parameters `createdAt` as well as `created_at` are working.

**Comment by stiffroy** [comment]
@soyuka Do you have some time to look into this issue too or mention someone who might be better fit?

**Comment by soyuka** [comment]
Can you check using the `2.6` branch? We usually do something like:

```
composer require api-platform/core --prefer-source
cd vendor/api-platform/core
```

Then checkout the 2.6 branch, delete the cache and check if it's fixed? Thanks!

**Comment by stiffroy** [comment]
Hi @soyuka 
I have tried as your recommendation but nothing happens with it. Only by disabling the `name_converter` shows the `Request Body` part. Also, I am not exactly sure about the `Authorize` button on the top right corner (why it is and how it works, etc.) but when the `name_converter` is active, the button disappears.

Without the name converter:

![Screenshot 2021-02-03 at 10 50 36](https://user-images.githubusercontent.com/13282223/106730883-27034380-660f-11eb-8a3c-d28fe767e569.png)

With the name converter:

![Screenshot 2021-02-03 at 10 51 20](https://user-images.githubusercontent.com/13282223/106730937-33879c00-660f-11eb-89a8-8502a498cc21.png)

**Comment by soyuka** [comment]
I'll check what goes on thanks for the report!
