### ISSUE TITLE
requestBody and responseBody in openapi_context not working

### ISSUE THREAD

**Issue by zalesak** [api-platform/core#4000]
**API Platform version(s) affected**: 2.6.X

**Description**  
I am not sure if it is a bug or feature with documentation issue :).

After upgrade from 2.5.x to 2.6.x. requestBody (responses as well) in annotation stops working as described in example here:

https://api-platform.com/docs/core/file-upload/#handling-file-upload

Actually I think there is only one workaround - decorate OpenApiFactory, but this is really too complicated. Having this settings in annotation was very handy.

**How to reproduce**  
Use this example: 
https://api-platform.com/docs/core/file-upload/#handling-file-upload

requestBody in openApi doc, remains the same as without "requestBody" specified.

**Possible Solution**  
add requestBody and responses support to OpenApiFactory

**Additional Context**  
N/A

**Comment by soyuka** [comment]
Thank you for reporting this issue. As this wasn't tested on our earlier Swagger component I forgot to add it. See #4001 for the patch.

**Comment by TheKassaK** [comment]
And what about the response in yml ?
