### ISSUE TITLE
After updating to api platform 2.61 and symfony 5.2.2 any other bundles endpoint is missing

### ISSUE THREAD

**Issue by Jurek-Raben** [api-platform/core#4014]
**API Platform version(s) affected**: 2.6.1

**Description**  
Using api platform 2.5.9 and symfony 5.2.1, the endpoint of the jwt-authentication-bundle and tilleuls/forgot-password-bundle were visible in the swagger docs under /api. After update to 2.6.1, these are gone (not visible anymore, but still working).

**How to reproduce**  
install tilleuls/forgot-password-bundle and lexik/jwt-authentication-bundle using symfony 5.21 and api-platform 2.5.9. Now do a composer update.

**Possible Solution**  
Provide a migration documentation?

EDIT: To be more clear, my own decorator for the authentification endpoint does not work and the endpoints of the bundles.

**Comment by soyuka** [comment]
fixed in #4016
