### ISSUE TITLE
Ability to force json response on bad api endpoints

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#4020]
**Description**  
Not sure if this is a bug or a feature :)

Currently api platform properly responds with json responses on mispelled api endpoints when explicitly "Accept" header is set to json. Otherwise it returns html response.

I'd like this to always respond with json.

**Example**  
https://demo.api-platform.com/books2.json accessing this directly via browser responds with html.

Tried also to force json on route import like:
```
    $routes
        ->import('.', 'api_platform')
        ->prefix('/api')
        ->format('json');
```

Still the same :)

**Comment by dunglas** [comment]
It's because these routes aren't handled by API Platform but by Symfony directly. Maybe Symfony can be configured to send JSON errors by default?

**Comment by norkunas** [comment]
At least API Platform could check if given endpoint is under configured api loader :)
