### ISSUE TITLE
openapi_context: "in"="body" regression in 2.6.2 

### ISSUE THREAD

**Issue by lazka** [api-platform/core#4035]
Upgrade from 2.6.1 to 2.6.2 leads to this error:

I have the following annotations:

```
 *             "openapi_context"={
 *                 "parameters"={
 *                    {"name"="body", "in"="body", "description"="Token", "type"="string", "example"={"token"="foo", "typeId"="bar"}, "required"=true}
 *                 }
 *             },
 ```

It seems that `"in"="body"` no longer works.

It leads to

```
Symfony\Component\PropertyAccess\Exception\AccessException:
The method "ApiPlatform\Core\OpenApi\Model\Parameter::getStyle()" returned "null", but expected type "string". Did you forget to initialize a property or to make the return type nullable using "?string"?

  at vendor/symfony/property-access/PropertyAccessor.php:403
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(array(object(Parameter)), 'style', false)
     (vendor/symfony/property-access/PropertyAccessor.php:93)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue(object(Parameter), 'style')
     (vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:148)
```

**Comment by lazka** [comment]
(also `"required"="true"` also throws an error now, but I fixed that locally to remove the quotes)

**Comment by cacahouwete** [comment]
I think my PR solve your problem about getStyle

https://github.com/api-platform/core/pull/4033

**Comment by cavasinf** [comment]
Same case here, even when following the [DOC](https://api-platform.com/docs/core/openapi/#changing-operations-in-the-openapi-documentation).

And I don't think the DOC is either up to date.

@lazka How did you manage your "body" whitout `schema` ?
Downgrading to `2.6.1` broke my `body` part..

**Comment by cavasinf** [comment]
@cacahouwete Doesn't seems to be the solution,
In the constructor of Parameter, `style` is defined there.
[Parameter contrustor Line](https://github.com/api-platform/core/blob/4b293b0c004597bcf5f6b653d7d464fa71e9d064/src/OpenApi/Model/Parameter.php#L50)

But I don't see the case for `body`, the "nearest" type is `query` ? 🤔

**Comment by cavasinf** [comment]
@lazka  & @cacahouwete 
Looking through `change logs` from 2.6.0, This PR is looking sus #4001.

So I've checked [the Test file for this part](https://github.com/api-platform/core/blob/588ace6004da888a85bb3b728d42670d7d65e013/tests/OpenApi/Factory/OpenApiFactoryTest.php#L70)

And, as I can see `in : "body"` is not a thing anymore.
We need to go through `requestBody` inside of `openapi_context`.

Here my case (with my Entity too) in YAML:

```yaml
App\Entity\construction_site\ConstructionSite:

    [...]

    itemOperations:
        ## GET ##
        get:
            method: 'GET'
        ## PUT ##
        put:
            method: 'PUT'

        ## SetCosu ##
        constructionSite_setCosu:
            method: "PUT"
            path: "construction_sites/{id}/setCosu"
            controller: App\Controller\API\SetConstructionSiteCosu
            security: "is_granted('ROLE_ADMIN')"
            openapi_context:
                summary: "Set cosu on Construction Site"
                description: "Set the cosu of a ConstructionSite"
                parameters:
                    -
                        in: "path"
                        name: "id"
                        description: "Id of ConstructionSite"
                        required: true
                        type: "integer"

                requestBody:
                    description: "Go to 'Schema' to see the description of the body fields"
                    content:
                        application/json:
                            schema:
                                type: "object"
                                required: "cosu"
                                properties:
                                    cosu:
                                        type: "boolean"
                                        description: "True : Disabled | False : Enabled"
                                        example: true
        #######################################
```

The Result:

![image](https://user-images.githubusercontent.com/25293190/107381378-0e9f9700-6aef-11eb-9bc1-cc8c0f192ebd.png)



Note : I think `input_formats` is gone too:

```yaml
constructionSite_setCosu:
            method: "PUT"
            [...]
            input_formats:
                json: "application/json"
```

**Comment by cacahouwete** [comment]
@cavasinf 
If the conditions about setting "style" are not true , then style can be null, there are no default value about style.
Having a correct type hint is important.
Or we have to change conditions to set style to have a default value like "simple" or ...

**Comment by soyuka** [comment]
Hello, finally got time to check this. `body` is not a valid parameter for the `in`, see the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject): 

> REQUIRED. The location of the parameter. Possible values are "query", "header", "path" or "cookie".

The corresponding style: 

> Describes how the parameter value will be serialized depending on the type of the parameter value. Default values (based on value of in): for query - form; for path - simple; for header - simple; for cookie - form.

You should use Swagger (configure the v2 instead of the v3) if you want the old behavior.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/4050 will allow you to specify a style so that it still works.

**Comment by lazka** [comment]
thanks. if https://api-platform.com/docs/core/openapi/#changing-operations-in-the-openapi-documentation was using the new preferred way, that would help me a lot.

**Comment by cavasinf** [comment]
> 
> 
> @cavasinf
> If the conditions about setting "style" are not true , then style can be null, there are no default value about style.
> Having a correct type hint is important.
> Or we have to change conditions to set style to have a default value like "simple" or ...

@cacahouwete You cannot use `body` inside the `in` now.
> REQUIRED. The location of the parameter. Possible values are "query", "header", "path" or "cookie".

You have to go though `openapi_context: requestBody: [...]`.
`style` is automatically defined for `parameters` part IF `in` is equal to "query", "header", "path" or "cookie".
In other case, style is null, and cannot work (your PR shows why : function type return is string and not null)

@soyuka, thanks for your replies. So the current DOC is only for the V2 at the moment ?
It will be nice, to mentionned that in the official DOC 👍

**Comment by yivi** [comment]
If any other poor soul needs to do the same but with an XML configuration file:


```xml
<attribute name="openapi_context">
    <attribute name="requestBody">
        <attribute name="content">
            <attribute name="application/json">
                <attribute name="schema">
                    <attribute name="type">object</attribute>
                    <attribute name="properties">
                        <attribute name="someIntegerProperty">
                            <attribute name="type">integer</attribute>
                        </attribute>
                    </attribute>
                </attribute>
            </attribute>
        </attribute>
    </attribute>
</attribute>
```

Definitely not the prettiest XML possible, but it works.
