### ISSUE TITLE
responses in openapi_context not working

### ISSUE THREAD

**Issue by TheKassaK** [api-platform/core#4038]
**API Platform version(s) affected:** 2.6.2

**Description**

Cant use response in yml like : 

        patch:
            openapi_context:
                responses:
                    '200':
                        description: OK

**Possible Solution**

add responses support

**Comment by tjcalma** [comment]
@TheKassaK for now the solution was to occupy version 2.5

**Comment by guilliamxavier** [comment]
Was that duplicated by #4106, fix released in 2.6.4?
You may also hit #4209, fix ready to be released in the next 2.6.5

**Comment by vincentchalamon** [comment]
Fixed in 2.6.4
