### ISSUE TITLE
"ksort() expects parameter 1 to be array, object given" in OpenApiNormizer (empty project)

### ISSUE THREAD

**Issue by rkeet** [api-platform/core#4047]
**API Platform version(s) affected**: 2.6.2

**Description**  & **How to reproduce**

Have:
- PHP 7.4.*
- Symfony CLI installed

Run :
- `composer create-project symfony/skeleton .`
- `composer require api`
- `symfony server:start -d`

Visit:
- `https://127.0.0.1:8000`

![image](https://user-images.githubusercontent.com/3327864/107332839-f90d7b80-6ab4-11eb-90da-85309fd83d74.png)

**Comment by soyuka** [comment]
The schema is empty an is an ArrayObject indeed because we use `PRESERVE_EMTPY_OBJECTS`. Add an entity and this will go away :). In the meantime a fix is coming.

**Comment by ishu202** [comment]
i created an entity and still getting ksort error. also tried clearing the cache

**Comment by HugoFerrant** [comment]
89 entities, all OK from `doctrine:mapping:info`, and still having the issue

**Comment by HugoFerrant** [comment]
OK I figured out what @soyuka meant by "Add an entity and this will go away :).". He meant "add a resource" which in my case was declaring my existing 89 Entities as ApiResources.
ping @ishu202 at it might fix your issue too :)

**Comment by hydropik** [comment]
> OK I figured out what @soyuka meant by "Add an entity and this will go away :).". He meant "add a resource" which in my case was declaring my existing 89 Entities as ApiResources.
> ping @ishu202 at it might fix your issue too :)

Hello

How are you doing that?

I add "use ApiPlatform\Core\Annotation\ApiResource;" and "#[ApiResource]" to my entities but didn't work.

**Comment by soyuka** [comment]
Btw the fix landed we're working on releasing it asap :)

**Comment by yspef** [comment]
... same error 
PHP 7.3.19 -1~deb10u1
Linux calac 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
Symfony Configuration
5.2.3
Symfony version
dev
Environment

**Comment by Mausino** [comment]
Thank you @soyuka for your fix

https://github.com/api-platform/core/pull/4051 i want only ask... maybe stupid question.. but why when i installed fresh/latest version of Api Platform ($composer require api) the folder in symfony aplication vendor/api-platform there is missing folder TEST

and in this repository in folder test  i see so much other folder.. need i do some other action that i will with installation of api-platform to do ?

**Comment by Grezor** [comment]
Hello 
My version symfony is 5.2.1
PHP version : 8.0

Are there people who have added api platform to their project ? 

I had a problem, during the path of api plaform to access this url : /api

I have replaced this : 
 **replace  " vendor/api-platform/core/src/OpenApi/Serializer/OpenApiNormalizer.php:58 " **

After : 
remplace line 58 
```
  // if ($value) {
  //     ksort($value);
  // }
```
Before : 
```php
    if (is_array($value)) {
        ksort($value);
    } elseif ($value instanceof \ArrayObject) {
        $value->ksort();
    }
```

Are there other solutions to solve this problem?
thank you in advance, 
Have a nice day

**Comment by gunter423** [comment]
There will be a patch ? because it's not a solutions of changed direcly in vendor xD

**Comment by adebsa2401** [comment]
Below is what I did to fix this issue
```
            if ('schemas' === $key) {
                if ($value) {
                    $value->ksort();
                }
            }
```

Just used ArrayObject method ksort() instead of builtin php ksort() function

**Comment by soyuka** [comment]
yes we're releasing asap !
