### ISSUE TITLE
ExpressionLanguage may throw SyntaxError with Authenticator-based security

### ISSUE THREAD

**Issue by Jontsa** [api-platform/core#4055]
**API Platform version(s) affected**: 2.6.*

**Description**  

When using [new Authenticator-based security](https://symfony.com/doc/current/security/experimental_authenticators.html), accessing a resource as anonymous user will throw [SyntaxError](https://github.com/symfony/symfony/blob/v5.2.3/src/Symfony/Component/ExpressionLanguage/Parser.php#L230) if the resource security expression includes _user_, _token_ or _roles_ variable.

For example this was valid before:
```
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *             "method"="GET",
 *             "security"="is_granted('ROLE_MERCHANT') and object.getMerchant() == user.getMerchant()",
 *         },
 *     },
 *     collectionOperations={
 *     }
 * )
```

But if you enable authenticator, it will throw SyntaxError like this:
```
Variable "user" is not valid around position 54 for expression `is_granted('ROLE_MERCHANT') and object.getMerchant() == user.getMerchant()`.`
```

**How to reproduce**  

**Possible Solution**  

In [ResourceAccessChecker](https://github.com/api-platform/core/blob/v2.6.2/src/Security/ResourceAccessChecker.php#L60), use NullToken if no authentication is available.

Replace this
```
if ($token = $this->tokenStorage->getToken()) {
    $variables = array_merge($variables, $this->getVariables($token));
}
```

with
```
$variables = array_merge($variables, $this->getVariables($this->tokenStorage->getToken() ?: new NullToken()));
```

**Additional Context**  

Tested using API-platform 2.6.2 and Symfony 5.2.3

**Comment by mehdibo** [comment]
I have the same issue

**Comment by Jontsa** [comment]
2.6.3 fixes this issue
