### ISSUE TITLE
can't update nested entities while doing patch

### ISSUE THREAD

**Issue by Adrillex** [api-platform/core#4061]
**API Platform version(s) affected**: 2.6.2

**Description**  
After upgrading from api platform 2.5.7 to 2.6.2, updating nested entites using patch request (application/merge-patch+json) result in inserting new nested entities even if id attribute is provided.

**How to reproduce**  
https://github.com/Adrillex/api-platform-2.6-patch-bug

The above project is a simple project with only two entities "resource" and "subresource".
to reproduce the bug : 

- post a resource containing a subresource : 
```
{
    "name": "test",
    "subResources": [
        {
            "name": "test1"
        }
    ]
}
```
- try to PATCH this resource and modify the subresource
`{{baseUrl}}/resources/1`
`Content-Type: application/merge-patch+json`
```
{
    "name": "test",
    "subResources": [
        {
            "id": 1,
            "name": "test2"
        }
    ]
}
```
It result in inserting a new subresource instead of updating the old one (like if the id property wasn't provided) : 
```
{
    "@context": "/contexts/Resource",
    "@id": "/resources/1",
    "@type": "Resource",
    "id": 1,
    "name": "test",
    "subResources": [
        {
            "@id": "/sub_resources/2",
            "@type": "SubResource",
            "id": 2,
            "name": "test2"
        }
    ]
}
```
I noticed that If I do the exact same request using PUT, it works. BTW actually the PUT behavior seems to be exactly the one PATCH should be since I can use PUT to modify a resource without replacing it entirely.
I can also do a POST resource while modifying the subresource, it also works.

It looks like the problem is only with PATCH

**Comment by Charles-Emmanuel-DEZANDEE** [comment]
> **API Platform version(s) affected**: 2.6.2
> 
> **Description**
> After upgrading from api platform 2.5.7 to 2.6.2, updating nested entites using patch request (application/merge-patch+json) result in inserting new nested entities even if id attribute is provided.
> 
> **How to reproduce**
> https://github.com/Adrillex/api-platform-2.6-patch-bug
> 
> The above project is a simple project with only two entities "resource" and "subresource".
> to reproduce the bug :
> 
> * post a resource containing a subresource :
> 
> ```
> {
>     "name": "test",
>     "subResources": [
>         {
>             "name": "test1"
>         }
>     ]
> }
> ```
> 
> * try to PATCH this resource and modify the subresource
>   `{{baseUrl}}/resources/1`
>   `Content-Type: application/merge-patch+json`
> 
> ```
> {
>     "name": "test",
>     "subResources": [
>         {
>             "id": 1,
>             "name": "test2"
>         }
>     ]
> }
> ```
> 
> It result in inserting a new subresource instead of updating the old one (like if the id property wasn't provided) :
> 
> ```
> {
>     "@context": "/contexts/Resource",
>     "@id": "/resources/1",
>     "@type": "Resource",
>     "id": 1,
>     "name": "test",
>     "subResources": [
>         {
>             "@id": "/sub_resources/2",
>             "@type": "SubResource",
>             "id": 2,
>             "name": "test2"
>         }
>     ]
> }
> ```
> 
> I noticed that If I do the exact same request using PUT, it works. BTW actually the PUT behavior seems to be exactly the one PATCH should be since I can use PUT to modify a resource without replacing it entirely.
> I can also do a POST resource while modifying the subresource, it also works.
> 
> It looks like the problem is only with PATCH

+1 
I have the same problem
it's work when I'm use : "id" : "/sub_resources/2"  for the subressource in PATCH method.
but in PUT method "@id" : "/sub_resources/2" works.
it's magic.

**Comment by gonzalovilaseca** [comment]
Same issue here

**Comment by soyuka** [comment]
The behavior explained at https://tools.ietf.org/html/rfc7386#section-3 shows that arrays must be replaced. Therefore this is the sole implementation of the merge-patch specification. The JSON PATCH specification (that is not implemented yet) may help solve that issue (https://tools.ietf.org/html/rfc6902#appendix-A.2). I'm closing this issue and we will follow that at https://github.com/api-platform/core/issues/759
