### ISSUE TITLE
Evaluate ORM\OrderBy for subressources?

### ISSUE THREAD

**Issue by NicoHaase** [api-platform/core#4066]
Through Graphql, we access an entity A with related entities B. The relation is set the following way within A:

    /**
     * @var Collection<string, B>
     *
     * @ORM\OneToMany(targetEntity="B", mappedBy="a", cascade="persist")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private iterable $b;

Data is gathered the following way:

    {
      A(id: "/api/a/id") {
        id
        b {
          edges {
            node {
              id
              position
            }
          }
        }
      }
    }

Even though the relation uses a `OrderBy` annotation, the inner edges are not returned sorted by position. Is this expected behaviour? Through debugging, I've found that `ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\OrderExtension` does not try to check for this annotation, but solely for those given in the operation or configured at the B entity

**Comment by alanpoulain** [comment]
Hello,
This is expected. The order is defined on the related resource.
But maybe it will be an improvement to configure it directly on the property too.
