### ISSUE TITLE
Update spec to OpenApi 3.1

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4069]
OpenAPI 3.1.0 got released https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0

**Comment by shouze** [comment]
@soyuka I'm in to help, from where should I start?

**Comment by Chris53897** [comment]
There are a lot of changes with 3.1.
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0

**format** (whether byte, binary, or base64) is no longer used to describe file payloads. As part of JSON Schema compliance, now contentEncoding and contentMediaType can be used for such specification.

>> Docs should be updated after merging. Example:
https://api-platform.com/docs/core/file-upload/#configuring-the-entity-receiving-the-uploaded-file
