### ISSUE TITLE
JSON-LD : Blank Nodes

### ISSUE THREAD

**Issue by Exalyon** [api-platform/core#4072]
**Description**  
Is it possible to implement Blank Node for the JSON-LD serializer ? https://www.w3.org/TR/json-ld/#identifying-blank-nodes.

I do realise the given section is non normative.

This is a way to identify and refer to node without identifier. This is useful for nested creation who depends on the root node to be fully created (mandatory arguments in the constructor for exemple).

If it is not possible, is there another way to handle the presented request below ?

**Example**  
POST /post
```
{
    "@id": "_:root" // Any name really if I understood the specfication right
    "test": "Lorem ipsum",
    "comments": [
        {
             "post": {"@id": "_:root"}
             "text": "Lorem ipsum"
        }
    ]
}

```

**Comment by soyuka** [comment]
It's already implement, what's missing is a way to handle this id yourself https://github.com/api-platform/core/pull/3946 

The identifier issue you may have is related to https://github.com/api-platform/core/pull/4052 which was merged pending release

**Comment by Exalyon** [comment]
Thank you for your reply.

I misuderstood the recommandation. The blank node as presented are for the serialisation of entities. I thought to use them for the deserialization. That would allow me to handle requests creating nested objects with dependency on the root object. 

Based on the previous exemple, I would be able to create a Comment object which has as a dependency on the created Post object.

Is it possible ? Or may be there is a better way ?

**Comment by soyuka** [comment]
The `@id` is an IRI reprensenting the resource. It should not represent something else (parent etc.). What you want to do probably already works: 

```
POST /api/comment

{"comment": "blabla", "post": "/posts/1"}
```

Will create a comment related to the Post 1. See https://github.com/api-platform/core/blob/main/features/main/relation.feature#L133 for example
