### ISSUE TITLE
Unclear documentation regarding security attribute and (custom?) data providers

### ISSUE THREAD

**Issue by lazka** [api-platform/core#4075]
https://api-platform.com/docs/core/security/ the first example says

> The user must be logged in to interact with Book resources

I was wondering if this is really true and turns out the data providers are still executed even if you don't have the rights. So a GET on a collection might still hit the DB with search queries and only after that is all done returns 401. So the API is easily DOS-able without any auth :/ I fixed this now by duplicating the security attribute to each operation.

Unless I'm missing something...

Imo it would be less confusing if there was a per entity security attribute that gets used for attributes and operations in all cases. In my case I just want `is_granted('IS_AUTHENTICATED_FULLY')` for everything regarding one entity.

**Comment by alanpoulain** [comment]
Why not adding an access control in `security.yaml`?

**Comment by lazka** [comment]
Could you point to an example? https://api-platform.com/docs/core/security/ doesn't mention security.yaml from what I can see.

**Comment by alanpoulain** [comment]
Yes, it is (but it can be missed):
> The API Platform security layer is built on top of the [Symfony Security component](http://symfony.com/doc/current/book/security.html).
> All its features, including [global access control directives](http://symfony.com/doc/current/book/security.html#securing-url-patterns-access-control) are supported.

**Comment by lazka** [comment]
Thanks! oh, so you mean I should restrict things on a per path basis?

Either way I think the docs should be made more clear in that `attributes={"security"="is_granted('ROLE_USER')"},` is not enough to secure an entity.

**Comment by alanpoulain** [comment]
Yes, per path or the whole API path.

I think it depends what "secure" means, but a PR to improve it will be welcomed!

**Comment by lazka** [comment]
by secure I mean "does not interact with the resource". ok, thanks!

**Comment by alanpoulain** [comment]
Closing it for now.
