### ISSUE TITLE
[OpenApi] Response - requestBody is not of type string

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#4080]
**API Platform version(s) affected**: 2.6

**Description**  
When i validate my generated swagger.json using validator.swagger.io  it is not valid because all write operations (post/patch/put) have an element "requestBody" with an empty array as value under the "links" node in responses.

Here is a snipped

``` 
      "patch": {
        "operationId": "patchNoteItem",
        "tags": [
          "Note"
        ],
        "responses": {
          "200": {
            "description": "Note resource updated",
            "content": {
              "application/ld+json": {
                "schema": {
                  "$ref": "#/components/schemas/Note.jsonld-read"
                }
              }
            },
            "links": {
              "GetNoteItem": {
                "operationId": "getNoteItem",
                "parameters": {
                  "uuid": "$response.body#/uuid"
                },
                "requestBody": [],  <--- THIS ONE
                "description": "The `uuid` value returned in the response can be used as the `uuid` parameter in `GET /api/v1/notes/{uuid}`."
              }
            }
          }, 
``` 

I'm not sure if it CAN be an array under this node but i think it has to be string if i understood https://swagger.io/docs/specification/links/ correctly.

I dont think it is used at the moment, its set to [] here --> https://github.com/api-platform/core/blob/b5805a17301db78f10bff92f937b24a2bb6049b3/src/OpenApi/Factory/OpenApiFactory.php#L358

**Possible Solution**  
The value is nullable in the Link model and that would be my suggestion. Set the default to null.

I can setup a PR but i would love to hear what @soyuka thinks since he set this default.

**Comment by soyuka** [comment]
You should check the specification here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#link-object 

This is a bug to me it should be null if not specified.
