### ISSUE TITLE
previous_data of embedded resource unavailable

### ISSUE THREAD

**Issue by MariusJ-micro** [api-platform/core#4081]
**API Platform version(s) affected**: at least ^2.5.7

**Description**  

The `previous_data` object accessible through `request->attributes->get('previous_data')` (or `$context['previous_data']` in APIP 2.6) doesn't contain the `previous_data` of embedded resources. This is an issue for complex validations systems as embedded resource's `previous_data` is unavailable.

For such cases, the only workaround we found is to use `$this->entityManager->getUnitOfWork()->getOriginalEntityData($embeddedResource)` inside a `ConstraintValidator` class at the level of each embedded resource.

**How to reproduce**  
Given a PUT on /foo/1 with body:

```json
{
  "title": "New Title",
  "bars": [
    {
       "@id": "/bars/1",
       "barTitle": "New Bar Title"
    }
  ]
}
```

The previous_data object will be:

```json
{
  "title": "Old Title",
  "bars": [
    {
       "@id": "/bars/1",
       "barTitle": "New Bar Title"
    }
  ]
}
```

**Comment by soyuka** [comment]
Embedded resource? You mean the related objects? This is not supported and will not be as it's too complicated, we don't retrieve these in API Platform and it's related to your persistence. What you did with Doctrine is perfectly fine IMHO.

**Comment by MariusJ-micro** [comment]
Hi soyuka,

Thanks for the answer. What do you mean by this not supported? This is not supported to update a related resource? (in my example = update a related Bar doing a PUT on /foos). Your doc seems to [state the opposite](https://api-platform.com/docs/core/serialization/#denormalization):

> The following rules apply when denormalizing embedded relations:
>
> - If an @id key is present in the embedded resource, then the object corresponding to the given URI will be retrieved through the data provider. Any changes in the embedded relation will also be applied to that object.
> - If no @id key exists, a new object will be created containing data provided in the embedded JSON document.

Is the doc outdated or am I misunderstanding?
