### ISSUE TITLE
422 Unprocessable Entity is now a default for validation errors, but not specified in the documentation

### ISSUE THREAD

**Issue by monteiro** [api-platform/core#4084]
**API Platform version(s) affected**: 2.6.2

**Description**  
The commit https://github.com/api-platform/core/commit/5b2cfdcd8feea9b9ff96371df1a7eeccc72432f4 did a BC of using the status code 422 for validation exceptions. 

In the commit there was no change in the documentation metadata factory, so when generating the documentation, using swagger-ui, it shows only the 400.

<img width="1280" alt="Captura de ecrã 2021-02-19, às 09 15 12" src="https://user-images.githubusercontent.com/74459/108483788-071c8280-7293-11eb-909d-d1f543521325.png">

**How to reproduce**  

Mark the doctrine entity with the `@ApiResource` to have a pre-generated CRUD.
You will see that in any of the methods there is no 422 reference.

And when we execute the API directly in the documentation it says it's not documented:

<img width="836" alt="Captura de ecrã 2021-02-19, às 09 21 16" src="https://user-images.githubusercontent.com/74459/108484566-db4dcc80-7293-11eb-8ddf-a446ce4cbe49.png">

**Possible Solution**  

Probably change the metadata factory and include those by default? 
Can someone point me to the right direction. Don't mind of doing a PR.

**Comment by alanpoulain** [comment]
It needs to be fixed indeed.
It's in the `DocumentationNormalizer` if you want to make the PR.

**Comment by soyuka** [comment]
And in OpenApiFactory :) thanks for the report!

**Comment by monteiro** [comment]
PR is going to be ready shortly.
