### ISSUE TITLE
ksort(): Argument #1 ($array) must be of type array, ArrayObject given

### ISSUE THREAD

**Issue by binita** [api-platform/core#4089]
https://github.com/api-platform/core/blob/v2.6.2/src/OpenApi/Serializer/OpenApiNormalizer.php#L59
I have setup `php 8.0.0` with `symfony 5.2.3` and after doing `composer require api` when I access the `localhost/api`
I got error `ksort(): Argument #1 ($array) must be of type array, ArrayObject given`

I replaced that line 59 with 

```
if (is_array($value)) {
      ksort($value);
}

if ($value instanceof \ArrayObject) {
     $value->ksort();
}
```

Now it is working.

Could someone, please look into this and fix it.

**Comment by soyuka** [comment]
was fixed in #4051 pending release, add resources and this won't happen
