### ISSUE TITLE
Class \Symfony\Component\Security\Core\Role\Role|string) does not exist

### ISSUE THREAD

**Issue by Charl13** [api-platform/core#4090]
**API Platform version(s) affected**: 2.6.2

**Description**  
When implementing `Symfony\Component\Security\Core\User\UserInterface` on a data model a `ReflectionException` with a message "Class \Symfony\Component\Security\Core\Role\Role|string) does not exist" is thrown.

![afbeelding](https://user-images.githubusercontent.com/2190306/108819748-82e03d00-75bb-11eb-889f-f33aa73d52fe.png)

**How to reproduce**  
1. Implement `Symfony\Component\Security\Core\User\UserInterface` on a data model.
2. Register the model as API platform resource.
3. Open /api/docs.

**Possible Solution**
I could track this issue down to this change https://github.com/symfony/security/commit/a9c0831d7e4f6bd2a72edc235bb31e59ec05f995

**Comment by soyuka** [comment]
it looks like the property info phpdoc extractor doesn't support this notation see https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php#L122 
I think that this needs a fix upstream.

**Comment by Charl13** [comment]
I can confirm overriding the method and its PhpDoc works. ✅

**Comment by soyuka** [comment]
Closing as duplicate of https://github.com/api-platform/core/issues/2503
