### ISSUE TITLE
[RFC] Resource configuration inheritance (Sylius)

### ISSUE THREAD

**Issue by alanpoulain** [api-platform/core#4091]
Since [API Platform is used by Sylius](https://sylius.com/blog/new-release-sylius-1-8-with-api-platform-and-loyalty-points-system/), there has been multiple PR to change how the resource configuration is inherited, since Sylius relies heavily on [inheritance of the models](https://docs.sylius.com/en/latest/customization/model.html) to customize it:
- https://github.com/api-platform/core/pull/3711 (merged)
- https://github.com/api-platform/core/pull/3724
- https://github.com/api-platform/core/pull/4012
- https://github.com/api-platform/core/pull/4314
- (https://github.com/api-platform/core/pull/4031) (not really an issue with configuration inheritance)

This issue will centralize them in order to have a global view and to discuss the whole problem.

Sylius made some changes to solve these issues: https://github.com/Sylius/Sylius/pull/12693.

**Comment by soyuka** [comment]
We definitely need to talk about this as we tend to have a policy of "replace" over "merge" as it provides less confusion, less weird issues and ease the maintenance.

**Comment by kayue** [comment]
The current behaviour of Api platform does "replace" some property like `description`, but ignored other like `itemOperations`. This is very weird and unexpected. If ApiPlatform decided to ignore some property it should at least throw a warning "property already defined" or maybe even "model already defined". 

To me as a Sylius developer, I want to be able to at least extend a resource's `itemOperations`, `collectionOperations` or `properties`.

I expect ApiPlatform should work similar to Symfony's routing and security configuration.

**Comment by alanpoulain** [comment]
See also: https://locastic.com/blog/clean-api-configuration-in-sylius/

**Comment by Nek-** [comment]
Hello, just so you know... This kind of system would be interesting for any open source project that want to use API Platform... Or any people that want to enable some features on a given resource based on a flag.

**Comment by laurentdabbb** [comment]
Hi, 
Some news ? 

Does ApiPlatform 3 facilitate config replacement ?

With ApiPlatform 2.7 And Sylius 1.12, we always can't override endpoint normalization groups for exemple. Defining a custom group  just merge groups and not replace it.

Thx

**Comment by soyuka** [comment]
sylius moves to attributes I think that we'll close this as it got improved a lot since then
