### ISSUE TITLE
`ksort() expects parameter 1 to be array, object given` from `src/OpenApi/Serializer/OpenApiNormalizer.php:59` when API documentation was empty.

### ISSUE THREAD

**Issue by Votanar** [api-platform/core#4114]
**API Platform version(s) affected**: 2.6.2

**Description**  
In my project public documentation depends of type of user so sometimes is empty. And:
I get `ksort() expects parameter 1 to be array, object given` from `src/OpenApi/Serializer/OpenApiNormalizer.php:59` when API documentation was empty. The reason is that when there aren't endpoints then we have an empty ArrayObject in `$value` and the ksort function throws an exception.

**How to reproduce**  
Open documentation with no endpoints.

**Possible Solution**  
In `src/OpenApi/Serializer/OpenApiNormalizer.php:58` in condition add object checking and do some another code for `ArrayObject` or find where is setting empty `ArrayObject` and change to empty array.

**Comment by soyuka** [comment]
has been fixed, pending release just add an  ApiResource and it'll be gone :)
