### ISSUE TITLE
OperationPathResolver deprecation notice

### ISSUE THREAD

**Issue by mtaylor567** [api-platform/core#4121]
**API Platform version(s) affected**: 2.6.3

**Description**  
the 4th parameter is commented out, so I get this '4th parameter' deprecation notice which is a bit annoying

https://github.com/api-platform/core/blob/main/src/PathResolver/OperationPathResolver.php

**How to reproduce**  
implementing OperationPathResolver.php

**Possible Solution**  
remove notice or uncomment parameter

**Comment by alanpoulain** [comment]
You need to use the fourth parameter in order to remove the deprecation.

**Comment by mtaylor567** [comment]
how do I do that when it's commented out?

**Comment by alanpoulain** [comment]
You just need to call it like there is a fourth parameter.

**Comment by mtaylor567** [comment]
ah, phpstorm...thanks
