### ISSUE TITLE
Context-dependent normalization/denormalization serializer groups

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#413]
Given:
`(Offer)-[:addOn]->(Offer)`

It is desired that the parent `Offer` should be normalized using the `offer_read` serializer group, but the child `Offer`s should use a different group e.g. `add_on_offer_read`.

How can this be achieved in a general way?

**Comment by dunglas** [comment]
The only way for such specifics needs is to create a custom normalizer decorating the `ItemNormalizer` and changing dynamically the context.

**Comment by teohhanhui** [comment]
I wonder if the Serializer can be made to support dynamic serializer groups, much like the Validator. Just a thought... But of course we don't have something like the JSR-303 here...

**Comment by dunglas** [comment]
It should be possible to add this feature with the new infrastructure of the serializer. PRs welcome :-)

**Comment by teohhanhui** [comment]
What about this kind of relation?

(Place)-[:containsPlace]->(Place)

Is it possible to specify that `Place`s under the `containsPlace` relation should be serialized only as a link?

**Comment by kbsali** [comment]
@teohhanhui did you manage to get around this in V2?

I have a very similar issue which i could easily solve in V1, but in V2 i'm stuck and don't seem to be able to find a solution... any help appreciated! /ping  @dunglas

**Comment by dunglas** [comment]
@kbsali this is now easy but it lacks docs. You can decorate this service: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/api.xml#L48 using Symfony services decorators and it should fit your needs.

Btw, I seen on Gitter that you have found broken links and issues with priority of events in the doc. Can you open PRs to fix them or bugs on the docs repository? Thanks!

**Comment by kbsali** [comment]
yep, awesome! I did try to decorate the service but i was missing the "decorates" option of the DI component (http://symfony.com/doc/current/service_container/service_decoration.html)!

Thanks for the hint! :)

**Comment by Simperfit** [comment]
Closing this, @kbsali if this is not documented could you please open an issue/PR on the documentation ;) ?
