### ISSUE TITLE
Call to a member function getClassMetadata() on null

### ISSUE THREAD

**Issue by grzegorz-stolarz** [api-platform/core#4188]
**API Platform version(s) affected**: v2.6.3
**Description**  
Fails on new Entity of new namespace, works for other, but for this one not.

**How to reproduce**  
`<?php

declare(strict_types=1);

namespace App\Contact\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use App\Program\Entity\Client;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Ramsey\Uuid\UuidInterface;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Validator\Constraints as Assert;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;

/**
 * @ORM\Entity()
 */
#[ApiResource]
#[ApiFilter(
    OrderFilter::class,
    properties: [
        'client',
        'email',
        'phoneNumber',
        'jobTitle',
],
    arguments: [
        'orderParameterName' => 'order'
    ]
)
]
#[ApiFilter(
    DateFilter::class,
    properties: [
        'createdAt',
        'updatedAt',
    ]
)
]
#[ApiFilter(
    SearchFilter::class,
    properties: [
        'client' => 'partial',
        'email' => 'partial',
        'phoneNumber' => 'partial',
        'jobTitle' => 'partial',
    ]
)
]
class Contact
{
    use TimestampableEntity, BlameableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private UuidInterface $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class)
     * @ORM\JoinColumn(columnDefinition="client_id", referencedColumnName="id", nullable=false)
     */
    private Client $client;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private string $email;

    /**
     * @ORM\Column(type="phone_number", nullable=true)
     * @AssertPhoneNumber()
     */
    private ?string $phoneNumber;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $jobTitle;

    public function getId(): UuidInterface
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    public function getJobTitle(): ?string
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?string $jobTitle): void
    {
        $this->jobTitle = $jobTitle;
    }
}
`

**Comment by norkunas** [comment]
That's probably because your doctrine registry can't find a manager for your entity, try to configure mapping for doctrine to that path

**Comment by grzegorz-stolarz** [comment]
> That's probably because your doctrine registry can't find a manager for your entity, try to configure mapping for doctrine to that path

Yes, You're right, I'll close issue.
