### ISSUE TITLE
[RFC] v2 metadata - confusing naming of interfaces and classes

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#420]
The new names do not convey the correct semantics (a case of over-correcting for succinctness?) and are therefore highly confusing.

I propose the following changes:

| Current                                                           | Proposed                                      |
|-------------------------------------------------------------------|-----------------------------------------------|
| ...\Metadata\Property\CollectionMetadata                          | PropertyCollectionMetadata                    |
| ...\Metadata\Property\Factory\CollectionMetadataFactoryInterface  | PropertyCollectionMetadataFactoryInterface    |
| ...\Metadata\Property\Factory\ItemMetadataFactoryInterface        | PropertyMetadataFactoryInterface              |
| ...\Metadata\Property\ItemMetadata                                | PropertyMetadata                              |
| ...\Metadata\Resource\CollectionMetadata                          | ResourceCollectionMetadata                    |
| ...\Metadata\Resource\Factory\CollectionMetadataFactoryInterface  | ResourceCollectionMetadataFactoryInterface    |
| ...\Metadata\Resource\Factory\ItemMetadataFactoryInterface        | ResourceMetadataFactoryInterface              |
| ...\Metadata\Resource\ItemMetadata                                | ResourceMetadata                              |

(and relevant changes of the same fashion elsewhere)

Additional proposal for naming implementation classes:

| Current                                                               | Proposed                                      |
|-----------------------------------------------------------------------|-----------------------------------------------|
| ...\Metadata\Property\Factory\CollectionMetadataAnnotationFactory     | AnnotationPropertyCollectionMetadataFactory   |
| ...\Metadata\Property\Factory\ItemMetadataAnnotationFactory           | AnnotationPropertyMetadataFactory             |
| ...\Metadata\Property\Factory\ItemMetadataSerializerFactory           | SerializerPropertyMetadataFactory             |
| ...\Metadata\Resource\Factory\CollectionMetadataAnnotationFactory     | AnnotationResourceCollectionMetadataFactory   |
| ...\Metadata\Resource\Factory\ItemMetadataAnnotationFactory           | AnnotationResourceMetadataFactory             |
| ...\Metadata\Resource\Factory\ItemMetadataOperationFactory            | OperationResourceMetadataFactory              |
| ...\Metadata\Resource\Factory\ItemMetadataPhpDocFactory               | PhpDocResourceMetadataFactory                 |
| ...\Metadata\Resource\Factory\ItemMetadataShortNameFactory            | ShortNameResourceMetadataFactory              |

**Comment by teohhanhui** [comment]
@dunglas @sroze

**Comment by dunglas** [comment]
Why not, I agree that having to add `as` statements when using both Resource and Property metadata is annoying.

**Comment by teohhanhui** [comment]
Additional proposal for naming implementation classes:

| Current                                                               | Proposed                            |
|-----------------------------------------------------------------------|-------------------------------------|
| ...\Metadata\Property\Factory\CollectionMetadataAnnotationFactory     | AnnotationMetadataCollectionFactory |
| ...\Metadata\Property\Factory\ItemMetadataAnnotationFactory           | AnnotationMetadataFactory           |
| ...\Metadata\Property\Factory\ItemMetadataSerializerFactory           | SerializerMetadataFactory           |
| ...\Metadata\Resource\Factory\CollectionMetadataAnnotationFactory     | AnnotationMetadataCollectionFactory |
| ...\Metadata\Resource\Factory\ItemMetadataAnnotationFactory           | AnnotationMetadataFactory           |
| ...\Metadata\Resource\Factory\ItemMetadataOperationFactory            | OperationMetadataFactory            |
| ...\Metadata\Resource\Factory\ItemMetadataPhpDocFactory               | PhpDocMetadataFactory               |
| ...\Metadata\Resource\Factory\ItemMetadataShortNameFactory            | ShortNameMetadataFactory            |

**Comment by teohhanhui** [comment]
Added implementation class naming examples.

**Comment by teohhanhui** [comment]
I've realized that my proposal of `MetadataCollection` is wrong, because it's not a collection of metadata but just metadata of the class/resource.

**Comment by teohhanhui** [comment]
Updated with proposal closer to current naming scheme.

**Comment by dunglas** [comment]
Currently:

* ResourceCollectionMetadata: the list of available resources classes (class names)
* ResourceItemMetadata: details about a specific resource class (its IRI, operations...)
* PropertyCollectionMetadata: the list of properties of a given resource (property names)
* PropertyItemMetadata: details of a specific property (IRI, required, ...)

It took me a lot of time to find explicit names, I prefer to keep them as close as possible than current ones (e.g: just add a Resource or Property prefix). WDYT?

:+1:  to move the relevant part of factories first. It makes more sense.

**Comment by sroze** [comment]
I definitely agree with all these changes!

| Current                                                           | Proposed                                      |
|-------------------------------------------------------------------|-----------------------------------------------|
| ...\Metadata\Property\CollectionMetadata                          | PropertyCollectionMetadata                    |
| ...\Metadata\Property\Factory\CollectionMetadataFactoryInterface  | PropertyCollectionMetadataFactoryInterface    |
| ...\Metadata\Property\Factory\ItemMetadataFactoryInterface        | PropertyMetadataFactoryInterface              |
| ...\Metadata\Property\ItemMetadata                                | PropertyMetadata                              |
| ...\Metadata\Resource\CollectionMetadata                          | ResourceCollectionMetadata                    |
| ...\Metadata\Resource\Factory\CollectionMetadataFactoryInterface  | ResourceCollectionMetadataFactoryInterface    |
| ...\Metadata\Resource\Factory\ItemMetadataFactoryInterface        | ResourceMetadataFactoryInterface              |
| ...\Metadata\Resource\ItemMetadata                                | ResourceMetadata                              |
| ...\Metadata\Property\Factory\CollectionMetadataAnnotationFactory     | AnnotationPropertyCollectionMetadataFactory   |
| ...\Metadata\Property\Factory\ItemMetadataAnnotationFactory           | AnnotationPropertyMetadataFactory             |
| ...\Metadata\Property\Factory\ItemMetadataSerializerFactory           | SerializerPropertyMetadataFactory             |
| ...\Metadata\Resource\Factory\CollectionMetadataAnnotationFactory     | AnnotationResourceCollectionMetadataFactory   |
| ...\Metadata\Resource\Factory\ItemMetadataAnnotationFactory           | AnnotationResourceMetadataFactory             |
| ...\Metadata\Resource\Factory\ItemMetadataOperationFactory            | OperationResourceMetadataFactory              |
| ...\Metadata\Resource\Factory\ItemMetadataPhpDocFactory               | PhpDocResourceMetadataFactory                 |
| ...\Metadata\Resource\Factory\ItemMetadataShortNameFactory            | ShortNameResourceMetadataFactory              |

**Comment by teohhanhui** [comment]
There's still this discrepancy that bugs me with the new naming system...

| Hydra                 | ApiPlatform           |
|-----------------------|-----------------------|
| Collection            | Resource              |
| different Collections | ResourceCollection    |
| resource              | item                  |

**Comment by teohhanhui** [comment]
Perhaps we can change `Resource` to `ResourceType` or `ResourceClass`?

But I'd actually prefer `Resource` -> `ResourceCollection` (and `Item` -> `Resource`) if we can get rid of the `ResourceCollection` (the way I see it could be a `ResourceCollectionRegistry` or `ResourceTypeRegistry`, if we move away from using the concept of metadata for that).

**Comment by dunglas** [comment]
As Hydra isn't mandatory anymore, it doesn't hurt me to have our own terminology.

ResourceCollectionMetadata / ResourceMetadata / PropertyCollectionMetadata / PropertyMetadata

**Comment by teohhanhui** [comment]
ResourceCollectionMetadata and PropertyCollectionMetadata are potentially misleading names... And as far as I can see, currently they are nothing more than glorified wrappers around an array. I'm not sure what future extensions you have in mind for them, but I suspect they won't turn out to fit the "metadata" concept well...

**Comment by dunglas** [comment]
They are basically `ArrayObject` indeed (and will be kept as is). What is misleading with the name? It's a list of resource name (data about data => basically metadata).

**Comment by teohhanhui** [comment]
I can understand that we're using "Resource" to refer to the type (similar to Doctrine "Entity"), but ResourceCollection - that's just confusing because in our case Resource indeed refers to (the type of) a collection of resources. So the terminology is overloaded.

**Comment by dunglas** [comment]
It's not a collection of resource. It's a collection of resource name.

**Comment by teohhanhui** [comment]
By the way, while you're correct going by the definition, it's not useful to refer to those lists as metadata. They are only lists of names - names that correlate to their own metadata.

PropertyMetadata: metadata on a property
ResourceMetadata: metadata on a resource

PropertyCollectionMetadata: metadata on a collection of properties (Metadata on a list? that's too meta - why not just PropertyNameCollection? That describes exactly what it is.)

**Comment by dunglas** [comment]
Ok for PropertyNameCollection / ResourceNameCollection

**Comment by teohhanhui** [comment]
> It's not a collection of resource. It's a collection of resource name.

I know. I was referring to the commonly used terminology in REST - a collection of resources.
