### ISSUE TITLE
Pagination for Symfony Controller

### ISSUE THREAD

**Issue by Mausino** [api-platform/core#4202]
API Platform contain pagination with many options.
Should be great if will possible easy this function of API Platform possible to use in Symfony Controller or EntityRepository to manage query from/to database

**Comment by WhiteRabbitDE** [comment]
You can use something like https://github.com/KnpLabs/KnpPaginatorBundle for the pagination in a controller. It is pretty straight forward to use with an api platform api.

Or did i miss your question ?

**Comment by Mausino** [comment]
@WhiteRabbitDE i know and i am using KpnPaginatorBundle  but i only thanked, if has API Platform build in the pagination and other functions.. why must be used only with api requests and why can't be reused inside Symfony as part of API Platform. I don't talking only about pagination other great extensions.

My idea is simple. why if you install one package via flex you can't reuse the parts inside Symfony on other parts of your project, but you must still install new packages.

My idea is only to change the view on why we must still install something new if we have it in packages but by it design it is not possible reuse it in other code of your project.

I am only newbie.. all PHP is about reusable code (i see everywhere: don't repeat yourself :+1: ) but for me are packages of Symfony as castle where you have only one gate and you can use only for one purpose as was designed
