### ISSUE TITLE
Warning: Undefined array key "content" Open Api Factory

### ISSUE THREAD

**Issue by djpremier** [api-platform/core#4209]
**API Platform version(s) affected**: 2.6.4
**API Platform version(s) with work**: 2.6.3

**Description**  

```Warning: Undefined array key "content"```

**How to reproduce**  

Add JWT Authentication according to the tutorial:
https://api-platform.com/docs/core/jwt/#jwt-authentication

**Possible Solution**  

**Additional Context**  

![image](https://user-images.githubusercontent.com/17091381/114449051-b4808800-9baa-11eb-9544-4666132fe123.png)

I don't know exactly how the problem arose, but from what I tracked it seems to involve these pull requests:
https://github.com/api-platform/core/pull/4138
https://github.com/api-platform/core/pull/4116

**Comment by alanpoulain** [comment]
Which response doesn't have a `content` key? But the fix is alright since only the `description` key is mandatory.

**Comment by guilliamxavier** [comment]
> Which response doesn't have a `content` key?

204 "No Content", for example 😄

**Comment by nnikolay** [comment]
Hi guys, when this fix will go online? 10x
