### ISSUE TITLE
Entity boolean propery is always true in openapi docs

### ISSUE THREAD

**Issue by evotodi** [api-platform/core#4211]
**API Platform version(s) affected**: 2.6.4

**Description**  
An entity with a boolean property that has a default value of false will always show in the openapi docs as true. This can be worked around by annotating the property with `@ApiProperty(attributes={"openapi_context"={"type"="boolean", "example"="false", "default"="false"}})` but is not ideal.
The default value for string, int, and array is properly shown in the docs.

**How to reproduce**  
Clone: [https://github.com/evotodi/ApiBooleanTest.git](https://github.com/evotodi/ApiBooleanTest.git)
_note: this is the symfony skeleton with composer require api as per the [getting started docs](https://api-platform.com/docs/distribution/)_
`composer install`
`bin/console doctrine:database:create`
`bin/console doctrine:schema:create`
`php -S 127.0.0.1:8000 -t public`

**Possible Solution**  
None at this time. I have looked through Api Platform's source but am unable to find where the property default values are collected.

**Additional Context**  

PHP Version 7.4
Adding @var bool annotation does not fix the issue.

**Entity**
![Screenshot 2021-04-13 122558](https://user-images.githubusercontent.com/1625853/114587231-73907e00-9c53-11eb-8c40-72f88e46ea3d.png)
**Api Docs**
All shown boolean values should show as false.
All operations show the same example data and Post/Patch "try it out" also has incorrect defaults.
![Screenshot 2021-04-13 122517](https://user-images.githubusercontent.com/1625853/114587223-712e2400-9c53-11eb-994e-a61111fc9e38.png)

**Comment by guilliamxavier** [comment]
> The default value for string, int, and array is properly shown in the docs.

except for "empty" values, respectively `""`, `0` and `[]`, for which `"default"`/`"example"` is not added to the schema (and Swagger-UI shows e.g. `"string"`, from [there](https://github.com/swagger-api/swagger-ui/blob/v3.46.0/src/core/plugins/samples/fn.js)). But that's actualy on purpose, see #3882 (for which there seems to be no workaround if the fix were to be reverted). I had the same issue as you (bool `= false`), and the workaround can be shortened to `@ApiProperty(openapiContext={"default": false})`

**Comment by evotodi** [comment]
@guilliamxavier  Thank you for the information!
Am I missing something or does this not fix at least the boolean properties?

```
From 6a36b676b2832b2ada2be42476888bb99e3df130 Mon Sep 17 00:00:00 2001
From: evotodi <evotodi@gmail.com>
Date: Tue, 13 Apr 2021 14:50:01 -0400
Subject: [PATCH] Issue #4211 Fix

Signed-off-by: evotodi <evotodi@gmail.com>
---
 src/JsonSchema/SchemaFactory.php | 13 +++++++++++--
 1 file changed, 11 insertions(+), 2 deletions(-)

diff --git a/src/JsonSchema/SchemaFactory.php b/src/JsonSchema/SchemaFactory.php
index b518c308..536d492b 100644
--- a/src/JsonSchema/SchemaFactory.php
+++ b/src/JsonSchema/SchemaFactory.php
@@ -200,8 +200,17 @@ final class SchemaFactory implements SchemaFactoryInterface
             $propertySchema['externalDocs'] = ['url' => $iri];
         }
 
-        if (!isset($propertySchema['default']) && !empty($default = $propertyMetadata->getDefault())) {
-            $propertySchema['default'] = $default;
+        if(!isset($propertySchema['default'])){
+            $default = $propertyMetadata->getDefault();
+            if(!is_null($propertyMetadata->getType()) && $propertyMetadata->getType() instanceof Type && $propertyMetadata->getType()->getBuiltinType() == Type::BUILTIN_TYPE_BOOL){
+                if(null !== $default){
+                    $propertySchema['default'] = $default;
+                }
+            }else{
+                if(!empty($default)){
+                    $propertySchema['default'] = $default;
+                }
+            }
         }
 
         if (!isset($propertySchema['example']) && !empty($example = $propertyMetadata->getExample())) {
-- 
2.27.0.windows.1
```

![Screenshot 2021-04-13 145156](https://user-images.githubusercontent.com/1625853/114605571-371b4d00-9c68-11eb-8089-797a6076f6c3.png)
![Screenshot 2021-04-13 145242](https://user-images.githubusercontent.com/1625853/114605577-38e51080-9c68-11eb-9f29-33f7b957e692.png)

**Comment by guilliamxavier** [comment]
You're looking at the "Example Value", but you should also look at the "Schema" (corresponding to the actual docs, from which Swagger-UI generates an example value).
Moreover I think it would be inconsistent to special-case `bool` in the SchemaFactory just because Swagger-UI uses `true` by default in the "Example Value" (by the way you can see that for `array` it uses `[ "string" ]` by default) (also you will always need a custom openapi_context if you want a default/example `null`), and the argument about `private string $foo = '';` and `private int $bar = 0;` in https://github.com/api-platform/core/issues/3882#issuecomment-811266198 could be made for `private bool $qux = false;` too...
Incidentally, I have found a related ticket on their repository: https://github.com/swagger-api/swagger-ui/issues/4964, their answer:
> some environments omit parameters defined as false, so we default to true. You're free to override that if you'd like to!

So, although I had the same problem, I fear we cannot really "revert" #3887 (even partially) without having a way to *remove* an auto-generated default/example from the schema 😔

**Comment by evotodi** [comment]
> You're looking at the "Example Value", but you should also look at the "Schema" (corresponding to the actual docs, from which Swagger-UI generates an example value).

I did look at the schema and yup it shows exactly as it should. All false.
![Screenshot 2021-04-15 162806](https://user-images.githubusercontent.com/1625853/114934201-9c597480-9e07-11eb-9534-ac6d0e1a8a7b.png)

> Moreover I think it would be inconsistent to special-case `bool` in the SchemaFactory just because Swagger-UI uses `true` by default in the "Example Value" (by the way you can see that for `array` it uses `[ "string" ]` by default). Incidentally, I have found a related ticket on their repository: [swagger-api/swagger-ui#4964](https://github.com/swagger-api/swagger-ui/issues/4964), their answer:

I did have code for all incorrect types but decided for the sake of this conversation it was to much noise to read through if I was not on the correct track. The inconsistency comes when as typed or annotated variable with a default value is not displayed with that default value and is inaccurately shown to the user. 

Thanks for the catch on the nullable bool. This code fixes that, and fixes the non-default boolean to the swagger default of true.
```
diff --git "a/src/JsonSchema/SchemaFactory.php" "b/src/JsonSchema/SchemaFactory.php"
index b518c308..19146741 100644
--- "a/src/JsonSchema/SchemaFactory.php"
+++ "b/src/JsonSchema/SchemaFactory.php"
@@ -200,8 +200,21 @@ final class SchemaFactory implements SchemaFactoryInterface
             $propertySchema['externalDocs'] = ['url' => $iri];
         }
 
-        if (!isset($propertySchema['default']) && !empty($default = $propertyMetadata->getDefault())) {
-            $propertySchema['default'] = $default;
+        if(!isset($propertySchema['default'])){
+            $default = $propertyMetadata->getDefault();
+            if(!is_null($propertyMetadata->getType()) && $propertyMetadata->getType() instanceof Type && $propertyMetadata->getType()->getBuiltinType() == Type::BUILTIN_TYPE_BOOL){
+                if($propertyMetadata->getType()->isNullable()){
+                    $propertySchema['default'] = $default;
+                }else{
+                    if(!is_null($default)){
+                        $propertySchema['default'] = $default;
+                    }
+                }
+            }else{
+                if(!empty($default)){
+                    $propertySchema['default'] = $default;
+                }
+            }
         }
 
         if (!isset($propertySchema['example']) && !empty($example = $propertyMetadata->getExample())) {
```

Your comment in [#3882-comment](https://github.com/api-platform/core/issues/3882#issuecomment-811266198) is a fine example but could also be solved by a custom validation for those infrequent cases.

My issue is that if a variable has a type and has a default value that default value should be used in the docs and not forced to something else. Yes the annotations can set the default value but that just causes inconsistency in code. Imagine this scenario...

```
/**
 * @ORM\Column(type="integer")
 * @ApiProperty(attributes={"openapi_context"={"type"="interger", "example"="5", "default"="5"}})
 */
public $myVar = 2;

/**
 * @ORM\Column(type="integer")
 * @Assert\Positive()
 */
public int $myPositiveVar = 0;
```

And the user posts to an endpoint with the following json expecting myVar to be 5:
```
{
  "myPositiveVar": 9
}
```
and they get back:
```
{
  "myVar": 2,
  "myPositiveVar": 9
}
```
I can just see them scratching their heads and cussing at the developer.
