### ISSUE TITLE
After upgrade to 2.6.4 - swagger "Request body schema" uses defined "output dto"

### ISSUE THREAD

**Issue by tecbird** [api-platform/core#4212]
**API Platform version(s) affected**: 2.6.4
**Description**  
Request schema is replaced with response model (dto)
And response shows also JsonLd attributes (on plain json, xml)

**How to reproduce**  
Create an "POST" endpoint with output dto

**Possible Solution**  
Downgrade to 2.6.3

**Additional Context**  
Swagger output (Request and Response uses same dto - makes no sense)
![image](https://user-images.githubusercontent.com/16688055/114671897-e0178580-9d04-11eb-89fd-355ad9b85b64.png)

Endpoint yaml:

> resources:
    App\DTOs\Erp\Import\Article\Availability\Articles:
        shortName: 'Availability'
        description: 'Import availability (stocks)'
        attributes:
            security: 'is_granted("IP_ACCESS")'
            security_message: 'Sorry, access forbidden'
            route_prefix: '/erp'
            formats:
                xml: [ 'application/xml', 'text/xml' ] # xml first - so it's default!
                json: [ 'application/json' ]
                jsonld: [ 'application/ld+json' ]
            denormalization_context:
                groups: [ 'write' ]
            normalization_context:
                groups: [ 'read' ]
        collectionOperations:
            post:
                path: '/import/availability/stock'
                status: 201
                output: App\DTOs\Erp\Generic\ResponseDto
                validation_groups:
                    - 'Default'
                    - 'write'
        itemOperations: [ ]

**Comment by RobinHoutevelts** [comment]
Confirmed. The same is happing with me after I upgrade to `2.6.4`

**Comment by TheKassaK** [comment]
Same here, without an outpt, but the denormalization_context group is not used for a POST route.

The shema is generated from the normalization_context group

**Comment by jamesisaac** [comment]
Yes getting the same issue.  Like said above it seems to be using the normalization_context instead of denormalization_context for the type of the Request Body.

I think I've narrowed it down to this PR: #4138 - reverting the contents of `OpenApiFactory.php` to as they were before that PR was merged solves the problem.  CC @soyuka (PR author).

**Comment by tecbird** [comment]
Thanks to all. Closing it in favor of #4138, #4213
