### ISSUE TITLE
OpenAPI documentation response examples are always in jsonld

### ISSUE THREAD

**Issue by bram123** [api-platform/core#4235]
**API Platform version(s) affected**: 2.6.4

**Description**  
When looking at the generated openapi documentation, only the jsonld schemas are actually used. It does generate a schema without the jsonld fields (@id/@type/@context) but these are never referenced.
And looking at the paths/[url]/[method]/responses/[statuscode]/content section, all formats use the .jsonld schema.

**How to reproduce**  
https://demo.api-platform.com/ & https://demo.api-platform.com/docs.json will show this same behaviour.

Opening the first endpoint (GET /books) and scrolling through the media types in the responses section, always shows the jsonld example schema value, even for application/json or text/csv.
Even though when trying the endpoint you get a different response format.

**Comment by guilliamxavier** [comment]
This looks like a complementary description of #4215, isn't it?

**Comment by bram123** [comment]
ah ye sorry.. Will close this one.
