### ISSUE TITLE
Unexpected deprecations when using Doctrine Inflector 1.4.3

### ISSUE THREAD

**Issue by vla74** [api-platform/core#4249]
**API Platform version(s) affected**: 2.5.10, 2.6.4

**Description**  
After updating API Platform from 2.5.7 to 2.5.10 (or 2.6.4) in my Symfony based project, I get hundreds of additional deprecation notices coming from the legacy Doctrine Inflector.

**How to reproduce**  
My project uses Doctrine/Inflector v1.4.3.
The project defines some APIs with API platform (v2.5.10 or 2.6.4).
APIs are tested through PHPunit and ApiTestCase client.
When running PHPunit I observe these new deprecation notices:
```
514x: The "Doctrine\Common\Inflector\Inflector::tableize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.
463x: The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.
```

**Possible Solution**  
#3564 aimed at solving this kind of deprecations through an Inflector facade which used the new Doctrine/Inflector implementation if present, and falled back to the legacy one otherwise.

As Doctrine/Inflector 1.4.3 defines both the new and the legacy implementation, the new implementation was called by default and no deprecation arose.

But #3903 swapped the facade's implementation so that the legacy inflector is called by default if present, which is the case with Doctrine/Inflector 1.4.3... 

IMO the original semantics of #3564 was smarter as far as progressive migration to the new Doctrine/Inflector code is concerned. In this respect the CI issue of #3903 should probably be addressed another way (for example @dunglas suggested disabling PHPstan for the concerned line).

**Comment by guilliamxavier** [comment]
Totally agree that reversing the condition #3903 was a wrong decision, even more so when it was only to work around a limitation of PHPStan

**Comment by vla74** [comment]
Thank you for the fix @guilliamxavier
