### ISSUE TITLE
denormalization does not ignore type enforcement for not nullable relationship fields.

### ISSUE THREAD

**Issue by felipyamorim** [api-platform/core#4250]
**API Platform version(s) affected**: 2.6.4

**Description**  

When i use the this config, the option "disable_type_enforcement" does not work for not nullable relationship fields.

Possible related issue: https://github.com/api-platform/api-platform/issues/1786

```
denormalization_context:
    disable_type_enforcement: true
```

**How to reproduce**  
```
    /**
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity=Foo::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $foo;
```

Send null value for the field in a post operation.

**Possible Solution**  
Allow denormalization process ignore type enforcement even when field is not nullable, like this:

```
        if (null === $value && ($type->isNullable() || $context[static::DISABLE_TYPE_ENFORCEMENT] ?? false)) {
            return $value;
        }
```
**Additional Context**

**Comment by guilliamxavier** [comment]
From https://github.com/api-platform/core/pull/1957, API Platform's behavior is supposed to match Symfony's. What happens when using the Symfony Serializer directly? (i.e. something like `$symfonySerializer->denormalize(['foo' => null], MainEntity::class)`)

**Comment by felipyamorim** [comment]
I tested using this code, and it worked as expected, accepted null value for not nullable relationship fields.


```
        $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader())));
        $serializer = new Serializer([$normalizer]);

        $idioma = $serializer->denormalize(
            ['tipoIdioma' => null],
            Idioma::class,
            null,
            ['groups' => ['write']]
        );
```

**Comment by guilliamxavier** [comment]
I forgot in my "something like", obviously you should add `'disable_type_enforcement' => true` to the context (last arg to denormalize()).  But you say it works even without, so the problem may be elsewhere...

Anyway it appears now that you're probably not giving enough information: your entity snippet is too incomplete (getter/setter? `ApiResource` annotation?...), and most importantly, what precise error do you get?

**Comment by felipyamorim** [comment]
Sorry, my mistake, i'll exemplify better.

When i send a single post request with the property "tipoIdioma" with null value, the api give me the following error: **"Expected IRI or nested document for attribute \"tipoIdioma\", \"NULL\" given."**

```
/**
 * @ApiResource(
 *     attributes={"pagination_client_items_per_page"=true},
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}, "disable_type_enforcement"=false}
 * )
 * @ApiFilter(OrderFilter::class, properties={"tipoIdioma.dsTipoIdioma"}, arguments={"orderParameterName": "order"})
 * @ORM\Entity(repositoryClass=IdiomaRepository::class)
 * @ORM\Table(name="tb_idioma")
 */
class Idioma
{
	
    /**
     * @Groups({"read", "write"})
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity=TipoIdioma::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $tipoIdioma;
    
    public function getTipoIdioma(): ?TipoIdioma
    {
        return $this->tipoIdioma;
    }

    public function setTipoIdioma(?TipoIdioma $tipoIdioma): self
    {
        $this->tipoIdioma = $tipoIdioma;

        return $this;
    }    
}

```

**Comment by felipyamorim** [comment]
Someone ? Is that a bug?

**Comment by guilliamxavier** [comment]
Just noticed your `@ApiResource` `denormalizationContext` `"disable_type_enforcement"` is `false` (not `true`), typo?

Anyway, there are many open issues, maybe you will get more attention if you provide a failing test (PHPUnit or Behat) and propose a fix (PR) (no guarantee but if you have some time...)

**Comment by felipyamorim** [comment]
Yes, my mistake, I already corrected the post.

I had found a workaround using service decorator, but I lost the issue link :/
