### ISSUE TITLE
composer require api don't work

### ISSUE THREAD

**Issue by nicodmf** [api-platform/core#4259]
Since today, when i launch

```
composer require api
```

i have this message :

```
[UnexpectedValueException]
"api" is not a valid alias. Did you mean one of these:
    "symfony/gatewayapi-notifier", supported aliases: "gatewayapi-notifier", "gatewayapinotifier"  
    "symfony/smsapi-notifier", supported aliases: "smsapi-notifier", "smsapinotifier"
```
 An idea ?
 
NB: Symfony was previously installed with `composer create-project symfony/skeleton folder`

**Comment by chalasr** [comment]
This one can be closed I think, https://github.com/symfony/recipes/issues/941 was the problem and it has been fixed.
