### ISSUE TITLE
Input/Output Dtos not working as expected in swagger and admin/client generator

### ISSUE THREAD

**Issue by simocheccoli** [api-platform/core#4272]
**API Platform version(s) affected**: v2.6.4

**Description**  
I have implement custom dtos as documentation: Greetin is a ApiResourse Entity that has a specific Dto for input and output for POST and PUT vebs.

```
/**
 * This is a dummy entity. Remove it!
 *
 * @ORM\Entity
 *
 * @ApiResource(
 *     collectionOperations={
 *         "create"={
 *             "method"="POST",
 *             "input"=CreateGreeting::class,
 *             "output"=GreetingOutput::class
 *         },
 *         "get"
 *     },
 *     itemOperations={
 *          "get",
 *          "delete",
 *          "put"={
 *             "method"="PUT",
 *             "input"=UpdateGreeting::class,
 *             "output"=GreetingOutput::class
 *          }
 *     }
 * )
 */
final class Greeting
{
    /**
     * The entity ID
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * A nice person
     *
     * @ORM\Column
     */
    public string $name = '';

    public function getId(): ?int
    {
        return $this->id;
    }
}

```

**How to reproduce**  
https://github.com/simocheccoli/test-sample-api-platform is a sample project api-platform generated, clone it and run docker containers and:
- **api platform api works perfectly**
- Swagger documentation wrong: POST and UPDATE has output field in body request : https://github.com/simocheccoli/test-sample-api-platform/blob/main/Swagger.png
-  Admin PWA has wrong form field in creation (3 field instead only one and is a merge about CreateDto, Entity and Output Dto) : https://github.com/simocheccoli/test-sample-api-platform/blob/main/Admin%20Create.png
-  Admin PWA has wrong form field in update but api works well (3 field instead only one and is a merge about CreateDto, Entity and Output Dto) : https://github.com/simocheccoli/test-sample-api-platform/blob/main/Admin%20Update.png
**Possible Solution**  
Dto is created as documentation, api works well, maybe is a bug abou Hydra and Swagger parsers?

**Additional Context**  
Nothin

**Comment by guilliamxavier** [comment]
Is this yet another duplicate of #4212?

**Comment by simocheccoli** [comment]
Not entirely, perhaps for the OpenApi context.

But what about Hydra ?

Look: [Create.png](https://github.com/simocheccoli/test-sample-api-platform/blob/main/Admin%20Create.png) [Update.png](https://github.com/simocheccoli/test-sample-api-platform/blob/main/Admin%20Update.png)

**Comment by simocheccoli** [comment]
I can confirm that Swagger is working as expected.

Hydra is not working: Dtos Input field are merged in create and update context (see Create.png Update.png).

I also have pushed this update to https://github.com/simocheccoli/test-sample-api-platform: it's a dummy use about Dto and Transformer for single operation verbs

**Comment by guilliamxavier** [comment]
It seems that https://github.com/simocheccoli/test-sample-api-platform/commit/0285c2d7a740f388e436049969f66063c1afd9a4 has updated to `dev-main`, maybe you must use `2.6.x-dev` rather than `^2.6@dev` 😕 

As for Hydra I don't know (only OpenAPI), sorry

**Comment by simocheccoli** [comment]
ok @guilliamxavier, i've changed the apiplatform core version to `2.6.x-dev` but the problem persists.
How can help me in this reasolution about Hydra? maybe i can help

**Comment by bettinz** [comment]
Hello @simocheccoli and @guilliamxavier same issue here:
I've 1 entity (News) and 2 DTOs for input/output; right now if I read my hydra I see each property repeated 3 times and I think it's because api-platform read each DTO as a separated entity. Do you know a fix for this?

**Comment by simocheccoli** [comment]
Any update on this? @guilliamxavier

**Comment by guilliamxavier** [comment]
@bettinz, @simocheccoli: Again, I don't use the Hydra admin (currently), only Swagger/OpenAPI, so it's no use pinging me 😕

**Comment by nicodmf** [comment]
Same problem here with swagger. The dev version works... When can we hope a stable version ?

**Comment by simocheccoli** [comment]
nothing new?
