### ISSUE TITLE
`before` and `strictly_after` parameters of DateFilter do not work right

### ISSUE THREAD

**Issue by sidz** [api-platform/core#4283]
**API Platform version(s) affected**: 2

**Description**  
[Documentation](https://api-platform.com/docs/core/filters/#date-filter) says that:
> The `after` and `before` filters will filter including the value whereas `strictly_after` and `strictly_before` will filter excluding the value.

Let say we have 3 records with dates: _2021-05-18_, _2021-05-19_ and _2021-05-20_

First case with `before` parameter: 
We try to find all records where dates _before_ 2021-05-19 date and based on the documentation I'd expect that API Platform returns 2 records with 2021-05-18 and 2021-05-19 but it returns 2021-05-20 only.

Second case with `strictly_after` parameter:
We try to find all records where dates _strictly_after_ 2021-05-19 date and based on the documentation I'd expect that API Platform returns 2021-05-20 record but it returns 2021-05-19 and 2021-05-20.

It happens due to https://github.com/api-platform/core/blob/main/src/Bridge/Doctrine/Orm/Filter/DateFilter.php#L143 DateTime/DateTimeImmutable creates an object with zero hours, minutes and seconds in case of date passed as a value.

**Possible Solution**
Set time to 23 hours, 59 minutes and 59 seconds in case _before_ or _strictly_after_ parameter is passed.
In this case DateFilter should not support filtering by date and time.
Introduce DateTimeFilter

this is for sure will be a BC break.

**Comment by norkunas** [comment]
> this is for sure will be a BC break.

it could be avoided with type detection because apip already maintains a list of supported types and it could check if it's a date or datetime

**Comment by sidz** [comment]
@norkunas unfortunatelly doctrine type can be `datetime_immutable` for example in case I would like to store Last Login At. But I would like to filter all records just by date.

**Comment by norkunas** [comment]
> @norkunas unfortunatelly doctrine type can be `datetime_immutable` for example in case I would like to store Last Login At. But I would like to filter all records just by date.

oh yes, then this is a different case :)
