### ISSUE TITLE
Updating embedded object with PATCH operation

### ISSUE THREAD

**Issue by KableCH** [api-platform/core#4293]
**API Platform version(s) affected**: v2.5.6

**Description**  
In a project I have two entities `Person` and `Address`, where `Address` is related to `Person` via ManyToOne. They look like this (shortened for brevity):

**Person.php**
```
/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 * @ApiResource(
 *      ...
 * )
 */
class Person
{
    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="person", orphanRemoval=true, cascade={"persist", "remove"})
     * @Groups({"user:read", "user:write"})
     */
    private $addresses;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setPerson($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            // set the owning side to null (unless already changed)
            if ($address->getPerson() === $this) {
                $address->setPerson(null);
            }
        }

        return $this;
    }
}
```

**Address**
```
/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 * @ApiResource(
 *    ...
 * )
 */
class Address
{
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"address:read", "address:write", "user:read", "user:write"})
     */
    private $country;

    /**
     * @ORM\ManyToOne(targetEntity=Person::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $person;

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(?Person $person): self
    {
        $this->person = $person;

        return $this;
    }
}
```

I want to be able to create new addresses at when posting to the `Person` collection, and update addresses when patching/putting a `Person` item. POST and PUT endpoints work as expected, as in, new Address items are created when posting and Address items are updated when putting. But when using PATCH, a new Addess is created and persisted and the old one is deleted by orphan removal, even when passing `@id`. Here is the request body I used (same for both operations):
```
{
  "firstName": "John",
  "lastName": "Smith",
  "addresses": [
    {
      "@id": "/api/addresses/1",
      "city": "New York",
      "street": "736 Manor Station St.",
      "country": "USA"
    }
  ]
}
```

And here the responses I got:
**PUT**:
```
{
  "@context": "/api/contexts/Person",
  "@id": "/api/people/1",
  "@type": "Person",
  "firstName": "John",
  "lastName": "Smith",
  "addresses": [
    {
      "@id": "/api/addresses/1",
      "@type": "Address",
      "city": "New York",
      "street": "736 Manor Station St.",
      "country": "USA"
    }
  ]
}
```

**PATCH**
```
{
  "@context": "/api/contexts/Person",
  "@id": "/api/people/1",
  "@type": "Person",
  "firstName": "John",
  "lastName": "Smith",
  "addresses": [
    {
      "@id": "/api/addresses/2",
      "@type": "Address",
      "city": "New York",
      "street": "736 Manor Station St.",
      "country": "USA"
    }
  ]
}
```
Note the @id's aren't the same

**How to reproduce**  
I created a fresh symfony project, installed api platform via `composer require api`, created the two entities (code above) and got the same behaviour when running the requests above.

**Additional Context**  
I am not sure if this is a bug or intended behaviour, but the I couldn't find anything in the api platform docs that would indicate that PATCH doesn't support updating embedded objects.

**Comment by soyuka** [comment]
> I can confirm that the related object is added to the relation collection as completely new. Thus without orphanRemoval, you'll have an additional object in the collection afterwards. With orphanRemoval=true, you'll have all previously related objects dropped and replaced with the objects you sent with the PATCH request. Notice that dropped here seriously means that the previous objects are completely dropped from the database.

Please understand that this is how the [Merge PATCH format](https://datatracker.ietf.org/doc/html/rfc7386) works. I think that you'd need this implementation instead: https://github.com/api-platform/core/issues/759. Let me know if I'm wrong and I'll reopen this issue.

**Comment by mbrodala** [comment]
@soyuka I am open for anything which works and tries to stick to standards as much as possible. The less workarounds and hacks we have, the better. So I'll have an eye on the mentioned issue.

**Comment by ahmed-bhs** [comment]
In case where we have an embed OneToMany relation, event with PUT method, the elements of the array collection will not be merged! And non specified elements going to be deleted  I tried with Patch same behavior :/ @MarcDiaz did you find any solution how to patch relation properties !?

**Comment by MarcDiaz** [comment]
> @MarcDiaz did you find any solution how to patch relation properties !?

@ahmed-bhs Unfortunately no, so I have used PUT instead of PATCH to update embedded relations without remplacements. And when you update a property that is a relation, yes you must send all related objects, else they are removed.

In API Platform 3 (and 2.7), you'll be able to add an object without resending all the elements of the collection, if I have well understood, thanks to the addition of POST/PUT/DELETE on subresouces.

**Comment by mbrodala** [comment]
Or `HttpOperation::PATCH` to avoid magic strings, indeed.

**Comment by erikkubica** [comment]
It's me again, not sure if it works after all. 

I am doing _PATCH {{url}}/api/v1/ambulances/1_
```
{
    "name": "Test ambulance"
    "availability": [
        {
            "@id": "/api/v1/ambulance_availabilities/22",
            "ambulance": "/api/v1/ambulances/1",
            "range": {
                "from": "2023-08-01T00:00:00+00:00",
                "to": "2023-08-15T23:59:59+00:00"
            },
            "availabilityRecords": [
                {
                    "@id": "/api/v1/ambulance_availability_records/33",
                    "range": {
                        "from": "09:00",
                        "to": "17:00"
                    },
                    "procedures": [],
                    "dayOfWeek": 1,
                    "doctor": "/api/v1/doctors/1",
                    "public": true
                }
            ]
        }
    ]
}
```

The ID of my availability is getting iterated and the data is getting duplicated in the database recreating all the child relationships as well. 

If I add "id: 22" under "@id" of my availability, the response for the PATCH request contains:
    "availability": [
        "/api/v1/ambulance_availabilities/1"
    ],
    
    how does availability with ID 22 and @id of 22, become ID 1  "/api/v1/ambulance_availabilities/1" ?

Its super duper messed up.

**Comment by MonkeyKiki** [comment]
I don't if it's a good idea but I had to modify code like this to make it works for the subelements :

```
        if (
            isset($data['@id']) && (
                $context['operation']?->getMethod() === HttpOperation::METHOD_PATCH ||
                $context['root_operation']?->getMethod() === HttpOperation::METHOD_PATCH
            )
        ) {
            unset($context[AbstractNormalizer::OBJECT_TO_POPULATE]);
        }
```

**Comment by erikkubica** [comment]
@MonkeyKiki thanks man, in my case operation is an undefined array key, however after adding some issets, it looks promising. its late at night, will test it in more detail tomorrow and let you know!

**Comment by erikkubica** [comment]
It seems to work but not deep enough, in our use-case we have an Ambulance that has AvailabilityGroups and those have AvailabilityRecords (yep a nice big form). When I PATCH the ambulance with the groups and records, groups are no longer re-created which is the expected behavior, but the availability records inside the availability group are getting recreated, which means relations targeting the records themselves are being unset which might cause issues. I will set up xdebug to see what's going on.

**Comment by mbrodala** [comment]
You can use `($context['root_operation'] ?? $context['operation'])?->getMethod()` as a shorter version but yeah, we had to do the same update due to https://github.com/api-platform/core/pull/5743

**Comment by soyuka** [comment]
Is there an issue here? please open a new one if needed an note that merge patch doesn't update embeded collections.

**Comment by mdieudonne** [comment]
Author of: [#5587](https://github.com/api-platform/core/issues/5587)
I am still encoutering the problem with the latest release, Updating embedded object with PATCH operation does not work for me.
Sticking to PUT (legacy PATCH behavior) when manytomany relation is involved.

**Comment by mskoric** [comment]
The Problem is still present in v3.3.11 . I traced the problem down to the `ObjectToPopulateTrait`.
`context[AbstractNormalizer::OBJECT_TO_POPULATE]` is always the `PersistentCollection`, so the calling normalizer  

AbstractItemNormalizer:L233 wont get the correct object, thus interpreting it as "this must be a new resource".

My workaround is to use the above code with a slight change.


```

<?php

declare(strict_types=1);
namespace App\Serializer\Normalizer;

use ApiPlatform\Metadata\HttpOperation;
use ApiPlatform\Metadata\Patch;
use App\Entity\LaboratorySystemRequest;
use App\Entity\LaboratorySystemRequestItem;
use App\Entity\LaboratorySystemRequestNote;
use Doctrine\ORM\PersistentCollection;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\SerializerAwareInterface;
use Symfony\Component\Serializer\SerializerInterface;

final class PatchAwareItemNormalizer implements NormalizerInterface, DenormalizerInterface, SerializerAwareInterface
{
    public function __construct(
        private readonly NormalizerInterface $decorated,
    ) {
        if (!$decorated instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException(
                sprintf('The decorated normalizer must implement the %s.', DenormalizerInterface::class)
            );
        }
    }

    public function supportsNormalization($data, string $format = null, array $context = []): bool
    {
        return $this->decorated->supportsNormalization($data, $format, $context);
    }

    public function normalize(
        $object,
        string $format = null,
        array $context = []
    ): array|bool|string|int|float|null|\ArrayObject {
        return $this->decorated->normalize($object, $format, $context);
    }

    public function supportsDenormalization($data, string $type, string $format = null, array $context = []): bool
    {
        if (!$this->decorated instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException(
                sprintf('The decorated normalizer must implement the %s.', DenormalizerInterface::class)
            );
        }

        return $this->decorated->supportsDenormalization($data, $type, $format, $context);
    }

    public function denormalize($data, string $type, string $format = null, array $context = []): mixed
    {
        if (!$this->decorated instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException(
                sprintf('The decorated normalizer must implement the %s.', DenormalizerInterface::class)
            );
        }

        $iri = $data['@id'] ?? null;
        $operation = $context['operation'] ?? null;
        $rootOps = $context['root_operation'] ?? null;


        if (is_a($operation, Patch::class) || is_a($rootOps, Patch::class)) {
            if ($context[AbstractNormalizer::OBJECT_TO_POPULATE] instanceof PersistentCollection) {
                if (null !== $iri) {
                    $id = explode('/', $iri);
                    $id = (int)array_pop($id);

                    foreach ($context[AbstractNormalizer::OBJECT_TO_POPULATE] as $object) {
                        if ($object->getId() === $id) {
                            $context[AbstractNormalizer::OBJECT_TO_POPULATE] = $object;
                        }
                    }
                }
                else {
                    unset($context[AbstractNormalizer::OBJECT_TO_POPULATE]);
                }
            }
        }

        return $this->decorated->denormalize($data, $type, $format, $context);
    }

    public function setSerializer(SerializerInterface $serializer): void
    {
        if ($this->decorated instanceof SerializerAwareInterface) {
            $this->decorated->setSerializer($serializer);
        }
    }
    public function getSupportedTypes(?string $format): array
    {
        return [
            LaboratorySystemRequestItem::class => true,
            LaboratorySystemRequestNote::class => true
        ];
    }
}

```

The crucial part:
```

 if (is_a($operation, Patch::class) || is_a($rootOps, Patch::class)) {
            if ($context[AbstractNormalizer::OBJECT_TO_POPULATE] instanceof PersistentCollection) {
                if (null !== $iri) {
                    $id = explode('/', $iri);
                    $id = (int)array_pop($id);

                    foreach ($context[AbstractNormalizer::OBJECT_TO_POPULATE] as $object) {
                        if ($object->getId() === $id) {
                            $context[AbstractNormalizer::OBJECT_TO_POPULATE] = $object;
                        }
                    }
                }
                else {
                    unset($context[AbstractNormalizer::OBJECT_TO_POPULATE]);
                }
            }
        }
```
The idea behind that is to provide the correct object to the "context". So the later processing get the correct Object from the context. If there is no matching id, we need to remove the collection from the context, to get the desired result (create a new record).

@mdieudonne maybe you can try to use the above code and confirm that it its working with your relations
