### ISSUE TITLE
[Mercure] - Add possibility to set a normalisation context within the "options" of the entity.

### ISSUE THREAD

**Issue by Xusifob** [api-platform/core#4298]
**Description**  
Mercure is great to send data... but it is not flexible when it comes to handling normalisation context.
Using it with a JSON:API app for example, it is complicated to set the "include" within the option.
I would like the possiblity to add in my "mercure options" a new key "context" that will be merged to the normalization context of the resource.

**Example**  
```php
// src/Entity/Message.php
    /**
     * @return array
     */
    public function getMercureOptions()
    {

    
       $topics = ["foo","bar"];

        return [
            "private" => true,
            "topics" => $topics,
            "context" => [
                'api_included' => ["foo"],
                'groups' => ['foo','bar']
            ]
        ];
    }
```
If needed, I have already a working example on local, I can create a PR

**Comment by soyuka** [comment]
In my opinion you should just write your own Mercure updates listener (https://github.com/api-platform/core/blob/main/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php) and add groups there :).
