### ISSUE TITLE
Getting a nested collection using GraphQL with authentication

### ISSUE THREAD

**Issue by entermix** [api-platform/core#4299]
**API Platform version(s) affected**: 2.6.4

**Description**  
I have 2 entities:

```
User
Book
```

Both entities are exposed as API resources (I am using DTO)

I want to allow only admins to view the collections of both entities, but I also need to be able to get the nested collection:

```
query {
    user(id: "/api/users/01F63NKKN7DWYB74K6G5N33DPP") {
    id
    books{
      edges{
        node{
          id
        }
      }
    }
    }
}
```

`Result: Access Denied.`

I can get a collection using REST (without authorization, knowing the user ID ), but how do I get a collection using GraphQL?

Is this expected behavior, or is it a bug? 

**How to reproduce**  

```
//src/Entity/User.php
#[ApiResource(
    collectionOperations: [
    'get' => [
        'security' => 'is_granted("ROLE_ADMIN")'
    ],
],
    graphql: [
    'collection_query' => [
        'security' => 'is_granted("ROLE_ADMIN")'
    ],
    'item_query',
],
    itemOperations: [
    'get',
],
    denormalizationContext: ['groups' => ['user:write']],
    normalizationContext: ['groups' => ['user:read']],
    output: UserOutput::class
)]
```

```
//src/Entity/Book.php
#[ApiResource(
    collectionOperations: [
    'get' => [
        'security' => 'is_granted("ROLE_ADMIN")'
    ],
],
    graphql: [
    'collection_query' => [
        'security' => 'is_granted("ROLE_ADMIN")'
    ],
    'item_query',
],
    itemOperations: [
    'get',
],
    denormalizationContext: ['groups' => ['book:write']],
    normalizationContext: ['groups' => ['book:read']],
    output: BookOutput::class
)]
```

```
//src/Dto/UserOutput.php
final class UserOutput
{
    #[Groups(['user:read', 'book:read'])]
    public Ulid $id;

    ...

    /** @var Book[] */
    #[Groups(['user:read'])]
    public iterable $books;
}
```

```
//src/Dto/BookOutput.php
final class BookOutput
{
    #[Groups(['book:read', 'user:read'])]
    public Ulid $id;

    #[Groups(['book:read'])]
    public User $user;

    ...
}
```

**Possible Solution**  
...

**Additional Context**  
https://stackoverflow.com/questions/67672843/how-do-i-get-a-nested-collection-correctly-using-graphql

**Comment by alanpoulain** [comment]
Have you seen https://github.com/api-platform/core/pull/4143?

**Comment by entermix** [comment]
I looked at the documentation

https://github.com/api-platform/docs/pull/1338/files

It seems that this is not quite what we need. I don't quite understand how this can be done with the help of voters.

Purpose: to provide the ability to view resources for everyone who knows their identifiers.
For example: if we have a user ID, we need to provide information about the user and his collection of books.

It would seem that this is a simple task and it can be easily solved using REST, but in order to get a list of user's books using GraphQL, we must open access to the entire list, otherwise there will be an access error.
