### ISSUE TITLE
API Platform schema bug in OpenApi

### ISSUE THREAD

**Issue by abdounikarim** [api-platform/core#4305]
**API Platform version(s) affected**: 2.6.4

**Description**  
Hello, i think there's a problem on the documentation generated by OpenAPI.
On `delete`, `post`, `put` and `patch` operations, the request body use the normalization_context schema instead of the denormalization_context schema.

**How to reproduce**  
Just see it in API Platform Demo, using the Review resource

**Possible Solution**  

**Additional Context**  
![image](https://user-images.githubusercontent.com/15892761/120785049-0996a580-c52d-11eb-8a30-a054eedc6390.png)
I think the schema should be `Review.jsonld-review.write` instead of `Review.jsonld-review.read`

A little precision : the bug appears only when we use `denormalization_context` and `normalization_context`. This works when we only use `denormalization_context`.

**Comment by smepti** [comment]
Related to [#1892](https://github.com/api-platform/api-platform/issues/1892)
