### ISSUE TITLE
itemsPerPage = 0 causes error

### ISSUE THREAD

**Issue by pauljura** [api-platform/core#4312]
**API Platform version(s) affected**: 2.6.3

**Description**  
I have enabled the "itemsPerPage" parameter with annotation @ApiResource(paginationClientItemsPerPage=true) and if I set itemsPerPage=0 then no validation is performed and the value of zero is passed through to the database query, which throws an exception (for SQL Server, haven't tested MySQL yet)

**How to reproduce**  
See above

**Possible Solution**  
Have some validation somewhere to ensure that itemsPerPage >= 1

I don't think setting an invalid "itemsPerPage" should throw an exception. If the requested itemsPerPage is > paginationMaximumItemsPerPage then it silently gets set to paginationMaximumItemsPerPage and I'm OK with that. So if itemsPerPage < 1 then I think it should silently get set to 1, or to the default paginationItemsPerPage, either is OK.

**Additional Context**  
Generated query ends with "OFFSET 0 ROWS FETCH NEXT 0 ROWS ONLY"

Error is:
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The number of rows provided for a FETCH clause must be greater then zero.

**Comment by jonag** [comment]
On some on our projects we do this (a request with itemsPerPage set to 0) to perform a "count" without retrieving any data. Changing this behaviour could have a small (but yet noticeable) impact on performance.
