### ISSUE TITLE
OpenApiNormalizer fails on Entity with `paths` property 

### ISSUE THREAD

**Issue by tassilogroeper** [api-platform/core#4318]
**API Platform version(s) affected**: 2.6

**Description**  
Introduced in `v2.6`, the new core subcomponent OpenApi/Serializer/OpenApiNormalizer.php throws an error when calling `recursiveClean`. Given an ApiResource with a property named `paths`. Visiting the swagger/OpenAPi documentation the error:
`Warning: Undefined array key "paths"`

```php
// in vendor/api-platform/core/src/OpenApi/Serializer/OpenApiNormalizer.php (line 64)
// Side effect of using getPaths(): Paths which itself contains the array
if ('paths' === $key) {
    $value = $data['paths'] = $data['paths']['paths'];
    if ($value) {
        ksort($value);
    }
    unset($data['paths']['paths']);
}
```

**How to reproduce**  
Have an Api resource with a property `paths` and visit the swagger/OpenAPi documentation (`/api/docs` by default).
```php
<?php
// api/src/Entity/Offer.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(iri: 'http://schema.org/Offer')]
class Offer
{
    // ...

    /**
     * @Groups({"offer_read"})
     */
    private array $paths = [];

    // ...
}
```

**Possible Solution**  
Refactor `vendor/api-platform/core/src/OpenApi/Serializer/OpenApiNormalizer.php` to only apply the array modification once or when needed.
Also possible: Declare `paths` a reserved property word.

**Workaround**
Rename the colliding property.

**Additional Context**  
![FireShot Capture 270 - Warning_ Undefined array key _paths_ (500 Internal Server Error)_ - interactapi lndo site](https://user-images.githubusercontent.com/1324354/121690376-120b5500-cac6-11eb-9b9b-5cfd1f43d59d.png)

**Comment by pheadeaux** [comment]
@soyuka You have been working on these parts, right? Please check the PR.
