### ISSUE TITLE
PRE_VALIDATE events are call on GET methods

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#4333]
**API Platform version(s) affected**: 2.6.4

**Description**  

According to the [documentation](https://api-platform.com/docs/core/events/#built-in-event-listeners), the `PRE_VALIDATE` event priority should be call only on `POST` and `PUT` method.

However, my subscriber is always called, even on a `GET` method call.

**How to reproduce**  

Create an event subscriber like this:

```php
namespace App\Subscriber;

use ApiPlatform\Core\EventListener\EventPriorities;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ViewEvent;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\KernelEvents;

final class AppEventSubscriber implements EventSubscriberInterface
{
    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => [
                ['handlePreValidate', EventPriorities::PRE_VALIDATE],
            ],
        ];
    }

    public function handlePreValidate(ViewEvent $event): void
    {
        if ($event->getRequest()->isMethod('GET')) {
            throw new \Exception('Should not be called.');
        }

        $object = $event->getControllerResult();
        // ...
    }
}
```

Make an HTTP call on any api-platform `GET` object method.

**Possible Solution**  

**Additional Context**  

1. I am not sure it's a bug or it is normal according to the Symfony event behaviors. In case of option 2, this may be specified on this documentation.
2. Shall a `PRE_VALIDATE` event be call on a `PATCH` method? This may also be added on the documentation.

**Comment by norkunas** [comment]
api-platform does not manage your application event listeners. If you want them not to be executed look at [this piece of code](https://github.com/api-platform/core/blob/main/src/Validator/EventListener/ValidateListener.php#L54-L63) and just check for same conditions :)

**Comment by guilliamxavier** [comment]
Indeed, the "Description" column in the documentation is not for the events [priorities] but for the listeners (`ValidateListener` here).

That said, each "`PUT`" could indeed be "`PUT`/`PATCH`" (that would be for https://github.com/api-platform/docs)

**Comment by alanpoulain** [comment]
https://github.com/api-platform/docs/pull/1393
