### ISSUE TITLE
Related resources not serialized into IRI-s, if root resource uses an output DTO

### ISSUE THREAD

**Issue by kgilden** [api-platform/core#4338]
**API Platform version(s) affected**: 2.6.5, but it's likely a much older problem

**Description**  
If a root resource uses an output DTO, then all properties referring to related API resources get serialized to objects instead of their IRI-s.

**How to reproduce**  

```php
/**
 * @ApiResource(output = ParentOutput::class)
 */
class Parent
{
    public int $id;
    public Child $child;
}

class ParentOutput
{
    public int $id;
    public Child $child;
}

/**
 * @ApiResource
 */
class Child
{
    public int $id;
}
```

**Current result**

```sh
curl api.example.com/parents/42
```

```json
{
  "@context": {},
  "@type": "Parent",
  "@id": "/parent/42",
  "id": 42,
  "child": {
    "@context": " ... ",
    "@id": "/children/1",
    "id": 1,
  }
}
```

**Expected result**

```sh
curl api.example.com/parents/42
```

```json
{
  "@context": {},
  "@type": "Parent",
  "@id": "/parent/42",
  "id": 42,
  "child": "/children/1"
}
```

**Possible Solution**  

The problem seems to be caused by [AbstractItemNormalizer](https://github.com/api-platform/core/blob/6336f6446722cd6728683c36fb70e0074553296d/src/Serializer/AbstractItemNormalizer.php). If the root resource **does not** specify an output class, the same normalizer normalizes the attributes, and [getAttributeValue](https://github.com/api-platform/core/blob/6336f6446722cd6728683c36fb70e0074553296d/src/Serializer/AbstractItemNormalizer.php#L609) gets called. If the root resource **does** specify an output class, the attributes are recursively passed to the serializer. The recursion causes the related resource objects to get converted to DTO-s and of course since DTO-s are not resources, they are not converted to IRI-s.

So there should be some kind of a mechanism that serializes the attributes of a DTO the same way as the attributes of a resource class.

**Additional Context**  

#3795 seems to describe the same problem, but due to lack of activity was closed. There is also some discussion about the same problem and workarounds at https://symfonycasts.com/screencast/api-platform-extending/collections-readable-link#comment-5107585662.

I myself came up with [a workaround](https://gist.github.com/kgilden/5a0bb420e7b4c8e20e6744e90e79a1f4), which uses the `resource_class` context property to determine what the root is and just use an IRI converter for all other cases. But this falls short, when trying to publish to a Mercure hub, because the context is created differently ([here](https://github.com/api-platform/core/blob/6336f6446722cd6728683c36fb70e0074553296d/src/EventListener/SerializeListener.php) vs [here](https://github.com/api-platform/core/blob/6336f6446722cd6728683c36fb70e0074553296d/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php#L264)).

**Comment by NikDevPHP** [comment]
The same for me.
