### ISSUE TITLE
Turn the content-negotiation part of DeserializeListener (getFormat()) to be public (or even a listener on itself)

### ISSUE THREAD

**Issue by ericovasconcelos** [api-platform/core#4339]
**Description**  
By turning the getFormat() method from DeserializeListener public you would make possible for those who are decorating the listener to call the content-negotiation being handle by that method, without having to rewrite it on the decorating service.

The use-case for this feature is such as when implementing a deserialization of multipart/form-data as demonstrated by @Grafikart on the video https://www.youtube.com/watch?v=K8iVhRvjPoM.

I would even consider if it isn't better to separate the content-negotiation part of DeserializationListener into a new ContentNegotiationListener by itself?

**Example**  
<!-- A simple example of the new feature in action (include PHP code, YAML config, etc.)

    */
  --  private function getFormat(Request $request, array $formats): string
  ++  public function getFormat(Request $request, array $formats): string
    {

I volunteer to make the push request, if approved.

**Comment by alanpoulain** [comment]
Hello,
Decorating the `DeserializeListener` to force a supported format is not a good idea.
Instead you can properly support the `multipart` format by introducing a dedicated decoder.
See: https://api-platform.com/docs/core/file-upload/#handling-the-multipart-deserialization

**Comment by ericovasconcelos** [comment]
Hello,
That's perfect. It do make more sense to register a decoder instead a decorated deserialization listener. Also, the code on the docs worked like a charm. 

Thank you for the answer.
