### ISSUE TITLE
ORM agnostic filters

### ISSUE THREAD

**Issue by kennaar** [api-platform/core#4348]
I think API-Platform should provide filters which can be applied to `ApiResource` classes which are **not** Doctrine entities. The DTO pattern is the advised way of implementing things, but none of the existing filters can be used.
Filters generate documentation _and_ alter the generated query. When I have to reimplement all these filters from scratch, all the documentation logic is more or less duplicated.

So I guess I want generic filters which can be:
- accessed in a custom data provider to do whatever you need for your particular persistence backend
- translated to the Doctrine filters in a custom data provider and then applied as usual (e.g.: decorating data provider)

**Comment by metaclass-nl** [comment]
"When I have to reimplement all these filters from scratch, all the documentation logic is more or less duplicated.".  I guess you have seen that traits like ApiPlatform\Core\Bridge\Doctrine\Common\Filter\SearchFilterTrait do provide some reuse for generating the documentation, but do depend on metadata from Doctrine. You could extend each of them and from each use another trait that overrides the methods for retrieving the metadata. Ugly, but less duplication.

If you do actually reiplement all filters, [here is an RFC about a requirement of composability](https://github.com/api-platform/core/issues/2400 ) suggesting reimplementation too, but i found that composition can also be done with the existing filters. But from [this pull request](https://github.com/api-platform/core/pull/2055) i can't make up if they are actively rebuilding, nor wheather they want to replace the existing filters entirely or just add composable filters that will coexist with the existing ones.

**Comment by metaclass-nl** [comment]
"When I have to reimplement all these filters from scratch, all the documentation logic is more or less duplicated.".  I guess you have seen that traits like ApiPlatform\Core\Bridge\Doctrine\Common\Filter\SearchFilterTrait do provide some reuse for generating the documentation, but do depend on metadata from Doctrine. You could extend each of them and from each use another trait that overrides the methods for retrieving the metadata. Ugly, but less duplication.

If you do actually reiplement all filters, [here is an RFC about a requirement of composability](https://github.com/api-platform/core/issues/2400 ) suggesting reimplementation too, but i found that composition can also be done with the existing filters. But from [this pull request](https://github.com/api-platform/core/pull/2055) i can't make up if they are actively rebuilding, nor wheather they want to replace the existing filters entirely or just add composable filters that will coexist with the existing ones.

**Comment by soyuka** [comment]
#2400 will get to the bottom of this eventually
