### ISSUE TITLE
Strange rendering bug with ReDoc and iri-references

### ISSUE THREAD

**Issue by ambroisemaupate** [api-platform/core#4354]
After browsing several API documentations, all based on API Platform and using ReDoc UI, I've found some strange rendering bug:

**Description**  
![image](https://user-images.githubusercontent.com/380026/125209121-fea30380-e296-11eb-828c-7c59319c8d2e.png)

All links in `hydra:view` context are generated with `../словник` value.

This does not occur using SwaggerUI and I did not find any issue mentionning this on [ReDoc issues](https://github.com/Redocly/redoc/issues).

**How to reproduce**  

A simple Google search on `api platform "/словник"`

- https://fashion.plus.demo.sylius.com/api/v2?ui=re_doc#operation/postCredentialsItem
- https://demo.api-platform.com/docs?ui=re_doc#tag/Book
- https://api.mail.tm/docs?ui=re_doc#tag/Domain
- https://api.cwa.rocks/docs?ui=re_doc

![image](https://user-images.githubusercontent.com/380026/125209194-85f07700-e297-11eb-89f1-203a285694ca.png)

**Comment by norkunas** [comment]
For some reason this value is hardcoded in `src/Bridge/Symfony/Bundle/Resources/public/redoc/redoc.standalone.js` :D

**Comment by ambroisemaupate** [comment]
Thanks @norkunas for the search! I did not find it with Github search engine.

https://github.com/api-platform/core/blob/main/src/Bridge/Symfony/Bundle/Resources/public/redoc/redoc.standalone.js

**Comment by norkunas** [comment]
Currently the update js part does blind copy of downloaded resources,probably should at least validate checksum

**Comment by ambroisemaupate** [comment]
I've just download the latest redoc release from npmjs. 
It is still in it.

![image](https://user-images.githubusercontent.com/380026/125270734-4020c680-e30a-11eb-9d0d-3d4f525de5f4.png)


```
mkdir redoc-test
cd redoc-test
yarn init
yarn add redoc
grep -o "словник" "node_modules/redoc/bundles/redoc.standalone.js"
```

**Comment by norkunas** [comment]
as this comes from the npm then it's a redoc issue

**Comment by norkunas** [comment]
https://github.com/Redocly/openapi-sampler/blob/2f28d8dfb2fac7746ffc1ef3642d474a6c5a05c8/src/samplers/string.js
