### ISSUE TITLE
How to serialize a discriminator column in Api platform ?

### ISSUE THREAD

**Issue by o-doreille** [api-platform/core#4355]
Hello !

when you make a inheritance mapping with doctrine in an Entity 

like this 
...... 

/**
 * @ORM\Entity(repositoryClass=ThingRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({

....

the field "discr" (ie) is create in the database but non access by api platform serialization 

is it possible ?
thank's

**Comment by o-doreille** [comment]
thank's
but  the value is not in other entities but in the field (discr) in the mysql table  of the parent abstract class 
have you an exemple ? :)

**Comment by norkunas** [comment]
You'd have to declare these values statically in entity based on the discriminator values and that's all :)

**Comment by o-doreille** [comment]
It work's ! thank's very very much !!!
