### ISSUE TITLE
Do not check if default or example is empty in SchemaFactory

### ISSUE THREAD

**Issue by arnedesmedt** [api-platform/core#4359]
**API Platform version(s) affected**: 2.6.5

**Description**  
When you got, for example, the boolean false as a default value of your propertyMetadata. The check on line 203 will not pass because we are searching via the empty method: https://github.com/api-platform/core/blob/main/src/JsonSchema/SchemaFactory.php#L203-203

**How to reproduce**  
Add an example or default where the value is a false boolean, or an empty string.

**Possible Solution**  
I think we should be more strict here and check if the default !== null.
Should I create an MR for this one?

**Comment by alanpoulain** [comment]
Related: https://github.com/api-platform/core/issues/3882
