### ISSUE TITLE
[Question/Help] Using ResourceInterface and ResourceCollectionInterface

### ISSUE THREAD

**Issue by MajdiJ** [api-platform/core#437]
Hi , Correct me if I'm wrong please :
I tried to understand how this bundle works and kind of found that once we declare a resource in the services.yml , the bundle creates a resource for the entity and adds it in the resources collection.
If possible ,What I want to do and need is to be able to retireve the list of resources in my own bundle and get the different propreties of a resource because DunglasApiBundle handles doctrine metadata in an awesome way = ) . Any guidance or corrections will be welcome .

ps: I'm posting my issues here since I get  more answers for this api than stackoverflow ,Hope i'm not bothering

**Comment by dunglas** [comment]
You can totally do that, take a look at how NelmioApiDoc do it: https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/AnnotationsProvider/DunglasApiProvider.php#L66

**Comment by MajdiJ** [comment]
How can I use ClassMetadataFactory from this bundle into one of my classes to get the metadata .
I couldn't find how to make the right instantiation , calls in my class .
