### ISSUE TITLE
Embedded object in entity and patch request

### ISSUE THREAD

**Issue by rtwent** [api-platform/core#4376]
**API Platform version(s) affected**: 2.6.5

**Description**  
Doctrine Bundle v2.4.2 (Postgresql v13, php: 8.0.2). Patch request on resource that has embedded object (value object for storing jsonb data) is not modifying embedded object. Details provided in repo https://github.com/rtwent/embedObjectBug

**How to reproduce**  
See the files in attached repo. In generated api doc try to send a PATCH request for modifying resource. While sending { "i18n": { "ru": { "name": "ru", "declination": "in ru" }, "ua": { "name": "ua", "declination": "in ua" } },  "lft": 2,  "rgt": 3 } changes affects only primitive types (lft and rgt), but jsonb field i18n keeps unchanged.

**Possible Solution**  
Workaround as custom persister provided in the repo. It has a questions about doctrine UnitOfWork and original entity data 

$originalData = $this->entityManager->getUnitOfWork()->getOriginalEntityData($data). 

In value $originalData['i18n'] I have data from user input, but not "original" (old) state (In primitive types lft and rgt I have old states). So, doctrine can not identify changes on the field i18n and refuse to update it (as a merge patch). I must set $originalData['i18n'] = null; and then write data to it again.

**Additional Context**  
Files in repo https://github.com/rtwent/embedObjectBug

**Comment by carlobeltrame** [comment]
I think you need to set `writableLink: true` to the `i18n` property to enable nested writing:
```php
#[ApiProperty(writableLink: true)]
private I18nNameDeclinationVO $i18n;
```

**Comment by rtwent** [comment]
@carlobeltrame thank You for attention. But "writableLink" does not help.
