### ISSUE TITLE
One resource for one entity inheritance.

### ISSUE THREAD

**Issue by Sorendil** [api-platform/core#438]
Hello,

I saw 2 issues about inheritance : #184 and #288 but none of them gave me answers i'm looking for.
I have the class Widget that has some subclasses (HtmlWidget, ...).
I'd like to retrieve all kind of widgets by doing this : /widgets without having to write other resources.

/widgets will be able to return a collection of Widget and HtmlWidget.

Unfortunetely, I got this error : No resource found for object of type "AppBundle\Entity\Widget\HtmlWidget"

This is because of ResourceResolverTrait search a resource able to handle HtmlWidget entity.
One fast and dirty way to solve the problem is to add this code
```
if (method_exists($object, 'getResourceNamespace')) {
    return $object->getResourceNamespace();
}
```
at the begining of the method getObjectClass of trait **ClassInfoTrait**.

Then, I added this code in the class Widget :

```
public function getResourceNamespace()
{
	return self::class;
}
```

And now, the route work again.

So, my questions are : 
 - Is my strategy REST compliant ?
 - If so, what is the right way to do ?
 - If not, how would you do ?

Thank you in advance !
Anthony.

**Comment by teohhanhui** [comment]
You just have to add the resource for HtmlWidget. Then it should work as expected.

https://github.com/dunglas/DunglasApiBundle/blob/1.x/features/crud_abstract.feature

**Comment by Simperfit** [comment]
@Sorendil Is it ok for you ?

**Comment by Sorendil** [comment]
Hi,

Sorry for the late,

I've done specific development and it almost work like  said before (https://github.com/api-platform/core/blob/1.x/features/crud_abstract.feature) except **widgets/1** doesn't work but **html_widgets/1** works.

But it's an old functionnality and I don't have time to try anything else :/ Thanks for your replies !

**Comment by dunglas** [comment]
Thanks for the feedback! Closing.
