### ISSUE TITLE
Doctrine ODM Document support

### ISSUE THREAD

**Issue by Sorendil** [api-platform/core#439]
Hello,

DunglasAPI doesn't natively work in Doctrine ODM.

If I adapt it for Doctrine ODM via pull requests, could plan to support Doctrine ODM ?

Thanks in advance,
Anthony.

**Comment by dunglas** [comment]
Hi,

I'll be glad to merge ODM support if you contribute it. But do it for the `master` as we add new features to this one only.

**Comment by rabbitby** [comment]
https://github.com/Talaka-by/api-platform-mongodb-bundle

**Comment by dunglas** [comment]
Great! What do you think of merging it directly in core repositories?
It will ease the maintenance and the installation. Contact me by mail (dunglas@gmail.com) if you want to do that.

**Comment by Sorendil** [comment]
Hi !

Yeah, it will be really great if it was merged in code repo !


Le ven. 4 mars 2016 à 07:19, Kévin Dunglas <notifications@github.com> a
écrit :

**Comment by samvdb** [comment]
Talaka's bundle is for v1.0 and not v2. I currently have a working mongodb fork but it's not complete and includes a pretty dumb  caching strategy. Didn't have much time to create a proper solution. I could open a PR if someone wants to help out i'd welcome them with open arms!

**Comment by Simperfit** [comment]
Could be great if some MongoDB users could help us on @samvdb's PR  :).

**Comment by Sorendil** [comment]
Oh, I'd like but I can't for now, my project is in suspend since I don't have enough time :/

I still don't know when I'll work on it again, sorry. I'll tell you as soon as I know. Thanks !

**Comment by alanpoulain** [comment]
PR is in WIP: https://github.com/api-platform/core/pull/2144

**Comment by alanpoulain** [comment]
Done in 2.4.
