### ISSUE TITLE
Layering of one ApiResources on another for entites with same class name but different namespace

### ISSUE THREAD

**Issue by chyshyya** [api-platform/core#4397]
**API Platform version(s) affected**: 2.6.5
Not checked other versions.

**Description**  
Layering of one ApiResources on another for entites with same class name but different namespace

**How to reproduce**  
in `src/Entities` two folders `FolderOne` and `FolderTwo`. Inside of each entity with same class name `Item`.
So we have two namespaces `App\FolderOne\Item` and `App\FolderTwo\Item`
Each of item has ApiResource() annotation.
The problem is that they have same name for API and really shows and work only item from `FolderOne` because of same route names and pathes

**Possible Solution**  
Like a temporary solution for Item from FolderTwo we set a `@ApiResource(shortName: "FolderTwoItem")`, but the path became `/api/folder_two_item`. Nothing else can help.
But we think there must be a way to generate entity names, pathes and route names according to namespaces
For example for entity with namespace `App\FolderTwo\Item`
```
name = "FolderTwoItem"
route_name i= "_api_folder_two_item_.........."
path = "/api/folder-two/item........."
```
This way will be more comfortable and undestandable.

**Additional Context**
On screenshot two Items are looks like one, but they from different namespaces but second has `"route_prefix"="/uni"`. So first action for one antity, others for second. That must not be so, don't you think so too?   
![Снимок](https://user-images.githubusercontent.com/994758/131225212-d3ae0af9-362a-4d99-8a61-1b48ec00cbb9.JPG)

**Comment by imvigil88** [comment]
I have the same problem. Is there any workaround for this yet?
