### ISSUE TITLE
Make sure every ApiResource/ApiProperty property is nullable

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4411]
The new `ApiPlatform/Metadata/ApiResource` and `ApiPlatform/Metadata/ApiProperty` properties should all be nullable and have null as default which is not the case right now. This makes decoration easier, when a factory runs it should skip nullable values. 

For example: https://github.com/api-platform/core/blob/main/src/Metadata/ApiResource.php#L162.

**Comment by Zowac** [comment]
I'd like to get into it if possible :)
