### ISSUE TITLE
Add support for new attributes in MakerBundle

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#4414]
**Description**

Symfony MakerBundle should be updated to support the new attributes.

Support for old attributes should be kept for projects using an version of API Platform or PHP 7.

**Comment by soyuka** [comment]
![20210906_13h13m05s_grim](https://user-images.githubusercontent.com/1321971/132208875-bf365877-d9c7-4f71-9c05-4f53db8f06a9.png)

DataPersister is now State\Processor
DataProvider is now State\Provider

**Comment by soyuka** [comment]
+ In Symfony MakerBundle we need to use the new MEtadata if avialbabel

**Comment by nikophil** [comment]
FYI https://github.com/symfony/maker-bundle/pull/968
