### ISSUE TITLE
V2 - Cannot load resource

### ISSUE THREAD

**Issue by 3kynox** [api-platform/core#442]
Hello,

Just updated phpdocumentor/reflection-docblock to 3.0 to make further tests with v2 of api-platform. As it seems correct now (no more phpdocumentor error returned) I have a Cannot load resource error now : 

```html
<div id="sf-resetcontent" class="sf-reset">
            <h1>Whoops, looks like something went wrong.</h1>
            <h2 class="block_exception clear_fix">
                <span class="exception_counter">2/2</span>
                <span class="exception_title">
                    <abbr title="Symfony\Component\Config\Exception\FileLoaderLoadException">FileLoaderLoadException</abbr> in 
                    <a title="D:\clients\veille\api-demo\www\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\Loader.php line 73" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Loader.php line 73</a>:
                </span>
                <span class="exception_message">Cannot load resource &quot;.&quot;.</span>
```

Routing file remain simple as for the 1.1 : 

```yml
api:
    resource: "."
    type:     "api"
```

refer to https://github.com/3kynox/api-demo/commit/5988dbed220ca0f2b90720fdcdd5bd6e4520e83b

Any idea ?

**Comment by 3kynox** [comment]
Ok corrected route file with : 

```yml
api:
    resource: "."
    type: "api_platform"
```

Now got when calling ../friends URI http://paste2.org/tWbMIydW

Database is ok, entities looks like too.

**Comment by dunglas** [comment]
Can you copy the mapping of your Friend entity?

**Comment by 3kynox** [comment]
Available here : https://github.com/3kynox/api-demo/blob/API-3/src/ContactBundle/Resources/config/doctrine/Friend.orm.yml

Actually building API-4 branch using mappedSuperclass

**Comment by 3kynox** [comment]
Built API-4 branch using mappedSuperclass entities, no more "No resource class found..." error but weird behavior, call to /friends returns : 

```json
{
  "@context": "/app_dev.php/contexts/Friend",
  "@id": "/app_dev.php/friends",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/app_dev.php/friends/1",
      "@type": "Friend",
      "friendSince": [],
      "name": "MARTINS",
      "surname": "Bruno",
      "birthDate": [],
      "commWay": [
        {
          "@id": "/app_dev.php/telephones/1",
          "@type": "Telephone",
          "contact": null
        },
        {
          "@id": "/app_dev.php/emails/2",
          "@type": "Email",
          "contact": null
        },
        {
          "@id": "/app_dev.php/adresses/3",
          "@type": "Adress",
          "contact": null
        }
      ]
    }
  ],
  "hydra:totalItems": 1
}
```

- Every property with date is empty (but value exists in database)
- Defined groups do not work properly (Telephones, Emails, ... childs showing URI with no details and showing empty "contact" property as it is not included in my serialization group.

**Comment by dunglas** [comment]
1. This set of dependencies should fix the date problem: https://github.com/3kynox/api-demo/pull/2
2. I've not the time to dig into it right now but it's maybe because you don't have set normalization groups properly on the abstract class. `@Resource` and `@Property` Annotations are not inherited from parent classes right now, and it seems that the `friends` property and getters/setters are missing.
