### ISSUE TITLE
$_SERVER is not filled on tests 

### ISSUE THREAD

**Issue by babeuloula** [api-platform/core#4439]
**API Platform version(s) affected**: 2.6.5

**Description**  
Hello,

On one of my project, I need to check some headers on `$_SERVER`. It's a legacy lib of my client and I can't modify any line of his code because it's a vendor.

It's like `test.api_platform.client` does not fill the superglobal `$_SERVER['HTTP_*']`.

**How to reproduce**  
```php
static::createClient(
	[],
	[
		'headers' => [
			'User-Agent' => 'my-agent',
		],
	],
);
```

or 

```php
static::createClient(
	[],
	[
		'headers' => [
			'HTTP_USER_AGENT' => 'my-agent',
		],
	],
);
```

If you debug `$_SERVER['HTTP_*']`, no headers was found.

Thanks

**Comment by mkrauser** [comment]
It is considered bad-practice to access Superglobals in a Symfony Application. Symfony only uses them to create the master request object. In general, itdoes not make sense to set superglobals in test cases.
If you need them to test your app, you need to set them by yourself (e.g. in a custom createClient-Function). It'll probably be good to unset them after each test to avoid side-effects.
Also one other hint: Depending on superglobals in your tests may prevent you from running your tests in parallel.

**Comment by babeuloula** [comment]
Hello @mkrauser I know, used $_SERVER is a bad practice. But It's a legacy code and I can't change how theses classes are called and filled.

**Comment by mkrauser** [comment]
Yes, I read that. But you can always set $_SERVER in your tests, if required.

**Comment by babeuloula** [comment]
Oh OK I understand what you want. It's possible, but if the service could do it for me ^^

**Comment by mkrauser** [comment]
Since this is not a very common requirement, I don't think, something like this will be implemented. 

But it should not be a big deal to implement this yourself. IMO the best option is to create a custom client-class which sets $_SERVER for every-requests and unsets it right after.
