### ISSUE TITLE
Fetch Relations with corresponding DataProvider.

### ISSUE THREAD

**Issue by velreine** [api-platform/core#4442]
**Description**  
I think it would be great, if it would be possible for the framework to automatically use a relations DataProvider to fetch related data.

Example if a Question Entity has a One-To-Many relation to Answer.
When fetching a Question and the "Answers" property is included in the normalization context, it would be great if ApiPlatform would first use the built-in ItemDataProvider to fetch Question, and then fetch Answers to the Question via AnswerCollectionDataProvider if such a service did exist.

I have a weird use case where I'm being tasked to implement a filter that will strip contents of the original result based on some criteria (this can only be performed in the DataProvider) as this is the place to modify the Paginator or array of data before it is returned from the provider.

A Normalizer would be able to modify the individual Answer objects, but not exclude that object from the result.

But this limitation then in turn means that those extra fields will not be populated if the specific AnswerCollectionDataProvider was not used to fetch that collection. (This applies for items too).

Example:

```
query getAnswer {
  answer(id: "/api/answers/1") {
    id
    text
    someFieldPopulatedInProvider
  }
}
```

```
query getQuestion {
  question(id: "/api/question/1") {
    id
    question
    answers {
      edges {
        node {
          id
          text
          someFieldPopulatedInProvider
        }
      }
    }
  }
}
```

In this scenario "someFieldPopulatedInProvider" will only be honored in the first query. For the second query the field will be NULL.

If the field was populated in a Normalizer objects could be populated in all the contexts ONE-BY-ONE but no optimization can be done to populate all those objects at once like in the provider. 

But if the field is then populated in the normalizer it will be impossible to remove the object that does not satisfy the filter criteria.

**Example**  
I don't know if there is a simpler way to satisfy my request, but i feel like the problem is a legit one.
I can see the benefits of Automatically left joining with QueryCollectionExtensions as is done now instead of firing requests per relation.

**Comment by ivanmunozruiz** [comment]
is there any solution for this?
