### ISSUE TITLE
GraphQL Type Converter to handle DateIntervals as strings?

### ISSUE THREAD

**Issue by jpremmel** [api-platform/core#4482]
I added a `dateinterval` field to one of my entities:

    class TrainingType extends BaseEntity
    {
        //...
        
        /**
         * @var string The amount of time a training record of this type is valid.
         *
         * @ORM\Column(type="dateinterval", nullable=true)
         */
        public $validFor;
        
        //...
    }

When I exported the graphql schema, this new `validFor` field showed up for `createTrainingTypeInput` and `updateTrainingTypeInput`, but not `type TrainingType`:

    type TrainingType implements Node {
      //...
      //I think validFor: String should be here but it's not
      //...
    }
    
    input createTrainingTypeInput {
      //...
      """The amount of time a training record of this type is valid."""
      validFor: String
      //...
    }
    
    input updateTrainingTypeInput {
      //...
      """The amount of time a training record of this type is valid."""
      validFor: String
      //...
    }

And my frontend gives the following error when trying to query a Training Type entity: `GraphQL error: Cannot query field "validFor" on type "TrainingType"`

I tried altering GraphQl/Type/TypeConverter.php (around lines 75-80 or so) from:

                if (is_a($type->getClassName(), \DateTimeInterface::class, true)) {
                    return GraphQLType::string();
                }

to:

                if (is_a($type->getClassName(), \DateTimeInterface::class, true) || is_a($type->getClassName(), \DateInterval::class, true)) {
                    return GraphQLType::string();
                }

When I made this change, the `validFor: String` field did show up under `type TrainingType` in my schema, and I was able query the entity in the frontend. Can support for date intervals as graphql strings be added?

**Comment by alanpoulain** [comment]
Hello,
Yes it would be nice to have this addition.
