### ISSUE TITLE
Is possible to pass more parameters to Redoc for more customization (introduction, sub-menu, etc ) ?

### ISSUE THREAD

**Issue by Dahkenangnon** [api-platform/core#4484]
Hello.
I have a problem with the documentation generated from api platforme with Redoc.

I noticed that there are several redoc parameters (which allow such a good customization) that Api platform does not support.
For example provide an introduction to the API, make submenus and many others.

Please, I would like to have a doc like this one:

https://rebilly.github.io/RebillyAPI/

If it exists a chance to add parameters that will use Redoc, thank you for helping me

**Comment by alanpoulain** [comment]
Related: https://github.com/api-platform/core/pull/3731
We could do the same thing for Redoc (second argument of `Redoc.init`).

**Comment by soyuka** [comment]
I think that you can easily customize the docs template if needed.
