### ISSUE TITLE
No operations defined in spec! with new ApiPlatform\Metadata\ApiResource

### ISSUE THREAD

**Issue by NotionCommotion** [api-platform/core#4485]
**API Platform version(s) affected**: 2.7.x-dev

**Description**  

When using the new `ApiPlatform\Metadata\ApiResource`, the swagger interface returns "No operations defined in spec!".

**How to reproduce**

Use `ApiPlatform\Metadata\ApiResource` instead of `ApiPlatform\Core\Annotation\ApiResource`.
Change `doctrine.orm.mappings.App.type` (api/packages/doctrine.yaml)  from `annotation` to `attribute`.
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Column;
use ApiPlatform\Metadata\ApiResource;
//use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 */
#[ApiResource(mercure: true)]
#[Entity]
class Greeting
{
    /**
     * The entity ID
     */
    #[Id]
    #[GeneratedValue]
    #[Column(type: 'integer')]
    private ?int $id = null;

    /**
     * A nice person
     */
    #[Assert\NotBlank]
    #[Column]
    public string $name = '';

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

**Possible Solution**  
Use the depreciated `ApiPlatform\Metadata\ApiResource`

**Additional Context**  
When initially executing `bin/console api:rector:upgrade -d src` (dry run), it indicated that operations should be added as attributes.  Tried doing so (and of course importing them from `ApiPlatform\Metadata\Get`, etc) but no change.
```
#[ApiResource(mercure: true)]
#[Get]
#[Put]
#[Patch]
#[Delete]
#[GetCollection]
#[Post]
```

**Comment by TheCrealm** [comment]
Had the same behaviour. 
I solved this by disabling the compat layer in the config:

`api_platform:
    metadata_backward_compatibility_layer: false`

With the compat layer enabled apip handles every class without the deprecated annotation not as resource class. 
At: https://github.com/api-platform/core/blob/main/src/Core/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php#L74

**Comment by NotionCommotion** [comment]
@TheCrealm Thanks!

Did you discover this solution just by randomly going through the code or is there some more proficient way?  I need to get better at troubleshooting api-platform and symfony.

**Comment by TheCrealm** [comment]
@NotionCommotion I know the very basics on how api platform generates an api resource and their corresponding operations. Its actually managed by the metadata system which got a complete overhaul for 2.7/3.0..
So i simply started to look here: https://github.com/api-platform/core/blob/main/src/Core/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php
Next i started a debug session in PHPStorm with a simple `bin/console cache:clear` command (Refreshes Cache -> Refreshes Metadata!).
I  noticed that the resource classes without the deprecated annotation wasnt even available there. So i concluded that they are omitted in one of the ResourceNameCollectionFactorys which collect resource class names.

Hope that helps a bit. maybe. PHPStorm combined with XDebug are a masterpiece for this!

**Comment by NotionCommotion** [comment]
@TheCrealm Nice bit of troubleshooting!  I really should consider looking into PHPStorm.

**Comment by cavasinf** [comment]
FYI: https://api-platform.com/docs/core/upgrade-guide/#api-platform-2730

**Comment by celorodovalho** [comment]
@TheCrealm Thanks! <3
