### ISSUE TITLE
Check mandatory fields on PUT operation

### ISSUE THREAD

**Issue by Fimeo** [api-platform/core#4505]
Hello,

I have a question regarding the configuration of PUT routes on apiplatform. How to validate the mandatory parameters of the payload during a request?
Indeed, following the REST convention, the PUT must completely replace the object, so if a field is not filled, a 422 must be raised on a null field.

However, the object is retrieved from the database and the object is hydrated to perform the validations. So the assert not blank control on a field is never raised.

How to solve this problem ?
A solution: custom validator applied on the fields of the entity then 
 retrieve the corresponding key and array diff on the request stack.

Thanks for your help

**Comment by dunglas** [comment]
Hi, see https://github.com/api-platform/core/issues/4344 for a proposal to fix this problem.
Closing as duplicate.
