### ISSUE TITLE
Cant use IRI for child class of a base class with a discriminator map

### ISSUE THREAD

**Issue by diaboloshogunate** [api-platform/core#4507]
**API Platform version(s) affected**: 2.6

**Description**  
When using an IRI for a child class, an exception is thrown in the abstract item normalizer. 

`throw new RuntimeException(sprintf('Type property "%s" not found for the abstract object "%s"', $mapping->getTypeProperty(), $class));`

This was introduced by https://github.com/api-platform/core/pull/3273

**How to reproduce**  
We are doing a post request with the data below
```
 [
     'parent' => '/api/carts/builder/eb54fcbf-18aa-4c2b-b337-73d1734c79e1',
     'product' => $this->findIri($product),
     'coreColorGroup' => $this->findIri($variant->getCoreColorGroup()),
     'selectedVariants' => [
         ['productVariant' => $this->findIri($variant)],
     ],
     'decoratedTemplates' => [$this->buildSampleDecoratedTemplateData()],
 ]
```

The iri for `product` is for a class that extends the product class. The base classes uses a `DiscriminatorMap`.

**Comment by soyuka** [comment]
can you provide a reproducer? Best case would be a failing behat test suite.

**Comment by diaboloshogunate** [comment]
I am going to close this for now. 

There are some other issues that should be resolved in future release such as https://github.com/api-platform/api-platform/issues/2093

If the issue pops up at that time we will work on providing a reproducer.
