### ISSUE TITLE
DateFilter does not convert date to default time zone

### ISSUE THREAD

**Issue by mrtnzagustin** [api-platform/core#4515]
**Description**  
When using DateFilter, the andWhere clause just print date and time as it is sent, without taking in consideration the timezone. This force you to always send the dates using your database/app timezone config.

**Example**  
Suppose you have a time timezone with -03:00 configured in php and database. 
When you use a filter like GET htttp://myapi.com/api/my_entity_endpoint?dateTimeField[after]=2021-10-12T09:24:25Z, the filter DateFIlter uses '2021-10-12 09:24:25' instead of '2021-10-12 06:24:25'

**Posible Solution**
add `$value->setTimeZone(new \DateTimeZone(date_default_timezone_get()));` after line https://github.com/api-platform/core/blob/1259ee5cb6c07267e5db5436234a4623b09512e5/src/Core/Bridge/Doctrine/Orm/Filter/DateFilter.php#L143

**Comment by bertrandseurot** [comment]
On the developper side, overriding the doctrine datetime field type as explained here : https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/cookbook/working-with-datetime.html#handling-different-timezones-with-the-datetime-type should be systematic anyway
