### ISSUE TITLE
Additional PHP 8 attributes for easier customization

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#4535]
**Description**  
Now that Symfony 6 will require PHP 8, we could leverage php attributes for `Processor`, `CollectionProvider` and `ItemProvider`.

For now when you have many custom operations and need to configure in what priority processor or providers run, you need to write custom configuration.

I am thinking that it could be nice to go in the same direction as Symfony with `AsEventListener` attribute.

**Example**  
```
class AsStateProcessor
{
    public function __construct(public int $priority = 0) {}
}

class AsCollectionProvider
{
    public function __construct(public int $priority = 0) {}
}

class AsItemProvider
{
    public function __construct(public int $priority = 0) {}
}
```

**Comment by alanpoulain** [comment]
I think it could be nice to have this feature too.
However, only an `AsStateProvider` is necessary, we don't make a distinction between item and collection anymore.
