### ISSUE TITLE
Language negocitation

### ISSUE THREAD

**Issue by lobodol** [api-platform/core#4538]
Hello there,

I've been using API-Platform for a few months and I really appreciate it. However, I noticed that [content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation) is well implemented but nothing about language negotiation.  
As a result, when I start a new project, I begin adding a simple class for that purpose:

```php
class LanguageNegotiatorSubscriber implements EventSubscriberInterface
{
    /**
     * Get the preferred language from header Accept-Language and set it as locale
     */
    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        $request->setLocale($request->getPreferredLanguage(['en', 'fr']));
    }

    public static function getSubscribedEvents(): array
    {
        return ['kernel.request' => ['onKernelRequest', 20]];
    }
}
```
It's a quick workaround but does the job.

Looking at api-platform dependencies, I saw package [willdurand/negotiation](https://github.com/willdurand/Negotiation) is used for content-negotiation. Moreover, it provides language-negotiation also.

My question is that simple: why not implementing language-negotiation in api-platform using `willdurand/negotiation`?

Thanks for reading. Regards,

[EDIT] I found `Negotiation\LanguageNegotiator` in api-platform sources but can't find a way to use it.

**Comment by norkunas** [comment]
Language negotiation was implemented in Symfony only month ago in https://github.com/symfony/symfony/commit/43f0161236381db8a0440db72d0be90289ba71bf so maybe there is nothing to do in api platform but instead just wait to be able to upgrade :)

**Comment by alanpoulain** [comment]
Maybe the only thing to do is to enable it by default in API Platform?

**Comment by lobodol** [comment]
> Language negotiation was implemented in Symfony only month ago in [symfony/symfony@43f0161](https://github.com/symfony/symfony/commit/43f0161236381db8a0440db72d0be90289ba71bf) so maybe there is nothing to do in api platform but instead just wait to be able to upgrade :)

Oh great! I was not aware about it.

> Maybe the only thing to do is to enable it by default in API Platform?

Seems a good idea to me.

**Comment by dunglas** [comment]
I would prefer to keep it opt-in has it may change the behavior of the cache cache.

**Comment by lobodol** [comment]
FYI, I tried enabling `framework.set_locale_from_accept_language` and it works fine. Here is my config:

```yaml
framework:
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales: [en, fr]
```
