### ISSUE TITLE
Annotation loading from Entity directory has unstable order

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#454]
This causes the following Behat scenario to fail on my machine (but it passes on Travis CI):
https://github.com/api-platform/core/blob/597f045fe8822c287f7323cef0127aa9db1dc196/features/json-ld/context.feature#L6-L29
(specifically the JSON equals part, because the keys might end up in the wrong order)

We need to somehow do a sort here:
https://github.com/api-platform/core/blob/597f045fe8822c287f7323cef0127aa9db1dc196/src/Metadata/Resource/Factory/AnnotationResourceNameCollectionFactory.php#L56-L75

**Comment by theofidry** [comment]
What about testing the JSON result without caring about the order instead? Something [like that](https://github.com/in6pio/Incipio/blob/master/features/api/job.feature#L24-L45):

```gherkin
  Scenario: It should be possible to get a specific job
    Given the fixtures file "job/president.yml" is loaded
    When I send a GET request to "/api/jobs/1"
    Then the response status code should be 200
    And the response should be in JSON-LD
    And the JSON response should have the following nodes:
      | node             | value             | type   |
      | @context         | /api/contexts/Job |        |
      | @id              | /api/jobs/1       |        |
      | @type            | Job               |        |
      | abbreviation     | PR                |        |
      | enabled          | true              | bool   |
      | mandate          |                   | object |
      | mandate->@id     | /api/mandates/1   |        |
      | mandate->@type   | Mandate           |        |
      | mandate->endAt   |                   |        |
      | mandate->name    | Mandate 2005/2006 |        |
      | mandate->startAt |                   |        |
      | title            | President         |        |
      | users            |                   | array  |
      | users[0]         | /api/users/4      |        |
    And the JSON node "users" should have 1 element
```

**Comment by teohhanhui** [comment]
That's good, but I'd argue that we should still ensure a deterministic load order.

**Comment by teohhanhui** [comment]
Using the php `->` syntax for JSON is not intuitive though...

**Comment by theofidry** [comment]
We could always change the syntax :)

That being said, is there a reason why this order should be deterministic? Of course I prefer when things are deterministic, but I mean there is somewhere (besides the current tests) where we explicitly expect the keys to be in the right order?

**Comment by teohhanhui** [comment]
@theofidry I refer to your own comment from months back: https://github.com/hautelook/AliceBundle/pull/64#issuecomment-132460523

:stuck_out_tongue:

**Comment by teohhanhui** [comment]
I don't think it's okay for the order of the keys to differ from one machine to another. We should ensure it stays the same. (Just because we don't rely on the ordering, doesn't mean somebody else should not be able to...)

**Comment by theofidry** [comment]
>@theofidry I refer to your own comment from months back: hautelook/AliceBundle#64 (comment)

But that was only for the tests, the library still never guarantee the order in which the files will be loaded.

In which case one would rely on the order of the keys (expect us for the tests right now – which is a different problem) as they have the keys to access to it?

My only concern is doing an extra processing to sort them, when it's actually not needed.

**Comment by teohhanhui** [comment]
Oops... You're right.

And I guess it's not really necessary.

**Comment by theofidry** [comment]
But we still have this problem for the tests: so maybe we should work on a solution to be able to test a JSON without caring about the actual order of the properties. We want to test the JSON equivalence, not the strict equality.

**Comment by teohhanhui** [comment]
The downside if we don't sort is that it'll still be harder for others to write functional tests (like what we're experiencing now...), but perhaps it's alright.

**Comment by theofidry** [comment]
>but perhaps it's alright.

Would stil be good if we could find something for it :)

**Comment by dunglas** [comment]
Having a way to test JSON documents without caring about the order would be a great improvement to Behatch. I've always the problem in my own project.

Anyway, I think that we should still test the order at least in some tests here. Changing the order of the JSON document acceptable but it's better if we are notified when we do it and can decide informed.

**Comment by theofidry** [comment]
>Changing the order of the JSON document acceptable but it's better if we are notified when we do it and can decide informed.

And having the proper diff... Ha I thinking I'm asking for too much here

**Comment by Simperfit** [comment]
Do we have to develop something into Behatch or can't we just use ? : 

```
  Scenario: Retrieve Entrypoint context
    When I send a "GET" request to "/"
    Then the response status code should be 200
    And the response should be in JSON
    And the header "Content-Type" should be equal to "application/ld+json"
    And the JSON nodes should contain:
        | abstractDummy            |  /abstract_dummies     |
...
```

BTW, this is working as expected, if we can use it like that, ill do a PR with the modification.

**Comment by Simperfit** [comment]
ping in here

**Comment by soyuka** [comment]
Why don't you use `the JSON should be valid according to this schema` to avoid repeating values? Then, order will not be a problem anymore and we won't have to update this file every time we add a resource in the fixtures.

**Comment by Simperfit** [comment]
:+1: @soyuka ,
If we don't need to test every resources in this test, ill send a PR.

ping @teohhanhui @theofidry @dunglas

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/516#issuecomment-214451797

**Comment by Simperfit** [comment]
This can be closed ?

**Comment by teohhanhui** [comment]
@Simperfit We have yet to reach agreement on this. See comments above.

**Comment by soyuka** [comment]
Wontfix?

**Comment by Simperfit** [comment]
I agree with @soyuka
