### ISSUE TITLE
Upgrade to PHPStan 1.0

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#4542]
PHPStan 1.0 has been released: https://phpstan.org/blog/phpstan-1-0-released
We need to upgrade it on branch 2.6.

**Comment by theMadness** [comment]
Checking on this.

**Comment by theMadness** [comment]
So the plan here is:
* attempt to upgrade phpstan
* possibly also its extra packages (phpstan/phpstan-doctrine, phpstan/phpstan-phpunit, phpstan/phpstan-symfony)
* review any notice it throws
* mark false positives as such
* fix actual detected issues
* push the PR

**Comment by theMadness** [comment]
@dunglas when we say phpstan 1.0, do we mean 1.0.x or 1.x? (latest version is 1.1.2 as of posting this message)

**Comment by dunglas** [comment]
@theMadness 1.1 is good. It's just a dev deps so let's support only the latest version.
