### ISSUE TITLE
Doctrine json_array type should now be json

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4547]
Since `json_array` has been deprecated in Doctrine DBAL we should use `json`. In graphql this changes how the type opperates. Change the `json` type in Entity/Dummy and fix the corresponding behat tests.

https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/Entity/Dummy.php#L136-L138 

Note that you should probably also change the `array` type or add the `nullable` PHP type .

+ allow the `doctrine/dbal` at version `3.x` (currently fixed at 2.6 https://github.com/api-platform/core/pull/4544/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R36)

**Comment by laryjulien** [comment]
I have opened a PR to resolve the other issue with doctrine/dbal 3.x

**Comment by soyuka** [comment]
is this fixed @dunglas  ?

**Comment by dunglas** [comment]
Yes: https://dunglas.dev/2022/01/json-columns-and-doctrine-dbal-3-upgrade/
