### ISSUE TITLE
Allow input on custom controllers

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#4567]
**Description**  
As far as I can tell it's not possible to have something like this:
```
        'wep_pin' => [
            'method' => 'POST',
            'path' => '/transactions/{id}/pin',
            'controller' => CheckWebPin::class,
            'input' => CheckWebPinInput::class,
        ],
```

Every time I try to work around this I'll get a `Cannot validate values of type \"null\" automatically. Please provide a constraint.` kind of error. 

Alternatively maybe add the ability to add {id} to Messanger enabled routes, both solutions would fix that problem that you can't seem to define custom itemOperation POST routes with input parameters (unless I'm missing something rather obvious here)

**Example**  
Like the thing above, and then in the controller part the __invoke would look something like:
`__project(Transaction $data, CheckWebPinInput $input)` or something like that.

**Comment by d-cichon** [comment]
Hi!

I have simillar issue, but i don't know how to resolve that. I see that you closed this task as completed. Can you tell me more about that? Did you find solution?

**Comment by KDederichs** [comment]
Since it's using symfonys messanger component you actually can't add stuff to __invoke, so you'll have to move the ID/Entity out of the URL and into the Input DTO.

In 2.7/3.0 you probably can cheese it with the Link attribute though
