### ISSUE TITLE
Make it easier to grab the Resource from a messanger component with an input and PUT/PATCH

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#4568]
**Description**  
Piggybagging of https://github.com/api-platform/core/issues/3082 :   
It's unnessecary hard (and actually not documented anywhere cause I assume that SUPER hacky and whacky) to make a message handler that gets both an Input object AND the object serialised by the URI if you have a construct like that:

```
    itemOperations: [
        'wep_pin' => [
            'method' => 'PUT',
            'messenger' => "input",
            'path' => '/transactions/{id}/pin',
            'input' => CheckWebPinInput::class,
        ],
]
```

Currently you can actually inject the `RequestStack` into the MessageHandler and then grab both with something like this:

```
  public function __invoke(CheckWebPinInput $checkWebPinInput)
    {
               /** @var Transaction $data */
        $data = $this->requestStack->getCurrentRequest()->attributes->get('previous_data');
    }
```

But I'll be honest that feels super hacky and the fact that it's not documented anywhere that that works means it probably is....

Now I'd love for an official way to get both my Entity that got fetched by the URL and Input passed to the hander.

**Example**  

Optimally I'd love to see something like this:
```
  public function __invoke(CheckWebPinInput $checkWebPinInput, Transaction $data)
    {
    }
```
where Api Platform will just go and pass both to the handler. That would be super convenient for people to work with.

Alternatively if the way I'm grapping it above is actually valid and supported for a long time I'd suggest you at least add that to the docs cause it took me forever to dig up that behaviour....

**Comment by KDederichs** [comment]
I also just saw you could do the same with the IriConverter and the request stack IF it didn't hard code GET as operation that is....
I'll open a new ticket for that one

**Comment by soyuka** [comment]
use 2.7 new metadata it gets easier
