### ISSUE TITLE
Review of Doctrine ItemDataProvider

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#457]
As reviewing some parts of the code, some questions are coming:

- When does this occurs: [`$identifierValues = explode('-', $id)`](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L71); couldn't find any test for it
- [The manager returns an [ObjectRepository](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/ObjectRepository.php)](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L95) which does not have the `createQueryBuilder()` method. So how does this works?

The second question is a false one: I know it works because we actually have an `EntityRepository` object, which has this `createQueryBuilder()` method. And with have an `EntityRepository` because the manager is an `EntityManager`. But we are assuming this and don't do any check for it.

So what do we do about this?

**Comment by theofidry** [comment]
ping @api-platform/core-team

**Comment by dunglas** [comment]
> When does this occurs: $identifierValues = explode('-', $id); couldn't find any test for it

It's for supporting composite primary keys, but I've not tested it yet...

> But we are assuming this and don't do any check for it.

:+1: for me to add a check.

**Comment by theofidry** [comment]
>:+1: for me to add a check.

@dunglas and what do we do if this check fails? Because this means that if a user is using a custom `EntityManager`, it will fail. And IIRC doctrine provide a decorator for the entity manager, so `EntityManager` is more likely to be decorated than extended.

Should I simply keep the current case and throw an exception in the meantime?

**Comment by dunglas** [comment]
What do you think of adding something like that:

```php
if (!method_exists($manager, 'createQueryBuilder')) {
    throw new RuntimeException('The manager must have a "createQueryBuilder" method.');
}
```

**Comment by theofidry** [comment]
Follow up in https://github.com/api-platform/core/pull/458/files#diff-c289b8d48b326bf2263d64149fd975d3R159.

**Comment by theofidry** [comment]
Closing the issue as the discussion should continue in the PR.
