### ISSUE TITLE
DI inject ExpressionLanguage into PublishMercureUpdatesListener

### ISSUE THREAD

**Issue by man-htsts** [api-platform/core#4571]
**Description**  

Please, add the ability to inject my own service of class ExpressionLanguage into PublishMercureUpdatesListener.
I need it to add more specific functions in mercure annotation of my entity `@ApiResource(mercure="get_options(object.getValue())")`.

**Example**  

My app services.yaml:
```
    api_platform.mercure.expression_language:
        class: App\Mercure\ExpressionLanguage
```
https://github.com/api-platform/core/blob/2.6/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml
```
...
        <service id="api_platform.doctrine.orm.listener.mercure.publish" class="ApiPlatform\Core\Bridge\Doctrine\EventListener\PublishMercureUpdatesListener">
            ...
            <argument type="service" id="api_platform.mercure.expression_language" on-invalid="ignore" />
            ...
        </service>
```
And it will be injected into this:
https://github.com/api-platform/core/blob/2.6/src/Bridge/Doctrine/EventListener/PublishMercureUpdatesListener.php

For now, i am inject my service via my Kernel.php:
```
    public function process(ContainerBuilder $container): void
    {
        if ($container->has('api_platform.doctrine.orm.listener.mercure.publish')) {
            $definition = $container->findDefinition('api_platform.doctrine.orm.listener.mercure.publish');
            $definition->addArgument(
                new Reference('api_platform.mercure.expression_language')
            );
        }
    }

```

**Comment by soyuka** [comment]
you should be able to do this using the symfony DI it's out of API Platform's scope

**Comment by man-htsts** [comment]
I am not able do it using symfony DI because of API Platform.
You should add:             
<argument type="service" id="api_platform.mercure.expression_language" on-invalid="ignore" />
Only after this i can use symfony DI
