### ISSUE TITLE
Call to undefined method Symfony\Component\Validator\Constraints\AtLeastOneOf::getNestedContraints()

### ISSUE THREAD

**Issue by michaelHottomali** [api-platform/core#4572]
https://github.com/api-platform/core/blob/10827bb570c44cdee2c1bb7a307a8a18df9b4f00/src/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestriction.php#L45
Should correct to
`        $oneOfConstraints = $constraint->getNestedConstraints();
`

**Comment by sidz** [comment]
here is a PR https://github.com/api-platform/core/pull/4564

as a temporary solution:
add symfony/validtor: ">5.3.10" or >4.4.33 to the conflict section inside of composer.json.

**Comment by mbrodala** [comment]
Or use said PR changes right now by [applying them as patch](https://packagist.org/packages/cweagans/composer-patches).
