### ISSUE TITLE
Swagger_UI BUG

### ISSUE THREAD

**Issue by Suvres** [api-platform/core#4574]
Your swager ui specyfication has to many 'paths' fields ->

![obraz](https://user-images.githubusercontent.com/67355511/143422847-e2ed7b64-c898-4c0e-98c9-31066083cf2b.png)

You can fix like that
![obraz](https://user-images.githubusercontent.com/67355511/143422814-de9b67de-cd4b-4f84-b53e-7584fffe07b1.png)

**Comment by Suvres** [comment]
@dunglas  @stloyd  @monteiro  @pborreli

**Comment by norkunas** [comment]
what is the bug that you are experiencing? :)

**Comment by soyuka** [comment]
not a bug, the normalizer is handling this
https://github.com/api-platform/core/blob/main/src/OpenApi/Serializer/OpenApiNormalizer.php#L43
