### ISSUE TITLE
To much normalizers

### ISSUE THREAD

**Issue by Suvres** [api-platform/core#4575]
@norkunas  in my opinion the bug is that, You use "all" normalizers in _constructor. That make, the OpenApiNormalizator is on place of this list, and others normalizators can normalize the openApi object earlier

**Comment by Suvres** [comment]
this one can handle this problem: 
![obraz](https://user-images.githubusercontent.com/67355511/143428883-228ef4f3-3eaa-40d2-8ea4-cada946ad933.png)

**Comment by dunglas** [comment]
Please stop opening so many issues for the same problem. Reply to existing issues to prevent spamming all watchers of this repo.
