### ISSUE TITLE
IriConverter only works on GET routes.

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#4579]
**API Platform version(s) affected**: <= 2.6.6

**Description**  
The 'match' function in https://github.com/api-platform/core/blob/main/src/Symfony/Routing/Router.php is limited to GET requests.
This blocks the usage of the IriConverter in situations where you might want to extract the object out of the URL in a message handler see (#4568 for example).

**How to reproduce**  

Try to use the IriConverter with any non GET routes and it'll tell you that the route doesn't exist.

**Possible Solution**  

Since this bug occurs because the method is hard coded as GET maybe change the way that is handled or use the original router? 

**Additional Context**  
Like I said this is useful if you are trying to extract the entity out of the URL in message handlers. Tbh I think this would be the cleanest way to do so if the iri converter actually worked on non GET operations.

**Comment by soyuka** [comment]
this was greatly improved in the new version please check that out
