### ISSUE TITLE
Custom filter gets injected twice into custom data provider

### ISSUE THREAD

**Issue by acirulis** [api-platform/core#4585]
**API Platform version(s) affected**: 2.6.6.

**Description**  
I have created a custom filter (implementing ApiPlatform\Core\Api\FilterInterface) and injected it into my custom data provider (from  (https://api-platform.com/docs/core/data-providers/#injecting-extensions-pagination-filter-eagerloading-etc)) . Problem is, that filter gets injected twice: one time with populated properties attribute, one time without.

As I understand, one comes from ApiFilter attribute & one from DI, but if this is not a bug, what's the correct way to access filter inside data provider?

**How to reproduce**  
I created an empty project with following setup:

**App\Entity\TestResource.php**
```
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Filter\TestFilter;

#[ApiResource()]
#[ApiFilter(TestFilter::class, properties: ['name' => 'partial'])]
class TestResource
{
    #[ApiProperty(identifier: true)]
    public int $id;
    public string $name;
    public int $number;

}
```

**App\Filter\TestFilter.php**"
```
namespace App\Filter;

use ApiPlatform\Core\Api\FilterInterface;
use Symfony\Component\PropertyInfo\Type;

class TestFilter implements FilterInterface
{


    public function __construct(
        private array $properties = [],
    )
    {
    }

    public function getDescription(string $resourceClass): array
    {
        $description = [];
        foreach ($this->properties as $property => $strategy) {
            $description["$property"] = [
                'property' => $property,
                'type' => Type::BUILTIN_TYPE_STRING,
                'required' => false,
                'description' => 'Filter with strategy: '.$strategy,
            ];
        }
        return $description;
    }
}
```

**App\DataProvider\TestDataProvider.php**
```
namespace App\DataProvider;

use ApiPlatform\Core\DataProvider\ContextAwareCollectionDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use App\Entity\TestResource;

class TestDataProvider implements ContextAwareCollectionDataProviderInterface, RestrictedDataProviderInterface
{


    public function __construct(
        private iterable $filterExtensions,
    )
    {
    }

    public function getCollection(string $resourceClass, string $operationName = null, array $context = [])
    {
        $availableFilters = iterator_to_array($this->filterExtensions);
        $xdebug_breakpoint_here = true;
    }

    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return TestResource::class === $resourceClass;
    }
}
```

**services.yaml**
```
    App\DataProvider\TestDataProvider:
        arguments:
            $filterExtensions: !tagged api_platform.filter

```

When calling:
```
curl -X 'GET' \
  'https://test.local.io/api/test_resources?page=1&name=searchstr' \
  -H 'accept: application/ld+json'
```
XDebug reports two instances of TestFilter:
![image](https://user-images.githubusercontent.com/27766961/144631311-bd310277-6e23-4583-bf81-62eab2172e09.png)

**Comment by zolex** [comment]
this is not a bug. you're mixing two concepts. In your example the TestFilter class is a Filter and seems to be an Extension at the same time.

Doctrine Extensions (Filter extensions) only make sense for DataProviders that fetch things from the database (I assume you don't want to do that because your entity is not a doctrine entity)

Filters are used by the filter extensions to pass in values into the extensions and then the extensions modify the database query according to the filter.

You probably want to create your own (non-doctrine) filter-extension with a custom service tag and inject that new tagged iterator as a dependency into your dataprovider.

**Comment by zolex** [comment]
but to not overcomplicate things: instead of implementing your custom non-doctrine FilterExtension you could simply inject the RequestStack into your DataProvider and get from the request what ever you need to provide your data. of course this is not a generic solution, but it's hard to say what is a good solution because you don't say what you actually want to do...

**Comment by acirulis** [comment]
My design goal is to separate entities from api resources (DTOs), which I`ve done with custom data providers/persisters. Data providers will still work with doctrine queries and make transformation to/from my DTO classes. Therefore I would like to reuse as much as built in functionality as possible. I have so far managed to reuse pagination (both Doctrine Paginator & API Platform's Pagination classes), works great. Now I am at Filters - my biggest misunderstanding was about Filter and Filter extension being the same thing.
RequestStack won't have access to ApiFilter() attribute properties, so I will explore extension approach more.

**Comment by zolex** [comment]
you don't need your own dataproviders to separate entities from DTOs. just use DataTransformers to do so!

**Comment by acirulis** [comment]
Yes, I considered and tested both - DataTransformers and DataProviders but decided to got with Data Providers:
1) DataProviders allows more flexibility in data selection (i.e. join from multiple entities, etc) and persistance if needed in the future. Transforming part can be easily implemented within Provider/Persister.
2) I will have cleaner separation between entities and resources
3) Api Platform docs also suggested custom Providers/Persisters as more common approach (https://api-platform.com/docs/core/design/)

It seems that I have solved Filters and can close this issue, once I understood and debugged through concept of FilterExtension vs Filter. Thanks @zolex

**Comment by AlinaSob** [comment]
In my case it was caused by inheritance: ApiFilter was defined for the property of an abstact superclass. 
I moved the Filter definition up to the abstract class itself (not its property) and it solved the problem.
