### ISSUE TITLE
Circular reference when decorating the serializer and using intersection type

### ISSUE THREAD

**Issue by jonag** [api-platform/core#4593]
**API Platform version(s) affected**: 2.6.6

**Description**  
Hello, I'm not sure if this should be handled through a documentation update or if there is something to do in the code to fix this.
I'm upgrading the PHP version on one of my projects to 8.1 and trying to use the new features of the language.

I have a custom Normalizer that decorate the API Platform one and defined like explained in the documentation :

```
services:
    'App\Serializer\UserNormalizer':
        # By default .inner is passed as argument
        decorates: 'api_platform.jsonld.normalizer.item'
```

```php
<?php

namespace App\Serializer;

(...)

final class UserNormalizer implements NormalizerInterface, DenormalizerInterface, SerializerAwareInterface
{
    /**
     * @param NormalizerInterface&DenormalizerInterface $decorated
     */
    public function __construct(
        private NormalizerInterface $decorated,
        private RoleHierarchyInterface $roleHierarchy,
    ) {
        if (!$decorated instanceof DenormalizerInterface) { // à retirer lors du passage à php 8.1 (remplacer par NormalizerInterface&DenormalizerInterface dans le constructeur)
            throw new \InvalidArgumentException(sprintf('The decorated normalizer must implement the %s.', DenormalizerInterface::class));
        }
    }

    (...)
}
```

I want to replace the check in the constructor with an intersection type, so my code looks like this :

```php
<?php

namespace App\Serializer;

(...)

final class UserNormalizer implements NormalizerInterface, DenormalizerInterface, SerializerAwareInterface
{
    public function __construct(
        private NormalizerInterface&DenormalizerInterface $decorated,
        private RoleHierarchyInterface $roleHierarchy,
    ) {
    }

    (...)
}
```

However, when doing that, Symfony throws an exception while clearing the cache :

> In CheckCircularReferencesPass.php line 67:
> 
>   [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
>   Circular reference detected for service "App\Normalizer\UserNormalizer", path: "App\Normalizer\UserNormalizer -> serializer -> App\Normalizer\UserNormalizer".

To fix the error I had to update my service definition by specifying explicitly which service to inject :

```
services:
    'App\Normalizer\UserNormalizer':
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments:
            $decorated: '@App\Normalizer\UserNormalizer.inner'
```

Is this the right fix (and if so, should I send a doc PR event if it's using a PHP 8.1 feature ?) or does something should be done in API Platform to handle this case correctly ?

**Comment by soyuka** [comment]
use [NormalizerAware](https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/Serializer/Normalizer/NormalizerAwareInterface.php)
