### ISSUE TITLE
EagerLoadingExtension does not respect serialization groups

### ISSUE THREAD

**Issue by rtwent** [api-platform/core#4594]
**API Platform version(s) affected**: 2.6.6

**Description**  
EagerLoadingExtension joins relations even if they are not in serialization context.

**How to reproduce**  
I've created an application from api-platform template https://github.com/rtwent/apitest. There are 3 entities. "Centers" is the main entity to reproduce behavior. There are two routes in "Centers" to reproduce unexpected for me database queries: "collection:get" and "collection:dropdown" (processed by controller). 
In "collection:get" i want to get a list of Centers with Representations and Groups bound to it - I expect two queries, that will join three tables because of ApiProperty(fetchEager=true): one for querying data, one for count.
In "dropdown" i just want to get the id and the name of the Center. I expect only one query, that will join nothing, only select data from Centers table. Pagination is disabled. Instead I get one query that joins three tables. Serialization groups for "collection:dropdown" are absent for "Representations" and "Groups" associations.

**Possible Solution**  
IMHO
In ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\EagerLoadingExtension::joinRelations() 
line 153
$propertyMetadata = $this->propertyMetadataFactory->create($resourceClass, $association, $options);
Seems does not respect ['serializer_groups'] in $options. I think it must be caught in try block.
I also read https://github.com/api-platform/core/issues/1290, may be such behavior is connected with readableLinks

**Additional Context**  
Doctrine query log for "collection:get" https://github.com/rtwent/apitest/blob/main/uploads/get_collection.png
Doctrine query log for "collection:dropdown" https://github.com/rtwent/apitest/blob/main/uploads/dropdown.png
I am new in Api-platform and may be it is expected behavior.
If I missed something in docs - i am sorry, just give me the right direction. (I spent two days and can not fix optimization issue)

**Comment by soyuka** [comment]
For complex use cases please use a custom state provider.
