### ISSUE TITLE
Fatal error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#460]
Is `phpdocumentor/reflection-docblock` required?

Otherwise we should check for its existence before registering the `api_platform.metadata.resource.metadata_factory.php_doc` service (`PhpDocResourceMetadataFactory`).

**Comment by dunglas** [comment]
Good catch. It should be checked.

**Comment by Simperfit** [comment]
@teohhanhui Can you close this ?
