### ISSUE TITLE
Unexpected non-object value for object property.

### ISSUE THREAD

**Issue by norkunas** [api-platform/core#4616]
**API Platform version(s) affected**: 2.6.7

**Description**  
Currently when you have an ApiResource on entity, which has a to-many relation with an object which is not an ApiResource, then it throws:
```
Symfony\Component\Serializer\Exception\UnexpectedValueException:
Unexpected non-object value for object property.

  at vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:649
```
**How to reproduce**  
```
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\OneToMany;

#[Entity()]
#[ApiResource()]
class Book {
  #[OneToMany(targetEntity: ExternalReview::class)]
  public Collection $externalReviews;
}
class ExternalReview {}
```

**Possible Solution**  
Maybe we should check if it's not a collection? Because if previous code paths didn't match where checking if `$type->isCollection()` then this https://github.com/api-platform/core/blob/2a2491c965570dd2e391dcfabcc30fb6ac6c7b1f/src/Serializer/AbstractItemNormalizer.php#L646-L657
totally ignores it.

**Additional Context**  
I was who cherry-picked the code in https://github.com/api-platform/core/pull/4521 to fix PropertyFilter on embedded objects and just added tests, but looks like I didn't test it thorougly in a full app context. :/

**Comment by OskarStark** [comment]
I have the same error, I upgraded from 2.6.6 to 2.6.7 🤷‍♂️

**Comment by OskarStark** [comment]
cc @silasjoisten

**Comment by fgarioli** [comment]
I have the same error, I upgraded from 2.6.6 to 2.6.7

**Comment by soyuka** [comment]
Should we revert https://github.com/api-platform/core/pull/4521 ?

**Comment by norkunas** [comment]
Please no :D see the possible solution I've added :)

**Comment by norkunas** [comment]
Please no :D see the possible solution I've added :)

**Comment by soyuka** [comment]
Then your fix won't work on nested collections. Changing the AbstractItemNormalizer is always risky maybe that we should instead find another solution to fix the Property filter? 

I should've checked in-depth, throwing here is a bad idea:

https://github.com/api-platform/core/pull/4521/files#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4fR643-R644

can you try just removing these lines?

**Comment by norkunas** [comment]
Yes it work then

**Comment by soyuka** [comment]
can you propose a patch removing the exception? I don't understand why it'd be needed.

**Comment by norkunas** [comment]
I don't either :) Will do

**Comment by digitaltim-de** [comment]
Same Error on Production!

**Comment by norkunas** [comment]
If you need a hotfix:
install https://github.com/cweagans/composer-patches
apply:
```diff
Index: vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php b/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php
--- a/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php	(revision ff6f385c1d74d480f0ccd727b01df61e9ae436de)
+++ b/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php	(date 1641538361510)
@@ -644,10 +644,6 @@
         unset($context['resource_class']);

         if ($type && $type->getClassName()) {
-            if (!\is_object($attributeValue) && null !== $attributeValue) {
-                throw new UnexpectedValueException('Unexpected non-object value for object property.');
-            }
-
             $childContext = $this->createChildContext($context, $attribute, $format);
             unset($childContext['iri']);


```

**Comment by Snowbaha** [comment]
Same issue for me, 40% of my tests faild with the 2.6.7. I rollback to 2.6.6 and I am waiting the 2.6.8

**Comment by digitaltim-de** [comment]
Will this be fixed?

**Comment by norkunas** [comment]
2.6.8 was released 6 days ago
