### ISSUE TITLE
[BC Break] 2.6 broke messenger support when using inheritance on entities

### ISSUE THREAD

**Issue by skalpa** [api-platform/core#4620]
**API Platform version(s) affected**: 2.6.7

**Description**  
2.6 changed the content of `$context['resource_class']` in some cases and broke messenger support 
(and probably more, that looks related to #4507) when using inheritance on entities.

**How to reproduce**  
I use inheritance on some entities:

```php

#[ORM\Entity]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'discr', type: 'string', length: 5)]
#[ORM\DiscriminatorMap(['' => Account::class, 'foo' => FooAccount::class, 'bar' => BarAccount::class])]
class Account {}

#[ORM\Entity]
class FooAccount extends Account {}
```

This is not advertised on public endpoints where consumers only know that they are getting an `Account`:

```yaml

Account:
  itemOperations:
    some-op:
      method: POST
      path: "/accounts/{id}/some-op"
      messenger: input
      input: Commands\SomeCommand
```

So there, the current resource retrieved by the data provider may actually be an instance of `Account` or of one of the child classes.

This worked fine on 2.5. However on 2.6, the `DataTransformer` is unable to find the `messenger` attribute and does not transform the input.

I was able to track this to #3273 and more precisely the changes in `AbstractItemNormalizer::denormalize()`.

Under 2.5: `$context['resource_class']` contains `Account`, the correct class defined in the configuration and everything works fine.

Under 2.6: If the current object to populate is an instance of `FooAccount`, then the call to `ResourceClassResolver::getResourceClass()` will now return the class of the object (which differs from the one in the configuration).

Subsequently, the data transformer will try to retrieve the `messenger` attribute of the `some-op` operation for the `FooAccount` resource class and fail to find it as it does not exist.

**Possible Solution**  
As `$context['resource_class']` is used in multiple places to retrieve metadata from the configuration it should always match the class used in the configuration (as it was the case in 2.5.x).

**Comment by soyuka** [comment]
Data transformers got removed, please check the new 2.7 and it'll get easier.
