### ISSUE TITLE
assertMatchesResourceItemJsonSchema returns invalid error "NULL value found, but an integer is required"

### ISSUE THREAD

**Issue by fancyproject** [api-platform/core#4621]
I just installed the latest version (2.6.7) of api-platform and I see new errors which did not arrive before.

In test I run this command:

`self::assertMatchesResourceItemJsonSchema(PayoutEntity::class);`

Then I receive:
```
App\Tests\EndpointTest::testGetPayoutItem
Failed asserting that Array &0 (
    'id' => '44a20ebe-9835-349b-9d16-3d3ec972d976'
    'netPay' => null
) matches the provided JSON Schema.
netPay: NULL value found, but an integer is required
```

Definition in PayoutEntity:

```class PayoutEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string")
     * @Groups({"payout"})
     *
     * @ApiProperty(openapiContext={"maxLength": 40})
     */
    private string $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"payout"})
     *
     * @ApiProperty(openapiContext={"type":"integer", "nullable": true},
     *     description="Net pay in cents")
     */
    private ?int $netPay;
}
```

Validation doesn't use nullable parameter from @ApiProperty annotation

**Comment by David-Crty** [comment]
Same issue here, I'm on **v2.6.8** & **Symfony 6**
Here is a screentshot showing the good nullable in the api doc :
![image](https://user-images.githubusercontent.com/3600892/149842048-57f28a63-9fea-4159-afe1-ab50f454e52a.png)

And here is what I get using `$this->assertMatchesResourceCollectionJsonSchema(Tile::class);` in my test

```
hydra:member[2].imagePreview: NULL value found, but an object is required
hydra:member[2].imagePreview: Failed to match at least one schema
hydra:member[2].imageLargePreview: NULL value found, but an object is required
hydra:member[2].imageLargePreview: Failed to match at least one schema
```

I try to force the nullable with `openapi_context` but I get the same result, maybe we are doing something wrong ?

**Comment by alanpoulain** [comment]
The issue comes from this condition block:
https://github.com/api-platform/core/blob/f966ddea3bb719597606d31f92d3cb5f0679da20/src/JsonSchema/TypeFactory.php#L171-L176
The nullable `$ref` should be handled differently in a JSON Schema, with `null` inside the `type` array instead of the `nullable` property.
See also:
https://github.com/api-platform/core/blob/f966ddea3bb719597606d31f92d3cb5f0679da20/src/JsonSchema/TypeFactory.php#L178-L187

PR welcome.
