### ISSUE TITLE
Should work when PropertyMetadata::getType returns null

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#463]
Should work without PropertyInfo since it's not listed in `require`

Too many places that we assume it's always available. There should be fallbacks / graceful degradation.

Currently at least `ItemNormalizer` would not behave properly, and also the `NelmioApiDocBundle` integration which just errors out.

**Comment by dunglas** [comment]
Should be added to require. It cannot work without it, the `Type` class is a hard dependency.

**Comment by teohhanhui** [comment]
It's still a problem when PropertyInfo fails to detect the `Type` of a property. Things should not just break like that.

**Comment by teohhanhui** [comment]
I suppose this is only a problem with the `NelmioApiDocBundle` integration part...

**Comment by theofidry** [comment]
As `symfony/property-info` has been added to the require, what's left is the case where `PropertyMetadata::getType()` returns `null`. Is there a reason why we allow it to be `null`?

**Comment by teohhanhui** [comment]
It's not so much that we *allow* it to be null, but rather it might not always be possible to infer the type information.

**Comment by teohhanhui** [comment]
Are you suggesting that the user must be forced to specify the type manually if such information cannot be inferred by the PropertyInfo extractors?

**Comment by theofidry** [comment]
I'm not suggesting anything yet :) I simply with to understand the nature of the problem. Having a property type sucks (or looks like it).

Is there another case than the user not providing the type where it might fail? And what's our current strategy when dealing with a property without a type?

**Comment by dunglas** [comment]
I'm ok to force the user to provide a type. Many things will not be ok if the system isn't able to find the type of the property (recursive denormalization, Hydra doc...). We can create something like a `CheckValidMetadataFactory` that decorate the last factory and check if everything is valid, and throw an exception either.

Another (similar) approach is to add a debug command to validate the mapping.

**Comment by theofidry** [comment]
>Another (similar) approach is to add a debug command to validate the mapping.

That would be great regardless of how we solve the first issue.

>We can create something like a CheckValidMetadataFactory that decorate the last factory and check if everything is valid, and throw an exception either.

Why not just not allowing to create a `Property` with its type set to `null`?

**Comment by teohhanhui** [comment]
> Why not just not allowing to create a Property with its type set to null?

The contract should be such that *some* metadata factory decorator will populate the type. It must remain nullable, because it might not be the responsibility of that particular decorator.

**Comment by theofidry** [comment]
>The contract should be such that some metadata factory decorator will populate the type. It must remain nullable, because it might not be the responsibility of that particular decorator.

I'm not sure to agree with that. Why not forcing it at the object construction level? Having things at the constructor level guarantees that the instantiated object will not result in an inconsistent state.

**Comment by teohhanhui** [comment]
> Why not forcing it at the object construction level? Having things at the constructor level guarantees that the instantiated object will not result in an inconsistent state.

Take a look at the current pattern of factory with decorators. I don't think that's doable if we stick to the pattern.

**Comment by theofidry** [comment]
Ha indeed, would require to switch to builder instead...

**Comment by theofidry** [comment]
Well nevermind, let's do it that way then. Let's stick to making sure factories are returning properties with a valid state.

**Comment by Simperfit** [comment]
What is the ETA on this ?

**Comment by Simperfit** [comment]
Closing as no feedback since 1yr.
