### ISSUE TITLE
`deep_object_to_populate: true` causes failure to update existing subresources

### ISSUE THREAD

**Issue by rimas-kudelis** [api-platform/core#4630]
When executing a partial update, and subresources are linked by their IRIs in the update payload, API Platform will fail to update them and instead attempt to create new ones.

This happens when `deep_object_to_populate` is `true` in the deserialization context, which is the case for all PATCH requests by default.

---

The long story:

While working on sylius/sylius#13441, I discovered that you can't just exchange PUT requests for PATCH ones at the moment, because even if you take care to change request Content Type, a PUT request like this will work, but a PATCH request will fail:

```
PUT|PATCH /api/v2/admin/product-variants/product1

{
    "channelPricings": {
        "default": {
            "@id": "/api/v2/admin/channel-pricings/1",
            "price": 3000,
            "originalPrice": 4000
        }
    }
}
````

This key here is that a related (ToMany) resource is being updated. By tracing these otherwise identical PUT and PATCH request, I stumbled upon this piece of code which appears to trigger a bug:
https://github.com/api-platform/core/blob/119b05b631aae94a922838c6c3ba2f64618210a5/src/Serializer/SerializerContextBuilder.php#L83-L85

The actual bug, I think is elsewhere, but this is the snowball which causes it later.

When `deep_object_to_populate` is `true`, Symfony Serializer [adds the object to populate](https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L394-L399) (the collection in this case) to the attribute deserialization context.

...which later on causes JSON-LD normalizer to **not** fill in this context key with the correct object (using the IRI), instead retaining the collection which is already there:
https://github.com/api-platform/core/blob/119b05b631aae94a922838c6c3ba2f64618210a5/src/JsonLd/Serializer/ItemNormalizer.php#L139-L151

Since that collection cannot be used as an object to populate the resource afterwards and [`extractObjectToPopulate()` returns null](https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Component/Serializer/Normalizer/ObjectToPopulateTrait.php#L24-L33), a new object is being created instead:
https://github.com/api-platform/core/blob/119b05b631aae94a922838c6c3ba2f64618210a5/src/Serializer/AbstractItemNormalizer.php#L226-L229

I think there are two issues at hand here:
1. special processing for PATCH requests which triggers the bug for PATCH requests only.
2. when building a context to serialize a single item within a collection, `object_to_populate` (if it is set in the parent context) is neither cleared, nor updated, which is the root cause of the bug.

**Comment by dunglas** [comment]
Thank you for the in depth investigation!

Do you think you could work on a PR to fix these bugs?

**Comment by rimas-kudelis** [comment]
Hmm, not sure. My brain almost exploded just writing all this. I have a hunch that Symfony's default denormalizer should probably be used for collections (instead of building an array in AbstractItemNormalizer), but I have no idea why it isn't like that at the moment.

**Comment by rimas-kudelis** [comment]
@dunglas I could certainly make a PR removing the special case for PATCH from `SerializerContextBuilder`. My gut says `$context['deep_object_to_populate']` should either always be set for updates, or never be set.,But it should not depend on the method. What do you think?

**Comment by dunglas** [comment]
I tend to agree but I need to double check... we can at least check if tests still pass if we remove this option for PATCH.

**Comment by usu** [comment]
Nice debug job @rimas-kudelis. I ran into the same issue but never got as far as you to identify the real root cause.

Issue https://github.com/api-platform/core/issues/4293 already described the same problem, but unfortunately was closed earlier last year. In that issue, @mbrodala posted a [workaround ](https://github.com/api-platform/core/issues/4293#issuecomment-831252083) that kind of worked for us. But of course it would be so much nicer to have a proper solution directly in the core.

**Comment by rimas-kudelis** [comment]
@dunglas I wonder what your team's position on this will be.

After reading #4293, I tend to disagree with @soyuka on whether patch currently works as expected, particularly when patching collection items is involved. I strongly believe that it doesn't. The JSON Merge Patch RFC has no knowledge of JSON-LD, so of course it could not say that if an embedded item is referenced by an IRI, you have to update the embedded item. But JSON-LD says very clearly that IRIs are identifiers (well, they are Internationalized Resource **Identifiers**, after all), so NOT updating an unambigously identified collection item seems to me like a wrong choice here.

Also, although this wasn't discussed in #4293, updating items in "associated" collections (in contrast to "indexed" collections ) should also work, because, at the very least, from the client's point of view, these collections are objects and not arrays.

Indexed collections, however, should lose all of their other members when patched. That is, if I had a resource like this:
```json
{
  "@context": "/api/contexts/Person",
  "@id": "/api/people/1",
  "@type": "Person",
  "firstName": "John",
  "lastName": "Smith",
  "addresses": [
    {
      "@id": "/api/addresses/1",
      "@type": "Address",
      "city": "New York",
      "street": "736 Manor Station St.",
      "country": "USA"
    },
    {
      "@id": "/api/addresses/2",
      "@type": "Address",
      "city": "Boston",
      "street": "7 Denver St.",
      "country": "USA"
    }
  ]
}
```
... and I attempted to update it like this:
```http
PATCH /api/people/1

{
  "addresses": [
    {
      "@id": "/api/addresses/1",
      "street": "63 Oak St."
    }
  ]
}
```
... the first address should be updated and the second one should be removed from the collection, resulting in an object like this:
 ```json
{
  "@context": "/api/contexts/Person",
  "@id": "/api/people/1",
  "@type": "Person",
  "firstName": "John",
  "lastName": "Smith",
  "addresses": [
    {
      "@id": "/api/addresses/1",
      "@type": "Address",
      "city": "New York",
      "street": "63 Oak St.",
      "country": "USA"
    }
  ]
}
```

**Comment by soyuka** [comment]
we need to get to the bottom of this eventually

**Comment by erikkubica** [comment]
Guys, can you please take a look at my last comment on a related issue? https://github.com/api-platform/core/issues/4293#issuecomment-1711782012
