### ISSUE TITLE
Cannot use class name for "validationGroups" in ApiResource attribute

### ISSUE THREAD

**Issue by mbrodala** [api-platform/core#4632]
**API Platform version(s) affected**: v2.6.8

**Description**  

When migrating the `@ApiResource` annotation with an `#[ApiResource]` attribute (PHP >= 8.0), the `validationGroups` property does not support a class name anymore. Before this was used to e.g. configure a class implementing the `ValidationGroupsGeneratorInterface` for dynamic validation groups.

Trying to migrate 1:1 results in an error:

```
[TypeError] ApiPlatform\Core\Annotation\ApiResource::__construct(): Argument #42 ($validationGroups) must be of type ?array, string given, called in /var/www/html/src/Entity/<entity>.php on line <line>
```

**How to reproduce**  

Add an `ApiResource` attribute to any class including a validation groups generator class name for `validationGroups`:

```php
#[ApiResource(
    # ...
    validationGroups: MyValidationGroupsGenerator::class,
)]
```

**Possible Solution**  

[The docs suggest](https://api-platform.com/docs/core/validation/#dynamic-validation-groups) to basically bypass the `ApiResource` attribute constructor and directly set the class name via `attributes` instead:

```php
#[ApiResource(
    # ...
    attributes: [
        'validation_groups' => MyValidationGroupsGenerator::class,
    ],
)]
```

From my POV this should have native support, especially since `Validator` did not change here.

**Comment by alanpoulain** [comment]
Thanks for this early testing!
Could you make a PR to allow a string in the metadata?

**Comment by mbrodala** [comment]
@alanpoulain I did a first step in #4640, can you have a look?

**Comment by soyuka** [comment]
Ohh I see, this is possible with API P 2.7 on the main branch though.
