### ISSUE TITLE
"Unable to generate an IRI for" when strategy set to IDENTITY

### ISSUE THREAD

**Issue by Lenny4** [api-platform/core#4633]
**API Platform version(s) affected**: 2.6.8
**PHP version**: 8.0
**POSTGRES version**: 13

**Description**  
I got 2 entites: `A` and `B`
```php
#[ApiResource(
    collectionOperations: [
        'get',
        'post',
    ],
    itemOperations: [
        'get',
    ],
)]
class A
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'a', targetEntity: B::class, cascade: ['persist'])]
    private array|PersistentCollection|ArrayCollection $bs;

    public function __construct()
    {
        $this->bs = new ArrayCollection();
    }
}
```

```php
#[ApiResource(
    collectionOperations: [
        'get',
    ],
    itemOperations: [
        'get',
    ],
)]
class B
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string')]
    private ?string $name = null;

    #[ORM\ManyToOne(targetEntity: A::class, inversedBy: 'bs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?A $a = null;
}
```

When I do a `POST` on `/a`:
```json
{
  "bs": [
    {"name": "1"},
    {"name": "2"}
  ]
}
```
My `A` and 2 `B` entities are created normaly.

Now I modify the `#[ORM\GeneratedValue]` of both entities to `#[ORM\GeneratedValue(strategy: 'IDENTITY')]` [doc here](https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/basic-mapping.html#identifier-generation-strategies)

When I do the same `POST` on `/a`, I got error:
```
{
    "@context": "/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Unable to generate an IRI for \"App\\Entity\\B\".",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/srv/api/vendor/api-platform/core/src/Bridge/Symfony/Routing/IriConverter.php",
            "line": 158,
            "args": []
        },
```

I don't anderstand why this error occur when I change the strategy to 'IDENTITY'.

Is it a bug ? Or did I miss something ?

It seems like if the id is not generated by doctrine API Platform can't handle the generation of the IRI, because when strategy 'IDENTITY' is selected the id is generated by the bdd when the row in added.

Thank you

**Comment by sheldonjuncker** [comment]
I'm also getting this error. What was the solution and why is this closed?

**Comment by sheldonjuncker** [comment]
Aha! It was because we both forgot to include getters for our id field. :) 

add the following and it works perfectly:
```php
public function getId(): ?string
{
    return $this->id;
}
```
