### ISSUE TITLE
Symfony 6 serializer compatibility 

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#4635]
**API Platform version(s) affected**:2.6.8

**Description**  
Trying to upgrade project to symfony 6, getting Compile Error:

" Fatal error: Declaration of ApiPlatform\Core\JsonLd\Serializer\ObjectNormalizer::normalize($object, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Normalizer\NormalizerInterface::normalize(mixed $object, ?string $format = null, array $context = []): ArrayObject|array|string|int|float|bool|null in /Users/mitalcoi/development/phonedo_project/phonedo/vendor/api-platform/core/src/JsonLd/Serializer/ObjectNormalizer.php on line 65
"

The only way to temporary fix - is to update directly in vendor/ folder specific types:
<img width="1092" alt="Снимок экрана 2022-01-17 в 14 05 52" src="https://user-images.githubusercontent.com/3224226/149758666-7f577946-a2c9-4ba5-ba48-94b71471343c.png">

**Comment by PierreRebeilleau** [comment]
What's your php version ? And ```Symfony\Component\Serializer\Normalizer\NormalizerInterface```  should look like this in vendor after update to sf6: 
 
![image](https://user-images.githubusercontent.com/49146882/149777011-d036c9be-df7a-4ee9-808c-73df7ef9be21.png)

**Comment by chalasr** [comment]
The `NormalizerInterface::normalize()` return type declaration has been removed in symfony/serializer v6.0.1 so it looks like you installed v6.0.0. Try running `composer update symfony/serializer --no-cache`

**Comment by mitalcoi** [comment]
Upgrading to serializer v6.0.1 fixed issue, thx a lot!
