### ISSUE TITLE
[UI] export the SwaggerUIBundle object to allow extensions

### ISSUE THREAD

**Issue by b2p-fred** [api-platform/core#4643]
**Description**  
Considering that:
1. It is allowed to [override the UI template](https://api-platform.com/docs/core/openapi/#overriding-the-ui-template)
2. In the `init-swagger-ui.js` released script, you create an instance of the SwaggerUIBundle object to configure the UI. 

I created a specific Javascript file to manage some extensions in the UI but I cannot get the SwaggerUIBundle object created during the setup... and it would be a non-sens to create a new one as it is still available.

a simple 
```
window.ui = ui;
``` 
at the end of the `window.onload` function would allow to get this object in another script.

A current solution is to replace the `init-swagger-ui.js` distributed script with a modified copy `init-swagger-ui.js` that simply exports the `ui` created object !

**Comment by dunglas** [comment]
+1 on my side. I would call the variable `swaggerUI`.

Do you want to work on a PR?

**Comment by b2p-fred** [comment]
I cloned the repo and I would submit a PR as soon as I have something acceptable :wink:
