### ISSUE TITLE
Support PKCE Authorization Code Grant on Swagger UI

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#4646]
**Description**
API Platform enables an `oauth` option through the Swagger UI OAuth 2.0 support. But when the documentation is exposed on production (which is the case most of the time), the "client_secret" is leaked in the Swagger UI JavaScript code.

According to the [Swagger UI OAuth 2.0 configuration](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/):
> Never use this parameter in your production environment. It exposes cruicial security information. This feature is intended for dev/test environments only.

Alternatively, we could use the PKCE Authorization Code Grant. This would prevent the "client_secret" to be leaked, as far as we don't need the "client" (in this case: Swagger UI) to be fully identified.

**Example**
Add a new config key `usePkceWithAuthorizationCodeGrant` on the bundle configuration and enable it on the `initOAuth` call. This option is available on Swagger UI since 3.24.0.

**Comment by dunglas** [comment]
Shouldn't this be reported directly to Swagger UI? Btw this isn't a prod tool so we respect the spec.

**Comment by vincentchalamon** [comment]
Swagger UI already supports it, thanks to the `usePkceWithAuthorizationCodeGrant` option. But in API Platform, we don't use this option: https://github.com/api-platform/core/blob/main/src/Symfony/Bundle/Resources/public/init-swagger-ui.js#L59-L68

**Comment by vincentchalamon** [comment]
> Btw this isn't a prod tool so we respect the spec.

Does it mean that we should not use the `oauth` API Platform configuration option in production? If so, we should definitively document it and explain why.

**Comment by dunglas** [comment]
+1 to support this option then! Couldn't we find a future-proof way to allow passing any Swagger UI options in the configuration?
