### ISSUE TITLE
GraphQL Iterable Filter Property 

### ISSUE THREAD

**Issue by kingschnulli** [api-platform/core#4651]
**API Platform version(s) affected**: 2.6.5

**Description**  
I'm trying to implement a (GraphQL) Filter that allows to send arbitary json as it's parameter.
It seems like the read stage somehow treats my arrays as objects which will lead to parts of 
the query being dropped.

**How to reproduce**  
```
<?php

declare(strict_types=1);

namespace App\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\FilterInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\PropertyInfo\Type;

final class JSONFilter implements FilterInterface
{
    private const PARAMETER_NAME = 'filter';

    public function apply(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null, array $context = [])
    {
        $filter = $context['filters'][self::PARAMETER_NAME] ?? null;
        if (null === $filter) {
            return;
        }
        print_r($filter);
        exit();
    }
    public function getDescription(string $resourceClass): array
    {
        $description[self::PARAMETER_NAME] = [
            'type' => Type::BUILTIN_TYPE_ARRAY,
            'required' => false,
            'property' => self::PARAMETER_NAME,
            'swagger' => [
                'description' => 'Filter using complex filter object',
                'name' => 'Filter',
                'type' => 'Custom filter',
            ],
        ];
        return $description;
    }
}
```
GraphQL Example Query, enabled filter for "Review" Entity in demo application
```
{
    reviews(filter: [
        {a: "b", b: "c"}, {a: "b2", b: "c2"}
    ]) {
        edges {
            node {                
                id
                author
            }
        }
    }
}
```
I would expect to have an array of arrays or array of objects, instead the simple debug output looks like:
```
Array
(
    [a] => b2
    [b] => c2
)
```

**Possible Solution**  
I think this is somehow because of IterableType thinking my value is ObjectValueNode instead of ListValueNode

**Comment by alanpoulain** [comment]
Hello,
I don't think we should have a feature like this. Maybe the better strategy would be to have the `getNormalizedFilters` method inside a dedicated service, and you would be able to decorate it to change its behavior like you want.

**Comment by kingschnulli** [comment]
Yes this would be completely sufficient and will keep out userland clutter of the core. Voting for having a dedicated service for getNormalizedFilters.
