### ISSUE TITLE
[OpenApi] Subresource path description wrong/missleading

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#4663]
**API Platform version(s) affected**: 2.6.8
**Description**  
Assuming you have the following classes:

```
#[ApiResource]
class Project {
    ...
    #[OneToMany(mappedBy: 'project', targetEntity: Transaction::class)]
    #[ApiSubresource]
   private Collection $collectionOfB;
}

#[ApiResource]
class Transaction {
   ...
    #[ManyToOne(targetEntity: A::class)]
    #[JoinColumn(name: 'project_id', referencedColumnName: 'id'')]
   private Project $project;
}
```

You'd expect the openApi to generate generate the subresource to be something like this:
```
[/api/projects/{id}/transactions] Retrieves a collection of Transaction resources.
```

You'll actually get this though:
![Screenshot 2022-02-22 at 16 12 20](https://user-images.githubusercontent.com/24696606/155161575-80f63174-452e-4f9d-a325-7b43d0ebf58b.png)

**How to reproduce**  
Setup a subresource as described above and go to the api docs.

**Possible Solution**  
n.A

**Additional Context**  
n.A

**Comment by henrikac** [comment]
The expected and the actual looks the same to me - I see no difference.

**Comment by KDederichs** [comment]
@henrikac It's in the description, if you looks closely on the picture it says 'Receives a PROJECT resource' while it should say Transaction.

**Comment by henrikac** [comment]
@KDederichs oh, I see. I thought you were talking about the url. I did  not learn about the subresource in api platform until like a week ago and my experience so far has been that they are difficult to configure.

**Comment by KDederichs** [comment]
tbh from what I've seen at the Symfony Live it might be mute with 2.7/3.0 anyways since they're scrapping the current sub resources, though maybe the same thing also occurs with the new Link attribute
