### ISSUE TITLE
[Bug] v3 without backwards compatibility - does not call decorated resource metadata factory for XML defined resources

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#4698]
**API Platform version(s) affected**: x.y.z

**Description**  
I have some resources defined in XML in the new schema. These resources are not included in the class names passed to any of my resource metadata factory extensions.

**How to reproduce**  
Check if a resource class that is defined in XML v3 is passed to the resource metadata factory class

**Possible Solution**  
Investigating.

**Additional Context**  
n/a

**Comment by silverbackdan** [comment]
Additionally I seem to get an error trying to delete the resource
```
Resource \u0022Silverback\\ApiComponentsBundle\\Entity\\Component\\Collection\u0022 not found.
```

The route is there though and I am calling it as I would have done before
```
_api_Collection_delete                                                DELETE   ANY      ANY    /component/collections/{id}.{_format}       
```

My XML for this resource:
```
<resources xmlns="https://api-platform.com/schema/metadata/resources-3.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://api-platform.com/schema/metadata/resources-3.0
           https://api-platform.com/schema/metadata/resources-3.0.xsd">
    <resource class="Silverback\ApiComponentsBundle\Entity\Component\Collection"
              output="Silverback\ApiComponentsBundle\Entity\Component\Collection"
              routePrefix="/component"
    />
</resources>
```

**Comment by alanpoulain** [comment]
Could you show us your configuration for your decorated metadata factory?

**Comment by silverbackdan** [comment]
Hi, sorry, I see that I'm decorating and extending the legacy `ResourceMetadataFactoryInterface` instead of `ResourceMetadataCollectionFactoryInterface` - so some resources are passed only to the legacy, and some passed to the latest when I create another factory. I'll continue to research and try to make all my resources compatible and using the non-legacy features.
