### ISSUE TITLE
[Bug][v3][Pagination] V3 pagination limits seem to be broken

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#4699]
**API Platform version(s) affected**: dev-master - v3.0 (no backwards compatibility)

**Description**  
On dev-master without backwards compatibility pagination seems to be broken.

**How to reproduce**  
I have a behat test running:
```
Scenario Outline: Pagination parameter is configured
    Given there are 120 DummyResourceWithPagination resources
    When I send a "GET" request to "/dummy_resource_with_paginations<postfix>"
    Then the response status code should be 200
    And the JSON node "hydra:member" should have "<total>" elements
    Examples:
      | total  | postfix           |
      | 10     |                   |
      | 20     | ?perPage=20       |
      | 40     | ?perPage=110      |
      | 120    | ?pagination=false |
      | 120    | ?perPage=0        |
```

and the attributes on the resource setup as 
```php
#[ApiResource(
    paginationClientEnabled: true,
    paginationClientItemsPerPage: true,
    paginationItemsPerPage: 10,
    paginationMaximumItemsPerPage: 40
)]
#[Get]
#[GetCollection]
#[ORM\Entity]
class DummyResourceWithPagination
{
    use IdTrait;
}
```

The test for pagination set to 110 by the client should return just 40, but returns 100. perPage 0 is returning 0 results, I think it defaulted to disabling pagination before.. but perhaps I'm mistaken and the only bug is allowing a user to override the max items per page.

**Possible Solution**  
not sure yet.

**Additional Context**  
I have set the config `api_platform.collection.pagination.items_per_page_parameter_name` to `perPage`

**Comment by silverbackdan** [comment]
I'm investigating this still.. It seems the ORM PaginationExtension does not find the request in my test to apply all of the logic and the request is instead passed to `ApiPlatform\State\Pagination\Pagination` - I am just making a dummy GET request in Behat to `/dummy_resource_with_paginations?perPage=110` so something here is a little strange - I've a complicated application so I'm working through to see if there's something else interfering somehow.

**Comment by silverbackdan** [comment]
So it appears no matter what I do with my attributes as shown here:
```
<?php

/*
 * This file is part of the Silverback API Components Bundle Project
 *
 * (c) Daniel West <daniel@silverback.is>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Silverback\ApiComponentsBundle\Tests\Functional\TestBundle\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\ORM\Mapping as ORM;
use Silverback\ApiComponentsBundle\Entity\Utility\IdTrait;

/**
 * @author Daniel West <daniel@silverback.is>
 */
#[ApiResource(
    paginationClientEnabled: true,
    paginationClientItemsPerPage: true,
    paginationItemsPerPage: 10,
    paginationMaximumItemsPerPage: 40
)]
#[Get(
    paginationClientEnabled: true,
    paginationClientItemsPerPage: true,
    paginationItemsPerPage: 10,
    paginationMaximumItemsPerPage: 40
)]
#[GetCollection(
    paginationClientEnabled: true,
    paginationClientItemsPerPage: true,
    paginationItemsPerPage: 10,
    paginationMaximumItemsPerPage: 40
)]
#[ORM\Entity]
class DummyResourceWithPagination
{
    use IdTrait;
}
```

`$operation->getPaginationMaximumItemsPerPage()` will always return 100. For some reason, even though I am setting the maximum items per page, it is not propagating through or being overridden. Still investigating...

**Comment by silverbackdan** [comment]
Sure, but it'll be `null === resourceMetadata->{$getter}()` because the method you linked to will cancel and return the original with the condition `if (null !== $resourceMetadata->{$getter}()) { ` whereas in the context of the metadata factory, the condition means we want to overwrite the value.

**Comment by alanpoulain** [comment]
You're right my answer is not clear.
The two methods are indeed "inverted" but the final result needs to be the same (which is not the case in `main`).

**Comment by silverbackdan** [comment]
I've opened a PR and added a test.. although I'm not sure of the structure of tests and if I added the entity with preferred naming conventions or tests in the correct place. But at least there is a test which should ensure that the attribute parameters will not be over-ridden by the defaults.

Just a Behat functional test - do you need any unit testing?

LMK if there's anything else I can do or need to for the fix.
