### ISSUE TITLE
Invalid submitted json is reported as server error

### ISSUE THREAD

**Issue by rimas-kudelis** [api-platform/core#4704]
**API Platform version(s) affected**: 2.6.8

**Description**  
When invalid JSON is being submitted to a POST endpoint, a 500 status code is being returned even though invalid input is a user error, not that of the server. A proper status code for this case would be 400, I think.

**How to reproduce**  
Submit intentionally broken JSON body to a POST endpoint, e.g., without a closing brace.

For a quick demo:
1. Open https://demo.sylius.com/api/v2/.
2. Find the group of requests named "Customer".
3. Expand the POST endpoint
4. paste the following body and submit the request:
   ```json
   {
     "firstName": "John",
     "lastName": "Doe",
     "email": "jdoe@example.com",
     "password": "Password",
     "subscribedToNewsletter": true
   ```
5. Note that you get a 500 server error. If you add the missing brace, you'll get an expected response code (204 or 422).

**Comment by gaetan-petit** [comment]
It's actually weird that default configuration doesn't come with:

    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400

**Comment by rimas-kudelis** [comment]
Has it really been fixed though?
