### ISSUE TITLE
Issue with link when creating (POST) a resource using a subresource

### ISSUE THREAD

**Issue by loic425** [api-platform/core#4710]
**API Platform version(s) affected**: 2.7.x

**Description**  

```php
#[ApiResource(
    uriTemplate: '/libraries/{id}/books',
    uriVariables: [
        'id' => new Link(
            fromClass: Library::class,
            toProperty: 'library',
        )
    ],
    operations: [new GetCollection(), new Post()]
)]
class Book
```

#### Route
```bash
_api_/libraries/{id}/books_get_collection   GET      ANY      ANY    /api/libraries/{id}/books 
_api_/libraries/{id}/books_post             POST     ANY      ANY    /api/libraries/{id}/books
```

#### Doctrine query to create the link to library

```SQL
SELECT b0_.id AS id_0, b0_.name AS name_1, b0_.created_at AS created_at_2, b0_.library_id AS library_id_3 
FROM book b0_ 
INNER JOIN library l1_ 
    ON b0_.library_id = l1_.id 
WHERE l1_.id = ?"
```

This query returns more than one row to get the library.

**How to reproduce**  

You can use this "testing" project to reproduce the bug => https://github.com/loic425/test-api-platform-2.7/blob/main/tests/Controller/BookApiTest.php#L65

**Comment by soyuka** [comment]
I don't get why `POST` would try to read data, for now we didn't try to use subresources to do writes.

**Comment by loic425** [comment]
@soyuka Yes, but that be awesome ;)

**Comment by zeromodule** [comment]
@loic425 have you found the solution?

**Comment by soyuka** [comment]
Use the `handleLinks` https://api-platform.com/docs/guides/handle-links/ feature

**Comment by henryfoster** [comment]
@soyuka But this can't be the solution right?
It makes no sense to do a select for a POST.

I implemented this hack which works but this can't be the way to solve this:
`    public static function handleLinks(QueryBuilder $queryBuilder, array $uriVariables, QueryNameGeneratorInterface $queryNameGenerator, array $context): void
    {
        $queryBuilder->andWhere($queryBuilder->getRootAliases()[0].'.realEstate = :realEstateId')
            ->setParameter('realEstateId', $uriVariables['realEstateId'])->setMaxResults(1);
    }`
