### ISSUE TITLE
Setting uriVariables without a direct relationship between classes

### ISSUE THREAD

**Issue by lermontex** [api-platform/core#4723]
**Description**  
Is it possible to set up a variable (uriVariables) if there is no direct relationship between classes (2.7@dev)? Unfortunately, I did not find an example in the documentation. Is such a possibility planned?

**Example**  
```
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ApiProperty(identifier: true)]
    private Ulid $id;

    #[ORM\OneToMany(mappedBy: "user", targetEntity: Domain::class, orphanRemoval: true)]
    private iterable $domains;
}
```

```
#[ORM\Entity(repositoryClass: DomainRepository::class)]
#[ApiResource(
    uriVariables: [
        'userId' => new Link(fromProperty: 'domains', fromClass: User::class),
        'id' => new Link(fromClass: self::class, identifiers: ['id'])
    ],
)]
#[Get(
    uriTemplate: '/users/{userId}/domains/{id}.{_format}',
)]
class Domain
{
    #[ORM\Id]
    #[ApiProperty(identifier: true)]
    private Ulid $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: "domains")]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: "domain", targetEntity: ResetTokenRequest::class, orphanRemoval: true)]
    private iterable $resetTokenRequests;
}
```

```
#[ORM\Entity(repositoryClass: ResetTokenRequestRepository::class)]
#[ApiResource(
    uriVariables: [
        'userId' => new Link(...), // <<<---------???
        'domainId' => new Link(fromProperty: 'resetTokenRequests', fromClass: Domain::class),
        'id' => new Link(fromClass: self::class, identifiers: ['id'])
    ],
    normalizationContext: ['groups' => ['user:domain:reset_token_request:read_normalization']],
)]
#[Get(uriTemplate: '/users/{userId}/domains/{domainId}/reset_token_requests/{id}.{_format}',)]
class ResetTokenRequest
{
    #[ORM\Id]
    #[ApiProperty(identifier: true)]
    private Ulid $id;

    #[ORM\ManyToOne(targetEntity: Domain::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Domain $domain;
}
```

Is it possible to set `userId` variable with Link?

**Comment by soyuka** [comment]
Yes this should work, juste define your `userId` link between Domain and User I'm guessing `new Link(fromProperty: 'domains', fromClass: User::class)`

**Comment by lermontex** [comment]
Unfortunately, it didn't work

```
curl -X 'GET' \
  'https://localhost/api/users/01G1CJ7WF6B46AWM4EWTKZ1YM1/domains/01G1CJ7WF6B46AWM4EWTKZ1YM2/reset_token_requests?page=1' \
  -H 'accept: application/ld+json'
```

`[Semantical Error] line 0, col 94 near 'user IN (SELECT': Error: Class App\\Entity\\ResetTokenRequest has no field or association named user`

```
query getApiTokenRequests{
  resetTokenRequests{
    edges{
      node{
        id
      }
    }
  }
}
```

"Unable to generate an IRI for the item of type \"App\\Entity\\ResetTokenRequest\""

Read more here:
https://github.com/lermontex/api-platform-bug-example

**Comment by mwierzbi** [comment]
@lermontex did you resolve this?

**Comment by lermontex** [comment]
@mwierzbi no, unfortunately, due to the lack of documentation I had to abandon the idea of using my own uriVariables

**Comment by nesl247** [comment]
Running into this myself. Would be great if this could be fixed. We have a class that has a relationship through an intermediate class, and want the ID in the url.

**Comment by ChrisCornelissen** [comment]
Hi, I encounter the same problem. I want to use ID in the uri but the classes only have a relationship through an intermediate class. Does anybody have a solution for this issue?

**Comment by soyuka** [comment]
please create a test case or a reproducer without knowing what you're doing exactly it's impossible to answer

**Comment by johnkhansrc** [comment]
same issue +1

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).

**Comment by bilik** [comment]
The described problem is still the same in last version 4.2
