### ISSUE TITLE
 The disable_type_enforcement option is ignored (custom GraphQl mutation name's)

### ISSUE THREAD

**Issue by lermontex** [api-platform/core#4727]
**API Platform version(s) affected**: v2.7.0-alpha.1

**Description**  
The `disable_type_enforcement` option is ignored if a custom GraphQl mutation name is used

**How to reproduce**  

```
#[ApiResource(
    normalizationContext: ['groups' => ['read_normalization']]
)]
#[Mutation(
    denormalizationContext: ['groups' => ['update_denormalization'], 'disable_type_enforcement' => true]
    name: 'update'
)]
#[Mutation(
    denormalizationContext: ['groups' => ['update_denormalization'], 'disable_type_enforcement' => true]
    name: 'update2'
)]
class Domain
{
    #[ORM\Column(type: "string", length: 255, nullable: false)]
    #[Groups(['update_denormalization', 'read_normalization'])]
    private ?string $apiToken = null;

    #[ORM\Column(type: "boolean")]
    #[Groups(['update_denormalization', 'read_normalization'])]
    private bool $isActive = false;
	
	// ...
}
```

```
{
  "input": {
      "id": "/api/domains/1",
      "apiToken": null,
      "isActive": false
  }
}
```

When trying to run the "update2Domain" mutation, an error occurs:

```
{
  "errors": [
    {
      "message": "Variable \"$input\" got invalid value {\"id\":\"\\/api\\/domains\\/1\",\"apiToken\":null,\"isActive\":false}; Expected non-nullable type String! not to be null at value.apiToken.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 24
        }
      ]
    }
  ]
}
```

Schema generated incorrectly ("Boolean!" instead of "Boolean")

```
"""Updates a Domain."""
input updateDomainInput {
  id: ID!
  isActive: Boolean
  clientMutationId: String
}
```
```
"""Update2s a Domain."""
input update2DomainInput {
  id: ID!
  isActive: Boolean!
  clientMutationId: String
}
```

https://s20.directupload.net/images/220421/jakshend.png
https://s20.directupload.net/images/220421/a32pgt3l.png

**Possible Solution**  
...

**Additional Context**  
https://github.com/api-platform/core/blob/39b4e43dff9463b13477cc64a760797978d052e8/src/Serializer/AbstractItemNormalizer.php#L1009

**Comment by soyuka** [comment]
hi, I checked the context at https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Stage/DeserializeStage.php#L51 and I do have the `disable_type_enforcement` if specified. Are you sure you removed the cache?

**Comment by lermontex** [comment]
Yes, I cleared the cache, but the problem is still there.

I have added a repository to demonstrate this error:
https://github.com/lermontex/api-platform-bug-example

**Comment by lermontex** [comment]
I checked version [v2.7.0-beta.4](https://github.com/api-platform/core/releases/tag/v2.7.0-beta.4) - the bug is still there
