### ISSUE TITLE
Dependency to symfony/http-foundation

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#474]
As of now we are explicitly requiring HttpFoundation `Request` and `Response` objects. Couldn't we also add support for PSR-7?

**Comment by teohhanhui** [comment]
Agree that we should move to PSR-7 exclusively.

**Comment by theofidry** [comment]
Ok can work on that then. Worth to do that in #472 directly or after?

**Comment by theofidry** [comment]
OK so quick update on the issue, right now we depend on HttpFondation in:

- Actions
- Symfony listeners
- Hydra and JsonLd
- Filters

So moving away from this will be quite painful. Still I believe that it would be wiser as:

- PSR-7 is still a growing standard, and if we wish an integration with any framework that's the way to go
- Even among frameworks using on `HttpFoundation`, there is some like `Laravel` for which it can still be a problem:
  - Framework as Laravel do not have listeners, they are using Middleware instead

For actions, we're actually not needing much from the `HttpFondation` API. If you check #472, you will see that we only need the `Request` for the Extractor to provide the right data to the ItemProviders. So even if we don't want to use the PSR-7 bridge for performance reasons, it will not require much extra work.

For the Symfony listeners, as risen in #473 it's a hard dependency on `symfony/http-kernel`, so it's a problem we will need to take care of anyway.

For `Hydra` and `JsonLd`: it's a mix of Actions and event listeners, two points we already talked about.

For filters, we always used it for convenience but we really never needed it. Indeed what we always used until now was the *parameters*, which are a fragment of the Request. We simply change a bit the way it works to have an extractor/parser in front of it to provide a standardised array, resulting in Request agnostic filters.
