### ISSUE TITLE
The type of the key must be "int", "string" given. While testing

### ISSUE THREAD

**Issue by Guervyl** [api-platform/core#4740]
**API Platform version(s) affected**: 2.5

**Description**  
I'm writing some tests but in `\Symfony\Bundle\FrameworkBundle\Test\WebTestCase`, `static::createClient()->xmlHttpRequest()` convert everything to string while sending the request. I'm testing an api using `Api-platform`. The `api-platform\\core\\src\\Serializer\\AbstractItemNormalizer.php` expect the value to be an int but in the test Symfony is sending the json int a string.

I even extend `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase` and use `static::createClient()->request(...["json"=[...]])` and it is giving me the same error.

How can I force api-plaform to cast the string to int or how can I force Symfony to send the int instead of a string?

Making curl request works, but I'm using `test` environment. So when I make the curl request it points to the `dev` environment.
**How to reproduce**  
1. Create an entity with a integer column.
2. Create a test extends `ApiTestCase`.
3. Send the request with an integer value. `static::createClient()->request("POST", "/api/companies", ["json" => [...]])`

**Comment by benjamindiaztito** [comment]
I'm having the same problem, but in my case it's even worse...

The Entity:
`#[ORM\Column(type: 'string', length: 255, nullable: true)]`
`private $siteTitle;`

JSON sent:
`{"siteTitle":"string"}`

The error message:
`"The type of the key \"siteTitle\" must be \"int\", \"string\" given."`

Please, any idea?

**Comment by soyuka** [comment]
Type your property accepting both types. Can't do much here.
