### ISSUE TITLE
Question on ClassInfoTrait

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#475]
**ClassInfoTrait**

Is there any point to have it as a trait? It only has the following method:

```php
private function getObjectClass($object)
    {
        return class_exists('Doctrine\Common\Util\ClassUtils') ? ClassUtils::getClass($object) : get_class($object);
    }
```

IMO this could be a public static function instead: having it as a trait only duplicate the method on which classes using it and it does only PHP function calls or static calls, so be it a private method in a trait or a public static method, it doesn't change anything in terms of testability (for the class using it), while make this util testable.

**Comment by dunglas** [comment]
Traits are easily testable? I don't see any benefit to remove the trait for adding a static method. :-1: for me.

**Comment by theofidry** [comment]
>Traits are easily testable?

With a private method it requires to have create a test class using this trait and having a public method calling it directly. Doable but slightly more annoying.

In any case I will add a test for it, but I really don't see the advantage of using a trait in this case (well, it's not like I'm fond of static calls either meh).

**Comment by dunglas** [comment]
You can use the `use { method as public; }` syntax. It's not a big deal. IMO traits are better than public static methods. Btw, if it's not already the case, I would make this trait `@internal`.

**Comment by theofidry** [comment]
>You can use the use { method as public; } syntax

Ah nice one.

>IMO traits are better than public static methods

Didn't make my opinion on it yet :p

> I would make this trait @internal.

It is don't worry

**Comment by theofidry** [comment]
Anyway will just take care of adding a test for it then

**Comment by teohhanhui** [comment]
I'm of the opinion that we don't need a test for this. It'll only be testing Doctrine's method, or `get_class`. Completely superfluous.

**Comment by theofidry** [comment]
Fair enough.

Anyway we need to get  https://github.com/phpspec/prophecy/pull/263 or https://github.com/phpspec/prophecy/pull/264 merged for proper unit testing :disappointed:
