### ISSUE TITLE
Unclear semantics of PropertyMetadata::readableLink / writableLink

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#479]
Currently, readableLink actually means "return embedded representation" and writableLink means "allow writing embedded properties".

There's a mismatch between the naming and the actual semantics.

Perhaps we can change it to something like: readDereferenceable / writeDereferenceable (or readDereferenced / writeDereferenced, whichever is more correct... I'm still trying to figure this out.)

**Comment by teohhanhui** [comment]
Also, these properties should be set to false (or perhaps null would be more appropriate to represent undefined semantics) when the property is not a link (relation).

**Comment by dunglas** [comment]
Refactored.

**Comment by teohhanhui** [comment]
Just looked at the latest code. I don't think this has been addressed.
