### ISSUE TITLE
Wrong values in PropertyMetadata - how does a factory decorator know if a value is "authoritative"?

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#480]
`PropertyInfoPropertyMetadataFactory` sets `writable` to false on to-many relations (Doctrine `Collection`), due to its inability to find the singular-named adder and remover methods - see symfony/symfony#18166; and in `SerializerPropertyMetadataFactory` we do not change any existing false values on `readable`/`writable`, since we cannot know whether it's safe to do so. This leads to incorrect result - basically all to-many relations having `writable` value of false. (Our functional testing does not catch this because `Dummy::relatedDummies` is a public property.)

But this is a more general problem. How does a factory decorator know when it's okay / not okay to "overrule" the value set by its predecessor(s)? Does there need to be a confidence value attached? Or even a voting system like that of Symfony Security component? (I'm not sure if I'm going in the right direction...)

**Comment by teohhanhui** [comment]
\*proud guinea pig\* :hamster:

**Comment by dunglas** [comment]
If we fix the bug in Symfony (and we will), this bug will be fixed as well right? Relying on the order of decorators should be enough IMO. Voters for that look like overkill.

**Comment by teohhanhui** [comment]
This will be fixed by symfony/symfony#18337

IMO this a blocker for 2.0...

**Comment by dunglas** [comment]
Unfortunately it hasn't been merged in 3.1.0. I hop it will be integrated in 3.1.1.

**Comment by dunglas** [comment]
3.1 has been released. This is now fixed.
