### ISSUE TITLE
Replace AbstractContextAwareFilter with AbstractFilter in docs

### ISSUE THREAD

**Issue by tacman** [api-platform/core#4823]
**API Platform version(s) affected**: 2.7

**Description**  

Documentation shows a custom filter extending from AbstractContextAwareFilter, but that class no longer exists.

**How to reproduce**  

Cut and paste the code from https://api-platform.com/docs/main/core/filters/#creating-custom-doctrine-orm-filters (which is the 2.7 documentation).  The class doesn't exist, nor does the filter work.

**Comment by tacman** [comment]
It appears that it should now simply extend AbstractFilter.  The constructor signature has changed.  I'll submit a PR in the docs.

**Comment by alanpoulain** [comment]
Done here https://github.com/api-platform/docs/pull/1560.
