### ISSUE TITLE
Mercure | On delete add @context to data

### ISSUE THREAD

**Issue by Ninos** [api-platform/core#4834]
Deleting an object/entity sends an event to Mercure with `@id` as data content. Sometimes on client-side you just want to refresh context-specific, not object-specific. Is it possible to extend core for adding `@context` into mercure push data? If not, can you please provide a small example of method-specific data manipulation (globally add `@context` to every delete event or manipulating data through method)? Would be awesome :-)

Kindest regards
Ninos

**Comment by martijnhartlief** [comment]
I just found out you can avoid overwriting the listener by setting the following config value in `api_platform.yaml`

```yaml
api_platform:
    mercure:
        include_type: true
```

Thankx @soyuka
