### ISSUE TITLE
Mercure | Create event for parent objects / entities

### ISSUE THREAD

**Issue by Ninos** [api-platform/core#4835]
Currently events are just sent to mercure for objects with stored data manipulation (doctrine). Some properties of entities may depend on child-specific entries, e.g. if children have status xy -> status of main element is yz. It's already possible to define getter as properties, just the push to mercure is not working out of the box (only chird sends an event, but not parent-element of child, because there was no data manipulation, but the output of method is different).

The easiest solution would be to add configuration for recursive event pushes (just go upstairs). So it's possible to enable/disable this "feature" if (not) needed.

If it's a won't fix:
Can you please provide an example, how to implement such custom event push in api platform e.g. using some doctrine listeners?

Thx! :-)

Ninos

**Comment by soyuka** [comment]
Indeed for these use cases we recommend to do a custom doctrine listener doing about the same thing as this class: 
https://github.com/api-platform/core/blob/main/src/Doctrine/EventListener/PublishMercureUpdatesListener.php
