### ISSUE TITLE
Custom operation get method with Controller doesn't work but other they work

### ISSUE THREAD

**Issue by romainpltr** [api-platform/core#4838]
Hi,

I do a project which need to create some routes with an api, so to do that we use Api plateform with Custom operations, but i dont know why, my route key_figures doesn't work anytimes.

# User Entity
<img width="705" alt="image" src="https://user-images.githubusercontent.com/14335973/179714118-e943bd4c-b32a-49b8-8a85-65e037a22e28.png">

But the others work perfectly. 

So a screen of the Controller KeyFigures & UserController

# Key Figures Controller

<img width="587" alt="image" src="https://user-images.githubusercontent.com/14335973/179714472-631b5ebe-01bf-4da6-b67e-32ca129708ed.png">

# User Controller

<img width="587" alt="image" src="https://user-images.githubusercontent.com/14335973/179714646-7eb23b1f-b69b-4331-9095-d53b76b1b6ee.png">

The error returned by Insomnia is this.

![image](https://user-images.githubusercontent.com/14335973/179714795-b63f7c4a-5377-4a19-8864-3e95c641013e.png)

Thanks

**Comment by vincentchalamon** [comment]
It looks like more a Symfony issue, a cache issue, or a service declaration issue, than an API Platform one.

@romainpltr Could you provide us a sandbox project reproducing this bug please?

**Comment by romainpltr** [comment]
Hello, i solve this problem with a delete and recreate a new controller. So, i think it's a cache issue. Thanks for your answer.
