### ISSUE TITLE
`bin/console make:state-processor` command does not work in an API Platform project (version 2.7)

### ISSUE THREAD

**Issue by GuillaumeKESTEMAN** [api-platform/core#4839]
**API Platform version(s) affected**: 2.7

**Description**  
The maker command `bin/console make:state-processor` does not work.
'Command "make:state-processor" is not defined.'

**How to reproduce**  
Run the `bin/console make:state-processor` command in an API Platform project (version 2.7)

**Possible Solution**  
Create the 'Maker' folder in ['core/src/Symfony/'](https://github.com/api-platform/core/tree/2.7/src/Symfony) like in [core/src/Core/Bridge/Symfony](https://github.com/api-platform/core/tree/2.7/src/Core/Bridge/Symfony) but with the new names of the makers.

**Comment by tacman** [comment]
Where does that command come from?  I don't think it's an API Platform command, it's not available in 2.6 either.

**Comment by GuillaumeKESTEMAN** [comment]
This command comes from [here](https://api-platform.com/docs/main/core/state-processors/#creating-a-custom-state-processor)
Yes, it's not available in 2.6 but I'm talking about version 2.7.

**Comment by tacman** [comment]
Ah, thanks!  Looks interesting, I hadn't seen it before.  So much cool stuff in 2.7!

**Comment by develth** [comment]
Imho the docs go for 3.x
The mentioned `@api_platform.state_processor` also does net exists.

**Comment by develth** [comment]
Currently i think thats just an search/replace of the data persister page, because it seems like the "decorated" stuff is not needed on the Processors at the moment but the section still exists

**Comment by GuillaumeKESTEMAN** [comment]
[This commit](https://github.com/api-platform/core/commit/4323f72b8c2c50d789673c3b92d4f9b0c420ef87) fixed the problem.
