### ISSUE TITLE
Version 3: $iriConverter generates /.well-known/genid instead of expected route

### ISSUE THREAD

**Issue by tacman** [api-platform/core#4846]
**API Platform version(s) affected**: 3.0-rc1

**Description** 

            $x = $this->iriConverter->getIriFromResource($entityOrClass, operation: new GetCollection());

In 2.7: as expected (/api/questions), 

in 3.0: /.well-known/genid/f59d0333e9a87def1d43?page=1&itemsPerPage=99&order[marking]=asc

What is /.well-known?  It's not matching any routes.

**Comment by dannyvw** [comment]
It is added here https://github.com/api-platform/core/commit/87b61505d2f719fcf0d8613414d9e6aa436fd61f#diff-ac4847d931ec39d251d7b28fc138a9c65b7fb2f981fe313d9e373a2c2d6b8860R121

**Comment by tacman** [comment]
Are there any examples of how to create the route, using $iriConverter, for operations that previously were subresources?  

Perhaps that could be added to the documentation page, now that subresources are no longer supported.

**Comment by dannyvw** [comment]
You need to define a "subresource" also as ApiResource see https://api-platform.com/docs/main/core/subresources/

**Comment by tacman** [comment]
Right, like this:

```php
#[ApiResource(
    uriTemplate: '/companies/{companyId}/employees',
    uriVariables: [
        'companyId' => new Link(fromClass: Company::class, toProperty: 'company'),
    ],
    operations: [ new GetCollection() ]
)]
```

My question, though, it how do I generate "/companies/27/employees" using $iriConverter?  What are the arguments that need to get passed in?

```php
$company = new Company(27);
$uri = $iriConverter->getIriFromResource(??);
assert($uri === '/companies/27/employees');
```

**Comment by dannyvw** [comment]
This should work

```php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use Doctrine\Common\Collections\Collection;

#[ApiResource(
    uriTemplate: '/companies/{companyId}/employees',
    uriVariables: [
        'companyId' => new Link(fromClass: Company::class, toProperty: 'company'),
    ],
    operations: [ new GetCollection() ]
)]
class Company
{}
```

```php
$iri = $iriConverter->getIriFromResource(Company::class, operation: new GetCollection(), context: [
    'uri_variables' => [
        'companyId' => 27,
    ]
]);
```

**Comment by tacman** [comment]
Thanks, I'm getting closer, but now I'm at one or the other.  My movie database has a ManyToOne relationship with Subtitles.  

```php
#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()
    ],
    openapiContext: ["description" => 'Subtitle Records (but not the subtitles themselves) from OST', "example" => "Rainman (en) by bob"],
    normalizationContext: ['groups' => ['subtitle.read', 'rp', 'movie.rp','subtitle.movie']])]
#[ApiResource(uriTemplate: '/movies/{movieId}/subtitles.{_format}',
    uriVariables: [
        'movieId' => new Link(fromClass: Movie::class, toProperty: 'movie')
    ],
    status: 200,
    normalizationContext: ['groups' => ['subtitle.read', 'rp', 'movie.rp']], operations: [new GetCollection()])]
```

I want to be able to get the route for all the subtitles for a given movie (without using the filter, using what used to be a subresource), OR all the subtitles.

Both routes exist:

```
  _api_/subtitles.{_format}_get_collection                    GET        ANY      ANY    /api/subtitles.{_format}                 
_api_/movies/{movieId}/subtitles.{_format}_get_collection   GET        ANY      ANY    /api/movies/{movieId}/subtitles.{_format}          
```

```php
// get all subtitles route
            $x = $this->iriConverter->getIriFromResource(Subtitle::class, operation: new GetCollection());
// get movie subtitles:
  $iri = $this->iriConverter->getIriFromResource(Subtitle::cass, operation: new GetCollection(), context: $context = [
            'uri_variables' => ['movieId' => $movieId]
        ]);
```

When there are 2 GetCollection resources, how are they distinguished?  Do I need to create another context? Or route?

**Comment by dannyvw** [comment]
You can set an operation name. This name is used to generate the route see https://github.com/api-platform/core/blob/main/src/Symfony/Routing/IriConverter.php#L168 but not sure if this is what you mean.

```php
new GetCollection(name: <value>)
```

**Comment by tacman** [comment]
Thanks, that works, but it intuitively feels like there's a solution for the common routes, without having to add a name parameter to each one.

That is, since there's no parameter (movieId), can the iriconverter look at all the getCollection operations and see which one matches?  Right now, it throws an error saying it's expecting movieId, but if it instead ignored that it would match the next one.

I _think_, but am not sure, that it may depend on the order of the ApiResource annotations.  If the general one was first, the iri came back /api/subtitles?movieid=123.

I can use the "name" parameter for my immediate use case, thanks for pointing that out and providing the example.  The IRIConverter service is so important (especially since the route names changed between 2.6 and 2.7!) that the more examples in the documentation, the better.

**Comment by tacman** [comment]
Even declaring the name, I'm still not sure how I can extract the route using the iri converter.

And it's definitely order-dependent, which makes sense.

Stepping back, at issue is sometimes I want to generate /api/subtitle?movieId=123, and sometimes /api/movie/123/subtitles.  Previously, the subresource route had it's own method call in iriConverter. 

It feels like if the uri_variables don't match, then it should be like a route that doesn't match and continue looking.  Does that make sense?

**Comment by tacman** [comment]
What else can be passed to the context?

**Comment by tacman** [comment]
This issue goes away when using the Version 3 namespace, I think it only happen when using version 3 but with version 2 namespaces, e.g. the ones with /core/ in them.
