### ISSUE TITLE
Bridge LexikJWTAuthenticationBundle

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#4883]
LexikJWTAuthenticationBundle is often used on API Platform projects, as it's easy to install and configure, specially for projects which don't need a complex security architecture (OAuth...).

We should bridge this bundle to automatically add its routes on documentations (OpenApi, Swagger, etc.) when the bundle is detected and installed.

**Comment by chalasr** [comment]
I have this in mind for long but just never took time to actually do it.
I thought about making it the other way around though: add some APIPlatform-specifics to the bundle. Reasoning being that API Platform's core is more low-level, does not depend on the bundle at all, and is agnostic from the authentication layer overall which is a good thing to me.

**Comment by vincentchalamon** [comment]
In progress here => https://github.com/lexik/LexikJWTAuthenticationBundle/pull/1098
/cc @chalasr
