### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#4884]
**Description**  
Now that we are doing 3.0 it would be an excellent time to introduce rate limiting to Api Platform (using the Symfony rate limiter) 

**Example**  
For syntax I'd suggest something like this:
```
#[Get(
   ratelimit: 'LIMITER_NAME'
)]
```

I'd assume with the Metadata system that shouldn't be too hard to integrate

**Comment by torbenbr** [comment]
Hello @KDederichs, I also need this feature for a project. Have you already started with the implementation? If not, I would do it.

**Comment by KDederichs** [comment]
No I didn't start a general implementation of it.
For now I'm just using a `kernel.request` listener till I need something more elaborate I guess....

**Comment by soyuka** [comment]
We recommend to do this within Caddy using https://github.com/mholt/caddy-ratelimit or you can use the symfony feature but we will not add this to API Platform.
