### ISSUE TITLE
DataPersister conflicting deprecation notice as presented by PHPUnit vs. phpDoc

### ISSUE THREAD

**Issue by CRC-Mismatch** [api-platform/core#4895]
**API Platform version(s) affected**: 2.6.8

**Description**  
When creating a DataPersister decorator (as per [the documentation](https://api-platform.com/docs/core/data-persisters/#decorating-the-built-in-data-persisters)), when running unit tests, PHPUnit reports a self-deprecation notice:
```
  1x: Method "ApiPlatform\Core\DataPersister\DataPersisterInterface::persist()" might add "void" as a native return type declaration in the future. Do the same in implementation "App\DataPersister\UserDataPersister" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in UserDataPersisterTest::testPersist from App\Tests\Unit\UserDataPersister
```

Before adding the native `void` return type to the implementation, I noticed that the phpDoc for DataPersisterInterface::persist() actually says the opposite:
https://github.com/api-platform/core/blob/e556dce76bf1d0f1cb6b07c73ba2872f1faa182b/src/DataPersister/DataPersisterInterface.php#L35

Upon further research, I noticed that [in 2.7 (coexisting for now) and moving forward, DataPersisterInterface will be replaced by ProcessorInterface](https://github.com/api-platform/core/blob/main/CHANGELOG.md#270-alpha1) (and that it's already [been removed in main](https://github.com/api-platform/core/commit/790bc36245ec1f5c1e0836915dabdf5a4aab7a27#diff-0b5988cf666b1f6195d548b2c0e24015160658bcdf5b12d4c0373431c21a6c84)).
Now I'm basically at an impasse, since our corporate CI/CD blocks us from merging PRs with self-deprecation notices, although it shouldn't matter since the entire interface will be removed in 3.0 (and doesn't seem to have any changes moving forward in `^2.7`).

**How to reproduce**  
Using the sample provided by the above documentation link, it should become evident by running a simple PHPUnit test like
```php
<?php
declare(strict_types=1);

namespace App\Tests\Unit\DataPersister;

use ApiPlatform\Core\DataPersister\ContextAwareDataPersisterInterface;
use App\DataPersister\UserDataPersister;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Mailer\MailerInterface;

public class UserDataPersisterTest extends TestCase
{
	public function testPersist(): void
	{
        $decorated = $this->getMockBuilder(ContextAwareDataPersisterInterface::class)
            ->getMockForAbstractClass();
		$decorated->expects(self::once())
			->method('persist')
			->willReturnArgument(0);
	    $mockMailer = $this->getMockBuilder(MailerInterface::class)
			->getMockForAbstractClass();
		
		$userDataPersister = new UserDataPersister($decorated, $mockMailer);
		self::assertNotNull($userDataPersister->persist(new stdClass()));
	}
}
```

**Possible Solution**  

**Additional Context**

**Comment by TheKassaK** [comment]
Up ?

Same problem here, I dont know how to manage theses deprecated notices.

I'm on 2.6.8

**Comment by soyuka** [comment]
The void issue is from symfony IIRC, please ignore them.
