### ISSUE TITLE
When having GraphQL, an exception occurs when Twig is not enabled

### ISSUE THREAD

**Issue by rvanlaak** [api-platform/core#4897]
**API Platform version(s) affected**: 3.0.0-rc.2

## Description  
The API Platform GraphiQL integration seems to have a dependency on the `twig` service, but that leads to an compilation exception when Twig is not enabled for the active environment.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/2707563/184863622-1673a435-0fc2-469a-ad09-2f94f497b627.png">
 
## How to reproduce

* require webonyx/graphql-php to enable GraphQL for api-platform
* but do not enable TwigBundle in bundles.php for the active environment (e.g. `prod`).

## Possible Solution

Do not enable the visual graphiQL playground when Twig service is not available or bundle is not enabled.

## Additional Context

see documentation https://api-platform.com/docs/core/graphql/#graphiql

Our use-case is that we do not want to have Twig enabled on our `prod` environment because we only support json and xml content types.

* Enabling TwigBundle in bundles.php for all environments solves the exception but is not preferable
* Disabling graphiql does not solve the exception:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/2707563/184864562-cb9c792e-4f44-4fdb-b8ad-37884c1b13a9.png">

**Comment by soyuka** [comment]
I think that this was already the case on API P 2.6 no ?

**Comment by rvanlaak** [comment]
Possibly, yes. But won't have the resources to verify this, as we are working on adopting 3.x

**Comment by soyuka** [comment]
I guess
