### ISSUE TITLE
identifier non writable is documented in .json schema but not in .jsonld one

### ISSUE THREAD

**Issue by celinederoland** [api-platform/core#4901]
**API Platform version(s) affected**: 2.6.8

**Description**  
Hello, I noticed that in .jsonld documentation, the api properties marked as identifier and not writable are removed from the documentation generated in .jsonld (it's shown in documentation generated in .json format and on the default graphical interface of the documentation provided by ApiPlatform).
I'm not sure if it is the expected behaviour or a bug ? And if this is the expected behaviour, does someone know the reason ?

**How to reproduce**  
The official api-platform demo reproduces the problem : (in https://demo.api-platform.com/docs.jsonld the Book schema starts with the property 'isbn', in https://demo.api-platform.com/docs.json the Book schema starts with the property id
![image](https://user-images.githubusercontent.com/6780152/187130519-967a6f96-f4cf-4cc5-addf-17231938fa50.png)

An interesting side effect : on the admin the property appears with OpenApiAdmin component, and doesn't appear with HydraAdmin component
![image](https://user-images.githubusercontent.com/6780152/187130901-c2b28b7d-2ec7-4b82-a0d2-8fa23e91c94d.png)

**Possible Solution**  
It's due to the condition here https://github.com/api-platform/core/blob/6ab093e902a3a7b72f023458cd0f9e5f06eb4b50/src/Hydra/Serializer/DocumentationNormalizer.php#L205
if (true === $propertyMetadata->isIdentifier() && false === $propertyMetadata->isWritable()) {
    continue;
}
If I comment those 3 lines of code, then the property appear in jsonLd documentation and is marked as identifier, and not writable.

**Additional Context**  
In the screenshot below you can see the definition of the resource, with a non writeable identifier named 'atlasId' and a second property 'name' of type string. On the right, you can see that the 'atlasId' property doesn't appear at all in the jsonld representation of the documentation (it starts with the next property 'name') and it appears in the json representation of the documentation (note : the behaviour of the API itself is correct, and the integrated graphical html documentation does show the property to, As far as I can see, only .jsonld representation of the documentation is affected). In the second screen-shot, you can see the result with the 3 lines commented.

![desappear-in-jsonld](https://user-images.githubusercontent.com/6780152/187131434-99b20596-69aa-4a47-8f9a-4611ad37aff1.png)
![do-not-desappear-when-i-comment](https://user-images.githubusercontent.com/6780152/187131448-35e9fc9f-cb24-4814-bc58-f1ff664654ad.png)

**Comment by soyuka** [comment]
It looks like a wanted behavior but I don't understand why, can you check @dunglas ? 

You added it here: https://github.com/api-platform/core/pull/2424

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
