### ISSUE TITLE
Messages are not dispatched when decorating the default Doctrine persister

### ISSUE THREAD

**Issue by DurandA** [api-platform/core#4902]
**API Platform version(s) affected**: v2.6.8

**Description**
When creating a Resource with the [`messenger` attribute set to `true`](https://api-platform.com/docs/core/messenger/#dispatching-a-resource-through-the-message-bus) and when the Resource is a Doctrine entity, messages are not dispatched if there is a [DataPersister decorating the built-in Doctrine data persister](https://api-platform.com/docs/core/data-persisters/#decorating-the-built-in-data-persisters) is used within the project.

**How to reproduce**
Minimal project to demonstrate the issue: https://github.com/DurandA/api-messenger-test

Entity:
```php
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource(collectionOperations: [
        "post" => ["messenger" => true, "output" => false, "status" => 202]
    ], itemOperations: []
)]
#[ORM\Entity]
class Foo
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\Column(type: 'string')]
    public string $baz;
}
```

Data persister:
```php
namespace App\DataPersister;

use ApiPlatform\Core\DataPersister\ContextAwareDataPersisterInterface;

class FooDataPersister implements ContextAwareDataPersisterInterface
{
    private ContextAwareDataPersisterInterface $decorated;

    public function __construct(ContextAwareDataPersisterInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function supports($data, array $context = []): bool
    {
        return $this->decorated->supports($data, $context);
    }

    public function persist($data, array $context = [])
    {
        $result = $this->decorated->persist($data, $context);
        return $result;
    }

    public function remove($data, array $context = [])
    {
        return $this->decorated->remove($data, $context);
    }
}
```

services.yml:
```yml
    App\DataPersister\FooDataPersister:
        bind:
            $decorated: '@api_platform.doctrine.orm.data_persister'
```

**Additional Context**  
If the data persister implements `ResumableDataPersisterInterface`, then the message is dispatched. However, I am not sure about the side effects of decorating the `ApiPlatform\Core\Bridge\Doctrine\Common\DataPersister` (which is not resumable) with a resumable persister.

**Comment by soyuka** [comment]
It's expected as you should call the persister that dispatches the message. ResumableDataPersisterInterface is deprecated, use a provider and if you want persistence decorate `api_platform.doctrine.orm.state.item_provider` or the messenger provider.
