### ISSUE TITLE
Wrong @id attribute with multiple GET routes when using custom routes and controllers, and routes in yaml file

### ISSUE THREAD

**Issue by necobm** [api-platform/core#4903]
Firstable, I have to say that I don't have de "default" setup of API Platform. I have resources defined in a separated YAML file, routes also goes to a separated "routes_api.yaml" file, and finally, all routes for my resources are customized with custom controllers, so far so god.

In this page of the documentation: https://api-platform.com/docs/core/controllers/#creating-custom-operations-and-controllers stands that "By default, API Platform uses the first GET operation defined in itemOperations to generate the IRI of an item", but, for some reason, this is not working properly with my setup.

I have one User resources, with this YAML configuration (User.yaml):

<pre>
Acme\SecurityBundle\Domain\Model\User:
  attributes:
    input_formats:
      jsonld: ['application/ld+json']
      json: ['application/json']
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
    code:
      serialized_name: id
      groups: [ 'read' ]
    email:
      groups: ['read','write']
    password:
      groups: ['write']
    name:
      groups: ['read','write']
    surnames:
      groups: ['read','write']
    profileImage:
      groups: [ 'read','write' ]
    emailSignature:
      groups: [ 'read','write' ]
    company:
      groups: [ 'read','write' ]
  properties:
    id:
      identifier: false
    code:
      identifier: true
    company:
      readableLink: false
      writableLink: false
  collectionOperations:
    get:
      method: GET
      route_name: security_api_user_get_users      
    post:
      method: POST
      route_name: security_api_user_post_collection
  itemOperations:
    get_item:
      method: GET
      route_name: security_api_user_get_item
    get_logged:
      method: GET
      route_name: security_api_user_get_logged
      openapi_context:
        parameters: []
        description: Get the logged user, providing a valid JWT Token
        summary: Get the logged user, providing a valid JWT Token
    put:
      method: PUT
      route_name: security_api_user_put_item
    delete:
      method: DELETE
      route_name: security_api_user_delete_item

</pre>

And the fallowing routes to that User resource (routes_api.yaml):

<pre>
security_api_user_get_logged:
  path: /user/logged
  methods: [ 'GET' ]
  defaults:
    _controller: ByLogic\LinceSecurityBundle\Controller\SecurityController::loggedUser
    _api_resource_class: ByLogic\LinceSecurityBundle\Domain\Model\User
    _api_item_operation_name: get_logged
    _api_receive: false

security_api_user_get_item:
  path: /user/{id}
  methods: ['GET']
  defaults:
    _controller:Acme\SecurityBundle\Controller\UserController::readUser
    _api_resource_class: Acme\SecurityBundle\Domain\Model\User
    _api_item_operation_name: get_item
    _api_receive: false
</pre>

According to the documentation, my first route under "itemOperations" is "security_api_user_get_item", so, this is the one API Platform should take to generate an IRI to User resource, but, somehow, it's not doing that, instead, it has taken the route "security_api_user_get_logged" to do that. 

I'm aware that it do that because the order of definition of the routes in "routes_api.yaml", when I change this order, it works, but I can't invert that order because Symfony will take the word "logged" and will try to find it as {id} of user, that's whay I need ti in that order.

**Comment by soyuka** [comment]
This got improved in API Platform 2.7 and 3.0. The first declared operation should be the first.
