### ISSUE TITLE
Disabling a subresource endpoint

### ISSUE THREAD

**Issue by laurentdabbb** [api-platform/core#4906]
**API Platform version(s) affected**: 2.6.8 (2.4+ ?)

**Description**  
Unable to overwrite a subresource declared on a property

Hi,
I use Sylius and I want to disable some subresource endpoints. But Sylius is not the cause. This issue is about merging/overwriting endpoint configuration.

By overwriting the Sylius subresourceOperation in my resource configuration file (in YAML), I'm able to disable the Sylius subresource endpoint.
```
subresourceOperations: 
    shop_billing_data_get_subresource:
        enabled: false
```
It works fine.

But, in Sylius configuration (in XML), subresource is also declared on the resource property :
```
<property name="shopBillingData" readable="true" writable="true">
    <subresource resourceClass="%sylius.model.shop_billing_data.class%" collection="false" />
</property>
```
So, Api Platform auto-generate an endpoint for this subresource (even if subresourceOperation was overwritten)...

Unfortunately, I can't remove/overwrite the subresource on property in my YAML file.  
It seems that we can't remove a subresource declaration on property in API Platform since at least 2.4. And I don't understand why...  
I tried to nullify subresource on property :  
```
properties:
    shopBillingData:
        subresource: ~
```
But it is not taken into account. If a property already has a subresource declared, we can't override it :
https://github.com/api-platform/core/blob/2.6/src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php#L119

Please, could you explain why I can't disable/overwrite a subresource on a property ?
How to do it ? Is it a bug ?

If I comment out the condition in the **ExtractorPropertyMetadataFactory.php** file at line 119, everything works fine !!
```
// if ($propertyMetadata->hasSubresource()) {
//     return $propertyMetadata;
// }

return $propertyMetadata->withSubresource($this->createSubresourceMetadata($metadata['subresource'], $propertyMetadata));
```
So what is the purpose of this condition ? Why overwriting a subresource property declaration is not allowed ?

Thanks ;-)

**Comment by soyuka** [comment]
use groups or switch to the new versions of api platform where this is easier
