### ISSUE TITLE
Extract JSON-LD parser / serializer into an independent package?

### ISSUE THREAD

**Issue by someniatko** [api-platform/core#4907]
As far as PHP community is concerned, API Platform seems like the only solution which allows pretty much effortlessly use JSON-LD standard for your API payload. However, its internal subcomponent for handling this is tightly coupled to the API-Platform itself. I think the community will be of benefit from allowing to use this component outside of API Platform.

There is also [ml/json-ld](https://github.com/lanthaler/JsonLD) library, which looks dead for two years, does not have modern OO style and also does not support JSON-LD 1.1.

I view JSON-LD and Hydra as a great improvement over semanticless pure JSON, and believe whole PHP ecosystem could benefit of having a decent tooling for working with it, without enchaining to a full-fledged solution like API Platform.

**Comment by soyuka** [comment]
You can easily install api-platform/core and only use the JSON-LD parts. We're thinking of adding a subtree split over our packages and the release of the 3.0 is a move forward but expect at least 1 year until we decide if we do so and maybe longer to have it effective.
