### ISSUE TITLE
Notice: Undefined variable: actionName

### ISSUE THREAD

**Issue by samvdb** [api-platform/core#491]
On dev-master the logic for a custom controller is not correct yet.

When defining a custom controller in the resource like this:

```php
/**
 *@Resource(itemOperations={"GET": {"controller": "test", "method": "test"}})
 */
```

You will get the following error:
*Notice: Undefined variable: actionName*

ref: src/Bridge/Symfony/Routing/ApiLoader.php:114
```php
        if (isset($operation['controller'])) {
            $controller = $operation['controller'];
        } else {
            $actionName = sprintf('%s_%s', strtolower($operation['method']), $collection ? 'collection' : 'item');
            $controller = self::DEFAULT_ACTION_PATTERN.$actionName;
        }
        $path = '/'.$normalizedShortName;
        if (!$collection) {
            $path .= '/{id}';
        }
        $routeName = sprintf('%s%s_%s', self::ROUTE_NAME_PREFIX, $normalizedShortName, $actionName);
```

**Comment by Simperfit** [comment]
@samvdb This is not the way you do it.
the method here as I understand it (ping @dunglas) means the http method,
 
For exemple : 

You have to add an `route_name` : 
```
/**
 *@Resource(itemOperations= {"custom_get"={"route_name"="entity.custom_get"}})
 */
```
 In  the route configuration you will to add something like this : 
```
entity.custom_get:
    path:  '/entity/{id}/custom'
    methods:  ['GET', 'HEAD']
    defaults:
        _controller:     'AppBundle:Test:test'
        _resource_class: 'AppBundle\Entity\Entity'
        _operation_name: 'custom_get'
```

**Comment by samvdb** [comment]
Hi simperfit,

Yes that is a working method by just setting a route name, however looking
at the code implemented i would guess that the intention is to specify a
custom controller also. This however leads to the error above.

Thanks for your reply though!

Op dinsdag 5 april 2016 heeft Simperfit <notifications@github.com> het
volgende geschreven:

> @samvdb <https://github.com/samvdb> This is not the way you do it.
> the method here as I understand it (ping @dunglas
> <https://github.com/dunglas>) means the http method,
>
> For exemple :
>
> You have to add an route_name :
>
> /**
>  *@Resource(itemOperations= {"custom_get"={"route_name"="entity.custom_get"}})
>  */
>
> In the route configuration you will to add something like this :
>
> entity.custom_get:
>     path:  '/entity/{id}/custom'
>     methods:  ['GET', 'HEAD']
>     defaults:
>         _controller:     'AppBundle:Test:test'
>         _resource_class: 'AppBundle\Entity\Entity'
>         _operation_name: 'custom_get'
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/api-platform/core/issues/491#issuecomment-205978094>
>


-- 

Met vriendelijke groeten,
Sam Van der Borght.

samvanderborght@gmail.com

**Comment by teohhanhui** [comment]
@samvdb

For your own custom action, the annotation should be like this:

```php
/**
 * @Resource(itemOperations={
 *     "test"={"method"="GET", "controller"="AppBundle:Product:test"},
 * })
 */
```

or

```php
/**
 * @Resource(itemOperations={
 *     "test"={"route_name"="app_product_test"},
 * })
 */
```
(you have to configure the route yourself if using this method)

**Comment by soyuka** [comment]
I can confirm this bug.

If the controller is defined, `$actionName` is never defined because it's only in the `else` condition.

Then it throws at line 115. 

@teohhanhui may I PR to fix this?
