### ISSUE TITLE
`$example` should be `mixed` instead of `string|null`

### ISSUE THREAD

**Issue by nesl247** [api-platform/core#4911]
**API Platform version(s) affected**: 3.0.0-rc2

**Description**  
In https://github.com/api-platform/core/blob/5ef1d612f34dce4cafd0aaec298e346db841c328/src/Metadata/ApiProperty.php#L32 it only supports `string|null`, however, the actual types can be `string|array|int|bool|null` at minimum at least. This is causing issues with `psalm`, even though PHP has no issues, and it works as expected.

**Comment by soyuka** [comment]
example is a literal-string in open api and there's no point in using something else

**Comment by nesl247** [comment]
@soyuka am I misunderstanding where this is used? I got this image from https://swagger.io/docs/specification/adding-examples/


![CleanShot 2022-09-05 at 09 42 42](https://user-images.githubusercontent.com/1037526/188463372-ab0c3b91-9874-42c4-9528-62aa3f68e9b8.png)

**Comment by juniorb2ss** [comment]
@soyuka 🏓

**Comment by soyuka** [comment]
Mhh right this actually refers to https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object and indeed should be a free form object.
