### ISSUE TITLE
multipart/form-data doesn't deserialize correctly float

### ISSUE THREAD

**Issue by bastien70** [api-platform/core#4921]
**API Platform version(s) affected**: 2.6.8

**Description**  
I followed this tutorial https://api-platform.com/docs/core/file-upload/#uploading-to-an-existing-resource-with-its-fields to allow file upload and fill other parameters.

But when sending POST request in multipart/form-data with inside 1 file, 2 strings, 1 date, and 1 float, I've the following error : 
`"The type of the \"stars\" attribute must be \"float\", \"string\" given."`

**How to reproduce**  

Create entity like this : 

```php
<?php

namespace App\Entity;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: MovieRepository::class)]
#[ApiResource(
    collectionOperations: [
        'get',
        'post' => [
            'input_formats' => [
                'multipart' => ['multipart/form-data'],
            ],
        ],
    ],
    denormalizationContext: ['groups' => ['movie:write']],
    normalizationContext: ['groups' => ['movie:read']]
)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['movie:read', 'movie:write'])]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['movie:read', 'movie:write'])]
    private ?string $description = null;

    #[ORM\Column(type: Types::FLOAT)]
    #[Groups(['movie:read', 'movie:write'])]
    private ?float $stars = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['movie:write'])]
    private ?\DateTimeInterface $releaseDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $filePath = null;

    #[Vich\UploadableField(mapping: 'movie_image', fileNameProperty: 'filePath')]
    #[Groups(['movie:write'])]
    private ?File $file = null;

    #[Groups(['movie:read'])]
    private ?string $fileUrl = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    public function __construct()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStars(): ?float
    {
        return $this->stars;
    }

    public function setStars(float $stars): self
    {
        $this->stars = $stars;

        return $this;
    }
   
   // ...
}
```

And the multipart decoder : 

```php
<?php

namespace App\Encoder;

use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Serializer\Encoder\DecoderInterface;

class MultipartDecoder implements DecoderInterface
{
    public const FORMAT = 'multipart';

    public function __construct(private readonly RequestStack $requestStack) {}

    public function decode(string $data, string $format, array $context = [])
    {
        $request = $this->requestStack->getCurrentRequest();

        if (!$request) {
            return null;
        }

        return array_map(static function (string $element) {
                // Multipart form values will be encoded in JSON.
                $decoded = json_decode($element, true);

                return \is_array($decoded) ? $decoded : $element;
            }, $request->request->all()) + $request->files->all();
    }

    public function supportsDecoding(string $format)
    {
        return self::FORMAT === $format;
    }
}
```

**Additional Context**  
Video : 

https://user-images.githubusercontent.com/53140475/188632288-bf1e1ffb-18e6-4882-947c-1531ffd79671.mp4

**Comment by soyuka** [comment]
bad usage please use other channels

**Comment by ahmed-bhs** [comment]
@bastien70 When you send data in `multipart/form-data` to an API, all values are transmitted as strings. Symfony’s **Decoder** is responsible for converting the request body content into a key-value array. However, even after this step, values like booleans, integers, or floats remain strings in the array. For example: `is_published: "true"`, `age: "30"`, or `height: "1.75"`.

In the documentation example, it simply uses `json_decode`, but it doesn’t automatically convert strings to native types (like turning `"true"` into `true` or `"30"` into `int`).

To properly handle data types (like booleans or floats), it’s often necessary to implement **custom decoders**. These allow you to intercept the data and transform it before assigning it to your object's properties, using functions like `filter_var()` to convert strings like `"true"` and `"false"` into actual booleans.

However, setting up a **custom decoder** can get tricky, especially when you need to manage relationships or more complex types within your entity model. So, it’s recommended that when you’re working with files sent in multipart, you separate your resources: create a dedicated resource solely for file uploads and another for handling other data in JSON or JSON-LD format.

The API Platform documentation also emphasizes that the API should remain simple and well-structured. In some cases, separating responsibilities across multiple resources helps maintain a cleaner and more manageable model. This approach avoids unnecessary overhead in the denormalization process and ensures better handling of varied data formats (strings, booleans, files, etc.).
