### ISSUE TITLE
Unexpected comma(s) in generated query

### ISSUE THREAD

**Issue by CS066** [api-platform/core#4923]
**API Platform version(s) affected**: 2.6.7, 2.6.8

**Description**  
Unexpected comma(s) in generated query, if used non-mandatory path parameters in OpenApi UI

**How to reproduce**  
1. Define a new API Factory (implements OpenApiFactoryInterface) with API resource contains path parameters
2. Defene path parameter(s) as a not mandatory (no define "required" argument)
3. Proceed to OpenAPI UI and try query with empty non-mandatory parameters

```
...
new Model\Parameter(
    'month',
    'path',
     'Month (MM)'
),
...
```

**Possible Solution**  
No solutions found

**Additional Context**  
![Screenshot _API Platform_1](https://user-images.githubusercontent.com/68877809/188756603-d6eedccd-31f3-4414-af17-463a2171c22f.png)
![Screenshot_API Platform_2](https://user-images.githubusercontent.com/68877809/188756616-50bc52d8-7814-435e-acba-798832856320.png)

**Comment by soyuka** [comment]
This looks like a swagger ui issue or a misconfiguration, use other channels for support.
