### ISSUE TITLE
Memory leak with the normalizer

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#4924]
**API Platform version(s) affected**: 2.6.8 (and other version too)
**Description**  

I found (the hard way) a memory leak.

APIP [automatically ships](https://github.com/api-platform/core/blob/v2.6.8/src/Serializer/AbstractItemNormalizer.php#L149) the IRI of a document in the `context`.

But Symfony serializes [all the context](https://github.com/symfony/symfony/blob/ef92fb5539f756d0183499f0de05fbcf00969a5f/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L703-L706) to compute the cache key.

So, every time one normalizes an object, a new cache key is generated, thus the `attributesCache` property keeps growing. And it never reset!

**Possible Solution**  

Symfony provides a way to remove some key from the context before computing the cache key.
IMHO, The normalizer should add the `uri` key in the `defaultContext`.

I'm not sure about the consequence, but I think it's safe, because the URI does not change the properties extracted.

WDYT?

**Comment by lyrixx** [comment]
What branch should I target?

**Comment by soyuka** [comment]
I think we should do this on 2.7 instead, 2.6 is in a freeze state and it'd require an hour to update (test suite broken, phpstan and cs updates etc.)f
