### ISSUE TITLE
Custom exception/error handling with interfaces

### ISSUE THREAD

**Issue by SpiGAndromeda** [api-platform/core#4935]
**Description**  
The exception to status code feature is doing a good job in the handling of custom exceptions.
The documentation mentions "expected exceptions" that can be converted to 400 messages. However, I couldn't find information what is "expected" and what is "unexpected" only by browsing through the code.

It would be really nice if API Platform would provide an Interface "ExpectedException" or something like that. I think some Symfony exceptions (and maybe other) are expected as well. Therefore wrapping this exceptions with a class that implements this interface could be necessary. The exception handling would have to be refactored to use this interface.

Custom exceptions could be handled a lot more appropriate with this feature. 

Furthermore more interfaces the status codes that "require" more structured information such as 422 (constraint violations) could be created.

I suggest, we discuss the feature here. Of cause I would take part in the implementation if it should be implemented (without bc breaks).

**Comment by soyuka** [comment]
Maybe that improving the documentation would be enough? Usually you want our status codes, and the `exception_to_status` feature is designed for userland exceptions (yours).
