### ISSUE TITLE
Use output walkers when ordering by non-fetched relation

### ISSUE THREAD

**Issue by Sajito** [api-platform/core#4936]
I'm not quiet sure, if this is there correct template, but I'm submitting this as an improvement, instead of bugfix, because the existing tests and comments related to this PR (https://github.com/api-platform/core/pull/2639) seem like the current behavior is intended.
For this reason I have not created a PR for my request, but might submit one later.

**Description**
At the moment the Method [`shouldDoctrinePaginatorUseOutputWalkers`](https://github.com/api-platform/core/blob/2062d410bf19d4d02e8dfa35c4f01a67569d531d/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L355-L407) will return false, when ordering by a field, which is not being selected. This will lead to the error, which should be prevented in the [last check of that method](https://github.com/api-platform/core/blob/2062d410bf19d4d02e8dfa35c4f01a67569d531d/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L396-L403).

The main difference between the checks in the [`hasOrderByOnFetchJoinedToManyAssociation`](https://github.com/api-platform/core/blob/2062d410bf19d4d02e8dfa35c4f01a67569d531d/src/Bridge/Doctrine/Orm/Util/QueryChecker.php#L89-L151) method and the validation in the [LimitSubqueryWalker](https://github.com/doctrine/orm/blob/434820973cadf2da2d66e7184be370084cc32ca8/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php#L122-L155), is that the QueryChecker is looking at the select parts and potentially traversing the whole relation tree, while the LimitSubqueryWalker at the moment is only looking at the order by parts.

**Proposal**  
The check in QueryChecker could be changed to be equivalent to the checks in LimitSubqueryWalker. Meaning we would look at the order by field and simply check if that relation is a to-many relation. This should be simple, performant and return the same result as the checks in the LimitSubqueryWalker. But it would break once doctrine actually fixes the [TODO for complex order by](https://github.com/doctrine/orm/blob/434820973cadf2da2d66e7184be370084cc32ca8/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php#L142).

Looking at the code:

https://github.com/api-platform/core/blob/2062d410bf19d4d02e8dfa35c4f01a67569d531d/src/Bridge/Doctrine/Orm/Util/QueryChecker.php#L89-L151

We could alternatively remove the lines 95, 103-117 and replace the variable `$selectAliases` in line 140 by the result of `$queryBuilder->getAllAliases()`.

This should increase the guessing success rate, with hopefully not so big performance impact.

What do you think?

**Comment by soyuka** [comment]
Why not. We could also add an option in operations to select the behavior manually. Please open a PR if you want and we'll discuss further.

**Comment by Sajito** [comment]
I've opened a PR with my proposed changes :)
