### ISSUE TITLE
Breaking change in 2.6.7 due to type hints introduced in DataProviders 

### ISSUE THREAD

**Issue by famoser** [api-platform/core#4942]
**API Platform version(s) affected**: >= 2.6.7

**Description**  
The type hints introduced with 7bc8fe750 break my custom data providers (more specifically, the change in `TraceableChainCollectionDataProvider.getCollection`). In 2.6.6 and lower, it used to be possible to directly return a `Response` from the data providers; to easy implement custom serialization or binary downloads. This works because the `SerializeListener` checks whether the controller result is already a `Response`, and if so, skips processing.

**How to reproduce**  
Example: https://github.com/baupen/web/blob/716a067f45c61c0d6e36adafb364512cc1f60b00/src/Api/DataProvider/IssueSummaryDataProvider.php#L56

**Possible Solution**  
Fixing this downstream is unfortunately not trivial. Some use cases which are no longer covered, and need new work-arounds:
- Return json of list of Dtos (rather than collection entities): Return list of Dtos in `MyCustomDataProvider`, configure the Dto with the same serialization groups as the entity. 
- Return json of single Dto: Return list with single Dto entry in `MyCustomDataProvider`; then use a custom `Encoder` which only  encodes the first entry of the list.
- Return binary (e.g. an image rendered based on collection items): Unclear. Custom `Encoder` does not work, as the [`Serializer` enforces `string` return types](https://github.com/symfony/serializer/blob/6.1/Serializer.php#L335). Possibly solvable using a custom kernel event...?
- Return a redirect: Unclear. Possibly solvable using a custom kernel event...?

There is an (unfinished) PR open with the described changes: https://github.com/baupen/web/pull/554

**Additional Context**  
Currently it feels like I am replacing a work-around with many more elaborated ones. I am happy to rewrite my data providers to align more closely with the Api Platform design principles; but do not really see a clean way forward right now.

**Comment by soyuka** [comment]
Hi, thanks for the report. First you shouldn't return a Response in a Data Provider its not meant to work like this. You can use a custom Controller instead. 

In API Platform 2.7 and 3.0 providers have been reviewed. The release is close, if you can assist the https://api-platform.com/con/2022/ (free for students but hurry places are limited) you'll get an overview that'll help with most cases written above.

**Comment by famoser** [comment]
With custom controller it works, and it is much easier than an `Encoder`. Thank you!

Should I keep the Issue open? Is this indeed a backwards compatibility break (easily resolved by reverting https://github.com/api-platform/core/commit/7bc8fe750bde618f5d981ebf52efc5d0c41d535f on the v2.6, v2.7 branches), or is this internal undocumented behavior which cannot be relied on?

**Comment by soyuka** [comment]
Indeed, sorry about that.
