### ISSUE TITLE
Using a Doctrine Expr for an innerJoin in a custom filter fails when using other filters

### ISSUE THREAD

**Issue by derTuca** [api-platform/core#4944]
**API Platform version(s) affected**: 2.6.8

**Description**  
I have created a custom filter in which I perform an innerJoin using Doctrine's Expr andX method because I need to use multiple EXISTS in the join. The filter works fine, however, when I add another filter to the query (in this case a SearchFilter on another property), the request fails in FilterEagerLoadingExtension.php at this line: `$condition = str_replace($aliases, $replacements, $joinPart->getConditions() ?? '');` (line 168 I believe).

The error is due to the fact that in this case the $joinPart->getCondition is not a string, but a Doctrine\ORM\Query\Expr\Composite (more specifically AndX) so str_replace fails.

**How to reproduce**  
Create a filter that has a similar logic to this snippet in the apply method:
```php
 $reqAlias = $queryBuilder->getRootAliases()[0];
 $alias = QueryBuilderHelper::addJoinOnce($queryBuilder, $queryNameGenerator, $reqAlias, "answers", Join::INNER_JOIN);
 $parameterName = $queryNameGenerator->generateParameterName("question");
 $queryBuilder->innerJoin("$alias.question", $paramName, Expr\Join::WITH, $queryBuilder->expr()->andX(...expressions));
```
Then create a entity that has this filter on a OneToMany property and a SearchFilter on another property and do a query search using properties from both filters.

**Possible Solution**  
I have fixed the problem locally by wrapping the join in an if statement, although I don't understand API Platform's internals that well to make sure this is the correct option. 
```php
if (!($joinPart->getCondition() instanceof Composite)) {
     $condition = str_replace($aliases, $replacements, $joinPart->getCondition() ?? '');
      QueryBuilderHelper::addJoinOnce($queryBuilderClone, $queryNameGenerator, $alias, $association, $joinPart->getJoinType(), $joinPart->getConditionType(), $condition, $originAlias, $newAlias);
}
```

**Comment by soyuka** [comment]
If the case is too complicated, juste create your own provider.This looks like a doctrine-related issue / support question.

**Comment by derTuca** [comment]
In this case, shouldn't we add at least a warning in the documentation page of Creating Custom Filters that we cannot use Doctrine's Expr in the query builder?
