### ISSUE TITLE
Attempted to load class "Differ" from namespace "SebastianBergmann\Diff".

### ISSUE THREAD

**Issue by babeuloula** [api-platform/core#4950]
**API Platform version(s) affected**: 2.7.0

**Description**  
Unable to execute api:upgrade-resource command

**How to reproduce**  
Just execute the command on a fresh APIP install.

**Possible Solution**  
Install the lib with the 2.7.0

**Comment by jffjck-dev** [comment]
Hello, 

I tried to reproduce your issue : 

- start by creating an empty symfony project with `composer create-project symfony/website-skeleton` .
- add API platform **2.7**, create a dummy entity and mark it as API Platform ressource with the maker bundle. 
- But using the maker bundle, already use the new Resource Metadata namespace. So i change the `use ApiPlatform\Metadata\ApiResource;` import by `use ApiPlatform\Core\Annotation\ApiResource;` in the entity class file.
- Then I execute the `api:upgrade-resource` command, the old namespace is still in place but I doesn't get any error message.

Version:
_api-platform v2.7
symfony v6.1
php v8.1_

**Comment by soyuka** [comment]
>  Just execute the command on a fresh APIP install.

Please explain "fresh API P install".

we could not reproduce, maybe that you need to install phpunit ?

**Comment by babeuloula** [comment]
> >  Just execute the command on a fresh APIP install.
> 
> Please explain "fresh API P install".
> 
> we could not reproduce, maybe that you need to install phpunit ?

I meen from scratch. I don't understand I need to install PHPunit to run this command. 
But your update with a message if we did not have the extension it's great
