### ISSUE TITLE
OpenApi: support multiple types within the schema

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4967]
- support multiple types on a property (see an example at https://github.com/api-platform/core/pull/4951) in the AbstractItemNormalizer
- the openapi specification doesn't support that yet we need to keep up to date they're trying to add this feature

**Comment by MaSpeng** [comment]
Just fell over the same issue.

My situation was the following:

```php
class Foo {
    public bool|int|float|null $property = null;
}
```

The expected result in the OpenAPI 3.0 would be:
```json
{
    "oneOf": [
        {
            "type": "boolean",
        },
        {
            "type": "integer",
        },
        {
            "type": "number",
        }
    ],
    "nullable": true,
}
```

Sadly providing an OpenAPI 3.0 compliant schema through `openapiContext` and/or `jsonSchemaContext` does not work either, the resulting schema looks like this:
```
{
    "oneOf": [
        {
            "type": "boolean",
        },
        {
            "type": "integer",
        },
        {
            "type": "number",
        }
    ],
    "nullable": true
    "type": "integer"
}
```

It is already described as a to-do for version 3.0 but didn't make it into the release.
https://github.com/api-platform/core/blob/039ba865ef634e79a757e49c2ff1ecacad2b7aa0/src/JsonSchema/SchemaFactory.php#L182

Would be great if this could be addressed in the near future!

**Comment by MaSpeng** [comment]
@soyuka I am happy to see this one has been closed as completed, sadly I cannot see any pul request associated with this issue. Could you please link the PR or commit that is solving this issue?
