### ISSUE TITLE
Hide fields

### ISSUE THREAD

**Issue by simplicitylab** [api-platform/core#497]
One of my entities has attributes that I don't want to exposed by the API, but I want it to be internally available so removing the getters and setters isn't something I really want. 

I've couldn't find a clue in the documentation and the only thing that I found on the internet was regarding making fields read-only. Is it even possible to do this ?

**Comment by teohhanhui** [comment]
Use Serializer groups for the normalization / denormalization. It's in the
documentation.

**Comment by Simperfit** [comment]
@simplicitylab Are you talking about master or 1.x ?

If I understand what you want to do correctly, i'll let you check this : 

If it's about 1.x, like @teohhanhui said it's in the documentation [here](https://api-platform.com/doc/1.0/api-bundle/serialization-groups-and-relations)

If it's about master (2.x)
You can look at [the dummy entity](https://github.com/api-platform/core/blob/master/tests/Fixtures/TestBundle/Entity/CustomNormalizedDummy.php) and [the behat feature](https://github.com/api-platform/core/blob/master/features/custom_normalized.feature) as an exemple.

**Comment by simplicitylab** [comment]
My apologies, for some reasons I interpreted that part of the documentation completely wrong :-/
