### ISSUE TITLE
Upgrade path for Filters, DataProviders, Extensions, etc.

### ISSUE THREAD

**Issue by stephanvierkant** [api-platform/core#4979]
I'm trying to upgrade to API Platform v3 and I'm impressed by the command that upgrades my entities. Thanks for creating such a command!

But there is more that should be modified and the upgrade path isn't very clear. Are there any plans to create tools to upgrade the DataProviders, Extensions, Filters, etc?

**Comment by soyuka** [comment]
No but please look at the new interfaces. For extensions and filters these are interfaces changes, these interfaces are documented in the CHANGELOG and should be done manually.

**Comment by stephanvierkant** [comment]
Why manually?

This looks pretty simple to automate:

```diff
- use ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\QueryCollectionExtensionInterface;
+ use ApiPlatform\Doctrine\Orm\Extension\QueryCollectionExtensionInterface;

final class UserItemExtension implements QueryCollectionExtensionInterface
{
    public function applyToCollection(
        QueryBuilder $queryBuilder,
-        \ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface $queryNameGenerator,
+        \ApiPlatform\Doctrine\Orm\Util\QueryNameGeneratorInterface $queryNameGenerator,
        string $resourceClass,
-        ?string $operationName = null,
+       \ApiPlatform\Metadata\Operation|null $operationName = null,
+       array $context = [],
    ) : void {
        $this->addWhere($queryBuilder, $resourceClass);
    }
}
```

**Comment by emmanuelballery** [comment]
`operationName` was previously a string and became an operation object. An automatic command could break the code relying on this variable.
