### ISSUE TITLE
[Provider] Inconsistent $uriVariables types

### ISSUE THREAD

**Issue by mpiot** [api-platform/core#4987]
**API Platform version(s) affected**: 3.0.0

**Description**  
In Providers that implement `ProviderInterface` the `$uriVariables` array contains only `int` variables. If the `uriTemplate` receive a string, the received value in the provider is `0`.

**How to reproduce**  
```php
new Get(
    uriTemplate: '/my_items/{id}/workflow/{transitionName<first_transition|second_transition|third_transition>}',
    output: MyOutput::class,
    provider: MyProvider::class,
)
```

In the provider, the `$uriVariables` contains:

```php
[
  "id" => 1,
  "transitionName" => 0,
]
```

instead of

```php
[
  "id" => 1,
  "transitionName" => "first_transition",
]
```

It seemd the problem come from `UriVariablesResolverTrait`, at the end call:
```php
 if ($this->uriVariablesConverter) {
      $context = ['operation' => $operation];
      $identifiers = $this->uriVariablesConverter->convert($identifiers, $operation->getClass() ?? $resourceClass, $context);
  }
```

Before it string is string, after it becames integers.

**Comment by soyuka** [comment]
Did you map the uri variable properly? look at the `getIdentifierTypes` we need to map your uri variable to a property to find out which type it is.

**Comment by mpiot** [comment]
@soyuka Mmm nope, no see infos about it.

Something like it ?
```php
            uriVariables: [
                'transitionName' => new ApiProperty(types: 'string'),
            ],
```

**Comment by soyuka** [comment]
```
  uriVariables: [
      'transitionName' => new ApiProperty(identifiers: ['transitionName']),
  ],
``` 
then in the class:

```
class .. {
  public string $transitionName;
}
```

We should add a way to put this directly to the metadata though.
