### ISSUE TITLE
[Serializer] Embed array of resources in custom output

### ISSUE THREAD

**Issue by mpiot** [api-platform/core#4989]
**API Platform version(s) affected**: 3.0.0

**Description**  
Like #4306, the Serializer now have same weird behavior in custom `Processor`, if you return an object with an array containing embed resources:

```php
{
    'level1Key' : {
        'level2Key: [
            {
                '@id' => '/api/resource_names/1',
                '@type' => 'ResourceName'
            },
            {
                '@id' => '/api/resource_names/2',
                '@type' => 'ResourceName'
            }
        ],
    },
   'otherLevel1Key': [
        {
            '@id' => '/api/other_resource_names/1',
            '@type' => 'OtherResourceName'
        },
        {
            '@id' => '/api/other_resource_names/2',
            '@type' => 'OtherResourceName'
        }
  ]
}
```

Instead of

```php
{
    'level1Key' : {
        'level2Key: [
            '/api/resource_names/1',
            '/api/resource_names/2',
        ],
    },
   'otherLevel1Key': [
        '/api/other_resource_names/1',
        '/api/other_resource_names/2',
  ]
}
```

**Comment by soyuka** [comment]
can't you use groups ? You may also benefit from the https://github.com/api-platform/core/blob/b80b5b069be6b9f78384c31249db06c2fa76d25c/src/Hydra/Serializer/CollectionNormalizer.php#L44 option (add this to the serializer context)

**Comment by mpiot** [comment]
@soyuka It seems not work in my case:

```php
#[ApiResource(
    operations: [
        // ...
        new Get(
            uriTemplate: '/my_items/{id}/workflow/{transitionName<transition_1|transition_2|transition_3>}',
            openapiContext: //...
            normalizationContext: ['groups' => [self::API_READ], 'iri_only' => true],
            output: MyItemOutput::class,
            provider: MyItemProvider::class,
        ),
        // ...
)]
class MyItem
```

```php
final class MyItemOutput
{
    #[Groups([MyItem::API_READ])]
    public array $steps = [];

    #[Groups([MyItem::API_READ])]
    #[Context(normalizationContext: ['iri_only' => true])]
    public array $items = [];
}
```
The processor set `$items` with an array of Resources, and `$steps` with an array, that contains array that target a Resrouces.

In `CollectionNormalizer`, it redirect to `normalizeRawCollection`, then never trigger the `$iriOnly` part.

**Comment by soyuka** [comment]
why not use `MyItemOutput` as a `ApiResource`?

**Comment by mpiot** [comment]
I can try your way, actually just find it in the doc: https://api-platform.com/docs/core/dto/#implementing-a-read-operation-with-an-output-different-from-the-resource
However, I don't really understand why define the DTO as `ApiResource` can resolve it ? Same Normalizer should be called, no ?

At the moment I've find this way:
```php
    #[Context(normalizationContext: ['api_empty_resource_as_iri' => true])]
```

It works because of the empty data (due to the Groups), then the called Normalizer in that case is the `AbstractItemNormalizer`.

Thanks a lot :)

**Comment by soyuka** [comment]
don't use outputs alltogether just do that:

```
#[Get(
    uriTemplate: '/my_items/{id}/workflow/{transitionName<transition_1|transition_2|transition_3>}',
    openapiContext: //...
    normalizationContext: ['groups' => [self::API_READ], 'iri_only' => true],
    provider: MyItemProvider::class,
)]
final class MyItemOutput
{
    // ...

    #[Groups([MyItem::API_READ])]
    #[Context(normalizationContext: ['iri_only' => true])]
    public array $steps = [];

    // ...

    #[Groups([MyItem::API_READ])]
    #[Context(normalizationContext: ['iri_only' => true])]
    public array $items = [];

    // ...
}
```

**Comment by mpiot** [comment]
@soyuka Your way is okay for direct collection (no sub arrays), if we add a `@var MyItem[] $items` annotation.

Thanks
