### ISSUE TITLE
AttribiuteLoader creates not existing property in Matadata resulting in error on POST v.1.1.0

### ISSUE THREAD

**Issue by tsurowiec** [api-platform/core#499]
v.1.1.0

the issues is as follows: 

I have a resource `Foo` that has a properly declared `OneToMany` relation to `Bar` resource, `$foo->bars`, so I have `getBars`, `addBar` and `removeBar` methods. 
When making a `POST` with `Foo` that includes collection of `Bars` (the same serialization group), the entities are correctly saved to database, and then I get an error : 

```
"hydra:title": "An error occurred",
  "hydra:description": "Neither the property \"member\" nor one of the methods \"getMember()\", \"member()\", \"isMember()\", \"hasMember()\", \"__get()\" exist and have public access in class \"AppBundle\\Entity\\Application\".",
```

after some debugging I have found that the class `Dunglas\ApiBundle\Mapping\AttributesLoader` in the line 71, based on setters: (`set|add|remove`) is adding singular 'bar' as a property to Metadata so then the getter `getBar` is required (as stated in the error description).

when the `add|remove` is removed from `preg_match` the error is gone...

what am i doing wrong, or this is an issue to be resolved ?

**Comment by tsurowiec** [comment]
just to clarify - exemplary `Bar` in my real code is in fact `Member` class - that's why in the error message there is `member`, `getMember` etc...

**Comment by Simperfit** [comment]
@tsurowiec I think this is fixed with the news version of symfony.

Could you try to update symfony ?
