### ISSUE TITLE
Authorization: Bearer [object Object]

### ISSUE THREAD

**Issue by FVesely** [api-platform/core#4993]
**API Platform version(s) affected**: 3.0.0

**Description**  
Swagger UI puts [object Object] to request instead of token.

**How to reproduce**  
https://github.com/swagger-api/swagger-ui/issues/7926

**Possible Solution**  
Update to newer version. Fixed in [v4.8.1](https://github.com/swagger-api/swagger-ui/releases/tag/v4.8.1)

**Comment by StefTweet** [comment]
```
$schemas = $openApi->getComponents()->getSecuritySchemes() ?? new \ArrayObject();

$schemas['JWT'] = new \ArrayObject([
            'type' => 'http',
            'scheme' => 'bearer',
            'bearerFormat' => 'JWT',
        ]);
```
This is the case when you add this code to update the openapi user interface via decorator as in the documentation.

[Documentation](https://api-platform.com/docs/core/jwt/)

If you delete this part of code, you must write bearer TOKEN_JWT in form

**Comment by FVesely** [comment]
Thank you, @StefTweet. Delete the code and add "Bearer " before the token can be used as a temporary solution. But I think this is a bug and it should work with the code.

If I replace the swagger-ui files in the public/bundles/apiplatform/swagger-ui folder with files from the newest release of swagger-api/swagger-ui the Authorization works. I want to send a pull request with a swagger-api/swagger-ui update, but the API Platform uses a fork instead of the original repository of swagger-api/swagger-ui.

**Comment by StefTweet** [comment]
Hi, i push PR now ;)
