### ISSUE TITLE
[3.0] ManyToMany self referencing not working

### ISSUE THREAD

**Issue by plamenh** [api-platform/core#5006]
**API Platform version(s) affected**: 3.0

**Description**  
With self-referencing many to many relationships the api breaks.

**How to reproduce**  

Add a ManyToMany relation and expose one of the sides. Depending on the side of the relationship you get:

`An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'employees.entity_target' in 'where clause'`

or

`An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'employees.entity_source' in 'where clause'`

Also, here's the culprit SQL statement for the first case, second case is similar:

`"SELECT t0.id AS id_1 FROM entity t0 INNER JOIN joinTable ON t0.id = joinTableName.entity_source WHERE joinTableName.entity_target = ?"`

So, it appears entity_source and entity_target should resolve to the joinColumn names, but they apparently do not.

**Comment by webda2l** [comment]
Still concerns a graphql resource?
You tried with and without the fork https://github.com/api-platform/core/issues/5001#issuecomment-1255923578 ?

**Comment by plamenh** [comment]
> Still concerns a graphql resource?
> You tried with and without the fork [#5001 (comment)](https://github.com/api-platform/core/issues/5001#issuecomment-1255923578) ?

This is being tested w/out graphql.

Have not had the chance to use the fork yet. If I can't troubleshoot it, I will have to try the fork, but it looks like it's almost exclusively graphic related.

**Comment by plamenh** [comment]
This was an issue with how Rector converted Annotations to Attributes. Not related to api-platform.
