### ISSUE TITLE
GraphQL Nested Children error ( is used outside the scope of its declaration )

### ISSUE THREAD

**Issue by develth** [api-platform/core#5007]
**API Platform version(s) affected**: 3.0

**Description**  
When query an item that have an nested set ( what i solved with [Doctrine Extensions Nested Set](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/tree.md#basic-examples) ) and want to make query with children, following error appears:

```
[Semantical Error] line 0, col 89 near 'o_a6.id = m_a7.deletedBy': Error: 'o_a6' is used outside the scope of its declaration.
```

The Request via REST is sucessful. 
Debuggin braught me `LinksHandlerTrait`, that wants to make sub query to fields that have a manyToOne relation on this object.

**How to reproduce**  
- DoctrineExtension with a NestedSet
- Query an Item with Children and that have a manyToOne relation to another Object

**Additional Context**  

GraphQL Query: 

```
query listTreeItemsQuery($treeItem: ID!) {
  treeItem(id: $treeItem) {
          id
          name
          children{
              totalCount
          }
        
  }
}
```

**Comment by develth** [comment]
Further Information:
It tries to add the failing fields that are outside the scope in following line:
https://github.com/api-platform/core/blob/d6112e2a85a5d76357205cdd3c5155250841d8dd/src/Doctrine/Orm/State/LinksHandlerTrait.php#L98

There it seems, that `$link->getFromClass()` and `$previousAlias` are the same and does not point to the referenced relation

**Comment by plamenh** [comment]
Same here in 2.7. It looks like 2.7 and 3.0 have so many issues with graphql that I don't think they are proper releases. I battled with 3.0 for more than a day, then went back to 2.7 and despite the small progress (now it at least returns responses in less than 300 seconds), the issues keep popping. There are some forks that supposedly 'fix' graphql issues, but they only take you that far. GraphQL keeps looking more and more like an afterthought with api-platform. And let's be real here, creating a serious API with REST is so 2000s it's not even funny.

**Comment by huelsmc** [comment]
Did someone saw a solution (in a fork) for this specific issue mentioned here?

**Comment by plamenh** [comment]
Sorry, I gave up and went back to 2.6.x. Good luck.

**Comment by tsdevelopment** [comment]
@alanpoulain will there be a fix for that in the near future?

**Comment by develth** [comment]
no really, because currently i get:

     "debugMessage": "More than one result was found for query although one row or none was expected.",

It wants to use the ItemProvider for the child collection

**Comment by develth** [comment]
IMHO its caused by this @alanpoulain 

https://github.com/api-platform/core/blob/v3.0.4/src/GraphQl/Type/FieldsBuilder.php#L265

especially: 

    $rootOperation->getClass() !== $resourceClass
    
With Children, both are same and it will decide everytime for ItemProvider instead of Collection

**Comment by alanpoulain** [comment]
The issue is more like, why this line gives you `false`, isn't it?
https://github.com/api-platform/core/blob/c62f66cecdad50efcf277c2206e2d9222a031c72/src/GraphQl/Type/FieldsBuilder.php#L253

**Comment by develth** [comment]
> The issue is more like, why this line gives you `false`, isn't it?

it is `true`

**Comment by alanpoulain** [comment]
OK it's because the root class is the same as the child class.
Maybe it needs a check on the depth instead.

**Comment by develth** [comment]
or just use the collectionCheck here, too?

**Comment by NicoHaase** [comment]
Are there any news on this topic? I'd like to update my application to ApiPlatform v3, but this bug blocks this update. Do you need any additional information to reproduce the problem?
