### ISSUE TITLE
Can no longer use an ApiResource as a the identifier for a Doctrine entity

### ISSUE THREAD

**Issue by NotionCommotion** [api-platform/core#5017]
**API Platform version(s) affected**: 3.0

**Description**  
API Platform 3.0 can no longer use an ApiResource as a the identifier for a Doctrine entity.  For example, the following worked with API Platform 2.6.

```php
#[ApiResource]
#[ORM\Entity]
class ProjectDirectory
{
    #[ORM\Id]
    #[ORM\OneToOne(targetEntity: Project::class, inversedBy: 'projectDirectory')]
    private ?Project $project=null;
}
```

```php
#[ApiResource]
#[ORM\Entity]
class ProjectDirectoryMember
{
    #[ORM\Id]
    #[ApiProperty(identifier: false)]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ApiProperty(identifier: true)]
    #[ORM\ManyToOne(targetEntity: UserInterface::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserInterface $user = null;
    
    #[ApiProperty(identifier: true)]
    #[ORM\ManyToOne(targetEntity: ProjectDirectory::class)]
    #[ORM\JoinColumn(nullable: false, referencedColumnName: 'project_id')]
    private ?ProjectDirectory $projectDirectory = null;
}
```
However, when attempted with API Platform 3.0, `api-platform/core/src/Symfony/Routing/IriConverter.php` errors with `"Unable to generate an IRI for the item of type "App\Entity\IntIdJoin"`.

Note that this functional never appeared to be documented very well, was not listed as a [Supported Identifier](https://api-platform.com/docs/core/identifiers/#supported-identifiers)  and perhaps has been removed intentionally.  Should this be the case, I am looking for a solution to implement this functionality myself such as potentially decorating the IriConverter, and feel this solution should also be included under the Supported Identifier section of the documentation.

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by NotionCommotion** [comment]
After searching for how to actually decorate IriConverter (which I never found), I stumbled upon [this commit](https://github.com/api-platform/core/commit/5cadcb32a91500f0741fc3d8f259c95b7f7d175c) which removes the script shown below.  I then added `  public function __toString()   { return (string) $this->id; }` to Project, and all works perfectly.  Guess, it wasn't originally "really supported" in the first place.

 ```php
           return (string) $identifierValue;
        }

        // TODO: remove this in 3.0
        // we could recurse to find correct identifiers until there it is a scalar but this is not really supported and adds a lot of complexity
        // instead we're deprecating this behavior in favor of something that can be transformed to a string
        if ($this->isResourceClass($relatedResourceClass = $this->getObjectClass($identifierValue))) {
            trigger_deprecation('api-platform/core', '2.7', 'Using a resource class as identifier is deprecated, please make this identifier Stringable');
            $relatedOperation = $this->resourceMetadataFactory->create($relatedResourceClass)->getOperation();

            $relatedLinks = [];
            if ($relatedOperation instanceof GraphQlOperation) {
                $relatedLinks = $relatedOperation->getLinks();
            } elseif ($relatedOperation instanceof HttpOperation) {
                $relatedLinks = $relatedOperation->getUriVariables();
            }

            if (1 === \count($relatedLinks)) {
                $identifierValue = $this->getIdentifierValue($identifierValue, $relatedResourceClass, current($relatedLinks)->getIdentifiers()[0], $parameterName);

                if (\is_scalar($identifierValue)) {
                    return $identifierValue;
                }

                if ($identifierValue instanceof \Stringable || method_exists($identifierValue, '__toString')) {
                    return (string) $identifierValue;
                }
            }
        }

        throw new RuntimeException(sprintf('We were not able to resolve the identifier matching parameter "%s".', $parameterName));
    }
}
```

**Comment by soyuka** [comment]
Indeed, really sorry about that we should've documented it in the CHANGELOG I'll do it ASAP. Identifiers if objects must be stringable or it's too hard to cover all the cases.

**Comment by NotionCommotion** [comment]
No worries.  Most of the time was searching for information about decorating the IRI converter, and once I gave up, finding the real solution was fairly quick.

Speaking of decorating the IRI converter, is it still something that should be done?  Often I see it mentioned, but never found anything showing how to actually do so.

1. https://gist.github.com/soyuka/a7a58732792872f000a09f79741042a4
2. https://github.com/api-platform/api-platform/issues/250
3. https://stackoverflow.com/questions/58040770/custom-collection-operation-and-iri-conversion-problem
4. https://lightrun.com/answers/api-platform-api-platform-question-how-to-implement-custom-child-entity-routes
5. https://lightrun.com/answers/api-platform-api-platform-subresource-without-using-doctrine

**Comment by soyuka** [comment]
Yes defintely decorate the IRI converter if needed, I do that often. Most of the time its enough to use `ApiProperty(types: [...])`
