### ISSUE TITLE
Inconsistent format for ULID identifiers

### ISSUE THREAD

**Issue by NotionCommotion** [api-platform/core#5021]
**API Platform version(s) affected**: 3.1

**Description**  

ApiPlatform displays ULID identifiers (Symfony\Component\Uid\Ulid) by default in base 32 format.  This format works for item requests for resources with a single identifier, however, does not work when the resource has multiple identifiers, and instead RFC4122 format must be used.  The ULID format should be consistent.

**How to reproduce**  
Create the following three entities.
```php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Ulid;
use Symfony\Bridge\Doctrine\IdGenerator\UlidGenerator;
use ApiPlatform\Metadata\ApiResource;

#[ApiResource]
#[ORM\Entity]
class EntityA
{
    #[ORM\Id]
    #[ORM\Column(type: 'ulid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UlidGenerator::class)]
    public ?Ulid $id = null;

    #[ORM\Column]
    public ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'entityA', targetEntity: EntityAB::class)]
    public Collection $entityABs;

    public function __construct()
    {
        $this->entityABs = new ArrayCollection();
    }

    public function __toString():string
    {
        return $this->id->toRfc4122();
        return (string) $this->id;
    }
}
```
```php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Ulid;
use Symfony\Bridge\Doctrine\IdGenerator\UlidGenerator;
use ApiPlatform\Metadata\ApiResource;

#[ApiResource]
#[ORM\Entity]
class EntityB
{
    #[ORM\Id]
    #[ORM\Column(type: 'ulid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UlidGenerator::class)]
    public ?Ulid $id = null;

    #[ORM\Column]
    public ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'entityB', targetEntity: EntityAB::class)]
    public Collection $entityABs;

    public function __construct()
    {
        $this->entityABs = new ArrayCollection();
    }

    public function __toString():string
    {
        return $this->id->toRfc4122();
        return (string) $this->id;
    }
}
```
```php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Ulid;
use Symfony\Bridge\Doctrine\IdGenerator\UlidGenerator;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiProperty;

#[ApiResource]
#[ORM\Entity]
class EntityAB
{
    #[ORM\Id]
    #[ApiProperty(identifier: false)]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ApiProperty(identifier: true)]
    #[ORM\ManyToOne(inversedBy: 'entityABs')]
    #[ORM\JoinColumn(nullable: false)]
    public ?EntityA $entityA = null;

    #[ApiProperty(identifier: true)]
    #[ORM\ManyToOne(inversedBy: 'entityABs')]
    #[ORM\JoinColumn(nullable: false)]
    public ?EntityB $entityB = null;

    #[ORM\Column]
    public ?string $name = null;
}
```

A POST request to /entity_a_bs using the Base32 ULID's is successful, and shows the newly recreated ID as `/entity_a_bs/entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX`.
```
curl -X 'POST' \
  'https://testing.example.com/entity_a_bs' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "entityA": "/entity_as/01GE2EV7Y39WWQ6HEPCHGHCDHX",
  "entityB": "/entity_bs/01GE2EVMG86MR47SE07Y860RDX",
  "name": "entityA1XentityB1"
}'
```

```json
{
  "@context": "/contexts/EntityAB",
  "@id": "/entity_a_bs/entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX",
  "@type": "EntityAB",
  "entityA": "/entity_as/01GE2EV7Y39WWQ6HEPCHGHCDHX",
  "entityB": "/entity_bs/01GE2EVMG86MR47SE07Y860RDX",
  "name": "entityA1XentityB1"
}
```

A collection GET request to /entity_a_bs is also succesful and also shows the ID as `/entity_a_bs/entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX`.
```
curl -X 'GET' \
  'https://testing.example.com/entity_a_bs?page=1' \
  -H 'accept: application/ld+json'
  ```

```json
{
  "@context": "/contexts/EntityAB",
  "@id": "/entity_a_bs",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/entity_a_bs/entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX",
      "@type": "EntityAB",
      "entityA": "/entity_as/01GE2EV7Y39WWQ6HEPCHGHCDHX",
      "entityB": "/entity_bs/01GE2EVMG86MR47SE07Y860RDX",
      "name": "entityA1XentityB1"
    }
  ],
  "hydra:totalItems": 1
}
```

A GET item request to /entity_a_bs using ID `entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX`, however, is not successful:

```
curl -X 'GET' \
  'https://testing.example.com/entity_a_bs/entityA%3D01GE2EV7Y39WWQ6HEPCHGHCDHX%3BentityB%3D01GE2EVMG86MR47SE07Y860RDX' \
  -H 'accept: application/ld+json'
```

```
An exception occurred while executing a query: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "01GE2EV7Y39WWQ6HEPCHGHCDHX"
CONTEXT:  unnamed portal parameter $1 = '...'
```

Changing the GET item request to /entity_a_bs use rfc4122 format and ID `entityA=018384ed-9fc3-4f39-7345-d6646116363d;entityB=018384ed-d208-3530-43e5-c03f906061bd`, however, is successful:

```
curl -X 'GET' \
  'https://testing.example.com/entity_a_bs/entityA%3D018384ed-9fc3-4f39-7345-d6646116363d%3BentityB%3D018384ed-d208-3530-43e5-c03f906061bd' \
  -H 'accept: application/ld+json'
```

```json
{
  "@context": "/contexts/EntityAB",
  "@id": "/entity_a_bs/entityA=01GE2EV7Y39WWQ6HEPCHGHCDHX;entityB=01GE2EVMG86MR47SE07Y860RDX",
  "@type": "EntityAB",
  "entityA": "/entity_as/01GE2EV7Y39WWQ6HEPCHGHCDHX",
  "entityB": "/entity_bs/01GE2EVMG86MR47SE07Y860RDX",
  "name": "entityA1XentityB1"
}
```
**Possible Solution**  

When using Symfony's Uid components, UUIDs when typecast as a string result in RFC4122, however, ULIDs when typecast as a string result in Base32.  Either Symfony needs to change their implementation to return the same format or API-Platform needs to explicitly convert to a string by calling toRfc4122().  Edit.  Likely not a good solution per https://github.com/symfony/symfony/issues/47717#issuecomment-1261407925.

**Additional Context**

**Comment by soyuka** [comment]
For now feel free to implement your own https://github.com/api-platform/core/blob/main/src/Symfony/UriVariableTransformer/UlidUriVariableTransformer.php and to do the transformation you want.

**Comment by NotionCommotion** [comment]
@soyuka

Thanks, Yes, I resolved the error by following the [Custom Identifier Normalizer](https://api-platform.com/docs/main/core/identifiers/#custom-identifier-normalizer) documentation and changing `return Ulid::fromString($value);` to either `return Uuid::fromString($value);` or `return Ulid::fromString($value)->toRfc4122();`.

It appears that [ULID's](https://github.com/ulid/spec) "default" format should be base 32 and not RFC4122.  Agree?

While this solution works, I don't feel one should have had to implement it.  Maybe I just missed it, but I didn't see another existing issue, and I see you closed this issue.  Is it not the intent to eventually update ApiPlatform to do so by default?

**Comment by NotionCommotion** [comment]
It appears that this issue and https://github.com/api-platform/core/issues/5017#issuecomment-1261924216 are very related, and that an UriVariableTransformer is not required if `toString()` returns `$this->id->toRfc4122()` instead of `(string) $this->id`.

At least I hope so as I wasn't able to get an UriVariableTransformer for entities which use other entities as identifiers working for all requests types.  For instance, for item requests, UriVariableTransformerInterface transform() and supportsTransformation() are called twice and given [UserObject, Resource] for $types.

True?

```php
#[ORM\Entity]
#[ApiResource]
#[ORM\UniqueConstraint(columns: ['user_object_id', 'resource_id'])]
class Junction
{
    #[ORM\Id]
    #[ORM\Column(type: 'ulid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UlidGenerator::class)]
    #[ApiProperty(identifier: false)]
    #[Ignore]
    private ?Ulid $id = null;

    #[ORM\ManyToOne(inversedBy: 'junctions')]
    #[ORM\JoinColumn(nullable: false)]
    #[ApiProperty(identifier: true)]
    private ?UserObject $userObject = null;

    #[ORM\ManyToOne(inversedBy: 'junctions')]
    #[ORM\JoinColumn(nullable: false)]
    #[ApiProperty(identifier: true)]
    private ?Resource $resource = null;

    // other properties...
}
```

**Comment by soyuka** [comment]
we don't recommend multiple identifiers good that you found a solution
