### ISSUE TITLE
2.7: Warning: Undefined array key "resource_class"

### ISSUE THREAD

**Issue by rsereir** [api-platform/core#5022]
**API Platform version(s) affected**: 2.7

**Description**  
I upgrade today in 2.7 to migrate without stress in few weeks on 3.0. I enable the great `    metadata_backward_compatibility_layer: false` parameter.

All it's working and i can create my new operations with the new 3.0 features and work with my 2.6 for now. But i have an issue on my routes with DataTransformers : 

`Warning: Undefined array key "resource_class"`

**How to reproduce**  
Call an endpoint with a DataTransformer on 2.7

**Possible Solution**  
I analyze in sources where it's breaking and i see:
```
// AbstractItemNormalizer
            if ($this->resourceMetadataFactory instanceof ResourceMetadataCollectionFactoryInterface && !isset($context['operation'])) {
                $context['operation'] = $this->resourceMetadataFactory->create($context['resource_class'])->getOperation();
            }```

I didn't know if i have any solution to bypass this condition

**Additional Context**

**Comment by soyuka** [comment]
data transformers are removed `$operation->getClass()` or keep the flag to `true` for retro-compatibility.

**Comment by rsereir** [comment]
@soyuka i can't have flag on `true ` with new 2.7 features.. ( my ApiResources operations from Metadata namespace does not appear on doc )
