### ISSUE TITLE
Loss the possibility to transform each item of collection in 3.0

### ISSUE THREAD

**Issue by rsereir** [api-platform/core#5023]
**API Platform version(s) affected**: 3.0

**Description**  
Sometimes, i used DataTransformer to add some virtualProperties on my collection items ( like `favorite: true/false` if the current user like this entity ). In my DataTransformer i've access to my services and i active the DataTransformer trigger with self class in output property. Today in 3.0 it's not possible: i can't update my collection items.

The current solution i have is to make a Provider with a foreach on each resources but i really don't know if it's the best way to do this. Maybe missing documentation on https://api-platform.com/docs/main/core/dto/ for GetCollection operation ? 

-> I see i loss native filters of api platform when i use Provider ( SearchFilter are not call for example )

**Comment by soyuka** [comment]
Use a normalizer or a Provider. If you want the filters you can decorate our data provider `api_platform.doctrine.orm.state.item_provider`
