### ISSUE TITLE
Allow easier extension of the (Hydra + OpenApi) Documentation

### ISSUE THREAD

**Issue by olivermack** [api-platform/core#5037]
**Description**  

As a developer of an api-platform backed application I'd like to be able to extend certain documentation-related parts without the necessity to decorate the whole DocumentationNormalizer.

The current implementation of the `\ApiPlatform\Hydra\Serializer\DocumentationNormalizer` is marked `final` (for good reason) and thus does not allow extension/overrides in the various steps which are being represented as private methods within the normalizer. In case I'd like to extend the documentation yielded for a certain class or property I'd need decorate the whole DocumentationNormalizer, get the _decoratable_ result and perform my magic on the whole output generated by the decorated normalizer. While this certainly works it does not seem very handy as I'd need to search for the desired part and replace it in the result accordingly. In most cases I came across in the meanwhile working with APIP this almost always required class- or property-metadata to be present for the affected item - essentially all the info which is already available in the base `DocumentationNormalizer`. For efficiency purposes I'd like to avoid the heavy scanning plus subsequent metadata lookup and to ask for a way to hook into the main `DocumentationNormalizer`.

I'm not having a concrete/preferred approach in mind but I can imagine that the Normalizer could emit Events which could allow the manipulation of the certain parts (which would introduce a dependency to the EventDispatcher obviously but would allow the reuse of already prepared metadata objects via event payload) or to split the various responsibilities of the main `DocumentationNormalizer` into more fine-grained individual normalizers which allow individual decoration. Additionally I guess the same principle should apply to the OpenApi Documentation.

However, I was already tempted to copy the whole main DocumentatioNormalizer to enhance it with my own extensions which is - I guess - not a good indication for extensibility (open-closed principle?).

**Comment by olivermack** [comment]
One small addition: currently the main reason for me to open this feature request was to enhance e.g. the property `range` (or alike) to represent PHP 8.1 native enum values. I've read somewhere that support for enums is going to be implemented in the core but in the meantime I need some alternative to fulfill my needs.

**Comment by soyuka** [comment]
OpenAPI should be more accessible using the OpenApiFactory (its documented). For hydra, use a normalizer. We're trying to improve how normalizers work inside Symfony but this will take time until we reach a better Dx.

**Comment by soyuka** [comment]
closing in favor of the one linked
