### ISSUE TITLE
Upgrade command does not remove #[ApiSubresource]

### ISSUE THREAD

**Issue by BeyerJC** [api-platform/core#5038]
**API Platform version(s) affected**: 2.7.1

**Description**  
Maybe this is intened but after running the upgrade command, a new ApiResource was added in my related entity class but the `#[ApiSubresource]` attribute was not removed.

**How to reproduce**  
Create two related entities, add #[ApiSubresource] attribute and run the upgrade command.

**Possible Solution**  
If this is not intended the command should remove the attribute after creating the new GetCollection.

**Comment by soyuka** [comment]
Even by using `php-cs-fixer` after? Maybe we forgot something even though it's not a big deal as they won't be processed in 3.0 (or legacy flag to false).

**Comment by BeyerJC** [comment]
No, php-cs-fixer did not remove the attribute. It did not cause any trouble besides my IDE complaining :-)
