### ISSUE TITLE
Authorization: Bearer [object Object]

### ISSUE THREAD

**Issue by FVesely** [api-platform/core#5044]
**API Platform version(s) affected**: 3.0.1

**Description**  
Re-open https://github.com/api-platform/core/issues/4993

**Possible Solution**  
Update Swagger UI

The problem persists after the update to 3.0.1. 

The Swagger UI files weren't updated in https://github.com/api-platform/core/pull/5028

**Comment by soyuka** [comment]
can you try 3.0.2 ? it should be fixed now sorry about the mistake

**Comment by FVesely** [comment]
@soyuka thank you, it's working now
