### ISSUE TITLE
[BUG + Possible solution] [Semantical Error] line 0, col 63 near 'o_a1.id = :id_p1': Error: 'o_a1' is not defined.

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#5052]
Originally posted here: https://github.com/api-platform/api-platform/issues/2286

I'm opening an issue here, too, as I don't know which is the right repo in which to post.

**API Platform version(s) affected**: 3.0.0 | 3.0.1

**Description**  
When upgraded from 2.7.0 to 3.0.0, I used the automatic tool provided by ApiPlatform.

It created some more operations on my entities but they seem not work.

For example, I have an Account entity and a Channel entity like below:

```php
# Entity/Account

#[ApiResource]
#[Entity(repositoryClass: AccountRepository::class)]
class Account implements \Stringable, Timestampable
{
    use TimestampableEntity;

    #[Column(name: 'id', type: Types::INTEGER)]
    #[Id]
    #[GeneratedValue(strategy: 'IDENTITY')]
    private int $id;

    #[OneToMany(targetEntity: Channel::class, mappedBy: 'account')]
    private Collection $channels;

    ...
}
```

```php
# Entity/Channel

#[API\ApiResource]
#[API\ApiResource(uriTemplate: '/accounts/{id}/channels.{_format}', uriVariables: ['id' => new API\Link(fromClass: Account::class, identifiers: ['id'])], status: 200, operations: [new API\GetCollection()])]
#[API\ApiResource(uriTemplate: '/users/{id}/accounts/{accounts}/channels.{_format}', uriVariables: ['id' => new API\Link(fromClass: User::class, identifiers: ['id']), 'accounts' => new API\Link(fromClass: Account::class, identifiers: ['id'])], status: 200, operations: [new API\GetCollection()])]
#[Entity(repositoryClass: ChannelRepository::class)]
class Channel implements ConfigurableRemote, \Stringable, Timestampable
{
    use RemoteTrait;
    use TimestampableEntity;

    #[Column(name: 'id', type: Types::INTEGER)]
    #[Id]
    #[GeneratedValue(strategy: 'IDENTITY')]
    private int $id;

    #[ManyToOne(targetEntity: Account::class, inversedBy: 'channels')]
    private Account $account;

    ...
}
```

When I call `/api/accounts/1/channels`, I get the following error from Doctrine:

> [Semantical Error] line 0, col 63 near 'o_a1.id = :id_p1': Error: 'o_a1' is not defined.

**Additional Context**  

The query that causes the bug is this:

    SELECT o FROM App\Entity\Channel o WHERE o_a1.id = :id_p1 ORDER BY o.id ASC

As you can see, it uses `o_a1` as table alias, while it sets the alias of the table to `o`. So it seems there is a problem generating the correct DQL.

Digging into the code following the origin of the bug, I came to the trait `ApiPlatform\Doctrine\Orm\State\LinksHandlerTrait::57`:

This is the interested code:

```php
            if (!$link->getFromProperty() && !$link->getToProperty()) {
                $doctrineClassMetadata = $manager->getClassMetadata($link->getFromClass());
/* 57 */        $currentAlias = $link->getFromClass() === $resourceClass ? $alias : $queryNameGenerator->generateJoinAlias($alias);

                foreach ($identifierProperties as $identifierProperty) {
                    $placeholder = $queryNameGenerator->generateParameterName($identifierProperty);
                    $queryBuilder->andWhere("$currentAlias.$identifierProperty = :$placeholder");
                    $queryBuilder->setParameter($placeholder, $this->getIdentifierValue($identifiers, $hasCompositeIdentifiers ? $identifierProperty : null), $doctrineClassMetadata->getTypeOfField($identifierProperty));
                }

                $previousAlias = $currentAlias;
                $previousJoinProperties = $doctrineClassMetadata->getIdentifierFieldNames();
                continue;
            }
```

At line "57" the code is executed well: I have two classes:

- `Account`
- `Channel`

so the code correctly calls the method `$queryNameGenerator->generateJoinAlias($alias)`.

The problem is that the query builder passed, in the DQL parts, for the `select` part, has the `o` value already set while the method `$queryNameGenerator->generateJoinAlias($alias)` returns `o_a1`.

**Possible solution**

The solution I tested is very simple: change `===` with `!==`:

```diff
            if (!$link->getFromProperty() && !$link->getToProperty()) {
                $doctrineClassMetadata = $manager->getClassMetadata($link->getFromClass());
- /* 57 */        $currentAlias = $link->getFromClass() === $resourceClass ? $alias : $queryNameGenerator->generateJoinAlias($alias);
+ /* 57 */        $currentAlias = $link->getFromClass() !== $resourceClass ? $alias : $queryNameGenerator->generateJoinAlias($alias);

                foreach ($identifierProperties as $identifierProperty) {
                    $placeholder = $queryNameGenerator->generateParameterName($identifierProperty);
                    $queryBuilder->andWhere("$currentAlias.$identifierProperty = :$placeholder");
                    $queryBuilder->setParameter($placeholder, $this->getIdentifierValue($identifiers, $hasCompositeIdentifiers ? $identifierProperty : null), $doctrineClassMetadata->getTypeOfField($identifierProperty));
                }

                $previousAlias = $currentAlias;
                $previousJoinProperties = $doctrineClassMetadata->getIdentifierFieldNames();
                continue;
            }
```

Doing this simple change, makes the DQL being generated correctly.

As I don't know deeply the internals of Api Platform, I don't know if this is an actual fix or simply a lucky shot.

UPDATE

Continuing to work on this, it seems the fix I provided is wrong: the problem is the logic is broken.

The fix I provided works with `GetCollection`.

But with `Get` it is completely broken (or, maybe, the documentation is wrong and I'm missing something in configuration of operations).

Anyway, the two DQL queries generated are wrong in any case:

    $currentAlias = $link->getFromClass() !== $resourceClass ? $alias : $queryNameGenerator->generateJoinAlias($alias);

generates 

    SELECT o FROM Coommercio\App\Coommercio\Entity\Channel o WHERE o.id = :id_p1 AND o_a1.id = :id_p2

while

    $currentAlias = $link->getFromClass() === $resourceClass ? $alias : $queryNameGenerator->generateJoinAlias($alias);

generates

    SELECT o FROM Coommercio\App\Coommercio\Entity\Channel o WHERE o_a1.id = :id_p1 AND o.id = :id_p2

In both cases, the alias `o_a1` is not defined.

More, the query seems to be wrong also for the fields it uses. The correct one should be similar to this:

    SELECT o FROM Coommercio\App\Coommercio\Entity\Channel o WHERE o.id = :id_p1 AND o.account_id = :id_p2

**Comment by soyuka** [comment]
- please check our fixtures for examples if the [documentation](https://api-platform.com/docs/core/subresources/#uri-variables-configuration) is not enough: https://github.com/api-platform/core/search?q=path%3Atests%2FFixtures+Link%28 you're missing the `property` option everywhere
- also try playing with `toClass` and `fromClass` 
- if a core Provider doesn't work like you want please create your own

When doing a patch you may want to run  our functional tests (see Contributing) to know if you break something within API P.

**Comment by Aerendir** [comment]
Hi @soyuka , thank you for your suggestion: just yesterday, after having posted the issue here, I saw that in the tag there is the list of PRs and that one of these is from you, implementing the subresources paths.

I'm going to check the functional tests and see how I can make the subresources work for me.

Just as a clarification: is the use of a custom provider intended in this situation? Shouldn't sub-resources work out of the box?

**Comment by Aerendir** [comment]
Ok, as you pointed out, the configuration of `fromProperty` made the endpoint work again!

As a debriefing, the problem comes from the automatic command: I simply leaved the attributes as created by the automatic conversion tool and the automatic conversion didn't add the `fromProperty` property on attributes.

I think that the automatic tool should add a comment that says something like this:

```php
// We have automatically created the subresources.
// For more info about the new way of configuring them in ApiPlatform Core 3.0.0, please read
// https://api-platform.com/docs/core/subresources/#uri-variables-configuration
#[API\ApiResource]
#[API\ApiResource(
    uriTemplate: '/accounts/{id}/channels.{_format}',
    uriVariables: ['id' => new API\Link(
        fromClass: Account::class,
        // fromProperty: Please, add here from the property that creates the relation between the two entities
        fromProperty: 'channels',
        identifiers: ['id']
    )],
    status: 200,
    operations: [new API\GetCollection()]
)]
#[Table(name: 'channels', schema: 'coommercio')]
#[Entity(repositoryClass: ChannelRepository::class)]
class Channel implements ConfigurableRemote, \Stringable, Timestampable
{
```

I completely missed this part of the documentation, absorbed by the fixing of other bugs: having a comment that explains what's going on, would be very very helpful for debugging and learning the new dynamics of Api Platform.

**Comment by soyuka** [comment]
This tool is more of a helper and we're trying our best, glad you make it work.
