### ISSUE TITLE
Impossible to use the security property in ApiProperty attribute

### ISSUE THREAD

**Issue by Xusifob** [api-platform/core#5054]
**API Platform version(s) affected**: 3.0.0

**Description**  
When using the security property on the ApiProperty attribute on an entity property, the _object_ object received, is null

**How to reproduce**  
````php
// src/Entity/Dummy.php 

    #[ApiProperty(
        security: "is_granted('VIEW',object)",
        securityPostDenormalize: "is_granted('MODERATE',object)",
        schema: [
            'type' => 'boolean',
        ])]
    public bool $isModerated = false;
 ````
 
 In my scenario, VIEW should returns true and MODERATE should returns false

**Possible Solution**  
The security attribute should get an access to the object that is created

**Additional Context**  

Here is the data my voters are getting
![image](https://user-images.githubusercontent.com/8103268/194146264-b49c6817-f90b-49ae-b9b5-97c3700a443f.png)

**Comment by soyuka** [comment]
We need a reproducer or more informations about what you're trying to do.
