### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by mpiot** [api-platform/core#5055]
**API Platform version(s) affected**: 3.0.0

**Description**  
Since upgrade to 3.0.0, response returned from the API cause trouble with accents: `Problème` appear as `Probl\u00e8me` for example.

This appear when calling the Entrypoint from Postman inside the "Raw" tab (since the 3.0.0 version).
Inside Firefox "JSON" tab or Postman "Pretty" tab, the accent is always properly rendered.

**Comment by soyuka** [comment]
I don't think its related to API Platform, provide a reproducer not using external tools (like a behat test) and we'll consider.
