### ISSUE TITLE
`ItemProvider` tries to search for a non-existent entity on `Post` request

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#5058]
**API Platform version(s) affected**: 3.0.1

Maybe linked to: https://github.com/api-platform/core/issues/5052

I'm trying to use subresources to post new entities.

This is the code:

```php
#[ORM\Entity]
#[Vich\Uploadable]
#[API\ApiResource(
    types: ['https://schema.org/MediaObject'],
    operations: [
        new API\Post(
            uriTemplate: self::API_ENDPOINT,
            uriVariables: [
                'account_id' => new API\Link(
                    fromClass: Account::class,
                    toProperty: 'account',
                    identifiers: ['id'],
                )
            ],
            controller: CreateFileVichAction::class,
            deserialize: false,
            validationContext: ['groups' => [Constraint::DEFAULT_GROUP, FileDocVich::GROUP_VAL_POST]],
        ),
        new API\Get(
            uriTemplate: self::API_ENDPOINT . '/{id}',
            uriVariables: [
                'account_id' => new API\Link(fromClass: Account::class, toProperty: 'account', identifiers: ['id']),
                'id' => new API\Link(fromClass: FileDocVich::class, identifiers: ['id']),
            ],
            openapiContext: ['tags' => [self::OPENAPI_TAG]],
        ),
    ],
)]
class FileDocVich extends FileAbstractVich
{
    public const API_ENDPOINT          = '/accounts/{account_id}/files/docs';
    ...
}
```

When trying to post to this endpoint, I get a 404 error:

> Not found

The error comes from `ApiPlatform\Symfony\EventListener\ReadListener`, at line 94:

```php
        try {
            $uriVariables = $this->getOperationUriVariables($operation, $parameters, $resourceClass);
            $data = $this->provider->provide($operation, $uriVariables, $context);
        } catch (InvalidIdentifierException|InvalidUriVariableException $e) {
            throw new NotFoundHttpException('Invalid identifier value or configuration.', $e);
        }

        if (null === $data) {
/* 94 */    throw new NotFoundHttpException('Not Found');
        }
```

The problem is that `$data = $this->provider->provide($operation, $uriVariables, $context);` returns `null`.

The provider used is `ApiPlatform\Doctrine\Orm\State\ItemProvider` and it generates a wrong DQL query:

> SELECT o FROM App\Common\Entity\FileDocVich o INNER JOIN o.account o_a1 WHERE o_a1.id = :id_p1

As you can see, it tries to retrieve the entity from `App\Common\Entity\FileDocVich` but, as this is a `POST` request, the entity doesn't exist.

More, it should query the `Account` table, not the `FileDocVich` one.

I don't understand why it tries to retrieve something that is known don't yet exist as I'm creating it.

I did some tests.

**Test 1**

```diff
        new API\Post(
            uriTemplate: self::API_ENDPOINT,
            uriVariables: [
                'account_id' => new API\Link(
-                    fromClass: Account::class,
+                    toClass: Account::class,
                    toProperty: 'account',
                    identifiers: ['id'],
                )
            ],
```

The resulting query is wrong

> SELECT o FROM App\Common\Entity\FileDocVich o

**Test 2**

```diff
        new API\Post(
            uriTemplate: self::API_ENDPOINT,
            uriVariables: [
                'account_id' => new API\Link(
                    fromClass: Account::class,
+                    toClass: self::class,
                    toProperty: 'account',
                    identifiers: ['id'],
                )
            ],
```

As expected, the DQL query is

> SELECT o FROM App\Common\Entity\FileDocVich o INNER JOIN o.account o_a1 WHERE o_a1.id = :id_p1

I really don't understand the logic behind the handling of subresources: what should work, doesn't.

I also checked the fixtures, but I cannot find any useful use case.

The stranger thing is that yesterday it worked for a while and then, without any apparent reason, it started to return the 404 error.

Maybe yesterday was just a coincidence it worked but now it doesn't work and I really don't understand if it is a fault of mine or if it is actually a bug.

PS
Without using the subresource endpoint, the code works without issues and correctly creates the entity and uploads the file.

**Comment by soyuka** [comment]
you've a really custom case here either disable read `read: false` or create an item provider. When you have URI variables in your URI API Platform tries to retrieve an object according to these values. See also our `CreateProvider`.

**Comment by Aerendir** [comment]
Thank you @soyuka Ok, I finally understood which is the problem (better: which ARE the problemS).

As I told, the configuration (without the suggested `read: false` parameter) worked (apparently) "randomly".

Thank to you hint about `read: false` a lamp lighted in my mind.

# EXPLANATION OF THE PROBLEM AND SOLUTION

This configuration works only if in the database is still present one and only one row that has the `FileDocVich::$account` property set (maybe created manually or from other "experiments").

In this case, in fact, the `ItemProvider` tries to get an instance of a `FileDocVich` that has `FileDocVich::$account === {account_id}`.

In this situation the endpoint doesn't trigger any error **and correctly creates a second row with `account === {account_id}`**. The association is handled by the custom controller:

```php
#[AsController]
final class CreateFileVichAction extends AbstractFileVichAction
{
    public function __invoke(Request $request, Account $account): FileDocVich
    {
        $uploadedFile = parent::getUploadingFile($request);
        $file = FileDocVich::createFromUploadedFile($uploadedFile);
        $file->setAccount($account);

        return $file;
    }
}
```

BUT, the second time the endpoint is called, another row with the same `account === {account_id}` exists (created by the previous call) and this time the `ItemProvider` triggers an error.

In fact, to retrieve the entity it uses `return $queryBuilder->getQuery()->getOneOrNullResult();`: this method triggers `Doctrine\ORM\NonUniqueResultException` if more than one row corresponding to the query exist.

So, those are the possible scenarios:

1. **DOESN'T WORK (404)** if there are 0 (zero) rows with `account === {account_id}`
    - `$queryBuilder->getQuery()->getOneOrNullResult();` cannot find a row and returns `null`;
    -  The `ReadListener` throws a `\Symfony\Component\HttpKernel\Exception\NotFoundHttpException` as `/* 93 */ if (null === $data)` is `true`
2. **WORKS** if there is only one row with `account === {account_id}`
    - `$queryBuilder->getQuery()->getOneOrNullResult();` can find a row and returns it;
    -  The `ReadListener` doesn't throw anything as `/* 93 */ if (null === $data)` is `false`
3. **DOESN'T WORK (500)** if "rows with `account === {account_id}` > 1"
    - `$queryBuilder->getQuery()->getOneOrNullResult();` throws a `Doctrine\ORM\NonUniqueResultException`

## Fixing the problem using `read: false`

### Scenario 1
In this case the `ReadListener` is not called (I suppose) and so no `NotFoundHttpException` is thrown.

One new row with `account === {account_id}` is correctly created (the association between `FileDocVich` and `Account` is set by `CreateFileVichAction`)

## Scenario 2

At this point we already have a row in the database with `account === {account_id}` and so the endpoint works per the dynamics explained above.

The property `read: false` is actually irrelevant.

## Scenario 3

At this point we already have two rows in the database with `account === {account_id}`.

The endpoint works also in this situation as `ReadListener` is not called due to `read: false`.

PS
All these words were not necessary: a simple "thank you @soyuka" would have been sufficient.

But I was going deeper in the problem as, also using `read: false` I got some errors.

Then I reset the database and now all works well.

I decided to leave the post as is for future reference: maybe it will be useful in future.

Anyway, an example with a `POST` request using subresources should be published in the documentation or (better) the `ReadListener` should be automatically disable on `POST` calls as it is not useful (I think but maybe it is for other use cases).

Anyway, a mention in the docs is mandatory in my opinion.

That said, many many thank you @soyuka for the support!
