### ISSUE TITLE
EagerLoadingExtension makes serialization groups usage mandatory

### ISSUE THREAD

**Issue by gaetan-petit** [api-platform/core#5062]
**API Platform version(s) affected**: 3.x and probably from 2.2.7

**Description**  
In the EagerLoadingExtension a check was introduced with 2.2.7 version where the `apply()` method would return void if no groups are defined in context. (see: https://github.com/api-platform/core/commit/000f6dfec5ec37e6b46ad6e8b7036650c70ddc09 from PR https://github.com/api-platform/core/pull/2002)

The documentation states:
> By default in API Platform, we made the choice to force eager loading for all relations, with or without the Doctrine fetch attribute. Thanks to the eager loading extension. The EagerLoadingExtension will join every readable association according to the serialization context.

It doesn't seems that defining a serialization group should be mandatory, but that it should be an out of the box behavior.

**How to reproduce**  
Set a Doctrine entity with a association mapped to another entity.
Don't set any groups, perform a GET operation on collection and inspect the performed Doctrine queries.
Commenting the `return;` from the `apply()` method in `EagerLoadingExtension` brings the Join back in the query and drop the multiple queries to the associated entity/entities.

**Possible Solution**  
Either the `apply()` method should not require user to define serialization groups or the documentation should be amended to add this requirement.

**Comment by gaetan-petit** [comment]
I'm willing to fix documentation if needed.
I just need a confirmation if this is a bug or not.

**Comment by soyuka** [comment]
Indeed EagerLoading is based on serialization groups to know which relation to join. Do you mean that we should allow the use of this extension without groups?

**Comment by gaetan-petit** [comment]
@soyuka I mean that before https://github.com/api-platform/core/commit/000f6dfec5ec37e6b46ad6e8b7036650c70ddc09 using a groups wasn't mandatory to trigger the fetch eager behavior. So either the doc should be amended accordingly, or it's a bug and we should allow back the behavior without a group.

I'm willing to amend the doc (easy fix), bringing back the behaviour however would probably need investigations see https://github.com/api-platform/core/pull/2002

**Comment by soyuka** [comment]
4 years old pr ? This should be fixed by amending the doc indeed :)
