### ISSUE TITLE
Incorrect deprecation: Since api-platform/core 2.7: Decorating the legacy `ApiPlatform\Core\Metadata\Property\Factory\PropertyMetadataFactoryInterface` is deprecated, use `ApiPlatform\Metadata\Property\Factory\PropertyMetadataFactoryInterface` instead.

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#5078]
**API Platform version(s) affected**: 2.7.2

**Description**  
Receive the deprecation
> Since api-platform/core 2.7: Decorating the legacy ApiPlatform\Core\Metadata\Property\Factory\PropertyMetadataFactoryInterface is deprecated, use ApiPlatform\Metadata\Property\Factory\PropertyMetadataFactoryInterface instead.

from https://github.com/api-platform/core/blob/41bbad94e93df49eb4ade0fe1307b20d9cd07102/src/Core/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php#L43

First of all, I am not `Decorating the legacy ApiPlatform\Core\Metadata\Property\Factory\PropertyMetadataFactoryInterface`, api-platform is decorating it.

It seems that `deprecate => false` in options should cascade down from `ApiPlatform\Metadata\Property\Factory\LegacyPropertyMetadataFactory`, but `LegacyPropertyMetadataFactory` is not in my chain of metadata factories, as this service is not loaded when `metadata_backward_compatibility_layer` is enabled.

This is reported by symfony phpunit bridge as a `self` deprecation handler, i.e. i should be able to resolve it in my own.
This is not true.

**How to reproduce**  
Use on a project using the legacy metadata system

**Possible Solution**  
Unknown

**Additional Context**  
introduced in https://github.com/api-platform/core/pull/4685

**Comment by soyuka** [comment]
thanks for the report this is definitely an issue I'll try to find some time to fix this

**Comment by bendavies** [comment]
thankyou as always @soyuka !

**Comment by soyuka** [comment]
fix will land in next patch

**Comment by bendavies** [comment]
thankyou!
