### ISSUE TITLE
PHPUnit test helpers/utils as separate package?

### ISSUE THREAD

**Issue by svbackend** [api-platform/core#5081]
**Description**  

On some projects I would be happy to use ApiPlatform's test utils/helpers because they are really convenient and easy way to test APIs (all these assertResponseStatusEquals(), assertResponseEquals() assertion helpers and much more) but I wish it would be possible to do it without installing the API Platform itself. Is there any plans to move this part to separate package?

**Comment by soyuka** [comment]
you can use `api-platform/core` its meant for that. There are plans to do a subtree split but its a "maybe" because its a lot of work.
