### ISSUE TITLE
Custom MetaData for Operation

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#5083]
**Description**  
While thinking about how to best implement rate limiting based on routes I thought it would be useful to be able to add custom meta data to each operation. That way you could just write custom configuration into the operation and then fetch it during the request. It's probably useful for a lot of route related stuff.

**Example**  
``` php
#[Get(
metaData: [
 // What ever the user wants
]
)]
```

and then you just fetch it using the Query Extension (or a non internal version of  OperationRequestInitiatorTrait?)

**Comment by soyuka** [comment]
you're looking for `extraProperties`

**Comment by KDederichs** [comment]
Ah nice, what would be the proper way to access that in a service or a event listener?
