### ISSUE TITLE
use new IriConverter with legacy ApiResource

### ISSUE THREAD

**Issue by louismariegaborit** [api-platform/core#5094]
We works on updating ApiPlatform to 2.7 with the `metadata_backward_compatibility_layer` flag to `false`.
We have an error `Provider not found on operation "%s"` when we call the function getResourceFromIri on a legacy ApiResource that have a custom DataProvider.

Shouldn't the new IriConverter be able to call either the CallableProvider or the ChainItemDataProvider in 2.7 as a bridge to use legacy ApiResource is still available without the backward compatibility layer?

It's a problem when we add an iri of this resource in a payload of a parent resource.

**Comment by soyuka** [comment]
No, if you're not using the backward compatibility layer you need to use a State\ProviderInterface

**Comment by louismariegaborit** [comment]
So, I have to change my legacy ApiResource to new ApiResource to use the new interface State\ProviderInterface or I can use this interface with legacy ApiResource ? When I read the new ReadListener, I think it's not possible.  

I am lost in the perimeter covered by the backward compatibility layer to false.  

That I understand, it's that the backward compatibility layer to false keep a bridge to the old ApiResource and so DataProvider and DataPersister. When I call a GET item operation with a custom DataProvider, it works. But when we have a payload that include an iri to an old ApiResource. The new IriConverter, called by AbstractItemNormalizer don't works because it can't call DataProvider.

**Comment by soyuka** [comment]
Using the backward compatibility layer you have access to old data providers and the old resource system. You can also transform your resources to the new `ApiPlatform\Metadata\ApiResource` and transform your providers. (uses the old ReadListener)

When **not** using the backward compatibility layer (means setting that to `false` explicitly on `2.7` or using `3.0`) you don't have access to these old interfaces, therefore the old data provider doesn't work anymore.  (uses the new ReadListener)

**Comment by louismariegaborit** [comment]
It's not that I can read on the [upgrade guide](https://api-platform.com/docs/core/upgrade-guide/#i-want-to-try-the-new-metadata-system).

What I understand : 
backward_compatibility to false can only access to old metadata and old interface. New ApiResource are not available.
backward_compatibility to true give access to the new metadata and new interface but keep a bridge to old ApiResource.

With backward_compatibility to true, I have no problem. But with false, when I have an old ApiResource with Post operation and a payload with embedded relation, the denormalizer calls only the new IriConverter that is only able to call a provider and, so, only new ApiResource.

That's why I suggested the PR.

**Comment by soyuka** [comment]
We're probably missing this information, old providers won't work with the disabled flag. It's very hard to handle old and new layers together. The best is to update your providers.

**Comment by louismariegaborit** [comment]
I don't understand why you wouldn't resolve this problem.
It's very hard to upgrade an application from 2.6 to 3.0 when you have multiples DataProviders/DataPersisters. 
The backward compatibility was a very interesting solution to upgrade progressively and continue to develop features with the new Metadata and interfaces... 😏
