### ISSUE TITLE
Failed to denormalize attribute \"publicationDate\" value for class \"App\\Entity\\Book\"

### ISSUE THREAD

**Issue by baudelotphilippe** [api-platform/core#5098]
**API Platform version(s) affected**: 3.0

If I follow the tutorial at this point : 
{
  "isbn": "9781782164104",
  "title": "Persistence in PHP with the Doctrine ORM",
  "description": "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM.",
  "author": "Kévin Dunglas",
  "publicationDate": "2013-12-01"
}

=>
curl -X 'POST' \
  'https://localhost/books' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "isbn": "9781782164104",
  "title": "Persistence in PHP with the Doctrine ORM",
  "description": "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM.",
  "author": "Kévin Dunglas",
  "publicationDate": "2013-12-01"
}'

I have a 400

{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Failed to denormalize attribute \"publicationDate\" value for class \"App\\Entity\\Book\": Expected argument of type \"?DateTimeImmutable\", \"DateTime\" given at property path \"publicationDate\".",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/app/vendor/symfony/serializer/Exception/NotNormalizableValueException.php",
      "line": 31,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Exception",
      "short_class": "NotNormalizableValueException",
      "class": "Symfony\\Component\\Serializer\\Exception\\NotNormalizableValueException",
      "type": "::",
      "function": "createForUnexpectedDataType",
      "file": "/srv/app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 413,
      "args": [
        [
          "string",
          "Failed to denormalize attribute \"publicationDate\" value for class \"App\\Entity\\Book\": Expected argument of type \"?DateTimeImmutable\", \"DateTime\" given at property path \"publicationDate\"."
        ],
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "array",
          [
            [
              "string",
              "unknown"
            ]
          ]
        ],
        [
          "null",
          null
        ],
        [
          "boolean",
          false
        ],
        [
          "integer",
          0
        ],
        [
          "object",
          "Symfony\\Component\\PropertyAccess\\Exception\\InvalidArgumentException"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "AbstractObjectNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/srv/app/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 208,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ],
            "api_denormalize": [
              "boolean",
              true
            ],
            "cache_key": [
              "string",
              "0a89ba1bc5ff20ca15a598f2972fd6ef"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Serializer",
      "short_class": "AbstractItemNormalizer",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/srv/app/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 139,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ],
            "api_denormalize": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\JsonLd\\Serializer",
      "short_class": "ItemNormalizer",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/srv/app/vendor/symfony/serializer/Debug/TraceableNormalizer.php",
      "line": 80,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Debug",
      "short_class": "TraceableNormalizer",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/srv/app/vendor/symfony/serializer/Serializer.php",
      "line": 238,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "denormalize",
      "file": "/srv/app/vendor/symfony/serializer/Serializer.php",
      "line": 151,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "deserialize",
      "file": "/srv/app/vendor/symfony/serializer/Debug/TraceableSerializer.php",
      "line": 65,
      "args": [
        [
          "array",
          {
            "isbn": [
              "string",
              "9781782164104"
            ],
            "title": [
              "string",
              "Persistence in PHP with the Doctrine ORM"
            ],
            "description": [
              "string",
              "This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM."
            ],
            "author": [
              "string",
              "Kévin Dunglas"
            ],
            "publicationDate": [
              "string",
              "2013-12-01"
            ]
          }
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Debug",
      "short_class": "TraceableSerializer",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableSerializer",
      "type": "->",
      "function": "deserialize",
      "file": "/srv/app/vendor/api-platform/core/src/Symfony/EventListener/DeserializeListener.php",
      "line": 78,
      "args": [
        [
          "string",
          "{\n  \"isbn\": \"9781782164104\",\n  \"title\": \"Persistence in PHP with the Doctrine ORM\",\n  \"description\": \"This book is designed for PHP developers and architects who want to modernize their skills through better understanding of Persistence and ORM.\",\n  \"author\": \"Kévin Dunglas\",\n  \"publicationDate\": \"2013-12-01\"\n}"
        ],
        [
          "string",
          "App\\Entity\\Book"
        ],
        [
          "string",
          "jsonld"
        ],
        [
          "array",
          {
            "operation_name": [
              "string",
              "_api_/books.{_format}_post"
            ],
            "operation": [
              "object",
              "ApiPlatform\\Metadata\\Post"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\Book"
            ],
            "skip_null_values": [
              "boolean",
              true
            ],
            "iri_only": [
              "boolean",
              false
            ],
            "request_uri": [
              "string",
              "/books"
            ],
            "uri": [
              "string",
              "https://localhost/books"
            ],
            "input": [
              "null",
              null
            ],
            "output": [
              "null",
              null
            ],
            "api_allow_update": [
              "boolean",
              false
            ],
            "debug_trace_id": [
              "string",
              "635a41186a705"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Symfony\\EventListener",
      "short_class": "DeserializeListener",
      "class": "ApiPlatform\\Symfony\\EventListener\\DeserializeListener",
      "type": "->",
      "function": "onKernelRequest",
      "file": "/srv/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 115,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 230,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "callListeners",
      "file": "/srv/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 59,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/app/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 153,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 129,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\RequestEvent"
        ],
        [
          "string",
          "kernel.request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/srv/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 75,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/app/vendor/symfony/http-kernel/Kernel.php",
      "line": 202,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/app/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php",
      "line": 35,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Runtime\\Runner\\Symfony",
      "short_class": "HttpKernelRunner",
      "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
      "type": "->",
      "function": "run",
      "file": "/srv/app/vendor/autoload_runtime.php",
      "line": 29,
      "args": []
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "require_once",
      "file": "/srv/app/public/index.php",
      "line": 5,
      "args": [
        [
          "string",
          "/srv/app/vendor/autoload_runtime.php"
        ]
      ]
    }
  ]
}

How can I fix it ?
Tanks

**Comment by soyuka** [comment]
Issue is not readable. Date has to have the correct format.

**Comment by baudelotphilippe** [comment]
Well, thanks to close this issue without proposition to explain or fix it.

I know that there is a problem with the format of the date. 
I followed your tutorial : https://api-platform.com/docs/distribution/#introduction with the Docker solution.
And it doesn't work.
