### ISSUE TITLE
[2.x] Call non-existing object returns 500

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#510]
When I call `GET /callers/42` (where 42 does not exist in database), it returns a 500 instead of a 404. This is due to serialization of a non-existing object.

I think the issue can be related to [`ItemDataProvider::getItem` method](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L92) which calls `EntityManager::getReference` method, but no validation is triggered to check if the related object exists (I guess `getReference` method only returns a reference of an object whatever it exists or not).

**Comment by dunglas** [comment]
```php
        if (!$fetchData || $manager instanceof EntityManagerInterface) {
            return $manager->getReference($resourceClass, $identifiers);
        }
````

Should be

```php
        if (!$fetchData && $manager instanceof EntityManagerInterface) {
            return $manager->getReference($resourceClass, $identifiers);
        }
```
