### ISSUE TITLE
[2.7] DTO not a resource error

### ISSUE THREAD

**Issue by metaclass-nl** [api-platform/core#5103]
**API Platform version(s) affected**: 2.7.2 with (metadata_backward_compatibility_layer: true), using symfony v6.0.14, PHP 8.16. Not present in 3.0 so i guess it will not be fixed. By reporting it anyway i hope to save other developers that (potentially) run into this problem some time. 

**Description**  
Hours operation get_day_report results in 
400 Error: Bad Request
`{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "No resource class found for object of type \"App\\Model\\DayTotalsPerEmployee\".",`
(..)

[walkback](https://github.com/metaclass-nl/tutorial-api-platform/files/9792380/tutorial.issue.2.walkback.txt)

**How to reproduce**  
Install https://github.com/metaclass-nl/tutorial-api-platform/, work through the api branches of chapters 1-10 to apply db migrations and datafixtures and to add packages and bundles. Arrived in branch chapter10-api create and check out a new branch, back in git history (reset cursor, mode: hard) to revision #c5a609c356eefdec7360a865c92dd2a1c48a7e7f,
run composer update,
Get a token by: 
```shell
curl -X POST -H "Content-Type: application/json" https://localhost/authentication_token -d '{"email":"d.peters@leiden.nl","password":"d.peters_password"}' -k
```
Test the colletion operation get_day_report on the Hours resource with start[after]=2019-01-01.

**Possible Solution**  
See [Issue 2 on the tutorial](https://github.com/metaclass-nl/tutorial-api-platform/issues/2)

**Additional Context**  
See the [readme.md of branch chaper9-api of the tutorial](https://github.com/metaclass-nl/tutorial-api-platform/blob/chapter9-api/README.md)

**Comment by soyuka** [comment]
This is weird though, have you find out the where? and probably also have a stack trace? 

If it not being present in 3.0 doesn't disturb you I guess it's fine ? \0/

**Comment by metaclass-nl** [comment]
[Issue 2 on the tutorial](https://github.com/metaclass-nl/tutorial-api-platform/issues/2) identifies the code that i think causes it. Clicking on the walkback link in the description above should download a walkback. 

It doesn't disturb me any more, i just migrated ;-) (the tutorial is now happily running on 3.0). Thanks for asking - and the entire team thanks for 3.0!
