### ISSUE TITLE
Wrong error message on invalid value during denormalization of relation

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#518]
Suppose we pass a non-string non-object to a not writable relation, the error message is:
> Nested objects for attribute "%s" of "%s" are not enabled. Use serialization groups to change that behavior.

Which is not helpful because it's misleading.

**Comment by Simperfit** [comment]
I've had this error passing directly the uid to the relation of an entity.

What should we say ?

`Nested objects for attribute "%s" of "%s" may not be enabled or you passed the wrong type of argument. Please check that you have passed a either a string or an object.`

**Comment by teohhanhui** [comment]
We should probably add a check so that we can write more helpful error messages.
