### ISSUE TITLE
Custom operation  returns wrong @id at normalizer based on uriTemplate

### ISSUE THREAD

**Issue by xavierrr1** [api-platform/core#5180]
Hi everyone,
As far as I remember this is my first support question, so please, forgive me for my mistakes.
I'm updating one of my projects from 2.6 to 3.0.
I have a Reserva (booking) entity with a custom operation as follow:
`new Put(uriTemplate: '/reservas/{id}/cancelar', security: "is_granted('ROLE_USUARIO')",
		input: CancelarReservaInput::class, name: 'cancelar_reserva', processor: CancelarReservaTransformer::class)`

I'm using the new State Processors to receive an input dto and return a Reserva object. The problem is that when it's serialized for the response the [@Id] generated in src/JsonLd/Serializer/ItemNormalizer.php at the following lines:
` if ($iri = $this->iriConverter->getIriFromResource($object, UrlGeneratorInterface::ABS_PATH, $context['operation'] ?? null, $context)) {
            $context['iri'] = $iri;
            $metadata['@id'] = $iri;
        }`
In the case of this operation $iri goes to "/reservas/12345/cancelar" instead of "/reservas/12345".
If i remove the Operation and the $context from the getIriFromResource call, then it resolves ok.
I don't know if I'm missing something at the custom operation definition.
Thank you in advance.

**Comment by xavierrr1** [comment]
Just in case someone arrives here for the same problem.
If you set output: Reserva::class, then it will work as expected.
The documentation on how to use this new way of setting custom operations is a bit short. As far as I read, ouput only should be used with a provider in a read operation.

**Comment by soyuka** [comment]
we take the first operation in your list maybe just reorder them
