### ISSUE TITLE
Symfony 5.4 ApiPlatform POST request body is always empty

### ISSUE THREAD

**Issue by pushkidman** [api-platform/core#5181]
Been struggling for 4 hours.

Unfortunately, Symfony docs only contains most basic examples and googling only gives solutions for old Symfony versions.

I have created an API endpoint with Symfony 5.4 which works perfectly via Postman.

However, trying to cover it with a test using `ApiPlatform` ends up with request being totally empty as it reaches the endpoint.

`var_dump($request->request);` at the start of the endpoint code gives me (does not happen with Postman) 
```
object(Symfony\Component\HttpFoundation\InputBag)#109 (1) {
  ["parameters":protected]=>
  array(0) {
  }
}
```

when trying to run this test:
```
use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;

class PropertyTest extends ApiTestCase
{
    public function testCreatePropertyValidNoParent(): void
    {
        $name = 'Test Property ' . uniqid();

        $payload = [];
        $payload['name'] = $name;

        $response = static::createClient()->request(
            'POST',
            '/api/property',
            [
                'headers' => ['Content-Type' => 'multipart/form-data'],
                'body'    => $payload
            ]
        );

        $this->assertResponseIsSuccessful();
    }
}
```

Replacing `body` with `json` produced the same result

Any ideas?

Was able to work around the issue by passing `parameters` like that:
```
$response = static::createClient()->request(
            'POST',
            '/api/property',
            [
                'headers' => ['Content-Type' => 'multipart/form-data'],
                'body'    => $payload,
                'extra' => [
                    'parameters' => $payload
                ]
            ]
        );
```
which seems like a stupid solution though...

Is there a proper way or is this expected to work like that?

**Comment by norkunas** [comment]
Did you try to use `static::createClient()->jsonRequest('POST', '/api/property', $payload)` ?

**Comment by soyuka** [comment]
Had the issue also but I don't remember what causes this, probably not related to our code. I was getting the body and json decoded it to get the body :/.

I don't think that this is related to how the ApiTestCase works look on symfony's http client issues maybe you'll find something there.
