### ISSUE TITLE
[DTO] Post Input-Processor Not Working

### ISSUE THREAD

**Issue by NeuralFramework** [api-platform/core#5183]
Hi everyone

I have a problem when creating a new record using **DTO** and Processor, when sending the data the following message is returned: **_Unable to generate an IRI for the item of type "App\\Entity\\Client\""_**

I have followed the process in the documentation but it doesn't work: https://api-platform.com/docs/core/dto/

This is the code I generated:

**DTO**

![Dto](https://user-images.githubusercontent.com/2681400/201506929-b88f6f93-e5c8-4716-9699-3940092e6812.png)

**PROCESSOR**

![Processor](https://user-images.githubusercontent.com/2681400/201506939-b0ceb58c-feae-44aa-9eab-229756290ef9.png)

**ENTITY**

![Entity](https://user-images.githubusercontent.com/2681400/201506959-eaa948c3-f15a-423b-b83d-c7bd81a7d13f.png)

**RESPONSE ERROR**

{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Unable to generate an IRI for the item of type \"App\\Entity\\Client\"",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php",
      "line": 151,
      "args": []
    },
    {
      "namespace": "ApiPlatform\\Symfony\\Routing",
      "short_class": "IriConverter",
      "class": "ApiPlatform\\Symfony\\Routing\\IriConverter",
      "type": "->",
      "function": "getIriFromResource",
      "file": "/var/www/vendor/api-platform/core/src/Symfony/EventListener/WriteListener.php",
      "line": 104,
      "args": [
        [
          "object",
          "App\\Entity\\Client"
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Symfony\\EventListener",
      "short_class": "WriteListener",
      "class": "ApiPlatform\\Symfony\\EventListener\\WriteListener",
      "type": "->",
      "function": "onKernelView",
      "file": "/var/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 115,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/var/www/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 230,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "callListeners",
      "file": "/var/www/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 59,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/var/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 153,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"
        ],
        [
          "string",
          "kernel.view"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/var/www/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 168,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"
        ],
        [
          "string",
          "kernel.view"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/var/www/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 75,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/var/www/vendor/symfony/http-kernel/Kernel.php",
      "line": 202,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/var/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php",
      "line": 35,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Runtime\\Runner\\Symfony",
      "short_class": "HttpKernelRunner",
      "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
      "type": "->",
      "function": "run",
      "file": "/var/www/vendor/autoload_runtime.php",
      "line": 29,
      "args": []
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "require_once",
      "file": "/var/www/public/index.php",
      "line": 5,
      "args": [
        [
          "string",
          "/var/www/vendor/autoload_runtime.php"
        ]
      ]
    }
  ]
}

`

Please help

**Comment by NeuralFramework** [comment]
**Versions**

**_Api-Platform:_** V3.0.3
**_Symfony:_** V6.1.7
**_PHP:_** V8.1.12

**Comment by soyuka** [comment]
not persisting the client == no id to retrieve 
please this is for bugs use other channels for support
