### ISSUE TITLE
Problem with custom variables in query / uriTemplate

### ISSUE THREAD

**Issue by bizley** [api-platform/core#5184]
**API Platform version(s) affected**: 3.0.3

**Description**  
If you set custom `uriTemplate` for an operation with non-identifiers as variables you will get 404 or 500.

**How to reproduce**  
Add operation with template similar to:
```
uriTemplate: '/photos/{uuid}/resize/{width}/{height}',
```
where `{uuid}` is an UUID identifier.

As I can see additional variables are "resolved" as identifiers for the relations in the data provider resulting in query broken or yielding no results at all.

**Possible Solution**  
I have made something I called NoExtraLinkProvider which is basically `ApiPlatform\Doctrine\Orm\State\ItemProvider` with additional code:

```php
if ($operation instanceof HttpOperation && array_key_exists('uuid', $uriVariables)) {
    $uriVariables = ['uuid' => $uriVariables['uuid']];
    $operation = $operation->withUriVariables(['uuid' => $operation->getUriVariables()['uuid']]);
}
```

which removes any uriVariables added automatically by the framework. With help of that I can get the Photo resource by `{uuid}` and pass additional `{with}` and `{height}` to my controller.

But this does not help with collection operations (without `{uuid}`, different resource but similar problem, like `/resources/search/{search}`) and I don't know what to do here.

**Additional Context**  
I did not find how to do this in v3, in v2 it worked without any problems. Maybe I'm doing something wrong (most probably) or maybe there is something missing in this beautiful framework. Please help or point me to the proper place to find help. Thank you.

**Comment by soyuka** [comment]
Side note: there's an issue with URI Variables beeing overriden even though it's setup by the user when `uriTemplate` contains more variables then the defined uri variables.

**Comment by bizley** [comment]
Thank you, I see your temp fix proposal is basically the same idea I had. Also side note - I don't rely on providing any variable there since the main identifier variable (`uuid` in my case) is automatically set; this might be the source of the problem, I would happy set it manually in order to not auto-set the rest of them from uriTemplate.

**Comment by soyuka** [comment]
Actually when you set something inside the metadata yourself it should not get overridden. Here we've a bug where in API Platform 3 we read your `uriTemplate` (`photos/{uuid}/resize/{width}/{height}`) and we find out there are 3 variables. We then override your configuration to add the ones that you didn't set up. This is definitely wrong and they should be left untouched if specified in the first place. This means that by setting this:

```
#[Get(uriVariables: ['uuid'])]
```

API Platform shouldn't be aware of height and width at all (even though its not perfect and I'd rather suggest creating your own Provider that handles the 3 variables).

**Comment by soyuka** [comment]
this was way harder then it should've been haha. A configuration with wrong URI variables will now let the Iri Converter throw when generating an IRI. 
Solutions available:
- add uriVariables configuration 
- decorate the Iri Converter
