### ISSUE TITLE
Inconsistency between YAML and attributes with output: false

### ISSUE THREAD

**Issue by temp** [api-platform/core#5185]
**API Platform version(s) affected**: 3.0.3

**Description**  
output: false is not honored in an operation that is loaded via YAML. It works fine with an ApiResource attribute.

**How to reproduce**  
Create a resource with a post operation, that has `output: false`, via YAML and another via attribute.
With YAML the post will have a response body, with the attribute it will be empty (as expected)

**Possible Solution**  
There are 2 possible errors, one in `ApiPlatform\Metadata\Extractor\YamlResourceExtractor::buildBase()`, input and output are defined as strings for phpize(), should be 'bool|string'. Other error is in `ApiPlatform\Metadata\Extractor\ResourceExtractorTrait::phpize()` itself, since the value is already a bool, it is not recognized and transformed into an empty string. Add `is_bool($resource[$key]) || \in_array...` inside the bool|string case worked fine for us.

**Comment by soyuka** [comment]
I'd love a PR if you already have the fix thanks!

**Comment by temp** [comment]
👍
