### ISSUE TITLE
[GraphQL][Serialization]: Child-Items that are already present get removed

### ISSUE THREAD

**Issue by develth** [api-platform/core#5189]
**API Platform version(s) affected**: 3.0.3 | 3.0.4

**Description**  
I have an Model that get its Data via an StageProvider via an external API. It Contains an array of a Model that also gets feed through this external API.
Those Models are not managed by Doctrine and so have no Mapping configured.

When doing query on those, i already have the Child-Items from the external API and filled them via the Stage Provider. But during Serialization they got removed, caused by the [ItemNormalizer:normalizeCollectionOfRelations](https://github.com/api-platform/core/blob/c62f66cecdad50efcf277c2206e2d9222a031c72/src/GraphQl/Serializer/ItemNormalizer.php#L101)

For sure i could then Fetch them via the other Provider, too - but that would be a lot of unnecassary calls.

Is there an "easy" way to solve it?

**Comment by soyuka** [comment]
Interesting but I'm pretty sure that we have a test case for these, can you provide some more details? Are there groups on your resources?

**Comment by develth** [comment]
I did not found a test regarding that @soyuka 
If you could tell me which test you mean i can check if that matches my case and then i have a look. 

> Are there groups on your resources?
Yes there are Groups, but they are not checked for that. 

The serialization after fetching already existing items again works great, the output is then as expected.
But through the linked code we have to refetch data.

Thanks!

**Comment by soyuka** [comment]
Probably that @alanpoulain has an idea of what's going on here ?

**Comment by develth** [comment]
@soyuka coming back to this staled issue, because i´m on that topic again. 
Is there a solution for it?

**Comment by develth** [comment]
Given following example:

Query my api that collect data from an external apI:

```
query doQueryExternalDatas() {
  externalDatas() {
      edges{
          node{
              id
              name
              relatedDataOfExternalDatas{
                  edges{
                      node{
                            id
                            status
                      }
                  }
              }
          }
      }    
  }
}
```

Within my provider is have all Data and fill my `ExternalData` and also my `RelatedExternalData` and assign it to the `relatedDataOfExternalDatas` array of `ExternalData`.
But the [ItemNormalizer:normalizeCollectionOfRelations](https://github.com/api-platform/core/blob/c62f66cecdad50efcf277c2206e2d9222a031c72/src/GraphQl/Serializer/ItemNormalizer.php#L101) clears it during serialization

**Comment by develth** [comment]
IMHO this part also sometimes already available data on entites where a new query would not be needed what costs performance

**Comment by reech-florian** [comment]
Hello @develth have you found a solution to your problem? I have exactly the same problem as you.

**Comment by develth** [comment]
Hey @reech-florian can´t answer, sorry. Too long ago. I think i solved it through an CacheAdapater i added to one of the stages that checks a hash of the orignal request und some other timestamps and added it, if it exists, to prevent multiple request to external db
