### ISSUE TITLE
v2.7.4 QueryNameGeneratorInterface does not exist in AbstractFilter.php

### ISSUE THREAD

**Issue by nayzo** [api-platform/core#5197]
**API Platform version(s) affected**: 2.7.4

**Description**  
The `AbstractFilter.php` class (cf: `src/Core/Bridge/Doctrine/Orm/Filter/AbstractFilter.php`) is requiring the `QueryNameGeneratorInterface` interface **which does not exist** (`ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface`) !

**Comment by oleg-andreyev** [comment]
The bad thing is that PhpStorm does not understand it...
`class_alias` approach that Symfony is using is better.

**Comment by soyuka** [comment]
We do class aliases, but yeah I know about PhpStorm but as it is a hack to trick PHP class system it's hard to cover. Don't worry too much this helped us to not break existing code (trick comes from doctrine code actually) and this is covered in 3.x.
