### ISSUE TITLE
Wrong route match if routePrefix is defined

### ISSUE THREAD

**Issue by usu** [api-platform/core#5203]
**API Platform version(s) affected**: 3.0.4

**Description**  
As of now, `routePrefix` is not included in operation name (which also serves as the symfony route name). This can lead to route name conflict and hence to wrong route matches, if multiple resources are defined on the the same resource class.

**How to reproduce**  
1. Specify a resource class with 2 ApiResources, one of them with a `routePrefix`:

```php
#[ApiResource(
    operations: [
        new Get(
            security: 'true'
        ),
        new GetCollection(
            security: 'true'
        ),
)]
#[ApiResource(
    operations: [
        new Get(
            security: 'false'
        ),
        new GetCollection(
            security: 'false'
        ),
    ],
    routePrefix: '/admin'
)]
class User {
}
```

2. Load '/admin/users'

_Expected result:_ 403 Forbidden (matching GetCollection operation of the second ApiResource)

_Received result:_ 200 (matching GetCollection operation of first ApiResource). Confusingly, the individual IRIs are still prefixed with /admin
```json
{
  "_links": {
    "self": {
      "href": "/admin/users"
    },
    "items": [
      {
        "href": "/admin/users/1234"
      },
      {
        "href": "/admin/users/5678"
      }
    ]
  },
  "totalItems": 2
}
```

**Possible Solution**  
Include `routePrefix` in operation name

**Additional context**
- In SwaggerUI, only the /admin/users endpoint are shown (see screenshot below)
- The routes of the first ApiResource seems to overwritten in Symfony router. Loading `/users` leads to a "404 No route found exception"

SwaggerUI:
![Screenshot 2022-11-20 073837](https://user-images.githubusercontent.com/449555/202889721-86cecf5e-7220-47d5-9148-876c9d7a16dd.png)

Route Match Log:
![Screenshot 2022-11-20 074206](https://user-images.githubusercontent.com/449555/202889727-945179e2-54b0-4df7-b20f-8ca21db577a8.png)

**Comment by usu** [comment]
Hi @soyuka. Could this issue be reopened? Not sure if you saw my comment directly in the PR https://github.com/api-platform/core/pull/5208#issuecomment-1328007551, but I think this is not yet resolved.

**Comment by divine** [comment]
@soyuka sorry to bump, this can be closed as PR has been merged.

Thanks!
