### ISSUE TITLE
Serializer with null values on API Platform 3

### ISSUE THREAD

**Issue by FabienPapet** [api-platform/core#5210]
**API Platform version(s) affected**: 3.0.4

**Description**  
Serializer does not serialize null values. I tried to serialize with and without groups, but the problem does not look to be there. 

**How to reproduce**  

I created a reproducer project, we just need to clone it, configure a database (postgres). There is a failing test in the /tests directory.

https://github.com/FabienPapet/serialization-bug-apip3

**Possible Solution**  

n/a

**Additional Context**  

Here's an example on what's failing, the `telephone` property is null in Customer#1

```json
{
  "@context": "/api/contexts/Customer",
  "@id": "/api/customers",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/customers/1",
      "@type": "Customer",
      "id": 1,
      "name": "foo"
    },
    {
      "@id": "/api/customers/2",
      "@type": "Customer",
      "id": 2,
      "name": "bar",
      "telephone": "0147200001"
    }
  ],
  "hydra:totalItems": 2
}
```

**Comment by mab05k** [comment]
Have you tried this? https://stackoverflow.com/questions/59314728/allowing-null-value-in-json-with-api-platform#59856013

Add `skip_null_values: false` to your ApiResource's normalization_context configuration.

**Comment by FabienPapet** [comment]
Nope, I'm just upgrading from a 2.6 to a 3.0 and I did not need that configuration anywhere before :/ . Is it mandatory to have it now ?

**Comment by mab05k** [comment]
Found this:
https://github.com/api-platform/core/blob/52a72743028d78255c14870b80eeb195e91740d8/CHANGELOG.md#300-beta1

`Serializer: skip_null_values now defaults to true`

**Comment by soyuka** [comment]
3.0.0-beta.1 changelog
