### ISSUE TITLE
assertMatchesResourceCollectionJsonSchema throws error when enable_max_depth is set to true

### ISSUE THREAD

**Issue by ciekals11** [api-platform/core#5211]
**API Platform version(s) affected**: 3.0

**Description**  
when testing with `assertMatchesResourceCollectionJsonSchema` on entity that have set in normalizationContext `enable_max_depth` to `true` this assert throws error:
```
hydra:member[6].item1[0].item2: String value found, but an object is required
``` 

**How to reproduce**  
Create entity that container another entity that contains another entity and set `enable_max_depth` to `true`
Then create test that uses `assertMatchesResourceCollectionJsonSchema`

**Comment by soyuka** [comment]
This got fixed I think
