### ISSUE TITLE
ResponderViewListener should call SerializerInterface::serialize instead of NormalizerInterface::normalize

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#522]
The selection of which normalizer(s) to use should be left up to the serializer.

**Comment by dunglas** [comment]
Anyway it should normalize. The JSON encoding must be left to the `Response` class.

**Comment by teohhanhui** [comment]
Why can't it be done the same way as https://github.com/api-platform/core/blob/9870182972fc50316c5a010dc7022d67cd68f6ea/tests/Fixtures/TestBundle/EventListener/XmlResponderViewListener.php#L85-L89

I'm not sure what's the purpose of the JsonLd `Response` class...

**Comment by teohhanhui** [comment]
I don't see why we should use `JsonResponse` when the Serializer can already handle it (better).

**Comment by dunglas** [comment]
Fixed during the refactoring of event listeners.
