### ISSUE TITLE
v2.7.4 Deprecated warning for ResourceMetadataFactoryInterface filling logs

### ISSUE THREAD

**Issue by finnef** [api-platform/core#5224]
API Platform version affected: 2.7.4
Currently working in a SF 5.4 project, so cannot yet upgrade to 3.0

When doing API requests the core of API platform 2.7.4 uses a lot of ResourceMetadataFactoryInterface calls, which trigger a deprecation notice. I have over a 100MB of deprication log files a day, filled with

"php.INFO: User Deprecated: Since api-platform/core 2.7: Use "ApiPlatform\Metadata\Resource\Factory\ResourceMetadataCollectionFactoryInterface" instead of "ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface". {"exception":null} {"client_ip":"127.0.0.1","method":"GET"}"

Why did you deprecate an interface in v2.7 when all development is focussing on v3? Now the deprecation will probably never be fixed in v2.7. I found over 260 usages in vendor/api-platform/core.

I would suggest 
- no longer triggering a deprecation warning (ideally only for internal usage) of the deprecated interface
- or fix the deprecations

**Comment by soyuka** [comment]
use monolog to redirect logs to elsewhere or disable them I don't think that in production they should go through your logs

also maybe related https://github.com/symfony/symfony/issues/35575#issuecomment-600544141

**Comment by kovinet** [comment]
In my case these logs go trough also in production. @finnef did you manage to disable them and would you mind sharing how?

I have basically default `prod/monolog.yaml` and I didn't uncomment following:

```yaml
        # Uncomment to log deprecations
        #deprecation:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        #deprecation_filter:
        #    type: filter
        #    handler: deprecation
        #    max_level: info
        #    channels: ["php"]
```
