### ISSUE TITLE
Inconsistent ID with PUT operation in API Platform 3.0

### ISSUE THREAD

**Issue by fabienlem** [api-platform/core#5226]
**API Platform version(s) affected**: 3.0

**Description**  

With custom PUT operation, the ID of the resourse is altered in the endpoint response.

My use case is the following:

I have many PUT endpoints on the same API resource with different paths and denormalization contexts.

```
        new Put(
            uriTemplate: '/my_resource/{uuid}/aaa',
            denormalizationContext: [
                'groups' => [
                    'edit_aaa',
                ],
            ],
            ...
        ),
        new Put(
            uriTemplate: '/my_resource/{uuid}/bbb',
            denormalizationContext: [
                'groups' => [
                    'edit_bbb',
                ],
            ],
            ...
        ),
        ...
```

**How to reproduce**  

In Mathias' repository, replace the POST operation line 50 by a PUT operation.

https://github.com/mtarld/apip-ddd/blob/main/src/BookStore/Infrastructure/ApiPlatform/Resource/BookResource.php#L50

In the API response, the @id is then inconsistent:

![image](https://user-images.githubusercontent.com/19775001/199926642-8a1b4bee-7d1f-402c-ab00-cbad4656fa57.png)

Thank you!

**Comment by soyuka** [comment]
It always take the first operation or you need to specify the one you want with `itemUriTemplate`. However I must say that this looks quite wrong from a REST point of view.
