### ISSUE TITLE
Customizing serializer context (e.g. json_encode_options)

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#523]
Currently there is no extension point for customizing serializer context.

**Comment by theofidry** [comment]
Can't you already do that by overriding the default json encoder service?

**Comment by teohhanhui** [comment]
Uhh, yes. Of course you could... But that's without taking advantage of the customizability provided through the `$context`.

**Comment by theofidry** [comment]
That's what I mean: if you want to inject a set of parameters to the context, you can decorate/extend the json(ld) encoder to inject those parameters to the context for the de/encoding.

But I guess it would make sense to enable that on our end.

**Comment by teohhanhui** [comment]
We could put this in the `ResourceMetadata` attributes / operation attributes. What do you think?

**Comment by dunglas** [comment]
Closing, there is now an extension point for that: https://github.com/api-platform/core/blob/master/src/Serializer/SerializerContextBuilder.php

**Comment by teohhanhui** [comment]
I'd argue that `$context['json_encode_options']` should be used instead of https://github.com/api-platform/core/blob/9c8fe81988cc0412060016bc5992319e7d14ad21/src/Serializer/JsonEncoder.php#L35-L38
