### ISSUE TITLE
[Route Names] API Route Naming Convention Changed from 2.6 to 3.0

### ISSUE THREAD

**Issue by gnito-org** [api-platform/core#5231]
**API Platform version(s) affected**: 3.0.x

**Description**  

In 2.6, the API routes for resource `Book` were named:

```
api_books_get_collection
api_books_post_collection
api_books_get_item
api_books_put_item
api_books_delete_item
```

In 3.0, the same routes are now named:

```
 _api_/book/{id}{._format}_get
 _api_/book{._format}_get_collection
 _api_/book{._format}_post
 _api_/book/{id}{._format}_put
 _api_/book/{id}{._format}_delete
 ```

Is this a bug, or is it an intentional change?

The new routes names are super ugly. Is there a setting to change them to something more palatable?

**Comment by Aerendir** [comment]
It is intended.

It is a placeholder that has to be substituted with the desired format.

https://api-platform.com/docs/core/

**Comment by gnito-org** [comment]
How does one substitute it with the desired format?

**Comment by gnito-org** [comment]
Just to be clear, I am not referring to API paths or URI templates.

I'm referring to the Symfony route name that you see when you run `./bin/console debug:router api`.

**Comment by Aerendir** [comment]
You simply call  _api_/book/{id}.json_get: it should work.

Yes, when you debug the router it gives you the URL with placeholders (and, in fact, you see {Id}

**Comment by gnito-org** [comment]
Precisely. I want to know if that route name format can be changed / substituted.

V2.6 used a [RouteNameGenerator](https://github.com/api-platform/core/blob/2.6/src/Bridge/Symfony/Routing/RouteNameGenerator.php) class, which is now absent from V3.0.

**Comment by soyuka** [comment]
you can use a `routeName` directly, we try to move away from Symfony. We had an issue in 2.6 where route names were conflicting. The best way to change every route names now would be to create a ResourceMetadataCollectionFactory and fixing that yourself there if needed.

**Comment by Aerendir** [comment]
@soyuka , "we try to move away from Symfony": can you explain better this phrase?

**Comment by soyuka** [comment]
We want to have less code that is hard linked to symfony which was the case in 2.6 for lots of things. For example here there is API Platform's operation name and Symfony's route name. The fact that these two are the same was a confusion for lots of users. You can customize anything just tell me what's the use case.

**Comment by soyuka** [comment]
If you want the logic behind the route name generator / operation name and that the default generation isn't a fit for you, create a ResourceMetadataCollectionFactory where you set your own defaults. 
You can inspire yourself from ours: https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php 

Note that if you set any value inside ApiResource or any Operation we won't replace it nor try to generate anything.
