### ISSUE TITLE
Cannot use ApiFilter() without ODM installed alongside ORM

### ISSUE THREAD

**Issue by SkipTheDragon** [api-platform/core#5233]
**API Platform version(s) affected**: 3.0.5

**Description**  
As the title states, I cannot use ApiFilter() without installing 'doctrine/mongodb-odm' package. I get an error if I add ` #[ApiFilter(SearchFilter::class, strategy: SearchFilterInterface::STRATEGY_EXACT)]` to any property or directly on the class itself.

**How to reproduce**  
Here is the exact class I'm using [Ticket.txt](https://github.com/api-platform/core/files/10097176/Ticket.txt),

**Possible Solution**  
Might have something to do with the changes for #5020. Also, installing 'doctrine/mongodb-odm' fixes the problem.

**Additional Context**  

I created the project using the Symfony CMD and installed api-platform later. 

The error I'm getting if I don't have 'doctrine/mongodb-odm' installed:

`
Attempted to load class "Type" from namespace "Doctrine\ODM\MongoDB\Types".
Did you forget a "use" statement for e.g. "phpDocumentor\Reflection\Type", "cebe\openapi\spec\Type", "Symfony\Component\Validator\Constraints\Type", "Symfony\Component\PropertyInfo\Type" or "Doctrine\DBAL\Types\Type"?
`

Stacktrace:

`
Symfony\Component\ErrorHandler\Error\ClassNotFoundError:
Attempted to load class "Type" from namespace "Doctrine\ODM\MongoDB\Types".
Did you forget a "use" statement for e.g. "phpDocumentor\Reflection\Type", "cebe\openapi\spec\Type", "Symfony\Component\Validator\Constraints\Type", "Symfony\Component\PropertyInfo\Type" or "Doctrine\DBAL\Types\Type"?
  at var/cache/dev/Container9nlEKMI/getAnnotatedAppEntityTicketApiPlatformDoctrineOdmFilterSearchFilterService.php:29
  at Container9nlEKMI\getAnnotatedAppEntityTicketApiPlatformDoctrineOdmFilterSearchFilterService::do(object(App_KernelDevDebugContainer), true)
     (var/cache/dev/Container9nlEKMI/App_KernelDevDebugContainer.php:442)
  at Container9nlEKMI\App_KernelDevDebugContainer->load('getAnnotatedAppEntityTicketApiPlatformDoctrineOdmFilterSearchFilterService.php')
     (vendor/symfony/dependency-injection/Container.php:383)
  at Symfony\Component\DependencyInjection\Container->getService('privates', 'annotated_app_entity_ticket_api_platform_doctrine_odm_filter_search_filter', 'getAnnotatedAppEntityTicketApiPlatformDoctrineOdmFilterSearchFilterService', true)
     (vendor/symfony/dependency-injection/Argument/ServiceLocator.php:43)
  at Symfony\Component\DependencyInjection\Argument\ServiceLocator->get('annotated_app_entity_ticket_api_platform_doctrine_odm_filter_search_filter')
     (vendor/api-platform/core/src/Api/FilterLocatorTrait.php:48)
  at ApiPlatform\OpenApi\Factory\OpenApiFactory->getFilter('annotated_app_entity_ticket_api_platform_doctrine_odm_filter_search_filter')
     (vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php:444)
  at ApiPlatform\OpenApi\Factory\OpenApiFactory->getFiltersParameters(object(GetCollection))
     (vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php:205)
  at ApiPlatform\OpenApi\Factory\OpenApiFactory->collectPaths(object(ApiResource), object(ResourceMetadataCollection), object(Paths), object(ArrayObject))
     (vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php:92)
  at ApiPlatform\OpenApi\Factory\OpenApiFactory->__invoke(array('base_url' => '/'))
     (src/OpenApi/JwtDecorator.php:17)
  at App\OpenApi\JwtDecorator->__invoke(array('base_url' => '/'))
     (vendor/api-platform/core/src/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php:45)
  at ApiPlatform\Symfony\Bundle\SwaggerUi\SwaggerUiAction->__invoke(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/shared/httpd/activator/ultimate-activator/vendor/autoload_runtime.php')
     (public/index.php:5)              
`
     
     
Composer Json contents:
     
     
`
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/core": "^3.0",
        "baileyherbert/envato": "^2.2",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.7",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.13",
        "lexik/jwt-authentication-bundle": "^2.16",
        "nelmio/cors-bundle": "^2.2",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.11",
        "symfony/asset": "6.1.*",
        "symfony/console": "6.1.*",
        "symfony/dotenv": "6.1.*",
        "symfony/expression-language": "6.1.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.1.*",
        "symfony/http-client": "6.1.*",
        "symfony/property-access": "6.1.*",
        "symfony/property-info": "6.1.*",
        "symfony/proxy-manager-bridge": "6.1.*",
        "symfony/runtime": "6.1.*",
        "symfony/security-bundle": "6.1.*",
        "symfony/serializer": "6.1.*",
        "symfony/twig-bundle": "6.1.*",
        "symfony/validator": "6.1.*",
        "symfony/yaml": "6.1.*"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.1.*"
        }
    },
    "require-dev": {
        "api-platform/schema-generator": "^5.1",
        "symfony/maker-bundle": "^1.47"
    }
}
`

**Comment by soyuka** [comment]
are you sure you had the ApiFilter namespace right? There is one for ODM and one for ORM

**Comment by SkipTheDragon** [comment]
Yea, that seems to be the problem. Looks like doctrine has both ODM and ORM classes inside their Core, and PHPStorm auto-imported the ODM one.

Thank you for your guidance.

**Comment by liaten** [comment]
I had the same problem with GraphQL:

Code:
![image](https://github.com/user-attachments/assets/ed49d875-e087-4398-93ab-bda5c5d922a7)

Problem:

![image](https://github.com/user-attachments/assets/817c25de-4239-42c8-8ee4-5166b727749f)

Solution: Changed ODM to ORM.

Thanks everyone!
