### ISSUE TITLE
[Performance] API Platform v3.0 is much slower than V2.6 by orders of magnitude

### ISSUE THREAD

**Issue by gnito-org** [api-platform/core#5236]
**API Platform version(s) affected**: 3.0.x

**Description**  

Has anyone done  performance testing on V3.0?

I'm getting truly worrying results.

I have a Symfony Command that creates and deletes an API resource in a loop that iterates 10 times. In other words, 10 POST and 10 DELETE API operations.

When run under V2.6, the command has a duration of +- 3.48 seconds, for an average of 0.348 seconds per iteration (one POST and one DELETE).

When run under V3.0, the command has a duration of +- 55.54 seconds, for an average of 5.55 seconds per iteration (one POST and one DELETE).

That is a huge performance difference.

I have a v2.6 branch of my app, and a v3.0 branch of the app, and here are the steps when running the tests:

- checkout the v2.6 branch of the app
- run `composer update` to install API Platform 2.6
- run the test command (takes 3.48 seconds)
- checkout the v3.0 branch of the app
- run `composer update` to install API Platform 3.0
- run the test command (takes 55.54 seconds)

Each time that `composer update` runs, it only says ` Upgrading api-platform/core (v2.6.8 => v3.0.5)` and `Downgrading api-platform/core (v3.0.5 => v2.6.8)`, and it removes and installs `fig/link-util`. No other packages are modified.

I've repeated this several times with exactly the same results. I've also reversed the order, running V3.0 first and then V2.6, with exactly the same results.

The database is exactly the same, the app is exactly the same, except for having StateProcessors and StateProviders instead of DataPersisters and DataProviders. The state processors and state providers contain the same code that was in the data persisters and data providers. The only other difference between the two branches of the app is the new ApiResource attribute format on the entities in the V3 branch.

The test command calls the same API endpoints with exactly the same parameters and data, and the state of the database is exactly the same.

In the current state I cannot run API Platform V3 in production. It will completely kill my app's performance.

**Comment by gnito-org** [comment]
As an additional test, I changed the API endpoint that is called in the Command.

In the previous test, the API endpoint uses a StateProcessor that decorates the built-in Doctrine processor, as per the [documentation](https://api-platform.com/docs/core/state-processors/#hooking-into-the-built-in-state-processors).

The API endpoint in the second test does not use a decorated state processor, and the resource has one less resource relation.

V2.6 results: duration 2.8 seconds, average 0.28 seconds per iteration.

V3.0 results: duration 6.0 seconds, average 0.6 seconds per iteration.

**Comment by Aerendir** [comment]
Just to say the obvious: may the problem be related to the generation of cache?

To exclude it, I would:

1. Delete the cache folder in var
2. Run the command the first time (to generate the cache)
3. Run the command the cons time to actually get the measurement

I would not use the console cache:clear command, but physically delete the folder.

**Comment by gnito-org** [comment]
I've run the command many times. It definitely is not caused by the cache.

**Comment by gnito-org** [comment]
Here are the Symfony Profiler Performance tab screenshots for both versions.

### Version 2.6

![V2_6_POST](https://user-images.githubusercontent.com/70450336/204166240-9a34a142-a148-479b-9e0d-e95bd33fe749.png)

### Version 3.0

![V3_0_POST](https://user-images.githubusercontent.com/70450336/204166241-e0756127-91b0-46d2-8304-72a44b88963d.png)

**Comment by acirulis** [comment]
Hi, please try following this comment/thread: https://github.com/api-platform/core/issues/4975#issuecomment-1253617780

**Comment by soyuka** [comment]
Hi, yes we did performances tests, on the last versions this is the diff 2.6 vs 3.0 for a READ operation: 

https://blackfire.io/profiles/compare/6bec923c-521f-426c-b7f1-1ab2fb962b80/graph 

The only PR we found that impacted the performances was https://github.com/api-platform/core/pull/4999 then fixed by #5100.

What version are you exactly on? @acirulis wasn't that corrected?

**Comment by gnito-org** [comment]
@acirulis Thank you, the [cache config](https://github.com/api-platform/core/issues/5236#issuecomment-1328654144) resolved the issue. Much appreciated. :pray:  

@soyuka I have already supplied the [version numbers](https://github.com/api-platform/core/issues/5236#issue-1465554114).

### V3.0 POST With [Caching Config](https://github.com/api-platform/core/issues/4975#issuecomment-1253617780)

![V3_0_POST_CACHE](https://user-images.githubusercontent.com/70450336/204271002-be0ed375-465e-4062-82f8-1c4d68125a48.png)

**Comment by soyuka** [comment]
Following: https://github.com/api-platform/core/issues/4975#issuecomment-1253617780
