### ISSUE TITLE
custom uriTemplate default variable value no longer works under 3.0.5 or 3.06

### ISSUE THREAD

**Issue by ovgray** [api-platform/core#5238]
**API Platform version(s) affected**: x.y.z
3.0.5, 3.0.6

**Description**  
I have an ApiResource with the following:

> #[ApiResource(
          operations: [
              new Get(
                  uriTemplate: '/participant_lists/{code}/calendar/{weeks}',
                  normalizationContext: ['groups' => ['calendar:read', 'name:read']],
                  name: 'get_participant_list_calendar',
                  provider: ParticipantListCalendarStateProvider::class
              ),
          ],
          uriVariables: ['code' => new Link(fromClass: ParticipantList::class, fromProperty: 'code')],
          defaults: ['weeks' => 26],
          requirements: ['weeks' => '\d+']
)]

Before 3.0.5, when I called  '/participant_lists/{code}/calendar`, my state provider's 'provide' function would receive this $uriVariables array:

> [
  "code" => "on"
  "weeks" => 26
] 

Under 3.0.5 or 3.0.6, it receives this $uriVariables array:

> [
  "code" => "on"
]

**Comment by acirulis** [comment]
Confirms that https://github.com/api-platform/core/issues/5234 was closed premature.

**Comment by soyuka** [comment]
Hi, this was working in 3.0.4 but it shouldn't have see https://github.com/api-platform/core/issues/5184.

In your case you forgot to declare `weeks` and we don't have any way of knowing that it should be checked for. Please specify another uri variable for the week:

```
uriVariables: ['code' => ..., 'week' => ...)], 
```

**Comment by ovgray** [comment]
@soyuka
Is there somewhere in the documentation that explains how to declare a uriVariable with anything other than a Link object?
How do I declare it to just be whatever is in the weeks variable in the custom uriTemplate?

**Comment by soyuka** [comment]
Yeah sorry it shouldn't have been working in the first place. For others coming here basically he did:

```
 uriVariables: ['code' => new Link(fromClass: ParticipantList::class, fromProperty: 'code'), 'week' => 'week'],
```

Where the later is a shortcut saying `week` is the `week` property of `self::class` and is an identifier. So if you call `IriConverter->getIriFromResource()` it should work.
