### ISSUE TITLE
Sorting operations with route priority

### ISSUE THREAD

**Issue by loic425** [api-platform/core#5241]
**API Platform version(s) affected**: 2.7.x && 3.x

**Description**  
The priority on an operation does not seem to work.

```php
#[ApiResource(
    shortName: 'Book',
    operations: [
        // queries
        new GetCollection(
            '/books/cheapest.{_format}',
            openapiContext: ['summary' => 'Find cheapest Book resources.'],
            paginationEnabled: false,
            provider: CheapestBooksProvider::class,
        ),

        // commands
        new Post(
            '/books/anonymize.{_format}',
            status: 202,
            openapiContext: ['summary' => 'Anonymize author of every Book resources.'],
            input: AnonymizeBooksCommand::class,
            output: false,
            processor: AnonymizeBooksProcessor::class,
        ),
        new Post(
            '/books/{id}/discount.{_format}',
            openapiContext: ['summary' => 'Apply a discount percentage on a Book resource.'],
            input: DiscountBookPayload::class,
            provider: BookItemProvider::class,
            processor: DiscountBookProcessor::class,
            priority: 100,
        ),
    ],
)]
```

The route with path ' '/books/{id}/discount.{_format}',' should be the first one according to Symfony documentation (https://symfony.com/doc/current/routing.html#priority-parameter).

**How to reproduce**  

**Possible Solution**  

I think the sort method is not called so could be simple as this following code:
```php
// src/Metadata/Operations.php

    public function getIterator(): \Traversable
    {
        $this->sort();       

        return (function (): \Generator {
            foreach ($this->operations as [$operationName, $operation]) {
                yield $operationName => $operation;
            }
        })();
    }
```
_I tried it, but that's not enough._

Moreover, to have the same rule as Symfony, we should switch the priority sorting to have high priority first.
```php
// src/Metadata/Operations.php

    public function sort(): self
    {
        usort($this->operations, fn ($a, $b): int|float => $b[1]->getPriority() - $a[1]->getPriority());

        return $this;
    }
```

**Additional Context**

**Comment by soyuka** [comment]
The operation priority isn't related to symfony's routing but I get the link.

> I think the sort method is not called so could be simple as this following code:

It is called when building operations (AttributesResourceMetadataCollectionFactory). I'm okay about the priority but this makes lot of changes to the actual code and this thing is quite internal right now (I should've called it `order` instead). 
Supporting a BC layer for this would be quite hard and therefore I suggest to keep how it is. 

 Does lowering the priority to -10 works?

**Comment by loic425** [comment]
@soyuka I've tried with -10, but it does not seem to work.
I'm ok with the BC-break, but if it does not work yet, it will not break anything :)
But maybe could be a feature for 3.1. this is not even documented on operation.

**Comment by soyuka** [comment]
It's not documented because it's only used internally. We just want to keep the order of your operations, why don't you just put this one as the first one in your declaration?

**Comment by loic425** [comment]
Hum I understand better what is the purpose of this priority which is a position.
Thx I will implement that a bit different on the resource bundle.
