### ISSUE TITLE
Route with custom uriTemplate variables stopped working after upgrade to 3.0.5/3.0.6

### ISSUE THREAD

**Issue by acirulis** [api-platform/core#5243]
**API Platform version(s) affected**: 3.0.5/3.0.6

Disclaimer: Repeat of #5234 which was incorrectly closed, imo.

**Description**  
I have a resource with following config:

```php
#[ApiResource(
    shortName: 'Inventory',
    operations: [
        new GetCollection(
            uriTemplate: '/warehouses/{warehouseId}/inventory',
        ),
        new Get(
            uriTemplate: '/warehouses/{warehouseId}/inventory/{id}',
        ),
    ],
    uriVariables: [
        'warehouseId' => new Link(
            fromProperty: 'id',
            fromClass: WarehouseResource::class,
        ),

    ],
    normalizationContext: ['groups' => ['inventory:read']],
    denormalizationContext: ['groups' => ['inventory:write']],
    provider: InventoryResourceProvider::class,
)]
class InventoryResource
{
    #[ApiProperty(identifier: true)]
    #[Groups(['inventory:read'])]
    public mixed $id = null;
// ...
```
After upgrade to v3.0.5, GetCollection endpoint dies with error ( "Unable to generate an IRI for the item of type "App\ApiResource\InventoryResource"",)

Trace:
```
"Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("id") to generate a URL for route "_api_/warehouses/{warehouseId}/inventory/{id}_get". in /var/www/html/api/vendor/symfony/routing/Generator/UrlGenerator.php:175
Stack trace:
#0 /var/www/html/api/vendor/symfony/routing/Generator/CompiledUrlGenerator.php(67): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, '_api_/warehouse...', 1, Array, Array)
#1 /var/www/html/api/vendor/symfony/routing/Router.php(225): Symfony\Component\Routing\Generator\CompiledUrlGenerator->generate('_api_/warehouse...', Array, 1)
#2 /var/www/html/api/vendor/api-platform/core/src/Symfony/Routing/Router.php(102): Symfony\Component\Routing\Router->generate('_api_/warehouse...', Array, 1)
#3 /var/www/html/api/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php(187): ApiPlatform\Symfony\Routing\Router->generate('_api_/warehouse...', Array, 1)
#4 /var/www/html/api/vendor/api-pl"
```

**Additional Context**  
Worked before 3.0.4

Also, as previously suggested in #5234 I tried adding id as part of uriVariables `( 'id' => new Link(identifiers: ['id'], fromClass: self::class))`, also tried providing itemUriTemplate in GetCollection operation without any success.

**Comment by soyuka** [comment]
It's correct imo, your `id` is not configured. If you look at the stack trace you'll most probably see that at

https://github.com/api-platform/core/blob/3.0/src/Symfony/Routing/IriConverter.php#L187 

`identifiers` is missing your `id`. API Platform has no way to know how to find the `id` of your URI. The error we fixed in 3.0.4 is that we wrongly modified `uriVariables`. 

You can `debug:api-resource` with `3.0.4` and compare the `uriVariables` but adding the `id` part should definitely work:

```
    uriVariables: [
        'warehouseId' => new Link(
            fromProperty: 'id',
            fromClass: WarehouseResource::class,
        ),
        'id' => new Link(
            identifiers: ['id']
        ),
    ],
```

**Comment by acirulis** [comment]
Ok, I got it working but it is still confusing and possible an improvement can be made, not sure:

There is a possibility to define `uriVariables` at resource level and/or operation level.

1) Operation level `uriVariables` currently replaces resource level `uriVariables` (merging would be better !?)

2) Collection operation requires only `warehouseId` to exist. If `id` is present, it crashes with `Invalid identifier value or configuration`

**So - config which should work (imo) but does not:**

```php
#[ApiResource(
    shortName: 'Inventory',
    operations: [
        new GetCollection(
            uriTemplate: '/warehouses/{warehouseId}/inventory',

        ),
        new Get(
            uriTemplate: '/warehouses/{warehouseId}/inventory/{id}',
        ),
    ],
    uriVariables: [
        'warehouseId' => new Link(
            fromProperty: 'id',
            fromClass: WarehouseResource::class,
        ),
        'id' => new Link(
            fromClass: self::class, identifiers: ['id']
        ),
    ],

)]
```

**And configuration which works but requires to define `warehouseId` twice:**

```php
#[ApiResource(
    shortName: 'Inventory',
    operations: [
        new GetCollection(
            uriTemplate: '/warehouses/{warehouseId}/inventory',
            uriVariables: [
                'warehouseId' => new Link(
                    fromProperty: 'id',
                    fromClass: WarehouseResource::class,
                ),
            ],
        ),
        new Get(
            uriTemplate: '/warehouses/{warehouseId}/inventory/{id}',
            uriVariables: [
                'warehouseId' => new Link(
                    fromProperty: 'id',
                    fromClass: WarehouseResource::class,
                ),
                'id' => new Link(
                    fromClass: self::class, identifiers: ['id']
                ),
            ],
        ),
    ],

)]
```

Alternative ideas for fix:

1) Do nothing (it works but is confusing)
2) Allow to merge operation `uriVariables` with resource `uriVariables` (prior being priority)
3) Allow to define all `uriVariables` at resource level but use only those present in IRI.

**Comment by soyuka** [comment]
Merging is hard, what if you have a collection operation with no uri variables ? 

You can always use php code to avoid repetition (uriVariables: [...self::WAREHOUSE_ID, ...self::ID])

We're currently working to improve the documentation sorry about that confusion.

**Comment by acirulis** [comment]
Ok, thanks!
