### ISSUE TITLE
Remove @internal from OperationRequestInitiatorTrait

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#5255]
**Description**  
As far as I've seen the `OperationRequestInitiatorTrait` is the only way to get the `HttpOperation` of the current request (which you'd need if you want to access the `getExtraProperties` on the operation.
It works well but it's marked as internal, which will cause severral things, such as PHPUnit to complain.

So unless there's another way to access those `getExtraProperties` I'd suggest removing that `@intenal`.

**Comment by soyuka** [comment]
you should't need to extract it from the request, where is it that you don't have the `operation`?

Basically you can use the [OperationMetadataFactory](https://github.com/api-platform/core/blob/main/src/Metadata/Operation/Factory/OperationMetadataFactory.php):

```
$operationMetadataFactory->create($request->attributes->get('_api_operation_name'));

```

**Comment by KDederichs** [comment]
I'm basically using it in a `KernelEvents::REQUEST` `EventPriorities::PRE_READ` eventlistener to do some custom rate limiting. 

I wasn't aware the `OperationMetadataFactory` was a thing though since the docs on extra properties are basically non existent as far as I can tell.
