### ISSUE TITLE
Allow unsafe operations without uri variables if a custom provider is defined.

### ISSUE THREAD

**Issue by gassan** [api-platform/core#5258]
https://github.com/api-platform/core/blob/06185b7c96eec95328fcd06375a74abc91564477/src/Symfony/EventListener/ReadListener.php#L54-L70

Could we slightly defuse the last or || condition in line 63 `(!$operation->getUriVariables() && !$request->isMethodSafe())`?

I have 2 api points:
GET /user/me
and
PUT user/me

I can use custom provider to get current user from Security service or throw AccessDeniedHttpException if no one is logged in.
It works with a safe method GET, but it does not work with PUT.

This condition is understandable - without uri variables probably all records could be fetched for an update which would be dangerous. But not in the case of doctrine - getOneOrNullResult throws NonUniqueResultException.

~~Let extend the condition to (!$operation->getUriVariables() && **!$operation->getProvider()** && !$request->isMethodSafe())~~

~~If the developer uses a custom provider, he himself is responsible for the consequences.~~

Update: Sorry, this will not work. `provider` is always defined (per default) and metadata is cached.

**Comment by soyuka** [comment]
Try this: 
```
#[Get('/users/me', uriVariables: ['me' => new Link(fromClass: User::class, identifiers: [], expandedValue: 'me'))
class User {}
```

**Comment by gassan** [comment]
Thank you, @soyuka. It works with an additional OnRequest listener that defines a requests attribute 'me'.

**Comment by soyuka** [comment]
> It works with an additional OnRequest listener that defines a requests attribute 'me'.

Mhh not sure to get what that listener does?

**Comment by soyuka** [comment]
I'll try to reproduce that at some point

**Comment by soyuka** [comment]
in 3.2 you can force any state this should solve the issue
