### ISSUE TITLE
[GraphQL] Pagination of sub-resources based on pages

### ISSUE THREAD

**Issue by lermontex** [api-platform/core#5278]
**API Platform version(s) affected**: 3.0.8

**Description**  

I'm trying to set up page-based pagination for a sub-resource, but I'm getting the error:

Error: `Variable \"$page\" is not defined by operation \"getResource\".`

**How to reproduce**  
```
#[ORM\Entity(repositoryClass: Resource::class)]
#[Query]
#[QueryCollection]
class Resource
{
    #[ORM\OneToMany(mappedBy: "resource", targetEntity: Item::class, orphanRemoval: true)]
    private iterable $items;
}
```

```
#[ORM\Entity(repositoryClass: Item::class)]
#[ApiResource(
    paginationType: 'page'
)]
#[Query]
#[QueryCollection]
class Item
{
    #[ORM\ManyToOne(targetEntity: Resource::class, inversedBy: "items")]
    #[ORM\JoinColumn(nullable: false)]
    private Resource $recource;
}
```
```

    const {
      result: getResourceQueryResult,
    } = useQuery(
      gql`
        query getResource($id: ID!, $page: Int) {
          recource(id: $id) {
            id
            createdAt
            updatedAt
            items(page: $page) {
              collection {
                id
                createdAt
                updatedAt
              }
            }
          }
        }
      `,
      () => ({
        id: "/api/resources/" + route.params.resourceId,
        page: route.params.page,
      })
    );
```

This works if I don't use the $page variable but set the value directly

**Additional Context**
https://api-platform.com/docs/core/pagination/
https://api-platform.com/docs/core/graphql/#using-the-page-based-pagination

**Comment by soyuka** [comment]
I think its not really related to api platform nor a bug, closing.

**Comment by lermontex** [comment]
@soyuka, but why? This error is api-platform's response to my GraphQL API request

Is it possible to use pagination for nested resources? If yes, how to do it?

**Comment by lermontex** [comment]
@alanpoulain, can you please comment on this issue?

**Comment by lermontex** [comment]
@alanpoulain, can you please comment on this issue?
