### ISSUE TITLE
graphQlOperations configuration require to add unused collection_query operation

### ISSUE THREAD

**Issue by webda2l** [api-platform/core#5280]
**API Platform version(s) affected**: 3.0.8

**Description**  

With a config like:
```
api_platform:
    defaults:
        stateless: true
        graphql_operations: []
        operations: []
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
```

And an Entity like:

```
#[APIP\ApiResource(
    [...]
    operations: [],
    graphQlOperations: [
        new APIP\GraphQl\QueryCollection(name: 'collection_query'),  // This line wasn't required previously!
        new APIP\GraphQl\QueryCollection(
            name: 'collectionPageQuery',
            resolver: PlaceCollectionResolver::class,
            paginationType: 'page'
        ),
    ],
```

It even require me to specify the paginationType because it's cursor otherwise by default. But it can be ok like this.

```
#[APIP\ApiResource(
    [...]
    operations: [],
    graphQlOperations: [
        new APIP\GraphQl\QueryCollection(
            name: 'collection_query',
            paginationType: 'page'
        ),
        new APIP\GraphQl\QueryCollection(
            name: 'collectionPageQuery',
            resolver: PlaceCollectionResolver::class,
            paginationType: 'page'
        ),
    ],
```

This wasn't previously required in 2.x, and earlier 3.x (at least 3.0 I think, I was previously on a fork https://github.com/api-platform/core/compare/v3.0.0...OLYBe:core:fix-graphql-coll-disabledpaginated-type) and now it's required. (doc generation fail with error about it)

However... if more verbose than previously, it's not a major issue and can stay as it is maybe. It's more explicit.

---

Otherwise, some cleaning about resource configuration in the future will be welcome I think. It's complicated sometime to to really understand some configurations like this `defaults.graphql_operations` cfg, you're unabled to find it in the code https://github.com/api-platform/core/search?q=graphql_operations&type=code or docs https://api-platform.com/docs/core/configuration/#configuration

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by soyuka** [comment]
using `graphql_operations: []` you're overriding everything to no default graphql operations. Therefore you have to redeclare every graphql operation and we have "sane defaults" which should be same as before. Isn't there a way to configure the default pagination options?

About the documentation we're working on improving that!

**Comment by webda2l** [comment]
> using `graphql_operations: []` you're overriding everything to no default graphql operations. Therefore you have to redeclare every graphql operation and we have "sane defaults" which should be same as before. Isn't there a way to configure the default pagination options?

Previoulsy in the 2.x and this config:

```
api_platform:
    defaults:
        graphql: []
        itemOperations: []
        collectionOperations: []
```

This `new APIP\GraphQl\QueryCollection(name: 'collection_query'),` wasn't required if don't mistake.

But yes it's not a big deal, and maybe more explicit like this as explain, so feel free to close this issue :)

About the default pagination, yes I could change it, but I have to keep cursor pagination on REST.

> 
> About the documentation we're working on improving that!

:+1:  Maybe add informations in Debug profiler itself too to better understand from where the final configuration of an operation is built.
