### ISSUE TITLE
custom Post route api 3.0.6. (method not allowed)

### ISSUE THREAD

**Issue by fuqeba** [api-platform/core#5282]
Greetings, currently I am migrating a project from api 2.6 to 3.0.6 version in symfony framework and this **POST route** is giving me troubles 
 `new Post
        (
            uriTemplate:'/columns/{model}/{version}',
            validationContext:['groups'=>'post-column'],
            requirements:['model'=>'a-zA-Z0-9_','version'=>'\d+'],
            uriVariables: [
                'model' => new Link(
                    fromClass: self::class, identifiers: ['model']
                ),
                'version' => new Link(
                    fromClass: self::class, identifiers: ['version']
                ),
            ],
            deserialize:false,
            read:false,
            controller:PostColumnController::class,
            paginationEnabled:false,
            paginationClientEnabled:false,
            denormalizationContext:['groups'=>'post-column','allow_extra_attributes'=>false],
            normalizationContext:['groups'=>'get-column']
)

`I have defined ApiProperty on model and version and this is my request body : 
"/api/columns/test_test/1"

`[
  {
    "name": "test1",
    "width": "50%",
    "priority": 1
  },
  {
    "name": "test2",
    "width": "50%",
    "priority": 2
  }
]`
status 405 : 
No route found for &quot;POST http://application.test/api/columns/test_test/1&quot;: Method Not Allowed (Allow: GET) (405 Method Not Allowed) 

Any advice or help would be appreciated , thanks in advance.

**Comment by soyuka** [comment]
If you use a controller probably stick with just a Symfony route.

**Comment by fuqeba** [comment]
I added two how should I say 'dummy' variables in entity class for uriVariables, modelInput and versionInput and it works fine now , but thanks for the advice. Cheers.
