### ISSUE TITLE
[Serializer] Group ignored without manual clear cache

### ISSUE THREAD

**Issue by louismariegaborit** [api-platform/core#5293]
**API Platform version(s) affected**: 2.7.5 with `metadata_backward_compatibility_layer: true`

**Description**  
If I add or remove a group serializer on a property, I must clear the symfony cache manually to the change works.
This problem not appear with `metadata_backward_compatibility_layer: false`. I can't switch the flag for the moment.

**Comment by KDederichs** [comment]
Dev or Prod mode?
Cause Prod mode would be intended behavior

**Comment by louismariegaborit** [comment]
Dev and test environment.

**Comment by Tersoal** [comment]
I have the same problem. Sometimes, embedded entities are serializer, sometimes not. I don't understand why this occur.

**Comment by soyuka** [comment]
Probably a cache issue we fixed at https://github.com/api-platform/core/pull/5242 can you try to backport this to 2.7 and probably open a PR? Thanks!

**Comment by louismariegaborit** [comment]
Ok I try.

**Comment by louismariegaborit** [comment]
I tried but it seems that the class ApiPlatformExtension is ok.  
But I seen that the service `api_platform.cache_warmer.cache_pool_clearer` don't exists in 2.7 with flag is true.  
I tried to add the service in the file `legacy/api.xml` with 2.6 configuration, the service now exists but don't resolve the issue.  
Do you have an idea @soyuka ?
