### ISSUE TITLE
Can't use UUID

### ISSUE THREAD

**Issue by polc** [api-platform/core#530]
Hello, 

It's impossible right now to use UUID for entity identifier. 

I don't know what's the purpose of this explode. : https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L71

**Comment by Simperfit** [comment]
How I see it and I have done it is to use both, one UID and one UUID, since the uid is incremented automatically you can set uuid and query on them.

WDYT ?

**Comment by theofidry** [comment]
@Simperfit there is two scenarios:

- having only a UUID as an ID
- having an auto-incremented ID ("private": used only in the application and never accessible to the user) and a UUID token ("public")

**Comment by Simperfit** [comment]
@theofidry then we may not support the first case, do we want to do so ?

@polc Do you get an invalid identifier exception on the first case ?

**Comment by theofidry** [comment]
@Simperfit I didn't check if we currently support the second case either. But I think we should support both. Using the database ID is quite common because simple, but not wanting to do so is also a common use case so it would be sad if we were not able to support it.

**Comment by Simperfit** [comment]
We support the 2nd case because I use it in my project, uid + uuid and it's working properly.

**Comment by dunglas** [comment]
The propose it's to support composed primary keys but indeed it's problematic for uuid and any other id containing a dash. I didn't think about that when I've made this change.

I think to 2 different solutions:

- always try to find the entity without exploding the key first (the easiest to implement will slow done the app when a composed primary key is in use)
- use another special character as separator (Insiggest a slash - it will cause similar problems if identifiers contain slashes but it should be more rare and we can document it)

I would prefer switch to /. Wdyt?

**Comment by theofidry** [comment]
@dunglas can't we configure providers on a route basis? Like that we can have one provider for each case and a provider registry which will try to do everything (by using the other provides). By default we can use the registry, and for fine tuning the developer can go further and manually configure the providers as he see fit.

**Comment by dunglas** [comment]
A less common separator but still significant is a double dot "..". What do you think?

**Comment by dunglas** [comment]
We can but it is still a problem if one of the composed keys contain the special char we use as separator.

**Comment by dunglas** [comment]
Instead of a provider, I was thinking to a flag for the Resource annotation.

**Comment by Simperfit** [comment]
@dunglas I don't understand why you explode on anything ? why not transform the uid in an array since anyway you will just transform it as an array with one key, am i wrong ?

**Comment by theofidry** [comment]
Could you give an example of what it looks like when using a composite key at the moment?

>Instead of a provider, I was thinking to a flag for the Resource annotation.

I said provider because I saw the line @polc pointing a line there, no problem if it can be done elsewhere.

**Comment by Simperfit** [comment]
Using `$identifierValues = (array) $id;` all tests are green and uuid are working properly, I've added some tests to behat. Does the tests does not test the composite value ?

@theofidry https://github.com/api-platform/core/blob/master/features/composite.feature

**Comment by dunglas** [comment]
Because we lack some tests regarding composite identifiers support I bet.
Currently if you use a composite key both keys are joined using a dash when generating the URL and exploded when retrieving data through the data provider.

**Comment by Simperfit** [comment]
1/ Use a flag in the Resource, to know if its a composite id or not let the dash exist and explode only if it's a composite id ?
2/ Use '..' as a separator ?

I would go for 1/ because like you said if in the composite id there is the separator we will have strange behavior.

**Comment by dunglas** [comment]
There is probably a better solution: inspect Doctrine metadata to detect if it's a composite key or not. If it is, explode.

**Comment by teohhanhui** [comment]
What about `(identifier-1,identifier-2)`?

**Comment by teohhanhui** [comment]
So perhaps we can go with something like:

`/dummies/dummyId=1,dummyUuid=41B29566-144B-11E6-A148-3E1D05DEFE78`

**Comment by soyuka** [comment]
> There is probably a better solution: inspect Doctrine metadata to detect if it's a composite key or not. If it is, explode.

+1 on this, it would be from far the cleanest and durable solution!

**Comment by dunglas** [comment]
I like this proposal from @teohhanhui: `/dummies/1,41B29566-144B-11E6-A148-3E1D05DEFE78`
The URL looks cleaner than the other one with explicit keys.

**Comment by teohhanhui** [comment]
But how do we tell which is which? We have the same problem with the current `explode`-based implementation. We're relying on a specific order of the properties, which should not matter (IMO).

**Comment by dunglas** [comment]
The current problem isn't the order. It is that ids are exploded if they contain a `- ` (even if no composed keys are used). The order is the natural order of Doctrine (the order where id are defined). It will be indeed be broken if the developper change the id order. But with your solution it will be broken if the developper change the name of one of the keys.

Both solutions have drawbacks. I prefer the one with the cleanest exposed URL.

**Comment by teohhanhui** [comment]
> The order is the natural order of Doctrine

No. Looking at the code, it's the order of properties as contained in the `PropertyNameCollection`. What's passed to Doctrine is an associative array with the field names as keys.

> But with your solution it will be broken if the developper change the name of one of the keys.

That is only to be expected.

**Comment by dunglas** [comment]
No. Looking at the code, it's the order of properties as contained in the PropertyNameCollection. What's passed to Doctrine is an associative array with the field names as keys.

Yes but this collection is populated using the Reflection API. It is in the "natural order" of properties (in the order or properties in the entity).

**Comment by dunglas** [comment]
Anyway, if everyone for `/dummies/dummyId=1,dummyUuid=41B29566-144B-11E6-A148-3E1D05DEFE78`, go for this one. As I never use composed keys, I don't care much :-)

**Comment by teohhanhui** [comment]
Indeed, I don't use composite keys too, but I'd prefer the one with least surprise.

**Comment by Simperfit** [comment]
@teohhanhui IIUC this will be use for composite keys ? instead of 1-1 we would use name=1,othername=1 ?

**Comment by soyuka** [comment]
yes, like `id_one=1,id_two=2`, hopefully there won't be any string identifier containing a coma :stuck_out_tongue_winking_eye: 

Still, with only one identifier, the current behavior won't change. 

I'm up for both but I prefer `1,41B29566-144B-11E6-A148-3E1D05DEFE78` because it's closer to the parameter without composite identifiers.

**Comment by teohhanhui** [comment]
The comma is a reserved character. We should have already URL-encoded the identifier value beforehand.

**Comment by teohhanhui** [comment]
Unfortunately it looks like if we URL-encode beforehand it'll get double-encoded...

**Comment by Simperfit** [comment]
I'm going for 1,1 or uid=1,uid2=1 ?

**Comment by theofidry** [comment]
> I'm going for 1,1 or uid=1,uid2=1 ?

`uid=1,uid2=1`

**Comment by Simperfit** [comment]
I've updated the PR but I don't like the modification I have made, it feels like a Hack,

It is one ? ping @teohhanhui @dunglas @theofidry

**Comment by teohhanhui** [comment]
I'm leaning towards semi-colon `;` as the separator now. The comma `,` can be kept for expressing a list of values (not that we should support that now... not sure if it even makes sense), what do you think?

e.g. `uid=1;uid2=1` or the hypothetical `uid=1;uid2=1,2,3`

**Comment by theofidry** [comment]
makes sense to me 👍

**Comment by dunglas** [comment]
👍

**Comment by soyuka** [comment]
+1 on semi-colon

**Comment by Simperfit** [comment]
I've updated the PR according to your comments
