### ISSUE TITLE
[Psalm] ProviderInterface does not allow for arrays to be returned

### ISSUE THREAD

**Issue by nesl247** [api-platform/core#5303]
**API Platform version(s) affected**: 3.0.7

**Description**  
In https://github.com/api-platform/core/blob/3a845f1fb0ee80d6a8dc547a2aa97633fcda0830/src/State/ProviderInterface.php#L23 the type is defined to be an object. Because of this, when running psalm, it complains if a provider returns an array, given that an array is not an object.

```
ERROR: InvalidTemplateParam - src/TestProvider.php:13:31 - Extended template param T expects type object, type array<array-key, mixed> given (see https://psalm.dev/183)
class TestProvider implements ProviderInterface
```

**How to reproduce**  
```
<?php

declare(strict_types=1);

namespace App;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;

/**
 * @implements ProviderInterface<array>
 */
class TestProvider implements ProviderInterface
{
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        return [];
    }
}
```
**Possible Solution**  
Change it to `T of object|array`. I'm not sure if this is incorrect, but I think it's valid, and it does fix the issue.

**Additional Context**

**Comment by soyuka** [comment]
@tyx can I have your insight on this?

**Comment by soyuka** [comment]
related https://github.com/api-platform/core/pull/5443

**Comment by nesl247** [comment]
@soyuka this is still an issue in `v3.3.12` using phpstan.
