### ISSUE TITLE
POST operation returns 'Unable to generate an IRI for the item' using ODM

### ISSUE THREAD

**Issue by walldemar** [api-platform/core#5308]
**API Platform version(s) affected**: v3.0.8

**Description**  
POST operation returns 'Unable to generate an IRI for the item of type \"App\\Document\\TestResource\"' using ODM.
In my project I am using: "doctrine/mongodb-odm-bundle": "^4.5.x-dev" which inside use "doctrine/mongodb-odm": "^2.3".
This link (https://www.doctrine-project.org/2021/12/04/mongodb-odm-2.3.html) says that from mongodb-odm:2.3 we can use PHP Attributes.

Soo I created a new API Platform 3 project with this mongodb support. I created "TestResource" like this:
```php
<?php declare (strict_types=1);

namespace App\Document;

use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiProperty;
use App\Repository\TestResourceRepository;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Doctrine\ODM\MongoDB\Types\Type;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    shortName: 'TestResource',
    operations: [new Get(), new Put(), new Delete(), new GetCollection(), new Post()],
    normalizationContext: ['groups' => ['test_resource:read']],
    denormalizationContext: ['groups' => ['test_resource:write']]
)]
#[ODM\Document(repositoryClass: TestResourceRepository::class)]
class TestResource
{
    #[ODM\Id(type: Type::STRING, strategy: "AUTO")]
    #[ApiProperty(readable: false, writable: false, identifier: true)]
    private ?string $id = null;

    #[ODM\Field(type: Type::STRING)]
    #[Groups(["test_resource:write", "test_resource:read"])]
    #[Assert\NotBlank]
    #[Assert\Length(min: 1, max: 128)]
    #[Assert\Type(type: "string")]
    #[Assert\Regex(pattern: '/^[0-9a-zA-Z ]+$/i')]
    private string $name;

    public function getId() : ?string
    {
        return $this->id;
    }
    public function setId(string $id) : self
    {
        $this->id = $id;
        return $this;
    }
    public function getName() : string
    {
        return $this->name;
    }
    public function setName(string $name) : self
    {
        $this->name = $name;
        return $this;
    }
}
```
and when I execute:
```curl
curl -X 'POST' \
  'http://127.0.0.1:8130/api/test_resources' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "name": "string"
}'
``` 
then I get response body like this:
```json
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Unable to generate an IRI for the item of type \"App\\Document\\TestResource\"",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/html/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php",
      "line": 181,
      "args": []
    },
    ...
```

**Additional Context**  
When in the same project I will change PHP Attributes to PHP Annotations (only part related to Doctrine\MongoDB - #[ODM...]), then it works.

**Comment by soyuka** [comment]
```
#[ApiProperty(readable: false, writable: false, identifier: true)]
```
    
 Why do you specify readable and writable ?
 
 This is the class responsible for the bug (if any): https://github.com/api-platform/core/blob/main/src/Doctrine/Odm/Metadata/Property/DoctrineMongoDbOdmPropertyMetadataFactory.php#L50 
 
 Is the `id` found?

**Comment by walldemar** [comment]
@soyuka I did once again a clear project and I got the same... but I found a reason :)

I created project using composer:
`composer create-project symfony/skeleton:"6.2.*" my_project_directory`.
Then I executed:
`composer require doctrine/mongodb-odm-bundle`.

I use this resource:
`
<?php declare(strict_types=1);

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;

/**
 * @ODM\Document
 */
#[ApiResource(
    //shortName: 'Test',
    operations: [
        new Get(),
        new GetCollection(),
        new Patch(),
        new Put(),
        new Delete(),
        new Post(),
    ],
    normalizationContext: ['groups' => 'Test:read'],
    denormalizationContext: ['groups' => 'Test:write'],
)]
class Test
{
    /**
     * @ODM\Id(strategy="INCREMENT", type="int")
     */
    #[ApiProperty(identifier: true)]
    #[Groups(["Test:read"])]
    private $id;

    /**
     * @ODM\Field(type="string")
     */
    #[Groups(["Test:read", "Test:write"])]
    private string $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

}
`

and I got an error... "Unable to generate an IRI for the item' using ODM...".

The problem was with the versions of the packages.

At this point in composer.json I got: **doctrine/mongodb-odm-bundle:^2.0**, soo I updated it to 4.5 using:
`composer require doctrine/mongodb-odm-bundle:^4.5`
but this command fails because this version of **doctrine/mongodb-odm-bundle** require **doctrine/annotations:^1.13**.
At that point I got doctrine/annotations:^2.0... soo first I downgraded **doctrine/annotations** and then upgraded **doctrine/mongodb-odm-bundle** using:
`
composer require doctrine/annotations:^1.13
composer require doctrine/mongodb-odm-bundle:^4.5
`

After this my test resource starts work.

**Comment by walldemar** [comment]
p.s It also works with PHP Attributes:

```php
<?php declare(strict_types=1);

namespace App\Document;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

#[ODM\Document]
#[ApiResource(
    shortName: 'Test',
    operations: [
        // queries
        // ...

        // commands
        // ...

        // basic crud
        new Get(),
        new GetCollection(),
        new Patch(),
        new Put(),
        new Delete(),
        new Post(),
    ],
)]
class Test
{
    #[ODM\Id(type: "int", strategy: "increment")]
    private $id;

    #[ODM\Field(name: 'name', type: "string")]
    private string $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

}
```

**Comment by soyuka** [comment]
Not surprising you don't have any operation to generate an IRI, add a `Get` operation:

```
#[ApiResource(
    shortName: 'Test',
    operations: [
        new Get(uriTemplate: '/test/{id}'),
        new Post(),
    ],
)]
```

It can also be a disabled operation:

```
#[ApiResource(
    shortName: 'Test',
    operations: [
        new NotExposed(uriTemplate: '/test/{id}'),
        new Post(),
    ],
)]
```

It's weird that this is not done automatically through https://github.com/api-platform/core/pull/4881 we may have forgotten something.

**Comment by walldemar** [comment]
Sorry I updated last comment. I have it but I clear file to much before pasting in here ;)

**Comment by vincentchalamon** [comment]
Hi @walldemar,

Do you still have the issue? I can't reproduce your bug (reproducer available here: https://github.com/vincentchalamon/api-platform-issues-5308).

Can you provide a reproducer GitHub repository please?
