### ISSUE TITLE
Querying a child relation of the same entity type not possible in GraphQL

### ISSUE THREAD

**Issue by NicoHaase** [api-platform/core#5310]
**API Platform version(s) affected**: 3.0.8

**Description**  
In my application, I use a parent/child relation with entities of the same type, like the following:

```php
<?php

declare(strict_types=1);

namespace App\Entity\QualityManual;

use ApiPlatform\Metadata\GraphQl\QueryCollection;
use ApiPlatform\Metadata\GraphQl\Query;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(
    graphQlOperations: [
        new Query(name: 'item_query'),
        new QueryCollection(name: 'collection_query'),
    ]
)]
#[ORM\Entity]
class Chapter
{
    #[ORM\Id]
    #[ORM\Column(type: 'guid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?string $id = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: Chapter::class, cascade: ['remove'])]
    #[ORM\OrderBy(['position' => 'ASC'])]
    private Collection $children;

    public function __construct()
    {
        $this->children  = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }
}
```

When I try to select a single `Chapter` entity and the number of it's children, the result is not built properly. As far as I can debug this, it's a problem of these lines:

> https://github.com/api-platform/core/blob/e2753faabe77eeb5e58cb76db2d4ac87a86cabab/src/GraphQl/Type/FieldsBuilder.php#L265-L268

Due to the last condition, the `$resourceOperation` is not properly set to a collection operation, but to an item operaion. This results in an error in

> https://github.com/api-platform/core/blob/e2753faabe77eeb5e58cb76db2d4ac87a86cabab/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php#L59-L62

as the resulting collection is **not** a collection, but `null` (even if there **are** entities matching this criteria).

**How to reproduce**  
- use the entity definition as above
- run a query like `{ chapter(id: "/api/chapters/chapterId") { id, children { totalCount } } }`

**Additional Context**  
- this worked properly in ApiPlatform v2.7 (with `metadata_backward_compatibility_layer=true`) and below
- this looks similar to #5007

**Comment by alanpoulain** [comment]
It would help if you could create a PR with a failing Behat test on the `3.0` branch.

**Comment by develth** [comment]
So, you do not get an error like in #5007 ?

**Comment by develth** [comment]
Your fix was successful for me @alanpoulain !
