### ISSUE TITLE
[SwaggerUI] Option to turn off auto-hide on "Copy to clipboard" button? Or move it?

### ISSUE THREAD

**Issue by paullallier** [api-platform/core#5320]
API-platform v3.0.8, PHP 8.2, Symfony 6.2

**Description**  
I like the aesthetic of the show-on-hover "copy to clipboard" button in the Swagger interface but, unfortunately, it causes me to click on the lock button pretty much every time I try to open an endpoint.  Can we have an option to make it always visible or (less good) disable it please?  Unless that already exists?

Alternatively, if it popped up to the left of the arrow to open the endpoint, that would be an improvement, I think. (I might even be able to work out how to implement that one!)

**Comment by soyuka** [comment]
Hi, sorry you need to override our template or ask the Swagger UI team directly.

**Comment by paullallier** [comment]
Thanks Soyuka.

**Comment by sbelitz** [comment]
Or, add this in the index.css:
`.swagger-ui .opblock .opblock-summary .view-line-link.copy-to-clipboard {
  width: 24px;
  margin: 0 5px;
}`
