### ISSUE TITLE
Multiple Links to the same ApiResource in IRI doesn't work

### ISSUE THREAD

**Issue by mrossard** [api-platform/core#5323]
(retrying here - originally posted in api-platform/api-platform)

**API Platform version(s) affected**: 3.0.8

**Description**  
I'm trying to add an ApiResource for a relation between an ApiResource and itself, and i can't get it to give me correct item IRIs

**How to reproduce**  
Create a basic resource : 
```php
#[ApiResource(
    operations: [
        new Get(
            uriTemplate: '/resources/{id}',
            provider   : ResourceProvider::class //just returns a dummy Resource
        ),
    ]
)]
class Resource
{
    #[ApiProperty(identifier: true)]
    public int $id;

    public string $name;
}
```

Then another for the relation : 
```php
#[ApiResource(
    operations: [
        new Get(
            uriTemplate : '/resources/{first}/relations/{second}',
            uriVariables: [
                'first' => new Link(toProperty: 'first', fromClass: Resource::class),
                'second' => new Link(toProperty: 'second', fromClass: Resource::class),
            ],
        ),
        new GetCollection(
            uriTemplate : '/resources/{first}/relations',
            uriVariables: [
                'first' => new Link(toProperty: 'first', fromClass: Resource::class),
            ],
            provider    : RelationProvider::class //builds a dummy Relation[] array
        ),
    ]
)]
class Relation
{
    #[ApiProperty(identifier: true)]
    public Resource $first;
    #[ApiProperty(identifier: true)]
    public Resource $second;

    public string $something;
}
```

Then call /resources/1/relations. You'll get something like that : 

```
{
  "@context": "/contexts/Relation",
  "@id": "/resources/1/relations",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/resources/1/relations/1",
      "@type": "Relation",
      "first": "/resources/1",
      "second": "/resources/2",
      "something": "ok"
    }
  ],
  "hydra:totalItems": 1
}
```

Notice the ending id in @id is the one from "first", not the one from "second".

**Possible Solution**  
No clue, i may just not understand this correctly. I tried all i could think of, but i either get this or "unable to create IRI for item...".

**Comment by mrossard** [comment]
Ok, so I dove into the code for a bit, and I think i found a clue about how this happens.

ApiPlatform\Api\IdentifiersExtractor, line 87 :
```php
$identifiers[$parameterName] = $this->getIdentifierValue($item, $link->getFromClass(), $link->getIdentifiers()[0], $parameterName);
````

Here the call to getIdentifierValue() never specifies which field from $item should be used. I suppose $link->getToProperty() should be present somewhere in this call.

Then line 124 could be changed from 
``` php
if ($type->getClassName() === $class)
```

to something like 

``` php
if ($type->getClassName() === $class && $propertyName==$targetproperty)
```

**Comment by mrossard** [comment]
Tried it, it does seem to work for my current use case : 

Line 79 : 
```
- $compositeIdentifiers[$identifier] = $this->getIdentifierValue($item, $link->getFromClass() ?? $operation->getClass(), $identifier, $link->getParameterName());
+ $compositeIdentifiers[$identifier] = $this->getIdentifierValue($item, $link->getFromClass() ?? $operation->getClass(), $identifier, $link->getParameterName(),  $link->getToProperty());
```

line 87 : 
```
- $identifiers[$parameterName] = $this->getIdentifierValue($item, $link->getFromClass(), $link->getIdentifiers()[0], $parameterName);
+ $identifiers[$parameterName] = $this->getIdentifierValue($item, $link->getFromClass(), $link->getIdentifiers()[0], $parameterName, $link->getToProperty());
```

line 96 : 
```
- private function getIdentifierValue(object $item, string $class, string $property, string $parameterName): float|bool|int|string
+ private function getIdentifierValue(object $item, string $class, string $property, string $parameterName, ?string $targetProperty): float|bool|int|string 
```

line 124 : 
```
- if ($type->getClassName() === $class) {
+ if ($type->getClassName() === $class && $targetProperty === $propertyName) {
```

I'm not exactly sure how to go about checking this wouldn't break anything and/or submitting a patch...

**Comment by soyuka** [comment]
I'm not sure to understand, are your classes Doctrine entities ? 

Can't you create your own Provider(s) and handle the joining yourself based on the `uriVariables` you get in the Provider arguments?

**Comment by mrossard** [comment]
Hi,

The problem is not the actual data, which, i am indeed fetching from doctrine just fine in the real app.
In the example I provided (not that clear now that i re-read it), the problem is the generated @id in the results : 
``` 
"hydra:member": [
    {
      "@id": "/resources/1/relations/1",
      "@type": "Relation",
      "first": "/resources/1",
      "second": "/resources/2",
      "something": "ok"
    }
  ],
```
the @id here should be "/resources/1/relations/2", not "/resources/1/relations/1".

**Comment by mrossard** [comment]
> I think the fix would be OK if:
> 
> * you add a Behat test (reproducer) with your case
> * it doesn't break existing tests

I'm not familiar with behat, but i'll try to do that!

**Comment by soyuka** [comment]
Please send me a reproducer and I'll look into that still I find it weird that identifiers and the `toProperty` are tight and I don't think they shoud.

**Comment by mrossard** [comment]
Here is a simple symfony project with a single phpunit test that shows the problem : https://github.com/mrossard/issue5323

**Comment by mrossard** [comment]
If i understand well, the current version of getIdentifierValue() is parsing properties from the class of the $item it gets, and if the property is an isntance of the $class it's looking for, it stops and returns the corresponding value.
The problem here is that there are 2 instances of $class in $item, and the method is not currently provided with a way to decide which one it should pick.
It might actually be the original point of current parameter $parameterName : it is only used in  resolveIdentifierValue(), to print a RuntimeException message?

**Comment by soyuka** [comment]
There's something I don't understand in your provider it can't be that simple:

```
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        return [
            new Relationship(
                new Resource($uriVariables['first']),
                new Resource('relatedTo.'.$uriVariables['first']),
                'whatever')
        ];
    }
```

This looks wrong there's stuff missing. What result do you expect when calling which route?

**Comment by mrossard** [comment]
In a real app, this provider would return the list of relationships where $first is the Resource with the id provided in $uriVariables['first'].
Calling /resources/1/relationships should return every relationship where first is the Resource with the id '1'.

This dummy provider does just that for the sake of demonstrating the problem, which occurs later : the generated relationship does contains 2 different instances of Resource, but when generating an IRI for it, Api platform can't currently find the correct identifier value for both.

**Comment by mrossard** [comment]
ok then, i'll rework that with doctrine - i might not have time to do it today though. 

And the wayt i see it, it shouldn't have any impact : my ApiResources are decoupled from the entities in this app, the only difference in this example would be that the provider retrieves the data through doctrine instead of returning dummy data.

**Comment by mrossard** [comment]
I updated the reproducer very quickly with doctrine and simple fixtures, and made it a bit closer to my real life use. (I just noticed there's a missing unique contraint on the resource name and another on (first, second) in relationships, but that shouldn't matter with this example).

**Comment by mrossard** [comment]
Have you tried through GetCollection and/or with an ApiResource that is not an ORM Entity?

When i try to apply that to the exact example i provided i get "Unable to generate an IRI for the item of type "App\ApiResource\Relationship" ?

I don't get how the Links are supposed to work in your version. The way you're writing them i see no mention of the "Resource" class or its fields, which is pretty confusing when you're in the Relation class and trying to Link it to the Resource class.

**Comment by mrossard** [comment]
I tried updating my example by using exactly your code, then adding the getCollection part like this : 
``` php
 new GetCollection(
            uriTemplate: '/resources/{firstId}/relationships',
            uriVariables: [
                'firstId' => new Link(
                    fromProperty: 'first',
                    fromClass   : Relationship::class,
                    identifiers : ['firstId'],
                )
            ]
        ),
```

The simple Get() works fine indeed, but the call to /resources/1/relationships gets me this error : " "[Semantical Error] line 0, col 246 near 'firstId = :firstId_p1)': Error: Class App\Entity\Relationship has no field or association named firstId" at /.../vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 43".

**Comment by mrossard** [comment]
My bad, didn't notice the provider was on the operation and not on the ApiResource in your example.

With the correct provider, the error becomes the usual "Unable to generate an IRI for the item"...

**Comment by mrossard** [comment]
The problem still seems to reside in the parameters passed to IndetifiersExtractor:getIdentifierValue . In the previous example :
$item is correct:
```
id: 1
name : first and second are related
first : Resource(id: 1, name: first)
second : Resource(id: 2, name: second)
```

$class is obviously correct too : `App\Entity\Relationship`

But then $property is `firstId`, which doesn't exist in the Relationship class...so the call to `$this->propertyAccessor->getValue($item, $property) `on line 100 triggers a NoSuchPropertyException.
