### ISSUE TITLE
V3.0.9 breaks symfony

### ISSUE THREAD

**Issue by frenci8** [api-platform/core#5340]
Hi, 

I upgraded api-platform/core to the latest version 3.0.9 on my symfony project and I get the following error on all the pages in my website: 

`"Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver::resolve()" must yield at most one value for non-variadic arguments.
` and in some other pages the error looks like this `An exception has been thrown during the rendering of a template (""Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver::resolve()" must yield at most one value for non-variadic arguments.").`

I downgraded to v3.0.8 because that one works fine. 

Any ideas? 

Thanks

**Comment by KDederichs** [comment]
What's the SF version? I'd assume 6.1.x?

**Comment by KDederichs** [comment]
Also, could you do me a favor and see if you locally replace this `yield`:
https://github.com/api-platform/core/blob/c39c3e8c1b775926215a750ecef6a03bb569ef40/src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php#L64
with a `return` if that happens to fix it?

**Comment by LoicBoursin** [comment]
> Also, could you do me a favor and see if you locally replace this `yield`:
> 
> https://github.com/api-platform/core/blob/c39c3e8c1b775926215a750ecef6a03bb569ef40/src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php#L64
> 
> 
> with a `return` if that happens to fix it?

@KDederichs I am having the exact same issue in my project and your solution fixes it 👍🏼

**Comment by frenci8** [comment]
> What's the SF version? I'd assume 6.2.x?

yes, 6.2.4 



> Also, could you do me a favor and see if you locally replace this `yield`:
> 
> https://github.com/api-platform/core/blob/c39c3e8c1b775926215a750ecef6a03bb569ef40/src/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php#L64
> 
> 
> with a `return` if that happens to fix it?

yes, that fixes it

**Comment by KDederichs** [comment]
yeah I added a PR with that, I'd assume @soyuka might merge it soon and release a new version

**Comment by KDederichs** [comment]
> Done but we need to prevent a regression on this, its thrown at https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php#L59 but I'm missing some context to write a test.

Context is this (I Think):
It's expecting at MOST one value, which breaks cause `yield` doesn't exit the control flow like `return` does. So `yield` -> `yield` returns two values instead of the permitted one.

I'm not quite sure how you'd test against it though.
