### ISSUE TITLE
[SwaggerUI] Custom URI variable description

### ISSUE THREAD

**Issue by paullallier** [api-platform/core#5343]
API-platform v3.0.8, PHP 8.2, Symfony 6.2

**Description**  
An easy way to customise the description of endpoint uri variables, especially for variables that don't map to an Entity.

**Example**  
As far as I can tell from the code and documentation, the UriVariables defined in (for example) ApiPlatform\Metadata\Get have to have a Link object defined for them - either explicitly, or an implicit one is assumed.  I don't think we can define an explicit one if the parameter isn't related to an Entity class, and if they are implicit, they end up with the generic description `<entity_class> identifier`.
<img width="831" alt="Screenshot 2023-01-15 at 23 00 19" src="https://user-images.githubusercontent.com/42591123/212572395-a67c25e5-0865-4a18-9ccb-97929a4ec616.png">

In this case, the `/invoices/<uuid>/history` endpoint returns a collection of historic versions of the invoice with that UUID, and the `/invoices/<uuid>history/<index>` endpoint returns full details the `<index>-th` version of that invoice.  It would be really useful if there was a way to set a more meaningful description in this case - unless there is and I've missed it.

Ideally, I'd like to be able to do something like this:
```
new Get(
	uriTemplate: '/invoices/{invoiceUuid}/history/{index}.{_format}',
	uriVariables: [
		'invoiceUuid',
		'index' => 'Description of the index parameter',
	],
	openapiContext: [
		'summary' => 'Get historic invoice version',
		'description' => 'Get historic version of a specific invoice',
	],
	normalizationContext: ['groups' => ['invoice:read_item']],
	provider: InvoiceStateProvider::class),
```

**Comment by Byidi** [comment]
The parameters descriptions can be edited in the operation's openapiContext: 

```php
new Get(
            uriTemplate: '/invoices/{invoiceUuid}/history/{index}.{_format}',
            uriVariables: ['invoiceUuid', 'index', ],
            openapiContext: [
                'summary' => 'Get historic invoice version',
                'description' => 'Get historic version of a specific invoice',
                'parameters' => [
                    [
                        'name' => 'index',
                        'in' => 'path',
                        'description' => 'your description',
                        'required' => true,
                        'schema' => ['type' => 'string'],
                    ]
                ]
            ],
            normalizationContext: ['groups' => ['invoice:read_item']],
            provider: InvoiceStateProvider::class,
        ),
```

IMO it's a bit tedious, and maybe it'll be easier and more logic to add an openapiContext parameter on the Link object.

**Comment by paullallier** [comment]
Ah, fantastic!  Thank you @Byidi.
