### ISSUE TITLE
[BC][2.7] ES extensions no longer executed

### ISSUE THREAD

**Issue by darthf1** [api-platform/core#5363]
Hi!

I'm trying to upgrade from `v2.6.8` to `v2.7.7`. 

https://github.com/api-platform/core/pull/5283 fixes a lot of issues for me, but now a few of my tests return errors because the API output is different as expected; I get more `hydra:items` returned as expected.

I use an extension, to perform additional filtering on the results if needed, by changing the ES request body:
```php
<?php

declare(strict_types=1);

namespace App\MyNamespace;

use ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\RequestBodySearchCollectionExtensionInterface;

final class MyESExtension implements RequestBodySearchCollectionExtensionInterface
{
    public function applyToCollection(array $requestBody, string $resourceClass, ?string $operationName = null, array $context = []): array
    {
        ....
    }
}
```

When I put a breakpoint inside the `applyToCollection` function, I noticed It's not called in `v2.7.7` and it is called in `v2.6.8`.

**Comment by soyuka** [comment]
probably that our ES provider is not called anymore, I guess you can't update to 3.x ? Is the ElasticsearchProvider called ?

**Comment by darthf1** [comment]
> Is the ElasticsearchProvider called?

If the provider would not be called, would I get a result at all? Because my issue is that the request body does not get altered (by me) because the extension is not called, not that I get no results at all.

I'll investigate.

> I guess you can't update to 3.x ?

I would really love to migrate to 3.x, especially with the new ES features released in 3.1, but I was hoping I could do it incrementally.

**Comment by darthf1** [comment]
> It's also possible that this interface namespace changed and that we forgot to tag this old interface

Yep that was it!

I've added the below to my `services.php` and these tests are now green! :)

```php
<?php

declare(strict_types=1);

namespace MyNamespace;

use ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\RequestBodySearchCollectionExtensionInterface;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    ....

    $services->instanceof(RequestBodySearchCollectionExtensionInterface::class)
        ->tag('api_platform.elasticsearch.request_body_search_extension.collection')
    ;
}
```

**Comment by soyuka** [comment]
Feel free to patch this on 2.7!
