### ISSUE TITLE
[BUG] v3.1.0 VarnishXKeysPurger getting a RewindableGenerator instead of an array

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#5365]
**API Platform version(s) affected**: 3.1.0

**Description**  
Since updating I now get an error:
```
ApiPlatform\HttpCache\VarnishXKeyPurger::__construct(): Argument #1 ($clients) must be of type array, Symfony\Component\DependencyInjection\Argument\RewindableGenerator given
```

**How to reproduce**  
Just by using the `VarnishXKeys` purger, has there been a change which would result in this? I'm noticing that the service declaration is for a set of tagged services. Was there any update to Symfony which changed this?

**Comment by silverbackdan** [comment]
I can confirm, downgrading to 3.0.11 does not have this error.

**Comment by soyuka** [comment]
Whate are you injecting as `$clients` ?

**Comment by soyuka** [comment]
can you let me know if my patch fixes the issue?

**Comment by silverbackdan** [comment]
I don't *think* I'm injecting any client on my own, sure I'll check now

**Comment by silverbackdan** [comment]
Yes, my tests are now all working again as expected, thank you :)

**Comment by soyuka** [comment]
nice thanks daniel!
