### ISSUE TITLE
"resource" is a soft reserved word since PHP 7

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#537]
> Whilst they may still be used as class, interface, and trait names (as well as in namespaces), usage of them is **highly discouraged** since they may be used in future versions of PHP.

http://php.net/manual/en/reserved.other-reserved-words.php

We should think of another name.

**Comment by dunglas** [comment]
For the annotation?

**Comment by teohhanhui** [comment]
Yes, but if we're changing that we should be consistent in the name change. PHP already has a `resource` type anyway, so it might cause confusion in the first place.

**Comment by dunglas** [comment]
But resource is also the right REST / Hydra term. And it used since the beginning. I'm ok to find another name like `@ResourceConfiguration` for the annotation but I don't think that it's a good idea to change it for another term everywhere.

**Comment by soyuka** [comment]
As long as no Class/Interface/Trait isn't using the name `Resource` it's safe enough no?

**Comment by teohhanhui** [comment]
`@ApiResource`?

**Comment by teohhanhui** [comment]
> But resource is also the right REST / Hydra term.

Actually I've elaborated before in https://github.com/api-platform/core/issues/420#issuecomment-191694267 why it's not the right term, but never mind. :smile:

**Comment by dunglas** [comment]
+1 for `@ApiResource`

**Comment by Simperfit** [comment]
ping @teohhanhui this can be closed
