### ISSUE TITLE
PUT (with extraProperties : ['standard_put' => true]), deserializer & provider

### ISSUE THREAD

**Issue by mrossard** [api-platform/core#5370]
**API Platform version(s) affected**: 3.1.0

**Description**  
I'm not sure it's a bug, maybe more of a question. I tried to use PUT (with standard_put set to true) - i usually prefer POST+PATCH, so i might misunderstand some things - and the way/order things get called doesn't feel right.

What happens : 
* first the provider::provide gets called
* then the deserializer:denormalize

What is troubling : 
* Writing a custom provider that handles creations via PUT feels pretty awkward - nothing to fetch from the underlying data store, can't return null or i get a 404, and as far as i can see the payload is not available at this stage either so you can't just build your new resource here.
* if i'm not mistaken the deserializer doesn't get the resulting resource as an input either, so isn't it just discarded in this case?

**How to reproduce**  
Have an api resource with Put() and a custom provider and deserializer, see what's getting called in what order with your debugger.

**Possible Solution**  
When the operation is PUT, maybe allowing the provider to return null without returning a 404 would do the trick?

**Comment by soyuka** [comment]
Use post/patch. You can use the `allowCreate` option on `PUT` if you want to use it to create a resource. All the information you'd need are at https://github.com/api-platform/core/pull/4996.

**Comment by mrossard** [comment]
OK, thanks, i'll look into the allowCreate option - using put as a "create or update" operation is something users love to have.
