### ISSUE TITLE
Issue with annotation_reader in 2.7 (compatibility_layer: true)

### ISSUE THREAD

**Issue by fabienlem** [api-platform/core#5371]
**API Platform version(s) affected**: 2.7.7

I encounter a bug that is similar to https://github.com/api-platform/core/pull/5358 in ApiPlatform 2.7 with `metadata_backward_compatibility_layer: true`.

![image](https://user-images.githubusercontent.com/19775001/214794374-fd238d74-6f25-4e63-9456-c8f94cbbf8a8.png)

**Description**  

When updating ApiPlatform, the following error is thrown when composer is clearing Symfony's cache.

`The service "api_platform.metadata.resource.name_collection_factory.annotation" has a dependency on a non-existent service "annotation_reader".`

**How to reproduce**  

Just update to ApiPlatform 2.7.7 with `metadata_backward_compatibility_layer: true`.

**Possible Solution**  

Adding `on-invalid="null"` in this file https://github.com/api-platform/core/blob/v2.7.7/src/Symfony/Bundle/Resources/config/legacy/metadata_annotation.xml solve the issue.

Thank you!

**Comment by soyuka** [comment]
Would you be able to patch this? Thanks!

**Comment by soyuka** [comment]
nvm I'll try to patch it as I see more to it then it looks like

**Comment by fabienlem** [comment]
Thank you for your quick reply and patch!

**Comment by louismariegaborit** [comment]
I try the 2.7.8 release but the bug is not fix.

There is a problem in this file : 
https://github.com/api-platform/core/blob/2.7/src/Core/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php#L86
![image](https://user-images.githubusercontent.com/15611563/215091696-05df40b6-3a10-45f9-894d-0c3042d65943.png)

**Comment by louismariegaborit** [comment]
The PR #5378 resolve the problem with the update of doctrine/annotation 1.13 to 1.14 but we can't update symfony from 6.2.0 to 6.2.5. Clear cache doesn't ended with success. We just have a memory error.

**Comment by soyuka** [comment]
damn I patched it at https://github.com/api-platform/core/blob/2.7/src/Core/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php#L59-L61 but forgot the below reader.
