### ISSUE TITLE
PUT tries to create new entity even when it already exists if ORM id is hidden in the API

### ISSUE THREAD

**Issue by mrossard** [api-platform/core#5372]
**API Platform version(s) affected**: 3.1.0

**Description**  
Sorry, i'm back with my non-standard uses!

I'm trying to use PUT for create or update on an entity where the ORM ids are purely internal, and other "human-readable" identifiers are used in the API/uriVariables.

When you do that, even if the provider does return the correct record, the Doctrine PersistProcessor tries to persist an entity where the orm id is not set, which causes either duplicate data, or a unique violation if your human readable identifier is set correctly on the database side.

**How to reproduce**  
I can add a reproducer if you think it's useful, but the problem seems pretty straightforward...it's more of a "how should this actually behave?" problem IMO. 

**Possible Solution**  
In ApiPlatform\Doctrine\Common\State\PersistProcessor, around lines 80 to 96 the properties tagged #[ORM\Id] likely shouldn't be overwritten if not made available throught the API.
Another option is obviously to write a custom processor, but shouldn't/couldn't it be standard behaviour?

**Comment by mrossard** [comment]
Another puzzling thing while trying to write a custom processor instead : the contents you get in $context['previous_data'] in the processor gets detached from doctrine's unitofwork somehow, which makes it awkward to use.

**Comment by soyuka** [comment]
what about not creating 2 issues around this and merging it with https://github.com/api-platform/core/issues/5370 ?

**Comment by mrossard** [comment]
It seemed like a different issue to me, and i thought you'd close the other one since allowCreate looked like the right answer - but i can close this one and duplicate its contents there if you like.

**Comment by soyuka** [comment]
Okay sorry then I didn't understood your issue

**Comment by mrossard** [comment]
I'll try to find some time to craft an example then. But after reading more closely what @dunglas says in https://github.com/api-platform/core/pull/4996 , it might actually be what he was refering to when he said "My refactoring doesn't handle the case where URI variables don't match the Doctrine properties"...

**Comment by soyuka** [comment]
yes it's a hard problem if that's the case

**Comment by mrossard** [comment]
I can imagine that! I couldn't get to it yet but i should find some time for an example in the next few days.

**Comment by mrossard** [comment]
A small update : i tried to build a simple example, but if i make it simple i stumble into another problem with the PersistProcessor.
IMO it needs a lot of work still, but as i dig into it i understand how complicated it is too.

The problem i stumbled upon today : line 58 of the PersistProcessor, there is a call to the entityManager to try and get a reference to the existing entity. The problem is that the id it is called with is the contents of uriVariables, which is not relevant in the context of Doctrine when you're not passing the ORM ids in the URIs.

for example : 
``` php
 
#[ApiResource(
    operations: [
        new Get(
            uriTemplate : '/some_entities/{publicIdentifier}',
            uriVariables: [
            'publicIdentifier' => new Link(fromProperty: 'publicIdentifier', fromClass: self::class)
        ],
            provider    : CustomProvider::class,
        ),
        new Put(
            uriTemplate    : '/some_entities/{publicIdentifier}',
            uriVariables   : [
                'publicIdentifier' => new Link(fromProperty: 'publicIdentifier', fromClass: self::class)
            ],
            provider       : CustomProvider::class,
            extraProperties: ['standard_put' => true],
            allowCreate    : true
        )
    ],
    normalizationContext: ['groups'=>'OUT'],
    denormalizationContext: ['groups'=>'IN'],
)]
class SomeEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[ApiProperty(identifier: false)]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[ApiProperty(identifier: true)]
    #[Groups(['OUT'])]
    private ?string $publicIdentifier = null;
```

The PersistProcessor currently tries to pass the $publicIdentifier value to entityManager->getReference(), which has no way to fetch the correct entity from it, since the ORM identifier is $id.

**Comment by mrossard** [comment]
That solution may not be entirely correct, but i feel like using uriVariables in this part of the framework has to be wrong. This is "doctrine-land", it shouldn't have to care about URIs, all that part of the work has been done before reaching here and the coressponding data is available in the context.

**Comment by mrossard** [comment]
I was thinking i'd at least try to see how PRs work so i can contribute more, but unit tests seem to fail out of the box on 
```
ApiPlatform\Tests\Symfony\Bundle\Command\OpenApiCommandTest::testExecuteWithYaml
nested object should be present.
Failed asserting that 'openapi: 3.0.0\n 
[...]...tens of thousands of lines... [...]
' contains "  /dummy_cars:
    get: [...]
```
Is it just me?

**Comment by mrossard** [comment]
Just a comment to prevent this from getting autoclosed. I'm still trying to find time for a better PR.
