### ISSUE TITLE
Add Swagger 2.0 support

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#538]

**Comment by teohhanhui** [comment]
Is there any action that we need to take on our end? I thought Swagger support should fall under NelmioApiDocBundle?

Or is this referring to using the Swagger spec for validation? Generating resources / operations based on the Swagger spec?

**Comment by dunglas** [comment]
Nelmio only support the Swagger v1 spec. And, as API Platform is now a standalone library, it would be nice to have native Swagger, support not relying on an external Symfony bundle.

> Or is this referring to using the Swagger spec for validation? Generating resources / operations based on the Swagger spec?

Yes.

**Comment by Simperfit** [comment]
How do we have to do that ? Can we use one of the php librairy that exist ou do we have to re-develop all the things ?

**Comment by teohhanhui** [comment]
Related: https://blog.liip.ch/archive/2016/05/11/convert-nelmioapidocbundle-to-swagger-php.html

**Comment by dunglas** [comment]
Yes, and this tweet: https://twitter.com/couac/status/730415066047234049

I've looked at this lib, it's not practical for API Platform (it relies on external annotations). Adding native Swagger support would be better.

**Comment by teohhanhui** [comment]
The problem I ran into when I first tried Swagger (v2) was that you have to maintain the spec separately. That's where annotations can help by auto-generating the Swagger spec based on `@ApiResource` and `@ApiProperty`.

**Comment by teohhanhui** [comment]
What I mean is that it's easier to do it code-first instead of schema-first.

**Comment by dunglas** [comment]
NelmioApiDoc has officially been deprecated: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.13.0

**Comment by teohhanhui** [comment]
@dunglas:

> NelmioApiDoc has officially been deprecated

No, it has not. He is "thinking about" it.

**Comment by teohhanhui** [comment]
In any case, if we can have dynamically generated Swagger spec (or generated by a console command or similar) based on API Platform metadata then I'll be happy.

**Comment by dunglas** [comment]
Ok but it is at least feature frozen... It's time to move on.

**Comment by Simperfit** [comment]
@dunglas this can be closed

**Comment by soyuka** [comment]
@Simperfit Hmm I'd leave this open, I see a few things left:

-  [swagger-ui ](https://github.com/api-platform/core/tree/master/src/Bridge/Symfony/Bundle/Resources/public/swagger-ui) can not stay in the repository, it's dirty 😛  (I saw something about it not beeing packaged can't remember where)
- Is the [NelmioApiDoc bridge](https://github.com/api-platform/core/tree/master/src/Bridge/NelmioApiDoc) still required?

**Comment by Simperfit** [comment]
@soyuka I disagree with you about swagger-ui, why not ? It has alot of features and can stay in this repository.

You are right about the bridge

**Comment by soyuka** [comment]
Can't it be a dependency? Because it sux for updates and maintenance. I'm sure we can add [some post install script in composer](https://getcomposer.org/doc/articles/scripts.md) to fetch it, couldn't we?

**Comment by teohhanhui** [comment]
@soyuka:
> Can't it be a dependency? Because it sux for updates and maintenance.

It sucks for trying to search in the repository too. We should definitely fix this before 2.0 release.

**Comment by soyuka** [comment]
+1
Le lun. 1 août 2016 à 10:42, Teoh Han Hui <notifications@github.com> a
écrit :

**Comment by soyuka** [comment]
Fyi you can use path: with github but still agree 200%

**Comment by dunglas** [comment]
It's on my todo list, I think @soyuka's solution is a good trade off: move Swagger UI assets from core to the standard edition.

What do you think?

**Comment by soyuka** [comment]
@dunglas won't there be a way to release a builded swagger-ui to packagist? This would be the cleanest solution IMO.

**Comment by dunglas** [comment]
Probably but it looks overkill. And is a pain to maintain.

What we can do is install Swagger UI in the standard edition using NPM or Bower (I prefer the first one) and create a hook in composer.json to update JS dependencies if NPM and related stuffes are installed.

**Comment by teohhanhui** [comment]
I've made the suggestion at swagger-api/swagger-ui#2310

**Comment by teohhanhui** [comment]
Swagger UI is now published at https://packagist.org/packages/swagger-api/swagger-ui

**Comment by soyuka** [comment]
This is great! Thanks @teohhanhui!

**Comment by dunglas** [comment]
Great but how can we put it in the right (public) directory?

**Comment by teohhanhui** [comment]
@soyuka is working on it in #768 :smile:
