### ISSUE TITLE
POST and PUT operations involving UUIDs are broken after upgrade to 3.1

### ISSUE THREAD

**Issue by MariusJam** [api-platform/core#5380]
**API Platform version(s) affected**: 3.1.*

**Description**  

After upgrade to 3.1.* a lot of our POST/PUT operations involving resources with UUIDs are broken. After a bit of debugging, I've found an InvalidIdentifierException is thrown at l.49 of UriVariablesResolverTrait. I think it's because the value returned by `$operation->getUriVariables()` changed between 3.0.* and 3.1.* (especially the number of identifiers) :

In 3.0.* : 

```
#uriVariables: array:1 [▼
    "uuid" => [ApiPlatform\Metadata\Link] {#2753 ▼
      -parameterName: "uuid"
      -fromProperty: null
      -toProperty: null
      -fromClass: "App\Entity\Fundraiser"
      -toClass: null
      -identifiers: array:1 [▼
        0 => "uuid"
      ]
      -compositeIdentifier: null
      -expandedValue: null
    }
  ]
```

In 3.1.* : 

```
#uriVariables: array:1 [▼
    "id" => ApiPlatform\Metadata\Link {#775 ▼
      -parameterName: "id"
      -fromProperty: null
      -toProperty: null
      -fromClass: "App\Entity\Fundraiser"
      -toClass: null
      -identifiers: array:2 [▼
        0 => "uuid"
        1 => "id"
      ]
      -compositeIdentifier: true
      -expandedValue: null
    }
  ]
```

Hence, in 3.0.* , the condition l.45 `if (($uriVariableDefinition->getCompositeIdentifier() ?? true) && 1 < ($numIdentifiers = \count($uriVariableDefinition->getIdentifiers() ?? [])))` was evaluated to false and, in 3.1.* , it is evaluated to true.

**Comment by soyuka** [comment]
Interesting, may you give me the full resource or a reproducer?

**Comment by MariusJam** [comment]
Yes, I have been able to finally reproduce the issue : 

```php
#[ORM\Entity(repositoryClass: FooRepository::class)]
#[ApiResource]
class Foo
{
    #[ORM\Id]
    #[ApiProperty(identifier: true)]
    #[ORM\Column(type: UuidType::NAME)]
    public Uuid $uuid;

    public function __construct()
    {
        $this->uuid = Uuid::v4();
    }
    
    public function getId(): string
    {
        return 'toto';
    }
}
```

```php
#[ORM\Entity(repositoryClass: BarRepository::class)]
#[ApiResource]
class Bar
{
    #[ORM\Id]
    #[ApiProperty(identifier: true)]
    #[ORM\Column(type: UuidType::NAME)]
    public Uuid $uuid;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(referencedColumnName: 'uuid', nullable: false)]
    public ?Foo $foo = null;

    public function __construct()
    {
        $this->uuid = Uuid::v4();
    }
}
```

With those ApiResources, a PUT on `/bars` with body `{ "foo": "/foos/d3a5cd86-b07e-446d-af0d-47da8bd64efb" }` will fail with an `Invalid IRI \"\/foos\/d3a5cd86-b07e-446d-af0d-47da8bd64efb\".` error.

What seems to provoke the problem is the presence of both `$uuid` property and the unrelated `getId()` method. In that case, `getId()` is considered as an identifier.

**Comment by soyuka** [comment]
Use this:

```
    #[ApiProperty(identifier: false)]
    public function getId(): string
    {
        return 'toto';
    }
```

Sorry for the disturbance, we can't really now that `id` isn't an identifier if it is declared we think it is.
