### ISSUE TITLE
OpenApi deprecation

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#5388]
**API Platform version(s) affected**: 3.1

**Description**  
In https://github.com/api-platform/docs/blob/3.1/core/openapi.md is described that you can use the following configuration (changed in PR https://github.com/api-platform/core/pull/5254 and https://github.com/api-platform/docs/pull/1679)

```
<openapi>
  <values>
    <value ...></value>
  </values>
</openapi>
```

But that gives the following error:

`Error while parsing Resource.xml: [ERROR 1871] Element '{https://api-platform.com/schema/metadata/resources-3.0}values': This element is not expected. Expected is one of ( {https://api-platform.com/schema/metadata/resources-3.0}tags, {https://api-platform.com/schema/metadata/resources-3.0}responses, {https://api-platform.com/schema/metadata/resources-3.0}externalDocs, {https://api-platform.com/schema/metadata/resources-3.0}parameters, {https://api-platform.com/schema/metadata/resources-3.0}requestBody, {https://api-platform.com/schema/metadata/resources-3.0}callbacks, {https://api-platform.com/schema/metadata/resources-3.0}security, {https://api-platform.com/schema/metadata/resources-3.0}servers, {https://api-platform.com/schema/metadata/resources-3.0}extensionProperties ).`

Using the old openapiContext works. Is the documentation wrong?

**Comment by vincentchalamon** [comment]
Hi @dannyvw,

Indeed, the documentation is not up to date. The `openapi` option has evolved and receive an [Operation](https://github.com/api-platform/core/blob/main/src/OpenApi/Model/Operation.php) object.

The documentation is fixed here: https://github.com/api-platform/core/issues/5388
