### ISSUE TITLE
Add HAL support

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#539]

**Comment by Simperfit** [comment]
How do we have to do that ? Can we use one of the php librairy that exist ou do we have to re-develop all the things ?

**Comment by dunglas** [comment]
My idea was to reuse our metadata infrastructure: creating a new HAL normalizer and a special Response class sending appropriate HTTP headers (like the JSON-LD one) should be enough.

I'm not sure that an external library can help here. The implementation will be easy to do anyway.

**Comment by Simperfit** [comment]
ping @dunglas this can be closed
