### ISSUE TITLE
Probleme with parameter read 

### ISSUE THREAD

**Issue by rafleboss47** [api-platform/core#5390]
**API Platform version(s) affected**: 2.5

**Description**  

Parameters "read" of custom operation doesnot work

**How to reproduce**  

Custom operation can call a get_collection of entity.
this code of class ToggleableOperationAttributeTrait is not good :
return !((bool) $resourceMetadata->getOperationAttribute($attributes, $attribute, !$default, $resourceFallback));
this code return always false because is not a good practice if you wan convert string to boolean

**Possible Solution**  

Use this 
        return !((bool)( $resourceMetadata->getOperationAttribute($attributes, $attribute, !$default, $resourceFallback) === 'false' ? false : true ));
or filter_var 

**Additional Context**

**Comment by soyuka** [comment]
please use 3.x this was fixed thanks

**Comment by rafleboss47** [comment]
@soyuka Thank you for your answer but it is not possible to change the version for the moment.
I share a solution for people in my situation
