### ISSUE TITLE
AbstractConstraintViolationListNormalizer cast $nameConverter with NameConverterInterface but uses AdvancedNameConverterInterface contract

### ISSUE THREAD

**Issue by syl20b** [api-platform/core#5391]
Hi,

Is there a reason for casting the `$nameConverter` property of the `ApiPlatform\Serializer\AbstractConstraintViolationListNormalizer` with the  `Symfony\Component\Serializer\NameConverter\NameConverterInterface` type  instead of `Symfony\Component\Serializer\NameConverter\AdvancedNameConverterInterface`  ?

**Comment by soyuka** [comment]
`AdvancedNameConverterInterface` doens't extend `AdvancedNameConverterInterface`?

**Comment by syl20b** [comment]
Yes, but inside the `AbstractConstraintViolationListNormalizer`, `AdvancedNameConverterInterface::normalize` signature is used.

**Comment by syl20b** [comment]
@soyuka I will provide a PR soon. What will be the target branch ? 3.1 ?
