### ISSUE TITLE
Split in multiple OpenApi files

### ISSUE THREAD

**Issue by tyx** [api-platform/core#5400]
**Description**  

Our API built around a monolithic modular is growing more and more and we would love to use the Topbar plugin of SwaggerUI (the one you hide in default css ;)).

For example (we talk about to dropdown at the top right corner) : 
![image](https://user-images.githubusercontent.com/245494/217870704-e0f8b75a-5bd2-4399-9bf9-adc68adc9c65.png)

We could take care of overriding the `SwaggerUiAction` and all js stuff currently managed by APIP ourselves but we miss a piece of puzzle. The ability of `OpenApiFactory` to build multiple files instead of one big.

We already split our definitions but at the end everything is put together without ability to filter : 
![image](https://user-images.githubusercontent.com/245494/217871480-047cbe7c-38dc-429b-a458-8744389c2e3a.png)

Unfortunately I have no better idea except providing a "path" parameter to context of : 
https://github.com/api-platform/core/blob/9b4b58ca0113a2645b58a116fe9e4bf200df8aa3/src/OpenApi/Factory/OpenApiFactoryInterface.php#L18-L24

And let the implementation only generate resource that matches this path. With this change we will be able to use to `openapi:export `command to build our differents files (and create a new Action to display swagger-ui with `urls` parameter)

But since I don't have a global view of the whole architecture maybe I'm missing a simpler or more elegant solution?

**Comment by soyuka** [comment]
Not so hard to do, use our `OpenApiFactory` service, but inject a modified version of `resourceNameCollection` with only a substract of the resources you want to document. 

https://github.com/api-platform/core/blob/main/src/OpenApi/Factory/OpenApiFactory.php#L89

**Comment by tyx** [comment]
Oh yes I love this idea. I will give a try
