### ISSUE TITLE
No way to get retrieved resource object in GraphQL state processor with DTO

### ISSUE THREAD

**Issue by DavidBennettUK** [api-platform/core#5401]
**API Platform version(s) affected**: 3.1.2

**Description**  
When implementing the [DTO pattern](https://api-platform.com/docs/core/dto/#implementing-a-write-operation-with-an-input-different-from-the-resource) for a GraphQL mutation, there is no way to access the original resource object.

`ProcessorInterface::process` also doesn't have access to `args` or any way to get the ID to fetch it manually, so no workaround seems possible.

It is also not possible to put an ID field on the input class, as it instead adds an additional `_id` field, because an `id` field is automatically added to all mutations. Should all mutations automatically be given this `id` field? The only way to remove it seems to define `args` manually, but that means that all the arguments in the input class have to be duplicated and defined in `args` - not great for type safety.

**How to reproduce**  

Example of a mutation to change a user's password.

Entity/resource:

```
#[ApiResource(graphQlOperations: [
    new Mutation(
        name: 'changePassword',
        input: UserChangePasswordInput::class,
        processor: UserChangePasswordProcessor::class),
        normalizationContext: ['groups' => ['read']],
        denormalizationContext: ['groups' => ['write']],
    )
])]
class User implements UserInterface
{
    // ...
}
```

Input:

```
class UserChangePasswordInput
{
    public function __construct(
        #[Groups(['write'])]
        public string $oldPassword,
        #[Groups(['write'])]
        public string $newPassword,
    ) {
    }
}
```

(I should probably create a separate issue, but it seems it's not possible to use `readonly` fields for input types, as the properties do not appear in the schema when they are `readonly`.)

Processor:

```
class UserChangePasswordProcessor implements ProcessorInterface
{
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): void
    {
        \assert($data instanceof UserChangePasswordInput);

        // No way to get the `User` in here, so can't change their password
    }
}
```

**Possible Solution**  

It seems the intention is to be able to get the resource object via `$context`. In a [REST test](https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/State/RecoverPasswordProcessor.php#L26), it shows that `previous_data` is available in the context to retrieve the original resource. However, in GraphQL, the [WriteStage](https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Stage/WriteStage.php#L42) does not recieve the `previousItem` from the [factory](https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php#L65) and does not insert it into the context passed to the state processor.

**Comment by soyuka** [comment]
Wouldn't it be easier to just declare a Mutation on the `UserChangePasswordInput` directly?
