### ISSUE TITLE
ExistsFilter is not working in GraphQL on 2.7

### ISSUE THREAD

**Issue by mbopp** [api-platform/core#5403]
**API Platform version(s) affected**: 2.7.9

**Description**  
With the following code in place, the exists filter does not function as it did in version 2.6.

```
use ApiPlatform\Doctrine\Orm\Filter\ExistsFilter;
use ApiPlatform\Metadata\ApiFilter;

#[ApiFilter(ExistsFilter::class, properties: [
    'completionDate',
])]
```

Query variable snippet.

```
{ "exists": [{  "completionDate": false  }],
```

I'm hoping this doesn't require an update to v3 at this time. While it's part of my strategic plan, the immediate bug needs a resolution in the meantime. If there are any other workarounds, please advise.

Thank You!

**Comment by mbopp** [comment]
It looks like I needed to use 

```
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\ExistsFilter
```
Instead of 
```
use ApiPlatform\Doctrine\Orm\Filter\ExistsFilter;
```

**Comment by soyuka** [comment]
we probably forgot an alias
