### ISSUE TITLE
Api resource upgrade command has gone

### ISSUE THREAD

**Issue by MrYamous** [api-platform/core#5404]
While upgrading a SF project using api platform from 2.6 to 3.0, i've tried to use api:upgrade-resource but this command seems to have disappeared.

The command is no longer present in Symfony/Command directory from Github : https://github.com/api-platform/core/tree/main/src/Symfony/Bundle/Command
I've found some old PR with files related to this project, and it's still on some contributors forks, but i can't find a way to reach it from Api platform package. 

Had the command been removed ?

**Comment by lermontex** [comment]
Seems you need to upgrade from 2.6 to 2.7 and then install 3.0 and up if you want to use `api:upgrade-resource
`
https://github.com/api-platform/core/tree/2.7/src/Core/Bridge/Symfony/Bundle/Command

> - Update the code to 2.7: composer require api-platform/core:^2.7
> - Take care of the deprecations and update your code to the new interfaces, documented on this page
> - Switch the metadata_backward_compatibility_layer flag to false
> - Use the [api:upgrade-resource command](https://api-platform.com/docs/core/upgrade-guide/#the-upgrade-command)

https://api-platform.com/docs/core/upgrade-guide/#im-migrating-from-26-and-want-to-prepare-for-30

**Comment by MrYamous** [comment]
Hum, namespace changes bait me, i was looking for file in https://github.com/api-platform/core/tree/2.7/src/Symfony/Bundle/Command 

Thx, i guess there is no big issue here then
