### ISSUE TITLE
JWT has a different endpoint

### ISSUE THREAD

**Issue by NotionCommotion** [api-platform/core#5406]
**API Platform version(s) affected**: 3.1.2

**Description**  
Not sure whether a bug or just that the documentation at https://api-platform.com/docs/main/core/jwt/ needs to be updated. 

Decorating api_platform.openapi.factory is no longer required and an endpoint named Login Check with path `/authentication_token` will automatically be created, and if one does follow the docs, they will have two endpoints.  These two endpoints brought some confusion at first as I had been using path `/authentication_token` (and not path `/auth`), and I was initially unaware that I had two endpoints being the same path.

![image](https://user-images.githubusercontent.com/2005437/219092588-7e946837-77bb-407f-b513-7d89e3ecbbb4.png)

**How to reproduce**  
Follow the instructions at https://api-platform.com/docs/main/core/jwt/ 
**Possible Solution**  

Do the configuration solely within the security configuration per https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.rst#api-platform-compatibility
**Additional Context**

**Comment by alanpoulain** [comment]
It has been done in 3.1: https://api-platform.com/docs/core/jwt/
It will be merged in main later.

**Comment by NotionCommotion** [comment]
Thanks alanpooulain,  Previously, one could specify default values or add new properties as shown below.  Is this part described under the 3.1 docs?  If not, and recommendations where to start investigating?  Don't care too much about the default values but do about the extra properties.  Thanks!

```php
        $schemas['Credentials'] = new \ArrayObject([
            'type' => 'object',
            'properties' => [
                'org_uuid' => [
                    'type' => 'string',
                    'example' => '23aa3ff9-8df2-457d-958a-6f9e5c48cfa5',
                ],
                'email' => [
                    'type' => 'string',
                    'example' => 'johndoe@example.com',
                ],
                'password' => [
                    'type' => 'string',
                    'example' => 'apassword',
                ],
            ],
        ]);
```

**Comment by alanpoulain** [comment]
You can decorate the OpenApiFactory to do so.
Just get the automatically added path and add the extra properties to it.

**Comment by NotionCommotion** [comment]
Thanks again.  Went with the following and it works.
```
    public function __invoke(array $context = []): OpenApi
    {
        $openApi = ($this->openApiFactory)($context);

        $o = $openApi->getPaths()->getPath('/authentication_token')->getPost()->getRequestBody()->getContent()->offsetGet('application/json')->getSchema();				
        $o->offsetSet('properties', array_merge($o->offsetGet('properties'), ['orgId'=>['type'=>'string', 'nullable'=>false]]));
        $o->offsetSet('required', array_merge($o->offsetGet('required'), ['orgId']));
        return $openApi;
    }
```
