### ISSUE TITLE
Match multiple properties with one parameter in SearchFilter

### ISSUE THREAD

**Issue by drennvinn** [api-platform/core#5407]
**Description**  
I think having to accumulate query params is quite annoying for some use cases with the SearchFilter.
for my personal use, I created a custom filter in order to solve this problem but It would be great if this feature could be implemented directly in the SearchFilter (or create a new one like MultipleFieldSearchFilter 😅)
the syntax could look like this: 
```php
#[ApiFilter(MultipleFieldSearchFilter::class, arguments: ['parameterName' => 'search'], properties: [
    "title" => "partial",
    "description" => "partial",
    "author.firstName" => "exact",
    "author.lastName" => "exact",
    ...
])]
```

**Comment by soyuka** [comment]
#2400
