### ISSUE TITLE
PropertyFilter generated description isn't shown as parameter description in openapi

### ISSUE THREAD

**Issue by frankdekker** [api-platform/core#5415]
**API Platform version(s) affected**: 3.1.2

**Description**  
In the `PropertyFilter.php::getDescription` method a nice description is generated, but this message doesn't appear in openapi docs.
![image](https://user-images.githubusercontent.com/2179983/221001240-61055c02-27ec-4911-b1c5-cad4502bb08c.png)

**How to reproduce**  
Create resource with GetCollection and add a PropertyFilter
```php
#[ApiResource(operations: [new GetCollection(security: 'is_granted("USER")')])]
#[ApiFilter(PropertyFilter::class, arguments: [])]
```
The parameter description of this field isn't displayed in openapi docs

**Possible Solution**  
In `OpenApiFactory.php::getFiltersParameters` the description is retrieved for each filter. There the property `$data['description']` is used as description for the filter. The `PropertyFilter.php` however returns $data['openapi']['description'] and $data['swagger']['description']. These properties aren't used and get lost. A solution would be to also set the `$data['description']` property in PropertyFilter.

**Comment by soyuka** [comment]
it should return `description` we want to avoid the openapi/swagger keys. There's a refactor needed on every filters for that matter.

**Comment by nawel-les-tilleuls** [comment]
I take this issue
