### ISSUE TITLE
PUT return 201 without ReadListener enabled

### ISSUE THREAD

**Issue by tyx** [api-platform/core#5417]
**API Platform version(s) affected**: 3.1.2

**Description**  

Since the merge of https://github.com/api-platform/core/pull/4996 we are in a difficult situation without efficient workaround ATM.

In our API and because we are full CQRS, we don't use `ReadListener` for `PUT` operation.
We are ok that we are living on the edge but we are pretty happy with our combination of APIP and our architecture. And latest change in APIP3 were so great for us.

But with those lines added : 
https://github.com/api-platform/core/blob/9b4b58ca0113a2645b58a116fe9e4bf200df8aa3/src/Symfony/EventListener/RespondListener.php#L93-L95

All our `PUT` operation return now `201`... And we have no way to get back the old behavior via the new `standard_put` properties.

**How to reproduce**  

Create a PUT operation without ReadListener

**Possible Solution**  

- We could update manually our `PUT` operations to manually add status: 200. But I should admit I'm scared that we could forget one (now or in the future) that could lead to break someting in prod.
- Is there a world where the lines updated above could rely also to an additionnal condition where we could act on it ? Like allowCreate ?

We are open to any solid solution that would involve to add some custom code in our codebase of course.

**Comment by soyuka** [comment]
We should add `allowCreate` on that condition, would that work?

**Comment by tyx** [comment]
It seems to me the best compromise if this option has a default value of false.

**Comment by soyuka** [comment]
yeah this option has a default value of `false` and will stay in API Platform 4.x + its value won't be `true` would you be able to patch that (on 3.1)?

**Comment by tyx** [comment]
Sounds perfect ! I'm ok to patch that of course. Seems a great TGIF work ;)
