### ISSUE TITLE
When compatibility elasticsearch/elasticsearch 8.*

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#5430]
**Description**  

Attempting to upgrade my ElasticSearch to 8.6 I found out that `api-platform/core` is not compatible with elasticsearch/elasticsearch >= 8.0

Do you have a time frame to allow for current versions of ElasticSearch ( and elasticsearch/elasticsearch of course)?

         "conflict": {
                "doctrine/common": "<3.2.2",
                "doctrine/dbal": "<2.10",
                "doctrine/mongodb-odm": "<2.4",
                "doctrine/orm": "<2.14.0",
                "doctrine/persistence": "<1.3",
                "elasticsearch/elasticsearch": ">=8.0",
                "phpspec/prophecy": "<1.15",
                "phpunit/phpunit": "<9.5",
                "symfony/service-contracts": "<3",
                "symfony/var-exporter": "<6.1.1"
            },

**Example**

**Comment by alanpoulain** [comment]
We don't have this compatibility on our roadmap, but we are open to a PR or a sponsoring.

**Comment by BernardA** [comment]
Reading that, my interpretation is that you are effectively dropping support for ElasticSearch altogether, which would be disappointing. 
It certainly does not seem to be a priority for you.
So, ES being a feature that was determinant in the choice of API-Platform it makes us wonder the long-term prospect of our choice.

**Comment by alanpoulain** [comment]
We are not dropping it but it's a low priority indeed. I could be wrong though, @dunglas will have a better insight than me.

**Comment by dunglas** [comment]
@alanpoulain is entirely right. API Platform is a community project with a limited workforce. We do want to support newer versions of ES and we'll be glad to merge a patch adding doing this.

If it's urgent and you cannot contribute such patch, it's indeed possible to hire or sponsor contributors to do the work.

**Comment by soyuka** [comment]
ES is really hard because their maintenance of the package follows the version of the Elasticsearch Server. Indeed, if we put the 8.x version, we constraint every user to upgrade to ES 8 and it may not be that easy to do, especially for production apis. I have no correct solution for this so that it helps users that wants to move on and doens't block users from upgrading because they're still on 7.x. 

Now it is so easy to add your own providers to make such compatibility you'd be better just creating your providers instead of waiting for us to find an impossible solution for everyone.

**Comment by BernardA** [comment]
@soyuka  I am by no means an ES expert, so I will not dwell on the challenges you mentioned concerning keeping it current. I just mention that `elasticsearch/elasticsearch` seems to handle that well.

I am trying to understand your point about creating our own providers. There are two aspect of ES: creating/populating the indices and reading. `elasticsearch/elasticseach` is used for the former and API-Platform for the latter from the developer perspective. 

So, the above mentioned conflict blocks us from upgrading to `elasticsearch\elasticsearch` 8.* and thus creating/populating the indices using ES 8.* .

Unless you are proposing to ignore `elasticsearch/elasticsearch` altogether and create our own providers both for creating/populating the indices and another one for reading. That would, I believe, imply creating our own 'homemade" version of `elasticssearch/elasticsearch`, which I would not qualify as easy. 

Could you please elaborate on your proposal?

@dunglas The other point concerns ES support for version 7.17 ( our current one ) which, according to [this](https://www.elastic.co/support/eol) will end at 08/2024. At that point, do you plan to provide support for 8.*?
Or are you going to let it become obsolete if you do not get this somehow done by the community?

**Comment by soyuka** [comment]
I agree that our `"elasticsearch/elasticsearch": ">=8.0"` conflict is not good, but if you install the `8.x` version our code will break, so what solution do we have? 

I have a suggestion:

1. remove the conflict from the api-platform composer
2. find a class that was introduced in `elasticsearch/elasticsearch:8.x` and with a `class_exists` we change the `registerElasticsearchConfiguration` and if the version is not compatible we do not load `elasticsearch.xml`. 

https://github.com/api-platform/core/blob/main/src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L711-L728 

Would you be able to work on this to help?

**Comment by BernardA** [comment]
hmm before we get into my ability to help with that, let me try to understand what would that accomplish. 

I think it is clear that one would be able to install `elasticsearch/elasticsearch` 8.* and thus create/populate indices.

But the implication would seem to be that API-Platform would have zero support for ES as such. Correct?

Then how about the reading part?

Of course we can read directly using the `elasticsearch/elasticsearch` client and controller/services ( as we partially do today ), but how would we go about doing that in the context of API-Platform? Regular entities/models plus providers and 100% custom filters?

**Comment by soyuka** [comment]
This is the problem, I'm not sure to know what is and what is not compatible. The only thing we do to read data with ES is at:

https://github.com/api-platform/core/blob/main/src/Elasticsearch/State/ItemProvider.php 

For filters we just add some things to the request body we sent to ES: https://github.com/api-platform/core/blob/main/src/Elasticsearch/State/CollectionProvider.php#L52 this should still work as there's nothing ES-related, except if request bodies did change in 8.x. 

If I check the [backward incompatible changes](https://github.com/elastic/elasticsearch-php#backward-incompatible-changes-boom) of the elasticsearch library I see a few things that impact us:

- we changed the namespace, now everything is under Elastic\Elasticsearch 
Almost sure we're impacted, handling the BC is not impossible but I don't have the time right now (and at least until may/june) but I can help you do this.

- we used the [elastic-transport-php](https://github.com/elastic/elastic-transport-php) library for HTTP communications; 
- we changed the Exception model, using the namespace Elastic\Elasticsearch\Exception. All the exceptions extends the ElasticsearchException interface, as in 7.x

Probably impacted within the providers but the impact is quite easy to handle.

**Comment by BernardA** [comment]
Thanks. I believe I know enough now so as to discuss this internally. I will get back to you soon as we make a determination on how to proceed.

**Comment by BernardA** [comment]
@soyuka Getting back to you on this. Folks internally decided to stick to ES 7 for now. I would be willing to contribute in bringing it up to ES 8 on my own time, meaning that it would take a while to get it done. Let me know whether or not you want to proceed with this.

**Comment by sidz** [comment]
Hi guys,

What about to move out elasticsearch support to independent package which could be installed whenever it needed instead of everything in one metapackage if you have limited workforce?

WDYT @soyuka, @alanpoulain, @dunglas?

**Comment by sidz** [comment]
PR is almost ready https://github.com/api-platform/core/pull/5503 Just need to solve one open question https://github.com/api-platform/core/pull/5503#discussion_r1150651833

Any suggestions are welcome

**Comment by soyuka** [comment]
also @BernardA would love your review as well thanks will look into it asap. Note that `main` will be out as `3.2` this summer. We'll also move that to its own component I'll give you the insights on how to do this asap.
