### ISSUE TITLE
Decorating SchemaFactory and getting the definition name for a resource class?

### ISSUE THREAD

**Issue by gremo** [api-platform/core#5436]
I'm trying to add dynamic properties to a resource, based on the presence of PHP attributes. The following example omits the part of reading attributes of `$className`.

I've decorated the `api_platform.json_schema.schema_factory` and I'm able to get the definition name `Product-product.read` and add the `foo` property. However, this is not dynamic. I see that the original factory uses [`buildDefinitionName`](https://github.com/api-platform/core/blob/main/src/JsonSchema/SchemaFactory.php#L224) which is private and can't be invoked.

I don't want to just copy & paste that method, expecially when things could change in the future.

What I'm missing here? Is there any other way for adding properties to the OpenAPI documentation?

```php
namespace App\OpenApi;

use ApiPlatform\JsonSchema\Schema;
use ApiPlatform\JsonSchema\SchemaFactoryInterface;
use ApiPlatform\Metadata\Operation;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;

#[AsDecorator(decorates: 'api_platform.json_schema.schema_factory')]
class SchemaFactory implements SchemaFactoryInterface
{
    public function __construct(
        private readonly SchemaFactoryInterface $decorated
    ) {
    }

    public function buildSchema(
        string $className,
        string $format = 'json',
        string $type = Schema::TYPE_OUTPUT,
        ?Operation $operation = null,
        ?Schema $schema = null,
        ?array $serializerContext = null,
        bool $forceCollection = false
    ): Schema {

        $retval = $this->decorated->buildSchema(
            $className,
            $forceCollection,
            $type,
            $operation,
            $schema,
            $serializerContext,
            $forceCollection
        );

        if (isset($retval->getDefinitions()['Product-product.read'])) {
            $retval->getDefinitions()['Product-product.read']['properties']['foo'] = [
                'readOnly' => true,
                'type' => 'string',
                'nullable' => true,
            ];
        }

        return $retval;
    }
}
```

**Comment by soyuka** [comment]
Hi, indeed this is quite a hard problem as the definitions may vary if you have groups and/or different formats. 

My suggestion would be to add your new property to our `ProperytNameCollectionFactory` and the `PropertyMetadataFactory`, as these are the extension points used by the Schema Factory:

https://github.com/api-platform/core/blob/main/src/JsonSchema/SchemaFactory.php#L122 

Could you maybe explain the use case with more details? Maybe that I have a better solution for you.

**Comment by gremo** [comment]
Sure @soyuka thanks!

My specific use case is the following: I created at `ImagineFilter` PHP attribute that can be applied to an exisisting property, i.e:

```php
#[ApiResource]
class Product
{
    #[ORM\Column(nullable: true)]
    #[ImagineFilter(filter: 'thumb_200', outputName: 'imageUrlThumb200', description: 'URL of the 200px thumb.')]
    private ?string $imageUrl = null;
}
```

Then in the `normalize` function ([custom normalizer](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data)) I'll check for the attribute, read `$imageUrl` and output a new property named `outputName` (the result is the application of [imagine filter](https://symfony.com/bundles/LiipImagineBundle/current/filters.html) to that property).

It works perfectly well, but of course the new property named `outputName` isn't documented!

As as workaround I've changed the logic and added a new property (which would be filled reading `fromProperty`), and this is of course documented:

```php
#[ApiResource]
class Product
{
    #[ORM\Column(nullable: true)]
    private ?string $imageUrl = null;

    #[ORM\Column(nullable: true)]
    #[ImagineFilter(filter: 'thumb_200', fromProperty: 'imageUrl ')]
    #[ApiProperty(description: 'URL of the 200px thumb.')]
    private ?string $imageUrlThumb200 = null;
}
```
