### ISSUE TITLE
[v3] Operation "_api_/xxx{._format}_get_collection\" not found for resource 

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/core#5438]
**API Platform version(s) affected**: 3.1.3, 2.7.10 (3.1.2 works well). The bug was introduced here: https://github.com/api-platform/core/commit/268c274e0280a9200172ae114e95b8b700a3c098#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4fR118-R121

**Description**  

After upgrading from 3.1.2 to 3.1.3 due to Security Vulnerability (https://github.com/advisories/GHSA-vr2x-7687-h6qv which is fixed in https://github.com/api-platform/core/commit/5723d68369722feefeb11e42528d9580db5dd0fb), operations, declared on base class of [Class Table Inheritance](https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/inheritance-mapping.html#class-table-inheritance) no longer work

**How to reproduce**  
In order to reproduce the issue, we need just 2 classes from the Doctrine's example of Class Table Inheritance. 

Base class `Person` (it is an API resource):

<details>
<summary>Person.php</summary>

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity()]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'discr', type: 'string')]
#[ORM\DiscriminatorMap(['employee' => Employee::class])]
#[ApiResource(
    operations: [
        new GetCollection(),
    ]
)]
abstract class Person 
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

```

</details>

and child class `Employee` which extends `Person`. This is also an API resource (it's important).

<details>
<summary>Employee.php</summary>

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity()]
#[ApiResource(
    operations: [
        new Get(),
    ]
)]
class Employee extends Person
{
}

```

</details>

Since we have `GetCollection` on a base class, we can call `/api/people` endpoint (`people` is a plural of `person`) to get all children of `Person` class - in our case it's just an `Employee`.

To reproduce the bug, there should be 1 record in DB to run normalization process.

What is the cause introduced in 3.1.3 comparing o 3.1.2?

The cause are these lines:

https://github.com/api-platform/core/blob/a93573d70f8e52c71aa2447e35415d25bb5cfe25/src/Serializer/AbstractItemNormalizer.php#L118-L120

If I remove them - everything works as expected, just like in 3.1.2.

Since `$context['operation']` is removed in the lines above, later in the flow this `if` statements returns `false` and the code tries to find operation in `ResourceMetadataCollection`, which fails. 

https://github.com/api-platform/core/blob/a93573d70f8e52c71aa2447e35415d25bb5cfe25/src/Serializer/AbstractItemNormalizer.php#L558-L561

> ***Warning***
> `ResourceMetadataCollection` for resource `Employee` (child) has no data for operation name `"_api_/people{._format}_get_collection"` of base class `Person`, this is why it fails.

**Possible Solution**  

I have no experience to understand a good solution, but at least the cause is known. Should `ResourceMetadataCollection` know about base class operations?

**Additional Context**  

![image](https://user-images.githubusercontent.com/3725595/223688906-35504647-610c-4e09-8017-4024acd7c5dd.png)

**Comment by yassinehamouten** [comment]
Hello @maks-rafalko,
I'm facing the same issue.
Did you find something to solve this issue without modifying APIP core ?

**Comment by maks-rafalko** [comment]
Not really, we just downgraded back to 3.1.2 unless we have a proper fix (in 3.1.4 I guess). 

But if you really need 3.1.3 - you can probably override [this method](https://github.com/api-platform/core/blob/a93573d70f8e52c71aa2447e35415d25bb5cfe25/src/Serializer/AbstractItemNormalizer.php#L102) by your own normalizer and remove the lines I highlighted in my first message.

**Comment by yassinehamouten** [comment]
I think we will also downgrade to 3.1.2 :/

Thank you Maks

**Comment by soyuka** [comment]
I'll check this asap, best is to provide a PR with a failing behat test case so that I can fix that in a jinx and release it by friday! Thanks everyone and sorry for breaking this!

**Comment by soyuka** [comment]
Fix incoming, releasing tomorrow please @CODEheures upgrade to 3.x it's a pain to maintain 2.7 but I'll add the patch there also :D.

**Comment by soyuka** [comment]
can you test this: 
https://github.com/api-platform/core/pull/5447/commits/dd9499ec7a58ac058b52c8258904c2cc6c812c79#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4f ?

**Comment by maks-rafalko** [comment]
> can you test this: [dd9499e#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4f](https://github.com/api-platform/core/commit/dd9499ec7a58ac058b52c8258904c2cc6c812c79#diff-d87efa25fbf52904daa06047002652f08645e3ad4a7f4985ffeec5a7c8e39c4f) (obviously whenever you can no hurry on my end :)) ?

It works, our tests are green with this patch!
