### ISSUE TITLE
Fix vulnerability in 2.6

### ISSUE THREAD

**Issue by ivanmunozruiz** [api-platform/core#5441]
Do we have an option to fix this issue [GHSA-vr2x-7687-h6qv](https://github.com/api-platform/core/security/advisories/GHSA-vr2x-7687-h6qv) in version 2.6? so as not to be forced to update to 2.7 with everything that entails

thank you!

**Comment by soyuka** [comment]
not maintained anymore, we couldn't reproduce the security issue in that branch I think you'll be fine.
