### ISSUE TITLE
The ValidateListener isn't invoked when the controller property is set. Undocumented?

### ISSUE THREAD

**Issue by gremo** [api-platform/core#5445]
**API Platform version(s) affected**: 3.1.2

**Description**  
The `ValidateListener` isn't invoked when the controller property is set.

**How to reproduce**  

Create an API resouce like this:

```php
#[ApiResource(uriTemplate: '/qr-codes')]
#[Post(
    input: QrCodeCreateInputDto::class,
    controller: CreateQrCode::class,
)]
class QrCode
{
}
```

Create a `QrCodeCreateInputDto` class with some validation constraints, then send a wrong/invalid payload. **As soon as you comment out `controller`, the validation kicks-in.**

Is this a feature? A bug? Simply undocumented?

**Comment by soyuka** [comment]
If you use the controller you skip all of the API Platform features, don't use a controller use a `Provider` or a `Processor` instead. This is valid since API Platform 1.

**Comment by gremo** [comment]
Thanks for the clarification. But using a processor I cannot access the request. Can you point me to the right direction?

**Comment by soyuka** [comment]
inject the RequestStack ? https://symfony.com/doc/current/service_container/request.html

**Comment by gremo** [comment]
Thanks but no. Api Platform should allow it by default. I'll go for listerners 😉
