### ISSUE TITLE
Elasticsearch deprecation

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#5446]
**API Platform version(s) affected**: 3.1

**Description**  
To avoid index calls to ES for doctrine entities on cache build you can define `elasticsearch: false` on your ApiResource which is documented in https://api-platform.com/docs/core/elasticsearch/#creating-models and added in https://github.com/api-platform/core/pull/5177 but this triggers this deprecation https://github.com/api-platform/core/blob/main/src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php#L53

Only on false a no index call is performed https://github.com/api-platform/core/blob/main/src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php#L101.  So not sure how we can fix this deprecation?

Also the index name in hasIndices is now from the shortName, but should it not something like this?

```
        $options = $operation->getStateOptions() instanceof Options ? $operation->getStateOptions() : new Options(index: $this->getIndex($operation));

        try {
            $this->client->cat()->indices(['index' => $options->getIndex() ?? $this->getIndex($operation)]);

            return true;
        } catch (Missing404Exception|NoNodesAvailableException) {
            return false;
        }

    private function getIndex(Operation $operation): string
    {
        return Inflector::tableize($operation->getShortName());
    }
```

**How to reproduce**  
```
#[ApiResource(
    elasticsearch: false
)]
```

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/main/tests/Fixtures/Elasticsearch/Model/Book.php

**Comment by soyuka** [comment]
Don't use `elasticsearch` anymore, use something like this:

```
use ApiPlatform\Elasticsearch\State\CollectionProvider;
use ApiPlatform\Elasticsearch\State\ItemProvider;

#[ApiResource(operations: [new Get(provider: ItemProvider::class), new GetCollection(provider: CollectionProvider::class)], normalizationContext: ['groups' => ['book:read']])]
```

You can even create your own ES resources and use them to avoid repetition:

```
use ApiPlatform\Elasticsearch\State\ItemProvider;

# declare this as attribute
class ElasticGet extends Get {
  __construct(provider: ItemProvider::class);
}
```

**Comment by dannyvw** [comment]
I use that configuration for the ES ApiResource which works fine. I only configured `elasticsearch: false` for disabling the index check for all other ApiResources.

**Comment by soyuka** [comment]
We should fix this, you shouldn't need to disable elasticsearch on other api resources and this class shouldn't even been hit.

**Comment by soyuka** [comment]
Suggestion:

```
if (null !== $elasticsearch && $this->hasIndices($operation)) {
    $operation = $operation->withElasticsearch(true);
}
```

https://github.com/api-platform/core/blob/main/src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php#LL55-L57C22

**Comment by dannyvw** [comment]
@soyuka Your suggested change works for all ApiResources. So non ES and ES resources are not checked with this change.

**Comment by soyuka** [comment]
My bad you  need to use the `HttpOperation` :). Would my fix resolve your issue?

**Comment by dannyvw** [comment]
@soyuka Yes!
