### ISSUE TITLE
[V2] AccessDeniedException throw 500 error

### ISSUE THREAD

**Issue by polc** [api-platform/core#545]
When I throw an AccessDeniedException in a listener, I get an 500 HTTP error.

Maybe a 403 HTTP error would be better?

**Comment by teohhanhui** [comment]
I've always got 403 when I throw `Symfony\Component\Security\Core\Exception\AccessDeniedException`.

**Comment by polc** [comment]
oh my bad.. the correct exception to throw is `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException`

**Comment by teohhanhui** [comment]
The short answer is: it depends.

**Comment by teohhanhui** [comment]
`Symfony\Component\Security\Core\Exception\AccessDeniedException` is caught by the Symfony Security firewall and converted into `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException`. In most cases you should be throwing `Symfony\Component\Security\Core\Exception\AccessDeniedException`.

**Comment by polc** [comment]
That's weird because in my case, if I throw a `Symfony\Component\Security\Core\Exception\AccessDeniedException ` in the `'kernel.view'` event then I got a 500.. and the exception is uncatched

**Comment by teohhanhui** [comment]
It sounds like something wrong with your Symfony Security setup...

**Comment by polc** [comment]
oh yea you're right.. thanks^^
