### ISSUE TITLE
Skolem IRI generated for GetCollection operation with custom item DTO

### ISSUE THREAD

**Issue by jelovac** [api-platform/core#5478]
**API Platform version(s) affected**: 3.1.5

**Description**  
Upgrading a project based on API Platform from v2.6 to v3. I have noticed a different behavior with IRI generation on GET Collection ORM resource which has custom DTO output. 

Prior to the upgrade the collection DTO output was generated using DataTransformers. For each item in the collection a DataTransformer logic run and returned the generated DTO. Afterwards during the serialization process the IRI (@id) attribute was appended to each item in the collection and it matched the IRI of the original GET item resource endpoint.

Now since DataTransformers are gone in v3, I have updated the code by creating a State Provider for the ORM Resource.

In the State Provider I am calling a decorated ORM Collection provider to return the collection of resources and then iterate through collection and generate custom DTO which I then return as collection/array of DTO's.

This works, but the issue I am currently having is that in the returned collection the @id is no longer IRI which matched GET item operation and instead it is a SKOLEM iri and looks like this:

```
 "@id": "\/.well-known\/genid\/f7d121a82bc5eb4fd775",
```

**How to reproduce**  

1. Create an ORM Resource with the following GetCollection operation:

```
        new GetCollection(
            name: 'get_custom_book_outputs',
            uriTemplate: '/books/custom_outputs',
            provider: BookCustomOutputCollectionProvider::class,
            output: BookCustomOutput::class,
        ),
```

2. Create a State Provider `BookCustomOutputCollectionProvider::class`

For example:

```
final class BookCustomOutputCollectionProvider implements ProviderInterface
{
    public function __construct(
        private readonly ProviderInterface $decorated,
    ) {
    }

    /**
     * @param array<mixed> $uriVariables
     * @param array<mixed> $context
     *
     * @return array<int,BookCustomOutput>
     */
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): array
    {
        $books = $this->decorated->provide($operation, $uriVariables, $context);

        $data = [];

        foreach ($books as $book) {
            $data[] = $this->createDto($book);
        }

        return $data;
    }

    private function createDto(Book $object): BookCustomOutput
    {
       $dto = new BookCustomOutput();
       
       $dto->id = $object->id;
       $dto->name = $object->name;
   
        return $dto;
    }
}
```

3. Register the state provider in services.{php|yml}

```
    $services
        ->set(BookCustomOutputCollectionProvider::class)
        ->bind(
            '$decorated',
            service('api_platform.doctrine.orm.state.collection_provider')
        );
```

4. Call the collection deponent

**Possible Solution**  

So what I want to achieve is to generate the IRI in the same way as it was generated prior the upgrade to new MetaData system for the custom collection output.

One of the solutions is to turn the DTO into a Resource. However doing that I would loose the flexibility of the built in ORM Extensions as I would not be able to use decorated ORM Collection Provider for a non existent ORM Resource and instead would have to create complete state provider logic.

**Comment by soyuka** [comment]
Just declare you `GetCollection` on `BookCustomOutput`
