### ISSUE TITLE
Entity not found cause error 500

### ISSUE THREAD

**Issue by theofidry** [api-platform/core#549]
When submitting a POST request to create a new form with an inexistent entity in the body, this cause a 500 error instead of a 400 one.

Originally reported by @aledeg in https://github.com/api-platform/api-platform/issues/88.

**Comment by teohhanhui** [comment]
So this is due to the use of `EntityManagerInterface::getReference` with an invalid (non-existent) id...

**Comment by teohhanhui** [comment]
We need to catch the `Doctrine\ORM\EntityNotFoundException`

**Comment by theofidry** [comment]
Yep, sorry I don't have the time to really look in the code and provide a fix right now :/

**Comment by soyuka** [comment]
I could work on a fix asap, just need some review on #552 first.
