### ISSUE TITLE
Cannot declare GetCollection subresource on ManyToMany relation

### ISSUE THREAD

**Issue by jelovac** [api-platform/core#5496]
**API Platform version(s) affected**: 3.1.5

**Description**  
Declaring a Sub Resource on entity property which has Doctrine ManyToMany relationship causes the following error:

```
[Semantical Error] line 0, col 469 near 'books IN': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected.
```

**How to reproduce**  

1. Create two ORM Resources: Book and Store.

2. On both of these entities create a ManyToMany relationship

```
// Store.php

    #[ORM\ManyToMany(targetEntity: Book::class, inversedBy: 'stores')]
    private Collection $books;
    
// Book.php

     #[ORM\ManyToMany(targetEntity: Store::class, mappedBy: 'books', fetch: 'EXTRA_LAZY')]
    private Collection $stores;
```

3. Define a SubResource on Store entity

```
#[ApiResource(
    uriTemplate: '/books/{id}/stores',
    uriVariables: [
        'id' => new Link(
            fromClass: Book::class,
            fromProperty: 'stores',
        ),
    ],
    operations: [
        new GetCollection(),
    ],
)]
```

**Possible Solution**  

I have searched the issue tracker and could be related to #5341 and #5075.

As suggested in #5341 I have attempted to add #Link[] on the inverse side of ManyToMany field however it doesn't work. I am using Doctrine ORM with MySQL.

```
// Book.php

     #[Link(toProperty: 'books')]
     #[ORM\ManyToMany(targetEntity: Store::class, mappedBy: 'books', fetch: 'EXTRA_LAZY')]
    private Collection $stores;
```

**Comment by soyuka** [comment]
You should probably create your own provider as it is a hard problem, we have an example on a ManyToMany on our https://github.com/api-platform/core/blob/ccef472cade42b189fa8cb7793e27fad1349e289/tests/Fixtures/TestBundle/Entity/RelatedDummy.php#LL47C43-L47C58 fixture maybe that this can help.

**Comment by jelovac** [comment]
Not 100% sure yet but it seems that the issue is gone.

I basically had to add to the SubResource delcaration both from* properties and to* properties:

So this seems to work:

```
#[ApiResource(
    uriTemplate: '/books/{id}/stores',
    uriVariables: [
        'id' => new Link(
            fromClass: Book::class,
            fromProperty: 'stores',
            toClass: self::class,
            toProperty: 'books'
        ),
    ],
    operations: [
        new GetCollection(),
    ],
)]
```

**Comment by crbanman** [comment]
I've actually just run into the exact same issue converting from v2 to v3.

Previously, the `#[ApiSubresource]` annotation would allow for pretty seamless retrieval of properties that were part ManyToMany relationships. Now, it seems you can only do the same on the inverse side of the relationship but not the owning side like in @jelovac's example.

I know the switch from the old subresource system to the new is a complete re-write so not all features will work the same, but it does seem incomplete if it can't support at least GetCollection operations from both sides of a ManyToMany relationship.

Is there any way we can work towards adding support for this, or any idea of where to start?
