### ISSUE TITLE
Using the new entityClass option with a custom provider 

### ISSUE THREAD

**Issue by mrossard** [api-platform/core#5510]
**API Platform version(s) affected**: 3.1.6

**Description**  
I can't get this new option to work as intended while using a custom provider. Either the Get() operation or the GetCollection() is broken.

**How to reproduce**  
https://github.com/mrossard/apip-entityclass

This version gets "The class 'App\\ApiResource\\DetachedResource' was not found in the chain configured namespaces App\\Entity" when you call the Get() operation. Comment the `uriVariables: ['id']`  and you get `Unable to generate an IRI for the item of type \"App\\ApiResource\\DetachedResource\`` on the GetCollection() operation.

**Possible Solution**  
In ApiPlatform\Api\IdentifiersExtractor, if you replace line 136
``` php
 throw new RuntimeException('Not able to retrieve identifiers.');
```
with
``` php
return $this->resolveIdentifierValue($this->propertyAccessor->getValue($item, $property), $property);
```
you seem to get the expected result (on the version without the explicit uriVariables).

**Comment by DartCZ** [comment]
This solution fixing issue #5502

**Comment by SergeyCherenkov** [comment]
If the related entity also has an [ApiResource], then I also get `Unable to generate an IRI for the item of type`. 
https://github.com/api-platform/api-platform/issues/2334#issuecomment-1512618993
This solution works, but it still seems to me that this should not be.
