### ISSUE TITLE
AddLinkHeaderListener always adds a link to docs

### ISSUE THREAD

**Issue by bashilbers** [api-platform/core#5528]
**API Platform version(s) affected**: all

**Description**  
[AddLinkHeaderListener.php](https://github.com/api-platform/core/blob/main/src/Hydra/EventListener/AddLinkHeaderListener.php) always adds a link to the api docs, even if enable_docs is false.

**How to reproduce**  

Set enable_docs to false. Your application will fail because the request listener will try to generate a url for a route that does not exist.

**Possible Solution**  

Inject the configuration value and check properly if the documentation exists before generating a link to it.

**Additional Context**

**Comment by Romaixn** [comment]
Hello @bashilbers! The error you mentioned in your issue, is it indeed related to retrieving the contexts of an entity? For example, using the URL `/contexts/Book`? Or does the mentioned bug appear elsewhere?
