### ISSUE TITLE
question about using the kernel.view event to persist entites

### ISSUE THREAD

**Issue by BenoitLeveque** [api-platform/core#554]
Hi, that's not an issue just a question.

it's seem weird to me to persist entities change or alter entities inside the kernel.view events in POST and PUT context.

Why not doing this directly inside the action and provide some entry point with pre and post event ?

**Comment by theofidry** [comment]
Doing things in the action is what was done in 1.x. However having a more event oriented flow makes it more flexible and customizable. For example, if you don't want to use doctrine or change the way entities are persisted, you can easily do so by overriding the `api_platform.jsonld.listener.view.responder` service.

**Comment by BenoitLeveque** [comment]
ok, thanks for your answer, still a bit weird to use the kernel.view event and not a custom event to handle persisting and other non-view related stuff

**Comment by theofidry** [comment]
It is, but 1.x taught us that it's way simpler and powerful that way :)

**Comment by teohhanhui** [comment]
`kernel.view` is badly named. It should actually be "post-controller".
