### ISSUE TITLE
TypeError: Nelmio\ApiDocBundle\Describer\ApiPlatformDescriber::__construct(): Argument #1 ($documentation) must be of type ApiPlatform\Documentation\DocumentationInterface, ApiPlatform\OpenApi\OpenApi given

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#5547]
**API Platform version(s) affected**: ^3.1.6

**Description**  

With ApiPlatform v.3.1.6, in NelmioApiDocBundle we receive this error:

> TypeError: Nelmio\ApiDocBundle\Describer\ApiPlatformDescriber::__construct(): Argument #1 ($documentation) must be of type ApiPlatform\Documentation\DocumentationInterface, ApiPlatform\OpenApi\OpenApi given, called in /srv/app/var/cache/test/ContainerU6TwUpp/getNelmioApiDoc_Describers_ApiPlatformService.php on line 24

**How to reproduce**  

Install `api-platform/core` and try to generate the documentation through `NelmioApiDocBundle`.

**Possible Solution**  

A possible fix was made in `NelmioApiDocBundle`, but it seems not be sufficient as the `DocumentationInterface` is used in many places.

See https://github.com/nelmio/NelmioApiDocBundle/pull/2092

**Additional Context**  

I suppose the sub-tree split done in `3.1.6` broke the code.

**Related issues**
https://github.com/nelmio/NelmioApiDocBundle/issues/2089

**Comment by Aerendir** [comment]
This issue is not stale.

There is a similar [issue on NelmioApiDoc](https://github.com/nelmio/NelmioApiDocBundle/issues/2089) and also a [PR to fix it](https://github.com/nelmio/NelmioApiDocBundle/pull/2092).

No one is replying.

Anyway, this should have been considered a breaking change and not included in a minor release: this is causing a lot of issues and impossibilities to update dependencies.

**Comment by GuilhemN** [comment]
This was fixed in NelmioApiDocBundle.
Although theoretically it's a bc break in API platform I think it's not much for most users and this can be closed.

**Comment by dunglas** [comment]
Thanks!!
