### ISSUE TITLE
Support for Symfony 5.4 (LTS) 

### ISSUE THREAD

**Issue by ZZromanZZ** [api-platform/core#5549]
**Description**  
As Symfony 6.4 (LTS) was not relesed yet. And current LTS version is still 5.4, ApiPlatfrom should support at least current LTS version of Symfony.

I believe, those who upgrades to LTS version only, considering this as a must.

**Comment by silverbackdan** [comment]
Believe you can use 2.7 for Symfony LTS support which is still getting updates and fixes.

**Comment by ZZromanZZ** [comment]
Considering Symfony 5.4 still as stable, we cannot run stable ApiPlaform version on stable Symfony version.

**Comment by mrossard** [comment]
> Considering Symfony 5.4 still as stable, we cannot run stable ApiPlaform version on stable Symfony version.

Yes you can, SF 6.2 is stable too. What is not available is a LTS version of Api Platform. The best you can get is 2.7 if you want to use an "outdated" LTS symfony version.

**Comment by soyuka** [comment]
5.4 is usable with 2.7, 3.1 is usable with 6.x

**Comment by ZZromanZZ** [comment]
@soyuka Is planned to (somehow) support 2.7 to next SF LTS (6.4) ?

**Comment by soyuka** [comment]
no 2.7 is maintained only for security fixes, upgrade to 3.1.

**Comment by ZZromanZZ** [comment]
For those who jump only on SF LTS is such situation unsolvable. Especially when 2.7 won't get any updates and SF 6.4 will be still unreleased. As far as i know, such approach is not very common accros SF ecosystem. At least, an official statement to this situation in documentation would be nice.

**Comment by mrossard** [comment]
> For those who jump only on SF LTS is such situation unsolvable. Especially when 2.7 won't get any updates and SF 6.4 will be still unreleased. As far as i know, such approach is not very common accros SF ecosystem. At least, an official statement to this situation in documentation would be nice.

Seems weird to me to wait for LTS to upgrade to the latest supported version...future migration to LTS is supposed to be painless.

**Comment by silverbackdan** [comment]
I would also agree, using Symfony 6.x has a backwards compatibility promise right up to the next LTS. I imagine you are familiar with the Symfony release process? As such, there is no real reason, as far as I can tell, to start a brand new project on Symfony 5.

**Comment by soyuka** [comment]
We though about an LTS version of API Platform but it's hard to do it for free... I'm not sure I understand your situation @ZZromanZZ

**Comment by ZZromanZZ** [comment]
@soyuka I hoped that dropping SF 5.4 was premature step without any severe technical reasons (I can be wrong, I have no deep insight to ApiPlatform) and time perspective from maintenance point of view also crossed my mind.

To clarify my situation, SF non LTS version has pretty short maintenance window. Imagine situation you upgrade to Symfony 6.2 (now it's current stable, and 6.4 LTS still not available) on large project, and after some months for 6.2 ends without any support (security upgrades included), 6.4 LTS will be available but due other circumstances (time, technical reasons, subsitute whichever reason you can imagine) you cannot upgrade. And you end up on unmaintaned version of SF.  With jumping on LTS only you have much longer time span to do upgrade and don't have to upgrade so often.

Now I have two choices, first is to upgrade with all stack to 6.* and upgrade again when LTS will be released or the second not upgrade anything, stay at 2.7 until SF LTS will be released and upgrade then.

I am pretty sad with this situation, nevertheless I made my peace with that. But as I mentioned before some official statement (like "there is no planned support for LTS Symfony versions") would be nice for other people with situation like I have.

**Comment by mrossard** [comment]
The thing is, with the LTS you don't get a magical guaranted bug-free version, you still have to update it when you want to get fixes. 
And upgrading from 6.a.x to 6.4.y or from 6.4.x to 6.4.y is "the same work" since backwards compatibility is guaranteed.

**Comment by soyuka** [comment]
You can definitely see 2.7 as a stable release, security is still backported. When SF 6 LTS is out I'd advise to migrate to API Platform 3. Having 2.7 working on Symfony 6 is a really hard problem and would require a lot of time and doing that for free is impossible and has not enough added value for me. It's possible but it'd require money and time.
