### ISSUE TITLE
Allow api-platform v1.1 with symfony 3.1

### ISSUE THREAD

**Issue by BenoitLeveque** [api-platform/core#555]
Looks like they are conflits issue between api-platform v1.1.0 deps and symfony 3.1

```
Problem 1
    - api-platform/core v1.1.0 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - api-platform/core v1.1.0 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - phpdocumentor/reflection 1.0.7 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - phpdocumentor/reflection 1.0.7 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.1 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.2 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.3 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.4 conflicts with symfony/symfony[v3.1.0].
    - symfony/symfony v3.1.0 conflicts with phpdocumentor/reflection-docblock[2.0.4].
    - Installation request for symfony/symfony 3.1.* -> satisfiable by symfony/symfony[v3.1.0].
    - Installation request for api-platform/core ^1.1 -> satisfiable by api-platform/core[v1.1.0].
```

I can make a PR to allow both version (the test are passing with the new version) but i don't know all the impact of this change

**Comment by BenoitLeveque** [comment]
@dunglas i tried to update `phpdocumentor/reflection` but `phpdocumentor/reflection-docblock` 3.0 can't be used with `phpdocumentor/reflection` 3.0, i've open an issue to have a new tag in the `phpdocumentor/reflection` repository

**Comment by dunglas** [comment]
Yes this is known incompatibility issue between Symfony 3.1 and phpDocumentor v1. I don't think there is an easy way to use 1.1 with Symfony 3.1.

You can use 2.0 with Symfony 3.1 or 1.1 with Symfony 3.0...

**Comment by BenoitLeveque** [comment]
2.0 is not ready for prod ? 

I think i will keep my Symfony 2.8 and only require the serializer from 3.1

**Comment by soyuka** [comment]
> 2.0 is not ready for prod ?
It's alpha for now. I won't say it's ready for production but it's almost there ;)

+1 @dunglas I haven't managed to use symfony 3.1 with api-platform 1.x without headache (you can make it work but it'll be dependencies-unstable).
