### ISSUE TITLE
Unable to update an embedded collection relation with a PATCH operation

### ISSUE THREAD

**Issue by jonag** [api-platform/core#5559]
**API Platform version(s) affected**: 3.1.8

**Description**  

I'm trying to update an embedded relation with a PATCH operation. [Basically this use case](https://github.com/api-platform/core/blob/main/features/main/relation.feature#L368-L397) but with a PATCH instead of a PUT. However my relation is deleted and recreated instead of updated.

**How to reproduce**  

1. Create a resource with a collection. 
2. Try to update an item of this collection with a PATCH operation.

**Possible Solution**  

I tried to debug the issue. I think the issue happens because when the request reach [this line](https://github.com/api-platform/core/blob/main/src/JsonLd/Serializer/ItemNormalizer.php#L142), `$data['@id']` contains the id of my relation but `$context[self::OBJECT_TO_POPULATE]` is set and contains the entire collection instead of just the item.

If I update [this line](https://github.com/api-platform/core/blob/main/src/Serializer/AbstractItemNormalizer.php#L491) with
```php
$childContext = $this->createChildContext($context, $attribute, $format);
$childContext[self::OBJECT_TO_POPULATE] = null;
$values[$index] = $this->denormalizeRelation($attribute, $propertyMetadata, $className, $obj, $format, $childContext);
```
then the request behave as expected, but I'm **really** not sure that this is the right fix.

Please tell me if I can do anything to help fix the issue (or if I'm doing anything wrong).

**Comment by soyuka** [comment]
Hi, merge-patch specification is like this see https://datatracker.ietf.org/doc/html/rfc7386 use put or help us implementing https://datatracker.ietf.org/doc/html/rfc6902 ?

**Comment by jonag** [comment]
Hello, thank you for your answer ! I've read the specification and while it states that the array will be replaced (which I'm totally fine with), it doesn't say that the members composing it should also be replaced (well actually this use case is not documented).

I don't know if my first message was detailed enough so here is exactly what I'm doing:
1. I have [these two resources](https://gist.github.com/jonag/550732ec9e54c6a8af83b5f8b34ab4c7)
2. I create a new Store with:
```bash
curl -X 'POST' \
  'http://localhost:8000/stores' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "name": "My store",
  "pets": [
    {
      "name": "Bernie",
      "age": 2
    },
    {
      "name": "Felix",
      "age": 3
    }
  ]
}'
```
3. The store is created and the API responds with:
```json
{
  "@context": "/contexts/Store",
  "@id": "/stores/1",
  "@type": "Store",
  "name": "My store",
  "pets": [
    {
      "@id": "/pets/1",
      "@type": "Pet",
      "name": "Bernie",
      "age": 2
    },
    {
      "@id": "/pets/2",
      "@type": "Pet",
      "name": "Felix",
      "age": 3
    }
  ]
}
```
4. I want to update the age of one of my pets with:
```bash
curl -X 'PATCH' \
  'http://localhost:8000/stores/1' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "pets": [
    "/pets/1",
    {
      "@id": "/pets/2",
      "age": 4
    }
  ]
}'
```
5. The API throws an error 500 because it tries to create a new pet instead of updating the existing pet and so some of its properties are not set anymore:
```
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « name » dans la relation « pet »\nDETAIL:  La ligne en échec contient (3, 1, null, 3).",
  "trace": [...]
}
```

If I'm doing a PUT instead:
```bash
curl -X 'PUT' \
  'http://localhost:8000/stores/1' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "pets": [
    "/pets/1",
    {
      "@id": "/pets/2",
      "age": 4
    }
  ]
}'
```

it works as expected:
```json
{
  "@context": "/contexts/Store",
  "@id": "/stores/1",
  "@type": "Store",
  "name": "My store",
  "pets": [
    {
      "@id": "/pets/1",
      "@type": "Pet",
      "name": "Bernie",
      "age": 2
    },
    {
      "@id": "/pets/2",
      "@type": "Pet",
      "name": "Felix",
      "age": 4
    }
  ]
}
```

If the PATCH behaviour is intended (completely replacing the objects of the collection), why sending an existing IRI is allowed and the existing pet (`/pet/1`) reused? Shouldn't the API throws with a message saying that only nested documents are allowed?

I'm fine with using a PUT operation (actually this is what I'm doing until now on my projects) but since partial updates with PUT operations are now deprecated, I'm working on migrating to the proposed alternative (which is using a PATCH). But if not supporting this behaviour is intentional, the migration will be quite hard since asking the consummers of my API to switch from PUT to PATCH is reasonable, asking them to send the complete object (to stay with PUT) or updating each child separatly, will need a huge work from their part.

Anyway the choice is yours and I will adapt according to your decision of this subject.

**Comment by omaewh4** [comment]
Hello !

I'm facing the same issue using PATCH. I'm confused since partial updates with PUT seems already deprecated and the notice ask us to use PATCH to keep the same behaviour :

https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/DeprecationResourceMetadataCollectionFactory.php#L36
```php
$this->triggerDeprecationOnce($operation, 'extraProperties["standard_put"]', 'In API Platform 4 PUT will always replace the data, use extraProperties["standard_put"] to "true" on every operation to avoid breaking PUT\'s behavior. Use PATCH to use the old behavior.');
```

It looks like it's not the case yet ?

**Comment by ilicmsreten** [comment]
@jonag  I encounter this problem https://github.com/api-platform/core/issues/5093 and PR https://github.com/api-platform/core/issues/5093

**Comment by mrossard** [comment]
> The second query fails because the column `name` is non-nullable. It seems that API Platform tries to create a completly new store with its pets, instead of replacing the existing one. I can upload a repository with my code if it can help better understand the issue.

Well that's exactly what a standard PUT is supposed to do : create or replace a resource entirely. Sending partial data for a standard PUT is incorrect and should trigger a validation error IMO..

**Comment by jonag** [comment]
Yes I know (I was only answering @soyuka answer), and because non-standard PUT are now deprecated I'm trying to migrate to PATCH operations (the recommended solution) but it behaves the same way as a standard PUT with collections, hence the original issue.

@ilicmsreten indeed your issue is exactly the same as mine and your fix is quite similar as the one I found! I hope your PR can get merged...

**Comment by mrossard** [comment]
> Yes I know (I was only answering @soyuka question), and because non-standard PUT are now deprecated I'm trying to migrate to PATCH operations (the recommended solution) but it behaves almost the same way as a standard PUT with collections, hence the original issue.

Indeed that's actually a BC break that can't be avoided IMO -  PATCH or (standard) PUT on the resource shouldn't try to do a partial update on members of the resource, which is a problem if you're currently relying on non-standard PUT behaviour that does that.

**Comment by soyuka** [comment]
Can't you work on `localhost:8000/stores/1/pets` ?

**Comment by mrossard** [comment]
@jonag Just my opinion, but in this case i'd expect a quotation resource containing multiple quotation lines (which have no need to be api resources  - as far as i can see quotation lines only have meaning in the context of the quotation, exposing them directly doesn't seem logical to me).

You'd POST a quotation containing all the lines needed, and be able to PATCH it to change them, just like any other member of the resource. You'd probably need a custom processor, but that's to be expected with "complex" resources that need validation according to specific business rules.

As far as i can see, either the subresource has meaning without its "parent" and you want to use direct operations on them, or they only exist in the context of their parent, and you don't actually need/want to expose them as api resources. There could be some use cases I don't see yet, but in my experience when you try to do that you likely want to reevaluate what you expose in your API and see if there isn't a better way to achieve the desired functionnality.

**Comment by jonag** [comment]
If the lines are not API Resource then if I patch the quotation its lines are replaced with the one in the payload (the old one are deleted and new one are created) so we loose all the fields not sent in the payload. And what if the user calling the API doesn't have the permission to write all the fields? AFAIK this was until now [the recommended way](https://github.com/api-platform/core/issues/1950#issuecomment-389168972).

Regarding the solution to use a custom processor, since the ValidateListener is called before the WriteListener, it won't work because the quotation won't be correctly deserialized at the validation stage.

**Comment by mrossard** [comment]
> If the lines are not API Resource then if I patch the quotation its lines are replaced with the one in the payload (the old one are deleted and new one are created) so we loose all the fields not sent in the payload. 

As far as i understand it, that's what's expected from a standard PUT. A PATCH could (should?) be able to do a partial update on collections (not sure whether it's supposed to do that "deep" in the objects contained in the collection or if it's just changing "complete" objects in the collection though), but as @soyuka mentioned earlier it doesn't right now in api platform.

> And what if the user calling the API doesn't have the permission to write all the fields?

Well in that case you need it to be a resource, but it definitely makes much more sense to use /quotations/{id}/lines/{lineid} to patch them than to try to allow that through /quotations/{id} !

> Regarding the solution to use a custom processor, since the ValidateListener is called before the WriteListener, it won't work because the quotation won't be correctly deserialized at the validation stage.

You can customize the deserializer too, if needed...you got the point. ;-)

**Comment by soyuka** [comment]
@jonag because we implement the specification we can't just add something that is not in the specification or we need a new format...

**Comment by broncha** [comment]
I am on 3.1.12 and neither PUT not PATCH work for me to update the related collection!
