### ISSUE TITLE
Item attributes not serialized if item is also iterable

### ISSUE THREAD

**Issue by colinodell** [api-platform/core#5564]
**API Platform version(s) affected**: 2.7.0 - 3.1.9

**Description**  
The `AbstractItemNormalizer::supportsNormalization()` method was [changed in 2.7.0](https://github.com/api-platform/core/commit/1259ee5cb6c07267e5db5436234a4623b09512e5#diff-09898da6292003e953033d2c1691c21960f5bdb0c76251a02a2aad1964907ddfR119) to now `return false` for objects that also happen to be iterable.  As a result, the properties/attributes of that item are no longer exposed in the API response - only the iterable data.

**How to reproduce**  

Try to serialize an item like this:

```php
final class Wishlist implements IteratorAggregate
{
    public int $id;
    public User $owner;
    public string $name;
    private array $products;

    public function getInStockProducts() {
        return array_filter($this->products, static fn (Product $p) => $p->inStock()));
    }

    public function getIterator() {
        return new ArrayIterator($this->products);
    }
}
```

Prior to 2.7.0, the normalized output would be an **object with all the properties** - something kind of like this:

```json5
{
    '@id': 123,
    'owner': { ... },
    'name: 'What I want for Christmas',
    'inStockProducts': [
        { /* product 1 */ },
        { /* product 3 */ },
    ]
}
```

But because of the change introduced in 2.7.0, the item normalizer no longer handles this, so it falls back to the collection normalizer and is normalized as **an array of the item's iterable contents** with no object properties:

```json5
[
    { /* product 1 */ },
    { /* product 2 */ },
    { /* product 3 */ },
]
```

The examples above are slightly contrived, but they convey the behavior I'm seeing.

**Possible Solution**  

I don't fully understand the context of why the change was made, so I don't know which solution is ideal.  I do lean more towards option 1, but option 2 might also work for me personally.

**Option 1: Remove that added `is_iterable()` check**

Revert the breaking change.  The PHPUnit test suite passes for both 2.7.0 and 3.1.8 with that revert.  However, if any users are deliberately relying on the 2.7.0+ behavior, this _could_ be seen as a BC break for them.  So we're trading one BC break for another.

**Option 2: Document this BC break somewhere**

If this change was intentionally implemented so that iterable items are treated as collections, it would be great to document this somewhere.  I couldn't find anything about this in the changelog, upgrading instructions, or as a limitation of resource classes.  Affected users would therefore have to modify their objects to make them non-iterable.  This would also require additional refactoring throughout their codebase (for non-API-Platform-related code relying on that iterable behavior).

**Comment by colinodell** [comment]
> What format are you using? It doesn't look like your example would be useable with json+ld

We had two affected endpoints - one was using json, and the other using json+ld (please don't ask me why we have both lol).  I ended up just refactoring the resources to not be iterable since that was a poor design choice we made in our domain and didn't want to keep.

I do think the ability to represent a collection resource is interesting though, and I hope to have an opportunity to play with that sometime.

**Comment by soyuka** [comment]
Shoul I just document this BC break in our changelog to fix this then?

**Comment by colinodell** [comment]
Yeah, I think so.
