### ISSUE TITLE
DISABLE_TYPE_ENFORCEMENT is ignored for non-scalar properties

### ISSUE THREAD

**Issue by emr-dev** [api-platform/core#5584]
I'm trying to disable type enforcement so I don't get type errors on nullable=false properties.
Instead, I want to see error messages from Assert\NotBlank, Assert\NotNull, etc.

```
#[ApiResource(
    operations: [
        new Post(
            denormalizationContext: [
                'disable_type_enforcement' => true,
                'collect_denormalization_errors' => true
            ],
        ),
    ],
 )]
class Entity
{
 
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank()]
    private ?Brand $brand = null;

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }
    
   public function setBrand(?Brand $brand): void
    {
        $this->brand = $brand;
    }

}
```

My request:

```
POST: 
{
  brand: null
}

```
Actual answer:

```
{
   "violations":[
      {
         "propertyPath":"brand",
         "message":"This value should be of type array|string.",
         "code":"0"
      }
}
```

Expected response:

```
{
   "violations":[
      {
         "propertyPath":"brand",
         "message":"This value should not be blank.",
         "code":"0"
      }
}
```

As you can see from the actual answer `DISABLE_TYPE_ENFORCEMENT` does not work for any objects. I have tested it for relations and enum classes (Works for only scalar types).

After researching the problem, I found that in properties with the Object type, we simply do not get to this condition.

https://github.com/api-platform/core/blob/7a1d351b0a37fc7107c548708f4b9e38a9dedc76/src/Serializer/AbstractItemNormalizer.php#L843-L845

What do you think about this? Maybe this was expected behavior for you? 

This issue has also been mentioned here: [#1786](https://github.com/api-platform/api-platform/issues/1786)

**Comment by felipyamorim** [comment]
I made a workaround using composer to replace a snippet of code from the AbstractItemNormalizer class.

```
    "scripts": {
        "post-autoload-dump": [
            "sed -i 's/null === \\$value && \\$type->isNullable()/null === \\$value \\&\\& (\\$type->isNullable() \\|\\| \\$context[static::DISABLE_TYPE_ENFORCEMENT] \\?\\? false)/g' vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php"
        ],
    }
```

Same solution as suggested in a previous issue #4250

**Comment by soyuka** [comment]
can you try my patch at #5593 ?

**Comment by felipyamorim** [comment]
@soyuka thank you for the fix.
