### ISSUE TITLE
3.1.11 - PUT does not work with ManyToMany deep nested relations

### ISSUE THREAD

**Issue by mdieudonne** [api-platform/core#5587]
**API Platform version(s) affected**: `3.1.11`

**Description**  
`PATCH` does not work with ManyToMany deep nested relations.
But now neither does PUT `standard_put: true` in `3.1.11`

**Possible Solution**  
Revert latest changes made in `ItemNormalizer.php`

**Comment by soyuka** [comment]
what because of https://github.com/api-platform/core/commit/ed4bca9b95571984f5c94924640dd0bbd0aa3ce9 ?

or use `standard_put: false`?

**Comment by mdieudonne** [comment]
> what because of [ed4bca9](https://github.com/api-platform/core/commit/ed4bca9b95571984f5c94924640dd0bbd0aa3ce9) ?
> 
> or use `standard_put: false`?

To be honest, it's challenging for me to pinpoint the exact cause.
I only have limited knowledge about Api P.

I retried with `standard_put: false` and it seems to be messing up with ids for example...
Payload:
![image](https://github.com/api-platform/core/assets/32196785/ac6bdd9a-641b-4ee1-840a-c9557480a189)
Response:
![image](https://github.com/api-platform/core/assets/32196785/a950169c-5011-4a9f-96ea-86ce622117ce)

But this seems to be cause by `'standard_put' => false`, and not the version number.

I do need partial updates aka "standard_put" aka "legacy PUT" of Api P. if I understand correctly

**Comment by mdieudonne** [comment]
I also do have this behavior.
when submitting deep nested relations:

Payload:
![image](https://github.com/api-platform/core/assets/32196785/ce25598e-a5e5-494a-b3e8-eebcb6a031c3)
Response:

3.1.11 + `'standard_put' => true` || `'standard_put' => false`
"Item not found for \"/api/qual/qopse/fields/2123\"."

3.1.10 + `'standard_put' => true` || `'standard_put' => false`
This is fine

**Comment by mdieudonne** [comment]
@soyuka Now if I retry my tests but reverting back this line in `ItemNormalizer.php`

`$iri = $this->iriConverter->getIriFromResource($context['resource_class'], UrlGeneratorInterface::ABS_PATH, $operation, ['uri_variables' => ['id' => $data['id']]]);`

Then this is fine in 3.1.11 too

**Comment by soyuka** [comment]
I tried to reproduce your issue without success, may you provide a reproducer?

**Comment by mdieudonne** [comment]
@soyuka I'm working on a reproducer.
Here's the repo: [](https://github.com/mdieudonne/apip-bug-repro)

ATM, I can't even get to PUT or PATCH a 'business' with nested ManyToMany relation.
Array stays empty.

See the postman export at the root of the project.
Well, PUT business doesn't work as expected.

**Comment by mdieudonne** [comment]
@soyuka 
As previously said, if I modified ItemNormalizer as below, it works:
```
// $uriVariables = $this->getContextUriVariables($data, $operation, $context);
// $iri = $this->iriConverter->getIriFromResource($context['resource_class'], UrlGeneratorInterface::ABS_PATH, $operation, ['uri_variables' => $uriVariables]);
$iri = $this->iriConverter->getIriFromResource($context['resource_class'], UrlGeneratorInterface::ABS_PATH, $operation, ['uri_variables' => ['id' => $data['id']]]);
```
I've added data dumps in `getContextUriVariables` as below:
```
    private function getContextUriVariables(array $data, $operation, array $context): array
    {
        dump('$context[\'uri_variables\']', $context['uri_variables']);
        dump('$data[\'id\']',$data['id']);
        if (!isset($context['uri_variables'])) {
            return ['id' => $data['id']];
        }
        ....
```
And it seems the parent id is used instead of the nested id.
Am I doing something wrong?

![image](https://github.com/api-platform/core/assets/32196785/42e33521-b538-46af-a623-8788b64fb62f)

**Comment by soyuka** [comment]
Thanks @mdieudonne I'll check we need to `unset` these variables once used. I'll work on a patch asap

**Comment by mdieudonne** [comment]
@soyuka I'd be glad to help and contribute, if you can drive me a bit on what needs to be done :)

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/5604 lmk if that works
