### ISSUE TITLE
Command Query Responsibility Segregation / Event-based

### ISSUE THREAD

**Issue by sroze** [api-platform/core#559]
A lot of non-CRUD applications designs are moving to the CQRS pattern, and I definitely value it for many reasons. Even if at the moment we can almost expose APIs for such applications with ApiPlatform using custom actions, it's not straightforward.

We may explore how we can improve and/or adapt ApiPlatform to be able to power such applications, maybe through another side library or bundle actually.

**Comment by theofidry** [comment]
👍 I didn't have time to investigate how usable is ApiPlatform with CQRS yet but I would love to see it working well with it.

**Comment by dunglas** [comment]
It should be easier to do with the last beta and the new custom action system. I tried to integrate Tactician with API Platform and it works well (using custom actions).

Can this issue be closed or can we do something else to ease the implementation of CQRS with API Platform? (Writing a tutorial on how to use Tactician and API Platform is on my todo list, but don't expect it before the end of the year).

**Comment by Simperfit** [comment]
@sroze Didn't you already implement something like this :p ?
