### ISSUE TITLE
Subresource doesn't respect Query and ItemFilter Extensions

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#5590]
**API Platform version(s) affected**: 3.1.11

**Description**  
If you define an Item/Query filter extension on class `Foo` and then do have a class `Bar` with the following Subresource definition:
```php
#[ApiResource(
    uriTemplate: '/foos/{fooId}/bars.{_format}',
    operations: [new GetCollection()],
    uriVariables: [
        'fooId' => new Link(toProperty: 'foo', fromClass: Foo::class)
    ]
)]
```

it'll load the `Bar` objects even though the filter extension should not allow it to do so, since the filter should already get rid of the `Foo` instance.

**How to reproduce**  
See above.

**Possible Solution**  

Apply the item filter to subresources as well.

**Comment by mrossard** [comment]
"Subresource" is a misleading term. The only common thing between foo and bar in your example is the IRI. The framework has no way to know that you want the filter to be applied.
If you're talking about a doctrine filter, you probably have a condition that looks like inside it
```
if (Foo::class !== $resourceClass) {
 return;
}
```
If you want it to apply to Bar you'll need to tweak it accordingly, and tweak the condition you add to the query too.

**Comment by mrossard** [comment]
Another possibility that i've been toying with recently would be to define your Bar resource using entityClass=Foo::class, then use a custom provider to return the related Bar objects instead of Foo, but that makes other optional filters a bit awkward to use. 

It'd require adding the possibility to rename query parameters for all filters to be really "clean", which isn't possible at the moment as far as i know.

**Comment by soyuka** [comment]
On the ApiResource only the filters you defined on that same resource are applied. Add your `Foo` filter on the `Bar` resource and it should work.

**Comment by KDederichs** [comment]
Yeah, adding a filter on `Bar` does work. It's a bit counter intuitive though.
Like the filter works EVERYWHERE except in subresources.
