### ISSUE TITLE
Command "api:upgrade-resource" doesn't work with YAML configuration

### ISSUE THREAD

**Issue by jnovakdev** [api-platform/core#5595]
**API Platform version(s) affected**: 2.7.11

**Description**  
Unfortunately, I've discovered that the `api:upgrade-resource` is not affecting _anything_ if the config is done via YAML files. 
My thought is that this coudn't be an intended behavior - or is it? 

**How to reproduce**  
1. setup an `api-platform/core: "2.7.*"` project
2. create an ApiResource via an YAML file
3. run the `api:upgrade-resource` command

**Comment by soyuka** [comment]
we didn't create a script for that use case indeed but it shouldn't be hard to do so

**Comment by jnovakdev** [comment]
Do you consider doing this or do you prefer community to take care of this?

**Comment by soyuka** [comment]
sorry it isn't my priority to do so
