### ISSUE TITLE
SearchFilter shouldn't rely on nested resources having an "id" field

### ISSUE THREAD

**Issue by mrossard** [api-platform/core#5605]
**API Platform version(s) affected**: 3.1.12

**Description**  
When you use a SearchFilter on a nested property that is a resource and doesn't use "id" as its identifier you get "Can't get a way to read the property \"id\" in class XXX".

**How to reproduce**  
Have 2 resources A and B, with A containing a B (both simple ApiResources using entityClass=... in my case)
Use an ApiIdentifier in B that is not "id", ie IRIs are /Bs/{someotherfield}.
Add a searchfilter for the B member on A : 
```php
#[ApiFilter(SearchFilter::class, properties:['b'])
```

**Possible Solution**  
Didn't have time to dig into this yet, but it's happening in SearchFilterTrait line 127 : 
```php
return $this->getPropertyAccessor()->getValue($item, 'id');
```
This should probably be replaced so it at least looks for id in the entityClass when present, or even tries to get the ORM to return the correct id(s) without hard coding it.

**Comment by j-schumann** [comment]
Similar issue here w/ same version. Only difference: Problem occurs when the resourceClass has an identifier *not* named "id", but the association's identifier is indeed "id", as [Doctrine\Orm\Filter\SearchFilter#L126](https://github.com/api-platform/core/blob/3.1/src/Doctrine/Orm/Filter/SearchFilter.php#L126) re-uses the resource's identifier name(s).

https://github.com/api-platform/core/pull/5623 in its current state would fix this.

**Comment by mrossard** [comment]
There are indeed 2 issues here - the hardcoded "id", and then the main resource metada being reused instead of the association's. I'll try to get my fix up to standards so it gets merged.
