### ISSUE TITLE
Extension made redundant due to method check on operation in the ReadListener

### ISSUE THREAD

**Issue by ovidiuenache** [api-platform/core#5617]
**API Platform version(s) affected**: v3.1.11

**Description**  
I have a resource called Activity.

This resource has a boolean property called _approved_ and I created an extension to filter out the Activity resources that are not approved (approved = 0).

I have the following endpoints (among others):
- GET /api/activities/{id}
    - gets one Activity resource identified by the given id
- POST /api/activities/{id}/reports
    - creates a Report sub-resource for the Activity resource identified by the given id

Assume we have a database with one Activity resource with id = 1 and approved = 0.

Because of the extension, a call to GET /api/activities/1 would give us the expected 404.

However, a call to POST /api/activities/1/reports that aims to create a Report for the non-approved Activity does NOT return a 404 (as I would expect) because of https://github.com/api-platform/core/pull/5583. Since we no longer throw the exception, the code eventually ends up in Symfony's EntityValueResolver which fetches the entity since it exists in the database, thus ignoring the extension I have for approved activities.

As you might have guessed, the controller for this action has an argument type hinted to Activity with no extra configuration:
```
_api_/activities/{id}_report:
    class: ApiPlatform\Metadata\Post
    method: POST
    uriTemplate: /activities/{id}/report
    controller: App\Controller\Api\Activity\Report
```

```
#[AsController]
final class Report
{
    public function __invoke(
        ...
        Activity $activity
        ...
    ): Response {
        ...
    }
}
```

While there might different solutions to this, I want to highlight that there is a breaking change introduced in this patch version since the previous v3.1.10 version behaves as expected and returns the 404 for the POST request.

What are your thoughts on this?

cc @soyuka

**Comment by soyuka** [comment]
don't use a controller, handle that in a processor, for example:

```
#[Post(uriTemplate: '/api/activities/{id}/reports', processor: [Report::class, 'createActivityReport'])]
class Report {
    public static function createActivityReport(mixed $data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        if (!$data->getActivity()->approved) {
          throw new BadRequestHttpException();
        }

        // continue
    }
}
```

**Comment by itorgov** [comment]
@soyuka Hi! I have the same issue. In your example above if the activity won't be found then the `$data` argument will equal to `null`. But as @ovidiuenache mentioned, "the previous v3.1.10 version behaves as expected and returns the 404 for the POST request". We really want to keep this behaviour and throw the `NotFoundHttpException` exception if a resource is not found (a POST request like `/api/activities/{id}/reports` is called [controller resource archetype](https://cagline.medium.com/restful-web-services-ddafb8019f2e)).

**Comment by itorgov** [comment]
In our company we often uses a controller resource archetype (like the `POST /alerts/245743/resend` example from the article I have mentioned above).

**Comment by BrandonGillis** [comment]
Having the same issue at the moment, it also looks like it create an issue with the security object expression usage, ex :

```php
        new Post(
            uriTemplate: '/job_postings/{slug}/duplicate',
            controller: Duplicate::class,
            security: "is_granted('PUBLICATION_ACCESS') and object.getCompany() == user.getCompany()",
            deserialize: false,
            validate: false,
            write: false,
        ),
```

when doing a `POST /job_postings/not-found/duplicate` before it was returning a **404**, now it return a 500, as the `object` in the security is null : `"Unable to call method \"getCompany\" of non-object \"object\".`
