### ISSUE TITLE
Bug with Symfony 6.2 and Symfony\Bridge\Twig

### ISSUE THREAD

**Issue by djbodya** [api-platform/core#5622]
**API Platform version(s) affected**: 3.1.11

**Description**  
I have application which use Symfony 6.3. When  version was 6.1 everything was fine. But now when i update the version API is broken. Error is "Warning: Undefined array key 'Symfony\Bridge\Twig\Attribute\Template'". This class is presented in Symfony 6.2. 

**How to reproduce**  
Install API-Platform Core with Symfony 6.2.

**Comment by soyuka** [comment]
stack trace?

**Comment by djbodya** [comment]
I am sorry. I install fresh api-platform without any additional dependencies and everything goes fine. Will search problem in my project.
