### ISSUE TITLE
Symfony 6.3 Normalizer deprecations

### ISSUE THREAD

**Issue by fwolfsjaeger** [api-platform/core#5634]
**API Platform version(s) affected**: 3.1.x

**Description**  
Symfony 6.3 introduced some changes to the serialization component, which results in quite a few deprecation warnings.

**How to reproduce**  
Upgrade Symfony to 6.3 and check the deprecation warnings.

**Possible Solution**  
Implement `NormalizerInterface::getSupportedTypes()` in all API-Platform normalizers.

**Additional Context**
Deprecation message:
```
User Deprecated: Since symfony/serializer 6.3:
Not implementing the "NormalizerInterface::getSupportedTypes()" in "Path\To\Normalizer" is deprecated.
```

These files seem to be affected:
- ApiPlatform\OpenApi\Serializer\ApiGatewayNormalizer
- ApiPlatform\Hydra\Serializer\ConstraintViolationListNormalizer
- ApiPlatform\Problem\Serializer\ConstraintViolationListNormalizer
- ApiPlatform\Hydra\Serializer\DocumentationNormalizer
- ApiPlatform\Hydra\Serializer\EntrypointNormalizer
- ApiPlatform\Hydra\Serializer\ErrorNormalizer
- ApiPlatform\Problem\Serializer\ErrorNormalizer
- ApiPlatform\JsonLd\Serializer\ItemNormalizer
- ApiPlatform\Serializer\ItemNormalizer
- ApiPlatform\Hydra\Serializer\CollectionFiltersNormalizer
- ApiPlatform\JsonLd\Serializer\ObjectNormalizer

**Comment by mrossard** [comment]
Someone's already working on it - see https://github.com/api-platform/core/issues/5610 and https://github.com/api-platform/core/pull/5611

**Comment by fwolfsjaeger** [comment]
Thanks, I didn't find the issue.
