### ISSUE TITLE
OpenApi override responses adds responses on top of the overriden ones

### ISSUE THREAD

**Issue by gospodinpopara** [api-platform/core#5635]
Symofny verison: 6.3
Php: 8.1.3
Api platform version 3.1.12
### new Post(
            uriTemplate: 'testing',
            controller: TestingController::class,
            openapi: new OpenApiOperation(
                responses: [
                    '200' => new OpenApiResponse(description: 'Ok')
                ],
                summary: 'Testing....',
                description: 'testing ....',
                requestBody: new RequestBody(
                    content: new ArrayObject(
                        [
                            'application/json' => [
                                'schema' => [
                                    'properties' => [
                                        'id' => ['type' => 'integer', 'required' => true, 'description' => 'id']
                                    ]
                                ],
                                'example' => [
                                    'id' => 12345
                                ]
                            ]
                        ]
                    )
                )
            )
        )
I'm not sure if this is how it's supposed to work, but I'm having problems overriding openapi default values. I created a custom route and I want to have only a specific response (in this case, 200), but for some reason, the default responses (201, 400, 422) are still present. :) I'm trying to customize my routes, but I can't override the default values. Is there a way :( ? 

![p2](https://github.com/api-platform/core/assets/51289425/5b6909d5-7221-4791-ae0e-46b04ad3f07e)

The above correctly updates the 200 response. However, I would expect that to be the only response that is shown. However, the defaults still remain.
 openapiContext property works perfectly fine in this case :).

**Comment by soyuka** [comment]
unsure how to fix this though as there's a hidden feature to add default operation responses, for now you've to decorate the OpenApiFactory

**Comment by soyuka** [comment]
I think this is a wontfix as our API always answers with the same error responses. If you really need this, decorate the openapifactory.
