### ISSUE TITLE
Inconsistent normalization between GET and GQL with multiple similar related entities

### ISSUE THREAD

**Issue by lcottingham** [api-platform/core#5639]
**API Platform version(s) affected**: 3.1 / Core v2.7.13

**Description**  
Sometimes api platform gives inconsistent normalization structured data from GET requests vs Graphql `Query` requests. It could be related to how it is automatically detecting related entities by variable type declarations and is tripping up when an entity relates to another entity more than once. I'm just speculating here.

**How to reproduce**  
See gist here: https://gist.github.com/lcottingham/d9ecf5b4329bf4548a2227a30c1fee2f
Here, the IRI would be `/submission_batches/1234` for the `SubmissionBatch` API entity.

Querying `'/submission_batches/1234` would return the properties for entity ID 1234, including the related `Job` entity data for `$incomingJobs` and `$outgoingJobs`, where the ids were related. This is the expected behaviour and correct.

Doing a similar query in graphql (documented in the gist), would return the properties for the entity, but an empty array for the related incomingJobs and outgoingJobs.

**Additional Context**  
<img width="864" alt="image" src="https://github.com/api-platform/core/assets/8629966/0af323ea-75fd-46bd-8e21-66ced559ab97">

<img width="568" alt="image" src="https://github.com/api-platform/core/assets/8629966/a8480e82-0ebd-44e5-8b09-662bc51703d1">

**Comment by soyuka** [comment]
interesting, what happens if you select more fields from the underlying collection?

**Comment by lcottingham** [comment]
@soyuka It returns `null` as if no results were found. I only included the total count to keep the visual brief for the issue report, but I did try querying the id and other fields from the related collection.

**Comment by soyuka** [comment]
please provide a reproducer with a test case
