### ISSUE TITLE
GraphQL: ManyToOne relation is required in mutations

### ISSUE THREAD

**Issue by phtmgt** [api-platform/core#5644]
**API Platform version(s) affected**: 3.0

**Description**  

```
#[ORM\ManyToOne(targetEntity: 'Address', inversedBy: 'properties')]
#[ORM\JoinColumn(nullable: true)]
#[Groups(['read', 'write'])]
```

results in 

`input updatePropertyInput {  address: updateAddressNestedInput! }`

**How to reproduce**  

Make a writeable ManyToOne relationship and generate the schema.

**Possible Solution**  

Well, find the issue and fix it, I guess.

**Additional Context**  

I tried adding #[ORM\JoinColumn(nullable: true)], but it does not change the output in any way (as I suspected - by definition relations should be nullable, right?).

I also tried supplying {}, { id: null } and { id: undefined} as updateAddressNestedInput!, it does not work, although the updateAddressNestedInput! is defined as below where none of the properties are required:

```
input updateAddressNestedInput {
  id: ID
  address: String

  """Many Postcodes have One Outcode."""
  postcode: String
  plusCode: String
  route: String
  streetNumber: String
  neighborhood: String
  clientMutationId: String
}
```

I get `"Type loader is expected to return a callable or valid type \"updateAddressNestedInput\", but it returned null"` or a similar error, depending on the varying input.

And, a side question: It used to be (at least in 2.6) that such nested mutations are disabled (even not possible, I think). This worked fine for me. Is there any way to disable this nested nonsense and just use IRIs? I hate to deal with the ambiguity (for example, what happens if my entity already has a relation and I do not include the related entity in the mutation... does it remove the related entity or does it leave it alone) Could not find anything in the documentation (or Google).

**Comment by plamenh** [comment]
I was able to solve this myself, using the following:

`#[ApiProperty(readableLink: true, writableLink: false)]` on the $address property.

However, this is still an issue, because the system seemingly haphazardly decides to treat some properties differently. For example:

```
#[ORM\ManyToOne(targetEntity: 'PropertySubtype', inversedBy: 'properties')]
#[Groups(['read', 'write'])]
private $subtype;

#[ORM\ManyToOne(targetEntity: 'Address', inversedBy: 'properties')]
#[Groups(['read', 'write'])]
private $address;
```

These two properties have no discernible differences and yet, one is a nested input, the other string.
