### ISSUE TITLE
Why validation is not triggered with DELETE method

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#5647]
See : https://github.com/api-platform/core/blob/4ef0ef856ced658ac942fd6a2c6f7c5c563078d1/src/Symfony/EventListener/ValidateListener.php#L53

I have a use case, where is I need validation:

* I have a project, and this project has some members.
* I want to forbid the removal of a user, if it's the last one

ATM, I use a listener for doing that, but I would prefer to use a regular Validator

**Comment by soyuka** [comment]
Yeah I wish be based our code only on the `canValidate` value, in API Platform 3.2 you'll be able to use `validate: true` to force validation.

**Comment by lyrixx** [comment]
Okay thank. I close this issue since I have a workaround and it'll be fixed in 3.2

Thanks for the fast answer
