### ISSUE TITLE
How to manage with Tree DoctrineExtension?

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#566]
Hi,

I'm trying to implement API Platform 2 on an entity using [Tree DoctrineExtension](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md). When I get a specific item (`GET /menus/1`), I would like to receive a response like:

```json
{
    "@context": "/contexts/Menu",
    "@id": "/menus/1",
    "@type": "Menu",
    "title": "Food",
    "children": [
        {
            "@id": "/menus/3",
            "@type": "Menu",
            "title": "Vegetables",
            "children": [
                {
                    "@id": "/menus/4",
                    "@type": "Menu",
                    "title": "Carrots",
                    "children": []
                }
            ]
        },
        {
            "@id": "/menus/2",
            "@type": "Menu",
            "title": "Fruits",
            "children": []
        }
    ]
}
```

My approach is to create an EventListener, listening to `kernel.view` event, and get `childrenHierarchy` through `NestedTreeRepository` with my current object (`$event->getControllerResult()`). It gives me an array, here I don't know how to manage it in JSON-LD.

Any idea how I can manage this feature?

**Comment by dunglas** [comment]
Why didn't you add a getChildren() method on the Menu entity then use @Groups to include children in the normalized array and optionally the @MaxDepth annotation to limit the depth of the tree?

I've already done something similar in a project using Doctrine Extensioms and it was working like a charm.

**Comment by vincentchalamon** [comment]
I've a `getChildren` in my Menu entity, but it's empty. Did I miss something?
```php
class Menu
{
    // ...

    /**
     * @var ArrayCollection|Menu[]
     *
     * @ORM\OneToMany(targetEntity="Menu", mappedBy="parent")
     * @ORM\OrderBy({"lft"="ASC"})
     *
     * @Groups({"menu_default_output"})
     */
    private $children;

    /**
     * @return ArrayCollection|Menu[]
     */
    public function getChildren()
    {
        return $this->children;
    }
}
```

**Comment by vincentchalamon** [comment]
In the `setChildren` method, I forgot to add `$children->setParent($this)`…

**Comment by vipulw2011** [comment]
> Why didn't you add a getChildren() method on the Menu entity then use @groups to include children in the normalized array and optionally the @maxdepth annotation to limit the depth of the tree?
> 
> I've already done something similar in a project using Doctrine Extensions and it was working like a charm.

@dunglas @vincentchalamon I have tree structure as req body. How can I patch the hierarchy in single api ?
