### ISSUE TITLE
Do not apply filters is `filters` option is already set on an operation

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#5665]
**API Platform version(s) affected**: 3.x

**Description**
Considering the following resource:
```php
#[ApiResource(
    types: ['https://schema.org/Review'],
    operations: [
        new GetCollection(),
        new Get(),
    ],
    routePrefix: '/admin',
    security: 'is_granted("ROLE_ADMIN")'
)]
#[ApiResource(
    uriTemplate: '/books/{bookId}/reviews{._format}',
    types: ['https://schema.org/Review'],
    operations: [
        new GetCollection(filters: [], itemUriTemplate: '/books/{bookId}/reviews/{id}{._format}'),
        new NotExposed(
            uriTemplate: '/books/{bookId}/reviews/{id}{._format}',
            uriVariables: [
                'bookId' => new Link(toProperty: 'book', fromClass: Book::class),
                'id' => new Link(fromClass: Review::class),
            ],
        ),
    ],
    uriVariables: [
        'bookId' => new Link(toProperty: 'book', fromClass: Book::class),
    ],
)]
class Review
{
    #[ApiFilter(NumericFilter::class)]
    public ?int $rating = null;
```
The filter on `rating` must be applied only on the first ApiResource (`/admin/reviews`), not the second one. To do so, I set the `filters: []` option to disable all filters. But the FiltersResourceMetadataCollectionFactory erases this configuration.

**Possible Solution**
Do not set filters on FiltersResourceMetadataCollectionFactory is `filters` is not null.

**Comment by soyuka** [comment]
can't you declare the filter on your resource instead of the property? To me a filter on a property is there for every resources, just like every ApiProperty informations.

**Comment by vincentchalamon** [comment]
> can't you declare the filter on your resource instead of the property? To me a filter on a property is there for every resources, just like every ApiProperty informations.

Will do. Do API Platform already supports the following syntax? (if not, do you think it'll be a good feature?):
```php
#[GetCollection(
    filters: [
        new ApiFilter(SearchFilter::class, properties: ['title', 'author']),
    ]
)]
```

**Comment by jamesisaac** [comment]
Relevant discussion: https://github.com/api-platform/core/discussions/5519

There is already a `filters` property on GetCollection, but it expects a string (`$filterId`).  It does actually work if you configure a unique service for the specific SearchFilter configuration, then pass in the service ID, similar to the example shown here: https://api-platform.com/docs/core/filters/#manual-service-and-attribute-registration

```yaml
services:
    'app.filter.book.search':
        class: 'ApiPlatform\Doctrine\Orm\Filter\SearchFilter'
        arguments: [ '@doctrine', '@api_platform.iri_converter', ~, '@logger', { 'title': ~ } ]
        tags: [ 'api_platform.filter' ]
```

```php
new GetCollection(filters: ['app.filter.book.search']),
```

But a more direct syntax like in the last comment where you can define the properties inline without needing to declare a service would be a nice addition!

**Comment by mrossard** [comment]
That would indeed be very nice!

**Comment by vincentchalamon** [comment]
Sadly, this syntax cannot work because the ApiFilter attributes (declared on class and properties) are dynamically converted into services in [AttributeFilterPass](https://github.com/api-platform/core/blob/main/src/Symfony/Bundle/DependencyInjection/Compiler/AttributeFilterPass.php). To declare ApiFilter objets in resource/operation `filters` option and convert them into services in this compiler pass, it would require to load the [metadata](https://github.com/api-platform/core/tree/main/src/Metadata/Resource/Factory), which is loaded AFTER the compiler pass...

**Comment by bendavies** [comment]
did you discover a workaround for this?
