### ISSUE TITLE
Child entity update

### ISSUE THREAD

**Issue by polc** [api-platform/core#567]
Given a `PasswordReset `resource with a property `$user`
```
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"password_reset_put"})
     */
    private $user;
```

If I do a `PUT /password-reset`
```
{
    "user": {
        "plainPassword": "newPassword"
    }
}
```
I except the user to be updated. But I get an exception:
`"A new entity was found through the relationship AppBundle\\Entity\\PasswordReset#user that was not configured to cascade persist operations for entity: AppBundle\\Entity\\User."`

To make it working I need to include the user ID in the request : 

`PUT /password-reset`
```
{
    "user": {
        "@id": "/users/1",
        "plainPassword": "newPassword"
    }
}
```

Is this a normal behavior?

**Comment by Simperfit** [comment]
Yes I think that is the normal behavior since you are posting to password-reset and not directly to user.

Since you don't know what user it is, he will ask you to persist a new user.

**Comment by soyuka** [comment]
Yes this is normal behavior. If the user id is not specified, it tries to create a new Entity. Here, as Doctrine is not configured to `persist: cascade` it throws the correct error.

**Comment by polc** [comment]
Okay I understand this, but should we not except the user id to not be updated if it's not specified in the denormalization context group ? Like any other fields ?

**Comment by teohhanhui** [comment]
We have no way to know which user it is if you don't specify it. It is therefore assumed to be a new user.

**Comment by polc** [comment]
eh ? The `PUT ` action perform a getItem(), and with `fetch="EAGER"` the user is already fetched no ?

**Comment by teohhanhui** [comment]
This is not a matter of our implementation. It does not make sense from the JSON-LD perspective to modify an existing resource when no "@id" is specified. We simply have no way to tell if you intended to modify an existing resource or to create a new one.

**Comment by polc** [comment]
ah okay, is it possible in API Platform to prevent a relation to change, but to be able to edit the relation properties ?

Here is my use case: https://gist.github.com/polc/32a997d8d3d0ac626cf252bcdf42e1b2 maybe I'm all wrong..

**Comment by teohhanhui** [comment]
Considering the user has to enter the correct current password, that's not reset password but change password... :stuck_out_tongue:

**Comment by teohhanhui** [comment]
And I don't see why the current password should be passed as query param. Why not just include it in the request body? (You can handle it with a custom normalizer.)

**Comment by polc** [comment]
No no the password is hashed :P, `PasswordReset#password` is a secret code generated automatically and sent as email to the user (`password `is misleading I should have called it `secret `or `token `maybe).

If the user want to update his password (`User#password`), he have to do a 
`PUT /password-resets?password=secretcodereceivedbyemail `
```
      {
          "user": {
              "plainPassword": "newPassword"
          }
      }
```

Excepted I can't find a way to update the user password from PasswordReset. I think it's a very common use case, so It could be great to find a solution and even maybe worth to add something to the doc in a cookbook about it.

**Comment by teohhanhui** [comment]
You could generate a JWT token for password reset, which includes the user ID as the `sub` (subject) claim (e.g. `"sub":"1"`) and a private claim (e.g. `"_myapp_intent":"password_reset"`). Of course you could also include the `exp` claim so that the token will expire.

How to use it? Perhaps send this token as `Authorization` header, or include it as a query param in the password reset link. I'm not sure what the RESTful endpoint for this should be, maybe `/password-resets` or even `/me` (if you're a fan of that...), with a body of `{"plainPassword": "newPassword"}`?

And the cool thing is, you don't even have to store the token in your database!

**Comment by polc** [comment]
Great idea to use a JWT Token! About the RESTful endpoint I was looking for a JSON-LD way..
