### ISSUE TITLE
QueryNameGenerator don't sanitize input, can lead to issue

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/core#5680]
**API Platform version(s) affected**: 2.7.* (also 3.0 more)

**Description**  
The query name generate an alias, that may be invalid. The example below leads to a query exception `Error: Expected end of string, got '-'`.

**How to reproduce**  

```
$code = "whatever-with--dashes";
$valueParameter = $queryNameGenerator->generateParameterName($code);
$queryBuilder
    ->andWhere($queryBuilder->expr()->eq(
        sprintf('%s.text', $productAttributesAlias), ':'.$valueParameter)
    )
    ->setParameter($valueParameter, $attributeValue)
;
```

**Possible Solution**  
Sanitizing the input would work. I'm not sure this issue is on your side, but I expected the queryNameGenerator to be able to handle this. This is maybe a feature request, I'm not sure :)

https://github.com/api-platform/core/blob/main/src/Doctrine/Orm/Util/QueryNameGenerator.php#L23

Thank you for your work

**Comment by dunglas** [comment]
Hi,

This looks expected to me. The parameter name must be a valid Doctrine parameter. I suggest just adding some PHPDocs describing this requirement in `QueryNameGeneratorInterface`.

**Comment by vasilvestre** [comment]
https://github.com/api-platform/core/blob/main/src/Doctrine/Orm/Util/QueryNameGenerator.php#L41

```php
return sprintf('%s_p%d', str_replace('.', '_', $name), $this->incrementedName++);
```

AFAIK the str_replace is used to sanitize, as str_replace takes an array as first argument wouldn't `str_replace(['.', '-'] , '_', $name)` be an acceptable solution ?

**Comment by dunglas** [comment]
Indeed this looks ok.

**Comment by vasilvestre** [comment]
I will try to find some time to read the contribution guide and make the change. Thank you for inputs
