### ISSUE TITLE
Does it possible to serialize only one side of a bidirectional entity relationship ?

### ISSUE THREAD

**Issue by AlexandreHagen** [api-platform/core#570]
Hi 
I am looking to migrate one of Symfony project to Api Plaform V2. In this project I have some bidirectional relationship between doctrine entities. But that is a problem during the serialization. Indeed I got very often this error from ```CircularReferenceException``` class:   
```
A circular reference has been detected (configured limit: 1).
```   
I know that it is possible to solve it with a group configuration. However it's not my goal to use it to continue to use my project without api platform. 
I am under Symfony 3.1 so I already tried to use ```@MaxDepth(1)``` annotation from Symfony serialise at parent entity level. But that does not have any impact and the error still the same. 

Here an example of relationship in my project : 
 ```
Space 1<->n UserSpace n<->1User
 ```
In that case the serialize try to process like this: 
```
Space->UserSpace->User->UserSpace 
``` 
That is why I got ```CircularReferenceException```. That is because UserSpace entity is serialized twice due to bidirectional relationship.

So I would like to know if it is possible to be serialized only the master side of a bidirectional entity relationship ?

**Comment by AlexandreHagen** [comment]
I found out how to do it ! I use ```@ApiProperty(readable = false)``` on inverse relationship side ! (But it can also work on a master relationship side.)
I hope it will help someone.

**Comment by AlexandreHagen** [comment]
Maybe it would be good to add this information to the doc ?

**Comment by dunglas** [comment]
Yes it is! Can you open a PR on https://github.com/api-platform/doc? Thanks!

**Comment by Simperfit** [comment]
@AlexandreHagen You can send a PR to [api-platform/doc](https://github.com/api-platform/doc/tree/master)

**Comment by AlexandreHagen** [comment]
Yes I can ! And I will !
