### ISSUE TITLE
The "ApiPlatform\Serializer\AbstractCollectionNormalizer" class implements "Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface" that is deprecated since Symfony 6.3, implement "getSupportedTypes(?string $format)" instead.

### ISSUE THREAD

**Issue by shakaran** [api-platform/core#5702]
**API Platform version(s) affected**: 3.1

**Description**  

The "ApiPlatform\Serializer\AbstractCollectionNormalizer" class implements "Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface" that is deprecated since Symfony 6.3, implement "getSupportedTypes(?string $format)" instead.

**How to reproduce**  
Using Symfony 6.3 with last version of this bundle

**Possible Solution**  
Remove CacheableSupportsMethodInterface from AbstractCollectionNormalizer and use getSupportedTypes

**Additional Context**  
Other warnings from other classes similar too

**Comment by mrossard** [comment]
This should be fixed by https://github.com/api-platform/core/pull/5696, it'll likely be ok in the next release.
