### ISSUE TITLE
depreciation: mongodb Builder::execute is deprecated

### ISSUE THREAD

**Issue by divine** [api-platform/core#5705]
**API Platform version(s) affected**: 3.1.x

**Description**  
`User Deprecated: Since doctrine/mongodb-odm 2.2: Using "Doctrine\ODM\MongoDB\Aggregation\Builder::execute" is deprecated. Please use "Doctrine\ODM\MongoDB\Aggregation\Builder::getAggregation()" instead.`

PR is coming but tests are failing.

**Comment by DavidePastore** [comment]
Today I migrated a project from `api-platform/core` 2.7.16 to 3.2.12 and I can still see this deprecation notice. Is it the expected behavior?
/cc @soyuka
