### ISSUE TITLE
ItemUriTemplate also for GET Operations

### ISSUE THREAD

**Issue by develth** [api-platform/core#5718]
When using an GET Operation as alternative to the default ID/UUID GET (to be more specific, it is a GET by a `slug`), the returned IRI should be the Primary-IRI defined by first GET Operation or a custom defined via the Option that is available on GetCollection or POST.

The definition like following snippet works nice, also no need for Provider anymore for such a case:

```
#[Get(
    uriTemplate: '/venues/slug/{slug}',
    uriVariables: [
        'slug' => new Link(fromClass: self::class, identifiers: ['slug']),
    ]
)]
```

But the returned `@id` is then like `"@id": "/venues/slug/nice-hotel-with-a-view"`.
On frontend i cache the Data with the `@id`, in this case i have the same Serialization Context and that results in duplicate data. Also on Handling with Sub-Resources i cannot use the IRI anymore to append a Sub-Resource call. 

I think i will not be the only guy facing that issues while handling with IRI. 
Or is there already an alternative Solution for that?

**Comment by mrossard** [comment]
How would you manage Get operations with different serialization contexts then? 
Your API would return 2 different objects with the same IRI, which seems much more inconsistent to me, and it would break any frontend caching system similar to yours, actually.

**Comment by soyuka** [comment]
this was on my todolist,feel free to open a pull request, I think that `itemUriTemplate` is valid on every operation.

**Comment by develth** [comment]
> Couldn't/shouldn't this result in some kind of redirect?
I would not go for a redirect here, because its a new full request cycle and costs imho more time / resource on both side (server/client). All Security validations etc. needs to be done again. 

> Or maybe there's a need for an "alternate location" concept on resources? 
That could be a possibility, for that we need to think about what we need for that to define on top (like alternative uri etc...)
But that would ensure that the context are the same.

> If so, always getting all valid IRIs for every resource would be pretty convenient - for caching purposes for example, wouldn't it?
I agree, if the context would differ. But i think, that If its the same context, its the same Resource.

IMHO `itemUriTemplate` is already a implemented feature we could easily reuse with smalle changes ( [see here](https://github.com/develth/api-platform-core/commit/53bbe1cee7b3a96cb5f99b382786ad569074f1b8) ) and would be a quick win.

**Comment by mrossard** [comment]
> I would not go for a redirect here, because its a new full request cycle and costs imho more time / resource on both side (server/client). All Security validations etc. needs to be done again.

In terms of computing resources it might not be ideal, but a solution that would simply use the content-location header would look pretty nice, if i'm not misreading the specs.

> I agree, if the context would differ. But i think, that If its the same context, its the same Resource.

I was thinking about the use case where they are the same resource. Having every IRI for this exact resource in the contents would help with caching - you wouldn't mistakenly call a "secondary" IRI for the same resource if the first one already told you it's the same thing, you would just register your contents for both IRIs the first time.

> IMHO `itemUriTemplate` is already a implemented feature we could easily reuse with smalle changes ( [see here](https://github.com/develth/api-platform-core/commit/53bbe1cee7b3a96cb5f99b382786ad569074f1b8) ) and would be a quick win.

Yes, that seems very doable, I was just trying to think ahead about how this could be used / how this could improve other uses.

**Comment by mrossard** [comment]
The content-location header would actually be a pretty neat way to do this IMO : you could return the resource the same way it does right now, with the id matching the requested uri, but a client cache could prioritise that header as a cache key, with @id as a the default.

**Comment by develth** [comment]
> this was on my todolist,feel free to open a pull request, I think that `itemUriTemplate` is valid on every operation.

Should i stilll open a PR for that, or is this already solvable by another solution?
