### ISSUE TITLE
main branch: Error stacktraces seem to be swallowed by ErrorListener

### ISSUE THREAD

**Issue by weaverryan** [api-platform/core#5720]
**API Platform version(s) affected**: unreleased `main` branch

**Description**  
In the latest, unreleased code, many errors seem to be swallowed with a bad stracktrace. For example, for a 404 thrown by `ReadListener`, compare the stack traces:

3.1.13:

<img width="1177" alt="Screenshot 2023-08-04 at 10 23 13 AM" src="https://github.com/api-platform/core/assets/121003/67ea5d9f-59e9-48be-9c90-86fa11cbda2f">

Compared to `main`:

<img width="1182" alt="Screenshot 2023-08-04 at 10 24 01 AM" src="https://github.com/api-platform/core/assets/121003/10d4a551-55bd-4911-8709-5a8a43ae6092">

In the `main` branch, most/all errors seem to be swallowed by the `ErrorListener`.

**How to reproduce**  
Use a project on the `main` branch and trigger any error.

Cheers!

**Comment by weaverryan** [comment]
It may still be an issue, but if nobody else has seen it, maybe not!

**Comment by divine** [comment]
Hello,

It was probably fixed in https://github.com/api-platform/core/pull/5837.

Thanks!
