### ISSUE TITLE
[Bug] symfony cache:clear stopped working

### ISSUE THREAD

**Issue by aledeg** [api-platform/core#574]
I've upgraded the core from 8bdf829 to cde69f8. After that, the ```bin/console cache:clear``` command stopped working.

I've got the following error message:

> [InvalidArgumentException]
  The "/var/www/src/MyBundle/Resources/config/" directory does not exist.

That directory does not exist because I don't need it. I don't understand why ```api-platform/core``` tries to enforced that rule.
Of course, I can create that directory (which I did for testing), but I cannot create those directories in bundles I cannot change (ie: vendors).

**Comment by teohhanhui** [comment]
This is a bug introduced by #568.

**Comment by soyuka** [comment]
Thanks for the bug report @aledeg

**Comment by soyuka** [comment]
@dunglas close rel to  #575

**Comment by aledeg** [comment]
@soyuka I updated my code with the latest version of the core and it's working fine.
