### ISSUE TITLE
Improve ApiTestAssertionsTrait::assertJsonEquals with `assertEquals` insteads of `assertEqualsCanonicalizing`

### ISSUE THREAD

**Issue by DaedalusDev** [api-platform/core#5751]
# Description
Dear ApiPlatform,

this issue is a development tools improvement to make functionnal tests easier and more effective.

I suggest to replace this code :
https://github.com/api-platform/core/blob/63697e7fe382dcebb8c4c6a2308e0705e7593867/src/Symfony/Bundle/Test/ApiTestAssertionsTrait.php#L77

With :
```php
        static::assertEqualsCanonicalizing($json, self::getHttpResponse()->toArray(false), $message);
```

# Why ?

## `assertEqualsCanonicalizing` can produce unexpected results
According to PhpUnit's doc, by canonicalizing comparison, keys are ignored and will produce non expected results.

### Example
```php
<?php

namespace App\Tests\Api;

use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;

class CanolicalizingTest extends ApiTestCase
{
    public function testCanonicalizing(): void
    {
        static::assertEqualsCanonicalizing(
            [
                'a' => 5,
                'b' => 10,
            ],
            [
                'c' => 5,
                'd' => 10,
            ],
            'assertEqualsCanonicalizing :-(',
        );
        static::assertEquals(
            [
                'a' => 5,
                'b' => 10,
            ],
            [
                'c' => 5,
                'd' => 10,
            ],
            'assertEquals :-(',
        );
    }
}
```
This exemple with produce :
```
assertEquals :-(
Failed asserting that two arrays are equal.
```

## `Object` are supposed be an unordered collection of zero or more name/value pairs
According https://www.rfc-editor.org/rfc/rfc7159.html :
> An object is an unordered collection of zero or more name/value
> pairs, where a name is a string and a value is a string, number,
> boolean, null, object, or array.

So, i think order of properties won't be used to assert a result. That mean this changed won't produce regression for existing projects (or will improve tests with previously false positive passing tests :stuck_out_tongue_closed_eyes:).

## Reference
This issues refer to another issue from api-platform/api-platform https://github.com/api-platform/api-platform/issues/1372

Thanks for your great work.

**Comment by dunglas** [comment]
JSON objects aren't ordered but PHP arrays are. To prevent false positives we will have to order the keys of associative array keys.

A better fix would be to correct the underlying PHPUnit bug.

**Comment by DaedalusDev** [comment]
> JSON objects aren't ordered but PHP arrays are. To prevent false positives we will have to order the keys of associative array keys.
> 
> A better fix would be to correct the underlying PHPUnit bug: [sebastianbergmann/phpunit#5019](https://github.com/sebastianbergmann/phpunit/issues/5019)

Sure ! But `assertEquals` compare elements recurcively as key paired value, so if it don't say a mistake, order is "not implicitly" compared, but value would not match.

Exemple :
```php
<?php

namespace App\Tests\Api;

use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;

/**
 * @internal
 *
 * @coversNothing
 */
class CanolicalizingTest extends ApiTestCase
{
    public function testAssertEquals(): void
    {
        static::assertEquals(
            [
                5,
                10,
            ],
            [
                10,
                5,
            ],
            'assertEquals :-(',
        );
    }
}
```
Result :
```
assertEquals :-(
Failed asserting that two arrays are equal.
<Click to see difference>
```
![image](https://github.com/api-platform/core/assets/16138648/52793bd3-9d0c-4fbe-9858-0c4c73b13e6c)
