### ISSUE TITLE
[elasticsearch] : Cannot update to 3.1.5

### ISSUE THREAD

**Issue by guelosuperstart** [api-platform/core#5762]
**API Platform version(s) affected**: > 3.0.0

**Description**  
I can't update api-platform/core beyond 3.0.0.
I'm using elasticsearch/elasticsearch 8.9.0 but I'm not using it under ApiResource.
How can I update to the latest version of api-platform/core ?

**Additional Context**  

Version : 

PHP : 8.2.8
SF : v6.3.0
API Platform : 3.0.0
elasticsearch : v8.9.0
```
  Problem 1
    - Root composer.json requires api-platform/core v3.1.5 -> satisfiable by api-platform/core[v3.1.5].
    - api-platform/core v3.1.5 conflicts with elasticsearch/elasticsearch >=8.0.
    - elasticsearch/elasticsearch is locked to version v8.9.0 and an update of this package was not requested.
```

Thank you

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/5503
