### ISSUE TITLE
Resource "ApiPlatform\ApiResource\Error" not found in . 

### ISSUE THREAD

**Issue by PhilETaylor** [api-platform/core#5763]
**API Platform version(s) affected**:  api-platform/core: v3.1.14

**Description**  

Trying to install API Platform into existing Symfony 6.3.x application

**How to reproduce**  

I just installed Api Platform into my existing Symfoyn application and then reloaded the web page, instant crash to this error message. 

**Possible Solution**  
The class `ApiPlatform\ApiResource\Error` doesnt even seem to be in v 3.1.14, but there are references in the history of the project on GitHub - im assuming the class has been removed but something still looking for it - but Im at a loss to what as the string doesnt exist anywhere in /vendor 

![dev mybackups guru_](https://github.com/api-platform/core/assets/400092/48fa852a-2bd0-4638-a46c-4809acd0c9d9)

**Additional Context**

**Comment by soyuka** [comment]
this class doesn't exist on 3.1, remove your cache

**Comment by soyuka** [comment]
you're still on `main` then in the composer.lock

**Comment by PhilETaylor** [comment]
Also not the case :( 
![ScreenShot-2023-08-21-13 26 51](https://github.com/api-platform/core/assets/400092/b072059e-607e-4d11-a389-19722ecf562c)

**Comment by PhilETaylor** [comment]
my bad.. it seems resources were being cached into redis db and not just in the var/cache folder and it also seems a bin/console clear:cache was not flushing them

As soon as I flushdb the whole redis I could then get past this error. 

Sorry for the waste of time here. Im an idiot, and wasted HOURS on this on Sunday afternoon when it was my own fault caching too much into redis. :(
