### ISSUE TITLE
Provide default operation name templates (collection and item) in API Platform configuration 

### ISSUE THREAD

**Issue by alebedev80** [api-platform/core#5775]
**Description**  
Default operation's name template changed from version 3. Most of my event subscribers ans data providers are using operation name(. The template is hardcoded here [src/Metadata/Resource/Factory/OperationDefaultsTrait.php:227](https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/OperationDefaultsTrait.php#L227). Will be good to extract string templates per collection and item operation to API Platform configuration file.

**Example**  
In version 2.7 it was
`api_groups_get_collection`
`api_groups_get_item`

In version 3.0
`_api_groups_get_collection`
`_api_groups_get`

**Comment by soyuka** [comment]
solution: create a metadata factory overriding the names, in 2.7 and 3.0 we had an unicity issue that had to be fixed in 3.1.
