### ISSUE TITLE
Incompatibility api-platform 2.7 and Symfony 4.4

### ISSUE THREAD

**Issue by clement-muset** [api-platform/core#5796]
**API Platform version(s) affected**: 2.7

**Description**  
A method is used in ApiPlatform\Api\IdentifiersExtractor at line 113 : getCollectionValueTypes(). 
In the package symfony/property-info v4.4, the method of Symfony\Component\PropertyInfo\Type is getCollectionValueType(), without "s" (return a Type, not an array).

**Comment by paullallier** [comment]
2.7 has this:
`"symfony/property-info": "^3.4 || ^4.4 || ^5.2.1 || ^6.0"`

But I think it might actually need:
`"symfony/property-info": "^5.3 || ^6.0"`

I've not checked if that's compatible with the other package requirements

**Comment by soyuka** [comment]
2.7 is not maintained anymore unless for security issues.
