### ISSUE TITLE
[AbstractItemNormalizer] Serialization circular error

### ISSUE THREAD

**Issue by mpiot** [api-platform/core#5809]
**API Platform version(s) affected**: >3.1.15

**Description**  
Since the PR #5663, there is an error by using Symfony Live Component on entity that refers to one linked to an API Resource.

**Possible Solution**  
There is a change in the `AbstractItemNormalizer` on lines 589-596:

Before
```php
           $operation = $context['root_operation'] ?? $context['operation'] ?? null;

            if (!$operation && $this->resourceMetadataCollectionFactory && $this->resourceClassResolver->isResourceClass($context['resource_class'])) {
                $resourceClass = $this->resourceClassResolver->getResourceClass(null, $context['resource_class']); // fix for abstract classes and interfaces
                $operation = $this->resourceMetadataCollectionFactory->create($resourceClass)->getOperation($context['root_operation_name'] ?? $context['operation_name'] ?? null);
            }

            if ($operation) {
```

After
```php
if ($operation = ($context['root_operation'] ?? null)) {
```

If I re-add the previous way, all code works well.

**Comment by stephanvierkant** [comment]
You closed this issue. How did you fix it? I've got the same issue.

**Comment by mpiot** [comment]
It looks like before that PR ApiPlatform do not have the expected behavior and take in charge the serialization when using LiveConponent and refer to a Resource.

If I use a version before (when it works), and remove ApiResource from entities the same error appear.

I've closed it for that reason.

**Comment by mpiot** [comment]
After investigations, it seems using: `useSerializerForHydration` from `LiveProp` is tricky if related to an `ApiResource`, in my case it passes by the ApiPlatform normalizer but without options, but also by non ApiPlatform normalizer...

In my case, by totally remove ApiPlatform from the project I've some errors due to a circular error on specific Entity, and with ApiPlatform enabled I've also a circular error but on another entity.

Because the serializer  try to resolve all ManyToOne relations, I've use `hydrateWith` and `dehydrateWith` methods of `LiveProp`, I'll check if we can find a way to disable the Serializer to throw all relations, in this case, maybe just using `useSerializerForHydration` with `serializationContext` should work.

**Comment by norkunas** [comment]
We had the same problem, so implemented a custom hydrator for LiveComponents which adds `live => true` to context and then a custom `LiveEntityNormalizer` which handles the entities/api resources manually if the `live` is in context

**Comment by norkunas** [comment]
I'm pretty sure that it would work without, but it would be too hard to remove it.

> but it seems reasonable that ApiPlatform should not handle the Normalization in the case of LiveComponent.

yes, because symfony forms doesn't send iri's but plain identifiers, so api-platform must not handle this.. but it detects that the entity is an api resource and starts to handle it..

**Comment by stephanvierkant** [comment]
I'm not using Symfony UX Live and still have this problem.

**Comment by soyuka** [comment]
There's a way to support plain identifiers: https://api-platform.com/docs/core/serialization/#plain-identifiers

**Comment by mpiot** [comment]
Thanks @soyuka for help us :)

When we use the Serializer to serialize an antity, if this one is an ApiResource, then ApiPlatform handle it (but we do not want, because it's not an API request). In that case, I do not really understand the link between Plain Identifers and ApiPlatform handle all serialization even when it didn't.

This problem is mentionned for exemple in https://symfonycasts.com/screencast/api-platform-security/data-page-load#serializing-to-json-ld-in-twig
