### ISSUE TITLE
[UriVariable] - Pass string as urivariable

### ISSUE THREAD

**Issue by JMauclair** [api-platform/core#5818]
Hi guys,

I've been digging into this issue since many hours, but didnt found my way.

I've got a custom provider called GetProductByEan which give me the ability to find a product with his EAN in my DB.

But now I'm trying to add the possibility to find the product with is SKU (like 'JGF-JFJGN-KGKG') but when I pass a string value in my url 
('/products/{id}/{ean}'), then ean value is always 0

Is there a way to define the type of my urivariable to pass my string in the url ?

**Comment by soyuka** [comment]
show me your resource definition please you're probably missing something

**Comment by JMauclair** [comment]
Hi,

Thanks for replying !

Here is my ressource definition :

`new Get(uriTemplate: '/products/{id}/{ean}', class: Configuration::class, provider: GetProductByEan::class)`

**Comment by soyuka** [comment]
where are uriVariables ? we can't guess them from your uriTemplate

**Comment by JMauclair** [comment]
The uriVariables are id and ean, as it seems.
Then I use it in my provider that way :

```  
public function provide(Operation $operation, array $uriVariables = [], array $context = []): object
    {

        $configuration = $this->doctrine->getRepository(Configuration::class)->find($uriVariables['id']);
        $productService = new ProductsService($configuration, $this->doctrine);
        $product_values = $productService->getProductByEan($uriVariables['ean']);
        if ($product_values) {
            return $productService->getProduct($product_values['id_product'], $product_values['id_product_attribute']);
        }
        return (object)[
            'error' => 'Aucun produit ne correspond'
        ];
    }
