### ISSUE TITLE
[ApiProperty] using 'writable: false' will not remove the property from POST / PUT / PATCH

### ISSUE THREAD

**Issue by llupa** [api-platform/core#5821]
**API Platform version(s) affected**: ^3.1 
locked at: 3.1.17 / I have not checked previous versions.

**Description**  
Using `#[ApiProperty(writable: false)]` on an entity property does not remove it from the body payload for POST / PUT / PATCH. This seems to work only when you use `#[ApiProperty(readable: false, writable: false)]`. 

Edit: Worth mentioning that the intent of the feature is working correctly. If a property is marked as non-writable then it does not matter if the payload attempts to write any data there. This will be ignored. The only issue is on the Schema definition and causes confusion for consumers of the API.

**Comment by soyuka** [comment]
These flags are used internally I guess you're speaking about the JSON schema (body payload ?) this can be customized as needed or using a DTO without these properties.

**Comment by llupa** [comment]
Hello @soyuka, 

Yes it is about the JSON Schema. If this is an intended behaviour then would you say a clarification over the docs would also help? 

My colleagues and I all misunderstood this the same way :D 

I can attempt for a doc update proposal.
