### ISSUE TITLE
[Discussion] Authorization

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#583]
Currently I'm doing authorization using a combination of the following:
- Symfony Security voters - for controlling access to individual resources, plus some coarse role-based rules, e.g. only admins can create a product
- Symfony Serializer normalizers - for controlling write access at the field level during create / edit
- ~~API Platform filters - for controlling access to resource collections~~ bad idea, see https://github.com/api-platform/core/issues/583#issuecomment-228011804

Thoughts?

**Comment by polc** [comment]
I don't know for security filters, on my side I use Security Voters for collection: I do a `foreach ` to check if the user has access to every item in the collection (maybe not optimal).

For write access at the field level I'm using a custom validator `@AccessRole({"ROLE_ADMIN"})` 

 I'm wondering if a security listener couldn't be integrated to API Platform by default as it's quite common to use security voters. (I think to a listener looking like this maybe : https://gist.github.com/polc/c2321fefeb977d6c4bdd06748221de37).

**Comment by teohhanhui** [comment]
> I do a foreach to check if the user has access to every item in the collection (maybe not optimal).

Interesting. I suppose you could consider it as "VIEW" (if you're using attributes same as the Symfony ACL conventions).

**Comment by teohhanhui** [comment]
@polc Here is mine for comparison: https://gist.github.com/teohhanhui/27cd70474eb17e72486c1e4650a2f23a

I've also included my base `ResourceVoter` which is then decorated by resource type-specific voters.

**Comment by teohhanhui** [comment]
> For write access at the field level I'm using a custom validator @AccessRole({"ROLE_ADMIN"})

I considered that too, but it seems odd to have the Validator care about anything else other than the object being validated.

It's actually very easy to do with a custom normalizer: https://gist.github.com/teohhanhui/38905f232f0a72386138a2e9e4fe61cf

**Comment by soyuka** [comment]
#521 #395 some relevant informations there

> 
- Symfony Security voters - for controlling access to individual resources, plus some coarse role-based rules, e.g. only admins can create a product

Same here

>
- Symfony Serializer normalizers - for controlling write access at the field level during create / edit

Didn't implement this yet, but I had about the same in mind.

> 
- API Platform filters - for controlling access to resource collections

What do you mean by that?

**Comment by teohhanhui** [comment]
@soyuka

> > * API Platform filters - for controlling access to resource collections

> What do you mean by that?

Actually, the reason why I started this discussion is because I ran into some limitations with that approach... I was enforcing certain mandatory filters to limit access, but it doesn't scale well when I add more filters (which means there are more combinations of different filters - things start to become too complicated and I'm not even sure if it's practical anymore). Looks like @polc's approach of looping through objects in the collection is better.

**Comment by polc** [comment]
> I considered that too, but it seems odd to have the Validator care about anything else other than the object being validated.

You're right is seem pretty odd.

The problem I see with your AccessControlListener is you can't use the resource attributes in the voter.

**Comment by teohhanhui** [comment]
> The problem I see with your AccessControlListener is you can't use the resource attributes in the voter.

Yes. I'm changing it to use `kernel.view`.

**Comment by teohhanhui** [comment]
@polc I've realized that the entire idea of performing resource-based authorization on `kernel.view` is deeply flawed for `PUT` operations, because the denormalization could have changed the attributes on the entity we use to decide on whether to grant / deny access.

Or am I wrong?

**Comment by teohhanhui** [comment]
We need to be able to get access to the unchanged entity. This would be possible if normalization / denormalization is done in a `kernel.view` listener. Thoughts, @dunglas?

**Comment by dunglas** [comment]
The normalization is already done `kernel.view`. Maybe can we do the denormalization at the `kernel.request` event?

**Comment by teohhanhui** [comment]
Since `kernel.request` is before `kernel.controller`, so we'll have no need for the controller / action then?

**Comment by dunglas** [comment]
@teohhanhui ok I've just dived into the code and you're right. `kernel.view` is the right event. Another possibility is to store the original entity in a request attribute but it's less elegant.

**Comment by dunglas** [comment]
I'm working on a PR.

**Comment by teohhanhui** [comment]
Actually it's not so far-fetched for us to remove the controller / action altogether. Just replace them with a no-op and do everything in event listeners.

**Comment by teohhanhui** [comment]
Coming back to the topic of this discussion, there is still a problem I haven't been able to figure out...

How do I permit / deny state changes based on arbitrary and/or complex business rules? Say, an admin can only change the `orderStatus` in an `Order`, but nothing else. And even the state transitions allowed for the `orderStatus` are limited.

**Comment by dunglas** [comment]
@teohhanhui I usually create custom validator dealing with the Doctrine UOW to do such validations.

**Comment by dunglas** [comment]
The new Symfony Workflow component can be useful here too.

**Comment by Simperfit** [comment]
@teohhanhui I think the workflow component will fit this.

What is the ETA of this discussion ? What should we do ?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/938 should fit most use cases. Complex ones are hard to solve in a general context. 
We just need more docs on #938 :p.

**Comment by Simperfit** [comment]
I will create an issue on doc
