### ISSUE TITLE
Eager Loading Extension is not joining some *toOne that should be joined

### ISSUE THREAD

**Issue by MariusJam** [api-platform/core#5847]
**API Platform version(s) affected**: 3.1.18

**Description**  

In some cases, the EagerLoadingExtension misses some joins it should normally load eagerly. This happens when a *ToOne relationship shares the same `inversedBy` name than in the parent class.

**How to reproduce**  

Given the three ApiResources below :

```php
#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ["groups" => ["employee:get"]],
        )
    ]
)]
#[ORM\Entity]
class Employee
{
   // [...]

    #[ORM\OneToMany(mappedBy: 'employee', targetEntity: Subscription::class)]
    #[Groups(['employee:get'])]
    public Collection $subscriptions;
}
```

```php
#[ApiResource]
#[ORM\Entity]
class Subscription
{
    // [...]

    #[ORM\ManyToOne(inversedBy: 'subscriptions')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['employee:get'])]
    public Project $project;
}
```

```php
#[ApiResource]
#[ORM\Entity]
class Project
{
   // [...]

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Subscription::class)]
    public iterable $subscriptions;
}
```

If you request `GET /employees`, the relation employee.subscriptions is correctly eager fetched but not the relation employee.subscriptions.project. This is due to the below piece of code in the EagerLoadingExtension which skips the eager loading if the inversedBy property has the same name as the parent association. But, in our case, the name is the same but it does not refer to the same class.

```php
// Avoid joining back to the parent that we just came from, but only on *ToOne relations
            if (
                null !== $parentAssociation
                && isset($mapping['inversedBy'])
                && $mapping['inversedBy'] === $parentAssociation
                && $mapping['type'] & ClassMetadata::TO_ONE
            ) {
                continue;
            }
```

**Possible Solution**  

Not completely sure, but checking additionally that the parent class is the same as the target one before skipping the eager loading could fix the issue.

**Comment by soyuka** [comment]
I guess this would break some other use cases? feel free to propose a patch, or to create your own query (it'll always be better)

**Comment by MariusJam** [comment]
Hi @soyuka,

Sorry for the late reply. I just proposed a PR on this. 

I'm not sure whether this would break some use cases. Maybe this might lead to some circular reference in some rare cases or, reuse of an already existing join alias if someone, by bad luck, was using the same alias as the one generated by the queryNameGenerator.

Could also have impact on performances, in good or bad, depending on the cases.

I let you decide what to do with the PR, I understand this can be considered a bit risky, at least on the stable branch. And, as you said there are other solutions as writing our own query or using doctrine extensions. But still, there is an existing bug currently on this eager joins feature, would be great to fix it.

**Comment by soyuka** [comment]
your patch makes sense indeed
