### ISSUE TITLE
Implementation of DTO for Collection in v3

### ISSUE THREAD

**Issue by botjaeger** [api-platform/core#5867]
https://api-platform.com/docs/core/dto/#implementing-a-read-operation-with-an-output-different-from-the-resource

I'm struggling to implement DTO for GetCollection operation. The docs shown example only for GetItem.

**Comment by soyuka** [comment]
please don't use `output` just declare a `GetCollection` on a DTO and use a provider for the data source.

**Comment by botjaeger** [comment]
Do we have some examples? Still can't figure it out.

**Comment by SherinBloemendaal** [comment]
> Do we have some examples? Still can't figure it out.

@botjaeger Maybe this helps: https://symfonycasts.com/screencast/api-platform-extending/provider-return-dto
