### ISSUE TITLE
Missing doctrine/annotations Dependency in SubresourceTransformer

### ISSUE THREAD

**Issue by roukmoute** [api-platform/core#5879]
**API Platform version(s) affected**: 2.7

**Description**  
In the [SubresourceTransformer.php](https://github.com/api-platform/core/blob/2.7/src/Core/Upgrade/SubresourceTransformer.php) file, there's a call to `Doctrine\Common\Annotations\AnnotationReader`. However, `AnnotationReader` isn't required in the project's `composer.json`, which can lead to dependency issues when using the subresource transformer. The exact version that seems to be referenced in the code is [2.1 from doctrine/annotations](https://github.com/doctrine/common/blob/2.1.x/lib/Doctrine/Common/Annotations/AnnotationReader.php).

Additionally, I cannot test this with API Platform 3 as I am on Symfony 5. When attempting to upgrade, I receive the error: `api-platform/core[v3.0.0, ..., v3.1.20] require symfony/http-foundation ^6.1.`

**How to reproduce**

1.  Install API Platform version 2.7.
2.  Try to use the SubresourceTransformer.
3.  The system might throw an error regarding the missing `Doctrine\Common\Annotations\AnnotationReader` class:
```sh
In SubresourceTransformer.php line 34:
                                                                                            
  Attempted to load class "AnnotationReader" from namespace "Doctrine\Common\Annotations".  
  Did you forget a "use" statement for another namespace?                                   
                                                                                            
```

**Possible Solution**  
Add `doctrine/annotations` as a dependency in the `composer.json` or check if the use of `AnnotationReader` in this context is really necessary and consider an alternative.

**Additional Context**  
The absence of this dependency can cause issues for those trying to use the subresource transformer without having `doctrine/annotations` previously installed.

**Comment by soyuka** [comment]
https://opencollective.com/api-platform/projects/27-lts

**Comment by roukmoute** [comment]
Hello,

Thank you for your quick reply. I consulted the link you shared with me concerning "https://opencollective.com/api-platform/projects/27-lts". Could I have more information on the relevance of this link to my original ticket? I want to understand your perspective.

My intention in creating the ticket was to contribute constructively to the project by pointing out a possible problem. I was hoping to obtain clarification or a possible solution to the issue mentioned.

If financial contributions are suggested for certain requests, it would be appreciated if this could be explained in a little more detail. This would help to better understand the context of your response.

I thank you in advance for your understanding and hope that we can work together positively to resolve this issue.

**Comment by soyuka** [comment]
Hi, indeed it's my bad the documentation isn't up to date but as 3.2 is out, 2.7 is now in EOL (end of life). I spent a lot of time on providing a BC layer but I can't spend time maintaining it anymore. We're trying to fund a 2.7 LTS (long term stable) version and we added information on the open collective page, I thought it'd provide enough information to why this won't get fixed.

If installing `doctrine/annotation` does solve the issue, then this is good enough, especially that the script is used once then you can remove that dependency. 

Sorry I wasn't clear enough in my previous answer :).
