### ISSUE TITLE
Add Eloquent `apiProperties`

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#5885]
**Description**  
We want to add `ApiProperty` to Eloquent models. To do so (inspired by  https://github.com/api-platform/core/pull/4197) we will add a `protected $apiProperties` on an Eloquent Model: 

```
class Book extends Model {
    protected $apiProperties = ['name' => new ApiProperty(...)];
}
```

These need to be read by the Laravel specific `PropertyMetadataFactories`.

https://github.com/api-platform/core/pull/5882

**Comment by vinceAmstoutz** [comment]
@alanpoulain @soyuka Should be closed no?
