### ISSUE TITLE
Custom controller when `event_listeners_backward_compatibility_layer` set to `false`

### ISSUE THREAD

**Issue by alexndlm** [api-platform/core#5887]
**API Platform version(s) affected**: 3.2.0

When option `event_listeners_backward_compatibility_layer` is set to `false`, should event listener be skipped for all controllers?

**Comment by soyuka** [comment]
I think that if you use controllers the best is to keep this option to `true`. I'm working on adding an option to enable listeners on a single operation/resource. Note that listeners won't disappear we will keep them as part of our Symfony bridge. 

I also want to add a way to help using controllers with API Platform but didn't manage to work on it for now.

**Comment by alexndlm** [comment]
Got it. Thank you. I look to the future with faith :)
