### ISSUE TITLE
Regression during 3.1 -> 3.2 upgrade

### ISSUE THREAD

**Issue by bpolaszek** [api-platform/core#5892]
Hey there - I've got several API-Platform 3.1 projects, but none of them would upgrade to 3.2 without pain. 
I didn't notice any upgrade guide about those versions, so I assumed it would require no effort, but it's not the case. 

For example, I’ve got [a very lightweight sample API-Platform project](https://github.com/bpolaszek/rolladice) that I use for training sessions.
It’s currently running API-Platform **3.1.14**, but upgrading it to **3.2** generates a regression:

```php
public function testAnUnknownUserGetsANotFoundError(): void
{
    static::createClient()->request('POST', '/auth/reset-password', [
        'json' => [
            'email' => 'foobar@example.com',
        ],
    ]);

    self::assertResponseStatusCodeSame(Response::HTTP_NOT_FOUND);
}
```

This endpoint `/auth/reset-password` uses a _Processor_ to throw a 404 whenever the provided e-mail does not exist.

It works on **3.1**. Nothing really complex here.

But on **3.2**, [it fails](https://github.com/bpolaszek/rolladice/actions/runs/6548329661/job/17782793759?pr=7#step:13:41):

> Unable to generate an IRI for the item of type “App\Entity\User”

Any ideas?

NB: Relevant code fragments [here](https://github.com/bpolaszek/rolladice/blob/main/api/src/Entity/User.php#L25-L31), [here](https://github.com/bpolaszek/rolladice/blob/main/api/src/State/UserResetPasswordRequestProcessor.php) and [there](https://github.com/bpolaszek/rolladice/blob/main/api/tests/Api/User/UserResetPasswordTest.php#L44-L53).

**Comment by soyuka** [comment]
Indeed, I wish more people would've tried the beta version but see #5845 has the same issues and a fix is pending: https://github.com/api-platform/core/pull/5891 

I'll release that Friday thanks for your report!

**Comment by bpolaszek** [comment]
Good news, I'll wait 🙂 

Thanks for all your work!

**Comment by soyuka** [comment]
3.2.1 is out and should fix these issues!

**Comment by bpolaszek** [comment]
CI passes, thanks a lot! 🎉
https://github.com/bpolaszek/rolladice/pull/7
