### ISSUE TITLE
IRI links on POST and PUT requests not documented correctly in 3.2

### ISSUE THREAD

**Issue by paullallier** [api-platform/core#5900]
**API Platform version(s) affected**: 3.2.1

**Description**  
IRIs to other resources including in POST and PUT requests are being displayed on the Swagger docs (reDoc looks OK).  
<img width="420" alt="Screenshot 2023-10-19 at 10 18 33" src="https://github.com/api-platform/core/assets/42591123/7cf2bf77-e1c3-46ee-8eb3-6fb56109df75">

**How to reproduce**  
I've previously seen it with the BagOfTests Entity from here - that's probably a good starting points for a test case.  
https://github.com/api-platform/core/pull/5810#issuecomment-1715400982

(Also mentioned by Dmitry Monk on Slack - not sure he's on here)

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/5638 
https://github.com/api-platform/core/pull/4669
https://github.com/api-platform/core/pull/4681

we don't specify any example value on swagger ui see related pull requests and comments.

**Comment by paullallier** [comment]
I don't think I entirely understand what you mean by "we don't specify any example value on swagger ui"?  That screenshot is the example values box from my SwaggerUI and I don't think I've turned anything extra on?

And it's a regression from the behaviour on 3.1 which showed this - not an IRI, but not a garbled string either:
<img width="340" alt="Screenshot 2023-10-19 at 10 55 04" src="https://github.com/api-platform/core/assets/42591123/db51bcef-32f7-47ca-b525-a709c30bb372">

**Comment by GwendolenLynch** [comment]
@paullallier I've hit the same thing, and have been trying to dig into what is happening …

Exporting the Open API docs and loading them in [SwaggerUI](https://editor-next.swagger.io/), I noticed that simply switching `"openapi": "3.1.0"` to `"openapi": "3.0.0"` changes `"path/실례.html"` back to `"string"`.

Digging into SwaggerUI it looks as though [string.js](https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/json-schema-2020-12-samples/fn/types/string.js#L63) calls [iri-reference.js](https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/json-schema-2020-12-samples/fn/generators/iri-reference.js#L4) when no example(s) text is found.

Additionally, when using Open API 3.1 — as generated by API Platform 3.2 — and changing relevant schema parts to have `"examples": []` gives a more logical display.

From:
```json
"country": {
  "type": "string",
  "format": "iri-reference"
}
```
To:
```json
"country": {
  "type": "string",
  "format": "iri-reference",
  "examples": [
    "/api/countries/abc-123"
  ]
}
```

How this should be handled by API Platform, however, is another question :innocent:

**Comment by weaverryan** [comment]
About the `path/실례.html` part, we've had 3 users on Symfonycasts - https://symfonycasts.com/screencast/api-platform-extending/entity-item-provider#comment-30714 - mentioning this same thing. I can't provide any more context, but this definitely looks like something that some users are coming up against :)

**Comment by vantoscenco** [comment]
same here

**Comment by Corepex** [comment]
I have the same issue. It seems to appear only for relations ...

**Comment by esdras-splitpay** [comment]
Passando pelo mesmo problema
for me too :(
![evidence_platform_issue](https://github.com/api-platform/core/assets/150732366/fefaba60-1b73-417f-bff2-d3b93c234b9c)

**Comment by bendavies** [comment]
i'm workaround around this globally at the moment like this:
```php
<?php

declare(strict_types=1);

namespace BindHQ\Api\ApiPlatform;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\Property\Factory\PropertyMetadataFactoryInterface;
use BindHQ\Api\ApiResource\AgencyApi;
use BindHQ\Api\ApiResource\AgentApi;
use BindHQ\Api\ApiResource\ApplicationApi;
use BindHQ\Api\ApiResource\CarrierApi;
use BindHQ\Api\ApiResource\DivisionApi;
use BindHQ\Api\ApiResource\InsuredApi;
use BindHQ\Api\ApiResource\MarketingCompanyApi;
use BindHQ\Api\ApiResource\UserApi;
use Psl;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;

#[AsDecorator('api_platform.json_schema.metadata.property.metadata_factory.schema')]
class SchemaPropertyMetadataFactoryDecorator implements PropertyMetadataFactoryInterface
{
    private static array $examples = [
        AgencyApi::class => '/api/v2/agencies/1',
        AgentApi::class => '/api/v2/agents/1',
        ApplicationApi::class => '/api/v2/application/1',
        CarrierApi::class => '/api/v2/carriers/1',
        DivisionApi::class => '/api/v2/divisions/1',
        InsuredApi::class => '/api/v2/insureds/1',
        MarketingCompanyApi::class => '/api/v2/marketing-companies/1',
        UserApi::class => '/api/v2/users/1',
    ];

    public function __construct(
        private readonly PropertyMetadataFactoryInterface $decorated,
    ) {
    }

    public function create(string $resourceClass, string $property, array $options = []): ApiProperty
    {
        $decorated = $this->decorated->create($resourceClass, $property, $options);
        $schema = $decorated->getSchema();

        if (\array_key_exists('format', $schema) && 'iri-reference' === $schema['format']) {
            $class = $decorated->getBuiltinTypes()[0]->getClassName();

            Psl\invariant(\array_key_exists($class, self::$examples), 'No example for class %s', $class);

            $schema['example'] = self::$examples[$class];

            return $decorated->withSchema($schema);
        }

        return $decorated;
    }
}

```

**Comment by soyuka** [comment]
should we provide examples? The path is generated by swagger we leave that empty... Adding an `example` value like at https://github.com/api-platform/demo/blob/main/api/src/Entity/Book.php#L108 works also.

**Comment by bendavies** [comment]
personally i don't want to add `example` to every `ApiProperty` as it would be a lot of repeated code.

for info, in the previous version of swagger ui, "string" was the example. seems better than some korean characters which look like a bug to be honest.

i wonder if api-platform can generate sane iri examples?

**Comment by soyuka** [comment]
it's a bug on swagger ui not on api platform...

**Comment by soyuka** [comment]
Let's fallback on https://github.com/api-platform/core/issues/6058

**Comment by dwgebler** [comment]
@bendavies thanks for your workaround, I've expanded on it to make detecting Doctrine entities and automatically generating correct examples for them, including embedded collections for Many relations...further manual classes for DTOs and the like could easily be added.

```php
<?php

namespace App\OpenApi;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\Property\Factory\PropertyMetadataFactoryInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\String\Inflector\EnglishInflector;
use function Symfony\Component\String\s;

#[AsDecorator('api_platform.json_schema.metadata.property.metadata_factory.schema')]
class SchemaPropertyMetadataFactory implements PropertyMetadataFactoryInterface
{
    private array $examples = [];

    public function __construct(
        private readonly PropertyMetadataFactoryInterface $decorated,
        private readonly EntityManagerInterface $entityManager
    ) {
        $inflector = new EnglishInflector();
        $entities = $this->entityManager->getConfiguration()->getMetadataDriverImpl()->getAllClassNames();
        foreach ($entities as $entity) {
            $inflected = s(str_replace('App\Entity\\', '', $entity))->snake();
            $inflected = $inflector->pluralize(strtolower($inflected))[0];
            $this->examples[$entity] = '/api/'. $inflected .'/1';
        }
    }

    public function create(string $resourceClass, string $property, array $options = []): ApiProperty
    {
        $decorated = $this->decorated->create($resourceClass, $property, $options);
        $schema = $decorated->getSchema();

        if (isset($schema['type']) && $schema['type'] === 'array' && isset($schema['items']['format']) && 'iri-reference' === $schema['items']['format']) {
            $class = $this->entityManager->getClassMetadata($resourceClass)->getAssociationTargetClass($property);

            if (!\array_key_exists($class, $this->examples)) {
                throw new \InvalidArgumentException(\sprintf('No example for class %s', $class));
            }

            $schema['items']['example'] = $this->examples[$class];

            return $decorated->withSchema($schema);

        }

        if (\array_key_exists('format', $schema) && 'iri-reference' === $schema['format']) {
            $class = $decorated->getBuiltinTypes()[0]->getClassName();

            if (!\array_key_exists($class, $this->examples)) {
                throw new \InvalidArgumentException(\sprintf('No example for class %s', $class));
            }

            $schema['example'] = $this->examples[$class];

            return $decorated->withSchema($schema);
        }

        return $decorated;
    }
}
```
