### ISSUE TITLE
Undefined array key "owl:maxCardinality"

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#5913]
**API Platform version(s) affected**: 3.2.0
Nelmio/ApiDocBundle: 4.12.0

**Description**  

The documentation cannot be generated and generates this error:

>  Caused by
>  ErrorException: Undefined array key "owl:maxCardinality"
>  
>  /srv/app/vendor/nelmio/api-doc-bundle/OpenApiPhp/Util.php:412
>  /srv/app/vendor/symfony/framework-bundle/Test/BrowserKitAssertionsTrait.php:33
>  /srv/app/tests/App/api/ApiDocRouteTest.php:27

With

- ApiPlatform 3.1.21
- Nelmio/ApiDocBundle: 4.12.0

All works well.

I don't know if it's a ApiDocBundle's fault or one of ApiPlatform/core's, but, as ApiDocBundle is working well with ApiPlatform/core 3.1.19, I'm posting the issue here.

I opened an [issue on ApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle/issues/2140), but closed it as the most recent release is of ApiPlatform.

**Comment by soyuka** [comment]
Mhh I wasn't aware we were still supporting this bundle... We introduced that inside JSON schemas with https://github.com/api-platform/core/pull/5470.

**Comment by Aerendir** [comment]
@soyuka , it is the only way I know to generate the docs of the API: are there others?

Anyway, I think that is the bundle that supports Api Platform, not the other way around.

So, maybe that the fix should be done in the bindle, not in Api Platform... But I don't know: this is the reason why I'm first asking here...

**Comment by soyuka** [comment]
just use OpenAPI and swagger? we also support Hydra

**Comment by Aerendir** [comment]
It is fixed by https://github.com/api-platform/core/releases/tag/v3.2.2 🎉
