### ISSUE TITLE
Custom input dto: ID field disappears

### ISSUE THREAD

**Issue by codedge** [api-platform/core#5917]
**API Platform version(s) affected**: 3.2.1

**Description**  
When using a custom input dto, that contains an `id` field, this field is not reflected in the generated GraphQL API schema.
The other field, `someIds`, is properly reflected inside the docs.

**How to reproduce**  

**Entity**

```php
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GraphQl;

#[
  ORM\Entity,
  ApiResource(
    mercure: false,
    graphQlOperations: [
            new GraphQl\Query(),
            new GraphQl\QueryCollection(paginationType: 'page'),
            new GraphQl\Mutation(
                resolver: MyCustomResolver::class,
                input: MyCustomDto::class,
                name: 'assignImagesTo',
            ),
    ]
  )
]
class MyEntity
{
  
}
```

**MyCustomDto**

```php
final class MyCustomDto
{
    #[
        Assert\NotBlank,
        Assert\Uuid,
    ]
    public string $id;

    /**
     * @var array<string>
     */
    public array $someIds = [];

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): MyCustomDto
    {
        $this->id = $id;

        return $this;
    }

    public function getSomeIds(): array
    {
        return $this->someIds;
    }

    public function getSomeIds(array $ids): MyCustomDto
    {
        $this->someIds = $ids;

        return $this;
    }
}
```

Instead, the field `_id` needs to be given as input which is then hydrated into the DTOs field `id`. See the difference with underscore `_`.

![2023-10-23_093438](https://github.com/api-platform/core/assets/4409904/eb303baa-3816-479d-906a-8fa68e7dd99b)

**Possible Solution**  

**Additional Context**  

I am unsure if this is a bug or some magic. I could live with this change if this would be explained somewhere. To my knowledge this worked differently before and we could pass `_id` and/or `id` as fields to a mutation with custom dto.

**Comment by soyuka** [comment]
Mhh looks like a bug but not sure from where it comes (maybe related to https://github.com/api-platform/core/issues/5914 ?). Also you should avoid using input for that can't you declare the Mutation directly on the DTO?

**Comment by codedge** [comment]
> declare the Mutation directly on the DTO

Can you eleborate on that? I don't understand how I should define it diffently to the `input` and `resolver` inside the entity.

**Comment by soyuka** [comment]
```php
#[GraphQl\Mutation(
    resolver: MyCustomResolver::class,
)]
class MyDto {}
```

I wonder why the id field changes though...

**Comment by codedge** [comment]
@soyuka I found the place where the `id` field disappears. In [`FieldsBuilder.php`](https://github.com/api-platform/core/blob/main/src/GraphQl/Type/FieldsBuilder.php#L231) the `id` from the input DTO is rewritten to `_id`

```php
// guess union/intersect types: check each type until finding a valid one
foreach ($propertyTypes as $propertyType) {
    if ($fieldConfiguration = $this->getResourceFieldConfiguration($property, $propertyMetadata->getDescription(), $propertyMetadata->getDeprecationReason(), $propertyType, $resourceClass, $input, $operation, $depth, null !== $propertyMetadata->getSecurity())) {
        $fields['id' === $property ? '_id' : $this->normalizePropertyName($property, $resourceClass)] = $fieldConfiguration;
        // stop at the first valid type
        break;
    }
}
```

which was introduced with the [3.2.0 release](https://github.com/api-platform/core/compare/v3.1.15...v3.2.0#diff-d7bf2d1671fc1d774236691a30000b7d2c1a9296094faf093c98fd549f727bd5R231).

Can you explain the reasoning behind and if this is a bug?

**Comment by NicoHaase** [comment]
Do you have any additional ideas about this problem? I'm facing the same errors after updating from v3.1.x to v3.2.x
