### ISSUE TITLE
Release 3.2: ErrorNormalizer not being used, ErrorResource used instead

### ISSUE THREAD

**Issue by HectorOrdonez** [api-platform/core#5921]
**API Platform version(s) affected**: 3.2.*

**Description**  
In 3.1.19 I have a decorated ErrorNormalizer, so I can add customised data to the exception.

That worked fine.

In 3.2.* tests are failing because the expected custom data is not being returned.

After debugging the conclusion is that ErrorNormalizer is not being used, therefore the decoration logic is not reached.

It seems like the ErrorResource (ApiResource/Error.php) is used instead. 

I see we have now deprecation messages in the ErrorNormalizer and what seems to be a feature flag `skip_deprecated_exception_normalizers`, but the logic doesn't reach there at all.

The code that seems to be related to the problem is [this one](https://github.com/api-platform/core/pull/5433/files).

However I am having a hard time figuring out which part, and how can I solve this problem, if it is in my side.

**How to reproduce**  
I am not sure exactly what part is the problem, but I am guessing the decoration of the exception.

So the configuration would be something like:
```
    MyApp\ApiPlatform\Serializer\ErrorNormalizer:
        decorates: 'api_platform.problem.normalizer.error'
```

The logic of the decorator doesn't really matter, since it is not reached at all.

**Comment by soyuka** [comment]
Mhh indeed this is a hard one to cover bc on as this normalizer isn't used anymore, I'll come back to this. In the mean time can you give me a bit more details on the Exception: is it an HttpException or is it an exception from your own code or from vendors? Format used? What changes do you want inside the normalizer?

**Comment by HectorOrdonez** [comment]
Hello @soyuka and thanks for replying!

It is a domain exception from my own code used during an api call. In my custom exception I have an error code that I was including in the json response. 

In order to include the error code in the json response I was decorating the ErrorNormalizer, so I could hook the error code into the data being outputted.

**Comment by soyuka** [comment]
If it's a custom exception you can just declare it as a resource now it should work (https://github.com/api-platform/core/blob/main/src/ApiResource/Error.php), using a provider on an error works.

Anyways I have a pending patch for this sorry for the break!

**Comment by HectorOrdonez** [comment]
Hey @soyuka , thank you for your reply and the PR!

As I was trying to fix my code based on the changes, I realised something strange. Maybe I am missing something.

So the [Error resource](https://github.com/api-platform/core/blob/main/src/ApiResource/Error.php) has a function createFromException. This I imagine is triggered when there is an exception, and it is hit before the normalizers.

The exception's message is passed as an Error detail.

Then the Error is passed to the ErrorNormalizer, in case of using the deprecated one.

The ErrorNornalizer gets the detail from `getErrorMessage`, but that code does not get the detail from the Error, thus the exception's message is lost.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/6463 adding the feature to skip our handler if you want to rely on symfony's
