### ISSUE TITLE
IriConverter reuses unrelated root operation

### ISSUE THREAD

**Issue by irmantas** [api-platform/core#5926]
**API Platform version(s) affected**: 3.2 (upgrade from 2.6)

**Description**  

Hi,

Upgrading from 2.6 to 3.2, do not know if this bug or old 2.6 behavior and won't be fixed. But I believe more people may encounter this if not fixed.
With API platform >2.7 I get an error `Unable to generate an IRI for the item of type` if Resource has a custom collection of resources or value object with other Resource without relation (like subresources) between them.

**How to reproduce**  

```php
<?php

#[ApiResource]
class Post
{
    public int $id;
    public ContentCollection $content;
    public function getContentCollection(): ContentCollection
    {
        return $this->content;
    }
}

// ---

class ContentCollection implements \IteratorAggregate
{
    private array $items;
    public function __construct(ContentItemInterface ...$items)
    {
        $this->items = $items;
    }
    public function getIterator(): \ArrayIterator
    {
        return new \ArrayIterator($this->items);
    }
}

class MediaContentItem implements ContentItemInterface
{
    public string $type;
    public Media $value;
}

//---
#[ApiResource]
class Media
{
    public int $id;
    /* ... */
}

```

**Possible Solution**  

https://github.com/api-platform/core/blob/e10cc5ecf88b98f862222b2e3fea0f4ace94c515/src/Symfony/Routing/IriConverter.php#L130

In my case solution is just to change this line, but I believe it may break other things as well.
```php
if (!$operation || ($operation->getClass() != $resourceClass)) {
```

**Comment by soyuka** [comment]
if it's not a resource it goes through https://github.com/api-platform/core/blob/e10cc5ecf88b98f862222b2e3fea0f4ace94c515/src/Symfony/Routing/IriConverter.php#L122.

I'll test this though.

**Comment by soyuka** [comment]
What was the Request that errored?

**Comment by soyuka** [comment]
Can't reproduce: 
![20231027_14h13m21s_grim](https://github.com/api-platform/core/assets/1321971/a2cdc864-2694-4630-bf6d-0a03d449b6ec)

Used: 
```
#[Get(uriTemplate: 'issue5926', provider: [HasContent::class, 'provide'])]
class HasContent
{
    public int $id;
    public ContentCollection $content;

    public static function provide(Operation $operation, array $uriVariables = []): self
    {
        $y = new Media();
        $y->id = 2;

        $m = new MediaContentItem();
        $m->type = 'audio';
        $m->value = $y;

        $s = new self();
        $s->id = 1;
        $s->content = new ContentCollection($m);
        return $s;
    }
}
```

see https://github.com/soyuka/core/commit/4248008e6bbd295f5c652ab70f36ac84ed8d389f if you want to try to reproduce fork my branch and use `php -d memory_limit=-1 vendor/bin/behat features/issues/5926.feature`

**Comment by irmantas** [comment]
Thanks for addressing this issue. It seems I missed one important detail, we are using only JSON format for our API backend.  Reproduced issue here https://github.com/irmantas/api-issue-5926

**Comment by soyuka** [comment]
Thanks for the reproducer!
