### ISSUE TITLE
Custom normalizer not working in sub-entity

### ISSUE THREAD

**Issue by polc** [api-platform/core#593]
Hello, 

So for using the `MisdPhoneNumberBundle` I have wrote a custom normalizer (https://gist.github.com/polc/8e6ce48e9dcb33a36e9c5a632e80ed10).

Everything is working fine when I have just one entity: https://gist.github.com/polc/73b1c9f47c68682880714185b1ce1a57

When I do `POST /entities`
```
{
    "mobilePhone": "0620202020"
}
```
Then I get 
```
{
    "@context": "/contexts/Entity",
    "@id": "/entities/1",
    "@type": "Entity",
    "mobilePhone": "+33623025411"
}
```

But when I use `phone_number ` type in a sub entity : https://gist.github.com/polc/a69ee44024be9f4789d3773eb3ee1e89 

When I do `POST /entities ` 
```
{
    "address": {
        "mobilePhone": "0620202020"
    }
}
```

I got `Expected argument of type \"libphonenumber\\PhoneNumber\", \"string\" given`

Note that `Common\Address ` isn't a resource, just an entity.

**Comment by teohhanhui** [comment]
Related to https://github.com/api-platform/core/issues/528#issuecomment-227431881

**Comment by polc** [comment]
Even if there is a lot of non-related code, you can check this bug in my project, just `git clone https://github.com/polc/papolco-api` and run `vendor/bin/behat features/agencies.feature -vvv`. 

The second test will show you the error. The error is in `Agency` entity.

**Comment by dunglas** [comment]
You need to register a custom normalizer for address.

**Comment by polc** [comment]
The issue has been fixed there is some time ago (I didn't had to add a custom normalizer nor to change my tests). 
Thanks !
