### ISSUE TITLE
error 500 -> acces denied for 'document' endpoints

### ISSUE THREAD

**Issue by mJeromeDiaz** [api-platform/core#5938]
Hi all,

I have an entity named "Document"
    
```php
#[ORM\Entity(repositoryClass: DocumentRepository::class)]
#[ApiResource(
    collectionOperations: [
        "get" => ["security" => "is_granted('ROLE_GUEST')"],
        "post" => ["security" => "is_granted('ROLE_GUEST')"],
    ],
    itemOperations: [
        "get" => ["security" => "is_granted('ROLE_GUEST')"],
        "delete" => ["security" => "is_granted('ROLE_GUEST')"],
        "patch" => ["security" => "is_granted('ROLE_GUEST')"],
    ],
)]
class Document
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["read:bibliotheque"])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(["read:bibliotheque"])]
    private ?string $title = null;
```     
my security.yml     
```yml
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER: ROLE_GUEST
```
    
i m sure, i have an ROLE_ADMIN account, but, only for Document entity, i cant use any endpoint.

All other entities works perfectly, but for Document, in production (linux) i have an 500 Error Access Denied. (works on dev > windows) why is not an 403 error ? and why only for 1 entity ? "Document" is an reserved word for apiplatform or symfony ?

**Comment by hosseinsalemi** [comment]
Same problem, when I use `security_post_denormalize: 'is_granted(request, [previous_object, object])'` in `api_platform.yaml` configuration file.
