### ISSUE TITLE
In v3.2.* ErrorResource converts exceptions into generic Error before hitting the normalizer

### ISSUE THREAD

**Issue by HectorOrdonez** [api-platform/core#5948]
**API Platform version(s) affected**: 3.2.*

**Description**  
This is a continuation of this [bug](https://github.com/api-platform/core/issues/5921). 

After the fix the Error reaches the ErrorNormalizer, however it reaches it after `Error::createFromException` logic transforms the exception into a generic Error, and therefore any custom logic in a ErrorNormalizer has no access to the actual exception.

**Possible Solution**  
I believe a fix could be to include the original exception in the Error generated in `Error::createFromException`.

**Comment by soyuka** [comment]
I guess this got fixed by https://github.com/api-platform/core/issues/5963 ?

**Comment by HectorOrdonez** [comment]
I was running into complications trying to use this approach, so eventually I refactored the code to use the new ErrorResource.
