### ISSUE TITLE
3.2 missing json-ld context properties

### ISSUE THREAD

**Issue by kstefanini** [api-platform/core#5950]
**API Platform version(s) affected**: 3.2.4

**Description**  
After updating from last 3.1 to 3.2.4 some json-ld context are reported missing 

**How to reproduce**  
Order has an OneToOne relation to Address available threw #Groups(['order:read'])
```php
#src/Entity/Order.php
    #[Groups(['order:read'])]
    #[ORM\OneToOne(targetEntity: Address::class)]
    private ?Address $address = null;
```
json-ld context is missing from schema Address.jsonld-order.read but not from Address.jsonld-address.read

**Additional Context**  
Before 3.2
![image](https://github.com/api-platform/core/assets/5382753/3acbc1c6-004c-4483-82cb-ab21f72a71ac)
After 3.2
![image](https://github.com/api-platform/core/assets/5382753/8b912db5-4378-4f16-a0e8-eac5ab51b1b1)

Thanks in advance for your attention! :)

**Comment by pmontoya** [comment]
@vincentchalamon : in #5470, you deprecate the `ApiPlatform\JsonSchema\TypeFactory` and the sub schema is now generated calling 
```
$subSchema = $this->buildSchema($className, $format, Schema::TYPE_OUTPUT, null, $subSchema, $serializerContext + [self::FORCE_SUBSCHEMA => true], false);
```
in the `ApiPlatform\JsonSchema\SchemaFactory` class. As this is not the `ApiPlatform\Hydra\JsonSchema\SchemaFactory`, the json-ld context is not added.

I'm the sure to understand why you deprecate the `ApiPlatform\JsonSchema\TypeFactory` so do you have any idea on how to fix this bug ?

Thank you

**Comment by vincentchalamon** [comment]
[information] The `JsonSchema\TypeFactory` has been deprecated in https://github.com/api-platform/core/pull/5897.

**Comment by soyuka** [comment]
thanks for the report!

**Comment by ytilotti** [comment]
@soyuka, is this error still present in version 4.1?
