### ISSUE TITLE
doctrine/inflector deprecation is breaking change (plural of 'equipment')

### ISSUE THREAD

**Issue by acirulis** [api-platform/core#5957]
**API Platform version(s) affected**: 3.2.4

**Description**  
There is a deprecation: 
```
Using doctrine/inflector is deprecated since API Platform 3.2 and will be removed in API Platform 4. Use symfony/string instead. Run "composer require symfony/string" and set "keep_legacy_inflector" to false in config.
```

After implementing it, some routes will change. 

Specific example: 

Before:
`/api/equipment`
After
`/api/equipments`

According to https://www.britannica.com/dictionary/eb/qa/equipments-equipment-noncount-mass-noun-singular-plural
correct plural form of `equipment` is `equipment`. It also feels natural but I am not a native speaker.

Should I submit this as issue for symfony/string? Or there are other considerations? Thanks!

**Comment by paullallier** [comment]
Equipment as the plural would definitely be grammatically correct.

**Comment by paullallier** [comment]
@acirulis:  I've spotted a few other issues in the symfony/string inflector too so I'm going to raise a PR - hope you don't mind.

**Comment by simpletoimplement** [comment]
is it possible in api-platform to use my own inflector?  
adding new rules to string is a possible solution, but string has an inflector interface. maybe something like use "this" inflector if "that" inflector does not have rule for needed words?

**Comment by dunglas** [comment]
@simpletoimplement yes, just implement the interface provided by Symfony.

Closing as a PR is opened on SF and it's technically not a BC break (by default, the old library is used and a manual action must be done to switch).

**Comment by paullallier** [comment]
@acirulis FYI, this fix is in Symfony 5.4.32 and 6.3.9.

**Comment by acirulis** [comment]
Thanks, already updated.

**Comment by acirulis** [comment]
Oh, now I got plural "settingss" out of "settings" - should I open new issue?
