### ISSUE TITLE
Security config is not working correctly in 3.2

### ISSUE THREAD

**Issue by hosseinsalemi** [api-platform/core#5968]
**API Platform version(s) affected**: 3.2.4

**Description**  

I can't get `Request` object in my voters file  when I use `security` or `securityPostDenormalize` in entity. This worked correctly in API Platform 3.1.9.

**How to reproduce**  

```php
#[
    ApiResource(
        operations: [
            new Get(),
            new GetCollection(),
            new Post(denormalizationContext: ['groups' => [self::GROUP_DESERIALIZE_ADD]]),
        ],
        normalizationContext: ['groups' => [self::GROUP_SERIALIZE_VIEW]],
        securityPostDenormalize: 'is_granted(request, [previous_object, object])',
    ),
]
```

**Possible Solution**  

I think API Platform overwrite securityPostDenormalize value with `is_granted('ROLE_ADMIN')`.

**Additional Context**  

In voters file I get `"ROLE_ADMIN"` when dump `$attribute`. The `Request` object must be taken.

```php
protected function supports($attribute, $subject): bool
{
    dump($attribute);
}
```

**Comment by soyuka** [comment]
you still have this issue?

**Comment by hosseinsalemi** [comment]
I installed v3.2.11. This issue has been fixed. Thank you.

**Comment by soyuka** [comment]
thanks for your feedback

**Comment by hosseinsalemi** [comment]
Same problem in v3.3.2.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/6341 ?

**Comment by hosseinsalemi** [comment]
Yes.
