### ISSUE TITLE
How to validate entity's proprty with enum type

### ISSUE THREAD

**Issue by alebedev80** [api-platform/core#5984]
There is an entity with property `$language`:

```
private Language $language = Language::ES;
```

On post request data with language from enum list (e.g. `es`) all is ok. But if value out of list response error (e.g. `00`):

```
{
    "title": "An error occurred",
    "detail": "The data must belong to a backed enumeration of type App\\Core\\Language",
    "status": 400,
    "type": "/errors/400"
}
```

Choice and custom validator useless because they execute AFTER deserialization where that error appears. So i need proper 422 error response. What and how to fix?

**Comment by bertrandseurot** [comment]
You can use a less stryctly typed input, and validate it before hydrating your real object in a custom processor. Would be great if Api platform could natively deal with it !

**Comment by bertrandseurot** [comment]
$language is a parameter of your object constructor, right ?

**Comment by alebedev80** [comment]
> $language is a parameter of your object constructor, right ?

@bertrandseurot  no. simple doctrine's entity.

**Comment by alebedev80** [comment]
Please help somebody

**Comment by soyuka** [comment]
disable_type_enforcement ?

**Comment by alebedev80** [comment]
@soyuka what's it? i couldn't find documentation about it(
