### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [api-platform/core#6004]
**Description**  

Symfony 7 will be out in the next few days.  Is there a branch of api-platform we can use to test?

**Example**  

composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "^7.0"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-platform/core v3.2.5 -> satisfiable by api-platform/core[v3.2.5].
    - api-platform/core v3.2.5 requires symfony/http-foundation ^6.1 -> found symfony/http-foundation[v6.1.0-BETA1, ..., 6.4.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by soyuka** [comment]
Hi, we're waiting for https://github.com/symfony/symfony/pull/52767 and we're testing this in our CI. Feel free to bump our requirements in a PR :).

**Comment by tacman** [comment]
As I imagine you're already aware, Symfony 7 is now out.  I bumped to only supported versions of (^6.3 || ^7.0) but I'm running into issues testing:

```
  Problem 1
    - phpspec/prophecy-phpunit[v2.0.1, ..., v2.0.2] require phpspec/prophecy ^1.3 -> satisfiable by phpspec/prophecy[v1.3.0, ..., v1.17.0].
    - api-platform/core 3.3.x-dev conflicts with phpspec/prophecy v1.5.0.
    - api-platform/core 3.3.x-dev conflicts with phpspec/prophecy v1.3.1.
    - phpspec/prophecy-phpunit v2.0.0 requires php ^7.3 -> your php version (8.3.0) does not satisfy that requirement.
    - phpspec/prophecy[v1.6.0, ..., v1.10.3] require php ^5.3|^7.0 -> your php version (8.3.0) does not satisfy that requirement.
    - phpspec/prophecy[1.11.0, ..., 1.11.1] require php ^7.2 -> your php version (8.3.0) does not satisfy that requirement.
    - phpspec/prophecy[1.12.0, ..., 1.13.0] require php ^7.2 || ~8.0, <8.1 -> your php version (8.3.0) does not satisfy that requirement.
    - phpspec/prophecy[1.14.0, ..., v1.15.0] require php ^7.2 || ~8.0, <8.2 -> your php version (8.3.0) does not satisfy that requirement.
    - phpspec/prophecy[v1.16.0, ..., v1.17.0] require php ^7.2 || 8.0.* || 8.1.* || 8.2.* -> your php version (8.3.0) does not satisfy that requirement.
    - api-platform/core is present at version 3.3.x-dev and cannot be modified by Composer
    - Root composer.json requires phpspec/prophecy-phpunit ^2.0 -> satisfiable by phpspec/prophecy-phpunit[v2.0.0, v2.0.1, v2.0.2].
```

I'll submit the PR anyway to get this started.
