### ISSUE TITLE
Performance problems when using Symfony 6.4

### ISSUE THREAD

**Issue by gnito-org** [api-platform/core#6020]
**API Platform version(s) affected**: 3.2.7

**Description**  
After changing the `composer.json` file of my Symfony app that uses API Platform to use Symfony 6.4 instead of Symfony 6.3, the Symfony RouterListener takes a very long time to finish execution.

![Screenshot from 6-4](https://github.com/api-platform/core/assets/70450336/941048fd-c629-4bb9-bfa8-a85e8476a46b)

If I revert the `composer.json` changes to use Symfony 6.3, the problem disappears.

![Screenshot from 6-3](https://github.com/api-platform/core/assets/70450336/72a11bb2-41af-4e83-aba0-3bd1cb050eeb)

The only thing that changed in the app is the `composer.json` file.

The app has roughly 440 API routes.

I have already upgraded another app to Symfony 6.4. It does not use API Platform and it does not suffer from the same performance problems.

**Comment by dunglas** [comment]
Hi, thanks for the report! Could you:

- report the problem to Symfony, as it's most likely a regression in SF
- do a profile using Blackfire or any other profiler, to see try to figure out what's happening

Thanks!

**Comment by gnito-org** [comment]
I am not convinced that it is a Symfony problem.

To test, I created a Symfony 6.3 webapp and a Symfony 6.4 webapp, each with a Controller that has 500 routes.

The performance under 6.3 and 6.4 is the same.

Symfony 6.3:
![symfony-6-3-500-routes](https://github.com/api-platform/core/assets/70450336/20389d37-970a-4a8d-a4bf-b9e04a805cd7)

Symfony 6.4:
![symfony-6-4-500-routes](https://github.com/api-platform/core/assets/70450336/4be1f2fa-54a2-44af-9a5b-51683ace1e5f)

The 500 routes in the Controller are numbered copies of the following code:

```php
    #[Route('/routes/001', name: 'app_routes_001')]
    public function route_001(): Response
    {
        return $this->render('routes/index.html.twig', [
            'controller_name' => 'RoutesController',
        ]);
    }
```

**Comment by gnito-org** [comment]
>     * do a profile using Blackfire or any other profiler, to see try to figure out what's happening

Unfortunately I do not have access to Blackfire and in any event would not use a third-party service that can read my proprietary code.

**Comment by dunglas** [comment]
XDebug Profiler is open-source and can do the trick too 😉

**Comment by gnito-org** [comment]
I suspect it may have had something to do with the cache. When I deleted var/cache/*, the issue was resolved.

**Comment by gnito-org** [comment]
Exactly the same thing happened again, this time in two separate applications.

This time around `rm -rf var/cache/*` did not solve the problem.

What did solve the problem was `./bin/console debug:router`. After running that command the `RouterListener` stopped taking very long to execute.

So, it appears that under some mysterious circumstances, the router does not cache the routes when creating the cache and recalculates them on every request.

**Comment by gnito-org** [comment]
Just to close the loop, the actual problem turned out to be a misconfiguration inside `config/packages/cache.yaml`.
