### ISSUE TITLE
Custom controllers with parameters are no longer working, throwing "Invalid identifier value or configuration." error

### ISSUE THREAD

**Issue by sujayjaju** [api-platform/core#6030]
**API Platform version(s) affected**: 3.2.7

**Description**  
Custom controllers with non `id` parameter routes are no longer working in version 3. I have migrated my project from version 2.6 to the latest one. Everything works as expected, but the endpoints having custom routes with parameters are not working now.

![1](https://github.com/api-platform/core/assets/1681240/f713734f-bd36-4760-9c48-d5ae0e6bef40)

![2](https://github.com/api-platform/core/assets/1681240/6fc710d9-11fd-4827-89d3-f9fffca6e784)

![3](https://github.com/api-platform/core/assets/1681240/7eaee863-ce6d-4c64-b278-1c674ec1d33d)

These routes does not have `id` parameters but still it shows in the doc and after execution it throwing "Invalid identifier value or configuration." error. 

**How to reproduce**  

CASE 1: This is not working

       `new GetCollection(
                uriTemplate: '/partners/join_after/{ts}',
                controller: FreshPartners::class,
                openapiContext: [
                    'summary' => 'Retrieves the collection of Partner resources.',
                    'parameters' => [
                        [
                            'name' => 'ts',
                            'description' => 'The timestamp when the partner joined.',
                            'type' => 'integer',
                            'in' => 'path',
                            'required' => true,
                        ]
                    ]
                ],
                normalizationContext: ['groups' => 'partner:list']
            )`

CASE 2: This one is also not working

            `new Post(
                uriTemplate: '/partners/bulk/{active}',
                controller: AddPartners::class,
                openapiContext: [
                    'consumes' => ['application/json'],
                    'summary' => 'Creates Partners.',
                    'parameters' => [
                        [
                            'name' => 'active',
                            'description' => 'The Partner status.',
                            'type' => 'integer',
                            'in' => 'path',
                            'required' => true
                        ]
                    ]
                ],
                openapi: new Model\Operation(
                    summary: 'Creates Partners',
                    description: '',
                    requestBody: new Model\RequestBody(
                        content: new \ArrayObject([
                            'application/json' => [
                                'schema' => [
                                    'type' => 'array',
                                    'items' => [
                                        'type' => 'object',
                                        'properties' => [
                                            'name' => ['type' => 'string'],
                                            'email' => ['type' => 'string'],
                                            'phone' => ['type' => 'string'],
                                            'doj' => ['type' => 'date', 'format' => 'date'],
                                        ]
                                    ]
                                ],
                            ]
                        ])
                    )
                ),
            )`

CASE 3: This one is working (see no parameter in the route):

          `new Post(
                uriTemplate: '/partners/bulk',
                controller: AddPartners::class,
                openapi: new Model\Operation(
                    summary: 'Creates Partners.',
                    description: '',
                    requestBody: new Model\RequestBody(
                        content: new \ArrayObject([
                            'application/json' => [
                                'schema' => [
                                    'type' => 'array',
                                    'items' => [
                                        'type' => 'object',
                                        'properties' => [
                                            'name' => ['type' => 'string'],
                                            'email' => ['type' => 'string'],
                                            'phone' => ['type' => 'string'],
                                            'doj' => ['type' => 'date', 'format' => 'date'],
                                            'active' => ['type' => 'boolean'],
                                        ]
                                    ]
                                ],
                            ]
                        ])
                    )
                ),
            )`

To reproduce these issues I have setup a new sample working [Repository](https://github.com/sujayjaju/sf-api-platform) with the latest Symfony and API Platform version having just a single entity with all three use cases in it.
   
**Additional Context**  

![4](https://github.com/api-platform/core/assets/1681240/27ef8db3-92c9-4f7d-b983-d94f144aab3c)

**Comment by soyuka** [comment]
you need to provide `uriVariables`
