### ISSUE TITLE
[Question] RequestAttributesExtractor internal

### ISSUE THREAD

**Issue by polc** [api-platform/core#605]
Hello

Do you know why `ApiPlatform\Core\Api\RequestAttributesExtractor `is marked as internal ? Is it a problem if I use it in a `kernel.request ` listener ?

**Comment by dunglas** [comment]
I made it internal because it's API is still pretty new and can be changed in the future. You can use it in your own listener, it will work, but the behavior of this class may change in a future version.

**Comment by polc** [comment]
thanks for the information.
