### ISSUE TITLE
SearchFilterInterface::STRATEGY_IPARTIAL is not case-insensitive

### ISSUE THREAD

**Issue by ojooss** [api-platform/core#6052]
**API Platform version(s) affected**: 3.1.*

**Description**  
I changed my filter definition from string 'ipartial' to SearchFilterInterface::STRATEGY_IPARTIAL. 
`#[ApiFilter(filterClass: SearchFilter::class, properties: ['name' => 'ipartial', 'abbreviation' => 'ipartial'])] ` to `#[ApiFilter(filterClass: SearchFilter::class, properties: ['name' => SearchFilterInterface::STRATEGY_IPARTIAL, 'abbreviation' => SearchFilterInterface::STRATEGY_IPARTIAL])]`

After that my case-insensitive tests failed. After some debugging I recognised that the value of ApiPlatform\Doctrine\Common\Filter\SearchFilterInterface::STRATEGY_IPARTIAL is only 'partial' without "I".
Whereas in ApiPlatform\Doctrine\Orm\Filter\SearchFilter::filterProperty:193 there is an explicitly check for the prefix "I".

Same problem for STRATEGY_ISTART, STRATEGY_IEND and STRATEGY_IWORD_START but not for STRATEGY_IEXACT. STRATEGY_IEXACT has the missing "I" and works as expected.

**How to reproduce**  
See https://github.com/api-platform/core/blob/3.2/src/Doctrine/Common/Filter/SearchFilterInterface.php#L42 and https://github.com/api-platform/core/blob/3.2/src/Doctrine/Orm/Filter/SearchFilter.php#L193

**Possible Solution**  
Add missing "I" to value of constants

**Comment by bendavies** [comment]
sorry, i meant to fix this ages ago and forgot
https://github.com/api-platform/core/pull/5850#discussion_r1360629154

**Comment by soyuka** [comment]
https://github.com/api-platform/core/commit/4f1b08cfff1bfff8f43a66e690a671efd7c7a59a
