### ISSUE TITLE
Errors that are supposed to be HTML get rendered as JSON

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#6067]
**API Platform version(s) affected**: 3.2.8 +

**Description**  
Since version 3.2.8 errors that are supposed to be normal Symfony HTML errors are rendered via API-Platforms JSON format.

I noticed it when working on my admin interface (EasyAdminBundle) and suddenly got JSON errors instead of the normal Symfony ones.

**How to reproduce**  
Have a twig template that produces an exception while rendering

**Possible Solution**  
Look at the Accept/Content-Type headers maybe?

**Comment by tacman** [comment]
Thanks for submitted this.  I'm seeing it as well, and it's making debugging a bit harder.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/5963#issuecomment-1862470872

**Comment by KDederichs** [comment]
> [#5963 (comment)](https://github.com/api-platform/core/issues/5963#issuecomment-1862470872)
> 
> If you send a `text/html` accept header you still get json?

I'm opening the page in the browser, so I'd assume it sends a text/HTML header

**Comment by KDederichs** [comment]
Dug into it a bit:

https://github.com/api-platform/core/commit/aac883e9331adac959c097796277e8a6d3e63ef0 that's the commit that broke it, especially the removal of:

```php
        if (
            !((RequestAttributesExtractor::extractAttributes($request)['respond'] ?? $request->attributes->getBoolean('_api_respond', false)) || $request->attributes->getBoolean('_graphql', false))
        ) {
            return;
        }
```

**Comment by soyuka** [comment]
I know but apparently we're supposed to handle symfony routing errors see https://github.com/api-platform/core/issues/5963#issuecomment-1862470872 
I'm going to revert that patch and introduce a configuration for that.

**Comment by KDederichs** [comment]
That makes no sense.
The API Component should handle API component errors and API component errors only....

In what world does it make sense to try and handle errors you're not responsible for?

If it ever did that in the past I'd argue that would have been the bug and now it's fixed.

**Comment by soyuka** [comment]
merry xmax it should be fixed

**Comment by KDederichs** [comment]
Thanks :)

Merry Xmas to you too!

**Comment by andrescevp** [comment]
Hi team, happy new year, is this path going to be in symfony repository?
