### ISSUE TITLE
RangeFilter not working in api-platform/core v3.2.10, Symfony 6.4

### ISSUE THREAD

**Issue by milos-ilic** [api-platform/core#6070]
**API Platform version(s) affected**: v3.2.10

**Description**  
Range filter not working. None of the filter options work, my fields are integers and filtering the results doesn't work. It always returns everything from the base as if the filter didn't exist. 
Tested from swagger documentation and via Postman as well, but the results are the same. It's not working.
I have some additional filters included as well which are working as expected. (SearchFilter)

**How to reproduce**  
Just try to implement Range filter as described in documentation.

**Possible Solution**  
I am not sure if there is some additional config option in order to make filter working

**Comment by norkunas** [comment]
Maybe mixed odm and orm filters?

**Comment by milos-ilic** [comment]
@norkunas  Yes you are right.

Thanks for your response. 

Closing issue since it was my fault.
