### ISSUE TITLE
Hydra jsonld normalized documentation doesn't include 'owl:maxCardinality' anymore of relation properties

### ISSUE THREAD

**Issue by anjeylink** [api-platform/core#6097]
**API Platform version(s) affected**: 3.2.10

**Description**  
When loading hydra documentation using "/api/docs.jsonld" endpoint relation properties that are ManyToOne are missing "owl:maxCardinality". 

**How to reproduce**  
I guess changes done in https://github.com/api-platform/core/pull/5470/files#diff-8f5ec9085af157908acc2558bd7cf8cb8a22f72b595bd6a7508f3b4ddd6f319aL466 caused this problem.

**Comment by J3m5** [comment]
Hello @anjeylink,

Thank you for reporting this issue.
It has been resolved in [this commit](https://github.com/api-platform/core/commit/3689ae5f47e68e77f6938b71e9e355c13623dbdb). 
We will publish a new release shortly.
