### ISSUE TITLE
 GraphQL MongoDB: Nested Collections 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#6107]
https://github.com/api-platform/core/pull/6038 was introduced (@jotwea) but we had mongodb tests disabled. I've skipped the test for now but it'd be nice to check what's going on: 

https://github.com/api-platform/core/blob/main/features/graphql/query.feature#L71 

Note that to run mongodb tests use the docker command + instructions from https://github.com/api-platform/core/blob/main/CONTRIBUTING.md#behat

**Comment by jotwea** [comment]
I want to help reproducing and fixing this issue. Unfortunatelly I have problems running `phpunit` and `behat` tests with the latest main branch. I got this error:

`Declaration of Doctrine\Bundle\MongoDBBundle\Form\DoctrineMongoDBTypeGuesser::guessType(string $class, string $property) must be compatible with Symfony\Component\Form\FormTypeGuesserInterface::guessType(string $class, string $property): ?Symfony\Component\Form\Gues
s\TypeGuess in ...`.

I am using Windows with WSL. I have no idea how to solve/workaround this. Any hints are welcome.

**Comment by jotwea** [comment]
I meanwhile solved my issue localy and was able to create a PR that fixes the issues with mongodb
