### ISSUE TITLE
Identifing a resource

### ISSUE THREAD

**Issue by polc** [api-platform/core#612]
Hello,

I'm wondering how to add a user to a resource without knowing the user ID but using the username.  For example: `"user": "/users?username=polc"` instead of  `"user": "/users/1"` with an error `"user doesn't exist"` if the user doesn't exist.

**Comment by Simperfit** [comment]
Hello polc, 

You can do this by adding an event listener on the user entity : 
Then you will have to get the request, use the repository and find the users or throw if not found.

If you want more insight into this, I can send you an exemple.

**Comment by teohhanhui** [comment]
@polc You should not do that, even if you could. It's against the principle of JSON-LD.

**Comment by teohhanhui** [comment]
You should instead send another request to get the user: `GET /users?username=polc`

**Comment by Simperfit** [comment]
@teohhanhui even if he want to assign directly that users ?

Is doing this on embedded relation is also against JSON-LD ?

**Comment by teohhanhui** [comment]
`"user": "/users?username=polc"` is just wrong. You're supposed to use the `@id` (IRI).

It's the same reason why we don't support using the bare integer id either...

**Comment by teohhanhui** [comment]
`"user": "/users/polc"` would be correct if `/users/polc` is the `@id`. In other words, using the username as id.

**Comment by polc** [comment]
`"user": "/users/polc"` is way better but I don't want to use the username as `@id` because the user can change his username. I also don't want to do another request to get the user, because mobile client sometimes have limited connection. 

Like @Simperfit right now I'm using a listener to populate the user property but I fell bad doing this.

One solution may be to add a secondary IRI based on username. Is this OK from a JSON-LD perspective?

**Comment by soyuka** [comment]
I'm using a data provider for those items that have to be fetched by using something different then the ID. You could also fetch the resource with both id and username with the logic in the data provider.

**Comment by polc** [comment]
@soyuka  this is a great idea !

**Comment by teohhanhui** [comment]
Of course you could do such things, but should you? :smile:

**Comment by soyuka** [comment]
Sometimes yes but if you can avoid it you should indeed.
Le mar. 12 juil. 2016 à 13:21, Teoh Han Hui <notifications@github.com> a
écrit :

**Comment by dunglas** [comment]
Can we close this issue?

**Comment by soyuka** [comment]
I think so

**Comment by polc** [comment]
@soyuka answer works great but @teohhanhui seem to dislike this solution. Maybe someone have a better idea for this use case ? (everyone have is own solution so it seem it's a very recurrent use case).

**Comment by theofidry** [comment]
@polc not really, as @teohhanhui it is not really RESTful and defeat the purpose of IRI. But if it suits your specific use case, you're free to use this solution, it is simply just not something we would recommend :)
