### ISSUE TITLE
SearchFilter with multiple strategies

### ISSUE THREAD

**Issue by jahsen** [api-platform/core#6122]
**Description**  
Can you add the possibility to have a search filter by string with multiple strategies. 
.. or a way to add a second search filter on the same field with a custom name and different strategy.

**Example**  
We can have `start` and `exact` strategies both at the same time, so different frontend modules can make use of different functionalities.
Maybe pass an array of strategies? 
`#[ApiFilter(SearchFilter::class, properties: ['name' => ['exact','start']])]` 
If I want to search by exact match I can pass `name` key in the filter and if i want autocomplete pass `name_start`.

**Comment by soyuka** [comment]
Search please.
