### ISSUE TITLE
Swagger 2.0 api documentation doesn't support custom operations.

### ISSUE THREAD

**Issue by samvdb** [api-platform/core#614]
How to reproduce:

```php
/**
 * @ApiResource(
 *     iri="https://schema.org/Foo",
 *     itemOperations={
 *          "bar": {"route_name": "api_foo_bar", "method": "GET"},
 *          "get": {"method": "GET"}
 *     }
 *     )
 */
```

Expected result:

2 operations in the swagger output, currently only the GET route is outputted.

Problem:
\ApiPlatform\Core\Swagger\ApiDocumentationBuilder::getSwaggerOperation

IMO the code before the switch statement is wrong.

**Comment by Simperfit** [comment]
You are right, I will be working on this. Thank you for reporting this @samvdb

**Comment by samvdb** [comment]
Do you have a branch for this? If i find the time i might contribute!

**Comment by Simperfit** [comment]
@samvdb I remember now why it is like that. Like you said swagger does not support custom operation [withouth path](http://swagger.io/specification/#pathItemObject).
But we will have to support custom operation with path
