### ISSUE TITLE
Security protect access to RESOURCEs not to OPERATIONs

### ISSUE THREAD

**Issue by d0niek** [api-platform/core#6142]
**API Platform version(s) affected**: 3.2.13

**Description**  
Security system works only on **resource** not on **operation** level. For example `ROLE_WORKER` doesn't have access to the `PUT /workers/{id}` **operation** (even to him self) but `ROLE_MANAGER` has and only to workers (**resources**) from his team.

Now when `ROLE_WORKER` will calls `PUT /workers/1` (s)he'll got `401` response (it's Ok!) but under the hood **custom provider**/**doctrine extensions** will run too. They shouldn't, worker doesn't have access to that operation.

The only way to deny access to the operation is `access_control` section in **config/packages/security.yaml** file.

**How to reproduce**  
- install the newest version of api-platform (https://github.com/api-platform/api-platform/releases/tag/v3.2.13),
- create new **custom provider**/**doctrine extension**  (can be empty) and setup it for **Greeting** resource,
- put `die(__CLASS__)` in **provider**/**extension**,
- setup in **Greeting** resource `security: "is_granted('ROLE_USER')"`,
- call any action (not `POST`) to `/greetings[/1]`,
- you will got class name in response,
- setup in `access_control` - `- { path: ^/greetings, roles: ROLE_USER }`,
- call any action (not `POST`) to `/greetings[/1]`,
- you will got `401`.

**Possible Solution**  
Update security documentation introduction "You can not apply access control expressions on operation level. Use `access_control` in **config/packages/security.yaml** file instead".

Or add new property in `ApiResource`/operations `operation_security` which will protect operation access and `security` property will protect resource access as it does now.

**Additional Context**  
Other issuses address the same problem:

https://github.com/api-platform/core/issues/4098
https://github.com/api-platform/core/issues/4075
https://github.com/api-platform/core/issues/4436

**Comment by soyuka** [comment]
Hi, yes we call the provider as the `security` expression language does have an `object` value. You can prevent that by handling the security yourself in that provider (decorate the Doctrine provider) and throw the `AccessDenied` before calling our data provider for example.

**Comment by d0niek** [comment]
I understood a concept with an `object` in security expression language but with this you're checking an access to the resource not to the operation. As I mentioned `ROLE_WORKER` doesn't have access to the operation `PUT /worker/{id}`, doesn't matter if (s)he asking for him self or for other workers.

Of course I can throw `AccessDenide` in providers or setup entry in `security.access_control` to check a role and after that check an `object` in `ApiResource::security`. It's working but now I have two places to keep my security up to date.

It would be nice to have security layer for operation and for resource in one place, ApiResource.

**Comment by nxtpge** [comment]
Hello @soyuka, I support @d0niek concern about this behavior.

Here is another use case to contribute to the discussion:

```
GIVEN an API using JWT authentication,

WHEN I request an `ApiResource` without a JWT

AND the operation `provider` needs the related ˋUser` to retrieve data from an external source,

THEN I receive an "500 Internal Server Error" instead of an "403 Forbidden" response.
```

For me, the suggested solution represents a bad developer experience as we have to denied access in each provider facing this problem instead of just letting Symfony do its job and then adding functionalities if necessary.

Are you sure there is no better way?

**Comment by soyuka** [comment]
Not sure about the 500 can I have a stack trace? If there's a security configuration on Symfony you should never reach this anyway as it should be catched by the firewall.
