### ISSUE TITLE
Unit tests using assertMatchesJsonSchema fail for ManyToOne properties

### ISSUE THREAD

**Issue by devzenfr** [api-platform/core#6146]
**API Platform version(s) affected**: 3.2.13

**Description**  

Since #6098 has been merged, my Unit Tests including `assertMatchesResourceCollectionJsonSchema` or `assertMatchesResourceItemJsonSchema` fail for ManyToOne properties. 

The error message is `Object value found, but a string or a null is required`. 

**How to reproduce**  

I have a BlogArticle Entity that contains a blogCategory property. This category is serialized into the json answer for Get and GetCollection operations. 

```php
#[ORM\ManyToOne(targetEntity: BlogCategory::class, inversedBy: 'blogArticles')]
#[ORM\JoinColumn(nullable: true)]
#[Groups([
    'blog_article:read',
    'blog_article:read:get_collection',
])]
private ?BlogCategory $blogCategory;
```

I test my GetCollection api calls with the following method:

```php
public function testGetCollection(): void
{
    static::createClient()->request('GET', '/blog_articles');

    self::assertResponseIsSuccessful();
    $this->assertJsonContains([
        '@type' => 'hydra:Collection',
        'hydra:totalItems' => 11,
    ]);

    $this->assertMatchesResourceCollectionJsonSchema(BlogArticle::class);
}
```

**Possible Solution**  

Inside `ApiTestAssertionsTrait`, I noticed these changes for methods `assertMatchesResourceCollectionJsonSchema`and `assertMatchesResourceItemJsonSchema` =>

```php
$schema = $schemaFactory->buildSchema($resourceClass, $format, Schema::TYPE_OUTPUT, $operation, null, $serializationContext);
```

became

```php
$schema = $schemaFactory->buildSchema($resourceClass, $format, Schema::TYPE_OUTPUT, $operation, null, ($serializationContext ?? []) + [BackwardCompatibleSchemaFactory::SCHEMA_DRAFT4_VERSION => true]);
```

If I change it back to the previous version, my tests are working again but I get new errors instead =>

```
quantity: Use of exclusiveMinimum requires presence of minimum  
```

For this property of the `Recipe` entity

```php
#[ORM\Column(type: 'integer', options: ['default' => 1])]
#[Positive]
#[Groups([
    'recipe:read',
])]
private int $quantity = 1;
```

All my tests were green when using API Platform 3.1. 

Thanks for your help!

**Comment by kevin-macquer-omnilog** [comment]
@jvengeon @devzenfr can you test with the change in this PR? I had the same problem and this fixed the issues with my tests.
https://github.com/api-platform/core/pull/6157

**Comment by devzenfr** [comment]
> @jvengeon @devzenfr can you test with the change in this PR? I had the same problem and this fixed the issues with my tests. #6157

This works fine on my side too! I hope this can be merged.

**Comment by jvengeon** [comment]
Thanks, this works for my first problem `logo: Object value found, but a string or a null is required`
The second problem is always here : `quoteValidityPeriod: Use of exclusiveMinimum requires presence of minimum`

**Comment by kevin-macquer-omnilog** [comment]
@jvengeon Hum this is very strange since my change are supposed to go back to 3.12 behaviours.
Can you confirm that your test works on 3.12 but doesn't work for 3.13?

**Comment by jvengeon** [comment]
The problem `Use of exclusiveMinimum requires presence of minimum` exists since 3.2.7

**Comment by louismariegaborit** [comment]
We tried and it's ok.

**Comment by devzenfr** [comment]
All my tests are green again, seems great! Thanks @kevin-macquer-omnilog and @soyuka 🙏 

I can close this.
