### ISSUE TITLE
[Bug] Abstract doctrine inheritance collection properties

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#615]
Is there a reason why collection properties on an abstract entity doesn't have it's child entities properties? I also tried to manage those with groups but they are not taken into consideration. 
For example [this test](https://github.com/api-platform/core/blob/master/features/crud_abstract.feature#L45) will not have the `instance` property, even though it is fetched from doctrine because it's a `SINGLE_TABLE` inheritance.

On an item, the behavior is different. See [this test](https://github.com/api-platform/core/blob/master/features/crud_abstract.feature#L29) where child properties are normalized well.

**Comment by soyuka** [comment]
I think that it has to do with the fact that the serializer only sees properties belonging to the parent (ie the abstract class).

**Comment by soyuka** [comment]
I narrowed down the issue to the NameCollectionFactories not having inherited properties.

@dunglas, I just saw that the `AnnotationPropertyNameCollectionFactory` is not used anymore. Also, you wrote that `PropertyInfoPropertyNameCollectionFactory` is not a decorator in the class comments. I agree that annotation for properties is a bit too much work to configure but getting the reflection class methods seems a good idea. Can you explain your choice? 

On one hand, `AnnotationPropertyNameCollectionFactory` had a reflection which would be able to get the parent properties (if I'm not mistaken `public object ReflectionClass::getParentClass ( void )`).
On the other hand, as this issue is doctrine-related I was going to add a `DoctrineOrmPropertyNameCollectionFactory` that checks for inheritance on the class metadata. On second thoughts I need your opinion (ping @teohhanhui) because properties inheritance should also be effective on non-doctrine resources, don't you think?
So, if that's the case, should the inherited properties be added in the `PropertyInfoPropertyNameCollectionFactory`? If yes, any ideas on how this could work seamlessly? 

Thanks!

**Comment by dunglas** [comment]
Currently the system doesn't support inheritance at all. It would be nice to be able to support it but indeed it should be done in a generic way (it should work for all loaders).

**Comment by soyuka** [comment]
Ok, my thoughts were correct.

> What do you think about adding a new ParentPropertyFactory class that will scan all parents classes, load their properties metadata and add them to the current Value Object if it doesn't already exist?
That way it would add inheritance support for all existing loaders.

Indeed this would be the solution. My concern still stands, is it possible to add a new NameCollection factory even if the `PropertyInfoPropertyNameCollectionFactory` is not a decorator? I think that the `ParentPropertyFactory` would have to act on the NameCollection rather then on the properties (they are yet unknown).

Still, the use case here is that the Parent class is the `ressourceClass`, and we still need a Doctrine factory to check if an inheritance is used. Then we could add the child properties (at least in a SINGLE_TABLE inheritance case. I don't think that php can find child instances from the parent one.

**Comment by soyuka** [comment]
I opened another issue about the php inheritance as it's not really the same use case. I'll first fix this one ;).

**Comment by dunglas** [comment]
Indeed we have to do something specific in the Doctrine loader.

The AnnotationPropertyNameCollectionFactory class is not used yet (it is here only for people using the component directly, without the Symfony integration). The PropertyInfoPropertyNameCollectionFactory class is preferred when available: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/metadata.xml

**Comment by soyuka** [comment]
thanks

**Comment by teohhanhui** [comment]
So the issue is actually Symfony PropertyInfo not returning inherited properties? If so, shouldn't we fix it there then?

**Comment by teohhanhui** [comment]
Definitely agree that it is not Doctrine-specific and should not be resolved as such.

**Comment by soyuka** [comment]
In fact we have inherited properties (or [this](https://github.com/api-platform/core/issues/664#issuecomment-236929027) won't be true). Here, the issue is that we call the parent class and want the child entity properties (see SINGLE_TABLE inheritance).
