### ISSUE TITLE
Validation on DELETE action

### ISSUE THREAD

**Issue by i-shippi** [api-platform/core#6182]
**API Platform version(s) affected**: 3.2.14

**Description**  
When trying to validate a DELETE action, the attribute property validate is ignored, even though it is set to true.

**How to reproduce**  
[This](https://api-platform.com/docs/guides/delete-operation-with-validation/) is an example from your docs

**Possible Solution**  
Change ApiPlatform\Symfony\EventListener\ValidateListener line 56 to not always return if the method is DELETE

**Additional Context**  
This is a nice feature and it is a shame that it is not working. I found another [issue](https://github.com/api-platform/core/issues/5647) which reported this bug and apparently the answer was that it will be fixed with version 3.2, which is not true.

**Comment by soyuka** [comment]
Hi when not using listeners this works. Set api_platform.event_listeners_backward_compatibility_layer to false

**Comment by i-shippi** [comment]
@soyuka Thanks for the answer. The solution suggested seems to work, but is there something that is also affected by this and I need to be aware of?

**Comment by soyuka** [comment]
If you use listeners yes, note that on 3.3 you can use listeners and this also got fixed, we could not break the behavior in 3.2...
