### ISSUE TITLE
ValidatorPropertyMetadataFactory is marking NotBlank constraints as required disregarding its arguments

### ISSUE THREAD

**Issue by ostrolucky** [api-platform/core#6183]
**API Platform version(s) affected**: 3.2.14

**Description**  
Picture instead of words
![image](https://github.com/api-platform/core/assets/496233/e638cb17-ed79-4eae-bd86-755e43129e5f)

**Possible Solution**  
Disregard the constraint if it allows null

**Comment by soyuka** [comment]
interesting use case, could you patch this on 3.2?

**Comment by ostrolucky** [comment]
will do
