### ISSUE TITLE
 Installation from new Symfony project fails because of webonyx/graphql-php

### ISSUE THREAD

**Issue by kstefanini** [api-platform/core#6191]
**API Platform version(s) affected**: 3.2.15

**Description**  
Installing a new project with graphql leads to an error

**How to reproduce**  
```
symfony new api-bug --webapp && cd api-bug
composer config extra.symfony.allow-contrib true
echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" > .env.local
composer require api
echo "title,string,80,yes," | sed "s/,/\n/g"  | bin/console -a make:entity Book
echo "book,ManyToOne,Book,no,yes,reviews,yes," | sed "s/,/\n/g"  | bin/console -a make:entity Review
bin/console doctrine:schema:update --force --complete
bin/console cache:clear -vvv
composer require webonyx/graphql-php
```

<details>
  <summary>Error log</summary>
<code>
  In FileLoader.php line 178:

  [Symfony\Component\Config\Exception\LoaderLoadException]
  Warning: Undefined property: Doctrine\ORM\Mapping\ManyToOneAssociationMapping::$mappedBy in . (which is being imported from "/home/user/projects/api-bug/config/routes/api_platform.yaml"). Make sure there is a loader supporting
  the "api_platform" type.
</code>
</details>

**Comment by soyuka** [comment]
interesting, you have no `mappedBy` I guess it fails because of a newer version of doctrine, we need to handle `$doctrineMetadata->isAssociationInverseSide($property)` inside `DoctrineOrmLinkFactory` (use `-vvv` on the cache:clear)

**Comment by rendyep** [comment]
I'm also affected. It was fine in Symfony 7.0.3 (Doctrine ORM 2.17.3). Using the new Symfony 7.0.4 (Doctrine ORM 3.0.1), I got the same error.

API Platform version(s) affected: 3.2.15

```
Warning: Undefined property: Doctrine\ORM\Mapping\ManyToOneAssociationMapping::$mappedBy in . (which is being imported from "/path/to/symfony/project/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.
```

**Comment by rendyep** [comment]
After removing the webonyx/graphql-php, another error got caught.

```
ApiPlatform\Metadata\Property\Factory\CachedPropertyNameCollectionFactory::create(): Argument #1 ($resourceClass) must be of type string, null given, called in /path/to/symfony/project/vendor/api-platform/core/src/Metadata/Resource/Factory/LinkFactory.php on line 77
```

**Comment by soyuka** [comment]
https://github.com/doctrine/orm/blob/3.0.x/src/Mapping/ClassMetadata.php#L2463C7-L2475C1 now throws @rendyep I'm on it please open a new issue once I fixed this if there's another unrelated issue.

**Comment by soyuka** [comment]
actually these may just be solved by https://github.com/api-platform/core/pull/6156

**Comment by soyuka** [comment]
we need https://github.com/api-platform/core/pull/6156
