### ISSUE TITLE
max_depth does not work 

### ISSUE THREAD

**Issue by NicolasSegond** [api-platform/core#6195]
Hello I have a problem with my mappers, I try to display the entity information but the response always contains a URI, yet I set max_depth to 1 why it does not work with entities? 

`<?php

namespace App\Mapper;

use App\ApiResource\FilesAPI;
use App\ApiResource\UserAPI;
use App\Entity\Files;
use App\Entity\User;
use Symfonycasts\MicroMapper\AsMapper;
use Symfonycasts\MicroMapper\MapperInterface;
use Symfonycasts\MicroMapper\MicroMapperInterface;
#[AsMapper(from: Files::class, to: FilesAPI::class)]
class FilesEntityToApiMapper implements MapperInterface
{
    public function __construct(
        private MicroMapperInterface $microMapper,
    )
    {
    }

    public function load(object $from, string $toClass, array $context): object
    {
        $entity = $from;
        assert($entity instanceof Files);

        $dto = new FilesAPI();
        $dto->id = $entity->getId();

        return $dto;
    }

    public function populate(object $from, object $to, array $context): object
    {
        $entity = $from;
        assert($entity instanceof Files);

        $dto = $to;
        assert($dto instanceof FilesAPI);

        $dto->id = $entity->getId();
        $dto->name = $entity->getName();
        $dto->description = $entity->getDescription();
        $dto->owner = $this->microMapper->map($entity->getOwner(), UserAPI::class, [
            MicroMapperInterface::MAX_DEPTH => 1,
        ]);
        $dto->date_creation = $entity->getDateCreation();
        $dto->poids = $entity->getPoids();
        $dto->chemin = $entity->getChemin();
        $dto->statut = $entity->getStatut();
        $dto->shared_with = $entity->getSharedWith();
        return $dto;
    }
}`

**Comment by Aerendir** [comment]
> the response always contains a URI

Do you mean it ONLY contains a URI? In this case, you have to use serialization groups.

So, in your case, for example, you can set the serialization group `file_read` and use it on both `FilesAPI` and `UserAPI`, on properties you want to be in the response.

**Comment by NicolasSegond** [comment]
Oh, okay, I didn't know that even with a DTO class you also had to set up serialization groups. Are there any other options, for example, if you have a lot of entities in your project? If not, I'll fill it in everywhere, thanks for your help.

**Comment by Aerendir** [comment]
Sorry, I'm not sure I understood: do you mean for all properties?

If this is what you are asking, maybe using (de)serialization contexts may help:

https://github.com/api-platform/core/blob/bfd759b627990926fddd11c6737af8f993af7bb5/src/Metadata/ApiResource.php#L320-L321

```php
#[API\ApiResource(
    normalizationContext: [
        AbstractNormalizer::GROUPS                       => [self::GROUP_NOR_READ],
        AbstractObjectNormalizer::ENABLE_MAX_DEPTH       => true,
    ],
    denormalizationContext: [
        AbstractNormalizer::GROUPS                 => [self::GROUP_DENOR_WRITE],
        AbstractObjectNormalizer::ENABLE_MAX_DEPTH => true,
    ],
)]
class YourEntity
```
