### ISSUE TITLE
Doctrine ORM 3 support

### ISSUE THREAD

**Issue by stevan-tosic** [api-platform/core#6199]
**API Platform version(s) affected**: 3.1.16

**Description**  
The doctrine/orm package version v3.* introduces breaking changes.

**How to reproduce**  
1. Update the doctrine/orm package to version 3.*.
2. Attempt to execute a GET method on a resource that has a OneToMany relation.

**Possible Solution**  
Set an upper version limit for the doctrine/orm package in composer.lock to v2.18.

**Additional Context**  
This issue affects all versions which contain the require block "doctrine/orm": "^2.14" in composer.lock.

**Comment by norkunas** [comment]
This misses doctrine/dbal v4 support :)

**Comment by soyuka** [comment]
feel free to open a pr!
