### ISSUE TITLE
Exists filter not working

### ISSUE THREAD

**Issue by PaulCombal** [api-platform/core#6203]
**API Platform version(s) affected**: 3.2.15

**Description**  

The exists filter never has any effect.

I'm using it on a ManyToOne relation where the attribute can be nullable.

**How to reproduce**  

```php
// Filter imported from the Orm filters
#[ApiFilter(ExistsFilter::class, properties: ['productCategory'])]
class Product
{
...

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\Column(nullable: true)] // I tried with and without this line
    private ?ProductCategory $productCategory = null;
```

`GET http://{{host}}/api/products?exists[productCategory]=true`

The above request always returns the full set of results regardless of the filter.

I had a quick look inside the API Platform package:

Depending whether I set the ORM\Column nullable, `ExistsFilter->isNullableField` returns `false` either from the nested ifs or the end of function.

I have never managed to make `isNullableField` return `true`.

**Possible Solution**  

You are doing an amazing job, would it be that the documentation does not insist enough on a detail I missed?

**Additional Context**  

Symfony 7.0.4

**Comment by kstefanini** [comment]
Hi, with `#[ORM\ManyToOne]` I use `#[ORM\JoinColumn]` _(which has nullable: true by default)_ instead of `#[ORM\Column]`.

Did you check the generated Doctrine query via the profiler?

**Comment by PaulCombal** [comment]
Hello, same result using \JoinColumn unfortunately..

The generated query: `SELECT p0_.id AS id_0, ..., p0_.product_category_id AS product_category_id_4 FROM product p0_ ORDER BY p0_.id ASC LIMIT 30`

And the above was with \JoinColumn(nullable: true). No filter applied here.. 

I forgot to mention I'm using php 8.3.3 if that's any help

**Comment by soyuka** [comment]
Thanks for your report, I bet it's because of the recent updates to this file due to doctrine/orm update, what `doctrine/orm` version do you use? Is there something you see in this patch that could affect your behavior? I'll try that asap.

https://github.com/api-platform/core/commit/d8e2d0c5e9b48c15d60a734086b0102b6ecf95c8#diff-6da6088f44d1853d914cc91c26ea81a9f3e5128f99b0d6b0d9781abfed1c2483

**Comment by soyuka** [comment]
nevermind, works perfectly fine

**Comment by PaulCombal** [comment]
If I understand the logic correctly, this doesn't test for the issue above:

```
  Scenario: Create a Product and filter on its categories
    When I add "Content-Type" header equal to "application/ld+json"
    And I send a "POST" request to "/issue6203_products" with body:
    """
    {}
    """
    Then the response status code should be 201
    And the response should be in JSON
    Then I send a "GET" request to "/issue6203_products?exists[productCategory]=0"
    And print last JSON response
```

Since the filter does not filter at all, and you request an entity with "exists[productCategory]=0" which would not be filtered anyway.

What would be interesting would be to use "exists[productCategory]=1" and check whether we have an empty result set, not the opposite.

I haven't checked out myself, correct me if I'm wrong @soyuka

**Comment by soyuka** [comment]
I checked both feel free to clone my branch and run it yourself or provide a reproducer please.

**Comment by PaulCombal** [comment]
Nevermind, this works again after a composer update. Probably this was a version issue like you pointed out earlier. Thank you for the support!
