### ISSUE TITLE
Warning: Undefined array key "resource_class" - when declaring the type of an array property in a DTO.

### ISSUE THREAD

**Issue by grichards** [api-platform/core#6211]
**API Platform version(s) affected**: 3.2.12

**Description**  

This yields the warning:
```
<?php

namespace App\DTO;

class UpdateCartDto
{
    /** @var CartItemDto[] */
    public array $items;
}
```
Removing:
```
/** @var CartItemDto[] */
```
will eliminate the warning, but then also I do not get accurate documentation inside Swagger.

My UpdateCart POST operation looks like:
```
#[Post(
    uriTemplate: '/cart/update-items',
    routePrefix: '/storefront',
    stateless: false,
    openapiContext: [
        'summary' => 'Frontend update cart item(s).',
        'tags' => ['Storefront - Cart']
    ],
    normalizationContext: ['groups' => ['storefront.cart']],
    security: "is_granted('PUBLIC_ACCESS')",
    input: UpdateCartDto::class,
    validate: false,
    processor: UpdateCartProcessor::class
)]
```

**Comment by soyuka** [comment]
Could not reproduce, please provide a stack trace, content type or a reproducer.

**Comment by grichards** [comment]
Hello @soyuka . Thank you for responding. Here is the stack trace:

{
  "@id": "/api/admin/errors/500",
  "@type": "hydra:Error",
  "title": "An error occurred",
  "detail": "Warning: Undefined array key \"resource_class\"",
  "status": 500,
  "type": "/errors/500",
  "trace": [
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 320,
      "function": "getAllowedAttributes",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 241,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 153,
      "function": "denormalize",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/src/Serializer/EmptyValueDenormalizer.php",
      "line": 42,
      "function": "denormalize",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Debug/TraceableNormalizer.php",
      "line": 84,
      "function": "denormalize",
      "class": "App\\Serializer\\EmptyValueDenormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Serializer.php",
      "line": 247,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 875,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 810,
      "function": "createAndValidateAttributeValue",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 478,
      "function": "createAttributeValue",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 395,
      "function": "setAttributeValue",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 241,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 153,
      "function": "denormalize",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/src/Serializer/EmptyValueDenormalizer.php",
      "line": 42,
      "function": "denormalize",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Debug/TraceableNormalizer.php",
      "line": 84,
      "function": "denormalize",
      "class": "App\\Serializer\\EmptyValueDenormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Serializer.php",
      "line": 247,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 208,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 153,
      "function": "denormalize",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/src/Serializer/EmptyValueDenormalizer.php",
      "line": 42,
      "function": "denormalize",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Debug/TraceableNormalizer.php",
      "line": 84,
      "function": "denormalize",
      "class": "App\\Serializer\\EmptyValueDenormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Serializer.php",
      "line": 247,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableNormalizer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Serializer.php",
      "line": 152,
      "function": "denormalize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/serializer/Debug/TraceableSerializer.php",
      "line": 62,
      "function": "deserialize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/State/Provider/DeserializeProvider.php",
      "line": 88,
      "function": "deserialize",
      "class": "Symfony\\Component\\Serializer\\Debug\\TraceableSerializer",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Symfony/Security/State/AccessCheckerProvider.php",
      "line": 53,
      "function": "provide",
      "class": "ApiPlatform\\State\\Provider\\DeserializeProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Symfony/Validator/State/QueryParameterValidateProvider.php",
      "line": 38,
      "function": "provide",
      "class": "ApiPlatform\\Symfony\\Security\\State\\AccessCheckerProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Symfony/Validator/State/ValidateProvider.php",
      "line": 32,
      "function": "provide",
      "class": "ApiPlatform\\Symfony\\Validator\\State\\QueryParameterValidateProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Symfony/Security/State/AccessCheckerProvider.php",
      "line": 53,
      "function": "provide",
      "class": "ApiPlatform\\Symfony\\Validator\\State\\ValidateProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/State/Provider/ContentNegotiationProvider.php",
      "line": 56,
      "function": "provide",
      "class": "ApiPlatform\\Symfony\\Security\\State\\AccessCheckerProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/api-platform/core/src/Symfony/Controller/MainController.php",
      "line": 82,
      "function": "provide",
      "class": "ApiPlatform\\State\\Provider\\ContentNegotiationProvider",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 181,
      "function": "__invoke",
      "class": "ApiPlatform\\Symfony\\Controller\\MainController",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 76,
      "function": "handleRaw",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/http-kernel/Kernel.php",
      "line": 197,
      "function": "handle",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php",
      "line": 35,
      "function": "handle",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/vendor/autoload_runtime.php",
      "line": 29,
      "function": "run",
      "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
      "type": "->"
    },
    {
      "file": "/Users/grichards/www/brake-performance/api/public/index.php",
      "line": 5,
      "function": "require_once"
    }
  ],
  "hydra:title": "An error occurred",
  "hydra:description": "Warning: Undefined array key \"resource_class\""
}

**Comment by soyuka** [comment]
Thanks, not much help though we tried to reproduce (live on twitch on Friday) but could not

**Comment by soyuka** [comment]
Would love a reproducer, reopening please add a use case on an api-platform template

**Comment by ZZromanZZ** [comment]
@soyuka Thank you, here is reproducer MR: https://github.com/ZZromanZZ/api-platform/pull/1/files

Just create Greeting (with id 1)  and request that with `GET /greetings/1`

**Comment by soyuka** [comment]
nice thanks! Note that for my patch you need `composer req phpdocumentor/reflection-docblock`

**Comment by ZZromanZZ** [comment]
Patch works, thank you very much
