### ISSUE TITLE
Multiple error routes although format is not configured

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#6214]
![20240313_11h43m16s_grim](https://github.com/api-platform/core/assets/1321971/1bc614e5-f5aa-45bd-a361-4e0e74b7dc0d)

**Comment by GwendolenLynch** [comment]
It is from the operations defined in the `#[ErrorResource]` annotations in:
- `ApiPlatform\Symfony\Validator\Exception\ValidationException` 
  - #5848 
  - #5841
- `ApiPlatform\State\ApiResource\Error` (formerly `ApiPlatform\ApiResource\Error`) 
  - #5433
  - #5974

Investigating an issue from my current set of PRs and I was about to open an issue, but you've already beat me to it :tada:

**Comment by soyuka** [comment]
I noted that this isn't quite done yet.

**Comment by soyuka** [comment]
nvm checked
