### ISSUE TITLE
Fetch EAGER ManyToOne nullable relation cannot be nulled during PUT or PATCH operation

### ISSUE THREAD

**Issue by ambroisemaupate** [api-platform/core#6218]
**API Platform version(s) affected**: 3.2.16

**Description**  

Entities with `ORM\ManyToOne(fetch: 'EAGER')` nullable relation can be setted during a `PUT` or `PATCH` with an IRI, but cannot be nulled.

If I remove `fetch: 'EAGER'`, I can set relation to `null`.

**How to reproduce**  

### With EAGER fetch

```php
#[ORM\ManyToOne(targetEntity: File::class, fetch: 'EAGER')]
#[ORM\JoinColumn(name:'image_id', nullable: true, onDelete: 'SET NULL')]
#[Groups(['block:read', 'block:write', 'webPage:single:read'])]
#[ApiProperty(description: 'File IRI reference', example: '/api/files/1ee8859e-d2fd-6bda-ae37-d9341637fbc1')]
private ?File $image = null;
```

![image](https://github.com/api-platform/core/assets/380026/705045ef-9b65-4263-84bb-49c84475e223)

When I inspect request in Symfony Profiler: previous_data contains an `image` but `data` too !

![image](https://github.com/api-platform/core/assets/380026/58742d2f-c7e7-493c-a7ec-9734cbac93af)

### Without EAGER fetch

```php
#[ORM\ManyToOne(targetEntity: File::class)]
#[ORM\JoinColumn(name: 'image_id', nullable: true, onDelete: 'SET NULL')]
#[Groups(['content:read', 'content:write'])]
#[ApiProperty(description: 'File IRI reference', example: '/api/files/1ee8859e-d2fd-6bda-ae37-d9341637fbc1')]
private ?File $image = null;
```

![image](https://github.com/api-platform/core/assets/380026/c6d300d9-6441-43ad-94c9-d760417e89da)

When I inspect request in Symfony Profiler: previous_data contains an `image` then `data` has `null` image

![image](https://github.com/api-platform/core/assets/380026/89141579-ae35-498f-be95-7fd41e24db2f)

**Comment by soyuka** [comment]
can you provide a reproducer ?

**Comment by ambroisemaupate** [comment]
> can you provide a reproducer ?

I'll make that. Male or female ? For the reproducer :rofl:
