### ISSUE TITLE
EventPriorities::POST_DESERIALIZE when implemented with "RequestEvent" affects @UniqueEntity Annotation, and the custom Exception class 

### ISSUE THREAD

**Issue by l0r3nc335** [api-platform/core#6219]
**API Platform version(s) affected**: ^2.7

**Description**  
EventPriorities::POST_DESERIALIZE when implemented with "RequestEvent" affects @UniqueEntity Annotation, and the custom Exception class 

Scenario 1:  Sending an existing username and email will allow the insert to the database. Expected: should not allow insert of duplicate/existing username and email.

Scenario 2: Sending empty array {} as body of the request returns the default error message from "@Assert\NotBlank" instead of using the custom EmptyBodyException.

Scenario 3: Sending nothing as body in the request produce ""hydra:description": "The \"Content-Type\" header must exist."," INSTEAD of using the custom EmptyBodyException

See codes below

**How to reproduce**

**User.php**
`
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 `
 
 #========================

**EmptyBodySubscriber.php**

`class EmptyBodySubscriber implements EventSubscriberInterface
{

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::REQUEST => ['handleEmptyBody', EventPriorities::POST_DESERIALIZE]
        ];
    }

    /**
     * @throws EmptyBodyException
     */
    public function handleEmptyBody(RequestEvent $event): void
    {
        $method = $event->getRequest()->getMethod();

        if(!in_array($method, [Request::METHOD_POST, Request::METHOD_PUT])){
            return;
        }

        $data = $event->getRequest()->get('data');

        if(null === $data){
            throw new EmptyBodyException;
        }
    }
}`
    
    
    `class EmptyBodyException extends \Exception
    {
              public function __construct(string $message = "", int $code = 0, ?Throwable $previous = null)
              {
                  parent::__construct("Request Body Can not be empty.", $code, $previous);
              }
    }
`

**api_platform.yaml**

    exception_to_status:
              App\Exception\EmptyBodyException: 400

**Possible Solution**  

**Additional Context**  

I first setup the Unique Entity and the NotBlank in the User.php, without any custom Exception it does produce the expected behavior which has default error messages when providing duplicate email and username as well as providing no request body.

However when I tried to add custom Exception named "EmptyBodyException", the unique entity was destroyed and not functioning as expected.

**Comment by soyuka** [comment]
Hello, 2.7 is not supported anymore, please update to API Platform 3. Feel free to open a new issue if this is still an issue.
