### ISSUE TITLE
Critical error release 2.7.17

### ISSUE THREAD

**Issue by Niiph** [api-platform/core#6226]
**API Platform version(s) affected**: 2.7.17

**Description**  
After yesterday's release I cant start php container:
```sh
In DebugClassLoader.php line 350:
php         | !!                                                                                 
php         | !!    The autoloader expected class "ApiPlatform\Core\Bridge\Symfony\Bundle\Depen  
php         | !!    dencyInjection\ApiPlatformExtension" to be defined in file "/srv/sylius/ven  
php         | !!    dor/composer/../api-platform/core/src/Core/Bridge/Symfony/Bundle/Dependency  
php         | !!    Injection/ApiPlatformExtension.php". The file was found but the class was n  
php         | !!    ot in it, the class name or namespace probably has a typo.  
```

this is how said file looks like:
```php
<?php

/*
 */

declare(strict_types=1);

namespace ApiPlatform\Core\Bridge\Symfony\Bundle\DependencyInjection;

class_exists(\ApiPlatform\Symfony\Bundle\DependencyInjection\ApiPlatformExtension::class);

if (false) {
    final class ApiPlatformExtension extends \ApiPlatform\Symfony\Bundle\DependencyInjection\ApiPlatformExtension
    {
    }
}
```

Also, tests for this release failed, with the same exception:
https://github.com/api-platform/core/actions/runs/8298539077/job/22712127997

**Comment by farram** [comment]
I have the same problem since this morning ...

**Comment by algorun77** [comment]
Hello, same issue for my coworker and I since this morning, after a `composer update` upgrading `api-platform/core` from 2.7.16 to 2.7.17.
We temporarily resolved it by restoring the version to it's previous version:
```bash
symfony composer require api-platform/core 2.7.16
```

**Comment by toar86** [comment]
the same here, after updating get this error

**Comment by CaptainFry** [comment]
We have the same problem

**Comment by michaljusiega** [comment]
Same issue. Looks like https://github.com/api-platform/core/pull/6227 will fix this.

**Comment by Niiph** [comment]
@michaljusiega it won't, there's the same exception in tests in this PR https://github.com/api-platform/core/actions/runs/8314885732/job/22752593386?pr=6227

**Comment by soyuka** [comment]
Really thought I would help by merging https://github.com/api-platform/core/pull/6217 and as our 2.7 version is not maintained I didn't take a closer look at the CI as it's red for more then a year now. I reverted everything and won't be merging anything to the 2.7 branch anymore, please upgrade to 3.x and sorry for the inconvenience.
