### ISSUE TITLE
Exception serialization fails if JSON:HAL is the only configured format

### ISSUE THREAD

**Issue by GwendolenLynch** [api-platform/core#6241]
**API Platform version(s) affected**: 3.2

**Description**  

When and exception is thrown the following is the first line of the HTML returned when the request is for `application/hal+json`

```html
<!-- Serialization for the format &quot;jsonld&quot; is not supported. (500 Internal Server Error) -->
```

**How to reproduce**  

1. Enable only `jsonhal` as a format:
```yaml
# config/packages/api_platform.yaml
api_platform:
    # ...
    formats:
        jsonhal:  ['application/hal+json']
```
2. Add a `throw new \Exception()` somewhere in the request chain, e.g. a state provider
3. `curl -X 'GET' 'https://127.0.0.1:8000/my_resources' -H 'accept: application/hal+json'`

The key point where this goes wrong is: https://github.com/api-platform/core/blob/874e4d6707ecdd48b27ed91b0b66ea5e33691e7c/src/Metadata/Util/ContentNegotiationTrait.php#L123-L124

… which is called from \ApiPlatform\Symfony\EventListener\ErrorListener` 
https://github.com/api-platform/core/blob/874e4d6707ecdd48b27ed91b0b66ea5e33691e7c/src/Symfony/EventListener/ErrorListener.php#L71

… which has the origin of the defaults passed into the listener coming from configuration:
https://github.com/api-platform/core/blob/874e4d6707ecdd48b27ed91b0b66ea5e33691e7c/src/Symfony/Bundle/DependencyInjection/Configuration.php#L172-L176

**Possible Solution**  
The easiest solution would appear to be to reorder the default array in `Configuration`
```php
        $this->addFormatSection($rootNode, 'error_formats', [
            'json' => ['mime_types' => ['application/problem+json', 'application/json']],
            'jsonproblem' => ['mime_types' => ['application/problem+json']],
            'jsonld' => ['mime_types' => ['application/ld+json']],
        ]);
```

**Comment by soyuka** [comment]
this got patched
