### ISSUE TITLE
Performance problem with Api Platform

### ISSUE THREAD

**Issue by NicolasSegond** [api-platform/core#6242]
Hello, I have a problem with API platform my requests take 1 or 2s to run on bad connections and 800 to 900 ms on a fiber connection, I use api platform as on symfonycast with a DTO part, I do not know where this can come from so I have no "attachments" to bring. Perhaps you'll be able to help me sort this out?

**Comment by dunglas** [comment]
Can you try to use a profiler such as Blackfire to see what's going on?

**Comment by NicolasSegond** [comment]
pas vraiment comment le faire

**Comment by NicolasSegond** [comment]
How do I use blackfire? I've never used it, so I don't really know how.

**Comment by NicolasSegond** [comment]
I made this test with the symfony profiler. I don't know if it can be useful for you. 

![Capture d’écran 2024-03-23 140431](https://github.com/api-platform/core/assets/105415895/634e3516-1fff-46cb-b26d-254f7599e109)

**Comment by soyuka** [comment]
Doctrine does lots of querying we need more data but presumably this is not optimized.

**Comment by soyuka** [comment]
check your doctrine queries ? this doesn't look like a bug, we can provide support at https://les-tilleuls.coop/en#contact
