### ISSUE TITLE
Interfaced object relations do not resolve JsonLd inheriting resource types

### ISSUE THREAD

**Issue by ambroisemaupate** [api-platform/core#6251]
**API Platform version(s) affected**: 3.2.18

**Description**  

If a DTO expose a property with a API Resource but this property is typed using an Interface to allow polymorphism: Api Platform won't be able to resolve the final resource' `types` and will serialize the short className in `@type` for JsonLd format.

```php
interface CommonResource {

}

#[ApiResource( types: [ 'https://schema.org/Thing' ] )]
class MyResource implements CommonResource {

}

class MyDto {
    #[ApiProperty]
    public ?CommonResource $resource = null;
}


$dto = (new MyDto())->resource = new MyResource();
```

Actual output:
```json
{
    "@type": "MyDto",
    "resource": {
        "@type": "MyResource"
    }
}
```

Expected output:
```json
{
    "@type": "MyDto",
    "resource": {
        "@type": "https://schema.org/Thing"
    }
}
```

**Possible cause : \ApiPlatform\JsonLd\Serializer\ItemNormalizer::normalize (line 84)**

I think that's because in `\ApiPlatform\JsonLd\Serializer\ItemNormalizer::normalize`, `$context['resource_class']` is populated with the interface `CommonResource` which is not an `ApiResource`.

```php
$resourceClass = $this->getObjectClass($object); // Here : MyResource
$previousResourceClass = $context['resource_class'] ?? null; // Here: CommonResource
```

So this condition cannot be true (line 84), and resource is normalized as an **anonymous** resource:

```php
if($isResourceClass = $this->resourceClassResolver->isResourceClass($resourceClass) && (null === $previousResourceClass || $this->resourceClassResolver->isResourceClass($previousResourceClass)))
{
    //...
}
```

**Possible solution:**

We should test if `$previousResourceClass` is an interface or abstract class and `$resourceClass` is an instanceof 
`$previousResourceClass` then build context against `$resourceClass`, not `$previousResourceClass`.

**Comment by soyuka** [comment]
use `#[ApiProperty(iris: ['https://schema.org/Thing'])]`

**Comment by ambroisemaupate** [comment]
> use `#[ApiProperty(iris: ['https://schema.org/Thing'])]`

That's not possible as we want polymorphism here.

```php
public ?CommonResource $resource = null;
``` 

will accept any `CommonResource` sub-class, and each sub-class may have a different `iris` configuration. 


```php
interface CommonResource {

}

#[ApiResource( types: [ 'https://schema.org/Thing' ] )]
class MyResource implements CommonResource {

}
#[ApiResource( types: [ 'https://schema.org/WebPage' ] )]
class MySecondResource implements CommonResource {

}

class MyDto {
    #[ApiProperty]
    public ?CommonResource $resource = null;
}

// https://schema.org/Thing
$dto = (new MyDto())->resource = new MyResource();
// https://schema.org/WebPage
$dto2 = (new MyDto())->resource = new MySecondResource();
```

**Comment by soyuka** [comment]
I see I'd just declare everything as resources with the `NotExposed` metadata attribute. I'm :+1: for the suggested change, would you be able to make the patch?
