### ISSUE TITLE
Allow use of environment variables in elasticsearch indexes within yaml stateOptions

### ISSUE THREAD

**Issue by tobyski-tdsultra** [api-platform/core#6253]
**Description**  
api-platform/core v3.1.14

When using the (now deprecated) mapping approach for elasticsearch resources I could leverage environment variables like so:

App\Model\X:
    index: "%env(APP_ENV)%_%env(APP_NAMESPACE)%_index_data_*"

This resolved correctly when being used by the Collection/ItemProvider (so that the correct elastic index is hit based on env and namespace)

I cannot seem to get the same to work when using this within stateOptions.

          stateOptions:
            elasticsearchOptions:
                index: "%env(APP_ENV)%_%env(APP_NAMESPACE)%_index_data_*"

This just goes through raw with no variable replacement.

Is there anything I can do to make this work?  Or maybe I am taking the wrong approach?

**Comment by soyuka** [comment]
use a metadata factory for dynamic things like this preferably
