### ISSUE TITLE
Enum priority change in symfony-dev

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#6264]
https://github.com/symfony/symfony/commit/c87e4a1aed7a8ce619497ee15d9b936503cf66d9 makes our sf-dev test fail it needs investigation

**Comment by GwendolenLynch** [comment]
`features/graphql/mutation.feature` fails as this now returns a string https://github.com/api-platform/core/blob/53a45d7d19e3298b653631531fe6f59ccdb04fbb/src/GraphQl/State/Processor/NormalizeProcessor.php#L88

… and throws an exception a little bit lower https://github.com/api-platform/core/blob/53a45d7d19e3298b653631531fe6f59ccdb04fbb/src/GraphQl/State/Processor/NormalizeProcessor.php#L105-L107

The origin is where `api_platform.graphql.normalizer.item` sets the `serializer.normalizer` tag priority
https://github.com/api-platform/core/blob/53a45d7d19e3298b653631531fe6f59ccdb04fbb/src/Symfony/Bundle/Resources/config/graphql.xml#L225-L226

For reference, the `BackedEnumNormalizer` has changed its priority from `-915` to `-880`. I couldn't find an easy single substitution that didn't break other tests, so shall leave this to the experts.

**Comment by soyuka** [comment]
nice thanks for debugging this, I guess that we need to update our priorities from the Symfony docs it's not a bc-break to change a service priority :/ (although it does break code).
