### ISSUE TITLE
JSONApi Normalizer: Empty has many relation should return empty array

### ISSUE THREAD

**Issue by RozbehSharahi** [api-platform/core#6265]
Hello,

the item normalizer of api-platform for jsonapi does not comply the specification. If we have an empty has-many relations it should not skip the relationship. Instead it should return an empty array:

```
relation: {
  data: []
}   
```
otherwise the consumer can not distinguish if the relations was not included or if there is simply no relations assigned. At least it is not that simple...

I didn't look too deeply into it yet, but i assume the safest fix would be checking if we have a many-to-may or 1:n relation and in such case return an empty array if value is empty.

https://github.com/api-platform/core/blob/e895b69a04cb52eb6eb030bcc51a1e143dd357cb/src/JsonApi/Serializer/ItemNormalizer.php#L406

**Comment by soyuka** [comment]
Nice, PR welcome!
