### ISSUE TITLE
ApiPlatform\Metadata\Exception\InvalidArgumentException : Unable to generate an IRI for the item of type "ApiPlatform\State\ApiResource\Error"

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#6269]
**API Platform version(s) affected**: 3.2.19

**Description**  
I have some tests that test some errors.

The exceptions, however, cannot be converted due the error in object.

The problem originates from the fact the route `api_errors` is not registered:

> Unable to generate a URL for the named route "api_errors" as such route does not exist.

![318193166-f3fb2918-0684-4365-92ca-954efc1af7c2-2](https://github.com/api-platform/core/assets/1968622/3f8fe375-ceb8-4142-8ec3-28039d57fce2)

https://github.com/api-platform/core/blob/d4d2cd422eb18555c1fb7feab01269b9f6de4fc3/src/Symfony/Routing/IriConverter.php#L188-L195

**How to reproduce**  
...

**Possible Solution**  
...

**Additional Context**  
I did nothing more than changing the ApiPltaform version: maybe there is a new configuration to register the built-in routes?

**Comment by soyuka** [comment]
Hi, mhh there should be a route declared see https://github.com/api-platform/core/pull/6263/files#diff-e3802e202f0fb1b9b1f0011e3a7b284875323fd6112fe7d900c9ec1d37c51b2fR17

**Comment by LoicBoursin** [comment]
I can confirm that I am getting the same error in my project after upgrading to 3.2.19

The error occurs when calling an API with a not found entity (ex. `/api/demo/random_uuid` which was expected to return a 404 previously)

**Comment by soyuka** [comment]
can you check why this route is not loaded @LoicBoursin ?

**Comment by mbrodala** [comment]
We see the same error but the `api_errors` route exists:

```
$ bin/console debug:router api_errors
+--------------+---------------------------------------------------------+
| Property     | Value                                                   |
+--------------+---------------------------------------------------------+
| Route Name   | api_errors                                              |
| Path         | /api/errors/{status}                                    |
| Path Regex   | {^/api/errors(?:/(?P<status>\d+))?$}sDu                 |
| Host         | ANY                                                     |
| Host Regex   |                                                         |
| Scheme       | ANY                                                     |
| Method       | ANY                                                     |
| Requirements | status: \d+                                             |
| Class        | Symfony\Component\Routing\Route                         |
| Defaults     | _controller: api_platform.action.not_exposed()          |
|              | status: 500                                             |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler |
|              | utf8: true                                              |
+--------------+---------------------------------------------------------+
```

Interestingly this does not exist in the `test` environment:

```
$ bin/console --env test debug:router api_errors

                                          
  The route "api_errors" does not exist.  
                                          

debug:router [--show-controllers] [--show-aliases] [--format FORMAT] [--raw] [--] [<name>]
```

**Comment by soyuka** [comment]
Sorry for the trouble thanks everyone for the details
