### ISSUE TITLE
Clerification/Bug regarding default ApiFilters

### ISSUE THREAD

**Issue by ili101** [api-platform/core#6290]
**API Platform version(s) affected**: Tested on 3.2.20 and older.

**Description**  
If the filter is not submitted to the API and a default filter exists, the default filter is ignored.

**How to reproduce**  
Add filter to the example Greeting class
```php
#[ApiResource(mercure: true)]
#[ORM\Entity]
#[ApiFilter(OrderFilter::class, properties: ['name' => 'DESC'])]
class Greeting
...
```
Create some greeting like "string1", "string2" and "string3".
Getting the greetings will ignore the default filter:
![image](https://github.com/api-platform/core/assets/6960531/82fad4f1-15e3-445e-9fc4-a29ba58264d5)

Setting "Send empty value" will apply the default filter:
![image](https://github.com/api-platform/core/assets/6960531/b23c96bc-acc7-4fa0-891f-98ced4e65251)

What is the intended behavior?
I assumed the opposite of how it behaves now, I assumed:
1. Client not sending any filters - The default filter should apply.
2. Client send `order[name]=` - The client want to remove the default filter. Or as it's now use the default filter, but in that case "Send empty value" will have no effect.

Is the correct behavior the intended behavior?

**Possible Solution**  

**Additional Context**

**Comment by GwendolenLynch** [comment]
Everything looks correct, albeit potentially confusing.

The [docs](https://api-platform.com/docs/core/default-order) say 
> By default, items in the collection are ordered in ascending (ASC) order by their resource identifier(s). If you want to customize this order, you must add an order attribute on your ApiResource annotation

Which is what you are seeing in your first screenshot. In that query your're calling `/greetings` so no filter is applied, just the default ordering for resources, i.e `id` => `ASC`.

In the second image it is sending the empty `order` filter parameter — `/greetings?order[name]=` — invoking the filter that then uses the default you configured for that property (`name`) in your filter:
```php
#[ApiFilter(OrderFilter::class, properties: ['name' => 'DESC'])]
```
