### ISSUE TITLE
Example documentation is ignored for Enum resources

### ISSUE THREAD

**Issue by gnito-org** [api-platform/core#6317]
**API Platform version(s) affected**: 3.2.20

**Description**  

When using a Backed Enum class as an API resource, any `example` value provided in the `ApiProperty` attribute is ignored and does not appear in the OpenAPI documentation.

This is true for `example: 'foo'` and `openapiContext: ['example' => 'foo']`.

On API resources that are Doctrine entities, the supplied example values appear in the OpenAPI documentation.

**How to reproduce**  

https://github.com/gnito-org/problem-replicator-api-platform-enum-example

**Possible Solution**  

**Additional Context**

**Comment by GwendolenLynch** [comment]
I think this is where the breakage occurs. 
https://github.com/api-platform/core/blob/97c8ae26eb5eb4cfaafadcc36b7d497b9fa2cb9e/src/Metadata/Property/Factory/AttributePropertyMetadataFactory.php#L62-L71

Removing the `return`, and handling `$reflectionEnum` below works (caveat emptor).
