### ISSUE TITLE
[meta][DX] Embedded resources support

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#634]
We should be able to use embedded objects as first-class anonymous resources.
## 

Related:

Handling of embedded objects / resources:
- ~~#166~~
- ~~#181~~
- #528
- ~~#593~~
- #618
- #885

Nested URL:
- ~~#186~~
- ~~#432~~

More advanced use cases:
- ~~#334~~

**Comment by dunglas** [comment]
Possible in v2 using custom operations and documented: https://github.com/api-platform/docs/blob/master/core/operations.md

**Comment by dunglas** [comment]
Nevermind my previous comment.

**Comment by jhonatanTeixeira** [comment]
I am having problems with Embedabble, wich is not being deserialized.
Embedabble is common practice for those wich are trying to use the Value Objects into their domain.

I don't know if im doing somethig wrong... but im trying to solve it with a port deserialize listener

**Comment by jhonatanTeixeira** [comment]
i've found my mistake... i didn't place a setter for my embedabbles and started them on my constructors.

That caused the serializer to not find a setter and not populate a not null property

**Comment by patie** [comment]
any news?

**Comment by soyuka** [comment]
Closing, embedded are supported the last thing that needs fixing is in the documentation (https://github.com/api-platform/core/issues/618)!
