### ISSUE TITLE
[3.3] Changelog

### ISSUE THREAD

**Issue by aurimasrimkusnfq** [api-platform/core#6346]
Changelog of the latest 3.3 version is showing a diff between https://github.com/api-platform/core/compare/v3.3.0-beta.2...v3.3.0
Wouldn't it make more sense to show the diff with the last minor version [v3.2.22](https://github.com/api-platform/core/releases/tag/v3.2.22)?

![image](https://github.com/api-platform/core/assets/54065117/1c177c5e-8c85-4de4-a35c-0e376d0b08aa)

**Comment by soyuka** [comment]
Mhh why not actually I think it'd make sense, I'll do that tomorrow with a 3.3.1 release!

**Comment by soyuka** [comment]
https://github.com/api-platform/core/releases/tag/v3.3.0 done, condensed the notes although the blog post at https://soyuka.me/api-platform-3.3/ has more details, hope that this is good enough!
