### ISSUE TITLE
Swagger and custom POST operation

### ISSUE THREAD

**Issue by napalm33700** [api-platform/core#635]
` /**
 * @ApiResource(
 *     collectionOperations={
 *         "create"={
 *            "path"="/customers/create",
 *            "method"="POST",
 *            "controller"="AppBundle:Customer:create",
 *            "hydra_context"={"@type"="hydra:Operation", "hydra:title"="Création de client", "returns"="jsonld"}
 *         }
 *     },`

this creates two operations in doc (POST /customers and POST customer/create)

**Comment by Simperfit** [comment]
Hi @napalm33700, 

Thanks for testing api-platform V2.

We will be looking into this.

**Comment by Simperfit** [comment]
@napalm33700 I updated the PR could you test again ?

Thank you.

**Comment by napalm33700** [comment]
Sorry if I have to create a new issue for this but,  do you know how I can change default parameters list for custom operation in Swagger ?
