### ISSUE TITLE
Separate DTOs for input and output with different id fields fail

### ISSUE THREAD

**Issue by xdrew** [api-platform/core#6355]
**API Platform version(s) affected**: ^3.3

**Description**  
I have a dto and api resource, updating order product count and returning the order dto:
```
#[ApiResource(
    shortName: 'OrderProduct',
    operations: [
        new Get(),
        new Patch(
            uriTemplate: '/order_products/{id}/count',
            controller: UpdateOrderProductCountController::class,
            exceptionToStatus: [\Exception::class => 400],
            class: OrderDto::class,
            input: OrderProductCountDto::class,
            output: OrderDto::class,
            read: false,
            write: false,
            name: 'order_product_update_count',
        ),
    ],
    order: ['position' => 'ASC'],
    provider: EntityToDtoStateProvider::class,
    stateOptions: new Options(entityClass: OrderProduct::class),
)]
class OrderProductCountDto
{
    #[ApiProperty(writable: false, identifier: true)]
    public ?int $id = null;

    public ?int $count = null;
}
```
```
class OrderDto
{
    #[ApiProperty(identifier: false)]
    public ?int $id = null;

    #[ApiProperty(identifier: true)]
    public ?Uuid $uuid = null;
//...
}
```
```
#[AsController]
class UpdateOrderProductCountController extends AbstractController
{
    public function __invoke(OrderProductCountDto $data, Request $request): OrderDto
    {
       
        $dto = new OrderDto();
        $dto->id = 1;
        // ...
        return $dto;
    }
```
Calling this controller leads to 400 Invalid identifier value or configuration error.

**How to reproduce**  
Use dtos with different id fields for input/output with custom controller as in my example

**Possible Solution**  
Place this check https://github.com/api-platform/core/commit/cc9f6a518222598d20556fc1ec62b7c4be52bf52#diff-6723d777fc70f000cb59deecf75e9a948f114ffd9ae63e284ca5821735b7cea3R105 
before this one https://github.com/api-platform/core/commit/cc9f6a518222598d20556fc1ec62b7c4be52bf52#diff-6723d777fc70f000cb59deecf75e9a948f114ffd9ae63e284ca5821735b7cea3R77

**Additional Context**  
The problem occures when you have different dtos for input/output and they also have different ids for example id and uuid. Platform then uses operation class for fetching getOperationUriVariables instead of resource_class. Maybe it's ok, and I'm doing this in a wrong way.

**Comment by soyuka** [comment]
Can you try my patch at https://github.com/api-platform/core/pull/6357 ?

**Comment by xdrew** [comment]
Yep. It fixes my issue. Thanks!

**Comment by soyuka** [comment]
will be released soon thanks for the report
