### ISSUE TITLE
cannot perform GraphQL sub-selections on non-doctrine resource collections

### ISSUE THREAD

**Issue by igoooor** [api-platform/core#6365]
I somehow can not join the slack workspace, so I'm asking here. Also it might be a bug but I'm not sure, so please feel free to let me know where is the better place for this topic.

I am trying to perform a sub-selection query on an array/collection resource, but my resources are not doctrine entities.
If I add all doctrine annotations (just for trying), then the sub-selection works without any other changes.

Here is the code example which fails:
```php
#[ApiResource(
    paginationEnabled: false,
    provider: UserProvider::class,
    shortName: 'user',
)]
#[QueryCollection(
    args: [
        'id' => ['type' => 'ID'],
        'what' => ['type' => 'String'],
    ],
    provider: UserCollectionProvider::class,
)]
final class UserResult
{
    /**
     * @param User[] $users
     */
    public function __construct(
        /**
         * @var User[]
         */
        public array $users,
        public Meta $meta,
        ....
    )
    {
    }
}
```

And the User class:
```php
#[ApiResource(
    paginationEnabled: false,
    shortName: 'userresource',
)]
final class User
{
    public function __construct(
        public int $id,
        public string $uuid,
        public string $companyName,
        ....
    ) {
    }
}
```

Here is an example of query:
```graphql
query searchQuery($what: String) {
  users(what: $what) {
    meta {
      totalCount
    }
    users {
      uuid
    }
  }
}
```
And variables:
```graphql
{
  "what": "hello"
}
```

There is no issue with the meta sub-selection, but with the users it gives the following error:
`"Field \"users\" of type \"Iterable!\" must not have a sub selection.",`

As I said above, if I add all ORM annotation to convert these simple classes into entities, then the sub-selection works out of the box, with the same code and same query.
Am I missing something to tell graphql/apiplatform that `$users` is an array of the `User::class` resource?

Thank you already for your support

**Comment by soyuka** [comment]
Can I see the UserProvider? Not sure if/how graphql works without doctrine, maybe that you need a custom resolver.

**Comment by igoooor** [comment]
@soyuka Currently the UserProvider is quite empty, just returning a mock object.
However, the request does not even reach the provider and fails even before.

**Comment by soyuka** [comment]
I see, inspect your schema, IIRC the type is computed at https://github.com/api-platform/core/blob/e867d07f59b82d5f1bdca69e096ddf452dd7efc8/src/GraphQl/Type/FieldsBuilder.php#L215-L228 not sure why `User[]` can't be found, is it a resource?

**Comment by igoooor** [comment]
Yes it has the `ApiResource` attribute, you can find the `User` class definition in my initial post

**Comment by igoooor** [comment]
With your comment pointing out the `FieldsBuilder` class, I think I was able to resolve that issue by adding the following attribute to my `$users` property:
```php
#[ApiProperty(
            builtinTypes: [new Type(
                builtinType: Type::BUILTIN_TYPE_ARRAY,
                collection: true,
                collectionKeyType: new Type(builtinType: Type::BUILTIN_TYPE_INT),
                collectionValueType: new Type(builtinType: Type::BUILTIN_TYPE_OBJECT, class: User::class),
            )],
        )]
```

Is that a valid use of `ApiProperty`?

**Comment by soyuka** [comment]
you shouldn't need this, try installing this:

```
composer require phpstan/phpdoc-parser
```

**Comment by igoooor** [comment]
Ok so without using the `ApiResource` (basically the `UserResult` as described on the initial message) and by installing `composer require phpstan/phpdoc-parser` that still ends up with the same message `"Field \"users\" of type \"Iterable!\" must not have a sub selection.",`
I tried different syntax (no property promotion on the constructor) but same error message.
So far the only way to make it work is with adding `ApiResource` to my array properties.

composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/core": "^3.2",
        "doctrine/dbal": "^3",
        "doctrine/doctrine-bundle": "^2.12",
        "doctrine/doctrine-migrations-bundle": "^3.3",
        "doctrine/orm": "^3.1",
        "phpstan/phpdoc-parser": "^1.29",
        "symfony/asset": "7.0.*",
        "symfony/console": "*",
        "symfony/dotenv": "*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "*",
        "symfony/runtime": "*",
        "symfony/twig-bundle": "7.0.*",
        "symfony/yaml": "*",
        "webonyx/graphql-php": "^15.11"
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "7.0.*"
        }
    },
    "require-dev": {
        "phpmd/phpmd": "^2.15.0",
        "phpstan/phpstan": "^1.10.67",
        "phpstan/phpstan-doctrine": "^1.3",
        "phpstan/phpstan-phpunit": "^1.3",
        "phpstan/phpstan-symfony": "^1.3",
        "phpunit/phpunit": "^10.2",
        "squizlabs/php_codesniffer": "*",
        "symfony/maker-bundle": "^1.58"
    }
}

```

**Comment by soyuka** [comment]
I assume you cleared the cache to reload the metadata after adding the phpdoc-parser?

**Comment by igoooor** [comment]
`rm -rf var/cache` yes

**Comment by soyuka** [comment]
could not reproduce
