### ISSUE TITLE
`property` field of FilterInterface::getDescription - string only?

### ISSUE THREAD

**Issue by ostrolucky** [api-platform/core#6369]
Another thing I notice when upgrading to 3.3.x is that we were using multi values for `property` in our filters, like so

```php
public function getDescription(string $resourceClass): array
{
    return [
        self::PROPERTY => [
            'property' => ['firstName', 'lastName', 'middleName'],
            'type' => SearchFilterInterface::STRATEGY_PARTIAL,
            'required' => false,
            'schema' => ['type' => 'string'],
        ],
    ];
}
```

I thought this was a valid solution to document which properties is filter using in query for filtering. But since 3.3.x this seems explicitly disallowed (which I'm not saying shouldn't have been done) and we get errors in SA like so
```
ERROR: InvalidReturnStatement - src/Bridge/ApiPlatform/Doctrine/Orm/Filter/UserNameFilter.php:42:16 - The inferred type 'array{name: array{property: list{'firstName', 'lastName', 'middleName'}, required: false, schema: array{type: 'string'}, type: 'partial'}}' does not match the declared return type 'array<string, array{description?: string, is_collection?: bool, openapi?: ApiPlatform\OpenApi\Model\Parameter|array<string, mixed>, property?: string, required?: bool, schema?: array<string, mixed>, strategy?: string, swagger?: array<string, mixed>, type?: string}>' for App\Bridge\ApiPlatform\Doctrine\Orm\Filter\UserNameFilter::getDescription (see https://psalm.dev/128)
        return [
            self::NAME => [
                'property' => ['firstName', 'lastName', 'middleName'],
                'type' => SearchFilterInterface::STRATEGY_PARTIAL,
                'required' => false,
                'schema' => ['type' => 'string'],
            ],
        ];
```

Hence I was forced to remove the line completely. 

Since `getDescription` is not really documented, I am reaching out to you here to check if I'm misunderstanding what is `property` field for. At the same time, this is also a request to add documentation for it and to consider extending type for this field from `string` to `string|list<string>`

**Comment by soyuka** [comment]
Interesting, yeah it's a shame and I tried to move the `getDescription` forward by documenting it in the last release. 

`property` is mainly used for https://www.hydra-cg.com/spec/latest/core/#templated-links and in the specification it is typed `string`, and I recently added the php doc:

https://github.com/api-platform/core/blob/e867d07f59b82d5f1bdca69e096ddf452dd7efc8/src/Metadata/FilterInterface.php#L56

In another change we now consider this as a string: https://github.com/api-platform/core/blob/e867d07f59b82d5f1bdca69e096ddf452dd7efc8/src/Hydra/Serializer/CollectionFiltersNormalizer.php#L178

Actually your filter should return an array per property supported: 

```
$description = ['type' => SearchFilterInterface::STRATEGY_PARTIAL,
                'required' => false,
                'schema' => ['type' => 'string']];
return ['firstName' => ['property' => 'firstName'] + $description, 'lastName' => ['property' => 'lastName'] + $description, 'middleName' => ['property' => 'middleName'] + $description]; 
```

**Comment by ostrolucky** [comment]
I think I cannot do this, because key should be name of the query parameter, which in my case is `name`. When consumer does `?name=foo`, filter will do `firstName LIKE '%foo%' OR lastName LIKE '%foo%' OR middleName LIKE '%foo%'`, hence I documented `['name' => ['property' => ['firstName', 'lastName', 'middleName']],`. If I split this to 3 filters with different key, this would indicate to consumer that they can do `?firstName=foo`, `?lastName=foo`, `?middleName=foo` instead of `?name=foo`, wouldn't it?

**Comment by soyuka** [comment]
Yes indeed, I think I had a discussion with someone recently about this (probably at https://github.com/api-platform/core/pull/5995 but can't find where). I think that what would be best would be to not set the `property` in your case as it has an impact only on the documentation.

**Comment by ostrolucky** [comment]
Ok then removing it is! Thanks for being reactive. I guess this is something we would have to address to folks making the standard itself?

**Comment by soyuka** [comment]
You mean hydra? Yeah I'm on the mailing list but it's quite cold for now :/.
