### ISSUE TITLE
Cached PropertyMetadata sometimes null

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#637]
> Type error: Return value of ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory::create() must be an instance of ApiPlatform\Core\Metadata\Property\PropertyMetadata, null returned

Could this be a Symfony Cache bug?

**Comment by dunglas** [comment]
It can also be a bug in our loader. If the cache component returns nul

**Comment by teohhanhui** [comment]
@dunglas That should not happen. An error would have been thrown earlier before we could have saved a null value in the cache.

**Comment by dunglas** [comment]
Any update on this one?

**Comment by teohhanhui** [comment]
Closing as I don't think it's an API Platform bug.
