### ISSUE TITLE
Swagger Docs jsonopenapi format return HTML

### ISSUE THREAD

**Issue by fabian-laine** [api-platform/core#6372]
**API Platform version(s) affected**: 3.3.3

**Description**  
Since upgrade from 3.2 to 3.3.3 the jsononpenapi docs url return HTML.

**How to reproduce**  
Just try https://127.0.0.1:8000/api/docs.jsonopenapi in local

**Comment by bendavies** [comment]
@soyuka this is due to [this change](https://github.com/api-platform/core/commit/cc9f6a518222598d20556fc1ec62b7c4be52bf52), which stops `$this->addRequestFormats($request, $formats);` being called on. line 155.

**Comment by soyuka** [comment]
Thanks, working on a fix.

**Comment by bendavies** [comment]
not fixed yet?

**Comment by soyuka** [comment]
thought I merged it

**Comment by bendavies** [comment]
can be closd
