### ISSUE TITLE
Support for JsonProblem (RFC 7807) Extension Member

### ISSUE THREAD

**Issue by gquemener** [api-platform/core#6414]
Hello,

As far as I have seen, the current state of ApiPlatform [limits the schema of the serialized exception to the following properties](https://github.com/api-platform/core/blob/main/src/Problem/Serializer/ErrorNormalizer.php#L48-L61):
- type
- title
- detail
- trace

The [RFC mentions that this schema could contain extra information](https://datatracker.ietf.org/doc/html/rfc7807#section-3) (named "extension members") and gives the example of an "account" field.

Is this supported by ApiPlatform ? (We are still using version 2.7)

Thanks.

**Comment by soyuka** [comment]
In API Platform 3.1/3.2 and forward you can put whatever you want in an error https://api-platform.com/docs/guides/error-resource/

On 2.7 you should create your own normalizer. Also this is not a bug, nor a feature request, use either the Discussions, slack or contact us at contact@les-tilleuls.coop.

**Comment by gquemener** [comment]
Thanks for taking the time answering.

I did not find the mentioned guide while browsing the doc :+1: 

Also, sorry about the noise, I'll go through a different channel next time.
