### ISSUE TITLE
Use only ItemOperations but it's does'nt work

### ISSUE THREAD

**Issue by Garfield-fr** [api-platform/core#647]
Hi,

I would like to use only ItemOperation GET on my ItemInfos object, because the CollectionOperations is not revelent. But, if i make this configuration, the service doesn't show on API Doc and doesn't work. Why ?

```
/**
 * @ApiResource(
 *     collectionOperations={}},
 *     itemOperations={"get"={"method"="GET","path"="/items/info/{id}"}}
 * )
 */
```

Another strange problem is the path. I don't show this in my page API. Only show:
`get /item_infos/{id} `

Thank's for your help

Bertrand

**Comment by Garfield-fr** [comment]
Precision: The service work correctly with this syntax. It's a bug in swagger display.

**Comment by dunglas** [comment]
@Simperfit can you take a look?

**Comment by Simperfit** [comment]
@Garfield-fr Could you please take a look at @Ener-Getick's PR ? #648

**Comment by Garfield-fr** [comment]
@Simperfit Yes, i tested on master branch and it work.

Thank's

**Comment by Simperfit** [comment]
Could you please this @Garfield-fr ?

**Comment by Garfield-fr** [comment]
I have a strange this with this PR:

If i use this syntax (without ORM)
```
/**
 * @ApiResource(
 *     collectionOperations={},
 *     itemOperations={"get"={"method"="GET","path"="/items/info/{id}"}}
 * )
 */
```
i show element(s) on API Doc and it work.

If i use this (with ORM)
```
/**
 * @ApiResource(
 *     collectionOperations ={},
 *     itemOperations={"get"={"method"="GET"}}
 * )
 * @ORM\Entity(readOnly=true)
 * @ORM\Table(name="reserve_item")
 */
```
I don't have this on API Doc and doesn't work.

Thank's

**Comment by Ener-Getick** [comment]
@Garfield-fr this is not related to this pr but to a current limitation of the IriConverter which only works if you have at least one collection operation.
Your first example works because you defined the path manually.

**Comment by Garfield-fr** [comment]
@Ener-Getick it's a bottleneck 📦 

I understand to have a definition of item if you have a collection, but the opposite should be possible.

**Comment by Garfield-fr** [comment]
@Ener-Getick Exactly. I define the path on ItemOperations and it work.

**Comment by soyuka** [comment]
Because it defines an operation ;)

**Comment by Ener-Getick** [comment]
@Garfield-fr see https://github.com/api-platform/core/pull/666
