### ISSUE TITLE
Invalid IRIs in output DTOs

### ISSUE THREAD

**Issue by bpolaszek** [api-platform/core#6475]
### Discussed in https://github.com/api-platform/core/discussions/6473

<div type='discussions-op-text'>

<sup>Originally posted by **bpolaszek** July 17, 2024</sup>
Hello there, 

I just noticed that when using DTO output to create a different representation of the resource, the IRI returned by API-Platform is a _generated_ one (as of API-Platform 3.x), instead of the _original_ one (as of API-Platform 2.x).

## TL; DR:
When requesting `GET /api/books/1`, I get 
```json
{
  "@type": "BookOutput",
  "@id": "/api/.well-known/genid/b10ecd57cce7b0b65b14"
}
``` 
instead of 

```json
{
  "@type": "Book",
  "@id": "/api/books/1"
}
```
</div>

-----

After further investigation,  I think this is a regression from API-Platform 2.x.
Here's a [minimal repository](https://github.com/bpolaszek/api-output) to reproduce the issue: 
- A [`Book`](https://github.com/bpolaszek/api-output/blob/main/src/Entity/Book.php) entity (`type='entity'`)
- A [`BookOutput`](https://github.com/bpolaszek/api-output/blob/main/src/Entity/BookOutput.php) representation (`type='output'`)
- A [`StateProvider`](https://github.com/bpolaszek/api-output/blob/main/src/State/BookProvider.php#L30-L36)
- An [integration test](https://github.com/bpolaszek/api-output/blob/main/tests/StateProviderTest.php) and [its result](https://github.com/bpolaszek/api-output/actions/runs/9988662426/job/27605639750#step:5:10)

The final API consumer should not know anything about `BookOutput`, they should just see a `Book` with a valid IRI.

Thank you,
Ben

**Comment by soyuka** [comment]
This is not a regression if BookOutput is a Book why not return a Book? It should be the other way around: 

- declare your `Get` on `BookOutput(shortName: 'Book')`
- in the `BookOutput::provider` (or use `stateOptions: new Options(entityClass: Book:class)`) fetch your book and map the data

**Comment by bpolaszek** [comment]
Hey @soyuka, thanks for your quick answer.
If I understand correctly, the `APIResource` annotation should be put on top of `BookOutput` instead of `Book`, right?

I just did the change [here](https://github.com/bpolaszek/api-output/pull/1) but here's the result:
- POST to `/books` properly creates a new book in database ✅ 
- Output of `POST` operation returns a serialization of `Book` instead of `BookOutput` :x:
- GET `/books` properly returns a collection of `BookOutput` with correct IRIs ✅ 
- GET `/books/1` returns a serialization of `BookOutput` like the one I expected in return of the `POST` operation.

So far everything works as expected, except the returned output from the `POST / books` operation, which should be the same as doing a `GET / books/1`.

Here's the result of [this test](https://github.com/bpolaszek/api-output/blob/feature/use-state-options/tests/StateProviderTest.php):
```
array:1 [
  "POST /api/books" => array:6 [
    "@context" => array:4 [
      "@vocab" => "http://localhost/api/docs.jsonld#"
      "hydra" => "http://www.w3.org/ns/hydra/core#"
      "name" => "Book/name"
      "type" => "Book/type"
    ]
    "@type" => "Book"
    "@id" => "/api/.well-known/genid/42d1873232123aa23" // <-- Nope
    "id" => 1
    "name" => "PHP for dummies"
    "type" => "entity" // <-- Nope
  ]
]
array:1 [
  "GET /api/books" => array:5 [
    "@context" => "/api/contexts/Book"
    "@id" => "/api/books"
    "@type" => "hydra:Collection"
    "hydra:totalItems" => 1
    "hydra:member" => array:1 [
      0 => array:5 [
        "@id" => "/api/books/1" // <-- Yep
        "@type" => "Book"
        "id" => 1
        "name" => "PHP for dummies"
        "type" => "output" // <-- Yep
      ]
    ]
  ]
]
array:1 [
  "GET /api/books/1" => array:6 [
    "@context" => "/api/contexts/Book"
    "@id" => "/api/books/1" // <-- Yep
    "@type" => "Book"
    "id" => 1
    "name" => "PHP for dummies"
    "type" => "output" // <-- Yep
  ]
]
```

Any ideas?

**Comment by soyuka** [comment]
> Output of POST operation returns a serialization of Book instead of BookOutput ❌

Probably that the WriteProcessor of API Platform is returning a Book not a BookOutput, we can probably add the "auto-mapping" to that but I wish we get to experiment https://github.com/symfony/symfony/pull/51741 which will bring a way more enjoyable developer experience.

**Comment by bpolaszek** [comment]
Yay 🎉 

I managed to make the test suite pass by enhancing processor / provider to handle every case [here](https://github.com/bpolaszek/api-output/pull/1/files).

I also added an input DTO to complicate things even more, and I succeeded [here](https://github.com/bpolaszek/api-output/pull/2/files). 

If you confirm this is the correct way to do, maybe I could suggest a deeper explanation / cookbook in the docs in the near future.

By the way, auto-mapping looks really cool 👍 

Thank you for your help @soyuka!

**Comment by soyuka** [comment]
It's not documented yet as experimental see https://github.com/api-platform/core/pull/5275 for more details ideas.

**Comment by bpolaszek** [comment]
Alright, thank you for your time anyway 🙂
