### ISSUE TITLE
Custom uri variable for DTO doesn't work

### ISSUE THREAD

**Issue by NikDevPHP** [api-platform/core#6524]
**API Platform version(s) affected**: 3.3.11

**Description** 

For 3.2.21 version it worked, what needs to be done to make it work for 3.3.11?

```
#[Get(
    uriTemplate: '/notifications/unread_count/{type}',
    uriVariables: [
        'type' => 'system|non_system|all',
    ],
    output: UnreadNotificationsCount::class,
    provider: UnreadNotificationsCountProvider::class,
)]
final readonly class UnreadNotificationsCount
{
    public function __construct(
        public int $count,
    ) {
    }
}
```
After update on v3.3.11 I get an error

```
  "detail": "Unable to generate an IRI for the item of type \"App\\DTO\\Notification\\UnreadNotificationsCount\"",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/app/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php",
      "line": 194,
      "args": []
    },
```

**Comment by NikDevPHP** [comment]
![image](https://github.com/user-attachments/assets/9614dd48-0507-4252-a3b8-22aa7b044b8b)

The root of the issue is that we get into the `getIriFromResource` method **twice** and the second time the context is an empty array

**Comment by NikDevPHP** [comment]
@soyuka Hello, why don't we pass `$context` further here

https://github.com/api-platform/core/blob/v3.3.11/src/State/Processor/RespondProcessor.php#L115

**Comment by soyuka** [comment]
It's because it could not find identifiers? Context is reset for embed resources it's expected

**Comment by NikDevPHP** [comment]
The identifier `all` in my case was found, if it had not been found we would have received an `InvalidArgumentException` here

https://github.com/api-platform/core/blob/v3.3.11/src/Symfony/Routing/IriConverter.php#L194

**Comment by soyuka** [comment]
The identifiers extractor is supposed to find the uri variables from the $originalData at https://github.com/api-platform/core/blob/v3.3.11/src/State/Processor/RespondProcessor.php#L115
