### ISSUE TITLE
[Question] Single table inheritance

### ISSUE THREAD

**Issue by polc** [api-platform/core#654]
Hello, 

In my project I'm using SINGLE_TABLE inheritance from Doctrine. 
```php
/**
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"user"="User", "admin"="Admin"})
 * @ApiResource()
 */
class User { /* ... */ }

/**
 * @ORM\Entity()
 * @ApiResource()
 */
class Admin extends User { /* ... */ }
```

If for example I have one users and one admin, `GET /users` will return the following: 
```json
{
  "@context": "/contexts/User",
  "@id": "/users",
  "@type": "hydra:Collection",
  "hydra:member": [
      {
          "@id": "/users/1",
          "@type": "User",
          "username": "user1@example.com",
      },
      {
          "@id": "/users/2",
          "@type": "Admin",
          "username": "admin@example.com",
      },
  ],
  "hydra:totalItems": 2
}
```

So the second item have only the User attributes which is what I want, but the `@type ` has Admin value, even if it's only the User part which is returned.

Is this the correct behavior ? :s

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/615 it's a bug

**Comment by dunglas** [comment]
Thanks for the report @polc. Closing as duplicate. Any help to fix this is welcome (I don't use Doctrine inheritance).
