### ISSUE TITLE
Introduce ScalarUI

### ISSUE THREAD

**Issue by valentimarco** [api-platform/core#6545]
**Description**  
I really like this new interactive API documentation call [ScalarUI](https://github.com/scalar/scalar) and would be great to add it 

**Example**  
At the moment I implemented using [Twig Replacement](https://github.com/scalar/scalar/discussions/2926#discussioncomment-10439002)

**Comment by soyuka** [comment]
Would you be able to document this? Thanks!

**Comment by valentimarco** [comment]
What should i do document? i can describe what i did to make that possible:

1. Create a twig file under <root project dir>/templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig
2. Copy the html below:
```html
  {# templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig #}
  {% set openApiJson = swagger_data["spec"] %}
  <!doctype html>
  <html>
  <head>
      <title>Scalar API Reference</title>
      <meta charset="utf-8"/>
      <meta
              name="viewport"
              content="width=device-width, initial-scale=1"/>
  </head>
  <body>
  <!-- Need a Custom Header? Check out this example https://codepen.io/scalarorg/pen/VwOXqam -->
  <script
          id="api-reference"
          type="application/json">{{ openApiJson| json_encode | raw }}</script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script> 
  </body>
  </html>
```
3. Under `api_platform.yaml`, define the following properties: ` tittle`, `description` and `version`

**Comment by soyuka** [comment]
this is awesome you could probably add it to https://github.com/api-platform/docs/blob/3.3/core/openapi.md ?
