### ISSUE TITLE
Cache: TagCollector is not called when collection is empty

### ISSUE THREAD

**Issue by TonySma** [api-platform/core#6546]
**API Platform version(s) affected**: 3.3.11

Thanks to the new mechanism TagCollector, we move our custom logic to gather tags within a class implementing the interface, removing our decorations of deprecated `api_platform.http_cache.listener.response.add_tags` 

**Description**  
When a collection is empty, the `TagCollectorInterface::collect()` method is not called, so we just get the tags by default and can't add some by our own logic.

**How to reproduce**  
Just create a class that implement the TagCollectorInterface and call a collection api with no results

**Possible Solution**  
Looking into it now 

**Additional Context**  
The TagCollector interface is used in the `AbstractItemNormalizer::normalize()` method but the `supports()` is not validated because there is no data (and this is logic btw)

**Comment by soyuka** [comment]
@usu wdyt? could you provide a fix targetting 3.3 @TonySma ?
