### ISSUE TITLE
Symfony Flex recipes missing for 4.x branch

### ISSUE THREAD

**Issue by lermontex** [api-platform/core#6631]
**API Platform version(s) affected**: 4.0.0

**Description**  
When trying to install a new version according to the guide, you will get an error because there are no recipes for the 4.x branch on the server, and the 3.3 recipes are not compatible

**How to reproduce**  

```
symfony new bookshop-api
cd bookshop-api
symfony composer require api
```

**Possible Solution**  
Update Symfony Flex recipes

**Additional Context**  
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 304:
!!                                                                              
!!    Unrecognized option "keep_legacy_inflector" under "api_platform". Available options are "asset_package", "collectio
!!    n", "defaults", "description", "docs_formats", "doctrine", "doctrine_mongodb_odm", "eager_loading", "elasticsearch"
!!    , "enable_docs", "enable_entrypoint", "enable_link_security", "enable_profiler", "enable_re_doc", "enable_swagger",
!!     "enable_swagger_ui", "error_formats", "exception_to_status", "formats", "graphql", "handle_symfony_errors", "http_
!!    cache", "inflector", "jsonschema_formats", "maker", "mapping", "mercure", "messenger", "name_converter", "oauth", "
!!    openapi", "patch_formats", "path_segment_name_generator", "resource_class_directories", "serializer", "show_webby",
!!     "swagger", "title", "use_symfony_listeners", "validator", "version".     
!!                                                                              
!!
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by soyuka** [comment]
We're on it, a few leftovers to fix this :) https://github.com/api-platform/core/pull/6635 then we tag then we fix the recipe (pr is ready)

**Comment by dunglas** [comment]
I opened the PR on Symfony repo: https://github.com/api-platform/core/issues/6631

**Comment by lermontex** [comment]
@dunglas, It works, thank you! 

Please note that the `api-platform/core` package will be installed instead of `api-platform/symfony`

Perhaps we should also update the `api-pack` package?

https://packagist.org/packages/api-platform/api-pack

**Comment by DIOHz0r** [comment]
I got the update (4.0.3) but I'm still getting the error if I do a `bin/console cache:clear`

here is the verbose output

$ bin/console cache:clear -vvv

In ArrayNode.php line 304:
                                                                                                                                                                                                                                      
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                                                                                                                       
  Unrecognized option "keep_legacy_inflector" under "api_platform". Available options are "asset_package", "collection", "defaults", "description", "docs_formats", "doctrine", "doctrine_mongodb_odm", "eager_loading", "elasticse   
  arch", "enable_docs", "enable_entrypoint", "enable_link_security", "enable_profiler", "enable_re_doc", "enable_swagger", "enable_swagger_ui", "error_formats", "exception_to_status", "formats", "graphql", "handle_symfony_error   
  s", "http_cache", "inflector", "jsonschema_formats", "maker", "mapping", "mercure", "messenger", "name_converter", "oauth", "openapi", "patch_formats", "path_segment_name_generator", "resource_class_directories", "serializer"   
  , "show_webby", "swagger", "title", "use_symfony_listeners", "validator", "version".                                                                                                                                                
                                                                                                                                                                                                                                      

Exception trace:
  at F:\webs\condorplus\api\vendor\symfony\config\Definition\ArrayNode.php:304
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at F:\webs\condorplus\api\vendor\symfony\config\Definition\BaseNode.php:357
 Symfony\Component\Config\Definition\BaseNode->normalize() at F:\webs\condorplus\api\vendor\symfony\config\Definition\Processor.php:32
 Symfony\Component\Config\Definition\Processor->process() at F:\webs\condorplus\api\vendor\symfony\config\Definition\Processor.php:46
 Symfony\Component\Config\Definition\Processor->processConfiguration() at F:\webs\condorplus\api\vendor\symfony\dependency-injection\Extension\Extension.php:109
 Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at F:\webs\condorplus\api\vendor\api-platform\core\src\Symfony\Bundle\DependencyInjection\ApiPlatformExtension.php:106
 ApiPlatform\Symfony\Bundle\DependencyInjection\ApiPlatformExtension->load() at F:\webs\condorplus\api\vendor\symfony\dependency-injection\Compiler\MergeExtensionConfigurationPass.php:81
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at F:\webs\condorplus\api\vendor\symfony\http-kernel\DependencyInjection\MergeExtensionConfigurationPass.php:40
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at F:\webs\condorplus\api\vendor\symfony\dependency-injection\Compiler\Compiler.php:73
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at F:\webs\condorplus\api\vendor\symfony\dependency-injection\ContainerBuilder.php:752
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at F:\webs\condorplus\api\vendor\symfony\http-kernel\Kernel.php:495
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at F:\webs\condorplus\api\vendor\symfony\http-kernel\Kernel.php:740
 Symfony\Component\HttpKernel\Kernel->preBoot() at F:\webs\condorplus\api\vendor\symfony\http-kernel\Kernel.php:120
 Symfony\Component\HttpKernel\Kernel->boot() at F:\webs\condorplus\api\vendor\symfony\framework-bundle\Console\Application.php:177
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at F:\webs\condorplus\api\vendor\symfony\framework-bundle\Console\Application.php:69
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at F:\webs\condorplus\api\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at F:\webs\condorplus\api\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at F:\webs\condorplus\api\vendor\autoload_runtime.php:29
 require_once() at F:\webs\condorplus\api\bin\console:15

**Comment by lermontex** [comment]
@DIOHz0r, The `keep_legacy_inflector` option is obsoleted and no longer supported in `api-platform/symfony` v4.0+, you need to remove it in your configuration (`packages/api_platform.yaml`)
