### ISSUE TITLE
Is it possible to forward a request / do a sub reuest to API Platform controller?

### ISSUE THREAD

**Issue by olia-bn** [api-platform/core#6652]
I can't figure out how to forward a request / perform a sub request to an API endpoint controller.

Is this possible and if so, how?

**Comment by soyuka** [comment]
Probably just inject the [MainController](https://github.com/api-platform/core/blob/main/src/Symfony/Controller/MainController.php) (or the [Laravel ApiPlatformController](https://github.com/api-platform/core/blob/main/src/Laravel/Controller/ApiPlatformController.php)) and call it? This is more a support question then a bug fix though, closing use slack or the questions tab thanks!.
