### ISSUE TITLE
Undesired "servers" on each operation - Operation Servers config in v3.3 does not seem to work

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#6671]
**API Platform version(s) affected**: 3.3.11

**Description**  

Upgrading from 3.1 to 3.3 noticed that the servers are shown on try-out for each operation, which was not the case before
. 
It is fine as such, but that's not a feature we want to have displayed at each operation.

I noticed that there's the "servers" config and tried to set it to null our an empty array, but the servers are still shown.

![image](https://github.com/user-attachments/assets/72dd513e-d68d-4ea6-944d-ee8be6129c66)

**How to reproduce**  

```
operations: [
            new GetCollection(
                openapi: new Operation(
                    servers: null,
```

**Possible Solution**  

**Additional Context**  

It may be the case that the "servers" config on Operation is not the right place to remove the servers from each operation, but the bottom line is that it should be possible to remove them.

**Comment by BernardA** [comment]
Still expecting some response to this. Thanks

**Comment by soyuka** [comment]
Isn't that an issue from the Swagger UI ? I don't reckon we changed anything unless updating js dependencies.

**Comment by BernardA** [comment]
@soyuka Not sure where the issue is coming from, but it's there. Are you suggesting I open this issue somewhere else and if so where?

**Comment by soyuka** [comment]
I'd like a way to reproduce, would you be able to make a reproducer based on the api-platform/api-platform template ?

**Comment by BernardA** [comment]
@soyuka As requested, please find the repo [here](https://github.com/BernardA/issue-core-6671).

There's not much to it. I just added a User entity. That's all. 

This is how the server show on try out:

![image](https://github.com/user-attachments/assets/3d64181f-034f-4852-b63c-dd89c1592518)

**Comment by soyuka** [comment]
There's not much I can do see https://github.com/swagger-api/swagger-ui/issues/8309
