### ISSUE TITLE
[Laravel] Feature: Support custom Normalizers

### ISSUE THREAD

**Issue by toitzi** [api-platform/core#6677]
**Description**  
In Laravel applications, it's common to cast model attributes using [casts](https://laravel.com/docs/11.x/eloquent-mutators#attribute-casting). For example, you can cast a value as an Enum or any custom class that supports casting:

![image](https://github.com/user-attachments/assets/4a6c22d1-31a5-421f-aaf6-9e3da65954ee)

The issue is that API Platform currently only handles casted types if they are compatible with one of the normalizers registered by the package:

![image](https://github.com/user-attachments/assets/cf3e84ad-e64b-4822-a99b-8143aa2ca435)

otherwise this will throw an Error. While it may work fine for many cases, casting to other types — such as enums — is quite common in Laravel. If API Platform would support custom Normalizers, one could just write his own EnumNormalizer and still profit from Laravel Casts.

**Example**  

In `config/api-platform.php`

```
'normalizer' => [
    \App\Normalizer\EnumNormalizer::class => -920, // Class => Priority
],
```

**Possible implementation**
Create the config entry, insert the normalizers inside the `ApiPlatformProvider`. Pretty straight forward tbh.

**Workarround**

Since this package heavily utilizes Laravel’s container classes, it’s possible to achieve this behavior by adding a custom service provider in Laravel and overriding the shared container binding.

**Summary**
I believe supporting this out of the box would be valuable, as it's a common practice. However, since there is a clean workaround available, it’s ultimately up to you whether to implement it. If you're interested, I’ve already patched this and can happily create a PR and update the documentation.

**Comment by dunglas** [comment]
Hi,

Indeed the recommended way to handle this is to use Laravel DI. Maybe adding some documentation explaining how to do that would be enough?

If it's not, we could maybe add add a specific config option, a new attribute or a trait to register a new normalizer in a more easy way?

**Comment by toitzi** [comment]
You are probably right. Not doing it now, does not mean it cannot be done later if it is needed by more people / or makes more sense at some point later on.

I will close this and do a Docs PR! :)

**Comment by andre-hoong-ps** [comment]
Do we have a link to the documentation for this? I am trying to implement this but running into issues where inserts into the SplPriorityQueue are not being respected

**Comment by toitzi** [comment]
@andre-hoong-ps no it is not in the docunentation yet, i will open a PR soon. If you try the way i did it in the screenshot above, it shold work, if it still does not please provide more info on how i can reproduce the issue, i will then look into it

**Comment by andre-hoong-ps** [comment]
Hey @toitzi this happens for me with:
```
"php": "^8.2",
"laravel/framework": "^11.9",   
"api-platform/laravel": "^4.0",

```

In my service provider I am trying to do 
```
        $this->app->extend('api_platform_normalizer_list', function (\SplPriorityQueue $list, Application $app) {
            $list->insert($app->make(BackedEnumNormalizer::class), -905);

            return $list;
        });
```

In my application after I create the list I don't see the backed enum denormalizer
```
app('api_platform_normalizer_list')
```

If I remove the dev dependency `nunomaduro/collision` that comes pre-installed with Laravel, it works. I'm not sure why this is the case though

**Comment by toitzi** [comment]
@andre-hoong-ps Sorry for the late response... hm really weired....your example works for me in what service provider are you adding the snippet above? Can you share the whole provider? and please also share your bootstrap/providers.php to check when all of this is loaded.
