### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by foolskill** [api-platform/core#668]
Hi everybody,

I have a problem with the documentation of my API.
In fact Swagger shows me a 500 error 'Internal server error'. I would like to know if anyone knows what it is about. my application works fine but no documentation

`{"error":{"code":500,"message":"Internal Server Error"}}`

Thank's

**Comment by Simperfit** [comment]
Could please run the swagger command ? `bin/console api:swagger:export`

**Comment by foolskill** [comment]
Hi @Simperfit 

Thank you.

the response about `php bin/console api:swagger:export` : 

`[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: serializer_groups  `

**Comment by dunglas** [comment]
Can you add the -vvv flag to the command? It should display the full stack trace.

**Comment by foolskill** [comment]
yes @dunglas 

the screenshot:

![beug-swagger](https://cloud.githubusercontent.com/assets/6184877/17473756/78a8515a-5d52-11e6-8362-7b9dd78dd49c.PNG)

**Comment by Simperfit** [comment]
Please re-open the issue if you still have it.
