### ISSUE TITLE
QueryParamter on DTO with stateOptions does not work

### ISSUE THREAD

**Issue by bendavies** [api-platform/core#6682]
**API Platform version(s) affected**: 3.4.1

**Description**  
using `ApiFilter`, this works:
```php
#[ApiFilter(DateFilter::class, properties: ['birthday'])]
#[ApiResource(
    stateOptions: new Options(entityClass: Agent::class),
    shortName: 'Agent',
    operations: [
        new GetCollection(),

    ]
)]
class AgentApi
{
...
}
```

Trying to change this to `QueryParameter` does not work:
```php
#[ApiFilter(DateFilter::class, properties: ['birthday'], alias: 'app_filter_date')]
#[ApiResource(
    stateOptions: new Options(entityClass: Agent::class),
    shortName: 'Agent',
    operations: [
        new GetCollection(parameters: [
            'bla[:property]' => new QueryParameter(filter: 'app_filter_date'),
        ])
    ]
)]
class AgentApi
{
...
}
```

This is because `stateOptions` are not respected here:
https://github.com/api-platform/core/blob/3.4/src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php#L120
https://github.com/api-platform/core/blob/3.4/src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php#L245

I fixed these to respect stateOptions and it still didn't work (swagger ui was wrong)
so maybe other places need fixing?

**Possible Solution**  
respect `stateOptions`

**Comment by soyuka** [comment]
releases friday but if you have time to try that earlier it'd be lovely!
