### ISSUE TITLE
Maximum items does not have effect for relations

### ISSUE THREAD

**Issue by Cruiser13** [api-platform/core#6687]
**API Platform version(s) affected**: 3.X (reproduced on 3.1.25 and 3.3.13)

**Description**  
We have a class FileSystem that has a OneToMany relation to our class File. If we run the /filesystem endpoint we expect to get all file systems back. That works but each file system does contain the IDs of all files associated with it. That's usually above ~50.000 entries. We'd expect the pagination_maximum_items_per_page setting (set to 100) to take effect here but it doesn't. This does cause severe memory limits on server and client. We did not find any documentation to limit these related values if pagination does not work.

**How to reproduce**  
Create a filesystem class (or any class with a OneToMany relation) and create > 10.000 related entities. It'll give you all of these entities.
```
#[ApiResource]
class FileSystem
{
    // .... other code

    #[ORM\OneToMany(mappedBy: 'fileSystem', targetEntity: File::class)]
    private $files;

      // .... others code
}
```

**Possible Solution**  
-

**Additional Context**  
Payload example screenshot with fewer relations:
![sample-payload](https://github.com/user-attachments/assets/73f1c195-33cf-44c3-9b2e-614f0961b655)

**Comment by Cruiser13** [comment]
@soyuka could you look at this maybe? It makes api platform completely unusable on bigger instances at the moment. Any pointer to where I could look at to submit a pr would be great too.

**Comment by Cruiser13** [comment]
Issue does still exist on [v3.4.5](https://github.com/api-platform/core/releases/tag/v3.4.5)

**Comment by soyuka** [comment]
Pagination has no effects on relation, we strongly discourage the usage of embedded collections like this. The solution we provide is described in that guide: https://api-platform.com/docs/guides/return-the-iri-of-your-resources-relations/. 
The idea is to create a resource that lists files for a given filesystem: `/filesystems/{id}/files`, follow our guide or the documentation at https://api-platform.com/docs/core/subresources/ to build this with Links. You can also provide a `LinksHandlerInterface` if you want to have more fine-tuning over the linkage of resources (https://api-platform.com/docs/guides/handle-links/). 
Then you reference this link using `#[ApiProperty(uriTemplate: '/filesystems/{id}/files')]`. 

Hope that this helps.

**Comment by Cruiser13** [comment]
@soyuka thank you for your reply! We actually only return the iri's, not the object itself. If you look at my screenshot above files is just an iri with ~16.000 iris in it. It's the number of iris that bring the server down.

**Comment by soyuka** [comment]
Please check https://api-platform.com/docs/guides/return-the-iri-of-your-resources-relations/, this should not serialize nor query the whole relation.

**Comment by Cruiser13** [comment]
Thank you @soyuka I guess we need to go this way in this case.
