### ISSUE TITLE
Error resource for domain exceptions is broken in 3.4

### ISSUE THREAD

**Issue by tobiasgv** [api-platform/core#6688]
**API Platform version(s) affected**: 3.4.1

**Description**  
Custom error resources for domain exceptions as described [here](https://api-platform.com/docs/v3.4/guides/error-resource/)  are not serialized as expected, i.e. public properties like 'title' or 'detail' (for exceptions implementing the ProblemExceptionInterface as recommended) are not included in the JSON response on error.

The feature broke somewhere here: https://github.com/api-platform/core/compare/v3.4.0-alpha.6...v3.4.0-alpha.7

**How to reproduce**  
Create an domain exception class with the ErrorResource attribute, add some public methods are properties, throw the exception and look at the response JSON. 

**Workaround**
Adding this to our error resource (which is a child of the ApiPlatfrom Error class) is a temporary workaround
```
    normalizationContext: [
        'groups' => null,
```

**Comment by soyuka** [comment]
Can you remove the following configuration?

```yaml
api_platform:
   defaults:
           rfc_7807_compliant_errors: true
```

**Comment by tobiasgv** [comment]
Thanks for the reply.

I now get more attributes, but my custom attributes are still not serialized:
```php
array:5 [
  "@context" => "/contexts/Error"
  "@type" => "hydra:Error"
  "hydra:title" => "An error occurred"
  "hydra:description" => "it wasn't me"
  "trace" => array:20 [ ...
```

Anyway, we are now at 3.4.2 and created a custom ErrorProvider (since some of out frontends still rely on 'hydra:description'), which creates our own ApiError (a subclass of api-platform Error). This works for us, for now.

**Comment by soyuka** [comment]
See in my test I do get custom fields but indeed on 4.x. 

https://github.com/api-platform/core/blob/main/src/Symfony/EventListener/ErrorListener.php#L96-L106

Closing then thanks for the report.
