### ISSUE TITLE
ramsey-uuid package required due some external package

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#6695]
**API Platform version(s) affected**: 3.4

**Description**  

We don't use ramsey/uuid in our own code but an external package is installing this package. Due the check inside api-platform/symfony we must install api-platform/ramsey-uuid to not get an error. 

**How to reproduce**  

**Possible Solution**  

Can we improve this check so we can remove this dependency?

**Additional Context**

**Comment by dunglas** [comment]
@dannyvw thanks for the report. Could you test if https://github.com/api-platform/core/pull/6696 fixes the issue on your project, please?

**Comment by dannyvw** [comment]
@dunglas Yes that works, thx for the quick fix!
