### ISSUE TITLE
[Laravel/GraphQL] Custom QueryParameter, removes default args

### ISSUE THREAD

**Issue by toitzi** [api-platform/core#6698]
**API Platform version(s) affected**: 4.0.3

**Description**  
I have a User Model, and the goal is to get all users (paginated) but also beeing able to order them. To archive this i added the following to my `App\Models\User`:

```
#[ApiResource(
    operations: [
        new Get(),
        new GetCollection(
            parameters: [
                new QueryParameter(key: 'order[:property]', filter: OrderFilter::class),
            ],
        )
    ],
    graphQlOperations: [
        new Query(),
        new QueryCollection(
            parameters: [
                new QueryParameter(key: 'order[:property]', filter: OrderFilter::class),
            ],
        )
    ],
)]
```

Once i do that, pagination features are not working anymore in GraphQL (if i would also apply some custom query parameter to `Query` or appy the filter globally, the filtering for `id` would not work anymore). That is different behaviour to the REST Version the above code will produce the following in the REST Version:

![image](https://github.com/user-attachments/assets/8ef15012-7e7b-4154-b673-ea48dce0087f)

As you can see, the pagination is still there. However in GraphQL, this will happen:

![image](https://github.com/user-attachments/assets/bb4230da-8722-4e1e-abb0-4e139563d201)

While the return type still is a user Cursor Connection, it is not possible to pass "first, after, etc..." pagination params. The reason for it is, that inside the `FieldsBuilder` the `$fieldConfiguration['args']` is only applied when there are no custom args/query parameters ([here](https://github.com/api-platform/core/blob/fcd9a0725fb9fab942b306e5d3cb0e96226ee63e/src/GraphQl/Type/FieldsBuilder.php#L110) and [here](https://github.com/api-platform/core/blob/fcd9a0725fb9fab942b306e5d3cb0e96226ee63e/src/GraphQl/Type/FieldsBuilder.php#L88)).

EDIT: That is what i would expect it to be.
![image](https://github.com/user-attachments/assets/063f452a-c5cf-4a72-bffc-c6df48a95af3)

**Comment by soyuka** [comment]
Really interesting, I'll add a test for this thanks!
