### ISSUE TITLE
Deprecation ElasticsearchProviderResourceMetadataCollectionFactory

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#6707]
**API Platform version(s) affected**: 3.4

**Description**  

User Deprecated: Since api-platform/core 4.0: Using $client at "ApiPlatform\Elasticsearch\Metadata\Resource\Factory\ElasticsearchProviderResourceMetadataCollectionFactory" is deprecated and the argument will be removed.

We have installed api-platform/core 3.4. Is the message perhaps incorrect?

**How to reproduce**  

**Possible Solution**  

**Additional Context**  

How can we solve this deprecation?

**Comment by soyuka** [comment]
do you have a stack trace for this? I guess installing the next version of elasticsearch php solves the issue. It looks like it should be 3.4 not 4.0.

**Comment by dannyvw** [comment]
Should indeed be resolved when updating elasticsearch. The client is set here https://github.com/api-platform/core/blob/3.4/src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L967 Changing the message to 3.4 is then enough
