### ISSUE TITLE
Laravel OpenID Connect authentication on Swagger UI

### ISSUE THREAD

**Issue by cay89** [api-platform/core#6713]
**API Platform version(s) affected**: 4.0.2

**Description**  
I don't think the [Api Platform documentation](https://api-platform.com/docs/laravel/#authentication) covers how to set up [OpenID Connect authentication](https://swagger.io/docs/specification/v3_0/authentication/openid-connect-discovery/) in Swagger UI. I would need to be able to configure it like this:

![image](https://github.com/user-attachments/assets/06c25154-08d2-49a7-877c-9e452e058641)

But how can this be done? Or is it not implemented yet?

**Comment by soyuka** [comment]
Your patch has been released, can you confirm it fixes your issue? Thanks for the report!

**Comment by cay89** [comment]
Yes, OpenID Connect works with the OAuth config now.
