### ISSUE TITLE
The root cause of the deserialization error remain hidden on API output

### ISSUE THREAD

**Issue by cay89** [api-platform/core#6725]
**API Platform version(s) affected**: 4.0.4

**Description**  
If `\ApiPlatform\State\Provider\DeserializeProvider::provide()` throws an error, I only get the message "An error occurred" alongside the "trace", but it doesn't specify what the actual issue is.

If I catch it here and print it out, it turns out that the message is "Update is not allowed for this operation."

\ApiPlatform\State\Provider\DeserializeProvider
![image](https://github.com/user-attachments/assets/bfb279e0-9b39-4a89-9fd4-1b131dc074bd)

**How to reproduce**  
Throw an exception in `\ApiPlatform\State\Provider\DeserializeProvider::provide()`.

**Possible Solution**  
Add `#[Groups(['jsonld', 'jsonproblem', 'jsonapi'])]` attribute to `ApiResource/Error::getDescription()` method.

ApiResource/Error
```php
#[SerializedName('description')]
#[Groups(['jsonld', 'jsonproblem', 'jsonapi'])]
public function getDescription(): string
{
    return $this->detail;
}
```

Result:

![image](https://github.com/user-attachments/assets/9519a818-91d6-40e8-9bab-3cece1d7dc5f)

**Comment by soyuka** [comment]
`description` is only for JSON-LD,  `detail` should always be available though.
