### ISSUE TITLE
[Laravel] Caching strategy and warm up

### ISSUE THREAD

**Issue by toitzi** [api-platform/core#6735]
**Description**  
While running into performance issues on my machine with requests taking up to seconds, i noticed that API Platform decides between 2 cache methods (array/file) based on the APP_DEBUG setting which was quite confusing. I get that the default value for using laravels cache setting `CACHE_STORE` is `file` and that in development instances you wouldn't wanna cache at all. So i can also see why you would check for another .env setting (like DEBUG). However i couldn't find that in the documentation (maybe i missed it). So i'd like to propose the following changes:

1. Document that the `DEBUG` setting changes the caching strategy for api platform (or switch to a config setting or to `ENVIRONMENT` (production/local) setting or whatever - altough i would prefer something like using the `ENVIRONMENT` setting, ultimately i think it does not really matter as long as it is in the docs)

2. Reagardless of the Above, keep `array` in "debug" cases but use the `CACHE_STORE` setting which comes with laravel for production e.g non debug. It defaults to file anyway and allows more control with no overhead.

3. Since that cache is stored "forever" when it is first accessed (Metadata etc.. does not change on production environments), it could be cool/useful to hook into the Optimze command of laravel ([described here](https://laravel.com/docs/11.x/packages#optimize-commands)) and "warm up" the cache with that data. I think that would be pretty neat.

Let me know what you think about that, i will happily submit a PR :)

**Comment by toitzi** [comment]
Nevermind, cache warm up seems to happen anyway when registering routes...using the laravel conf for cache provider would still be great, in case some might want to use memory caching like apcu instead of file caches

**Comment by soyuka** [comment]
Indeed we didn't thought it'd need to be documented. In symfony we rely on the `debug` value as if you don't debug you probably want the metadata to be cached no? Maybe that we should just add a configuration for this and default to the `debug` value?

:+1: to use the `CACHE_STORE`, I wasn't aware of this setting do you have a reference on how to use this?

**Comment by amermchaudhary** [comment]
@soyuka https://laravel.com/docs/11.x/cache#main-content

**Comment by amermchaudhary** [comment]
In my [PR](https://github.com/api-platform/core/pull/6744) above, I'm using Laravel's cache and also setting the default cache driver to null for workbench tests

**Comment by toitzi** [comment]
@soyuka You are right my bad, debug is the recommended setting anyway for this (also in [laravel](https://laravel.com/docs/11.x/configuration#debug-mode)). So it is fine leave that part as is.

Opend a PR for using laravel cache settings tho, since that is what one would probably expect.

**Comment by toitzi** [comment]
Closed with #6751
