### ISSUE TITLE
problem with base url in Restangular

### ISSUE THREAD

**Issue by dem3trio** [api-platform/core#675]
Hi everyone,

I'm a newbie with api platform and I'm doing some basic things and this issue I don't know if is a problem from api platform, a problem from Restangular or (more probably) a thing that I'm not understanding well.

I have configured my restangular app as the [documentation](https://github.com/api-platform/docs/blob/master/core/angularjs-integration.md#restangular) says. With one difference, my base url is: `http://myapplication.dev/app_dev.php/api`

The symfony application has a basic configuration (added the annotations to the entities and a route) as the core [documentation](https://github.com/api-platform/docs/blob/master/core/getting-started.md) says.

I have this controller

``` javascript
(function () {
    'use strict';

    angular.module('app')
        .controller('companyController', [ "$scope", "Restangular", "$mdDialog", function($scope, Restangular, $mdDialog){

            $scope.companies = [];
            $scope.company = null;
            $scope.people = [];

            var peopleApi = Restangular.all('people');

            $scope.loadCompanies = function() {
                $scope.companies = Restangular.all('companies').getList().$object;
            };

            $scope.loadCompanies();

            $scope.loadPeople = function(company)
            {
                if(null === company) { return; }
                $scope.people = peopleApi.getList({company: company['@id']}).$object;
            };

            $scope.$watch('company', function(company) {
                $scope.loadPeople(company);
            });

            $scope.selectCompany = function(index){
                $scope.company = $scope.companies[index];
            };

            $scope.confirmEmployeeDelete = function(ev, employee) {
                var confirm = $mdDialog.confirm()
                    .title('Do yow want to delete this employee?')
                    .textContent('Delete ' + employee.name + ' ' + employee.lastname1 + '.')
                    .targetEvent(ev)
                    .ok('Accept')
                    .cancel('Cancel');

                $mdDialog.show(confirm).then(function() {
                    employee.remove().then(function() {
                        $scope.loadPeople($scope.company);
                    });
                }, function() {
                    console.log('do nothing');
                });
            };
        }]);
})();

```

My problem is with the `employee.remove()` function. It is a Restangular resource. the `@id` in this case is something like `app_dev.php/api/people/1`. So the remove function is making a DELETE request to `http://myapplication.dev/app_dev.php/api/app_dev.php/api/people/8`. So I get a 404.

What I'm doing wrong?

Thanks in advance

**Comment by Simperfit** [comment]
The base URL in documentation is `RestangularProvider.setBaseUrl('http://localhost:8000');`, the one you are using should be `http://myapplication.dev/` or and you should request what the hydra's iri gives you.

**Comment by dem3trio** [comment]
Thanks for the response. But this makes me to have another question.

If I set the base url to ```http://myapplication.dev/```, my rest api client (in this case, Restangular),  won't work, because the entry point of the API is at ```http://myapplication.dev/api/``` 

Shouldn't be the hydra's iris, relative to the entry point? I mean, ```/people/1``` instead of ```/api/people/1``` (or in my case, in the symfony's dev environment, ```app_php/api/people/1```)

**Comment by Simperfit** [comment]
No, Hydra IRIs are relative to the baseUrl not to the entrypoint url.

You should adapt the Restangular configuration based on the url you are using.

You should set `http://myapplication.dev/api/` as baseUrl and adapt the configuration to call the `@id` without the `/api/`.

**Comment by dem3trio** [comment]
I have reconfigured Restangular, modifying the ```@id```. Like this:

```javascript

    angular.module('app').config(function (RestangularProvider) {

        var baseUrl = 'http://api.myeeting.dev/app_dev.php/api';
        var urlComplement = '/app_dev.php/api';

        RestangularProvider.setBaseUrl(baseUrl);
  
     // ... same as the previous configuration
  
        // Hydra collections support
        RestangularProvider.addResponseInterceptor(function (data, operation) {

            function populateHref(data) {
                if (data['@id']) {
                    data['@id'] = data['@id'].substr(urlComplement.length);
                    data.href = data['@id'];
                }
            }

            // Populate href property for the collection
            populateHref(data);
                  // ... same as the previous configuration
        });
    });
```

And now, the method ```loadPeople(company)``` isn't working, because the api platform filtering is not recognizing the ids without the ``/api/```.

```
// ...
var peopleApi = Restangular.all('people');
// ...
$scope.loadPeople = function(company)
 {
     if(null === company) { return; }
     $scope.people = peopleApi.getList({company: company['@id']}).$object;
 };
// ...
```

**Comment by Simperfit** [comment]
@dem3trio Did you find a solution ?
 ```
      // JSON-LD @id support
        RestangularProvider.setRestangularFields({
            id: '@id',
            selfLink: '@id'
        });
```

Did you have something like this  BTW ?
