### ISSUE TITLE
`Symfony\...\MethodNotAllowedHttpException` not transformed in `hydra:Error`

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#6778]
**API Platform version(s) affected**: 4.0.6 (maybe also previous 4.* versions)

**Description**  
I hve tests that check that particular HTTP methods are disabled.

They use a custom assertion like this:

```php
    protected function assertResponseIsMethodNotAllowed(string $endpoint, string $method, array $subset, array $placeholders = []): void
    {
        $this->assertResponseStatusCodeSame(Response::HTTP_METHOD_NOT_ALLOWED);
        $this->assertResponseMatchesJsonPattern(
            endpoint: $endpoint,
            subset: $subset,
            placeholders: $placeholders,
            pattern: [
                '@context'          => '/api/contexts/Error',
                '@type'             => 'hydra:Error',
                'hydra:title'       => 'An error occurred',
                'hydra:description' => sprintf('@string@.startsWith("No route found").contains("%s https://").contains("/{app_api_entrypoint}{api_endpoint}").contains("Method Not Allowed")', $method),
                'trace'             => '@...@',
            ],
        );
    }
```

But the response is, instead, this:

```json
{
    "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
    "title": "An error occurred",
    "status": 405,
    "detail": "No route found for \"POST https:\/\/myapp.localhost\/api\/accounts\/2\/orders\/2\/collects\/1\": Method Not Allowed (Allow: GET)",
    "class": "Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException",
    "trace": ...
}
```

**Is this on purpose or there is something broken with the new version of Api Platform?**

**How to reproduce**  

1. Enable `json-ld` format
2. Set the `hydra_prefix` to `true`
3. Disable an HTTP method for a resource
4. Try to access that resource with the disabled method

```yaml
api_platform:
  formats:
    jsonld: ['application/ld+json']
  serializer:
    hydra_prefix: true
```

**Possible Solution**  
-

**Additional Context**  

I'm still using `api-platform/core`.

**Comment by soyuka** [comment]
it looks like you requested without `accept: application/ld+json`?

**Comment by Aerendir** [comment]
I'm setting the correct mime type.

To call the endpoint, I use another custom method:

```php
protected static function callEndpoint(string $method, string $endpoint, array $jsonData = [], array $requestOptions = [], array $kernelOptions = [], array $defaultOptions = [], array $placeholders = []): ResponseInterface
    {
        $endpoint       = self::prepareEndpoint($endpoint, $placeholders);
        $client         = self::createClient($kernelOptions, $defaultOptions);
        $jsonLdContentType = MimeType::fromExtension('jsonld');
        $contentType    = $jsonLdContentType;
        if (Request::METHOD_PATCH === $method) {
            $contentType = 'application/merge-patch+json';
        }

        $requestOptions = ['json' => $jsonData, 'headers' => ['Content-Type' => $contentType, 'Accept' => $jsonLdContentType], ...$requestOptions];

        return $client->request($method, $endpoint, $requestOptions);
    }
```

Before your hint, I didn't added the `Accept` header.

Adding it, when calling the endpoint, these are the request options:

```
Array
(
    [json] => Array
        (
            [username] => username
            [password] => password
        )

    [headers] => Array
        (
            [Content-Type] => application/ld+json
            [Accept] => application/ld+json
        )

)
```

Also with the `Accept` header, the response is the same...

**Comment by soyuka** [comment]
My guess is that this error is thrown before content negotiation occurs, therefore we can't know that the json-ld format is prefered. As it's compatible with problem+json anyways it's not a big deal, or is it?

**Comment by Aerendir** [comment]
> My guess is that this error is thrown before content negotiation occurs, therefore we can't know that the json-ld format is prefered. As it's compatible with problem+json anyways it's not a big deal, or is it?

Absolutely not: it is not a big deal.

Actually, i had to set `serializer.hydra_prefix` to maintain the `hydra:` prefix.

But, as far as I understand (and as far as it seems to me you are confirming), prefixing keys with `hydra:` is not mandatory.

I simply had a doubt about this necessity.

But, as it seems not mandatory, I think I will remove the `hydra:` prefix from all keys (and the issue reported in this issue will "magically" vanish 😬).

So, as far as I understand also reading https://github.com/api-platform/core/issues/6209 it's absolutely safe to simply remove the prefix.

Thank your for your support!
