### ISSUE TITLE
[Laravel] 404 Format \"xxx\" is not supported when have 2 API with similar route

### ISSUE THREAD

**Issue by chung1905** [api-platform/core#6779]
**API Platform version(s) affected**: 4.0.6

**Description**  
I'm using Laravel 11 and API Platform 4.
I have 2 API Resource:
```
#[Entity]
#[ApiResource]
class Staff extends Model
{
}
```
and
```
#[Entity]
#[ApiResource]
class StaffPositionHistory extends Model
{
}
```

I believe the content doesn't matter so I tripped them down.
When I calling to `.../api/staff_position_histories?page=1`
I got this 404 error: `Format \"position_histories\" is not supported`
I debugged a bit and found, the operation it's matching Staff route instead of Staff Position History
![image](https://github.com/user-attachments/assets/6a039d1f-67b1-4d36-9070-3b3c8b211c5b)

Is there any way I disable the `{_format}` in route matching for now?

**Comment by soyuka** [comment]
mhh indeed this is anoying, let me check that
