### ISSUE TITLE
Using the Orm/Filter/SearchFilter to filter the "id" property of a relation leads to unnecessary INNER JOIN in the query when filter contains invalid values

### ISSUE THREAD

**Issue by ES-Six** [api-platform/core#6790]
**API Platform version(s) affected**: 3.3.11

**Description**  
I have an AdminProfile entity that has a OneToOne relation with a GlobalConfiguration entity. This relation is nullable, like this :
```php
    #[ApiProperty(openapiContext: SchemaConst::INTEGER_SCHEMA, jsonSchemaContext: SchemaConst::INTEGER_JSON_SCHEMA)]
    #[ORM\OneToOne(inversedBy: 'adminProfileBuilder', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    #[Groups(['admin-profile:update'])]
    private ?GlobalConfiguration $defaultGlobalConfiguration = null;
```

I declared in the AdminProfile entity the following SearchFilter :
```php
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;

[...]

#[ApiFilter(filterClass: SearchFilter::class, properties: [
    'defaultGlobalConfiguration.id' => 'exact',
])]
```

The filter itself works fine when passing valid values, but if I pass an invalid value, the filter will add an unused INNER JOIN that will change the current query behaviour because if I have a nullable relation between both entities, the presence of the unused INNER JOIN will filter all the entities having a relations and eliminate the one that doesn't have one.

The problem is due to this part of the SearchFilter in the filterProperty function, I added comments to the following extract of code to show the problem  :
```php
$associations = [];

       // --------> HERE the INNER JOIN is added to the query
        if ($this->isPropertyNested($property, $resourceClass)) {
            [$alias, $field, $associations] = $this->addJoinsForNestedProperty($property, $alias, $queryBuilder, $queryNameGenerator, $resourceClass, Join::INNER_JOIN);
        }

        $caseSensitive = true;
        $strategy = $this->properties[$property] ?? self::STRATEGY_EXACT;

        // prefixing the strategy with i makes it case insensitive
        if (str_starts_with($strategy, 'i')) {
            $strategy = substr($strategy, 1);
            $caseSensitive = false;
        }

        $metadata = $this->getNestedMetadata($resourceClass, $associations);

        if ($metadata->hasField($field)) {
            if ('id' === $field) {
                $values = array_map($this->getIdFromValue(...), $values);
                // todo: handle composite IDs
            }

            // --------> HERE the filtered values are checked but the INNER JOIN was already added above, so the SearchFilter changed the current query behaviour
            if (!$this->hasValidValues($values, $this->getDoctrineFieldType($property, $resourceClass))) {
                $this->logger->notice('Invalid filter ignored', [
                    'exception' => new InvalidArgumentException(sprintf('Values for field "%s" are not valid according to the doctrine type.', $field)),
                ]);

                return;
            }

            $this->addWhereByStrategy($strategy, $queryBuilder, $queryNameGenerator, $alias, $field, $values, $caseSensitive);

            return;
        }
```

**How to reproduce**  
- Use a SearchFilter with exact strategy on an entity having a nullable OneToOne relation with another entity using the DOCTRINE_INTEGER_TYPE in it's property (eg : an id of type int).
- Make a GET request to the API, like this one in my context :
    - https://localhost/api/v3/schools/1/admin-profiles?defaultGlobalConfiguration.id=ABC
    - ABC is not a valid integer but the "id" property in the GlobalConfiguration entity is of type int on its doctrine column, so the filter should be ignored.

**Possible Solution**  
- Check values validity **before** the SearchFilter apply the INNER JOIN in the query

**Additional Context**  
- After examining the SearchFilter code on the api-platform/core main, the bug will be also on the latest versions as the code on the main branch have it :
    - Inner join is added here : https://github.com/api-platform/core/blob/main/src/Doctrine/Orm/Filter/SearchFilter.php#L184
    - But valid values are checked after the inner join is added here : https://github.com/api-platform/core/blob/main/src/Doctrine/Orm/Filter/SearchFilter.php#L204

**Comment by ES-Six** [comment]
test

**Comment by soyuka** [comment]
When the search filter doesn't work your way please do your own filter as it's quite hard to support all the cases. Feel free to propose a patch if you have one I think your case is quite valid. We're in the process of improving the filters with `QueryParameter`, there you can add `constraints` and you'll never reach the filter if the value is the wrong type. Note that currently every parameters are `strings` so you need some kind of `is_numeric` constraint to valid your entry.

**Comment by ES-Six** [comment]
Ok, I take note of that.
