### ISSUE TITLE
[Laravel] Collection relations are not working correctly

### ISSUE THREAD

**Issue by amermchaudhary** [api-platform/core#6791]
**API Platform version(s) affected**: 4.*

**Description**  
All collection relations return all records instead of related records

**How to reproduce**  
Lets say I want to get a list of all my companies and the users related to those companies

1. Create two related models (ex: company and user)
2. Create a HasMany relation from first model to second model (company has many users)
3. Try to query all companies with their users
```
query companies {
  companies {
    edges {
      node {
        id
        name
        users {
          edges {
            node{
              id
            }
          }
        }
      }
    }
  }
}
```
4. The returned users will be from all companies instead of the related company

**Comment by toitzi** [comment]
Yes relates to this issue (https://github.com/api-platform/api-platform/discussions/2795).

Fix is in progress:
https://github.com/api-platform/core/pull/6792
