### ISSUE TITLE
PHPStan PHPDocParser missing constructor attribute

### ISSUE THREAD

**Issue by dbotezat** [api-platform/core#6795]
**API Platform version(s) affected**: 4.0.8

**Description**  

 [critical] Uncaught Error: Too few arguments to function PHPStan\PhpDocParser\Parser\ConstExprParser::__construct(), 0 passed in /DriversCheck/dev/projects/beed-backend/vendor/api-platform/core/src/Metadata/Resource/Factory/PhpDocResourceMetadataCollectionFactory.php on line 62 and exactly 1 expected

currently using phptan v1.12

**How to reproduce**  

create new ymfony project usinc smyfony cli
add api platform via composer

**Possible Solution**  

repalce with
$phpDocParser = new PhpDocParser(new ParserConfig(),new TypeParser(new ConstExprParser()), new  ConstExprParser());
**Additional Context**  

Error screenshot
![image](https://github.com/user-attachments/assets/886657e4-61ac-4ae2-922d-87e9140bb225)

Composer requirements screenshot
![image](https://github.com/user-attachments/assets/9c768faf-0e42-4dea-abba-07eb76d8ed1e)

**Comment by dbotezat** [comment]
this fixed the issue

if (class_exists(PhpDocParser::class)) {
            $config = new ParserConfig([]);
            $phpDocParser = new PhpDocParser($config,new TypeParser($config,new ConstExprParser($config)), new
            ConstExprParser($config));
            $lexer = new Lexer($config);
        }

**Comment by soyuka** [comment]
it's going to be fixed by https://github.com/api-platform/core/pull/6789
