### ISSUE TITLE
Using hashmaps produces invalid openapi schema

### ISSUE THREAD

**Issue by ostrolucky** [api-platform/core#6800]
**API Platform version(s) affected**: 4.0.9

**Description**  

**How to reproduce**  
```php
#[ApiResource]
class Test {
    /** @var array<string, Foo> */
    public array $foos;
}

class Foo {
    public string $bar;
}
```

above produces schema like so
```json
"Test": {
  "type": "object",
  "description": "",
  "deprecated": false,
  "properties": {
    "foos": {
      "type": "object",
      "additionalProperties": {
        "type": "unknown_type"
      }
    }
  }
},
```

since "unknown_type" isn't actually recognized by OpenAPI, **openapi schema validators will reject this kind of schema**.

Instead, I would expect it generates schema like so
```json
"Test": {
  "type": "object",
  "description": "",
  "deprecated": false,
  "properties": {
    "foos": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {"bar": {"type": "string"}}
      }
    }
  }
},
```

**Possible Solution**  

**Additional Context**

**Comment by vinceAmstoutz** [comment]
@ostrolucky  Have you tried with `Foo[]` or `array<Foo>`?

**Comment by ostrolucky** [comment]
That's not accurate though, for us it's really a hashmap like so
```
{
  "foos": { 
    "randomProp123" : "string",
    "randomProp321" : "string",
  }
}
```

hence needs to be reflected in php docblocks and openapi docs as such. Especially openapi docs because they are consumed by FE devs and for them it makes a big difference treating the prop as object or array.

In places where we don't use hashmap but list, that's documented as `list<Foo>` and generated openapi docs is correct, hence this issue is only about hashmaps.

**Comment by ostrolucky** [comment]
I have both packages installed. To me it seems issue is that $keyType is not passed to `getType`

![image](https://github.com/user-attachments/assets/1f313c05-ac1d-41a5-83f1-ce265594700c)
----
![image](https://github.com/user-attachments/assets/16b779d0-37cd-4756-9b5b-9a5fc82800af)

**Comment by soyuka** [comment]
Thanks for the details @ostrolucky !
