### ISSUE TITLE
[Laravel] Boolean Cast is not working with GraphQL

### ISSUE THREAD

**Issue by amermchaudhary** [api-platform/core#6807]
**API Platform version(s) affected**: 4.*

**Description**  
Adding a boolean cast doesn't work correctly with GraphQL as it requires String! type

**How to reproduce**  
```
    protected $casts = [
        'id' => 'integer',
        'is_active' => 'boolean',
    ];
```

**Comment by toitzi** [comment]
@amermchaudhary can be closed i think, fixed with [4.0.10 release](https://github.com/api-platform/core/releases/tag/v4.0.10), let me know if this still needs fixing, i have time to investigate and pr if necessary
