### ISSUE TITLE
Custom dto output return tons of @context 

### ISSUE THREAD

**Issue by HrjSnz** [api-platform/core#6810]
**API Platform version(s) affected**: 4.0.7 +

**Description**  
With custom resource and use parameter "output" for custom dto return in response full "@ context" . In version 4.0.6 and below not.
If not use "output" everything works fine.

**How to reproduce**  
Just make custom output DTO.

**Possible Solution**  
Is this bug ? I couldn't find any mention of this in the changes. 

**Additional Context**  
custom api resource
<img width="397" alt="image" src="https://github.com/user-attachments/assets/428f579c-9e6c-42cf-9df8-94733305e960">

in response tons of "@ context" (around 1k lines)
<img width="624" alt="image" src="https://github.com/user-attachments/assets/85eadf54-357a-4eb9-8f90-20f8795f3218">

**Comment by soyuka** [comment]
mark your DTO as an API Resource to avoid that, I'll check if we can do something.

**Comment by HrjSnz** [comment]
Hi, thanks for tip, but does not work for me. Still getting around 1k lines context. Updated and tested on 4.0.9. Tried add #[ApiResource] to all related DTOs and still not work.

<img width="705" alt="image" src="https://github.com/user-attachments/assets/ecb152a7-a42f-455e-ac04-792235e50921">

**Comment by Gist-race** [comment]
I encountered a similar issue, and I managed to resolve it by adding the _#[ApiPlatform\Metadata\ApiResource]_ attribute to my DTO and registering it in the _api_platform.yaml_ configuration file under the mapping section. After making these changes, everything worked as expected.

**Comment by HrjSnz** [comment]
Wow, thanks. It works. I configured `mapping` and `resource_class_directories` and it works. But it's interesting, it wasn't needed before. Nowhere in the changes is there any mention of this necessary configuration. Until 4.0.6 everything was fine. Anyway, thank you

**Comment by HrjSnz** [comment]
@soyuka @Gist-race so.. i just tested it again and i mentioned context is correct but now documentation is not correct. DTO is now as resource in doc which is wrong. For fix it need write `#[ApiResource(
    operations: []
)]` . This is to much writing for fix context response. Something must have changed in 4.0.7 that affects this

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/45a23db6-72aa-4b80-9145-3de3283c83ef">

**Comment by HrjSnz** [comment]
@soyuka Hello, i am sorry lack of time. I wl try it tomorrow. Just what i see in your test you use ```
GetCollection()
``` but my problem is with output on ```
Post()
```

I will try it tomorrow and provide more information. Thanks

**Comment by HrjSnz** [comment]
@soyuka Hello, i think i found problem. And  i think it started in 4.0.0 . Reason why test is without error is in 

https://github.com/api-platform/core/blob/main/tests/Fixtures/app/AppKernel.php#L278
There is default value ```true```
https://github.com/api-platform/core/blob/de3bed269838556d46899e78ed5603b7e6229e8b/tests/Fixtures/app/AppKernel.php#L277-L279

In 
https://github.com/api-platform/core/blob/de3bed269838556d46899e78ed5603b7e6229e8b/src/Symfony/Bundle/DependencyInjection/Configuration.php#L145-L150 is as default value ```false```

_So all test run with ``` 'hydra_prefix' => true``` but default configuration bundle is   ```'hydra_prefix' => false```._

Place where is wrong set context is here https://github.com/api-platform/core/blob/de3bed269838556d46899e78ed5603b7e6229e8b/src/JsonLd/ContextBuilder.php#L187-L189
There in _test_  in ```$this->defaultContext[self::HYDRA_CONTEXT_HAS_PREFIX]``` is ```true``` but in app is default ```false``` so result is opposite in real app instead in test.

another indicator is api_platform.yaml. In my api_platform.yaml if let it default so getting this wrong context. If i use 
```
api_platform:
    serializer:
        hydra_prefix: true
```
so problem gone and it return correct context

**Comment by SherinBloemendaal** [comment]
> @soyuka @Gist-race so.. i just tested it again and i mentioned context is correct but now documentation is not correct. DTO is now as resource in doc which is wrong. For fix it need write `#[ApiResource( operations: [] )]` . This is to much writing for fix context response. Something must have changed in 4.0.7 that affects this
> 
> <img alt="image" width="1507" src="https://private-user-images.githubusercontent.com/81477556/390865632-45a23db6-72aa-4b80-9145-3de3283c83ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDI5MDQsIm5iZiI6MTczMzkwMjYwNCwicGF0aCI6Ii84MTQ3NzU1Ni8zOTA4NjU2MzItNDVhMjNkYjYtNzJhYS00YjgwLTkxNDUtM2RlMzI4M2M4M2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA3MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MWI1OTM2MzhkYjY5ODk2NGViZTZmYWExOTc0MDBmODdjYTE1ODhiYjFjNzJkODgzMzEyZmYxZDE5MDNiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BOQjJSf1znyNnEuscwmvKvDJ5V7twJF_zw-hKwBTlHM">

I also ran in to the same issue. What I usually do is instead of marking it as an complete `#[ApiResource]`I use a single `#[Get]` attribute:
`#[Get(controller: NotFoundAction::class, openapi: false, output: false, read: false)]`

**Comment by HrjSnz** [comment]
@SherinBloemendaal  yes, but before it works without it. And write additional endpoint and close it is in my opinion bad practice. As i mentioned above, i probably found the error, but then no one responds to it. Problem is not context itself but if statement which is called wrong.

**Comment by soyuka** [comment]
I managed to reproduce I'm looking into this.
