### ISSUE TITLE
[Laravel] BelongToMany does not work

### ISSUE THREAD

**Issue by amermchaudhary** [api-platform/core#6817]
**API Platform version(s) affected**: 4.*

**Description**  
BelongsToMany relations do not work because getQualifiedForeignKeyName is not used in BelongsToMany relation

**How to reproduce**  
Add a BelongsToMany relation

**Possible Solution**  
use getQualifiedForeignPivotKeyName instead of getQualifiedForeignKeyName for belongsToMany relations

**Comment by toitzi** [comment]
@amermchaudhary can be closed i think, fixed with [latest 4.0.11 release](https://github.com/api-platform/core/releases/tag/v4.0.11), let me know if this still needs fixing, i have time to investigate and pr if necessary
