### ISSUE TITLE
`keep_legacy_inflector` configuration removed from v4.0 but still the default behavior in the new Inflector

### ISSUE THREAD

**Issue by AirBair** [api-platform/core#6828]
**API Platform version(s) affected**: 4.0.10

**Description**  

After upgrading to Api-Platform 4 which remove the deprecated `keep_legacy_inflector` configuration, the legacy inflector is used again by default in the new Inflector service:

https://github.com/api-platform/core/blob/main/src/Metadata/Util/Inflector.php
```
namespace ApiPlatform\Metadata\Util;
// ...
final class Inflector implements InflectorInterface
{
    public function __construct(private bool $keepLegacyInflector = true)
    {
    }
    // ...
}
```

**How to reproduce**  

Since there are differences between Doctrine Inflector and Symfony Inflector, it changes some urls after upgrading.

For example, matrix:
- matrices given by Doctrine inflector
- matrixes given by Symfony inflector

**Possible Solution** 

Change this default value to false to smooth the upgrade, but not sure of the side effects if not possible to use the legacy inflector, see #6023 

**Additional Context**

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/6447 fixes this imo

**Comment by AirBair** [comment]
Indeed ! But is it the wanted behavior to use the legacy Inflector by default on v4 ?

**Comment by soyuka** [comment]
yeah we should probably just remove or change the name at some point as both inflector are quite valid and changing breaks too much stuff

**Comment by AlexanderKopyl** [comment]
Still presented \ApiPlatform\Symfony\Bundle\DependencyInjection\ApiPlatformExtension::registerInflectorConfiguration

    private function registerInflectorConfiguration(array $config): void
    {
        if ($config['keep_legacy_inflector']) {
            Inflector::keepLegacyInflector(true);
            trigger_deprecation('api-platform/core', '3.2', 'Using doctrine/inflector is deprecated since API Platform 3.2 and will be removed in API Platform 4. Use symfony/string instead. Run "composer require symfony/string" and set "keep_legacy_inflector" to false in config.');
        } else {
            Inflector::keepLegacyInflector(false);
        }
    }
