### ISSUE TITLE
Configuration to switch off Hydra markup

### ISSUE THREAD

**Issue by jkabat** [api-platform/core#6836]
Recently I have upgraded to v4.0 and all my tests are broken - json-ld @context is bloated by Hydra prefixes. Is possible to turn it off so I have it clean like it was in v3.0?

Several config tries with the value of "hydra_prefix" false are not working as expected and by reading the code it should also be the default. Id like to have my API for schema.org markup as minimal as possible. Any suggestions?

**Comment by jkabat** [comment]
After more debugging I was able to find a way by setting hydra_prefix to "TRUE"!!! Kind of ilogical...
Is it what you had in mind? Or it is a bug? Because it is not documented and it is a major change since v3.*

```yaml
api_platform:
    serializer:
        hydra_prefix: true
```

**Comment by dunglas** [comment]
Hi,

This is intended and documented: https://api-platform.com/docs/core/upgrade-guide/#api-platform-34

The `hydra:` prefix has been removed to align with the updated best practices of the specification.

**Comment by jkabat** [comment]
Actually it is not yet removed and I'm glad is there and could be disabled (by strange setting "true").
