### ISSUE TITLE
[Laravel] Global Resources Defaults for "order" has no effect 

### ISSUE THREAD

**Issue by cay89** [api-platform/core#6839]
**API Platform version(s) affected**: 4.0.10

**Description** 
If I set the Global Resource Defaults for ordering in the config as shown in the [documentation](https://api-platform.com/docs/core/configuration/#global-resources-defaults-for-laravel), it has no effect.

![image](https://github.com/user-attachments/assets/a77358d1-0b8a-453c-a80a-e31998396a2c)

I also don't see this parameter being used anywhere in the code.

**Comment by cay89** [comment]
Maybe the "order" setting isn't working at all? It still returns me the same thing:

![image](https://github.com/user-attachments/assets/9937d246-aa96-4de8-8246-b1a3fbaca203)

**Comment by toitzi** [comment]
Can confirm this is happening. I will look into it and open a PR
