### ISSUE TITLE
Empty resource description

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#686]
If there's a `@see` tag with URI (such as the default generated by `api-platform/schema-generator`), `ResourceMetadata::$description` ends up being null.

This is due to phpDocumentor/ReflectionDocBlock#78 causing `InvalidArgumentException` to be thrown.

**Comment by dunglas** [comment]
Should be fixed in ReflectionDocBlock directly. We should keep this issue open to track the advancement.

**Comment by Simperfit** [comment]
It has been fixed by @Seldaek

**Comment by teohhanhui** [comment]
Will be fixed by phpDocumentor/ReflectionDocBlock#88
