### ISSUE TITLE
Use an iterator tools library like nikic/iter

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#687]
PHP's built-in functions (e.g. `array_*`) suck. What do you think about using `nikic/iter`? It's not very full-featured, but it is well tested and it's by one of the PHP guys.

For reference, Drupal has this discussion here: https://www.drupal.org/node/2757489

**Comment by dunglas** [comment]
Why not at some point but it's too early now. We need some feedback about such libraries. It also make contributions harder (people need to know this library).

**Comment by Simperfit** [comment]
@dunglas do we want to use this ? if not can we close this ?

**Comment by dunglas** [comment]
Closing for now
