### ISSUE TITLE
Added custom action for POST and GET in services, does not work!

### ISSUE THREAD

**Issue by BerislavSapina** [api-platform/core#692]
Hi,

I am working with symfony2.8 and dunglas bundle.

This is my services.yml:

services:
#   API
    resource.member:
        parent: "api.resource"
        arguments:  [ "AppBundle\\Entity\\User" ]
        calls:
            - method:    "initNormalizationContext"
              arguments: [ { groups: [ "member_norm" ] } ]
            - method:    "initDenormalizationContext"
              arguments: [ { groups: [ "member_denorm" ] } ]
            - method:    "initCollectionOperations"
              arguments:
                -
                  - "@resource.member.collection_operation.post"
                  - "@resource.member.collection_operation.get"
            -      [ initShortName, [ Member ] ]
        tags:       [ { name: "api.resource" }]

    resource.member.collection_operation.post:
        public: false
        class: "Dunglas\ApiBundle\Api\Operation\Operation"
        factory: [ "@api.operation_factory", "createCollectionOperation"]
        arguments: [ "@resource.member", "POST", null , "AppBundle:Member:cpost"]
        lazy: true
    resource.member.collection_operation.get:
        public: false
        class: "Dunglas\ApiBundle\Api\Operation\Operation"
        factory: [ "@api.operation_factory", "createCollectionOperation"]
        arguments: [ "@resource.member", "GET", null, "AppBundle:Member:cget"]
        lazy: true
************************************++
First it initalize post service, then when initialize get service it delete post, and then i don't have post service, niether route in nelmio api doc.

I tried to add custom route, won't work. Try clear cache, won't work!
Please help!

Thank you!

**Comment by BerislavSapina** [comment]
I solved it! Only thing i needed to add is in arguments. Fifth argument is route name! I defined that for every operation and that is it! So the working code look like this:

***
           - method:    "initCollectionOperations"
              arguments:
                -
                  - "@resource.member.collection_operation.get"
                  - "@resource.member.collection_operation.post"
            -      [ initShortName, [ Member ] ]
        tags:       [ { name: "api.resource" }]

    resource.member.collection_operation.post:
        public: false
        class: "Dunglas\ApiBundle\Api\Operation\Operation"
        factory: [ "@api.operation_factory", "createCollectionOperation"]
        arguments: [ "@resource.member", "POST",null, "AppBundle:Member:cpost","api_member_post"]
        lazy: true
    resource.member.collection_operation.get:
        public: false
        class: "Dunglas\ApiBundle\Api\Operation\Operation"
        factory: [ "@api.operation_factory", "createCollectionOperation"]
        arguments: [ "@resource.member", "GET", null, "AppBundle:Member:cget","api_member_get"]
        lazy: true

**Comment by teohhanhui** [comment]
I'd recommend using API Platform 2.0
