### ISSUE TITLE
[Coverage] How can this line return `null`?

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#711]
Was looking at the coverage, and [this looks weird](https://coveralls.io/builds/7646813/source?filename=src%2FBridge%2FSymfony%2FPropertyInfo%2FMetadata%2FProperty%2FPropertyInfoPropertyNameCollectionFactory.php#L42)

Especially that the `PropertyInfoExtractor` doesn't return anything if it's null [see here](https://github.com/symfony/property-info/blob/2.8/PropertyInfoExtractor.php#L118). May we drop the line instead? Or maybe did I missed something.

**Comment by dunglas** [comment]
This method can return `null`: https://github.com/symfony/property-info/blob/2.8/PropertyListExtractorInterface.php#L29

It is the case when no extractor is registered or support the given property. (returning nothing in PHP < 3.1 is the same thing than returning null).

**Comment by soyuka** [comment]
Hmm okay, But if it's not registered will the class still run?

**Comment by soyuka** [comment]
Thanks didn't knew about the not returning is null
