### ISSUE TITLE
Path generated in the Swagger doc don't take into account `app_dev.php`

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#722]
Steps to reproduce:

1. Install API Platform using Docker
2. Download `http://localhost/app_dev.php/doc.json`

The Swagger document should include `app_dev.php` paths, it doesn't.
So, when using Swagger UI in dev mode, requests are sent in prod mode.

cc @Simperfit

**Comment by Simperfit** [comment]
@dunglas I've checked this issue and I can't reproduce it (with last api-platform/api-platform)

here is my view with a dummy entity : 
<img width="976" alt="capture d ecran 2016-09-03 a 17 46 59" src="https://cloud.githubusercontent.com/assets/3451634/18225874/99786774-71fe-11e6-8dc6-cccd989772aa.png">

**Comment by dunglas** [comment]
I just checked with @Simperfit and we confirm this bug impact `dev-master` (but not the last beta).

This bug has probably been introduced in #666 (cc @Ener-Getick).

**Comment by Ener-Getick** [comment]
This should be fixed using base_path i guess, i'll try to do that tonight.
