### ISSUE TITLE
Concat filters

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#745]
[This](https://github.com/api-platform/core/commit/e4eca423d32720bc0cba3fd9a0e47675c1fa21c1#diff-77ec54980605d6062780fcd93ba31c64R192) introduced a bug on Oracle as `CONCAT` only accepts 2 arguments. @teohhanhui any reason you prefered concat over the default `LIKE` string? Also, the DQL documentation [only refers two parameters](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#dql-functions) in the `CONCAT` method (this can't be fixed on the Doctrine side IMO).

Sorry I didn't noticed this sooner.

I can work on a fix tomorrow, just by removing `CONCAT`s where there are more than 2 arguments.

**Comment by teohhanhui** [comment]
@soyuka It should work...

https://github.com/doctrine/dbal/blob/a3577e49dc3897410f0059b701f5bccbbc646407/tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php#L95-L99

**Comment by teohhanhui** [comment]
Also, DQL `CONCAT` supports variadic arguments: https://github.com/doctrine/doctrine2/blob/cd11723e6310b5973f50e7d9819c58916721d290/lib/Doctrine/ORM/Query/AST/Functions/ConcatFunction.php

**Comment by soyuka** [comment]
Weird, it's not translating to `||` in my query. But indeed, I tried manually with `'%' || :bindparam || '%'` and it works. I'm investigating asap.
