### ISSUE TITLE
[Question] filters are not working after core update.

### ISSUE THREAD

**Issue by aledeg** [api-platform/core#757]
I made a core update today and my filters are not working anymore.
I fixed my filters to match the new method signature to fix my unit tests.
But then I ran my behat tests and I got 500 errors with the following message:

> Notice: Undefined index: type in vendor/api-platform/core/src/Swagger/Serializer/DocumentationNormalizer.php line 540 (500 Internal Server Error)

I don't know what to do with that error. I've check that class, but I do not understand what I should provide to make it work.
I am surprised that this class is used at all since I do not use Swagger. It might be related to the Swagger style auto-generated documentation with nelmio bundle.

Any help would be appreciated!

**Comment by teohhanhui** [comment]
Please refer to https://github.com/api-platform/core/blob/f9c2cc992ecec39d6f84b7f1bd83929bac236336/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L71 to see what you should return from `ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\FilterInterface::getDescription`.

(You're missing the `type` key.)

**Comment by teohhanhui** [comment]
> I am surprised that this class is used at all since I do not use Swagger.

Are you sure? :smile:

**Comment by aledeg** [comment]
> (You're missing the type key.)

You're right! I've tried that before without success. Probably a cache problem. It's fixed now.

>> I am surprised that this class is used at all since I do not use Swagger.

> Are you sure? :smile:

> Oh yeah, Swagger UI is currently set up to intercept all HTML requests. So if you're loading from the browser you can do /products.jsonld?myfilterkey=value for example.

I was until... I figured I can do what you suggested by adding the format I wanted. In my case, I support only ld+json so I disabled all formats except this one.
