### ISSUE TITLE
[Swagger] Question on using swagger-codegen with JSON+LD

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#760]
When using [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to generate the API SDK, it will default to using `application/json`. The client works, but accessing the API with `Accept: application/json` will not expose metadata such as:

    "hydra:totalItems": 275,
    "hydra:view": {
        "@id": "/api/example?page=1",
        "@type": "hydra:PartialCollectionView",
        "hydra:first": "/api/example?page=1",
        "hydra:last": "/api/example?page=10",
        "hydra:next": "/api/example?page=2"
    }

available with `Accept: application/ld+json`. This makes the client much less usable as we can't, for example, create a client-side pagination.

Is there a way to somehow combine using JSON-LD with the Swagger code generator? It's quite attractive to have compatibility with it as it's capable of producing SDKs in plenty of languages out of the box. I've looked for similar Hydra-based tools and found none. Maybe the Swagger definition could be tweaked to point to JSON-LD variation?

Thanks.

**Comment by dunglas** [comment]
Can't you edit the generated code to change the MIME Type sent in the `Accept` header? It would be nice to add the ability to use custom mime type in Swagger gen (maybe this possibility already exists?).

I don't see what we can do on the API Platform for this issue, it need to be handled in swagger-codegen directly.

**Comment by dkarlovi** [comment]
@dunglas thanks for the reply.

My idea here is to somehow tweak the Swagger definition to fit JSON+LD consumption. For example, the code which codegen emits looks like this:

        if (count($content_type) === 0 or (count($content_type) === 1 and $content_type[0] === '')) {
            return 'application/json';
        } elseif (preg_grep("/application\/json/i", $content_type)) {
            return 'application/json';
        } else {
            return implode(',', $content_type);
        }

It means, if it sees `application/json` in `produces`, it will use it. I can of course edit the SDK generated and make it much better, but that means I cannot just regenerate later. The project I'm working on will probably require integration between the two (API-Platform, swagger-codegen) so I expect to contribute there and here.

I asked here in case I was missing something obvious, it was a long shot. :) Thanks.

**Comment by dunglas** [comment]
Maybe that the regex (and the corresponding MIME type to use) can be changed to`/application\/.+\+json/`, this way it will also support JSON-LD and HAL for instance.

**Comment by dkarlovi** [comment]
I'll need to look into it more. Might have to drop the Swagger route, though.

**Comment by teohhanhui** [comment]
Yes, this should be solved in swagger-codegen.

**Comment by dkarlovi** [comment]
@teohhanhui there's nothing to fix at their side: they support Swagger, not Hydra. API Platform exposes certain aspects (total number of items, for example) in Hydra only, not in Swagger. That's the actual issue, IMO.

**Comment by teohhanhui** [comment]
No, it's a problem that the only support the `application/json` MIME type, when in fact it should support (standard) extensions to that too.

This has nothing to do with API Platform. Our content negotiation is doing the right thing.

**Comment by dkarlovi** [comment]
OK, how do I access the equivalent of `hydra:totalItems` in `application/json` context?

**Comment by teohhanhui** [comment]
If you want JSON-LD / Hydra, then send the correct header:
`Accept: application/ld+json`

Some things to ponder about:

* https://github.com/geo4web-testbed/topic3/wiki/Content-negotiation
* https://lists.w3.org/Archives/Public/public-hydra/2014Aug/0045.html

**Comment by dkarlovi** [comment]
@teohhanhui I can't be in the `application/json` context and `application/ld+json` context at the same time. :)

To avoid all confusion and misunderstandings, here it is again, reworded: how do I get access to the number of pages in the pagination when in `application/json`?

**Comment by teohhanhui** [comment]
You can't, simply because it's not hypermedia and we do not have anywhere
to put such information. If you want such information, request for a
hypermedia type :smile:

**Comment by dkarlovi** [comment]
@teohhanhui fair enough. :)

But how about putting it in response headers, say `X-Pagination-TotalItems: X`? [Swagger2 supports specifying additional metadata in headers](http://swagger.io/specification/#headersObject), like so

    description: A simple string response
    schema:
      type: string
    headers:
      X-Rate-Limit-Limit:
        description: The number of allowed requests in the current period
        type: integer
      X-Rate-Limit-Remaining:
        description: The number of remaining requests in the current period
        type: integer
      X-Rate-Limit-Reset:
        description: The number of seconds left in the current period
        type: integer

**Comment by dunglas** [comment]
@dkarlovi the question is: why creating a new proprietary hypermedia format for while we already support JSON-LD and HAL (both open standards).

**Comment by dkarlovi** [comment]
@dunglas great point, had no idea you supported HAL, need to check the docs obviously. Thanks.

**Comment by dkarlovi** [comment]
If anybody else goes searching for it, HAL is available, but not mentioned in the docs and not enabled by default, you need to add it to `formats` config, like so:

    api_platform:
        # ...
        formats:
            html:
            - text/html
            json:
            - application/json
            jsonhal:
            - application/hal+json
            jsonld:
            - application/ld+json

@dunglas thanks for the hint.

**Comment by dunglas** [comment]
We indeed need to update the doc (https://github.com/api-platform/docs/blob/master/core/content-negotiation.md). @dkarlovi do you think that you can do it?

**Comment by dkarlovi** [comment]
Not in the near future, sorry.
