### ISSUE TITLE
[Swagger] emit "host" field in Swagger definition

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#761]
As the platform emits `basePath: /api` in Swagger definition, so it should also emit the current host in `host`, [as specified](http://swagger.io/specification/) (sorry, no anchors to link directly to page section).

> The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.

Example:

```
host: my.example.com
basePath: /api
```

Using [swagger-codegen](https://github.com/swagger-api/swagger-codegen), it will generate the client to automatically connect to `https://<host><basePath>` which is a reasonable default, can be overridden) and will default to `localhost` if not specified, in which case you MUST override each time.

**Comment by dunglas** [comment]
Can you open a PR?

**Comment by dkarlovi** [comment]
@dunglas yes, will try to do it today.

**Comment by dunglas** [comment]
Thanks!

**Comment by SalvatorePollaci** [comment]
Hi, any update on this issue?
Thanks

**Comment by Simperfit** [comment]
@meyerbaptiste Is this fixed with the PR you've made ?

**Comment by meyerbaptiste** [comment]
Nop, there is a dedicated PR for this issue: https://github.com/api-platform/core/issues/765

**Comment by dkarlovi** [comment]
Sadly, it's probably not going to happen as it required quite a bit of underlying work which wasn't there (at the time) and I wan't knowledgeable on API Platform to do it on my own, sorry.

**Comment by soyuka** [comment]
This is definitely possible today.
