### ISSUE TITLE
[Swagger] More complete info metadata

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#762]
Currently in Swagger definition you support `info.title`, `info.description` and `info.version`.

Please consider providing support for the complete [Info object](http://swagger.io/specification/#infoObject), which includes `info.termsOfService`, `info.contact` and `info.license`, the latter two get embedded into generated code as **Author** and **License**.

**Comment by dunglas** [comment]
You can decorate the doc generator to add more field if you need to.

**Comment by dkarlovi** [comment]
@dunglas so you don't feel the Platform itself should support this better?

**Comment by dkarlovi** [comment]
I'm having trouble decorating the doc generator as the `api_platform.swagger.action.ui` has a hardcoded class, as does `api_platform.swagger.normalizer.documentation`.

Also, all classes to override / extend are final so can't do it that way either. Is there a recommended way?

**Comment by dunglas** [comment]
Use Symfony service decoration: http://symfony.com/doc/current/service_container/service_decoration.html

**Comment by dkarlovi** [comment]
Did not know about `decorates`, thanks!

**Comment by dkarlovi** [comment]
BTW this worked like this, if anybody tries to find it:

    # app/config/services.yml
    services:
        app.swagger.normalizer.documentation:
            class:     AppBundle\Swagger\Normalizer\DocumentationNormalizer
            decorates: api_platform.swagger.normalizer.documentation
            arguments:
            - '@app.swagger.normalizer.documentation.inner'
            - '@router.request_context'
            public:    false

@dunglas this worked for the controller, but not for the command: `Type error: Argument 1 passed to ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand::__construct() must be an instance of ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer, instance of AppBundle\Swagger\Normalizer\DocumentationNormalizer given`.

Do I override the command too? Or is the fact that the command is not typehinted to an interface a bug here?

Thanks for all the answers, BTW.

**Comment by dkarlovi** [comment]
@dunglas I tried to

1) just decorate the command, but still
`Argument 1 passed to ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand::__construct() must be an instance of ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer, instance of AppBundle\Swagger\Normalizer\DocumentationNormalizer given`

2) remove the original definition in the compiler pass
`You have requested a non-existent service "api_platform.swagger.command.swagger_command".`

3) remove my decorator, but keep the original service removed
`Unable to autowire argument of type "ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand" for the service "appbundle\command\swaggercommand". No services were found matching this class and it cannot be auto-registered.`

So I'd say there's no way to decorate the Swagger definition without editing API Platform files.

**Comment by dkarlovi** [comment]
I ended up just NO-OP-ing the service as it seems it cannot be decorated currently:

    # app/config/services.yml
    services:
        api_platform.swagger.command.swagger_command:
            class: StdClass

**Comment by teohhanhui** [comment]
@dkarlovi

> Argument 1 passed to ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand::__construct() must be an instance of ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer, instance of AppBundle\Swagger\Normalizer\DocumentationNormalizer given

You were missing a use statement.

**Comment by desmax** [comment]
Its insanely inefficient to decorate Normalizer in my case instead of extending it.
Even if I could extend it - you have all methods marked as private there. Whats the point of this restriction? 
I just wanted to add description generation for custom PATCH methods and its turns out I basically have to duplicate whole DocumentationNormalizer in my project.

**Comment by Simperfit** [comment]
@dkarlovi Do you think we need to do something for this to work ?

The swagger accept a NormalizerInterface, so it seems that's no more an issue. feel free to ping if it's still one.
