### ISSUE TITLE
Notice: Undefined index: subType

### ISSUE THREAD

**Issue by dagrinchi** [api-platform/core#763]
Notice: Undefined index: subType
in vendor/dunglas/api-bundle/src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php at line 220

**Comment by teohhanhui** [comment]
Which version are you using? 1.1?

**Comment by dagrinchi** [comment]
Hello, 

First, I installed from here:

`composer require dunglas/api-bundle:dev-master`

Then, I removed and install again from:

`composer require api-platform/core:v2.0.0-rc.1`

And problem solved 👍 

Thanks for your reply!

**Comment by tacman** [comment]
I'm getting this as well now, I think the issue may be that api-platform/core is on RC6 and api-bundle is a few versions back.

**Comment by dunglas** [comment]
You should use api-platform/core or dunglas/api-bundle but not both.
