### ISSUE TITLE
Extend usage of name converter

### ISSUE THREAD

**Issue by jderusse** [api-platform/core#78]
Actualy name converter is used in (de)normalization of the object. 
But it should also be used in several locations:
- In violation's propertyPath

```
"violations": [
        {
            "message": "This value should not be blank.", 
            "propertyPath": "content" <== here
        }
    ]
```
- In filters => `http://localhost:8000/api/offers?price=10` price should be denormalized
- or in `/offers?order[name]=desc&order[id]=asc`.

**Comment by dunglas** [comment]
Also in `EntrypointBuilder` and in `ApiDocumentationBuilder`.

**Comment by Simperfit** [comment]
What is this about ? Is it still relevant ?

**Comment by dunglas** [comment]
It has been partially fixed by @meyerbaptiste in #770 but I think there are still some places to cover like property paths and filters.

**Comment by aistis-** [comment]
The issue still persist in v2.0.3

I use config:

```
api_platform:
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```

**Comment by Simperfit** [comment]
This has been fixed by @meyerbaptiste
