### ISSUE TITLE
Allow empty body for POST and PUT requests

### ISSUE THREAD

**Issue by kbsali** [api-platform/core#781]
Right now it is not possible to POST or PUT requests without specifying at least an empty object.
While this is correct for most of the use case, we've had to add a listener to bypass this for new PUT entry points we are creating which "carries" the change to be applied to our object.
     eg. PUT /api/blog_posts/[id]/publish

Here is a "serious" source showing that this is perfectly fine : http://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0276.html :)

Do you agree? If you do, I will try to submit a PR asap, otherwise i'll live with our custom listener...

**Comment by teohhanhui** [comment]
I think your solution is fine because we're talking about custom operations anyway.

Yes, I myself have run into this problem too when I implemented a `copyOf` filter to clone a resource (sending empty body).

**Comment by teohhanhui** [comment]
But it'd be good if we can take care of this automatically.

**Comment by kbsali** [comment]
@teohhanhui so do you think a PR would be acceptable for this? :)

**Comment by teohhanhui** [comment]
Yes please.

**Comment by teohhanhui** [comment]
Just adding a check here should do: https://github.com/api-platform/core/blob/f1a6537f99120bcecd41b722fd0743f39f17b30f/src/EventListener/DeserializeListener.php#L66-L71

**Comment by kbsali** [comment]
closing as this has been apparently discarded!
too bad... i don't understand why it was ok to do this to start with, and once a PR was submitted, it was discarded. :-(

**Comment by dunglas** [comment]
@kbsali I'm still ok to merge it, we just need to finish it.

**Comment by teohhanhui** [comment]
I suggest decorating the listener, like https://github.com/api-platform/docs/blob/e698aef1b147e94190dc189471b1c4b093545856/core/form-data.md
