### ISSUE TITLE
[DateTime normalizer] avoid 00:00:00 when doctrine type is date (without time)

### ISSUE THREAD

**Issue by karser** [api-platform/core#784]
Doctrine has date / datetime / datetimetz types which ideally should be rendered as 2016-09-30 / 2016-09-30T00:00:00 and 2016-09-30T00:00:00+00:00 correspondingly.

I was thinking about custom SerializeListener which checks for the date types from doctrine metadata. Is there a better solution? Probably it should be date normalizer.

Example:
```
class User {
    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    private $customDate;
//id, username, email, etc
}
```

the output would be
```
{
  "id": 33,
  "customDate": "2016-09-30T00:00:00+00:00", 
  "username": "mm1",
  "email": "mm@gmail.com",
}
```

**Comment by soyuka** [comment]
#482
