### ISSUE TITLE
[Question] Allow header

### ISSUE THREAD

**Issue by polc** [api-platform/core#786]
Not sure but shouldn't Api Platform add an `Allow` header by default (`Allow: GET,POST` for example) ?

I can't find a way to make my client auto consuming the API (using JSON-LD).

**Comment by soyuka** [comment]
I don't see how this brings anything valuable:

>       The Allow entity-header field lists the set of methods supported
      by the resource identified by the Request-URI. The purpose of this
      field is strictly to inform the recipient of valid methods
      associated with the resource. An Allow header field MUST be
      present in a 405 (Method Not Allowed) response.
          Allow   = "Allow" ":" #Method
      Example of use:
          Allow: GET, HEAD, PUT
      **This field cannot prevent a client from trying other methods.**
      However, the indications given by the Allow header field value
      SHOULD be followed. The actual set of allowed methods is defined
      by the origin server at the time of each request.
      The Allow header field MAY be provided with a PUT request to
      recommend the methods to be supported by the new or modified
      resource. **The server is not required to support these methods and
      SHOULD include an Allow header in the response giving the actual
      supported methods.**
      A proxy MUST NOT modify the Allow header field even if it does not
      understand all the methods specified, since the user agent might
      have other means of communicating with the origin server.

Anyway, you may want to add the [NelmioCorsBundle](https://github.com/nelmio/NelmioCorsBundle), it's embeded in the `api-platform/api-platform` package and does add `Allow` headers.

**Comment by polc** [comment]
I'm not clear I mean add an `Allow` header which is different based on resources configuration. 

For example a collection `/users` could have the header `Allow: GET, POST` and the resource `/users/1` could have `Allow: GET, DELETE`. 

It allow my client to know the operations possible on this resource. Is NelmioCorsBundle doing what I want ? Because It don't seem to add the Allow header in direct requests.

**Comment by dkarlovi** [comment]
[Symfony already does this](http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Exception/MethodNotAllowedHttpException.html):

    $ curl -vX PUT --header 'Accept: application/json'  'http://example.com/api/ingredients'
    > ...
    < HTTP/1.1 405 Method Not Allowed
    < Allow: GET, HEAD, POST

**Comment by polc** [comment]
Yeah but it does only for 405 responses. I would like to be able to do a `HEAD /resource` to know available methods.

**Comment by teohhanhui** [comment]
This is provided by NelmioCorsBundle. You can definitely extend from there for your particular needs.

**Comment by Simperfit** [comment]
@api-platform/core-team WDYT ?

**Comment by Simperfit** [comment]
IMHO this should implemented directly in Symfony, I don't see why should api-platform have this feature only.

**Comment by polc** [comment]
Yeah I agree with you! I'm closing then, this issue do not belongs to API Platform.
