### ISSUE TITLE
[Question] Record id with dot and slash

### ISSUE THREAD

**Issue by Garfield-fr** [api-platform/core#791]
Hi,

It's possible to configure the api-platform routing to accept dot and slash in record id.

Some records in my database are this syntax:
doaj_xmloai:doaj.org/article:73054a153191488880f25fc48d2773ab

On Symfony routing parameter, i have this parameter (requirement=".+") to change the process.

Thank's for your answer.

Bertrand

**Comment by teohhanhui** [comment]
What is the problem that you are running into? Can you shed some light on the issues?

**Comment by Simperfit** [comment]
@Garfield-fr Do you still have the issue ?

**Comment by Garfield-fr** [comment]
@Simperfit i encode with base64, because the identifier contains many slash.

I close this.

Thank's
