### ISSUE TITLE
Serialization groups on related entities

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#810]
I was wondering how you're using groups to avoid having joined entites you don't want by mistake.
#### Story:

I'm using Traits for columns like `createdAt/updatedAt` which I use in many entities. Seems like a good practice at first because it's DRY. 
Now, I want those to be serialized every time. I just added a: `@Groups({"default"})` on Traits properties and added the group to my entities.
#### WAT moment

Recently, I could not figure out why my entity was doing unwanted relations on properties which should not have been returned. In fact, this was because both entities (Master and Child) had the same `default` group (see `relatedGroups` in the metadata factory) and therefore had `isReadableLink` to `true`.

Is there a solution for those kind of properties or I have to specify every group that uses them on the Trait property (for example `@Groups({"product", "order" ...})`)? Note that this solution would not be DRY anymore and I'd better just put those fields in my entites.

Btw, I'm not sure that our behavior in case of related groups is right but I can't find how we could improve this, nore how to explain why it's not great.

**Comment by dunglas** [comment]
Maybe can you use XML or YAML serializer mapping for that?

**Comment by soyuka** [comment]
For groups or ORM?

I'm using yaml to declare my resources and groups/orm with annotations.

**Comment by dunglas** [comment]
For groups.

**Comment by soyuka** [comment]
So you say I should use one group per entity using the Trait on my `createdAt/updatedAt` fields? Maybe using yaml feels better for that I'll think about it.

**Comment by teohhanhui** [comment]
I use YAML for Symfony Serializer and Validator mappings. It does not suffer the limitations of using annotations. The only downside is that I might forget to update them when something changes in the class.

**Comment by soyuka** [comment]
I think I know what's wrong, or maybe it's just my use of serialization that's wrong...

At first, you're requesting an entity with some serialization context here `foo`. When the serializer founds a new relation, where `isReadableLink === true`, `create` gets called with a new `resourceClass` and the normalization context is now the one of the child resource `bar`. This means that every property that has to be serialized by the child entity will be serialized if it matches `bar`, without taking the origin context into consideration `foo`.

Indeed, the first normalization context is lost.

Isn't this a case where we should run in [this condition](https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php#L153)? If it were the case, the below `array_intersect` that sets `isReadableLink` would take the initial context `foo` instead of the one of the child entity `bar`.

Let me know if you didn't understood a word of this, it's kinda hard to explain.

**Comment by teohhanhui** [comment]
Some examples would be helpful to illustrate the problem.

**Comment by soyuka** [comment]
Yeah in fact it's the `EagerLoadingExtension` that should keep the initial groups, because it's calling `           $propertyMetadata = $this->propertyMetadataFactory->create($resourceClass, $association, $propertyMetadataOptions);` with the related class and therefore gets the relation serialization groups instead of the original ones.

**Comment by soyuka** [comment]
@dunglas @teohhanhui would you see any objection in having the `AbstractItemNormalizer`'s `context`  to be transfered to `getItemFromIri` and then to data providers? Or maybe you've an idea on how I could get the normalizer's context back there?

I think it would simplify lots of things. It also gives the ability to work on denormalization through the correct initial group instead of the resource's denormalization context. Atm I'm hacking around for the normalization process and it works (because `getItem`/`getCollection`) are called with the initial resource class. On denormalization, it is not.

**Comment by Simperfit** [comment]
@soyuka Does the PR fix this issue ?
