### ISSUE TITLE
swagger url problem with /app_dev.php/

### ISSUE THREAD

**Issue by Kralock** [api-platform/core#815]
Hi,
I've got a problem with swagger Ui. I saw the correction but in 2.0RC3, the bug is still present.

Take a look on this screen 
![capture d ecran 2016-10-24 a 10 59 15](https://cloud.githubusercontent.com/assets/10655148/19639637/8ac742a6-99d9-11e6-96ea-c738034b19a6.png)
![capture d ecran 2016-10-24 a 10 58 34](https://cloud.githubusercontent.com/assets/10655148/19639636/8ac54e42-99d9-11e6-9fc3-c1c96c7cc74c.png)

And no prob using Postman 

<img width="1116" alt="capture d ecran 2016-10-24 a 11 04 47" src="https://cloud.githubusercontent.com/assets/10655148/19639698/c912475e-99d9-11e6-96f2-e05a91811a6c.png">

Its work perfectly in prod env, but not in dev..

**Comment by dunglas** [comment]
It's probably because you use the prod mode with Swagger UI (`app.php`)  and the dev mode with Postman (`app_dev.php`).

Can you try to clear the cache? `bin/console c:c -e=prod`

**Comment by Kralock** [comment]
In dev env, i always get a 404 error

![capture d ecran 2016-10-24 a 11 22 07](https://cloud.githubusercontent.com/assets/10655148/19640268/2fb75a6a-99dc-11e6-80ad-e71489985b3e.png)

In prod env, its work correctly.

**Comment by dunglas** [comment]
Can you try to clear the cache in dev? Sometimes it is necessary when creating a new entity: `bin/console c:c -e=dev`

**Comment by Kralock** [comment]
Ok it work with a bin/console c:c -e=dev,  but in dev env we don't have to clear cache no ?

**Comment by Kralock** [comment]
Hmmm, I'll see in app.dev_php, the "$kernel->loadClassCache();" is not comment. It'll be work perfectly now :)

**Comment by teohhanhui** [comment]
@Kralock What do you mean?

**Comment by Kralock** [comment]
When i create new symfony project, this line "$kernel->loadClassCache();" in app_dev.php doesn't exist or comment.
I didn't check it before open issue... Sorry for losing time :(
