### ISSUE TITLE
Problem with Doctrine Embeddable

### ISSUE THREAD

**Issue by polc** [api-platform/core#829]
### Problem 1:
```php
PUT /resources
{
    "myEmbeddable": {
        "field123": "Test"
    }
}
```
Actually : Every attributes of **myEmbeddable** will be set to null, excepted **field123** which will be correctly updated.
Excepted : **field123** is updated but other attributes remain the same

### Problem 2:
```php
PUT /resources
{
    "myEmbeddable": {
        "anOtherEmbeddable": {
            "Test"
        },
    }
}
```
Actually : I got an **ContextErrorException** : _Warning: json_decode() expects parameter 1 to be string, array given_
Excepted: **anOtherEmbeddable** is unserialized the same way than other objects

### Problem 3:
```php
/**
 * @ORM\Embeddable()
 */
class Person
{
    /**
     * @ORM\Embedded(class="Address")
     */
    private $address;

    public function __construct(Address $address = null)
    {
        $this->address = $address ?: new Address();
    }

    public function getAddress() : Address
    {
        return $this->address;
    }

    public function setAddress(Address $address)
    {
        $this->address = $address;
    }
}
```
Actually: The **setAddress** setter is required for being able to update Address
Excepted: There shouldn't be a setter for an embeddable from a Domain point of view.

**Comment by teohhanhui** [comment]
This is handled by https://github.com/symfony/serializer/blob/f25e8c1dac293657910be704b9bedf2e2a4ec7c1/Normalizer/AbstractNormalizer.php#L271-L370

**Comment by teohhanhui** [comment]
Your expectation in "Problem 1" is that a new value object should always be created, right? You can do it by decorating the normalizer.

"Problem 2" has invalid JSON, so there's nothing we can do about that.

As for "Problem 3", are you sure it's a supported use case in Doctrine ORM? AFAICT embeddables cannot be nested.

**Comment by polc** [comment]
For problem 1 if I set only one attribute, all others attributes are set to null. Is the the normal behavior ?

For problem 2, I made a typo but the problem still remain, serializer try to deserialize anOtherEmbeddable into a string.

Nesting embeddables are supported : https://github.com/doctrine/doctrine2/issues/4037 :)

**Comment by teohhanhui** [comment]
Oh, sorry I misread that...

Please provide us with more information, including where Person is embedded.

Also, please provide the corrected JSON for "problem 2"...

**Comment by polc** [comment]
Checkout https://github.com/polc/api-platform/tree/master/src/AppBundle/Entity 

It look like embedded objects are not well deserialized.

**Comment by Simperfit** [comment]
did you thing something for this @polc ?

**Comment by polc** [comment]
Long time since I tried so I don't know if the problem is still there. And now I think Embedabble are not a so good idea so if no one else has complained, it can probably be close. :)

**Comment by latenzio** [comment]
As seen at https://symfony.com/doc/current/components/serializer.html#deserializing-in-an-existing-object:
> When the AbstractObjectNormalizer::DEEP_OBJECT_TO_POPULATE option is set to true, existing children of the root OBJECT_TO_POPULATE are updated from the normalized data, instead of the denormalizer re-creating them.
