### ISSUE TITLE
2.8 Compatibility

### ISSUE THREAD

**Issue by jayesbe** [api-platform/core#840]
Opening this issue to see if we can make v2 compatible with Symfony 2.8 LTS on PHP 7.0+

I forked and created a branch and modified the composer.json a bit
https://github.com/jayesbe/core/blob/2.8-compat/composer.json

One very strange thing I noticed..  

When I try to install my branch.. I get 

```
  Problem 1
    - Conclusion: remove symfony/symfony v2.8.13
    - Conclusion: don't install symfony/symfony v2.8.13
    - Conclusion: don't install symfony/symfony v2.8.12
    - Conclusion: don't install symfony/symfony v2.8.11
    - Conclusion: don't install symfony/symfony v2.8.10
    - Conclusion: don't install symfony/symfony v2.8.9
    - Conclusion: don't install symfony/symfony v2.8.8
    - Conclusion: don't install symfony/symfony v2.8.7
    - Conclusion: don't install symfony/symfony v2.8.6
    - api-platform/core dev-2.8-compat requires symfony/property-info ~3.1 -> satisfiable by symfony/property-info[v3.1.6, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5].
    - api-platform/core dev-2.8-compat requires symfony/property-info ~3.1 -> satisfiable by symfony/property-info[v3.1.6, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5].
    - don't install symfony/symfony v2.8.5|remove symfony/property-info v3.1.6
    - don't install symfony/property-info v3.1.0|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.1|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.2|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.3|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.4|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.5|don't install symfony/symfony v2.8.5
    - don't install symfony/property-info v3.1.6|don't install symfony/symfony v2.8.5
    - Installation request for symfony/symfony ^2.8.5 -> satisfiable by symfony/symfony[v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Installation request for api-platform/core dev-2.8-compat -> satisfiable by api-platform/core[dev-2.8-compat].

```

Now I also got it to install.. which is the strange part.

I took the dependencies exactly as as stated in the above composer.json.. and added it directly into my application.

```
	"api-platform/core": "dev-2.8-compat",
        "symfony/property-info": "~3.1",
        "symfony/serializer": "~3.1",
```

This time.. installation went through perfectly and I am able to generate API Documentation.  Have not confirmed API works as expected.. but hopefully I can determine that soon.

Regardless.. Why would I need to add those dependencies specifically into my application's composer.json?  Why are they not handled via the api-platform/core composer.json?  They are literally the exact same dependencies.

**Comment by teohhanhui** [comment]
You have to add these to your root composer.json because `symfony/symfony` "replaces" all the Symfony component packages.

**Comment by theofidry** [comment]
As @teohhanhui, it's a case where your `symfony/symfony` and `api-platform/core` deps are conflicting, so you have to explicitly tell which dep to use for the conflicting ones.

**Comment by teohhanhui** [comment]
Please pay close attention to https://github.com/api-platform/core/blob/97fda1b2cba891535d8da9489fe97c17b5b97f2d/composer.json#L41-L50

**Comment by teohhanhui** [comment]
Hmm... Actually I take back what I said. `symfony/symfony` only replaces packages of the same version.

**Comment by jayesbe** [comment]
@teohhanhui  @theofidry  there shouldn't be a conflict.  I would assume that Composer can implicitly determine which packages to install. However in this case I needed to explicitly state the packages and they are identical. Perhaps there is ambiguity somewhere and that's why Composer couldn't determine. So far the changes for 2.8 compatibility are minor. 

Keeping at it.

**Comment by Simperfit** [comment]
@jayesbe How did you achieve this, could you please tell us ?

**Comment by Simperfit** [comment]
Api-Platform 2.0.3 is compatible with 2.8, you don't need to change anything in the code-base but to fix the composer.json according to you're needs en api-platform's one.

If there something you want to add in this, tell us we will reopen this issue.

**Comment by jayesbe** [comment]
@Simperfit my apologies for not responding before, I totally lost sight on this ticket because I got stuck and lowered the priority, its great that its now compatible as my priority for this just got raised.. thanks a lot.
