### ISSUE TITLE
Embedded resources in v2

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#846]
#432 describes my use case, but the tips are for v1 of api-platform.

What is the best way to accomplish this in v2? In my use case, I have a "View" entity (which contains a bunch of rules, similar to database views) that filters a set of "Defects". I have separate end points for Views and Defects, but the Defects that each View contains are generated at run time, so I can't run a `/defects?view=xxx` query.

I think the easiest query to do this would be something like `/views/xxx/defects`. Any tips on how to appropriately implement something like this?

**Comment by dunglas** [comment]
Hi @bwegrzyn,

You can use custom actions to do that: https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers

**Comment by bwegrzyn** [comment]
Hi @dunglas,

I understand custom actions and have been using them. I suppose my questions are this:

1. Do I tie this custom action back to the Defect resource or View resource?
2. Do I return just a collection of Defects or do I return the View resource with a "defects" property?

At the end of the day, I know how to implement this. I'm just curious as to what you think is the best strategy to go with.

Thanks for your input!

**Comment by Simperfit** [comment]
It depends on your needs anyway. If you have to do something like `/views/xxx/defects` you can affect that to the View resource. If you go like this you should return a views resource with the defect property.

**Comment by Simperfit** [comment]
@bwegrzyn is it ok for you ?

**Comment by bwegrzyn** [comment]
@Simperfit My needs were a little more complicated than the new sub resource feature, as the results of my sub resource come from an external service, rather than a simple database query on the relation. I ended up implementing this through a custom action.

However, for simpler needs, the sub resource feature would cover this use case. I would consider this issue resolved.

**Comment by teohhanhui** [comment]
You can do that with a [custom collection data provider](https://api-platform.com/docs/core/data-providers#custom-collection-data-provider). :smile:

**Comment by soyuka** [comment]
Custom subresource data provider also exists :).

**Comment by teohhanhui** [comment]
Hmm... How? :D

**Comment by soyuka** [comment]
By implementing the SubresourceDataProviderInterface?
