### ISSUE TITLE
[Question] 405 Method not allowed

### ISSUE THREAD

**Issue by Garfield-fr** [api-platform/core#854]
Hi,

I would like to return a "405 Method not allowed" on my REST API, if my route has not declared.

Example:
- GET -> enabled
- POST -> disabled return 405 (Not declared in my entity annotation)
- etc

Thank's for your help

Bertrand

**Comment by GregoireHebert** [comment]
Here is the definition of 405 HTTP Status code:

> 405 Method Not Allowed
> The request method is known by the server but has been disabled and cannot be used

if your route is not declared, it means it does not exist. it's not really something you forbid to your users. IMO a 404 HTTP status code match better your case.

**Comment by Garfield-fr** [comment]
Thank's for your answer, but  if your read this page, you are another specification:

http://restful-api-design.readthedocs.io/en/latest/methods.html

Point 2: Just issue the method you want to issue, but be prepared for a “405 Method Not Allowed” response that indicates the method is not accepted for this resource or collection.

My question: it's possible to implement this on API-Platform ?

Thank's

Bertrand

**Comment by GregoireHebert** [comment]
My bad, you said your route was not declared so I thought there wasn't anything behind the routes you wanted to handle with a 405. But I read again your problem and realized you actually want to disable the POST operation for your resource.

if you look at the documentation : https://api-platform.com/docs/core/operations#enabling-and-disabling-operations

you'll see that if you manually specify only the GET operation, POST operation will then return a 405 HTTP status.

**Comment by Garfield-fr** [comment]
Exactly.

Example:
```
/**
 * @ApiResource(
 *     collectionOperations={"get"={"method"="GET"}},
 *     itemOperations={"get"={"method"="GET"}}
 * )
 */
```

This is my minimal configuration on Entity.

**Comment by Simperfit** [comment]
Is it ok for you ?
