### ISSUE TITLE
PUT with embedded relation, no route matches "<int>", ItemNormalizer bug ?

### ISSUE THREAD

**Issue by VaN-dev** [api-platform/core#857]
Hello,

i'm facing a bug when submitting a PUT request with embedded relation :

data sample posted :

```
array:7 [
  "@context" => "/app_dev.php/contexts/Staking"
  "@id" => "/app_dev.php/stakings/10"
  "@type" => "Staking"
  "id" => 10
  "tournaments" => array:1 [
    0 => array:4 [
      "@id" => "/app_dev.php/staking_tournaments/3"
      "@type" => "StakingTournament"
      "id" => 3
      "tournament" => "/app_dev.php/tournaments/1"
    ]
  ]
  "name" => "Staking #111"
  "mode" => "simple"
]
```

api-platform returns me the following error :

```
{
    "@context":"\app_dev.php/contexts/Error",
    "@type":"Error",
    "hydra:title":"An error occurred",
    "hydra:description":"No route matches "3".", 
    ...
}
```

The error is caused by `src\Serializer\ItemNormalizer.php`, line 36, using `$data['id']` instead of `$data['@id']`. In my case, `$data['id']` is supposed to be an integer, the PK in database, not a resource URL.

**Comment by Simperfit** [comment]
Could you please test the PR ?

**Comment by dunglas** [comment]
I think this bug is related with how embed relations are handled. @VaN-dev, can you open a PR with a failing Behat test?

**Comment by dunglas** [comment]
Can you also post the full stack trace, because `src\Serializer\ItemNormalizer.php` should not be called at all (the JSON-LD normalizer must be used).

**Comment by Simperfit** [comment]
I've added the failing behat test case and this happen when sending an int in iri using the header to be application/json like in this [case](https://github.com/api-platform/core/pull/877/files#diff-bd4acc142ca94f33b7ba882cc1b52e42R52)
