### ISSUE TITLE
Question: Does the API Platform support Propel

### ISSUE THREAD

**Issue by denormalizer** [api-platform/core#861]
It looks like the API Platform uses Doctrine quite heavily.

We currently have a requirement to use Propel instead of Doctrine.

Does the API Platform support Propel. If not, does it intend to support Propel in the future.

Thanks

**Comment by dunglas** [comment]
Hi @denormalizer,

There is no builtin Propel support but you can add support for it (or any other persistance layer) by implementing the data providers interface: https://api-platform.com/docs/core/data-providers

As far as I know, nobody is actually working on Propel support, but if someone want to contribute it, we'll be happy to merge it.

**Comment by tacman** [comment]
Propel is dead.  Propel 1.7 is marked as outdated and unmaintained, Propel 2 has been in alpha for a few years now.  Any time spent supporting Propel would be better spent migrating to Doctrine. Alas, this was a very expensive lesson for us to learn!

**Comment by denormalizer** [comment]
@tacman It depends what drivers you are using. If you can get doctrine to play nice with MS SQL let me know.
http://propelorm.org/Propel/cookbook/using-mssql-server.html

**Comment by Simperfit** [comment]
@denormalizer Maybe this could be contributed in ApiPlatform or in a external bundle, i'm not using propel at all so I could not help with this.

**Comment by denormalizer** [comment]
@Simperfit That's OK, I'm not really pushing for it. I can understand why Propel is not supported by default.

**Comment by Simperfit** [comment]
As said, this could be in an external bundle first, if this is something people want we could think about adding in the core.
