### ISSUE TITLE
[BUG] Generate custom path entity definition with parameters in url

### ISSUE THREAD

**Issue by Garfield-fr** [api-platform/core#865]
Hi,

I defined a custom path annotation on my Entity for my collectionOperations (GET). This is a hierarchy
for get some informations (requests, histories, etc).
 
```
"path" = "/patrons/{barcode}/requests",
```

But, in the class IriConverter, function getIriFromResourceClass, you don't get url parameter(s).

```
$this->router->generate($this->routeNameResolver->getRouteName($resourceClass, true), [], $referenceType)
```

What's the best solution for this definition ?

Thank's for you help

Bertrand

**Comment by dunglas** [comment]
You should [use custom actions](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers) to do that, the `path` option only allows to customize "standard" URL (not something like your barcode parameter).

**Comment by Garfield-fr** [comment]
Super. Merci
