### ISSUE TITLE
Custom entity namespace for annotation loading

### ISSUE THREAD

**Issue by digilist** [api-platform/core#868]
Currently, the API bundle looks only for annotation based mappings in the entity namespace of bundles (see here: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L257).

It would be really nice to have an option to add further paths, because my entities are not placed inside a bundle, so that I do not have to use the YAML configuration.

**Comment by dunglas** [comment]
You can already did it using a custom compiler pass, but indeed, it would be nice to add a configuration option in the bundle.

Are you interested in working on a PR adding this feature?

**Comment by digilist** [comment]
Sure :smiley:

**Comment by Simperfit** [comment]
Thank you @digilist
