### ISSUE TITLE
[Question] Custom operations routing

### ISSUE THREAD

**Issue by Plasmagun86** [api-platform/core#870]
I have an entity contact and i would like to add a collection operation.
The route of my new collection operation is /contacts/download.

The problem is that my route is handle by the default get route for my entity. Api platform search the entity with id = download and return a 404.

Is there a way to specify that my entities use integer id in default route ?

FYI : I use Api Platform v2.

**Comment by Simperfit** [comment]
I think you need a custom operation as settled in the [documentation](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers)

**Comment by Plasmagun86** [comment]
Thanks for your answer.

I already use a custom operation.

When i call /contacts/download, I use the default "GET" route /contacts/{id}. The ReadListener search a contact with download as id, don't find it and return a 404.

I would like to precise in default get route that id need to be a number. Then the route /contacts/1 will use the route /contacts/{id} and the route /contacts/download will use my custom operation.

**Comment by Simperfit** [comment]
Could you please post here the code and the configuration ?

**Comment by Plasmagun86** [comment]
Entity =>
```php
/**
 * @ORM\Entity
 * @ORM\Table(name="contact")
 * @ApiResource(
 * attributes={
 *     "normalization_context"={
 *         "groups"={"direct_debit_batch_norm"},
 *         "datetime_format"="Y-m-d"
 *     },
 *     "denormalization_context"={
 *         "groups"={"direct_debit_batch_denorm"},
 *         "fetch_data"=true
 *     },
 *     "filters"={
 *         "filter.direct_debit_batch_search",
 *         "filter.direct_debit_batch_date"
 *     }
 * },
 * collectionOperations={
 *     "get"={"method"="GET"},
 *     "post"={"method"="POST"},
 *     "download_get_collection"={
 *         "route_name"="api_contacts_get_download_collection",
 *         "hydra_context"={"@type"="hydra:Operation", "hydra:title"="Download operation", "returns"="xmls:string"}
 *     }
 * },
 * itemOperations={
 *     "get"={"method"="GET"},
 *     "put"={"method"="PUT"},
 *     "delete"={"method"="DELETE"},
 *     "download_get"={
 *         "route_name"="api_contacts_get_download",
 *         "hydra_context"={"@type"="hydra:Operation", "hydra:title"="Download operation", "returns"="xmls:string"}
 *     }
 * })
 */
class Contact
{
```

Action => 
```php
/**
     * @Route(
     *     name="api_contacts_get_download_collection",
     *     path="/contacts/download",
     *     defaults={
     *         "_api_resource_class"=Contact::class,
     *         "_api_collection_operation_name"="download_get_collection"
     *     }
     * )
     * @Method("GET")
     */
    public function __invoke($data)
    {
```

For the moment, i found a solution by changing the route to /contacts/file/all/download.

**Comment by Simperfit** [comment]
Yeah, I think it's the better way to avoid collision by using /contacts/{id}/download to download just one and then to use something like /contacts/all/download to download all.

**Comment by kate-kate** [comment]
@Simperfit could you please advice, do we always have to make custom item operation route like /contacts/{id}/download? Also does it means, that route like /contacts/new/retrieve should return collection?

**Comment by Simperfit** [comment]
@kate-kate IMO, if you want to be restful, you have to add the {id} parameters when it's a custom item operation. I think it should be avoided for item operation to leave out the {id}.

**Comment by kate-kate** [comment]
@Simperfit and what if I need to get a new item with some presets (which depends on request params)? Like I send phone and if it is in db, I need to get entity with its phone IRI, customer IRI set and maybe some other fields processed?

**Comment by Simperfit** [comment]
The OP seems to be resolved.

@kate-kate if you still needs some advices, please feel free to join the API-Platform channel on the symfony's slack.
