### ISSUE TITLE
The total number of joined

### ISSUE THREAD

**Issue by foolskill** [api-platform/core#876]
Hello team,

I started to develop my application with ApiPlatform. It works well but I just have a problem with one of my entities. I can not read it (GET). In return I have the following error:

`{
  "@context": "/api/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "The total number of joined relations has exceeded the specified maximum. Raise the limit if necessary."
}`

Could someone help me? Have you ever been confronted with this problem?

thank you

**Comment by foolskill** [comment]
I solved the problem by half. By just removing the annotation  `normalization_context` my api work.
I wonder how that happens. I have, however, reproduced the documentation on the `normalization_context`.

**Comment by dunglas** [comment]
@foolskill can you try to set `force_eager` to `false` for this resource as described here: https://api-platform.com/docs/core/performance#eager-loading?

**Comment by soyuka** [comment]
>  I have, however, reproduced the documentation on the normalization_context.

Can you remember where in the documentation? Thanks!

**Comment by Simperfit** [comment]
Closing as there are no feedback
