### ISSUE TITLE
[Swagger] attribute definitions.Dummy.externalDocs is unexpected

### ISSUE THREAD

**Issue by maechler** [api-platform/core#878]
The swagger online validator is throwing an error on the attribute `externalDocs`. I have tested this with version `2.0.1` of `api-platform/core`.

I simply copied the expected value from the following test and put it on a webserver:

**test**
https://github.com/api-platform/core/blob/master/tests/Swagger/Serializer/DocumentationNormalizerTest.php#L711

**produced json**
http://www.bit9.ch/apiplatform.json

**swagger validator**
http://online.swagger.io/validator/debug?url=http://www.bit9.ch/apiplatform.json

```json
{
  "messages": [
    "attribute definitions.Dummy.externalDocs is unexpected",
    "attribute definitions.Dummy_be35824b9d92d1dfc6f78fe086649b8f.externalDocs is unexpected"
  ]
}
```

The swagger specification seems to allow the attribute `externalDocs`: http://swagger.io/specification/#schemaObject
Do you know about that error? Is that rather a bug of the swagger online validator?
I have not found anything to that issue so far..

**Comment by Simperfit** [comment]
It is allowed by the schema and the schema is validated with [swagger-cli](https://www.npmjs.com/package/swagger-cli)

I don't know about that error. 

Maybe it's not allowed in the definitions anymore ?

**Comment by dunglas** [comment]
It looks like a bug in the online validator. Using `externalDocs` is explicitly allowed by the spec: http://swagger.io/specification/#schemaObject

**Comment by maechler** [comment]
Thanks for having a look at it! 

https://github.com/swagger-api/validator-badge/issues/97
