### ISSUE TITLE
[RespondListener] POST_RESPOND not hookable ?

### ISSUE THREAD

**Issue by nicolasmure** [api-platform/core#879]
Hello,

Thank you for the framework 👍 !

After have played with it a little, I saw on the [documentation](https://api-platform.com/docs/core/events) that there is a [`POST_RESPOND`](https://github.com/api-platform/core/blob/master/src/EventListener/EventPriorities.php#L30) event priority which can be used on the `kernel.view` event.

However, the [RespondListener](https://github.com/api-platform/core/blob/master/src/EventListener/RespondListener.php) is executed on `kernel.view` at a higher priority than `POST_RESPOND` (as expected), but it is calling the `setResponse` function of the event [which is stopping its propagation](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Event/GetResponseEvent.php#L53).

Does the POST_RESPOND is not hookable at all or am I missing something ?

Thanks 😉

**Comment by dunglas** [comment]
Good catch, it's a bug. I'll fix that.

**Comment by Simperfit** [comment]
This has been fixed and released.
