### ISSUE TITLE
[V2] Custom operation + deserialization

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#880]
Hello.

### My context

I have two entities `Env` and `User`. And and env could have members (users).
So I wanted to add a new custom operation.

In this case, it do not need to send a body content, because I can give everything in the URL (`api/v2/{env uuid}/add-memeber/{user uuid}`). So I would like to be able to disable the automatic deserialization. 

### Note

I saw in the doc, the following route param are mandatory:
`*     defaults={"_api_resource_class"=Env::class, "_api_item_operation_name"="add-member"}`
But I looked at the code, and actually, it's not really mandatory, because there is a try/catch [there](https://github.com/api-platform/core/blob/master/src/EventListener/DeserializeListener.php#L52-L56)

Then, Even if I add theses param, the new operation is not displayed in the doc (swagger)

### RFC

Add an option in the route configuration to not enable the automatic deserialization. because sometimes, you don't need it.

**Comment by kbsali** [comment]
@dunglas @teohhanhui sounds familiar! ;)
@lyrixx we also had that very same need (see #781) and provided a PR : #782 which has been moved to #805 ...

I would therefore consider this as a "WIP duplicate"!

**Comment by dunglas** [comment]
The route option looks like a good solution to me.

**Comment by Simperfit** [comment]
I think this has been fixed, @lyrixx if it's not feel free to ping me
