### ISSUE TITLE
How can I add routes like /resource/{parameter}?

### ISSUE THREAD

**Issue by valtovar** [api-platform/core#887]
Hey, guys, I have my Action, and I have this:

`@Route(
     *     name="get_localized",
     *     path="/resource/{lang}",
     *     defaults={"_api_resource_class"=Resource::class, "_api_collection_operation_name"="localized"}
     * )
    public function __invoke($data) 
    {
               return $data;
    }
`

My question is how to use the parameter? When I update the API webpage it shows me the route, but I can't see the parameter, and if I try like http://...../resource/en.json, It doesn't send my URL parameter, and if I try something like:

`public function __invoke($data, $lang) 
    {
               echo $lang;
               exit();
               return $data;
    }`

It shows "{lang}", not its value "en" on this case.

Any suggestion?

Thanks.

**Comment by piotrbrzezina** [comment]
Hi 

For now "api platform" cannot extract additional parameters from custom action. To solve this problem you should add custom swaager_context. In this topic https://github.com/api-platform/docs/issues/143 I describes how to do it

Yesterday I created PR with refactor and improve to swagger normalizer my solution can extract additional parameters from custom action. But for now you should use the solution which I have already mentioned 

https://github.com/api-platform/core/pull/886
