### ISSUE TITLE
[Bug?] difference between configure mapping with YAML and XML

### ISSUE THREAD

**Issue by hugohenrique** [api-platform/core#889]
Exists a difference between configure mapping com YAML and XML with relation the attributes:

in YAML is ```collectionOperations``` 
and XML ```collectionOperation```

<img width="1148" alt="screen shot 2016-12-19 at 17 41 38" src="https://cloud.githubusercontent.com/assets/4316743/21328381/6f6758b0-c612-11e6-8c48-3cdc686eced9.png">

**Comment by teohhanhui** [comment]
This is by design.
