### ISSUE TITLE
MaxDepth not working because ClassMetadataFactory is missing

### ISSUE THREAD

**Issue by digilist** [api-platform/core#890]
I am trying to use the @MaxDepth annotation with an api-platform resource. But it looks like the annotation is ignored, because the classMetadataFactory is not set.

The max depth is not checked if the classMetadataFactory is not available (see. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L75). And it is not available, because it is not injected (see https://github.com/api-platform/core/blob/master/src/Serializer/AbstractItemNormalizer.php#L44). Is there any reason to do this or can we add the classMetadataFactory as a parameter? It might be a BC break.

**Comment by Simperfit** [comment]
@digilist does #895 fix the issue ?

**Comment by digilist** [comment]
Yes, thank you, it's working. But only with the Json Normalizer, the problem exists with the JsonLd Normalizer. But that's only because, the parameter is not passed to the parent constructor. I opened a PR to fix this: #896

**Comment by Simperfit** [comment]
Both PR merged
