### ISSUE TITLE
nested resources /subjects/{subject}/lessons

### ISSUE THREAD

**Issue by piotrbrzezina** [api-platform/core#898]
What do you think about adding filters an ability to get values from a path part of the url instead of getting it from a query part of the url? With this solution, it would be possible to make nested resources like  ``/subjects/{subject}/lessons`` where the variable ``subject`` would be taken as a filter value.

**Comment by teohhanhui** [comment]
Nested resources must be one of the most requested features. See #634

**Comment by dunglas** [comment]
I think that @soyuka is working on it.

**Comment by soyuka** [comment]
Didn't started yet but yeah I'll look into this asap!

**Comment by piotrbrzezina** [comment]
ok so I'm waiting for this feature
