### ISSUE TITLE
Keep default relation links when using @Groups

### ISSUE THREAD

**Issue by ybouhjira** [api-platform/core#901]
Hi, and thank you for making this great framework. But I have stumbled upon a problem. When I use the `@Groups({"read", "write"})` annotation the links that are generated by default by the framework (example below) disappear. How to I keep them without embedding that relation?

```
  "books": [
      "books/1",
      "books/2",
  ]
```

**Comment by Simperfit** [comment]
You can specify the groups more precisely maybe ? `@Groups({"books_read", "books_write"})`

**Comment by ybouhjira** [comment]
It works :) thank you
