### ISSUE TITLE
How to serialize a discr column ?

### ISSUE THREAD

**Issue by guiyomh** [api-platform/core#911]
Hi,
How to serialize a discr column when i have SINGLE_TABLE inheritance ?

For Example , I have 3 class : 
```php
/**
 * @ApiResource
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="user_type",type="string")
 * @ORM\DiscriminatorMap({
 *          "member" = "AppBundle\Entity\User\Member",
 *          "manager" = "AppBundle\Entity\User\Manager"
 *     })
 */
abstract class User {
    private $username;
}

//...

/**
 * @ApiResource
 */
class Member extends User {}

//...

/**
 * @ApiResource
 */
class Manager extends User {}
```

And i would like only one URI to manage this entities.

For example :
`GET /users` = for get the collection
`GET /users/{id}` 
`PUT /users/{id}`
`POST /users` for to create a member or a manager

I would like get or post a json like this
```json
{
  "usrname": "my username",
  "user_type": "manager",
}
```

it's possible ?

**Comment by teohhanhui** [comment]
You should have a different `@type` IRI when you GET the collection? If
not, maybe we should fix that...

**Comment by karser** [comment]
@guiyomh you might serialize a method output, e.g:
```
abstract class User {
    private $username;
    /**
     * @ApiResource
     */
    public function getUserType() {
        return get_class($this); //or split it by "/" and return the last part
    }
}
```

**Comment by teohhanhui** [comment]
I wouldn't recommend that. The `@type` is the right way to do it.

**Comment by Simperfit** [comment]
What is the ETA on this @karser ?

**Comment by karser** [comment]
@Simperfit I'm not fully following your question, maybe you intended to tag @teohhanhui ?

**Comment by guiyomh** [comment]
Exit json, i switch to Hydra ! And i use `@type`
thx  @teohhanhui
