### ISSUE TITLE
Normalisation context depending of the output format

### ISSUE THREAD

**Issue by Plasmagun86** [api-platform/core#913]
I would like to export my data in CSV. I have updated my config to allow it like this : 

```json
api_platform:
    title:       "%api_name%"
    description: "%api_description%"
    formats:
        jsonld:
            - application/ld+json
        json:
            - application/json
        csv:
            - text/csv
```

But the data exported need to be cleaned, some fields need to be removed.

There is a way to change the serialization context depending of the output format ?

By the way, I need to export all my data in CSV but I don't want to allow users to change my pagination settings. There is a way to disable pagination depending of the output format ?

**Comment by dunglas** [comment]
Yes: https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically

You in the context builder, you have access to the request and you can check the current format.

**Comment by Plasmagun86** [comment]
Thank you for your quick answer. It is what i was looking for.
What about pagination ?

**Comment by dunglas** [comment]
Pagination for CSV?

**Comment by Plasmagun86** [comment]
I want to disable pagination on csv format only but not on json format.

**Comment by dunglas** [comment]
You could decorate the [`PaginationExtension`](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php) to do that but you shouldn't: the resource(s) returned by the API should always be the same for all formats (only the format should change when using content negotiation, not the data).

I would instead create a custom action returning the list not paged (for every formats).

Another alternative is to let the client disable the pagination: https://api-platform.com/docs/core/pagination#client-side
