### ISSUE TITLE
No resource class found for object of type

### ISSUE THREAD

**Issue by ufik** [api-platform/core#916]
Hello,

I have entity Role which has collection of RoleResource entities, but this one (RoleResource) is not registered as an API resource. It's giving me back `No resource class found for object of type Resource`, which is an attribute in RoleResource and is registered as an API resource.

```
    /**
     * Resources of the role and their permissions.
     *
     * @ORM\OneToMany(targetEntity="RoleResource", mappedBy="role", cascade={"remove"}, fetch="EAGER")
     **/
    private $resources;
```

If I add @ApiProperty(readable=false) on resources, it's working fine, but I need this property to be propagated.

Another strange thing is, when I remove ApiResource from Resource entity, it works as well. (By it works, I mean Role API endpoint)

Any idea, what's wrong?

**Comment by teohhanhui** [comment]
This seems similar to api-platform/api-platform#201

If you can help us add a failing test case it'd be great.

**Comment by ufik** [comment]
Hi, I have a project on github which has an example.

[security bundle](https://travis-ci.org/ufik/webcookcms-security-bundle)

It's about Roles and Resources as I explained above.

You can see entities here [Entities](https://github.com/ufik/webcookcms-security-bundle/tree/master/src/Webcook/Cms/SecurityBundle/Entity).

And tests which are failing are here [role controller test](https://github.com/ufik/webcookcms-security-bundle/blob/master/tests/Controller/RoleControllerTest.php)

if you run for example first test, there is already var dump, with error message.

**Comment by Simperfit** [comment]
@ufik does the PR fix the issue ?

**Comment by ufik** [comment]
I will try, but it seems PR was about to create tests not fix the issue.

**Comment by soyuka** [comment]
If test pass, it means there was no issue :p.

**Comment by ufik** [comment]
Ok then you can close it, I won't have time to get closer to this problem any time soon.
