### ISSUE TITLE
EagerLoading with pagination and many relations

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#920]
There is a bug when doing lots of joins with the pagination. The query results are truncated and the limit number in that query isn't taking in consideration that we might have more than X results because we're adding  lines for each joined entities.

Example:

Entity Dummy has ManyToMany with 1 Dummy result and 20 DummyLines
 
Query is something like :

```sql
SELECT * FROM DUMMY d
LEFT JOIN DUMMY_LINES_JOIN_TABLE t ON t.dummy = d.id
LEFT JOIN DUMMY_LINES l ON t.dummy_lines = l.id
```

Gets back  20 lines from database, 1 for each line, Doctrine is hydrating this fine and it's fast.

Then the paginator does something like:

```sql
SELECT a.* FROM ( 
  SELECT * FROM DUMMY d
  LEFT JOIN DUMMY_LINES_JOIN_TABLE t ON t.dummy = d.id
  LEFT JOIN DUMMY_LINES l ON t.dummy_lines = l.id
) WHERE ROWNUM <= 10 
-- on Oracle
```

This obviously fails as the pagination should check the number of lines on `d` not on the global result.

I need to reproduce this in a clean test case, for now solutions are:

1. Disable pagination
2. Disable eager loading (not sure if that actually solves the issue, we may just observe the same thing without it but I need to test)

**Comment by teohhanhui** [comment]
So what's the situation? :D

**Comment by soyuka** [comment]
Haha no bugs ! I had a hack that override the pagination and broke
everything, this just works fine natively!
