### ISSUE TITLE
MaxDepth and dynamic context builder

### ISSUE THREAD

**Issue by desmax** [api-platform/core#933]
I experience weird behavior(v2.0.3). I have MaxDepth annotation on relation field and when I add context group of that field dynamically MaxDepth param value seems to increase by 1.

My entity

```php
/**
 * @ApiResource(
 *  attributes={
 *      "normalization_context"={"groups"={"company", "company-read"}, "enable_max_depth"=true},
 *      "denormalization_context"={"groups"={"company", "company-write"}}
 *  })
 */
class Company
{
    /**
     * @var integer
     *
     * @Groups({"company-read"})
     */
    private $id;

    /**
     * @var Company
     *
     * @Groups({"company-parent"})
     *
     * @MaxDepth(1)
     */
    private $parent;
}
```

I decorate context builder:
```yml
    app.serializer.builder.company:
        decorates: api_platform.serializer.context_builder
        class: AppBundle\Company\CompanyContextBuilder
        arguments: ['@app.serializer.builder.company.inner', '@security.authorization_checker']
```

AppBundle\Company\CompanyContextBuilder:
```php
<?php

namespace AppBundle\Company;

use ApiPlatform\Core\Serializer\SerializerContextBuilderInterface;
use AppBundle\Security\Voter\VEPBaseVoter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use AppBundle\Entity\Company;

final class CompanyContextBuilder implements SerializerContextBuilderInterface
{
    /**
     * @var SerializerContextBuilderInterface
     */
    private $decorated;

    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    public function __construct(SerializerContextBuilderInterface $decorated, AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->decorated = $decorated;
        $this->authorizationChecker = $authorizationChecker;
    }

    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null) : array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);
        $subject = $request->attributes->get('data');

        if (true === $normalization &&
            $subject instanceof Company &&
            $this->authorizationChecker->isGranted(VEPBaseVoter::VIEW, $subject->getParent())
        ) {
            $context['groups'][] = 'company-parent';
        }

        return $context;
    }
}
```

$context array is the same in both cases. When I add `company-parent` dynamically I have two parent companies, when I add that group in `normalization_context` annotation, I have only one(which is what I expect). what do I miss here?

**Comment by desmax** [comment]
anybody?

**Comment by dunglas** [comment]
It's weird, those 2 features aren't related at all. Can you add a failing test case to allow us to hack on this?

**Comment by desmax** [comment]
Tried to replicate it via tests, but failed. Debugging further.

**Comment by desmax** [comment]
@dunglas Either symfony serializer has a bug, either Im doing smth wrong.
My relation is not initialized which caused method `Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer::isMaxDepthReached` return wrong result.
First time $class parameter equals to AppBundle\Entity\Company, second time its Proxies\__CG__\AppBundle\Entity\Company.

**Comment by desmax** [comment]
if I use `$class = \Doctrine\Common\Util\ClassUtils::getClass($object);` instead of `$class = get_class($object);` everything works as expected.

**Comment by desmax** [comment]
Another question why my relation is not eager loaded. As I understand from documentation - you force it by default.

**Comment by desmax** [comment]
Eager loading does not applied, because I initially have no serialization group of that property.

**Comment by desmax** [comment]
I decided to go other way around and remove context group dynamically. That worked, but I don't understand why `fetch: EAGER` on relation in Company.orm.yml did not work.
@dunglas @sroze @theofidry

**Comment by teohhanhui** [comment]
> First time $class parameter equals to AppBundle\Entity\Company, second time its Proxies_CG_\AppBundle\Entity\Company.

> if I use $class = \Doctrine\Common\Util\ClassUtils::getClass($object); instead of $class = get_class($object); everything works as expected.

But the inheritance problem is already handled in the Symfony Serializer:

https://github.com/symfony/symfony/blob/v3.2.3/src/Symfony/Component/Serializer/Mapping/Factory/ClassMetadataFactory.php#L77-L80

Perhaps it's API Platform code (where?) that fails to take inheritance into account?

**Comment by soyuka** [comment]
closing in favor of #1764
