### ISSUE TITLE
[Hydra] Normalization error in ErrorNormalizer.php for Error type

### ISSUE THREAD

**Issue by fmata** [api-platform/core#934]
In ErrorNormalizer.php we have : 

```php
$data = [
            '@context' => $this->urlGenerator->generate('api_jsonld_context', ['shortName' => 'Error']),
            '@type' => 'Error',
            'hydra:title' => $context['title'] ?? 'An error occurred',
            'hydra:description' => $message ?? (string) $object,
        ];
```
But the type `Error` does not exist in the context provided by api-platform.
To be resolved, it needs the context `http://www.w3.org/ns/hydra/core#` aliased by `hydra`.

Si I think it's a bug because at the moment it is not possible to discover the right type of a response when an error is encountered.

PR is coming.

**Comment by dunglas** [comment]
Indeed, it should be `hydra:Error`
