### ISSUE TITLE
[Swagger] Wrong serializing in docs

### ISSUE THREAD

**Issue by aistis-** [api-platform/core#940]
Hi,

I am using a default bundle of API platform v2 and run into small, but annoying docs problem.

I have two entities - `ExpenseCategory` which hold a reference to `Expense` under `expense` property. The problem is, that it is serialized incorrectly `ExpenseCategory` hold a reference to itself instead of `Expense`.

Any ideas? The config is more or less default - I have only registered `ExpenseCategory`

![screenshot](https://s30.postimg.org/d866l7vn5/API_Platform.png)
![screenshot](https://s29.postimg.org/6s4vvdz2f/API_Platform2.png)

**Comment by Simperfit** [comment]
Could you please do the following ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test that and confirm.
