### ISSUE TITLE
"add + remove" elements of collection in a same PUT only process remove

### ISSUE THREAD

**Issue by ZeBigDuck** [api-platform/core#943]
Hi here,

When editing an existing entity, when I add items in my collection, it works. When I delete previously persisted items, it works too. But if I do both in the same PUT, only the removeMyObject($myObject) is called (I put a dump in both add and remove methods).

It seems that when an element is removed, nothing checks if something has been added.

**Comment by teohhanhui** [comment]
More details please. Add / remove is processed by Symfony PropertyAccess component.

**Comment by Simperfit** [comment]
@ZeBigDuck Do you still have an issue ?
