### ISSUE TITLE
Set default format to use

### ISSUE THREAD

**Issue by BerislavSapina** [api-platform/core#951]
Hi.
How can i set default format to use in my api in xml?

This is my resources.xml:
<?xml version="1.0" encoding="UTF-8" ?>
<resources>
    <resource class="Locastic\AppBundle\Entity\Tip">
        <itemOperation name="get">
            <attribute name="method">GET</attribute>
        </itemOperation>
        <collectionOperation name="get">
            <attribute name="method">GET</attribute>
        </collectionOperation>
    </resource>
</resources>

How to add thet get collection always use format jsonld???

Thank you

**Comment by dunglas** [comment]
Can you post your XML file please?

**Comment by BerislavSapina** [comment]
Yes, sure!
`<?xml version="1.0" encoding="UTF-8" ?>
<resources>
    <resource class="Locastic\AppBundle\Entity\Tip">
        <itemOperation name="get">
            <attribute name="method">GET</attribute>
        </itemOperation>
        <collectionOperation name="get">
            <attribute name="method">GET</attribute>
        </collectionOperation>
    </resource>
</resources>`

Thanks! :D

**Comment by Simperfit** [comment]
This seems outdate, @BerislavSapina if you still need help please feel free to ping me.
