### ISSUE TITLE
[Question] Error after add application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by ThomAille** [api-platform/core#954]
Hi Guys,

Since I created the DeserializeListener decorator, I have this error when I make a POST call
I have followed all the steps of this page : https://api-platform.com/docs/core/form-data

Here is the error : Uncaught PHP Exception Symfony\Component\Validator\Exception\RuntimeException: "Cannot validate values of type "NULL" automatically. Please provide a constraint." at /Users/Thomas/Project/apiEngine/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 187

If I remove the decorator I no longer have the error

Do you have an idea ?

Best Regards
Thomas

**Comment by jordscream** [comment]
Hi @ThomAille ,

Are you sure to post all fields required for your entity ?
If it is the case , can you give me your POST data and your Entity for example ?

**Comment by Simperfit** [comment]
Closing since there are no feedback from the users.
