### ISSUE TITLE
[Question] Receive list of entities while deleting all not-receive entities

### ISSUE THREAD

**Issue by aistis-** [api-platform/core#958]
Hello!

What approach you could suggest for exposing API endpoint, which receive a batch of entities, would persist them, and delete the others (not received) entities.

1. Should it be implemented by custom action?
2. Would it be a `PATCH` method for `http://api.com/categories/` (an example).

**Comment by Simperfit** [comment]
Github is more for bug report or feature request then mere question, could you please use stackoverflow or slack if you still need help ?
