### ISSUE TITLE
Deserializing Concrete Entites at Abstract Endpoint?

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#968]
Lets say I have an abstract Animal resource and a concrete Dog resource.

Api platform will generate two sets of routes:

GET /animals
POST /animals
GET /animals/{id}
DELETE /animals/{id}

GET /dogs
POST /dogs
GET /dogs/{id}
PUT /dogs/{id}
DELETE /dogs/{id}

When you have many of these kind of concrete resources, this gets very hectic. In my case, I have 5 concrete classes, which ends up generating 25 routes that are all pretty much the same but with a different URL. 

I have tried to use the abstract end point to create Dog resources (POST /animals with @type=Dog), but this returns an error saying that you cannot instantiate an abstract class. Why have a POST route on the abstract endpoint if you cannot create a concrete resource from it by passing the @type attribute in your request? Similarly, the PUT abstract endpoint appears to be missing. Is this an intended design consideration or a legitimate bug?

I would like to have an option to manage all my concrete resources at the abstract end point with a provided @type attribute. This greatly simplifies things not only on the server side, but also on the UI side.

**Comment by bwegrzyn** [comment]
I apologize, I just noticed that the POST route on the abstract resource endpoint is my own doing, so you can ignore that.

However, my second point still stands. Is there a way to disable generation of all these extra routes for each concrete resource and just have them all go through the abstract endpoint with a @type attribute required?

**Comment by bwegrzyn** [comment]
Looks to be related to #872.

**Comment by soyuka** [comment]
Still an issue? Lmk if I need to open again.
