### ISSUE TITLE
Filters not working with @ORM\Embedded 

### ISSUE THREAD

**Issue by elazer** [api-platform/core#969]
My entity has a "partySize", an embedded class with "value", "minValue", "maxValue".

But trying to filter with partySize.value or any of the other 2 properties would have no effects.

**Comment by dunglas** [comment]
It's indeed not currently supported. I don't know if it can be easily be added but PR about this are very welcome!

**Comment by antograssiot** [comment]
I have a version for the boolean filter that supports embeddable.  I can try to find some time to open a PR but I guess that you're expecting the same level of support on every filters whigh will take much more time.
I know my implementation is far away from ideal but it could beasily a starting point for discussion. WDYT ?

**Comment by soyuka** [comment]
@antograssiot +1 about the starting point!

**Comment by jordscream** [comment]
Hi @antograssiot, @soyuka : the same for me ^^. I have a branch I develop last week with an implementation of Embed Filter for Boolean. Functionnal and  ready for a PR. (except I did not write unit test and need discussions about my implementation). @antograssiot , Do you want I push for a PR if you have not time ?

**Comment by antograssiot** [comment]
Sure go for it.

**Comment by antograssiot** [comment]
So my naive implementation looks like that

https://gist.github.com/antograssiot/e971410aa740ac18c54ba999cc513143

Still needs refractoring, I didn't had a chance to spend more time on it

**Comment by jordscream** [comment]
@antograssiot , thanks. I did a PR. We had the same logic to deal that. Do not hesitate to comment What I did in the PR
