### ISSUE TITLE
[Question] API concurrent versioning

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/core#972]
Is there currently support or a best practice plan to version the API?

In which I mean, how to go about having API v1 and API v2 running in parallel, where v1 is used by legacy clients and required to be running for at least (say) six months alongside v2 which is a new, backward incompatible version.

**Comment by dunglas** [comment]
For at least basic use cases you can use serialization groups to do that.

**Comment by dkarlovi** [comment]
@dunglas that's a start, but seems quite limited, might be wrong, though.

Is this the recommended way of doing it by the project? It seems like [a big, important topic](https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/) (references are good too) to leave up to the end developer.

**Comment by soyuka** [comment]
#45

**Comment by dkarlovi** [comment]
@soyuka have you done the additional research you mentioned there? :)

The ideas @dunglas gave on having a different resource and groups, but same entity seems very interesting, seeing as this is two years old, is this still the preferred way to go? The cookbook entry with a couple of worked out use cases might really be the best solution here.

**Comment by teohhanhui** [comment]
What about running them as separate PHP projects? :) The alternative of
building both versions into one app sounds like it'll just unnecessarily
tie you down in many ways.

**Comment by dkarlovi** [comment]
@teohhanhui I don't think that's viable long term as you might need to maintain both versions for a really long time, maybe forever, which increases the possibility of having more than two versions running at the same time, you might have dozens. That means running and debugging (for example) 12 instances of the mostly-the-same-but-not-quite app, sounds like a maintenance nightmare. But you're right, having 12 versions in the same app sounds like a nightmare too. :)

**Comment by soyuka** [comment]
> @soyuka have you done the additional research you mentioned there? :)

Yeah, I read about it and from what I remember it had more downsides then upsides. Like you said, if you're maintaining API versions, it often becomes a mess and you'd rather deprecate and update client-relying parts.

Though, I can understand that this can be useful sometimes and my solution would be the same as @teohhanhui. Use two api endpoints, if they point on the same entity, use groups. It's limited, but for the better.

**Comment by wadjeroudi** [comment]
Is there some api version management (except fos version, and jms serializer) in api platform ?
Because I see in the doc generated v 0.0.0, how is it defined ?
```
[ base url: /app_dev.php/sapi , api version: 0.0.0 ]
```

**Comment by Simperfit** [comment]
@wadjeroudi it's the parameter, and it's for information

**Comment by gorghoa** [comment]
I can see that this is quite a recurring question, might be valuable to write down those opinionated thoughts in the doc?

**Comment by gorghoa** [comment]
it is https://github.com/api-platform/core/issues/45#issuecomment-99607627 ^^
