### ISSUE TITLE
[Question] 206 Partial Content Response

### ISSUE THREAD

**Issue by jordscream** [api-platform/core#974]
Hello,

According the REST recommendation
http://www.restpatterns.org/HTTP_Status_Codes/206_-_Partial_Content

It is good practice to respond 206 HTTP status code when the content sent is partial.

RespondListener class of APIPlatform returns only 200 for GET method.

Do you think, it's good to include partial content according the rules defined in REST recommendation ?

THanks

**Comment by teohhanhui** [comment]
`206 Partial Content` does not mean what you think it means. It's used together with the `Range` header.

**Comment by teohhanhui** [comment]
If we use the `Range` header for pagination, then it makes sense.
