### ISSUE TITLE
[Question] Child/Subresources URLs

### ISSUE THREAD

**Issue by Plevoscoba** [api-platform/core#983]
Hi.

I'm new to both REST APIs and API-Platform so I might be wrong here.

In the API-Platform demo application you have `GET /books`, `GET /books/{bookID}` and also `GET /reviews`, `GET /reviews/{reviewID}`but it somehow fells wrong isn't it?

I'm wondering if we can have URLs like `GET /books/{bookID}/reviews` like the ones you can generate using the `parent`configuration in the FOSRestBundle.

Many thanks in advance.

**Comment by soyuka** [comment]
Soon! https://github.com/api-platform/core/pull/904
