### ISSUE TITLE
JSON-LD failed to load resource

### ISSUE THREAD

**Issue by yellowmamba** [api-platform/core#998]
Hi there,

We have bumped into an issue where a resource has failed to load in `jsonld` format, while can successfully load with an `json` request.

We have `Book` and `Category` entities, and `Category` entity does not have `$id` field as its primary key in Doctrine but the `$name` field. So it looks like this:

```
class Category {
	/**
          * @ORM\Id
	  * @ORM\Column(type="string", length=255, unique=true)
        */
	private $name;
}
```
When I tried to `get` a book resource in json, the categories information has been populated as a sub document without any issue. However, if I request for a `jsonld` resource, it gives me the following error message:

> "hydra:description": "Parameter \"id\" for route \"api_categories_get_item\" must match \"[^/\\.]++\" (\"\" given) to generate a corresponding URL."

It looks like json-ld only supports `$id` field as a primary key. Not sure if my understanding is correct, but looking for help.

If it helps, we are using Doctrine ORM `v2.5.6`

**Comment by teohhanhui** [comment]
Please help us add a failing test.

**Comment by teohhanhui** [comment]
Anyway, that error message is coming from the Symfony Router. Can you share an example of the URL?
 (e.g. `/api/categories/my-category-name`)

**Comment by yellowmamba** [comment]
So the entities are like this:

```php
class Category {
      /**
        * @ORM\Id
	* @ORM\Column(type="string", length=255, unique=true)
      */
      private $name;

       /**
	* @ORM\OneToMany(targetEntity="BooksCategories", mappedBy="category", cascade={"persist", "remove"})
	*/
	private $books;
}
```

```php
class Book {
        /**
          * @var integer $id
	  *
          * @ORM\Id
          * @ORM\Column(type="integer")
	  * @ORM\GeneratedValue(strategy="IDENTITY")
	  */
	private $id;

	/**
          * @ORM\Id
	  * @ORM\Column(type="string", length=255, unique=true)
        */
	private $name;

       /**
	* @ORM\OneToMany(targetEntity="BooksCategories", mappedBy="book", cascade={"persist", "remove"})
	*/
        private $categories;
}
```

```php
class BooksCategories {
	/**
		 *
		 * @ORM\Id
		 * @ORM\ManyToOne(targetEntity="Book", inversedBy="categories")
		 * @ORM\JoinColumn(name="book_id", referencedColumnName="id")
		 */
		private $book;

		/**
		 *
		 * @ORM\Id
		 * @ORM\ManyToOne(targetEntity="Category", inversedBy="books", cascade={"persist"})
		 * @ORM\JoinColumn(name="category_name", referencedColumnName="name")
		 */
		private $category;
}
```

And when we try the endpoint: `/books/5.jsonld`, it gives us the error above. However, if you request `/books/5.json`, the categories of the book load correctly as embedded documents, like this

```json
{
  "id": 5,
  "name": "My Book",
  "categories": [
    {
      "category": {
        "name": "Category 1"
      }
    }
  ],
```

Hence, my guess is JSON-LD cannot figure out if `@Id` is not pointing at the `$id` field as Symfony router is expecting `{id}` in the path, or it can't figure out composite primary key as in `BooksCategories`.

**Comment by teohhanhui** [comment]
I think it's the whitespace in your category name that's tripping things up.

**Comment by yellowmamba** [comment]
I don't think so. Sorry, it was a lame copy and paste mockup code from me, the production code definitely has the right indentation.

**Comment by teohhanhui** [comment]
Yeah, I gave it some thought too, and that doesn't seem to be an issue.

Can you provide a stack trace?

**Comment by teohhanhui** [comment]
I think you're right, somewhere we must have hardcoded to use the "id" property, or not handling composite identifiers properly.

/cc @Simperfit

**Comment by Simperfit** [comment]
Coud you please do the following  @yellowmamba  if you still have the issue ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test that and confirm.

**Comment by yellowmamba** [comment]
Thanks but I will close this one now. It's either been worked around or fixed by us. We didn't touch the api platform core code.
